### ISSUE TITLE
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([nacos.hxsoft.com:8848]) tried

### ISSUE THREAD

**Issue by AaronChen2012** [alibaba/nacos#1000]
版本：NACOS1.0.0-RC3
在前端看到都是正常的，也不影响使用，就是一直提示错误
![image](https://user-images.githubusercontent.com/3069732/55473464-604c8000-5641-11e9-9480-60202eddcf24.png)
![image](https://user-images.githubusercontent.com/3069732/55473472-66daf780-5641-11e9-9ed6-b4d75246a1d2.png)
![image](https://user-images.githubusercontent.com/3069732/55473497-70fcf600-5641-11e9-83bf-4a0cc785d3f6.png)
![image](https://user-images.githubusercontent.com/3069732/55473541-8bcf6a80-5641-11e9-813b-15c484c10536.png)
![image](https://user-images.githubusercontent.com/3069732/55473607-ab669300-5641-11e9-811b-79b7a86a6e67.png)

**Comment by nkorange** [comment]
@AaronChen2012 Add the property ```spring.zipkin.discoveryClientEnabled=false```

**Comment by dislazy** [comment]
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([nacos.bosong.online]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:338)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:271)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:170)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:160)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:146)
	at com.alibaba.nacos.spring.factory.DelegatingNamingService.registerInstance(DelegatingNamingService.java:56)

**Comment by zouy1222** [comment]
@nkorange   Hello, if you have time, please help me with this question. Thank you.
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:304) [nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:327) [nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310) [nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257) [nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340) [nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429) [nacos-client-0.6.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_131]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_131]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_131]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_131]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]

2019-04-22 15:59:14.512 ERROR [ace-gateway,,,] 19712 --- [.naming.updater] com.alibaba.nacos.client.naming          : [] [] [NA] failed to update serviceName: localhost

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([127.0.0.1:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335) ~[nacos-client-0.6.2.jar:na]

**Comment by luohaoGit** [comment]
我也遇到了，看了几个相似问题都没解决，请问你解决了吗

**Comment by chuntaojun** [comment]
非nacos问题，已经在spring-cloud-seluth 解决了
