### ISSUE TITLE
The request was rejected because the URL was not normalized

### ISSUE THREAD

**Issue by guozongkang** [alibaba/nacos#10002]
2023-02-22 14:37:34.141  WARN [ TID: N/A ] 440965 --- [com.alibaba.nacos.client.naming.updater] c.a.n.c.naming                           : [NA] failed to update serviceName: DEFAULT_GROUP@@inner-private-pap StkH:d4b94114
com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance/list after all servers([https://online-nacos.aa.com/]) tried: ErrCode:500, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Feb 22 14:37:34 CST 2023</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>The request was rejected because the URL was not normalized.</div></body></html>
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:556) ~[nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) ~[nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) ~[nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407) ~[nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378) ~[nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460) ~[nacos-client-1.4.1.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[?:?]
        at java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[?:?]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]Hide

**Comment by YunWZ** [comment]
What's your server-address?

**Comment by YunWZ** [comment]
> What's your server-address?

I means how do you set this property in your client project.

**Comment by guozongkang** [comment]
Nacos-client:  1.4.1
Nacos server  2.0.2

**Comment by guozongkang** [comment]
这个域名已经接入了300多个服务，都没有出问题，只有这个服务报错
并且将域名改成IP，该问题就可以得到解决

**Comment by guozongkang** [comment]
> What's your server-address?

这个域名已经接入了300多个服务，都没有出问题，只有这个服务报错
并且将域名改成IP，该问题就可以得到解决。    但是这样导致我们域名无法推进，还是服务使用IP连接的Nacos集群，想问下怎么解决

**Comment by YunWZ** [comment]
> Nacos-client:  1.4.1
> 
> Nacos server  2.0.2
> 
> 项目中使用域名连接的Nacos集群
> 
> spring.cloud.nacos.discovery.server-addr = https://online-nacos.okg.com/

在域名后面加上端口8848。
BTW，你可以使用2.x的客户端。

**Comment by guozongkang** [comment]
> > Nacos-client:  1.4.1
> > Nacos server  2.0.2
> > 项目中使用域名连接的Nacos集群
> > spring.cloud.nacos.discovery.server-addr = https://online-nacos.okg.com/
> 
> 在域名后面加上端口8848。 BTW，你可以使用2.x的客户端。

必须开放8848端口么？
spring.cloud.nacos.discovery.server-addr = https://online-nacos.okg.com:8848
为什么会出现这样的情况。   使用http://online-nacos.okg.com::80或者https://online-nacos.okg.com:443不行么

**Comment by YunWZ** [comment]
> > > Nacos-client:  1.4.1
> 
> > > Nacos server  2.0.2
> 
> > > 项目中使用域名连接的Nacos集群
> 
> > > spring.cloud.nacos.discovery.server-addr = https://online-nacos.com/
> 
> > 
> 
> > 在域名后面加上端口8848。 BTW，你可以使用2.x的客户端。
> 
> 
> 
> 必须开放8848端口么？
> 
> spring.cloud.nacos.discovery.server-addr = https://online-nacos.com:8848
> 
> 为什么会出现这样的情况。   使用http://online-nacos.com:80或者https://online-nacos.com:443不行么

8848是nacos服务端的默认端口，如果你修改了这个端口或者使用了代理，则根据你的环境配置

**Comment by guozongkang** [comment]
> > > > Nacos-client:  1.4.1
> > 
> > 
> > > > Nacos server  2.0.2
> > 
> > 
> > > > 项目中使用域名连接的Nacos集群
> > 
> > 
> > > > spring.cloud.nacos.discovery.server-addr = https://online-nacos.com/
> > 
> > 
> > > 
> > 
> > 
> > > 在域名后面加上端口8848。 BTW，你可以使用2.x的客户端。
> > 
> > 
> > 必须开放8848端口么？
> > spring.cloud.nacos.discovery.server-addr = https://online-nacos.com:8848
> > 为什么会出现这样的情况。   使用[http://online-nacos.com:80或者https://online-nacos.com:443不行么](http://online-nacos.com:80%E6%88%96%E8%80%85https://online-nacos.com:443%E4%B8%8D%E8%A1%8C%E4%B9%88)
> 
> 8848是nacos服务端的默认端口，如果你修改了这个端口或者使用了代理，则根据你的环境配置

是的，我们修改了，都是使用80或者443注册的

**Comment by YunWZ** [comment]
那看看服务端日志吧

**Comment by guozongkang** [comment]
> 那看看服务端日志吧

有没有对应的日志文件名称 ？
我看了naming.log   nacos.log  naming-server.log  都没有查到报错信息

**Comment by KomachiSion** [comment]
用域名不行，但是ip可以，说明nacos没什么问题，单纯的是配置问题。

可能这个服务所在的DNS将域名解析到了其他ip上，然后对应ip也是个80端口的服务，但是没有nacos的URL

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
