### ISSUE TITLE
 开启权限后 只有nacos 账号可以注册服务

### ISSUE THREAD

**Issue by 564907422** [alibaba/nacos#10013]
nacos-client 2.1.0 版本
开启权限后 使用nacos账号可以注册服务 其他用户设置了读写权限后 报错 求指教
如下 register-rw用户拥有public 读写权限 注册就会报错 （nacos 正常）
另外 register-rw用户拥有namespaceId的读写权限 就可以再namespaceId中注册服务了。
使用curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080&username=register-rw&password=123456' 拥有public空间权限时又可以注册

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        register-enabled: true
        username: register-rw
        password: 123456
      #        namespace: c5714bfb-ea9a-44e1-bcec-feac8e4dc8a6
      #        username: nacos
      #        password: nacos

com.alibaba.nacos.api.exception.NacosException: authorization failed!
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:358)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:310)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:295)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:173)
	at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:414)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.start(NacosWatch.java:132)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295)
	at com.mgtv.media.vrssearch.VrsSearchApplication.main(VrsSearchApplication.java:25)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

**Comment by KomachiSion** [comment]
duplicate with https://github.com/alibaba/nacos/issues/3525 and refer to https://github.com/alibaba/nacos/issues/9846

**Comment by KomachiSion** [comment]
You can use other namespace to use first.

**Comment by 564907422** [comment]
![image](https://user-images.githubusercontent.com/4861650/222031874-769d1e4a-d602-429f-bb65-0f8927dd1e3f.png)
修改数据库，问题得到解决
