### ISSUE TITLE
nacos2.0.4集群 client同时存在2.1.0 和 1.2.1版本报错  

### ISSUE THREAD

**Issue by silent-night-no-trace** [alibaba/nacos#10031]
**Describe the bug**
server version is 2.0.4 
server nodes count  3  
client version is 2.1.0
client version is 1.2.1
use client version 2.1.0 application is gateway  application rate is 10% or less 
use client version 1.2.1 applications are user , order, customed, and so on   application rate is  90% or more 
 
**Expected behavior**
everything is well

**Actually behavior**
A clear and concise description of what you actually to happen.
-   user , order, customed applicaitons failed to register with the nacos cluster 
-  The number of healthy application nodes in the nacos cluster is 0
-  use high version nacos client application  (gateway) The gateway cannot obtain other applications

then restart nacos node
nacos.log  display 
request: /nacos/v1/ns/instance/beat failed, servers: [nacos2.xxxt:8848], code: 400, msg: <html><body>
ERROR CONSOLE /nacos/v1/ns/catalog/service

com.alibaba.nacos.api.exception.NacosException: service not found, namespace: 69689de8-c239-4a0c-af4c-df0954d6fe93, serviceName: user

lasty 

Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode

When will nacos automatically downgrade to 1.x mode 

But the nacos upgrade has been running steadily for a month and was released yesterday before this problem occurred

Is it related to the ratio of different versions of clients? If there are too many versions of clients, serve automatically switches to 1.x mode
 

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
The problem should not relate to client versions, the 1.x version client and 2.x version both can register and subscribe service from 2.x server.

I think there are some problem in your cluster deploy or problem between your app and nacos server.

you can check the logs in 1.x client version, whether some error in app logs or &{user.home}/logs/nacos/naming.log

**Comment by silent-night-no-trace** [comment]
Where can I see logs on nacos client
I saw some naming related logs on nacos server

There are some errors in naming-push.log
```java

2023-03-02 00:08:34,334 WARN ack takes too long from /172.21.49.242:47118 ack json: {"type": "push-ack", "lastRefTime":"6138936335410792", "data":""}

2023-03-02 00:08:34,335 ERROR [NACOS-PUSH] error while receiving ack data

java.lang.IllegalStateException: unable to find ackEntry for key: 172.21.49.242,47118,6138936335410792, ack json: {"type": "push-ack", "lastRefTime":"6138936335410792", "data":""}
        at com.alibaba.nacos.naming.push.UdpPushService$Receiver.run(UdpPushService.java:447)
        at java.lang.Thread.run(Thread.java:750)
2023-03-02 00:11:39,891 INFO DEFAULT_GROUP@@ssplottery-service is changed, add it to push queue.

2023-03-02 00:11:39,894 INFO serviceName: DEFAULT_GROUP@@user-service changed, schedule push for: 172.21.49.112:51927, agent: Nacos-Java-Client:v1.4.2, key: 172.21.49.112,51927,614570057550641

2023-03-02 00:11:39,894 INFO send udp packet: 172.21.49.112,51927,6145703057550641
```

There are some errors in naming-server.log

```java
2023-03-02 00:00:03,509 INFO upgrade check result false

2023-03-02 00:00:08,509 INFO upgrade check result false

2023-03-02 00:00:13,509 INFO upgrade check result false

2023-03-02 00:00:18,509 INFO upgrade check result false

2023-03-02 00:00:23,509 INFO upgrade check result false

2023-03-02 00:00:27,130 INFO Client connection 172.21.62.217:8540#true disconnect, remove instances and subscribers

2023-03-02 00:00:27,130 INFO Client connection 172.21.61.183:8540#true disconnect, remove instances and subscribers

2023-03-02 00:00:27,130 INFO Client connection 172.21.48.41:8540#true disconnect, remove instances and subscribers

2023-03-02 00:00:27,130 INFO Client connection 172.21.61.177:8540#true disconnect, remove instances and subscribers

2023-03-02 00:00:27,130 INFO Client connection 172.21.61.236:8540#true disconnect, remove instances and subscribers


2023-03-02 00:01:54,514 INFO double write for service DEFAULT_GROUP@@user-service, ephemeral: true, content INSTANCE

2023-03-02 00:01:54,514 INFO Client change for service Service{namespace='59b2cc24-861e-496e-9dad-f6183e1dff98', group='DEFAULT_GROUP', name='user-service', ephemeral=true, revision=0}, 12.21.60.253:8073#true

2023-03-02 00:01:54,514 INFO Client connection 172.21.61.134:8070#true connect
```

**Comment by silent-night-no-trace** [comment]
How does nacos recheck upgrades

**Comment by silent-night-no-trace** [comment]
Why is nacos checking for upgrades

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/v2/upgrading/2.0.0-upgrading.html

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
