### ISSUE TITLE
nacos2.1.0开启鉴权后，springcloud服务启动报错，请问一下，是怎么回事，该如何解决

### ISSUE THREAD

**Issue by zhaoxuguang** [alibaba/nacos#10070]
springcloudalibaba 版本2.2.1.RELEASE
nacos 版本  2.1.0
开启nacos配置文件中的 nacos.core.auth.enabled=true
之后，应用配置文件中配置如下：
spring.cloud.nacos.discovery.server-addr=localhost:8848
spring.cloud.nacos.discovery.namespace=993ebc2a-2f11-4d27-abbe-dd227c73071b
spring.cloud.nacos.config.server-addr=localhost:8848
spring.cloud.nacos.config.file-extension=properties
spring.cloud.nacos.config.namespace=993ebc2a-2f11-4d27-abbe-dd227c73071b
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos

启动就报错了：
`2023-03-10 10:41:14 [INFO] [org.springframework.boot.web.embedded.tomcat.TomcatWebServer:203] - Tomcat started on port(s): 27070 (http) with context path '' 
2023-03-10 10:41:14 [INFO] [com.alibaba.nacos.client.naming.beat.BeatReactor:66] - [BEAT] adding beat: {"cluster":"DEFAULT","ip":"192.168.184.1","metadata":{"preserved.register.source":"SPRING_CLOUD"},"period":5000,"port":27070,"scheduled":false,"serviceName":"DEFAULT_GROUP@@service-openapi","stopped":false,"weight":1.0} to beat map. 
2023-03-10 10:41:14 [INFO] [com.alibaba.nacos.client.naming.net.NamingProxy:196] - [REGISTER-SERVICE] 993ebc2a-2f11-4d27-abbe-dd227c73071b registering service DEFAULT_GROUP@@service-openapi with instance: {"clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ip":"192.168.184.1","ipDeleteTimeout":30000,"metadata":{"preserved.register.source":"SPRING_CLOUD"},"port":27070,"weight":1.0} 
2023-03-10 10:41:14 [ERROR] [com.alibaba.nacos.client.naming.net.NamingProxy:492] - request: /nacos/v1/ns/instance failed, servers: [localhost:8848], code: 403, msg: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Mar 10 10:41:14 CST 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html> 
2023-03-10 10:41:14 [ERROR] [com.alibaba.cloud.nacos.registry.NacosServiceRegistry:69] - nacos registry, service-openapi register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='localhost:8848', endpoint='', namespace='993ebc2a-2f11-4d27-abbe-dd227c73071b', watchDelay=30000, logName='', service='service-openapi', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.184.1', networkInterface='', port=27070, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null}}, 
com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([localhost:8848]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Mar 10 10:41:14 CST 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:496)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:401)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:397)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:212)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:207)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:64)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239)
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:76)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:165)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.richinfo.pushcenter.openapi.Application.main(Application.java:23)
2023-03-10 10:41:14 [INFO] [org.apache.juli.logging.DirectJDKLog:173] - Pausing ProtocolHandler ["http-nio-27070"] 
2023-03-10 10:41:16 [INFO] [org.apache.juli.logging.DirectJDKLog:173] - Stopping service [Tomcat] 
2023-03-10 10:41:16 [INFO] [org.apache.juli.logging.DirectJDKLog:173] - Stopping ProtocolHandler ["http-nio-27070"] 
2023-03-10 10:41:16 [INFO] [org.apache.juli.logging.DirectJDKLog:173] - Destroying ProtocolHandler ["http-nio-27070"] 
2023-03-10 10:41:16 [INFO] [org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener:136] - 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'taskScheduler' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'taskScheduler' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'tailExecutor' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'receiveExecutor' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'DealSmsUpside' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'pushMessageExecutor' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'taskPriorityCExecutor' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'taskPriorityBExecutor' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'taskPriorityAExecutor' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'taskPushExecutor' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'taskProgressExecutor' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'scheduledTaskTimePushExecutor' 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 'taskTest' 
2023-03-10 10:41:16 [INFO] [com.alibaba.druid.pool.DruidDataSource:1543] - {dataSource-1} closed 
2023-03-10 10:41:16 [INFO] [org.springframework.scheduling.concurrent.ExecutorConfigurationSupport:218] - Shutting down ExecutorService 
2023-03-10 10:41:16 [ERROR] [org.springframework.boot.SpringApplication:826] - Application run failed 
java.lang.reflect.UndeclaredThrowableException: null
	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:147)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:73)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239)
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:76)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:165)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:405)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.richinfo.pushcenter.openapi.Application.main(Application.java:23)
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([localhost:8848]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Mar 10 10:41:14 CST 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:496)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:401)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:397)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:212)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:207)
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:64)
	... 20 common frames omitted
2023-03-10 10:41:19 [ERROR] [com.alibaba.nacos.client.naming.net.NamingProxy:492] - request: /nacos/v1/ns/instance/beat failed, servers: [localhost:8848], code: 403, msg: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Mar 10 10:41:19 CST 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html> 
2023-03-10 10:41:19 [ERROR] [com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask:139] - [CLIENT-BEAT] failed to send beat: {"cluster":"DEFAULT","ip":"192.168.184.1","metadata":{"preserved.register.source":"SPRING_CLOUD"},"period":5000,"port":27070,"scheduled":false,"serviceName":"DEFAULT_GROUP@@service-openapi","stopped":false,"weight":1.0}, code: 403, msg: failed to req API:/api//nacos/v1/ns/instance/beat after all servers([localhost:8848]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Mar 10 10:41:19 CST 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html> 
2023-03-10 10:41:24 [ERROR] [com.al`

**Comment by YunWZ** [comment]
These properties is only enable in `config` module:
```properties
spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos
```
If you want to share user/passwd on `config` and `discovery`, maybe u should use:
```properties
spring.cloud.nacos.username=nacos
spring.cloud.nacos.password=nacos
```

**Comment by zhaoxuguang** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好我没有在线，无法亲自回复您的邮件。我将在上线后后，尽快给您回复。

**Comment by zhaoxuguang** [comment]
> These properties are only enable in `config` module:
> 
> ```ini
> spring.cloud.nacos.config.username=nacos
> spring.cloud.nacos.config.password=nacos
> ```
> 
> If you want to share user/passwd on `config` and `discovery`, maybe u should use:
> 
> ```ini
> spring.cloud.nacos.username=nacos
> spring.cloud.nacos.password=nacos
> ```

you  are  right.  jast now  i  found the  answer.and   now   is this:

spring.cloud.nacos.config.username=nacos
spring.cloud.nacos.config.password=nacos
spring.cloud.nacos.discovery.username=nacos
spring.cloud.nacos.discovery.password=nacos


thank you   very  much!

**Comment by zhaoxuguang** [comment]
问题已解决，还是说中文得劲。
