### ISSUE TITLE
2.0.4 readytoupgrade状态不一致，导致注册服务异常

### ISSUE THREAD

**Issue by zhangdejin-tom** [alibaba/nacos#10104]
Nacos版本：2.0.4
正常搭建的Nacos集群，客户端也是正常引用Nacos客户端API注册服务，无任何特殊操作，但控制台节点元数据的readytoupgrade状态不一致，有的为false，有的为true,导致集群有些服务无法注册到Nacos集群

**Describe the bug**
protocol-raft.log报错如下：

2023-03-15 15:48:10,029 ERROR Failed to join the cluster, retry...

java.lang.IllegalStateException: Fail to get leader of group naming_instance_metadata, Unknown leader, Unknown leader, Unknown leader
	at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:631)
	at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:524)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.registerSelfToCluster(JRaftServer.java:361)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.lambda$createMultiRaftGroup$0(JRaftServer.java:272)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2023-03-15 15:48:10,030 ERROR Fail to refresh leader for group : naming_service_metadata, status is : Status[UNKNOWN<-1>: Unknown leader, Unknown leader, Unknown leader]

2023-03-15 15:48:10,038 ERROR Fail to refresh route configuration for group : naming_service_metadata, status is : Status[UNKNOWN<-1>: Fail to get leader of group naming_service_metadata]

2023-03-15 15:48:10,077 ERROR Failed to join the cluster, retry...

java.lang.IllegalStateException: Fail to get leader of group naming_service_metadata, Unknown leader, Unknown leader, Unknown leader
	at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:631)
	at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:524)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.registerSelfToCluster(JRaftServer.java:361)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.lambda$createMultiRaftGroup$0(JRaftServer.java:272)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2023-03-15 15:48:10,653 INFO This Raft event changes : RaftEvent{groupId='naming_service_metadata', leader='nacos-cluster-0.nacos-headless.paas-middleware.svc.cluster.local:7848', term=1, raftClusterInfo=[nacos-cluster-0.nacos-headless.paas-middleware.svc.cluster.local:7848, nacos-cluster-1.nacos-headless.paas-middleware.svc.cluster.local:7848, nacos-cluster-2.nacos-headless.paas-middleware.svc.cluster.local:7848]}

2023-03-15 15:48:10,895 INFO This Raft event changes : RaftEvent{groupId='naming_instance_metadata', leader='nacos-cluster-0.nacos-headless.paas-middleware.svc.cluster.local:7848', term=1, raftClusterInfo=[nacos-cluster-0.nacos-headless.paas-middleware.svc.cluster.local:7848, nacos-cluster-1.nacos-headless.paas-middleware.svc.cluster.local:7848, nacos-cluster-2.nacos-headless.paas-middleware.svc.cluster.local:7848]}

**Comment by KomachiSion** [comment]
下面不是选举出leader了吗？

https://nacos.io/zh-cn/docs/v2/upgrading/2.0.0-upgrading.html

文档下面又一些API， 可以查看下升级状态。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
