### ISSUE TITLE
IDEA 2022 设置NacosCheckStyle报错

### ISSUE THREAD

**Issue by zonghay** [alibaba/nacos#10144]
**Describe the bug**
com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module TreeWalker - cannot initialize module JavadocMethod - Property 'scope' does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:481)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:61)
	at org.infernus.idea.checkstyle.service.cmd.OpCreateChecker.execute(OpCreateChecker.java:26)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.executeCommand(CheckstyleActionsImpl.java:130)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:60)
	at org.infernus.idea.checkstyle.service.CheckstyleActionsImpl.createChecker(CheckstyleActionsImpl.java:51)
	at org.infernus.idea.checkstyle.checker.CheckerFactoryWorker.run(CheckerFactoryWorker.java:46)
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: cannot initialize module JavadocMethod - Property 'scope' does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:129)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:201)
	at com.puppycrawl.tools.checkstyle.Checker.setupChild(Checker.java:476)
	... 7 more
Caused by: com.puppycrawl.tools.checkstyle.api.CheckstyleException: Property 'scope' does not exist, please check the documentation
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.tryCopyProperty(AutomaticBean.java:227)
	at com.puppycrawl.tools.checkstyle.api.AutomaticBean.configure(AutomaticBean.java:194)
	at com.puppycrawl.tools.checkstyle.TreeWalker.setupChild(TreeWalker.java:124)
	... 9 more
**Desktop (please complete the following information):**
 - OS: macOS
 - Version Nacos2.2.0

**Comment by KomachiSion** [comment]
这不是应该提交到checkstyle社区吗？

checkstyle的idea插件需要设置checkstyle的版本，扫描范围（scope）和checkstyle文件路径。

报错提示是scope配置不存在， 那说明这个版本插件有问题，应该不是nacos的问题吧。

![image](https://user-images.githubusercontent.com/37170243/226532649-e1f8ea4e-95ec-48e9-8ef4-7354e476c748.png)

**Comment by KomachiSion** [comment]
这不是应该提交到checkstyle社区吗？

checkstyle的idea插件需要设置checkstyle的版本，扫描范围（scope）和checkstyle文件路径。

报错提示是scope配置不存在， 那说明这个版本插件有问题，应该不是nacos的问题吧。

![image](https://user-images.githubusercontent.com/37170243/226532649-e1f8ea4e-95ec-48e9-8ef4-7354e476c748.png)
