### ISSUE TITLE
SpringCloud整合nacos启动异常: Connection is unregistered

### ISSUE THREAD

**Issue by InsaneLighter** [alibaba/nacos#10154]
1. 问题说明

   下述整合nacos client版本分别为1.4.2、2.0.4、2.1.0，nacos服务端为2.1.1版本，本地项目只有在客户端为1.4.2版本时能够正常启动，其他两个版本启动均会抛出异常。

2. pom.xml内容

   ```xml
   <properties>
       <maven.compiler.source>8</maven.compiler.source>
       <maven.compiler.target>8</maven.compiler.target>
   
       <!--nacos client 2.1.0-->
       <!--<spring.boot.version>2.3.12.RELEASE</spring.boot.version>
       <spring.cloud.alibaba.version>2.2.9.RELEASE</spring.cloud.alibaba.version>
       <spring.cloud.version>2020.0.1</spring.cloud.version>-->
   
       <!--nacos client 2.0.4-->
       <!--<spring.boot.version>2.6.11</spring.boot.version>
       <spring.cloud.alibaba.version>2021.0.4.0</spring.cloud.alibaba.version>
       <spring.cloud.version>2021.0.4</spring.cloud.version>-->
   
       <!--nacos client 1.4.2-->
       <spring.boot.version>2.6.3</spring.boot.version>
       <spring.cloud.alibaba.version>2021.0.1.0</spring.cloud.alibaba.version>
       <spring.cloud.version>2021.0.1</spring.cloud.version>
   </properties>
   
   <dependencyManagement>
       <dependencies>
           <dependency>
               <groupId>org.springframework.boot</groupId>
               <artifactId>spring-boot-dependencies</artifactId>
               <version>${spring.boot.version}</version>
               <type>pom</type>
               <scope>import</scope>
           </dependency>
           <dependency>
               <groupId>org.springframework.cloud</groupId>
               <artifactId>spring-cloud-dependencies</artifactId>
               <version>${spring.cloud.version}</version>
               <type>pom</type>
               <scope>import</scope>
           </dependency>
   
           <dependency>
               <groupId>com.alibaba.cloud</groupId>
               <artifactId>spring-cloud-alibaba-dependencies</artifactId>
               <version>${spring.cloud.alibaba.version}</version>
               <type>pom</type>
               <scope>import</scope>
           </dependency>
       </dependencies>
   </dependencyManagement>
   
   <dependencies>
       <dependency>
           <groupId>org.springframework.boot</groupId>
           <artifactId>spring-boot-starter-web</artifactId>
       </dependency>
   
       <dependency>
           <groupId>org.springframework.boot</groupId>
           <artifactId>spring-boot-starter-actuator</artifactId>
       </dependency>
       <!--nacos discovery-->
       <dependency>
           <groupId>com.alibaba.cloud</groupId>
           <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
       </dependency>
       <!--nacos config-->
       <dependency>
           <groupId>com.alibaba.cloud</groupId>
           <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
       </dependency>
       <!--spring cloud bootstrap-->
       <dependency>
           <groupId>org.springframework.cloud</groupId>
           <artifactId>spring-cloud-starter-bootstrap</artifactId>
       </dependency>
       <!--Feign-->
       <dependency>
           <groupId>org.springframework.cloud</groupId>
           <artifactId>spring-cloud-starter-openfeign</artifactId>
       </dependency>
       <!--feign http 连接池-->
       <!--<dependency>
           <groupId>io.github.openfeign</groupId>
           <artifactId>feign-okhttp</artifactId>
       </dependency>-->
       <dependency>
           <groupId>io.github.openfeign</groupId>
           <artifactId>feign-httpclient</artifactId>
       </dependency>
       <!--loadbalancer-->
       <dependency>
           <groupId>org.springframework.cloud</groupId>
           <artifactId>spring-cloud-loadbalancer</artifactId>
       </dependency>
   </dependencies>
   ```

3. 异常内容说明

   ```
   org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is java.lang.reflect.UndeclaredThrowableException
   	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.22.jar:5.3.22]
   	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.22.jar:5.3.22]
   	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.22.jar:5.3.22]
   	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_181]
   	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.22.jar:5.3.22]
   	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.22.jar:5.3.22]
   	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.22.jar:5.3.22]
   	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.22.jar:5.3.22]
   	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.11.jar:2.6.11]
   	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745) [spring-boot-2.6.11.jar:2.6.11]
   	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420) [spring-boot-2.6.11.jar:2.6.11]
   	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.6.11.jar:2.6.11]
   	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) [spring-boot-2.6.11.jar:2.6.11]
   	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) [spring-boot-2.6.11.jar:2.6.11]
   	at com.huang.Main.main(Main.java:17) [classes/:na]
   Caused by: java.lang.reflect.UndeclaredThrowableException: null
   	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:147) ~[spring-core-5.3.22.jar:5.3.22]
   	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:82) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.0.4.0.jar:2021.0.4.0]
   	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:232) ~[spring-cloud-commons-3.1.4.jar:3.1.4]
   	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.0.4.0.jar:2021.0.4.0]
   	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:133) ~[spring-cloud-commons-3.1.4.jar:3.1.4]
   	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:98) ~[spring-cloud-commons-3.1.4.jar:3.1.4]
   	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:86) ~[spring-cloud-commons-3.1.4.jar:3.1.4]
   	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) ~[spring-cloud-commons-3.1.4.jar:3.1.4]
   	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.22.jar:5.3.22]
   	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.22.jar:5.3.22]
   	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.22.jar:5.3.22]
   	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.22.jar:5.3.22]
   	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.22.jar:5.3.22]
   	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:46) ~[spring-boot-2.6.11.jar:2.6.11]
   	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.22.jar:5.3.22]
   	... 14 common frames omitted
   Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
   	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:290) ~[nacos-client-2.0.4.jar:na]
   	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129) ~[nacos-client-2.0.4.jar:na]
   	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115) ~[nacos-client-2.0.4.jar:na]
   	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:94) ~[nacos-client-2.0.4.jar:na]
   	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.0.4.jar:na]
   	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.0.4.0.jar:2021.0.4.0]
   	... 27 common frames omitted
   Caused by: com.alibaba.nacos.api.exception.NacosException: Connection is unregistered.
   	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:669) ~[nacos-client-2.0.4.jar:na]
   	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:630) ~[nacos-client-2.0.4.jar:na]
   	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:280) ~[nacos-client-2.0.4.jar:na]
   	... 32 common frames omitted
   ```

**Comment by KomachiSion** [comment]
`Caused by: com.alibaba.nacos.api.exception.NacosException: Connection is unregistered.` 

连接还没连上

**Comment by KomachiSion** [comment]
服务端看下remote-xxx.log

客户端看下${user.home}/logs/nacos/remote.log

**Comment by InsaneLighter** [comment]
> 服务端看下remote-xxx.log
> 
> 客户端看下${user.home}/logs/nacos/remote.log

客户端启动后remote-digest.log中的日志会增加
```
2023-03-22 13:04:41,702 INFO new connection registered successfully, connectionId = 1679461481575_127.0.0.1_1390,connection=Connection{traced=false, abilities=com.alibaba.nacos.api.ability.ClientAbilities@1f5950b9, metaInfo=ConnectionMeta{connectType='GRPC', clientIp='10.66.66.41', remoteIp='127.0.0.1', remotePort=1390, localPort=9848, version='Nacos-Java-Client:v2.1.0', connectionId='1679461481575_127.0.0.1_1390', createTime=Wed Mar 22 13:04:41 CST 2023, lastActiveTime=1679461481693, appName='unknown', tenant='', labels={source=sdk, taskId=0, module=config, AppName=unknown}}} 

2023-03-22 13:04:44,474 INFO Connection check task start

2023-03-22 13:04:44,474 INFO Total count =1, sdkCount=1,clusterCount=0, currentLimit=1, toExpelCount=0

2023-03-22 13:04:44,474 INFO Check over limit for ip limit rule, over limit ip count=0

2023-03-22 13:04:44,474 INFO Out dated connection ,size=0

2023-03-22 13:04:44,474 INFO Connection check task end

2023-03-22 13:04:46,216 INFO Connection transportReady,connectionId = 1679461486216_127.0.0.1_1396 

2023-03-22 13:04:46,222 WARN [1679461486216_127.0.0.1_1396]Connection register fail,reason: server is over limited.

2023-03-22 13:04:46,339 WARN [grpc] Invalid connection Id ,connection [1679461486216_127.0.0.1_1396] is un registered ,

2023-03-22 13:04:46,347 INFO Connection transportReady,connectionId = 1679461486347_127.0.0.1_1398 

2023-03-22 13:04:46,354 WARN [1679461486347_127.0.0.1_1398]Connection register fail,reason: server is over limited.

2023-03-22 13:04:46,469 INFO Connection transportTerminated,connectionId = 1679461486216_127.0.0.1_1396 

2023-03-22 13:04:46,558 WARN [grpc] Invalid connection Id ,connection [1679461486347_127.0.0.1_1398] is un registered ,

2023-03-22 13:04:46,564 INFO Connection transportReady,connectionId = 1679461486564_127.0.0.1_1399 

2023-03-22 13:04:46,570 WARN [1679461486564_127.0.0.1_1399]Connection register fail,reason: server is over limited.

2023-03-22 13:04:46,685 INFO Connection transportTerminated,connectionId = 1679461486347_127.0.0.1_1398 

2023-03-22 13:04:46,701 WARN [grpc] Invalid connection Id ,connection [1679461486564_127.0.0.1_1399] is un registered ,

2023-03-22 13:04:46,707 INFO Connection transportReady,connectionId = 1679461486707_127.0.0.1_1404 

2023-03-22 13:04:46,713 WARN [1679461486707_127.0.0.1_1404]Connection register fail,reason: server is over limited.

2023-03-22 13:04:46,813 INFO Connection transportTerminated,connectionId = 1679461486564_127.0.0.1_1399 

2023-03-22 13:04:46,924 WARN [grpc] Invalid connection Id ,connection [1679461486707_127.0.0.1_1404] is un registered ,

2023-03-22 13:04:46,931 INFO Connection transportReady,connectionId = 1679461486931_127.0.0.1_1405 

2023-03-22 13:04:46,939 WARN [1679461486931_127.0.0.1_1405]Connection register fail,reason: server is over limited.

2023-03-22 13:04:47,050 INFO Connection transportTerminated,connectionId = 1679461486707_127.0.0.1_1404 

2023-03-22 13:04:47,342 WARN [grpc] Invalid connection Id ,connection [1679461486931_127.0.0.1_1405] is un registered ,

2023-03-22 13:04:47,350 INFO Connection transportReady,connectionId = 1679461487350_127.0.0.1_1408 

2023-03-22 13:04:47,358 WARN [1679461487350_127.0.0.1_1408]Connection register fail,reason: server is over limited.

2023-03-22 13:04:47,467 INFO Connection transportTerminated,connectionId = 1679461486931_127.0.0.1_1405 

2023-03-22 13:04:47,481 INFO Connection check task start

2023-03-22 13:04:47,481 INFO Total count =1, sdkCount=1,clusterCount=0, currentLimit=1, toExpelCount=0

2023-03-22 13:04:47,481 INFO Check over limit for ip limit rule, over limit ip count=0

2023-03-22 13:04:47,481 INFO Out dated connection ,size=0

2023-03-22 13:04:47,481 INFO Connection check task end

2023-03-22 13:04:47,562 WARN [grpc] Invalid connection Id ,connection [1679461487350_127.0.0.1_1408] is un registered ,

2023-03-22 13:04:47,570 INFO Connection transportReady,connectionId = 1679461487570_127.0.0.1_1410 

2023-03-22 13:04:47,578 WARN [1679461487570_127.0.0.1_1410]Connection register fail,reason: server is over limited.

2023-03-22 13:04:47,683 INFO Connection transportReady,connectionId = 1679461487683_127.0.0.1_1411 

2023-03-22 13:04:47,692 WARN [1679461487683_127.0.0.1_1411]Connection register fail,reason: server is over limited.

2023-03-22 13:04:47,800 WARN [grpc] Invalid connection Id ,connection [1679461487683_127.0.0.1_1411] is un registered ,

2023-03-22 13:04:47,807 INFO Connection transportReady,connectionId = 1679461487807_127.0.0.1_1412 

2023-03-22 13:04:47,814 WARN [1679461487807_127.0.0.1_1412]Connection register fail,reason: server is over limited.

2023-03-22 13:04:47,927 INFO Connection transportTerminated,connectionId = 1679461487683_127.0.0.1_1411 

2023-03-22 13:04:48,022 WARN [grpc] Invalid connection Id ,connection [1679461487807_127.0.0.1_1412] is un registered ,

2023-03-22 13:04:48,029 INFO Connection transportReady,connectionId = 1679461488029_127.0.0.1_1413 

```

**Comment by InsaneLighter** [comment]
麻烦问下上述日志说明的问题是什么呢
