### ISSUE TITLE
k8s中 集群模式下的2.0.4和2.1.2版本的nacos无法启动

### ISSUE THREAD

**Issue by Accelerator96** [alibaba/nacos#10164]
使用的是dockerhub上的镜像版本，3节点内置数据库
### nacos.log

2023-03-22 15:24:16,341 INFO The server IP list of Nacos is [nacos-cluster-0.nacos-cluster-headless.skoala-demo.svc.cluster.local:8848, nacos-cluster-1.nacos-cluster-headless.skoala-demo.svc.cluster.local:8848, nacos-cluster-2.nacos-cluster-headless.skoala-demo.svc.cluster.local:8848]

2023-03-22 15:24:16,407 INFO Starting Nacos v2.1.2 using Java 1.8.0_352 on nacos-cluster-0 with PID 1 (/home/nacos/target/nacos-server.jar started by root in /home/nacos)

2023-03-22 15:24:16,408 INFO No active profile set, falling back to 1 default profile: "default"

2023-03-22 15:24:17,343 INFO Nacos is starting...

2023-03-22 15:24:18,347 INFO Nacos is starting...

2023-03-22 15:24:19,349 INFO Nacos is starting...

2023-03-22 15:24:20,401 INFO Nacos is starting...

2023-03-22 15:24:21,402 INFO Nacos is starting...

2023-03-22 15:24:22,403 INFO Nacos is starting...

2023-03-22 15:24:23,405 INFO Nacos is starting...

2023-03-22 15:24:24,406 INFO Nacos is starting...

2023-03-22 15:24:25,406 INFO Nacos is starting...

2023-03-22 15:24:26,407 INFO Nacos is starting...

2023-03-22 15:24:27,408 INFO Nacos is starting...

2023-03-22 15:24:28,408 INFO Nacos is starting...

2023-03-22 15:24:28,944 INFO Tomcat initialized with port(s): 8848 (http)

2023-03-22 15:24:29,015 INFO Initializing ProtocolHandler ["http-nio-8848"]

2023-03-22 15:24:29,016 INFO Starting service [Tomcat]

2023-03-22 15:24:29,016 INFO Starting Servlet engine: [Apache Tomcat/9.0.63]

2023-03-22 15:24:29,306 INFO Initializing Spring embedded WebApplicationContext

2023-03-22 15:24:29,306 INFO Root WebApplicationContext: initialization completed in 12663 ms

2023-03-22 15:24:29,409 INFO Nacos is starting...

2023-03-22 15:24:30,410 INFO Nacos is starting...

2023-03-22 15:24:30,412 INFO Nacos-related cluster resource initialization

2023-03-22 15:24:30,429 INFO Load com.alibaba.nacos.core.ability.RemoteAbilityInitializer for ServerAbilityInitializer

2023-03-22 15:24:30,430 INFO Load com.alibaba.nacos.naming.ability.NamingAbilityInitializer for ServerAbilityInitializer

2023-03-22 15:24:30,510 INFO The cluster resource is initialized

2023-03-22 15:24:31,013 INFO Get Distro config from env, DistroConfig{syncDelayMillis=1000, syncTimeoutMillis=3000, syncRetryDelayMillis=3000, verifyIntervalMillis=5000, verifyTimeoutMillis=3000, loadDataRetryDelayMillis=30000}

2023-03-22 15:24:31,411 INFO Nacos is starting...

2023-03-22 15:24:32,412 INFO Nacos is starting...

2023-03-22 15:24:33,534 INFO Nacos is starting...

2023-03-22 15:24:34,536 INFO Nacos is starting...

2023-03-22 15:24:35,537 INFO Nacos is starting...

2023-03-22 15:24:36,538 INFO Nacos is starting...

2023-03-22 15:24:37,539 INFO Nacos is starting...

2023-03-22 15:24:38,650 INFO Nacos is starting...

2023-03-22 15:24:39,650 INFO Nacos is starting...

2023-03-22 15:24:40,006 INFO HikariPool-1 - Starting...

2023-03-22 15:24:40,012 WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.

2023-03-22 15:24:40,651 INFO Nacos is starting...

2023-03-22 15:24:41,652 INFO Nacos is starting...

2023-03-22 15:24:42,653 INFO Nacos is starting...

2023-03-22 15:24:43,654 INFO Nacos is starting...

2023-03-22 15:24:44,710 INFO Nacos is starting...

2023-03-22 15:24:45,321 INFO HikariPool-1 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)

2023-03-22 15:24:45,327 INFO HikariPool-1 - Start completed.

2023-03-22 15:24:45,713 INFO Nacos is starting...

2023-03-22 15:24:46,714 INFO Nacos is starting...

2023-03-22 15:24:47,715 INFO Nacos is starting...

2023-03-22 15:24:48,117 INFO HikariPool-2 - Starting...

2023-03-22 15:24:48,118 WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.

2023-03-22 15:24:48,716 INFO Nacos is starting...

2023-03-22 15:24:48,811 INFO HikariPool-2 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)

2023-03-22 15:24:48,813 INFO HikariPool-2 - Start completed.

2023-03-22 15:24:49,717 INFO Nacos is starting...

2023-03-22 15:24:50,718 INFO Nacos is starting...

2023-03-22 15:24:51,718 INFO Nacos is starting...

**之后就一直是 Nacos is starting...**

### naming-server.log

2023-03-22 15:31:40,436 WARN Exception while request: http://nacos-cluster-1.nacos-cluster-headless.skoala-demo.svc.cluster.local:8848/nacos/v1/ns/operator/cluster/state, caused: {}

org.apache.http.conn.HttpHostConnectException: Connect to nacos-cluster-1.nacos-cluster-headless.skoala-demo.svc.cluster.local:8848 [nacos-cluster-1.nacos-cluster-headless.skoala-demo.svc.cluster.local/10.233.105.120] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.alibaba.nacos.common.http.client.request.DefaultHttpClientRequest.execute(DefaultHttpClientRequest.java:58)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchange(NacosRestTemplate.java:447)
	at com.alibaba.nacos.naming.misc.HttpClient.request(HttpClient.java:119)
	at com.alibaba.nacos.naming.misc.HttpClient.httpGet(HttpClient.java:82)
	at com.alibaba.nacos.naming.misc.NamingProxy.reqCommon(NamingProxy.java:308)
	at com.alibaba.nacos.naming.cluster.ServerListManager$ServerInfoUpdater.run(ServerListManager.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at org.apache.http.conn.socket.PlainConnectionSocketFactory.connectSocket(PlainConnectionSocketFactory.java:75)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
	... 23 common frames omitted
2023-03-22 15:31:40,436 WARN NamingProxy

java.io.IOException: failed to req API:http://nacos-cluster-1.nacos-cluster-headless.skoala-demo.svc.cluster.local:8848/nacos/v1/ns/operator/cluster/state. code:500 msg: org.apache.http.conn.HttpHostConnectException: Connect to nacos-cluster-1.nacos-cluster-headless.skoala-demo.svc.cluster.local:8848 [nacos-cluster-1.nacos-cluster-headless.skoala-demo.svc.cluster.local/10.233.105.120] failed: Connection refused (Connection refused)
	at com.alibaba.nacos.naming.misc.NamingProxy.reqCommon(NamingProxy.java:323)
	at com.alibaba.nacos.naming.cluster.ServerListManager$ServerInfoUpdater.run(ServerListManager.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
2023-03-22 15:31:41,289 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: nacos-cluster-2.nacos-cluster-headless.skoala-demo.svc.cluster.local:8848

java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:750)
2023-03-22 15:31:41,290 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: nacos-cluster-0.nacos-cluster-headless.skoala-demo.svc.cluster.local:8848

java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:750)
2023-03-22 15:31:41,290 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: nacos-cluster-1.nacos-cluster-headless.skoala-demo.svc.cluster.local:8848

java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:750)

**可是在容器中 nacos-cluster-1.nacos-cluster-headless.skoala-demo.svc.cluster.local 这些dns是能够ping通的 不知道为什么8848这个端口访问不了**

### protocol-raft.log

2023-03-22 15:33:48,400 ERROR Failed to join the cluster, retry...

java.lang.IllegalStateException: Fail to get leader of group naming_persistent_service, Fail to find node nacos-cluster-2.nacos-cluster-headless.skoala-demo.svc.cluster.local:7848 in group naming_persistent_service, Unknown leader, Fail to find node nacos-cluster-0.nacos-cluster-headless.skoala-demo.svc.cluster.local:7848 in group naming_persistent_service, Fail to find node nacos-cluster-1.nacos-cluster-headless.skoala-demo.svc.cluster.local:7848 in group naming_persistent_service
	at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:631)
	at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:524)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.registerSelfToCluster(JRaftServer.java:353)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.lambda$createMultiRaftGroup$0(JRaftServer.java:264)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**这个也一直在重复刷这条信息**

### cluster.conf文件

<img width="606" alt="image" src="https://user-images.githubusercontent.com/13599846/226832758-9802c554-39ca-4909-913b-55a43ce46992.png">

麻烦大佬帮忙看看问题

**Comment by KomachiSion** [comment]
看下alipay-jraft.log, 应该是raft选不出主，所以配置中心dump不到数据。

**Comment by Accelerator96** [comment]
解决了 在k8s中集群模式使用内置数据库的情况下 

PREFER_HOST_MODE这个环境变量需要是'hostname'
不然会导致诸如 nacos一直在starting.. 还有cluster.conf会自动加上本机ip的情况。
