### ISSUE TITLE
Invalid character ':' for HOST_IPV4 in "fd15:4ba5:5a2b:1008:c548:71c5:a076:b3fb"

### ISSUE THREAD

**Issue by podigua** [alibaba/nacos#10199]
有两个服务
1. spring cloud gateway  `public-gatway`
2.  业务服务 `monitor-operation-server`

以上两个服务 都注册到了`nacos`,`public-gatway`以IPV4的方式注册,`monitor-operation-server` 以IPV6的方式注册;
`public-gatway`
![image](https://user-images.githubusercontent.com/25717106/227840796-96ff7730-5f13-41a4-ad40-eb5eb4588826.png)
`monitor-operation-server` 
![image](https://user-images.githubusercontent.com/25717106/227840898-7496c256-57b6-4b19-8da2-b46b72d97813.png)

版本信息;
nacos:2.2.0
spring-cloud-alibaba.version: 2021.1
 

**Describe the bug**
通过 gateway 访问`/monitor-operation-server/operation-plan/page?pageSize=10&pageNum=1&executionPlanName=%E6%B5%8B%E8%AF%95&executionPlanTag=&categoryId=&vender=` 有以下异常
 
HierarchicalUriComponents 的方法判断IPV6 简单粗暴;而且是其他地方也是这么判断,所以怀疑是不是 nacos返回serviceInstance时,ipv4和ipv6 应该是不同的格式.
private Type getHostType() {
        return this.host != null && this.host.startsWith("[") ? HierarchicalUriComponents.Type.HOST_IPV6 : HierarchicalUriComponents.Type.HOST_IPV4;
    }

2023-03-27 09:40:08.240 [reactor-http-epoll-8] [ERROR] org.springframework.boot.autoconfigure.web.reactive.error.AbstractErrorWebExceptionHandler [f5bb9513-1325]  500 Server Error for HTTP GET "/monitor-operation-server/operation-plan/page?pageSize=10&pageNum=1&executionPlanName=%E6%B5%8B%E8%AF%95&executionPlanTag=&categoryId=&vender="
java.lang.IllegalArgumentException: Invalid character ':' for HOST_IPV4 in "fd15:4ba5:5a2b:1008:c548:71c5:a076:b3fb"
        at org.springframework.web.util.HierarchicalUriComponents.verifyUriComponent(HierarchicalUriComponents.java:416)
        Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
        *__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
        *__checkpoint ⇢ HTTP GET "/monitor-operation-server/operation-plan/page?pageSize=10&pageNum=1&executionPlanName=%E6%B5%8B%E8%AF%95&executionPlanTag=&categoryId=&vender=" [ExceptionHandlingWebHandler]
Original Stack Trace:
                at org.springframework.web.util.HierarchicalUriComponents.verifyUriComponent(HierarchicalUriComponents.java:416)
                at org.springframework.web.util.HierarchicalUriComponents.verify(HierarchicalUriComponents.java:379)
                at org.springframework.web.util.HierarchicalUriComponents.<init>(HierarchicalUriComponents.java:145)
                at org.springframework.web.util.UriComponentsBuilder.buildInternal(UriComponentsBuilder.java:483)
                at org.springframework.web.util.UriComponentsBuilder.build(UriComponentsBuilder.java:472)
                at org.springframework.cloud.client.loadbalancer.LoadBalancerUriTools.doReconstructURI(LoadBalancerUriTools.java:107)
                at org.springframework.cloud.client.loadbalancer.LoadBalancerUriTools.reconstructURI(LoadBalancerUriTools.java:92)
                at org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter.reconstructURI(ReactiveLoadBalancerClientFilter.java:161)
                at org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter.lambda$filter$2(ReactiveLoadBalancerClientFilter.java:140)
                at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185)
                at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
                at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
                at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:98)
                at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:44)
                at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:421)
                at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:686)
                at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:250)
                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
                at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
                at reactor.core.publisher.DrainUtils.postCompleteDrain(DrainUtils.java:132)
                at reactor.core.publisher.DrainUtils.postComplete(DrainUtils.java:187)
                at reactor.core.publisher.FluxMaterialize$MaterializeSubscriber.onComplete(FluxMaterialize.java:141)
                at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2400)
                at reactor.core.publisher.FluxMaterialize$MaterializeSubscriber.request(FluxMaterialize.java:148)
                at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onSubscribe(MonoCollectList.java:79)
                at reactor.core.publisher.FluxMaterialize$MaterializeSubscriber.onSubscribe(FluxMaterialize.java:103)
                at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68)
                at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
                at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
                at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:282)
                at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863)
                at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
                at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
                at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:151)
                at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:120)
                at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:82)
                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:282)
                at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:863)
                at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
                at reactor.core.publisher.MonoPeekTerminal$MonoTerminalPeekSubscriber.onNext(MonoPeekTerminal.java:180)
                at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
                at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.onNext(MonoFilterWhen.java:149)
                at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2398)
                at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.onSubscribe(MonoFilterWhen.java:112)
                at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:55)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:451)
                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:251)
                at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:98)
                at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:44)
                at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:272)
                at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:230)
                at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.request(FluxDematerialize.java:127)
                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:236)
                at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onSubscribe(FluxDematerialize.java:77)
                at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
                at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
                at reactor.core.publisher.InternalFluxOperator.subscribe(InternalFluxOperator.java:62)
                at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:54)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:451)
                at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:219)
                at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
                at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
                at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
                at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
                at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:255)
                at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
                at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64)
                at reactor.netty.http.server.HttpServer$HttpServerHandle.onStateChange(HttpServer.java:962)
                at reactor.netty.ReactorNetty$CompositeConnectionObserver.onStateChange(ReactorNetty.java:671)
                at reactor.netty.transport.ServerTransport$ChildObserver.onStateChange(ServerTransport.java:478)
                at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:560)
                at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:93)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:220)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436)
                at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:327)
                at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:299)
                at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
                at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
                at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
                at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
                at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795)
                at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480)
                at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378)
                at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
                at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
                at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
                at java.lang.Thread.run(Thread.java:748)

**Comment by podigua** [comment]
跟 url 编码有关, 经过编码的会报错, 我get请求里有汉字,会编码, 如果没有汉字的话是正常的.

**Comment by KomachiSion** [comment]
nacos注册的实例的ip是自定义的，字符串应该都可以， 域名，v4，v6都可以，没有做很特殊的校验。

获取的时候也不会做处理，属于你注册的时候是什么样，获取的时候就什么样。

**Comment by podigua** [comment]
跟 url 编码有关, 经过编码的会报错, 我get请求里有汉字,会编码, 如果没有汉字的话是正常的.

**Comment by KomachiSion** [comment]
这个报错不是nacos报的， 是你的应用调用下游应用的时候报的错， 需要您自己排查下。

**Comment by KomachiSion** [comment]
not nacos' problem,

**Comment by zky959** [comment]
可以尝试增加配置spring.cloud.nacos.discovery.ip。且需要以[]括住
