### ISSUE TITLE
java.net.ConnectException: Connection refused: connect

### ISSUE THREAD

**Issue by Python-IBM** [alibaba/nacos#1022]
01 2019-04-08 16:02:14.182 INFO [main :c.a.n.c.naming] [BEAT] [] [] adding beat: {"cluster":"default","ip":"192.168.10.4","metadata":{},"port":8091,"scheduled":false,"serviceName":"serverAddr","weight":1.0} to beat map.
01 2019-04-08 16:02:14.306 INFO [main :c.a.n.c.naming] [REGISTER-SERVICE] [] [] public registering service serverAddr with instance: {"clusterName":"default","enabled":true,"ip":"192.168.10.4","metadata":{},"port":8091,"valid":true,"weight":1.0}
01 2019-04-08 16:02:15.385 WARN [main :c.a.n.c.naming] [] [] [] failed to request http://localhost:8848/nacos/v1/ns/instance?metadata=%7B%7D&namespaceId=public&port=8091&enable=true&healthy=true&ip=192.168.10.4&clusterName=default&weight=1.0&serviceName=serverAddr&encoding=UTF-8& from 127.0.0.1
01 2019-04-08 16:02:15.403 ERROR [main :c.a.n.c.naming] [] [] [NA] failed to request 
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1169)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1105)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:999)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:933)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:72)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:315)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:358)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:175)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:178)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:161)
	at com.alibaba.fescar.discovery.registry.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:78)
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:153)
	at com.alibaba.fescar.core.rpc.netty.RpcServer.init(RpcServer.java:130)
	at com.alibaba.fescar.server.Server.main(Server.java:88)
01 2019-04-08 16:02:15.420 ERROR [main :c.a.n.c.naming] [] [] [CALL-SERVER] failed to req API:http://localhost:8848/nacos/v1/ns/instance. code:500 msg: java.net.ConnectException: Connection refused: connect
01 2019-04-08 16:02:15.421 ERROR [main :c.a.n.c.naming] [] [] [NA] req api:/nacos/v1/ns/instance failed, server(localhost
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:333)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:358)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:175)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:178)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:161)
	at com.alibaba.fescar.discovery.registry.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:78)
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:153)
	at com.alibaba.fescar.core.rpc.netty.RpcServer.init(RpcServer.java:130)
	at com.alibaba.fescar.server.Server.main(Server.java:88)

**Comment by nkorange** [comment]
@Python-IBM Confirm that your nacos server is UP.
