### ISSUE TITLE
nacos-client:v2.1.0 ClassNotFoundException SecretPerfMarkImpl

### ISSUE THREAD

**Issue by SonicBrother** [alibaba/nacos#10239]
## Issue Description

Type: *bug report* or *feature request*
bug report
### Describe what happened (or what feature you want)
when i set logging.level.root=debug, i found the error as below, but it works normal.
```
2023-03-31 13:27:31.622 DEBUG 12404 --- [           main] c.a.nacos.shaded.io.perfmark.PerfMark    : Error during PerfMark.<clinit>

java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.perfmark.impl.SecretPerfMarkImpl$PerfMarkImpl
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387) ~[na:1.8.0_361]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418) ~[na:1.8.0_361]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355) ~[na:1.8.0_361]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351) ~[na:1.8.0_361]
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_361]
	at java.lang.Class.forName(Class.java:264) ~[na:1.8.0_361]
	at com.alibaba.nacos.shaded.io.perfmark.PerfMark.<clinit>(PerfMark.java:37) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.<init>(ClientCallImpl.java:100) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ManagedChannelImpl$RealChannel.newCall(ManagedChannelImpl.java:861) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ServiceConfigInterceptor.interceptCall(ServiceConfigInterceptor.java:153) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.CensusTracingModule$TracingClientInterceptor.interceptCall(CensusTracingModule.java:388) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.CensusStatsModule$StatsClientInterceptor.interceptCall(CensusStatsModule.java:691) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ClientInterceptors$InterceptorChannel.newCall(ClientInterceptors.java:156) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ManagedChannelImpl.newCall(ManagedChannelImpl.java:826) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ForwardingManagedChannel.newCall(ForwardingManagedChannel.java:63) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestFutureStub.request(RequestGrpc.java:213) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:147) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:264) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:390) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.start(NamingGrpcClientProxy.java:96) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.<init>(NamingGrpcClientProxy.java:89) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:76) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:95) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:81) [nacos-client-2.0.4.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_361]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_361]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_361]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_361]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77) [nacos-client-2.0.4.jar:na]
	at com.alibaba.cloud.nacos.NacosServiceManager.createNewNamingService(NacosServiceManager.java:99) [spring-cloud-starter-alibaba-nacos-discovery-2021.0.4.0.jar:2021.0.4.0]
	at com.alibaba.cloud.nacos.NacosServiceManager.buildNamingService(NacosServiceManager.java:90) [spring-cloud-starter-alibaba-nacos-discovery-2021.0.4.0.jar:2021.0.4.0]
	at com.alibaba.cloud.nacos.NacosServiceManager.getNamingService(NacosServiceManager.java:46) [spring-cloud-starter-alibaba-nacos-discovery-2021.0.4.0.jar:2021.0.4.0]
	at com.alibaba.cloud.nacos.discovery.NacosWatch.start(NacosWatch.java:130) [spring-cloud-starter-alibaba-nacos-discovery-2021.0.4.0.jar:2021.0.4.0]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) [spring-context-5.3.20.jar:5.3.20]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_361]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) [spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.20.jar:5.3.20]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.0.jar:2.7.0]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.0.jar:2.7.0]
	at com.example.demo.Demo1Application.main(Demo1Application.java:10) ~[classes/:na]
```
and, when I debug, i don't understand why nacos-client  call a non-existent class firstly, then provide a default instance;
 
![9b438c60c966c5a3d2ae4bfc6761e39](https://user-images.githubusercontent.com/74613038/229035111-32bb6a32-a26c-48bd-aae1-cb32e7fbda4b.png)
![40cde62563fb530d99d13e631cf2888](https://user-images.githubusercontent.com/74613038/229035145-c002bf17-c96c-47d1-bcfa-3c4d4c967bf9.png)

### How to reproduce it (as minimally and precisely as possible)
1. use spring-cloud-starter-alibaba-nacos-discovery,nacos-client:2.1.0

### Tell us your environment
cloudAlibaba:2021.0.5.0
nacos-client:2.1.0
springcloud:2021.0.5
boot:2.6.13
os:window10

### Anything else we need to know?
none

**Comment by KomachiSion** [comment]
nacos-client shard the grpc into nacos-client to reduce conflict problem.

So your print logic is not nacos' codes but other dependency' codes. 

For your exception, I think it's more problem reason is you import some conflict dependency version.

You can search your project whether import nacos-common or nacos-api by yourself or other third dependency.

**Comment by KomachiSion** [comment]
Also you can create a new project only depend nacos-client to test.

**Comment by SonicBrother** [comment]
I create a demo , here is my pom.xml.
and I drop the instance.log here
~~~xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.7.0</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.example</groupId>
    <artifactId>demo1</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo1</name>
    <description>demo1</description>
    <properties>
        <java.version>1.8</java.version>
    </properties>
    <dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework.boot</groupId>
                    <artifactId>spring-boot-starter-tomcat</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-undertow</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2021.0.4.0</version>
        </dependency>

        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
            </plugin>
        </plugins>
    </build>

</project>

~~~
![image](https://user-images.githubusercontent.com/74613038/229049145-242d1ec0-de99-4f56-9321-700f564b3abd.png)
![image](https://user-images.githubusercontent.com/74613038/229049236-81a8a04e-c964-4491-b1af-16f4fdbe412f.png)
![image](https://user-images.githubusercontent.com/74613038/229049345-f577580b-a268-4fd1-a98a-98bb570b61e7.png)

[instance.log](https://github.com/alibaba/nacos/files/11119192/instance.log)

**Comment by SonicBrother** [comment]
[demo1.zip](https://github.com/alibaba/nacos/files/11133761/demo1.zip)
this is the demo project, and i found that nacos-client:v2.0.4,v2.1.0,v2.1.1 all generated this error 
![image](https://user-images.githubusercontent.com/74613038/229389016-74daf4b7-b5a4-468f-847c-e238ffdaed1a.png)

**Comment by KomachiSion** [comment]
I see, the log is debug log from perfmark. Not any effect for your app.

Please set log level as INFO, or ignore the no effect debug log.

**Comment by SonicBrother** [comment]
and can i ignore those exception  too ?
![image](https://user-images.githubusercontent.com/74613038/230521632-ba0f7c88-940b-46f8-a4a9-c4685076f45f.png)

**Comment by KomachiSion** [comment]
Yes, these expection all is DEBUG logs which dependency **try** to find classes.

**Comment by SonicBrother** [comment]
thx
