### ISSUE TITLE
2.2.1单例模式启动报错

### ISSUE THREAD

**Issue by colshep** [alibaba/nacos#10242]
**Describe the bug**
Error creating bean with name 'instanceMetadataProcessor' defined in URL [jar:file:/D:/core_tech/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.2.1.jar!/com/alibaba/nacos/naming/core/v2/metadata/InstanceMetadataProcessor.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.metadata.InstanceMetadataProcessor]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Fail to init node, please see the logs to find the reason.

**How to Reproduce**
1. 使用standalone模式
2. 使用mysql数据库
3. 本地测试环境正常，正式环境报错
4. See errors

**Desktop (please complete the following information):**
 - OS: Windows Server 2008 R2
 - Version nacos-server 2.2.1

**Additional context**
附上启动报错日志见附件
[logs.zip](https://github.com/alibaba/nacos/files/11119430/logs.zip)

**Comment by colshep** [comment]
> ```
> 2023-03-31 15:22:42,783 ERROR Fail to init RocksDBLogStorage, path=D:\core_tech\nacos\data\protocol\raft\naming_instance_metadata\log.
> 
> org.rocksdb.RocksDBException: Failed to open NewSequentialFileD:\core_tech\nacos\data\protocol\raft\naming_instance_metadata\log/MANIFEST-000036: ϵͳÕҲ»µ½ָ¶¨µ
> 	at org.rocksdb.RocksDB.open(Native Method)
> 	at org.rocksdb.RocksDB.open(RocksDB.java:307)
> 	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.openDB(RocksDBLogStorage.java:312)
> 	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.initAndLoad(RocksDBLogStorage.java:230)
> 	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.init(RocksDBLogStorage.java:209)
> 	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.init(RocksDBLogStorage.java:72)
> 	at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.init(LogManagerImpl.java:184)
> 	at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.init(LogManagerImpl.java:76)
> 	at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:591)
> 	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:1005)
> 	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:141)
> 	at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
> 	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
> 	at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGroup(JRaftServer.java:260)
> ```
> 
> 1. 确保-Dnacos.standalone=true
> 2. 从alipay-jraft.log看着有点怪，要是测试环境，你把这个data目录删了，再试一试

确实可以，启动成功了，谢谢你！
