### ISSUE TITLE
Redo subscriber operation REGISTER for DEFAULT_GROUP@@report# failed.

### ISSUE THREAD

**Issue by xiaobai-tx** [alibaba/nacos#10285]
Describe the bug
I have a report service that has been registered with nacos and can also be accessed, but this service keeps throwing exceptions:
```
Redo subscriber operation REGISTER for DEFAULT_GROUP@@report# failed.
```

and the stack trace is here:
```
<#8b486020> com.alibaba.nacos.api.exception.NacosException: token expired!
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:306)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:255)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForSubscribe(RedoScheduledTask.java:127)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForSubscribes(RedoScheduledTask.java:108)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.run(RedoScheduledTask.java:52)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

Version information
nacos server: 2.1.0
nacos-client: 2.1.2
spring-cloud-starter-alibaba-nacos-config: 2.1.4.RELEASE
spring-cloud-starter-alibaba-nacos-discovery: 2.1.4.RELEASE

**Comment by mayl0415** [comment]
我也遇到了，有解决吗

**Comment by xiaobai-tx** [comment]
> 我也遇到了，有解决吗 好像不一样，我都是 request nacos server failed，user not found

没有解决。。

**Comment by mayl0415** [comment]
> > 我也遇到了，有解决吗 好像不一样，我都是 request nacos server failed，user not found
> 
> 没有解决。。

我都是使用了NameService这个实例，然后试着加了一下配置
nacos.username=${spring.cloud.nacos.username}
nacos.password=${spring.cloud.nacos.password}

刚启动两分钟还没报错，再观察一下

**Comment by xiaobai-tx** [comment]
> > > 我也遇到了，有解决吗 好像不一样，我都是 request nacos server failed，user not found
> > 
> > 
> > 没有解决。。
> 
> 我都是使用了NameService这个实例，然后试着加了一下配置 nacos.username=${spring.cloud.nacos.username} nacos.password=${spring.cloud.nacos.password}
> 
> 刚启动两分钟还没报错，再观察一下

我配置了这个：
```
spring.cloud.nacos.username=${spring.cloud.nacos.config.username}
spring.cloud.nacos.password=${spring.cloud.nacos.config.password}
```
还是报这个问题

**Comment by mayl0415** [comment]
> 
我配置了四项
spring.cloud.nacos.username
spring.cloud.nacos.password
nacos.username
nacos.password

**Comment by xiaobai-tx** [comment]
> > 
> 
> 我配置了四项 spring.cloud.nacos.username spring.cloud.nacos.password nacos.username nacos.password

文档上也没个说明该配置那个呀
![0A821929](https://user-images.githubusercontent.com/20533626/230701234-d1cdc2d9-4bd2-4517-b765-e068db8254ae.gif)
期待你的最终结果

**Comment by mayl0415** [comment]
> > > 
> > 
> > 
> > 我配置了四项 spring.cloud.nacos.username spring.cloud.nacos.password nacos.username nacos.password
> 
> 文档上也没个说明该配置那个呀 ![0A821929](https://user-images.githubusercontent.com/20533626/230701234-d1cdc2d9-4bd2-4517-b765-e068db8254ae.gif) [ ](https://user-images.githubusercontent.com/20533626/230701234-d1cdc2d9-4bd2-4517-b765-e068db8254ae.gif) ![0A821929](https://user-images.githubusercontent.com/20533626/230701234-d1cdc2d9-4bd2-4517-b765-e068db8254ae.gif) [ ](https://user-images.githubusercontent.com/20533626/230701234-d1cdc2d9-4bd2-4517-b765-e068db8254ae.gif) 期待你的最终结果

我是引用了
@NacosInjected
NameService
这个实例，然后看@NacosInjected里面有个默认的NacosProperties，这个配置里有user.name和user.password。于是我就试着配置了一下。目前看我的正常了

**Comment by KomachiSion** [comment]
NacosException: token expired! , means your app has some problem cause no update auth token.

see #10275
