### ISSUE TITLE
nacos restart no database set

### ISSUE THREAD

**Issue by VioletSY** [alibaba/nacos#10286]
I deployed Nacos Server and the MySQL database used by Nacos Server based on Docker. After each MySQL restart, confirm that MySQL has been restarted, and then restart the Nacos Server, which will fail. Use the third-party tool DataGrip to open a table in MySQL at will, restart the Nacos Server, and Nacos can be successfully restarted. The above scenario has been tested many times and can be reproduced every time.

NACOS run the command:
docker run -d \
--restart=always \
-e PREFER_HOST_MODE=hostname \
-e MODE=standalone \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e NACOS_SERVER_IP=10.5.0.1 \
-e NACOS_SERVER_PORT=11304 \
-e MYSQL_SERVICE_HOST=10.5.0.1 \
-e MYSQL_SERVICE_PORT=11150 \
-e MYSQL_SERVICE_USER=test \
-e MYSQL_SERVICE_PASSWORD=test \
-e MYSQL_SERVICE_DB_NAME=nacos \
-p 21302:8848 \
-p 20302:7848 \
-p 22302:9848 \
--name nacos \
nacos/nacos-server:v2.1.0

Error log:
Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:225)
	at com.alibaba.nacos.config.server.service.dump.ExternalDumpService.init(ExternalDumpService.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java :307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 53 common frames omitted
Caused by: java.lang.IllegalStateException: No DataSource set
	at org.springframework.util.Assert.state(Assert.java:73)
	at org.springframework.jdbc.support.JdbcAccessor.obtainDataSource(JdbcAccessor.java:77)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:473)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:480)
	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.findConfigMaxId(ExternalStoragePersistServiceImpl.java:674)
	at com.alibaba.nacos.config.server.service.dump.processor.DumpAllProcessor.process(DumpAllProcessor.java:51)
	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpConfigInfo(DumpService.java:282)
	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:195)
	... 61 common frames omitted

中文描述：
我基于docker部署了nacos server以及nacos server 使用的mysql数据库。每次mysql重启之后，确认mysql已重启完成再重启nacos server都会重启失败。使用第三方工具datagrip打开随意mysql中的一张表，在重启nacos server，nacos就可以重启成功。以上情景测试多次，每次都可以复现。

nacos运行命令：
docker run -d \
--restart=always \
-e PREFER_HOST_MODE=hostname \
-e MODE=standalone \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e NACOS_SERVER_IP=10.5.0.1 \
-e NACOS_SERVER_PORT=11304 \
-e MYSQL_SERVICE_HOST=10.5.0.1 \
-e MYSQL_SERVICE_PORT=11150 \
-e MYSQL_SERVICE_USER=test \
-e MYSQL_SERVICE_PASSWORD=test \
-e MYSQL_SERVICE_DB_NAME=nacos \
-p 21302:8848 \
-p 20302:7848 \
-p 22302:9848 \
--name nacos \
nacos/nacos-server:v2.1.0

报错日志：
Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:225)
	at com.alibaba.nacos.config.server.service.dump.ExternalDumpService.init(ExternalDumpService.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 53 common frames omitted
Caused by: java.lang.IllegalStateException: No DataSource set
	at org.springframework.util.Assert.state(Assert.java:73)
	at org.springframework.jdbc.support.JdbcAccessor.obtainDataSource(JdbcAccessor.java:77)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:473)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:480)
	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.findConfigMaxId(ExternalStoragePersistServiceImpl.java:674)
	at com.alibaba.nacos.config.server.service.dump.processor.DumpAllProcessor.process(DumpAllProcessor.java:51)
	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpConfigInfo(DumpService.java:282)
	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:195)
	... 61 common frames omitted

**Comment by VioletSY** [comment]
update  nacos  run commang：

docker run -d
--restart=always
-e PREFER_HOST_MODE=hostname
-e MODE=standalone
-e SPRING_DATASOURCE_PLATFORM=mysql
-e NACOS_SERVER_IP=10.5.0.1
-e NACOS_SERVER_PORT=21302
-e MYSQL_SERVICE_HOST=10.5.0.1
-e MYSQL_SERVICE_PORT=11150
-e MYSQL_SERVICE_USER=test
-e MYSQL_SERVICE_PASSWORD=test
-e MYSQL_SERVICE_DB_NAME=nacos
-p 21302:8848
-p 20302:7848
-p 22302:9848
--name nacos
nacos/nacos-server:v2.1.0

**Comment by KomachiSion** [comment]
描述上看，非Nacos问题，环境问题，自查。
