### ISSUE TITLE
docker 启动nacos 报错。

### ISSUE THREAD

**Issue by xt19960729** [alibaba/nacos#10363]
启动命令如下：
   docker run -d -e MODE=standalone -e SPRING_DATASOURCE_PLATFORM=mysql -e MYSQL_SERVICE_HOST=xxxxxx -e MYSQL_SERVICE_PORT=3306 -e MYSQL_SERVICE_USER=root -e MYSQL_SERVICE_PASSWORD=xxxx -e MYSQL_SERVICE_DB_NAME=nacos_config -p 8848:8848 -p 9848:9848 -p 9849:9849 --restart=always --privileged=true  --name nacos nacos/nacos-server:v2.0.4

版本2.0.4 启动报错 No DataSource set 
怎么都不好使。。我进入容器ping 我mysql 没有问题。。数据库100%确定无错误。启动命令 无错误。。。但是依旧报错连不上数据库。如何知道具体情况。

**Comment by xt19960729** [comment]
2023-04-21 17:37:19,624 WARN [WatchFileCenter] start close

2023-04-21 17:37:19,626 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /home/nacos/data/tps

2023-04-21 17:37:19,626 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /home/nacos/conf

2023-04-21 17:37:19,627 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /home/nacos/data/loader

2023-04-21 17:37:19,627 WARN [WatchFileCenter] already closed

2023-04-21 17:37:19,627 WARN [NotifyCenter] Start destroying Publisher

2023-04-21 17:37:19,627 WARN [NotifyCenter] Destruction of the end

2023-04-21 17:37:19,627 ERROR Nacos failed to start, please see /home/nacos/logs/nacos.log for more details.

2023-04-21 17:37:19,660 INFO 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2023-04-21 17:37:19,668 ERROR Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.0.4.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:598)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1402)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:591)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:413)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1761)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:595)
	... 41 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:225)
	at com.alibaba.nacos.config.server.service.dump.ExternalDumpService.init(ExternalDumpService.java:52)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 53 common frames omitted
Caused by: java.lang.IllegalStateException: No DataSource set
	at org.springframework.util.Assert.state(Assert.java:73)
	at org.springframework.jdbc.support.JdbcAccessor.obtainDataSource(JdbcAccessor.java:77)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:452)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:462)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:473)
	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:480)
	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.findConfigMaxId(ExternalStoragePersistServiceImpl.java:667)
	at com.alibaba.nacos.config.server.service.dump.processor.DumpAllProcessor.process(DumpAllProcessor.java:51)
	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpConfigInfo(DumpService.java:282)
	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:195)
	... 61 common frames omitted

**Comment by xt19960729** [comment]
但是。有一个问题。。。。。我本机docker 部署时可以的。。。用的也是同一个数据库。用一个命令。。版本。所有一摸一样。。。一个报错，一个不报错。无法找到问题，

**Comment by wilsonwu** [comment]
从日志无法看出来根因，如果所有截至都一样，那么看看环境链接数据库是否正常？

**Comment by KomachiSion** [comment]
可以看看其他日志，比如config-fatal, config-server，nacos.log 有没有数据库具体的报错。

**Comment by sannan28** [comment]
我遇到了同样的问题 根据我的观察nacos 2.0.4 应该是在连接数据库失败一次后 console就再也登录不上了。但是我感觉貌似切换网络 也会有这种问题 不清楚是不是和缓存有关系 暂时想到的方式 就重新创建一个容器   用docker也比较方便

**Comment by sannan28** [comment]
你好 我现在已经找到原因 主要是 结合nacos.log 和config-fatal.log 日志，我的报错问题是体现在config-fatal.log 日志中 Public Key Retrieval is not allowed  解决的方式 在Nacos的配置文件application.properties中的数据库连接配置db.url.0参数加上allowPublicKeyRetrieval=true 希望能帮到你

**Comment by xt19960729** [comment]
> 你好 我现在已经找到原因 主要是 结合 nacos.log 和config-fatal.log 日志，我的报错问题是体现在config-fatal.log 日志中 公钥检索是不允许的 解决的方式 在Nacos的配置文件application.properties中的数据库连接配置db.url.0参数加上allowPublicKeyRetrieval=true 希望能帮到你

先谢谢您，我试过加上url.0来尝试解决这个问题。依然是行不通。。而且。我在本机测试。docker 镜像版本啥的都一模一样。。本地可以。。但是服务器就不行。可以确定服务器能数据库链接没问题。

**Comment by xt19960729** [comment]
经过我昨天重复开nacos。。我发现。我的nacos 在服务器docker 启动，然后我的服务器内存就满了。导致卡死。后来我给所有的已经启动的容器全部停掉。单独创建nacos容器。并设置了。jvm 使用内存。。发现。。所有相同的操作。。他可以了。

docker run -d -e MODE=standalone -e SPRING_DATASOURCE_PLATFORM=mysql -e JVM_XMS=128m -e JVM_XMX=128m -e MYSQL_SERVICE_HOST=XXX -e MYSQL_SERVICE_PORT=3306 -e MYSQL_SERVICE_USER=root -e MYSQL_SERVICE_PASSWORD=XXX-e MYSQL_SERVICE_DB_NAME=nacos_config -p 8848:8848 -p 9848:9848 -p 9849:9849 --restart=always --privileged=true  -e MYSQL_SERVICE_DB_PARAM='useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8' --name nacos nacos/nacos-server:v2.0.4

**Comment by xt19960729** [comment]
所以我不确定。是不是因为我服务器内存不够。但是实际我还看了一下服务器可用内存。。是够用的。。。而且。内存不够。应该不会报错。。。No DataSource set  这个吧。。。具体不知道。很奇怪。

**Comment by sannan28** [comment]
> 所以我不确定。是不是因为我服务器内存不够。但是实际我还看了一下服务器可用内存。。是够用的。。。而且。内存不够。应该不会报错。。。No DataSource set 这个吧。。。具体不知道。很奇怪。

可以看看日志

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.

**Comment by haroldduan** [comment]
> 所以我不确定。是不是因为我服务器内存不够。但是实际我还看了一下服务器可用内存。。是够用的。。。而且。内存不够。应该不会报错。。。No DataSource set 这个吧。。。具体不知道。很奇怪。

MySQL 是使的Docker还是物理主机的,可能是-e MYSQL_SERVICE_HOST=XXX \ 这块儿的问题,我也碰到了,设置成Docker的依赖指向-e MYSQL_SERVICE_HOST=host.docker.internal \ 有问题,我改成实际的MySQL地址就好了,很奇怪,我也还还在研究.
