### ISSUE TITLE
Redo subscriber operation REGISTER for DEFAULT_GROUP@@ids-service# failed.

### ISSUE THREAD

**Issue by silent-night-no-trace** [alibaba/nacos#10364]
**Describe the bug**

2023-04-21 17:41:55.889 [com.alibaba.nacos.client.naming.grpc.redo.0] INFO  [,,,] com.alibaba.nacos.client.naming.redoForSubscribe - Redo subscriber operation REGISTER for DEFAULT_GROUP@@ids-service#
2023-04-21 17:41:55.891 [com.alibaba.nacos.client.naming.grpc.redo.0] ERROR [,,,] com.alibaba.nacos.client.naming.redoForSubscribes - Redo subscriber operation REGISTER for DEFAULT_GROUP@@ids-service# failed.
com.alibaba.nacos.api.exception.NacosException: user not found!
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:359)
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:311)
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForSubscribe(RedoScheduledTask.java:127)
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForSubscribes(RedoScheduledTask.java:108)
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.run(RedoScheduledTask.java:52)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Expected behavior**

everything well 
**Actually behavior**
A clear and concise description of what you actually to happen.

2023-04-21 17:41:55.889 [com.alibaba.nacos.client.naming.grpc.redo.0] INFO  [,,,] com.alibaba.nacos.client.naming.redoForSubscribe - Redo subscriber operation REGISTER for DEFAULT_GROUP@@ids-service#
2023-04-21 17:41:55.891 [com.alibaba.nacos.client.naming.grpc.redo.0] ERROR [,,,] com.alibaba.nacos.client.naming.redoForSubscribes - Redo subscriber operation REGISTER for DEFAULT_GROUP@@ids-service# failed.
com.alibaba.nacos.api.exception.NacosException: user not found!
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:359)
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:311)
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForSubscribe(RedoScheduledTask.java:127)
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForSubscribes(RedoScheduledTask.java:108)
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.run(RedoScheduledTask.java:52)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
nacos-server 2.2.2
nacos-client 2.2.2

**Additional context**

**Comment by silent-night-no-trace** [comment]
There are two services . first  is ec-service ,second is ids-service, Each service has two nodes .
when i call ec-service interface, Method using the feign interface to request ids service  .then  Method using the feign interface to request ids

**Comment by KomachiSion** [comment]
`com.alibaba.nacos.api.exception.NacosException: user not found!`

**Comment by silent-night-no-trace** [comment]
Look at the source code

```java
public ServiceInfo doSubscribe(String serviceName, String groupName, String clusters) throws NacosException {
      SubscribeServiceRequest request = new SubscribeServiceRequest(namespaceId, groupName, serviceName, clusters,
              true);
      SubscribeServiceResponse response = requestToServer(request, SubscribeServiceResponse.class);
      redoService.subscriberRegistered(serviceName, groupName, clusters);
      return response.getServiceInfo();
  }
```

No username or password was passed in when subscribing to the service。 I think it's a bug。

订阅服务时 未传入 username和 password

**Comment by silent-night-no-trace** [comment]
```java
public NamingGrpcRedoService(NamingGrpcClientProxy clientProxy) {
      this.redoExecutor = new ScheduledThreadPoolExecutor(REDO_THREAD, new NameThreadFactory(REDO_THREAD_NAME));
      this.redoExecutor.scheduleWithFixedDelay(new RedoScheduledTask(clientProxy, this), DEFAULT_REDO_DELAY,
              DEFAULT_REDO_DELAY, TimeUnit.MILLISECONDS);
  }
```
A scheduled task is triggered every 3 seconds

So there are two solutions
1. Add the user name and password to the subscription request
2. The subscription service request is filtered out through the authentication filter

**Comment by silent-night-no-trace** [comment]
nacos account passwords for configuration and service discovery have been defined in the configuration file, but the above errors still occur in service subscription

**Comment by KomachiSion** [comment]
see com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy#requestToServer

security info will be inject by `            request.putAllHeader(
                    getSecurityHeaders(request.getNamespace(), request.getGroupName(), request.getServiceName()));`

**Comment by silent-night-no-trace** [comment]
The problem has now been solved. thanks
Cause of the problem, the project introduced the basic toolkit. There's a subscription service in the toolkit, But this subscription service uses PollingServerListUpdater (A default strategy for the dynamic server list updater to update). The operation uses the direct call API form. They didn't carry any authentication information. Nacos source implementation will have a regular task Once every three seconds ( redoExecutor.scheduleWithFixedDelay(new RedoScheduledTask(clientProxy, this), DEFAULT_REDO_DELAY,
        DEFAULT_REDO_DELAY, TimeUnit.MILLISECONDS);)
Wrong judgment, there is a problem with nacos subscription.
