### ISSUE TITLE
Nacos client is unable to register an instance by using its own created account

### ISSUE THREAD

**Issue by sixsixsix516** [alibaba/nacos#10365]
## Issue Description

Type: question

### Describe what happened (or what feature you want)

Nacos Server 开启了鉴权功能：nacos.core.auth.enabled=true

Nacos Client 操作的时候 需要配置好 username 、password

properties.setProperty("username", "nacos");
properties.setProperty("password", "nacos");
NamingService naming = NamingFactory.createNamingService(properties);

Nacos 使用的默认的 Nacos Nacos 账号、admin 权限，此时都没有问题。

然后我后台新建了个账号：
用户JAVA_CLIENT 
密码123456
角色 ROLE_CLIENT
权限 PUBLIC RW

将账号配置到客户端的时候，此时提示授权失败 403
Exception in thread "main" ErrCode:403, ErrMsg:authorization failed!
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:358)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:209)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:123)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:98)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:152)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:141)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:130)
	at com.alibaba.nacos.example.NamingExample.main(NamingExample.java:54)

我定位到源码关键位置
![image](https://user-images.githubusercontent.com/45815935/233604663-89d978fc-1039-41c9-b182-cba10a3f18f4.png)

问题是，权限后台只能如此配置。但是现在却无法使用。

权限默认为 :.*:.*
需要匹配的权限为 public:DEFAULT_GROUP:naming/nacos.test.3

所以此时正则没有满足，则未匹配到，则没有权限。

如果我手动在默认的权限前面再加个  .* 就可以匹配上了。

![image](https://user-images.githubusercontent.com/45815935/233604717-7aef771f-d7ab-422f-9c04-aa28211cfa5c.png)

所以如何处理呢？是否nacos-client 只能使用默认的 nacos 账号 ？
不支持自己创建账号？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
Nacos 2.2.0

**Comment by sixsixsix516** [comment]
账号信息
![image](https://user-images.githubusercontent.com/45815935/233605334-6b5baf4c-8805-401d-8889-6897cd6315e5.png)

![image](https://user-images.githubusercontent.com/45815935/233605386-bde2f866-d571-45e2-bb8d-b4df4170791a.png)

![image](https://user-images.githubusercontent.com/45815935/233605401-07d33051-da38-44a1-b7ae-77bdea0d92d5.png)

**Comment by KomachiSion** [comment]
duplicate with #10347
