### ISSUE TITLE
客户端请求grpc异常，后台出现异常打印

### ISSUE THREAD

**Issue by ljh205sy** [alibaba/nacos#10436]
Spring Boot Version: 2.7.10 (v2.7.10)
nacos-client： 2.1.1
nacos-server:  2.1.1  
后端异常grpc的打印，现象看起来是服务可以注册，配置可以获取，后台一直有异常输出，不知道是否对应用有影响？？？

2023-05-06 17:40:14.723 ERROR 19092 --- [2.168.19.37-527] c.a.n.c.remote.client.grpc.GrpcClient    : [1683365089550_192.168.118.88_51998]Request stream error, switch server,error={}

2023-05-06 17:40:14.723 ERROR 19092 --- [2.168.19.37-527] c.a.n.c.remote.client.grpc.GrpcClient    : [1683365089550_192.168.118.88_51998]Request stream error, switch server,error={}

com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
	at com.alibaba.nacos.shaded.io.grpc.Status.asRuntimeException(Status.java:533) ~[nacos-client-2.1.1.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:460) [nacos-client-2.1.1.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426) [nacos-client-2.1.1.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66) [nacos-client-2.1.1.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689) [nacos-client-2.1.1.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577) [nacos-client-2.1.1.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751) [nacos-client-2.1.1.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740) [nacos-client-2.1.1.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) [nacos-client-2.1.1.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) [nacos-client-2.1.1.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_341]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_341]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_341]

Class transformation time: 4.465214728s for 17841 classes or 2.502782763298022E-4s per class

**Comment by ljh205sy** [comment]
![image](https://user-images.githubusercontent.com/25653599/236617564-1d6f54ba-32de-4e12-8bbb-f69b8c073262.png)
要怎么处理这个事情呢？

**Comment by KomachiSion** [comment]
大概率是网络问题，看下是否有vip，vpn等转发组件， 去掉转发组件，直连试一下。

或者把vpn/vip的模式改成纯tcp模式，不要用http或http2模式。

**Comment by ljh205sy** [comment]
> 大概率是网络问题，看下是否有vip，vpn等转发组件， 去掉转发组件，直连试一下。
> 
> 或者把vpn/vip的模式改成纯tcp模式，不要用http或http2模式。

nacos的三台主机，
![image](https://user-images.githubusercontent.com/25653599/236725587-5b65600c-9bf6-4e31-a5d7-bef53fa2f1ce.png)

idea采用直连配置的模式，
spring:
  cloud:
    nacos:
      config:
        enabled: ${NACOS_CONFIG:true}
        server-addr: ${SERVER_ADDR}
        namespace:   ${NAMESPACE}
        file-extension: yml
        username: nacos
        password: Qwe123!@#
        shared-configs:
          - data-id: base-dev.yaml
            group: DEFAULT_GROUP
            refresh: true
      discovery:
        server-addr: ${SERVER_ADDR}
        namespace: ${NAMESPACE}
        enabled: true
#        ip: ${LOCAL_SERVER_IP:192.168.118.88}
        username: nacos
        password: Qwe123!@#
SERVER_ADDR: ${NACOS_CLUSTER:192.168.19.37:8848,192.168.19.40:8848,192.168.19.41:8848}
NAMESPACE: ${NACOS_NAMESPACE:a338c762-d2a7-4a2f-86f0-022c171c0928}

**Comment by KomachiSion** [comment]
看报错就是纯网络问题，连接被rst了
```com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream```

得自行在环境中查找一下原因了。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by ljh205sy** [comment]
> 看报错就是纯网络问题，连接被rst了
> 
> ```
> Received Rst Stream
> ```
> 
> 得自行在环境中查找一下原因了。

有思路吗？怎么去自行排查呀
