### ISSUE TITLE
获取旧的数据

### ISSUE THREAD

**Issue by liuxuzxx** [alibaba/nacos#10440]
**Describe the bug**
我们现在在Nacos上有个配置信息 info.json
```json
{
  "channel" : {
   ....省略很多属性信息
    "zone" : "ns",
    "propertyWrappers" : [ {
      "propertyKey" : "role",
      "propertyValue" : "战略"
    } ]
  }
}
```
当把propertyWrappers置为 [] 的时候，
```json
{
  "channel" : {
   ....省略很多属性信息
    "zone" : "ns",
    "propertyWrappers" : [ ]
  }
}
```

在客户端接收到的还是之前的信息：
```json
"propertyWrappers" : [ {
      "propertyKey" : "role",
      "propertyValue" : "战略"
    } ]
```

正确的结果应该是：[]  但是还是之前的老数据，只有在这个propertyWrappers从有数据变成为[]的时候才会出现 nacos:2.0.3

**Comment by KomachiSion** [comment]
1. 确认订阅了配置，控制台上可以看到订阅者列表和订阅者当前这个配置的md5
2. 看nacos-client的日志，${user.home}/logs/nacos/config.log 确认是否收到新的配置
3. snapshot ${user.home}/nacos/config 中也有配置，查看是否是新的
4. 确认你的应用在listener有进行新配置的读取。

**Comment by liuxuzxx** [comment]
看了下，日志信息：

```bash
2023-05-08 10:47:28.566 ERROR [com.alibaba.nacos.client.Worker:impl.ClientWorker] Async listen config change error 
com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:UNHEALTHY
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:650) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1007) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:986) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.executeConfigListen(ClientWorker.java:777) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.lambda$startInternal$2(ClientWorker.java:695) ~[nacos-client-2.0.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_362]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_362]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
2023-05-08 10:47:28.566 ERROR [com.alibaba.nacos.client.Worker:impl.ClientWorker] Async listen config change error 
com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:UNHEALTHY
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:650) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1007) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:986) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.executeConfigListen(ClientWorker.java:777) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.lambda$startInternal$2(ClientWorker.java:695) ~[nacos-client-2.0.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_362]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_362]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
2023-05-08 10:47:28.567 ERROR [com.alibaba.nacos.client.Worker:impl.ClientWorker] Async listen config change error 
com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:UNHEALTHY
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:650) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1007) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:986) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.executeConfigListen(ClientWorker.java:777) ~[nacos-client-2.0.4.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.lambda$startInternal$2(ClientWorker.java:695) ~[nacos-client-2.0.4.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_362]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_362]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_362]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_362]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_362]
	at java.lang.Thread.run(Thread.java:750) [?:1.8.0_362]
2023-05-08 10:47:28.567 INFO [com.alibaba.nacos.client.remote.worker:impl.ClientWorker] [94abe119-e95c-4813-adfc-d4cde2214aa7_config-0] DisConnected,clear listen context...
2023-05-08 10:47:28.567 INFO [com.alibaba.nacos.client.remote.worker:impl.ClientWorker] [94abe119-e95c-4813-adfc-d4cde2214aa7_config-0] Connected,notify listen context...

```

**Comment by liuxuzxx** [comment]
但是很奇怪的是：
propertyWrappers这个List，新增一个，修改其中的信息，只要是不清空，就没有任何问题，同步更新都正常，只有在之前是非空的情况下，然后清空了，就会出现这个问题！

**Comment by liuxuzxx** [comment]
3. snapshot ${user.home}/nacos/config 中也有配置，查看是否是新的

我按照查看了下，是最新的，和nacos上是一致的

**Comment by liuxuzxx** [comment]
#3803 感觉和这个是相同的问题

**Comment by liuxuzxx** [comment]
找到了一个解决方案：
```java
@Component
public class CleanupRamConfig implements ApplicationListener<RefreshEvent>, Ordered {

    @Autowired
    private ChannelConfig channelConfig;

    @Override
    public void onApplicationEvent(RefreshEvent event) {
        channelConfig.setPropertyWrappers(Collections.emptyList());
    }

    @Override
    public int getOrder() {
        return Ordered.HIGHEST_PRECEDENCE;
    }
}
```

就是监听RefreshEvent事件，然后设置这个对应的属性清理为null/空的List 这个事件是在EnvironmentChangeEvent之前触发的

**Comment by KomachiSion** [comment]
那个日志信息如果一直在打印， 说明你的客户端和服务端之间的连接很不稳定， 可能是vip/vpn的设置有问题，也可能是网络问题。

**Comment by liuxuzxx** [comment]
不是网络问题，网络没有问题



---原始邮件---
发件人: "杨翊 ***@***.***&gt;
发送时间: 2023年5月9日(周二) 下午5:46
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] 获取旧的数据 (Issue #10440)




 
那个日志信息如果一直在打印， 说明你的客户端和服务端之间的连接很不稳定， 可能是vip/vpn的设置有问题，也可能是网络问题。

**Comment by liuxuzxx** [comment]
> 那个日志信息如果一直在打印， 说明你的客户端和服务端之间的连接很不稳定， 可能是vip/vpn的设置有问题，也可能是网络问题。

和 #3803 这个问题一样的问题

**Comment by KomachiSion** [comment]
先理解问题本质， 你的问题本质是连不上服务端，链接状态一直是unhealthy，说明你客户端请求不到服务端。所以一直用的缓存数据（旧数据）。

解决了网络问题，让客户端能连接到服务端，自然就会取到新数据。

**Comment by liuxuzxx** [comment]
> 先理解问题本质， 你的问题本质是连不上服务端，链接状态一直是unhealthy，说明你客户端请求不到服务端。所以一直用的缓存数据（旧数据）。
> 
> 解决了网络问题，让客户端能连接到服务端，自然就会取到新数据。

问题应该是这样子的：
1.首先我检查了下作者让我检查的几个选项，然后我发现，nacos也会把数据同步到本地磁盘上一份，我发现，本地磁盘上的那份确实是和nacos上一致的，这个没有任何问题
2.然后我跟踪了下源码，发现RefreshEvent和EnvironmentChangeEvent这俩事件其实是拿到了这个更新的数据的
3.接着我贴出来的日志，应该是因为我本地断点导致没有及时回复给nacos服务端的问题

**Comment by liuxuzxx** [comment]
总体来说：
1.硬盘上确实是和Nacos服务端上的一致
2.跟踪源码，发现更新之后的数据也是拿到了，但是最后就是没有更新到对象当中

**Comment by KomachiSion** [comment]
没有更新到应用对象中那就和nacos没什么关系了， 配置推送到之后， 是否使用是由应用程序或应用框架决定的。

**Comment by KomachiSion** [comment]
如果用的是SCA，就转issue到SCA社区中看下。

如果是nacos-spring-boot-starter， 可以先用starter的example跑一下试试，研究一下example中的一些配置设置，看下是否开启了。比如一些Refresh开关。

**Comment by liuxuzxx** [comment]
> 
排查了下，是使用spring-cloud，没有使用Nacos的RefreshScope，因为，我们需要支持多种配置中心，所以没法使用RefreshScope注解，暂时先用RefreshEvent这个事件来解决吧.多谢解答
