### ISSUE TITLE
nginx不管怎么配置 客户端启动都报错 

### ISSUE THREAD

**Issue by liruhui** [alibaba/nacos#10452]
## 1. 问题说明
```
这个问题我已经提交过一次了 https://github.com/alibaba/nacos/issues/10437   我也按照其他issues提供的方式配置了，
但是最终都不成功 ，我想把过程再演示一遍  帮我看看到底是哪的问题  谢谢 
```

## 2. 环境说明
```
五个虚拟机  其中三台安装nacos  一台安装mysql  一台安装nginx 

nacos所在的机器的ip分别是  
192.168.191.148
192.168.191.164
192.168.191.165


mysql所在机器的ip是  192.168.191.163

nginx所在机器的ip是 192.168.191.160 
```

### 3.1. 第一步： 三个nacos配置mysql地址 
![image](https://user-images.githubusercontent.com/24687986/236811001-1c02dbcc-5b61-437b-a64f-109bdf027323.png)

### 3.2. 第二步: 三个nacos同时修改cluster.conf文件 
![image](https://user-images.githubusercontent.com/24687986/236811320-adc77d29-7272-4860-ba51-154cf013fc9e.png)

### 3.3. 第三步：分别启动Nacos 集群搭建成功
![image](https://user-images.githubusercontent.com/24687986/236811635-02718b79-52b5-4659-9d35-64b58cec5e80.png)

### 4.1. 编写Nginx配置文件 
![image](https://user-images.githubusercontent.com/24687986/236812223-a4e00d88-9361-4491-8629-4a9f41bd290a.png)

### 4.2. 修改配置文件
![image](https://user-images.githubusercontent.com/24687986/236812316-cede3aee-cfd0-46fa-bbd7-2640d7c0dbb2.png)

### 4.3. 启动报错
```
Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
```
## 5. Nginx负载均衡错误二（演示）
```
 根据issue 9004 的方式配置  还是报错  
```
### 5.1. 修改nginx的配置文件
![image](https://user-images.githubusercontent.com/24687986/236813916-fb9cda69-ff53-4477-85ce-c3aa34eb0abf.png)

### 5.2. 修改修改配置文件
![image](https://user-images.githubusercontent.com/24687986/236814145-e775e4e8-5515-44e2-b22c-6b38b437d680.png)

### 5.3. 启动依旧报错 
```
Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:288) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:128) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:114) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:94) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.9.RELEASE.jar:2.2.9.RELEASE]
	... 27 common frames omitted
```

**Comment by wilsonwu** [comment]
社区的朋友如果有nginx配置成功的，可以把相关配置贴出来，然后我们可以根据成功经验总结成一个使用文档。

**Comment by KomachiSion** [comment]
9848端口不要用 proxy_pass， 这个是代理转发，不支持grpc

**Comment by KomachiSion** [comment]
```
    upstream grpc_server {
       server 127.0.0.1:8001;
    }

    server {
        listen 9848 so_keepalive=on;
        proxy_responses 1;
        proxy_timeout 20s;
        proxy_pass grpc_server;

    }
```

**Comment by KomachiSion** [comment]
> ```
>     upstream grpc_server {
>        server 127.0.0.1:9848;
>     }
> 
>     server {
>         listen xxxx so_keepalive=on;
>         proxy_responses 1;
>         proxy_timeout 20s;
>         proxy_pass grpc_server;
> 
>     }
> ```

**Comment by liruhui** [comment]
@wilsonwu @KomachiSion  
**大哥 大哥 还是不行啊**

## 如果把配置放到http内不行 如图
![image](https://github.com/alibaba/nacos/assets/24687986/560fbe21-bd27-438e-bc6f-ef780ddf19e2)



## 把配置放到http外还是不行 如图
![image](https://github.com/alibaba/nacos/assets/24687986/6d37355b-d8e1-427f-bcc3-d1a4946c2a73)

**Comment by KomachiSion** [comment]
那就不清楚了， 我反正这么设置是可以的， 很稳定。

**Comment by HisinR** [comment]
@wilsonwu 大佬能解决一下吗？好老火啊，这个问题，不管怎样都不行的。网上教程，官方文档都没有一个是正确的配置，一直报错

**Comment by wilsonwu** [comment]
@HisinR 感谢你的at，我稍后尝试一下看看能不能在本地环境解决你的问题，不过最近月底比较忙，时间不确定，你可以一遍寻找其他方案一遍等待。

**Comment by KomachiSion** [comment]
The issue has no response more than one month, whether can we close issue first?

**Comment by KomachiSion** [comment]
It's long time no response for author and assigner. Close issue first. If question more, please submit new issue and relative this issue.

**Comment by akwangl** [comment]
官方不能指定tcp/rpc方式吗？都把楼上哥们整破防了
