### ISSUE TITLE
Failed to initialize inline Byte Buddy mock maker in nacos-api,NetUtilsTest,testLocalIpWithException Method

### ISSUE THREAD

**Issue by shx1461260427** [alibaba/nacos#10497]
**Describe the bug**
When running the "testLocalIpWithException" test method in the Nacos API module, an error occurs during the initialization of the Mockito library. It fails to initialize the inline Byte Buddy mock maker.

**Expected behavior**
The test should run without errors and the Mockito library should be initialized successfully.

**Actually behavior**
The test fails with the following error:
```
java.lang.IllegalStateException: Could not initialize plugin: interface org.mockito.plugins.MockMaker (alternate: null)
	at org.mockito.internal.configuration.plugins.PluginLoader$1.invoke(PluginLoader.java:84)
	at com.sun.proxy.$Proxy5.isTypeMockable(Unknown Source)
	at org.mockito.internal.util.MockUtil.typeMockabilityOf(MockUtil.java:33)
	at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:22)
	at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:250)
	at org.mockito.internal.creation.MockSettingsImpl.build(MockSettingsImpl.java:232)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:61)
	at org.mockito.Mockito.mock(Mockito.java:1951)
	at org.mockito.Mockito.mock(Mockito.java:1862)
	at com.alibaba.nacos.api.utils.NetUtilsTest.testLocalIpWithException(NetUtilsTest.java:72)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:235)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:54)
Caused by: java.lang.IllegalStateException: Failed to load interface org.mockito.plugins.MockMaker implementation declared in sun.misc.CompoundEnumeration@153f5a29
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:57)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:65)
	at org.mockito.internal.configuration.plugins.PluginLoader.loadPlugin(PluginLoader.java:50)
	at org.mockito.internal.configuration.plugins.PluginRegistry.<init>(PluginRegistry.java:19)
	at org.mockito.internal.configuration.plugins.Plugins.<clinit>(Plugins.java:16)
	at org.mockito.internal.util.MockUtil.<clinit>(MockUtil.java:28)
	... 35 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.mockito.internal.configuration.plugins.PluginInitializer.loadImpl(PluginInitializer.java:52)
	... 40 more
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker.
It appears as if your JDK does not supply a working agent attachment mechanism.
Java               : 1.8
JVM vendor name    : Amazon.com Inc.
JVM vendor version : 25.342-b07
JVM name           : OpenJDK 64-Bit Server VM
JVM version        : 1.8.0_342-b07
JVM info           : mixed mode
OS name            : Windows 11
OS version         : 10.0
```
**How to Reproduce**

1. Run the testLocalIpWithException test method in the Nacos API module.
2. Observe the error occurring during Mockito initialization.

**Desktop (please complete the following information):**
OS: Windows 11
JDK: OpenJDK 64-Bit Server VM (Java 1.8.0_342-b07)
Nacos Version: DEVELOP
Module: API

**Additional context**
It seems that the initialization of the inline Byte Buddy mock maker is failing due to a missing implementation of the ‘org.mockito.plugins.MockMaker’ interface. This occurs with the provided JDK and Nacos configuration.

Any assistance or guidance to resolve this issue would be greatly appreciated.

**Comment by KomachiSion** [comment]
```
Caused by: org.mockito.exceptions.base.MockitoInitializationException: 
Could not initialize inline Byte Buddy mock maker.
It appears as if your JDK does not supply a working agent attachment mechanism.
```

It seems mockito can't support your jdk version， or your jdk version has some bug.

The test run well in my local env(macos) and github ci action env(ubuntu and centos)

**Comment by KomachiSion** [comment]
So I think you should submit issue to mockito community. The problem is mockito can't support OpenJDK

**Comment by KomachiSion** [comment]
Of cource, you can solve problem with submiting PR in nacos, to change the UT with other way.

**Comment by KomachiSion** [comment]
No more response from author, I think this is not nacos' problem.
