### ISSUE TITLE
com.alibaba.nacos.client.config.utils.IOUtils#toString(java.io.InputStream, java.lang.String) NPE

### ISSUE THREAD

**Issue by javase** [alibaba/nacos#10503]
**Describe the bug**
Erro log is : `java.lang.NullPointerException: null
	at java.io.Reader.<init>(Reader.java:78)
	at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
	at com.alibaba.nacos.client.config.utils.IOUtils.toString(IOUtils.java:33)
	at com.alibaba.nacos.client.config.impl.HttpSimpleClient.httpPost(HttpSimpleClient.java:129)
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:135)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:377)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:352)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:512)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Expected behavior**
no error log 

**Actually behavior**
NPE log 

**How to Reproduce**
start up the springboot ， then when long polling ,NPE

**Desktop (please complete the following information):**
 - OS: [MAC]
 - Version [e.g. nacos-server 1.1.3, nacos-client 1.1.3]
 - Module [client]
 - SDK [spring boot / nacos ]

**Additional context**
com.alibaba.nacos.client.config.utils.IOUtils#toString(java.io.InputStream, java.lang.String)

new InputStreamReader(input, Constants.ENCODE)

need to consider the input is null

**Comment by KomachiSion** [comment]
Which version?
