### ISSUE TITLE
fabric-gateway-java 与 nacos 集成 导致 io_grpc_netty_shaded_netty_tcnative_windows_x86_64.dll 无法加载

### ISSUE THREAD

**Issue by rundon** [alibaba/nacos#10522]
**Describe the bug**
存在多个io_grpc_netty_shaded_netty_tcnative_windows_x86_64.dll 导致加载失败。(The presence of more than one io_grpc_netty_shaded_netty_tcnative_windows_x86_64.dll caused the load to fail.)

**Expected behavior**
没有使用nacos可以正常初始化，希望从nacos获取配置文件也可以正常初始化。(It can be initialized normally without using nacos, and it is hoped that the configuration file obtained from nacos can also be initialized normally)

**Actually behavior**
A clear and concise description of what you actually to happen.
调用 gateway.getNetwork(channel); 获取network时异常。(Exception when calling gateway.getNetwork(channel); to get network.)

**How to Reproduce**
详细日志：
11:19:20.107 [main] INFO  c.g.f.g.c.FabricContext - [initialize,85] - 初始化 钱包
11:19:20.243 [main] INFO  c.g.f.g.c.FabricContext - [initialize,99] - 初始化 gateway
11:19:20.313 [main] INFO  c.g.f.g.c.FabricContext - [initialize,115] - 初始化网络... 
11:19:20.550 [main] WARN  o.s.b.w.s.c.AnnotationConfigServletWebServerApplicationContext - [refresh,591] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fabricController': Unsatisfied dependency expressed through field 'fabricService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fabricService' defined in class path resource [com/ggy/config/SpringFabricGatewayAutoConfigure.class]: Unsatisfied dependency expressed through method 'fabricService' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fabricContext': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: failed to load the required native library
11:19:20.551 [main] INFO  o.a.c.c.StandardService - [log,173] - Stopping service [Tomcat]
11:19:20.580 [main] ERROR o.s.b.SpringApplication - [reportFailure,821] - Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fabricController': Unsatisfied dependency expressed through field 'fabricService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fabricService' defined in class path resource [com/ggy/config/SpringFabricGatewayAutoConfigure.class]: Unsatisfied dependency expressed through method 'fabricService' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fabricContext': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: failed to load the required native library
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:660)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:640)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:399)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1431)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:619)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292)
	at com.ggy.GuoGuFabricApplication.main(GuoGuFabricApplication.java:14)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'fabricService' defined in class path resource [com/ggy/config/SpringFabricGatewayAutoConfigure.class]: Unsatisfied dependency expressed through method 'fabricService' parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fabricContext': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: failed to load the required native library
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.resolveFieldValue(AutowiredAnnotationBeanPostProcessor.java:657)
	... 20 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'fabricContext': Invocation of init method failed; nested exception is java.lang.UnsatisfiedLinkError: failed to load the required native library
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1391)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1311)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:887)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:791)
	... 33 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: failed to load the required native library
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.ensureAvailability(OpenSsl.java:596)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContext.newClientContextInternal(SslContext.java:830)
	at io.grpc.netty.shaded.io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:611)
	at org.hyperledger.fabric.sdk.Endpoint.<init>(Endpoint.java:269)
	at org.hyperledger.fabric.sdk.Endpoint.createEndpoint(Endpoint.java:476)
	at org.hyperledger.fabric.sdk.Peer.getEndorserClient(Peer.java:241)
	at org.hyperledger.fabric.sdk.Peer.sendProposalAsync(Peer.java:223)
	at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4898)
	at org.hyperledger.fabric.sdk.Channel.sendProposalToPeers(Channel.java:4848)
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:941)
	at org.hyperledger.fabric.sdk.Channel.getConfigBlock(Channel.java:907)
	at org.hyperledger.fabric.sdk.Channel.parseConfigBlock(Channel.java:1964)
	at org.hyperledger.fabric.sdk.Channel.loadCACertificates(Channel.java:1801)
	at org.hyperledger.fabric.sdk.Channel.initialize(Channel.java:1222)
	at org.hyperledger.fabric.gateway.impl.NetworkImpl.initializeChannel(NetworkImpl.java:59)
	at org.hyperledger.fabric.gateway.impl.NetworkImpl.<init>(NetworkImpl.java:50)
	at org.hyperledger.fabric.gateway.impl.GatewayImpl.getNetwork(GatewayImpl.java:252)
	at com.ggy.fabric.gateway.config.FabricContext.initialize(FabricContext.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
	... 46 common frames omitted
Caused by: java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty_tcnative_windows_x86_64, netty_tcnative_x86_64, netty_tcnative]
	at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:114)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:705)
	at io.grpc.netty.shaded.io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:146)
	at io.grpc.netty.shaded.io.grpc.netty.GrpcSslContexts.configure(GrpcSslContexts.java:167)
	at org.hyperledger.fabric.sdk.Endpoint.getSslContextBuilder(Endpoint.java:301)
	at org.hyperledger.fabric.sdk.Endpoint.<init>(Endpoint.java:261)
	... 67 common frames omitted
	Suppressed: java.lang.IllegalStateException: Multiple resources found for 'META-INF/native/io_grpc_netty_shaded_netty_tcnative_windows_x86_64.dll' with different content: [jar:file:/C:/Users/Rundon/.m2/repository/io/grpc/grpc-netty-shaded/1.53.0/grpc-netty-shaded-1.53.0.jar!/META-INF/native/io_grpc_netty_shaded_netty_tcnative_windows_x86_64.dll, jar:file:/C:/Users/Rundon/.m2/repository/com/alibaba/nacos/nacos-client/2.0.4/nacos-client-2.0.4.jar!/META-INF/native/io_grpc_netty_shaded_netty_tcnative_windows_x86_64.dll]
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.getResource(NativeLibraryLoader.java:301)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:173)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 72 common frames omitted
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: io_grpc_netty_shaded_netty_tcnative_x86_64
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 72 common frames omitted
	Caused by: java.io.FileNotFoundException: META-INF/native/io_grpc_netty_shaded_netty_tcnative_x86_64.dll
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
		... 73 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative_x86_64 in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
			at java.lang.Runtime.loadLibrary0(Runtime.java:870)
			at java.lang.System.loadLibrary(System.java:1122)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 73 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative_x86_64 in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
				at java.lang.Runtime.loadLibrary0(Runtime.java:870)
				at java.lang.System.loadLibrary(System.java:1122)
				at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 74 common frames omitted
	Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: io_grpc_netty_shaded_netty_tcnative
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:105)
		... 72 common frames omitted
	Caused by: java.io.FileNotFoundException: META-INF/native/io_grpc_netty_shaded_netty_tcnative.dll
		at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
		... 73 common frames omitted
		Suppressed: java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative in java.library.path
			at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
			at java.lang.Runtime.loadLibrary0(Runtime.java:870)
			at java.lang.System.loadLibrary(System.java:1122)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:391)
			at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
			... 73 common frames omitted
			Suppressed: java.lang.UnsatisfiedLinkError: no io_grpc_netty_shaded_netty_tcnative in java.library.path
				at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
				at java.lang.Runtime.loadLibrary0(Runtime.java:870)
				at java.lang.System.loadLibrary(System.java:1122)
				at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
				at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
				at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
				at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
				at java.lang.reflect.Method.invoke(Method.java:498)
				at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:425)
				at java.security.AccessController.doPrivileged(Native Method)
				at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:417)
				at io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:383)
				... 74 common frames omitted
11:19:20.582 [Thread-3] WARN  c.a.n.c.h.HttpClientBeanHolder - [shutdown,108] - [HttpClientBeanHolder] Start destroying common HttpClient
11:19:20.582 [Thread-8] WARN  c.a.n.c.n.NotifyCenter - [shutdown,136] - [NotifyCenter] Start destroying Publisher
11:19:20.582 [Thread-8] WARN  c.a.n.c.n.NotifyCenter - [shutdown,153] - [NotifyCenter] Destruction of the end

**Desktop (please complete the following information):**
 - OS: window 11 专业版
 - Version  nacos-client 2.0.4，fabric-gateway-java 2.2.1
 - Module config
 - SDK spring-cloud-alibaba-nacos

**Additional context**

**Comment by KomachiSion** [comment]
Maybe you should use pure client, default nacos-client will shard grpc into client for class conflict.

https://nacos.io/zh-cn/docs/v2/guide/user/sdk.html

native version at lease 2.2.1

**Comment by KomachiSion** [comment]
那就看下是否你自己用2.0.4的tag，build一个2.0.4的client来用

**Comment by rundon** [comment]
方向是对的。修改nacos的jackson，grpc的版本与fabric-gateway-java一致，首先保证nacos可以正常获取配置接下来就是补充启动时缺少的依赖包。一句话概述，有的玩了。
