### ISSUE TITLE
spring cloud gateway return 404

### ISSUE THREAD

**Issue by nunuqq1** [alibaba/nacos#1054]
nacos server version 0.9.0
spring boot version: 2.0.6.RELEASE
spring cloud version: Finchley.RELEASE
spring-cloud-starter-ablibaba-nacos-discovery: 0.2.1.RELEASE

my gateway: spring cloud gateway
my application name: app for example

A
1. start gateway
2. start app
3. get app api with gateway, it's ok

B 
1. start app
2. start gateway
3. fail to get app api with gateway, and will alway return 404

C
2. start app
3. get app api with gateway, it's ok
4. restart app
5. fail to get app api for a while, and soon will ok

my question:
1. B why?
2.C,how to make it work faster?  for example, eureka has a setting instance-info-replication-interval-seconds can change the interval

**Comment by Albert-Hugo** [comment]
@nunuqq1 Could you show your gateway config? I would like to have a look.

**Comment by nunuqq1** [comment]
server:
  port: 8050
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  application:
    name: @artifactId@
logging:
  level:
    org.springframework.cloud.gateway: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8848/eureka/
    instance-info-replication-interval-seconds: 3


nacos properties has been removed, which is just simply set a value for nacos.config.server-addr

**Comment by nunuqq1** [comment]
server:
  port: 8050
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
  application:
    name: @artifactId@
logging:
  level:
    org.springframework.cloud.gateway: debug
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8848/eureka/
    instance-info-replication-interval-seconds: 3


nacos config has been removed, which is simply set value for nacos.config.server-addr

**Comment by Albert-Hugo** [comment]
Why did you also using eureka for discovery

**Comment by nunuqq1** [comment]
that's the yml i'm using now, which nacos has been replaced by eureka, because eureka has no such problems,and as described in my response, when using nacos, just remove eureka properties and add nacos.config.server-addr

**Comment by nkorange** [comment]
@nunuqq1 This may be triggered by the behaviors of Spring Cloud Gateway. I need to have a look at it.

**Comment by gclsoft** [comment]
I have the same problem: debug too long time spring cloud gateway 404, using nacos too.
I have set:
```
spring

  zipkin:

   #他不断的去跟踪所有服务，
      discovery-client-enabled: false
```
But not work  @nkorange

**Comment by gclsoft** [comment]
Another problem: When I visit a service url api but the service is not started, then the gateway print the error all the time, never stop until I start the service:
```
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://pigx-register:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@pigx-codegen
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

2019-07-26 11:48:27.468 ERROR 148344 --- [.naming.updater] com.alibaba.nacos.client.naming          : [NA] failed to update serviceName: DEFAULT_GROUP@@pigx-codegen

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([pigx-register:8848]) tried: failed to req API:http://pigx-register:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@pigx-codegen
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```
