### ISSUE TITLE
本地启动连接nacos2.2.1有时会注册成功，有时失败，报错 ErrCode:-401, ErrMsg:Client not connected, current status:STARTING

### ISSUE THREAD

**Issue by TangGe2010** [alibaba/nacos#10558]
**Describe the bug**
Starting the local IDEA service and connecting to the nacos2.2.1 registry service may result in successful registration or failure,
Error ErrCode: -401, ErrMsg: Client not connected, current status: Starting

本地IDEA启动服务，连接nacos2.2.1注册中心服务有时会注册成功，有时失败，
报错 ErrCode:-401, ErrMsg:Client not connected, current status:STARTING

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
1、As shown in the following figure:
When the main thread registers a service with the nacos service, this. currentConnection==null, and the connection has not been established yet, resulting in Client not connected, current status: Starting. After analyzing the code, it was found that the connection was created by the asynchronous thread com. alibaba. nacos. client. remote. worker. Since it is asynchronous, the main thread may register the service before the asynchronous thread establishes the connection, which can cause problems
1. 如下图所示：
当main线程往nacos服务注册服务的时候，this.currentConnection == null,连接还未建立，所以导致Client not connected, current status: Starting。分析了代码，是因为是异步线程com.alibaba.nacos.client.remote.worker去创建连接的，既然是异步，所以main线程有可能会在异步线程建立连接前先去注册服务，就会导致问题
![NACOS registration issue](https://github.com/alibaba/nacos/assets/42267099/f80f59ae-004b-4727-b879-359be8afdf56)

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.2.1, nacos-client 2.2.1-RC]
 - Module [e.g. naming/config]
 - SDK [spring-cloud-starter-alibaba-nacos-discovery-2021.1, ]

**Additional context**

**Comment by KomachiSion** [comment]
刚创建的首次连接我印象中是同步的，会阻塞一段时间。

**Comment by KomachiSion** [comment]
@shiyiyue1102 看下

**Comment by TangGe2010** [comment]
> 刚创建的首次连接我印象中是同步的，会阻塞一段时间。
进一步深入调式发现确实是同步进行连接的，但是不清楚为什么同步连接不上，导致转为异步了。telnet 本地端口8848 和 9848 都能通的
![nacos同步连接不上转为异步](https://github.com/alibaba/nacos/assets/42267099/671e5c26-21fc-45a3-b8d6-3116057dc7e9)

**Comment by KomachiSion** [comment]
看客户端日志,remote.log 里面有连不上的具体信息。

**Comment by Daydreamer-ia** [comment]
> 刚创建的首次连接我印象中是同步的，会阻塞一段时间。

首次连接的时候是同步的，在连接失败后才会转为异步

**Comment by TangGe2010** [comment]
> 本地端口都是正常启动的，也能telnet通，啥原因会导致同步连不上？下图有控制台打印的具体异常信息
![本地启动端口正常](https://github.com/alibaba/nacos/assets/42267099/3c8bc90a-b769-4e5a-8d72-123c31103684)

![nacos本地连接异常信息](https://github.com/alibaba/nacos/assets/42267099/6223ddb3-bcbc-4b8b-abdf-35960c59d91c)

**Comment by TangGe2010** [comment]
还有如下异常信息：
Exception in thread "nacos-grpc-client-executor-localhost-2" java.util.concurrent.RejectedExecutionException: event executor terminated
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.reject(SingleThreadEventExecutor.java:926)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.offerTask(SingleThreadEventExecutor.java:353)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.addTask(SingleThreadEventExecutor.java:346)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:828)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.execute(SingleThreadEventExecutor.java:818)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.WriteQueue.scheduleFlush(WriteQueue.java:67)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.WriteQueue.enqueue(WriteQueue.java:87)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyClientStream$Sink.writeFrameInternal(NettyClientStream.java:182)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyClientStream$Sink.writeFrame(NettyClientStream.java:208)
	at com.alibaba.nacos.shaded.io.grpc.internal.AbstractClientStream.deliverFrame(AbstractClientStream.java:199)
	at com.alibaba.nacos.shaded.io.grpc.internal.MessageFramer.commitToSink(MessageFramer.java:352)
	at com.alibaba.nacos.shaded.io.grpc.internal.MessageFramer.close(MessageFramer.java:328)
	at com.alibaba.nacos.shaded.io.grpc.internal.AbstractStream.endOfMessages(AbstractStream.java:72)
	at com.alibaba.nacos.shaded.io.grpc.internal.AbstractClientStream.halfClose(AbstractClientStream.java:206)
	at com.alibaba.nacos.shaded.io.grpc.internal.ForwardingClientStream.halfClose(ForwardingClientStream.java:67)
	at com.alibaba.nacos.shaded.io.grpc.internal.DelayedStream$9.run(DelayedStream.java:320)
	at com.alibaba.nacos.shaded.io.grpc.internal.DelayedStream.drainPendingCalls(DelayedStream.java:163)
	at com.alibaba.nacos.shaded.io.grpc.internal.DelayedStream.setStream(DelayedStream.java:132)
	at com.alibaba.nacos.shaded.io.grpc.internal.DelayedClientTransport$PendingStream.createRealStream(DelayedClientTransport.java:358)
	at com.alibaba.nacos.shaded.io.grpc.internal.DelayedClientTransport$PendingStream.access$300(DelayedClientTransport.java:341)
	at com.alibaba.nacos.shaded.io.grpc.internal.DelayedClientTransport$5.run(DelayedClientTransport.java:300)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by KomachiSion** [comment]
java.util.concurrent.RejectedExecutionException: event executor terminated 
你执行队列满了， 要再往前翻， 看最初的几个报错原因

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by wcollin** [comment]
在arm64的服务器上遇到同样的问题，服务端2.2.3，客户端2.0.3

**Comment by LL3706** [comment]
最后这个问题是怎么解决的

**Comment by svipmusic** [comment]
检查一下是否开启了IP白名单
