### ISSUE TITLE
spring boot 3.0.2 集成nacos 

### ISSUE THREAD

**Issue by zhang1995632** [alibaba/nacos#10563]
![image](https://github.com/alibaba/nacos/assets/41946899/64cbf2e0-ddff-498e-b44a-e16a68a75d1c)
![image](https://github.com/alibaba/nacos/assets/41946899/414a97c3-c92f-4f47-a97b-b8b686ec77ee)

报错提示如下:
Caused by: java.lang.ExceptionInInitializerError: Exception java.lang.NoClassDefFoundError: org/apache/http/nio/reactor/IOReactorException [in thread "main"]
	at com.alibaba.nacos.client.config.impl.ConfigHttpClientManager.<clinit>(ConfigHttpClientManager.java:54)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	... 53 more
我都是按照nacos 官方配置 不晓得是哪里的问题

**Comment by zhengke666** [comment]
大哥们nacos支持Springboot3了吗
