### ISSUE TITLE
nacos配置中心超时问题：java.net.ConnectException: no available server, currentServerAddr

### ISSUE THREAD

**Issue by leosandy** [alibaba/nacos#10562]
项目使用 nacos版本为2.0.0，服务与nacos在不同的服务器上，同一内网。
     服务注册与发现的版本为 springcloud alibaba 2.2.5.RELEASE 版本对应的nacos服务注册与发现,服务运行一段时间偶发性报错
现象
> 1.cpu升高至500 ~ 600%左右
> 2.服务503无法访问

nacos version used by the project is 2.0.0, and the service and nacos are on different servers and the same Intranet.
The version of service registration and discovery is the nacos service registration and discovery corresponding to springcloud alibaba 2.2.5.RELEASE. An error may occur occasionally after the service has been running for a period of time
Phenomenon
> 1. The cpu increases to 500 to 600%
> 2. Service 503 cannot be accessed

The specific error information is as follows:
13:16:03.828 [,,,] [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to request
java.net.SocketTimeoutException: null
        at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111) ~[?:1.8.0-292]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0-292]
        at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0-292]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990) ~[?:1.8.0-292]
        at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:112) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:603) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460) [nacos-client-1.4.1.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0-292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0-292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0-292]
13:21:49.587 [,,,] [com.alibaba.nacos.client.Worker.longPolling.fixed-1xxxxxx_8848-229ce7a5-35d2-4010-bb19-e6bbddd4e04c] ERROR com.alibaba.nacos.client.config.http.ServerHttpAgent - [NACOS SocketTimeoutException httpPost] currentServerAddr: http://192.xxx.xxxx60:8848， err : null
13:23:18.173 [,,,] [com.alibaba.nacos.client.Worker.longPolling.fixed-1xxxxxx8848-229ce7a5-35d2-4010-bb19-e6bbddd4e04c] ERROR com.alibaba.nacos.client.config.http.ServerHttpAgent - no available server, currentServerAddr : http://192.xxx.xxxx60:8848
13:23:49.826 [,,,] [com.alibaba.nacos.client.Worker.longPolling.fixed-1xxxxxx_8848-229ce7a5-35d2-4010-bb19-e6bbddd4e04c] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-xxxxx_8848-229ce7a5-35d2-4010-bb19-e6bbddd4e04c] [check-update] get changed dataId exception
java.net.ConnectException: no available server, currentServerAddr : http://192.xxx.xxxx60:8848
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:190) ~[nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:68) ~[nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:441) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:408) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:596) [nacos-client-1.4.1.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0-292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0-292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0-292]
13:26:59.982 [,,,] [com.alibaba.nacos.client.Worker.longPolling.fixed-xxxxx_8848-229ce7a5-35d2-4010-bb19-e6bbddd4e04c] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - longPolling error : 
java.net.ConnectException: no available server, currentServerAddr : http://xxxxxxx:8848
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:190) ~[nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:68) ~[nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:441) ~[nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:408) ~[nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:596) [nacos-client-1.4.1.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0-292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0-292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0-292]
13:25:21.893 [,,,] [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to request
java.net.SocketTimeoutException: null
        at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111) ~[?:1.8.0-292]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0-292]
        at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0-292]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990) ~[?:1.8.0-292]
        at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:112) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:603) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460) [nacos-client-1.4.1.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0-292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0-292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0-292]
13:24:52.483 [,,,] [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to request
java.net.SocketTimeoutException: null
        at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111) ~[?:1.8.0-292]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0-292]
        at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0-292]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:840) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0-292]
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0-292]
        at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getStatusCode(JdkHttpClientResponse.java:75) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:43) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:483) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:603) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460) [nacos-client-1.4.1.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0-292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0-292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0-292]
13:25:12.077 [,,,] [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to request
java.net.SocketTimeoutException: null
        at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111) ~[?:1.8.0-292]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0-292]
        at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0-292]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990) ~[?:1.8.0-292]
        at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:112) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:603) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460) [nacos-client-1.4.1.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0-292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0-292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0-292]
13:23:11.659 [,,,] [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to request
java.net.SocketTimeoutException: null
        at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111) ~[?:1.8.0-292]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0-292]
        at java.net.Socket.connect(Socket.java:607) ~[?:1.8.0-292]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0-292]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056) ~[?:1.8.0-292]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990) ~[?:1.8.0-292]
        at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:112) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427) ~[nacos-common-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:603) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378) [nacos-client-1.4.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460) [nacos-client-1.4.1.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0-292]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0-292]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0-292]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0-292]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0-292]

**Comment by KomachiSion** [comment]
连接超时问题为环境问题，自查网络、负载、GC问题。

从描述上看cpu 500%～600%，应该是负载过高。

**Comment by leosandy** [comment]
> 连接超时问题为环境问题，自查网络、负载、GC问题。
> 
> 从描述上看cpu 500%～600%，应该是负载过高。

出现负载过高，我重启之后负载恢复正常？假如是网络问题，网络恢复后为什么CPU还是居高不下？只有重启才能恢复正常？
