### ISSUE TITLE
springcloud gateway + nacos访问微服务出现invalid version format: UNSUPPORTED！

### ISSUE THREAD

**Issue by sxqem** [alibaba/nacos#10605]
Dubbo version: 3.2.0
springboot 3.0.6
springcloud 2022.0.2
Operating System version: windows 11
Java version: 17
Steps to reproduce this issue
2023-05-07 19:51:18.986 [ERROR] [o.s.b.a.w.r.error.AbstractErrorWebExceptionHandler : 102]
				- [48396b42-2]  500 Server Error for HTTP GET "/api/v1/xxxx"
java.lang.IllegalArgumentException: invalid version format: UNSUPPORTED
	at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:123)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/api/v1/xxxx" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at io.netty.handler.codec.http.HttpVersion.<init>(HttpVersion.java:123)
		at io.netty.handler.codec.http.HttpVersion.valueOf(HttpVersion.java:85)
		at io.netty.handler.codec.http.HttpResponseDecoder.createMessage(HttpResponseDecoder.java:155)
		at io.netty.handler.codec.http.HttpObjectDecoder.decode(HttpObjectDecoder.java:277)
		at io.netty.handler.codec.http.HttpClientCodec$Decoder.decode(HttpClientCodec.java:239)
		at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:529)
		at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:468)
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:290)
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412)
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440)
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420)
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724)
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650)
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562)
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
		at java.base/java.lang.Thread.run(Thread.java:833)
我调试了一下，貌似服务返回的是HTTP2.0,导致netty的HttpVersion验证不通过，HttpVersion只支持到1.1，这个有办法解决吗？还是有什么配置可以处理？而且我还遇到校验时好时坏的情况，有时候连续访问，有时成功，有时失败。

**Comment by YunWZ** [comment]
gateway 默认使用HTTP 1.1 如果要支持HTTP 2.0， 需要开启配置项，具体配置项参考SCG的官方文档吧。记不得了。

**Comment by KomachiSion** [comment]
Not nacos‘ problem

**Comment by Sami116** [comment]
请问问题解决了么
