### ISSUE TITLE
Failed to retry register dubbo consumer

### ISSUE THREAD

**Issue by Python-IBM** [alibaba/nacos#1064]
## Issue Description

Dubbo providers successfully registered with nacos, but consumers failed to register with Nacos.

### Describe what happened (or what feature you want)
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:366) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:175) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:178) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry$2.callback(NacosRegistry.java:148) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:460) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:146) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.support.FailbackRegistry.retry(FailbackRegistry.java:321) [dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.registry.support.FailbackRegistry$1.run(FailbackRegistry.java:74) [dubbo-2.6.5.jar:2.6.5]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_73]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [?:1.8.0_73]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_73]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_73]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_73]

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
1、dubbo v2.6.5
2、nacos v1.0.0
3、windows 7

**Comment by nkorange** [comment]
Check {user.home}/logs/nacos/naming.log for error message.

**Comment by Python-IBM** [comment]
> Check {user.home}/logs/nacos/naming.log for error message.

01 2019-04-15 17:36:44.196 ERROR [main :client.naming] [] [] [CALL-SERVER] failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance. code:500 msg: ErrCode:400,ErrMsg:instance already exist: 192.168.10.4:unknown:DEFAULT_1.0_true_false_DEFAULT
01 2019-04-15 17:36:44.196 ERROR [main :client.naming] [] [] [NA] req api:/nacos/v1/ns/instance failed, server(127.0.0.1:8848
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:333) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:358) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:175) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:178) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry$2.callback(NacosRegistry.java:148) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:460) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:146) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:137) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:303) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:287) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:69) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:106) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:65) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:394) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:333) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:163) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:67) ~[dubbo-2.6.5.jar:2.6.5]

**Comment by Python-IBM** [comment]
> Check {user.home}/logs/nacos/naming.log for error message.
What's the problem?

01 2019-04-15 21:48:05.634 INFO [main :client.naming] [REGISTER-SERVICE] [] [] public registering service consumers:com.sky.demo.service.storage.ITStorageService with instance: {"enabled":true,"ip":"192.168.10.4","metadata":{"side":"consumer","default.lazy":"true","methods":"updateAllColumnBatchById,update,insert,delete,insertOrUpdateAllColumnBatch,deleteBatchIds,insertOrUpdate,deleteByMap,insertOrUpdateBatch,updateBatchById,selectMapsPage,insertAllColumn,selectPage,selectObj,insertOrUpdateAllColumn,selectByMap,selectById,updateById,selectObjs,selectBatchIds,selectOne,selectList,decreaseStorage,deleteById,selectMap,insertBatch,selectCount,updateAllColumnById,selectMaps,updateForSet","default.check":"false","dubbo":"2.0.2","pid":"8176","check":"false","interface":"com.winsky.demo.service.storage.ITStorageService","protocol":"consumer","application":"apiProxyClient","default.client":"netty4","category":"consumers","default.sticky":"true","timestamp":"1555336085613"},"port":0,"valid":true,"weight":1.0}
01 2019-04-15 21:48:05.637 ERROR [main :client.naming] [] [] [CALL-SERVER] failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance. code:500 msg: ErrCode:400,ErrMsg:instance already exist: 192.168.10.4:unknown:DEFAULT_1.0_true_false_DEFAULT
01 2019-04-15 21:48:05.637 ERROR [main :client.naming] [] [] [NA] req api:/nacos/v1/ns/instance failed, server(127.0.0.1:8848
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:333) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:358) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:175) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:178) ~[nacos-client-0.8.0.jar:?]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry$2.callback(NacosRegistry.java:148) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:460) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:146) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:137) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:303) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:287) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:65) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:106) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:69) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:394) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:333) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:163) ~[dubbo-2.6.5.jar:2.6.5]
	at com.alibaba.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:67) ~[dubbo-2.6.5.jar:2.6.5]
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:171) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]

**Comment by nkorange** [comment]
@Python-IBM Is your server version 1.0.0 (Not RC version)?
