### ISSUE TITLE
nacos2.2.3 版本使用内置数据库模式，集群启动报错，提示embeddedDumpService相关异常

### ISSUE THREAD

**Issue by wuhui7324** [alibaba/nacos#10641]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/mnt/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.2.3.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'embeddedDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
errCode: 500, errMsg: java.util.concurrent.CompletionException: com.alibaba.nacos.consistency.exception.ConsistencyException: The Raft Group [nacos_config] did not find the Leader node 
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:423)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)

启动命令sh startup.sh -p embedded
默认不配置数据源，仅修改了cluster.conf 配置文件。
如果是单节点部署，则没有问题，集群模式报错

**Comment by KomachiSion** [comment]
`The Raft Group [nacos_config] did not find the Leader node` 自行查看日志并解决选不出leader的问题。

**Comment by YOUYOUxxx** [comment]
求解

**Comment by wuhui7324** [comment]
> `The Raft Group [nacos_config] did not find the Leader node` 自行查看日志并解决选不出leader的问题。

找不出来，求解

**Comment by KomachiSion** [comment]
那推荐你们考虑使用外置数据库，如MySQL。
既然选择使用内置数据库的集群模式，就需要了解raft并且能够知道如何运维raft集群。至少明确知道是选不出leader的时候能够找到原因并能够尝试解决。

**Comment by boom-amazing** [comment]
解决了吗

**Comment by wuhui7324** [comment]
没有解决



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年8月4日(星期五) 下午3:12
收件人: ***@***.***&gt;; 
抄送: "大 ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] nacos2.2.3 版本使用内置数据库模式，集群启动报错，提示embeddedDumpService相关异常 (Issue #10641)





 
解决了吗

**Comment by xiaoshumiao6** [comment]
我测试了2.1.1 与2.2.3 版本， 全部有这个问题； 内置数据 + 集群模式
