### ISSUE TITLE
nacos 1.4.2 jraft 线程池MpscSingleThreadExecutor队列满的异常

### ISSUE THREAD

**Issue by alexwylp** [alibaba/nacos#10680]
同#10589
nacos 1.4.2，5节点集群。近期nacos.log出现了几次jraft报错（对外、控制台功能都正常），每次都是其中1台，重启后解决，经KomachiSion解答，是“请求过于频繁， 线程池队列满了， 拒绝了新的请求”。
2023-06-01 09:03:01,093 ERROR Exception while executing runnable io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed@58cd151b java.util.concurrent.RejectedExecutionException: null at com.alipay.sofa.jraft.util.concurrent.RejectedExecutionHandlers.lambda$static$0(RejectedExecutionHandlers.java:32) at com.alipay.sofa.jraft.util.concurrent.MpscSingleThreadExecutor.reject(MpscSingleThreadExecutor.java:288) at com.alipay.sofa.jraft.util.concurrent.MpscSingleThreadExecutor.addTask(MpscSingleThreadExecutor.java:215) at com.alipay.sofa.jraft.util.concurrent.MpscSingleThreadExecutor.execute(MpscSingleThreadExecutor.java:140) at com.alipay.sofa.jraft.rpc.impl.GrpcServer.lambda$registerProcessor$2(GrpcServer.java:194) at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172) at 

在此想继续请教一下：
1）这套集群5节点，负载比较低，这个集群间jraft同步操作的功能是？
2）是否是存在路由不均匀的情况？导致某一台的队列生产速度>>消费速度？
3）这个MpscSingleThreadExecutor的默认队列大小是否是30000多？如果生产速度>>消费速度，那在队列未满，RejectedExecutionHandlers不报错的时候，队列已出现阻塞（消费速度慢），同步操作的时效性已经受影响了？所以说将队列初始大小调大也是治标不治本？
4）是否可以通过参数调大消费的线程数量？但是看名字是MpscSingleThreadExecutor，不知是否可行？
5）有没有比较好的工具推荐，可以监控和观测这个MpscSingleThreadExecutor的任务生产者动作？

万分感谢！

**Comment by KomachiSion** [comment]
1. 如果没有使用derby数据库的集群模式， 那么只有修改服务/实例元数据，持久化服务会使用jraft
2. 每个raft group是一个leader，如果频繁写会导致leader负载高
3. 默认大小正常使用是足够的，消费速度理论上并不慢，状态机写入都是内存写入，出现阻塞应该是其他原因，我这边无法复现，需要更多信息。
4. 5. 可以到Jraft社区询问一下。

**Comment by alexwylp** [comment]
好的，谢谢。貌似找到原因了，apm监控工具有冲突。
