### ISSUE TITLE
The IPv4 address("nacos-cs.nacos") is incorrect.

### ISSUE THREAD

**Issue by hdpingshao** [alibaba/nacos#10690]
## Issue Description
我们使用阿里云k8s部署的nacos，中间有一段时间连续9次出现java.lang.IllegalArgumentException: The IPv4 address("nacos-cs.nacos") is incorrect.的报错信息，随后恢复正常后客户端未重新注册上来，了解下是什么原因导致的，并且咨询下这个报错是什么原因导致的呢？
完整错误日志：
2023-06-23 13:48:00,397 [WARN] [] [] [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming [HostReactor.java : 484] [NA] failed to update serviceName: DEFAULT_GROUP@@market
java.lang.IllegalArgumentException: The IPv4 address("nacos-cs.nacos") is incorrect.
	at com.alibaba.nacos.common.utils.IPUtil.splitIPPortStr(IPUtil.java:152)
	at com.alibaba.nacos.common.utils.IPUtil.containsPort(IPUtil.java:119)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:595)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

### Tell us your environment
1、使用的是三节点的集群模式部署的
2、nacos版本是2.1.0的
3、nacos-client的版本是1.4.1

**Comment by KomachiSion** [comment]
Please upgrade the client version, 1.4.1 will try to call DNS to parse the domain, if can't parsed, will throw exception, has been fixed.

**Comment by hdpingshao** [comment]
请问下是在哪个版本解决了呢？需要升级到哪个版本？

**Comment by hdpingshao** [comment]
请问下是在哪个版本解决了呢？需要升级到哪个版本？而且我看这个时间点过后解析是恢复正常了，但是为什么不会自动重新注册到nacos呢？

**Comment by PRANRAVEE** [comment]
ส่งจากโทรศัพท์มือถือ Huawei ของฉ-------- ข้อความต้นฉบับ --------จาก: hdpingshao ***@***.***>วันที่: จ. 26 มิ.ย. 2023 09:51ถึง: alibaba/nacos ***@***.***>สำเนา: Subscribed ***@***.***>เรื่อง: Re: [alibaba/nacos] The IPv4 address("nacos-cs.nacos") is incorrect. (Issue #10690)
请问下是在哪个版本解决了呢？需要升级到哪个版本？而且我看这个时间点过后解析是恢复正常了，但是为什么不会自动重新注册到nacos呢？

**Comment by KomachiSion** [comment]
1.4.2 以上即可

**Comment by KomachiSion** [comment]
duplicate with https://github.com/alibaba/nacos/issues/5291
