### ISSUE TITLE
failed to req API:http://127.0.0.1:8848/nacos/v1/ns/api/srvIPXT. code:404 msg: service not found

### ISSUE THREAD

**Issue by gavinChen123** [alibaba/nacos#1076]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
`20190418 15:21:44.766 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [] [] [CALL-SERVER] failed to req API:http://127.0.0.1:8848/nacos/v1/ns/api/srvIPXT. code:404 msg: service not found: DEFAULT_GROUP@@127.0.0.1
20190418 15:21:44.767 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [] [] [NA] req api:/nacos/v1/ns/api/srvIPXT failed, server(127.0.0.1:8848
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:327)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
20190418 15:21:44.767 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [] [] [NA] failed to update serviceName: 127.0.0.1
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([127.0.0.1:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)``

### Describe what you expected to happen
I wish has no exception

### How to reproduce it (as minimally and precisely as possible)

1. start the app
2. access to any controller, it will be print the exception repeatedly

### Tell us your environment
spring boot: 2.0.7.RELEASE
spring cloud: Finchley.SR2
spring-cloud-alibaba: 0.2.1.RELEASE
zipkin server: zipkin-server-2.12.8-exec.jar
nacos : nacos-server-1.0.0

**Comment by gavinChen123** [comment]
I see in #1000, and set the properties 
spring:
  zipkin:
    discovery-client-enabled: false

but no effect .

![image](https://user-images.githubusercontent.com/42809948/56347165-4fca0700-61f6-11e9-9eed-456d3846e1f8.png)

**Comment by kukukikits** [comment]
According to this message : code:404 msg: 'service not found: DEFAULT_GROUP@@127.0.0.1',
that means your Nacos server doesn't have a service named 127.0.0.1.
So try to manually create a service named "127.0.0.1" on your Nacos dashboard to work around this issue.

**Comment by gavinChen123** [comment]
I create a service named "127.0.0.1" on my Nacos dashboard to resolve it.
![image](https://user-images.githubusercontent.com/42809948/56400062-4d15f300-6284-11e9-87b0-7fc52b26e36b.png)
but I don't think this is a qualified solution.

**Comment by gstripe** [comment]
从服务列表将服务删除掉，所有客户端不应该抛出failed to update serviceName的异常。
只需要默默的从本地服务列表清除就好了吧。
