### ISSUE TITLE
Nacos local cluster

### ISSUE THREAD

**Issue by 15034549446** [alibaba/nacos#10803]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalStoragePersistServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:413)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1761)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:595)
	... 146 common frames omitted
Caused by: java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
	at com.alibaba.nacos.config.server.service.datasource.DynamicDataSource.getDataSource(DynamicDataSource.java:60)
	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.init(ExternalStoragePersistServiceImpl.java:133)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 158 common frames omitted
Caused by: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
	at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl.init(ExternalDataSourceServiceImpl.java:109)
	at com.alibaba.nacos.config.server.service.datasource.DynamicDataSource.getDataSource(DynamicDataSource.java:55)
	... 166 common frames omitted
2023-07-16 17:58:32,489 WARN [WatchFileCenter] start close

2023-07-16 17:58:32,490 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /Users/a/Downloads/MAC/nacos/localhostNacos/nacos/conf

2023-07-16 17:58:32,490 WARN [WatchFileCenter] already closed

2023-07-16 17:58:32,490 WARN [NotifyCenter] Start destroying Publisher

2023-07-16 17:58:32,490 WARN [NotifyCenter] Destruction of the end

2023-07-16 17:58:32,490 ERROR Nacos failed to start, please see /Users/a/Downloads/MAC/nacos/localhostNacos/nacos/logs/nacos.log for more details.

2023-07-16 18:15:56,689 WARN [ThreadPoolManager] Start destroying ThreadPool

2023-07-16 18:15:56,690 WARN [ThreadPoolManager] Destruction of the end

Console：sh startup.sh 
/Library/Java/JavaVirtualMachines/jdk11.0.8.jdk/Contents/Home/bin/java  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/Users/a/Downloads/MAC/nacos/localhostNacos/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.member.list= -Xlog:gc*:file=/Users/a/Downloads/MAC/nacos/localhostNacos/nacos/logs/nacos_gc.log:time,tags:filecount=10,filesize=102400 -Dloader.path=/Users/a/Downloads/MAC/nacos/localhostNacos/nacos/plugins/health,/Users/a/Downloads/MAC/nacos/localhostNacos/nacos/plugins/cmdb -Dnacos.home=/Users/a/Downloads/MAC/nacos/localhostNacos/nacos -jar /Users/a/Downloads/MAC/nacos/localhostNacos/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/Users/a/Downloads/MAC/nacos/localhostNacos/nacos/conf/ --logging.config=/Users/a/Downloads/MAC/nacos/localhostNacos/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
nacos is starting with cluster
nacos is starting，you can check the /Users/a/Downloads/MAC/nacos/localhostNacos/nacos/logs/start.out

**Comment by KomachiSion** [comment]
`[db-load-error]load jdbc.properties error` please see other logs to find out the load failed reason.

**Comment by 15034549446** [comment]
The problem has been solved, so the detailed process will not be sent. Some of the problems that appear after configuring the database information can be found on the Internet for solutions to problems related to ‘No DataSource set’.

**Comment by KomachiSion** [comment]
> The problem has been solved, so the detailed process will not be sent. Some of the problems that appear after configuring the database information can be found on the Internet for solutions to problems related to ‘No DataSource set’.

The problem has discuss in other issues, please search all issues and join discussion.
