### ISSUE TITLE
Failed to bind properties under 'db.pool.config' to com.zaxxer.hikari.HikariDataSource

### ISSUE THREAD

**Issue by HuangRenhui** [alibaba/nacos#10833]
i upgrade version 2.2.0 of nacos-server,also i add db.pool.config.driverClassName=dm.jdbc.driver.DmDriver in application.properties or JAVA_OPT="${JAVA_OPT} -Ddb.pool.config.driverClassName=dm.jdbc.driver.DmDriver" in startup.sh，but not valid.
how to solve question:
Caused by: org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'db.pool.config' to com.zaxxer.hikari.HikariDataSource
at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:384)
at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:344)
at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:329)
at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:259)
at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:220)
at com.alibaba.nacos.config.server.service.datasource.DataSourcePoolProperties.build(DataSourcePoolProperties.java:64)
at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceProperties.build(ExternalDataSourceProperties.java:81)
at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl.reload(ExternalDataSourceServiceImpl.java:134)
... 77 common frames omitted
Caused by: java.lang.IllegalStateException: Unable to set value for property driver-class-name

**Comment by wuchubuzai2018** [comment]
不建议在JVM启动参数上配置，还是在默认的application.properties文件里面配置比较好

**Comment by HuangRenhui** [comment]
> 不建议在JVM启动参数上配置，还是在默认的application.properties文件里面配置比较好

my question is add db.pool.config.driverClassName=dm.jdbc.driver.DmDriver in application.properties ,but not valid.
