### ISSUE TITLE
使用内置数据启动部署的集群，机器cpu很高时70%这样，集群节点直接一直报错超时日志

### ISSUE THREAD

**Issue by mrhjx2** [alibaba/nacos#10830]
五个节点组成的集群
每个节点16C32G的linux

2023-07-20 20:04:03,445 WARN Exception while request: http://xxx.xx.xx.xx:18848/nacos/v1/ns/instance/beat, caused: {}

java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.SessionInputBufferImpl.streamRead(SessionInputBufferImpl.java:137)
        at org.apache.http.impl.io.SessionInputBufferImpl.fillBuffer(SessionInputBufferImpl.java:153)
        at org.apache.http.impl.io.SessionInputBufferImpl.readLine(SessionInputBufferImpl.java:280)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:138)
        at org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
        at org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
        at org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
        at org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
        at org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
        at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)
        at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:272)
        at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)

**Comment by wilsonwu** [comment]
JVM的内存设置是多少？

**Comment by KomachiSion** [comment]
cpu很高有可能是因为jvm参数设置过小，导致经常GC， 也可能是请求量太大，把负载打高了。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
