### ISSUE TITLE
数据库比nacos启动晚一点，可能超出30s，nacos容器就挂了，报连接不上数据库，应该可以改成无限重连，或者给个重连次数的吧。

### ISSUE THREAD

**Issue by baiguoz** [alibaba/nacos#10840]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.2.0.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)

修改数据库连接url的connectTimeout=1800000&socketTimeout=1800000都不行
修改db.pool.config.connectionTimeout=1800000也不行

**Comment by dyrnq** [comment]
我也遇到一样的问题

**Comment by wilsonwu** [comment]
是不是和这个问题类似：https://github.com/alibaba/nacos/issues/10294

**Comment by baiguoz** [comment]
是的，就是这个问题，最起码服务不能挂，可以一直重试

**Comment by KomachiSion** [comment]
启动完成的nacos在数据库挂掉后，会采取无限重试的方式。因为此时集群有历史数据库， 是可读的。

如果启动完成前数据库挂掉，是不可行的：
1. 如果放任跳过，异步重试，会导致服务端数据缺失，最终导致了业务测获取到空数据，直接导致故障。
2. 如果不跳过，采取无限重试，那一方面排查起来费劲，到时候你的问题就是 `连不上数据库，一直在starting`，所以不如直接给出数据库不可用的明显错误后退出；另外容器化之后，liveness也会让无限重试机制失效。
3. 如果是新环境，状态不正确快速退出也没有问题；如果是旧环境，一直无限重试也会可能导致客户端处于查询/连接超时状态。而和两个状态往往有很多可能性，不如直接停止掉，客户端如果连接到这个ip， `connection refused`可以明确的知道是端口为监听（大概率是程序未正确启动）。

综上，我认为现在的这个机制没有太大必要修改。

**Comment by tm2018** [comment]
> 启动完成的nacos在数据库挂掉后，会采取无限重试的方式。因为此时集群有历史数据库， 是可读的。
> 
> 如果启动完成前数据库挂掉，是不可行的：
> 
> 1. 如果放任跳过，异步重试，会导致服务端数据缺失，最终导致了业务测获取到空数据，直接导致故障。
> 2. 如果不跳过，采取无限重试，那一方面排查起来费劲，到时候你的问题就是 `连不上数据库，一直在starting`，所以不如直接给出数据库不可用的明显错误后退出；另外容器化之后，liveness也会让无限重试机制失效。
> 3. 如果是新环境，状态不正确快速退出也没有问题；如果是旧环境，一直无限重试也会可能导致客户端处于查询/连接超时状态。而和两个状态往往有很多可能性，不如直接停止掉，客户端如果连接到这个ip， `connection refused`可以明确的知道是端口为监听（大概率是程序未正确启动）。
> 
> 综上，我认为现在的这个机制没有太大必要修改。

是否可以加个参数控制？默认不自动重试，有需求的使用者自己开启重试机制。从系统管理员的角度来讲，一套系统重启后系统无法自行恢复，是不正常的，而nacos正好是这其中的风险之一。

**Comment by tm2018** [comment]
> 启动完成的nacos在数据库挂掉后，会采取无限重试的方式。因为此时集群有历史数据库， 是可读的。
> 
> 如果启动完成前数据库挂掉，是不可行的：
> 
> 1. 如果放任跳过，异步重试，会导致服务端数据缺失，最终导致了业务测获取到空数据，直接导致故障。
> 2. 如果不跳过，采取无限重试，那一方面排查起来费劲，到时候你的问题就是 `连不上数据库，一直在starting`，所以不如直接给出数据库不可用的明显错误后退出；另外容器化之后，liveness也会让无限重试机制失效。
> 3. 如果是新环境，状态不正确快速退出也没有问题；如果是旧环境，一直无限重试也会可能导致客户端处于查询/连接超时状态。而和两个状态往往有很多可能性，不如直接停止掉，客户端如果连接到这个ip， `connection refused`可以明确的知道是端口为监听（大概率是程序未正确启动）。
> 
> 综上，我认为现在的这个机制没有太大必要修改。

是否可以加个参数控制？默认不自动重试，有需求的使用者自己开启重试机制。从系统管理员的角度来讲，一套系统重启后系统无法自行恢复，是不正常的，而nacos正好是这其中的风险之一。
