### ISSUE TITLE
nacos 2.0.3 在控制台更新配置文件内容，然后点击发布，进程异常退出

### ISSUE THREAD

**Issue by mulihong** [alibaba/nacos#10853]
问题描述:  
 - nacos 2.0.3 在控制台更新配置文件内容，然后点击发布，进程异常退出。两外两个节点连不上异常退出的节点，进程也异常停止，导致整个集群故障不可用

环境信息
 - CentOS Linux release 7.6.1810 (Core)
 - 3.10.0-1160.6.1.el7.x86_64
 - nacos server version: 2.0.3
 - nacos client version: nacos-client-2.0.3
 
异常退出节点日志nacos.log
2023-07-24 20:11:37,944 INFO [capacityManagement] end correct usage, cost: 0s
2023-07-24 20:21:37,934 WARN clearConfigHistory start
2023-07-24 20:21:37,944 INFO [capacityManagement] start correct usage
2023-07-24 20:21:37,945 INFO [capacityManagement] end correct usage, cost: 0s
2023-07-24 20:25:55,127 WARN [HttpClientBeanHolder] Start destroying common HttpClient
2023-07-24 20:25:55,129 WARN [ConfigServer-HttpClientManager] Start destroying NacosRestTemplate
2023-07-24 20:25:55,124 WARN [NotifyCenter] Start destroying Publisher
2023-07-24 20:25:55,129 WARN [ThreadPoolManager] Start destroying ThreadPool
2023-07-24 20:25:55,173 WARN [WatchFileCenter] start close
2023-07-24 20:25:55,173 WARN [NotifyCenter] Destruction of the end
2023-07-24 20:25:55,174 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /app/nacos-2.0.3-02/data/tps
2023-07-24 20:25:55,174 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /app/nacos-2.0.3-02/data/loader
2023-07-24 20:25:55,177 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /app/nacos-2.0.3-02/conf
2023-07-24 20:25:55,180 WARN [WatchFileCenter] already closed
2023-07-24 20:25:55,197 WARN [ConfigServer-HttpClientManager] Destruction of the end
2023-07-24 20:25:55,202 WARN [HttpClientBeanHolder] Destruction of the end
2023-07-24 20:25:55,246 INFO Shutting down ExecutorService 'taskScheduler'
2023-07-24 20:25:55,252 INFO Shutting down ExecutorService 'applicationTaskExecutor'
2023-07-24 20:25:57,962 WARN [ThreadPoolManager] Destruction of the end

remote.log 日志
2023-07-24 20:25:55,123 INFO Nacos GrpcClusterServer Rpc server stopping
2023-07-24 20:25:55,123 INFO Nacos GrpcSdkServer Rpc server stopping
2023-07-24 20:25:55,195 INFO Nacos GrpcClusterServer Rpc server stopped successfully...
2023-07-24 20:25:55,196 INFO Nacos GrpcSdkServer Rpc server stopped successfully...

naming-server.log 日志
2023-07-24 20:25:55,173 WARN [NamingServerHttpClientManager] Start destroying HTTP-Client
2023-07-24 20:25:55,204 WARN [NamingServerHttpClientManager] Destruction of the end
2023-07-24 20:25:55,210 INFO Client connection 1681746005753_10.xxx.xxx.xx1_34440 disconnect, remove instances and subscribers
2023-07-24 20:25:55,210 INFO Client connection 1689259829448_10.xxx.1xx.xx_22971 disconnect, remove instances and subscribers

naming-distro.log 日志
2023-07-24 20:25:57,380 ERROR [NACOS-DISTRO] Error while handling notifying task
java.lang.InterruptedException: null
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
        at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
        at java.util.concurrent.ArrayBlockingQueue.take(ArrayBlockingQueue.java:403)
        at com.alibaba.nacos.naming.consistency.ephemeral.distro.DistroConsistencyServiceImpl$Notifier.run(DistroConsistencyServiceImpl.java:412)
另外节点日志:
2023-07-24 20:20:43,263 INFO [capacityManagement] end correct usage, cost: 0s
2023-07-24 20:25:55,212 ERROR [1681746005753_10.xxx.xx8.xx1_34440]Request stream error, switch server,error={}
io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
        at io.grpc.Status.asRuntimeException(Status.java:533)
        at io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:442)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700)
        at io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39)
        at io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23)
        at io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40)
        at io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2023-07-24 20:25:55,214 INFO [Cluster-10.xxx.xx8.xx0:8848] try to re connect to a new server ,server is  not appointed,will choose a random server.
2023-07-24 20:25:55,241 ERROR Server check fail, please check server 10.xxx.xx8.xx0 ,port 9849 is available , error ={}
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

**Comment by KomachiSion** [comment]
看日志没有发现退出原因， 你看下磁盘是不是满了，导致在发布配置的时候触发了保护机制，进程自杀了。

**Comment by mulihong** [comment]
磁盘空间未满，系统日志也没有kill。并且其中一个节点退出后，过两分钟另外两个节点进程也没有了。

**Comment by mulihong** [comment]
> 看日志没有发现退出原因， 你看下磁盘是不是满了，导致在发布配置的时候触发了保护机制，进程自杀了。

磁盘空间未满，系统日志也没有kill。并且其中一个节点退出后，过两分钟另外两个节点进程也没有了。

**Comment by mulihong** [comment]
最终排查发现有脚本在停止java程序时，把nacos进程kill
