### ISSUE TITLE
gateway服务cpu百分百，nacos-server版本2.2.1是否有问题

### ISSUE THREAD

**Issue by xiaoyuwang1987** [alibaba/nacos#10865]
gateway服务cpu一直很高，通过jstack一下 发现有两个线程一直在占用cpu资源

"XNIO-2 I/O-1" #47 prio=5 os_prio=0 cpu=2323887679.25ms elapsed=4872583.83s tid=0x00007f221a3ce5f0 nid=0x67 runnable  [0x00007f21c85fb000]
   java.lang.Thread.State: RUNNABLE
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:285)
        at io.undertow.channels.DetachableStreamSinkChannel$SetterDelegatingListener.handleEvent(DetachableStreamSinkChannel.java:272)
        at org.xnio.ChannelListeners.invokeChannelListener(ChannelListeners.java:92)
        at org.xnio.conduits.WriteReadyHandler$ChannelListenerHandler.writeReady(WriteReadyHandler.java:65)
        at org.xnio.nio.NioSocketConduit.handleReady(NioSocketConduit.java:94)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:591)

"XNIO-2 I/O-2" #48 prio=5 os_prio=0 cpu=2383115631.81ms elapsed=4872583.83s tid=0x00007f2219e2d660 nid=0x68 runnable  [0x00007f21c84fa000]
   java.lang.Thread.State: RUNNABLE
        at java.util.HashMap.putVal(java.base@17.0.5/HashMap.java:629)
        at java.util.HashMap.put(java.base@17.0.5/HashMap.java:610)
        at java.util.HashSet.add(java.base@17.0.5/HashSet.java:221)
        at sun.nio.ch.SelectorImpl.processReadyEvents(java.base@17.0.5/SelectorImpl.java:307)
        at sun.nio.ch.EPollSelectorImpl.processEvents(java.base@17.0.5/EPollSelectorImpl.java:195)
        at sun.nio.ch.EPollSelectorImpl.doSelect(java.base@17.0.5/EPollSelectorImpl.java:135)
        at sun.nio.ch.SelectorImpl.lockAndDoSelect(java.base@17.0.5/SelectorImpl.java:129)
        - locked <0x00000000d6918510> (a sun.nio.ch.Util$2)
        - locked <0x00000000d69184c0> (a sun.nio.ch.EPollSelectorImpl)
        at sun.nio.ch.SelectorImpl.select(java.base@17.0.5/SelectorImpl.java:141)
        at org.xnio.nio.WorkerThread.run(WorkerThread.java:551)

![0c605a79c48dcc6fb08d12198aca626b](https://github.com/alibaba/nacos/assets/24749103/8d671dad-f5fc-471d-a08a-3501ed69d0cb)

**Comment by DarrenLuo** [comment]
这里看出来的是 undertow 的线程占用高，但是 nacos 中并没有使用 undertow

**Comment by KomachiSion** [comment]
您的gateway占用cpu满，和nacos无关，请自查或提交到gateway对应的社区。

**Comment by xiaoyuwang1987** [comment]
> 这里看出来的是 undertow 的线程占用高，但是 nacos 中并没有使用 undertow

后面我也看出来是undertow问题，我先升级一下版本感觉应该跟大版本兼容不稳定有关系
