### ISSUE TITLE
nacos 2.2.3 使用内置数据源 启动集群 报空指针

### ISSUE THREAD

**Issue by ccccaoqing** [alibaba/nacos#10913]
2023-08-04 14:29:24,255 ERROR CONSOLE /nacos/v1/cs/configs
.com.alibaba.nacos.api.exception.runtime.NacosRuntimeException:errCode:500,errMsg:java.Lang.NullPointerException
at com.alibaba.nacos.config.server.service.repository_embedded.DistributedDatabase0perateImpl.queryOne(DistributedDatabaseOperateImpl.java:286)
at com.alibaba.nacos.config.server.service.repository.embedded.EmbeddedConfigInfoPersistServiceImpl.findConfiginfo(EmbeddedConfigInfoPersistServiceImpl.java:668)
latcom.alibaba.nacos.config.server.service.repository.embedded_EmbeddedConfigInfoPersistServiceImpl.insertorUpdate(EmbeddedConfigInfoPersistServiceImpl.java:207)
at com.alibaba.nacos. config. server. service. ConfigoperationService.publishConfig(ConfigOperationService.java:97)
at com.alibaba. nacos. config. server controller. ConfigController_publishConfig(ConfigControllen.java:198)
at com.alibaba.nacos.config.server_controller_ConfigController$$FastCLassBySpringCGLIB$$dbb89c58.invoke(<generated>)
atorg.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
latorg.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CgLibAopProxy.java:795)
atorg.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.ñava:163)
a org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
a org.springframework.aop.aspectj.MethodInvocationProceedinqJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:89)
at com.alibaba.nacos.config_server.aspect.RequestLogAspect.LogCLientReguest(RequestLogAspect.java:194)
at com.alibaba. nacos. config. server. aspect. RequestLogAspect.interfacePublishSingle(RequestLogAspect.java:131)
at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethod)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun. reflect. DelegatingMethodAccessorImpl. invoke(DelegatingMethodAccessorImpl.java:43)
at java -Lang -neflect Method invoke (Hethod nava: 498)
at org-spningtpamewons.aop -aspec t - AbstractAspectJAdvice invokeAdvi cewe thodvithGivenArgs CADstrac tAspectbAavace Tavaa Gs4)
at ong:spningframewonkuaop raspecti -AbstractAspec tJAavice anvokeAdvicenetnod cAbstnact Aspect JAdviceuFava:o24)
at org-springframework. aop-aspectj.AspectjAroundAdvice.invoke(AspectjAnoundAdvice.java:72)
atorg.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.iava:175)
at org-springfnamework. aop. framework_CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.nava:763)
at org.springfnamework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeinvocationInterceptor.ava:97)
at org.springframework.aop.framework.ReflectiveMethodInvocation_proceed(RefLectiveMethodinvocation.java:186)
at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CgibAopProxy.Tava:763)
Structure
at org-spningtname wonk -aop -Thamewonk cghiDAOpPnoxy$DynamacAavi sedIntencep ton u intercept (CaL2DAOpRnaxyu iava:zoe)
at com.alibaba.nacos.config.server.controller.ConfigControllerSsEnhancerByspringCLIBSS79a85356.publishConfig(<generated»)
at sun. reflect. NativeMethodAccessorImpl. invoke0(Native Method)
at sun. reflect. NativeMethodAccessor[mpl.invoke (NativeMethodAccessorImpl. Java:02)
at sun. reflect. DelegatingMethodAccessorImpl. invoke (DelegatingMethodAccessorImpl.Java: 45)
at java. Lang. reflect. Method. invoke (Method. java: 498)
at org.springfnamework.web.method.support.InvocableHandlerMethod.doInvoke(InvocapleHandlerMethod.java-205)
*
at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocabLeHandLerMethod.java:150)

**Comment by Daydreamer-ia** [comment]
Please upgrade the version of nacos-server. Refer to https://github.com/alibaba/nacos/issues/10657
