### ISSUE TITLE
ErrCode:-401, ErrMsg:Client not connected, current status:UNHEALTHY

### ISSUE THREAD

**Issue by hell0w0orld** [alibaba/nacos#10916]
**Describe the bug**
Caused by: ErrCode:-401, ErrMsg:Client not connected, current status:UNHEALTHY
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:651)
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:631)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:278)

nacos服务端版本2.1.1，客户端版本2.1.0；9848，9849端口已经开启；服务有时候能注册到nacos上，有时候会连不上nacos

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Ubuntu]
 - Version [e.g. nacos-server 2.1.1, nacos-client 2.1.0]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
连接不健康， 请自查环境问题：
1. 服务端负载，网络情况
2. 服务端和客户端之间的网络情况（包括负载均衡，vpn，转发器等等所有网络中间节点）
3. 客户端自身负载，运行状态，网络情况。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
