### ISSUE TITLE
nacos集群化部署grpc.StatusRuntimeException: UNAVAILABLE: io exception

### ISSUE THREAD

**Issue by ljh205sy** [alibaba/nacos#11002]
在nacos集群化部署中， 
在web页面显示的是集群状态是up的状态，在后端的nacos的log日志打印protocol-raft.log 的日志报错，显示日志如下：

java.lang.IllegalStateException: Fail to get leader of group naming_service_metadata, Unknown leader, Unknown leader, Unknown leader
        at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:605)
        at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:498)
        at com.alibaba.nacos.core.distributed.raft.JRaftServer.registerSelfToCluster(JRaftServer.java:353)
        at com.alibaba.nacos.core.distributed.raft.JRaftServer.lambda$createMultiRaftGroup$0(JRaftServer.java:264)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
2023-08-22 11:30:15,060 INFO This Raft event changes : RaftEvent{groupId='naming_service_metadata', leader='192.168.19.27:27848', term=257, raftClusterInfo=[192.168.19.27:27848, 192.168.19.28:27848, 192.168.19.31:27848]}

在nacos-client端显示的是无法连接，这个如何去处理？   nacos-client  2.2.4   ， nacos-server  2.2.3
在删除nacos/data的目录， 重启nacos之后，正常一段时间后，过一会又出现了上面的选举失败的问题。 

![image](https://github.com/alibaba/nacos/assets/25653599/b9cb42f8-7f26-492d-96b9-c42230ee3105)

![image](https://github.com/alibaba/nacos/assets/25653599/a85281d6-bff7-4d97-8c19-16e5ce200c04)

![image](https://github.com/alibaba/nacos/assets/25653599/d456b8b9-d6e0-4fb4-805b-a61a416b2b6b)

![image](https://github.com/alibaba/nacos/assets/25653599/440967c3-b60d-4d4a-bfb5-5e860146544e)

2023-08-22 09:25:02.217 [nacos-grpc-client-executor-192.168.19.31-28] ERROR c.a.nacos.common.remote.client.grpc.GrpcClient - [1692667447458_192.168.19.30_49248]Request stream error, switch server,error={}
com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: CANCELLED: RST_STREAM closed stream. HTTP/2 error code: CANCEL
        at com.alibaba.nacos.shaded.io.grpc.Status.asRuntimeException(Status.java:539)
        at com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
        at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
        at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
        at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
        at com.alibaba.nacos.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at com.alibaba.nacos.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
2023-08-22 09:25:02.215 [nacos-grpc-client-executor-192.168.19.31-34] ERROR c.a.nacos.common.remote.client.grpc.GrpcClient - [1692667436459_192.168.19.30_48922]Request stream error, switch server,error={}
com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: CANCELLED: RST_STREAM closed stream. HTTP/2 error code: CANCEL
        at com.alibaba.nacos.shaded.io.grpc.Status.asRuntimeException(Status.java:539)
        at com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:487)
        at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563)
        at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70)
        at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744)
        at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723)
        at com.alibaba.nacos.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at com.alibaba.nacos.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
2023-08-22 09:25:02.386 [nacos.client.config.listener.task-0] ERROR com.alibaba.nacos.common.remote.client - Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY5MjY4NTQzNX0.v3f1Q__wjTSXZxx5CQssg6oEXAlMYCTpkBADH-FyFOw, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=53f9b1779b6e24fd23941cd67585c059, Client-RequestTS=1692667502356, exConfigInfo=true}, requestId='null'}, retryTimes = 0, errorMessage = java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
2023-08-22 09:25:02.387 [nacos.client.config.listener.task-0] ERROR com.alibaba.nacos.common.remote.client - Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY5MjY4NTQzNX0.v3f1Q__wjTSXZxx5CQssg6oEXAlMYCTpkBADH-FyFOw, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=53f9b1779b6e24fd23941cd67585c059, Client-RequestTS=1692667502356, exConfigInfo=true}, requestId='null'}, retryTimes = 1, errorMessage = java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: io exception

**[root@localhost logs]# cat alipay-jraft.log**
----
2023-08-22 16:55:18,470 INFO Save raft meta, path=/u01/opt/bigdata/nacos/data/protocol/raft/naming_instance_metadata/meta-data, term=276, votedFor=0.0.0.0:0, cost time=8 ms

2023-08-22 16:55:18,482 INFO Save raft meta, path=/u01/opt/bigdata/nacos/data/protocol/raft/naming_instance_metadata/meta-data, term=276, votedFor=192.168.19.27:27848, cost time=12 ms

2023-08-22 16:55:18,637 INFO Node <naming_service_metadata/192.168.19.28:27848> received PreVoteRequest from 192.168.19.27:27848, term=270, currTerm=269, granted=true, requestLastLogId=LogId [index=263, term=269], lastLogId=LogId [index=263, term=269].

2023-08-22 16:55:18,640 INFO Node <naming_service_metadata/192.168.19.28:27848> received RequestVoteRequest from 192.168.19.27:27848, term=270, currTerm=269.

2023-08-22 16:55:18,643 INFO Save raft meta, path=/u01/opt/bigdata/nacos/data/protocol/raft/naming_service_metadata/meta-data, term=270, votedFor=0.0.0.0:0, cost time=3 ms

2023-08-22 16:55:18,645 INFO Save raft meta, path=/u01/opt/bigdata/nacos/data/protocol/raft/naming_service_metadata/meta-data, term=270, votedFor=192.168.19.27:27848, cost time=2 ms

**Comment by ljh205sy** [comment]
nacos的客户端直接连接的 三台nacos的地址，， 之前是正常，过一段时间后就会出现这个异常。 

Caused by: com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: 拒绝连接: /192.168.19.28:29848
Caused by: java.net.ConnectException: 拒绝连接
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:715)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.doFinishConnect(NioSocketChannel.java:337)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.finishConnect(AbstractNioChannel.java:334)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:710)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
2023-08-22 09:25:02.671 [nacos.client.config.listener.task-0] ERROR com.alibaba.nacos.common.remote.client - Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY5MjY4NTQzNX0.v3f1Q__wjTSXZxx5CQssg6oEXAlMYCTpkBADH-FyFOw, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=cacaff4ae95be9b00a57f5bc9d3f031d, Client-RequestTS=1692667502441, exConfigInfo=true}, requestId='null'}, retryTimes = 0, errorMessage = Client not connected, current status:UNHEALTHY
2023-08-22 09:25:02.771 [nacos.client.config.listener.task-0] ERROR com.alibaba.nacos.common.remote.client - Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY5MjY4NTQzNX0.v3f1Q__wjTSXZxx5CQssg6oEXAlMYCTpkBADH-FyFOw, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=cacaff4ae95be9b00a57f5bc9d3f031d, Client-RequestTS=1692667502441, exConfigInfo=true}, requestId='null'}, retryTimes = 1, errorMessage = Client not connected, current status:UNHEALTHY

**Comment by KomachiSion** [comment]
拒绝连接了，说明网络有问题或者端口未监听，环境问题自查

**Comment by ljh205sy** [comment]
> 

环境从哪方便去自查？ 能发散一下吗？

**Comment by KomachiSion** [comment]
拒绝连接一般就3种情况：
1. 程序未启动或启动未完成，还未监听对应端口， 此时系统会直接拒绝tcp连接。
2. 有slb或vip等代理层， 关联或挂载了错误的端口，因为找不到后端RS，直接拒绝连接。
3. 发起方的网络有问题，在发出请求是，本地操作系统直接拒绝了向外发起的tcp连接。

无论哪种都是环境本身问题。 和nacos无关。
