### ISSUE TITLE
2.2.3 国产服务器银河麒麟专用机启动问题，无法从共享目标中映射段

### ISSUE THREAD

**Issue by sunxiaobo821** [alibaba/nacos#11016]
oro.sprinoframework.beansfactory.UnsatisfiedDependencyException: Error creating bean with nameusr/local/latfor/nacos/taret/aos-Serer-iar! /-NE/baos-amim- -3.ar/cn/alibaba/acos/naino/core/instaceperatorclientimpl.classUnsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframeworkbeans.factoryUnsatisfiedDependencyException:defined in URL [[jar:file:/usr/local/platform/nacos/target/nacos-server.jar!/B00T-INF/lib/Error] creating bean with  name'clientoperationserviceProxy'nacos-naning-2.2.3jar!/co/alibaba/ncos/naning/core/v2/service/clientoperationserviceProxy.class): Unsatisfied dependency expressed through constructorarameter 1; nested exception is org.springframework.beans.factoryBeanCreationException:Error creatina bean with name"persistentlientoperationervicelmpl’defined in UR. [jar:file:/usr/local/platforn/nacos/target/nacos-server.jar!/30-INF/Lib/nacos-naning-2.2.3.jar!/on/alibaba/nacos naming/core v2/serviceimpl/Persistentclientperationservicempl.class : Bean instantiation via constructor failed: nested exception org.springframework.beans.BeanInstantiationException: Failed to instantiate(com.alibaba.nacos.naning.corev2.service.impl.persistentclientperationservicelmpl]: Constructor threw exception; nested exception isjava.lang.UnsatisfiedLinkError: /tmp/ ibrocksdbjni598778425169178433.so: /tmp/Librocksdbini598784255169178433.so: 无法从共享目标中映射段a
t orgspringframework.beans.factory.support,ConstructorResolver .createArgumentArray(ConstructorResolver .java:800)
at org.springframework.beans.factory.support.ConstructorResolver .autowireonstructor(ConstructorResolver .java:229)
at-rinframewor_hean.fO.D AstractAutnireapableenfactor. autowironsTruCTorAbstratAutoirelanatl eReanFartaru.java1372at org.springframework.beansfactrysupport.AbstractAutowireapableBeanFactory.createBeaninstance(AbstractAutowire(apableBeanFactory.java:122)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)at org-springfranework.beansfactory.supportAbstractAutowireapableBeanFactory.createBean(AbstractAutoireCapableBeanFactory.java:542)
at org.springframework.beans.factory.supportAbstractBeanFactory.lambdasdocetBeans0(AbstractBeanFactory.java:335)
at orgspringframework.beans.factorysupport,DefaultsingletonBeanRegistry.getSingleton(DefaultSingletonBeanRecistry,java:234)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetbean(AbstractBeanFactory.java:333)
at org.springframework.beans.factory.support.AbstractBeanFactorygetBean(AbstractBeanFactory.java:208)
at orgspringframeworkbeans.factory.suport.DefaultlistableBeanFactory.prelnstantiatesingletons(DefaultlistablebeanFactory.java:955)
at org.springframework.contextsupprtAbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
at org.springframework.context,support.AbstractApplicationContext.refresh(AbstractApplicationContext. java:583)
at org.springframework.boot.web.servlet.context.SeryletweServerApplicationontext.refresh(ServletHebServerApplication(ontext.java:145)
at org.springframework.boot.SpringApplication.refresh(SpringApplication.iava:745)
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:423)
at org.springframework.boot,SpringApplication.run(SpringApplication.java:307)
at org.springframework.bootSpringApplication.run(SpringApplication.java:1317)
at org.springframework,boot,SpringApplication.run(SpringApplication.java:1306)
at comalibaba.nacos .Nacos .main(Nacos.java:35)53t sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImol.invoke(NativeMethodAccessorImpl.iava:62)
at sun,reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

**Comment by KomachiSion** [comment]
rocksdb对系统有一定要求，可能需要替换其他的kv存储实现，或者让rocksdb适配对应系统，再升级对应版本。

**Comment by KomachiSion** [comment]
duplicate with #4336

**Comment by Mrwangjw** [comment]
一样的问题，2024年5月了，解决了没？
