### ISSUE TITLE
Exception calling after GraalVM editing

### ISSUE THREAD

**Issue by fallsea** [alibaba/nacos#11025]
**Describe the bug**
Discovering call exceptions through services

**How to Reproduce**
1. Package as GraalVM executable file
2. Run Execution File
3. Interface call
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Windows11]
 - Version [e.g. nacos-server 2.2.3, nacos-client 2.2.1,spring-cloud 2022.0.4 ,spring boot 3.1.2]
 - SDK [e.g. spring-cloud-starter-alibaba-nacos-discovery, spring-cloud-loadbalancer]

**Additional context**

```
spring:
  cloud:
    gateway:
      routes: 
      - id: demo 
        uri: lb://web-example
        predicates: 
        - Path=/demo/**
```

```
2023-08-26T20:45:14.997+08:00 DEBUG 42976 --- [grpc-nio-worker-ELG-1-4] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x0dbfe873, L:/10.10.100.6:64627 - R:/47.97.103.155:9848] OUTBOUND HEADERS: streamId=29 headers=GrpcHttp2OutboundHeaders[:authority: 47.97.103.155:9848, :path: /Request/request, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.50.2, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2023-08-26T20:45:14.997+08:00 DEBUG 42976 --- [grpc-nio-worker-ELG-1-4] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x0dbfe873, L:/10.10.100.6:64627 - R:/47.97.103.155:9848] OUTBOUND DATA: streamId=29 padding=0 endStream=true length=80 bytes=000000004b12231a124865616c7468436865636b52657175657374420d3139322e3136382e332e3130321a2412227b2268656164657273223a7b7d2c226d6f64...
2023-08-26T20:45:15.069+08:00 DEBUG 42976 --- [grpc-nio-worker-ELG-1-4] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x0dbfe873, L:/10.10.100.6:64627 - R:/47.97.103.155:9848] INBOUND PING: ack=false bytes=1234
2023-08-26T20:45:15.069+08:00 DEBUG 42976 --- [grpc-nio-worker-ELG-1-4] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x0dbfe873, L:/10.10.100.6:64627 - R:/47.97.103.155:9848] OUTBOUND PING: ack=true bytes=1234
2023-08-26T20:45:15.069+08:00 DEBUG 42976 --- [grpc-nio-worker-ELG-1-4] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x0dbfe873, L:/10.10.100.6:64627 - R:/47.97.103.155:9848] INBOUND HEADERS: streamId=29 headers=GrpcHttp2ResponseHeaders[:status: 200, content-type: application/grpc, grpc-encoding: identity, grpc-accept-encoding: gzip] padding=0 endStream=false
2023-08-26T20:45:15.070+08:00 DEBUG 42976 --- [grpc-nio-worker-ELG-1-4] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x0dbfe873, L:/10.10.100.6:64627 - R:/47.97.103.155:9848] INBOUND DATA: streamId=29 padding=0 endStream=false length=79 bytes=000000004a12151a134865616c7468436865636b526573706f6e73651a31122f7b22726573756c74436f6465223a3230302c226572726f72436f6465223a302c...
2023-08-26T20:45:15.070+08:00 DEBUG 42976 --- [grpc-nio-worker-ELG-1-4] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x0dbfe873, L:/10.10.100.6:64627 - R:/47.97.103.155:9848] OUTBOUND PING: ack=false bytes=1234
2023-08-26T20:45:15.070+08:00 DEBUG 42976 --- [grpc-nio-worker-ELG-1-4] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x0dbfe873, L:/10.10.100.6:64627 - R:/47.97.103.155:9848] INBOUND HEADERS: streamId=29 headers=GrpcHttp2ResponseHeaders[grpc-status: 0] padding=0 endStream=true
2023-08-26T20:45:15.140+08:00 DEBUG 42976 --- [grpc-nio-worker-ELG-1-4] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x0dbfe873, L:/10.10.100.6:64627 - R:/47.97.103.155:9848] INBOUND PING: ack=true bytes=1234
2023-08-26T20:45:15.140+08:00 DEBUG 42976 --- [grpc-nio-worker-ELG-1-4] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : Window: 1,048,576
2023-08-26T20:45:15.317+08:00 ERROR 42976 --- [reactor-http-nio-2] a.w.r.e.AbstractErrorWebExceptionHandler : [910ba9a7-1]  500 Server Error for HTTP POST "/demo/login"

java.lang.IllegalArgumentException: Object of class [org.springframework.context.support.GenericApplicationContext] must be an instance of interface org.springframework.context.annotation.AnnotationConfigRegistry
	at org.springframework.util.Assert.instanceCheckFailed(Assert.java:713) ~[na:na]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.web.filter.reactive.ServerHttpObservationFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP POST "/demo/login" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at org.springframework.util.Assert.instanceCheckFailed(Assert.java:713) ~[na:na]
		at org.springframework.util.Assert.isInstanceOf(Assert.java:613) ~[na:na]
		at org.springframework.util.Assert.isInstanceOf(Assert.java:644) ~[na:na]
		at org.springframework.cloud.context.named.NamedContextFactory.registerBeans(NamedContextFactory.java:143) ~[gateway-example.exe:4.0.4]
		at org.springframework.cloud.context.named.NamedContextFactory.createContext(NamedContextFactory.java:137) ~[gateway-example.exe:4.0.4]
		at org.springframework.cloud.context.named.NamedContextFactory.getContext(NamedContextFactory.java:122) ~[gateway-example.exe:4.0.4]
		at org.springframework.cloud.context.named.NamedContextFactory.getInstances(NamedContextFactory.java:236) ~[gateway-example.exe:4.0.4]
		at org.springframework.cloud.gateway.filter.ReactiveLoadBalancerClientFilter.filter(ReactiveLoadBalancerClientFilter.java:114) ~[gateway-example.exe:4.0.7]
		at org.springframework.cloud.gateway.handler.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:137) ~[na:na]
		at org.springframework.cloud.gateway.filter.OrderedGatewayFilter.filter(OrderedGatewayFilter.java:44) ~[gateway-example.exe:4.0.7]
		at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:117) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableSubscriber.onNext(FluxMapFuseable.java:129) ~[na:na]
		at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.MonoReduceSeed$ReduceSeedSubscriber.onComplete(MonoReduceSeed.java:163) ~[na:na]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.onComplete(Operators.java:2205) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:2547) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.Operators$MultiSubscriptionSubscriber.set(Operators.java:2341) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onSubscribe(FluxOnErrorResume.java:74) ~[na:na]
		at reactor.core.publisher.FluxJust.subscribe(FluxJust.java:68) ~[na:na]
		at reactor.core.publisher.Flux.subscribe(Flux.java:8773) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onError(FluxOnErrorResume.java:103) ~[na:na]
		at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.deferredError(FluxUsingWhen.java:398) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxUsingWhen$RollbackInner.onComplete(FluxUsingWhen.java:475) ~[na:na]
		at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89) ~[na:na]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.checkTerminated(FluxFlatMap.java:825) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drainLoop(FluxFlatMap.java:609) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.drain(FluxFlatMap.java:589) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onComplete(FluxFlatMap.java:466) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxArray$ArraySubscription.slowPath(FluxArray.java:138) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxArray$ArraySubscription.request(FluxArray.java:100) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxFlatMap$FlatMapMain.onSubscribe(FluxFlatMap.java:371) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxMerge.subscribe(FluxMerge.java:70) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxUsingWhen$UsingWhenSubscriber.onError(FluxUsingWhen.java:364) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.Operators.error(Operators.java:198) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxError.subscribe(FluxError.java:43) ~[na:na]
		at reactor.core.publisher.Flux.subscribe(Flux.java:8773) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxUsingWhen.subscribe(FluxUsingWhen.java:94) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.MonoFlatMap.subscribeOrReturn(MonoFlatMap.java:53) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:57) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.Mono.subscribe(Mono.java:4495) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51) ~[na:na]
		at reactor.core.publisher.InternalMonoOperator.subscribe(InternalMonoOperator.java:64) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53) ~[na:na]
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:165) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74) ~[na:na]
		at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:122) ~[na:na]
		at reactor.core.publisher.FluxDefaultIfEmpty$DefaultIfEmptySubscriber.onNext(FluxDefaultIfEmpty.java:122) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.FluxContextWrite$ContextWriteSubscriber.onNext(FluxContextWrite.java:107) ~[na:na]
		at reactor.core.publisher.FluxMapFuseable$MapFuseableConditionalSubscriber.onNext(FluxMapFuseable.java:299) ~[na:na]
		at reactor.core.publisher.FluxFilterFuseable$FilterFuseableConditionalSubscriber.onNext(FluxFilterFuseable.java:337) ~[na:na]
		at reactor.core.publisher.Operators$BaseFluxToMonoOperator.completePossiblyEmpty(Operators.java:2071) ~[gateway-example.exe:3.5.8]
		at reactor.core.publisher.MonoCollect$CollectSubscriber.onComplete(MonoCollect.java:145) ~[na:na]
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[na:na]
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260) ~[na:na]
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144) ~[na:na]
		at reactor.netty.channel.FluxReceive.onInboundComplete(FluxReceive.java:413) ~[gateway-example.exe:1.1.9]
		at reactor.netty.channel.ChannelOperations.onInboundComplete(ChannelOperations.java:431) ~[gateway-example.exe:1.1.9]
		at reactor.netty.http.server.HttpServerOperations.onInboundNext(HttpServerOperations.java:682) ~[gateway-example.exe:1.1.9]
		at reactor.netty.channel.ChannelOperationsHandler.channelRead(ChannelOperationsHandler.java:114) ~[gateway-example.exe:1.1.9]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:444) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[gateway-example.exe:4.1.94.Final]
		at reactor.netty.http.server.HttpTrafficHandler.channelRead(HttpTrafficHandler.java:284) ~[gateway-example.exe:1.1.9]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:346) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:318) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:442) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:412) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:440) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:420) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166) ~[gateway-example.exe:4.1.94.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:788) ~[na:na]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:724) ~[na:na]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:650) ~[na:na]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:562) ~[na:na]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997) ~[na:na]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[na:na]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[na:na]
		at java.base@17.0.8/java.lang.Thread.run(Thread.java:833) ~[gateway-example.exe:na]
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807) ~[gateway-example.exe:na]
		at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:179) ~[na:na]

```

**Comment by KomachiSion** [comment]
Not nacos' problem. The error info is all apps' exception.

**Comment by fallsea** [comment]
Resolved, reference address: https://docs.spring.io/spring-cloud-gateway/docs/current/reference/html/#aot-and-native-image-support
