### ISSUE TITLE
k8s中部署nacos集群，version:2.1.1，运行一段时间就会出现java.lang.OutOfMemoryError: unable to create new native thread报错

### ISSUE THREAD

**Issue by zhiguo-ren** [alibaba/nacos#11149]
Exception in thread "com.alibaba.nacos.core.protocal.distro.3131" java.lang.OutOfMemoryError: unable to create new native thread
at java.lang.Thread.start0(Native Method)
at java.lang.Thread.start(Thread.java:719)
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
Exception in thread "com.alibaba.nacos.core.protocal.distro.2911" java.lang.OutOfMemoryError: unable to create new native thread
at java.lang.Thread.start0(Native Method)
at java.lang.Thread.start(Thread.java:719)
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)
Exception in thread "com.alibaba.nacos.core.protocal.distro.3134" java.lang.OutOfMemoryError: unable to create new native thread
at java.lang.Thread.start0(Native Method)
at java.lang.Thread.start(Thread.java:719)
at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:750)

**Comment by zhiguo-ren** [comment]
jvm参数JAVA_OPT=' -server -Xms2g -Xmx4g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/nacos/logs/java_heapdump.hprof'

**Comment by KomachiSion** [comment]
seems env problem.

Please make sure follow items:
1. number of Runtime.currentProcessors, If large, please make your pod limit right but not read from node.
2. check your system setting, default system only allow one process create some thread, if the limit is low, please set the system limit higher.

**Comment by zhiguo-ren** [comment]
max user processes   (-u) 4194304,应该够用，pod中cpu使用50m~100m，同时又加了限制
resources:
            limits:
              cpu: '1'

**Comment by KomachiSion** [comment]
那可能是内存不足以创建线程了， 创建线程需要1M左右的堆以及一部分的栈内存，你看下你的应用是不是没有了这部分内存。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by flyletc** [comment]
> max user processes (-u) 4194304,应该够用，pod中cpu使用50m~1100m，同时刚又加了限制， resources: limits: cpu: '1'

您好，问题解决了吗，我们也遇到了类似的问题

**Comment by wcbkobe** [comment]
请问您的这个问题解决了嘛，我也遇到同样的问题，nacos集群启动失败，一直报内存溢出，单机又能正常启动
