### ISSUE TITLE
graalvm 打包后启动异常，UNAVAILABLE: Connection closing while performing protocol negotiation for

### ISSUE THREAD

**Issue by fallsea** [alibaba/nacos#11161]
nacos版本号：2.2.4
jdk：17

```
2023-09-20T20:35:02.215+08:00  INFO 33376 --- [main] c.a.n.p.a.s.c.ClientAuthPluginManager    : [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl success.
2023-09-20T20:35:02.215+08:00  INFO 33376 --- [main] c.a.n.p.a.s.c.ClientAuthPluginManager    : [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.ram.RamClientAuthServiceImpl success.
2023-09-20T20:35:02.293+08:00  INFO 33376 --- [main] c.a.n.c.a.r.identify.CredentialWatcher   : null No credential found
2023-09-20T20:35:02.293+08:00  INFO 33376 --- [main] com.alibaba.nacos.common.remote.client   : [RpcClientFactory] create a new rpc client of 8595a65c-c3e5-40d1-98fd-52960b49c604
2023-09-20T20:35:02.293+08:00  INFO 33376 --- [main] com.alibaba.nacos.common.remote.client   : [8595a65c-c3e5-40d1-98fd-52960b49c604] RpcClient init, ServerListFactory = com.alibaba.nacos.client.naming.core.ServerListManager
2023-09-20T20:35:02.293+08:00  INFO 33376 --- [main] com.alibaba.nacos.common.remote.client   : [8595a65c-c3e5-40d1-98fd-52960b49c604] Registry connection listener to current client:com.alibaba.nacos.client.naming.remote.gprc.redo.NamingGrpcRedoService
2023-09-20T20:35:02.293+08:00  INFO 33376 --- [main] com.alibaba.nacos.common.remote.client   : [8595a65c-c3e5-40d1-98fd-52960b49c604] Register server push request handler:com.alibaba.nacos.client.naming.remote.gprc.NamingPushRequestHandler
2023-09-20T20:35:02.294+08:00  INFO 33376 --- [main] com.alibaba.nacos.common.remote.client   : [8595a65c-c3e5-40d1-98fd-52960b49c604] Try to connect to server on start up, server: {serverIp = '192.168.3.200', server main port = 8848}
2023-09-20T20:35:02.294+08:00  INFO 33376 --- [main] c.a.n.c.remote.client.grpc.GrpcClient    : grpc client connection server:192.168.3.200 ip,serverPort:9848,grpcTslConfig:{"sslProvider":"","enableTls":false,"mutualAuthEnable":false,"trustAll":false}
2023-09-20T20:35:02.441+08:00 ERROR 33376 --- [main] c.a.n.c.remote.client.grpc.GrpcClient    : Server check fail, please check server 192.168.3.200 ,port 9848 is available , error ={}

java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closing while performing protocol negotiation for [NettyClientHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:445) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:218) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:329) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:363) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.start(NamingGrpcClientProxy.java:105) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.<init>(NamingGrpcClientProxy.java:98) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:78) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:102) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:85) ~[websocket-example-server.exe:na]
	at java.base@17.0.8/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[websocket-example-server.exe:na]
	at java.base@17.0.8/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59) ~[websocket-example-server.exe:na]
	at com.gatewayiot.lvs.client.GatewayiotLvsClient.loadRegisterServer(GatewayiotLvsClient.java:141) ~[websocket-example-server.exe:na]
	at com.gatewayiot.lvs.client.GatewayiotLvsClient.start(GatewayiotLvsClient.java:93) ~[websocket-example-server.exe:na]
	at java.base@17.0.8/java.lang.reflect.Method.invoke(Method.java:568) ~[websocket-example-server.exe:na]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1874) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1827) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1766) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:598) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:520) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:326) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:324) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:200) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:973) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:942) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:608) ~[websocket-example-server.exe:6.0.11]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[websocket-example-server.exe:3.1.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:436) ~[websocket-example-server.exe:3.1.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[websocket-example-server.exe:3.1.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[websocket-example-server.exe:3.1.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[websocket-example-server.exe:3.1.3]
	at com.gatewayiot.Application.main(Application.java:48) ~[websocket-example-server.exe:na]
Caused by: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Connection closing while performing protocol negotiation for [NettyClientHandler#0, WriteBufferingAndExceptionHandler#0, DefaultChannelPipeline$TailContext#0]
	at com.alibaba.nacos.shaded.io.grpc.Status.asRuntimeException(Status.java:539) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:544) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:471) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:435) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:468) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:563) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:723) ~[na:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[websocket-example-server.exe:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[websocket-example-server.exe:na]
	at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[websocket-example-server.exe:na]
	at java.base@17.0.8/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base@17.0.8/java.lang.Thread.run(Thread.java:833) ~[websocket-example-server.exe:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:807) ~[websocket-example-server.exe:na]
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:179) ~[na:na]
```

**Comment by fallsea** [comment]
已解决

**Comment by littleantsos** [comment]
解决你吗的比

**Comment by WangJincheng4869** [comment]
@fallsea 兄弟，如何解决的分享一下，我也遇见了同样的问题。

**Comment by fallsea** [comment]
@WangJincheng4869 官方文档中有描述，必须使用`@LoadBalancerClient`注解才可以，把服务id写上，不然就异常

https://docs.spring.io/spring-cloud-gateway/reference/4.3/spring-cloud-gateway-server-webflux/aot-and-native-image-support.html
