### ISSUE TITLE
部署了三台nacos1.4.3，docker启动服务的时候报错

### ISSUE THREAD

**Issue by gglsian** [alibaba/nacos#11179]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-09-22T10:15:57.576325283Z 2023-09-22 18:15:57.575 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
2023-09-22T10:15:57.576386867Z org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is java.lang.reflect.UndeclaredThrowableException
2023-09-22T10:15:57.576396994Z 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181)
2023-09-22T10:15:57.576404285Z 	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
2023-09-22T10:15:57.576424048Z 	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
2023-09-22T10:15:57.576430268Z 	at java.base/java.lang.Iterable.forEach(Iterable.java:75)
2023-09-22T10:15:57.576435578Z 	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
2023-09-22T10:15:57.576441636Z 	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
2023-09-22T10:15:57.576447269Z 	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
2023-09-22T10:15:57.576452684Z 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
2023-09-22T10:15:57.576458255Z 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
2023-09-22T10:15:57.576470856Z 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
2023-09-22T10:15:57.576476309Z 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414)
2023-09-22T10:15:57.576481616Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
2023-09-22T10:15:57.576486982Z 	at com.qtzl.qtsso.SsoApplication.main(SsoApplication.java:22)
2023-09-22T10:15:57.576492174Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-09-22T10:15:57.576497894Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-09-22T10:15:57.576503524Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-09-22T10:15:57.576508954Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-09-22T10:15:57.576514246Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
2023-09-22T10:15:57.576521263Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
2023-09-22T10:15:57.576527047Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
2023-09-22T10:15:57.576532513Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
2023-09-22T10:15:57.576537916Z Caused by: java.lang.reflect.UndeclaredThrowableException: null
2023-09-22T10:15:57.576543040Z 	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:147)
2023-09-22T10:15:57.576548807Z 	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:82)
2023-09-22T10:15:57.576554412Z 	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:232)
2023-09-22T10:15:57.576560341Z 	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78)
2023-09-22T10:15:57.576570129Z 	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:133)
2023-09-22T10:15:57.576576002Z 	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:98)
2023-09-22T10:15:57.576581644Z 	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:86)
2023-09-22T10:15:57.576587372Z 	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47)
2023-09-22T10:15:57.576592971Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176)
2023-09-22T10:15:57.576598631Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169)
2023-09-22T10:15:57.576604134Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143)
2023-09-22T10:15:57.576609997Z 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421)
2023-09-22T10:15:57.576615491Z 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378)
2023-09-22T10:15:57.576621024Z 	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:46)
2023-09-22T10:15:57.576627378Z 	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
2023-09-22T10:15:57.576633228Z 	... 20 common frames omitted
2023-09-22T10:15:57.576638524Z Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([100.64.1.62:8848]) tried: ErrCode:400, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Sep 22 18:15:48 CST 2023</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 100.64.1.62</div></body></html>
2023-09-22T10:15:57.576650937Z 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:556)
2023-09-22T10:15:57.576656647Z 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
2023-09-22T10:15:57.576661905Z 	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493)
2023-09-22T10:15:57.576667129Z 	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:246)
2023-09-22T10:15:57.576672788Z 	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:212)
2023-09-22T10:15:57.576679363Z 	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74)
2023-09-22T10:15:57.576688421Z 	... 33 common frames omitted

**Comment by huangkemingyyds** [comment]
感觉是 Nacos 配置出现了问题，导致服务不能注册。

**Comment by gglsian** [comment]
只修改了数据库配置，密码配置，集群配置，其余未改动

**Comment by KomachiSion** [comment]
部署问题， 查看cluster.conf文件中的配置是否正确。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
