### ISSUE TITLE
配置中心dataId对应content内容4万多行，导致403

### ISSUE THREAD

**Issue by lyyu1988** [alibaba/nacos#11238]
**Describe the bug**
nacos客户端版本为1.3.3，当往配置中心提交修改配置的请求时，若content内容过长（4万多行），会返回403响应。

**Desktop (please complete the following information):**
 - Version nacos-client 1.3.1
 - Module config
 - SDK spring-cloud-alibaba-nacos 2.2.3.RELEASE
**Additional context**
具体报错如下

[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:44.271 INFO 34364 [] [main] c.a.n.client.config.NacosConfigService   [fixed-192.168.108.100_8848] [publish-single] ok, dataId=menus, group=onepark, tenant=, config={
	"bmpcar":[
		{
			"protoMenuFlag":true,
			"sliceOrder":2147483647,
			"navigator":"bmpcar",
			"...
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:44.318 INFO 34364 [] [main] c.a.n.client.config.NacosConfigService   [fixed-192.168.108.100_8848] [publish-single] ok, dataId=sys.menus, group=onepark, tenant=, config={
	"bmpcar":[],
	"pcs":[
		{
			"protoMenuFlag":true,
			"sliceOrder":2147483647,
			"navigator":"sy...
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:45.734 INFO 34364 [] [main] c.a.n.client.config.NacosConfigService   [fixed-192.168.108.100_8848] [publish-single] ok, dataId=infor-manage-AUTHORIZED, group=onepark, tenant=, config={
	"infor-manage":[
		{
			"readApi":true,
			"menuKey":"default",
			"patterns":[
				"/rpc-api/inf...
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:45.803 INFO 34364 [] [main] c.a.n.client.config.NacosConfigService   [fixed-192.168.108.100_8848] [publish-single] ok, dataId=infor-manage-AUTHENTICATED, group=onepark, tenant=, config={
	"infor-manage":[
		{
			"readApi":true,
			"menuKey":"default",
			"patterns":[
				"/admin-api/i...
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:45.836 INFO 34364 [] [main] c.a.n.client.config.NacosConfigService   [fixed-192.168.108.100_8848] [publish-single] ok, dataId=SERVER-LIST, group=onepark, tenant=, config={
	"serverList":[
		"bmpcar",
		"pcs",
		"pub-server",
		"user-server",
		"item-manage",
		"infra-se...
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:46.324 WARN 34364 [] [main] c.a.n.client.config.NacosConfigService   [fixed-192.168.108.100_8848] [publish-single] error, dataId=authority, group=onepark, tenant=, code=403, msg=<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Oct 09 14:25:46 CST 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>user not found!</div></body></html>
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:46.354 WARN 34364 [] [main] ConfigServletWebServerApplicationContext Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authorityManager' defined in class path resource [com/cmiot/common/config/AuthorityConfiguration.class]: Invocation of init method failed; nested exception is com.cmiot.common.exception.LockException: com.cmiot.common.store.StoreException: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Oct 09 14:25:46 CST 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>user not found!</div></body></html>
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:46.354 INFO 34364 [] [main] o.s.s.c.ThreadPoolTaskScheduler          Shutting down ExecutorService 'taskScheduler'
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:46.354 INFO 34364 [] [main] o.s.s.concurrent.ThreadPoolTaskExecutor  Shutting down ExecutorService 'applicationTaskExecutor'
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:46.364 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.beat.BeatReactor do shutdown begin
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:46.365 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.beat.BeatReactor do shutdown stop
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:46.365 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.core.EventDispatcher do shutdown begin
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:49.365 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.core.EventDispatcher do shutdown stop
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:49.365 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.core.HostReactor do shutdown begin
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:49.365 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.core.PushReceiver do shutdown begin
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.368 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.core.PushReceiver do shutdown stop
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.368 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown begin
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.368 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown stop
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.368 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.core.HostReactor do shutdown stop
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.368 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.net.NamingProxy do shutdown begin
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.369 WARN 34364 [] [main] com.alibaba.nacos.client.naming          [NamingHttpClientManager] Start destroying NacosRestTemplate
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.369 WARN 34364 [] [main] com.alibaba.nacos.client.naming          [NamingHttpClientManager] Destruction of the end
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.369 INFO 34364 [] [main] com.alibaba.nacos.client.naming          com.alibaba.nacos.client.naming.net.NamingProxy do shutdown stop
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.369 INFO 34364 [] [main] com.alibaba.druid.pool.DruidDataSource   {dataSource-1} closing ...
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.373 ERROR 34364 [] [com.alibaba.nacos.naming.push.receiver] com.alibaba.nacos.client.naming          [NA] error while receiving push data

java.net.SocketException: socket closed
	at java.net.DualStackPlainDatagramSocketImpl.socketReceiveOrPeekData(Native Method)
	at java.net.DualStackPlainDatagramSocketImpl.receive0(DualStackPlainDatagramSocketImpl.java:124)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:149)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at com.alibaba.nacos.client.naming.core.PushReceiver.run(PushReceiver.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.378 INFO 34364 [] [main] com.alibaba.druid.pool.DruidDataSource   {dataSource-1} closed
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.424 INFO 34364 [] [main] o.apache.catalina.core.StandardService   Stopping service [Tomcat]
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.466 INFO 34364 [] [main] ConditionEvaluationReportLoggingListener 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[infor-manage:2.0.1.55:48099] 2023-10-09 14:25:52.494 ERROR 34364 [] [main] o.s.boot.SpringApplication               Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'authorityManager' defined in class path resource [com/cmiot/common/config/AuthorityConfiguration.class]: Invocation of init method failed; nested exception is com.cmiot.common.exception.LockException: com.cmiot.common.store.StoreException: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Oct 09 14:25:46 CST 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>user not found!</div></body></html>
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1794)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at com.cmict.eaap.module.infor.manage.InforManagerApplication.main(InforManagerApplication.java:24)
Caused by: com.cmiot.common.exception.LockException: com.cmiot.common.store.StoreException: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Oct 09 14:25:46 CST 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>user not found!</div></body></html>
	at com.cmiot.common.lock.DistributedSafeOperator.safeOperate(DistributedSafeOperator.java:37)
	at com.cmiot.common.authority.AuthorityProvider.afterPropertiesSet(AuthorityProvider.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1853)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1790)
	... 16 common frames omitted
Caused by: com.cmiot.common.store.StoreException: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Oct 09 14:25:46 CST 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>user not found!</div></body></html>
	at com.cmiot.configure.apis.NacosResourceStore.store(NacosResourceStore.java:41)
	at com.cmiot.common.authority.AuthorityProvider.storeAuthorities(AuthorityProvider.java:155)
	at com.cmiot.common.authority.AuthorityProvider.doOperate(AuthorityProvider.java:144)
	at com.cmiot.common.lock.DistributedSafeOperator.safeOperate(DistributedSafeOperator.java:28)
	... 19 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Oct 09 14:25:46 CST 2023</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>user not found!</div></body></html>
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfigInner(NacosConfigService.java:261)
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfig(NacosConfigService.java:115)
	at com.cmiot.configure.apis.NacosResourceStore.store(NacosResourceStore.java:39)
	... 22 common frames omitted

**Comment by KomachiSion** [comment]
`user not found!`

**Comment by chixinwang** [comment]
@lyyu1988 你的问题解决了嘛，我这边也是出现了同样的问题，当数据量比较小的时候可以正常推送配置，一旦数据量过大，像你说的4万行（我这边是1.2MB左右的文本数据）就会出现403。
