### ISSUE TITLE
使用了nacos作为dubbo的服务注册与发现，springboot容器关闭后再启动，nacos的线程没有关闭干净

### ISSUE THREAD

**Issue by caoyanan666** [alibaba/nacos#11294]
报错：
[2023-10-27T17:17:06,910] [ERROR] [nacos.publisher-com.alibaba.nacos.client.naming.event.InstancesChangeEvent#179] com.alibaba.nacos.common.notify.NotifyCenter#208 - Event callback exception: 
java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7e8b0f12[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@18cef563[Wrapped task = org.apache.dubbo.registry.RegistryNotifier$NotificationTask@6cef5ca6]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@1142eb02[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 8]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562) ~[?:?]
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:715) ~[?:?]
	at java.util.concurrent.Executors$DelegatedExecutorService.submit(Executors.java:714) ~[?:?]
	at org.apache.dubbo.registry.RegistryNotifier.notify(RegistryNotifier.java:77) ~[dubbo-registry-api-3.0.15.jar:3.0.15]
	at org.apache.dubbo.registry.nacos.NacosRegistry$RegistryChildListenerImpl.onEvent(NacosRegistry.java:723) ~[dubbo-registry-nacos-3.0.15.jar:3.0.15]
	at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:126) ~[nacos-client-2.2.4.jar:?]
	at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:42) ~[nacos-client-2.2.4.jar:?]
	at com.alibaba.nacos.common.notify.DefaultPublisher.lambda$notifySubscriber$0(DefaultPublisher.java:199) ~[nacos-client-2.2.4.jar:?]
	at com.alibaba.nacos.common.notify.DefaultPublisher.notifySubscriber(DefaultPublisher.java:206) [nacos-client-2.2.4.jar:?]
	at com.alibaba.nacos.common.notify.DefaultPublisher.receiveEvent(DefaultPublisher.java:190) [nacos-client-2.2.4.jar:?]
	at com.alibaba.nacos.common.notify.DefaultPublisher.openEventHandler(DefaultPublisher.java:112) [nacos-client-2.2.4.jar:?]
	at com.alibaba.nacos.common.notify.DefaultPublisher.run(DefaultPublisher.java:95) [nacos-client-2.2.4.jar:?]

复现：
@SpringBootApplication
public class XxxBootstrap {

	private static ConfigurableApplicationContext APPLICATION;

	public static void main(String[] args) {
		APPLICATION = SpringApplication.run(XxxBootstrap.class, args);
	}

	public static void stop() {
		if (Objects.isNull(APPLICATION)) {
			throw new RuntimeException("The application has not been started and cannot be stopped");
		}
		try {
			SpringApplication.exit(APPLICATION, () -> 0);
		} catch (Exception ex) {
			throw new RuntimeException(ex);
		}
	}
}

public class MySOFAArk {

	public static void main(String[] args) {
		XxxBootstrap.main(args);
		XxxBootstrap.stop();
		XxxBootstrap.main(args); //第二次启动的时候就会报这个错
	}
}

诉求：
是不是nacos-client的线程池没有正常的shutdown

**Comment by stone-98** [comment]
这个异常看异常栈，应该是触发InstancesChangeEvent时，dubbo的ThreadPoolExecutor已经被shutdown导致了，dubbo应该需要检查一下线程池是否shutdown再进行处理~

**Comment by KomachiSion** [comment]
看堆栈是dubbo实现服务监听器的时候， 被回调时线程池已经关闭导致的， 不是nacos-client的问题。

看下是dubbo来判断线程池状态，还是确保先调用nacos-client的shutdown方法，确保先关闭nacos-client再进行关闭自己线程池。

**Comment by caoyanan666** [comment]
我debug的结构是InstancesChangeNotifier 这个示例，当spring容器销毁了，它没有正常释放掉
