### ISSUE TITLE
微服务注册在nacos后，运行一段时间，微服务网管报错：[NA] failed to write cache for dom:*****

### ISSUE THREAD

**Issue by liutinglt077** [alibaba/nacos#11313]
使用springboot 2.4.3版本和nacos 2.0.3版本，运行一段时间之后，网关服务日志中会报错，具体报错：
16:31:35.835 [com.alibaba.nacos.naming.failover] ERROR c.a.n.client.naming - [write,78] - [NA] failed to write cache for dom:yt-system
java.io.IOException: file not exist
        at com.alibaba.nacos.client.naming.cache.ConcurrentDiskUtil.writeFileContent(ConcurrentDiskUtil.java:163)
        at com.alibaba.nacos.client.naming.cache.DiskCache.write(DiskCache.java:75)
        at com.alibaba.nacos.client.naming.backups.FailoverReactor$DiskFileWriter.run(FailoverReactor.java:274)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
我们将写入缓存的文件权限开放至777，也无法解决

**Comment by tomlikeyou** [comment]
`java.io.IOException: file not exist` ，是不是写入路径有问题，默认${user.home}/nacos/naming/public/failover 目录

**Comment by liutinglt077** [comment]
> `java.io.IOException: file not exist` ，是不是写入路径有问题，默认${user.home}/nacos/naming/public/failover 目录

我们默认使用root用户去操作nacos的

**Comment by KomachiSion** [comment]
这个文件没什么关系，可以忽略。
