### ISSUE TITLE
nacos 开启了权限认证后使用用户名和密码注册服务，除nacos用户外的其他服务无法将服务注册到public命名空间下，即使已授权其它用户public空间的读写权限

### ISSUE THREAD

**Issue by fengxiuli6** [alibaba/nacos#11311]

**Comment by fengxiuli6** [comment]
2023-11-01 08:52:18.397 ERROR 1 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, blade-admin register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='nacos:8848', username='service', password='nacos', endpoint='', namespace='', watchDelay=30000, logName='', service='blade-admin', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={IPv6=null, preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='172.21.13.238', networkInterface='', port=7002, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, instanceEnabled=true, ephemeral=true, failureToleranceEnabled=false}, ipDeleteTimeout=null, failFast=true}},




com.alibaba.nacos.api.exception.NacosException: authorization failed!

**Comment by tomlikeyou** [comment]
具体的版本、环境信息以及更多的日志信息需要提供

**Comment by fengxiuli6** [comment]
版本2.2.3
开启权限认证
nacos.core.auth.enabled=true
nacos.core.auth.server.identity.key=Chinasws@nacos
nacos.core.auth.server.identity.value=SWS@nacos123
nacos.core.auth.plugin.nacos.token.secret.key=VGhpc0lzTXlDdXN0b21TZWNyZXRLZX    kxMjM0NTY3ODk=


---启动中，读取到的环境变量:[test]，jar地址:[file:/blade/admin/app.jar]----


2023-11-01 09:05:14.525  INFO 1 --- [           main] c.a.n.p.a.s.c.ClientAuthPluginManager    : [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl success.


2023-11-01 09:05:14.526  INFO 1 --- [           main] c.a.n.p.a.s.c.ClientAuthPluginManager    : [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.ram.RamClientAuthServiceImpl success.


                   ______  _             _       ___   ___


                   | ___ \| |           | |      \  \ /  /


                   | |_/ /| |  __ _   __| |  ___  \  V  /


                   | ___ \| | / _` | / _` | / _ \   > <


                   | |_/ /| || (_| || (_| ||  __/ /  .  \


                   \____/ |_| \__,_| \__,_| \___|/__/ \__\




:: BladeX 3.1.1.RELEASE :: blade-admin:test :: Running SpringBoot 2.7.11 :: 




2023-11-01 09:05:16.293  WARN 1 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[blade-admin] & group[DEFAULT_GROUP]


2023-11-01 09:05:16.300  WARN 1 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[blade-admin.yaml] & group[DEFAULT_GROUP]


2023-11-01 09:05:16.307  WARN 1 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[blade-admin-test.yaml] & group[DEFAULT_GROUP]


2023-11-01 09:05:16.308  INFO 1 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-blade-admin-test.yaml,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-blade-admin.yaml,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-blade-admin,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-blade-test.yaml,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-blade.yaml,DEFAULT_GROUP'}]


2023-11-01 09:05:16.342  INFO 1 --- [           main] org.springblade.admin.AdminApplication   : The following 1 profile is active: "test"


2023-11-01 09:05:17.986  INFO 1 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=5877ea99-fea0-3318-9b6f-e6d51614732c


2023-11-01 09:05:17.990  INFO 1 --- [           main] s.c.l.p.BladePropertySourcePostProcessor : BladePropertySourcePostProcessor init.


2023-11-01 09:05:18.008  INFO 1 --- [           main] s.c.l.p.BladePropertySourcePostProcessor : BladePropertySourcePostProcessor process @BladePropertySource bean.


2023-11-01 09:05:18.179  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'cloud.tianai.captcha.spring.autoconfiguration.ImageCaptchaAutoConfiguration' of type [cloud.tianai.captcha.spring.autoconfiguration.ImageCaptchaAutoConfiguration$$EnhancerBySpringCGLIB$$3b55462e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)


2023-11-01 09:05:18.220  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)


2023-11-01 09:05:18.221  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig' of type [org.springframework.cloud.client.loadbalancer.reactive.LoadBalancerBeanPostProcessorAutoConfiguration$ReactorDeferringLoadBalancerFilterConfig] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)


2023-11-01 09:05:18.223  INFO 1 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'reactorDeferringLoadBalancerExchangeFilterFunction' of type [org.springframework.cloud.client.loadbalancer.reactive.DeferringLoadBalancerExchangeFilterFunction] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)


2023-11-01 09:05:18.919  WARN 1 --- [           main] ion$DefaultTemplateResolverConfiguration : Cannot find template location: classpath:/templates/ (please add some templates, check your Thymeleaf configuration, or set spring.thymeleaf.check-template-location=false)


2023-11-01 09:05:19.558  INFO 1 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 19 endpoint(s) beneath base path '/actuator'


2023-11-01 09:05:19.663  INFO 1 --- [           main] c.t.c.g.AbstractImageCaptchaGenerator    : 图片验证码[SpringMultiImageCaptchaGenerator]初始化...


2023-11-01 09:05:20.006  INFO 1 --- [           main] f.a.AutowiredAnnotationBeanPostProcessor : Inconsistent constructor declaration on bean with name 'org.springblade.core.launch.server.ServerInfo': single autowire-marked constructor flagged as optional - this constructor is effectively required since there is no default constructor to fall back to: public org.springblade.core.launch.server.ServerInfo(org.springframework.boot.autoconfigure.web.ServerProperties)


2023-11-01 09:05:20.341  WARN 1 --- [           main] iguration$LoadBalancerCaffeineWarnLogger : Spring Cloud LoadBalancer is currently working with the default cache. While this cache implementation is useful for development and tests, it's recommended to use Caffeine cache in production.You can switch to using Caffeine cache, by adding it and org.springframework.cache.caffeine.CaffeineCacheManager to the classpath.


2023-11-01 09:05:20.621  INFO 1 --- [           main] o.s.b.web.embedded.netty.NettyWebServer  : Netty started on port 7002


2023-11-01 09:05:20.641  INFO 1 --- [           main] c.a.n.p.a.s.c.ClientAuthPluginManager    : [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.impl.NacosClientAuthServiceImpl success.


2023-11-01 09:05:20.641  INFO 1 --- [           main] c.a.n.p.a.s.c.ClientAuthPluginManager    : [ClientAuthPluginManager] Load ClientAuthService com.alibaba.nacos.client.auth.ram.RamClientAuthServiceImpl success.


2023-11-01 09:05:20.876 ERROR 1 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, blade-admin register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='nacos:8848', username='service', password='nacos', endpoint='', namespace='', watchDelay=30000, logName='', service='blade-admin', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={IPv6=null, preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='172.21.14.26', networkInterface='', port=7002, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, instanceEnabled=true, ephemeral=true, failureToleranceEnabled=false}, ipDeleteTimeout=null, failFast=true}},




com.alibaba.nacos.api.exception.NacosException: authorization failed!


	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:306) ~[nacos-client-2.1.2.jar!/:na]


	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:154) ~[nacos-client-2.1.2.jar!/:na]


	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:117) ~[nacos-client-2.1.2.jar!/:na]


	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:96) ~[nacos-client-2.1.2.jar!/:na]


	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:149) ~[nacos-client-2.1.2.jar!/:na]


	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:75) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.0.5.0.jar!/:2021.0.5.0]


	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:232) [spring-cloud-commons-3.1.6.jar!/:3.1.6]


	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) [spring-cloud-starter-alibaba-nacos-discovery-2021.0.5.0.jar!/:2021.0.5.0]


	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:133) [spring-cloud-commons-3.1.6.jar!/:3.1.6]


	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:98) [spring-cloud-commons-3.1.6.jar!/:3.1.6]


	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:86) [spring-cloud-commons-3.1.6.jar!/:3.1.6]


	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) [spring-cloud-commons-3.1.6.jar!/:3.1.6]


	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.boot.web.reactive.context.WebServerManager.start(WebServerManager.java:57) [spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.boot.web.reactive.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:40) [spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.DefaultLifecycleProcessor$$Lambda$336/00000000FCB99DA0.accept(Unknown Source) [spring-context-5.3.27.jar!/:5.3.27]


	at java.lang.Iterable.forEach(Unknown Source) [na:1.8.0_262]


	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:937) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) [spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) [spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) [spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) [spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) [spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) [spring-boot-2.7.11.jar!/:2.7.11]


	at org.springblade.core.launch.BladeApplication.run(BladeApplication.java:50) [blade-core-launch-3.1.1.RELEASE.jar!/:na]


	at org.springblade.admin.AdminApplication.main(AdminApplication.java:36) [classes!/:na]


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_262]


	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_262]


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_262]


	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_262]


	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app.jar:na]


	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [app.jar:na]


	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app.jar:na]


	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) [app.jar:na]




2023-11-01 09:05:20.876  WARN 1 --- [           main] onfigReactiveWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is java.lang.reflect.UndeclaredThrowableException


2023-11-01 09:05:23.251  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener : 




Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.


2023-11-01 09:05:23.288 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed




org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is java.lang.reflect.UndeclaredThrowableException


	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.DefaultLifecycleProcessor$$Lambda$336/00000000FCB99DA0.accept(Unknown Source) ~[na:na]


	at java.lang.Iterable.forEach(Unknown Source) ~[na:1.8.0_262]


	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:937) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:731) ~[spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) [spring-boot-2.7.11.jar!/:2.7.11]


	at org.springblade.core.launch.BladeApplication.run(BladeApplication.java:50) [blade-core-launch-3.1.1.RELEASE.jar!/:na]


	at org.springblade.admin.AdminApplication.main(AdminApplication.java:36) [classes!/:na]


	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_262]


	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_262]


	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_262]


	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_262]


	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app.jar:na]


	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [app.jar:na]


	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app.jar:na]


	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) [app.jar:na]


Caused by: java.lang.reflect.UndeclaredThrowableException: null


	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:147) ~[spring-core-5.3.27.jar!/:5.3.27]


	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:83) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.0.5.0.jar!/:2021.0.5.0]


	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:232) ~[spring-cloud-commons-3.1.6.jar!/:3.1.6]


	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.0.5.0.jar!/:2021.0.5.0]


	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:133) ~[spring-cloud-commons-3.1.6.jar!/:3.1.6]


	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:98) ~[spring-cloud-commons-3.1.6.jar!/:3.1.6]


	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:86) ~[spring-cloud-commons-3.1.6.jar!/:3.1.6]


	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) ~[spring-cloud-commons-3.1.6.jar!/:3.1.6]


	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.27.jar!/:5.3.27]


	at org.springframework.boot.web.reactive.context.WebServerManager.start(WebServerManager.java:57) ~[spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.boot.web.reactive.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:40) ~[spring-boot-2.7.11.jar!/:2.7.11]


	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.27.jar!/:5.3.27]


	... 23 common frames omitted


Caused by: com.alibaba.nacos.api.exception.NacosException: authorization failed!


	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:306) ~[nacos-client-2.1.2.jar!/:na]


	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:154) ~[nacos-client-2.1.2.jar!/:na]


	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:117) ~[nacos-client-2.1.2.jar!/:na]


	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:96) ~[nacos-client-2.1.2.jar!/:na]


	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:149) ~[nacos-client-2.1.2.jar!/:na]


	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:75) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.0.5.0.jar!/:2021.0.5.0]


	... 37 common frames omitted




2023-11-01 09:05:24.225  WARN 1 --- [      Thread-11] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Start destroying Publisher


2023-11-01 09:05:24.225  WARN 1 --- [       Thread-5] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Start destroying common HttpClient


2023-11-01 09:05:24.225  WARN 1 --- [      Thread-11] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Destruction of the end

**Comment by fengxiuli6** [comment]
command:
            - '--spring.profiles.active=test'
#            - '--spring.zipkin.base-url=http://zipkin-service:9411'
            - '--spring.cloud.nacos.discovery.namespace=bb3083ed-0f84-4409-a230-378713b8dc9b'
            - '--spring.cloud.nacos.config.namespace=bb3083ed-0f84-4409-a230-378713b8dc9b'
            - '--spring.cloud.sentinel.transport.dashboard=sentinel:8858'
            - '--spring.cloud.nacos.discovery.server-addr=nacos:8848'
            - '--spring.cloud.nacos.discovery.username=service'
            - '--spring.cloud.nacos.discovery.password=nacos'
            - '--spring.cloud.nacos.config.server-addr=nacos:8848'
            - '--spring.cloud.nacos.config.username=service'
            - '--spring.cloud.nacos.config.password=nacos'
            - '--spring.cloud.nacos.config.refreshable-dataids=blade.yaml,blade-test.yaml'
           增加namespace  可以成功注入其他命名空间

**Comment by KomachiSion** [comment]
duplicate with https://github.com/alibaba/nacos/issues/9846
