### ISSUE TITLE
windows环境正常启动,linux docker启动报错数据库连不上 No DataSource set

### ISSUE THREAD

**Issue by zyy-zhangfaming** [alibaba/nacos#11321]
mysql8.0; spring-boot 2.7.10; nacos 2.2.3；在本地windows环境可以正常启动，打包成docker镜像，启动报错

Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos Server did not start because dumpservice bean construction failure :
2023-11-02T09:26:23.868193827Z No DataSource set
2023-11-02T09:26:23.868210901Z 	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:260)
2023-11-02T09:26:23.868214221Z 	at com.alibaba.nacos.config.server.service.dump.ExternalDumpService.init(ExternalDumpService.java:61)
2023-11-02T09:26:23.868217305Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2023-11-02T09:26:23.868219888Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
2023-11-02T09:26:23.868232181Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2023-11-02T09:26:23.868235008Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
2023-11-02T09:26:23.868237676Z 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
2023-11-02T09:26:23.868240407Z 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
2023-11-02T09:26:23.868243139Z 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
2023-11-02T09:26:23.868245855Z 	... 40 common frames omitted
2023-11-02T09:26:23.868248438Z Caused by: java.lang.IllegalStateException: No DataSource set
2023-11-02T09:26:23.868251016Z 	at org.springframework.util.Assert.state(Assert.java:76)
2023-11-02T09:26:23.868253535Z 	at org.springframework.jdbc.support.JdbcAccessor.obtainDataSource(JdbcAccessor.java:86)
2023-11-02T09:26:23.868256267Z 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:376)
2023-11-02T09:26:23.868259415Z 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:465)
2023-11-02T09:26:23.868261939Z 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:475)
2023-11-02T09:26:23.868264433Z 	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:508)
2023-11-02T09:26:23.868267006Z 	at org.springframework.jdbc.core.JdbcTemplate.queryForObject(JdbcTemplate.java:515)
2023-11-02T09:26:23.868269729Z 	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalConfigInfoPersistServiceImpl.findConfigMaxId(ExternalConfigInfoPersistServiceImpl.java:632)
2023-11-02T09:26:23.868272540Z 	at com.alibaba.nacos.config.server.service.dump.processor.DumpAllProcessor.process(DumpAllProcessor.java:51)
2023-11-02T09:26:23.868275141Z 	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpConfigInfo(DumpService.java:317)
2023-11-02T09:26:23.868277724Z 	at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:230)
2023-11-02T09:26:23.868280736Z 	... 48 common frames omitted

**Comment by KomachiSion** [comment]
This error means your datasource is not ready.

It might caused by wrong configuration, network problem, datasource can't be connected and so on.

Please check other logs like config-fatal.log and nacos.log to see the why datasource not ready.

**Comment by 3473664996** [comment]
我也遇到了 是 mysql 也是 docker 版的 且部署到了一起 然后 ip 写的 127.0.0.1 需要 docker network inspect bridge 看一下docker 分组的ip 使用这个id才行 或者尝试使用 本机ip应该也可以

**Comment by 3473664996** [comment]
> > 我也遇到了 是 mysql 也是 docker 版的 且部署到了一起 然后 ip 写的 127.0.0.1 需要 docker network inspect bridge 看一下docker 分组的ip 使用这个id才行 或者尝试使用 本机ip应该也可以
> 
> ➜ example git:(master) ✗ docker network inspect bridge [ { "Name": "bridge", "Id": "0b32642f7ac837571d17c15dd88678b498c4cf552a81368d2d7f6eadd7933bba", "Created": "2024-07-19T07:34:58.31453675Z", "Scope": "local", "Driver": "bridge", "EnableIPv6": false, "IPAM": { "Driver": "default", "Options": null, "Config": [ { "Subnet": "172.17.0.0/16", "Gateway": "172.17.0.1" } ] }, "Internal": false, "Attachable": false, "Ingress": false, "ConfigFrom": { "Network": "" }, "ConfigOnly": false, "Containers": {}, "Options": { "com.docker.network.bridge.default_bridge": "true", "com.docker.network.bridge.enable_icc": "true", "com.docker.network.bridge.enable_ip_masquerade": "true", "com.docker.network.bridge.host_binding_ipv4": "0.0.0.0", "com.docker.network.bridge.name": "docker0", "com.docker.network.driver.mtu": "65535" }, "Labels": {} } ]
> 
> 分组 ip 是 "Subnet": "172.17.0.0/16", 这个吗， 貌似不起作用啊

只要不是127.0.0.1的这种就行因为这样他在容器内部去找了,自己搭的话推荐看一下MySQL所在网关的 ip 然后用这个网段下的ip地址 全是本机的话直接用本机内网路由器的ip也行
