### ISSUE TITLE
Param check invalid:Param 'Metadata' is illegal, the param length should not exceed 1024.

### ISSUE THREAD

**Issue by ChinaJeckXu** [alibaba/nacos#11475]
**Describe the bug**
Param check invalid:Param 'Metadata' is illegal, the param length should not exceed 1024.

**Expected behavior**
2023-12-06 16:52:18.698 ERROR 1999 --- [ing.grpc.redo.0] com.alibaba.nacos.client.naming          : Redo instance operation REGISTER for DUBBO-SERVICE-DEV@@consumers:org.jeckxu.magical.merchant.tunnel.dubbo.rpc.MerchantBaseInfoRpc:3.7.2.SNAPSHOT.jre11.x86_64:dev failed. 

com.alibaba.nacos.api.exception.NacosException: Param check invalid:Param 'Metadata' is illegal, the param length should not exceed 1024.
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:452)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:249)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.processRegisterRedoType(RedoScheduledTask.java:102)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForInstance(RedoScheduledTask.java:79)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForInstances(RedoScheduledTask.java:61)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.run(RedoScheduledTask.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:305)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Macos]
 - Version [e.g. nacos-server 2.3.0, nacos-client 2.3.0]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by ChinaJeckXu** [comment]
In actual production environments, the parameter length of 1024 is too strict.

**Comment by fireflyingup** [comment]
i got the same error (2.3.0)
Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:290)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:94)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145)
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.lambda$registerInstance$3(NacosNamingServiceWrapper.java:71)
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.accept(NacosNamingServiceWrapper.java:146)
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:71)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:180)
	... 47 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: Param check invalid:Param 'Metadata' is illegal, the param length should not exceed 1024.
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:282)
	... 55 common frames omitted

**Comment by KomachiSion** [comment]
https://nacos.io/zh-cn/docs/v2/guide/user/parameters-check.html

**Comment by bs352** [comment]
+1 for 1024 is too strict in production environment.
I am using nacos as a dubbo registry center, if any dubbo service contains slightly too many methods, the registration would fail.

Yes, turning off parameters check is a workaround, but I still want to the other param checks to work.

Can I propose that we make the param check rule configurable via configuration files?
I am willing to contribute if this proposal is accepted by the community.

**Comment by tanglinyan** [comment]
Is the new version fixed?

**Comment by bs352** [comment]
> Is the new version fixed?

not that i am aware of, turning off params check is the currently the only work around.
You can add "nacos.core.param.check.enabled=false" to application.properties to turn off the check.

**Comment by YangNovice** [comment]
> > Is the new version fixed?
> 
> not that i am aware of, turning off params check is the currently the only work around. You can add "nacos.core.param.check.enabled=false" to application.properties to turn off the check.

这个不行，我试过了。我的是nacos-client:2.0.3，然后是nacos2.4.1
