### ISSUE TITLE
Nacos客户端升级到2.3.0后，Dubbo服务不能注册

### ISSUE THREAD

**Issue by ldcsaa** [alibaba/nacos#11503]
**Describe the bug**
Nacos客户端从2.2.4升级到2.3.0后，启动Dubbo服务报错，服务注册不成功：

```
2023-12-13 14:44:28.096 WARN  [main] o.a.d.common.logger.log4j2.Log4j2Logger#warn(L:86) ->  [DUBBO] Failed to request nacos naming server. Dubbo will try to retry in 10. Try times: 10, dubbo version: 3.2.7, current host: 192.168.56.1, error code: 1-37. This may be caused by , go to https://dubbo.apache.org/faq/1/37 to find instructions. 
com.alibaba.nacos.api.exception.NacosException: wrong group name prefix of instance service name! it should be: DUBBO_GROUP, Instance: Instance{instanceId='null', ip='192.168.56.1', port=6002, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='null', serviceName='hp-demo-infra-basic-service', metadata={dubbo.endpoints=[{"port":6002,"protocol":"tri"}], dubbo.metadata-service.url-params={"prefer.serialization":"fastjson2,hessian2","version":"1.0.0","dubbo":"2.0.2","release":"3.2.7","side":"provider","port":"6002","protocol":"tri"}, dubbo.metadata.revision=6a960ac1cfd76a1adaaf3a3104e262dc, dubbo.metadata.storage-type=local}}
	at com.alibaba.nacos.client.naming.NacosNamingService.checkAndStripGroupNamePrefix(NacosNamingService.java:490) ~[nacos-client-2.3.0.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.3.0.jar:?]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.lambda$registerInstance$5(NacosNamingServiceWrapper.java:121) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.accept(NacosNamingServiceWrapper.java:465) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:121) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.lambda$doRegister$0(NacosServiceDiscovery.java:95) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.common.function.ThrowableConsumer.execute(ThrowableConsumer.java:49) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.common.function.ThrowableConsumer.execute(ThrowableConsumer.java:63) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.doRegister(NacosServiceDiscovery.java:93) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.register(AbstractServiceDiscovery.java:145) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.update(AbstractServiceDiscovery.java:161) ~[dubbo-3.2.7.jar:3.2.7]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.apache.dubbo.registry.client.metadata.ServiceInstanceMetadataUtils.refreshMetadataAndInstance(ServiceInstanceMetadataUtils.java:230) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.refreshServiceInstance(DefaultApplicationDeployer.java:943) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.registerServices(DefaultModuleDeployer.java:403) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:184) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:148) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:155) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:141) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52) ~[dubbo-3.2.7.jar:3.2.7]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:445) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:969) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.6.jar:3.1.6]
	at io.github.hpsocket.soa.framework.web.server.main.AppStarter.main(AppStarter.java:39) ~[classes/:?]
2023-12-13 14:44:28.106 WARN  [main] o.a.d.common.logger.log4j2.Log4j2Logger#warn(L:86) ->  [DUBBO] Failed to request nacos naming server. Exceed retry max times.Try times: 11, dubbo version: 3.2.7, current host: 192.168.56.1, error code: 1-37. This may be caused by , go to https://dubbo.apache.org/faq/1/37 to find instructions. 
com.alibaba.nacos.api.exception.NacosException: wrong group name prefix of instance service name! it should be: DUBBO_GROUP, Instance: Instance{instanceId='null', ip='192.168.56.1', port=6002, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='null', serviceName='hp-demo-infra-basic-service', metadata={dubbo.endpoints=[{"port":6002,"protocol":"tri"}], dubbo.metadata-service.url-params={"prefer.serialization":"fastjson2,hessian2","version":"1.0.0","dubbo":"2.0.2","release":"3.2.7","side":"provider","port":"6002","protocol":"tri"}, dubbo.metadata.revision=6a960ac1cfd76a1adaaf3a3104e262dc, dubbo.metadata.storage-type=local}}
	at com.alibaba.nacos.client.naming.NacosNamingService.checkAndStripGroupNamePrefix(NacosNamingService.java:490) ~[nacos-client-2.3.0.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.3.0.jar:?]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.lambda$registerInstance$5(NacosNamingServiceWrapper.java:121) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.accept(NacosNamingServiceWrapper.java:465) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:121) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.lambda$doRegister$0(NacosServiceDiscovery.java:95) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.common.function.ThrowableConsumer.execute(ThrowableConsumer.java:49) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.common.function.ThrowableConsumer.execute(ThrowableConsumer.java:63) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.doRegister(NacosServiceDiscovery.java:93) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.register(AbstractServiceDiscovery.java:145) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.update(AbstractServiceDiscovery.java:161) ~[dubbo-3.2.7.jar:3.2.7]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.apache.dubbo.registry.client.metadata.ServiceInstanceMetadataUtils.refreshMetadataAndInstance(ServiceInstanceMetadataUtils.java:230) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.refreshServiceInstance(DefaultApplicationDeployer.java:943) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.registerServices(DefaultModuleDeployer.java:403) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:184) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:148) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:155) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:141) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52) ~[dubbo-3.2.7.jar:3.2.7]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:445) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:969) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.6.jar:3.1.6]
	at io.github.hpsocket.soa.framework.web.server.main.AppStarter.main(AppStarter.java:39) ~[classes/:?]
2023-12-13 14:44:28.106 ERROR [main] o.a.d.common.logger.log4j2.Log4j2Logger#error(L:101) ->  [DUBBO] Refresh instance and metadata error., dubbo version: 3.2.7, current host: 192.168.56.1, error code: 5-12. This may be caused by , go to https://dubbo.apache.org/faq/5/12 to find instructions. 
java.lang.RuntimeException: wrong group name prefix of instance service name! it should be: DUBBO_GROUP, Instance: Instance{instanceId='null', ip='192.168.56.1', port=6002, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='null', serviceName='hp-demo-infra-basic-service', metadata={dubbo.endpoints=[{"port":6002,"protocol":"tri"}], dubbo.metadata-service.url-params={"prefer.serialization":"fastjson2,hessian2","version":"1.0.0","dubbo":"2.0.2","release":"3.2.7","side":"provider","port":"6002","protocol":"tri"}, dubbo.metadata.revision=6a960ac1cfd76a1adaaf3a3104e262dc, dubbo.metadata.storage-type=local}}
	at org.apache.dubbo.common.function.ThrowableConsumer.execute(ThrowableConsumer.java:51) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.common.function.ThrowableConsumer.execute(ThrowableConsumer.java:63) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.doRegister(NacosServiceDiscovery.java:93) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.register(AbstractServiceDiscovery.java:145) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.update(AbstractServiceDiscovery.java:161) ~[dubbo-3.2.7.jar:3.2.7]
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at org.apache.dubbo.registry.client.metadata.ServiceInstanceMetadataUtils.refreshMetadataAndInstance(ServiceInstanceMetadataUtils.java:230) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.refreshServiceInstance(DefaultApplicationDeployer.java:943) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.registerServices(DefaultModuleDeployer.java:403) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.startSync(DefaultModuleDeployer.java:184) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:148) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:155) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:141) ~[dubbo-3.2.7.jar:3.2.7]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:52) ~[dubbo-3.2.7.jar:3.2.7]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:174) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:167) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:445) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:969) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:619) ~[spring-context-6.0.14.jar:6.0.14]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:738) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:440) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-3.1.6.jar:3.1.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-3.1.6.jar:3.1.6]
	at io.github.hpsocket.soa.framework.web.server.main.AppStarter.main(AppStarter.java:39) ~[classes/:?]
```

**Expected behavior**
不报错

**Actually behavior**
报错，服务注册失败

**How to Reproduce**
1. 启动dubbo服务

**Desktop (please complete the following information):**
 - OS: win 10
 - Version: nacos-client 2.3.0
 - SDK dubbo

**Comment by KomachiSion** [comment]
duplicate with #11493

**Comment by honorjoey** [comment]
升级到2.3.3可解决
