### ISSUE TITLE
nacos2.2.3 + nginx1.24.0 搭建集群，服务端一切启动正常，就是服务注册不了，请看报错信息~

### ISSUE THREAD

**Issue by cenlm** [alibaba/nacos#11566]
#user  nobody;
worker_processes  auto;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

pid logs/nginx.pid;

events {
    worker_connections  1024;
}

http {

   upstream nacos_cluster_http {
        server 192.168.3.101:8848;
  server 192.168.3.101:8888;
  server 192.168.3.101:8890;
  server 192.168.3.101:8892;
     }

    server {
        listen 8008;
        location / {
          proxy_pass http://nacos_cluster_http;
        }

   }

  upstream nacos_cluster_grpc {
    server 192.168.3.101:9848;
    server 192.168.3.101:9888;
    server 192.168.3.101:9890;
    server 192.168.3.101:9892;
  }

  server {
    listen 9008;
     location / {
     grpc_pass grpc://nacos_cluster_grpc;
      }
  }

}

2023-12-27 21:47:11.252  INFO 18460 --- [  restartedMain] com.alibaba.nacos.common.remote.client   : [dd47c15c-a18c-40ba-b768-ec7d3383443b] Try to connect to server on start up, server: {serverIp = '192.168.228.131', server main port = 8008}
2023-12-27 21:47:11.263 ERROR 18460 --- [  restartedMain] c.a.n.c.remote.client.grpc.GrpcClient    : Server check fail, please check server 192.168.228.131 ,port **9008** is available , error ={}

java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: INTERNAL: http2 exception
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:445) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:148) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:264) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:390) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.start(NamingGrpcClientProxy.java:96) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.<init>(NamingGrpcClientProxy.java:89) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:76) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:95) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:81) [nacos-client-2.0.4.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_333]

9008 是grpc端口，很明显使用到grpc通信。

另外，也配置过tcp方式转发：
stream {
  upstream nacos_cluster_tcp {
    server 192.168.3.101:8048;
    server 192.168.3.101:8888;
    server 192.168.3.101:8890;
    server 192.168.3.101:8892;
  }

  server {
    listen 8008;
      proxy_pass nacos_cluster_tcp;
  }
}
也还是注册不了。
官方文档说“使用VIP/nginx请求时，需要配置成TCP转发，不能配置http2转发，否则连接会被nginx断开。” 所有方式都弄过了，要么根本启动不了，要么启动了也注册不了~
不是很多大厂都在使用nacos吗？难道都没有使用nginx+nacos 搭建集群的吗？真费解~ 各位大佬在哪里？出来支支招呀~

**Comment by seedscoder** [comment]
```
upstream nacos_cluster_grpc {
      server 192.168.3.101:9848;
      server 192.168.3.101:9888;
      server 192.168.3.101:9890;
      server 192.168.3.101:9892;
}

```

你的这串配置是不是放在 `http {}` 块内部的？这样的话，那 GRPC 的代理配置的位置就不对了

**Comment by seedscoder** [comment]
```
http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                      '$status $body_bytes_sent "$http_referer" '
                      '"$http_user_agent" "$http_x_forwarded_for"';

    access_log  /var/log/nginx/access.log  main;

    sendfile        on;
    #tcp_nopush     on;

    keepalive_timeout  65;

    #gzip  on;

    include /etc/nginx/conf.d/*.conf;
}



stream {
    upstream nacos-server-grpc {
        server nacos1:9848;
        server nacos2:9848;
        server nacos3:9848;
    }
    server {
        listen 9848;
        proxy_pass nacos-server-grpc;
    }
}
```

**Comment by cenlm** [comment]
> ```
> http {
>     include       /etc/nginx/mime.types;
>     default_type  application/octet-stream;
> 
>     log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
>                       '$status $body_bytes_sent "$http_referer" '
>                       '"$http_user_agent" "$http_x_forwarded_for"';
> 
>     access_log  /var/log/nginx/access.log  main;
> 
>     sendfile        on;
>     #tcp_nopush     on;
> 
>     keepalive_timeout  65;
> 
>     #gzip  on;
> 
>     include /etc/nginx/conf.d/*.conf;
> }
> 
> 
> 
> stream {
>     upstream nacos-server-grpc {
>         server nacos1:9848;
>         server nacos2:9848;
>         server nacos3:9848;
>     }
>     server {
>         listen 9848;
>         proxy_pass nacos-server-grpc;
>     }
> }
> ```

你的配置虽然nginx服务器能跑起来，但还是注册不了~ 你这也还是tcp转发，处理不了客户端与服务端的grpc通信。
虽然我的配置：
`upstream nacos_cluster_grpc {
server 192.168.3.101:9848;
server 192.168.3.101:9888;
server 192.168.3.101:9890;
server 192.168.3.101:9892;
}

server {
listen 9008;
location / {
grpc_pass grpc://nacos_cluster_grpc; #grpc_pass 指定grpc代理，nginx官网文档有说明
}
}`
nginx能跑起来，但也还是注册不了~
通过报错信息，
Caused by: com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: Connection refused: no further information: /192.168.228.131:9008
Caused by: java.net.ConnectException: Connection refused: no further information
可知 9008 [是客户端grpc请求服务端（nginx）的端口，是与主端口 8008 的偏移量](https://nacos.io/zh-cn/docs/v2/guide/admin/cluster-mode-quick-start.html) ，因为nginx只监听了8008端口，所以客户端想要与nginx 9008端口通信的时候就报错了。这样的话，难道在nginx上要通过计算主端口的偏移量，然后一个个的进行反向代理配置吗？这~

**Comment by cenlm** [comment]
> ```
> http {
>     include       /etc/nginx/mime.types;
>     default_type  application/octet-stream;
> 
>     log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
>                       '$status $body_bytes_sent "$http_referer" '
>                       '"$http_user_agent" "$http_x_forwarded_for"';
> 
>     access_log  /var/log/nginx/access.log  main;
> 
>     sendfile        on;
>     #tcp_nopush     on;
> 
>     keepalive_timeout  65;
> 
>     #gzip  on;
> 
>     include /etc/nginx/conf.d/*.conf;
> }
> 
> 
> 
> stream {
>     upstream nacos-server-grpc {
>         server nacos1:9848;
>         server nacos2:9848;
>         server nacos3:9848;
>     }
>     server {
>         listen 9848;
>         proxy_pass nacos-server-grpc;
>     }
> }
> ```

`#user  nobody;
worker_processes  auto;

#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

pid logs/nginx.pid;


events {
    worker_connections  1024;
}

http {
   default_type  application/octet-stream;
   sendfile        on;
    keepalive_timeout  65;
}

stream {
  upstream nacos_cluster {
    server 192.168.3.101:8848;
    server 192.168.3.101:8888;
    server 192.168.3.101:8890;
    server 192.168.3.101:8892;
  }

  server {
    listen 8008;
     proxy_pass nacos_cluster;
  }

  upstream nacos_cluster_9008 {
    server 192.168.3.101:9848;
    server 192.168.3.101:9888;
    server 192.168.3.101:9890;
    server 192.168.3.101:9892;
  }

  server {
    listen 9008;
     proxy_pass nacos_cluster_9008;
  }

}`

太炸裂了~ 终于可以了！主端口（+1000）的偏移量 9008 是要再弄一份反向代理配置进行转发，这，第一次整这活，真废脑，今晚加餐-兄弟！感谢帮助！你的tcp转发配置是对的~ 官方文档说明：使用VIP/nginx请求时，需要配置成TCP转发，不能配置http2转发，否则连接会被nginx断开。

**Comment by imkiven** [comment]
8848也要配置 stream ，不能配置 http吗

**Comment by jonycw** [comment]
服了 搞了大半天 偏移量固定+1000这操作绝了。。。
