### ISSUE TITLE
nacos2.1.1服务注册后一直会报连接失败

### ISSUE THREAD

**Issue by ponyton** [alibaba/nacos#11578]
**Describe the bug**
服务注册上nacos之后每过一段时间会断开

**Expected behavior**
应用内不应显示连接失败、位置服务等报错

**Actually behavior**
[eesa-user-pools:10.244.64.52:7007] 2024-01-01 03:19:39.622 ERROR 1 [-] [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming          request: /nacos/v1/ns/instance/beat failed, servers: [172.27.98.110:30064], code: 500, msg: java.net.UnknownHostException: nacos-1.nacos-headless.dev.svc.cluster.local
[eesa-user-pools:10.244.64.52:7007] 2024-01-01 03:19:39.623 ERROR 1 [-] [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming          [CLIENT-BEAT] failed to send beat: {"port":7007,"ip":"10.244.64.52","weight":1.0,"serviceName":"DEFAULT_GROUP@@eesa-user-pools","cluster":"DEFAULT","metadata":{"preserved.register.source":"SPRING_CLOUD"},"scheduled":false,"period":5000,"stopped":false}, code: 500, msg: failed to req API:/nacos/v1/ns/instance/beat after all servers([172.27.98.110:30064]) tried: ErrCode:500, ErrMsg:java.net.UnknownHostException: nacos-1.nacos-headless.dev.svc.cluster.local
[eesa-user-pools:10.244.64.52:7007] 2024-01-01 05:20:20.829 ERROR 1 [-] [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming          [NA] failed to request
com.alibaba.nacos.api.exception.NacosException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
        at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:433)
        at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
[eesa-user-pools:10.244.64.52:7007] 2024-01-02 08:19:42.301 ERROR 1 [-] [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming          [NA] failed to request
com.alibaba.nacos.api.exception.NacosException: java.net.UnknownHostException: nacos-1.nacos-headless.dev.svc.cluster.local: Name or service not known
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
        at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:433)
        at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
以上是服务的报错信息，每隔一段时间可能是几小时会出现一次，但是在nacos中能看到服务是已经注册上了的
![image](https://github.com/alibaba/nacos/assets/119477983/5f311a50-7129-471c-ada7-26219e707343)

**Comment by godhth** [comment]
你这报错不是UnknownHostException么检查下dns或者headless正不正常吧
