### ISSUE TITLE
nacos2.2.3开启鉴权，gateway动态网关路由 返回403

### ISSUE THREAD

**Issue by bqey** [alibaba/nacos#11591]
![image](https://github.com/alibaba/nacos/assets/86216991/46ec588e-95a1-4a5a-a891-1440b4b7b643)

web使用用户名密码登录查看都没有问题
程序配置
spring:
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        username: nacos
        password: huaxin
      config:
        server-addr: 127.0.0.1:8848
        username: nacos
        password: huaxin
        namespace: dev
        group: BaseServiceGroup
启动报错

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2024-01-05 10:36:41.675 ERROR 9452 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'routeConfigListener': Invocation of init method failed; nested exception is ErrCode:403, ErrMsg:http error, code=403,msg=user not found!,dataId=gateway-json-routes,group=BaseServiceGroup,tenant=dev
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) ~[spring-boot-2.6.13.jar:2.6.13]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745) ~[spring-boot-2.6.13.jar:2.6.13]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420) ~[spring-boot-2.6.13.jar:2.6.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.6.13.jar:2.6.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.13.jar:2.6.13]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.13.jar:2.6.13]
	at com.fallen.gateway.FallenGatewayApplication.main(FallenGatewayApplication.java:14) ~[classes/:na]
依赖是这些
![image](https://github.com/alibaba/nacos/assets/86216991/42082a0b-52c3-4bb3-b0da-db67a7ad3aa6)
网上的方法都尝试了，没能解决，降包也不行，关闭鉴权后就正常了

**Comment by bqey** [comment]
问题解决了，我并没有测试服务注册与发现，而是启动动态路由的时候发现的问题，只在配置里加了用户名密码，
Nacos动态路由的监听器没有添加上用户名密码
![image](https://github.com/alibaba/nacos/assets/86216991/c8087c1d-137b-4b04-9a99-6bc0700e842a)

**Comment by springcloudconf** [comment]
我想请问一下，你们都是谁啊，为啥天天给我发邮件啊？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年1月5日(星期五) 上午10:50
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[alibaba/nacos] nacos2.2.3开启鉴权，返回403 (Issue #11591)





 
image.png (view on web)
 
web使用用户名密码登录查看都没有问题
 程序配置
 spring:
 main:
 web-application-type: reactive
 cloud:
 nacos:
 discovery:
 username: nacos
 password: huaxin
 config:
 server-addr: 127.0.0.1:8848
 username: nacos
 password: huaxin
 namespace: dev
 group: BaseServiceGroup
 启动报错
 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
 2024-01-05 10:36:41.675 ERROR 9452 --- [           main] o.s.boot.SpringApplication               : Application run failed
 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'routeConfigListener': Invocation of init method failed; nested exception is ErrCode:403, ErrMsg:http error, code=403,msg=user not found!,dataId=gateway-json-routes,group=BaseServiceGroup,tenant=dev
 at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.23.jar:5.3.23]
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.23.jar:5.3.23]
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.23.jar:5.3.23]
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.23.jar:5.3.23]
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
 at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
 at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
 at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
 at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
 at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
 at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
 at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) ~[spring-boot-2.6.13.jar:2.6.13]
 at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745) ~[spring-boot-2.6.13.jar:2.6.13]
 at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420) ~[spring-boot-2.6.13.jar:2.6.13]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.6.13.jar:2.6.13]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.13.jar:2.6.13]
 at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.13.jar:2.6.13]
 at com.fallen.gateway.FallenGatewayApplication.main(FallenGatewayApplication.java:14) ~[classes/:na]
 依赖是这些
 image.png (view on web)
 网上的方法都尝试了，没能解决，降包也不行，关闭鉴权后就正常了

**Comment by bqey** [comment]
呃，你好，打扰了，我不清楚为什么会发送到你的邮箱里，我在github上提交了一个问题，现在已经解决了，如果你不是作者的话，那可能是作者将你设置为
协助解决lssues之类的把，我也遇见过这种问题，当时可烦了






------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2024年1月5日(星期五) 中午11:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] nacos2.2.3开启鉴权，gateway动态网关路由 返回403 (Issue #11591)





 我想请问一下，你们都是谁啊，为啥天天给我发邮件啊？ 
 
 
 ------------------&amp;nbsp;原始邮件&amp;nbsp;------------------ 
 发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&amp;gt;; 
 发送时间:&amp;nbsp;2024年1月5日(星期五) 上午10:50 
 ***@***.***&amp;gt;; 
 ***@***.***&amp;gt;; 
 主题:&amp;nbsp;[alibaba/nacos] nacos2.2.3开启鉴权，返回403 (Issue #11591) 
 
 
 
 
 
   
 image.png (view on web) 
   
 web使用用户名密码登录查看都没有问题 
  程序配置 
  spring: 
  main: 
  web-application-type: reactive 
  cloud: 
  nacos: 
  discovery: 
  username: nacos 
  password: huaxin 
  config: 
  server-addr: 127.0.0.1:8848 
  username: nacos 
  password: huaxin 
  namespace: dev 
  group: BaseServiceGroup 
  启动报错 
   
 Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
  2024-01-05 10:36:41.675 ERROR 9452 --- [           main] o.s.boot.SpringApplication               : Application run failed 
   
 org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'routeConfigListener': Invocation of init method failed; nested exception is ErrCode:403, ErrMsg:http error, code=403,msg=user not found!,dataId=gateway-json-routes,group=BaseServiceGroup,tenant=dev 
  at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160) ~[spring-beans-5.3.23.jar:5.3.23] 
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440) ~[spring-beans-5.3.23.jar:5.3.23] 
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796) ~[spring-beans-5.3.23.jar:5.3.23] 
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.23.jar:5.3.23] 
  at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23] 
  at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23] 
  at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23] 
  at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23] 
  at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23] 
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23] 
  at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23] 
  at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23] 
  at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:64) ~[spring-boot-2.6.13.jar:2.6.13] 
  at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745) ~[spring-boot-2.6.13.jar:2.6.13] 
  at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420) ~[spring-boot-2.6.13.jar:2.6.13] 
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:307) ~[spring-boot-2.6.13.jar:2.6.13] 
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.13.jar:2.6.13] 
  at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.13.jar:2.6.13] 
  at com.fallen.gateway.FallenGatewayApplication.main(FallenGatewayApplication.java:14) ~[classes/:na] 
  依赖是这些 
  image.png (view on web) 
  网上的方法都尝试了，没能解决，降包也不行，关闭鉴权后就正常了

**Comment by KomachiSion** [comment]
应该是你github点了watch社区。范围包含了issue
