### ISSUE TITLE
服务启动时nacos没启动报nacos连接不上错误，启动nacos后无法自动重连nacos，必须重启服务才行

### ISSUE THREAD

**Issue by justinbaby** [alibaba/nacos#11638]
**Describe the bug**
服务启动时nacos没启动报nacos连接不上错误，启动nacos后无法自动重连nacos，必须重启服务才行

**Expected behavior**
A  自动重连nacos

**Actually behavior**
A 无法重连

**How to Reproduce**
1. 启动springboot微服务，不启动nacos
2. 启动nacos
3. 提示“Grpc Connection is disconnect, skip current redo task”

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 2.0.3, nacos-client 2.0.3]
 - Module [e.g. nacos.client.naming.remote.gprc.redo]
 - SDK [e.g. original, spring-cloud-alibaba-nacos]

**Additional context**

**Comment by KomachiSion** [comment]
nacos会无限重连的， 但是旧版本客户端如果注册失败的话不会加入的redo里， 新版本已经修复了，可以升级下nacos-client再试。

**Comment by justinbaby** [comment]
先启动服务，再启动nacos，这里重连时isConnected一直是false， 升级了nacos也不行吧？
<img width="649" alt="image" src="https://github.com/alibaba/nacos/assets/12798438/ca934c49-62a3-4571-a81c-8df09e24f7f5">

**Comment by justinbaby** [comment]
> nacos会无限重连的， 但是旧版本客户端如果注册失败的话不会加入的redo里， 新版本已经修复了，可以升级下nacos-client再试。

**Comment by justinbaby** [comment]
> nacos会无限重连的， 但是旧版本客户端如果注册失败的话不会加入的redo里， 新版本已经修复了，可以升级下nacos-client再试。

 2.0.3版本，先开微服务再开nacos还是不行

**Comment by zerolincku** [comment]
使用的 2.3.0 的客户端也出现了这个情况，报了这个错误，但是项目没有停止运行，所用 docker 不会重启容器，nacos 服务重启启动后，客户端也没有重新注册上来
`org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is java.lang.reflect.UndeclaredThrowableException
2024-01-15 11:35:26     at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:357) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
2024-01-15 11:35:26     at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:156) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:124) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:938) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:66) ~[spring-boot-2.7.17.jar!/:2.7.17]
2024-01-15 11:35:26     at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.7.17.jar!/:2.7.17]
2024-01-15 11:35:26     at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) ~[spring-boot-2.7.17.jar!/:2.7.17]
2024-01-15 11:35:26     at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.17.jar!/:2.7.17]
2024-01-15 11:35:26     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300) ~[spring-boot-2.7.17.jar!/:2.7.17]
2024-01-15 11:35:26     at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289) ~[spring-boot-2.7.17.jar!/:2.7.17]
2024-01-15 11:35:26     at com.jshc.qiaoliangateway.QiaolianGatewayApplication.main(QiaolianGatewayApplication.java:12) ~[classes!/:na]
2024-01-15 11:35:26     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
2024-01-15 11:35:26     at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
2024-01-15 11:35:26     at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
2024-01-15 11:35:26     at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
2024-01-15 11:35:26     at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:na]
2024-01-15 11:35:26     at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:na]
2024-01-15 11:35:26     at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:na]
2024-01-15 11:35:26     at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) ~[app.jar:na]
2024-01-15 11:35:26 Caused by: java.lang.reflect.UndeclaredThrowableException: null
2024-01-15 11:35:26     at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:147) ~[spring-core-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:83) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.0.5.0.jar!/:2021.0.5.0]
2024-01-15 11:35:26     at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:232) ~[spring-cloud-commons-3.1.5.jar!/:3.1.5]
2024-01-15 11:35:26     at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.0.5.0.jar!/:2021.0.5.0]
2024-01-15 11:35:26     at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:133) ~[spring-cloud-commons-3.1.5.jar!/:3.1.5]
2024-01-15 11:35:26     at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:98) ~[spring-cloud-commons-3.1.5.jar!/:3.1.5]
2024-01-15 11:35:26     at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:86) ~[spring-cloud-commons-3.1.5.jar!/:3.1.5]
2024-01-15 11:35:26     at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) ~[spring-cloud-commons-3.1.5.jar!/:3.1.5]
2024-01-15 11:35:26     at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     at org.springframework.boot.web.reactive.context.WebServerManager.start(WebServerManager.java:57) ~[spring-boot-2.7.17.jar!/:2.7.17]
2024-01-15 11:35:26     at org.springframework.boot.web.reactive.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:40) ~[spring-boot-2.7.17.jar!/:2.7.17]
2024-01-15 11:35:26     at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:179) ~[spring-context-5.3.30.jar!/:5.3.30]
2024-01-15 11:35:26     ... 22 common frames omitted
2024-01-15 11:35:26 Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING
2024-01-15 11:35:26     at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:647) ~[nacos-client-2.3.0.jar!/:na]
2024-01-15 11:35:26     at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:626) ~[nacos-client-2.3.0.jar!/:na]
2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:450) ~[nacos-client-2.3.0.jar!/:na]
2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:249) ~[nacos-client-2.3.0.jar!/:na]
2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerServiceForEphemeral(NamingGrpcClientProxy.java:144) ~[nacos-client-2.3.0.jar!/:na]
2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:136) ~[nacos-client-2.3.0.jar!/:na]
2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:98) ~[nacos-client-2.3.0.jar!/:na]
2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:146) ~[nacos-client-2.3.0.jar!/:na]
2024-01-15 11:35:26     at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:75) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.0.5.0.jar!/:2021.0.5.0]
2024-01-15 11:35:26     ... 36 common frames omitted
2024-01-15 11:35:26`

**Comment by KomachiSion** [comment]
我自己测试，是没问题的， 先启动nacos-client 连接localhost， 并且注册一个服务，再启动nacos-server。

**Comment by KomachiSion** [comment]
> 使用的 2.3.0 的客户端也出现了这个情况，报了这个错误，但是项目没有停止运行，所用 docker 不会重启容器，nacos 服务重启启动后，客户端也没有重新注册上来
> 
> ```
> 2024-01-15 11:35:26 Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING
> 2024-01-15 11:35:26     at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:647) ~[nacos-client-2.3.0.jar!/:na]
> 2024-01-15 11:35:26     at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:626) ~[nacos-client-2.3.0.jar!/:na]
> 2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:450) ~[nacos-client-2.3.0.jar!/:na]
> 2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:249) ~[nacos-client-2.3.0.jar!/:na]
> 2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerServiceForEphemeral(NamingGrpcClientProxy.java:144) ~[nacos-client-2.3.0.jar!/:na]
> 2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:136) ~[nacos-client-2.3.0.jar!/:na]
> 2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:98) ~[nacos-client-2.3.0.jar!/:na]
> 2024-01-15 11:35:26     at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:146) ~[nacos-client-2.3.0.jar!/:na]
> 2024-01-15 11:35:26     at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:75) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.0.5.0.jar!/:2021.0.5.0]
> 2024-01-15 11:35:26     ... 36 common frames omitted
> 2024-01-15 11:35:26
> ```

你这个报错是没连上nacos， 实际上一直在重试。

**Comment by KomachiSion** [comment]
No more response from author, and the new version seems solved the problem.

**Comment by cxhello** [comment]
> > nacos会无限重连的， 但是旧版本客户端如果注册失败的话不会加入的redo里， 新版本已经修复了，可以升级下nacos-client再试。
> 
> 2.0.3版本，先开微服务再开nacos还是不行

哥们，我也遇到这个问题了，你解决了吗？

**Comment by cxhello** [comment]
> > > > nacos会无限重连的， 但是旧版本客户端如果注册失败的话不会加入的redo里， 新版本已经修复了，可以升级下nacos-client再试。
> > > 
> > > 
> > > 2.0.3版本，先开微服务再开nacos还是不行
> > 
> > 
> > 哥们，我也遇到这个问题了，你解决了吗？
> 
> 没有

好的，谢谢。

**Comment by AhDEV-free** [comment]
这个问题有解决吗
