### ISSUE TITLE
nacos集群2.2.1 PUSH-FAIL

### ISSUE THREAD

**Issue by lkygit01** [alibaba/nacos#11700]
centos7部署3台nacos集群，通过nginx轮询反向代理。
nacos的naming-push.log一直在刷
```
2024-01-20 00:00:11,086 INFO serviceName: DEFAULT_GROUP@@dc-authentication-service changed, schedule push for: resolve_failed:39964, agent: Nacos-Java-Client:v1.4.2, key: null

2024-01-20 00:00:24,781 INFO DEFAULT_GROUP@@dc-authentication-service is changed, add it to push queue.

2024-01-20 00:00:24,796 ERROR [NACOS-PUSH] failed to compress data: {type=dom, data={"name":"DEFAULT_GROUP@@dc-authentication-service","clusters":"DEFAULT","cacheMillis":10000,"hosts":[{"instanceId":"192.168.20.142#8082#DEFAULT#DEFAULT_GROUP@@dc-authentication-service","ip":"192.168.20.142","port":8082,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@dc-authentication-service","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000},{"instanceId":"192.168.20.139#8082#DEFAULT#DEFAULT_GROUP@@dc-authentication-service","ip":"192.168.20.139","port":8082,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@dc-authentication-service","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000},{"instanceId":"192.168.20.141#8082#DEFAULT#DEFAULT_GROUP@@dc-authentication-service","ip":"192.168.20.141","port":8082,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@dc-authentication-service","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}],"lastRefTime":1705680024781,"checksum":"","allIPs":false,"reachProtectionThreshold":false,"valid":true}, lastRefTime=24582567118132550} to client: resolve_failed:45665, error: {}

java.lang.NullPointerException: null
        at com.alibaba.nacos.naming.push.UdpPushService.prepareAckEntry(UdpPushService.java:126)
        at com.alibaba.nacos.naming.push.UdpPushService.prepareAckEntry(UdpPushService.java:115)
        at com.alibaba.nacos.naming.push.UdpPushService.prepareAckEntry(UdpPushService.java:101)
        at com.alibaba.nacos.naming.push.UdpPushService.pushDataWithCallback(UdpPushService.java:89)
        at com.alibaba.nacos.naming.push.v2.executor.PushExecutorUdpImpl.doPushWithCallback(PushExecutorUdpImpl.java:54)
        at com.alibaba.nacos.naming.push.v2.executor.PushExecutorDelegate.doPushWithCallback(PushExecutorDelegate.java:53)
        at com.alibaba.nacos.naming.push.v2.task.PushExecuteTask.run(PushExecuteTask.java:68)
        at com.alibaba.nacos.common.task.engine.TaskExecuteWorker$InnerWorker.run(TaskExecuteWorker.java:120)
```

naming-server.log里服务一直在刷不停的上下线

```
2024-01-26 00:02:10,302 INFO Client connection 192.168.20.141:56659#true connect

2024-01-26 00:02:43,666 INFO Client connection 192.168.20.142:53491#true disconnect, remove instances and subscribers

2024-01-26 00:02:48,666 INFO Client connection resolve_failed:53192#true disconnect, remove instances and subscribers

2024-01-26 00:02:53,630 INFO Client connection 192.168.20.142:53491#true connect

2024-01-26 00:03:05,745 INFO Client connection 192.168.20.141:56659#true disconnect, remove instances and subscribers

2024-01-26 00:03:14,752 INFO Client connection 192.168.20.141:56659#true connect

2024-01-26 00:03:16,895 INFO Client connection 192.168.20.141:42918#true disconnect, remove instances and subscribers

2024-01-26 00:03:28,745 INFO Client connection resolve_failed:53192#true connect

2024-01-26 00:03:34,908 INFO Client connection 192.168.20.141:42918#true connect

2024-01-26 00:03:45,776 INFO Client connection 192.168.20.141:56659#true disconnect, remove instances and subscribers

2024-01-26 00:03:50,318 INFO Client connection 192.168.20.141:56659#true connect
```

**Comment by KomachiSion** [comment]
两个问题，推送失败看起来是压缩数据的时候时候失败了， 可以根据堆栈排查一下，不过UDP方式已经不推荐了，建议升级到nacos2.x的客户端，使用grpc来进行推送。


至于里服务一直在刷不停的上下线， 和推送失败没关系， 是应用节点的续约没续约上，需要查一下应用是否有问题。

**Comment by lkygit01** [comment]
> 两个问题，推送失败看起来是压缩数据的时候时候失败了， 可以根据堆栈排查一下，不过UDP方式已经不推荐了，建议升级到nacos2.x的客户端，使用grpc来进行推送。
> 
> 至于里服务一直在刷不停的上下线， 和推送失败没关系， 是应用节点的续约没续约上，需要查一下应用是否有问题。

嗯嗯，客户端版本的问题正在升级。根据堆栈排查请指导一下

**Comment by KomachiSion** [comment]
![image](https://github.com/alibaba/nacos/assets/37170243/cf87f607-40d8-411f-aa04-6951ff793419)

反正我从代码来看， 应该还是网络环境的问题，大概率是InetSocketAddress没拿到对应需要推送的ip或者端口。

**Comment by KomachiSion** [comment]
InetSocketAddress 是java的 native类， 里面很多native实现获取系统参数。 因此网络问题的可能性更大。

或者您自行进行debug，arthas等方法在环境中进行追踪， 找到null的内容。

**Comment by KomachiSion** [comment]
No more response from author, It seems env problem.
