### ISSUE TITLE
nacos service start error

### ISSUE THREAD

**Issue by 1346735074** [alibaba/nacos#1172]
```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'communicationController' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-1.0.0.jar!/com/alibaba/nacos/config/server/controller/CommunicationController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
```

**Comment by 1346735074** [comment]
`Caused by: java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
        at com.alibaba.nacos.config.server.service.dump.DumpService.init(DumpService.java:155)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
        ... 40 common frames omitted`

**Comment by crazy6995** [comment]
你可能在用MySQL8+
要支持8+还需要引入plugins(mysql8的连接库)

**Comment by 1346735074** [comment]
数据库是同一个  本地启动没有问题

**Comment by fthmko** [comment]
通过docker启动，自己指定的mysql，也报相同的错误，解决方案如下，供参考。

从日志中看到有一句
`Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Table 'nacos_dev.config_info' doesn't exist`
我猜是没有自动创建表。
下载release包，先在数据库执行里面的conf/nacos-mysql.sql，再启动就OK了。

**Comment by eaglesy** [comment]
> 数据库是同一个 本地启动没有问题

我也是这个错误为啥

**Comment by TanqiZhou** [comment]
使用MySQL8.0渠驱动，修改com.mysql.cj.jdbc.MysqlDataSource

**Comment by xin-hu** [comment]
我用的nacos-server-1.1.4，为什么没有/plugins/文件夹？
