### ISSUE TITLE
通过 Flink 命令提交作业时，Flink 客户端会抛出如下的异常信息，但作业却能正常提交到集群执行。

### ISSUE THREAD

**Issue by colacatCN** [alibaba/nacos#11735]
通过 Flink 命令提交作业时，Flink 客户端会抛出如下的异常信息，但作业却能正常提交到集群执行。

Exception in thread "Thread-1" java.lang.NoClassDefFoundError: com/alibaba/nacos/common/http/DefaultHttpClientFactory
at com.alibaba.nacos.common.http.HttpClientBeanHolder.shutdown(HttpClientBeanHolder.java:110)
at com.alibaba.nacos.common.http.HttpClientBeanHolder.access$000(HttpClientBeanHolder.java:35)
at com.alibaba.nacos.common.http.HttpClientBeanHolder$1.run(HttpClientBeanHolder.java:50)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: com.alibaba.nacos.common.http.DefaultHttpClientFactory
at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
at org.apache.flink.util.FlinkUserCodeClassLoader.loadClassWithoutExceptionHandling(FlinkUserCodeClassLoader.java:67)
at org.apache.flink.util.ChildFirstClassLoader.loadClassWithoutExceptionHandling(ChildFirstClassLoader.java:74)
at org.apache.flink.util.FlinkUserCodeClassLoader.loadClass(FlinkUserCodeClassLoader.java:51)
at java.lang.ClassLoader.loadClass(ClassLoader.java:357)

把 Jar 反编译后内部是存在 com.alibaba.nacos.common.http.DefaultHttpClientFactory 这个类的 class 文件。进一步 debug 类加载的过程后发现 JVM 并没有扫描到这个 class 文件，不太清楚为什么会出现这个问题，麻烦大佬们帮忙看看这个问题。所使用的 nacos-client 版本是 1.4.1。

![image](https://github.com/alibaba/nacos/assets/22804423/8cf6c13b-2fd3-4fc4-aba5-584f3221af47)
![image](https://github.com/alibaba/nacos/assets/22804423/479a21fa-aa64-479a-92e4-59f545465375)
![image](https://github.com/alibaba/nacos/assets/22804423/be866ccf-aa18-444e-86b5-8f7162670aab)
![2481a19020e651662eb51544e8335e0](https://github.com/alibaba/nacos/assets/22804423/9d1b2b85-7a7e-4d6a-a2e4-475e78195eca)
![image](https://github.com/alibaba/nacos/assets/22804423/3b6b5a82-4ba6-44ff-ac34-4aa47526c95e)

**Comment by KomachiSion** [comment]
应该和这个类加载器时flink自己实现的有关， 自定义的类加载器可能阻断了标准类加载器的类加载和扫描过程。应该不是nacos的问题。
