### ISSUE TITLE
 Nacos startup error

### ISSUE THREAD

**Issue by sennyhan** [alibaba/nacos#11750]
I encountered an error while starting nacos. How can I resolve this?  daily record:

2024-02-01 18:02:18,605 INFO The server IP list of Nacos is [nacos-sts-0.nacos-svc.dop.svc.cluster.local:8848, nacos-sts-1.nacos-svc.dop.svc.cluster.local:8848, nacos-sts-2.nacos-svc.dop.svc.cluster.local:8848]

2024-02-01 18:02:19,610 INFO Nacos is starting...

......

2024-02-01 18:03:09,296 INFO Nacos is starting...

2024-02-01 18:03:09,707 INFO Nacos Log files: /home/nacos/logs

2024-02-01 18:03:09,709 INFO Nacos Log files: /home/nacos/conf

2024-02-01 18:03:09,709 INFO Nacos Log files: /home/nacos/data

2024-02-01 18:03:09,784 ERROR Startup errors : 

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'serviceMetadataProcessor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.1.0.jar!/com/alibaba/nacos/naming/core/v2/metadata/ServiceMetadataProcessor.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.metadata.ServiceMetadataProcessor]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Fail to init node, please see the logs to find the reason.
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:304)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.metadata.ServiceMetadataProcessor]: Constructor threw exception; nested exception is java.lang.IllegalStateException: Fail to init node, please see the logs to find the reason.
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:187)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300)
	... 27 common frames omitted
Caused by: java.lang.IllegalStateException: Fail to init node, please see the logs to find the reason.
	at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:48)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGroup(JRaftServer.java:269)
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.addRequestProcessors(JRaftProtocol.java:163)
	at com.alibaba.nacos.naming.core.v2.metadata.ServiceMetadataProcessor.<init>(ServiceMetadataProcessor.java:73)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:175)
	... 29 common frames omitted
2024-02-01 18:03:11,926 WARN [WatchFileCenter] start close

2024-02-01 18:03:11,989 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /home/nacos/data/tps

2024-02-01 18:03:11,991 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /home/nacos/conf

2024-02-01 18:03:11,992 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /home/nacos/data/loader

2024-02-01 18:03:11,994 WARN [WatchFileCenter] already closed

2024-02-01 18:03:11,994 WARN [NotifyCenter] Start destroying Publisher

2024-02-01 18:03:11,998 WARN [NotifyCenter] Destruction of the end

2024-02-01 18:03:12,000 ERROR Nacos failed to start, please see /home/nacos/logs/nacos.log for more details.

**Comment by KomachiSion** [comment]
`see /home/nacos/logs/nacos.log for more details` 
need more information from nacos.log or alipay-jraft.log

**Comment by KomachiSion** [comment]
No more response from author, It seems env problem.
