### ISSUE TITLE
Dotnet 启动项目，显示 Client not connected,current status: STARTING

### ISSUE THREAD

**Issue by fengcharles** [alibaba/nacos#11830]
使用 dotnet 启动项目 在centos7.9环境下， nacos 服务器（win2016）与 dotnet项目服务器互通，所有的端口全部打开，防火墙也关闭了， 并且telnet 没有任何问题。

但是启动还是报错。 显示无法连接。以下是日志
```
info: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [subscribe] ActiveSign_Config+Active+6688001a-88f2-4c10-80e2-93345cf449e5
fail: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [sub-server-error] dataId=ActiveSign_Config, group=Active, tenant=6688001a-88f2-4c10-80e2-93345cf449e5, code=Client not connected,current status: STARTING 
      Nacos.V2.Exceptions.NacosException: Client not connected,current status: STARTING
         at Nacos.V2.Remote.RpcClient.Request(CommonRequest request, Int64 timeoutMills)
         at Nacos.V2.Config.Impl.ConfigRpcTransportClient.RequestProxy(RpcClient rpcClientInner, CommonRequest request, Int64 timeout)
         at Nacos.V2.Config.Impl.ConfigRpcTransportClient.QueryConfig(String dataId, String group, String tenant, Int64 readTimeous, Boolean notify)
warn: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [get-config] get from server error, dataId=ActiveSign_Config, group=Active, tenant=6688001a-88f2-4c10-80e2-93345cf449e5, msg=Client not connected,current status: STARTING
warn: Nacos.V2.Config.NacosConfigService[0]
      [config_rpc_client] [get-config] get snapshot ok, dataId=ActiveSign_Config, group=Active, tenant=6688001a-88f2-4c10-80e2-93345cf449e5, config=
fail: Nacos.V2.Config.NacosConfigService[0]
      async listen config change error 
      Nacos.V2.Exceptions.NacosException: Client not connected,current status: STARTING
         at Nacos.V2.Remote.RpcClient.Request(CommonRequest request, Int64 timeoutMills)
         at Nacos.V2.Config.Impl.ConfigRpcTransportClient.RequestProxy(RpcClient rpcClientInner, CommonRequest request, Int64 timeout)
         at Nacos.V2.Config.Impl.ConfigRpcTransportClient.ExecuteConfigListen()
warn: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
      MS Config Query config error, dataid=ActiveSign_Config, group=Active, tenant=6688001a-88f2-4c10-80e2-93345cf449e5
      System.ArgumentNullException: Value cannot be null. (Parameter 's')
         at System.IO.StringReader..ctor(String s)
         at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.ParseString(String input)
         at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.Parse(String input)
         at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.Load()
fail: Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider[0]
      Load config error
      System.ArgumentNullException: Value cannot be null. (Parameter 's')
         at System.IO.StringReader..ctor(String s)
         at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.ParseString(String input)
         at Nacos.Microsoft.Extensions.Configuration.DefaultJsonConfigurationStringParser.Parse(String input)
         at Nacos.Microsoft.Extensions.Configuration.NacosV2ConfigurationProvider.Load()
Unhandled exception. System.ArgumentNullException: String reference not set to an instance of a String. (Parameter 's')
   at System.Text.Encoding.GetBytes(String s)
   at CZT.Active.SignApi.Startup.ConfigureServices(IServiceCollection services) in /data/git/activity/czt_activity/CZT.Active.SignApi/Startup.cs:line 98
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Span`1& arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services, Object instance)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at CZT.Active.SignApi.Program.Main(String[] args) in /data/git/activity/czt_activity/CZT.Active.SignApi/Program.cs:line 23
Aborted (core dumped)
```

运行环境
dotnet 6.0
nacos 2.2.3

请问下还有什么原因会导致这个问题发生？

**Comment by fengcharles** [comment]
这个 Nacos 8848 7848 9848 8849 端口 均已打开，并且其他的服务都在正常的使用。
而新建的 .Net 项目 打开一直报上面的错误。 这个新建的.Net 项目的包 放到 nacos 服务器上也能正常启动。
只有在 linux 环境的服务器下，会报这个错

**Comment by fengcharles** [comment]
找到了原因了，是dotnet 打包的问题。打的win64版本的包 在linux环境下运行，报的 Nacos的错。。。
