### ISSUE TITLE
Load balancer does not have available server for client

### ISSUE THREAD

**Issue by nsecn** [alibaba/nacos#1183]
2019-05-07 17:39:48 [ERROR] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet][175] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.lang.RuntimeException: com.netflix.client.ClientException: Load balancer does not have available server for client: nacos-service-xxx] with root cause
com.netflix.client.ClientException: Load balancer does not have available server for client: nacos-service-xxx
	at com.netflix.loadbalancer.LoadBalancerContext.getServerFromLoadBalancer(LoadBalancerContext.java:483)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:184)
	at com.netflix.loadbalancer.reactive.LoadBalancerCommand$1.call(LoadBalancerCommand.java:180)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)

This behavior occurs after the service has been running for a while. Used version springcloud Greenwich.RELEASE, springboot 2.1.2.RELEASE, nacos 1.0.0

**Comment by nkorange** [comment]
Report it to [Spring Cloud Alibaba ](https://github.com/spring-cloud-incubator/spring-cloud-alibaba)please.
