### ISSUE TITLE
nacos1.4.1单机模式启动失败(English: The standalone mode startup of Nacos 1.4.1 fails)

### ISSUE THREAD

**Issue by hunaulys** [alibaba/nacos#11846]
**Describe the bug**
nacos1.4.1单机模式启动后，过一会儿会显示内嵌tomcat启动失败，然后自动关闭服务(English: After initiating the standalone mode, it shows an embedded Tomcat startup failure and then automatically shuts down the service)

**Expected behavior**
nacos启动成功，访问 http://192.168.60.1:8848/nacos/index.html 可以正常显示内容

**Actually behavior**
访问 http://192.168.60.1:8848/nacos/index.html 显示“ERR_CONNECTION_REFUSED”

**How to Reproduce**
1. 解压 nacos-server-1.4.1.zip 到 F 盘根目录(English: The nacos-server-1.4.1.zip file was extracted to the root directory of drive F)
2. 在 F:\nacos\bin 运行命令 startup.cmd -m standalone

**Desktop (please complete the following information):**
 - OS: Windows 11 家庭中文版 21H2（64位）(English: Windows 11 Home Chinese Edition 21H2 (64-bit))
 - Version: nacos-server-1.4.1
 - Module: bin/startup.cmd
 - JDK: 1.8.0_211（64位）
 - MAVEN: 3.8.4

**Additional context**
`2024-03-18 22:38:11,634 INFO Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@6c0d7c83' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2024-03-18 22:38:11,770 INFO Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)

2024-03-18 22:38:12,693 INFO Tomcat initialized with port(s): 8848 (http)

2024-03-18 22:38:13,384 INFO Root WebApplicationContext: initialization completed in 7239 ms

2024-03-18 22:38:30,259 WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat

2024-03-18 22:38:30,280 INFO Nacos Log files: F:\nacos\logs

2024-03-18 22:38:30,281 INFO Nacos Log files: F:\nacos\conf

2024-03-18 22:38:30,282 INFO Nacos Log files: F:\nacos\data

2024-03-18 22:38:30,282 ERROR Startup errors : {}

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
        at com.alibaba.nacos.Nacos.main(Nacos.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:124)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:86)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:416)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:180)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153)
        ... 16 common frames omitted
Caused by: java.lang.IllegalStateException: StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[/nacos] failed to start
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.rethrowDeferredStartupExceptions(TomcatWebServer.java:169)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:108)
        ... 21 common frames omitted
2024-03-18 22:38:36,348 WARN [WatchFileCenter] start close

2024-03-18 22:38:36,349 WARN [WatchFileCenter] start to shutdown this watcher which is watch : F:\nacos\conf

2024-03-18 22:38:36,356 WARN [WatchFileCenter] already closed

2024-03-18 22:38:36,357 WARN [NotifyCenter] Start destroying Publisher

2024-03-18 22:38:36,360 WARN [NotifyCenter] Destruction of the end

2024-03-18 22:38:36,361 ERROR Nacos failed to start, please see F:\nacos\logs\nacos.log for more details.

2024-03-18 22:38:36,387 INFO

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2024-03-18 22:38:36,390 ERROR Application run failed

org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
        at com.alibaba.nacos.Nacos.main(Nacos.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:124)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.<init>(TomcatWebServer.java:86)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getTomcatWebServer(TomcatServletWebServerFactory.java:416)
        at org.springframework.boot.web.embedded.tomcat.TomcatServletWebServerFactory.getWebServer(TomcatServletWebServerFactory.java:180)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:180)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:153)
        ... 16 common frames omitted
Caused by: java.lang.IllegalStateException: StandardEngine[Tomcat].StandardHost[localhost].TomcatEmbeddedContext[/nacos] failed to start
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.rethrowDeferredStartupExceptions(TomcatWebServer.java:169)
        at org.springframework.boot.web.embedded.tomcat.TomcatWebServer.initialize(TomcatWebServer.java:108)
        ... 21 common frames omitted`

**Comment by 985492783** [comment]
什么场景必须使用1.x的服务端吗，可以升级2.x的稳定版本

**Comment by hunaulys** [comment]
> 什么场景必须使用1.x的服务端吗，可以升级2.x的稳定版本

我在B站看黑马程序员的视频，就是用1.4.1教学的。我刚刚卸载了这个版本的jdk，改用jdk1.8.0.171，可以正常运行了。我认为nacos1.4.1似乎没有兼容所有jdk1.8的小版本，再贴上通义千问对上述异常信息的解答，很有可能就是jdk的问题，当然我也是菜鸡一个，如果有看到的大佬请帮忙解答一下：


> 根据您提供的日志，Nacos 1.4.1 启动过程中主要出现了以下问题：
> 
> XML Schema找不到警告：
>
> 日志中的几条警告信息表明Tomcat在启动时未能找到对应的XML Schema文件，这可能导致XML验证失败。通常这不是致命错误，但可能会影响XML配置的严格性检查。
>
> AbstractMethodError异常：
> 
> 最关键的问题在于最后两部分报错，显示了两个过滤器（trafficReviseFilter和authFilter）初始化时抛出了java.lang.AbstractMethodError异常。这是一个运行时错误，通常发生在当代码试图调用抽象方法时，而在运行时找不到其实现。
> 
> 这种情况可能是由于类库版本不兼容导致的。Nacos依赖的某个类库在新版本中移除了或者修改了某个方法的实现，而Nacos本身的代码仍然尝试调用旧版本中的方法。
> 
> 解决建议：
> 
> 检查Nacos所依赖的所有类库版本是否与Nacos 1.4.1兼容，特别是与过滤器相关的类库。
> 确保没有使用过时或不兼容的Spring Boot、Tomcat或其他相关依赖版本。
> 查阅Nacos官方文档或社区论坛，看是否有类似问题的解决方案或已知问题列表。
> 如果有自定义的filter（例如trafficReviseFilter和authFilter），确保它们的实现符合当前使用的类库接口要求。
> 总之，根据上述日志，您需要进一步排查是否存在类库版本冲突或不兼容的问题，并针对AbstractMethodError进行修复。

**Comment by KomachiSion** [comment]
大概率是jdk本身的问题，对java有了解的人都知道，正常开发java代码的时候，只要语法正确并且解析器兼容，同样的代码可以在不同jdk版本和不同平台上运行，
但是jdk本身也会存在一些bug，java的LTS版本也不停的在发布新版本修复问题，所有有可能某些小版本的jdk存在bug，然后导致tomcat在启动的时候因为这个bug失败。 nacos本身是能够兼容jdk8～jdk17的版本的。

**Comment by hunaulys** [comment]
> 大概率是jdk本身的问题，对java有了解的人都知道，正常开发java代码的时候，只要语法正确并且解析器兼容，同样的代码可以在不同jdk版本和不同平台上运行， 但是jdk本身也会存在一些bug，java的LTS版本也不停的在发布新版本修复问题，所有有可能某些小版本的jdk存在bug，然后导致tomcat在启动的时候因为这个bug失败。 nacos本身是能够兼容jdk8～jdk17的版本的。

建议给出 nacos 与 jdk 之间兼容的版本，或者反过来列举不兼容的版本
