### ISSUE TITLE
[Graalvm] Use `spring boot maven plugin` generation hints files appeared warning info.

### ISSUE THREAD

**Issue by yuluo-yx** [alibaba/nacos#11861]
```md
Warning: Error processing trace entry map(size=5, {(tracer,reflect),(function,getSystemResource),(caller_class,com.alibaba.nacos.client.auth.ram.identify.CredentialWatcher),(result,true),(args,[null])}): java.lang.NullPointerException
        at java.base@22/java.util.regex.Pattern.quote(Pattern.java:1499)
        at org.graalvm.nativeimage.configure/com.oracle.svm.configure.trace.ReflectionProcessor.processEntry(ReflectionProcessor.java:84)
        at org.graalvm.nativeimage.configure/com.oracle.svm.configure.trace.TraceProcessor.processEntry(TraceProcessor.java:88)
        at org.graalvm.nativeimage.agent.tracing/com.oracle.svm.agent.tracing.ConfigurationResultWriter.traceEntry(ConfigurationResultWriter.java:53)
        at org.graalvm.nativeimage.agent.tracing/com.oracle.svm.agent.tracing.core.Tracer.traceCall(Tracer.java:117)
        at org.graalvm.nativeimage.agent.tracing/com.oracle.svm.agent.BreakpointInterceptor.traceBreakpoint(BreakpointInterceptor.java:188)
        at org.graalvm.nativeimage.agent.tracing/com.oracle.svm.agent.BreakpointInterceptor.traceReflectBreakpoint(BreakpointInterceptor.java:177)
        at org.graalvm.nativeimage.agent.tracing/com.oracle.svm.agent.BreakpointInterceptor.handleGetSystemResources(BreakpointInterceptor.java:620)
        at org.graalvm.nativeimage.agent.tracing/com.oracle.svm.agent.BreakpointInterceptor.getSystemResource(BreakpointInterceptor.java:610)
        at org.graalvm.nativeimage.agent.tracing/com.oracle.svm.agent.BreakpointInterceptor.onBreakpoint(BreakpointInterceptor.java:1091)
```

## env
```shell
os: windows 11

openjdk version "22" 2024-03-19
OpenJDK Runtime Environment GraalVM CE 22+36.1 (build 22+36-jvmci-b02)
OpenJDK 64-Bit Server VM GraalVM CE 22+36.1 (build 22+36-jvmci-b02, mixed mode, sharing)

nacos-client: 2.3.0
```

**Comment by dengjuan0721** [comment]
@KomachiSion could you assign it to me so i can start working on it ；）

**Comment by yangzehan** [comment]
解决了吗

**Comment by yangzehan** [comment]
[GraalVM CE 24.2.0-dev-20240716_0023](https://github.com/graalvm/graalvm-ce-dev-builds/releases/tag/24.2.0-dev-20240716_0023)
我用最新的dev构建的graalvm 虽然也会有警告但是元数据可以产出

**Comment by yangzehan** [comment]
https://github.com/graalvm/graalvm-ce-dev-builds/releases  用dev的jdk 貌似解决了这个告警
