### ISSUE TITLE
NACOS 0.9.0   beat  ERROR

### ISSUE THREAD

**Issue by haochencheng** [alibaba/nacos#1186]
2019-05-08 10:26:04.540  INFO 49279 --- [           main] com.alibaba.nacos.client.naming          : [BEAT] adding beat: {"cluster":"DEFAULT","ip":"192.168.199.200","metadata":{"preserved.register.source":"SPRING_CLOUD"},"port":40100,"scheduled":false,"serviceName":"DEFAULT_GROUP@@microservice-integration-gateway","weight":1.0} to beat map.
2019-05-08 10:26:04.565  INFO 49279 --- [           main] com.alibaba.nacos.client.naming          : [REGISTER-SERVICE] 68da671b-ef91-47e0-b5d0-d3a458bd743a registering service DEFAULT_GROUP@@microservice-integration-gateway with instance: {"clusterName":"DEFAULT","enabled":true,"ephemeral":true,"healthy":true,"ip":"192.168.199.200","metadata":{"preserved.register.source":"SPRING_CLOUD"},"port":40100,"weight":1.0}
2019-05-08 10:26:04.574 DEBUG 49279 --- [           main] com.alibaba.nacos.client.naming          : Request from server: http://localhost:8848/nacos/v1/ns/instance?groupName=DEFAULT_GROUP&metadata=%7B%22preserved.register.source%22%3A%22SPRING_CLOUD%22%7D&namespaceId=68da671b-ef91-47e0-b5d0-d3a458bd743a&port=40100&enable=true&healthy=true&clusterName=DEFAULT&ip=192.168.199.200&weight=1.0&ephemeral=true&serviceName=DEFAULT_GROUP%40%40microservice-integration-gateway&encoding=UTF-8
2019-05-08 10:26:08.124  INFO 49279 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : [BEAT] 68da671b-ef91-47e0-b5d0-d3a458bd743a sending beat to server: {"cluster":"DEFAULT","ip":"192.168.199.200","metadata":{"preserved.register.source":"SPRING_CLOUD"},"port":40100,"scheduled":true,"serviceName":"DEFAULT_GROUP@@microservice-integration-gateway","weight":1.0}
2019-05-08 10:26:08.125 DEBUG 49279 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : Request from server: http://localhost:8848/nacos/v1/ns/instance/beat?beat=%7B%22cluster%22%3A%22DEFAULT%22%2C%22ip%22%3A%22192.168.199.200%22%2C%22metadata%22%3A%7B%22preserved.register.source%22%3A%22SPRING_CLOUD%22%7D%2C%22port%22%3A40100%2C%22scheduled%22%3Atrue%2C%22serviceName%22%3A%22DEFAULT_GROUP%40%40microservice-integration-gateway%22%2C%22weight%22%3A1.0%7D&serviceName=DEFAULT_GROUP%40%40microservice-integration-gateway&encoding=UTF-8&namespaceId=68da671b-ef91-47e0-b5d0-d3a458bd743a
2019-05-08 10:26:08.128 DEBUG 49279 --- [naming.failover] com.alibaba.nacos.client.naming          : failover switch is not found, failover00-00---000-VIPSRV_FAILOVER_SWITCH-000---00-00
2019-05-08 10:26:08.135 ERROR 49279 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : request localhost:8848 failed.

com.alibaba.nacos.api.exception.NacosException: failed to req API:http://localhost:8848/nacos/v1/ns/instance/beat. code:400 msg: dom name can only have these characters: 0-9a-zA-Z.:_-; current: DEFAULT_GROUP@@microservice-integration-gateway

	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:227)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:109)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

2019-05-08 10:26:08.135 ERROR 49279 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : [CLIENT-BEAT] failed to send beat: {"cluster":"DEFAULT","ip":"192.168.199.200","metadata":{"preserved.register.source":"SPRING_CLOUD"},"port":40100,"scheduled":true,"serviceName":"DEFAULT_GROUP@@microservice-integration-gateway","weight":1.0}

**Comment by nkorange** [comment]
Use nacos-client 1.0.0
