### ISSUE TITLE
2023.x  分支 连接 Nacos 2.3.1 获取配置文件失败！

### ISSUE THREAD

**Issue by Exclusive-gfj** [alibaba/nacos#11863]
请教一下，在使用 分支 2023.x 运行获取配置的时候一直获取不到，Nacos 是使用 Docker 安装的 2.3.1 版本。 请问是那里配置的不对吗？

```
Connected to the target VM, address: '127.0.0.1:2763', transport: 'socket'

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::                (v3.2.0)

2024-03-21T11:08:25.871+08:00  INFO 4976 --- [nacos-config-example] [           main] c.a.c.examples.NacosConfigApplication    : Starting NacosConfigApplication using Java 20 with PID 4976 (D:\WorkSpace\Server\spring-cloud-alibaba\spring-cloud-alibaba-examples\nacos-example\nacos-config-example\target\classes started by Ja in D:\WorkSpace\Server\spring-cloud-alibaba)
2024-03-21T11:08:25.873+08:00  INFO 4976 --- [nacos-config-example] [           main] c.a.c.examples.NacosConfigApplication    : No active profile set, falling back to 1 default profile: "default"
2024-03-21T11:08:25.899+08:00  WARN 4976 --- [nacos-config-example] [           main] c.a.c.n.c.NacosConfigDataLoader          : [Nacos Config] config[dataId=nacos-config-example.properties, group=DEFAULT_GROUP] is empty
2024-03-21T11:08:25.899+08:00 DEBUG 4976 --- [nacos-config-example] [           main] c.a.c.n.c.NacosConfigDataLoader          : [Nacos Config] config[dataId=nacos-config-example.properties, group=DEFAULT_GROUP] content: 
null
2024-03-21T11:08:26.494+08:00  INFO 4976 --- [nacos-config-example] [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=5e3017fe-c68e-3022-885d-4a26f05d9052
2024-03-21T11:08:26.688+08:00  INFO 4976 --- [nacos-config-example] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port 18084 (http)
2024-03-21T11:08:26.694+08:00  INFO 4976 --- [nacos-config-example] [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2024-03-21T11:08:26.695+08:00  INFO 4976 --- [nacos-config-example] [           main] o.apache.catalina.core.StandardEngine    : Starting Servlet engine: [Apache Tomcat/10.1.16]
2024-03-21T11:08:26.735+08:00  INFO 4976 --- [nacos-config-example] [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2024-03-21T11:08:26.735+08:00  INFO 4976 --- [nacos-config-example] [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 835 ms
2024-03-21T11:08:26.879+08:00  INFO 4976 --- [nacos-config-example] [           main] c.a.nacos.client.config.impl.CacheData   : config listener notify warn timeout millis use default 60000 millis 
2024-03-21T11:08:26.880+08:00  INFO 4976 --- [nacos-config-example] [           main] c.a.nacos.client.config.impl.CacheData   : nacos.cache.data.init.snapshot = true 
2024-03-21T11:08:26.880+08:00  INFO 4976 --- [nacos-config-example] [           main] c.a.n.client.config.impl.ClientWorker    : [fixed-112.74.61.91_8848] [subscribe] nacos-config-example.properties+DEFAULT_GROUP
2024-03-21T11:08:26.887+08:00  INFO 4976 --- [nacos-config-example] [           main] c.a.nacos.client.config.impl.CacheData   : [fixed-112.74.61.91_8848] [add-listener] ok, tenant=, dataId=nacos-config-example.properties, group=DEFAULT_GROUP, cnt=1
2024-03-21T11:08:27.001+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=e0ffe9743ee078ee84704d16cf2fde29, Client-RequestTS=1710990506888, exConfigInfo=true}, requestId='null'}, retryTimes = 0, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:27.109+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=e0ffe9743ee078ee84704d16cf2fde29, Client-RequestTS=1710990506888, exConfigInfo=true}, requestId='null'}, retryTimes = 1, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:27.219+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=e0ffe9743ee078ee84704d16cf2fde29, Client-RequestTS=1710990506888, exConfigInfo=true}, requestId='null'}, retryTimes = 2, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:27.316+08:00  INFO 4976 --- [nacos-config-example] [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 16 endpoint(s) beneath base path '/actuator'
2024-03-21T11:08:27.328+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=e0ffe9743ee078ee84704d16cf2fde29, Client-RequestTS=1710990506888, exConfigInfo=true}, requestId='null'}, retryTimes = 3, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:27.328+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] c.a.n.client.config.impl.ClientWorker    : Execute listen config change error 

com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:647) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1152) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1133) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.lambda$checkListenCache$7(ClientWorker.java:957) ~[nacos-client-2.3.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]

2024-03-21T11:08:27.375+08:00  INFO 4976 --- [nacos-config-example] [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port 18084 (http) with context path ''
2024-03-21T11:08:27.428+08:00  INFO 4976 --- [nacos-config-example] [           main] c.a.c.examples.NacosConfigApplication    : Started NacosConfigApplication in 15.194 seconds (process running for 15.827)
2024-03-21T11:08:27.434+08:00  INFO 4976 --- [nacos-config-example] [           main] c.a.nacos.client.config.impl.CacheData   : [fixed-112.74.61.91_8848] [add-listener] ok, tenant=, dataId=nacos-config-example.properties, group=DEFAULT_GROUP, cnt=2
2024-03-21T11:08:27.434+08:00  INFO 4976 --- [nacos-config-example] [           main] c.a.c.n.refresh.NacosContextRefresher    : [Nacos Config] Listening config: dataId=nacos-config-example.properties, group=DEFAULT_GROUP
2024-03-21T11:08:27.501+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=7d079a01525306e36861f165217b243d, Client-RequestTS=1710990507390, exConfigInfo=true}, requestId='null'}, retryTimes = 0, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:27.609+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=7d079a01525306e36861f165217b243d, Client-RequestTS=1710990507390, exConfigInfo=true}, requestId='null'}, retryTimes = 1, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:27.718+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=7d079a01525306e36861f165217b243d, Client-RequestTS=1710990507390, exConfigInfo=true}, requestId='null'}, retryTimes = 2, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:27.826+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=7d079a01525306e36861f165217b243d, Client-RequestTS=1710990507390, exConfigInfo=true}, requestId='null'}, retryTimes = 3, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:27.826+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] c.a.n.client.config.impl.ClientWorker    : Execute listen config change error 

com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:647) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1152) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1133) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.lambda$checkListenCache$7(ClientWorker.java:957) ~[nacos-client-2.3.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]

2024-03-21T11:08:27.911+08:00  INFO 4976 --- [nacos-config-example] [)-192.168.10.28] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2024-03-21T11:08:27.911+08:00  INFO 4976 --- [nacos-config-example] [)-192.168.10.28] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2024-03-21T11:08:27.913+08:00  INFO 4976 --- [nacos-config-example] [)-192.168.10.28] o.s.web.servlet.DispatcherServlet        : Completed initialization in 2 ms
2024-03-21T11:08:27.998+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=6393cc8096626e65b05f252aff2a89ca, Client-RequestTS=1710990507887, exConfigInfo=true}, requestId='null'}, retryTimes = 0, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:28.106+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=6393cc8096626e65b05f252aff2a89ca, Client-RequestTS=1710990507887, exConfigInfo=true}, requestId='null'}, retryTimes = 1, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:28.215+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=6393cc8096626e65b05f252aff2a89ca, Client-RequestTS=1710990507887, exConfigInfo=true}, requestId='null'}, retryTimes = 2, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:28.324+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=6393cc8096626e65b05f252aff2a89ca, Client-RequestTS=1710990507887, exConfigInfo=true}, requestId='null'}, retryTimes = 3, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:28.324+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] c.a.n.client.config.impl.ClientWorker    : Execute listen config change error 

com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:647) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1152) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1133) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.lambda$checkListenCache$7(ClientWorker.java:957) ~[nacos-client-2.3.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]

2024-03-21T11:08:28.324+08:00 ERROR 4976 --- [nacos-config-example] [t.remote.worker] c.a.n.c.remote.client.grpc.GrpcClient    : Server check fail, please check server 112.74.61.91 ,port 9848 is available , error ={}

java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 9 milliseconds, 27300 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@4eeb1b7e[status=PENDING, info=[GrpcFuture{clientCall=PendingCall{realCall=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@1e530163, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@14d8444b, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@71466383}}}}]]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:531) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:243) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:367) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:505) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.lambda$start$2(RpcClient.java:332) ~[nacos-client-2.3.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]

2024-03-21T11:08:28.431+08:00  INFO 4976 --- [nacos-config-example] [t.remote.worker] c.a.n.c.remote.client.grpc.GrpcClient    : grpc client connection server:112.74.61.91 ip,serverPort:9848,grpcTslConfig:{"sslProvider":"","enableTls":false,"mutualAuthEnable":false,"trustAll":false}
2024-03-21T11:08:28.493+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=79e127e395682eab0614f5d25af5140a, Client-RequestTS=1710990508385, exConfigInfo=true}, requestId='null'}, retryTimes = 0, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:28.602+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=79e127e395682eab0614f5d25af5140a, Client-RequestTS=1710990508385, exConfigInfo=true}, requestId='null'}, retryTimes = 1, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:28.710+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=79e127e395682eab0614f5d25af5140a, Client-RequestTS=1710990508385, exConfigInfo=true}, requestId='null'}, retryTimes = 2, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:28.819+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=79e127e395682eab0614f5d25af5140a, Client-RequestTS=1710990508385, exConfigInfo=true}, requestId='null'}, retryTimes = 3, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:28.819+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] c.a.n.client.config.impl.ClientWorker    : Execute listen config change error 

com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:647) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1152) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1133) ~[nacos-client-2.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.lambda$checkListenCache$7(ClientWorker.java:957) ~[nacos-client-2.3.0.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:577) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:317) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:1623) ~[na:na]

2024-03-21T11:08:28.991+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=c6b9db63e256cadd9a9cddbbee38b2e8, Client-RequestTS=1710990508881, exConfigInfo=true}, requestId='null'}, retryTimes = 0, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:29.100+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=c6b9db63e256cadd9a9cddbbee38b2e8, Client-RequestTS=1710990508881, exConfigInfo=true}, requestId='null'}, retryTimes = 1, errorMessage = Client not connected, current status:STARTING
2024-03-21T11:08:29.209+08:00 ERROR 4976 --- [nacos-config-example] [listener.task-0] com.alibaba.nacos.common.remote.client   : Send request fail, request = ConfigBatchListenRequest{headers={accessToken=eyJhbGciOiJIUzM4NCJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTcxMTAwODQ5Mn0.VyxO3yOZ_lJL_pOkkXPZzl_Lk4C2BNVBu9IeVET6TtEonLXze1ezrPuM3fpcAWE6, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=c6b9db63e256cadd9a9cddbbee38b2e8, Client-RequestTS=1710990508881, exConfigInfo=true}, requestId='null'}, retryTimes = 2, errorMessage
```

### 相关组件 Version
- Nacos,：2.3.1
- spring-cloud-alibaba：2023.0.0.0-RC1
- spring-cloud：2023.0.0
- spring-boot：3.2.0
- Open JDK 20

### application.yaml 配置
```
server:
  port: 18084

spring:
  application:
    name: nacos-config-example
  cloud:
    nacos:
      config:
        serverAddr: 192.168.0.1:8848
        username: 'nacos'
        password: 'nacos'
  config:
    import:
      - nacos:nacos-config-example.properties?refresh=true
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
logging:
  level:
    com.alibaba.cloud.nacos.configdata: debug
```

### Naocs 配置
```
PREFER_HOST_MODE=hostname
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=mysql
MYSQL_SERVICE_DB_NAME=nacos_devtest
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=nacos
MYSQL_SERVICE_PASSWORD=nacos
MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
NACOS_AUTH_ENABLE=true
NACOS_AUTH_IDENTITY_KEY=serverIdentity
NACOS_AUTH_IDENTITY_VALUE=security
NACOS_AUTH_TOKEN=SecretKey012345678901234567890123456789012345678901234567890123456789
```
![微信图片_20240321112916](https://github.com/alibaba/nacos/assets/25816191/6e42c6f9-3da6-4435-a7ed-3a247d1c5904)

**Comment by Exclusive-gfj** [comment]
Nacos 控制面板
![微信图片_20240321112916](https://github.com/alibaba/nacos/assets/25816191/c7f2e93a-f3a7-40e4-9bc9-8a84d84ef791)

**Comment by Powerveil** [comment]
我2.3.0前一段时间还没问题，最近也有问题了
