### ISSUE TITLE
Problem: host machiene nacos client can't register to nacos server which deploy by docker on Macos.

### ISSUE THREAD

**Issue by syjzlee** [alibaba/nacos#11921]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)
Description:  I create my nacos on a docker container and map 8848 port to Host machine; Then I run my jar for test register Feature but i always response: ErrCode:-401, ErrMsg:Client not connected, current status:STARTING;

### How to reproduce it (as minimally and precisely as possible)

MacM1Max, nacos on docker container and map 8848;  register nacos  jar on host machine and connect to nacos container with address '127.0.0.1:8848'
1. The docker-compose.yml 
```
  joolun-nacos:
    image: nacos/nacos-server:v2.2.0
    restart: always
    container_name: *******
    environment:
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=*******
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=*******
      - MYSQL_SERVICE_USER=*******
      - MYSQL_SERVICE_PASSWORD=*******
    ports:
      - 8848:8848
    networks:
      - joolun-network
    depends_on:
      - joolun-mysql
  ```
      
 networks:
  joolun-network:
    external: true
    
 3. The jar code
 ```java
 try{
	Properties properties = new Properties();
	properties.put("serverAddr", "127.0.0.1:8848");
	// 创建 NamingService 实例
	NamingService namingService = NacosFactory.createNamingService(properties);

	// 构建服务实例
	Instance instance = new Instance();
	instance.setIp("127.0.0.1");
	instance.setPort(8080);
	instance.setServiceName("testLocalhost");

	// 注册服务
	log.info("status: {}", namingService.getServerStatus());
	namingService.registerInstance("testLocalhost", instance);
	log.info("Service registered successfully!");

} catch (NacosException e){
	e.printStackTrace();
}
```
4. The Error Response 
```
ErrCode:-401, ErrMsg:Client not connected, current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:639)
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:619)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:356)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:209)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:123)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:98)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:152)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:146)
	at com.joolun.cloud.common.nacos.util.NacosConfigUtils.main(NacosConfigUtils.java:63)
```
### Tell us your environment
1.Apple M1 Max(Sonoma 14.1.1)
2. Nacos server run in docker container
3. JDK1.8, com.alibaba.nacos:nacos-client:2.2.0

**Comment by syjzlee** [comment]
My Nacos server is working successful.

![image](https://github.com/alibaba/nacos/assets/21698608/eb7f8f2d-9157-4845-856c-6e11e3b1703f)

**Comment by KomachiSion** [comment]
`Client not connected, current status:STARTING`  your configuration or env setting with wrong， the error information means the client can't connect server anymore, and keeping starting status.

**Comment by syjzlee** [comment]
docker-compose  need add map port.
