### ISSUE TITLE
Error "The Raft Group [naming_persistent_service_v2] did not find the Leader node" happens  when my docker standalone  nacos restart

### ISSUE THREAD

**Issue by Yelijah** [alibaba/nacos#11950]
**Describe the bug**
My nacos was deployed in standalone mode and in docker. 
After I restart nacos  container, and nacos container ip was changed. 
Then the nacos client can't register instance to nacos any more, the error is like
```
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([192.168.250.2:8848]) tried: ErrCode:500, ErrMsg:caused: java.util.concurrent.ExecutionException: com.alibaba.nacos.consistency.exception.ConsistencyException: The Raft Group [naming_persistent_service_v2] did not find the Leader node;caused: com.alibaba.nacos.consistency.exception.ConsistencyException: The Raft Group [naming_persistent_service_v2] did not find the Leader node;caused: The Raft Group [naming_persistent_service_v2] did not find the Leader node;
	at com.alibaba.nacos.client.naming.remote.http.NamingHttpClientProxy.reqApi(NamingHttpClientProxy.java:451) ~[nacos-lib.jar:?]
	at com.alibaba.nacos.client.naming.remote.http.NamingHttpClientProxy.reqApi(NamingHttpClientProxy.java:392) ~[nacos-lib.jar:?]
	at com.alibaba.nacos.client.naming.remote.http.NamingHttpClientProxy.reqApi(NamingHttpClientProxy.java:387) ~[nacos-lib.jar:?]
	at com.alibaba.nacos.client.naming.remote.http.NamingHttpClientProxy.registerService(NamingHttpClientProxy.java:166) ~[nacos-lib.jar:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:94) ~[nacos-lib.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-lib.jar:?]
```

**Expected behavior**
The nacos client can connec to nacos.

**Actually behavior**
Like the above description

**How to Reproduce**
1. create nacos docker container:
```
docker run -it --name=nacos \
-e MODE=standalone -e JVM_XMX=2g \
-e NACOS_AUTH_ENABLE=true -e NACOS_AUTH_TOKEN="VGhpc0lzTXlDdXN0b21TZWNyZXRLZXkwMTIzNDU2Nzg=" \
-e NACOS_AUTH_IDENTITY_KEY=nacos -e NACOS_AUTH_IDENTITY_VALUE=nacos \
-p 8848:8848 -p 9848:9848 \
-v /Users/elijah/Documents/AppData/docker/volumes/nacos/data:/home/nacos/data \
-v /Users/elijah/Documents/AppData/docker/volumes/nacos/logs:/home/nacos/logs \
-d nacos/nacos-server:v2.2.3
```
2. create another nginx docker container.

3.Stop nacos docker container and another docker container. Then start the two containers by different order. Then the docker container ip changed

4. use nacos client  to register instance to nacos, the error happened:
```
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([192.168.250.2:8848]) tried: ErrCode:500, ErrMsg:caused: java.util.concurrent.ExecutionException: com.alibaba.nacos.consistency.exception.ConsistencyException: The Raft Group [naming_persistent_service_v2] did not find the Leader node;caused: com.alibaba.nacos.consistency.exception.ConsistencyException: The Raft Group [naming_persistent_service_v2] did not find the Leader node;caused: The Raft Group [naming_persistent_service_v2] did not find the Leader node;
	at com.alibaba.nacos.client.naming.remote.http.NamingHttpClientProxy.reqApi(NamingHttpClientProxy.java:451) ~[nacos-lib.jar:?]
	at com.alibaba.nacos.client.naming.remote.http.NamingHttpClientProxy.reqApi(NamingHttpClientProxy.java:392) ~[nacos-lib.jar:?]
	at com.alibaba.nacos.client.naming.remote.http.NamingHttpClientProxy.reqApi(NamingHttpClientProxy.java:387) ~[nacos-lib.jar:?]
	at com.alibaba.nacos.client.naming.remote.http.NamingHttpClientProxy.registerService(NamingHttpClientProxy.java:166) ~[nacos-lib.jar:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:94) ~[nacos-lib.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-lib.jar:?]
```

**Desktop (please complete the following information):**
 - OS:  macos docker
 - Version [e.g. nacos-server :v2.2.3  nacos-client:v2.1]
 - Module [e.g. naming]
 - SDK [e.g. original]

**Additional context**

**Comment by KomachiSion** [comment]
If you ip changed, please use host mode run nacos so that the raft member in metadata don't save the non-exist ip.

**Comment by KomachiSion** [comment]
> > If you ip changed, please use host mode run nacos so that the raft member in metadata don't save the non-exist ip.
> 
> Do you mean I should use env `PREFER_HOST_MODE=hostname` to fix the problem?

Right

**Comment by KomachiSion** [comment]
No more response from author, It seems usage problem.

**Comment by supery-chen** [comment]
- **docker image**：`nacos/nacos-server:v2.2.3-slim`
- **MODE**=`standalone`
- **PREFER_HOST_MODE**=`hostname`

![Image](https://github.com/user-attachments/assets/062463a2-740b-4a08-a6e1-1244a5ce39a7)

![Image](https://github.com/user-attachments/assets/c8e6157a-96a7-4b34-9966-0aca715cf55a)

/nacos/v1/ns/instance response

```
caused: errCode: 500, errMsg: do metadata operation failed ;caused: com.alibaba.nacos.consistency.exception.ConsistencyException: The Raft Group [naming_instance_metadata] did not find the Leader node;caused: The Raft Group [naming_instance_metadata] did not find the Leader node;
```

![Image](https://github.com/user-attachments/assets/9cba4e2d-0dd7-4790-a37a-26082cde953f)

![Image](https://github.com/user-attachments/assets/263c3cd4-bb78-4843-b0c8-a92ee1a1b048)
