### ISSUE TITLE
nacos grpc 如何压测？

### ISSUE THREAD

**Issue by huayangchan** [alibaba/nacos#11993]
想对nacos的grpc做压测，用postman尝试通过grpc发起一个ServiceListRequest，
{
    "body": {
        "type_url": "",
        "value": "IntcImhlYWRlcnNcIjp7fSxcIm5hbWVzcGFjZVwiOlwicHVibGljXCIsXCJzZXJ2aWNlTmFtZVwiOlwiXCIsXCJncm91cE5hbWVcIjpcIkRFRkFVTFRfR1JPVVBcIixcInBhZ2VOb1wiOjEsXCJwYWdlU2l6ZVwiOjIxNDc0ODM2NDcsXCJtb2R1bGVcIjpcIm5hbWluZ1wifSI"
    },
    "metadata": {
        "type": "ServiceListRequest",
        "clientIp": "127.0.0.1"
    }
}
但返回
{
    "metadata": {
        "headers": {},
        "type": "ErrorResponse",
        "clientIp": ""
    },
    "body": {
        "type_url": "",
        "value": "eyJyZXN1bHRDb2RlIjo1MDAsImVycm9yQ29kZSI6MzAxLCJtZXNzYWdlIjoiQ29ubmVjdGlvbiBpcyB1bnJlZ2lzdGVyZWQuIiwic3VjY2VzcyI6ZmFsc2V9"
    }
}
将响应中的value中进行解码得到：
{"resultCode":500,"errorCode":301,"message":"Connection is unregistered.","success":false}，提示连接未注册，InstanceRequest，HealthCheckRequest也有这种我问题，请问在发起这些请求之前是不是还需要发起别的请求注册连接，才能正常响应ServiceListRequest，InstanceRequest这些请求，能指导一下不。
![image](https://github.com/alibaba/nacos/assets/50742197/333636ee-0f88-4e87-9071-06c8527953fd)

**Comment by KomachiSion** [comment]
https://nacos.io/docs/latest/guide/admin/nacos2-naming-benchmark/ 使用nacos-client进行压测

如果要自行模拟请求测试的话， 需要先把连接上之后，先发起ConnectionSetupRequest，注册上连接信息，之后再发起正常的请求。期间需要一直保持HealthCheck

**Comment by huayangchan** [comment]
我用jmeter+nacos-client试了压测。我是继承了jmeter的AbstractJavaSamplerClient，实现了它的runTest方法，在runTest的方法里先创建好GrpcSdkClient，用GrpcSdkClient.start方法建立起链接，new好注册请求，调用request方法发送请求，但是报错
四月 28, 2024 10:36:23 上午 com.alibaba.nacos.shaded.io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference cleanQueue
严重: *~*~*~ Channel ManagedChannelImpl{logId=25, target=******} was not shutdown properly!!! ~*~*~*
    Make sure to call shutdown()/shutdownNow() and wait until awaitTermination() returns true.
java.lang.RuntimeException: ManagedChannel allocation site
        at com.alibaba.nacos.shaded.io.grpc.internal.ManagedChannelOrphanWrapper$ManagedChannelReference.<init>(ManagedChannelOrphanWrapper.java:94)
        at com.alibaba.nacos.shaded.io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:52)
        at com.alibaba.nacos.shaded.io.grpc.internal.ManagedChannelOrphanWrapper.<init>(ManagedChannelOrphanWrapper.java:43)
        at com.alibaba.nacos.shaded.io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:524)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewChannelStub(GrpcClient.java:149)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:299)
        at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:389)
        at org.example.chy.JmeterRequest.setupTest(JmeterRequest.java:46)
        at org.apache.jmeter.protocol.java.sampler.JavaSampler.sample(JavaSampler.java:194)
        at org.apache.jmeter.threads.JMeterThread.doSampling(JMeterThread.java:651)
        at org.apache.jmeter.threads.JMeterThread.executeSamplePackage(JMeterThread.java:570)
        at org.apache.jmeter.threads.JMeterThread.processSampler(JMeterThread.java:501)
        at org.apache.jmeter.threads.JMeterThread.run(JMeterThread.java:268)
        at java.lang.Thread.run(Thread.java:748)

**Comment by KomachiSion** [comment]
自行创建的GrpcSdkClient的话，需要您自行管理哈，从报错上看是使用grpc的方式出错了。

建议直接创建NacosNamingSerivce和NacosConfigService进行测试

**Comment by KomachiSion** [comment]
Client not connected, current status:STARTING

说明客户端没连上服务端，  排查一下配置是否正确，比如host，端口，以及网络本身是否正常。

**Comment by huayangchan** [comment]
> Client not connected, current status:STARTING
> 
> 说明客户端没连上服务端， 排查一下配置是否正确，比如host，端口，以及网络本身是否正常。

我把nacos的项目中的nacos-client模块本地打包，放在jmeter里用，服务能注册上，用maven仓中的nacos-client反而不行

**Comment by KomachiSion** [comment]
那就不清楚了，社区的压测也是拿jmeter构建nacos-client进行的。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and current information is not enough to judge problem.
