### ISSUE TITLE
HttpRequestInstanceBuilderTest unit test failed:NullPointerException

### ISSUE THREAD

**Issue by llzcx** [alibaba/nacos#11994]
Describe the bug

environments:

java version: 1.8
nacos server version: 2.4.0
nacos deployment mode: standalone, windows10 PC

Error appears in testBuildSimple() and testBuildFull() `Instance actual = builder.setRequest(request).build();`

error info：

`java.util.ServiceConfigurationError: com.alibaba.nacos.api.naming.spi.generator.InstanceIdGenerator: Provider com.alibaba.nacos.naming.pojo.instance.SnowFlakeInstanceIdGenerator could not be instantiated
	at java.util.ServiceLoader.fail(ServiceLoader.java:232)
	at java.util.ServiceLoader.access$100(ServiceLoader.java:185)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:384)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at com.alibaba.nacos.common.spi.NacosServiceLoader.load(NacosServiceLoader.java:49)
	at com.alibaba.nacos.naming.pojo.instance.InstanceIdGeneratorManager.init(InstanceIdGeneratorManager.java:46)
	at com.alibaba.nacos.naming.pojo.instance.InstanceIdGeneratorManager.<init>(InstanceIdGeneratorManager.java:42)
	at com.alibaba.nacos.naming.pojo.instance.InstanceIdGeneratorManager.<clinit>(InstanceIdGeneratorManager.java:37)
	at com.alibaba.nacos.naming.pojo.instance.HttpRequestInstanceBuilder.setInstanceId(HttpRequestInstanceBuilder.java:142)
	at com.alibaba.nacos.naming.pojo.instance.HttpRequestInstanceBuilder.build(HttpRequestInstanceBuilder.java:75)
	at com.alibaba.nacos.naming.pojo.instance.HttpRequestInstanceBuilderTest.testBuildFull(HttpRequestInstanceBuilderTest.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.mockito.internal.runners.DefaultInternalRunner$1$1.evaluate(DefaultInternalRunner.java:54)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.mockito.internal.runners.DefaultInternalRunner$1.run(DefaultInternalRunner.java:99)
	at org.mockito.internal.runners.DefaultInternalRunner.run(DefaultInternalRunner.java:105)
	at org.mockito.internal.runners.StrictRunner.run(StrictRunner.java:40)
	at org.mockito.junit.MockitoJUnitRunner.run(MockitoJUnitRunner.java:163)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater$1.execute(IdeaTestRunner.java:38)
	at com.intellij.rt.execution.junit.TestsRepeater.repeat(TestsRepeater.java:11)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:35)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:232)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:55)
Caused by: java.lang.ExceptionInInitializerError
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:380)
	... 43 more
Caused by: java.lang.NullPointerException
	at com.alibaba.nacos.sys.env.EnvUtil.getProperty(EnvUtil.java:162)
	at com.alibaba.nacos.core.distributed.id.SnowFlowerIdGenerator.<init>(SnowFlowerIdGenerator.java:91)
	at com.alibaba.nacos.naming.pojo.instance.SnowFlakeInstanceIdGenerator.<clinit>(SnowFlakeInstanceIdGenerator.java:33)
	... 49 more`

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/pull/11995,
