### ISSUE TITLE
集群某个节点重启后和其他两个节点数据不一致

### ISSUE THREAD

**Issue by dogcida** [alibaba/nacos#12012]
我用3个节点 10.111.106.10 10.111.107.10 10.111.108.10构建成集群，有一个节点重启了，但是数据和其他两个节点不同步，在这个节点的web界面修改数据后，其他两个节点生效，此节点不生效。在其他节点修改数据后，只有此节点不生效。问题节点日志报错：2024-04-24 15:24:53,608 ERROR [DISTRO-INIT] load snapshot Nacos:Naming:v2:ClientData from 10.111.107.10:8878 failed.

com.alibaba.nacos.core.distributed.distro.exception.DistroException: [DISTRO-EXCEPTION][DISTRO] Cancel get snapshot caused by target server 10.111.107.10:8878 unhealthy
        at com.alibaba.nacos.naming.consistency.ephemeral.distro.v2.DistroClientTransportAgent.getDatumSnapshot(DistroClientTransportAgent.java:190)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.loadAllDataSnapshotFromRemote(DistroLoadDataTask.java:104)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.load(DistroLoadDataTask.java:87)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.run(DistroLoadDataTask.java:63)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2024-04-24 15:24:53,608 INFO [DISTRO-INIT] load snapshot Nacos:Naming:v2:ClientData from 10.111.108.10:8878

2024-04-24 15:24:53,608 ERROR [DISTRO-INIT] load snapshot Nacos:Naming:v2:ClientData from 10.111.108.10:8878 failed.

com.alibaba.nacos.core.distributed.distro.exception.DistroException: [DISTRO-EXCEPTION][DISTRO] Cancel get snapshot caused by target server 10.111.108.10:8878 unhealthy
        at com.alibaba.nacos.naming.consistency.ephemeral.distro.v2.DistroClientTransportAgent.getDatumSnapshot(DistroClientTransportAgent.java:190)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.loadAllDataSnapshotFromRemote(DistroLoadDataTask.java:104)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.load(DistroLoadDataTask.java:87)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.run(DistroLoadDataTask.java:63)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

master节点报错：2024-04-24 11:53:24,247 INFO [DISTRO-END] DistroKey{resourceKey='10.111.121.233:60750#true', resourceType='Nacos:Naming:v2:ClientData', targetServer='10.111.106.10:8878'} result: false

应该如何处理？

**Comment by KomachiSion** [comment]
加载快照失败了， 提示的是10.111.108.10:8878这个节点不健康。

建议排查一下这个节点是否存活，比如能不能ping通， telnet能不能通。如果网络就访问不通，那么说明重启的节点无法和另外2个节点组成集群，那数据不一致是正常的， 修复一下网络问题即可。

**Comment by KomachiSion** [comment]
No more response from author, It seems env problem.
