### ISSUE TITLE
SpringBoot3.2.4 project cannot be registered and started on  Nacos2.3.2

### ISSUE THREAD

**Issue by becage** [alibaba/nacos#12131]
<img width="1239" alt="image" src="https://github.com/alibaba/nacos/assets/41765271/b359c8cb-05d9-4505-bd54-98dfa25a9596">

### On remote server, ip x.x.x144

`docker run -d --name nacos-server   -p 10100:8848   -e MODE=standalone   nacos/nacos-server:v2.3.2`
<img width="1150" alt="image" src="https://github.com/alibaba/nacos/assets/41765271/c113e8e1-5dbe-43b5-bdbd-1370d846e350">

### My Spring boot project
```
<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>3.2.4</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>2023.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2023.0.1.0</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
</dependencies>
    </dependencyManagement>

<dependencies>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>

        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
        </dependency>
</dependencies>
```
```
server:
  port: 10102
spring:
  application:
    name: micro-web
  cloud:
    nacos:
      discovery:
        server-addr: x.x.x.144:10100
```

What does it have to do with gRpc? Is it necessary?

<img width="1254" alt="image" src="https://github.com/alibaba/nacos/assets/41765271/61e1ec40-9d25-4cab-933c-8d7eeef50c6d">
``` 
2024-05-24T14:30:41.191+08:00  WARN 66846 --- [micro-web] [ing.grpc.redo.0] com.alibaba.nacos.client.naming          : Grpc Connection is disconnect, skip current redo task
2024-05-24T14:30:41.304+08:00 ERROR 66846 --- [micro-web] [           main] c.a.n.c.remote.client.grpc.GrpcClient    : Server check fail, please check server x.x.x.144 ,port 11100 is available , error ={}

java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 1 milliseconds, 115625 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@32ddcca[status=PENDING, info=[GrpcFuture{clientCall=PendingCall{realCall=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@1ddc8fc, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@77d58f3a, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@1e288c76}}}}]]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:531) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:243) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:367) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:349) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.start(NamingGrpcClientProxy.java:117) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.<init>(NamingGrpcClientProxy.java:110) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:80) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:107) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:90) ~[nacos-client-2.3.2.jar:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[na:na]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77) ~[nacos-client-2.3.2.jar:na]
	at com.alibaba.cloud.nacos.NacosServiceManager.createNewNamingService(NacosServiceManager.java:99) ~[spring-cloud-starter-alibaba-nacos-discovery-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.NacosServiceManager.buildNamingService(NacosServiceManager.java:90) ~[spring-cloud-starter-alibaba-nacos-discovery-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.NacosServiceManager.getNamingService(NacosServiceManager.java:46) ~[spring-cloud-starter-alibaba-nacos-discovery-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.namingService(NacosServiceRegistry.java:193) ~[spring-cloud-starter-alibaba-nacos-discovery-2023.0.1.0.jar:2023.0.1.0]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:68) ~[spring-cloud-starter-alibaba-nacos-discovery-2023.0.1.0.jar:2023.0.1.0]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:264) ~[spring-cloud-commons-4.1.2.jar:4.1.2]
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) ~[spring-cloud-starter-alibaba-nacos-discovery-2023.0.1.0.jar:2023.0.1.0]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:156) ~[spring-cloud-commons-4.1.2.jar:4.1.2]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:119) ~[spring-cloud-commons-4.1.2.jar:4.1.2]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:49) ~[spring-cloud-commons-4.1.2.jar:4.1.2]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:185) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:178) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:156) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:451) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:384) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:47) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:288) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:471) ~[spring-context-6.1.5.jar:6.1.5]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:260) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:205) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:981) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:627) ~[spring-context-6.1.5.jar:6.1.5]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:456) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:334) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-3.2.4.jar:3.2.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-3.2.4.jar:3.2.4]
	at com.cage.web.MicroWebApplication.main(MicroWebApplication.java:12) ~[classes/:na]
```

**Comment by KomachiSion** [comment]
超时无非3种可能：

服务端负载高，请求无法及时响应， 自查是否服务端处于高CPU，线程池使用满，FullGC等问题
网络问题，请求丢包或服务端回包丢失
客户端负载高，请求已返回，但是客户端没有资源处理，导致积压在tcp队列中，或任务队列中，自查是否应用端处于高CPU，线程池使用满，FullGC等问题

**Comment by becage** [comment]
> 超时无非3种可能：
> 
> 服务端负载高，请求无法及时响应， 自查是否服务端处于高CPU，线程池使用满，FullGC等问题 网络问题，请求丢包或服务端回包丢失 客户端负载高，请求已返回，但是客户端没有资源处理，导致积压在tcp队列中，或任务队列中，自查是否应用端处于高CPU，线程池使用满，FullGC等问题

负载高不存在的，新建的空项目，nacos启动端口10100，网上找资料说nacos2.3会自动偏移100使用11100端口给gRpc，根据报错gRpc需要单独安装运行？

**Comment by KomachiSion** [comment]
无关，超时就是超时，稍微了解原理就知道超时就上面我说的3种可能。

**Comment by KomachiSion** [comment]
具体是哪个地方导致的超时，需要根据实际情况分析。

**Comment by fuhouyu** [comment]
Nacos2.x使用的是Grpc连接，docker需要再对外开放一个端口，11100，启动命令应为
`docker run -d --name nacos-server   -p 10100:8848  -p 11100:9848  -e MODE=standalone   nacos/nacos-server:v2.3.2` 
<img width="882" alt="Shottr 2024-06-03 09 56 50" src="https://github.com/alibaba/nacos/assets/50112066/868ed2cd-fc38-4919-849f-0b9e62e142a0">
