### ISSUE TITLE
客户端使用2.2.3 nacos-client，服务端2.3.1，开启安全认证，微服务注册临时实例成功后修改密码，微服务配置不做修改和重启，服务持续在线

### ISSUE THREAD

**Issue by ZrBac** [alibaba/nacos#12175]
**Describe the bug**
客户端使用2.2.3 nacos-client，服务端2.3.1，开启安全认证，微服务注册成功后修改密码，微服务配置不做修改和重启，服务持续在线
token失效后，客户端有报错，但是临时实例还是健康在线状态

```
2024-06-04 16:27:51.284  WARN 76592 --- [aming.updater.0] com.alibaba.nacos.client.naming          : [NA] failed to update serviceName: DEFAULT_GROUP@@content-service

com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:288) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.queryInstancesOfService(NamingGrpcClientProxy.java:168) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.queryInstancesOfService(NamingClientProxyDelegate.java:110) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.core.ServiceInfoUpdateService$UpdateTask.run(ServiceInfoUpdateService.java:185) ~[nacos-client-2.1.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_332]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_332]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_332]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_332]
	at java.lang.Thread.run(Thread.java:750) [na:1.8.0_332]
Caused by: com.alibaba.nacos.api.exception.NacosException: token expired!
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:280) ~[nacos-client-2.1.0.jar:na]
	... 10 common frames omitted

2024-06-04 16:27:51.432 ERROR 76592 --- [s.client.Worker] c.a.n.c.a.i.process.HttpLoginProcessor   : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Tue, 04 Jun 2024 08:27:51 GMT","Keep-Alive":"timeout=60"},"originalResponseHeader":{"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Tue, 04 Jun 2024 08:27:51 GMT"],"Keep-Alive":["timeout=60"]},"charset":"UTF-8"}}
2024-06-04 16:27:56.348 ERROR 76592 --- [naming.security] c.a.n.c.a.i.process.HttpLoginProcessor   : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Tue, 04 Jun 2024 08:27:56 GMT","Keep-Alive":"timeout=60"},"originalResponseHeader":{"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Tue, 04 Jun 2024 08:27:56 GMT"],"Keep-Alive":["timeout=60"]},"charset":"UTF-8"}}
2024-06-04 16:27:56.514 ERROR 76592 --- [s.client.Worker] c.a.n.c.a.i.process.HttpLoginProcessor   : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Tue, 04 Jun 2024 08:27:56 GMT","Keep-Alive":"timeout=60"},"originalResponseHeader":{"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Tue, 04 Jun 2024 08:27:56 GMT"],"Keep-Alive":["timeout=60"]},"charset":"UTF-8"}}
2024-06-04 16:28:01.425 ERROR 76592 --- [naming.security] c.a.n.c.a.i.process.HttpLoginProcessor   : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Tue, 04 Jun 2024 08:28:01 GMT","Keep-Alive":"timeout=60"},"originalResponseHeader":{"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Tue, 04 Jun 2024 08:28:01 GMT"],"Keep-Alive":["timeout=60"]},"charset":"UTF-8"}}
2024-06-04 16:28:01.591 ERROR 76592 --- [s.client.Worker] c.a.n.c.a.i.process.HttpLoginProcessor   : login failed: {"code":403,"message":"user not found!","header":{"header":{"Accept-Charset":"UTF-8","Connection":"keep-alive","Content-Length":"15","Content-Security-Policy":"script-src 'self'","Content-Type":"text/html;charset=UTF-8","Date":"Tue, 04 Jun 2024 08:28:01 GMT","Keep-Alive":"timeout=60"},"originalResponseHeader":{"Connection":["keep-alive"],"Content-Length":["15"],"Content-Security-Policy":["script-src 'self'"],"Content-Type":["text/html;charset=UTF-8"],"Date":["Tue, 04 Jun 2024 08:28:01 GMT"],"Keep-Alive":["timeout=60"]},"charset":"UTF-8"}}

```

![image](https://github.com/alibaba/nacos/assets/33156501/649b33e5-02bf-45f1-8a29-d8e00ed4674d)

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by kangzhaok** [comment]
I guess it is normal design

**Comment by KomachiSion** [comment]
因为你注册服务的时候 用户名密码是正确的，数据就写入了，之后修改完密码，连接没有断开的情况下，服务是不会掉线的， 符合预期。

只有需要重新发起请求的时候，比如redo注册，或者重启应用，发布应用的时候才会继续拦截。

**Comment by ZrBac** [comment]
ok

**Comment by Melod-YI** [comment]
> 因为你注册服务的时候 用户名密码是正确的，数据就写入了，之后修改完密码，连接没有断开的情况下，服务是不会掉线的， 符合预期。
> 
> 只有需要重新发起请求的时候，比如redo注册，或者重启应用，发布应用的时候才会继续拦截。

即使token已经超期失效了，这个行为也是符合预期的吗？
