### ISSUE TITLE
单机模式下 配置有特殊符号 的报错

### ISSUE THREAD

**Issue by kylincodelab** [alibaba/nacos#12238]
**Describe the bug**
单机模式下，发布配置到nacos v1.4.7报错

java.lang.IllegalArgumentException: Invalid character found in the request target [/nacos/v1/ns/instance?ephemeral=true&serviceName=DEFAULT_GROUP@@hoj-judgeserver&port=8088&namespaceId=public&ip=[240e:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]&clusterName=DEFAULT&?encoding=UTF-8&nofix=1 ]. The valid characters are defined in RFC 7230 and RFC 3986
        at org.apache.coyote.http11.Http11InputBuffer.parseRequestLine(Http11InputBuffer.java:482)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:262)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:63)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:926)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1791)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:52)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.base/java.lang.Thread.run(Thread.java:840)

**Expected behavior**
解决出现特殊 符号 [] 出现的报错，

**Desktop (please complete the following information):**
 nacos-server v1.4.7 client v1.4.7

**Comment by HMYDK** [comment]
你这ip咋是这种格式？ip=[240e:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]

**Comment by KomachiSion** [comment]
这个报错应该是你的网络代理导致的， 在传输包的过程中，往tcp协议中加入了额外的数据包，比如ppv2等代理协议，从而导致tomcat在解析的时候解析到了不合法的字符。

建议去除代理层后重试。

**Comment by kylincodelab** [comment]
ipv6地址





------------------ 原始邮件 ------------------
From: HMYDK ***@***.***&gt;
发送时间: 06/17/2024, 11:24
To: alibaba/nacos ***@***.***&gt;
抄送: security and code ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [alibaba/nacos] 单机模式下 配置有特殊符号 的报错 (Issue #12238)





 
你这ip咋是这种格式？ip=[240e:xxx:xxxx:xxxx:xxxx:xxxx:xxxx:xxxx]

**Comment by kylincodelab** [comment]
没有代理，是直接nacos client上报配置，但是服务段接收就报错。nacos 服务端和客户端都是v1.4.7版本





------------------ 原始邮件 ------------------
From: 杨翊 SionYang ***@***.***&gt;
发送时间: 06/17/2024, 14:36
To: alibaba/nacos ***@***.***&gt;
抄送: security and code ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [alibaba/nacos] 单机模式下 配置有特殊符号 的报错 (Issue #12238)





 
这个报错应该是你的网络代理导致的， 在传输包的过程中，往tcp协议中加入了额外的数据包，比如ppv2等代理协议，从而导致tomcat在解析的时候解析到了不合法的字符。
 
建议去除代理层后重试。

**Comment by KomachiSion** [comment]
上述这个错误是tomcat直接拒绝了， 原因是http协议解析失败，目前仅知道的场景就是存在代理的情况下，如果有一些代理自己的协议写在tcp的package里，导致http解析失败。

**Comment by KomachiSion** [comment]
这个代理不仅仅指vpc。包括了vip，slb等任何网络中转设备。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems env problem.
