### ISSUE TITLE
docker 启动 nacos 失败，报 jdbc 连接不上

### ISSUE THREAD

**Issue by caosuyang** [alibaba/nacos#12379]
**Describe the bug**

在 nacos 启动时，和数据库相关配置或连接出现异常，主要是 jdbc 异常

```
2024-07-18 09:01:12,624 ERROR Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'namespaceControllerV2' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/classes!/com/alibaba/nacos/console/controller/v2/NamespaceControllerV2.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'namespaceOperationService' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-core-2.3.1.jar!/com/alibaba/nacos/core/service/NamespaceOperationService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalOtherPersistServiceImpl' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-core-2.3.1.jar!/com/alibaba/nacos/core/namespace/repository/ExternalNamespacePersistServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.core.namespace.repository.ExternalNamespacePersistServiceImpl]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:801)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:224)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:929)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
	at com.alibaba.nacos.Nacos.main(Nacos.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'namespaceOperationService' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-core-2.3.1.jar!/com/alibaba/nacos/core/service/NamespaceOperationService.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalOtherPersistServiceImpl' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-core-2.3.1.jar!/com/alibaba/nacos/core/namespace/repository/ExternalNamespacePersistServiceImpl.class]: Instantiation of bean failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.core.namespace.repository.ExternalNamespacePersistServiceImpl]: Constructor threw exception; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
```

**Desktop (please complete the following information):**
 - OS: mac m3 pro
 - Version [e.g. nacos-docker-2.3.0]
 - Module [e.g. naming/config] :/home/nacos
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo] mysql (    platform: linux/x86_64)

**Comment by HMYDK** [comment]
Caused by: java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.


Caused by: java.lang.RuntimeException: [db-load-error]load jdbc.properties error


日志明显是数据库没有连接上。
docker启动nacos, `MYSQL_SERVICE_HOST=127.0.0.1`你这个地址配置应该是有问题的。

**Comment by BennettChina** [comment]
docker里用127.0.0.1连的是docker里的网络，你mysql是宿主机上的服务。

**Comment by BennettChina** [comment]
你可以用 `host.docker.internal` 这个域名去代替 `127.0.0.1`

**Comment by BennettChina** [comment]
如果 nacos 、mysql 都是 docker 启动，那么在同一个容器网络，然后使用容器名作为 hostname 访问就能直接访问到。但如果 db 是宿主机服务，nacos 作为容器服务从容器内访问宿主机服务只能使用`host.docker.internal`这个域名，否则只能使用 `host` 模式启动容器。

你似乎在用 nacos-docker 项目的 example 里的启动方式，那么 `nacos-standlone-mysql.env` 文件中的 `MYSQL_SERVICE_HOST` 是不需要改动的，以及检验下数据库是否已创建、表数据是否已导入，另外可以查看 nacos.log 文件分析更准确的报错原因。

**Comment by BennettChina** [comment]
如果你用这个 docker-compose 启动服务，那么你的 mysql 应当用的是容器模式（如果你启动命令不是单独启动的 nacos 的话），因为 `docker-compose up -d` 会把这里面写的两个服务都启动起来。

是的，如果 mysql 为非容器服务，就用那个域名访问，这是 docker 官方文档中对那个域名的描述[i-want-to-connect-from-a-container-to-a-service-on-the-host](https://docs.docker.com/desktop/networking/#i-want-to-connect-from-a-container-to-a-service-on-the-host)。

我建议如果本地有了 mysql 服务可以不用案例的那个 docker-compose 文件，可以参考下面这个文件使用。

```
version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:v2.3.2-slim
    container_name: nacos-standalone
    restart: always
    ports:
      - "8848:8848"
      - "9848:9848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - NACOS_AUTH_IDENTITY_KEY=nacos_auth_identity_key
      - NACOS_AUTH_IDENTITY_VALUE=ZGllbCoqKioqc3BwKioqKnNNNzgtKHJedCZzc1NFdmpmSUYs
      - NACOS_AUTH_TOKEN=Ym5zb0lAKioqKjAzNCoqKkpLRWd9NDZPcjY4LEpYQVE5Yg==
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=host.docker.internal
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
    volumes:
      - ./logs/:/home/nacos/logs
      - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
```

或者

```bash
docker run -d \
--name nacos \
-p 8848:8848 -p 9848:9848 \
--restart=always \
-e PREFER_HOST_MODE=hostname \
-e MODE=standalone \
-e NACOS_AUTH_ENABLE=true \
-e NACOS_AUTH_IDENTITY_KEY=nacos_auth_identity_key \
-e NACOS_AUTH_IDENTITY_VALUE=ZGllbCoqKioqc3BwKioqKnNNNzgtKHJedCZzc1NFdmpmSUYs \
-e NACOS_AUTH_TOKEN=Ym5zb0lAKioqKjAzNCoqKkpLRWd9NDZPcjY4LEpYQVE5Yg== \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=host.docker.internal \
-e MYSQL_SERVICE_PORT=3306 \
-e MYSQL_SERVICE_DB_NAME=nacos_config \
-e MYSQL_SERVICE_USER=root \
-e MYSQL_SERVICE_PASSWORD=root \
-v /Users/bennett/Java_Relational/nacos/custom.properties:/home/nacos/init.d/custom.properties \
-v /Users/bennett/Java_Relational/nacos/standalone-logs/:/home/nacos/logs \
nacos/nacos-server:v2.3.2-slim
```

**Comment by KouShenhai** [comment]
您好，我问一下，你的mysql版本，我之前有使用用docker部署nacos，使用mysql8.x会出现这个问题，我的解决方式是mysql连接参数增加一个 ```&allowPublicKeyRetrieval=true```

**Comment by BennettChina** [comment]
你 db 里的表是否已经创建好了？表未创建也会报这个错误。

**Comment by BennettChina** [comment]
<img width="598" alt="image" src="https://github.com/user-attachments/assets/9335a35d-5635-4d1e-bfb8-9503bd87a4b1">

你的截图没看到一个 nacos 使用的表。

**Comment by KomachiSion** [comment]
Caused by: java.net.ConnectException: Connection refused (Connection refused)

拒绝连接，要么配置错误，要么数据库未启动

**Comment by BennettChina** [comment]
> > <img alt="image" width="598" src="https://private-user-images.githubusercontent.com/48208644/350769869-9335a35d-5635-4d1e-bfb8-9503bd87a4b1.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzE3MTgsIm5iZiI6MTcyMTYzMTQxOCwicGF0aCI6Ii80ODIwODY0NC8zNTA3Njk4NjktOTMzNWEzNWQtNTYzNS00ZDFlLWJmYjgtOTUwM2JkODdhNGIxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA2NTY1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI0ODU4OGRmYjk3OTQ2ZDNhZDVhOGI3OTI1MWMyMjJmMmEyMTZlMTBiMTgzYWUyZWU1YTdhZTllZjkzODc5MGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.l2_5BEIn0lmk9QxfQuysdxFPHT-1E4hOhVqqbv-3zUQ">
> > 你的截图没看到一个 nacos 使用的表。
> 
> ![image](https://private-user-images.githubusercontent.com/21099022/350866394-b4a0af71-5c07-4d59-82fa-f632dc07f2e2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzE4MzgsIm5iZiI6MTcyMTYzMTUzOCwicGF0aCI6Ii8yMTA5OTAyMi8zNTA4NjYzOTQtYjRhMGFmNzEtNWMwNy00ZDU5LTgyZmEtZjYzMmRjMDdmMmUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA2NTg1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OTMyNGJhZTA4Y2MxNjcxZTYyOGU3NmZiZDU3OTJmNzdjYzZkNDQ3OTE3OWRkYTMxN2NkYTFmZDhjNjA1NDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Mdu2qrP-1r49T78x0I0XcW2fzmWvOZH9ZKBRR53CyKs)
> 
> 是这张表

那你就把连接用的 `MYSQL_SERVICE_DB_NAME ` 改为这个 `nacos_config`
