### ISSUE TITLE
Nacos Client brushing log

### ISSUE THREAD

**Issue by caojianqiang1984** [alibaba/nacos#1252]
**Which Component**
com.alibaba.nacos:nacos-client:1.0.0

**Describe the bug**
只要请求不存在的服务，就会不断刷日志

**To Reproduce**

注入服务发现客户端

> @Autowired
> private DiscoveryClient discoveryClient;

偿试获取一个不存在的服务

> discoveryClient.getInstances("service-i");

当服务"service-i"不存在或者下线时，客户端就会不断打印如下日志
```
11:03:47.307 ERROR [] HostReactor.updateServiceNow:278 [NA] failed to update serviceName: DEFAULT_GROUP@@DBB-Applyjava.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([service.dev.furong.ink:8848]) tried: failed to req API:http://service.dev.furong.ink:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@service-i
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380)
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
at java.base/java.lang.Thread.run(Thread.java:834)

```
**Additional context**
版本号：
Java11 + spring cloud Greenwich.RELEASE + org.springframework.cloud:spring-cloud-starter-alibaba-nacos-discovery:0.9.0.RELEASE

**Comment by nkorange** [comment]
Nacos Java Client的默认行为是查询时会自动订阅该服务，因此当查询一个不存在的服务时，会不停的去轮询该服务，导致大量日志。但是可以在调用时将subscribe参数设为false，这样就不会一直刷日志了

![image](https://user-images.githubusercontent.com/4593375/58231868-a2a15c00-7d6a-11e9-9e55-493814bb561e.png)

如上图所示，用红框中的方法，并将subscribe参数设为fals即可。

不过不幸的是，这需要Spring Cloud Alibaba支持配置这个参数，目前Spring Cloud Alibaba客户端都是使用的默认接口。
