### ISSUE TITLE
nacos2.4.1在jdk21下启动失败（Description nacos2.4.1 failed to start in jdk21）

### ISSUE THREAD

**Issue by luxiao0000** [alibaba/nacos#12549]
使用jdk21启动，2.3.2版本没有这个问题，升级到2.4.1后存在此问题，疑似hessian版本导致，在2.3.2中为4.0.63，而在2.4.1中为4.0.4

When jdk21 is used to start, the 2.3.2 version does not have this problem, but the problem exists after the upgrade to 2.4.1, which is suspected to be caused by the hessian version, which is 4.0.63 in 2.3.2 and 4.0.4 in 2.4.1

java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.StackTraceElement.classLoaderName accessible: module java.base does not "opens java.lang" to unnamed module @10b48321
	at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
	at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
	at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
	at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
	at com.caucho.hessian.io.JavaDeserializer.getFieldMap(JavaDeserializer.java:363)
	at com.caucho.hessian.io.JavaDeserializer.<init>(JavaDeserializer.java:72)
	at com.caucho.hessian.io.StackTraceElementDeserializer.<init>(StackTraceElementDeserializer.java:60)
	at com.caucho.hessian.io.ContextSerializerFactory.<clinit>(ContextSerializerFactory.java:481)
	at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:143)
	at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:137)
	at com.alibaba.nacos.consistency.serialize.NacosHessianSerializerFactory.<init>(NacosHessianSerializerFactory.java:59)
	at com.alibaba.nacos.consistency.serialize.HessianSerializer.<init>(HessianSerializer.java:41)
	at com.alibaba.nacos.consistency.SerializeFactory.<clinit>(SerializeFactory.java:39)
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.<init>(JRaftProtocol.java:100)
	at com.alibaba.nacos.core.distributed.ConsistencyConfiguration.lambda$strongAgreementProtocol$0(ConsistencyConfiguration.java:40)
	at com.alibaba.nacos.core.distributed.ConsistencyConfiguration.getProtocol(ConsistencyConfiguration.java:53)
	at com.alibaba.nacos.core.distributed.ConsistencyConfiguration.strongAgreementProtocol(ConsistencyConfiguration.java:40)
	at com.alibaba.nacos.core.distributed.ConsistencyConfiguration$$EnhancerBySpringCGLIB$$905fc9db.CGLIB$strongAgreementProtocol$0(<generated>)
	at com.alibaba.nacos.core.distributed.ConsistencyConfiguration$$EnhancerBySpringCGLIB$$905fc9db$$FastClassBySpringCGLIB$$dca98636.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
	at com.alibaba.nacos.core.distributed.ConsistencyConfiguration$$EnhancerBySpringCGLIB$$905fc9db.strongAgreementProtocol(<generated>)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:641)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:626)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:334)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:234)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1284)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveNamedBean(DefaultListableBeanFactory.java:1245)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveBean(DefaultListableBeanFactory.java:494)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:349)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:342)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1189)
	at com.alibaba.nacos.sys.utils.ApplicationUtils.getBeanIfExist(ApplicationUtils.java:155)
	at com.alibaba.nacos.core.distributed.ProtocolManager.initCPProtocol(ProtocolManager.java:124)
	at com.alibaba.nacos.core.distributed.ProtocolManager.getCpProtocol(ProtocolManager.java:85)
	at com.alibaba.nacos.naming.cluster.ServerStatusManager.hasLeader(ServerStatusManager.java:70)
	at com.alibaba.nacos.naming.cluster.ServerStatusManager.refreshServerStatus(ServerStatusManager.java:62)
	at com.alibaba.nacos.naming.cluster.ServerStatusManager.access$000(ServerStatusManager.java:37)
	at com.alibaba.nacos.naming.cluster.ServerStatusManager$ServerStatusUpdater.run(ServerStatusManager.java:92)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:358)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by luxiao0000** [comment]
估计没有针对jdk17+做测试（It is estimated that there is no testing for jdk17+）

**Comment by luxiao0000** [comment]
据估计没有针对jdk17+做测试
It is estimated that no tests have been conducted against jdk17+

**Comment by wz826** [comment]
JDK17+有按模块引入包语法，不兼容之前的语法，需要加入命令：
文件：nacos/bin/startup.sh
`JAVA_OPT="${JAVA_OPT} --add-opens java.base/java.lang=ALL-UNNAMED "`

**Comment by luxiao0000** [comment]
> 和hessian关系不大，主要是因为nacos配置为JDK1.8，而JDK17+开始使用按模块引入包语法，不兼容之前的语法，不过一定要运行的话可以加入以下命令： 文件：nacos/bin/startup.sh `JAVA_OPT="${JAVA_OPT} --add-opens java.base/java.lang=ALL-UNNAMED "`

add-open不是标准做法，明显是hessian低版本没有适配模块化用到了反射，nacos2.4.1中的hessian版本比naocs2.3.2中的低，不符合常理。并且nacos2.3.2跑在jdk21上没有问题。从而也能看出来官方没有对jdk17+做测试

**Comment by wz826** [comment]
> > 和hessian关系不大，主要是因为nacos配置为JDK1.8，而JDK17+开始使用按模块引入包语法，不兼容之前的语法，不过一定要运行的话可以加入以下命令： 文件：nacos/bin/startup.sh `JAVA_OPT="${JAVA_OPT} --add-opens java.base/java.lang=ALL-UNNAMED "`
> 
> add-open不是标准做法，明显是hessian低版本没有适配模块化用到了反射，nacos2.4.1中的hessian版本比naocs2.3.2中的低，不符合常理。并且nacos2.3.2跑在jdk21上没有问题。从而也能看出来官方没有对jdk17+做测试

add-open不是标准做法，但也只能临时这么用。确实和hessian有关系，而且很奇怪，nacos:2.3.2用的是com.caucho.hessian:4.0.63，在nacos:2.4.1用的却是com.alipay.sofa.hessian:4.0.4（已经是最新2020-05-11）所以还得等官方升级支持JDK17+语法。

**Comment by lk101** [comment]
2.4.0.1也没有这个问题

**Comment by KomachiSion** [comment]
duplicate with #12498

**Comment by luxiao0000** [comment]
我不是不会处理这个问题，难道官方没有基于jdk17+测试吗，我不理解这个点
