### ISSUE TITLE
启动startup.sh脚本，日志报错

### ISSUE THREAD

**Issue by stoneLee81** [alibaba/nacos#12560]
nacos server版本 2.4.1
jdk版本 jdk-21
macos
启动startup.sh -m `standard，nacos服务启动，但是在logs/start.out日志里面，报错，
`
`java.lang.reflect.InaccessibleObjectException: Unable to make field private java.lang.String java.lang.StackTraceElement.classLoaderName accessible: module java.base does not
 "opens java.lang" to unnamed module @5c0369c4
        at java.base/java.lang.reflect.AccessibleObject.throwInaccessibleObjectException(AccessibleObject.java:391)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:367)
        at java.base/java.lang.reflect.AccessibleObject.checkCanSetAccessible(AccessibleObject.java:315)
        at java.base/java.lang.reflect.Field.checkCanSetAccessible(Field.java:183)
        at java.base/java.lang.reflect.Field.setAccessible(Field.java:177)
        at com.caucho.hessian.io.JavaDeserializer.getFieldMap(JavaDeserializer.java:363)
        at com.caucho.hessian.io.JavaDeserializer.<init>(JavaDeserializer.java:72)
        at com.caucho.hessian.io.StackTraceElementDeserializer.<init>(StackTraceElementDeserializer.java:60)
        at com.caucho.hessian.io.ContextSerializerFactory.<clinit>(ContextSerializerFactory.java:481)
        at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:143)
        at com.caucho.hessian.io.SerializerFactory.<init>(SerializerFactory.java:137)
        at com.alibaba.nacos.consistency.serialize.NacosHessianSerializerFactory.<init>(NacosHessianSerializerFactory.java:59)
        at com.alibaba.nacos.consistency.serialize.HessianSerializer.<init>(HessianSerializer.java:41)
        at com.alibaba.nacos.consistency.SerializeFactory.<clinit>(SerializeFactory.java:39)
        at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.<init>(JRaftProtocol.java:100)
        at com.alibaba.nacos.core.distributed.ConsistencyConfiguration.lambda$strongAgreementProtocol$0(ConsistencyConfiguration.java:40)
        at com.alibaba.nacos.core.distributed.ConsistencyConfiguration.getProtocol(ConsistencyConfiguration.java:53)
        at com.alibaba.nacos.core.distributed.ConsistencyConfiguration.strongAgreementProtocol(ConsistencyConfiguration.java:40)
        at com.alibaba.nacos.core.distributed.ConsistencyConfiguration$$EnhancerBySpringCGLIB$$8d2160dc.CGLIB$strongAgreementProtocol$0(<generated>)
        at com.alibaba.nacos.core.distributed.ConsistencyConfiguration$$EnhancerBySpringCGLIB$$8d2160dc$$FastClassBySpringCGLIB$$2b6e647e.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at com.alibaba.nacos.core.distributed.ConsistencyConfiguration$$EnhancerBySpringCGLIB$$8d2160dc.strongAgreementProtocol(<generated>)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
        at java.base/java.lang.reflect.Method.invoke(Method.java:580)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:641)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:626)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:336)`

**Comment by fuhouyu** [comment]
你使用的jdk21，由于模块化的关系，需要临时添加参数，以放行未命名模块对于java.lang的访问。
`
--add-opens java.base/java.lang=ALL-UNNAMED
`

**Comment by stoneLee81** [comment]
> 你使用的jdk21，由于模块化的关系，需要临时添加参数，以放行未命名模块对于java.lang的访问。 `--add-opens java.base/java.lang=ALL-UNNAMED`

在启动sh,并没有加--add-opens java.base/java.lang=ALL-UNNAMED，但是，2.4.0启动没错误

**Comment by lingyuwai** [comment]
> --add-opens java.base/java.lang=ALL-UNNAMED
你好 请问这个加在哪里呢 启动参数 还是哪个配置文件呢  不懂java

**Comment by fuhouyu** [comment]
> > --add-opens java.base/java.lang=ALL-UNNAMED
> > 你好 请问这个加在哪里呢 启动参数 还是哪个配置文件呢  不懂java

如果你使用的是java -jar 启动，就加在-jar 后面，如：java -jar --add-opens java.base/java.lang=ALL-UNNAMED xxx.jar
如果使用的是docker脚本启动，可以使用环境变量的形式，如：
`
export JAVA_OPT='--add-opens java.base/java.lang=ALL-UNNAMED'
`
