### ISSUE TITLE
Nacos 2.4.1 failed to get user list, "Request error, please try again later!"

### ISSUE THREAD

**Issue by GeorgeShawn** [alibaba/nacos#12601]
## Environment
- kubernetes
- nacos/nacos-server:2.4.1
- spring-boot-version: 2.7.11
- spring-cloud-version: 2021.0.6
---
## Situation
We deployed nacos 2.4.1 with [nacos-k8s](https://github.com/nacos-group/nacos-k8s) in kubernetes, and inserted nacos user into the database table using command as follow:
```
INSERT INTO users (username, password, enabled) VALUES ('nacos', '$2a$10$6fqqvuEflt4DfGi00wzV9u5kaZMpes4/BeNQAZUJV4QbJhe4Hj.A2', TRUE);

INSERT INTO roles (username, role) VALUES ('nacos', 'ROLE_ADMIN');
```
When we complete it, we can login the nacos console with user "nacos" created just now, but failed to load the user list and couldn't create user when clicking the "Create User" button:
```"Request error, please try again later!"```
![image](https://github.com/user-attachments/assets/a0cceb9c-04df-43d1-b20c-105b210944b7)

What's more, when we start our spring cloud application in kubernetes, we found the errors: ```NacosException: http error, code=403,msg=user not found!```. Details are as follows:
```
2024-09-04T07:06:38.814663167Z :: Blade 5.3.6.RELEASE :: blade-system:test :: Running SpringBoot 2.7.11 :: 
2024-09-04T07:06:38.814666060Z 
2024-09-04T07:06:44.622792635Z 2024-09-04 15:06:44.621 ERROR 1 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : get data from Nacos error,dataId:blade.yaml 
2024-09-04T07:06:44.622816811Z 
2024-09-04T07:06:44.622820468Z com.alibaba.nacos.api.exception.NacosException: http error, code=403,msg=user not found!,dataId=blade.yaml,group=DEFAULT_GROUP,tenant=
2024-09-04T07:06:44.622823908Z 	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:987) ~[nacos-client-2.1.2.jar!/:na]
2024-09-04T07:06:44.622827260Z 	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:404) ~[nacos-client-2.1.2.jar!/:na]
2024-09-04T07:06:44.622830409Z 	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:182) ~[nacos-client-2.1.2.jar!/:na]
2024-09-04T07:06:44.622833344Z 	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:94) ~[nacos-client-2.1.2.jar!/:na]
2024-09-04T07:06:44.622836357Z 	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:85) [spring-cloud-starter-alibaba-nacos-config-2021.0.5.0.jar!/:2021.0.5.0]
2024-09-04T07:06:44.622839461Z 	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:73) [spring-cloud-starter-alibaba-nacos-config-2021.0.5.0.jar!/:2021.0.5.0]
2024-09-04T07:06:44.622842597Z 	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199) [spring-cloud-starter-alibaba-nacos-config-2021.0.5.0.jar!/:2021.0.5.0]
2024-09-04T07:06:44.622845788Z 	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186) [spring-cloud-starter-alibaba-nacos-config-2021.0.5.0.jar!/:2021.0.5.0]
2024-09-04T07:06:44.622849176Z 	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosConfiguration(NacosPropertySourceLocator.java:158) [spring-cloud-starter-alibaba-nacos-config-2021.0.5.0.jar!/:2021.0.5.0]
2024-09-04T07:06:44.622859890Z 	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadSharedConfiguration(NacosPropertySourceLocator.java:116) [spring-cloud-starter-alibaba-nacos-config-2021.0.5.0.jar!/:2021.0.5.0]
2024-09-04T07:06:44.622864445Z 	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:101) [spring-cloud-starter-alibaba-nacos-config-2021.0.5.0.jar!/:2021.0.5.0]
2024-09-04T07:06:44.622867620Z 	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51) [spring-cloud-context-3.1.6.jar!/:3.1.6]
2024-09-04T07:06:44.622870736Z 	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) [spring-cloud-context-3.1.6.jar!/:3.1.6]
2024-09-04T07:06:44.622873760Z 	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95) [spring-cloud-context-3.1.6.jar!/:3.1.6]
2024-09-04T07:06:44.622876894Z 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:604) [spring-boot-2.7.11.jar!/:2.7.11]
2024-09-04T07:06:44.622880385Z 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:373) [spring-boot-2.7.11.jar!/:2.7.11]
2024-09-04T07:06:44.622884962Z 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:306) [spring-boot-2.7.11.jar!/:2.7.11]
2024-09-04T07:06:44.622889389Z 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) [spring-boot-2.7.11.jar!/:2.7.11]
2024-09-04T07:06:44.622893679Z 	at org.springblade.core.launch.BladeApplication.run(BladeApplication.java:50) [blade-core-launch-3.1.1.RELEASE.jar!/:na]
2024-09-04T07:06:44.622897973Z 	at org.springblade.system.SystemApplication.main(SystemApplication.java:35) [classes!/:na]
2024-09-04T07:06:44.622901828Z 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_262]
2024-09-04T07:06:44.622905095Z 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_262]
2024-09-04T07:06:44.622907905Z 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[na:1.8.0_262]
2024-09-04T07:06:44.622910627Z 	at java.lang.reflect.Method.invoke(Unknown Source) ~[na:1.8.0_262]
2024-09-04T07:06:44.622913569Z 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [app.jar:na]
2024-09-04T07:06:44.622916456Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [app.jar:na]
2024-09-04T07:06:44.622919253Z 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [app.jar:na]
2024-09-04T07:06:44.622922071Z 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:65) [app.jar:na]
```
## What should we do to fix this problem? Does anyone meet the same situation, please comment below! We would greatly appreciate any assistance you could provide!

**Comment by KomachiSion** [comment]
I can't reproduce your problem, can you see the browser console and get the response information?

and do debug for your application to check whether your app input right username and password to nacos-client?

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem community can't reproduce.
