### ISSUE TITLE
IDEA启动springboot服务，无法访问到nacos

### ISSUE THREAD

**Issue by babymore001** [alibaba/nacos#12627]
各位大神好，我使用的nacos2.4.1版本，服务在linux服务器上正常启动并且可以正常打开web页面，我把端口改成8000，现在在windows本地的IDEA中，启动springboot服务的时候，需要多次启动服务尝试访问nacos，才能正常启动一次，几率几乎是10比1，不知道大家是否有类似的情况。
![1725851517203](https://github.com/user-attachments/assets/21995292-9ac7-4b45-b24e-a943641c7f1d)

idea报错如下
2024-09-09 11:15:13.637 ERROR c.a.c.n.c.NacosConfigDataLoader  [main] - Error getting properties from nacos: NacosConfigDataResource{properties=NacosConfigProperties{serverAddr='10.176.37.7:8000', encode='null', group='DEFAULT_GROUP', prefix='null', fileExtension='properties', timeout=3000, maxRetry='null', configLongPollTimeout='null', configRetryTime='null', enableRemoteSyncConfig=false, endpoint='null', namespace='7d5e0ad7-5fc6-4b1e-bd9b-e40e396094ec', accessKey='null', secretKey='null', ramRoleName='null', contextPath='null', clusterName='null', name='null'', shares=null, extensions=null, refreshEnabled=true}, optional=true, profiles=[Profiles@5e268ce6 active = '[]', default = '[default]', accepted = '[default]'], config=NacosItemConfig{group='DEFAULT_GROUP', dataId='timer_phase3.properties', suffix='properties', refreshEnabled=true, preference=null}}
com.alibaba.nacos.api.exception.NacosException: http error, code=403,msg=user not found!,dataId=timer_phase3.properties,group=DEFAULT_GROUP,tenant=7d5e0ad7-5fc6-4b1e-bd9b-e40e396094ec
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:987)
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:404)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:184)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:96)
	at com.alibaba.cloud.nacos.configdata.NacosConfigDataLoader.pullConfig(NacosConfigDataLoader.java:141)
	at com.alibaba.cloud.nacos.configdata.NacosConfigDataLoader.doLoad(NacosConfigDataLoader.java:82)
	at com.alibaba.cloud.nacos.configdata.NacosConfigDataLoader.load(NacosConfigDataLoader.java:69)
	at com.alibaba.cloud.nacos.configdata.NacosConfigDataLoader.load(NacosConfigDataLoader.java:58)
	at org.springframework.boot.context.config.ConfigDataLoaders.load(ConfigDataLoaders.java:108)
	at org.springframework.boot.context.config.ConfigDataImporter.load(ConfigDataImporter.java:132)
	at org.springframework.boot.context.config.ConfigDataImporter.resolveAndLoad(ConfigDataImporter.java:87)
	at org.springframework.boot.context.config.ConfigDataEnvironmentContributors.withProcessedImports(ConfigDataEnvironmentContributors.java:116)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processWithProfiles(ConfigDataEnvironment.java:311)
	at org.springframework.boot.context.config.ConfigDataEnvironment.processAndApply(ConfigDataEnvironment.java:232)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:102)
	at org.springframework.boot.context.config.ConfigDataEnvironmentPostProcessor.postProcessEnvironment(ConfigDataEnvironmentPostProcessor.java:94)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEnvironmentPreparedEvent(EnvironmentPostProcessorApplicationListener.java:102)
	at org.springframework.boot.env.EnvironmentPostProcessorApplicationListener.onApplicationEvent(EnvironmentPostProcessorApplicationListener.java:87)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:178)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:171)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:145)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:133)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:85)
	at org.springframework.boot.SpringApplicationRunListeners.lambda$environmentPrepared$2(SpringApplicationRunListeners.java:66)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120)
	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:65)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:344)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1300)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1289)
	at com.aspire.cmmall.paygw.Application.main(Application.java:40)

**Comment by bes2008** [comment]
遇到过这个情况，并且重启无效。其它访问nacos的服务正常。

**Comment by babymore001** [comment]
我在linux服务器上部署服务正常访问nacos，但是windows本地用idea启动访问就不行，很奇怪，我的配置如下
spring:
    application:
        name: paygw-test
    main:
        allow-bean-definition-overriding: true
    cloud:
        nacos:
            username: nacos_test
            #mima使用的时候自己填下，避开扫描
            discovery:
                server-addr: 10.176.37.7:8000
                namespace: e1ffb84a-0c19-484d-89a9-ca611cffb71d
                metadata:
                    management:
                        context-path: ${server.servlet.context-path}/metaservice
            config:
                server-addr: 10.176.37.7:8000
                namespace: 7d5e0ad7-5fc6-4b1e-bd9b-e40e396094ec
                import-check:
                    enabled: false
    config:
        import:
            - optional:nacos:application.yaml?group=DEFAULT_GROUP&refreshEnabled=true




<dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>fastjson</artifactId>
                    <groupId>com.alibaba</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>jackson-databind</artifactId>
                    <groupId>com.fasterxml.jackson.core</groupId>
                </exclusion>
                <exclusion>
                    <artifactId>archaius-core</artifactId>
                    <groupId>com.netflix.archaius</groupId>
                </exclusion>
                <exclusion>
                    <groupId>org.yaml</groupId>
                    <artifactId>snakeyaml</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.2.0</version>
            <exclusions>
                <exclusion>
                    <groupId>org.yaml</groupId>
                    <artifactId>snakeyaml</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
                <exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-core</artifactId>
                </exclusion>
				<exclusion>
					<groupId>com.fasterxml.jackson.core</groupId>
					<artifactId>jackson-databind</artifactId>
				</exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by fuhouyu** [comment]
`http error, code=403,msg=user not found!`
看这个报错，是属于用户未找到或权限问题

**Comment by babymore001** [comment]
使用的用户名密码，我验证过可以正常登录的

**Comment by fuhouyu** [comment]
> 使用的用户名密码，我验证过可以正常登录的

可以使用curl验证下是否正常：
`curl --location 'http://ip:port/nacos/v1/auth/users/login' \
--form 'username="username"' \
--form 'password="password"'`
账号密码都对的情况，可以看下你依赖的`spring cloud nacos`的版本，是否支持2.x，再不行的话就debug看下你在yaml里面配置的参数是否是正常传递进去的。

**Comment by XiaZhouxx** [comment]
> 我在linux服务器上部署服务正常访问nacos，但是windows本地用idea启动访问就不行，很奇怪，我的配置如下 spring: application: name: paygw-test main: allow-bean-definition-overriding: true cloud: nacos: username: nacos_test #mima使用的时候自己填下，避开扫描 discovery: server-addr: 10.176.37.7:8000 namespace: e1ffb84a-0c19-484d-89a9-ca611cffb71d metadata: management: context-path: ${server.servlet.context-path}/metaservice config: server-addr: 10.176.37.7:8000 namespace: 7d5e0ad7-5fc6-4b1e-bd9b-e40e396094ec import-check: enabled: false config: import: - optional:nacos:application.yaml?group=DEFAULT_GROUP&refreshEnabled=true
> 
> com.alibaba.cloud spring-cloud-starter-alibaba-nacos-discovery fastjson com.alibaba jackson-databind com.fasterxml.jackson.core archaius-core com.netflix.archaius org.yaml snakeyaml com.alibaba.nacos nacos-client com.alibaba.nacos nacos-client 2.2.0 org.yaml snakeyaml com.google.guava guava com.fasterxml.jackson.core jackson-core com.fasterxml.jackson.core jackson-databind com.alibaba.cloud spring-cloud-starter-alibaba-nacos-config com.alibaba.nacos nacos-client

应该是配置问题,试试这个呢
```
spring:
  cloud:
    nacos:
      config:
        username: nacos
        password: nacos
      discovery:
        username: nacos
        password: nacos
```

**Comment by babymore001** [comment]
感谢大家的帮助，其实报错的意思是通过用户名密码访问nacos服务器访问超时，但是我通过浏览器正常访问。
现在我本地问题已解决，解决方案是删除掉本地的nacos快照文件后，重启就成功了。
