### ISSUE TITLE
nacos 磁盘满了，清除后重启集群后运行一段时间节点之间心跳不通。

### ISSUE THREAD

**Issue by rageyao** [alibaba/nacos#12636]
nacos 2.3.2 
jdk
openjdk version "1.8.0_282"
OpenJDK Runtime Environment (build 1.8.0_282-b08)
OpenJDK 64-Bit Server VM (build 25.282-b08, mixed mode)

nacos集群三个节点，之前一直是好的。后来磁盘满了，清除后重启集群，运行一段时间节点之间心跳不通。也有jvm报错。 telnet 端口是通的。机器在同一网段，之间没有网络限制。

2024-09-06 19:56:31,067 INFO Out dated connection ,size=0

2024-09-06 19:56:31,067 INFO Connection check task end

2024-09-06 19:56:31,183 INFO ConnectionMetrics, totalCount = 45, detail = {long_connection=1, long_polling=44}

2024-09-06 19:56:31,770 INFO grpc client connection server:xxx.xx.xx.xx ip,serverPort:9849,grpcTslConfig:{"sslProvider":"","enableTls":false,"mutualAuthEnable":false,"trustAll":false}

2024-09-06 19:56:31,772 ERROR Server check fail, please check server xxx.xx.xx.xx ,port 9849 is available , error ={}

java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:592)
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:467)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:243)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:367)
        at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:502)
        at com.alibaba.nacos.common.remote.client.RpcClient.lambda$start$1(RpcClient.java:329)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception
        at io.grpc.Status.asRuntimeException(Status.java:537)
        at io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:548)
        at io.grpc.internal.DelayedClientCall$DelayedListener$3.run(DelayedClientCall.java:489)
        at io.grpc.internal.DelayedClientCall$DelayedListener.delayOrExecute(DelayedClientCall.java:453)
        at io.grpc.internal.DelayedClientCall$DelayedListener.onClose(DelayedClientCall.java:486)
        at io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:567)
        at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:71)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:735)
        at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:716)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
        ... 3 common frames omitted
Caused by: io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: /xxx.xxx.xxx.xxx:9849
Caused by: java.net.ConnectException: finishConnect(..) failed: Connection refused
        at io.grpc.netty.shaded.io.netty.channel.unix.Errors.newConnectException0(Errors.java:166)
        at io.grpc.netty.shaded.io.netty.channel.unix.Errors.handleConnectErrno(Errors.java:131)
        at io.grpc.netty.shaded.io.netty.channel.unix.Socket.finishConnect(Socket.java:359)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.doFinishConnect(AbstractEpollChannel.java:710)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.finishConnect(AbstractEpollChannel.java:687)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.epollOutReady(AbstractEpollChannel.java:567)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:489)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:397)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)
2024-09-06 19:56:31,772 INFO [Cluster-xx.xx.xx.xxx:8848] Fail to connect server, after trying 47 times, last try server is {serverIp = 'xxx.xxxx.xxx.xxx', server main port = 8848}, error = unknown

2024-09-06 19:56:34,067 INFO Connection check task start

2024-09-06 19:56:34,067 INFO Long connection metrics detail ,Total count =1, sdkCount=0,clusterCount=1

2024-09-06 19:56:34,067 INFO Out dated connection ,size=0

```
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGSEGV (0xb) at pc=0x0000ffff4f6ef7c0, pid=1597002, tid=0x0000ffff4deaf1e0
#
# JRE version: OpenJDK Runtime Environment (8.0_282-b08) (build 1.8.0_282-b08)
# Java VM: OpenJDK 64-Bit Server VM (25.282-b08 mixed mode linux-aarch64 compressed oops)
# Problematic frame:
# V  [libjvm.so+0x5bf7c0]  oopDesc::size_given_klass(Klass*)+0x0
#
# Core dump written. Default location: /home/user/nacos/bin/core or core.1597002
#
# If you would like to submit a bug report, please visit:
#   https://github.com/AdoptOpenJDK/openjdk-support/issues
#

---------------  T H R E A D  ---------------

Current thread (0x0000ffff48060800):  GCTaskThread [stack: 0x0000ffff4dcb0000,0x0000ffff4deb0000] [id=1597007]

siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x000000042cf0c588

vm_info: OpenJDK 64-Bit Server VM (25.282-b08) for linux-aarch64 JRE (1.8.0_282-b08),

```

**Comment by KomachiSion** [comment]
Connection refused: /xxx.xxx.xxx.xxx:9849

请确认地址正确，进程正确地洞，并确认有端口监听。

**Comment by rageyao** [comment]
还是网络的问题。已经解决。感谢您的回复。
