### ISSUE TITLE
[notify-error] 不停在报错

### ISSUE THREAD

**Issue by SmallSeals** [alibaba/nacos#12699]
[fixed-dev-172.31.8.203_8848] [notify-error] dataId=hc-erp-pdc-common.yaml, group=hc-erp-pdc,tenant=dev, md5=fccdec5c9c8ac988869bebac962527a3, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@2b6f2e8a tx=
	at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
	at java.base/java.lang.Class.privateGetDeclaredMethods(Class.java:3347)
	at java.base/java.lang.Class.getDeclaredMethods(Class.java:2454)
	at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperties.getDeclaredMethods(JavaBeanBinder.java:140)
	at ... 

nacos 2.3.1

**Comment by XiaZhouxx** [comment]
感觉是刷新配置的时候绑定配置出错了, 客户端重启也这样嘛？

**Comment by SmallSeals** [comment]
调试代码后发现少了一个依赖包
<dependency>
      <groupId>org.apache.commons</groupId>
      <artifactId>commons-pool2</artifactId>
  </dependency>  
加入这个依赖就一切正常了
