### ISSUE TITLE
nacos client 一直报一个告警

### ISSUE THREAD

**Issue by wetool19** [alibaba/nacos#12755]
nacos-server版本：2.3.2
nacos-client:  2.3.2

在应用端每隔1分钟左右就会爆一个告警：

10-17 09:46:51.051 [-Executor(13-0)] wARN c.n.p.p.r.g.GrpcCommandService
    -- Failed to command stream, cause=UNAVAILABLE
: Network closed for unknown reason
io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
    at io.grpc.Status.asRuntimeException(Status.java:535) ~[grpc-api-1.49.2.jar:1.49.2]
     at io.grpc.stub.ClientCalls$Stream0bserverToCallListenerAdapter.onClose(ClientCalls.java:487) ~[grpc-stub-1.49.2.jar:1.49.
2]
    at io.grpc.internal.ClientCallImpl.close0bserver(ClientCallImpl.java:563) ~[grpc-core-1.49.2.jar:1.49.2]
    at io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:70) ~[grpc-core-1.49.2.jar:1.49.2]
     at io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:744) ~[grpc-core
-1.49.2.jar:1.49.2]
     at io.grpc. internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl. java:723） ~[grpc-cor
e-1.49.2.jar:1.49.2]
     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[grpc-core-1.49.2.jar:1.49.2]
    at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) ~[grpc-core-1.49.2.jar:1.49.2]
    at java.util. concurrent.ThreadPoolExecutor. runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_201]
    at java.util. concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_201]
    at java.lang.Thread.run(Thread.java:748) ~[?:1.8.0_201]

请问这是啥问题?

**Comment by xujunhua555** [comment]
兄弟，后面查出是啥问题了吗
