### ISSUE TITLE
Switching the registration center failed to re-register successfully

### ISSUE THREAD

**Issue by chenzhiguo** [alibaba/nacos#12810]
**Describe the bug**
The application registration center address is configured as VIP. When the default registration center goes down, it quickly redirects to the backup Nacos cluster by modifying the resolved IP of the VIP (the usernames and passwords for both Nacos clusters remain consistent). Currently, the issue observed is that the application-side Nacos client SDK detects a connection drop, attempts to reconnect and re-register, but fails to register. The logs are as follows:

应用注册中心地址配置为VIP，当默认的注册中心宕机后，通过修改VIP的解析IP，快速重定向到备用Nacos集群（两个nacos集群用户名密码保持一致）。
目前问题现象：应用端nacos client sdk识别到连接断开，重连以及重新注册这些行为。但是注册失败。日志如下：

```
2024-11-01 16:50:03.488 ERROR 10536 --- [.domain.io-77] c.a.n.c.remote.client.grpc.GrpcClient    : [1730450842269_127.0.0.1_58668]Request stream error, switch server,error={}

com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: CANCELLED: HTTP/2 error code: CANCEL
Received Rst Stream
	at com.alibaba.nacos.shaded.io.grpc.Status.asRuntimeException(Status.java:533)
	at com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$StreamObserverToCallListenerAdapter.onClose(ClientCalls.java:460)
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:426)
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.access$500(ClientCallImpl.java:66)
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:689)
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$900(ClientCallImpl.java:577)
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:751)
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:740)
	at com.alibaba.nacos.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at com.alibaba.nacos.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

2024-11-01 16:50:03.489  INFO 10536 --- [t.remote.worker] com.alibaba.nacos.common.remote.client   : [db8a41ff-97db-48ac-b9db-c3ac2426cc3f] Try to reconnect to a new server, server is  not appointed, will choose a random server.
2024-11-01 16:50:03.632  INFO 10536 --- [t.remote.worker] com.alibaba.nacos.common.remote.client   : [db8a41ff-97db-48ac-b9db-c3ac2426cc3f] Success to connect a server [aaa.domain.io:8848], connectionId = 1730451003696_106.38.115.52_3732
2024-11-01 16:50:03.633  INFO 10536 --- [t.remote.worker] com.alibaba.nacos.common.remote.client   : [db8a41ff-97db-48ac-b9db-c3ac2426cc3f] Abandon prev connection, server is aaa.domain.io:8848, connectionId is 1730450842269_127.0.0.1_58668
2024-11-01 16:50:03.633  INFO 10536 --- [t.remote.worker] com.alibaba.nacos.common.remote.client   : Close current connection 1730450842269_127.0.0.1_58668
2024-11-01 16:50:03.637  INFO 10536 --- [t.remote.worker] com.alibaba.nacos.common.remote.client   : [db8a41ff-97db-48ac-b9db-c3ac2426cc3f] Notify disconnected event to listeners
2024-11-01 16:50:03.637  WARN 10536 --- [t.remote.worker] com.alibaba.nacos.client.naming          : Grpc connection disconnect, mark to redo
2024-11-01 16:50:03.638  WARN 10536 --- [t.remote.worker] com.alibaba.nacos.client.naming          : mark to redo completed
2024-11-01 16:50:03.638  INFO 10536 --- [t.remote.worker] com.alibaba.nacos.common.remote.client   : [db8a41ff-97db-48ac-b9db-c3ac2426cc3f] Notify connected event to listeners.
2024-11-01 16:50:03.638  INFO 10536 --- [t.remote.worker] com.alibaba.nacos.client.naming          : Grpc connection connect
2024-11-01 16:50:04.095  INFO 10536 --- [ing.grpc.redo.0] com.alibaba.nacos.client.naming          : Redo instance operation REGISTER for DEFAULT_GROUP@@service-provider
2024-11-01 16:50:04.133 ERROR 10536 --- [ing.grpc.redo.0] com.alibaba.nacos.client.naming          : Redo instance operation REGISTER for DEFAULT_GROUP@@service-provider failed. 

com.alibaba.nacos.api.exception.NacosException: Invalid signature
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:358)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:209)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.processRegisterRedoType(RedoScheduledTask.java:102)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForInstance(RedoScheduledTask.java:79)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForInstances(RedoScheduledTask.java:61)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.run(RedoScheduledTask.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)

2024-11-01 16:50:07.139  INFO 10536 --- [ing.grpc.redo.0] com.alibaba.nacos.client.naming          : Redo instance operation REGISTER for DEFAULT_GROUP@@service-provider
2024-11-01 16:50:07.173 ERROR 10536 --- [ing.grpc.redo.0] com.alibaba.nacos.client.naming          : Redo instance operation REGISTER for DEFAULT_GROUP@@service-provider failed. 

com.alibaba.nacos.api.exception.NacosException: Invalid signature
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:358)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:209)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.processRegisterRedoType(RedoScheduledTask.java:102)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForInstance(RedoScheduledTask.java:79)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForInstances(RedoScheduledTask.java:61)
	at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.run(RedoScheduledTask.java:51)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:842)
```

**Expected behavior**
Re-registration successful.

**Actually behavior**
Failed to re-register successfully.

**Comment by KomachiSion** [comment]
com.alibaba.nacos.api.exception.NacosException: Invalid signature

密码虽然一样，但是生成accessToken用的 secure.token 不一样，新集群不认可这个客户端的身份。

建议主备集群的所有除数据库以外的配置`application.properties`，最好都保持一致。

**Comment by chenzhiguo** [comment]
是否检测到token不可用后，重新自动获取token更好些？

**Comment by KomachiSion** [comment]
> 是否检测到token不可用后，重新自动获取token更好些？

has issue about it https://github.com/alibaba/nacos/issues/12719
