### ISSUE TITLE
spring服务从nacos默认账号换成新创建的账号，启动后一直有报错但又不影响业务

### ISSUE THREAD

**Issue by zhangys529** [alibaba/nacos#12829]
## Issue Description
spring服务从nacos默认账号换成新创建的账号（该账号设置了读写权限），启动后一直有报错，但又不影响业务，出现的错误有以下这些：
`request: /nacos/v1/ns/instance/beat failed`
`request: /nacos/v1/ns/service/list failed`
`request: /nacos/v1/ns/instance/list failed`

**Comment by KomachiSion** [comment]
报错具体内容是什么？ 是403还是400？

**Comment by zhangys529** [comment]
报的403，具体堆栈信息：
```
com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance/list after all servers([x.x.x.x:18848]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Nov 07 01:07:38 UTC 2024</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>authorization failed!</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:496)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:401)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:397)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:321)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:281)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:327)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
```

**Comment by KomachiSion** [comment]
那就是鉴权失败了， 确认给这个用户正确授权了，用户密码是正确的

**Comment by zhangys529** [comment]
确实是正确的，否则会无法正确读取到配置

**Comment by KomachiSion** [comment]
读取配置的客户端和获取服务的客户端是两个， 如果你只配置了一个，比如config.username. 那么获取服务的时候是没有登录的状态，会报错。

**Comment by KomachiSion** [comment]
No more response from author for a long time, and this problem seems usage problem.
