### ISSUE TITLE
The service can't be registered, so worry.

### ISSUE THREAD

**Issue by ouyangzhiming** [alibaba/nacos#1284]
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([127.0.0.1:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
05-29 09:59:41.726 ERROR [com.alibaba.nacos.client.naming] - [] [] [CALL-SERVER] failed to req API:http://127.0.0.1:8848/nacos/v1/ns/api/clientBeat. code:500 msg: java.net.SocketTimeoutException: Read timed out
05-29 09:59:41.727 ERROR [com.alibaba.nacos.client.naming] - [] [] [NA] req api:/nacos/v1/ns/api/clientBeat failed, server(127.0.0.1:8848
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:327)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callAllServers(NamingProxy.java:238)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:99)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
05-29 09:59:41.727 ERROR [com.alibaba.nacos.client.naming] - [] [] [NA] req api:/nacos/v1/ns/api/clientBeat failed, servers: [127.0.0.1:8848]
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/clientBeat after all servers([127.0.0.1:8848]) tried

**Comment by nkorange** [comment]
看样子是网络问题，检查下Nacos server是否能正常连上

**Comment by ouyangzhiming** [comment]
不是网络问题，我都能从nacos获取配置下来，就是注册服务不行
现在我换成了nacos-all 0.8.0,则提示我
05-30 16:32:00.511 ERROR [com.alibaba.nacos.client.naming] - [CLIENT-BEAT] failed to send beat: {"cluster":"DEFAULT","ip":"192.168.200.238","metadata":{"name":"平台基础服务","preserved.register.source":"SPRING_CLOUD"},"port":8233,"scheduled":true,"serviceName":"DEFAULT_GROUP@@opencloud-base-provider","weight":1.0}
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([127.0.0.1:8848]) tried: failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance/beat. code:400 msg: dom name can only have these characters: 0-9a-zA-Z.:_-; current: DEFAULT_GROUP@@opencloud-base-provider

提示我这个服务名：不符合规则
"serviceName":"DEFAULT_GROUP@@opencloud-base-provider",  这个服务名是咋来的？

**Comment by nkorange** [comment]
Server版本多少，客户端版本多少？

**Comment by nkorange** [comment]
很有可能是你的客户端版本是1.0，但是server端版本低于1.0，请升级server版本到1.0
