### ISSUE TITLE
动态链接库 librocksdbjni dll 未提供 Windows 11 Arm64 的版本 报错如下

### ISSUE THREAD

**Issue by think-gem** [alibaba/nacos#12995]
```
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\x\AppData\Local\Temp\librocksdbjni14055836232141884970.dll: Can't load AMD 64-bit .dll on a ARM 64-bit platform
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1957)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:107)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:87)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:71)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:36)
	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.<clinit>(RocksDBLogStorage.java:69)
	at com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory.createLogStorage(DefaultJRaftServiceFactory.java:51)
	at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:579)
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:1004)
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:141)
	at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGroup(JRaftServer.java:260)
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.addRequestProcessors(JRaftProtocol.java:163)
	at com.alibaba.nacos.naming.misc.SwitchManager.<init>(SwitchManager.java:96)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:481)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:213)
	... 20 common frames omitted
```

**Desktop (please complete the following information):**
 - OS: Windows 11 ARM64
 - Version: nacos-server 2.4
 - SDK: jdk17

**Comment by 985492783** [comment]
跟Nacos没关系

**Comment by think-gem** [comment]
虽然是第三方库，但是 nacos 选型的一部分，我已找到临时替代方案，使用 java 扩展，替换了 rocksdb 实现

**Comment by Dario-s-j** [comment]
Ok

Em seg., 6 de jan. de 2025, 04:38, 杨翊 SionYang ***@***.***>
escreveu:
