### ISSUE TITLE
com.alibaba.nacos.api.exception.NacosException: null

### ISSUE THREAD

**Issue by shaohuanan** [alibaba/nacos#1310]
## Issue Description

I want to use NACOS as config's center. But when the appliaction is starting,the exception is always appearing . AND if the application does not ues the property of the  configuration files，the application is normal accessed .（我想用nacos配置中心的功能，但是应用启动的时候，会出现这个异常。如果没有用到配置中心的属性，项目可以正常访问）
Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:45) ~[nacos-api-1.0.0.jar:na]
	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:41) ~[nacos-api-1.0.0.jar:na]
	at org.springframework.cloud.alibaba.nacos.NacosConfigProperties.configServiceInstance(NacosConfigProperties.java:343) ~[spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:63) [spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94) [spring-cloud-context-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:654) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:390) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:331) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1277) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1265) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at com.shn.springcloud.nacosconfigclient.NacosConfigClientApplication.main(NacosConfigClientApplication.java:11) [classes/:na]
### How to reproduce it (as minimally and precisely as possible)

1. bootstrap.properties is ok
spring.application.name=discovery-config-client
server.port=8085
spring.cloud.nacos.discovery.server-addr=**************.8848
2. Data ID : discovery-config-client.properties
3. 

### Tell us your environment
spring-cloud-dependencies(version):Finchley.SR1
spring-boot-starter-parent(version):2.0.5.RELEASE
spring-cloud-alibaba-dependencies(version):0.2.2.RELEASE
nacos：1.0

**Comment by shaohuanan** [comment]
create config service error!properties=NacosConfigProperties{serverAddr='null', encode='null', group='DEFAULT_GROUP', prefix='null', fileExtension='properties', timeout=3000, endpoint='null', namespace='null', accessKey='null', secretKey='null', contextPath='null', clusterName='null', name='null', sharedDataids='null', refreshableDataids='null', extConfig=null},e=,

**Comment by shaohuanan** [comment]
should be :spring.cloud.nacos.config.server-addr 
but mine is :spring.cloud.nacos.discovery.server-addr
embarrassed...
