### ISSUE TITLE
Nacos 1.0, MySQL 8.0+, startup failure

### ISSUE THREAD

**Issue by fangkk0168** [alibaba/nacos#1312]
1、Nacos 1.0, MySQL 8.0+, Centos 7.2 。  startup failure

2、Start command : （ sh startup.sh-m standalone& ）

3、Error reporting information：

2019-05-31 00:05:03,415 INFO [capacityManagement] start correct usage

2019-05-31 00:05:03,418 INFO [capacityManagement] end correct usage, cost: 0s

2019-05-31 00:05:03,860 WARN clearConfigHistory start

2019-05-31 00:05:03,861 WARN clearConfigHistory, getBeforeStamp:2019-05-01 00:05:03.0, totalCount:42, pageSize:1000, removeTime:1

2019-05-31 00:05:03,862 ERROR clearConfigHistory error

org.springframework.jdbc.UncategorizedSQLException: PreparedStatementCallback; uncategorized SQLException for SQL [delete from his_config_info where gmt_modified < ? OFFSET 0 ROWS FETCH NEXT ? ROWS ONLY]; SQL state [null]; error code [0]; Borrow prepareStatement from pool failed; nested exception is org.apache.commons.dbcp.SQLNestedException: Borrow prepareStatement from pool failed
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:89)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:81)
        at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1444)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:632)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:862)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:917)
        at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:927)
        at com.alibaba.nacos.config.server.utils.PaginationHelper.updateLimit(PaginationHelper.java:211)
        at com.alibaba.nacos.config.server.service.PersistService.removeConfigHistory(PersistService.java:872)
        at com.alibaba.nacos.config.server.service.PersistService$$FastClassBySpringCGLIB$$21ae4232.invoke(<generated>)
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:749)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163)
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:139)
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688)
        at com.alibaba.nacos.config.server.service.PersistService$$EnhancerBySpringCGLIB$$4476a653.removeConfigHistory(<generated>)
        at com.alibaba.nacos.config.server.service.dump.DumpService$3.run(DumpService.java:112)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.commons.dbcp.SQLNestedException: Borrow prepareStatement from pool failed
        at org.apache.commons.dbcp.PoolingConnection.prepareStatement(PoolingConnection.java:113)
        at org.apache.commons.dbcp.DelegatingConnection.prepareStatement(DelegatingConnection.java:281)
        at org.apache.commons.dbcp.PoolingDataSource$PoolGuardConnectionWrapper.prepareStatement(PoolingDataSource.java:313)
        at org.springframework.jdbc.core.JdbcTemplate$SimplePreparedStatementCreator.createPreparedStatement(JdbcTemplate.java:1557)
        at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:615)
        ... 21 common frames omitted
Caused by: java.sql.SQLSyntaxErrorException: Syntax error: Encountered "OFFSET" at line 1, column 52.
        at org.apache.derby.impl.jdbc.SQLExceptionFactory40.getSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.Util.generateCsSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.wrapInSQLException(Unknown Source)
        at org.apache.derby.impl.jdbc.TransactionResourceImpl.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.ConnectionChild.handleException(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement.<init>(Unknown Source)
at org.apache.derby.impl.jdbc.EmbedPreparedStatement20.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement30.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement40.<init>(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedPreparedStatement42.<init>(Unknown Source)
        at org.apache.derby.jdbc.Driver42.newEmbedPreparedStatement(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
        at org.apache.derby.impl.jdbc.EmbedConnection.prepareStatement(Unknown Source)
        at org.apache.commons.dbcp.PoolingConnection.makeObject(PoolingConnection.java:285)
        at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1220)
        at org.apache.commons.dbcp.PoolingConnection.prepareStatement(PoolingConnection.java:107)
        ... 25 common frames omitted

[logs.zip](https://github.com/alibaba/nacos/files/3246193/logs.zip)

**Comment by yanlinly** [comment]
请调优jvm参数
2019-06-03T14:30:41.049+0800: 4.607: [GC (Metadata GC Threshold) [PSYoungGen: 96767K->6628K(249344K)] 105749K->17529K(511488K), 0.0190017 secs] [Times: user=0.06 sys=0.00, real=0.02 secs] 
2019-06-03T14:30:41.068+0800: 4.626: [Full GC (Metadata GC Threshold) [PSYoungGen: 6628K->0K(249344K)] [ParOldGen: 10901K->16671K(262144K)] 17529K->16671K(511488K), [Metaspace: 33955K->33955K(1081344K)], 0.1250218 secs] [Times: user=0.57 sys=0.01, real=0.13 secs] 
2019-06-03T14:30:42.848+0800: 6.406: [GC (Allocation Failure) [PSYoungGen: 242688K->9699K(252416K)] 259359K->29461K(514560K), 0.0131581 secs] [Times: user=0.05 sys=0.00, real=0.02 secs] 
2019-06-03T14:30:44.423+0800: 7.981: [GC (Allocation Failure) [PSYoungGen: 252387K->9696K(241152K)] 272149K->37674K(503296K), 0.0415256 secs] [Times: user=0.13 sys=0.01, real=0.04 secs] 
2019-06-03T14:30:45.440+0800: 8.998: [GC (Metadata GC Threshold) [PSYoungGen: 168833K->4720K(246784K)] 196812K->41436K(508928K), 0.0433896 secs] [Times: user=0.15 sys=0.00, real=0.05 secs] 
2019-06-03T14:30:45.483+0800: 9.041: [Full GC (Metadata GC Threshold) [PSYoungGen: 4720K->0K(246784K)] [ParOldGen: 36716K->33247K(262144K)] 41436K->33247K(508928K), [Metaspace: 56240K->56185K(1101824K)], 0.1961107 secs] [Times: user=0.75 sys=0.01, real=0.19 secs]

**Comment by fangkk0168** [comment]
> 请调优jvm参数
> 2019-06-03T14:30:41.049+0800: 4.607: [GC (Metadata GC Threshold) [PSYoungGen: 96767K->6628K(249344K)] 105749K->17529K(511488K), 0.0190017 secs] [Times: user=0.06 sys=0.00, real=0.02 secs]
> 2019-06-03T14:30:41.068+0800: 4.626: [Full GC (Metadata GC Threshold) [PSYoungGen: 6628K->0K(249344K)] [ParOldGen: 10901K->16671K(262144K)] 17529K->16671K(511488K), [Metaspace: 33955K->33955K(1081344K)], 0.1250218 secs] [Times: user=0.57 sys=0.01, real=0.13 secs]
> 2019-06-03T14:30:42.848+0800: 6.406: [GC (Allocation Failure) [PSYoungGen: 242688K->9699K(252416K)] 259359K->29461K(514560K), 0.0131581 secs] [Times: user=0.05 sys=0.00, real=0.02 secs]
> 2019-06-03T14:30:44.423+0800: 7.981: [GC (Allocation Failure) [PSYoungGen: 252

这个日志，是logs 目录下面哪个文件呢

**Comment by fangkk0168** [comment]
logs 目录下面，nacos_gc.log.0.current 文件。

JVM的参数调整了。  Xms1g -Xmx1g -Xmn512m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m

查看GC日志，发现一直 Allocation Failure（分配失败），具体日志信息如下：

**Comment by xavierzhao** [comment]
> logs 目录下面，nacos_gc.log.0.current 文件。
> 
> JVM的参数调整了。 Xms1g -Xmx1g -Xmn512m -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m
> 
> 查看GC日志，发现一直 Allocation Failure（分配失败），具体日志信息如下：
> 
> [nacos_gc.log.0.zip](https://github.com/alibaba/nacos/files/3255388/nacos_gc.log.0.zip)

同样的问题，请问你解决了吗？

**Comment by fangkk0168** [comment]
> > logs目录下面，nacos_gc.log.0.current文件。
> > JVM的参数调整了.Xms1g -Xmx1g -Xmn512m -XX：MetaspaceSize = 128m -XX：MaxMetaspaceSize = 320m
> > 查看GC日志，发现一直Allocation Failure（分配失败），具体日志信息如下：
> > [nacos_gc.log.0.zip](https://github.com/alibaba/nacos/files/3255388/nacos_gc.log.0.zip)
> 
> 同样的问题，请问你解决了吗？

JVM参数调整了，nacos的JVM参数目前设置：JAVA_OPT="${JAVA_OPT} -Xms4g -Xmx4g -Xmn2g"

这样设置后，暂时没有发现问题。
