### ISSUE TITLE
Nacos config gives an error every few minutes

### ISSUE THREAD

**Issue by lza1997** [alibaba/nacos#1327]
java.net.ConnectException: no available server
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:141) ~[nacos-client-1.0.0.jar:na]
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.0.0.jar:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:361) [nacos-client-1.0.0.jar:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:335) [nacos-client-1.0.0.jar:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:478) [nacos-client-1.0.0.jar:na]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by chuntaojun** [comment]
能贴出更详细的日志信息吗？
```java
if (result.code == HttpURLConnection.HTTP_INTERNAL_ERROR
                    || result.code == HttpURLConnection.HTTP_BAD_GATEWAY
                    || result.code == HttpURLConnection.HTTP_UNAVAILABLE) {
                    LOGGER.error("[NACOS ConnectException] currentServerAddr: {}, httpCode: {}",
                        serverListMgr.getCurrentServerAddr(), result.code);
                }
```
当Http请求返回的状态码为以上三种时认为需要重试，如果超时就会报错：no available server

**Comment by lza1997** [comment]
2019-六月-05 12:19:14 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - [NACOS SocketTimeoutException]
2019-六月-05 12:19:14 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - no available server
2019-六月-05 12:19:14 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.i.ClientWorker - [fixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] [check-update] get changed dataId exception
java.net.ConnectException: no available server
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:141) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:361) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:335) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:478) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-六月-05 12:19:44 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - [NACOS SocketTimeoutException]
2019-六月-05 12:19:44 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - no available server
2019-六月-05 12:19:44 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.i.ClientWorker - [fixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] [check-update] get changed dataId exception
java.net.ConnectException: no available server
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:141) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:361) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:335) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:478) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-六月-05 12:49:16 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - [NACOS SocketTimeoutException]
2019-六月-05 12:49:16 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - no available server
2019-六月-05 12:49:16 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.i.ClientWorker - [fixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] [check-update] get changed dataId exception
java.net.ConnectException: no available server
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:141) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:361) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:335) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:478) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-六月-05 12:49:46 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - [NACOS SocketTimeoutException]
2019-六月-05 12:49:46 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - no available server
2019-六月-05 12:49:46 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.i.ClientWorker - [fixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] [check-update] get changed dataId exception
java.net.ConnectException: no available server
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:141) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:361) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:335) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:478) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-六月-05 12:53:55 WARN  [HikariPool-1 housekeeper] c.z.h.p.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=4m23s395ms).
2019-六月-05 12:54:09 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - [NACOS SocketTimeoutException]
2019-六月-05 12:54:09 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - no available server
2019-六月-05 12:54:09 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.i.ClientWorker - [fixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] [check-update] get changed dataId exception
java.net.ConnectException: no available server
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:141) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:361) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:335) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:478) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-六月-05 13:55:59 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - [NACOS SocketTimeoutException]
2019-六月-05 13:55:59 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.h.ServerHttpAgent - no available server
2019-六月-05 13:55:59 ERROR [com.alibaba.nacos.client.Worker.longPollingfixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] c.a.n.c.c.i.ClientWorker - [fixed-tmc-nacos.ekuaibao.com_80-341e6b14-2f60-474e-b0a3-f35367185e15] [check-update] get changed dataId exception
java.net.ConnectException: no available server
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:141) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:361) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:335) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:478) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-六月-05 13:56:12 WARN  [HikariPool-1 housekeeper] c.z.h.p.HikariPool - HikariPool-1 - Thread starvation or clock leap detected (housekeeper delta=32m16s669ms).
2019-六月-05 14:09:12 ERROR [com.alibaba.nacos.naming.beat.sender] c.a.n.c.naming - [NA] failed to request 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[na:1.8.0_181]
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[na:1.8.0_181]
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[na:1.8.0_181]
	at java.net.Socket.connect(Socket.java:589) ~[na:1.8.0_181]
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[na:1.8.0_181]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[na:1.8.0_181]
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[na:1.8.0_181]
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[na:1.8.0_181]
	at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[na:1.8.0_181]
	at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1334) ~[na:1.8.0_181]
	at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1309) ~[na:1.8.0_181]
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:85) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:326) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:227) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:109) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-六月-05 14:09:12 ERROR [com.alibaba.nacos.naming.beat.sender] c.a.n.c.naming - request tmc-nacos.ekuaibao.com:80 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://tmc-nacos.ekuaibao.com:80/nacos/v1/ns/instance/beat. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:227) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:109) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]
2019-六月-05 14:09:12 ERROR [com.alibaba.nacos.naming.beat.sender] c.a.n.c.naming - [CLIENT-BEAT] failed to send beat: {"cluster":"DEFAULT","ip":"192.168.30.41","metadata":{"preserved.register.source":"SPRING_CLOUD"},"port":9005,"scheduled":true,"serviceName":"DEFAULT_GROUP@@usercenter","weight":1.0}
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([tmc-nacos.ekuaibao.com:80]) tried: failed to req API:http://tmc-nacos.ekuaibao.com:80/nacos/v1/ns/instance/beat. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:227) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:109) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_181]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_181]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_181]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_181]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_181]

**Comment by chuntaojun** [comment]
配置中心的所有节点都可以访问吗？

**Comment by lza1997** [comment]
可以的，正常可以，但是idea开发，过几个小时就出现一次

**Comment by lza1997** [comment]
![02343FDC-C276-4A28-BE8A-6B950BB608E2](https://user-images.githubusercontent.com/22244178/58939316-f5a0e900-8744-11e9-835c-8e41ac5e8662.png)

**Comment by lza1997** [comment]
![image](https://user-images.githubusercontent.com/22244178/58939534-6811c900-8745-11e9-9211-2b5d4541f177.png)，java端配置

**Comment by chuntaojun** [comment]
你看下nacos server 对应的日志信息，在你出现此错误的前后三十秒时间内

**Comment by lza1997** [comment]
我在k8s中查看了三个节点的日志，没有任何信息，好奇怪

**Comment by chuntaojun** [comment]
> 我在k8s中查看了三个节点的日志，没有任何信息，好奇怪

你加下我钉钉吧 dvxx6ro

**Comment by chuntaojun** [comment]
I'll solve it
