### ISSUE TITLE
Custom `groupName` are not supported when I registering service

### ISSUE THREAD

**Issue by wolfdriver** [alibaba/nacos#1346]
## Issue Description
There is http error 404, when I request URL `http://ip:8848/nacos/v1/ns/catalog/service?serviceName=xxx&groupName=yyy&namespaceId=zzz`

And I found the following error message in `logs/naming-server.log`:
```
com.alibaba.nacos.naming.exception.NacosException: serivce DEFAULT_GROUP@@xxx is not found!
	at com.alibaba.nacos.naming.controllers.CatalogController.instanceList(CatalogController.java:112)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)

### Describe what you expected to happen


### How to reproduce it (as minimally and precisely as possible)

### Tell us your environment
linux , nacosV1.0.0

### Anything else we need to know?

Custom `groupName` are not supported when I registering service. This works fine when I don't use the` groupName` parameter for `NamingService#registerInstance()`

**Comment by nkorange** [comment]
That's weird, this url works for me. And your url 'catalog/service' is not relevant to the error stack 'CatalogController.instanceList' .
