### ISSUE TITLE
no available server

### ISSUE THREAD

**Issue by 1346735074** [alibaba/nacos#1350]
```
2019-06-11 10:20:40.311 [com.alibaba.nacos.client.Worker.longPollingfixed-10.1.1.99_32000-bd7aa53d-edc4-4f5e-99a7-7b03d760c644] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-10.1.1.99_32000-bd7aa53d-edc4-4f5e-99a7-7b03d760c644] [check-update] get changed dataId exception
java.net.ConnectException: no available server
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:141)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:361)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:335)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```
迁移到k8s nacos  该错误出现频繁，内网环境
之前docker 集群环境基本正常

**Comment by nkorange** [comment]
#1214 已经修复这个日志频繁问题，但是你这个问题的根因还是你的server连不上，需要检查下你的serverAddr是否能够连上

**Comment by jinshubao** [comment]
同样的问题，内网环境，启动就报错
```
2019-06-19 17:46:32.491  INFO 16108 --- [1c-46bc0d1804e0] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2019-06-19 17:46:32.508  INFO 16108 --- [1c-46bc0d1804e0] o.s.boot.SpringApplication               : Started application in 1.354 seconds (JVM running for 19.678)
2019-06-19 17:46:32.537  INFO 16108 --- [1c-46bc0d1804e0] com.alibaba.druid.pool.DruidDataSource   : set poolPreparedStatements false -> false
2019-06-19 17:46:32.553  INFO 16108 --- [1c-46bc0d1804e0] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: []
2019-06-19 17:50:58.605 ERROR 16108 --- [1c-46bc0d1804e0] c.a.n.c.config.http.ServerHttpAgent      : [NACOS SocketTimeoutException]
2019-06-19 17:50:58.606 ERROR 16108 --- [1c-46bc0d1804e0] c.a.n.c.config.http.ServerHttpAgent      : no available server
2019-06-19 17:50:58.610 ERROR 16108 --- [1c-46bc0d1804e0] c.a.n.client.config.impl.ClientWorker    : [fixed-10.52.2.53_8848-da5b375b-f215-4f9c-921c-46bc0d1804e0] [check-update] get changed dataId exception

java.net.ConnectException: no available server
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:141)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:361)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:335)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:478)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)


```

**Comment by 1346735074** [comment]
@jinshubao 你好 这个问题 如果可以获取到配置的话 说明nacos正常  偶尔抛这个异常的话  源码里面设置的连接时间有点短的原因导致这个异常了  好像是1秒 连接服务器超过这个数字就好判断nacos异常了

**Comment by jinshubao** [comment]
非常感谢你的回复，我把超时时间设置长点试试

发自我的 iPhone

**Comment by nkorange** [comment]
我先关闭issue，如果你还存在问题，请重新打开

**Comment by lvgitt** [comment]
一模一样的问题，求解决方法

**Comment by tangaoyu520hf** [comment]
一模一样的问题，求解决方法，是不是该升级一个版本了，我现在用的1.0.1
