### ISSUE TITLE
After stopping the services what have registered in nacos, a series of errors occurred.

### ISSUE THREAD

**Issue by hyygavin1990** [alibaba/nacos#1370]
2019-06-14 10:07:00.821  ERROR 8 --- [com.alibaba.nacos.client.naming.updater] c.a.n.c.naming: [NA] failed to update serviceName: DEFAULT_GROUP@@rule-server
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([192.168.2.168:8848, 192.168.2.169:8848]) tried: failed to req API:http://192.168.2.169:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@rule-server
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
        at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

## Issue Description
Stop the successful registration service, the service list in nacos will not disappear, and when the service is deleted by the delete function in the nacos page, all the services registered on the nacos will have 404 error.
停止注册成功的服务，nacos中的服务列表不会消失，而且当用nacos页面中的删除功能删除该服务时，所有注册在该nacos上的服务，都会出现404报错

#environment
nacos 1.0.1 
springcloud Finchley.SR1 
spring-cloud-alibaba 0.2.2.RELEASE
springboot 2.0.5.RELEASE

**Comment by IanCao** [comment]
#1367

**Comment by hyygavin1990** [comment]
两个服务没有关联性，主动的想要关闭一个服务，没有道理另一个服务也会受到影响啊

**Comment by nkorange** [comment]
> 两个服务没有关联性，主动的想要关闭一个服务，没有道理另一个服务也会受到影响啊

请截取控制台的页面和你调用端的报错

**Comment by hyygavin1990** [comment]
vipkid-v4-rule-server是一个服务，我已将其关闭，但是服务列表中，依然显示红色，不会自动消失
![1560580016](https://user-images.githubusercontent.com/10229939/59547983-bcede480-8f7a-11e9-9673-fbd5de7c5cfd.jpg)
当我用删除按钮，删除这个服务之后，其他服务就开始疯狂报错
![微信图片_20190615143648](https://user-images.githubusercontent.com/10229939/59548002-0cccab80-8f7b-11e9-9199-b2d96a9d221c.png)

**Comment by hyygavin1990** [comment]
当我再次上线这个服务，报错停止

**Comment by 11122604** [comment]
nacos

**Comment by nkorange** [comment]
这个问题会在 #1367 解决
