### ISSUE TITLE
empty config at nacos-server make an exception java.util.ConcurrentModificationException: null

### ISSUE THREAD

**Issue by Comven** [alibaba/nacos#1383]
nacos 1.0.0
spring-cloud Greenwich SR1

当在程序中配置了配置中心地址后spring.cloud.nacos.config.server-addr后，15日凌晨1点过突然出现了一个这样的问题
`[fixed-127.0.0.1_8848] [sub-server] get server config exception, dataId=xxx-center.properties, group=DEFAULT_GROUP, tenant=

java.net.ConnectException: no available server`

我想可能是因为配置了配置中心地址，但却有增加对应的配置的关系。于是在nacos服务端配置列表增加一个配置xxx-center.properies后，由于不允许直接发布空文件，于是随便配置了一个参数`test=1`。然后当我启动xxx-center程序后直接报错，程序挂掉。错误如下：
`
java.util.ConcurrentModificationException: null
	at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:909)
	at java.util.ArrayList$Itr.next(ArrayList.java:859)
	at org.springframework.cloud.netflix.ribbon.RibbonApplicationContextInitializer.initialize(RibbonApplicationContextInitializer.java:46)
	at org.springframework.cloud.netflix.ribbon.RibbonApplicationContextInitializer.onApplicationEvent(RibbonApplicationContextInitializer.java:54)
	at org.springframework.cloud.netflix.ribbon.RibbonApplicationContextInitializer.onApplicationEvent(RibbonApplicationContextInitializer.java:30)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.boot.context.event.EventPublishingRunListener.running(EventPublishingRunListener.java:105)
	at org.springframework.boot.SpringApplicationRunListeners.running(SpringApplicationRunListeners.java:78)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:332)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
`
根据提示找到`RibbonApplicationContextInitializer`发现是如下代码中
`
	protected void initialize() {
		if (clientNames != null) {
			for (String clientName : clientNames) {
				this.springClientFactory.getContext(clientName);
			}
		}
	}
`
在初始化过程中clientNames的元素值被改为了null，因为我程序中使用了`ribbon.eager-load`加载配置所以报了这个ribbon初始化的异常。

当我删掉nacos服务端的xxx.properties后，程序才能够正常启动。

**Comment by Comven** [comment]
How can I solve this problem?

**Comment by glameyzhou** [comment]
我也碰到了同样的问题，nacos spring cloud版本都一样。

我的问题是，配置了robbin.eager-load下面初始化了三个clients。启动就报错了，说ConcurrentModificationException异常，但是不知道是在那个地方把clients列表做了修改。

**Comment by Comven** [comment]
Using Nacos as the configuration center causes this exception

**Comment by xlb** [comment]
我也遇到了这个问题，目前的解决方案是把 eager-load全部注释掉，不知道楼主有没有比较好的解决方法，之前用eureka 及springcloudconfig是没有这个问题的

**Comment by xlb** [comment]
关键我本地elipse启动是不错报错的，这也很奇怪

**Comment by xlb** [comment]
原因找到了，之前由于用的是springcloudconfig，我的写法是类似于
```
ribbon:
  eager-load:
    enabled: true
    clients: a,b
```
然后本身配置要求的是一个string List，估计springcloudconfig做了支持，
现在修改成 
```
ribbon:
  eager-load:
    enabled: true
    clients:
      - a
      - b
```
即可
