### ISSUE TITLE
SocketTimeoutException happened every few minutes

### ISSUE THREAD

**Issue by wmj765** [alibaba/nacos#1439]
## Issue Description

SocketTimeoutException happened every few minutes. actually , the network is ok

### Describe what happened (or what feature you want)
servers are normal,and also can call the api interface normally;but SocketTimeoutException happened every few minutes including naming.updater、naming.beat.sender

java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:89)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:326)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
|-  -|-  -| provider -| 2019-06-27 15:24:16.939 -| ERROR -| com.alibaba.nacos.client.naming.updater -| com.alibaba.nacos.client.naming [370] -| request 139.217.80.102:7000 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://139.217.80.102:7000/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Tell us your environment
nacos 1.0.1
nacos-discovery 0.2.2.RELEASE
nacos-config 0.2.2.RELEASE

**Comment by wmj765** [comment]
I can request http://139.217.80.102:7000/nacos/v1/ns/instance/list success on the Browser in Local environment,but why the beat request failed;

**Comment by nkorange** [comment]
Does the command ```curl http://139.217.80.102:7000/nacos/v1/ns/instance/list``` return 200 on the Nacos client machine?

**Comment by wmj765** [comment]
yes,it can return right result; i copy the callNacosServer method in the nacos client with params which request failed,and  I try more than 100 times,it returns correctly;
![image](https://user-images.githubusercontent.com/19549289/60319681-d1ce6d00-99a9-11e9-93b5-23ffe8954a2f.png)

![image](https://user-images.githubusercontent.com/19549289/60319726-fb879400-99a9-11e9-8ee8-ff68d20c5fb2.png)

**Comment by wmj765** [comment]
code=500  means some errors occured in the nacos server,but i can not find the error log in nacos server;
only have ---2019-06-28 03:37:45,542|29500|timeout|139.217.80.102|polling|1|75--- logs in config-client-request.log;
![image](https://user-images.githubusercontent.com/19549289/60320128-4eae1680-99ab-11e9-9ad7-f8fc5062896c.png)

**Comment by nkorange** [comment]
Do you have your network monitored? Was there any network failure? And also check the GC log of Nacos server please.

**Comment by wmj765** [comment]
When the client is deployed on the server side, the exception will not happen again. I guess The exception may be caused by the network.
I have some questions about the nacos-config，the client get configs  from the config-server by longpolling,and contrast  is  different by md5 . it is the polling mode, But How to ensure the efficiency of longpolling when i have about 1000 nodes,why not using the pushing mode? 
can u help me about the doubt,thanks a lot.
