### ISSUE TITLE
运行example 报告无法找到日志类: org.apache.logging.log4j.core.Logger

### ISSUE THREAD

**Issue by chinausers** [alibaba/nacos#145]
我试着使用现在的版本尝试跑一下 example 下的configexample 得到了如下报错 ：
Tue Oct 23 19:22:54 CST 2018 sun.misc.Launcher$AppClassLoader@18b4aac2 JM.Log:WARN Init JM logger with NopLoggerFactory, pay attention. sun.misc.Launcher$AppClassLoader@18b4aac2
java.lang.ClassNotFoundException: org.apache.logging.log4j.core.Logger
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.alibaba.nacos.client.logger.log4j2.Log4j2LoggerFactory.<init>(Log4j2LoggerFactory.java:33)
	at com.alibaba.nacos.client.logger.LoggerFactory.<clinit>(LoggerFactory.java:59)
	at com.alibaba.nacos.client.config.utils.LogUtils.<clinit>(LogUtils.java:50)
	at com.alibaba.nacos.client.config.NacosConfigService.<clinit>(NacosConfigService.java:53)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:43)
	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:44)
	at com.alibaba.nacos.example.ConfigExample.main(ConfigExample.java:40)
似乎与依赖有关系 - -..........

**Comment by chinausers** [comment]
db.num=2
db.url.0=jdbc:mysql://11.162.196.161:3306/diamond_devtest?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.url.1=jdbc:mysql://11.163.152.91:3306/diamond_devtest?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.user=diamond_devtest
db.password=4b9622f3f70c7677835ac5a6719e7caf
..... 这个配置也能放上来吗。。。

**Comment by chinausers** [comment]
默认模式 我直接拉master的代码 exmaple跑一下就error就报错了 怀疑是依赖问题 但是不知道为什么 。

**Comment by yanlinly** [comment]
loss log impl , i fix it. thx!
