### ISSUE TITLE
Too much error logs if service does not exist

### ISSUE THREAD

**Issue by ralf0131** [alibaba/nacos#1450]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)

When request to `com.alibaba.nacos.client.naming.NacosNamingService#getAllInstances(java.lang.String, java.util.List<java.lang.String>)`, if the service does not exist, the following exception stackstrace will be thrown:

```
ErrCode:500,ErrMsg:failed to req API:http://127.0.0.1:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@configurators:org.apache.dubbo.demo.DemoService:1.0.0.test:xxxxxxx
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor.getServiceInfo(HostReactor.java:232)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:373)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:365)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:354)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:334)
	at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doSubscribe$3(NacosRegistry.java:169)
```

### Describe what you expected to happen

Do not log the errors, but throw the exception to the caller. Let the caller to decide how to handle the exception.

### How to reproduce it (as minimally and precisely as possible)

1. Start a Dubbo provider  with NacosRegistry, version 2.7.3-SNAPSHOT
2. Start a Dubbo consumer, with NacosRegistry, version 2.7.3-SNAPSHOT
3. You will see lots of error logs go output every few seconds.

### Tell us your environment

MacOS + Java 11

**Comment by nkorange** [comment]
Already tracked in #1367 and will be fixed in 1.1.0
