### ISSUE TITLE
The nacos registry function is used under k8s, but a service is scrolled to the last pod when it is removed. An exception will be issued.

### ISSUE THREAD

**Issue by pengzai170** [alibaba/nacos#1451]
k8s下使用nacos的注册中心功能，但某一个服务滚动更新到最后一个pod移除的时候。就会发出异常。
nacos:1.0
docker：17.3.2
k8s: v1.11.3

system_error_rules_dingtalk

@timestamp: 2019-06-27T10:15:59.860Z
@version: 1
_id: rNhvmGsBj9kHEinWT8sr
_index: qbxc-product-2019.06.27
_type: doc
env: prod
env,source,logger: prod, shopxxx, org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask
host: None
level: ERROR
location: {
    "class": "org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask", 
    "file": "ReconnectTimerTask.java", 
    "line": "51", 
    "method": "doTask"
}
logger: org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask
message:  [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [172.20.160.104:0 -> /172.20.166.88:20880]], dubbo version: 2.7.1, current host: 172.20.160.104
num_hits: 4
num_matches: 4
path: None
source: shopxxx
tags: []
thread: dubbo-client-idleCheck-thread-1
throwable: org.apache.dubbo.remoting.RemotingException: client(url: dubbo://172.20.166.88:20880/com.xxx.api.xxx.service.TakeOutPageService?anyhost=true&application=shopxxx&bean.name=providers:dubbo:com.xxx.api.xxx.service.TakeOutPageService:1.0.0&category=providers&check=false&codec=dubbo&default.check=false&default.deprecated=false&default.dynamic=false&default.generic=false&default.lazy=false&default.register=true&default.sticky=false&deprecated=false&dubbo=2.0.2&dynamic=false&generic=false&heartbeat=60000&interface=com.xxx.api.xxx.service.TakeOutPageService&lazy=false&methods=takeOutOrderList,takeOutOrderDetail&path=com.xxx.api.xxx.service.TakeOutPageService&pid=7&protocol=dubbo&qos.enable=false&register=true&register.ip=172.20.160.104&release=2.7.1&remote.application=xxx&remote.timestamp=1561627750779&revision=1.0.0&side=consumer&sticky=false&timestamp=1561429165129&version=1.0.0) failed to connect to server /172.20.166.88:20880 client-side timeout 3000ms (elapsed: 3000ms) from netty client 172.20.160.104 using dubbo version 2.7.1
  at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:136) ~[dubbo-2.7.1.jar!/:2.7.1]
  at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:186) ~[dubbo-2.7.1.jar!/:2.7.1]
  at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:242) ~[dubbo-2.7.1.jar!/:2.7.1]
  at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:152) ~[dubbo-2.7.1.jar!/:2.7.1]
  at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49) ~[dubbo-2.7.1.jar!/:2.7.1]
  at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87) [dubbo-2.7.1.jar!/:2.7.1]
  at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648) [dubbo-2.7.1.jar!/:2.7.1]
  at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727) [dubbo-2.7.1.jar!/:2.7.1]
  at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449) [dubbo-2.7.1.jar!/:2.7.1]
  at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

**Comment by nkorange** [comment]
看起来是Dubbo报错了，是否有Nacos相关的错误？
