### ISSUE TITLE
nacos server naming-server.log print many NacosException: service not found

### ISSUE THREAD

**Issue by xuxiao1987** [alibaba/nacos#1466]
env: 2 nacos server, version: 1.0.0 release
2 nacos server nodes print error  logs quickly in naming-server.log，msgs is like this：
2019-07-02 20:54:46,674 ERROR got exception. service not found: DEFAULT_GROUP@@imageUploadServer

com.alibaba.nacos.naming.exception.NacosException: service not found: DEFAULT_GROUP@@imageUploadServer
        at com.alibaba.nacos.naming.controllers.InstanceController.doSrvIPXT(InstanceController.java:372)
        at com.alibaba.nacos.naming.controllers.InstanceController.list(InstanceController.java:169)

imageUploadServer service was discard and is not regist on nacos server list， why print this error logs？

**Comment by nkorange** [comment]
This will be fixed in #1367
