### ISSUE TITLE
Pseudo-cluster clientBeat failed

### ISSUE THREAD

**Issue by OneJane** [alibaba/nacos#1514]
## 通过官方的样例伪集群启动nacos启动一段时间报错

```
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:304) [nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:327) [nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310) [nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.callAllServers(NamingProxy.java:238) [nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:99) [nacos-client-0.6.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]

2019-07-09 19:27:22.920 ERROR 20620 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : [] [] [NA] req api:/nacos/v1/ns/api/clientBeat failed, servers: [192.168.2.155:183]

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/clientBeat after all servers([192.168.2.155:183]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.callAllServers(NamingProxy.java:238) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:99) [nacos-client-0.6.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]
```
基本访问操作都没问题，就是客户端连接后报错心跳检测的错误。
### 版本
spring-cloud-alibaba：0.2.1.RELEASE
spring-cloud：Finchley.SR2
NACOS：1.0.1

**Comment by nkorange** [comment]
{user.home}/logs/nacos/naming.log看看具体错误是什么。

**Comment by OneJane** [comment]
更新版本解决问题
