### ISSUE TITLE
java.net.ConnectException: no available server

### ISSUE THREAD

**Issue by rogerlmj123** [alibaba/nacos#1542]
配置中心更新配置文件，控制台就报如下错误

When the configuration center updates the configuration file, the console reports the following error

----------------------The questions are as follows---------------------------
2019-07-12 23:18:08,650 [main] INFO (StartupInfoLogger.java:59)- Started OpenGatewayApplication in 7.113 seconds (JVM running for 7.644)
2019-07-12 23:19:05,679 [com.alibaba.nacos.client.Worker.longPollingfixed-financial-nacos_8848] ERROR (ServerHttpAgent.java:130)- [NACOS SocketTimeoutException]
2019-07-12 23:19:05,679 [com.alibaba.nacos.client.Worker.longPollingfixed-financial-nacos_8848] ERROR (ServerHttpAgent.java:140)- no available server
2019-07-12 23:19:05,682 [com.alibaba.nacos.client.Worker.longPollingfixed-financial-nacos_8848] ERROR (ClientWorker.java:373)- [fixed-financial-nacos_8848] [check-update] get changed dataId exception
java.net.ConnectException: no available server
at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:141)
at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64)
at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:361)
at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:335)
at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:478)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by nkorange** [comment]
请检查你的Server是否能正常连上：
```
curl '$nacos_server:8848/nacos/v1/cs/health'
```
