### ISSUE TITLE
Nacos Server1.1.0 cluster mode cluster.conf cannot be started normally using hostname

### ISSUE THREAD

**Issue by onethin** [alibaba/nacos#1582]
## Issue Description
bug report
Nacos Server1.1.0，集群模式，cluster.conf里面配置主机名无法正常启动
cluster.conf里的配置如下，主机名与IP的映射均在hosts里正常配置，hostname -i可正常显示IP
zk-test-app1
zk-test-app2
zk-test-app3
启动naming-server.log报错如下异常：
2019-07-22 16:54:25,768 WARN [STATUS-SYNCHRONIZE] failed to request serviceStatus, remote server: zk-test-app1:8848
2019-07-22 16:54:25,770 WARN [STATUS-SYNCHRONIZE] failed to request serviceStatus, remote server: zk-test-app3:8848
2019-07-22 16:54:25,771 WARN [STATUS-SYNCHRONIZE] failed to request serviceStatus, remote server: zk-test-app2:8848
2019-07-22 16:54:26,692 ERROR got exception. ip: 10.32.233.222:8848 is not in serverlist
com.alibaba.nacos.naming.exception.NacosException: ip: 10.32.233.222:8848 is not in serverlist
	at com.alibaba.nacos.naming.controllers.ServiceController.serviceStatus(ServiceController.java:309)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)

### Describe what happened (or what feature you want)
集群的节点无法正常选举成功，服务不可用

### Describe what you expected to happen
应该正常启动并选举成功

### How to reproduce it (as minimally and precisely as possible)

1. cluster.conf使用主机名配置

### Tell us your environment
Redhat Enterprise Linux X64
Oracle JDK x64 8u191

### Anything else we need to know?
如果cluster.conf改成IP列表能正常启动成功

**Comment by nkorange** [comment]
You have to set the following property in the application.properties to make Nacos recognize hostname:
```properties
nacos.inetutils.prefer-hostname-over-ip=true
```
