### ISSUE TITLE
What's the matter with this problem?  Client service cannot regist to nacos.

### ISSUE THREAD

**Issue by winnyboy** [alibaba/nacos#1589]
nacos ns get an exception within starting:
`java.lang.IllegalStateException: unable to find local peer: 121.201.65.156:8848, all peers: [192.168.122.1:8848]
        at com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.local(RaftPeerSet.java:224)
        at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore$MasterElection.run(RaftCore.java:370)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2019-07-23 17:32:29,892 INFO initializing Raft sub-system
2019-07-23 17:32:29,893 INFO finish loading all datums, size: 0 cost 0 ms.
2019-07-23 17:32:29,893 INFO raft notifier started
2019-07-23 17:32:29,895 INFO cache loaded, datum count: 0, current term: 0
2019-07-23 17:32:29,895 INFO finish to load data from disk, cost: 2 ms.
2019-07-23 17:32:29,756 INFO server list is updated, new: 1 servers: [{"adWeight":0,"alive":false,"ip":"192.168.122.1","key":"192.168.122.1:0","lastRefTime":0,"servePort":0,"site":"unknown","weight":1}]
2019-07-23 17:32:29,916 INFO timer started: leader timeout ms: 15000, heart-beat timeout ms: 5000
2019-07-23 17:32:29,928 INFO raft peers changed: [{"adWeight":0,"alive":false,"ip":"192.168.122.1","key":"192.168.122.1:0","lastRefTime":0,"lastRefTimeStr":"","servePort":0,"site":"unknown","weight":1}]
2019-07-23 17:32:30,026 INFO add listener: com.alibaba.nacos.naming.domains.meta.
2019-07-23 17:32:32,079 INFO add listener: com.alibaba.nacos.naming.domains.meta.00-00---000-NACOS_SWITCH_DOMAIN-000---00-00
2019-07-23 17:32:34,746 INFO server list is updated, new: 1 servers: [{"adWeight":0,"alive":false,"ip":"192.168.122.1","key":"192.168.122.1:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]
2019-07-23 17:32:34,746 INFO server list is updated, dead: 1, servers: [{"adWeight":0,"alive":false,"ip":"192.168.122.1","key":"192.168.122.1:0","lastRefTime":0,"lastRefTimeStr":"","servePort":0,"site":"unknown","weight":1}]
2019-07-23 17:32:34,746 INFO raft peers changed: [{"adWeight":0,"alive":false,"ip":"192.168.122.1","key":"192.168.122.1:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]
2019-07-23 17:32:34,748 INFO raft peers changed: [{"adWeight":0,"alive":false,"ip":"192.168.122.1","key":"192.168.122.1:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]
2019-07-23 17:32:45,005 WARN [IS LEADER] no leader is available now!
2019-07-23 17:32:46,397 INFO leader timeout, start voting,leader: null, term: 0
2019-07-23 17:33:00,000 WARN [IS LEADER] no leader is available now!
2019-07-23 17:33:02,396 INFO leader timeout, start voting,leader: null, term: 1`

And when client service regist to nacos , its got exception of 
`java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([121.201.65.156:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:374)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:300)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:185)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:280)`

and meanwhile,  when i use command of curl `curl -X GET 'http://192.168.122.1:8848/nacos/v1/ns/instance?serviceName=api-gateway&ip=10.96.4.23&port=6128` and get a result text of 'server is DOWN now, please try again later!'.

Some properties in  application.properties are setting as below:
`nacos.inetutils.ip-address=192.168.122.1
nacos.inetutils.use-only-site-local-interfaces=true
nacos.inetutils.preferred-networks[0]=192.168.122.
nacos.inetutils.preferred-networks[0]=192.168.122.(25[0-5]|2[0-4]\\d|((1d{2})|([1-9]?\\d))),30.5.124.(25[0-5]|2[0-4]\\d|((1d{2})|([1-9]?\\d)))`

Anyone can tell me what's the matter? how to correct it ?

**Comment by winnyboy** [comment]
I have set the properties of :
nacos.inetutils.ip-address=192.168.122.1
nacos.inetutils.use-only-site-local-interfaces=true

but its gets an exception when I execute the command of 'curl -X POST 'http://192.168.122.1:8848/nacos/v1/ns/instance?serviceName=api-gateway&ip=10.96.4.23&port=6128', its get respond text of 'server is DOWN now, please try again later!'

**Comment by winnyboy** [comment]
Now I got an exception with nacos starting as described below:
`javax.net.ssl.SSLException: Certificate for <192.168.122.1> doesn't match common name of the certificate subject: test.xxx.com`
ns get respond text as mentioned above

**Comment by winnyboy** [comment]
Now got an Exception: `java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([121.201.65.156:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:374)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:347)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290)
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:272)
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:249)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:406)
`

**Comment by winnyboy** [comment]
It's resolved
