### ISSUE TITLE
When I visit a service url api but the service is not started, then the gateway print the error all the time, never stop until I start the service

### ISSUE THREAD

**Issue by gclsoft** [alibaba/nacos#1608]
## Issue Description
I'm using spring cloud gateway and nacos.
When I visit a service url api but the service is not started, then the gateway print the error all the time, never stop until I start the service

### Describe what happened (or what feature you want)
```
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://pigx-register:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@pigx-codegen
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273) [nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]

2019-07-26 11:48:27.468 ERROR 148344 --- [.naming.updater] com.alibaba.nacos.client.naming          : [NA] failed to update serviceName: DEFAULT_GROUP@@pigx-codegen

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([pigx-register:8848]) tried: failed to req API:http://pigx-register:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@pigx-codegen
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318) [nacos-client-1.0.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_151]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
```
I have set the yaml:
```
spring

  zipkin:

   #他不断的去跟踪所有服务，
      discovery-client-enabled: false
```
But not work

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
This error indicates that you query a service named 'pigx-codegen'. Please check if this service is already registered.

**Comment by nkorange** [comment]
Also upgrade to nacos-client 1.1.3, which depresses the error log.
