### ISSUE TITLE
naocs 1.0.1 code:503 msg: server is DOWN now, please try again later!

### ISSUE THREAD

**Issue by xiaobailalala** [alibaba/nacos#1657]
nacos为集群方式启动，部署环境是k8s，先前使用的是nacos 0.9.0集群，由于k8s组件变更，将原先的kube-dns替换为coredns，相应的容器服务也重新部署。重新部署了nacos集群后发生这类问题：集群启动看似正常，在3 node的-raft日志中没有发现异样
![image](https://user-images.githubusercontent.com/29720406/62547617-14804080-b898-11e9-898b-90c7e8ff1d61.png)
进行服务发布时出现无法正常注册的情况：
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([nacos-headless:8848]) tried: failed to req API:http://nacos-headless:8848/nacos/v1/ns/service/list. code:503 msg: server is DOWN now, please try again later!
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380) ~[nacos-client-1.0.0.jar!/:na]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:346) ~[nacos-client-1.0.0.jar!/:na]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:294) ~[nacos-client-1.0.0.jar!/:na]
        at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:276) ~[nacos-client-1.0.0.jar!/:na]
        at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:252) ~[nacos-client-1.0.0.jar!/:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:525) ~[nacos-client-1.0.0.jar!/:na]
        at org.springframework.cloud.alibaba.nacos.discovery.NacosWatch.nacosServicesWatch(NacosWatch.java:127) ~[spring-cloud-alibaba-nacos-discovery-0.9.0.RELEASE.jar!/:0.9.0.RELEASE]
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.5.RELEASE.jar!/:5.1.5.RELEASE]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_111]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) ~[na:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) ~[na:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
在问题区看到类似的情况，因此将镜像换为1.0.1，问题仍然存在

**Comment by nkorange** [comment]
It seems everything is normal, please update to Nacos 1.1.3 and see what happens.
