### ISSUE TITLE
Nacos k8s failed to start and found that the service domain has one more. How can this be clear?

### ISSUE THREAD

**Issue by shaojielinux** [alibaba/nacos#1690]
java.lang.IllegalStateException: unable to find local peer: nacos-0.nacos-headless.nacos.svc.cluster.local.:8848, all peers: [nacos-2.nacos-headless.nacos.svc.cluster.local:8848, nacos-1.nacos-headless.nacos.svc.cluster.local:8848, nacos-0.nacos-headless.nacos.svc.cluster.local:8848]

     at com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.local(RaftPeerSet.java:224)
	at com.alibaba.nacos.naming.monitor.PerformanceLoggerThread.collectMetrics(PerformanceLoggerThread.java:100)
	at sun.reflect.GeneratedMethodAccessor74.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by paderlol** [comment]
quickstart or nfs？

**Comment by shaojielinux** [comment]
nfs

**Comment by shaojielinux** [comment]
Is there any way to solve this problem?

**Comment by shaojielinux** [comment]
Is there any way to solve this problem?

**Comment by paderlol** [comment]
This problem has already fixed, you can see that [PR](https://github.com/nacos-group/nacos-k8s/pull/50)

**Comment by paderlol** [comment]
If you don't use the peerfinder plugin, you need to solve this problem yourself, because this is a problem with k8s dns.

**Comment by shaojielinux** [comment]
解决因kubelet参数--cluster-domain = cluster.local。 修改这个参数？

**Comment by paderlol** [comment]
你可以这么解决,但是目前peerfinder那个插件会去解决这个问题,如果你没用这个peerfinder这个插件,那就只能通过k8s指定来解决了

**Comment by paderlol** [comment]
如果使用了peerfinder就更新一下镜像

**Comment by KomachiSion** [comment]
Can you try to use latest version and retry? The issue is too old to search. If latest version still has problem, please open a new issue let us know.
