### ISSUE TITLE
使用服务治理时 nacos地址被301重定向到https时报错  When using service governance, the nacos address is reported incorrectly when redirected to https by 301. 

### ISSUE THREAD

**Issue by zzhgithub** [alibaba/nacos#1696]
## Issue Description
When using service governance, the nacos address is reported incorrectly when redirected to https by 301.
使用服务治理时 nacos地址被301重定向到https时报错

 *bug report* 

### Describe what happened 
服务治理配置一个地址，但是这个地址被301重定向到https了，报错了。
Service management configures an address, but this address is redirected to https by 301, and an error is reported.

### Describe what you expected to happen
报错信息
```
 Error watching Nacos Service change

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([nacos.xxx.com:80]) tried: failed to req API:http://nacos.baffedu.com:80/nacos/v1/ns/service/list. code:301 msg: 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:346) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:294) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:276) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:252) ~[nacos-client-1.0.0.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:525) ~[nacos-client-1.0.0.jar:na]
	at org.springframework.cloud.alibaba.nacos.discovery.NacosWatch.nacosServicesWatch(NacosWatch.java:127) ~[spring-cloud-alibaba-nacos-discovery-0.9.0.RELEASE.jar:0.9.0.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_152]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_152]

```

### Tell us your environment
```
<spring-cloud.version>Greenwich.SR1</spring-cloud.version>

<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>0.9.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

**Comment by nkorange** [comment]
请确认```http://nacos.baffedu.com:80```这个地址是否正确配置了Nacos服务端地址，Nacos本身不会返回301的。

**Comment by zzhgithub** [comment]
调查过了 是ng做的http强跳的https。 这里客户端不能支持吗?

**Comment by nkorange** [comment]
> 调查过了 是ng做的http强跳的https。 这里客户端不能支持吗?

那看起来应该是客户端没有使用https导致，可以参考[文档](https://nacos.io/zh-cn/docs/system-configurations.html)开启https：
```
-Dcom.alibaba.nacos.client.naming.tls.enable=true
```
