### ISSUE TITLE
Nacos login into the page cannot be nested into their system, the login prompt cross-domain...

### ISSUE THREAD

**Issue by longmingfeng** [alibaba/nacos#1724]
Nacos login into the page cannot be nested into their system, the login prompt cross-domain...
![image](https://user-images.githubusercontent.com/26614867/63333533-3388d300-c36c-11e9-8b40-d32a265df41e.png)

**Comment by nkorange** [comment]
Repeated with #1495

**Comment by slieer** [comment]
这个问题解决了吗？ 版本1.1.4。   想把nacos和其它的若干维运页统一起来。

main.js:71 DOMException: Blocked a frame with origin "http://172.28.17.95:8848" from accessing a cross-origin frame.
    at R (http://172.28.17.95:8848/nacos/js/main.js:1:4809)
    at new ConfigurationManagement (http://172.28.17.95:8848/nacos/js/main.js:55:339167)
    at lo (http://172.28.17.95:8848/nacos/js/main.js:71:45257)
    at Lr (http://172.28.17.95:8848/nacos/js/main.js:71:60033)
    at Pr (http://172.28.17.95:8848/nacos/js/main.js:71:66478)
    at Ki (http://172.28.17.95:8848/nacos/js/main.js:71:90458)
    at qi (http://172.28.17.95:8848/nacos/js/main.js:71:90842)
    at Ds (http://172.28.17.95:8848/nacos/js/main.js:71:97701)
    at Es (http://172.28.17.95:8848/nacos/js/main.js:71:97088)
    at ks (http://172.28.17.95:8848/nacos/js/main.js:71:96111)
