### ISSUE TITLE
Nacos client memory overflow

### ISSUE THREAD

**Issue by oliver831220** [alibaba/nacos#1772]
nacos client 跑了几天后出现内存溢出，各种配置均为默认，依赖的nacos-client版本1.0.0, 日志如下：
![image](https://user-images.githubusercontent.com/38642890/63739350-73e1d700-c8bf-11e9-8455-c26478469678.png)

**Comment by 663534597** [comment]
我也遇到了相同的问题，我把nacos-client 升级到1.1.3版本还是有这个问题

**Comment by chenshao0594** [comment]
Hi  any update about this issue?
 thx.

**Comment by nkorange** [comment]
请jmap分析一下内存，看看哪些类的对象占据了内存？

**Comment by oliver831220** [comment]
昨天测试发现内存溢出日志如下

2019-09-09 13:58:57.837 [com.alibaba.nacos.client.Worker.longPollingfixed-10.0.2.90_8848-c1977baf-12c8-4342-9583-5534b27c4ead] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - longPolling error
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:717)
        at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:112)
        at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:96)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:95)
        at sun.net.www.http.HttpClient.putInKeepAliveCache(HttpClient.java:438)
        at sun.net.www.http.HttpClient.finished(HttpClient.java:395)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1856)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at com.alibaba.nacos.client.config.impl.HttpSimpleClient.httpPost(HttpSimpleClient.java:123)
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:115)
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64)
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:361)
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:335)
        at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:478)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

**Comment by chuntaojun** [comment]
升级nacos-client客户端为1.1.0+即可解决

问题代码

```java
public class ClientWorker {
    ...
    executorService = Executors.newCachedThreadPool(new ThreadFactory() {
            @Override
            public Thread newThread(Runnable r) {
                Thread t = new Thread(r);
                t.setName("com.alibaba.nacos.client.Worker.longPolling" + agent.getName());
                t.setDaemon(true);
                return t;
            }
        });
    ...
}
```
