### ISSUE TITLE
NPE when adding a instance if no leader in the raft cluster 

### ISSUE THREAD

**Issue by nanamikon** [alibaba/nacos#181]
**Version**
0.3.0-RC1

**Description**
Just as the title says

**How to replay**
Build a cluster with 3 node， and kill two of them，  finally call the api "PUT /nacos/v1/ns/instance",  the
server will return as follow
`
{
    "timestamp": "2018-10-29T06:48:16.283+0000",
    "status": 500,
    "error": "Internal Server Error",
    "message": "No message available",
    "path": "/nacos/v1/ns/instance"
}
`

**Error message**
1. Error code
`
Loggers.RAFT.info("[IS LEADER] leader: " + leader.ip + ", ip: " + ip);
`

1. Error stack
`
java.lang.NullPointerException: null
        at com.alibaba.nacos.naming.raft.PeerSet.isLeader(PeerSet.java:90)
        at com.alibaba.nacos.naming.raft.RaftCore.isLeader(RaftCore.java:897)
        at com.alibaba.nacos.naming.raft.RaftCore.signalPublish(RaftCore.java:186)
        at com.alibaba.nacos.naming.core.DomainsManager.easyAddOrReplaceDom(DomainsManager.java:282)
        at com.alibaba.nacos.naming.web.ApiCommands.addOrReplaceDom(ApiCommands.java:452)
        at com.alibaba.nacos.naming.web.ApiCommands.regDom(ApiCommands.java:266)
        at com.alibaba.nacos.naming.web.ApiCommands.regService(ApiCommands.java:544)
        at com.alibaba.nacos.naming.controllers.InstanceController.register(InstanceController.java:110)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:891)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:974)
        at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:888)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:664)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:851)
`

**Suggestion**
Adding a method to check the leader is null or not  instead of using leader object directly  and we can throw a nice nacos exception to user  when there is no leader now

**Comment by nkorange** [comment]
@nanamikon I will track this issue.
