### ISSUE TITLE
Tomcat war deployment garbled does not start properly

### ISSUE THREAD

**Issue by PQbaojian** [alibaba/nacos#1871]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
我想让 nacos  客户端在tomcat 里面启动 但是tomcat 默认是 GBK 编码 
建议解析 yml 和请求的 编码保持一致 或者默认都用utf-8
### Describe what you expected to happen
[192.168.248.1:9001] 2019-09-24 23:21:27.169 ERROR 35052 [RMI TCP Connection(3)-127.0.0.1] com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder parse data from Nacos error,dataId:taroco-authentication-server-dev.yml,data:# jpa閰嶇疆 鏁版嵁婧愰厤缃�
spring:
  datasource:
    url: ${base.mysql.url}/taroco_authentication?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull&allowPublicKeyRetrieval=true
    username: root
    password: mysql.PQbaojian520
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      pool-name: Taroco-Authentication-HikariCP
  #redis閰嶇疆
  redis:
    host: ${base.redis.host}
    port: ${base.redis.port}
    password: ${base.redis.password}
    database: 0
  session:
    store-type: redis

taroco:
  oauth2:
    key-store:
      location: classpath:taroco.jks
      secret: taroco!@#$
      alias: taroco
    url-permit-all:
      - /smsCode/*
      - /actuator/**
      - /login/mobile
      - /oauth/mobile
      - /oauth/exit
      - /webjars/**
      - /static/**
      - /**/*.css
      - /**/*.jpg
      - /**/*.jpeg
      - /**/*.png
      - /**/*.svg
      - /**/*.woff2
      - /**/*.js
      - /**/*.ico
,

org.yaml.snakeyaml.error.YAMLException: java.nio.charset.MalformedInputException: Input length = 1
at org.yaml.snakeyaml.reader.StreamReader.update(StreamReader.java:254) ~[snakeyaml-1.19.jar:na]
	at org.yaml.snakeyaml.reader.StreamReader.<init>(StreamReader.java:58) ~[snakeyaml-1.19.jar:na]
	at org.yaml.snakeyaml.Yaml.loadAll(Yaml.java:537) ~[snakeyaml-1.19.jar:na]
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:166) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.config.YamlProcessor.process(YamlProcessor.java:139) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.createProperties(YamlPropertiesFactoryBean.java:135) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at org.springframework.beans.factory.config.YamlPropertiesFactoryBean.getObject(YamlPropertiesFactoryBean.java:115) ~[spring-beans-5.0.9.RELEASE.jar:5.0.9.RELEASE]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:100) [spring-cloud-alibaba-nacos-config-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:75) [spring-cloud-alibaba-nacos-config-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:179) [spring-cloud-alibaba-nacos-config-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:159) [spring-cloud-alibaba-nacos-config-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:88) [spring-cloud-alibaba-nacos-config-2.0.0.RELEASE.jar:2.0.0.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94) [spring-cloud-context-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:654) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:390) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:331) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.run(SpringBootServletInitializer.java:157) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.createRootApplicationContext(SpringBootServletInitializer.java:137) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.boot.web.servlet.support.SpringBootServletInitializer.onStartup(SpringBootServletInitializer.java:91) [spring-boot-2.0.5.RELEASE.jar:2.0.5.RELEASE]
	at org.springframework.web.SpringServletContainerInitializer.onStartup(SpringServletContainerInitializer.java:172) [spring-web-5.0.9.RELEASE.jar:5.0.9.RELEASE]

### How to reproduce it (as minimally and precisely as possible)

1. 配置一个 utf-8的配置文件在 nacos 并且有 GBK 没有的字符
2. Windows 环境中安装 tomcat9 并部署 war
3. 因为默认请求yml 的编码是 utf-8 获取到的数据没得问题
4. 当解析 yml 文件的时候 用了默认的编码 Charset.defaultCharset() 此时为GBK 
class NacosPropertySourceBuilder ....
   ....
   if (fileExtension.equalsIgnoreCase("yaml") || fileExtension.equalsIgnoreCase("yml")) {
                    YamlPropertiesFactoryBean yamlFactory = new YamlPropertiesFactoryBean();
                    yamlFactory.setResources(new Resource[]{new ByteArrayResource(data.getBytes())});
                    return yamlFactory.getObject();
     }
   ...
5. 因为编码不一致导致部分特殊的 utf-8 字符不能读取就出现上述错误 

### Tell us your environment
windows 2008 或者 window10
tomcat 9

### Anything else we need to know?
建议解析 yml 和请求的 编码保持一致 或者默认都用utf-8

另外我希望这个项目越来越好

**Comment by amao12580** [comment]
same issue.

**Comment by chenquanyu** [comment]
It seems to be the same [issue](https://github.com/alibaba/spring-cloud-alibaba/issues/1200).
