### ISSUE TITLE
Dubbo can't link nacos, the error is as follows

### ISSUE THREAD

**Issue by suxg001** [alibaba/nacos#1889]
dubbo version: 2.7.1,   dubbo-registry-nacos 0.0.2    

 jar:file:/Users/wjj/.m2/repository/com/alibaba/dubbo-registry-nacos/0.0.2/dubbo-registry-nacos-0.0.2.jar!/META-INF/dubbo/com.alibaba.dubbo.registry.RegistryFactory, cause: com/alibaba/dubbo/registry/support/AbstractRegistryFactory
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:705)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:674)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:635)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:619)
	at org.apache.dubbo.common.extension.ExtensionLoader.getSupportedExtensions(ExtensionLoader.java:375)
	at org.apache.dubbo.common.extension.factory.SpiExtensionFactory.getExtension(SpiExtensionFactory.java:32)
	at org.apache.dubbo.common.extension.factory.AdaptiveExtensionFactory.getExtension(AdaptiveExtensionFactory.java:47)
	at org.apache.dubbo.common.extension.ExtensionLoader.injectExtension(ExtensionLoader.java:562)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:531)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:347)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:559)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:417)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:375)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:337)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:319)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:113)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:59)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at io.seata.samples.dubbo.starter.DubboAccountServiceStarter.main(DubboAccountServiceStarter.java:33)
Caused by: java.lang.NoClassDefFoundError: com/alibaba/dubbo/registry/support/AbstractRegistryFactory
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:702)
	... 27 more

**Comment by paderlol** [comment]
This is not an error caused by nacos
In dubbo version: 2.7.1, You should use the new **nacos** dependency
``` xml
     <!-- Dubbo dependencies -->
      <dependency>
        <groupId>org.apache.dubbo</groupId>
        <artifactId>dubbo-dependencies-bom</artifactId>
        <version>${dubbo.version}</version>
        <type>pom</type>
        <scope>import</scope>
      </dependency>

  <dependency>
      <groupId>org.apache.dubbo</groupId>
      <artifactId>dubbo-registry-nacos</artifactId>
      <version>2.7.1</version>
    </dependency>
```

**Comment by suxg001** [comment]
jar!/META-INF/dubbo/internal/org.apache.dubbo.registry.RegistryFactory, cause: com/alibaba/nacos/api/exception/NacosException
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:705)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:674)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:632)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:619)
	at org.apache.dubbo.common.extension.ExtensionLoader.getSupportedExtensions(ExtensionLoader.java:375)
	at org.apache.dubbo.common.extension.factory.SpiExtensionFactory.getExtension(SpiExtensionFactory.java:32)
	at org.apache.dubbo.common.extension.factory.AdaptiveExtensionFactory.getExtension(AdaptiveExtensionFactory.java:47)
	at org.apache.dubbo.common.extension.ExtensionLoader.injectExtension(ExtensionLoader.java:562)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:531)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:347)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:559)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:417)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:375)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:337)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:319)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:113)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:59)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at io.seata.samples.dubbo.starter.DubboAccountServiceStarter.main(DubboAccountServiceStarter.java:33)
Caused by: java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)

> This is not an error caused by nacos
> In dubbo version: 2.7.1, You should use the new **nacos** dependency
> 
> ```
>      
>       <dependency>
>         <groupId>org.apache.dubbo</groupId>
>         <artifactId>dubbo-dependencies-bom</artifactId>
>         <version>${dubbo.version}</version>
>         <type>pom</type>
>         <scope>import</scope>
>       </dependency>
> 
>   <dependency>
>       <groupId>org.apache.dubbo</groupId>
>       <artifactId>dubbo-registry-nacos</artifactId>
>       <version>2.7.1</version>
>     </dependency>
> ```

jar!/META-INF/dubbo/internal/org.apache.dubbo.registry.RegistryFactory, cause: com/alibaba/nacos/api/exception/NacosException
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:705)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:674)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:632)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:619)
	at org.apache.dubbo.common.extension.ExtensionLoader.getSupportedExtensions(ExtensionLoader.java:375)
	at org.apache.dubbo.common.extension.factory.SpiExtensionFactory.getExtension(SpiExtensionFactory.java:32)
	at org.apache.dubbo.common.extension.factory.AdaptiveExtensionFactory.getExtension(AdaptiveExtensionFactory.java:47)
	at org.apache.dubbo.common.extension.ExtensionLoader.injectExtension(ExtensionLoader.java:562)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:531)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:347)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:559)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:417)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:375)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:337)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:319)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:113)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:59)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:549)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
	at io.seata.samples.dubbo.starter.DubboAccountServiceStarter.main(DubboAccountServiceStarter.java:33)
Caused by: java.lang.NoClassDefFoundError: com/alibaba/nacos/api/exception/NacosException
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)

**Comment by paderlol** [comment]
plz import nacos api 
``` xml
 <dependency>
      <groupId>com.alibaba.nacos</groupId>
      <artifactId>nacos-client</artifactId>
    </dependency>
```

**Comment by suxg001** [comment]
add import nacos api
 <dependency>
      <groupId>com.alibaba.nacos</groupId>
      <artifactId>nacos-client</artifactId>
    </dependency>
last .....................................????????

com/alibaba/nacos/api/exception/NacosException
	at org.apache.dubbo.common.extension.ExtensionLoader.loadResource(ExtensionLoader.java:705)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadDirectory(ExtensionLoader.java:674)
	at org.apache.dubbo.common.extension.ExtensionLoader.loadExtensionClasses(ExtensionLoader.java:632)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtensionClasses(ExtensionLoader.java:619)
	at org.apache.dubbo.common.extension.ExtensionLoader.getSupportedExtensions(ExtensionLoader.java:375)
	at org.apache.dubbo.common.extension.factory.SpiExtensionFactory.getExtension(SpiExtensionFactory.java:32)
	at org.apache.dubbo.common.extension.factory.AdaptiveExtensionFactory.getExtension(AdaptiveExtensionFactory.java:47)
	at org.apache.dubbo.common.extension.ExtensionLoader.injectExtension(ExtensionLoader.java:562)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:531)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:347)
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:559)
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:417)
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:375)
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:337)
	at org.apache.dubbo.config.spring.ServiceBean.export(ServiceBean.java:319)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:113)
	at org.apache.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:59)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)

**Comment by paderlol** [comment]
Please refer to the case of [Dubbo](https://github.com/apache/dubbo-samples/tree/master/dubbo-samples-nacos)
