### ISSUE TITLE
update SwitchDomain cause NPE

### ISSUE THREAD

**Issue by EZLippi** [alibaba/nacos#1912]
## Issue Description

I try to update an entry in SwitchDomain use operator api, but cause a NullPointerException.

DistroConsistencyServiceImpl] [NACOS-DISTRO] error while notifying listener of key: com.alibaba.nacos.naming.domains.meta.00-00---000-NACOS_SWITCH_DOMAIN-000---00-00
java.lang.NullPointerException: null
	at com.alibaba.nacos.registry.consistency.ephemeral.distro.DistroConsistencyServiceImpl$Notifier.run(DistroConsistencyServiceImpl.java:420) [classes!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

Type: *bug report* 

### Describe what happened (or what feature you want)

![image](https://user-images.githubusercontent.com/5326814/66537163-172a3b00-eb52-11e9-9cda-410b573d7fe4.png)

![image](https://user-images.githubusercontent.com/5326814/66537115-f19d3180-eb51-11e9-9d12-8c9364702746.png)

![image](https://user-images.githubusercontent.com/5326814/66537283-75571e00-eb52-11e9-9dcb-11e7de9ea8a4.png)

**Comment by EZLippi** [comment]
i have another question, SwitchManager use DistroConsistencyService to apply the changes for switch domain, does it mean the changes apply to a server should be apply in other servers?

**Comment by nkorange** [comment]
![image](https://user-images.githubusercontent.com/4593375/66619281-ff64bc80-ec0e-11e9-9653-1c56bf515741.png)

This is weird, the switch datum key shouldn't have been mapped to DistroConsistencyService.

**Comment by EZLippi** [comment]
i see,i made a mistake
