### ISSUE TITLE
How to solve this problem： [NACOS-0002] no available server ERR-CODE: [NACOS-0002], Type: [环境问题],

### ISSUE THREAD

**Issue by zuixiaoyao001** [alibaba/nacos#1924]
## Issue Description

Nacos cluster built on ali cloud server is used as the configuration center. The project can start up and run normally, but the following log is always printed：
使用阿里云服务器上搭建的nacos集群作为配置中心，项目可以正常启动运行，但是总是打印如下日志：
2019-10-11 17:23:25.312 [com.alibaba.nacos.client.Worker.longPullingfixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] ERROR com.alibaba.nacos.client.config.impl.ServerHttpAgent - [] [] [NACOS  SocketTimeoutException] currentServerAddr:192.168.2.49:8848
2019-10-11 17:23:25.313 [com.alibaba.nacos.client.Worker.longPullingfixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] ERROR com.alibaba.nacos.client.config.impl.ServerHttpAgent - [] [] [NACOS-0002] no available server ERR-CODE: [NACOS-0002], Type: [环境问题], More: [http://console.taobao.net/help/NACOS-0002]
2019-10-11 17:23:25.313 [com.alibaba.nacos.client.Worker.longPullingfixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] [] [NACOS-XXXX] [check-update] get changed dataId exception, msg=java.net.ConnectException: no available server
2019-10-11 17:23:55.319 [com.alibaba.nacos.client.Worker.longPullingfixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] ERROR com.alibaba.nacos.client.config.impl.ServerHttpAgent - [] [] [NACOS  SocketTimeoutException] currentServerAddr:192.168.2.49:8848
2019-10-11 17:23:55.322 [com.alibaba.nacos.client.Worker.longPullingfixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] ERROR com.alibaba.nacos.client.config.impl.ServerHttpAgent - [] [] [NACOS-0002] no available server ERR-CODE: [NACOS-0002], Type: [环境问题], More: [http://console.taobao.net/help/NACOS-0002]
2019-10-11 17:23:55.322 [com.alibaba.nacos.client.Worker.longPullingfixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] [] [NACOS-XXXX] [check-update] get changed dataId exception, msg=java.net.ConnectException: no available server
2019-10-11 17:24:54.820 [com.alibaba.nacos.client.Worker.longPullingfixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] ERROR com.alibaba.nacos.client.config.impl.ServerHttpAgent - [] [] [NACOS  SocketTimeoutException] currentServerAddr:192.168.2.49:8848
2019-10-11 17:24:54.821 [com.alibaba.nacos.client.Worker.longPullingfixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] ERROR com.alibaba.nacos.client.config.impl.ServerHttpAgent - [] [] [NACOS-0002] no available server ERR-CODE: [NACOS-0002], Type: [环境问题], More: [http://console.taobao.net/help/NACOS-0002]
2019-10-11 17:24:54.821 [com.alibaba.nacos.client.Worker.longPullingfixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] [] [NACOS-XXXX] [check-update] get changed dataId exception, msg=java.net.ConnectException: no available server
2019-10-11 17:25:24.849 [com.alibaba.nacos.client.Worker.longPullingfixed-192.168.2.49_8848-192.168.2.48_8848-192.168.2.50_8848-d6775f80-ed7a-409a-8dbc-49b2cddee4d1] ERROR com.alibaba.nacos.client.config.impl.ServerHttpAgent - [] [] [NACOS  SocketTimeoutException] currentServerAddr:192.168.2.48:8848

if the configuration center on the machine is used, these error messages will not be printed:
如果使用本机上的配置中心则不会打印这些error信息：
Using a configuration timeout does not turn off these prints
采用配置超时时间也不能关闭这些打印信息：
Bootstrap.properties is configured as follows:
bootstrap.properties配置如下:
spring.cloud.nacos.config.server-addr=192.168.2.48:8848,192.168.2.49:8848,192.168.2.50:8848
#spring.cloud.nacos.config.server-addr=127.0.0.1:8848
spring.application.name=beings-springboot
server.port=8002
spring.profiles.active=local
spring.cloud.nacos.config.file-extension=properties
#spring.cloud.nacos.config.namespace=d6775f80-ed7a-409a-8dbc-49b2cddee4d1
spring.cloud.nacos.config.timeout=5000
NACOS.CONNECTION.TIMEOUT=5000
### Describe what you expected to happen
该如何配置关闭这些打印或者有其他解决办法
How do you configure to turn off these prints or are there other solutions?

### How to reproduce it (as minimally and precisely as possible)
1. 
2. 
3. 

### Tell us your environment
jdk1.8
nacos1.1.0
springboot 2.0.1.RELEASE

**Comment by nkorange** [comment]
192.168.2.48:8848 这个地址能连上吗？

**Comment by zuixiaoyao001** [comment]
> 192.168.2.48:8848
nacos集群地址可以连接上，项目也可以正常运行，就是打印那些日志，如何关闭，或者直接关闭alibaba.nacos.client.config.impl.xx有关的日志？

**Comment by zuixiaoyao001** [comment]
> 192.168.2.48:8848 这个地址能连上吗？
nacos集群地址可以连接上，项目也可以正常运行，就是打印那些日志，如何关闭，或者直接关闭alibaba.nacos.client.config.impl.xx有关的日志？

**Comment by werfei** [comment]
I had the same problem.

**Comment by wcollin** [comment]
I had the same problem.

**Comment by paderlol** [comment]
这是集群没有启动成功。

**Comment by wcollin** [comment]
> 这是集群没有启动成功。

启动成功的，配置也能获取，页面显示也是正常的
![image](https://user-images.githubusercontent.com/17266901/68639211-ccc81f80-053e-11ea-8c47-bd7704425aed.png)

**Comment by werfei** [comment]
@paderlol 
![图片](https://user-images.githubusercontent.com/18606985/68639233-dc476880-053e-11ea-8464-ff14071bb811.png)

**Comment by zzujustme** [comment]
i have the same problem.cluster is ok.

**Comment by slieer** [comment]
I had the same problem.
=================================================================

2019-12-25 02:21:39.787 ERROR 1 --- [ XNIO-1 task-19] c.a.n.c.config.http.ServerHttpAgent      : [NACOS SocketTimeoutException httpGet] currentServerAddr:http://nacos.ltserver.lan:8848， err : Read timed out
2019-12-25 02:21:39.787 ERROR 1 --- [ XNIO-1 task-19] c.a.n.c.config.http.ServerHttpAgent      : no available server
2019-12-25 02:21:39.788 ERROR 1 --- [ XNIO-1 task-19] c.a.n.client.config.impl.ClientWorker    : [fixed-nacos.ltserver.lan_8848-a137dccd-932c-4da5-b4ee-a8394d633d0b] [sub-server] get server config exception, dataId=skyworth-pay.ya
ml, group=DEFAULT_GROUP, tenant=a137dccd-932c-4da5-b4ee-a8394d633d0b
java.net.ConnectException: no available server
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpGet(ServerHttpAgent.java:115)
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpGet(MetricsHttpAgent.java:48)
        at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:234)
        at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:173)
        at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:122)
        at com.alibaba.cloud.nacos.endpoint.NacosConfigHealthIndicator.doHealthCheck(NacosConfigHealthIndicator.java:58)
        at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82)
        at org.springframework.boot.actuate.health.CompositeHealthIndicator.health(CompositeHealthIndicator.java:95)
        at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:50)
        at org.springframework.boot.actuate.health.HealthEndpointWebExtension.health(HealthEndpointWebExtension.java:53)
        at sun.reflect.GeneratedMethodAccessor232.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

=================================================================
可以肯定的是是整个系统负载都很轻， 配置没有问题，网络是OK的。系统已经运行了一两个月了。
昨天晚上我重启业务模块时突然出现的， 业务模块因此就是启不起来了。接着试了几次，又OK了。今天也重启了几次业务模块， 未出现此问题。

**Comment by KANLON** [comment]
我有同样的问题，还没解决吗？

**Comment by KANLON** [comment]
> 我有同样的问题，还没解决吗？

我后面使用lvs的 虚拟ip，作为集群的地址就没有问题了，估计是自己的采用原始的ip链接不通有关系。

**Comment by handsometong** [comment]
I had the same problem

**Comment by mylonelyplanet** [comment]
I have the same problem

**Comment by KomachiSion** [comment]
no available server

就是客户端找不到可用的服务端，确认客户端所在服务器能与至少一个你配置的nacos服务端服务器网络畅通，并能通过指定端口连接。
