### ISSUE TITLE
How to solve weblogic when deploying springmvc project service can not be registered

### ISSUE THREAD

**Issue by dcliu** [alibaba/nacos#1925]
weblogic 12c  nacos-server1.0   nacos-client1.1.3  spring project

Did not meet stated content length of OutputStream:  you wrote 0 bytes and I was expecting  you to write exactly 223 bytes!!!

[2019-10-11 22:12:35.743 WARN ] Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.amarsoft.rax.nacos.event.NacosEventListenerConfiguration#0': Invocation of init method failed; nested exception is java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([30.79.110.22:8848, 30.79.110.23:8848]) tried: failed to req API:30.79.110.23:8848/nacos/v1/ns/instance. code:500 msg: java.net.ProtocolException: Did not meet stated content length of OutputStream: you wrote 0 bytes and I was expecting you to write exactly 227 bytes!!! @org.springframework.web.context.support.XmlWebApplicationContext 
[2019-10-11 22:12:35.778 ERROR] Context initialization failed @org.springframework.web.context.ContextLoader 
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.amarsoft.rax.nacos.event.NacosEventListenerConfiguration#0': Invocation of init method failed; nested exception is java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([30.79.110.22:8848, 30.79.110.23:8848]) tried: failed to req API:30.79.110.23:8848/nacos/v1/ns/instance. code:500 msg: java.net.ProtocolException: Did not meet stated content length of OutputStream: you wrote 0 bytes and I was expecting you to write exactly 227 bytes!!!
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:778)
at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:839)
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:538)
at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:444)
at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:326)
at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
at weblogic.servlet.internal.EventsManager$FireContextListenerAction.run(EventsManager.java:705)
at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:328)
at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
at weblogic.servlet.provider.WlsSubjectHandle.run(WlsSubjectHandle.java:71)
at weblogic.servlet.internal.EventsManager.executeContextListener(EventsManager.java:251)
at weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(EventsManager.java:204)
at weblogic.servlet.internal.EventsManager.notifyContextCreatedEvent(EventsManager.java:189)
at weblogic.servlet.internal.WebAppServletContext.preloadResources(WebAppServletContext.java:1921)
at weblogic.servlet.internal.WebAppServletContext.start(WebAppServletContext.java:3106)
at weblogic.servlet.internal.WebAppModule.startContexts(WebAppModule.java:1843)
at weblogic.servlet.internal.WebAppModule.start(WebAppModule.java:884)
at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:360)
at weblogic.application.internal.ExtensibleModuleWrapper$StartStateChange.next(ExtensibleModuleWrapper.java:356)
at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:138)
at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
at weblogic.application.internal.flow.ModuleStateDriver.start(ModuleStateDriver.java:78)
at weblogic.application.internal.flow.StartModulesFlow.activate(StartModulesFlow.java:52)
at weblogic.application.internal.BaseDeployment$2.next(BaseDeployment.java:752)
at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
at weblogic.application.internal.BaseDeployment.activate(BaseDeployment.java:262)
at weblogic.application.internal.SingleModuleDeployment.activate(SingleModuleDeployment.java:52)
at weblogic.application.internal.DeploymentStateChecker.activate(DeploymentStateChecker.java:165)
at weblogic.deploy.internal.targetserver.AppContainerInvoker.activate(AppContainerInvoker.java:90)
at weblogic.deploy.internal.targetserver.BasicDeployment.activate(BasicDeployment.java:274)
at weblogic.deploy.internal.targetserver.BasicDeployment.activateFromServerLifecycle(BasicDeployment.java:507)
at weblogic.management.deploy.internal.DeploymentAdapter$1.doActivate(DeploymentAdapter.java:53)
at weblogic.management.deploy.internal.DeploymentAdapter.activate(DeploymentAdapter.java:202)
at weblogic.management.deploy.internal.AppTransition$2.transitionApp(AppTransition.java:52)
at weblogic.management.deploy.internal.ConfiguredDeployments$2.doItem(ConfiguredDeployments.java:741)
at weblogic.management.deploy.internal.parallel.BucketInvoker$2.run(BucketInvoker.java:95)
at weblogic.work.ContextWrap.run(ContextWrap.java:46)
at weblogic.work.SelfTuningWorkManagerImpl$WorkAdapterImpl.run(SelfTuningWorkManagerImpl.java:678)
at weblogic.invocation.ComponentInvocationContextManager._runAs(ComponentInvocationContextManager.java:352)
at weblogic.invocation.ComponentInvocationContextManager.runAs(ComponentInvocationContextManager.java:337)
at weblogic.work.LivePartitionUtility.doRunWorkUnderContext(LivePartitionUtility.java:57)
at weblogic.work.PartitionUtility.runWorkUnderContext(PartitionUtility.java:41)
at weblogic.work.SelfTuningWorkManagerImpl.runWorkUnderContext(SelfTuningWorkManagerImpl.java:652)
at weblogic.work.ExecuteThread.execute(ExecuteThread.java:420)
at weblogic.work.ExecuteThread.run(ExecuteThread.java:360)
Caused by: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([30.79.110.22:8848, 30.79.110.23:8848]) tried:
 failed to req API:30.79.110.23:8848/nacos/v1/ns/instance. code:500 msg: java.net.
ProtocolException: Did not meet stated content length of OutputStream: you wrote 0 bytes and I was expecting you to write exactly 227 bytes!!!
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467)
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:191)
at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:207)
at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:181)
at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:169)
at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:159)
at com.amarsoft.rax.nacos.event.NacosEventListenerConfiguration.init(NacosEventListenerConfiguration.java:62)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:354)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:305)
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:133)
... 58 common frames omitted
<2019-10-11 下午10时12分35,779秒 CST> <Warning> <HTTP> <BEA-101162> <User defined listener org.springframework.web.context.ContextLoaderListener failed: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.amarsoft.rax.nacos.event.NacosEventListenerConfiguration#0': Invocation of init method failed; nested exception is java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([30.79.110.22:8848, 30.79.110.23:8848]) tried: failed to req API:30.79.110.23:8848/nacos/v1/ns/instance. code:500 msg: java.net.ProtocolException: Did not meet stated content length of OutputStream: you wrote 0 bytes and I was expecting you to write exactly 227 bytes!!!.
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'com.amarsoft.rax.nacos.event.NacosEventListenerConfiguration#0': Invocation of init method failed; nested exception is java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([30.79.110.22:8848, 30.79.110.23:8848]) tried: failed to req API:30.79.110.23:8848/nacos/v1/ns/instance. code:500 msg: java.net.ProtocolException: Did not meet stated content length of OutputStream: you wrote 0 bytes and I was expecting you to write exactly 227 bytes!!!
at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:408)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1574)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:545)
at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:482)
Truncated. see log file for complete stacktrace
Caused By: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([30.79.110.22:8848, 30.79.110.23:8848]) tried: failed to req API:30.79.110.23:8848/nacos/v1/ns/instance. code:500 msg: java.net.ProtocolException: Did not meet stated content length of OutputStream: you wrote 0 bytes and I was expecting you to write exactly 227 bytes!!!
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467)
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:191)
at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:207)
at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:181)
Truncated. see log file for complete stacktrace
> 
<2019-10-11 下午10时12分35,794秒 CST> <Error> <HTTP> <BEA-101267> <Failed while destroying filter: WebSocket filter.
java.lang.NullPointerException
at weblogic.websocket.tyrus.TyrusServletFilter.destroy(TyrusServletFilter.java:305)
at weblogic.servlet.internal.FilterManager$FilterDestroyAction.run(FilterManager.java:416)
at weblogic.security.acl.internal.AuthenticatedSubject.doAs(AuthenticatedSubject.java:328)
at weblogic.security.service.SecurityManager.runAsForUserCode(SecurityManager.java:197)
at weblogic.servlet.provider.WlsSecurityProvider.runAsForUserCode(WlsSecurityProvider.java:203)
Truncated. see log file for complete stacktrace
> 
<2019-10-11 下午10时12分35,857秒 CST> <Error> <Deployer> <BEA-149231> <Unable to set the activation state to true for the application "dczl-core-ea".
weblogic.application.ModuleException: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([30.79.110.22:8848, 30.79.110.23:8848]) tried: failed to req API:30.79.110.23:8848/nacos/v1/ns/instance. code:500 msg: java.net.ProtocolException: Did not meet stated content length of OutputStream: you wrote 0 bytes and I was expecting you to write exactly 227 bytes!!!
at weblogic.application.internal.ExtensibleModuleWrapper.start(ExtensibleModuleWrapper.java:140)
at weblogic.application.internal.flow.ModuleListenerInvoker.start(ModuleListenerInvoker.java:124)
at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:233)
at weblogic.application.internal.flow.ModuleStateDriver$3.next(ModuleStateDriver.java:228)
at weblogic.application.utils.StateMachineDriver.nextState(StateMachineDriver.java:45)
Truncated. see log file for complete stacktrace
Caused By: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([30.79.110.22:8848, 30.79.110.23:8848]) tried: failed to req API:30.79.110.23:8848/nacos/v1/ns/instance. code:500 msg: java.net.ProtocolException: Did not meet stated content length of OutputStream: you wrote 0 bytes and I was expecting you to write exactly 227 bytes!!!
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467)
at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:191)
at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:207)
at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:181)
Truncated. see log file for complete stacktrace
> 
<2019-10-11 下午10时12分35,921秒 CST> <Notice> <Cluster> <BEA-000138> <Listening for announcements from cluster dczl-cbs-ea-stgSFCluster44124 on 239.11.41.24:37002.> 
<2019-10-11 下午10时12分35,925秒 CST> <Notice> <Cluster> <BEA-000133> <Waiting to synchronize with other running members of dczl-cbs-ea-stgSFCluster44124.> 
<2019-10-11 下午10时12分36,303秒 CST> <Notice> <Log Management> <BEA-170027> <The server has successfully established a connection with the Domain level Diagnostic Service.> 
<2019-10-11 下午10时12分42,850秒 CST> <Notice> <Cluster> <BEA-000142> <Trying to download cluster JNDI tree from server dczl-cbs-ea-stgSF109906.> 
<2019-10-11 下午10时12分42,970秒 CST> <Notice> <Cluster> <BEA-000164> <Synchronized cluster JNDI tree from server dczl-cbs-ea-stgSF109906.> 
<2019-10-11 下午10时12分42,977秒 CST> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to ADMIN.> 
<2019-10-11 下午10时12分43,088秒 CST> <Notice> <WebLogicServer> <BEA-000365> <Server state changed to RESUMING.> 
<2019-10-11 下午10时12分43,185秒 CST> <Notice> <Cluster> <BEA-000162> <Starting "async" replication service with remote cluster address "null"> 
<2019-10-11 下午10时12分43,229秒 CST> <Notice> <WebLogicServer> <BEA-000330> <Started the WebLogic Server Managed Server "dczl-cbs-ea-stgSF109905" for domain "StgWLDom73405" running in production mode.> 
<2019-10-11 下午10时12分43,229秒 CST> <Notice> <Server> <BEA-002613> <Channel "Default[1]" is now listening on 127.0.0.1:37003 for protocols iiop, t3, ldap, snmp, http.> 
<2019-10-11 下午10时12分43,230秒 CST> <Notice> <Server> <BEA-002613> <Channel "Default" is now listening on 30.79.114.205:37003 for protocols iiop, t3, ldap, snmp, http.> 
<2019-10-11 下午10时12分43,230秒 CST> <Notice> <Server> <BEA-002613> <Channel "Default[1]" is now listening on 127.0.0.1:37003 for protocols iiop, t3, ldap, snmp, http.> 
<2019-10-11 下午10时12分43,230秒 CST> <Notice> <Server> <BEA-002613> <Channel "Default" is now listening on 30.79.114.205:37003 for protocols iiop, t3, ldap, snmp, http.> 
<2019-10-11 下午10时12分43,315秒 CST> <Notice> <Cluster> <BEA-000102> <Joining cluster dczl-cbs-ea-stgSFCluster44124 on 239.11.41.24:37002>

**Comment by antz-H** [comment]
https://thecattlecrew.net/2016/01/14/1001_wls/
 you can refer this issue

**Comment by nkorange** [comment]
It seems a weblogic bug, you can upgrade you weblogic and try again.
