### ISSUE TITLE
check="false" is invalid

### ISSUE THREAD

**Issue by duanzonglong** [alibaba/nacos#1935]
Error:
17:38:47,370 ERROR naming:455 - request 172.172.172.96:8848 failed.
ErrCode:500, ErrMsg:failed to req API:172.172.172.96:8848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@providers:com.behosoft.inter.dubbo.IInventoryAndSaleElsService:1.0:
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:425)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:452)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:387)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:298)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:279)
	at com.alibaba.nacos.client.naming.core.HostReactor.getServiceInfo(HostReactor.java:238)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:290)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:282)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:271)
	at com.alibaba.nacos.client.naming.NacosNamingService.getAllInstances(NacosNamingService.java:251)
	at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doSubscribe$3(NacosRegistry.java:174)
	at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:466)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:172)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:168)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:295)

env:
compile ('org.apache.dubbo:dubbo:2.7.3')
compile ('org.apache.dubbo:dubbo-registry-nacos:2.7.3')
compile ('com.alibaba.nacos:nacos-client:1.1.3')

**Comment by nkorange** [comment]
This error means your subscribing service is not found. Check the console of Nacos to see if the service ```providers:com.behosoft.inter.dubbo.IInventoryAndSaleElsService:1.0:``` is registered.
