### ISSUE TITLE
http://null/nacos/serverlist'. Server returned: 500

### ISSUE THREAD

**Issue by jonahzheng** [alibaba/nacos#1948]
## Issue Description

Type: *bug report* or *feature request*

`java.io.IOException: Error while requesting: http://null/nacos/serverlist'. Server returned: 500
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServerListFromEndpoint(NamingProxy.java:102)
	at com.alibaba.nacos.client.naming.net.NamingProxy.refreshSrvIfNeed(NamingProxy.java:135)
	at com.alibaba.nacos.client.naming.net.NamingProxy.access$000(NamingProxy.java:39)
	at com.alibaba.nacos.client.naming.net.NamingProxy$2.run(NamingProxy.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)`

### Describe what happened (or what feature you want)
看到代码，是这个函数，endpoint怎么变成null了，我在application.properties中配置spring.cloud.nacos.discovery.server-addr，endpoint是不是这个值。
线上的服务已经正常运行一段时候了
    public List<String> getServerListFromEndpoint() {

        try {
            String urlString = "http://" + endpoint + "/nacos/serverlist";
            List<String> headers = builderHeaders();

            HttpClient.HttpResult result = HttpClient.httpGet(urlString, headers, null, UtilAndComs.ENCODING);
            if (HttpURLConnection.HTTP_OK != result.code) {
                throw new IOException("Error while requesting: " + urlString + "'. Server returned: "
                    + result.code);
            }

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by nkorange** [comment]
Please report this issue to https://github.com/alibaba/spring-cloud-alibaba.
