### ISSUE TITLE
 Failed to rename context [rent] as [nacos] java.lang.IllegalStateException: Context has been already given a name

### ISSUE THREAD

**Issue by 3EDCKenneth** [alibaba/nacos#1959]
启动nacos后，出现错误日志：

21:50:39,908 |-ERROR in ch.qos.logback.classic.joran.action.ContextNameAction - Failed to rename context [rent] as [nacos] java.lang.IllegalStateException: Context has been already given a name
	at java.lang.IllegalStateException: Context has been already given a name

21:50:49,667 |-INFO in ReconfigureOnChangeTask(born:1571752239667) - Empty watch file list. Disabling 
21:50:59,664 |-INFO in ReconfigureOnChangeTask(born:1571752239667) - Empty watch file list. Disabling 
21:51:09,663 |-INFO in ReconfigureOnChangeTask(born:1571752239667) - Empty watch file list. Disabling 
21:51:09,903 |-INFO in ReconfigureOnChangeTask(born:1571752239907) - Empty watch file list. Disabling 
21:51:19,664 |-INFO in ReconfigureOnChangeTask(born:1571752239667) - Empty watch file list. Disabling 
21:51:29,664 |-INFO in ReconfigureOnChangeTask(born:1571752239667) - Empty watch file list. Disabling 
21:51:39,664 |-INFO in ReconfigureOnChangeTask(born:1571752239667) - Empty watch file list. Disabling 
21:51:39,904 |-INFO in ReconfigureOnChangeTask(born:1571752239907) - Empty watch file list. Disabling 
21:51:49,664 |-INFO in ReconfigureOnChangeTask(born:1571752239667) - Empty watch file list. Disabling 
21:51:59,659 |-INFO in ReconfigureOnChangeTask(born:1571752239667) - Empty watch file list. Disabling 
21:52:09,659 |-INFO in ReconfigureOnChangeTask(born:1571752239667) - Empty watch file list. Disabling

**Comment by 3EDCKenneth** [comment]
22:04:52,040 |-ERROR in ch.qos.logback.classic.joran.action.ContextNameAction - Failed to rename context [rent] as [nacos] java.lang.IllegalStateException: Context has been already given a name
	at java.lang.IllegalStateException: Context has been already given a name
	at 	at ch.qos.logback.core.ContextBase.setName(ContextBase.java:194)
	at 	at ch.qos.logback.classic.LoggerContext.setName(LoggerContext.java:107)
	at 	at ch.qos.logback.classic.joran.action.ContextNameAction.body(ContextNameAction.java:31)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBodyAction(Interpreter.java:289)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.characters(Interpreter.java:172)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:57)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at com.alibaba.nacos.client.logging.logback.LogbackNacosLogging.loadConfiguration(LogbackNacosLogging.java:44)
	at 	at com.alibaba.nacos.client.utils.LogUtils.<clinit>(LogUtils.java:47)
	at 	at com.alibaba.nacos.client.config.NacosConfigService.<clinit>(NacosConfigService.java:57)
	at 	at java.lang.Class.forName0(Native Method)
	at 	at java.lang.Class.forName(Class.java:264)
	at 	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:40)
	at 	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:43)
	at 	at com.alibaba.nacos.spring.factory.CacheableEventPublishingNacosServiceFactory.doCreateConfigService(CacheableEventPublishingNacosServiceFactory.java:79)
	at 	at com.alibaba.nacos.spring.factory.CacheableEventPublishingNacosServiceFactory.createConfigService(CacheableEventPublishingNacosServiceFactory.java:71)
	at 	at com.alibaba.boot.nacos.config.autoconfigure.NacosConfigApplicationContextInitializer.lambda$initialize$0(NacosConfigApplicationContextInitializer.java:69)
	at 	at com.alibaba.boot.nacos.config.util.NacosConfigUtils.reqNacosConfig(NacosConfigUtils.java:114)
	at 	at com.alibaba.boot.nacos.config.util.NacosConfigUtils.reqGlobalNacosConfig(NacosConfigUtils.java:95)
	at 	at com.alibaba.boot.nacos.config.util.NacosConfigUtils.loadConfig(NacosConfigUtils.java:67)
	at 	at com.alibaba.boot.nacos.config.autoconfigure.NacosConfigApplicationContextInitializer.initialize(NacosConfigApplicationContextInitializer.java:81)
	at 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:628)
	at 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:364)
	at 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at 	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:137)
	at 	at com.cykj.brain.sys.user.Application.main(Application.java:38)

**Comment by 3EDCKenneth** [comment]
spingboot2.0.3   +nacos1.1.3

**Comment by chuntaojun** [comment]
看着错误像是日志框架的名称冲突了，你看下你的logback和nacos自带的logback设置，对比看看

**Comment by songhanlin** [comment]
这个是因为logback命名之后不允许二次修改contextName的名字, 我也遇到了这个问题, 我自己项目的contextName是TestA, 运行的好好的, 就遇到nacos里面的contextName [nacos]

**Comment by chuntaojun** [comment]
关于 log contextname的问题我们会进行讨论的

**Comment by GaoJiaxin1995** [comment]
这个问题到目前为止处理好了吗？我今天也出现了这样的问题。

**Comment by duerlatter** [comment]
> 这个问题到目前为止处理好了吗？我今天也出现了这样的问题。

可以先设置禁用来解决这个问题

`nacos.logging.default.config.enabled=false`

**Comment by trump-virus** [comment]
@chuntaojun nacos1.2.1 也这样报错


Caused by: java.lang.IllegalStateException: Logback configuration error detected:
ERROR in ch.qos.logback.classic.joran.action.ContextNameAction - Failed to rename context [nacos] as [yyc_cms] java.lang.IllegalStateException: Context has been already given a name

**Comment by wangjia2016** [comment]
这个问题应该还是没有修复 
SpringCloudAlibaba2.2.3.RELEASE的版本

**Comment by shihua-guo** [comment]
可以试试这样子引入应用名称。
`
    <property resource="bootstrap.yml" />
    <property resource="application.yml" />
    <property  name="APP_NAME" value="${spring.application.name:xxx}" />`

**Comment by shihua-guo** [comment]
上面那个设置我并没有设置成功，但是我通过更改配置文件名解决了这个问题。把logback.xml更改成：logback-spring.xml

**Comment by xiangyunup** [comment]
0.2.10 还是遇到了这个问题

**Comment by WilliamShoww** [comment]
> > 这个问题到目前为止处理好了吗？我今天也出现了这样的问题。
> 
> 可以先设置禁用来解决这个问题
> 
> `nacos.logging.default.config.enabled=false`
> 
> `System.setProperty("nacos.logging.default.config.enabled", "false");`

我测试代码加这句也没有用啊

**Comment by duzengjie** [comment]
> > > 这个问题到目前为止处理好了吗？我今天也出现了这样的问题。
> > 
> > 
> > 可以先设置禁用来解决这个问题
> > `nacos.logging.default.config.enabled=false`
> > `System.setProperty("nacos.logging.default.config.enabled", "false");`
> 
> 我测试代码加这句也没有用啊

我也是

**Comment by sunyanqing01** [comment]
> 上面那个设置我并没有设置成功，但是我通过更改配置文件名解决了这个问题。把logback.xml更改成：logback-spring.xml

改为logback-spring.xml后直接就不加载了

**Comment by sunyanqing01** [comment]
> > 这个问题到目前为止处理好了吗？我今天也出现了这样的问题。
> 
> 可以先设置禁用来解决这个问题
> 
> `nacos.logging.default.config.enabled=false`
> 
> `System.setProperty("nacos.logging.default.config.enabled", "false");`

没有起作用

**Comment by SarielAngel** [comment]
> > > 这个问题到目前为止处理好了吗？我今天也出现了这样的问题。
> > 
> > 
> > 可以先设置禁用来解决这个问题
> > `nacos.logging.default.config.enabled=false`
> > `System.setProperty("nacos.logging.default.config.enabled", "false");`
> 
> 没有起作用
System.setProperty("nacos.logging.default.config.enabled", "false");这句放启动方法前是有用的。上面的配置确实没用
