### ISSUE TITLE
用nacos做配置中心和注册中心，在单元测试时，进行数据库操作，报错

### ISSUE THREAD

**Issue by xlb** [alibaba/nacos#1968]
数据源用的默认的 HikariPool  配置文件如下

`spring:
  datasource:
    url: jdbc:mysql://mysql:3306/cloud?useUnicode=true&characterEncoding=UTF8&useSSL=false&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    #password: abc123!
    password: 123456
    max-idle: 10
    min-idle: 5
    test-on-borrow: false
    time-between-eviction-runs-millis: 18800
    test-while-idle: true
    validation-query: SELECT 1`
单元测试代码如下
`	@Test
	@Transactional
	public void insertOneByOne() throws InterruptedException {
		IPage<PmcObjLog> page = new Page<PmcObjLog>();
		page.setSize(500);
		List<PmcObjLog> list = pmcObjLogService.page(page).getRecords();
		for (PmcObjLog pmcObjLog : list) {
			pmcObjLog.setId(snowflakeIdWorker.nextIdString());
		}
		for (int i = 0; i < list.size(); i++) {
			pmcObjLogService.save(list.get(i));
		}
	}`

` HikariPool-1 - Starting...
2019-10-25 14:55:12.393 [main] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Start completed.
2019-10-25 14:55:12.407 [main] INFO  o.s.test.context.transaction.TransactionContext - Began transaction (1) for test context [DefaultTestContext@81da6a3 testClass = ObjLogTest, testInstance = com.soptop.eam.device.ObjLogTest@5816fd13, testMethod = insertOneByOne@ObjLogTest, testException = [null], mergedContextConfiguration = [WebMergedContextConfiguration@1fe275d8 testClass = ObjLogTest, locations = '{}', classes = '{class com.soptop.eam.device.EamDeviceServiceApplication}', contextInitializerClasses = '[]', activeProfiles = '{}', propertySourceLocations = '{}', propertySourceProperties = '{org.springframework.boot.test.context.SpringBootTestContextBootstrapper=true}', contextCustomizers = set[org.springframework.boot.test.context.filter.ExcludeFilterContextCustomizer@75c56eb9, org.springframework.boot.test.json.DuplicateJsonObjectContextCustomizerFactory$DuplicateJsonObjectContextCustomizer@6531a794, org.springframework.boot.test.mock.mockito.MockitoContextCustomizer@0, org.springframework.boot.test.web.client.TestRestTemplateContextCustomizer@42e25b0b, org.springframework.boot.test.autoconfigure.properties.PropertyMappingContextCustomizer@0, org.springframework.boot.test.autoconfigure.web.servlet.WebDriverContextCustomizerFactory$Customizer@2e32ccc5], resourceBasePath = 'src/main/webapp', contextLoader = 'org.springframework.boot.test.context.SpringBootContextLoader', parent = [null]], attributes = map['org.springframework.test.context.web.ServletTestExecutionListener.activateListener' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.populatedRequestContextHolder' -> true, 'org.springframework.test.context.web.ServletTestExecutionListener.resetRequestContextHolder' -> true]]; transaction manager [org.springframework.jdbc.datasource.DataSourceTransactionManager@52c0c594]; rollback [true]
2019-10-25 14:55:12.746 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  o.s.c.a.nacos.client.NacosPropertySourceBuilder - Loading nacos data, dataId: 'application.yml', group: 'DEFAULT_GROUP'
2019-10-25 14:55:12.764 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  o.s.c.a.nacos.client.NacosPropertySourceBuilder - Loading nacos data, dataId: 'eam-device-service-dev.yml', group: 'DEFAULT_GROUP'
2019-10-25 14:55:12.765 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  o.s.c.b.c.PropertySourceBootstrapConfiguration - Located property source: CompositePropertySource {name='NACOS', propertySources=[NacosPropertySource {name='eam-device-service-dev.yml'}, NacosPropertySource {name='eam-device-service.yml'}, NacosPropertySource {name='application.yml'}]}
2019-10-25 14:55:12.792 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  org.springframework.boot.SpringApplication - The following profiles are active: dev
2019-10-25 14:55:12.797 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  o.s.c.a.AnnotationConfigApplicationContext - Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@216967a2: startup date [Fri Oct 25 14:55:12 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@4137ae57
2019-10-25 14:55:12.810 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  o.s.b.f.a.AutowiredAnnotationBeanPostProcessor - JSR-330 'javax.inject.Inject' annotation found and supported for autowiring
2019-10-25 14:55:12.868 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  org.springframework.boot.SpringApplication - Started application in 2.564 seconds (JVM running for 33.374)
2019-10-25 14:55:12.868 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@216967a2: startup date [Fri Oct 25 14:55:12 CST 2019]; parent: org.springframework.context.annotation.AnnotationConfigApplicationContext@4137ae57
2019-10-25 14:55:12.869 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  o.s.c.a.AnnotationConfigApplicationContext - Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@4137ae57: startup date [Fri Oct 25 14:55:11 CST 2019]; root of context hierarchy
2019-10-25 14:55:13.160 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown initiated...
2019-10-25 14:55:13.172 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  com.zaxxer.hikari.HikariDataSource - HikariPool-1 - Shutdown completed.
2019-10-25 14:55:13.173 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  o.s.cloud.endpoint.event.RefreshEventListener - Refresh keys changed: []
2019-10-25 14:55:13.173 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  com.alibaba.nacos.client.config.impl.CacheData - [fixed-eam-server_8848] [notify-ok] dataId=eam-device-service-dev.yml, group=DEFAULT_GROUP, md5=01abfc750a0c942167651c40d088531d, listener=org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1@6cc487e1 
2019-10-25 14:55:13.174 [com.alibaba.nacos.client.Worker.longPollingfixed-eam-server_8848] INFO  com.alibaba.nacos.client.config.impl.CacheData - [fixed-eam-server_8848] [notify-listener] time cost=2876ms in ClientWorker, dataId=eam-device-service-dev.yml, group=DEFAULT_GROUP, md5=01abfc750a0c942167651c40d088531d, listener=org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1@6cc487e1 
2019-10-25 14:55:13.214 [main] WARN  com.zaxxer.hikari.pool.ProxyConnection - HikariPool-1 - Connection com.mysql.jdbc.JDBC4Connection@258d7d06 marked as broken because of SQLSTATE(08003), ErrorCode(0)
com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: No operations allowed after connection closed.
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)`

估计原因是springboot启动完成后立马进行了test单元测试，且我这边启动了事务，但是循环过程中nacos应该是重置了上下文，导致后续找不到之前的连接源，报错。
只要我启用事务，一般进行到70左右就会异常，如果我取消事务，那么有一定可能能够完成循环，一定可能不行，取决去当时代码执行的进程。

**Comment by xlb** [comment]
只要我手动不执行	applicationContext.publishEvent(
						new RefreshEvent(this, null, "Refresh Nacos config"));这个方法，

让`	@EventListener
	public void handle(RefreshEvent event) {
		if (this.ready.get()) { // don't handle events before app is ready
			log.debug("Event received " + event.getEventDesc());
			Set<String> keys = this.refresh.refresh();
			log.info("Refresh keys changed: " + keys);
		}
	}`
不执行就不会有问题

**Comment by xlb** [comment]
原因貌似是因为我引入了springcloudstream，我这里用的是spring-cloud-starter-bus-amqp

**Comment by xlb** [comment]
这边是测试用例 https://github.com/xulb-study/nacos_example/tree/master/nacos-spring-cloud-example/nacos-spring-cloud-config-multi-data-ids-example  使用UserTest即可，用之前先配置nacos及初始化test.sql

**Comment by xlb** [comment]
英文版 https://github.com/alibaba/nacos/issues/1973

**Comment by chuntaojun** [comment]
This should be a spring - cloud - alibaba project integration problems, I will move the issue to the spring - cloud - alibaba project
