### ISSUE TITLE
com.alibaba.nacos.client.config.utils.IOUtils.toString NPE

### ISSUE THREAD

**Issue by steveguoshao** [alibaba/nacos#2020]
org.apache.dubbo.rpc.RpcException: Failed to put org.apache.dubbo.metadata.identifier.MetadataIdentifier@e4a8091 to nacos {"side":"consumer","release":"2.7.3","methods":"xxxxx,"lazy":"false","logger":"slf4j","dubbo":"2.0.2","check":"false","interface":"xxxx","version":"1.0.0","qos.enable":"false","generic":"false","timeout":"3000","revision":"1.0.0","retries":"0","application":"xxx,"sticky":"false","validation":"true"}, cause: null
        at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.storeMetadata(NacosMetadataReport.java:132) ~[dubbo-2.7.3.jar!/:2.7.3]
        at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.doStoreConsumerMetadata(NacosMetadataReport.java:121) ~[dubbo-2.7.3.jar!/:2.7.3]
        at org.apache.dubbo.metadata.support.AbstractMetadataReport.storeConsumerMetadataTask(AbstractMetadataReport.java:274) ~[dubbo-2.7.3.jar!/:2.7.3]
        at org.apache.dubbo.metadata.support.AbstractMetadataReport.lambda$storeConsumerMetadata$1(AbstractMetadataReport.java:260) ~[dubbo-2.7.3.jar!/:2.7.3]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[?:1.8.0_221]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[?:1.8.0_221]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_221]
Caused by: java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78) ~[?:1.8.0_221]
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97) ~[?:1.8.0_221]
        at com.alibaba.nacos.client.config.utils.IOUtils.toString(IOUtils.java:33) ~[nacos-client-1.1.1.jar!/:?]
        at com.alibaba.nacos.client.config.impl.HttpSimpleClient.httpPost(HttpSimpleClient.java:129) ~[nacos-client-1.1.1.jar!/:?]
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:135) ~[nacos-client-1.1.1.jar!/:?]
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.1.1.jar!/:?]
        at com.alibaba.nacos.client.config.NacosConfigService.publishConfigInner(NacosConfigService.java:283) ~[nacos-client-1.1.1.jar!/:?]
        at com.alibaba.nacos.client.config.NacosConfigService.publishConfig(NacosConfigService.java:139) ~[nacos-client-1.1.1.jar!/:?]
        at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.storeMetadata(NacosMetadataReport.java:126) ~[dubbo-2.7.3.jar!/:2.7.3]
        ... 6 more

**Comment by nkorange** [comment]
这个问题一般是配置的Nacos集群地址错误，导致返回的响应体为空导致。

**Comment by steveguoshao** [comment]
> 这个问题一般是配置的Nacos集群地址错误，导致返回的响应体为空导致。

Nacos集群地址是正常的，是这样的，先配置dubbo的注册中心为nacos，然后应用都启动正常能访问，然后开启dubbo的元数据上报，重启应用，就会出现大量上面的那个异常
