### ISSUE TITLE
code:503 msg: server is STARTING now, please try again later!

### ISSUE THREAD

**Issue by sgzwiz** [alibaba/nacos#2041]
在阿里云容器服务(ACS)里安装了nacos-pvc-nfs，成功启动了nacos-0、nacos-1、nacos-2，但是其他服务启动时，出现以下错误：
Nacos-pvc-nfs is installed in Alibaba cloud container service (ACS), and nacos-0, nacos-1 and nacos-2 are successfully started. However, when other services are started, the following errors occur:

[api-gateway:172.20.1.171:35700] 2019-11-10 14:36:03.326 ERROR 1 [main] org.springframework.cloud.alibaba.nacos.discovery.NacosDiscoveryClient get service name from nacos server fail,

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([nacos-0.nacos-headless:8848]) tried: failed to req API:nacos-0.nacos-headless:8848/nacos/v1/ns/service/list. code:503 msg: server is STARTING now, please try again later!
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:433) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:379) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:361) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:337) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:442) ~[nacos-client-1.1.4.jar!/:na]
	at org.springframework.cloud.alibaba.nacos.discovery.NacosDiscoveryClient.getServices(NacosDiscoveryClient.java:99) ~[spring-cloud-alibaba-nacos-discovery-0.9.0.RELEASE.jar!/:0.9.0.RELEASE]

请教解决方法
Ask for solutions

**Comment by sgzwiz** [comment]
直接设置为POD IP，依然出现错误。
Set to pod IP directly, still error.

[api-gateway:172.20.1.174:35700] 2019-11-10 15:41:58.996 ERROR 1 [main] org.springframework.cloud.alibaba.nacos.discovery.NacosDiscoveryClient get service name from nacos server fail,
 java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([172.20.1.155:8848]) tried: failed to req API:172.20.1.155:8848/nacos/v1/ns/service/list. code:503 msg: server is STARTING now, please try again later!
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:433) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:379) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:361) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:337) ~[nacos-client-1.1.4.jar!/:na]

**Comment by sgzwiz** [comment]
cd nacos-k8s
chmod +x quick-startup.sh
./quick-startup.sh
采用以上方法，依然出现相同错误。
Using the above method, the same error still occurs.

[api-gateway:172.23.0.13:35700] 2019-11-10 16:14:25.200 ERROR 1 [main] org.springframework.cloud.alibaba.nacos.discovery.NacosDiscoveryClient get service name from nacos server fail,
 java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([nacos-0.headless:8848]) tried: failed to req API:nacos-0.headless:8848/nacos/v1/ns/service/list. code:500 msg: java.net.UnknownHostException: nacos-0.headless
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:433) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:379) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:361) ~[nacos-client-1.1.4.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:337) ~[nacos-client-1.1.4.jar!/:na]

**Comment by sgzwiz** [comment]
应该是nacos-pvc-nfs配置不对，quick-startup.sh是可以的。
