### ISSUE TITLE
整合dubbo采用nacos作为注册中心报错 [NACOS SocketTimeoutException httpPost] currentServerAddr: http://192.168.3.58:8848， err : Read timed out

### ISSUE THREAD

**Issue by zuixiaoyao001** [alibaba/nacos#2056]
不影响运行程序，但是总是打印如下日志和上个issues如出一辙，能尽快帮着解决一下吗？大佬们，谢谢！
2019-11-13 13:48:59.604 [com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.3.57_8848-192.168.3.58_8848-192.168.3.59_8848] ERROR com.alibaba.nacos.client.config.http.ServerHttpAgent - [NACOS SocketTimeoutException httpPost] currentServerAddr: http://192.168.3.58:8848， err : Read timed out
2019-11-13 13:48:59.604 [com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.3.57_8848-192.168.3.58_8848-192.168.3.59_8848] ERROR com.alibaba.nacos.client.config.http.ServerHttpAgent - no available server, currentServerAddr : http://192.168.3.59:8848
2019-11-13 13:48:59.604 [com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.3.57_8848-192.168.3.58_8848-192.168.3.59_8848] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-192.168.3.57_8848-192.168.3.58_8848-192.168.3.59_8848] [check-update] get changed dataId exception
java.net.ConnectException: no available server, currentServerAddr : http://192.168.3.59:8848
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:170)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:377)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:352)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:512)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-11-13 13:48:59.604 [com.alibaba.nacos.client.Worker.longPolling.fixed-192.168.3.57_8848-192.168.3.58_8848-192.168.3.59_8848] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - longPolling error : 
java.net.ConnectException: no available server, currentServerAddr : http://192.168.3.59:8848
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:170)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:377)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:352)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:512)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by chuntaojun** [comment]
这个问题已经提了pr了，预计下个版本解决
