### ISSUE TITLE
集成zipkin后 链路追踪没问题 但是使用zipkin的服务 nacos日志一直报错

### ISSUE THREAD

**Issue by wangyingwei001** [alibaba/nacos#2070]
2019-11-18 14:43:36.016 ERROR [com.alibaba.nacos.client.naming.updater] [com.alibaba.nacos.client.logger.slf4j.Slf4jLogger.java:149] - [] [] [NA] failed to update serviceName: 127.0.0.1
java.lang.NullPointerException: null
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at com.alibaba.nacos.client.naming.core.HostReactor.processServiceJSON(HostReactor.java:94)
at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:342)
at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
2019-11-18 14:43:37.058 ERROR [com.alibaba.nacos.client.naming.updater] [com.alibaba.nacos.client.logger.slf4j.Slf4jLogger.java:149] - [] [] [NA] failed to update serviceName: 127.0.0.1
java.lang.NullPointerException: null
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
at com.alibaba.nacos.client.naming.core.HostReactor.processServiceJSON(HostReactor.java:94)
at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:342)
at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by nkorange** [comment]
请参考：https://github.com/alibaba/nacos/issues/1300

**Comment by chuntaojun** [comment]
cloud用户请更新cloud-seluth的依赖，这个是seluth内部的bug

**Comment by wangyingwei001** [comment]
那意思只能等zipkin修复这个bug了吗

**Comment by chuntaojun** [comment]
这个问题已经修复了的，更新seluth依赖就好了

发自我的iPhone

在 2019年11月19日，16:10，wangyingwei <notifications@github.com> 写道：

﻿

那意思只能等zipkin修复这个bug了吗

**Comment by wangyingwei001** [comment]
你更新的哪个版本
我现在的是
  <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-zipkin</artifactId>
            <version>2.0.0.RELEASE</version>
        </dependency>

**Comment by wangyingwei001** [comment]
解决了 我发现两种方法

**Comment by wangyingwei001** [comment]
解决了
