### ISSUE TITLE
nacos-server和客户端都使用docker，客户端获取配置会报错。

### ISSUE THREAD

**Issue by fosin** [alibaba/nacos#2076]
服务端：使用得docker镜像，镜像版本是最新版nacos/nacos-server:latest
客户端：基于Spring Cloud GreenWish.SR3,直接使用jar包可以正常启动使用，但是把jar打包到docker中运行就报错，我个人怀疑是nacos-server在发送配置文件到客户端容器时出了问题，客户端貌似没有读取到配置文件，才会报druid数据源的问题。
请大神帮看看，要怎么解决，谢谢！

dockerfile的内容如下：

FROM openjdk:8-jre-alpine
MAINTAINER fosin 28860823@qq.com
VOLUME /tmp
VOLUME /logs
ENV LANG C.UTF-8
ARG jarFile
COPY ${jarFile} app.jar
RUN echo "Asia/Shanghai" > /etc/timezone
RUN apk add --update netcat-openbsd && rm -rf /var/cache/apk/*
EXPOSE 51400
CMD ["java","-Djava.security.egd=file:/dev/./urandom","-jar","/app.jar"]

docker-composite启动容器后，报错日志如下：

。。。。。。。。。。。。。。。。。。部分不重要内容省略。。。。。。。。

Spring Boot Version: 2.1.9.RELEASE
------------------------------------------------------------
Java Home: /usr/lib/jvm/java-1.8-openjdk/jre
Java Vendor: IcedTea
Java Version: 1.8.0_212
JVM Free Memory: 218 MB
JVM Maximum Memory: 665 MB
JVM Total Memory: 267 MB
JCE Installed: Yes
------------------------------------------------------------
OS Architecture: amd64
OS Name: Linux
OS Version: 3.10.0-957.el7.x86_64
OS Date/Time: 2019-11-19T21:32:05.806
OS Temp Directory: /tmp
------------------------------------------------------------

2019-11-19 21:32:05,873 main INFO Log4j appears to be running in a Servlet environment, but there's no log4j-web module available. If you want better web container support, please add the log4j-web JAR to your web archive or server lib directory.
21:32:11,172 [main] INFO  org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration: Located property source: CompositePropertySource {name='NACOS', propertySources=[NacosPropertySource {name='anan-authserver-local.yaml'}, NacosPropertySource {name='anan-authserver.yaml'}, NacosPropertySource {name='application.yaml'}]}
21:32:11,283 [main] INFO  com.github.fosin.anan.AuthServerApplication: The following profiles are active: local

。。。。。。。。。。。。。。。。。。部分不重要内容省略。。。。。。。。

com.netflix.config.ConcurrentCompositeConfiguration@63ec445c
21:32:22,669 [main] INFO  com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure: Init DruidDataSource
21:32:22,796 [main] WARN  org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext: Exception encountered during context initialization - cancelling refresh attempt: org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is java.lang.RuntimeException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'servletEndpointRegistrar' defined in class path resource [org/springframework/boot/actuate/autoconfigure/endpoint/web/ServletEndpointManagementContextConfiguration$WebMvcServletEndpointManagementContextConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar]: Factory method 'servletEndpointRegistrar' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'healthEndpoint' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthEndpointConfiguration.class]: Unsatisfied dependency expressed through method 'healthEndpoint' parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'healthIndicatorRegistry' defined in class path resource [org/springframework/boot/actuate/autoconfigure/health/HealthIndicatorAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.actuate.health.HealthIndicatorRegistry]: Factory method 'healthIndicatorRegistry' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'org.springframework.boot.actuate.autoconfigure.jdbc.DataSourceHealthIndicatorAutoConfiguration': Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dataSource' defined in class path resource [com/alibaba/druid/spring/boot/autoconfigure/DruidDataSourceAutoConfigure.class]: Invocation of init method failed; nested exception is org.springframework.boot.autoconfigure.jdbc.DataSourceProperties$DataSourceBeanCreationException: Failed to determine a suitable driver class
21:32:23,443 [AsyncReporter{RabbitMQSender{addresses=[localhost:5672], queue=zipkin}}] WARN  zipkin2.reporter.AsyncReporter$BoundedAsyncReporter: Spans were dropped due to exceptions. All subsequent errors will be logged at FINE level.
21:32:23,444 [AsyncReporter{RabbitMQSender{addresses=[localhost:5672], queue=zipkin}}] WARN  zipkin2.reporter.AsyncReporter$BoundedAsyncReporter: Dropped 0 spans due to RuntimeException(Unable to establish connection to RabbitMQ server)
java.lang.RuntimeException: Unable to establish connection to RabbitMQ server
	at zipkin2.reporter.amqp.RabbitMQSender.newConnection(RabbitMQSender.java:250)
	at zipkin2.reporter.amqp.RabbitMQSender.get(RabbitMQSender.java:239)
	at zipkin2.reporter.amqp.RabbitMQSender$1.initialValue(RabbitMQSender.java:270)
	at zipkin2.reporter.amqp.RabbitMQSender$1.initialValue(RabbitMQSender.java:267)
	at java.lang.ThreadLocal.setInitialValue(ThreadLocal.java:180)
	at java.lang.ThreadLocal.get(ThreadLocal.java:170)
	at zipkin2.reporter.amqp.RabbitMQSender$RabbitMQCall.publish(RabbitMQSender.java:290)
	at zipkin2.reporter.amqp.RabbitMQSender$RabbitMQCall.doExecute(RabbitMQSender.java:285)
	at zipkin2.reporter.amqp.RabbitMQSender$RabbitMQCall.doExecute(RabbitMQSender.java:277)
	at zipkin2.Call$Base.execute(Call.java:380)
	at zipkin2.reporter.AsyncReporter$BoundedAsyncReporter.flush(AsyncReporter.java:285)
	at zipkin2.reporter.AsyncReporter$Flusher.run(AsyncReporter.java:354)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at com.rabbitmq.client.impl.SocketFrameHandlerFactory.create(SocketFrameHandlerFactory.java:60)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1102)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:1054)
	at com.rabbitmq.client.ConnectionFactory.newConnection(ConnectionFactory.java:931)
	at zipkin2.reporter.amqp.RabbitMQSender.newConnection(RabbitMQSender.java:248)
	... 12 more
21:32:23,504 [main] INFO  org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLoggingListener: 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
21:32:23,511 [main] ERROR org.springframework.boot.diagnostics.LoggingFailureAnalysisReporter: 

***************************
APPLICATION FAILED TO START
***************************

Description:

Failed to configure a DataSource: 'url' attribute is not specified and no embedded datasource could be configured.

Reason: Failed to determine a suitable driver class

Action:

Consider the following:
	If you want an embedded database (H2, HSQL or Derby), please put it on the classpath.
	If you have database settings to be loaded from a particular profile you may need to activate it (no profiles are currently active).

**Comment by fosin** [comment]
已解决

**Comment by decaMinCow** [comment]
> 已解决

怎么解决的啊
