### ISSUE TITLE
Nacos frequently sees client and server link timeouts

### ISSUE THREAD

**Issue by zqgback** [alibaba/nacos#2096]
java.net.SocketTimeoutException: connect timed out

nacos 版本1.1.3
srping cloud 版本Greenwich.SR1
spring-cloud-alibaba 版本2.1.0.RELEASE
spring boot 版本2.1.3.RELEASE

单机部署, 不管是部署到云服务，还是本地局域网环境，都会出现偶尔的心跳超时：

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([192.168.145.53:8848]) tried: failed to req API:192.168.145.53:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467) ~[nacos-client-1.1.4.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389) ~[nacos-client-1.1.4.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:300) ~[nacos-client-1.1.4.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:279) ~[nacos-client-1.1.4.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:325) [nacos-client-1.1.4.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_31]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_31]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_31]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_31]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_31]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_31]

**Comment by nkorange** [comment]
#2027 should have fixed this problem. The root cause of this time out is the tremendous amount of TIME_WAIT on either server side or client side. You can check it by this command:
```
netstat -ant | grep -c TIME_WAIT
```

**Comment by zqgback** [comment]
I checked with this command and found that the result was 0.
Since this is only a local test, the maximum value for TIME_WAIT is 10, but timeout errors are often reported

**Comment by nkorange** [comment]
> I checked with this command and found that the result was 0.
> Since this is only a local test, the maximum value for TIME_WAIT is 10, but timeout errors are often reported

Did you check both server side and client side?

**Comment by zqgback** [comment]
> > I checked with this command and found that the result was 0.
> > Since this is only a local test, the maximum value for TIME_WAIT is 10, but timeout errors are often reported
> 
> Did you check both server side and client side?

I have checked them all, but they are not big. I just saw other Issues and said that this problem will be fixed in 1.2 version.

**Comment by nkorange** [comment]
Since you are doing a local test, I suggest you use the latest nacos-client 1.1.5-SNAPSHOT to verify if your problem is fixed. Follow the [guide](https://nacos.io/zh-cn/docs/faq.html#3.15) to see how to update your dependency.
