### ISSUE TITLE
can't use 127.0.0.1:3306 for nacos-mysql

### ISSUE THREAD

**Issue by jackfruitran** [alibaba/nacos#2151]
## Issue Description
about use docker mysql for nacos

### Describe what happened (or what feature you want)
i have a docker container(mysql:5.7) and a datebase for nacos(this config, i always use for my k8s-nacos)
but i use nacos-server for this config
```
version: "2"
services:
  nacos:
    image: nacos/nacos-server:latest
    container_name: nacos
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_MASTER_SERVICE_HOST=127.0.0.1
      - MYSQL_MASTER_SERVICE_DB_NAME=nacos
      - MYSQL_MASTER_SERVICE_PORT=3306
      - MYSQL_MASTER_SERVICE_USER=root
      - MYSQL_MASTER_SERVICE_PASSWORD=123456
      - MYSQL_SLAVE_SERVICE_HOST=127.0.0.1
      - MYSQL_SLAVE_SERVICE_PORT=3306
    volumes:
      - ./standalone-logs/:/nacos/logs
      - ./init.d/custom.properties:/home/init.d/custom.properties
    ports:
      - "8848:8848"
```
i could't start up it 
they tell me can't connect to mysql

```
 org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Could not create connection to database server. Attempted reconnect 3 times. Giving up.)
nacos    | 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:81)
nacos    | 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:371)
nacos    | 	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:523)
nacos    | 	at com.alibaba.nacos.config.server.service.BasicDataSourceServiceImpl$SelectMasterTask.run(BasicDataSourceServiceImpl.java:317)
nacos    | 	at com.alibaba.nacos.config.server.service.BasicDataSourceServiceImpl.reload(BasicDataSourceServiceImpl.java:213)
nacos    | 	at com.alibaba.nacos.config.server.service.BasicDataSourceServiceImpl.init(BasicDataSourceServiceImpl.java:131)
nacos    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos    | 	at java.lang.reflect.Method.invoke(Method.java:498)
nacos    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
nacos    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
nacos    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
nacos    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
nacos    | 	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1083)
nacos    | 	at com.alibaba.nacos.config.server.service.DynamicDataSource.getDataSource(DynamicDataSource.java:54)
nacos    | 	at com.alibaba.nacos.config.server.service.PersistService.init(PersistService.java:91)
nacos    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos    | 	at java.lang.reflect.Method.invoke(Method.java:498)
nacos    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
nacos    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
nacos    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
nacos    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
nacos    | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273)
nacos    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1237)
nacos    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164)
nacos    | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
nacos    | 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
nacos    | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
nacos    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
nacos    | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273)
nacos    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1237)
nacos    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164)
nacos    | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
nacos    | 	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
nacos    | 	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:374)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1378)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:575)
nacos    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
nacos    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
nacos    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
nacos    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
nacos    | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
nacos    | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
nacos    | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
nacos    | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
nacos    | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
nacos    | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
nacos    | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
nacos    | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
nacos    | 	at com.alibaba.nacos.Nacos.main(Nacos.java:33)
nacos    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos    | 	at java.lang.reflect.Method.invoke(Method.java:498)
nacos    | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
nacos    | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
nacos    | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
nacos    | 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
nacos    | Caused by: org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Could not create connection to database server. Attempted reconnect 3 times. Giving up.)
nacos    | 	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1549)
nacos    | 	at org.apache.commons.dbcp.BasicDataSource.createDataSource(BasicDataSource.java:1388)
nacos    | 	at org.apache.commons.dbcp.BasicDataSource.getConnection(BasicDataSource.java:1044)
nacos    | 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151)
nacos    | 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)
nacos    | 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)
nacos    | 	... 82 more
nacos    | Caused by: com.mysql.jdbc.exceptions.jdbc4.MySQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.
nacos    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
nacos    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
nacos    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
nacos    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
nacos    | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
nacos    | 	at com.mysql.jdbc.Util.getInstance(Util.java:360)
nacos    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:956)
nacos    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:935)
nacos    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:924)
nacos    | 	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:870)
nacos    | 	at com.mysql.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:2144)
nacos    | 	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2069)
nacos    | 	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:790)
nacos    | 	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:44)
nacos    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
nacos    | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
nacos    | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
nacos    | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
nacos    | 	at com.mysql.jdbc.Util.handleNewInstance(Util.java:377)
nacos    | 	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:395)
nacos    | 	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:325)
nacos    | 	at org.apache.commons.dbcp.DriverConnectionFactory.createConnection(DriverConnectionFactory.java:38)
nacos    | 	at org.apache.commons.dbcp.PoolableConnectionFactory.makeObject(PoolableConnectionFactory.java:582)
nacos    | 	at org.apache.commons.dbcp.BasicDataSource.validateConnectionFactory(BasicDataSource.java:1556)
nacos    | 	at org.apache.commons.dbcp.BasicDataSource.createPoolableConnectionFactory(BasicDataSource.java:1545)
nacos    | 	... 87 more

```
i always user cluster ip for my k8s-nacos ,it can startup
now ,i can't start up for 127.0.0.1

0b8f6f7fb308        nacos/nacos-server:latest   "bin/docker-startu..."   2 minutes ago       Exited (137) 2 minutes ago                                                       nacos
88f17792b1ec        mysql:5.7                   "docker-entrypoint..."   38 minutes ago      Up 38 minutes                0.0.0.0:3306->3306/tcp, 33060/tcp                   mysql

### Describe what you expected to happen
i want use docker container for myself 

### How to reproduce it (as minimally and precisely as possible)

1. docker run mysql 
2. docker run nacos-server (use 127.0.0.1 )

### Tell us your environment
centos 7.6
mysql 5.7
docker1.13.1

### Anything else we need to know?
wait for you answer thanks

**Comment by jackfruitran** [comment]
oh, and when i use outer net ,it can start up

**Comment by nkorange** [comment]
You should telnet 127.0.0.1 3306 in your nacos server container, I guess it's a network failure.

**Comment by jackfruitran** [comment]
> You should telnet 127.0.0.1 3306 in your nacos server container, I guess it's a network failure.

why,i can't access 127.0.0.1 3306 in nacos server container? 
I can use 127.0.0.1 for other springboot images(withi mysql by 127.0.0.1 3306)

**Comment by jackfruitran** [comment]
> You should telnet 127.0.0.1 3306 in your nacos server container, I guess it's a network failure.
thanks i know , i need --link order

**Comment by Barzarrhey** [comment]
you konw what, I have the same sitution here, and I try to fix it. But I didn't make it work. As a child, when I surf the Internet in the Internet bar, when my computer has what fault, the waiter there told me nothing but to restart.  So I just restart the server, it works. Besides, I just install the mysql 5.7 on my centOS 7 and without rebooting. There must be network failure here.
