### ISSUE TITLE
Nacos作为配置中心：密文配置项的解密

### ISSUE THREAD

**Issue by fungoddd** [alibaba/nacos#2254]
## 问题描述

类型: *功能需求*

### 能否提供额外的扩展功能,在获取Nacos配置中心的配置后,刷新配置前可以进行一些自定义的处理,如：Nacos配置中心上的数据源配置为密文,可以在获取到配置后自己进行解密后,在刷新解密过的配置.

执行reBind重写绑定bean的时候因为获取到的配置值无法解密导致抛出异常

org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.datasource.druid.slave' to javax.sql.DataSource
	at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:250)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:226)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:210)
	at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:192)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:82)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:107)
	at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:93)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:416)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1686)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:407)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:102)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:84)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:128)
	at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:50)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354)
	at org.springframework.cloud.context.refresh.ContextRefresher.refreshEnvironment(ContextRefresher.java:79)
	at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:68)
	at org.springframework.cloud.endpoint.event.RefreshEventListener.handle(RefreshEventListener.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:180)
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354)
	at org.springframework.cloud.alibaba.nacos.refresh.NacosContextRefresher$1.receiveConfigInfo(NacosContextRefresher.java:124)
	at com.alibaba.nacos.client.config.impl.CacheData$1.run(CacheData.java:188)
	at com.alibaba.nacos.client.config.impl.CacheData.safeNotifyListener(CacheData.java:213)
	at com.alibaba.nacos.client.config.impl.CacheData.checkListenerMd5(CacheData.java:160)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPullingRunnable.run(ClientWorker.java:495)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### Tell us your environment
JDK1.8
spring-cloud-starter-alibaba-nacos-config 0.2.1.RELEASE

**Comment by nkorange** [comment]
你的需求是否和 #492 一样？

**Comment by fungoddd** [comment]
是的，希望可以刷新配置前可以自己对配置信息进行处理

**Comment by nkorange** [comment]
合并到 #492
