### ISSUE TITLE
com.alibaba.nacos.naming.push.receiver] but has failed to stop it. This is very likely to create a memory leak

### ISSUE THREAD

**Issue by xjr100419** [alibaba/nacos#2309]
## Issue Description

`
2020-01-16 11:57:57 [WARN] [org.apache.catalina.loader.WebappClassLoaderBase] The web application [ROOT] appears to have started a thread named [com.alibaba.nacos.naming.push.receiver] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.net.DualStackPlainDatagramSocketImpl.socketReceiveOrPeekData(Native Method)
 java.net.DualStackPlainDatagramSocketImpl.receive0(DualStackPlainDatagramSocketImpl.java:124)
 java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
 java.net.DatagramSocket.receive(DatagramSocket.java:812)
 com.alibaba.nacos.client.naming.core.PushReceiver.run(PushReceiver.java:73)
 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 java.util.concurrent.FutureTask.run(FutureTask.java:266)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 java.lang.Thread.run(Thread.java:748)
`

### Tell us your environment
nacos-server
Nacos 1.1.4

```
<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.0.3.RELEASE</version>
        <relativePath/>
    </parent>
<dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>Finchley.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
<!--       spring-cloud-alibaba 版本説明     https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E-->
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.0.1.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
```

org.springframework.boot:spring-boot-starter-web:2.0.3.RELEASE
org.springframework.cloud:spring-cloud-starter-openfeign:2.0.0.RELEASE
com.alibaba.cloud:spring-cloud-alibaba-nacos-discovery:2.0.1.RELEASE
com.alibaba.cloud:spring-cloud-alibaba-nacos-config:2.0.1.RELEASE

bootstrap.yaml

```
server:
  port: 8012
spring:
  application:
    name: xxxx
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        file-extension: yaml
        server-addr: 127.0.0.1:8848
        shared-dataids: application.yaml
```

**Comment by xjr100419** [comment]
in debug model
```
2020-01-16 12:52:24 [DEBUG] [sun.rmi.server.call] RMI TCP Connection(6)-192.168.1.130: [192.168.1.130] exception: 
javax.management.InstanceNotFoundException: org.springframework.boot:type=Admin,name=SpringApplication
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getMBean(DefaultMBeanServerInterceptor.java:1095)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.getAttribute(DefaultMBeanServerInterceptor.java:643)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.getAttribute(JmxMBeanServer.java:678)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1445)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.getAttribute(RMIConnectionImpl.java:639)
	at sun.reflect.GeneratedMethodAccessor78.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-01-16 12:52:24.976 DEBUG 11272 --- [ost-startStop-2] o.apache.catalina.core.StandardContext   : resetContext Tomcat:j2eeType=WebModule,name=//localhost/,J2EEApplication=none,J2EEServer=none
2020-01-16 12:52:24 [DEBUG] [org.apache.catalina.core.StandardContext] resetContext Tomcat:j2eeType=WebModule,name=//localhost/,J2EEApplication=none,J2EEServer=none
2020-01-16 12:52:24.976 DEBUG 11272 --- [)-192.168.1.130] sun.rmi.transport.tcp                    : RMI TCP Connection(6)-192.168.1.130: (port 54780) op = 80
2020-01-16 12:52:24 [DEBUG] [sun.rmi.transport.tcp] RMI TCP Connection(6)-192.168.1.130: (port 54780) op = 80
2020-01-16 12:52:24.976 DEBUG 11272 --- [ost-startStop-2] o.apache.catalina.core.StandardContext   : Stopping complete
2020-01-16 12:52:24 [DEBUG] [org.apache.catalina.core.StandardContext] Stopping complete
2020-01-16 12:52:26.391 DEBUG 11272 --- [naming.failover] com.alibaba.nacos.client.naming          : failover switch is not found, failover00-00---000-VIPSRV_FAILOVER_SWITCH-000---00-00
2020-01-16 12:52:26 [DEBUG] [com.alibaba.nacos.client.naming] failover switch is not found, failover00-00---000-VIPSRV_FAILOVER_SWITCH-000---00-00
```

**Comment by xjr100419** [comment]
when I remove configuration annotation
@ConfigurationProperties
it work fine

**Comment by bsed** [comment]
java.lang.Thread.run(Thread.java:748)
2020-07-20 11:47:19.200  WARN 25960 --- [           main] org.apache.juli.logging.DirectJDKLog.log:173 : The web application [ROOT] appears to have started a thread named [com.alibaba.nacos.naming.push.receiver] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:

**Comment by xiao-ma-nong** [comment]
解决了吗

**Comment by flyking999** [comment]
重启一下nacos应该能解决
