### ISSUE TITLE
Statement cancelled due to timeout or client request

### ISSUE THREAD

**Issue by fullee** [alibaba/nacos#2369]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
```
[root@iZbp1bto74otitpefmid5pZ nacos-compose]# docker-compose logs -f
Attaching to nacos1
nacos1    | + export DEFAULT_SEARCH_LOCATIONS=classpath:/,classpath:/config/,file:./,file:./config/
nacos1    | + DEFAULT_SEARCH_LOCATIONS=classpath:/,classpath:/config/,file:./,file:./config/
nacos1    | + export CUSTOM_SEARCH_LOCATIONS=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/
nacos1    | + CUSTOM_SEARCH_LOCATIONS=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/
nacos1    | + export CUSTOM_SEARCH_NAMES=application,custom
nacos1    | + CUSTOM_SEARCH_NAMES=application,custom
nacos1    | + PLUGINS_DIR=/home/nacos/plugins/peer-finder
nacos1    | + [[ standalone == \s\t\a\n\d\a\l\o\n\e ]]
nacos1    | + JAVA_OPT=' -Xms512m -Xmx512m -Xmn256m'
nacos1    | + JAVA_OPT=' -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true'
nacos1    | + [[ all == \c\o\n\f\i\g ]]
nacos1    | + [[ all == \n\a\m\i\n\g ]]
nacos1    | + [[ ! -z '' ]]
nacos1    | + [[ ! -z '' ]]
nacos1    | + [[ ! -z '' ]]
nacos1    | + [[ ! -z '' ]]
nacos1    | + [[ hostname == \h\o\s\t\n\a\m\e ]]
nacos1    | + JAVA_OPT=' -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true'
nacos1    | ++ /usr/lib/jvm/java-1.8.0-openjdk/bin/java -version
nacos1    | ++ sed -E -n 's/.* version "([0-9]*).*$/\1/p'
nacos1    | + JAVA_MAJOR_VERSION=1
nacos1    | + [[ 1 -ge 9 ]]
nacos1    | nacos is starting,you can check the /home/nacos/logs/start.out
nacos1    | + JAVA_OPT=' -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb'
nacos1    | + JAVA_OPT=' -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M'
nacos1    | + JAVA_OPT=' -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos'
nacos1    | + JAVA_OPT=' -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar'
nacos1    | + JAVA_OPT=' -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar '
nacos1    | + JAVA_OPT=' -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/'
nacos1    | + JAVA_OPT=' -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/ --spring.config.name=application,custom'
nacos1    | + JAVA_OPT=' -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/ --spring.config.name=application,custom --logging.config=/home/nacos/conf/nacos-logback.xml'
nacos1    | + echo 'nacos is starting,you can check the /home/nacos/logs/start.out'
nacos1    | + nohup /usr/lib/jvm/java-1.8.0-openjdk/bin/java -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/ --spring.config.name=application,custom --logging.config=/home/nacos/conf/nacos-logback.xml
nacos1    | + echo '/usr/lib/jvm/java-1.8.0-openjdk/bin/java  -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/ --spring.config.name=application,custom --logging.config=/home/nacos/conf/nacos-logback.xml'
nacos1    | /usr/lib/jvm/java-1.8.0-openjdk/bin/java  -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.preferHostnameOverIp=true -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/cmdb -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/home/nacos/conf/,/home/nacos/init.d/ --spring.config.name=application,custom --logging.config=/home/nacos/conf/nacos-logback.xml
nacos1    |          ,--.
nacos1    |        ,--.'|
nacos1    |    ,--,:  : |                                           Nacos 1.1.0
nacos1    | ,`--.'`|  ' :                       ,---.               Running in stand alone mode, All function modules
nacos1    | |   :  :  | |                      '   ,'\   .--.--.    Port: 8848
nacos1    | :   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: 26
nacos1    | |   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://nacos1:8848/nacos/index.html
nacos1    | '   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_
nacos1    | |   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io
nacos1    | '   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \
nacos1    | |   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  /
nacos1    | '   : |     ;  :   .'   \   :    : `----'  '--'.     /
nacos1    | ;   |.'     |  ,     .-./\   \  /            `--'---'
nacos1    | '---'        `--`---'     `----'
nacos1    | 2020-02-18 17:09:27,211 INFO Bean 'org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration' of type [org.springframework.security.config.annotation.configuration.ObjectPostProcessorConfiguration$$EnhancerBySpringCGLIB$$c42d329e] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
nacos1    | 2020-02-18 17:09:27,315 INFO Bean 'objectPostProcessor' of type [org.springframework.security.config.annotation.configuration.AutowireBeanFactoryObjectPostProcessor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
nacos1    | 2020-02-18 17:09:27,318 INFO Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@25ce9dc4' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
nacos1    | 2020-02-18 17:09:27,322 INFO Bean 'org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration' of type [org.springframework.security.config.annotation.method.configuration.GlobalMethodSecurityConfiguration$$EnhancerBySpringCGLIB$$e901d550] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
nacos1    | 2020-02-18 17:09:27,328 INFO Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
nacos1    | 2020-02-18 17:09:27,886 INFO Tomcat initialized with port(s): 8848 (http)
nacos1    | 2020-02-18 17:09:28,033 INFO Root WebApplicationContext: initialization completed in 2652 ms
nacos1    | 2020-02-18 17:09:43,007 WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'opsController' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-1.1.0.jar!/com/alibaba/nacos/config/server/controller/OpsController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
nacos1    | PreparedStatementCallback; SQL [SELECT id,data_id,group_id,tenant_id,app_name,content,md5,gmt_modified from config_info where id > ? order by id asc limit ?,?]; Statement cancelled due to timeout or client request; nested exception is com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
nacos1    | 2020-02-18 17:09:43,035 INFO Nacos Log files: /home/nacos/logs/
nacos1    | 2020-02-18 17:09:43,035 INFO Nacos Conf files: /home/nacos/conf/
nacos1    | 2020-02-18 17:09:43,035 INFO Nacos Data files: /home/nacos/data/
nacos1    | 2020-02-18 17:09:43,035 ERROR Nacos failed to start, please see /home/nacos/logs/nacos.log for more details.
nacos1    | 2020-02-18 17:09:43,051 INFO
nacos1    | Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
nacos1    | 2020-02-18 17:09:43,053 ERROR Application run failed
nacos1    | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'opsController' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-1.1.0.jar!/com/alibaba/nacos/config/server/controller/OpsController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
nacos1    | PreparedStatementCallback; SQL [SELECT id,data_id,group_id,tenant_id,app_name,content,md5,gmt_modified from config_info where id > ? order by id asc limit ?,?]; Statement cancelled due to timeout or client request; nested exception is com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
nacos1    | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
nacos1    | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
nacos1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308)
nacos1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154)
nacos1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
nacos1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
nacos1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
nacos1    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
nacos1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
nacos1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
nacos1    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
nacos1    | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
nacos1    | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
nacos1    | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
nacos1    | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
nacos1    | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
nacos1    | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
nacos1    | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
nacos1    | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
nacos1    | 	at com.alibaba.nacos.Nacos.main(Nacos.java:33)
nacos1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos1    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos1    | 	at java.lang.reflect.Method.invoke(Method.java:498)
nacos1    | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
nacos1    | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
nacos1    | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
nacos1    | 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
nacos1    | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
nacos1    | PreparedStatementCallback; SQL [SELECT id,data_id,group_id,tenant_id,app_name,content,md5,gmt_modified from config_info where id > ? order by id asc limit ?,?]; Statement cancelled due to timeout or client request; nested exception is com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
nacos1    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
nacos1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
nacos1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)
nacos1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
nacos1    | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
nacos1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
nacos1    | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
nacos1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
nacos1    | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
nacos1    | 	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273)
nacos1    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1237)
nacos1    | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164)
nacos1    | 	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
nacos1    | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
nacos1    | 	... 27 common frames omitted
nacos1    | Caused by: java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
nacos1    | PreparedStatementCallback; SQL [SELECT id,data_id,group_id,tenant_id,app_name,content,md5,gmt_modified from config_info where id > ? order by id asc limit ?,?]; Statement cancelled due to timeout or client request; nested exception is com.mysql.jdbc.exceptions.MySQLTimeoutException: Statement cancelled due to timeout or client request
nacos1    | 	at com.alibaba.nacos.config.server.service.dump.DumpService.init(DumpService.java:155)
nacos1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos1    | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos1    | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos1    | 	at java.lang.reflect.Method.invoke(Method.java:498)
nacos1    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
nacos1    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
nacos1    | 	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
nacos1    | 	... 40 common frames omitted
```

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

linux 
docker
nacos:1.1.0
mysql5.7

**Comment by ZShUn** [comment]
建议先升到1.1.4看看
