### ISSUE TITLE
GlobalExecutor queued up by ServiceUpdater leading to heap exhaustion

### ISSUE THREAD

**Issue by FinalVersion** [alibaba/nacos#2408]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)

Nacos does not respond to any request, java heap is exhausted, when naming service has around 100,000 services and 0 instances, and config service has nothing.

Heap dump analysis shows the retained heap of workQueue from `GlobalExecutor` is 11G(96% of the total heap). The workQueue is full of `ServiceManager$ServiceUpdater`s.

![image](https://user-images.githubusercontent.com/4286873/75851474-ba8f2b80-5e24-11ea-8d6a-bbc45b0e7fee.png)
![image](https://user-images.githubusercontent.com/4286873/75851477-bd8a1c00-5e24-11ea-822b-9d869360517a.png)

Exceptions in `naming-server.log`:
```
java.io.IOException: failed to req API:http://xxx.xxx.xxx.208:8848/nacos/v1/ns/instance/statuses. code:500 msg: java.net.ConnectException: Connection timed out (Connection timed out)
        at com.alibaba.nacos.naming.misc.NamingProxy.reqAPI(NamingProxy.java:168)
        at com.alibaba.nacos.naming.misc.ServiceStatusSynchronizer.get(ServiceStatusSynchronizer.java:85)
        at com.alibaba.nacos.naming.core.ServiceManager.updatedHealthStatus(ServiceManager.java:298)
        at com.alibaba.nacos.naming.core.ServiceManager$ServiceUpdater.run(ServiceManager.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

```
2020-02-29 23:59:26,680 WARN [DOMAIN-UPDATER] Exception while update service: DEFAULT_GROUP@@losbeyzg from xxx.xxx.xxx.208:8848, error: {}

java.lang.NullPointerException: null
        at com.alibaba.nacos.naming.core.ServiceManager.updatedHealthStatus(ServiceManager.java:299)
        at com.alibaba.nacos.naming.core.ServiceManager$ServiceUpdater.run(ServiceManager.java:230)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**xxx.xxx.xxx.208** has errors in `nacos.log` until 02-28 22:51:28, and has no `naming-server.log` sinc 02-29. 
Last error from `nacos.log`
```
2020-02-28 22:51:28,786 ERROR Servlet.service() for servlet [dispatcherServlet] in context with path [/nacos] threw exception

java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
        at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:456)
        at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120)
        at com.alibaba.nacos.naming.web.DistroFilter.doFilter(DistroFilter.java:143)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.nacos.naming.web.AuthFilter.doFilter(AuthFilter.java:98)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.nacos.naming.web.TrafficReviseFilter.doFilter(TrafficReviseFilter.java:69)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
```

### Describe what you expected to happen

Heap shouldn't be exhausted.

### How to reproduce it (as minimally and precisely as possible)

Haven't tried to consistently reproduce it. But the main operations I've taken before the issue were load testing the naming service by registering/querying/deregistering service intsances 

### Tell us your environment

- Nacos version: 1.1.4
- Deployment: 6 node cluster across several data centers
- Server Spec: 4 core/16G 
- OS: CentOS 7.4
- JVM: openjdk version "1.8.0_161"
- Heap configurations: -Xms8g -Xmx12g -Xmn3g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m

### Anything else we need to know?

Some preliminary analysis:
GlobalExecutor queued up by ServiceUpdater
 caused by: ServiceUpdater takes too long to run 
  cassed by: com.alibaba.nacos.naming.misc.NamingProxy#reqAPI stuck in requesting an unresponding node

**Comment by chuntaojun** [comment]
“Connection timed out” Is that a lot of misinformation

**Comment by FinalVersion** [comment]
> “Connection timed out” Is that a lot of misinformation

I think it may be part of the root cause, since it's a request made inside `ServiceUpdater.run`

**Comment by chuntaojun** [comment]
> > “Connection timed out” Is that a lot of misinformation
> 
> I think it may be part of the root cause, since it's a request made inside `ServiceUpdater.run`

Yes, the problem is caused by the internal timeout time, too few lines to process the task, and the invalid Service information synchronization. Both the network reason and the thread reason cause this problem. Because the number of threads is too small, the amount of consumption will be less than the number of new tasks for information synchronization

**Comment by FinalVersion** [comment]
> > > “Connection timed out” Is that a lot of misinformation
> > 
> > 
> > I think it may be part of the root cause, since it's a request made inside `ServiceUpdater.run`
> 
> Yes, the problem is caused by the internal timeout time, too few lines to process the task, and the invalid Service information synchronization. Both the network reason and the thread reason cause this problem. Because the number of threads is too small, the amount of consumption will be less than the number of new tasks for information synchronization

Reducing the timeout should help. Anyway, the Executor workQueue size should be bounded.

**Comment by chuntaojun** [comment]
> > > > “Connection timed out” Is that a lot of misinformation
> > > 
> > > 
> > > I think it may be part of the root cause, since it's a request made inside `ServiceUpdater.run`
> > 
> > 
> > Yes, the problem is caused by the internal timeout time, too few lines to process the task, and the invalid Service information synchronization. Both the network reason and the thread reason cause this problem. Because the number of threads is too small, the amount of consumption will be less than the number of new tasks for information synchronization
> 
> Reducing the timeout should help. Anyway, the Executor workQueue size should be bounded.

agree with you
