### ISSUE TITLE
docker 1.2.0 修改密码时NullPointerException

### ISSUE THREAD

**Issue by niyaode** [alibaba/nacos#2427]
```
java.lang.NullPointerException: null
	at com.alibaba.nacos.console.controller.UserController.updatePassword(UserController.java:211)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
```

**Comment by chuntaojun** [comment]
Under repair
