### ISSUE TITLE
[NA] failed to request

### ISSUE THREAD

**Issue by weinianta** [alibaba/nacos#2437]
经常这样发送连接失败，但是服务又没任何问题

![image](https://user-images.githubusercontent.com/13379708/76180331-a4081c00-61f8-11ea-93ee-aefdda4d3ebf.png)

![image](https://user-images.githubusercontent.com/13379708/76180359-b1bda180-61f8-11ea-81df-c29e1572bdc1.png)

**Comment by nkorange** [comment]
看起来是域名解析不太稳定，可能需要联系你的DNS解析服务咨询下。

**Comment by SandNight** [comment]
> 看起来是域名解析不太稳定，可能需要联系你的DNS解析服务咨询下。

我也遇到了同样的问题，nacos-server 1.1.3升级到1.2.0  
nacos-client version  1.1.4

2020-03-12 14:20:51 [com.alibaba.nacos.client.naming.updater]  WARN  com.alibaba.nacos.client.naming - failed to request http://172.16.5.16:8848/nacos/v1/ns/instance/list?app=unknown&healthyOnly=false&namespaceId=bddf255f-a744-4702-9aea-6e6b7016eb75&clientIP=192.168.1.9&serviceName=DEFAULT_GROUP%40%40dzf-account-server&udpPort=56270&encoding=UTF-8 from 172.16.5.16
2020-03-12 14:20:51 [com.alibaba.nacos.client.naming.updater]  ERROR com.alibaba.nacos.client.naming - [NA] failed to request 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:89)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:413)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:454)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:300)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:279)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:325)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-03-12 14:20:51 [com.alibaba.nacos.client.naming.updater]  ERROR com.alibaba.nacos.client.naming - request 172.16.5.16:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:172.16.5.16:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:427)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:454)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:300)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:279)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:325)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by weinianta** [comment]
是的，我域名解析很稳定的。肯定不是这个问题------------------ 原始邮件 ------------------
发件人: "jade"<notifications@github.com>
发送时间: 2020年3月12日(星期四) 下午2:33
收件人: "alibaba/nacos"<nacos@noreply.github.com>;
抄送: "weinianta"<851161583@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [alibaba/nacos] [NA] failed to request (#2437)




  
看起来是域名解析不太稳定，可能需要联系你的DNS解析&#x670D;务咨询下。
  
我也遇到了同样的问题，nacos-server 1.1.3升级到1.2.0
 nacos-client version  1.1.4
 
2020-03-12 14:20:51 [com.alibaba.nacos.client.naming.updater]  WARN  com.alibaba.nacos.client.naming - failed to request http://172.16.5.16:8848/nacos/v1/ns/instance/list?app=unknown&healthyOnly=false&namespaceId=bddf255f-a744-4702-9aea-6e6b7016eb75&clientIP=192.168.1.9&serviceName=DEFAULT_GROUP%40%40dzf-account-server&udpPort=56270&encoding=UTF-8 from 172.16.5.16
 2020-03-12 14:20:51 [com.alibaba.nacos.client.naming.updater]  ERROR com.alibaba.nacos.client.naming - [NA] failed to request
 java.net.SocketTimeoutException: connect timed out
 at java.net.PlainSocketImpl.socketConnect(Native Method)
 at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
 at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
 at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
 at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
 at java.net.Socket.connect(Socket.java:589)
 at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
 at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
 at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
 at sun.net.www.http.HttpClient.(HttpClient.java:242)
 at sun.net.www.http.HttpClient.New(HttpClient.java:339)
 at sun.net.www.http.HttpClient.New(HttpClient.java:357)
 at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
 at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
 at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
 at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
 at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:89)
 at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:413)
 at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:454)
 at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
 at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:300)
 at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:279)
 at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:325)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
 at java.util.concurrent.FutureTask.run(FutureTask.java)
 at java.util.concurrent.ScheduledThreadPoolExecutor201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
 2020-03-12 14:20:51 [com.alibaba.nacos.client.naming.updater]  ERROR com.alibaba.nacos.client.naming - request 172.16.5.16:8848 failed.
 com.alibaba.nacos.api.exception.NacosException: failed to req API:172.16.5.16:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
 at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:427)
 at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:454)
 at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
 at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:300)
 at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:279)
 at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:325)
 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
 at java.util.concurrent.FutureTask.run(FutureTask.java)
 at java.util.concurrent.ScheduledThreadPoolExecutor201(ScheduledThreadPoolExecutor.java:180)
 at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
 at java.lang.Thread.run(Thread.java:748)
 
&mdash;

**Comment by lijilina** [comment]
这个问题如何解决

**Comment by abcf49** [comment]
同问。
有无可能是网络原因？

**Comment by zhangzh0508** [comment]
同问，一直刷，使用k8s后，域名都是{service}.{namespace}:8848，k8s的dns解析问题吗？

**Comment by JiaShengLiao** [comment]
我遇到了这个问题
2022-09-20 00:22:36.634 ERROR 8 --- [.naming.updater] com.alibaba.nacos.client.naming : [NA] failed to request
java.net.SocketTimeoutException: null
	at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:211)
	at sun.net.www.http.HttpClient.New(HttpClient.java:308)
	at sun.net.www.http.HttpClient.New(HttpClient.java:326)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966)
	at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:112)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:603)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
