### ISSUE TITLE
开启验证：NACOS_AUTH_ENABLE=true后，启动项目报错

### ISSUE THREAD

**Issue by michaelmofa** [alibaba/nacos#2442]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)
从1.1.4版本升级到了1.2.0之后，启用nacos的NACOS_AUTH_ENABLE=true，在业务项目启动的时候，发生了报错，服务没有成功注册到nacos，是不是还需要配置什么？

After upgrading from 1.1.4 to 1.2.0, NACOS_AUTH_ENABLE = true is enabled for nacos. When the business project is started, an error occurs and the service is not successfully registered with nacos. Is there anything else to configure?

### How to reproduce it (as minimally and precisely as possible)
项目配置如下图
Configuration
1. pom.xml
![image](https://user-images.githubusercontent.com/7973111/76202932-a71efe80-6230-11ea-9d31-f4e1f7920adb.png)

2. bootstrap.properties
![image](https://user-images.githubusercontent.com/7973111/76203011-d59cd980-6230-11ea-9f72-269c8c7ddbab.png)

3. application.yml
![image](https://user-images.githubusercontent.com/7973111/76203068-f402d500-6230-11ea-8b66-66c3ffd99017.png)

报错信息如下
Error message

> `com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Mar 09 17:49:26 GMT+08:00 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>`

![image](https://user-images.githubusercontent.com/7973111/76203207-37f5da00-6231-11ea-9635-76db4eecde00.png)

> `com.alibaba.nacos.api.exception.NacosException: failed to req API:http://127.0.0.1:8848/nacos/v1/ns/service/list. code:403 msg: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Mar 09 17:49:53 GMT+08:00 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>`

![image](https://user-images.githubusercontent.com/7973111/76203266-4d6b0400-6231-11ea-9f0b-7bfa3df07434.png)

**Comment by chuntaojun** [comment]
目前cloud还没有正式适配nacos 1.2.0 的权限控制，请耐心等待下，此issue将被移到spring-cloud-alibaba

**Comment by chuntaojun** [comment]
Issue moved to [alibaba/spring-cloud-alibaba #1241](https://github.com/alibaba/spring-cloud-alibaba/issues/1241) via [**ZenHub**](https://www.zenhub.com/)

**Comment by chuntaojun** [comment]
Issue moved to [alibaba/spring-cloud-alibaba #1242](https://github.com/alibaba/spring-cloud-alibaba/issues/1242) via [**ZenHub**](https://www.zenhub.com/)

**Comment by MsencSir** [comment]
我的项目也是同样的问题，也是引入的org.springframework.cloud的依赖 不开启nacos登录权限是没有问题的，一旦开启就会报和楼主一样的异常！

**Comment by W-Knight** [comment]
> 我的项目也是同样的问题，也是引入的org.springframework.cloud的依赖 不开启nacos登录权限是没有问题的，一旦开启就会报和楼主一样的异常！

试下把public空间也授权给登录用户

**Comment by wenbiao2019** [comment]
com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Jun 17 17:29:50 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:262) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:143) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:92) ~[nacos-client-1.2.1.jar:na]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:85) [spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:75) [spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:179) [spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:155) [spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:88) [spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:52) [spring-cloud-context-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) [spring-cloud-context-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:97) [spring-cloud-context-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at com.wenbiao.FansApplication.main(FansApplication.java:15) [classes/:na]

2021-06-17 17:29:50.359 ERROR 13880 --- [           main] o.s.c.a.n.c.NacosPropertySourceBuilder   : get data from Nacos error,dataId:service-provider-wen-dev.properties, 

com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Jun 17 17:29:50 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:262) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:143) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:92) ~[nacos-client-1.2.1.jar:na]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:85) [spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:75) [spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:179) [spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:159) [spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.alibaba.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:88) [spring-cloud-alibaba-nacos-config-0.2.2.RELEASE.jar:0.2.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:52) [spring-cloud-context-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) [spring-cloud-context-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:97) [spring-cloud-context-2.2.2.RELEASE.jar:2.2.2.RELEASE]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.6.RELEASE.jar:2.2.6.RELEASE]
	at com.wenbiao.FansApplication.main(FansApplication.java:15) [classes/:na]

**Comment by DemoMoon** [comment]
password  不是 passwork 吧？
