### ISSUE TITLE
nacos1.2.0 版本 dubbo注册一直报错，返回unknown user!

### ISSUE THREAD

**Issue by wcfeng9527** [alibaba/nacos#2501]
dubbo版本使用2.7.4.1，nacos服务端使用1.2.0，客户端使用1.2.0，把dubbo服务注册到nacos中，
当nacos服务端配置nacos.core.auth.enabled=true时，一直返回错误信息如下：
```
2020-03-20 21:21:49.355 [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming - request: /nacos/v1/ns/instance/list failed, servers: [172.16.2.107:8848], code: 403, msg: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mappingfor /error, so you are seeing this as a fallback.</p><div id='created'>Fri Mar 20 21:21:49 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
2020-03-20 21:21:49.355 [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming - [NA] failed to update serviceName: DEFAULT_GROUP@@providers:cn.com.esgcc.tc.core.order.refund.api.OrderReturnFlowService:1.0.0:
com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance/list after all servers([172.16.2.107:8848]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Mar 20 21:21:49 CST 2020</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
    at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:490)
    at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:395)
    at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:391)
    at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:319)
    at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:281)
    at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:327)
```

目前在dubbo注册时配置了username和password,但是不起作用

**Comment by chuntaojun** [comment]
#2508

**Comment by caiwei1988** [comment]
我也碰到同样问题，请问怎么解决的？

**Comment by chengbinghan** [comment]
.........

**Comment by silentsugar** [comment]
同问  一样的问题
