### ISSUE TITLE
 NACOS 1.1.4 code:503 msg: server is STARTING now, please try again later!

### ISSUE THREAD

**Issue by silverlight** [alibaba/nacos#2612]
## Issue Description

Type: *bug report* or *feature request*
用K8S安装nacos 1.1.4 并用ingress暴露8848端口。访问dashborad正常。用程序连接nacos时报错。
虽然报错了，但是POD没有任何log打印出来。
```
 | [com.alibaba.nacos.naming.beat.sender] |  | 2020-04-11 18:14:44,099 | ERROR | com.alibaba.nacos.client.naming | request nacos.beencoding.com:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://nacos.xxxxx.com:8848/nacos/v1/ns/instance/beat. code:503 msg: server is STARTING now, please try again later!
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340) ~[nacos-client-1.0.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367) [nacos-client-1.0.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) [nacos-client-1.0.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:227) [nacos-client-1.0.0.jar:?]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:109) [nacos-client-1.0.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
 | [com.alibaba.nacos.naming.beat.sender] |  | 2020-04-11 18:14:44,099 | ERROR | com.alibaba.nacos.client.naming | [CLIENT-BEAT] failed to send beat: {"cluster":"DEFAULT","ip":"172.17.231.1","metadata":{"preserved.register.source":"SPRING_CLOUD"},"port":18081,"scheduled":true,"serviceName":"DEFAULT_GROUP@@commodity-center","weight":1.0}
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([nacos.beencoding.com:8848]) tried: failed to req API:http://nacos.beencoding.com:8848/nacos/v1/ns/instance/beat. code:503 msg: server is STARTING now, please try again later!
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380) ~[nacos-client-1.0.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) ~[nacos-client-1.0.0.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:227) [nacos-client-1.0.0.jar:?]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:109) [nacos-client-1.0.0.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_152]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_152]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_152]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_152]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_152]
```
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment

centos 7.6 k8s 1.16 nacos 1.1.4
### Anything else we need to know?
nacos.yml
```
apiVersion: v1
kind: Service
metadata:
  name: nacos-headless
  labels:
    app: nacos-headless
spec:
  ports:
    - port: 8848
      name: server
      targetPort: 8848
  selector:
    app: nacos
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos-cm
data:
  mysql.db.name: "nacos_devtest"
  mysql.port: "3306"
  mysql.user: "nacos"
  mysql.password: "nacos"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nacos
spec:
  serviceName: nacos-headless
  replicas: 1
  template:
    metadata:
      labels:
        app: nacos
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos-headless
              topologyKey: "kubernetes.io/hostname"
      containers:
        - name: k8snacos
          imagePullPolicy: Always
          image: nacos/nacos-server:latest
          ports:
            - containerPort: 8848
              name: client
          env:
            - name: NACOS_REPLICAS
              value: "1"
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos-cm
                  key: mysql.password
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos-0.nacos-headless.default.svc.cluster.local:8848"
  selector:
    matchLabels:
      app: nacos

```

**Comment by zhuuvzhi** [comment]
原因是nacos无法将pod的IP和domain name对应起来，不能识别成同一台节点，我准备提交PR
