### ISSUE TITLE
SQLException when config server quickstart

### ISSUE THREAD

**Issue by wangweizZZ** [alibaba/nacos#2657]
## Issue Description

Type: *bug report* 

### Describe what happened (or what feature you want)
The sql in `com.alibaba.nacos.config.server.service.PersistService#listGroupKeyMd5ByPage()` miss return param `type` resulting in error when convert to bean by ConfigInfoWrapperRowMapper.
 
> PreparedStatementCallback; uncategorized SQLException for SQL [ SELECT t.id,data_id,group_id,tenant_id,app_name,md5,gmt_modified FROM ( SELECT id FROM config_info ORDER BY id LIMIT ?,?  ) g, config_info t WHERE g.id = t.id]; SQL state [S0022]; error code [0]; Column 'type' not found.; nested exception is java.sql.SQLException: Column 'type' not found.
	at com.alibaba.nacos.config.server.service.dump.DumpService.init(DumpService.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
---
使用到 ConfigInfoWrapperRowMapper 的部分sql 中缺少type返回,而该mapper需要此参数
其他几处由于未使用到而未触发，开启快速启动时不走全量dump会触发

### How to reproduce it (as minimally and precisely as possible)

1.  set isQuickStart=true
2.  make sure nacos/status/heartBeat.txt exists so  nacos will not start with allDump

**Comment by wolfgangzhu** [comment]
@i will solve it@
