### ISSUE TITLE
Windows下调试nacos，出现不能注册服务的问题。

### ISSUE THREAD

**Issue by Jnoee** [alibaba/nacos#276]
在本机运行nacos，应用配置设置成127.0.0.1:8848是可以正常注册服务的。
但我把nacos部署到容器后，应用配置设置成10.9.4.155:8848，抛出异常：

2018-11-14 17:24:39.822 ERROR 8172 --- [           main] o.s.c.a.n.registry.NacosServiceRegistry  : nacos registry, film-server register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='10.9.4.155:8848', endpoint='', namespace='', logName='', service='film-server', weight=1.0, clusterName='DEFAULT', metadata={}, registerEnabled=true, ip='10.9.6.45', networkInterface='', port=8020, secure=false, accessKey='', secretKey=''}},

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([10.9.4.155:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:339) ~[nacos-client-0.3.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:272) ~[nacos-client-0.3.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:171) ~[nacos-client-0.3.0.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:161) ~[nacos-client-0.3.0.jar:na]
	at org.springframework.cloud.alibaba.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:58) [spring-cloud-alibaba-nacos-discovery-0.2.0.RELEASE.jar:0.2.0.RELEASE]
	at org.springframework.cloud.alibaba.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:31) [spring-cloud-alibaba-nacos-discovery-0.2.0.RELEASE.jar:0.2.0.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:209) [spring-cloud-commons-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.cloud.alibaba.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:75) [spring-cloud-alibaba-nacos-discovery-0.2.0.RELEASE.jar:0.2.0.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:108) [spring-cloud-commons-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:73) [spring-cloud-commons-2.0.1.RELEASE.jar:2.0.1.RELEASE]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_162]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_162]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_162]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_162]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:261) [spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:180) [spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142) [spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) [spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) [spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:164) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) [spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1258) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1246) [spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at com.cntest.su.boot.film.FilmServer.main(FilmServer.java:18) [classes/:na]

以及心跳也抛出异常：
2018-11-14 17:24:49.782 ERROR 8172 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : [] [] [NA] req api:/nacos/v1/ns/api/clientBeat failed, servers: [10.9.4.155:8848]

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/clientBeat after all servers([10.9.4.155:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:339) ~[nacos-client-0.3.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:314) ~[nacos-client-0.3.0.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.callAllServers(NamingProxy.java:242) ~[nacos-client-0.3.0.jar:na]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:94) [nacos-client-0.3.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_162]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]

http://10.9.4.155:8848/nacos 控制台是正常的，配置也是可用的。
我是在windows下的Eclipse中启动的一个应用。

**Comment by nkorange** [comment]
10.9.4.155:8848/nacos/v1/ns/api/hello 在浏览器上执行这个URL看看返回什么

**Comment by Jnoee** [comment]
部署到linux了，还是存在这个问题，服务注册不了。
日志看到client的版本是0.3.0，把nacos控制台换成0.3.0也不行。
服务列表显示有服务名，集群数为1，实例数和健康实例数均为0。

执行10.9.4.155:8848/nacos/v1/ns/api/hello返回：
{"msg":"Hello! I am Nacos-Naming and healthy! total dom: diamond 0,raft 3, local port:8848"}

我同时在测试sentinel，在sentinel的机器列表里可以看到服务实例的机器。
通过spring cloud alibaba来跟spring cloud集成的nacos和sentinel。

**Comment by nkorange** [comment]
@Jnoee Docker Swarm集群应该也是容器的，你看看Swarm集群里，容器间的网络通信是否正常

**Comment by Jnoee** [comment]
查到原因了，部署nacos服务的时候network选错了...

**Comment by RookieoftheYear** [comment]
> 查到原因了，部署nacos服务的时候network选错了...

请问在哪设置的？
我也遇到这个问题了

**Comment by copyshop** [comment]
我也碰到这种情况 我是本机运行 没有其他网络选择，请问题主怎么解决的。

**Comment by copyshop** [comment]
> > 查到原因了，部署nacos服务的时候network选错了...
> 
> 请问在哪设置的？
> 我也遇到这个问题了

我也碰到这个问题了 你是怎么解决的

**Comment by qq1311256696** [comment]
应该是nacos退出的时候没有用脚本退出吧
