### ISSUE TITLE
Nacos   1.2.1   删除 服务异常

### ISSUE THREAD

**Issue by Johnson-Jia** [alibaba/nacos#2786]
### **Nacos   1.2.1   删除 服务**

com.alibaba.nacos.api.exception.NacosException: Raft remove failed, key:com.alibaba.nacos.naming.domains.meta.940b7352-8228-453c-8b7d-ff87f7a65b76##DEFAULT_GROUP@@consumers:com.tbc.app.mc.account.remote.RemoteService:1.0:
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftConsistencyServiceImpl.remove(RaftConsistencyServiceImpl.java:72)
	at com.alibaba.nacos.naming.consistency.DelegateConsistencyServiceImpl.remove(DelegateConsistencyServiceImpl.java:47)
	at com.alibaba.nacos.naming.core.ServiceManager.easyRemoveService(ServiceManager.java:450)
	at com.alibaba.nacos.naming.controllers.ServiceController.remove(ServiceController.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)

**Comment by Johnson-Jia** [comment]
Caused by: java.lang.NullPointerException: null

**Comment by chuntaojun** [comment]
集群模式还是单机模式，你的情况属于leader节点的信息不存在引起的，请核对下你的cluster.conf文件和本机的ip信息

**Comment by Johnson-Jia** [comment]
单机模式， cluster.conf 配置了当前机器 ip 与端口  例如：127.0.0.1:8849

**Comment by chuntaojun** [comment]
单机模式下这个cluster.conf不需要配置，你是使用k8s吗？还是直接物理机部署

**Comment by Johnson-Jia** [comment]
不对 直接使用 startup.sh 启动的没有加单机模式 参数，应该是 集群模式，  但是只配置了一个自己的节点，物理机。

**Comment by chuntaojun** [comment]
集群模式推荐还是需要三台机子，因为集群模式和单机模式的内部运行逻辑还是有所不同的

**Comment by Johnson-Jia** [comment]
好的，谢谢
