### ISSUE TITLE
1.2.1 大量线程堵塞 在 AbstractMultiworkerIOReactor$Worker （Windows运行1~2 h后 ）导致CPU百分百

### ISSUE THREAD

**Issue by xiaohusuper** [alibaba/nacos#2797]
通过 ProcessExplorer 和 jstack -l 15888 > c:/15888.stack 命令查看结果

"I/O dispatcher 22" #173 prio=5 os_prio=0 tid=0x000000002ea42800 nid=0x4e0c runnable [0x0000000037a5e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl.resetWakeupSocket0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl.resetWakeupSocket(WindowsSelectorImpl.java:473)
	- locked <0x00000005c5af0910> (a java.lang.Object)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:174)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000005c5aef360> (a sun.nio.ch.Util$3)
	- locked <0x00000005c5aef350> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000005c5aef1e0> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- None

"I/O dispatcher 21" #172 prio=5 os_prio=0 tid=0x000000002ea49000 nid=0x1ec0 runnable [0x000000003795e000]
   java.lang.Thread.State: RUNNABLE
	at sun.nio.ch.WindowsSelectorImpl.resetWakeupSocket0(Native Method)
	at sun.nio.ch.WindowsSelectorImpl.resetWakeupSocket(WindowsSelectorImpl.java:473)
	- locked <0x00000005c5b07420> (a java.lang.Object)
	at sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:174)
	at sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:86)
	- locked <0x00000005c5ae3a78> (a sun.nio.ch.Util$3)
	- locked <0x00000005c5ae3a68> (a java.util.Collections$UnmodifiableSet)
	- locked <0x00000005c5ae39e8> (a sun.nio.ch.WindowsSelectorImpl)
	at sun.nio.ch.SelectorImpl.select(SelectorImpl.java:97)
	at org.apache.http.impl.nio.reactor.AbstractIOReactor.execute(AbstractIOReactor.java:255)
	at org.apache.http.impl.nio.reactor.BaseIOReactor.execute(BaseIOReactor.java:104)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor$Worker.run(AbstractMultiworkerIOReactor.java:588)
	at java.lang.Thread.run(Thread.java:748)

**Comment by zscboy** [comment]
![image](https://user-images.githubusercontent.com/8179656/83862528-a5dc6f80-a754-11ea-8917-03b6a17ac87e.png)
版本：1.3.0

**Comment by chuntaojun** [comment]
you can see here ：https://blog.csdn.net/liu_005/article/details/86253576
