### ISSUE TITLE
 failed to req API:/nacos/v1/ns/instance after all servers ([xxx.xx.xx.xx:8848])tried 

### ISSUE THREAD

**Issue by wkztselina** [alibaba/nacos#284]
# 当单机模式运行时，可以进行服务的注册。可是改成集群模式以后，就提示 `failed to req API:/nacos/v1/ns/instance after all servers ([xxx.xx.xx.xx:8848])tried `错误。cluster.conf 中配置为
`localhost:8848` 求解决

**Comment by nkorange** [comment]
集群模式最小要求三个节点

**Comment by tangwt** [comment]
> 集群模式最小要求三个节点

我这边就是3个节点搭建集群，也报这个错误，后台的日志是WARN Resolved [java.lang.IllegalArgumentException: dom not found: service-provider]，这个大概是什么问题？

**Comment by yangyshdan** [comment]
You probably need to upload your log so we can take a look and help :-)

**Comment by tangwt** [comment]
看了下源代码，这是个小的bug导致的。在Nacos4的NetUtils类中取localIP的时候用的是InetAddress.getLocalHost().getHostAddress()这个方法，这个应该是不严谨的。所以导致集群中取到的ip都是127.0.0.1，导致leader选举一直失败。希望能优化这个代码。目前我的解决方案是修改/etc/hosts内的配置。

**Comment by nkorange** [comment]
@tangwt 如果你是集群模式的问题，请单独提一个issue，说明你的配置和错误信息。

**Comment by wkztselina** [comment]
> 集群模式最小要求三个节点

如果我，现在不想走集群，但是想把存储改为mysql，请问这样的话，要怎么配置一下。我看只有集群模式支持mysql是吧？，求大佬

**Comment by nkorange** [comment]
> > 集群模式最小要求三个节点
> 
> 如果我，现在不想走集群，但是想把存储改为mysql，请问这样的话，要怎么配置一下。我看只有集群模式支持mysql是吧？，求大佬

@hxy1991 帮看下

**Comment by hxy1991** [comment]
> mysql是吧？，求大

这个目前是不支持的。请问你是什么场景？能否详细描述下？

**Comment by jackorjack** [comment]
这个问题现在要怎么解决

**Comment by d22shen** [comment]
各位大佬，我是在照着文档在本地试验fescar-samples，在启动Fescar-server的时候不断报这个错，求帮助
https://github.com/fescar-group/fescar-samples/tree/master/nacos

**Comment by d22shen** [comment]
2019-03-11 13:34:59.871 INFO [main]c.a.fescar.core.rpc.netty.AbstractRpcRemotingServer.start:150 -Server started ... 
Mon Mar 11 13:35:08 CST 2019 sun.misc.Launcher$AppClassLoader@776ec8df JM.Log:INFO Init JM logger with Slf4jLoggerFactory success, sun.misc.Launcher$AppClassLoader@776ec8df
Mon Mar 11 13:35:08 CST 2019 sun.misc.Launcher$AppClassLoader@776ec8df JM.Log:INFO Log root path: C:\Users\dsshen\logs\
Mon Mar 11 13:35:08 CST 2019 sun.misc.Launcher$AppClassLoader@776ec8df JM.Log:INFO Set nacos log path: C:\Users\dsshen\logs\nacos
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost]) tried
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:154)
	at com.alibaba.fescar.core.rpc.netty.RpcServer.init(RpcServer.java:130)
	at com.alibaba.fescar.server.Server.main(Server.java:81)
Caused by: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([localhost]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:366)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:290)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:175)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:178)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:161)
	at com.alibaba.fescar.discovery.registry.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:78)
	at com.alibaba.fescar.core.rpc.netty.AbstractRpcRemotingServer.start(AbstractRpcRemotingServer.java:151)

**Comment by liuheyong** [comment]
666

**Comment by OneJane** [comment]
> 看了下源代码，这是个小的bug导致的。在Nacos4的NetUtils类中取localIP的时候用的是InetAddress.getLocalHost().getHostAddress()这个方法，这个应该是不严谨的。所以导致集群中取到的ip都是127.0.0.1，导致leader选举一直失败。希望能优化这个代码。目前我的解决方案是修改/etc/hosts内的配置。

您好，请我如何修改hosts，是容器内部的还是宿主机的呀

**Comment by paderlol** [comment]
Nacos支持你自己自定义网段，甚至指定IP，官方文档里面有关于多网卡的配置。

**Comment by CharleyCao** [comment]
集群模式下，注册总是失败，直接postman调用注册接口都提示500超时

**Comment by luanhj** [comment]
前提是单机的方式启动的nacos(sh startup.sh -m standalone ) ,项目部署服务器a若该服务器装的有nacos环境，则项目启动只需要在application.properties配置nacos信息里配置就能正常启动   若项目在b服务器上部署没有装nacos环境用a服务器上的nacos，项目中中必须要有2个配置文件 bootstrap.properties和application.properties 并且2个配置文件都需要配置nacos，出现上面那个原因是因为在b服务器上bootstrap.properties和application.properties都配置了nacos信息(配置改成a服务器上的nacos的ip和端口)，application.properties中的nacos配置信息注掉了

**Comment by coder-PengWenHao** [comment]
how to solve?
