### ISSUE TITLE
导入idea后，naming模块无法独立启动

### ISSUE THREAD

**Issue by shizhengxing** [alibaba/nacos#3042]
download源码导入idea后，naming模块无法独立启动，报错如下。经过查看这个AuthManager是在console模块有实现类，难道naming模块不能独立启动吗？感觉与设计不符啊
```
`Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.alibaba.nacos.core.auth.AuthManager' available: expected at least 1 bean which qualifies as autowire candidate. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true)}
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoMatchingBeanFound(DefaultListableBeanFactory.java:1644)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1203)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:593)
	... 77 common frames omitted`
```

**Comment by KomachiSion** [comment]
Start console/Nacos with VM option `-Dnacos.functionMode=naming`
