### ISSUE TITLE
nacos1.3开启权限后，在nacos配置了sentinel的限流规则，但是请求的数据的时候报403的错误，请问该怎么解决？ 

### ISSUE THREAD

**Issue by wangzhedong** [alibaba/nacos#3148]
引用了sentinel-datasource-nacos，用nacos配置sentinel的限流规则，配置如下：
  #远程naocs config配置sentinel限流规则
    sentinel:
      datasource.ds1.nacos:
        server-addr: @nacos.config.addr@
        namespace: @nacos.namespace@
        group-id: DEFAULT_GROUP
        data-id: sysmg-flow
        data-type: json
        rule-type: flow
在启动的时候报：[sub-server-error] no right, dataId=sysmg-flow, group=DEFAULT_GROUP, tenant=local
[check-update] get changed dataId error, code: 403
是不是在设计权限的时候没有考虑到这方面的问题？

**Comment by KomachiSion** [comment]
没有更详细一点的日志吗？ 只这么看看不出什么问题。

**Comment by wangzhedong** [comment]
2020-06-23 09:19:31.950 ERROR 15392 --- [           main] c.a.n.client.config.impl.ClientWorker    : [fixed-localhost_8848-local] [sub-server-error] no right, dataId=sysmg-flow, group=DEFAULT_GROUP, tenant=local

2020-06-23 09:19:41.778 ERROR 15392 --- [host_8848-local] c.a.n.client.config.impl.ClientWorker    : [fixed-localhost_8848-local] [check-update] get changed dataId error, code: 403

错误日志就这么多了，然后我看了下发起请求时的参数，没有发现token或者用户名和密码之类的参数

**Comment by KomachiSion** [comment]
服务端那边没有错误日志吗？

**Comment by wangzhedong** [comment]
nacos.log文件里只有一个空指针的报错
java.lang.NullPointerException: null
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore.receivedBeat(RaftCore.java:590)
	at com.alibaba.nacos.naming.controllers.RaftController.beat(RaftController.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
你就告诉我，你们发送post或者get请求是往里面放token的关键类是那些，我自己找找看，应该是请求远程nacos config数据时没有token

**Comment by KomachiSion** [comment]
我不清楚是不是sentinel还不支持填写user和password。nacos-group中的example已经是挺早以前的了。需要更新。

**Comment by KomachiSion** [comment]
然后关于权限token，一般是放在request header里的accessToken

**Comment by KomachiSion** [comment]
No response more than **7 days**, close issue

**Comment by gongmb** [comment]
问题解决了嘛??

**Comment by lihaipeng0417** [comment]
> 问题解决了嘛??

sentinel-datasource中没有支持username和password，需要可以自己手工添加

**Comment by justinytsoft** [comment]
> > 问题解决了嘛??
> 
> sentinel-datasource中没有支持username和password，需要可以自己手工添加

能详细说下怎么添加吗？ 谢谢

**Comment by justinytsoft** [comment]
我解决了。。。 只需要把nacos地址换成本地的即可； 参考地址：[https://www.langhuaquan.com/blog/145.html](url)
