### ISSUE TITLE
nacos1.3.0连接mysql8.0失败

### ISSUE THREAD

**Issue by zhygit0610** [alibaba/nacos#3156]
mysql账号密码，主机端口信息均无错误。已提前在数据库中执行sql脚本，脚本地址为https://github.com/alibaba/nacos/blob/develop/distribution/conf/nacos-mysql.sql
使用1.2.1连接mysql5.6可以正常使用。

config-fatal.log报错信息：
2020-06-23 11:59:45,521 ERROR Nacos Server did not start because dumpservice bean construction failure :
java.lang.IllegalStateException: No DataSource set

2020-06-23 11:59:52,640 ERROR [master-db] master db not found.

2020-06-23 11:59:52,649 ERROR [db-error] master db  down.

2020-06-23 12:02:39,827 ERROR [master-db] master db not found.

nacos.log报错信息：
Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
        at com.alibaba.nacos.config.server.service.dump.DumpService.dumpOperate(DumpService.java:191)
        at com.alibaba.nacos.config.server.service.dump.ExternalDumpService.init(ExternalDumpService.java:49)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)

**Comment by chuntaojun** [comment]
https://github.com/alibaba/nacos/issues/2916
