### ISSUE TITLE
disconnect message show

### ISSUE THREAD

**Issue by xuechaos** [alibaba/nacos#32]
Nacos Server stop or network is not work，Client don`t show disConnect message through the log.

**Comment by mytang0** [comment]
Is the connection status of the client ESTABLISHED?

**Comment by xuechaos** [comment]
@mytang0 The data that SDK gets maybe is cached data. so need the way to know the data.

**Comment by hxy1991** [comment]
When the Nacos service hangs or there is a problem with the network connection, some corresponding logs will be recorded in "${user.home}/logs/nacos/".

#### config.log

```shell
# Recording client failed to get config from server
01 2018-12-26 19:48:29.222 WARN [main :c.a.n.c.c.NacosConfigService] [fixed-localhost_8848] [] [] [get-config] get from server error, dataId=test, group=nacos, tenant=, msg=ErrCode:500,ErrMsg:no available server
# Recording client used local cached data
01 2018-12-26 19:48:29.223 WARN [main :c.a.n.c.c.NacosConfigService] [fixed-localhost_8848] [] [] [get-config] get snapshot ok, dataId=test, group=nacos, tenant=, config=

# Recording client failed to listen config from server
01 2018-12-26 19:48:29.221 ERROR [main :c.a.n.c.c.i.ClientWorker] [fixed-localhost_8848] [] [NACOS-XXXX] [sub-server] get server config exception, dataId=test, group=nacos, tenant=, msg=java.net.ConnectException: no available server
01 2018-12-26 19:48:29.239 ERROR [com.alibaba.nacos.client.Worker.longPullingfixed-localhost_8848:c.a.n.c.c.i.ServerHttpAgent] [] [] [NACOS ConnectException] currentServerAddr:localhost:8848
01 2018-12-26 19:49:29.442 ERROR [com.alibaba.nacos.client.Worker.longPullingfixed-localhost_8848:c.a.n.c.c.i.ClientWorker] [fixed-localhost_8848] [] [NACOS-XXXX] [check-update] get changed dataId exception, msg=java.net.ConnectException: no available server
```

#### naming.log

```shell
# Recording client failed to update service info from server
01 2018-12-26 19:50:49.976 WARN [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] [] [] [] failed to request http://localhost:8848/nacos/v1/ns/api/srvIPXT?dom=test&clientIP=30.5.125.77&udpPort=65117&encoding=UTF-8& from 127.0.0.1
01 2018-12-26 19:50:49.977 ERROR [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] [] [] [NA] failed to request
java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
```

If you want to output logs to stdout, you can configure the log configuration file (logback.xml) as follows:

```
<appender name="STDOUT" class="ch.qos.logback.core.ConsoleAppender">
    <encoder>
        <Pattern>%date %level %msg%n%n</Pattern>
        <charset>UTF-8</charset>
    </encoder>
</appender>

<logger name="com.alibaba.nacos.client.config.NacosConfigService">
    <appender-ref ref="STDOUT"/>
    <level value="WARN"/>
</logger>

<logger name="com.alibaba.nacos.client.config.impl.ClientWorker">
    <appender-ref ref="STDOUT"/>
    <level value="WARN"/>
</logger>
```
