### ISSUE TITLE
Nacos naming server Raft remove failed.

### ISSUE THREAD

**Issue by eonezhang** [alibaba/nacos#3202]
## Issue Description

Type: *bug report*

### Describe what happened
Nacos naming server Raft remove failed.

```
2020-06-29 14:29:51,682 WARN namespace : 56f023d8-ad71-4450-adba-cdf2d8b797d8, [DEV@@visits-service] services are automatically cleaned

2020-06-29 14:29:51,684 ERROR namespace : 56f023d8-ad71-4450-adba-cdf2d8b797d8, [DEV@@visits-service] services are automatically clean has error : {}

com.alibaba.nacos.api.exception.NacosException: Raft remove failed, key:com.alibaba.nacos.naming.domains.meta.56f023d8-ad71-4450-adba-cdf2d8b797d8##DEV@@visits-service
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftConsistencyServiceImpl.remove(RaftConsistencyServiceImpl.java:74)
	at com.alibaba.nacos.naming.consistency.DelegateConsistencyServiceImpl.remove(DelegateConsistencyServiceImpl.java:52)
	at com.alibaba.nacos.naming.core.ServiceManager.easyRemoveService(ServiceManager.java:394)
	at com.alibaba.nacos.naming.core.ServiceManager$EmptyServiceAutoClean.lambda$null$1(ServiceManager.java:788)
	at java.util.concurrent.ConcurrentHashMap.computeIfPresent(ConcurrentHashMap.java:1769)
	at com.alibaba.nacos.naming.core.ServiceManager$EmptyServiceAutoClean.lambda$null$2(ServiceManager.java:777)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.concurrent.ConcurrentHashMap$EntrySpliterator.forEachRemaining(ConcurrentHashMap.java:3606)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at com.alibaba.nacos.naming.core.ServiceManager$EmptyServiceAutoClean.lambda$run$3(ServiceManager.java:777)
	at java.util.concurrent.ConcurrentHashMap.forEach(ConcurrentHashMap.java:1597)
	at com.alibaba.nacos.naming.core.ServiceManager$EmptyServiceAutoClean.run(ServiceManager.java:765)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalArgumentException: Malformed escape pair at index 37: http://fe80:0:0:0:aede:48ff:fe00:1122%4:8848/nacos/v1/ns/raft/datum/commit
	at java.net.URI.create(URI.java:852)
	at com.ning.http.client.RequestBuilderBase.buildURI(RequestBuilderBase.java:390)
	at com.ning.http.client.RequestBuilderBase.setUrl(RequestBuilderBase.java:373)
	at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.setUrl(AsyncHttpClient.java:339)
	at com.ning.http.client.AsyncHttpClient.requestBuilder(AsyncHttpClient.java:597)
	at com.ning.http.client.AsyncHttpClient.prepareDelete(AsyncHttpClient.java:493)
	at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpDeleteLarge(HttpClient.java:212)
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore.signalDelete(RaftCore.java:254)
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftConsistencyServiceImpl.remove(RaftConsistencyServiceImpl.java:70)
	... 24 common frames omitted
Caused by: java.net.URISyntaxException: Malformed escape pair at index 37: http://fe80:0:0:0:aede:48ff:fe00:1122%4:8848/nacos/v1/ns/raft/datum/commit
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.scanEscape(URI.java:2978)
	at java.net.URI$Parser.scan(URI.java:3001)
	at java.net.URI$Parser.parseAuthority(URI.java:3142)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at java.net.URI.create(URI.java:850)
	... 32 common frames omitted
```

### Describe what you expected to happen
can register/de-register from naming server successfully.

### How to reproduce it (as minimally and precisely as possible)

1. nacos stand-lone env
2. with one customized namespace
3. register service to naming server(it seems `group` not working result in what happened.)
```
spring:
  profiles: default
  cloud:
    nacos:
      discovery:
        server-addr: http://localhost:8848
        namespace: 56f023d8-ad71-4450-adba-cdf2d8b797d8
        group: DEV
```
### Tell us your environment
nacos-1.3.0
```
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-config:2.2.1.RELEASE'
    implementation 'com.alibaba.cloud:spring-cloud-starter-alibaba-nacos-discovery:2.2.1.RELEASE'
```

**Comment by KomachiSion** [comment]
Nacos do not support IPV6 for now.

**Comment by eonezhang** [comment]
> Nacos do not support IPV6 for now.

how does it happen, `http://fe80:0:0:0:aede:48ff:fe00:1122%4:8848/nacos/v1/ns/raft/datum/commit` is the nacos server address.

**Comment by KomachiSion** [comment]
see your `cluster.conf` file, the cluster member ip is setting in there.
