### ISSUE TITLE
使用nacos作为注册中心，自建一个logback-spring.xml日志配置文件，在日志配置文件中配置<contextName>为非'nacos'，项目启动时会报错，但项目正常启动

### ISSUE THREAD

**Issue by yuxioman** [alibaba/nacos#3251]
报错信息：
```
ERROR in ch.qos.logback.classic.joran.action.ContextNameAction - Failed to rename context [自己配置的ContextName] as [nacos] java.lang.IllegalStateException: Context has been already given a name
	at java.lang.IllegalStateException: Context has been already given a name
	at 	at ch.qos.logback.core.ContextBase.setName(ContextBase.java:194)
	at 	at ch.qos.logback.classic.LoggerContext.setName(LoggerContext.java:107)
	at 	at ch.qos.logback.classic.joran.action.ContextNameAction.body(ContextNameAction.java:31)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.callBodyAction(Interpreter.java:289)
	at 	at ch.qos.logback.core.joran.spi.Interpreter.characters(Interpreter.java:172)
	at 	at ch.qos.logback.core.joran.spi.EventPlayer.play(EventPlayer.java:57)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:165)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:152)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:110)
	at 	at ch.qos.logback.core.joran.GenericConfigurator.doConfigure(GenericConfigurator.java:53)
	at 	at ch.qos.logback.classic.util.ContextInitializer.configureByResource(ContextInitializer.java:75)
	at 	at com.alibaba.nacos.client.logging.logback.LogbackNacosLogging.loadConfiguration(LogbackNacosLogging.java:44)
	at 	at com.alibaba.nacos.client.utils.LogUtils.<clinit>(LogUtils.java:47)
	at 	at com.alibaba.nacos.client.config.NacosConfigService.<clinit>(NacosConfigService.java:57)
	at 	at java.lang.Class.forName0(Native Method)
	at 	at java.lang.Class.forName(Class.java:264)
	at 	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:40)
	at 	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:43)
	at 	at com.alibaba.cloud.nacos.NacosConfigProperties.configServiceInstance(NacosConfigProperties.java:368)
	at 	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:67)
	at 	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:97)
	at 	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:623)
	at 	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:367)
	at 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at 	at com.cpw.common.XXXXXXApplication.main(XXXXXXApplication.java:26)
```
相关环境：
日志配置文件中添加了关于将日志输出到 logstash 的简单配置

**Comment by KomachiSion** [comment]
For print `nacos` naming or config log to other log file so that no effect business log, the client build in a logback/log4j configuration, and use contextName - nacos.

The error will only effect the nacos naming and config log. Will not effect your application and bussiness log.

**Comment by KomachiSion** [comment]
latest version has remove context.

**Comment by miaojincs** [comment]
> latest version has remove context.

i also encountered this problem,

version:
<spring-cloud.version>2021.0.1</spring-cloud.version>
<spring-cloud-alibaba.version>2021.0.1.0</spring-cloud-alibaba.version>
nacos-client 1.4.2

i want to know which version fix this issue
