### ISSUE TITLE
启动服务发现添加完pom坐标springboot启动后报错

### ISSUE THREAD

**Issue by changhe626** [alibaba/nacos#326]
springboot版本<version>1.5.10.RELEASE</version>
jdk1.8

pom中内容是:

	<parent>
		<groupId>org.springframework.boot</groupId>
		<artifactId>spring-boot-starter-parent</artifactId>
		<version>1.5.10.RELEASE</version>
		<relativePath/> 
	</parent>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
		<java.version>1.8</java.version>
	</properties>
	<dependencies>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.1.0</version>
        </dependency>
        <dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-discovery-spring-boot-starter</artifactId>
            <version>0.1.0</version>
        </dependency>
    </dependencies>
	

启动报错为:

java.io.IOException: Error while requesting: http://null/vipserver/serverlist'. Server returned: 500
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServerListFromEndpoint(NamingProxy.java:102)
	at com.alibaba.nacos.client.naming.net.NamingProxy.refreshSrvIfNeed(NamingProxy.java:135)
	at com.alibaba.nacos.client.naming.net.NamingProxy.access$000(NamingProxy.java:39)
	at com.alibaba.nacos.client.naming.net.NamingProxy$2.run(NamingProxy.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call$$$capture(Executors.java:511)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

重试了好多次都报这个错误
2018年11月21日15:35:05

**Comment by flystar32** [comment]
请问你配置了 nacos.discovery.server-addr=  这个参数吗？

**Comment by changhe626** [comment]
> 请问你配置了 nacos.discovery.server-addr= 这个参数吗？
> 详情可以参考这个文档 https://github.com/nacos-group/nacos-spring-boot-project#nacos-discovery
是的,我配置了.
nacos.config.server-addr=127.0.0.1:8848
但是看着控制台上没有任何的日志输出

**Comment by changhe626** [comment]
thanks

**Comment by changhe626** [comment]
thanks
