### ISSUE TITLE
K8S 节点注册运行出现注册不同步

### ISSUE THREAD

**Issue by lijilina** [alibaba/nacos#3307]
运行在K8S上的三节点NACOS集群，出现节点注册数据不同步的问题,

![image](https://user-images.githubusercontent.com/58079402/87267675-eae58580-c4fa-11ea-8263-264b1f3355c5.png)
在naocs控制台点查询 我们正常来说是有三个服务注册的，但是点查询有时候会出现只有两个服务

我们目前分析是有个节点注册数据不同步，把那个不同步的节点关闭，再重新添加这个节点就又恢复正常
查看 naming-raft.log
```
2020-07-13 01:56:13,931 ERROR NACOS-RAFT error while sending heart-beat to peer: nacos-cluster-2.nacos-headless.cfyy-app
.svc.cluster.local:8848 {}

java.net.ConnectException: http://nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local:8848/nacos/v1/ns/raft/beat
        at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
        at org.jboss.netty.channel.DefaultChannelFuture.addListener(DefaultChannelFuture.java:145)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1072)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:894)
        at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:520)
        at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:233)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpPostLarge(HttpClient.java:194)
        at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore$HeartBeat.sendBeat(RaftCore.java:546)
        at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore$HeartBeat.run(RaftCore.java:475)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:101)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
        at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:109)
        at org.jboss.netty.channel.Channels.connect(Channels.java:634)
        at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1030)
        ... 13 common frames omitted
2020-07-13 01:56:18,932 ERROR NACOS-RAFT error while sending heart-beat to peer: nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local:8848 {}

java.net.ConnectException: http://nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local:8848/nacos/v1/ns/raft/beat
        at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
        at org.jboss.netty.channel.DefaultChannelFuture.addListener(DefaultChannelFuture.java:145)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1072)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:894)
        at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:520)
        at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:233)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpPostLarge(HttpClient.java:194)
        at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore$HeartBeat.sendBeat(RaftCore.java:546)
        at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore$HeartBeat.run(RaftCore.java:475)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:101)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
        at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:109)
        at org.jboss.netty.channel.Channels.connect(Channels.java:634)
        at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1030)
        ... 13 common frames omitted
2020-07-13 05:13:47,798 INFO raft peers changed: [{"adWeight":0,"alive":false,"ip":"nacos-cluster-0.nacos-headless.cfyy-app.svc.cluster.local","key":"nacos-cluster-0.nacos-headless.cfyy-app.svc.cluster.local:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":false,"ip":"nacos-cluster-1.nacos-headless.cfyy-app.svc.cluster.local","key":"nacos-cluster-1.nacos-headless.cfyy-app.svc.cluster.local:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":false,"ip":"nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local","key":"nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]

2020-07-13 05:13:49,799 INFO raft peers changed: [{"adWeight":0,"alive":false,"ip":"nacos-cluster-0.nacos-headless.cfyy-app.svc.cluster.local","key":"nacos-cluster-0.nacos-headless.cfyy-app.svc.cluster.local:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":false,"ip":"nacos-cluster-1.nacos-headless.cfyy-app.svc.cluster.local","key":"nacos-cluster-1.nacos-headless.cfyy-app.svc.cluster.local:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":false,"ip":"nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local","key":"nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]

2020-07-13 09:54:40,311 INFO server list is updated, dead: 1, servers: [{"adWeight":0,"alive":false,"ip":"nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local","key":"nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]
2020-07-13 09:54:40,515 ERROR NACOS-RAFT error while sending heart-beat to peer: nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local:8848 {}

java.net.ConnectException: connection timed out: nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local/10.42.0.191:8848 to http://nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local:8848/nacos/v1/ns/raft/beat
        at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
        at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:380)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:140)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:83)
        at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
        at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
        at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
        at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.jboss.netty.channel.ConnectTimeoutException: connection timed out: nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local/10.42.0.191:8848
        at org.jboss.netty.channel.socket.nio.NioClientBoss.processConnectTimeout(NioClientBoss.java:137)
        ... 8 common frames omitted
2020-07-13 09:54:43,650 INFO raft peers changed: [{"adWeight":0,"alive":false,"ip":"nacos-cluster-0.nacos-headless.cfyy-app.svc.cluster.local","key":"nacos-cluster-0.nacos-headless.cfyy-app.svc.cluster.local:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":false,"ip":"nacos-cluster-1.nacos-headless.cfyy-app.svc.cluster.local","key":"nacos-cluster-1.nacos-headless.cfyy-app.svc.cluster.local:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]
```

**Comment by lijilina** [comment]
我们把 nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local 这个pod重启之后 就恢复正常了，查看 kubelet日志也没有错误信息

**Comment by lijilina** [comment]
几天之后又出现这个问题了，可以确定另外两个节点可以解析到nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local这个节点 
这个是naming-raft.log
2020-07-14 23:29:31,717 ERROR NACOS-RAFT error while sending heart-beat to peer: nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local:8848 {}

java.net.ConnectException: http://nacos-cluster-2.nacos-headless.cfyy-app.svc.cluster.local:8848/nacos/v1/ns/raft/beat
        at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
        at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
        at org.jboss.netty.channel.DefaultChannelFuture.addListener(DefaultChannelFuture.java:145)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1072)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.execute(NettyAsyncHttpProvider.java:894)
        at com.ning.http.client.AsyncHttpClient.executeRequest(AsyncHttpClient.java:520)
        at com.ning.http.client.AsyncHttpClient$BoundRequestBuilder.execute(AsyncHttpClient.java:233)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpPostLarge(HttpClient.java:194)
        at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore$HeartBeat.sendBeat(RaftCore.java:546)
        at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore$HeartBeat.run(RaftCore.java:475)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.nio.channels.UnresolvedAddressException: null
        at sun.nio.ch.Net.checkAddress(Net.java:101)
        at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:622)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.connect(NioClientSocketPipelineSink.java:108)
        at org.jboss.netty.channel.socket.nio.NioClientSocketPipelineSink.eventSunk(NioClientSocketPipelineSink.java:70)
        at org.jboss.netty.handler.codec.oneone.OneToOneEncoder.handleDownstream(OneToOneEncoder.java:54)
        at org.jboss.netty.handler.codec.http.HttpClientCodec.handleDownstream(HttpClientCodec.java:97)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleDownstream(ChunkedWriteHandler.java:109)
        at org.jboss.netty.channel.Channels.connect(Channels.java:634)
        at org.jboss.netty.channel.AbstractChannel.connect(AbstractChannel.java:207)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:229)
        at org.jboss.netty.bootstrap.ClientBootstrap.connect(ClientBootstrap.java:182)
        at com.ning.http.client.providers.netty.NettyAsyncHttpProvider.doConnect(NettyAsyncHttpProvider.java:1030)
        ... 13 common frames omitted

有什么解决方法吗

**Comment by KomachiSion** [comment]
`InetSocketAddress.isUnresolved失败`自行搜索类似的问题的解决办法。 
从目前信息来看，这个错误并非nacos产生的，而是创建socket连接时，java的Net层对域名和地址的处理无效导致的。
