### ISSUE TITLE
When a node of Nacos is down, occasionally some instances of services will not be offline

### ISSUE THREAD

**Issue by yyt6200** [alibaba/nacos#3337]
After the server where Nacos is located is down, sometimes some service instances will not be offline. In fact, the service instance is also hung up due to the server downtime. At this time, the suspended machine must be started before the service instance can be offline

**Comment by KomachiSion** [comment]
Nacos down has no related for the instances of services. They will switch to other Nacos node to send beat and register.

So i can't understand your problem.

**Comment by yyt6200** [comment]
Thank you for your reply. I mean that when a Nacos node is offline, a certain service will exit at this time, which will cause the service to be online all the time. It doesn't happen every time. It's random. I'm sure that service has exited on swarm, but that service instance still exists in Nacos's list of services

**Comment by KomachiSion** [comment]
I read your supplementary explanation. But I am still confused. 

1. `a Nacos nodes is offline` means Nacos server node is down, but from your context, I think you want to explain the service which register to Nacos is offline, isn't it?
2. `I'm sure that service has exited on swarm, but that service instance still exists in Nacos's list of services`, It depends that you whether deregister instance before you exited instance. If not deregister, the only way of remove instance is by healthy check, it will cost at least 45s, almost 1 min.
3. If you said the offline is the button `offline`, the instance will exist in server list all the time, because the `offline` is a logic status, which means your don't want to let this instance provide feature, but it is a registered instance, and you should see and control it.

**Comment by yyt6200** [comment]
我直接用中文描述吧，也许翻译存在歧义。
我先描述下环境，三台虚拟机作为Nacos(N-A,N-B,N-C)的服务器,6台虚拟机作为Swarm集群。9台虚拟机分别在三台PC宿主机上（A,B,C）。分别是一台PC宿主机有1个Nacos和两个Swarm节点。
Swarm上跑了N个服务，都是两个副本
A机因为一些原因，直接关机了。也就是N-A节点和Swarm的两个节点下线了。下线的Swarm节点上面的服务会迁移到剩下的四台节点上。
通过上述操作，我就发现有两个服务在Nacos上实例数是3。其实应该是2。是有一个服务一直不下线。我把A机器开机后，开启Swarm的虚拟机，通过查询容器的日志比对注册实例的IP确定三个实例中一个已经死掉的实例就是属于刚开启的Swarm节点。（这个时候Nacos那台虚拟机我还没开启）。这个实际上死掉的实例一直在线，不下线的！最后我开启了N-A这个虚拟机，过了几十秒，那个实际上死掉的实例居然自己下线了。后来我了解了下心跳的规则，大概是这样的工作原理。Nacos集群检测心跳，是每个节点认领部分的实例来维持心跳，感觉是N-A节点下线后，检测任务没有重新分配导致的。不知道我猜测的是否正确。

**Comment by yyt6200** [comment]
![微信图片_20200720141541](https://user-images.githubusercontent.com/44914868/87905597-8fd00780-ca93-11ea-9b09-a279fec0cd02.png)
图片里10.0.1.176 实例就是已经Down掉的，但是一直挂在Nacos上面。只有当N-A开启后，这个176实例才下线

**Comment by yyt6200** [comment]
可以解答下这个问题么

**Comment by KomachiSion** [comment]
什么版本的nacos？

**Comment by yyt6200** [comment]
1.2.1版本的

**Comment by KomachiSion** [comment]
可以搜索一下naming-raft.log 查一下关键字`server list is updated` 看下当时A机器挂掉 其他Nacos节点是否获取到？

**Comment by yyt6200** [comment]
查询了15号的日志，server list is updated 相关的显示的是三个节点健在的
2020-07-15 11:06:16,241 INFO server list is updated, new: 3 servers: [{"adWeight":0,"alive":false,"ip":"192.168.3.110","key":"192.168.3.110:8848","lastRefTime":0,"servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":false,"ip":"192.168.3.111","key":"192.168.3.111:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":false,"ip":"192.168.3.112","key":"192.168.3.112:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]
然后我刚刚试着把192.168.3.110这个节点关闭了，看了下另外两台的日志输出如下内容

2020-07-23 14:45:38,276 INFO raft peers changed: 2020-07-23 14:45:33,240 ERROR NACOS-RAFT error while sending heart-beat to peer: 192.168.3.110:8848 {}

java.net.ConnectException: 拒绝连接: /192.168.3.110:8848 to http://192.168.3.110:8848/nacos/v1/ns/raft/beat
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:380)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: 拒绝连接: /192.168.3.110:8848
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 common frames omitted
2020-07-23 14:45:38,246 ERROR NACOS-RAFT error while sending heart-beat to peer: 192.168.3.110:8848 {}

**Comment by KomachiSion** [comment]
主要看下节点关闭后的，server list is updated日志，如果一直没有日志就说明没有生效。

**Comment by yyt6200** [comment]
在另外两个节点的**naming-raft.log**中，没看到 **server list is updated** 相关的日志。**192.168.3.111**输出的都是些 拒绝链接的。

**192.168.3.111**上的**naming-raft.log**文件内容只有这个
2020-07-23 14:45:38,276 INFO raft peers changed: [{"adWeight":0,"alive":false,"ip":"192.168.3.110","key":"192.168.3.110:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":false,"ip":"192.168.3.111","key":"192.168.3.111:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":false,"ip":"192.168.3.112","key":"192.168.3.112:8848","lastRefTime":0,"lastRefTimeStr":"","servePort":8848,"site":"unknown","weight":1}]

**Comment by KomachiSion** [comment]
还有 naming-server 下的 `[NACOS-DISTRO] healthy server list changed`  也搜一下，这个日志是感知服务是否健康的

**Comment by yyt6200** [comment]
**192.168.3.111** 节点上的 **naming-server** 文件输出这个

2020-07-23 14:45:38,930 INFO [NACOS-DISTRO] healthy server list changed, old: [{"adWeight":0,"alive":true,"ip":"192.168.3.110","key":"192.168.3.110:8848","lastRefTime":1595040053687,"lastRefTimeStr":"2020-07-18 10:40:53","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":true,"ip":"192.168.3.111","key":"192.168.3.111:8848","lastRefTime":1595040052706,"lastRefTimeStr":"2020-07-18 10:40:52","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":true,"ip":"192.168.3.112","key":"192.168.3.112:8848","lastRefTime":1595040053830,"lastRefTimeStr":"2020-07-18 10:40:53","servePort":8848,"site":"unknown","weight":1}], new: [{"adWeight":0,"alive":true,"ip":"192.168.3.111","key":"192.168.3.111:8848","lastRefTime":1595486736929,"lastRefTimeStr":"2020-07-23 14:45:36","servePort":8848,"site":"unknown","weight":1}, {"adWeight":0,"alive":true,"ip":"192.168.3.112","key":"192.168.3.112:8848","lastRefTime":1595486738276,"lastRefTimeStr":"2020-07-23 14:45:38","servePort":8848,"site":"unknown","weight":1}]

2020-07-23 14:45:38,931 INFO [NACOS-DISTRO] disable health check for 60000 ms from now on.

2020-07-23 14:45:38,931 INFO receive config info: unknown#192.168.3.111:8848#1595486738931#1


2020-07-23 14:45:40,268 INFO receive config info: unknown#192.168.3.112:8848#1595486740277#1


2020-07-23 14:45:40,933 INFO receive config info: unknown#192.168.3.111:8848#1595486740933#1


2020-07-23 14:45:42,269 INFO receive config info: unknown#192.168.3.112:8848#1595486742278#1


2020-07-23 14:45:42,380 WARN Exception while request: http://192.168.3.110:8848/nacos/v1/ns/operator/cluster/state, caused: {}

java.net.ConnectException: 拒绝连接 (Connection refused)

**Comment by KomachiSion** [comment]
从日志来看，已经识别到了那个节点不健康，之后的请求转发和服务负责节点也会重新计算。看上去是没有问题的

**Comment by yyt6200** [comment]
但是这种因为节点和服务同时down的情况我的确是碰到过了。图片里的10.0.1.176是一个已经停止的容器实例

**Comment by KomachiSion** [comment]
当时的日志还在吗 查一下当时的naming-server ，看下有没有变更信息

**Comment by yyt6200** [comment]
在的，我查下

**Comment by yyt6200** [comment]
15号的日志不在了。。最早只有16号的了。。

**Comment by KomachiSion** [comment]
那就是一下刚才这样down掉之后，控制台是否还是3个节点可用。如果已经ok了，就等下次出现了 保留现场，然后再提issue。 这个issue可以先关了。

**Comment by yyt6200** [comment]
现在控制台是两个节点可用，都正常的

**Comment by yyt6200** [comment]
谢谢指导

**Comment by coolbeevip** [comment]
> 现在控制台是两个节点可用，都正常的

我也遇到过类似问题，你的问题解决了吗

**Comment by coolbeevip** [comment]
> 那就是一下刚才这样down掉之后，控制台是否还是3个节点可用。如果已经ok了，就等下次出现了 保留现场，然后再提issue。 这个issue可以先关了。

Hi，这个人问题我能够复现，并记录了日志，能帮我看看这个问题吗？https://github.com/alibaba/nacos/issues/4510
