### ISSUE TITLE
程序shutdown 后,不能退出进程

### ISSUE THREAD

**Issue by hsoftxl** [alibaba/nacos#3362]
2020-07-17 12:53:48.204 ERROR [pdf,,,] 34340 --- [.naming.updater] com.alibaba.nacos.client.naming          : request: /nacos/v1/ns/instance/list failed, servers: [192.168.1.251:8848], code: 500, msg: Connection pool shut down
2020-07-17 12:53:48.205 ERROR [pdf,,,] 34340 --- [.naming.updater] com.alibaba.nacos.client.naming          : [NA] failed to update serviceName: DEFAULT_GROUP@@seata-server

com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance/list after all servers([192.168.1.251:8848]) tried: java.lang.IllegalStateException: Connection pool shut down
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:552)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:330)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:397)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

2020-07-17 12:53:58.206 ERROR [pdf,,,] 34340 --- [.naming.updater] com.alibaba.nacos.client.naming          : [NA] failed to request

java.lang.IllegalStateException: Connection pool shut down
	at org.apache.http.util.Asserts.check(Asserts.java:34)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.requestConnection(PoolingHttpClientConnectionManager.java:269)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:176)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.alibaba.nacos.common.http.client.DefaultHttpClientRequest.execute(DefaultHttpClientRequest.java:54)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:330)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:319)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:599)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:330)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:397)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:264)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by zongtanghu** [comment]
"com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance/list after all servers([192.168.1.251:8848]) tried: java.lang.IllegalStateException: Connection pool shut down
"
看你贴的打印初以来的日志，看样子是client端去请求Nacos服务端，API接口—“/nacos/v1/ns/instance/list”，失败；你可以查看下Nacos的Server端服务是否正常？

**Comment by Maijh97** [comment]
与该问题相似 #3324 ，目前已经解决，可以先使用1.3.0或者1.2.1版本的客户端。
