### ISSUE TITLE
如何动态更新元数据

### ISSUE THREAD

**Issue by HuangDayu** [alibaba/nacos#3410]
目前有个需求，服务消费者要获取服务提供者的一个自定义标签的元数据的值，这个元数据的值是服务提供者动态刷新的。

**Comment by HuangDayu** [comment]
```java
com.netflix.appinfo.ApplicationInfoManagerobject.registerAppMetadata(Map<String, String>)
```
尝试通过eureka的方法进行赋值，但是无效。

**Comment by KomachiSion** [comment]
nacos本身是支持元数据变更的，但是spring-cloud-nacos-discovery可能没有实现。

**Comment by HuangDayu** [comment]
@KomachiSion 能否给个示例，谢谢。

**Comment by HuangDayu** [comment]
```java
nacosServiceRegistry.setStatus(nacosRegistration, "UP");
```
通过这个方法更新状态时，没有对groupName做出判断，调用的方法直接使用了默认的DEFAULT_GROUP，所以报了没有找到服务异常。

```xml
2020-07-22 15:47:23.036 ERROR 5756 --- [   scheduling-1] com.alibaba.nacos.client.naming          : request: /nacos/v1/ns/instance failed, servers: [127.0.0.1:8848], code: 500, msg: caused: service not found, namespace: public, service: DEFAULT_GROUP@@iot-service;
2020-07-22 15:47:23.051 ERROR 5756 --- [   scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.RuntimeException: update nacos instance status fail
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.setStatus(NacosServiceRegistry.java:132) ~[spring-cloud-starter-alibaba-nacos-discovery-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	at com.xx.iot.task.UpdateIotConnectedCountTask.timingUpdate(UpdateIotConnectedCountTask.java:81) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_91]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_91]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_91]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_91]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.1.8.RELEASE.jar:5.1.8.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308) [na:1.8.0_91]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_91]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_91]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_91]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_91]
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: caused: service not found, namespace: public, service: DEFAULT_GROUP@@iot-service;
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:496) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:401) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:397) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.updateInstance(NamingProxy.java:248) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingMaintainService.updateInstance(NacosNamingMaintainService.java:84) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingMaintainService.updateInstance(NacosNamingMaintainService.java:79) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.setStatus(NacosServiceRegistry.java:129) ~[spring-cloud-starter-alibaba-nacos-discovery-2.1.2.RELEASE.jar:2.1.2.RELEASE]
	... 15 common frames omitted
```

**Comment by KomachiSion** [comment]
nacos 控制台， 服务列表-》服务详情-》编辑服务-》输入元数据即可（json格式）

**Comment by worldlxy** [comment]
可以注入NacosRegistration实例操作元数据，

例如：
@Component
public class ServiceIDConfig {
    private NacosRegistration registration;
    private static String serviceId;

    public ServiceIDConfig(NacosRegistration registration) {
        this.registration = registration;
    }

    @PostConstruct
    public void initServiceInfo() {
        serviceId = UUID.randomUUID().toString();
        registration.getMetadata().put("serviceId", serviceId);
    }
}
