### ISSUE TITLE
kubernetes部署nacos集群的bug

### ISSUE THREAD

**Issue by qihaooo** [alibaba/nacos#3415]
## Issue Description

Type: *bug report* or *feature request*
关于kubernetes部署nacos集群的bug
### Describe what happened (or what feature you want)
1 在拉取官方部署脚本：https://github.com/nacos-group/nacos-k8s.git
2 使用快速部署的yaml，页面访问正常，如下图所示：
![image](https://user-images.githubusercontent.com/26671062/88149952-57672f80-cc33-11ea-9f68-a9760f276982.png)
3 在容器内部，三个节点总有一个节点会报如下的错误：
2020-07-22 14:31:10,171 WARN Exception while request: http://nacos-1.nacos-headless.default.svc.cluster.local.:8848/nacos/v1/ns/distro/datums, caused: {}

java.net.UnknownHostException: nacos-1.nacos-headless.default.svc.cluster.local.
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.alibaba.nacos.naming.misc.HttpClient.request(HttpClient.java:121)
	at com.alibaba.nacos.naming.misc.HttpClient.httpGet(HttpClient.java:95)
	at com.alibaba.nacos.naming.misc.NamingProxy.getAllData(NamingProxy.java:99)
	at com.alibaba.nacos.naming.consistency.ephemeral.distro.DistroConsistencyServiceImpl.syncAllDataFromRemote(DistroConsistencyServiceImpl.java:276)
	at com.alibaba.nacos.naming.consistency.ephemeral.distro.DistroConsistencyServiceImpl.load(DistroConsistencyServiceImpl.java:153)
	at com.alibaba.nacos.naming.consistency.ephemeral.distro.DistroConsistencyServiceImpl$LoadDataTask.run(DistroConsistencyServiceImpl.java:119)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-07-22 14:31:11,761 INFO receive config info: unknown#nacos-2.nacos-headless.default.svc.cluster.local.:8848#1595399471758#1

4 我通过dns工具发现我的域名能解析，但是问题出现在nacos容器内部的域名解析
![image](https://user-images.githubusercontent.com/26671062/88150253-bb89f380-cc33-11ea-903d-7159ecd81f11.png)

5 测试命令for i in 0 1 2; do echo nacos-$i; kubectl exec nacos-$i curl "http://localhost:8848/nacos/v1/ns/raft/state"; done
报如下错误：server is DOWN now, please try again later!

6 我的kubelet配置--cluster-domain=cluster.local. 
   所以在k8s的编排文件注入的环境变量加入后缀".",还是会出现上述的问题

### Describe what you expected to happen
希望能解如下错误：server is DOWN now, please try again later!

### How to reproduce it (as minimally and precisely as possible)
1. 部署k8s集群
2. 使用https://github.com/nacos-group/nacos-k8s.git的master分支，使用快速部署文件部署
3. 测试命令for i in 0 1 2; do echo nacos-$i; kubectl exec nacos-$i curl "http://localhost:8848/nacos/v1/ns/raft/state"; done

### Tell us your environment
kubernetes: 1.9.6
nacos: 1.3.0
mysql: 5.7
### Anything else we need to know?
在issue中看到有人发布类似的issue，好像没有解决答案，希望大佬帮忙一下

**Comment by JackSun-Developer** [comment]
I also met 'server is DOWN now, please try again later!' in standalone mode, and i deleted the directory ${user.home}/nacos/naming, the problem is then fixed. Hope this weak solution could help you...
I am finding the reason for this problem..

**Comment by kpioneer123** [comment]
```
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([nacos-headless:8848]) tried: ErrCode:503, ErrMsg:server is DOWN now, please try again later!
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:552) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:239) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:200) ~[nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:185) ~[nacos-client-1.3.3.jar:na]
	at io.seata.discovery.registry.nacos.NacosRegistryServiceImpl.register(NacosRegistryServiceImpl.java:85) ~[seata-discovery-nacos-1.5.0-SNAPSHOT.jar:na]
	at io.seata.core.rpc.netty.NettyServerBootstrap.start(NettyServerBootstrap.java:153) ~[seata-core-1.5.0-SNAPSHOT.jar:na]
	... 3 common frames omitted
```

**Comment by kpioneer123** [comment]
I have the same problem @KomachiSion

**Comment by KomachiSion** [comment]
The original problem is k8s pod can parse one hostname, he need to find out why his pod can parse this hostname.

@kpioneer123 your problem is lark to information to judge what's the problem. If you want get help, please open a new issue and provide your nacos-server logs.

**Comment by bigfacewo** [comment]
同样的问题 @KomachiSion，而且我们ping通nacos提供的域名
![image](https://user-images.githubusercontent.com/31603897/104094295-fc9dbf00-52ca-11eb-8a87-d87b64ebd62e.png)
![image](https://user-images.githubusercontent.com/31603897/104094314-38388900-52cb-11eb-8822-c6eba520ef15.png)
但是查看容器的运行日志：
![image](https://user-images.githubusercontent.com/31603897/104094362-7afa6100-52cb-11eb-9ace-876a80fa0000.png)
总是告诉我server is down，不知道这个问题咋解决。

**Comment by sundong1982** [comment]
我也是k8s遇到这个问题

**Comment by sawyerwu** [comment]
Finally I resolved it by updating "- name: NACOS_SERVERS" field in the nacos-quick-start.yaml.
```
- name: NACOS_SERVERS
        value: "nacos-0.nacos-headless.nacos.svc.cluster.local.:8848 nacos-1.nacos-headless.nacos.svc.cluster.local.:8848 nacos-2.nacos-headless.nacos.svc.cluster.local.:8848"
```

**Comment by bigfacewo** [comment]
> Finally I resolved it by updating "- name: NACOS_SERVERS" field in the nacos-quick-start.yaml.
> 
> ```
> - name: NACOS_SERVERS
>         value: "nacos-0.nacos-headless.nacos.svc.cluster.local.:8848 nacos-1.nacos-headless.nacos.svc.cluster.local.:8848 nacos-2.nacos-headless.nacos.svc.cluster.local.:8848"
> ```

Me too

**Comment by sawyerwu** [comment]
@bigfacewo Hi, can I ask what's your k8s version?

**Comment by bigfacewo** [comment]
> @bigfacewo Hi, can I ask what's your k8s version?

v1.15.11

**Comment by clannon** [comment]
不限于k8s，只要cluster.conf中配置了与当前主机名不一样的hostname就会出现，这显然是个bug，问题也非常容易复现，可以参考[#5222](https://github.com/alibaba/nacos/issues/5222#issuecomment-812397894)。但回复说是环境问题，然后让再去设置别的参数……

**Comment by Jesus-cl** [comment]
请问这种k8s环境部署集群，在本地注册服务的时候，server-addr应该配置什么？
使用nacos-0.nacos-headless.xxx.svc.cluster.local:8848 这样的域名地址是不行的，该填写什么样的地址呢

**Comment by bigfacewo** [comment]
应该不需要写前面的nacos-0吧，因为你用的是service的域名地址。

**Comment by Jesus-cl** [comment]
> 应该不需要写前面的nacos-0吧，因为你用的是service的域名地址。
本地代码配置是        server-addr: nacos-0.nacos-headless.bsc-passport.svc.cluster.local:8848,nacos-1.nacos-headless.bsc-passport.svc.cluster.local:8848,nacos-2.nacos-headless.bsc-passport.svc.cluster.local:8848

会报错：
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([nacos-0.nacos-headless.bsc-passport.svc.cluster.local:8848, nacos-1.nacos-headless.bsc-passport.svc.cluster.local:8848, nacos-2.nacos-headless.bsc-passport.svc.cluster.local:8848]) tried: failed to req API:nacos-2.nacos-headless.bsc-passport.svc.cluster.local:8848/nacos/v1/ns/instance. code:500 msg: java.net.SocketException: Unexpected end of file from server
看上去是心跳检测的时候有问题，连接不上这个地址，k8s使用了ingress，直接写暴露的域名地址也不行。
大佬有什么经验吗？

**Comment by hxy91819** [comment]
> Finally I resolved it by updating "- name: NACOS_SERVERS" field in the nacos-quick-start.yaml.
> 
> ```
> - name: NACOS_SERVERS
>         value: "nacos-0.nacos-headless.nacos.svc.cluster.local.:8848 nacos-1.nacos-headless.nacos.svc.cluster.local.:8848 nacos-2.nacos-headless.nacos.svc.cluster.local.:8848"
> ```

not working for me
