### ISSUE TITLE
后台一直轮询抛出异常，不影响服务调用，请问是哪里的问题，谢谢！

### ISSUE THREAD

**Issue by tankliu1980** [alibaba/nacos#3429]
后台一直轮询（30S）输出以下异常，网上检索配置了spring.cloud.nacos.config.server-addr地址后不应该启用endpoint的东西，可是我试了好多配置一直无效，请问是哪里的问题，谢谢，异常如下：
java.io.IOException: Error while requesting: http:///nacos/serverlist'. Server returned: 500
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServerListFromEndpoint(NamingProxy.java:142)
	at com.alibaba.nacos.client.naming.net.NamingProxy.refreshSrvIfNeed(NamingProxy.java:175)
	at com.alibaba.nacos.client.naming.net.NamingProxy.access$000(NamingProxy.java:60)
	at com.alibaba.nacos.client.naming.net.NamingProxy$2.run(NamingProxy.java:118)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at 

我的配置如下：
spring.cloud.nacos.config.server-addr=192.168.*.*:8848
spring.application.name=consumer-test
spring.cloud.nacos.discovery.server-addr=192.168.*.*:8848
server.port=8080
# 端点检查（健康检查）
management.endpoints.web.exposure.include= "*"

**Comment by KomachiSion** [comment]
提供下相关的版本信息

**Comment by tankliu1980** [comment]
nacos的版本是1.3，spring-cloud-starter-alibaba-nacos-config.jar的版本是0.1.1.RELEASE，spring-cloud-starter-alibaba-nacos-discovery.jar的版本是0.1.2.RELEASE

**Comment by KomachiSion** [comment]
可以试着更新一下spring-cloud-starter-alibaba的版本，我用2.2.1版本没有复现你的问题。

**Comment by KomachiSion** [comment]
@tankliu1980 any process?

**Comment by KomachiSion** [comment]
No response more than ** 7 days ** and I use new version can reproduce problem. I think it has fixed.
