### ISSUE TITLE
failed to create cache dir

### ISSUE THREAD

**Issue by zuonidelaowang** [alibaba/nacos#3479]
When starting the jar in the docker container, not used  root user, 
Cannot create cache directory or file

nacos-client 
1.3.1

java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at com.alibaba.nacos.client.naming.cache.DiskCache.write(DiskCache.java:59)
        at com.alibaba.nacos.client.naming.core.HostReactor.processServiceJson(HostReactor.java:211)
        at com.alibaba.nacos.client.naming.core.PushReceiver.run(PushReceiver.java:89)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

[NA] failed to backup file on startup.java.lang.IllegalStateException: failed to create cache dir: /data/webs/failover
        at com.alibaba.nacos.client.naming.backups.FailoverReactor$2.run(FailoverReactor.java:100)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Comment by horizonzy** [comment]
NacosNamingService need local cache file to persist instanceInfo.and the default dir is user.home/nacos/naming/{namespace}/xxx
two way to resolve it:
1.make sure the program's run permission can create file at the default dir
2.add the system property (key=com.alibaba.nacos.naming.cache.dir),the value is your custom dir,you just set the dir where you have create permission

**Comment by KomachiSion** [comment]
`Permission denied` the error is very obvious. Solution just like @horizonzy said.

**Comment by zuonidelaowang** [comment]
I found the problem.
app run in docker, not use root user starts jar
 
`System.getProperties().getProperty("user.home") return "?"`

the user.home directory was not found.
so nacos log write error

Didn't find the reason, why did user.home return "?"

**Comment by KomachiSion** [comment]
Please check your docker env set. It's not nacos' problem, close issue.
