### ISSUE TITLE
 failed to update serviceName

### ISSUE THREAD

**Issue by lizhichao999** [alibaba/nacos#3491]
2020-07-31 16:05:11,965 110959467 [com.alibaba.nacos.client.naming.updater] ERROR c.a.n.c.naming.core.HostReactor[] - [NA] failed to update serviceName: DEFAULT_GROUP@@xxx
java.lang.IllegalArgumentException: bound must be positive
	at java.util.Random.nextInt(Random.java:388)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:476)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:412)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:408)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:336)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:283)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:329)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

客户端运行一段时间，报这块错，导致服务列表找不到注册的服务（无缘无故下线），http请求不到 nacos 1.2版本

**Comment by lizhichao999** [comment]
修改源码导致
