### ISSUE TITLE
(File name too long)

### ISSUE THREAD

**Issue by ChinaJeckXu** [alibaba/nacos#3605]
**Describe the bug**
多个nacos节点(3个), 配置中心地址叠加自定义namespace 之后字符过长, 导致程序启动时保存本地配置快照文件名称太长无法保存

Multiple nacos nodes (3), after the configuration center address is superimposed on the custom namespace, the characters are too long, causing the local configuration snapshot file name to be too long to save when the program starts

**Desktop (please complete the following information):**
 - OS: [Centos7.6, Docker CE 19.03.5, Kubernetes 1.18.0]
 - Version [nacos-server 1.3.2, nacos-client 1.3.2]
 - Module [config]
 - SDK [com.alibaba.nacos-nacos-client]

**Additional context**

```
2020-08-14 03:19:59.025 ERROR 1 --- [      elastic-7] c.a.n.c.c.impl.LocalConfigInfoProcessor  : [fixed-magical-nacos-server-0.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-1.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-2.magical-nacos-headless.default.svc.cluster.local_8848-d96ed582-904a-451d-9f56-34b31626a1cc] save snapshot error
2020-08-14 03:19:59.027 ERROR 1 --- [      elastic-7] c.a.n.c.c.impl.LocalConfigInfoProcessor  : [fixed-magical-nacos-server-0.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-1.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-2.magical-nacos-headless.default.svc.cluster.local_8848-d96ed582-904a-451d-9f56-34b31626a1cc] save snapshot error, /root/nacos/config/fixed-magical-nacos-server-0.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-1.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-2.magical-nacos-headless.default.svc.cluster.local_8848-d96ed582-904a-451d-9f56-34b31626a1cc_nacos/snapshot-tenant/d96ed582-904a-451d-9f56-34b31626a1cc/SENTINEL_FLOW_TEST_GROUP/magical-gateway-Sentinel
java.io.FileNotFoundException: /root/nacos/config/fixed-magical-nacos-server-0.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-1.magical-nacos-headless.default.svc.cluster.local_8848-magical-nacos-server-2.magical-nacos-headless.default.svc.cluster.local_8848-d96ed582-904a-451d-9f56-34b31626a1cc_nacos/snapshot-tenant/d96ed582-904a-451d-9f56-34b31626a1cc/SENTINEL_FLOW_TEST_GROUP/magical-gateway-Sentinel (File name too long)
	at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_202]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_202]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_202]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_202]
	at com.alibaba.nacos.common.utils.IoUtils.writeStringToFile(IoUtils.java:121) ~[nacos-common-1.3.2.jar!/:na]
	at com.alibaba.nacos.client.config.impl.LocalConfigInfoProcessor.saveSnapshot(LocalConfigInfoProcessor.java:132) ~[nacos-client-1.3.2.jar!/:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:309) [nacos-client-1.3.2.jar!/:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:149) [nacos-client-1.3.2.jar!/:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:97) [nacos-client-1.3.2.jar!/:na]
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.readSource(NacosDataSource.java:141) [sentinel-datasource-nacos-1.7.1.jar!/:na]
	at com.alibaba.csp.sentinel.datasource.nacos.NacosDataSource.readSource(NacosDataSource.java:42) [sentinel-datasource-nacos-1.7.1.jar!/:na]
	at com.alibaba.csp.sentinel.datasource.AbstractDataSource.loadConfig(AbstractDataSource.java:44) [sentinel-datasource-extension-1.7.1.jar!/:na]
	at com.alibaba.cloud.sentinel.endpoint.SentinelHealthIndicator.doHealthCheck(SentinelHealthIndicator.java:128) [spring-cloud-starter-alibaba-sentinel-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.boot.actuate.health.AbstractHealthIndicator.health(AbstractHealthIndicator.java:82) [spring-boot-actuator-2.1.16.RELEASE.jar!/:2.1.16.RELEASE]
	at org.springframework.boot.actuate.health.HealthIndicatorReactiveAdapter.invoke(HealthIndicatorReactiveAdapter.java:48) [spring-boot-actuator-2.1.16.RELEASE.jar!/:2.1.16.RELEASE]
	at org.springframework.boot.actuate.health.HealthIndicatorReactiveAdapter.lambda$null$0(HealthIndicatorReactiveAdapter.java:43) [spring-boot-actuator-2.1.16.RELEASE.jar!/:2.1.16.RELEASE]
	at reactor.core.scheduler.ElasticScheduler$DirectScheduleTask.run(ElasticScheduler.java:292) ~[reactor-core-3.2.19.RELEASE.jar!/:3.2.19.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:50) ~[reactor-core-3.2.19.RELEASE.jar!/:3.2.19.RELEASE]
	at reactor.core.scheduler.SchedulerTask.call(SchedulerTask.java:27) ~[reactor-core-3.2.19.RELEASE.jar!/:3.2.19.RELEASE]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_202]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_202]
```

**Comment by KomachiSion** [comment]
The env_name is too long. And the env_name is merged by server list. Your server list is hostName and hostName is long so that the path is too long.

How can we solve this problem? Any idea from community?

**Comment by ChinaJeckXu** [comment]
I personally think that the hostname can be replaced with the LAN IP of the container itself, so as to avoid the hostname being too long

**Comment by KomachiSion** [comment]
If user set hostname, we need to use hostname, because it can cover the information of changing of IP.

**Comment by realhm** [comment]
Is it appropriate to add a optional configuration item which can be defined by users themselves?

**Comment by ChinaJeckXu** [comment]
> Is it appropriate to add a optional configuration item which can be defined by users themselves?

In terms of usability, it needs to be done.

**Comment by horizonzy** [comment]
> The env_name is too long. And the env_name is merged by server list. Your server list is hostName and hostName is long so that the path is too long.
> 
> How can we solve this problem? Any idea from community?

Just add a workaround to solve it. Add a propertity. if configed, use md5 that transfered from name to replace it.
