### ISSUE TITLE
/actuator/health提示服务状态为down，但nacos控制台服务状态为健康

### ISSUE THREAD

**Issue by zhujiebing** [alibaba/nacos#3618]
**Which Component**
Nacos Discovery

**Describe what problem you have encountered**
在服务运行过程中，在nacos控制台配置管理修改为错误的jdbc连接，模拟服务异常。  此时spring boot admin提示服务已处于down的状态。但是nacos服务列表里面状态还是健康的。 且这个服务的接口还可以正常调用。
nacos的服务健康检查只需要客户端一直保持心跳就行吗？跟/actuator/health检查是否不一致。辛苦答疑。谢谢。
![image](https://user-images.githubusercontent.com/25639514/90365423-51c90200-e098-11ea-9b3e-33375eb0b1d8.png)
![image](https://user-images.githubusercontent.com/25639514/90365446-5beb0080-e098-11ea-8290-de87db6c4550.png)
![image](https://user-images.githubusercontent.com/25639514/90365468-63120e80-e098-11ea-8e30-06e89a3ddb58.png)
![image](https://user-images.githubusercontent.com/25639514/90365481-6a391c80-e098-11ea-8415-f558a5076d77.png)
![image](https://user-images.githubusercontent.com/25639514/90365498-702efd80-e098-11ea-89ae-b794d639ead4.png)

**Describe what information you have read**
spring cloud alibaba 2.2.1.RELEASE；spring cloud Hoxton.SR1；spring boot 2.2.2.RELEASE; nacos server是linux外置mysql 1.3.1集群三个节点 ;

```java
<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.alibaba.nacos</groupId>
					<artifactId>nacos-client</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
			<exclusions>
				<exclusion>
					<groupId>com.alibaba.nacos</groupId>
					<artifactId>nacos-client</artifactId>
				</exclusion>
			</exclusions>
		</dependency>
		<dependency>
			<groupId>com.alibaba.nacos</groupId>
			<artifactId>nacos-client</artifactId>
                         <version>1.3.1</version>
		</dependency>
```

**Comment by KomachiSion** [comment]
非持久化实例，目前通过心跳上报来确认健康状态，如果实例心跳上报一直正常，但是接口本身存在异常，nacos目前是检测不出来的。

持久化实例可以通过设置主动探测的方式，但是并不确认语义。比如您这个检测接口，通过返回的内容是up还是down区分，这个相当于定制需求。
之后不排除会优化开放自定义接口来探测，但是目前没有。

**Comment by zhujiebing** [comment]
> 非持久化实例，目前通过心跳上报来确认健康状态，如果实例心跳上报一直正常，但是接口本身存在异常，nacos目前是检测不出来的。
> 
> 持久化实例可以通过设置主动探测的方式，但是并不确认语义。比如您这个检测接口，通过返回的内容是up还是down区分，这个相当于定制需求。
> 之后不排除会优化开放自定义接口来探测，但是目前没有。

对比了一下consul和eureka注册中心，consul或者eureka client端是通过配置healthCheckPath: /actuator/health或者healthcheck:  
          enabled: true来检查实例状态。实际上都是通过spring-boot-actuator模块的/health端点来监控。这样应用程序就会将自己的健康状态传播到consul或者eureka Sever。

**Comment by KomachiSion** [comment]
肯定有调研对比过，但是目前没有朝这个方向走有2个原因：
1. 通过自定义方式来检测实例状态已经有这个功能，持久化实例就是通过主动探测的方式进行，但是只测试连通性，不测试内容。
2. 通过自定义方式探测，如果需要感知内容变化，那么需要完全形成标准，比如UP代表可用，DOWN代表不可用，spring-boot-actuator是这样的，但是可能并不是所有用户都是这样。eureka完全服务于spring-cloud，那么作为spring全家桶，这么做自然无可厚非；因此目前nacos只能通过探测联通性来检测。

后续肯定不排除添加这种自定义接口来探测。

**Comment by zhujiebing** [comment]
@KomachiSion     生产环境刚好遇到一个这样的场景，某一个服务出现了OOM，经过排查大致过程如下，当时/actuator/health返回了down，OOM导致实例无法给nacos server端正常上报心跳，nacos服务列表踢除了这个服务。  过了一段时间内存回收，服务恢复正常，/actuator/health又恢复为up状态。  但此时服务已经不在nacos服务列表，没办法继续提供服务。     感谢答疑。

**Comment by KomachiSion** [comment]
可以继续排查，
1. 抓包看下是否客户端的确没有给服务端发心跳。
2. 看下是否是OOM把心跳上报的Task给清理掉了，可以查看nacos客户端日志，看看有没有`[CLIENT-BEAT]`相关的失败日志，或者dump一下线程，看下`com.alibaba.nacos.naming.beat.sender`线程是否一直没有工作。

**Comment by zhujiebing** [comment]
```java
2020-08-20 15:52:19,442 [com.alibaba.nacos.naming.beat.sender] ERROR [com.alibaba.nacos.client.naming] NamingProxy.java:491 - request: /nacos/v1/ns/instance/beat failed, servers: [nacos1.com:8848, nacos2.com:8848, nacos3.com:8848], code: 500, msg: java.net.SocketTimeoutException
2020-08-20 15:52:31,123 [com.alibaba.nacos.naming.beat.sender] ERROR [com.alibaba.nacos.client.naming] BeatReactor.java:139 - [CLIENT-BEAT] failed to send beat: {"port":18013,"ip":"172.1.1.129","weight":1.0,"serviceName":"prod@@cvnavi-tsp-external-call","cluster":"DEFAULT","metadata":{"preserved.register.source":"SPRING_CLOUD"},"scheduled":false,"period":5000,"stopped":false}, code: 500, msg: failed to req API:/nacos/v1/ns/instance/beat after all servers([nacos1.com:8848, nacos2.com:8848, nacos3.com:8848]) tried: java.net.SocketTimeoutException
2020-08-20 15:52:38,754 [com.alibaba.nacos.client.naming.updater] ERROR [com.alibaba.nacos.client.naming] HttpClient.java:102 - [NA] failed to request 
java.net.SocketTimeoutException: null
	at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:86)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:432)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:400)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:396)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:321)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:282)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-08-20 15:53:14,982 [com.alibaba.nacos.client.naming.updater] ERROR [com.alibaba.nacos.client.naming] HttpClient.java:102 - [NA] failed to request 
java.net.SocketTimeoutException: null
	at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:86)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:432)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:400)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:396)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:321)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:282)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:330)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2020-08-20 15:54:35,945 [com.alibaba.nacos.naming.beat.sender] ERROR [com.alibaba.nacos.client.naming] HttpClient.java:102 - [NA] failed to request 
java.net.SocketTimeoutException: null
	at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:606)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:86)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:432)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:400)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:396)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:213)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:133)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by KomachiSion** [comment]
这OOM恢复了吗？ 我感觉没有恢复吧。感觉还一直处于FullGC的状态，所以一直没有办法上报心跳。

**Comment by zhujiebing** [comment]
@KomachiSion  OOM确认恢复了。 api正常可以访问的，但是/bin/logs/下的access_log.log没有再出现beat日志，  client端也没有再出现beat异常的日志。

**Comment by KomachiSion** [comment]
有dump当时的线程现场吗？ 得看一下是线程不工作了还是beat信息没了。
