### ISSUE TITLE
nacos1.3.2单机服务器上注册报错

### ISSUE THREAD

**Issue by vowor** [alibaba/nacos#3629]
nacos版本：1.3.2
部署模式：单机
数据库：MySQL
部署系统：Centos 7.2
部署启动命令：./startup.sh -m standalone
本机系统：windows10
问题：
    本机启动nacos，Spring cloud注册本机的nacos不会报错可以正常注册，注册到服务器上的nacos注册时报错。
项目报错信息：

```
2020-08-18 17:16:51.118 ERROR 2024 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : request: /nacos/v1/ns/instance/beat failed, servers: [rate-register:8848], code: 500, msg: Connection reset
2020-08-18 17:16:51.119 ERROR 2024 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : [CLIENT-BEAT] failed to send beat: {"port":22000,"ip":"192.168.3.115","weight":1.0,"serviceName":"DEFAULT_GROUP@@rate-gateway","cluster":"DEFAULT","metadata":{"preserved.register.source":"SPRING_CLOUD"},"scheduled":false,"period":5000,"stopped":false}, code: 500, msg: failed to req API:/nacos/v1/ns/instance/beat after all servers([rate-register:8848]) tried: java.net.SocketException: Connection reset
2020-08-18 17:16:56.172 ERROR 2024 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : [NA] failed to request

java.net.SocketException: Connection reset

naming-server.log 日志信息：
2020-08-18 17:19:13,828 INFO [DEAD-SERVICE] {"name":"DEFAULT_GROUP@@rate-gateway","protectThreshold":0.0,"groupName":"DEFAULT_GROUP","metadata":{},"finalizeCount":5,"owners":[],"resetWeight":false,"enabled":true,"selector":{"type":"none"},"namespaceId":"public","ipDeleteTimeout":30000,"lastModifiedMillis":1597742221200,"checksum":"9c11d47040d38f7ce9101d03ede545cd","clusterMap":{"DEFAULT":{"serviceName":"DEFAULT_GROUP@@rate-gateway","name":"DEFAULT","healthChecker":{"type":"TCP"},"defaultPort":80,"defaultCheckPort":80,"useIPPort4Check":true,"metadata":{},"sitegroup":"","defCkport":80,"defIPPort":80,"empty":true}},"empty":true}

2020-08-18 17:40:19,591 ERROR [HEALTH-CHECK] error while processing NIO task

java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(AbstractQueuedSynchronizer.java:2088)
	at java.util.concurrent.LinkedBlockingQueue.poll(LinkedBlockingQueue.java:467)
	at com.alibaba.nacos.naming.healthcheck.TcpSuperSenseProcessor.processTask(TcpSuperSenseProcessor.java:137)
	at com.alibaba.nacos.naming.healthcheck.TcpSuperSenseProcessor.run(TcpSuperSenseProcessor.java:154)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by KomachiSion** [comment]
network problem. Please check network config, firewall settings.

**Comment by vowor** [comment]
> network problem. Please check network config, firewall settings.

可能不是网络问题吧，防火墙是关的   Nacos平台界面也能打开进去，配置中心的配置Spring Cloud也能正常读取，只有注册失败，而且看报错内容，好像返回的错误码是500

**Comment by vowor** [comment]
> network problem. Please check network config, firewall settings.

嗯，是被防火墙拦截了，我们这里有物理防火墙，物理防火墙默认只允许常用的get/post请求能正常使用，其它类型的请求就被拦截了，使用fiddler抓包发现服务注册用的是PUT请求，所以拦截了，让网管把服务器IP加入到防火墙白名单就没有问题了。
