### ISSUE TITLE
“Address already in use: connect”--Nacos use too many port

### ISSUE THREAD

**Issue by cookier** [alibaba/nacos#3640]
三天前使用dubbo+nacos搭建项目，运行正常，中间有过重启项目也没问题。但是今天再重启项目时出现问题，启动失败，查看日记发现大量异常，提示地址已被使用`Address already in use: connect`。
```
[message] 2020-08-19 10:12:00,693 - com.alibaba.nacos.client.naming -278896 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming  - [NA] failed to update serviceName: DEFAULT_GROUP@@providers:com.xxx.Provider::
ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/instance/list after all servers([127.0.0.1:8848]) tried: java.net.BindException: Address already in use: connect
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:552)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:330)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:397)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[message] 2020-08-19 10:12:00,700 - com.alibaba.nacos.client.naming -278903 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming  - [NA] failed to request
java.net.BindException: Address already in use: connect
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
```
检查本机端口使用情况，发现nacos竟然占用了1W+的端口。
```
 TCP    127.0.0.1:49152        activate:8848          TIME_WAIT
 TCP    127.0.0.1:*******        activate:8848          TIME_WAIT
 TCP    127.0.0.1:65535        activate:8848          TIME_WAIT
```
在重启nacos服务后，端口并没有释放，一直占用着，请问这种情况可能会是什么原因？
我猜测是项目使用 nacos 注册发现服务时，一直在建立新的 http 链接，同时旧链接没有过期，导致端口不断被占用。
不知道具体该如何解决，升级 dubbo 版本也没用。

相关环境：
OS: windows10
jdk java8
dubbo: apache dubbo 2.7.5
nacos: 1.3.2

**Comment by KomachiSion** [comment]
TIME_WAIT 是tcp层面的状态，意思是已经发起关闭的连接 接收到对端的回包 之后 还会存在一段时间才会CLOSE。

**Comment by KomachiSion** [comment]
不过这个数量级还是有点夸张的，还是需要排查一下

**Comment by chuntaojun** [comment]
> 不过这个数量级还是有点夸张的，还是需要排查一下

排查下common的http模块对于java.http的使用

**Comment by Maijh97** [comment]
@cookier 麻烦可以贴一下完整pom文件吗？

**Comment by cookier** [comment]
> @cookier 麻烦可以贴一下完整pom文件吗？

我是改造旧项目(传统spring结构)，将`dubbo+zk`改为`dubbo+nacos`，包含十几个独立的子模块，所以pom文件很复杂，全贴出来可能理不清。就贴一下改动和引入的依赖部分吧，如果还想看哪些依赖可以说一下。
```
			<dependency>
				<groupId>org.apache.dubbo</groupId>
				<artifactId>dubbo</artifactId>
				<version>2.7.7</version>
			</dependency>
			<dependency>
				<groupId>org.apache.dubbo</groupId>
				<artifactId>dubbo-registry-nacos</artifactId>
				<version>2.7.7</version>
			</dependency>
			<dependency>
				<groupId>com.alibaba.nacos</groupId>
				<artifactId>nacos-client</artifactId>
				<version>1.3.2</version>
			</dependency>

			<dependency>
				<groupId>org.apache.curator</groupId>
				<artifactId>curator-framework</artifactId>
				<version>2.12.0</version>
			</dependency>
			<dependency>
				<groupId>org.apache.curator</groupId>
				<artifactId>curator-recipes</artifactId>
				<version>2.12.0</version>
			</dependency>
```
其他基本没有变化，因为只改动注册中心，后面又将`dubbo`升级至`2.7.7`测试。
昨天重启电脑，再次运行项目，经过多次重启测试，目前端口占用2K+。
[nacos依赖](https://ftp.bmp.ovh/imgs/2020/08/39c30cdfa94aaab9.png)
[端口占用](https://ftp.bmp.ovh/imgs/2020/08/0642c6e9dc608aa6.png)

**Comment by Maijh97** [comment]
@cookier 方便留一下钉钉号码吗？想和你仔细沟通一下这个问题

**Comment by cookier** [comment]
> @cookier 方便留一下钉钉号码吗？想和你仔细沟通一下这个问题

你好，钉钉号：chinaq

**Comment by KomachiSion** [comment]
TIME_WAIT其实是资源已经释放，等待系统回收了，占了一万多端口我推测是因为客户端服务端都在一台机器上，所以客户端服务端都占用端口导致的。 根据我自己的压测，并发在数百tps时，tcp连接占用也不会超过4000（版本1.3.2）
因此如果只是本地测试，建议不要大面积测试，只做一下基本的功能验证。
