### ISSUE TITLE
Param 'beat' is required

### ISSUE THREAD

**Issue by beetle-p** [alibaba/nacos#3664]
com.alibaba.nacos.api.exception.NacosException: Param 'beat' is required.
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:611)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)

path:
com/alibaba/nacos/naming/controllers/InstanceController.java

**in version 1.1.3, the "beat" parameter checked is as follows:** 
在1.1.3版本中，beat参数通过如下方法校验
in server:

```
         String beat = WebUtils.required(request, "beat")
```

in client:

```
        if (NAMING_LOGGER.isDebugEnabled()) {
             NAMING_LOGGER.debug("[BEAT] {} sending beat to server: {}", namespaceId, beatInfo.toString());
        }
        Map<String, String> params = new HashMap<String, String>(4);
        params.put("beat", JSON.toJSONString(beatInfo));
        params.put(CommonParams.NAMESPACE_ID, namespaceId);
        params.put(CommonParams.SERVICE_NAME, beatInfo.getServiceName());
        String result = reqAPI(UtilAndComs.NACOS_URL_BASE + "/instance/beat", params, HttpMethod.PUT);

```

**in version 1.1.3, the "beat" parameter checked is as follows:**
在1.3.1版本中，beat参数通过如下方法校验
in server:

```
        String beat = WebUtils.optional(request, "beat", StringUtils.EMPTY);
```

in client:

```
        Map<String, String> params = new HashMap<String, String>(8);
        Map<String, String> bodyMap = new HashMap<String, String>(2);
        if (!lightBeatEnabled) {
            bodyMap.put("beat", JacksonUtils.toJson(beatInfo));
        }
        params.put(CommonParams.NAMESPACE_ID, namespaceId);
        params.put(CommonParams.SERVICE_NAME, beatInfo.getServiceName());
        params.put(CommonParams.CLUSTER_NAME, beatInfo.getCluster());
        params.put("ip", beatInfo.getIp());
        params.put("port", String.valueOf(beatInfo.getPort()));
        String result = reqApi(UtilAndComs.nacosUrlBase + "/instance/beat", params, bodyMap, HttpMethod.PUT);

```

Version: nacos-server 1.1.3 nacos-client 1.3.1

Is it possible to do parameter compatibility？
是否可以做一下参数兼容

**Comment by KomachiSion** [comment]
可以逐台灰度升级。

**Comment by KomachiSion** [comment]
@beetle-p 1.3.2 客户端关闭轻量心跳功能，应该是可以支持的
