### ISSUE TITLE
nacos在项目启动一段时间后（10分钟左右），报心跳连接超时的错误

### ISSUE THREAD

**Issue by zhouzhiy** [alibaba/nacos#3683]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
2020-08-25 16:18:50,963 - failed to request http://127.0.0.1:8848/nacos/v1/ns/instance/beat?app=unknown&namespaceId=public&port=8766&clusterName=DEFAULT&ip=10.21.6.2&serviceName=DEFAULT_GROUP%40%40platform-app&encoding=UTF-8 from 127.0.0.1
2020-08-25 16:18:50,965 - [NA] failed to request 
java.net.SocketTimeoutException: connect timed out
	at java.net.DualStackPlainSocketImpl.waitForConnect(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:85)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:86)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:427)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:462)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:395)
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:337)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:108)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### How to reproduce it (as minimally and precisely as possible)

1. 启动项目
2. 等10分钟
3. 控制台报错

### Tell us your environment
spring-cloud-alibaba-dependencies:2.2.0.RELEASE
nacos-client:1.2.0
nacos-server:1.3.0

**Comment by KomachiSion** [comment]
There are many reasons for `connect timed out`. Such as firewall, network, Full GC of server.

Your information is not enough to judge what's the reason. So can you provide more information? Such as nacos_gc log?

**Comment by zhouzhiy** [comment]
一定要保证服务和注册中心间的网络良好，最好放在同一内网，不然就报上边的错，时不时的来一下
