### ISSUE TITLE
nacos 1.3.2 集成的dubbo 消费端自动报错但是可以正常使用

### ISSUE THREAD

**Issue by madongbao** [alibaba/nacos#3799]
org.apache.http.impl.execchain.RequestAbortedException: Request execution failed
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:199) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.12.jar:4.5.12]
	at com.alibaba.nacos.common.http.client.DefaultHttpClientRequest.execute(DefaultHttpClientRequest.java:54) ~[nacos-common-1.3.1.jar:na]
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:330) ~[nacos-common-1.3.1.jar:na]
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:319) ~[nacos-common-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:599) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:330) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:397) [nacos-client-1.3.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: java.util.concurrent.CancellationException: Operation aborted
	at org.apache.http.pool.AbstractConnPool.operationAborted(AbstractConnPool.java:182) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.pool.AbstractConnPool.access$200(AbstractConnPool.java:70) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:251) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:198) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:306) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:282) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190) ~[httpclient-4.5.12.jar:4.5.12]
	... 24 common frames omitted

![image](https://user-images.githubusercontent.com/33247803/92716842-f5ed5280-f391-11ea-984d-c8cc152f110f.png)
循环的报错

**Comment by Maijh97** [comment]
@madongbao 你这个nacos-client不是1.3.2版本的把

**Comment by madongbao** [comment]
> @madongbao 你这个nacos-client不是1.3.2版本的把

1.3.1 的  我升级下试试

**Comment by madongbao** [comment]
> nacos-client

![image](https://user-images.githubusercontent.com/33247803/92719766-3bac1a00-f396-11ea-8e64-46d8e71420cd.png)
已经全部升级了   mvn dependency:tree 已经确认过

**Comment by Maijh97** [comment]
![image](https://user-images.githubusercontent.com/37288946/92719906-701fd600-f396-11ea-8f23-2027a3aef248.png)
这里还是1.3.1版本的

**Comment by madongbao** [comment]
> ![image](https://user-images.githubusercontent.com/37288946/92719906-701fd600-f396-11ea-8f23-2027a3aef248.png)
> 这里错误日志显示还是1.3.1版本的哦。

😵

**Comment by Maijh97** [comment]
或者可以提供一下pom文件的截图 @madongbao

**Comment by madongbao** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.3.RELEASE</version>
        <relativePath/> 
    </parent>
    <groupId>cn.raretime</groupId>
    <artifactId>time-manager</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <packaging>pom</packaging>
    <modules>
        <module>time-manager-service</module>
        <module>time-manager-m</module>
        <module>time-manager-web</module>
        <module>time-manager-api</module>
        <module>time-manager-base</module>
    </modules>
    <properties>
        <java.version>1.8</java.version>
        <druid.version>1.1.10</druid.version>
        <lombok.version>1.18.12</lombok.version>
        <dubbo.version>2.7.8</dubbo.version>
        <time-manager-api.version>0.0.1-SNAPSHOT</time-manager-api.version>
        <time-manager-base.version>1.0.0-SNAPSHOT</time-manager-base.version>
        <spring-cloud.alibaba.version>2.2.1.RELEASE</spring-cloud.alibaba.version>
        <nacos.client.version>1.3.2</nacos.client.version>
        <spring-cloud.alibaba.sms.version>2.1.1.RELEASE</spring-cloud.alibaba.sms.version>
        <spring-cloud.alibaba.oss.version>2.2.0.RELEASE</spring-cloud.alibaba.oss.version>
        <dubbo-registry-nacos.version>2.7.8</dubbo-registry-nacos.version>
        <mybatis-plus.version>3.4.0</mybatis-plus.version>
        <hutool.version>5.4.2</hutool.version>
        <jedis.version>2.9.0</jedis.version>
        <ali.sms.version>4.5.7</ali.sms.version>
    </properties>
    <dependencyManagement>
        <dependencies>
            
            <dependency>
                <groupId>cn.raretime</groupId>
                <artifactId>time-manager-api</artifactId>
                <version>${time-manager-api.version}</version>
            </dependency>
            <dependency>
                <groupId>cn.raretime</groupId>
                <artifactId>time-manager-base</artifactId>
                <version>${time-manager-base.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.alibaba</groupId>
                <artifactId>druid-spring-boot-starter</artifactId>
                <version>${druid.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.auth0</groupId>
                <artifactId>java-jwt</artifactId>
                <version>3.10.3</version>
            </dependency>
            
            <dependency>
                <groupId>com.github.pagehelper</groupId>
                <artifactId>pagehelper-spring-boot-starter</artifactId>
                <version>1.2.13</version>
            </dependency>
            
            <dependency>
                <groupId>com.github.binarywang</groupId>
                <artifactId>weixin-java-mp</artifactId>
                <version>3.9.0</version>
            </dependency>
            
            <dependency>
                <groupId>org.projectlombok</groupId>
                <artifactId>lombok</artifactId>
                <version>${lombok.version}</version>
            </dependency>
            
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-spring-boot-starter</artifactId>
                <version>${dubbo.version}</version>
            </dependency>
            
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-registry-nacos</artifactId>
                <version>${dubbo-registry-nacos.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.alibaba.nacos</groupId>
                        <artifactId>nacos-client</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
                <version>${spring-cloud.alibaba.version}</version>
                <exclusions>
                    <exclusion>
                        <groupId>com.alibaba.nacos</groupId>
                        <artifactId>nacos-client</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            
            <dependency>
                <groupId>com.alibaba.nacos</groupId>
                <artifactId>nacos-client</artifactId>
                <version>${nacos.client.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
                <version>${spring-cloud.alibaba.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alibaba-sentinel</artifactId>
                <version>${spring-cloud.alibaba.version}</version>
                <exclusions>
                    <exclusion>
                        <artifactId>jackson-dataformat-xml</artifactId>
                        <groupId>com.fasterxml.jackson.dataformat</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
            
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alicloud-sms</artifactId>
                <version>${spring-cloud.alibaba.sms.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-starter-alicloud-oss</artifactId>
                <version>${spring-cloud.alibaba.oss.version}</version>
            </dependency>
            
            <dependency>
                <groupId>com.baomidou</groupId>
                <artifactId>mybatis-plus-generator</artifactId>
                <version>${mybatis-plus.version}</version>
            </dependency>
            <dependency>
                <groupId>org.freemarker</groupId>
                <artifactId>freemarker</artifactId>
                <version>2.3.29</version>
            </dependency>
            <dependency>
                <groupId>mysql</groupId>
                <artifactId>mysql-connector-java</artifactId>
                <version>8.0.21</version>
            </dependency>
            
            <dependency>
                <groupId>cn.hutool</groupId>
                <artifactId>hutool-all</artifactId>
                <version>${hutool.version}</version>
            </dependency>
            
            <dependency>
                <groupId>redis.clients</groupId>
                <artifactId>jedis</artifactId>
                <version>${jedis.version}</version>
            </dependency>
        </dependencies>
    </dependencyManagement>

    
    <repositories>
        <repository>
            <id>public</id>
            <name>aliyun nexus</name>
            <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>public</id>
            <name>aliyun nexus</name>
            <url>http://maven.aliyun.com/nexus/content/groups/public/</url>
            <releases>
                <enabled>true</enabled>
            </releases>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </pluginRepository>
    </pluginRepositories>
</project>

**Comment by madongbao** [comment]
> 可以提供一下pom文件的截图 帮你看一下@madongbao

![image](https://user-images.githubusercontent.com/33247803/92720420-28e61500-f397-11ea-817c-77641381a1df.png)
![image](https://user-images.githubusercontent.com/33247803/92720435-2d123280-f397-11ea-9013-3f2ff5d830fe.png)
![image](https://user-images.githubusercontent.com/33247803/92720448-326f7d00-f397-11ea-9183-e3ac64f4e4b0.png)
![image](https://user-images.githubusercontent.com/33247803/92720460-369b9a80-f397-11ea-847e-4bbd0f04b26b.png)
![image](https://user-images.githubusercontent.com/33247803/92720475-3ac7b800-f397-11ea-88b1-8030be6ef470.png)

**Comment by Maijh97** [comment]
pom文件没有错的哦，执行一下mvn install试试？

**Comment by madongbao** [comment]
> com.alibaba.cloud
> spring-cloud-starter-alibaba-nacos-config
> 也exclusion看看？

好的！我再试试

**Comment by madongbao** [comment]
> com.alibaba.cloud
> spring-cloud-starter-alibaba-nacos-config
> 也exclusion看看？

可以了感谢
