### ISSUE TITLE
no available server, currentServerAddr

### ISSUE THREAD

**Issue by lambert0529** [alibaba/nacos#3802]
```[20200911 122346 636][ERROR][com.alibaba.nacos.client.Worker.longPolling.fixed-172.17.101.101_8848-riverrace][com.alibaba.nacos.client.Worker.longPolling.fixed-172.17.101.101_8848-river][com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost][159]:[NACOS SocketTimeoutException httpPost] currentServerAddr: http://172.17.101.101:8848， err : Read timed out
[20200911 122349 879][ERROR][com.alibaba.nacos.client.Worker.longPolling.fixed-172.17.101.101_8848-riverrace][com.alibaba.nacos.client.Worker.longPolling.fixed-172.17.101.101_8848-river][com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost][177]:no available server, currentServerAddr : http://172.17.101.101:8848
[20200911 122349 880][ERROR][com.alibaba.nacos.client.Worker.longPolling.fixed-172.17.101.101_8848-riverrace][com.alibaba.nacos.client.Worker.longPolling.fixed-172.17.101.101_8848-river][com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr][399]:[fixed-172.17.101.101_8848-river] [check-update] get changed dataId exception
java.net.ConnectException: no available server, currentServerAddr : http://172.17.101.101:8848
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:178) ~[nacos-client-1.3.0.jar!/:?]
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.3.0.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:387) [nacos-client-1.3.0.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:355) [nacos-client-1.3.0.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:522) [nacos-client-1.3.0.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
[20200911 122349 880][ERROR][com.alibaba.nacos.client.Worker.longPolling.fixed-172.17.101.101_8848-riverrace][com.alibaba.nacos.client.Worker.longPolling.fixed-172.17.101.101_8848-river][com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run][567]:longPolling error : 
java.net.ConnectException: no available server, currentServerAddr : http://172.17.101.101:8848
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:178) ~[nacos-client-1.3.0.jar!/:?]
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.3.0.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:387) ~[nacos-client-1.3.0.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:355) ~[nacos-client-1.3.0.jar!/:?]
        at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:522) [nacos-client-1.3.0.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_131]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_131]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_131]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_131]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]```

The network is fine, this error occurs occasionally, and the client version used is 1.3.0

**Comment by KomachiSion** [comment]
The log is not the root error info. Please provide more logs so that community can find the problem.

**Comment by horizonzy** [comment]
pls make sure set right serverList in your client.

**Comment by KomachiSion** [comment]
From provided logs, occasionally happen this error may be due to transient network interruption. 

It will recovery after network interruption finished.
