### ISSUE TITLE
nacos.log里全都是这个错误，请问该如何解决？

### ISSUE THREAD

**Issue by shadowhunterhh** [alibaba/nacos#3843]
java.lang.IllegalStateException: can not find peer: 172.17.0.17:8848
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore.receivedVote(RaftCore.java:494)
	at com.alibaba.nacos.naming.controllers.RaftController.vote(RaftController.java:88)
	at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:189)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:800)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1038)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:942)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1005)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:908)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:660)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:882)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:90)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.naming.web.DistroFilter.doFilter(DistroFilter.java:154)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.naming.web.TrafficReviseFilter.doFilter(TrafficReviseFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

**Comment by mark4z** [comment]
你改了集群的配置但是没有全部重启？

**Comment by shadowhunterhh** [comment]
> 你改了集群的配置但是没有全部重启？
I'm not sure. I will try restart later. Thank you

我不太记得了,我晚点重启试一下，谢谢你的建议

**Comment by shadowhunterhh** [comment]
> 你改了集群的配置但是没有全部重启？
I also want to ask that I have not configured 172.17.0.17:8848, which is not the IP of any of my servers. Do you know what this?

还想问下,我没有配置172.17.0.17:8848,这不是我任何一台服务器的ip,您知道这个是做什么的吗?

**Comment by mark4z** [comment]
> 172.17.0.17:

k8s吗？或者docker的ip吗

**Comment by shadowhunterhh** [comment]
> 你改了最大化的配置但是沒有全部重啟？

我已经试了把所有nacos服务全都重启了，但是log日志里仍然一直在打这个错误，而且非常频繁，导致log文件特别大

**Comment by mark4z** [comment]
> > 你改了最大化的配置但是沒有全部重啟？
> 
> 我已经试了把所有nacos服务全都重启了，但是log日志里仍然一直在打这个错误，而且非常频繁，导致log文件特别大

把你的 版本、cluster.conf和实际部署情况发出来一下。

**Comment by mark4z** [comment]
另外可以考虑一下删除nacos的缓存，conf同级目录下的naming，做好备份

**Comment by shadowhunterhh** [comment]
> > > 你改了最大化的配置但是沒有全部重啟？
> > 
> > 
> > 我已经试了把所有nacos服务全都重启了，但是log日志里仍然一直在打这个错误，而且非常频繁，导致log文件特别大
> 
> 把你的 版本、cluster.conf和实际部署情况发出来一下。

nacos版本1.3.1，cluster配置
#2020-09-16T18:15:01.842
111.229.166.xxx:8848
123.206.216.xxx:8848
150.158.104.xx:8848
172.17.0.15:8848
部署情况指什么呢？我在linux服务器部署了一个，两台windows服务器分别部署了一个服务，并且端口也开通了

**Comment by mark4z** [comment]
> > > > 你改了最大化的配置但是沒有全部重啟？
> > > 
> > > 
> > > 我已经试了把所有nacos服务全都重启了，但是log日志里仍然一直在打这个错误，而且非常频繁，导致log文件特别大
> > 
> > 
> > 把你的 版本、cluster.conf和实际部署情况发出来一下。
> 
> nacos版本1.3.1，cluster配置
> #2020-09-16T18:15:01.842
> 111.229.166.xxx:8848
> 123.206.216.xxx:8848
> 150.158.104.xx:8848
> 172.17.0.15:8848
> 部署情况指什么呢？我在linux服务器部署了一个，两台windows服务器分别部署了一个服务，并且端口也开通了



> > > > 你改了最大化的配置但是沒有全部重啟？
> > > 
> > > 
> > > 我已经试了把所有nacos服务全都重启了，但是log日志里仍然一直在打这个错误，而且非常频繁，导致log文件特别大
> > 
> > 
> > 把你的 版本、cluster.conf和实际部署情况发出来一下。
> 
> nacos版本1.3.1，cluster配置
> #2020-09-16T18:15:01.842
> 111.229.166.xxx:8848
> 123.206.216.xxx:8848
> 150.158.104.xx:8848
> 172.17.0.15:8848
> 部署情况指什么呢？我在linux服务器部署了一个，两台windows服务器分别部署了一个服务，并且端口也开通了

试试把最后一条删掉，这个似乎是局域网ip

**Comment by KomachiSion** [comment]
172.17.0.15:8848 可能是你宿主机的ip。 nacos通过`java.net.InetSocket`获取你本机ip。 而172.17.0.15很可能是nacos获取出来的

**Comment by shadowhunterhh** [comment]
172.17.0.15:8848,这个ip我试着删除过，删除后把三台服务器的nacos重新部署了，然后这个ip就会自动出现在配置文件里。还想请问下现在nacos集群是不是失败的状态?这个报错该如何解决？三台服务器的端口和防火墙都是通的

**Comment by KomachiSion** [comment]
应该和你容器或宿主机的配置有关系，nacos会读到172.17.0.15 说明这个才是你容器的实际ip地址。你可以试一下自己写个测试程序，用java.net.InetSocket去取本地ip，应该就是这个172.17.0.15。

解决方法就是改机器配置，让应用程序读取到的ip是虚拟之后的ip就可以了

**Comment by shadowhunterhh** [comment]
> 應該和你容器或宿主機的配置有關係，nacos會讀到172.17.0.15說明這個才是你容器的實際ip地址。你可以試一下自己寫個測試程序，用java.net.InetSocket去取本地ip ，應該就是這個172.17.0.15。
> 
> 解決方法就是改機器配置，讓應用程序讀取到的ip是虛擬之後的ip就可以了

刚刚仔细看了一下，172.17.0.15实际是服务器本机内网ip，我在nacos的application.properties中配置了nacos.inetutils.ip-address=本机ip并且重启了nacos服务，现在似乎不会再报错了。感谢
