### ISSUE TITLE
项目停止是，不要输出java.net.SocketException: socket closed这样的错误

### ISSUE THREAD

**Issue by jasonpyf** [alibaba/nacos#3850]
![11](https://user-images.githubusercontent.com/16953632/93411553-fd4eb780-f8cd-11ea-9af3-de980f04af1a.png)

**Comment by KomachiSion** [comment]
@jasonpyf which version you used?

**Comment by yueyemisi** [comment]
nacos server version:1.3.2
nacos client version:1.3.2

2020-09-18 11:50:22.156  INFO c.a.n.c.naming            149-[]: com.alibaba.nacos.client.naming.beat.BeatReactor do shutdown stop
2020-09-18 11:50:22.157  INFO c.a.n.c.naming            149-[]: com.alibaba.nacos.client.naming.core.EventDispatcher do shutdown begin
2020-09-18 11:50:25.160  INFO c.a.n.c.naming            152-[]: com.alibaba.nacos.client.naming.core.EventDispatcher do shutdown stop
2020-09-18 11:50:25.162  INFO c.a.n.c.naming            370-[]: com.alibaba.nacos.client.naming.core.HostReactor do shutdown begin
2020-09-18 11:50:27.550  INFO c.a.n.c.naming            118-[]: com.alibaba.nacos.client.naming.core.PushReceiver do shutdown begin
2020-09-18 11:50:30.553  INFO c.a.n.c.naming            122-[]: com.alibaba.nacos.client.naming.core.PushReceiver do shutdown stop
2020-09-18 11:50:30.555  INFO c.a.n.c.naming            132-[]: com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown begin
2020-09-18 11:50:30.558  INFO c.a.n.c.naming            134-[]: com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown stop
2020-09-18 11:50:30.558  INFO c.a.n.c.naming            374-[]: com.alibaba.nacos.client.naming.core.HostReactor do shutdown stop
2020-09-18 11:50:30.558  INFO c.a.n.c.naming            715-[]: com.alibaba.nacos.client.naming.net.NamingProxy do shutdown begin
2020-09-18 11:50:30.559  WARN c.a.n.c.naming            72-[]: [NamingHttpClientManager] Start destroying NacosRestTemplate
2020-09-18 11:50:30.560  WARN c.a.n.c.naming            79-[]: [NamingHttpClientManager] Destruction of the end
2020-09-18 11:50:30.560  INFO c.a.n.c.naming            718-[]: com.alibaba.nacos.client.naming.net.NamingProxy do shutdown stop
2020-09-18 11:50:30.561  WARN f.s.DisposableBeanAdapter 349-[]: Destroy method 'close' on bean with name 'nacosServiceRegistry' threw an exception: java.lang.NullPointerException
2020-09-18 11:50:30.574 ERROR c.a.n.c.naming            110-[]: [NA] error while receiving push data
java.net.SocketException: socket closed
	at java.net.DualStackPlainDatagramSocketImpl.socketReceiveOrPeekData(Native Method)
	at java.net.DualStackPlainDatagramSocketImpl.receive0(DualStackPlainDatagramSocketImpl.java:120)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:144)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at com.alibaba.nacos.client.naming.core.PushReceiver.run(PushReceiver.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by RuoLing** [comment]
nacos server version:1.3.2
nacos client version:1.3.3
spring-cloud-starter-alibaba-nacos-discovery version: 2.2.3.RELEASE

13:43:19 [SpringContextShutdownHook] INFO  com.alibaba.nacos.client.naming - com.alibaba.nacos.client.naming.beat.BeatReactor do shutdown stop
13:43:19 [SpringContextShutdownHook] INFO  com.alibaba.nacos.client.naming - com.alibaba.nacos.client.naming.core.EventDispatcher do shutdown begin
13:43:22 [SpringContextShutdownHook] INFO  com.alibaba.nacos.client.naming - com.alibaba.nacos.client.naming.core.EventDispatcher do shutdown stop
13:43:22 [SpringContextShutdownHook] INFO  com.alibaba.nacos.client.naming - com.alibaba.nacos.client.naming.core.HostReactor do shutdown begin
13:43:22 [SpringContextShutdownHook] INFO  com.alibaba.nacos.client.naming - com.alibaba.nacos.client.naming.core.PushReceiver do shutdown begin
13:43:25 [SpringContextShutdownHook] INFO  com.alibaba.nacos.client.naming - com.alibaba.nacos.client.naming.core.PushReceiver do shutdown stop
13:43:25 [SpringContextShutdownHook] INFO  com.alibaba.nacos.client.naming - com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown begin
13:43:25 [com.alibaba.nacos.naming.push.receiver] ERROR com.alibaba.nacos.client.naming - [NA] error while receiving push data
java.net.SocketException: socket closed
	at java.net.DualStackPlainDatagramSocketImpl.socketReceiveOrPeekData(Native Method)
	at java.net.DualStackPlainDatagramSocketImpl.receive0(DualStackPlainDatagramSocketImpl.java:124)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at com.alibaba.nacos.client.naming.core.PushReceiver.run(PushReceiver.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
13:43:25 [SpringContextShutdownHook] INFO  com.alibaba.nacos.client.naming - com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown stop
13:43:25 [SpringContextShutdownHook] INFO  com.alibaba.nacos.client.naming - com.alibaba.nacos.client.naming.core.HostReactor do shutdown stop
13:43:25 [SpringContextShutdownHook] INFO  com.alibaba.nacos.client.naming - com.alibaba.nacos.client.naming.net.NamingProxy do shutdown begin
13:43:25 [SpringContextShutdownHook] WARN  com.alibaba.nacos.client.naming - [NamingHttpClientManager] Start destroying NacosRestTemplate
13:43:25 [SpringContextShutdownHook] WARN  com.alibaba.nacos.client.naming - [NamingHttpClientManager] Destruction of the end
13:43:25 [SpringContextShutdownHook] INFO  com.alibaba.nacos.client.naming - com.alibaba.nacos.client.naming.net.NamingProxy do shutdown stop
13:43:25 [SpringContextShutdownHook] WARN  o.s.b.f.s.DisposableBeanAdapter - Destroy method 'close' on bean with name 'nacosServiceRegistry' threw an exception: java.lang.NullPointerException
