### ISSUE TITLE
Nacos 采用 Docker 部署集群，LEADER 宕机以后，FOLLOWER 没有自动选举为 LEADER

### ISSUE THREAD

**Issue by Rambo1203** [alibaba/nacos#3853]
**环境概述**
```text
100.100.100.100 Nginx 做 upstream 负载 101、102、103
100.100.100.101 Nacos 8848
100.100.100.102 Nacos 8848
100.100.100.103 Nacos 8848 
```

为测试功能，四台机器都关闭了防火墙

**Docker脚本**
```shell
docker run --net=host --rm -it -p 8848:8848 \
--name nacos-cluster-mysql \
-e MODE=cluster \
-e NACOS_SERVERS="100.100.100.101:8848 100.100.100.102:8848 100.100.100.103:8848" \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=100.100.100.100 \
-e MYSQL_SERVICE_PORT=3306 \
-e MYSQL_SERVICE_DB_NAME=nacos \
-e MYSQL_SERVICE_USER=root \
-e MYSQL_SERVICE_PASSWORD=123456 \
-e NACOS_AUTH_TOKEN_EXPIRE_SECONDS=3600 \
-e JVM_XMS=256m \
-e JVM_XMX=512m \
nacos/nacos-server:1.3.2
```

**Nginx脚本**
```shell
upstream nacos {
    server 100.100.100.101:8848;
    server 100.100.100.102:8848;
    server 100.100.100.103:8848;
}

server {
    listen       80;
    server_name  localhost;
    location /nacos/ {
        proxy_pass http://nacos;
    }
}
```  

**问题描述**  
1、初次启动，通过 Nginx 代理访问到 Nacos 界面可以看到 101、102、103 为 UP 状态，并且可以看到一个 LEADER 两个FOLLOWER  

2、假设 LEADER 在 102 ，并手动停止 102 的 Docker 容器，可以看到界面 102 为 DOWN 的状态，但是102的节点元数据详情中还是 LEADER 

3、查看有最高集群任期的 naming-raft.log 一直刷 挂掉节点的 8848 Connection refused 异常，没有进行下一步的选举  

```text
[root@node103 logs]# tail -f naming-raft.log 
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: /100.100.100.102:8848
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 common frames omitted
2020-09-17 14:37:25,981 ERROR NACOS-RAFT error while sending heart-beat to peer: 100.100.100.102:8848 {}

java.net.ConnectException: Connection refused: /100.100.100.102:8848 to http://100.100.100.102:8848/nacos/v1/ns/raft/beat
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:380)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: /100.100.100.102:8848
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:714)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 common frames omitted
2020-09-17 14:37:30,986 ERROR NACOS-RAFT error while sending heart-beat to peer: 100.100.100.102:8848 {}
```  

4、期望状态是，103 自动选举为 LEADER，101 还是 FOLLOWER，当 102 启动后以 FOLLOWER 身份加入到集群（目前状态是：102 挂掉了以后 节点元数据 还是 LEADER ， 其它两个健康的节点都是 FOLLOWER）。

**P.S**  

**<font color="red">经验证，1.3.2 采用 tar.gz 包安装的方式也存在同样的问题！！！</font>**

**Comment by KomachiSion** [comment]
duplicate with #3384

**Comment by 0521ak47** [comment]
1.32版本出现同样问题，关闭LEADER节点，其他两个节点一直保持是FOLLOWER，无法自动选举新LEADER
