### ISSUE TITLE
failed to req API:http://150.158.104.44:8848/nacos/v1/ns/instance. code:500 msg: java.net.SocketTimeoutException: Read timed out

### ISSUE THREAD

**Issue by shadowhunterhh** [alibaba/nacos#3861]
dubbo整合nacos做注册中心，连接本地nacos server可以正常启动服务并注册成功，但注册到服务器nacos server会报错，提示:
failed to req API:http://150.158.104.xx:8848/nacos/v1/ns/instance. code:500 msg: java.net.SocketTimeoutException: Read timed out

(Dubbo integrated nacos as the registry, connected to the local nacos Server can start the service normally and register successfully, but connected to the server nacos Server will report an error, prompt:
failed to req API:http://150.158.104.xx:8848/nacos/v1/ns/instance. code:500 msg: java.net.SocketTimeoutException: Read timed out)

maven dependency：
dubbo 版本 2.6.0
dubbo-registry-nacos 2.6.9
nacos-client 1.0.0
spring-cloud-starter-alibaba-nacos-config 1.5.1.RELEASE

**Comment by shadowhunterhh** [comment]
同时服务器的naming-server.log会打印大量相同的报错内容，单次启动服务打印了约13MB的日志，内容为：

(Meanwhile, the naming-server.log of the server will print a large number of the same error reporting content, and the single startup service prints about 13MB of the log, which reads as follows:)

java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.alibaba.nacos.naming.misc.HttpClient.getResult(HttpClient.java:565)
	at com.alibaba.nacos.naming.misc.HttpClient.request(HttpClient.java:168)
	at com.alibaba.nacos.naming.web.DistroFilter.doFilter(DistroFilter.java:143)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:60)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.naming.web.TrafficReviseFilter.doFilter(TrafficReviseFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2020-09-18 11:26:35,735 WARN Exception while request: http://172.17.0.15:8848/nacos/v1/ns/instance?groupName=DEFAULT_GROUP&metadata=%7B%22side%22%3A%22provider%22%2C%22methods%22%3A%22getGradeCodeByKey%2CgetUserByKey%2CgetThirdPartyUser%2CgetGradeByCode%2CgetSubjectByKey%2CgetClassByKey%2CgetSchoolByKey%2CgetGradeByKey%2CgetSubjectCodeByKey%22%2C%22dubbo%22%3A%222.6.0%22%2C%22pid%22%3A%226012%22%2C%22interface%22%3A%22com.datedu.base.service.BaseInfoService%22%2C%22generic%22%3A%22false%22%2C%22revision%22%3A%220.0.6%22%2C%22protocol%22%3A%22dubbo%22%2C%22application%22%3A%22datedu-service-base%22%2C%22default.timeout%22%3A%223000%22%2C%22category%22%3A%22providers%22%2C%22anyhost%22%3A%22true%22%2C%22timestamp%22%3A%221600399596747%22%7D&namespaceId=public&port=20882&enable=true&healthy=true&nofix=1&ip=192.168.10.131&weight=100.0&ephemeral=true&serviceName=DEFAULT_GROUP%40%40providers%3Acom.datedu.base.service.BaseInfoService&encoding=UTF-8&, caused: {}

**Comment by KomachiSion** [comment]
检查一下服务端的gc，网络和防火墙。
从日志来看是服务端转发请求到其他节点时超时了。

**Comment by shadowhunterhh** [comment]
> 检查一下服务端的gc，网络和防火墙。
> 从日志来看是服务端转发请求到其他节点时超时了。

忘记说了，我现在是三台服务器集群的，bootstrap配置如下：
dubbo.registry.address=nacos://150.158.104.xx:8848?backup:123.206.216.xx:8848,111.229.166.xx:8848

我试了单独在其中一台服务器上换一个端口单独起一个nacos，然后把bootstrap配置更改如下，
dubbo.registry.address=nacos://150.158.104.xx:8847
其他所有配置保持不变，是可以正常启动和注册到nacos的
服务器的防火墙确定是通的，并且是内网服务器

**Comment by KomachiSion** [comment]
172.17.0.15 is not in your cluster, but nacos transport request to it.

I think it's the reason.

**Comment by shadowhunterhh** [comment]
> 172.17.0.15 is not in your cluster, but nacos transport request to it.
> 
> I think it's the reason.
> 
> search `healthy server list` in naming-server.log` and check the server list is your expected.

我使用三台服务器部署了集群，这是其中一台服务器的内网ip
I deployed the cluster with three servers, and this IP is the Intranet IP of one of the servers

**Comment by shadowhunterhh** [comment]
More specific error messages：

2020-09-18 15:30:03.148 [main] ERROR com.alibaba.nacos.client.naming - request 150.158.104.44:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://150.158.104.44:8848/nacos/v1/ns/instance. code:500 msg: java.net.SocketTimeoutException: Read timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:186)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:298)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:279)
	at com.alibaba.dubbo.registry.nacos.NacosRegistry$2.callback(NacosRegistry.java:147)
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:463)
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:145)
	at com.alibaba.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:136)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:116)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:135)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:66)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:91)
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:505)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:357)
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:316)
	at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:215)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:121)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:50)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:393)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:347)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:883)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.finishRefresh(EmbeddedWebApplicationContext.java:144)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
	at com.datedu.base.DateduServiceBaseApplication.main(DateduServiceBaseApplication.java:19)
2020-09-18 15:30:03.149 [main] INFO  org.apache.catalina.core.StandardService - Stopping service [Tomcat]
2020-09-18 15:30:03.174 [localhost-startStop-1] WARN  org.apache.catalina.loader.WebappClassLoaderBase - The web application [ROOT] appears to have started a thread named [Abandoned connection cleanup thread] but has failed to stop it. This is very likely to create a memory leak. Stack trace of thread:
 java.lang.Object.wait(Native Method)

**Comment by chimw** [comment]
@shadowhunterhh how to fix this issue? can you share?

**Comment by shadowhunterhh** [comment]
> @shadowhunterhh how to fix this issue? can you share?

I changed the cluster server address in cluster.conf to the Intranet IP address, other configurations remained the same, and then restarted nacos Server, and the problem was solved
