### ISSUE TITLE
nacos server cpu 飙高

### ISSUE THREAD

**Issue by allskylove** [alibaba/nacos#3911]
**Describe the bug**
nacos server cpu 飙高，占300%. version:  NACOS1.4.0-SNAPSHOT

"com.alibaba.nacos.MergeDatum.0" #173 daemon prio=5 os_prio=0 tid=0x00007f2f1d663000 nid=0x675 runnable [0x00007f2eee0e1000]
   java.lang.Thread.State: RUNNABLE
	at com.alibaba.nacos.common.task.engine.AbstractNacosTaskExecuteEngine$ProcessRunnable.run(AbstractNacosTaskExecuteEngine.java:175)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	
	
	
	
	"com.alibaba.nacos.server.DumpTaskManager.0" #154 daemon prio=5 os_prio=0 tid=0x00007f2f1d37a000 nid=0x663 runnable [0x00007f2eef2f3000]
   java.lang.Thread.State: RUNNABLE
	at java.util.concurrent.ConcurrentHashMap$Traverser.advance(ConcurrentHashMap.java:3339)
	at java.util.concurrent.ConcurrentHashMap$BaseIterator.<init>(ConcurrentHashMap.java:3391)
	at java.util.concurrent.ConcurrentHashMap$KeyIterator.<init>(ConcurrentHashMap.java:3410)
	at java.util.concurrent.ConcurrentHashMap$KeySetView.iterator(ConcurrentHashMap.java:4578)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at com.alibaba.nacos.common.task.engine.AbstractNacosTaskExecuteEngine.getAllTaskKeys(AbstractNacosTaskExecuteEngine.java:144)
	at com.alibaba.nacos.common.task.engine.NacosDelayTaskExecuteEngine.processTasks(NacosDelayTaskExecuteEngine.java:54)
	at com.alibaba.nacos.config.server.manager.TaskManager.processTasks(TaskManager.java:118)
	at com.alibaba.nacos.common.task.engine.AbstractNacosTaskExecuteEngine$ProcessRunnable.run(AbstractNacosTaskExecuteEngine.java:172)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

"com.alibaba.nacos.server.DumpAllTaskManager.0" #155 daemon prio=5 os_prio=0 tid=0x00007f2f1d381800 nid=0x664 runnable [0x00007f2eef1f2000]
   java.lang.Thread.State: RUNNABLE
	at java.util.AbstractCollection.addAll(AbstractCollection.java:343)
	at com.alibaba.nacos.common.task.engine.AbstractNacosTaskExecuteEngine.getAllTaskKeys(AbstractNacosTaskExecuteEngine.java:144)
	at com.alibaba.nacos.common.task.engine.NacosDelayTaskExecuteEngine.processTasks(NacosDelayTaskExecuteEngine.java:54)
	at com.alibaba.nacos.config.server.manager.TaskManager.processTasks(TaskManager.java:118)
	at com.alibaba.nacos.common.task.engine.AbstractNacosTaskExecuteEngine$ProcessRunnable.run(AbstractNacosTaskExecuteEngine.java:172)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

应该是这里的代码问题 
com.alibaba.nacos.common.task.engine.AbstractNacosTaskExecuteEngine

 private class ProcessRunnable implements Runnable {
    
        @Override
        public void run() {
            while (!closed.get()) {
                try {
                    AbstractNacosTaskExecuteEngine.this.processTasks();
                } catch (Throwable e) {
                    log.error(e.toString(), e);
                }
            }
        }
    }

**Comment by KomachiSion** [comment]
Has been fixed I remember.

**Comment by KomachiSion** [comment]
fixed by https://github.com/alibaba/nacos/pull/3715
