### ISSUE TITLE
nacos 切换集群模式报错

### ISSUE THREAD

**Issue by xiahuhu1** [alibaba/nacos#3928]
####  nacos 从单节点切换到三个节点的群集模式报错
```
2020-09-29 00:12:38.429 ERROR [hsp-xxxx,,,] [hsp-xxxx] 1 --- [bboShutdownHook] com.alibaba.nacos.client.naming          : request 192.168.10.162:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:192.168.10.162:8848/nacos/v1/ns/instance. code:500 msg: java.net.SocketTimeoutException: Read timed out
    at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:427)
    at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:454)
    at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
    at com.alibaba.nacos.client.naming.net.NamingProxy.deregisterService(NamingProxy.java:208)
    at com.alibaba.nacos.client.naming.NacosNamingService.deregisterInstance(NacosNamingService.java:246)
    at com.alibaba.nacos.client.naming.NacosNamingService.deregisterInstance(NacosNamingService.java:233)
    at com.alibaba.nacos.client.naming.NacosNamingService.deregisterInstance(NacosNamingService.java:218)
    at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doUnregister$2(NacosRegistry.java:169)
    at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:583)
    at org.apache.dubbo.registry.nacos.NacosRegistry.doUnregister(NacosRegistry.java:166)
    at org.apache.dubbo.registry.support.FailbackRegistry.unregister(FailbackRegistry.java:289)
    at org.apache.dubbo.registry.support.AbstractRegistry.destroy(AbstractRegistry.java:473)
    at org.apache.dubbo.registry.support.FailbackRegistry.destroy(FailbackRegistry.java:439)
    at org.apache.dubbo.registry.support.AbstractRegistryFactory.destroyAll(AbstractRegistryFactory.java:88)
    at org.apache.dubbo.config.DubboShutdownHook.destroyAll(DubboShutdownHook.java:128)
    at org.apache.dubbo.config.bootstrap.DubboBootstrap.destroy(DubboBootstrap.java:1065)
    at org.apache.dubbo.config.bootstrap.DubboBootstrap$1.callback(DubboBootstrap.java:193)
    at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46)
    at org.apache.dubbo.common.lang.ShutdownHookCallbacks.lambda$callback$0(ShutdownHookCallbacks.java:70)
    at java.lang.Iterable.forEach(Iterable.java:75)
    at org.apache.dubbo.common.lang.ShutdownHookCallbacks.callback(ShutdownHookCallbacks.java:70)
    at org.apache.dubbo.config.DubboShutdownHook.callback(DubboShutdownHook.java:85)
    at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:73)
2020-09-29 00:12:38.585 ERROR [hsp-xxxx,,,] [hsp-xxxx] 1 --- [TaskScheduler-1] o.s.s.s.TaskUtils$LoggingErrorHandler    : Unexpected error occurred in scheduled task.

java.lang.IllegalStateException: org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@394e1a0f has been closed already
    at org.springframework.context.support.AbstractApplicationContext.assertBeanFactoryActive(AbstractApplicationContext.java:1067)
    at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1082)
    at org.springframework.context.event.ApplicationListenerMethodAdapter.getTargetBean(ApplicationListenerMethodAdapter.java:286)
    at org.springframework.context.event.ApplicationListenerMethodAdapter.doInvoke(ApplicationListenerMethodAdapter.java:256)
    at org.springframework.context.event.ApplicationListenerMethodAdapter.processEvent(ApplicationListenerMethodAdapter.java:179)
    at org.springframework.context.event.ApplicationListenerMethodAdapter.onApplicationEvent(ApplicationListenerMethodAdapter.java:142)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
    at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:398)
    at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:355)
    at com.alibaba.cloud.nacos.discovery.NacosWatch.nacosServicesWatch(NacosWatch.java:121)
    at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
    at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
    at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
    at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)


2020-09-29 00:12:32.151 ERROR [hsp-xxxx,,,] [hsp-xxxx] 1 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : [CLIENT-BEAT] failed to send beat: {"ip":"172.16.0.3","metadata":{"side":"provider","methods":"getUserInfoByUserId,getUserInfoByUserIdList","release":"2.7.7","deprecated":"false","dubbo":"2.0.2","pid":"1","interface":"com.ichoice.hsp.auth.facade.service.UserInfoFacadeService","generic":"false","revision":"2.0-SNAPSHOT","path":"com.ichoice.hsp.auth.facade.service.UserInfoFacadeService","protocol":"dubbo","application":"hsp-auth","dynamic":"true","category":"providers","anyhost":"true","timestamp":"1601309379781"},"period":5000,"port":20880,"scheduled":false,"serviceName":"DEFAULT_GROUP@@providers:com.ichoice.hsp.auth.facade.service.UserInfoFacadeService::","stopped":false,"weight":1.0}

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([192.168.10.162:8848]) tried: failed to req API:192.168.10.162:8848/nacos/v1/ns/instance/beat. code:500 msg: java.net.SocketTimeoutException: Read timed out
```
####  bootstrap-public.yml 配置
```yaml
spring:
  application:
    name: hsp-xxxx
  cloud:
    nacos:
      config:
        server-addr: 192.168.10.166:8848,192.168.10.167:8848,192.168.10.168:8848
        file-extension: yaml
        namespace: public
```
#### nacos 上的配置文件
```yaml
# nacos配置
spring:
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.10.162:8848,192.168.10.163:8848,192.168.10.164:8848

# dubbo 配置
dubbo:
  application:
    name: hsp-xxxx
  registry:
      address: nacos://192.168.10.162:8848?backup=192.168.10.163:8848,192.168.10.164:8848
      check: false
```
nacos集群的状态也是ok的，一个 `LEADER` 和两个 `FOLLOWER`,部署方式是通过 `docker` ，奇怪的是在nacos上面看到服务的注册都已经注册上去了。

切换回单节点之后一切恢复正常。

**Comment by KomachiSion** [comment]
推测是集群模式搭建的有问题，可以到nacos服务端看下服务端日志，有没有什么报错信息，还有确认下cluster.conf的配置文件，是否配置正确。

**Comment by KomachiSion** [comment]
@xiahuhu1 Any process? If no more response, we will close issue.

**Comment by xiahuhu1** [comment]
我这边是通过docker的方式部署的，配置文件如下：
**nacos01**
```bash
#!/bin/bash
docker stop nacos-server-1
docker rm -f nacos-server-1

docker run -d \
-e PREFER_HOST_MODE=hostname \
-e MODE=cluster \
-e NACOS_APPLICATION_PORT=8848 \
-e NACOS_SERVERS="192.168.10.162:8848 192.168.10.163:8848 192.168.10.164:8848" \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=192.168.10.162 \
-e MYSQL_SERVICE_PORT=3306 \
-e MYSQL_SERVICE_USER=xxxx\
-e MYSQL_SERVICE_PASSWORD=xxxx\
-e MYSQL_SERVICE_DB_NAME=nacos_config \
-e MYSQL_SLAVE_SERVICE_HOST=192.168.10.163 \
-e MYSQL_SLAVE_SERVICE_PORT=3306 \
-e NACOS_SERVER_IP=192.168.10.162 \
-e JVM_XMS=512m \
-e JVM_XMX=1g \
--privileged=true \
-p 8848:8848 \
-v $PWD/logs:/home/nacos/logs \
-v $PWD/conf:/home/nacos/conf \
-v $PWD/conf:/home/nacos/data \
--name nacos-server-1 \
nacos/nacos-server
```
**nacos02**
```bash
#!/bin/bash
docker stop nacos-server-2
docker rm -f nacos-server-2

docker run -d \
-e PREFER_HOST_MODE=hostname \
-e MODE=cluster \
-e NACOS_APPLICATION_PORT=8848 \
-e NACOS_SERVERS="192.168.10.162:8848 192.168.10.163:8848 192.168.10.164:8848" \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=192.168.10.162 \
-e MYSQL_SERVICE_PORT=xxxx\
-e MYSQL_SERVICE_USER=xxxx\
-e MYSQL_SERVICE_PASSWORD=xxxx\
-e MYSQL_SERVICE_DB_NAME=nacos_config \
-e MYSQL_SLAVE_SERVICE_HOST=192.168.10.163 \
-e MYSQL_SLAVE_SERVICE_PORT=xxxx\
-e NACOS_SERVER_IP=192.168.10.163 \
-e JVM_XMS=512m \
-e JVM_XMX=1g \
--privileged=true \
-p 8848:8848 \
-v $PWD/logs:/home/nacos/logs \
-v $PWD/conf:/home/nacos/conf \
-v $PWD/conf:/home/nacos/data \
--name nacos-server-2 \
nacos/nacos-server
```
**nacos03**
```bash
docker stop nacos-server-3
docker rm -f nacos-server-3

docker run -d \
-e PREFER_HOST_MODE=hostname \
-e MODE=cluster \
-e NACOS_APPLICATION_PORT=8848 \
-e NACOS_SERVERS="192.168.10.162:8848 192.168.10.163:8848 192.168.10.164:8848" \
-e SPRING_DATASOURCE_PLATFORM=mysql \
-e MYSQL_SERVICE_HOST=192.168.10.162 \
-e MYSQL_SERVICE_PORT=3306 \
-e MYSQL_SERVICE_USER=nacos \
-e MYSQL_SERVICE_PASSWORD=nacos \
-e MYSQL_SERVICE_DB_NAME=nacos_config \
-e MYSQL_SLAVE_SERVICE_HOST=192.168.10.163 \
-e MYSQL_SLAVE_SERVICE_PORT=3306 \
-e NACOS_SERVER_IP=192.168.10.163 \
-e JVM_XMS=512m \
-e JVM_XMX=1g \
--privileged=true \
-p 8848:8848 \
-v $PWD/logs:/home/nacos/logs \
-v $PWD/conf:/home/nacos/conf \
-v $PWD/conf:/home/nacos/data \
--name nacos-server-3 \
nacos/nacos-server
```
**cluster.conf**
```bash
[root@630033d8a843 conf]# cat cluster.conf 
#2020-09-29T00:06:26.566
192.168.10.162:8848
192.168.10.163:8848
192.168.10.164:8848
```
请告诉我还需要我提供什么，感谢回复！

**Comment by KomachiSion** [comment]
麻烦提供2个内容
1. 192.168.10.162 的 nacos-server.log 和nacos.log 主要看是否有错误信息
2. nacos服务端的版本和nacos客户端的版本

**Comment by KomachiSion** [comment]
I test in my env with nacos-group/nacos-docker 1.3.2 and can't reproduce the problem.

The issue author has no more response with a long time. So close issue.

**Comment by Tinywan** [comment]
@xiahuhu1 你可以使用 docker-compose.yml 编排呀
[参考：https://github.com/Tinywan/dnmp/blob/master/docker-compose.yml](https://github.com/Tinywan/dnmp/blob/master/docker-compose.yml)
```
  # 单机模式
  # nacos:
  #   # build:
  #   #   context: ./services/nacos
  #   image: nacos/nacos-server:1.4.0
  #   ports:
  #     - "8848:8848"
  #   volumes:
  #     - ./log/nacos:/home/nacos/logs
  #     - ./services/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
  #   networks:
  #     - backend
  #   container_name: dnmp-nacos
  #   env_file:
  #     - ./services/nacos/env/nacos-standlone-mysql.env

  # 集群模式
  # nacos1:
  #   image: nacos/nacos-server:1.4.0
  #   ports:
  #     - "8848:8848"
  #   volumes:
  #     - ./log/nacos:/home/nacos/logs
  #     - ./services/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
  #   networks:
  #     - backend
  #   container_name: dnmp-nacos1
  #   env_file:
  #     - ./services/nacos/env/nacos-hostname.env

  # nacos2:
  #   image: nacos/nacos-server:1.4.0
  #   ports:
  #     - "8849:8848"
  #   volumes:
  #     - ./log/nacos:/home/nacos/logs
  #     - ./services/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
  #   networks:
  #     - backend
  #   container_name: dnmp-nacos2
  #   env_file:
  #     - ./services/nacos/env/nacos-hostname.env

  # nacos3:
  #   image: nacos/nacos-server:1.4.0
  #   ports:
  #     - "8850:8848"
  #   volumes:
  #     - ./log/nacos:/home/nacos/logs
  #     - ./services/nacos/init.d/custom.properties:/home/nacos/init.d/custom.properties
  #   networks:
  #     - backend
  #   container_name: dnmp-nacos3
  #   env_file:
  #     - ./services/nacos/env/nacos-hostname.env
```
