### ISSUE TITLE
[mvn build failed] mvn -Prelease-nacos clean install -U, can't pass Tests

### ISSUE THREAD

**Issue by AngryMills** [alibaba/nacos#3929]
## Issue Description

mvn -Prelease-nacos clean install -U, cann't pass Tests

### Describe what happened (or what feature you want)
I don't know why can't pass Tests
![1](https://user-images.githubusercontent.com/19707438/94495703-04a68700-0225-11eb-9b97-a009010a43b0.png)
![2](https://user-images.githubusercontent.com/19707438/94495708-083a0e00-0225-11eb-8f00-497118245a5d.png)
![3](https://user-images.githubusercontent.com/19707438/94495714-096b3b00-0225-11eb-8256-d0c8b1b98bde.png)

### Tell us your environment
windows 10
jdk 8

有没有大佬能帮忙解答下

**Comment by GTerryLiu** [comment]
![image](https://user-images.githubusercontent.com/56809491/94504192-ce740200-023a-11eb-99db-b366cba6ea6d.png)
我的也编译不了。

**Comment by AngryMills** [comment]
> ![image](https://user-images.githubusercontent.com/56809491/94504192-ce740200-023a-11eb-99db-b366cba6ea6d.png)
> 我的也编译不了。

你这个jdk 版本...换下版本

**Comment by GTerryLiu** [comment]
> > ![image](https://user-images.githubusercontent.com/56809491/94504192-ce740200-023a-11eb-99db-b366cba6ea6d.png)
> > 我的也编译不了。
> 
> 你这个jdk 版本...换下版本

是不能用openjdk，还是openjdk的版本号要换？

**Comment by AngryMills** [comment]
> > > ![image](https://user-images.githubusercontent.com/56809491/94504192-ce740200-023a-11eb-99db-b366cba6ea6d.png)
> > > 我的也编译不了。
> > 
> > 
> > 你这个jdk 版本...换下版本
> 
> 是不能用openjdk，还是openjdk的版本号要换？

试试 11 以下

**Comment by GTerryLiu** [comment]
多谢了，我试了openjdk10和openjdk11，都可以编译通过

**Comment by AngryMills** [comment]
> 多谢了，我试了openjdk10和openjdk11，都可以编译通过

mvn -Prelease-nacos clean install -U ,执行这个也可以通过么？

**Comment by GTerryLiu** [comment]
> > 多谢了，我试了openjdk10和openjdk11，都可以编译通过
> 
> mvn -Prelease-nacos clean install -U ,执行这个也可以通过么？

我用的是：mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U

**Comment by GTerryLiu** [comment]
> > 多谢了，我试了openjdk10和openjdk11，都可以编译通过
> 
> mvn -Prelease-nacos clean install -U ,执行这个也可以通过么？

我用的是：mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U，与你那个命令的差别是不用跑测试。我试了一下你那个要跑测试的命令，不能通过，有报错。你要想通过的话，还是把测试skip掉吧。

**Comment by AngryMills** [comment]
> > > 多谢了，我试了openjdk10和openjdk11，都可以编译通过
> > 
> > 
> > mvn -Prelease-nacos clean install -U ,执行这个也可以通过么？
> 
> 我用的是：mvn -Prelease-nacos -Dmaven.test.skip=true clean install -U，与你那个命令的差别是不用跑测试。我试了一下你那个要跑测试的命令，不能通过，有报错。你要想通过的话，还是把测试skip掉吧。

好的，谢谢，我想pr代码，必须得测试通过。

**Comment by KomachiSion** [comment]
报错信息是什么？

**Comment by AngryMills** [comment]
> 报错信息是什么？

我用的原仓库的工程也是报这个错。develop 分支
10:09:58.921 [main] ERROR com.alibaba.nacos.console.controller.HealthController - Naming health check fail.
java.lang.RuntimeException: HealthControllerTest.testReadiness
        at com.alibaba.nacos.console.controller.HealthController.isNamingReadiness(HealthController.java:102)
        at com.alibaba.nacos.console.controller.HealthController.readiness(HealthController.java:72)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.
java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapte
r.java:892)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.jav
a:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at org.springframework.test.web.servlet.TestDispatcherServlet.service(TestDispatcherServlet.java:72)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.springframework.mock.web.MockFilterChain$ServletFilterProxy.doFilter(MockFilterChain.java:167)
        at org.springframework.mock.web.MockFilterChain.doFilter(MockFilterChain.java:134)
        at org.springframework.test.web.servlet.MockMvc.perform(MockMvc.java:183)
        at com.alibaba.nacos.console.controller.HealthControllerTest.testReadiness(HealthControllerTest.java:103)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:7
4)
        at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)

        at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
        at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
        at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
        at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
        at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:272)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:236)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
....
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /E:/my/gitee/nacos-alibaba/test/src/test/java/com/alibaba/nacos/test/config/ConfigLongPoll_CITCase.java:[19,25] 找不到符号
  符号:   类 Nacos
  位置: 程序包 com.alibaba.nacos
[ERROR] /E:/my/gitee/nacos-alibaba/test/src/test/java/com/alibaba/nacos/test/naming/MultiTenant_ITCase.java:[19,25] 找不到符号
  符号:   类 Nacos
  位置: 程序包 com.alibaba.nacos
[ERROR] /E:/my/gitee/nacos-alibaba/test/src/test/java/com/alibaba/nacos/test/core/auth/Role_ITCase.java:[18,25] 找不到符号
  符号:   类 Nacos
  位置: 程序包 com.alibaba.nacos
[ERROR] /E:/my/gitee/nacos-alibaba/test/src/test/java/com/alibaba/nacos/test/core/auth/Permission_ITCase.java:[18,25] 找不到符号
  符号:   类 Nacos
  位置: 程序包 com.alibaba.nacos
[ERROR] /E:/my/gitee/nacos-alibaba/test/src/test/java/com/alibaba/nacos/test/core/auth/User_ITCase.java:[18,25] 找不到符号
  符号:   类 Nacos
  位置: 程序包 com.alibaba.nacos
[ERROR] /E:/my/gitee/nacos-alibaba/test/src/test/java/com/alibaba/nacos/test/core/auth/User_ITCase.java:[22,39] 程序包com.alibaba.nacos.conso
le.utils不存在
[ERROR] /E:/my/gitee/nacos-alibaba/test/src/test/java/com/alibaba/nacos/test/naming/RestAPI_ITCase.java:[18,25] 找不到符号
  符号:   类 Nacos
  位置: 程序包 com.alibaba.nacos
[ERROR] /E:/my/gitee/nacos-alibaba/test/src/test/java/com/alibaba/nacos/test/naming/Unsubscribe_ITCase.java:[18,25] 找不到符号
  符号:   类 Nacos
  位置: 程序包 com.alibaba.nacos
[ERROR] /E:/my/gitee/nacos-alibaba/test/src/test/java/com/alibaba/nacos/test/naming/SubscribeCluster_ITCase.java:[18,25] 找不到符号
  符号:   类 Nacos
  位置: 程序包 com.alibaba.nacos
[ERROR] /E:/my/gitee/nacos-alibaba/test/src/test/java/com/alibaba/nacos/test/naming/Cmdb_ITCase.java:[18,25] 找不到符号
  符号:   类 Nacos

**Comment by KomachiSion** [comment]
报错找不到对应的内容，可能是你clone的代码有问题，或者maven的配置不正确。执行一下mvn clean或者从github重新clone之后再试

**Comment by AngryMills** [comment]
> 报错找不到对应的内容，可能是你clone的代码有问题，或者maven的配置不正确。执行一下mvn clean或者从github重新clone之后再试

上边那老哥也说执行test报错，直接用我自己clone的仓库不行，换成直接从alibaba的仓库也不行，本地打包报这个错，自己的仓库 travis-ci 上打包也报这个错。maven 还需要什么特别的配置么？

**Comment by AngryMills** [comment]
> 报错找不到对应的内容，可能是你clone的代码有问题，或者maven的配置不正确。执行一下mvn clean或者从github重新clone之后再试

说错了，travis-ci 上报的错不是这个。是这个。
[ERROR] There are test failures.
Please refer to /home/travis/build/alibaba/nacos/api/target/surefire-reports for the individual test results.
Please refer to dump files (if any exist) [date]-jvmRun[N].dump, [date].dumpstream and [date]-jvmRun[N].dumpstream.
The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/travis/build/alibaba/nacos/api && /usr/local/lib/jvm/openjdk11/bin/java -javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.8/org.jacoco.agent-0.7.8-runtime.jar=destfile=/home/travis/build/alibaba/nacos/api/target/jacoco.exec -jar /home/travis/build/alibaba/nacos/api/target/surefire/surefirebooter8265549495945553259.jar /home/travis/build/alibaba/nacos/api/target/surefire 2020-09-28T13-19-11_167-jvmRun1 surefire13739256503128433449tmp surefire_07715113177627456487tmp
Error occurred in starting fork, check output in log
Process Exit Code: 134
org.apache.maven.surefire.booter.SurefireBooterForkException: The forked VM terminated without properly saying goodbye. VM crash or System.exit called?
Command was /bin/sh -c cd /home/travis/build/alibaba/nacos/api && /usr/local/lib/jvm/openjdk11/bin/java -javaagent:/home/travis/.m2/repository/org/jacoco/org.jacoco.agent/0.7.8/org.jacoco.agent-0.7.8-runtime.jar=destfile=/home/travis/build/alibaba/nacos/api/target/jacoco.exec -jar /home/travis/build/alibaba/nacos/api/target/surefire/surefirebooter8265549495945553259.jar /home/travis/build/alibaba/nacos/api/target/surefire 2020-09-28T13-19-11_167-jvmRun1 surefire13739256503128433449tmp surefire_07715113177627456487tmp
Error occurred in starting fork, check output in log
Process Exit Code: 134
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:679)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.fork(ForkStarter.java:533)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:279)
	at org.apache.maven.plugin.surefire.booterclient.ForkStarter.run(ForkStarter.java:243)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeProvider(AbstractSurefireMojo.java:1077)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.executeAfterPreconditionsChecked(AbstractSurefireMojo.java:907)
	at org.apache.maven.plugin.surefire.AbstractSurefireMojo.execute(AbstractSurefireMojo.java:785)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:137)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:210)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:156)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:148)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:56)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:305)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:192)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:105)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:957)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:289)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:193)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:282)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:225)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:406)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:347)

**Comment by KomachiSion** [comment]
这个是maven的错误吧，或者是jdk的问题。
你可以看一下源代码里的trival配置文件，看一下环境，以及maven的测试命令

**Comment by AngryMills** [comment]
> 这个是maven的错误吧，或者是jdk的问题。
> 你可以看一下源代码里的trival配置文件，看一下环境，以及maven的测试命令
我再研究下，谢了
