### ISSUE TITLE
Conflict logback context error

### ISSUE THREAD

**Issue by wangjia2016** [alibaba/nacos#3944]
**Describe the bug**
ERROR in ch.qos.logback.classic.joran.action.ContextNameAction - Failed to rename context [nacos] as [otx] java.lang.IllegalStateException: Context has been already given a name
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.loadConfiguration(LogbackLoggingSystem.java:169)
	at org.springframework.boot.logging.AbstractLoggingSystem.initializeWithSpecificConfig(AbstractLoggingSystem.java:66)
	at org.springframework.boot.logging.AbstractLoggingSystem.initialize(AbstractLoggingSystem.java:57)
	at org.springframework.boot.logging.logback.LogbackLoggingSystem.initialize(LogbackLoggingSystem.java:118)
	at org.springframework.boot.context.logging.LoggingApplicationListener.initializeSystem(LoggingApplicationListener.java:310)
	... 14 more

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
SpringBootWebApplication：
SpringBoot version 2.3.3.RELEASE
spring-cloud-dependencies Hoxton.SR8
spring-cloud-alibaba-dependencies 2.2.3.RELEASE

**Desktop (please complete the following information):**
 OS: windows idea
Version NACOS1.1.4

**Comment by horizonzy** [comment]
bro.pls reedit your title... the message is your log conifg's problem.LoggerContext already set name as 'nacos'. did you config  'otx' as your loggerContext name

**Comment by horizonzy** [comment]
bro.pls reedit your title... the message is your log conifg's problem.LoggerContext already set name as 'nacos'. did you config  'otx' as your loggerContext name

**Comment by KomachiSion** [comment]
duplicate with #3251
