### ISSUE TITLE
  Springboot integrates nacos startup error，ClassNotFoundException: com.alibaba.nacos.common.util.SystemUtils，version：2.2.3

### ISSUE THREAD

**Issue by j-dejavu** [alibaba/nacos#3948]
java.lang.NoClassDefFoundError: com/alibaba/nacos/common/util/SystemUtils
	at com.alibaba.nacos.core.listener.StartingSpringApplicationRunListener.environmentPrepared(StartingSpringApplicationRunListener.java:68)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:345)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.dejavu.gulimall.product.ProductServiceApplication.main(ProductServiceApplication.java:12)
Caused by: java.lang.ClassNotFoundException: com.alibaba.nacos.common.util.SystemUtils
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 7 common frames omitted

**Comment by horizonzy** [comment]
pls check your nacos-client version. this class already remove in recent version. maybe your nacos-client need previous version. try to reduce nacos-client's version and have a try.

**Comment by chuntaojun** [comment]
Nacos服务端启动出现的问题是吧，nacos目录下的plugin这个目录可以不要了，进行删除吧
