### ISSUE TITLE
no available server in Kubernetes Nacos 

### ISSUE THREAD

**Issue by zhengyanxiong** [alibaba/nacos#3960]
## Issue Description

Type: *bug report* 

### 2020-10-09 11:32:46.389   ---  [           main]  : [NACOS SocketTimeoutException httpGet] currentServerAddr:http://nacos.default.10.1.103.172.xip.io:80， err : Connect timed out 
2020-10-09 11:32:48.391   ---  [           main]  : [NACOS SocketTimeoutException httpGet] currentServerAddr:http://nacos.default.10.1.103.172.xip.io:80， err : Connect timed out 
2020-10-09 11:32:48.391   ---  [           main]  : no available server 

```
2020-10-09 11:32:48.394   ---  [           main]  : [fixed-nacos.default.10.1.103.172.xip.io_80-b1f595f8-d7f1-4385-8cbf-0f6d752c5ec8] [sub-server] get server config exception, dataId=rabbitmq.properties, group=DEFAULT_GROUP, tenant=b1f595f8-d7f1-4385-8cbf-0f6d752c5ec8 
 
java.net.ConnectException: no available server 
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpGet(ServerHttpAgent.java:123) 
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpGet(MetricsHttpAgent.java:48) 
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:230) 
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:143) 
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:92) 
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:85) 
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:74) 
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:204) 
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:191) 
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosConfiguration(NacosPropertySourceLocator.java:161) 
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadSharedConfiguration(NacosPropertySourceLocator.java:117) 
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:101) 
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:94) 
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:623) 
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:367) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) 
	at io.agilefast.gateway.AgileFastGatewayApplication.main(AgileFastGatewayApplication.java:13) 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64) 
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) 
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:51) 
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:52) 
```
### I deployed the nacos cluster in the Rancher+K3s environment. The nacos cluster can be accessed normally. However, the deployed service will have the above error on the node where the LEADER of nacos is located. In this Issues https://github.com/ alibaba/nacos/issues/2206, I followed the method inside to upgrade *spring-cloud-alibaba-dependencies* to *2.1.3.RELEASE*, but still did not solve this problem.
```
<dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.1.3.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
                <exclusions>
                    <exclusion>
                        <groupId>com.alibaba.nacos</groupId>
                        <artifactId>nacos-client</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
            <dependency>
                <groupId>com.alibaba.nacos</groupId>
                <artifactId>nacos-client</artifactId>
                <version>1.2.0</version>
            </dependency>
```

### My environment
. Spring Boot Version: 2.2.2.RELEASE
. Spring Clound Version: Greenwich.RELEASE
. Spring Cloud Alibaba Version: 2.1.3.RELEASE
. Nacos Version: 1.3.2
. Java : 1.8

> Explain: The http://nacos.default.10.1.103.172.xip.io:80 address here can be accessed normally, can access the nacos management interface, and can be registered normally on other machines, which is the entrance to the nacos cluster

**Comment by KomachiSion** [comment]
Can you check in nacos-server whether have error in logs?

Or check in `conf/cluster.conf` whether the cluster config is right?

**Comment by KomachiSion** [comment]
@zhengyanxiong Any response and process? If no more response we will close issue

**Comment by zhengyanxiong** [comment]
It should be that the cluster address is not properly configured. When I query the address configuration (conf/cluster.conf) of each node, the path displayed by each node is different, as shown below.
```
[root@node1 nacos]# for i in 0 1; do echo nacos-$i; kubectl exec nacos-$i cat conf/cluster.conf; done
nacos-0
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
#2020-10-14T18:55:35.634
nacos-0.nacos-headless.default.svc.cluster.local:8848
nacos-1
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
#2020-10-14T18:56:17.454
nacos-0.nacos-headless.default.svc.cluster.local:8848
nacos-1.nacos-headless.default.svc.cluster.local:8848
nacos-2.nacos-headless.default.svc.cluster.local:8848
```
When I restarted, the display is as follows, the configuration is normal.
```
[root@node1 nacos]# for i in 0 1 2; do echo nacos-$i; kubectl exec nacos-$i cat conf/cluster.conf; done
nacos-0
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
#2020-10-19T17:23:38.614
nacos-0.nacos-headless.default.svc.cluster.local:8848
nacos-1.nacos-headless.default.svc.cluster.local:8848
nacos-2.nacos-headless.default.svc.cluster.local:8848
nacos-1
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
#2020-10-19T17:24:31.206
nacos-0.nacos-headless.default.svc.cluster.local:8848
nacos-1.nacos-headless.default.svc.cluster.local:8848
nacos-2.nacos-headless.default.svc.cluster.local:8848
nacos-2
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
#2020-10-19T17:24:46.156
nacos-0.nacos-headless.default.svc.cluster.local:8848
nacos-1.nacos-headless.default.svc.cluster.local:8848
nacos-2.nacos-headless.default.svc.cluster.local:8848
```
Thank you very much. @KomachiSion
