### ISSUE TITLE
failed to req API:47.104.224.45:8848/nacos/v1/ns/instance/list

### ISSUE THREAD

**Issue by xh649225370** [alibaba/nacos#3971]
偶发性报错，nacos版本1.3.2
单机模式启动

com.alibaba.nacos.api.exception.NacosException: failed to req API:127.0.0.1:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:424)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:451)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:297)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:270)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Sc

**Comment by KomachiSion** [comment]
1. 检查nacos服务端是否有FullGc或者CMSGC
2. 检查本地连接数量是否达到上限导致无法建立新的请求连接
3. 检查nacos服务端的所有日志，看下当时是否有报错信息，如果有的话请贴出来
