### ISSUE TITLE
配置了如下的server-addr地址，nacos始终请求localhost:8848  ？？？

### ISSUE THREAD

**Issue by HyattJobs** [alibaba/nacos#3986]
配置了如下的server-addr地址，nacos始终请求localhost:8848
``` yml
server:
  port: 8000

spring:
  application:
    name: server-auth
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.247.132:8848        #这里是一个外部地址
      config:
        file-extension: yaml
        group: DEFAULT_GROUP
        prefix: ${spring.application.name}
```

控制台依然 打印请求 http://localhost:8848

``` 
 :: Spring Boot ::        (v2.3.4.RELEASE)

2020-10-13 10:28:19,218  INFO [ INFO ] [service-oauth,,,] 2377 --- [           main] c.a.n.c.c.impl.LocalConfigInfoProcessor  : LOCAL_SNAPSHOT_PATH:/root/nacos/config
2020-10-13 10:28:19,282  INFO [ INFO ] [service-oauth,,,] 2377 --- [           main] c.a.nacos.client.config.impl.Limiter     : limitTime:5.0
2020-10-13 10:28:19,351 ERROR [ ERROR] [service-oauth,,,] 2377 --- [           main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2020-10-13 10:28:19,495 ERROR [ ERROR] [service-oauth,,,] 2377 --- [           main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2020-10-13 10:28:19,696 ERROR [ ERROR] [service-oauth,,,] 2377 --- [           main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2020-10-13 10:28:19,895 ERROR [ ERROR] [service-oauth,,,] 2377 --- [           main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2020-10-13 10:28:19,897 ERROR [ ERROR] [service-oauth,,,] 2377 --- [           main] c.a.n.client.config.impl.ClientWorker    : [fixed-localhost_8848] [sub-server] get server config exception, dataId=service-oauth, group=DEFAULT_GROUP, tenant=

java.net.ConnectException: [NACOS HTTP-GET] The maximum number of tolerable server reconnection errors has been reached
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpGet(ServerHttpAgent.java:115)
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpGet(MetricsHttpAgent.java:48)
        at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:230)
        at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:143)
        at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:92)
        at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:85)
        at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:74)
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:204)
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:191)
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:142)
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:103)
        at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:52)
        at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47)
        at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:98)
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:626)
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:370)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:314)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at com.zkna.serviceoauth.ServiceOauthApplication.main(ServiceOauthApplication.java:19)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

2020-10-13 10:28:19,897  WARN [ WARN ] [service-oauth,,,] 2377 --- [           main] c.a.n.client.config.NacosConfigService   : [fixed-localhost_8848] [get-config] get from server error, dataId=service-oauth, group=DEFAULT_GROUP, tenant=, msg=ErrCode:500, ErrMsg:[NACOS HTTP-GET] The maximum number of tolerable server reconnection errors has been reached
2020-10-13 10:28:19,898  WARN [ WARN ] [service-oauth,,,] 2377 --- [           main] c.a.n.client.config.NacosConfigService   : [fixed-localhost_8848] [get-config] get snapshot ok, dataId=service-oauth, group=DEFAULT_GROUP, tenant=, config=
2020-10-13 10:28:19,898  WARN [ WARN ] [service-oauth,,,] 2377 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[service-oauth] & group[DEFAULT_GROUP]
2020-10-13 10:28:19,899 ERROR [ ERROR] [service-oauth,,,] 2377 --- [           main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2020-10-13 10:28:20,100 ERROR [ ERROR] [service-oauth,,,] 2377 --- [           main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2020-10-13 10:28:20,300 ERROR [ ERROR] [service-oauth,,,] 2377 --- [           main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
```
## nacos必须配置到本地么？

**Comment by Maijh97** [comment]
spring.cloud.nacos.config 项缺少server-addr的配置，参考帮助文档 https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html

**Comment by KomachiSion** [comment]
您只配置了nacos.discovery的地址，没有配置config的地址。

**Comment by HyattJobs** [comment]
> 您只配置了nacos.discovery的地址，没有配置config的地址。

谢了。

**Comment by HyattJobs** [comment]
> spring.cloud.nacos.config 项缺少server-addr的配置，参考帮助文档 https://nacos.io/zh-cn/docs/quick-start-spring-cloud.html
谢了

**Comment by liaobaikai** [comment]
发现windows版本没有这个问题，MAC版本有这个问题

**Comment by fangdengfu** [comment]
我这里时好时坏。  旧的开发机器上基本不会出这个。。 新来的人员or开发机就会偶尔冒这个。

config和discovery的server-addr都是配的。。 部分机器总是找localhost:8848

**Comment by XINJIN422** [comment]
https://github.com/alibaba/nacos/issues/4509#issuecomment-751987292

**Comment by aomsir** [comment]
> 发现windows版本没有这个问题，MAC版本有这个问题

macOS确实有这个问题
