### ISSUE TITLE
集群模式内置数据源启动有时候出现启动失败  一直Nacos is starting

### ISSUE THREAD

**Issue by MarkBellCN** [alibaba/nacos#3991]
version 1.3.2
集群模式内置数据源启动有时候出现启动失败  一直Nacos is starting...  
2020-10-15 08:29:03,831 INFO Nacos is starting...

2020-10-15 08:29:04,413 ERROR Event listener exception : {}

java.lang.NullPointerException: null
	at com.alibaba.nacos.common.notify.DefaultSharePublisher.receiveEvent(DefaultSharePublisher.java:101)
	at com.alibaba.nacos.common.notify.DefaultPublisher.openEventHandler(DefaultPublisher.java:117)
	at com.alibaba.nacos.common.notify.DefaultPublisher.run(DefaultPublisher.java:94)
2020-10-15 08:29:04,836 INFO Nacos is starting...

**Comment by KomachiSion** [comment]
看一下protocol-raft.log 和 alipay-jraft.log 有没有错误。
如果一直在starting很可能是jraft启动或者加载失败了

**Comment by MarkBellCN** [comment]
只启用了naming 然后只有一个节点
java.lang.IllegalArgumentException: Blank leader
  at com.alipay.sofa.jraft.util.Requires.requireTrue(Requires.java:85)
  at com.alipay.sofa.jraft.RouteTable.updateLeader(RouteTable.java:181)
  at com.alipay.sofa.jraft.RouteTable.refreshLeader(RouteTable.java:264)
  at com.alipay.sofa.jraft.RouteTable.refreshConfiguration(RouteTable.java:298)
  at com.alibaba.nacos.core.distributed.raft.JRaftServer.refreshRouteTable(JRaftServer.java:500)
  at com.alibaba.nacos.core.distributed.raft.JRaftServer.lambda$createMultiRaftGroup$1(JRaftServer.java:276)
  at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
  at java.util.concurrent.FutureTask.runAndReset(Unknown Source)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(Unknown Source)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
  at java.lang.Thread.run(Unknown Source)
2020-10-15 15:40:45,481 ERROR Fail to refresh route configuration for group : nacos_config, error is : {}

**Comment by KomachiSion** [comment]
单节点启动建议用命令` startup.sh -m standalone -f naming`

**Comment by SammyZheng** [comment]
2020-10-17 20:28:16,867 ERROR Event listener exception : {}

java.lang.NullPointerException: null
	at com.alibaba.nacos.common.notify.DefaultSharePublisher.receiveEvent(DefaultSharePublisher.java:101)
	at com.alibaba.nacos.common.notify.DefaultPublisher.openEventHandler(DefaultPublisher.java:117)
	at com.alibaba.nacos.common.notify.DefaultPublisher.run(DefaultPublisher.java:94)
遇到了同样的问题

**Comment by KomachiSion** [comment]
> 2020-10-17 20:28:16,867 ERROR Event listener exception : {}
> 
> java.lang.NullPointerException: null
> at com.alibaba.nacos.common.notify.DefaultSharePublisher.receiveEvent(DefaultSharePublisher.java:101)
> at com.alibaba.nacos.common.notify.DefaultPublisher.openEventHandler(DefaultPublisher.java:117)
> at com.alibaba.nacos.common.notify.DefaultPublisher.run(DefaultPublisher.java:94)
> 遇到了同样的问题

这个问题没有关系，1.4.0会修复，且这个问题不会导致启动阻塞。 问题是raft选主失败导致的。

**Comment by KomachiSion** [comment]
No more response from author, and it seems no a problem.

The reason is that if start server by cluster mode, raft need to choose leader first, if failed will not provide server.
And user only start one node, it can't choose leader, because raft need more than half node vote. So still staring.
