### ISSUE TITLE
Public Key Retrieval is not allowed

### ISSUE THREAD

**Issue by xiao-ma-nong** [alibaba/nacos#4040]
`Caused by: com.mysql.cj.exceptions.CJException: Public Key Retrieval is not allowed
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:124)
	at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:151)
	at com.mysql.cj.protocol.a.authentication.CachingSha2PasswordPlugin.nextAuthenticationStep(CachingSha2PasswordPlugin.java:49)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.proceedHandshakeWithPluggableAuthentication(NativeAuthenticationProvider.java:596)
	at com.mysql.cj.protocol.a.NativeAuthenticationProvider.connect(NativeAuthenticationProvider.java:202)
	at com.mysql.cj.protocol.a.NativeProtocol.connect(NativeProtocol.java:1452)
	at com.mysql.cj.NativeSession.connect(NativeSession.java:165)
	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:849)`

------------------------------------------
nacos1.3.2 连接mysql8.0 

   早上启动还好好的，然后现在启动nacos报

**Comment by horizonzy** [comment]
参考一下这个 https://blog.csdn.net/u013360850/article/details/80373604

**Comment by KomachiSion** [comment]
I think it's not nacos' problem. It might be MySQL or env problem.

**Comment by xiao-ma-nong** [comment]
莫名奇妙的又好了，不知道是不是第一次mysql没启动连接mysql的问题失败
多次重启nacos跟mysql就好了

**Comment by wuyb518** [comment]
> 莫名奇妙的又好了，不知道是不是第一次mysql没启动连接mysql的问题失败
> 多次重启nacos跟mysql就好了

Add `allowPublicKeyRetrieval=true` to jdbc conneciton string maybe help you, the reference doc is https://mysqlconnector.net/connection-options/

**Comment by xiao-ma-nong** [comment]
> > 莫名奇妙的又好了，不知道是不是第一次mysql没启动连接mysql的问题失败
> > 多次重启nacos跟mysql就好了
> 
> 添加`allowPublicKeyRetrieval=true`到jdbc连接字符串可能会帮助您，参考文档为https://mysqlconnector.net/connection-options/

已经解决了

**Comment by xiao-ma-nong** [comment]
> 参考一下这个 https://blog.csdn.net/u013360850/article/details/80373604
在连接地址加个 
`allowPublicKeyRetrieval=true`
就可以了

**Comment by hsingpuwoo** [comment]
如果是K8s集群部署的 如何解决呢  configmap不是这样的字符串拼接
