### ISSUE TITLE
nacos,服务间调用相对比较频繁,会OOM。

### ISSUE THREAD

**Issue by hujiang75277381** [alibaba/nacos#4042]
下面是栈信息：
java.lang.OutOfMemoryError: Java heap space
	at sun.net.www.http.ChunkedInputStream.<init>(ChunkedInputStream.java:81)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:890)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.alibaba.nacos.client.naming.net.HttpClient.getResult(HttpClient.java:114)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:91)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:413)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:454)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:300)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:279)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:325)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by horizonzy** [comment]
这个是你客户端内存达到阈值了。刚好一个http请求，把你的应用压死了，你把你的应用的内存加大一点。

**Comment by KomachiSion** [comment]
能dump一下堆内存分析一下吗？看看是不是nacos的对象导致的OOM，很可能是应用业务逻辑中有内存泄漏，或者内存太小设置太小，刚好nacos发起新请求时触发了。

**Comment by KomachiSion** [comment]
No response from author and current information is not enough to judge whether is nacos' problem. Close issue.
