### ISSUE TITLE
nacos-node: ERROR [NACOS-RAFT] Error while handling notifying task

### ISSUE THREAD

**Issue by lkzlee** [alibaba/nacos#4071]
Nacos reports an error after startup, and the status of the three nodes are as follows:

nacos-0.nacos- headless.default.svc . cluster.local:8848   UP         Node metadata

nacos-1.nacos- headless.default.svc . cluster.local:8848   DOWN  Node metadata

nacos-2.nacos- headless.default.svc . cluster.local:8848   UP         Node metadata

error detail：

nacos-0 error log：

2020-10-27 10:22:03,656 ERROR NACOS-RAFT error while sending heart-beat to peer: nacos-1.nacos-headless.default.svc.cluster.local:8848 {}
java.net.ConnectException: Connection refused: nacos-1.nacos-headless.default.svc.cluster.local/10.244.85.222:8848 to http://nacos-1.nacos-headless.default.svc.cluster.local:8848/nacos/v1/ns/raft/beat
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:380)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

nacos-1 error log：
2020-10-27 10:11:35,397 ERROR [NACOS-RAFT] Error while handling notifying task

java.lang.InterruptedException: null
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
	at java.util.concurrent.LinkedBlockingQueue.take(LinkedBlockingQueue.java:442)
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore$Notifier.run(RaftCore.java:1052)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by KomachiSion** [comment]
It seems that nacos-1 start failed so that it can't provide service.

Your logs are async operation, which is not the true error. Please check nacos.log and start.log in nacos-1. The true error should in there.

**Comment by KomachiSion** [comment]
No enough information to judge what's the problem and no response from author. Close issue.
