### ISSUE TITLE
单机模式启动失败，报db.num is null等错误

### ISSUE THREAD

**Issue by Yanwenjingcn** [alibaba/nacos#4074]
代码从git上拉取下来直接单机模式启动，**mac上成功执行，但是在linux上失败了**

版本：
nacos1.4.0+jdk1.8.0_251

报错如下:
1、db.num is null（好像是有内置的存储结构，不需要mysql吧）
java.io.IOException: java.lang.IllegalArgumentException: db.num is null
        at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl.reload(ExternalDataSourceServiceImpl.java:141)
        at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl.init(ExternalDataSourceServiceImpl.java:115)
        at com.alibaba.nacos.config.server.service.datasource.DynamicDataSource.getDataSource(DynamicDataSource.java:53)
        at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.init(ExternalStoragePersistServiceImpl.java:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)

2、Unable to start embedded Tomcat
org.springframework.context.ApplicationContextException: Unable to start web server; nested exception is org.springframework.boot.web.server.WebServerException: Unable to start embedded Tomcat
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:156)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:544)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
        at com.alibaba.nacos.Nacos.main(Nacos.java:35)

3、
        ... 21 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.springframework.boot.web.servlet.FilterRegistrationBean]: Factory method 'authFilterRegistration' threw exception; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authFilter': Unsatisfied dependency expressed through field 'authManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosAuthManager': Unsatisfied dependency expressed through field 'authenticationManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosAuthConfig': Unsatisfied dependency expressed through field 'userDetailsService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosUserDetailsServiceImpl': Unsatisfied dependency expressed through field 'userPersistService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'externalUserPersistServiceImpl': Unsatisfied dependency expressed through field 'persistService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalStoragePersistServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:622)
        ... 61 common frames omitted
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'authFilter': Unsatisfied dependency expressed through field 'authManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosAuthManager': Unsatisfied dependency expressed through field 'authenticationManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosAuthConfig': Unsatisfied dependency expressed through field 'userDetailsService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosUserDetailsServiceImpl': Unsatisfied dependency expressed through field 'userPersistService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'externalUserPersistServiceImpl': Unsatisfied dependency expressed through field 'persistService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalStoragePersistServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:598)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1402)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:591)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)

**Comment by horizonzy** [comment]
检查一下是否配置了spring.datasource.platform=mysql

**Comment by ZhangShaoWu** [comment]
没有配置数据库

**Comment by horizonzy** [comment]
确认一下conf/application.properties文件呢。看看里面是否配置了spring.datasource.platform=mysql

**Comment by jinchaofeiyang** [comment]
1.3.2版本 cmd startup.cmd -m standalone 启动失败 提示jdbc.properties找不到 db.num没配置等错误提示

**Comment by jinchaofeiyang** [comment]
> 检查一下是否配置了spring.datasource.platform=mysql

下载的1.3.2的zip解压的 没有修改任何配置

**Comment by KomachiSion** [comment]
@Yanwenjingcn  查看一下配置文件吧，我拿1.3.2和1.4.0-BETA的包都试了一下，都是正常的启动。

你发出的报错信息位置就是读取到了外部数据库，如果是单机启动的就是`spring.datasource.platform=mysql` 或者没有按照单机模式启动

**Comment by Yanwenjingcn** [comment]
> @Yanwenjingcn 查看一下配置文件吧，我拿1.3.2和1.4.0-BETA的包都试了一下，都是正常的启动。
> 
> 你发出的报错信息位置就是读取到了外部数据库，如果是单机启动的就是`spring.datasource.platform=mysql` 或者没有按照单机模式启动

哥，天地良心，咱代码拉取下来啥也没动，直接单机模式启动。我试了一台mac、两台linux，在linux上都是报db.num is null，后来我妥协了，配置了mysql就好了。

**Comment by horizonzy** [comment]
> > @Yanwenjingcn 查看一下配置文件吧，我拿1.3.2和1.4.0-BETA的包都试了一下，都是正常的启动。
> > 你发出的报错信息位置就是读取到了外部数据库，如果是单机启动的就是`spring.datasource.platform=mysql` 或者没有按照单机模式启动
> 
> 哥，天地良心，咱代码拉取下来啥也没动，直接单机模式启动。我试了一台mac、两台linux，在linux上都是报db.num is null，后来我妥协了，配置了mysql就好了。

老铁。能发一下你用的那个包吗

**Comment by KomachiSion** [comment]
> > @Yanwenjingcn 查看一下配置文件吧，我拿1.3.2和1.4.0-BETA的包都试了一下，都是正常的启动。
> > 你发出的报错信息位置就是读取到了外部数据库，如果是单机启动的就是`spring.datasource.platform=mysql` 或者没有按照单机模式启动
> 
> 哥，天地良心，咱代码拉取下来啥也没动，直接单机模式启动。我试了一台mac、两台linux，在linux上都是报db.num is null，后来我妥协了，配置了mysql就好了。

我的意思是我没有办法复现你的问题，我们需要更新信息。 提供application.conf文件内容或者更加详细的环境信息和复现步骤。

**Comment by fanzihao** [comment]
你的版本应该默认是集群方式启动，修改startup.cmd文件为单节点启动，应该就好了。
![image](https://user-images.githubusercontent.com/46786409/97418712-170b0200-1944-11eb-83ca-e925c3dd345b.png)

**Comment by horizonzy** [comment]
> > @Yanwenjingcn 查看一下配置文件吧，我拿1.3.2和1.4.0-BETA的包都试了一下，都是正常的启动。
> > 你发出的报错信息位置就是读取到了外部数据库，如果是单机启动的就是`spring.datasource.platform=mysql` 或者没有按照单机模式启动
> 
> 哥，天地良心，咱代码拉取下来啥也没动，直接单机模式启动。我试了一台mac、两台linux，在linux上都是报db.num is null，后来我妥协了，配置了mysql就好了。

单机模式启动是不是没有加上参数. -m standalone

**Comment by Yanwenjingcn** [comment]
> > > @Yanwenjingcn 查看一下配置文件吧，我拿1.3.2和1.4.0-BETA的包都试了一下，都是正常的启动。
> > > 你发出的报错信息位置就是读取到了外部数据库，如果是单机启动的就是`spring.datasource.platform=mysql` 或者没有按照单机模式启动
> > 
> > 
> > 哥，天地良心，咱代码拉取下来啥也没动，直接单机模式启动。我试了一台mac、两台linux，在linux上都是报db.num is null，后来我妥协了，配置了mysql就好了。
> 
> 我的意思是我没有办法复现你的问题，我们需要更新信息。 提供application.conf文件内容或者更加详细的环境信息和复现步骤。

一、系统信息：

Linux version 2.6.32-754.27.1.el6.x86_64 (mockbuild@x86-02.bsys.centos.org) (gcc version 4.4.7 20120313 (Red Hat 4.4.7-23) (GCC) ) #1 SMP Tue Jan 28 14:11:45 UTC 2020

Linux 2.6.32-754.27.1.el6.x86_64 #1 SMP Tue Jan 28 14:11:45 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

二、软件包

从你们git上提供的位置下载的，开箱即用
https://github.com/alibaba/nacos/releases/tag/1.4.0-BETA
nacos-server-1.4.0-BETA.tar.gz

**_忘了说，我mac那台能启动用的软件包是我自己编译的，linux上用的是我懒得装maven，直接下载你们提供的。_**

**_看我！看我！看我！
springboot+nacos-config-sping-boot-starter 0.2.7 我在nacos上更新的配置，不能自动刷新到springboot应用里。_**


三、application.properties

#*************** Spring Boot Related Configurations ***************#
### Default web context path:
server.servlet.contextPath=/nacos
### Default web server port:
server.port=8848

#*************** Network Related Configurations ***************#
### If prefer hostname over ip for Nacos server addresses in cluster.conf:
# nacos.inetutils.prefer-hostname-over-ip=false

### Specify local server's IP:
# nacos.inetutils.ip-address=


#*************** Config Module Related Configurations ***************#
### If use MySQL as datasource:
# spring.datasource.platform=mysql

### Count of DB:
# db.num=1

### Connect URL of DB:
# db.url.0=jdbc:mysql://127.0.0.1:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
# db.user=nacos
# db.password=nacos


#*************** Naming Module Related Configurations ***************#
### Data dispatch task execution period in milliseconds:
# nacos.naming.distro.taskDispatchPeriod=200

### Data count of batch sync task:
# nacos.naming.distro.batchSyncKeyCount=1000

### Retry delay in milliseconds if sync task failed:
# nacos.naming.distro.syncRetryDelay=5000

### If enable data warmup. If set to false, the server would accept request without local data preparation:
# nacos.naming.data.warmup=true

### If enable the instance auto expiration, kind like of health check of instance:
# nacos.naming.expireInstance=true

nacos.naming.empty-service.auto-clean=true
nacos.naming.empty-service.clean.initial-delay-ms=50000
nacos.naming.empty-service.clean.period-time-ms=30000


#*************** CMDB Module Related Configurations ***************#
### The interval to dump external CMDB in seconds:
# nacos.cmdb.dumpTaskInterval=3600

### The interval of polling data change event in seconds:
# nacos.cmdb.eventTaskInterval=10

### The interval of loading labels in seconds:
# nacos.cmdb.labelTaskInterval=300

### If turn on data loading task:
# nacos.cmdb.loadDataAtStart=false


#*************** Metrics Related Configurations ***************#
### Metrics for prometheus
#management.endpoints.web.exposure.include=*

### Metrics for elastic search
management.metrics.export.elastic.enabled=false
#management.metrics.export.elastic.host=http://localhost:9200

### Metrics for influx
management.metrics.export.influx.enabled=false
#management.metrics.export.influx.db=springboot
#management.metrics.export.influx.uri=http://localhost:8086
#management.metrics.export.influx.auto-create-db=true
#management.metrics.export.influx.consistency=one
#management.metrics.export.influx.compressed=true


#*************** Access Log Related Configurations ***************#
### If turn on the access log:
server.tomcat.accesslog.enabled=true

### The access log pattern:
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i

### The directory of access log:
server.tomcat.basedir=


#*************** Access Control Related Configurations ***************#
### If enable spring security, this option is deprecated in 1.2.0:
#spring.security.enabled=false

### The ignore urls of auth, is deprecated in 1.2.0:
nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-fe/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**

### The auth system to use, currently only 'nacos' is supported:
nacos.core.auth.system.type=nacos

### If turn on auth system:
nacos.core.auth.enabled=true

### The token expiration in seconds:
nacos.core.auth.default.token.expire.seconds=18000

### The default token:
nacos.core.auth.default.token.secret.key=SecretKey012345678901234567890123456789012345678901234567890123456789

### Turn on/off caching of auth information. By turning on this switch, the update of auth information would have a 15 seconds delay.
nacos.core.auth.caching.enabled=true


#*************** Istio Related Configurations ***************#
### If turn on the MCP server:
nacos.istio.mcp.server.enabled=false



###*************** Add from 1.3.0 ***************###


#*************** Core Related Configurations ***************#

### set the WorkerID manually
# nacos.core.snowflake.worker-id=

### Member-MetaData
# nacos.core.member.meta.site=
# nacos.core.member.meta.adweight=
# nacos.core.member.meta.weight=

### MemberLookup
### Addressing pattern category, If set, the priority is highest
# nacos.core.member.lookup.type=[file,address-server]
## Set the cluster list with a configuration file or command-line argument
# nacos.member.list=192.168.16.101:8847?raft_port=8807,192.168.16.101?raft_port=8808,192.168.16.101:8849?raft_port=8809
## for AddressServerMemberLookup
# Maximum number of retries to query the address server upon initialization
# nacos.core.address-server.retry=5
## Server domain name address of [address-server] mode
# address.server.domain=jmenv.tbsite.net
## Server port of [address-server] mode
# address.server.port=8080
## Request address of [address-server] mode
# address.server.url=/nacos/serverlist

#*************** JRaft Related Configurations ***************#

### Sets the Raft cluster election timeout, default value is 5 second
# nacos.core.protocol.raft.data.election_timeout_ms=5000
### Sets the amount of time the Raft snapshot will execute periodically, default is 30 minute
# nacos.core.protocol.raft.data.snapshot_interval_secs=30
### raft internal worker threads
# nacos.core.protocol.raft.data.core_thread_num=8
### Number of threads required for raft business request processing
# nacos.core.protocol.raft.data.cli_service_thread_num=4
### raft linear read strategy. Safe linear reads are used by default, that is, the Leader tenure is confirmed by heartbeat
# nacos.core.protocol.raft.data.read_index_type=ReadOnlySafe
### rpc request timeout, default 5 seconds
# nacos.core.protocol.raft.data.rpc_request_timeout_ms=5000


我不知道git issue里面怎么上传文件，不然我可以直接把我的软件包给你们。

**Comment by Yanwenjingcn** [comment]
> > > @Yanwenjingcn 查看一下配置文件吧，我拿1.3.2和1.4.0-BETA的包都试了一下，都是正常的启动。
> > > 你发出的报错信息位置就是读取到了外部数据库，如果是单机启动的就是`spring.datasource.platform=mysql` 或者没有按照单机模式启动
> > 
> > 
> > 哥，天地良心，咱代码拉取下来啥也没动，直接单机模式启动。我试了一台mac、两台linux，在linux上都是报db.num is null，后来我妥协了，配置了mysql就好了。
> 
> 单机模式启动是不是没有加上参数. -m standalone

加了哈，这个有认真看文档

**Comment by Yanwenjingcn** [comment]
> 你的版本应该默认是集群方式启动，修改startup.cmd文件为单节点启动，应该就好了。
> ![image](https://user-images.githubusercontent.com/46786409/97418712-170b0200-1944-11eb-83ca-e925c3dd345b.png)

看了下，脚本是默认集群，但是我是sh startup.sh -m standalone 启动的

**Comment by horizonzy** [comment]
加个钉钉呢。老铁，看下这个包



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Wengie <notifications@github.com&gt;
发送时间: 2020年10月29日 20:50
收件人: alibaba/nacos <nacos@noreply.github.com&gt;
抄送: 赵延 <1060026287@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[alibaba/nacos] 单机模式启动失败，报db.num is null等错误 (#4074)

**Comment by Yanwenjingcn** [comment]
> 加个钉钉呢。老铁，看下这个包 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Wengie <notifications@github.com&gt; 发送时间: 2020年10月29日 20:50 收件人: alibaba/nacos <nacos@noreply.github.com&gt; 抄送: 赵延 <1060026287@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[alibaba/nacos] 单机模式启动失败，报db.num is null等错误 (#4074)
t1x_b0mmv87sk

**Comment by Yanwenjingcn** [comment]
> 加个钉钉呢。老铁，看下这个包 

t1x_b0mmv87sk

**Comment by Yanwenjingcn** [comment]
> 加个钉钉呢。老铁，看下这个包 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: Wengie <notifications@github.com&gt; 发送时间: 2020年10月29日 20:50 收件人: alibaba/nacos <nacos@noreply.github.com&gt; 抄送: 赵延 <1060026287@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[alibaba/nacos] 单机模式启动失败，报db.num is null等错误 (#4074)

t1x_b0mmv87sk

**Comment by Yanwenjingcn** [comment]
> > 加个钉钉呢。老铁，看下这个包 发自我的iPhone
> > […](#)
> > ------------------ 原始邮件 ------------------ 发件人: Wengie <[notifications@github.com](mailto:notifications@github.com)> 发送时间: 2020年10月29日 20:50 收件人: alibaba/nacos <[nacos@noreply.github.com](mailto:nacos@noreply.github.com)> 抄送: 赵延 <[1060026287@qq.com](mailto:1060026287@qq.com)>, Comment <[comment@noreply.github.com](mailto:comment@noreply.github.com)> 主题: 回复：[alibaba/nacos] 单机模式启动失败，报db.num is null等错误 (#4074)
> 
> t1x_b0mmv87sk

是不是每个公司的数据都有个horizon，哈哈

**Comment by horizonzy** [comment]
user use `sh startup.sh -m standalone` again, it works well. Maybe `standalone` typo before.

**Comment by xbr1dge** [comment]
我也遇到你这个问题了,直接下载解压;
输入 sh startup.sh -m standalone 进行单机模式启动,但是他还是以集群方式启动 nacos is starting with cluster;
打开logs查看是报 db.num is null;
后面我修改了一下 startup.sh 脚本;
set MODE="cluster" -> set MODE="standalone" ;
使用 sh startup.sh 命令不加 -m standalone 就启动成功了

**Comment by horizonzy** [comment]
> 我也遇到你这个问题了,直接下载解压;
> 输入 sh startup.sh -m standalone 进行单机模式启动,但是他还是以集群方式启动 nacos is starting with cluster;
> 打开logs查看是报 db.num is null;
> 后面我修改了一下 startup.sh 脚本;
> set MODE="cluster" -> set MODE="standalone" ;
> 使用 sh startup.sh 命令不加 -m standalone 就启动成功了

-m standalone == set MODE="standalone". 确认下是不是自己拼错了，-m standalone，有很多人其实都是拼错了

**Comment by xbr1dge** [comment]
> > 我也遇到你这个问题了,直接下载解压;
> > 输入 sh startup.sh -m standalone 进行单机模式启动,但是他还是以集群方式启动 nacos is starting with cluster;
> > 打开logs查看是报 db.num is null;
> > 后面我修改了一下 startup.sh 脚本;
> > set MODE="cluster" -> set MODE="standalone" ;
> > 使用 sh startup.sh 命令不加 -m standalone 就启动成功了
> 
> -m standalone == set MODE="standalone". 确认下是不是自己拼错了，-m standalone，有很多人其实都是拼错了

我是直接copy官网的应该不会错

**Comment by zhangdaxian87** [comment]
windows下命令启动 bin目录下："startup.cmd" -m standalone

**Comment by xiaojie119120** [comment]
#!/bin/sh 不能识别"[[]]"符号，可以把#!/bin/sh改成#! /bin/bash

**Comment by wwjjqd** [comment]
不要用sh startup.sh -m standalone 直接./startup.sh -m standalone  linux上用sh无法识别[[]] 会造成无法以单机形式启动 所以就会读数据库了

**Comment by wiviam** [comment]
> 不要用sh startup.sh -m standalone 直接./startup.sh -m standalone linux上用sh无法识别[[]] 会造成无法以单机形式启动 所以就会读数据库了

正解，thx
