### ISSUE TITLE
1.3.0 & 1.3.2 版本在Ubuntu上使用服务配置nacos-config，创建命名空间失败，提示Required String parameter 'customNamespaceId' is not present

### ISSUE THREAD

**Issue by LcmBlog** [alibaba/nacos#4108]
**org.springframework.web.bind.MissingServletRequestParameterException: Required String parameter 'customNamespaceId' is not present**
	at org.springframework.web.method.annotation.RequestParamMethodArgumentResolver.handleMissingValue(RequestParamMethodArgumentResolver.java:202)
	at org.springframework.web.method.annotation.AbstractNamedValueMethodArgumentResolver.resolveArgument(AbstractNamedValueMethodArgumentResolver.java:113)
	at org.springframework.web.method.support.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:126)
	at org.springframework.web.method.support.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:166)

**Comment by KomachiSion** [comment]
清理浏览器缓存再试。

**Comment by LcmBlog** [comment]
原来真的是缓存问题，害，谢谢大佬。

**Comment by LcmBlog** [comment]
> 清理浏览器缓存再试。

原来真的是缓存问题，害，谢谢大佬

**Comment by yinminghui** [comment]
> > 清理浏览器缓存再试。
> 
> 原来真的是缓存问题，害，谢谢大佬

是清理登入nacos服务的游览器吗
