### ISSUE TITLE
Failed to request , connect time out

### ISSUE THREAD

**Issue by liuzwei** [alibaba/nacos#4139]
## Issue Description

错误日志:

`
2020-11-05 00:18:57.875 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to request
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
        at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:86)
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:433)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:482)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:401)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:397)
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:321)
        at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:281)
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:327)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
`

### Describe what happened (or what feature you want)

使用的是单机nacos，这个connect time out 不定时出现。

### Tell us your environment

CentOS Linux release 7.6.1810
java version "1.8.0_201"
nacos 内存分配： -Xms2g -Xmx2g -Xmn1g
nacos version：1.2.1
目前大约是20个模块服务，服务之间采用dubbo

现在没有排查方向，不知道为什么会一直报这个错，烦请指导，谢谢！

**Comment by KomachiSion** [comment]
1. 查看一下连接数，包含nacos server的机器和应用所在的机器。
2. 是否当时存在网络抖动等问题
3. 可以适当调高nacos server的tomcat 最大连接数，连接并发数等参数，调整方式参照spring-boot embedded tomcat的配置方式。
4. 在你的应用启动时添加-Dcom.alibaba.nacos.client.naming.ctimeout 参数调高连接超时时间

**Comment by liuzwei** [comment]
> 1. 查看一下连接数，包含nacos server的机器和应用所在的机器，是否有过多连接导致新连接无法建立。
> 2. 是否当时存在网络抖动等问题
> 3. 可以适当调高nacos server的tomcat 最大连接数，连接并发数等参数，调整方式参照spring-boot embedded tomcat的配置方式。
> 4. 在你的应用启动时添加-Dcom.alibaba.nacos.client.naming.ctimeout 参数调高连接超时时间，默认是3s的超时时间

非常感谢，我实验一下！

**Comment by mylonelyplanet** [comment]
> > 1. 查看一下连接数，包含nacos server的机器和应用所在的机器，是否有过多连接导致新连接无法建立。
> > 2. 是否当时存在网络抖动等问题
> > 3. 可以适当调高nacos server的tomcat 最大连接数，连接并发数等参数，调整方式参照spring-boot embedded tomcat的配置方式。
> > 4. 在你的应用启动时添加-Dcom.alibaba.nacos.client.naming.ctimeout 参数调高连接超时时间，默认是3s的超时时间
> 
> 非常感谢，我实验一下！

请问，最终问题是怎么解决的？我们也有类似的问题

**Comment by zhousheng2** [comment]
遇到同样的问题，nacos是1.3.2版本

**Comment by jerryduan** [comment]
我出现这样的问题，是因为集群中有一个实例启动失败导致的
