### ISSUE TITLE
springcloud Alibaba+dubbo+nacos+k8s, 容器启动时有时候报死锁

### ISSUE THREAD

**Issue by liuhonglin** [alibaba/nacos#4147]
```

Found one Java-level deadlock:
=============================
"com.alibaba.nacos.naming.client.listener":
  waiting to lock monitor 0x00007f097009c558 (object 0x00000000c113a5e0, a java.util.concurrent.ConcurrentHashMap),
  which is held by "main"
"main":
  waiting to lock monitor 0x00007f09d0003b98 (object 0x00000000c236fc48, a org.apache.dubbo.registry.integration.RegistryDirectory),
  which is held by "com.alibaba.nacos.naming.client.listener"

Java stack information for the threads listed above:
===================================================
"com.alibaba.nacos.naming.client.listener":
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:183)
	- waiting to lock <0x00000000c113a5e0> (a java.util.concurrent.ConcurrentHashMap)
	at org.springframework.beans.factory.support.AbstractBeanFactory.isTypeMatch(AbstractBeanFactory.java:517)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doGetBeanNamesForType(DefaultListableBeanFactory.java:533)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:505)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBeanNamesForType(DefaultListableBeanFactory.java:491)
	at org.springframework.context.support.AbstractApplicationContext.getBeanNamesForType(AbstractApplicationContext.java:1230)
	at org.springframework.beans.factory.BeanFactoryUtils.beanNamesForTypeIncludingAncestors(BeanFactoryUtils.java:228)
	at com.alibaba.spring.util.BeanFactoryUtils.getBeans(BeanFactoryUtils.java:80)
	at com.alibaba.spring.util.BeanFactoryUtils.getOptionalBean(BeanFactoryUtils.java:59)
	at org.apache.dubbo.config.spring.extension.SpringExtensionFactory.getExtension(SpringExtensionFactory.java:69)
	at org.apache.dubbo.common.extension.factory.AdaptiveExtensionFactory.getExtension(AdaptiveExtensionFactory.java:47)
	at org.apache.dubbo.common.extension.ExtensionLoader.injectExtension(ExtensionLoader.java:657)
	at org.apache.dubbo.common.extension.ExtensionLoader.createExtension(ExtensionLoader.java:614)
	at org.apache.dubbo.common.extension.ExtensionLoader.getExtension(ExtensionLoader.java:405)
	- locked <0x00000000c27b69c8> (a org.apache.dubbo.common.utils.Holder)
	at org.apache.dubbo.common.extension.ExtensionLoader.getActivateExtension(ExtensionLoader.java:264)
	at org.apache.dubbo.common.extension.ExtensionLoader.getActivateExtension(ExtensionLoader.java:228)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.buildInvokerChain(ProtocolFilterWrapper.java:54)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:161)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.registry.integration.RegistryDirectory.toInvokers(RegistryDirectory.java:455)
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshInvoker(RegistryDirectory.java:312)
	at org.apache.dubbo.registry.integration.RegistryDirectory.refreshOverrideAndInvoker(RegistryDirectory.java:271)
	at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:254)
	- locked <0x00000000c236fc48> (a org.apache.dubbo.registry.integration.RegistryDirectory)
	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:426)
	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:373)
	at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:364)
	at org.apache.dubbo.registry.nacos.NacosRegistry.notifySubscriber(NacosRegistry.java:445)
	at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$subscribeEventListener$10(NacosRegistry.java:425)
	at org.apache.dubbo.registry.nacos.NacosRegistry$$Lambda$525/2033490785.onEvent(Unknown Source)
	at com.alibaba.nacos.client.naming.core.EventDispatcher$Notifier.run(EventDispatcher.java:132)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"main":
	at org.apache.dubbo.registry.integration.RegistryDirectory.notify(RegistryDirectory.java:230)
	- waiting to lock <0x00000000c236fc48> (a org.apache.dubbo.registry.integration.RegistryDirectory)
	at org.apache.dubbo.registry.support.AbstractRegistry.notify(AbstractRegistry.java:426)
	at org.apache.dubbo.registry.support.FailbackRegistry.doNotify(FailbackRegistry.java:373)
	at org.apache.dubbo.registry.support.FailbackRegistry.notify(FailbackRegistry.java:364)
	at org.apache.dubbo.registry.nacos.NacosRegistry.notifySubscriber(NacosRegistry.java:445)
	at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doSubscribe$3(NacosRegistry.java:175)
	at org.apache.dubbo.registry.nacos.NacosRegistry$$Lambda$524/784422651.callback(Unknown Source)
	at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:499)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:169)
	at org.apache.dubbo.registry.nacos.NacosRegistry.doSubscribe(NacosRegistry.java:165)
	at org.apache.dubbo.registry.support.FailbackRegistry.subscribe(FailbackRegistry.java:299)
	at org.apache.dubbo.registry.ListenerRegistryWrapper.subscribe(ListenerRegistryWrapper.java:105)
	at org.apache.dubbo.registry.integration.RegistryDirectory.subscribe(RegistryDirectory.java:185)
	at org.apache.dubbo.registry.integration.RegistryProtocol.doRefer(RegistryProtocol.java:429)
	at org.apache.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:410)
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:70)
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:73)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:159)
	at org.apache.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at org.apache.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:318)
	at org.apache.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:258)
	- locked <0x00000000c2277de8> (a org.apache.dubbo.config.spring.ReferenceBean)
	at org.apache.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:158)
	- locked <0x00000000c2277de8> (a org.apache.dubbo.config.spring.ReferenceBean)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.getOrCreateProxy(ReferenceAnnotationBeanPostProcessor.java:274)
	at org.apache.dubbo.config.spring.beans.factory.annotation.ReferenceAnnotationBeanPostProcessor.doGetInjectedBean(ReferenceAnnotationBeanPostProcessor.java:143)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:359)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:539)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:130)
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:142)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1427)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:594)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
	at org.springframework.beans.factory.support.AbstractBeanFactory$$Lambda$189/1495454697.getObject(Unknown Source)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:226)
	- locked <0x00000000c113a5e0> (a java.util.concurrent.ConcurrentHashMap)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:895)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	- locked <0x00000000c10fd428> (a java.lang.Object)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.sdiread.backend.usergroup.dubbo.UserGroupDubboApplication.main(UserGroupDubboApplication.java:19)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

Found 1 deadlock.

```

        <spring-boot.version>2.3.0.RELEASE</spring-boot.version>
        <spring-cloud-alibaba.version>2.2.1.RELEASE</spring-cloud-alibaba.version>
        <spring-cloud.version>Hoxton.SR4</spring-cloud.version>
        <undertow.version>2.3.0.RELEASE</undertow.version>

**Comment by KomachiSion** [comment]
从锁内容来看，是nacos回调了dubbo的注册的监听器，持有锁对象的逻辑在dubbo客户端里面。死锁是dubbo产生的，请提交次issue到dubbo社区。谢谢。

**Comment by liuhonglin** [comment]
> 从锁内容来看，是nacos回调了dubbo的注册的监听器，持有锁对象的逻辑在dubbo客户端里面。死锁是dubbo产生的，请提交次issue到dubbo社区。谢谢。

好的，感谢。
