### ISSUE TITLE
[NA] failed to update serviceName

### ISSUE THREAD

**Issue by shenyonggang** [alibaba/nacos#4189]
**Describe the bug**
`^[[1;31m[ ERROR ] [2020-11-10 10:27:48.856] [ LOGID: ] [,,,] [com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:278)] [NA] failed to update serviceName: DEFAULT_GROUP@@data-archive
^[[m java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([10.10.3.54:18848, 10.10.3.55:18848, 10.10.3.56:18848]) tried: failed to req API:http://10.10.3.54:18848/nacos/v1/ns/instance/list. code:404 msg: service not found: DEFAULT_GROUP@@data-archive
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:461) ~[nacos-client-1.0.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:385) ~[nacos-client-1.0.1.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:296) ~[nacos-client-1.0.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273) [nacos-client-1.0.1.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318) [nacos-client-1.0.1.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_191]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_191]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]`

**Expected behavior**
no exception happened

**Acutally behavior**
When i remove some useless service in nacos console, the exception happen in some other service. but not all.
在控制台移除部分无用的服务，另外一些服务出现上面的报错信息，但并不是所有的服务都报错。
重新在控制台创建移除的服务，报错消失，再次移除，报错复现。

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [Centos]
 - Version [nacos-server 1.0.1, nacos-client 1.0.1]
 - Module [naming]
 - SDK [spring-cloud-alibaba-nacos ]

**Additional context**

**Comment by KomachiSion** [comment]
还在报错说明你报错的那个应用还在订阅和监听你删除的服务。

**Comment by a5618555** [comment]
> 还在报错说明你报错的那个应用还在订阅和监听你删除的服务。

我同样遇到这个问题  其他的应用一直在监听已经在列表中删除的服务 并且报错404  请问这个如果服务的重启外  有无其他api可以更新服务的本地缓存  批量更新服务的监听列表
