### ISSUE TITLE
消费者的订阅列表被中断

### ISSUE THREAD

**Issue by ymingxu** [alibaba/nacos#4224]
nacos server:1.3.1，nacos client:1.2.1，dubbo:2.7.6
A提供者先启动并在nacos注册中心注册成功，B消费者后启动，从B消费者启动日志看，获取到了提供者A的地址列表，但是随后就与提供者A断开连接了。/192.168.7.74:50080 -> /192.168.7.74:28500 ，这里的28500是提供者A的dubbo端口，50080端口不知道如何而来。日志如下：

2020-11-13 14:38:56.826 [com.alibaba.nacos.naming.client.listener] [INFO ]  org.apache.dubbo.registry.nacos.NacosRegistry {AbstractRegistry.java:407} -  [DUBBO] Notify urls for subscribe url consumer://192.168.7.74/com.demo.fund.portal.api.service.DictManageService?application=pay-bt-service-provider&category=providers,configurators,routers&check=false&cluster=failover&dubbo=2.0.2&init=false&interface=com.demo.fund.portal.api.service.DictManageService&metadata-type=local&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,queryById,statistics&pid=18828&qos.enable=false&release=2.7.6&retries=0&side=consumer&sticky=false&timeout=15000&timestamp=1605249536746, urls: [dubbo://192.168.7.74:28500/com.demo.fund.portal.api.service.DictManageService?anyhost=true&application=portal-service-provider&category=providers&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.demo.fund.portal.api.service.DictManageService&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,statistics,queryById&path=com.demo.fund.portal.api.service.DictManageService&pid=6532&protocol=dubbo&release=2.7.6&retries=0&side=provider&timeout=30000&timestamp=1605249509999], dubbo version: 2.7.6, current host: 192.168.7.74
2020-11-13 14:38:56.831 [main] [INFO ]  org.apache.dubbo.registry.nacos.NacosRegistry {AbstractRegistry.java:407} -  [DUBBO] Notify urls for subscribe url consumer://192.168.7.74/com.demo.fund.portal.api.service.DictManageService?application=pay-bt-service-provider&category=providers,configurators,routers&check=false&cluster=failover&dubbo=2.0.2&init=false&interface=com.demo.fund.portal.api.service.DictManageService&metadata-type=local&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,queryById,statistics&pid=18828&qos.enable=false&release=2.7.6&retries=0&side=consumer&sticky=false&timeout=15000&timestamp=1605249536746, urls: [dubbo://192.168.7.74:28500/com.demo.fund.portal.api.service.DictManageService?anyhost=true&application=portal-service-provider&category=providers&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.demo.fund.portal.api.service.DictManageService&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,statistics,queryById&path=com.demo.fund.portal.api.service.DictManageService&pid=6532&protocol=dubbo&release=2.7.6&retries=0&side=provider&timeout=30000&timestamp=1605249509999], dubbo version: 2.7.6, current host: 192.168.7.74
2020-11-13 14:38:56.833 [com.alibaba.nacos.naming.client.listener] [INFO ]  org.apache.dubbo.remoting.transport.AbstractClient {AbstractClient.java:200} -  [DUBBO] Successed connect to server /192.168.7.74:28500 from NettyClient 192.168.7.74 using dubbo version 2.7.6, channel is NettyChannel [channel=[id: 0xa70b41df, L:/192.168.7.74:50080 - R:/192.168.7.74:28500]], dubbo version: 2.7.6, current host: 192.168.7.74
2020-11-13 14:38:56.833 [NettyClientWorker-4-2] [INFO ]  org.apache.dubbo.remoting.transport.netty4.NettyClientHandler {NettyClientHandler.java:62} -  [DUBBO] The connection of /192.168.7.74:50080 -> /192.168.7.74:28500 is established., dubbo version: 2.7.6, current host: 192.168.7.74
2020-11-13 14:38:56.833 [com.alibaba.nacos.naming.client.listener] [INFO ]  org.apache.dubbo.remoting.transport.AbstractClient {AbstractClient.java:73} -  [DUBBO] Start NettyClient /192.168.7.74 connect to the server /192.168.7.74:28500, dubbo version: 2.7.6, current host: 192.168.7.74
2020-11-13 14:38:56.838 [com.alibaba.nacos.naming.client.listener] [INFO ]  org.apache.dubbo.registry.nacos.NacosRegistry {AbstractRegistry.java:407} -  [DUBBO] Notify urls for subscribe url consumer://192.168.7.74/com.demo.fund.portal.api.service.DictManageService?application=pay-bt-service-provider&category=providers,configurators,routers&check=false&cluster=failover&dubbo=2.0.2&init=false&interface=com.demo.fund.portal.api.service.DictManageService&metadata-type=local&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,queryById,statistics&pid=18828&qos.enable=false&release=2.7.6&retries=0&side=consumer&sticky=false&timeout=15000&timestamp=1605249536746, urls: [empty://192.168.7.74/com.demo.fund.portal.api.service.DictManageService?application=pay-bt-service-provider&category=providers&check=false&cluster=failover&dubbo=2.0.2&init=false&interface=com.demo.fund.portal.api.service.DictManageService&metadata-type=local&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,queryById,statistics&pid=18828&qos.enable=false&release=2.7.6&retries=0&side=consumer&sticky=false&timeout=15000&timestamp=1605249536746], dubbo version: 2.7.6, current host: 192.168.7.74
2020-11-13 14:38:56.838 [main] [INFO ]  org.apache.dubbo.config.ReferenceConfig {ReferenceConfig.java:352} -  [DUBBO] Refer dubbo service com.demo.fund.portal.api.service.DictManageService from url nacos://127.0.0.1:8848/org.apache.dubbo.registry.RegistryService?anyhost=true&application=pay-bt-service-provider&category=providers&check=false&cluster=failover&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&init=false&interface=com.demo.fund.portal.api.service.DictManageService&metadata-type=local&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,queryById,statistics&path=com.demo.fund.portal.api.service.DictManageService&pid=18828&protocol=dubbo&qos.enable=false&register.ip=192.168.7.74&release=2.7.6&remote.application=portal-service-provider&retries=0&side=consumer&sticky=false&timeout=15000&timestamp=1605249536746, dubbo version: 2.7.6, current host: 192.168.7.74
2020-11-13 14:38:56.838 [com.alibaba.nacos.naming.client.listener] [INFO ]  org.apache.dubbo.remoting.transport.netty4.NettyChannel {NettyChannel.java:201} -  [DUBBO] Close netty channel [id: 0xa70b41df, L:/192.168.7.74:50080 - R:/192.168.7.74:28500], dubbo version: 2.7.6, current host: 192.168.7.74
2020-11-13 14:38:56.840 [NettyClientWorker-4-2] [INFO ]  org.apache.dubbo.remoting.transport.netty4.NettyClientHandler {NettyClientHandler.java:76} -  [DUBBO] The connection of /192.168.7.74:50080 -> /192.168.7.74:28500 is disconnected., dubbo version: 2.7.6, current host: 192.168.7.74
2020-11-13 14:38:56.841 [Dubbo-thread-1] [DEBUG]  org.apache.dubbo.rpc.protocol.dubbo.DubboProtocol {DubboProtocol.java:167} -  [DUBBO] disconnected from /192.168.7.74:28500,url:dubbo://192.168.7.74:28500/com.demo.fund.portal.api.service.DictManageService?anyhost=true&application=pay-bt-service-provider&category=providers&check=false&cluster=failover&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&heartbeat=60000&init=false&interface=com.demo.fund.portal.api.service.DictManageService&metadata-type=local&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,statistics,queryById&path=com.demo.fund.portal.api.service.DictManageService&pid=18828&protocol=dubbo&qos.enable=false&register.ip=192.168.7.74&release=2.7.6&remote.application=portal-service-provider&retries=0&side=consumer&sticky=false&timeout=15000&timestamp=1605249509999, dubbo version: 2.7.6, current host: 192.168.7.74

**Comment by horizonzy** [comment]
首先回答你的第一个问题。50080是你的消费者的netty端口，消费者和提供者需要建立netty通信，发送数据包。

根据你的日志看起来，消费者首先是发现了提供者的，顺利建立了netty连接。后面消费者又收到了提供者下线的时间，把之前的netty连接进行了关闭，整个流程看起来都是正常的。
关注一下提供者是否存在问题，或者提供者是否被人为关闭了。

**Comment by ymingxu** [comment]
> 首先回答你的第一个问题。50080是你的消费者的netty端口，消费者和提供者需要建立netty通信，发送数据包。
> 
> 根据你的日志看起来，消费者首先是发现了提供者的，顺利建立了netty连接。后面消费者又收到了提供者下线的时间，把之前的netty连接进行了关闭，整个流程看起来都是正常的。
> 关注一下提供者是否存在问题，或者提供者是否被人为关闭了。

  @horizonzy 感谢您的解答。
首先，整个环境是我自己的本地开发环境，故不存在提供者被人为关闭或者下线。
其次，我反复进行了验证，此问题确实存在。
验证场景1：提供者先启动，消费者后启动，出现之前的问题，消费者无法调用提供者。
![1](https://user-images.githubusercontent.com/32387653/99208746-5a96b480-27fc-11eb-8590-fa96fce16245.jpg)
<img width="796" alt="2" src="https://user-images.githubusercontent.com/32387653/99208748-61252c00-27fc-11eb-8822-c151eadbad74.png">

验证场景2：提供者先启动，消费者后启动，在nacos管控台将提供者下线，在上线后，消费者收到通知（dubbo有异常抛出），并可以正常调用。

2020-11-16 11:11:17.224 [com.alibaba.nacos.naming.client.listener] [INFO ]  org.apache.dubbo.registry.nacos.NacosRegistry {AbstractRegistry.java:407} -  [DUBBO] Notify urls for subscribe url consumer://192.168.7.74/com.demo.fund.portal.api.service.DictManageService?application=pay-bt-service-provider&category=providers,configurators,routers&check=false&cluster=failover&dubbo=2.0.2&init=false&interface=com.demo.fund.portal.api.service.DictManageService&metadata-type=local&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,statistics,queryById&pid=14568&qos.enable=false&release=2.7.6&retries=0&side=consumer&sticky=false&timeout=15000&timestamp=1605495824143, urls: [empty://192.168.7.74/com.demo.fund.portal.api.service.DictManageService?application=pay-bt-service-provider&category=providers&check=false&cluster=failover&dubbo=2.0.2&init=false&interface=com.demo.fund.portal.api.service.DictManageService&metadata-type=local&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,statistics,queryById&pid=14568&qos.enable=false&release=2.7.6&retries=0&side=consumer&sticky=false&timeout=15000&timestamp=1605495824143], dubbo version: 2.7.6, current host: 192.168.7.74
2020-11-16 11:11:21.009 [com.alibaba.nacos.naming.client.listener] [INFO ]  org.apache.dubbo.registry.nacos.NacosRegistry {AbstractRegistry.java:407} -  [DUBBO] Notify urls for subscribe url consumer://192.168.7.74/com.demo.fund.portal.api.service.DictManageService?application=pay-bt-service-provider&category=providers,configurators,routers&check=false&cluster=failover&dubbo=2.0.2&init=false&interface=com.demo.fund.portal.api.service.DictManageService&metadata-type=local&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,statistics,queryById&pid=14568&qos.enable=false&release=2.7.6&retries=0&side=consumer&sticky=false&timeout=15000&timestamp=1605495824143, urls: [dubbo://192.168.7.74:28500/com.demo.fund.portal.api.service.DictManageService?anyhost=true&application=portal-service-provider&category=providers&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.demo.fund.portal.api.service.DictManageService&methods=updateByIdInBatch,getDictMapByParent,update,insert,delete,deleteDictMapByParentId,getPageList,getList,dataVerification,getOne,getCount,statistics,queryById&path=com.demo.fund.portal.api.service.DictManageService&pid=14528&protocol=dubbo&release=2.7.6&retries=0&side=provider&timeout=30000&timestamp=1605495639699], dubbo version: 2.7.6, current host: 192.168.7.74
2020-11-16 11:11:28.010 [http-nio-9080-exec-3] [WARN ]  org.apache.dubbo.rpc.protocol.dubbo.LazyConnectExchangeClient {LazyConnectExchangeClient.java:138} - safe guard client , should not be called ,must have a bug.
java.lang.IllegalStateException: safe guard client , should not be called ,must have a bug.
	at org.apache.dubbo.rpc.protocol.dubbo.LazyConnectExchangeClient.warning(LazyConnectExchangeClient.java:138)
	at org.apache.dubbo.rpc.protocol.dubbo.LazyConnectExchangeClient.request(LazyConnectExchangeClient.java:127)
	at org.apache.dubbo.rpc.protocol.dubbo.ReferenceCountExchangeClient.request(ReferenceCountExchangeClient.java:91)
	at org.apache.dubbo.rpc.protocol.dubbo.DubboInvoker.doInvoke(DubboInvoker.java:100)
	at org.apache.dubbo.rpc.protocol.AbstractInvoker.invoke(AbstractInvoker.java:162)
	at org.apache.dubbo.rpc.protocol.AsyncToSyncInvoker.invoke(AsyncToSyncInvoker.java:52)
	at org.apache.dubbo.monitor.support.MonitorFilter.invoke(MonitorFilter.java:89)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.protocol.dubbo.filter.FutureFilter.invoke(FutureFilter.java:51)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.filter.ConsumerContextFilter.invoke(ConsumerContextFilter.java:55)
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper$1.invoke(ProtocolFilterWrapper.java:81)
	at org.apache.dubbo.rpc.listener.ListenerInvokerWrapper.invoke(ListenerInvokerWrapper.java:78)
	at org.apache.dubbo.rpc.protocol.InvokerWrapper.invoke(InvokerWrapper.java:56)
	at org.apache.dubbo.rpc.cluster.support.FailoverClusterInvoker.doInvoke(FailoverClusterInvoker.java:82)
	at org.apache.dubbo.rpc.cluster.support.AbstractClusterInvoker.invoke(AbstractClusterInvoker.java:259)
	at org.apache.dubbo.rpc.cluster.interceptor.ClusterInterceptor.intercept(ClusterInterceptor.java:47)
	at org.apache.dubbo.rpc.cluster.support.wrapper.AbstractCluster$InterceptorInvokerNode.invoke(AbstractCluster.java:92)
	at org.apache.dubbo.rpc.cluster.support.wrapper.MockClusterInvoker.invoke(MockClusterInvoker.java:82)
	at org.apache.dubbo.rpc.proxy.InvokerInvocationHandler.invoke(InvokerInvocationHandler.java:74)
	at org.apache.dubbo.common.bytecode.proxy2.getDictMapByParent(proxy2.java)

验证场景3：消费者先启动，提供者后启动，无问题，消费者正常可以调用。

最后，本人猜想问题是不是出现在dubbo的版本上呢

**Comment by KomachiSion** [comment]
找一下消费者端 nacos的naming日志， 看一下nacos是否接收到了该服务ip列表的变更信息。如果nacos日志已经显示了新ip列表，那么以ing该是dubbo的问题。

日志位置：${user.home}/logs/nacos/naming.log

**Comment by zhaoziji** [comment]
我觉得大家遇到的是同一个问题：

https://github.com/alibaba/spring-cloud-alibaba/issues/1805
springCloudAlibaba+dubbo+nacos环境下，重启服务提供者或先启动服务消费者后启动服务提供者的情况下，消费者有时候会出现找不到服务的问题及解决方案

https://github.com/alibaba/spring-cloud-alibaba/issues/1529
spring-cloud-starter-dubbo消费者订阅服务时No provider available from registry localhost:9090

**Comment by KomachiSion** [comment]
@ymingxu Any process？We need some log information to judge what‘s the problem. If no more response, we can only think you have solve the problem and close issue.

**Comment by ymingxu** [comment]
> @ymingxu Any process？We need some log information to judge what‘s the problem. If no more response, we can only think you have solve the problem and close issue.

已经解决了，继续使用zk作为注册中心，关闭吧
