### ISSUE TITLE
NACOS 1.4.0 code:503 msg: server is DOWN now, please try again later!

### ISSUE THREAD

**Issue by houyaogit** [alibaba/nacos#4250]
## Issue Description

When i try to service registration  （nacos 1.4.0 ，standalone ,  ./startup.sh -m standalone）

curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'
result message ： server is DOWN now, please try again later!

### Describe what happened (or what feature you want)
Service registration:

2020-11-18 09:26:52.949 ERROR 10950 --- [  restartedMain] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, nacos-payment-provider register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='', endpoint='', namespace='', watchDelay=30000, logName='', service='nacos-payment-provider', weight=1.0, clusterName='DEFAULT', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.71.47', networkInterface='', port=9001, secure=false, accessKey='', secretKey=''}},

java.lang.IllegalArgumentException: no server available
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:438) ~[nacos-client-1.1.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386) ~[nacos-client-1.1.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:188) ~[nacos-client-1.1.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:205) ~[nacos-client-1.1.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:184) ~[nacos-client-1.1.1.jar:na]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:61) ~[spring-cloud-alibaba-nacos-discovery-2.1.0.RELEASE.jar:2.1.0.RELEASE]

tail -200 protocol-raft.log 

2020-11-18 00:06:07,330 ERROR Fail to refresh raft metadata info for group : naming_persistent_service, error is : {}

java.lang.IllegalArgumentException: Blank leader
	at com.alipay.sofa.jraft.util.Requires.requireTrue(Requires.java:85)
	at com.alipay.sofa.jraft.RouteTable.updateLeader(RouteTable.java:181)
	at com.alipay.sofa.jraft.RouteTable.refreshLeader(RouteTable.java:264)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.refreshRouteTable(JRaftServer.java:501)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.lambda$createMultiRaftGroup$1(JRaftServer.java:276)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)

### Describe what you expected to happen

Service registered successfully

### How to reproduce it (as minimally and precisely as possible)

1. ./startup.sh -m standalone
2. curl -X POST 'http://127.0.0.1:8848/nacos/v1/ns/instance?serviceName=nacos.naming.serviceName&ip=20.18.7.10&port=8080'
3. 

### Tell us your environment
Standalone test

### Anything else we need to know?

Seems to be misconfigured

**Comment by KomachiSion** [comment]
standalone mode and ip changed? If so, duplicate with #4210

**Comment by houyaogit** [comment]
thanks a lot

**Comment by houyaogit** [comment]
resolved :  delete {nacos.home}/nacos/data/protocol  restart
