### ISSUE TITLE
Caused by: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni6296585452473038563.so

### ISSUE THREAD

**Issue by skyice2013** [alibaba/nacos#4253]
nacos在中标麒麟（龙芯）操作系统上启动不成功，报以下异常
JDK版本：http://ftp.loongnix.org/toolchain/java/openjdk8/loongson_openjdk8.1.5-jdk8u252b09-linux-loongson3a.tar.gz

Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.consistency.persistent.impl.PersistentServiceProcessor]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni6296585452473038563.so: /tmp/librocksdbjni6296585452473038563.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a MIPS64 LE-bit platform)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:187)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300)
	... 140 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni6296585452473038563.so: /tmp/librocksdbjni6296585452473038563.so: cannot open shared object file: No such file or directory (Possible cause: can't load AMD 64-bit .so on a MIPS64 LE-bit platform)
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1934)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1817)
	at java.lang.Runtime.load0(Runtime.java:809)
	at java.lang.System.load(System.java:1088)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.<clinit>(RocksDBLogStorage.java:75)
	at com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory.createLogStorage(DefaultJRaftServiceFactory.java:50)
	at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:545)
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:961)
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:137)
	at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGroup(JRaftServer.java:267)
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.addLogProcessors(JRaftProtocol.java:163)
	at com.alibaba.nacos.naming.consistency.persistent.impl.PersistentServiceProcessor.init(PersistentServiceProcessor.java:149)
	at com.alibaba.nacos.naming.consistency.persistent.impl.PersistentServiceProcessor.<init>(PersistentServiceProcessor.java:143)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:175)
	... 142 common frames omitted

**Comment by sanxun0325** [comment]
应该是JDK 版本和操作系统的原因,可以换JDK版本做一些尝试么？

**Comment by skyice2013** [comment]
> 看报错信息是JDK版本和操作系统的原因，这应该不是Nacos能处理的范围了。

是的，这个文件 /tmp/librocksdbjni6296585452473038563.so 存在的，RocksDB读这个文件出错了
Possible cause: can't load AMD 64-bit .so on a MIPS64 LE-bit platform

**Comment by KomachiSion** [comment]
应该是这个操作系统不支持rocksDB，rocksDB应该是Jraft引入的，降回1.2.1版本试试，应该可以启动。

**Comment by skyice2013** [comment]
从1.4.0降到1.2.1，没有jraft可以使用了。

**Comment by KomachiSion** [comment]
那麻烦提issue 到rocksDB社区，我估计jraft也没辙。

**Comment by fkfgq2008** [comment]
这个怎么解决的？目前无法降低版本

**Comment by fkfgq2008** [comment]
2.0.+的nacos版本也不行，有没有哪个2.0+的可以用？用在银河麒麟上

**Comment by zhshqo** [comment]
我刚下载的2.2.2，在中科方德安全版操作系统上运行，也是报threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni5415780267701769402.so: /tmp/librocksdbjni5415780267701769402.so: failed to map segment from shared object，不知道有什么解决办法没？

**Comment by lngg057** [comment]
> 

Waiting for an official solution.

**Comment by HuaiAnGG** [comment]
anybody can get a linked for the solution?

**Comment by beijibingdong** [comment]
> failed to map segment from shared object，不知道有什么解决办法没？



> 我刚下载的2.2.2，在中科方德安全版操作系统上运行，也报了异常；嵌套异常是java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni5415780267701769402.so: /tmp/librocksdbjni5415780267701769402.so: failed to mapegment from共享对象，不知道有什么解决办法没？

我也遇到了同样问题，请问你的解决了吗？

**Comment by Kevinboy2020** [comment]
同样的问题，请问解决了么，谢谢

**Comment by Mrwangjw** [comment]
The same question, waiting for a linked for the solution。 3q

**Comment by Kevinboy2020** [comment]
> The same question, waiting for a linked for the solution。 3q

Reduced the version of nacos

**Comment by Mrwangjw** [comment]
> > The same question, waiting for a linked for the solution。 3q
> 
> Reduced the version of nacos

I try to use nacos1.4.1 ,it work well ,but ,There are some Vulnerabilities。 I have a idea , Reduced the version of Jraft?

**Comment by Kevinboy2020** [comment]
> > > The same question, waiting for a linked for the solution。 3q
> > 
> > 
> > Reduced the version of nacos
> 
> I try to use nacos1.4.1 ,it work well ,but ,There are some Vulnerabilities。 I have a idea , Reduced the version of Jraft?

you can have a try ,if it works well.share with us ,haha

**Comment by yangjb0913** [comment]
https://github.com/alibaba/nacos/issues/6718#issuecomment-2217023361
希望对你们有帮助

**Comment by justicerling** [comment]
> 我刚下载的2.2.2，在中科方德安全版操作系统上运行，也是报threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni5415780267701769402.so: /tmp/librocksdbjni5415780267701769402.so: failed to map segment from shared object，不知道有什么解决办法没？

@zhshqo 请问你最后解决了吗

**Comment by xiaoyang1012** [comment]
> 我刚下载的2.2.2，在中科方德安全版操作系统上运行，也是报threw exception; nested exception is java.lang.UnsatisfiedLinkError: /tmp/librocksdbjni5415780267701769402.so: /tmp/librocksdbjni5415780267701769402.so: failed to map segment from shared object，不知道有什么解决办法没？

mount /tmp -o remount,exec     执行这个
