### ISSUE TITLE
some questions about nacos 1.3.2

### ISSUE THREAD

**Issue by devOfWei** [alibaba/nacos#4328]
use nacos 1.3.2  dubbo  2.7.8 
always happen the following problem：
1、2020-11-25 10:57:50.737|[TID: N/A]|DubboSaveRegistryCache-thread-1|||WARN|NacosRegistry| [DUBBO] Failed to save registry cache file, will retry, cause: null, dubbo version: 2.7.8, current host: 172.28.167.248
java.nio.channels.OverlappingFileLockException: null
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
        at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
        at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:180)
        at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:526)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2020-11-25 10:57:50.737|[TID: N/A]|DubboSaveRegistryCache-thread-1|||WARN|NacosRegistry| [DUBBO] Failed to save registry cache file after retrying 3 times, cause: null, dubbo version: 2.7.8, current host: 172.28.167.248
java.nio.channels.OverlappingFileLockException: null
        at sun.nio.ch.SharedFileLockTable.checkList(FileLockTable.java:255)
        at sun.nio.ch.SharedFileLockTable.add(FileLockTable.java:152)
        at sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1108)
        at java.nio.channels.FileChannel.tryLock(FileChannel.java:1155)
        at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:180)
        at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:526)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

2、the cpu and memory  too  high  
3、2020-11-25 11:23:54.129|[TID: N/A]|com.alibaba.nacos.client.Worker.longPolling.fixed-171.16.46.180_8848-htdt-orderprocess-dev||ERROR|ClientWorker|[fixed-171.16.46.180_8848-htdt-orderprocess-dev] [check-update] get changed dataId exception
java.net.ConnectException: no available server, currentServerAddr : http://171.16.46.180:8848

i am waiting for your answer  ； Could I have your WeChat?  i have more questions  about nacos，thanks

**Comment by KomachiSion** [comment]
Can you make sure 171.16.46.180:8848 can be accessed when the problem happen?

**Comment by paderlol** [comment]
I see that the IP of your Dubbo service and the Nacos registration service are both privatized IPs, and they are not in the same network segment. It seems that communication is not possible. 

You can reach us in the Nacos community group of Dingding

**Comment by devOfWei** [comment]
@paderlol   how can i join  the Nacos community group of Dingding

**Comment by devOfWei** [comment]
@KomachiSion  i am sure it can be can be accessed when the problem happen.

**Comment by paderlol** [comment]
Nacos社区群2 DingTalk Group Number: 30438813

**Comment by paderlol** [comment]
`Failed to save registry cache file`

You can see if your cache file is locked and cannot be written

**Comment by chuntaojun** [comment]
the cpu and memory too high？Can you locate which thread it is

**Comment by KomachiSion** [comment]
@devOfWei  Any response？

**Comment by KomachiSion** [comment]
Author no response more than 7 days and current information is not enough to make sure is nacos problem. So close issue, if you reproduce problem, please provide more information about nacos and re-submit issue.
