### ISSUE TITLE
upstream connect error or disconnect/reset before headers. reset reason: connection failure

### ISSUE THREAD

**Issue by AllenJol** [alibaba/nacos#4405]
i upgrade the nacos server from 1.3.2 to 1.4.0,and nacos client also from 1.3.2 upgrade to 1.4.0。and then，in my k8s cluster,i hava four namespace and each namespace install a nacos server for three pod。 some namespace's nacos access will report an error about: upstream connect error or disconnect/reset before headers. reset reason: connection failure

and nacos logs :
WARN [Channel<11>: (nacos-0.nacos.mynamespace.svc.cluster.local:7848)] Failed to resolve name. status=Status{code=UNAVAILABLE, description=Unable to resolve host nacos-0.nacos.mynamespace.svc.cluster.local, cause=java.lang.RuntimeException: java.net.UnknownHostException: nacos-0.nacos.mynamespace.svc.cluster.local
	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:420)
	at io.grpc.internal.DnsNameResolver$Resolve.resolveInternal(DnsNameResolver.java:256)
	at io.grpc.internal.DnsNameResolver$Resolve.run(DnsNameResolver.java:213)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.UnknownHostException: nacos-0.nacos.mynamespace.svc.cluster.local
	at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
	at java.net.InetAddress.getAllByName(InetAddress.java:1193)
	at java.net.InetAddress.getAllByName(InetAddress.java:1127)
	at io.grpc.internal.DnsNameResolver$JdkAddressResolver.resolveAddress(DnsNameResolver.java:640)
	at io.grpc.internal.DnsNameResolver.resolveAll(DnsNameResolver.java:388)
	... 5 more
}

waiting for help

**Comment by KomachiSion** [comment]
`Caused by: java.net.UnknownHostException: nacos-0.nacos.mynamespace.svc.cluster.local`

Please check your k8s cluster can parse your hostname, If can't, might be solve the problem by setting k8s cluster make pod can parse hostname or add `-Dnacos.server.ip=ip or domain which can be parse`

**Comment by AllenJol** [comment]
thank you very much。i have  test for it and i got the result that domain can be parse。
i know that why i have this problem。 It's because i upgrade nacos server and my yaml file have set the volumeMount。
when i upgrade.i have not clean the volumes。when i clean the volumes,and Do not mount，The problem is solved。
