### ISSUE TITLE
IDEA print error log constantly when nacos run in cluster mode but one of three is down

### ISSUE THREAD

**Issue by roadToit** [alibaba/nacos#4420]
**Describe the bug**

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.
When I is developing with IDEA and in Spring Boot Project, use nacos as Registry and Configuration Center, and 
nacos run in cluster mode with three, then one nacos is down, other two nacos server is run normally. The nacos 
cluster is still usable.
But the IDEA is constantly print error log, and the project seems to still work.

**How to Reproduce**
nacos run with cluster mode in Directly connected to ip mode
or
nacos run with cluster mode in Mount the VIP mode
shutdown one of the nacos servers in cluster mode
see the nacos cluster is still work
go to the IDEA project and see the console is constantly print error log, just can't connect to the nacos.

**Desktop (please complete the following information):**
 - OS: [e.g. Centos] windos10
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1] nacos-server-1.4.0
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo] jdk-1.8

**Additional context**

one Sprin Boot service print as this:
com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Dec 07 04:11:17 EST 2020</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 10.99.99.99</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:611)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:538)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:426)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
17:11:16.999 [com.alibaba.nacos.naming.beat.sender] ERROR c.a.n.c.naming - [NA] failed to request

another Spring Boot Service print as this:
2020-12-07 17:12:49.555 ERROR 17612 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : [NA] failed to request
com.alibaba.nacos.api.exception.NacosException: java.net.ConnectException: 拒绝连接 (Connection refused)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:611) [nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524) [nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) [nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:426) [nacos-client-1.3.3.jar:na]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167) [nacos-client-1.3.3.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_40]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_40]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_40]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_40]

**Comment by horizonzy** [comment]
It's normal, is you config three nodes in your client properites? If so, client will request server by random load balance, the down server will be request, but the server is already crash. So this request will be refuse.

**Comment by KomachiSion** [comment]
This problem can be solved in 2.0.0 version by long connection model.

**Comment by KomachiSion** [comment]
At last, I explain that problem.

The client has the nacos server ip list from user input, but has no sense about the status of this server for now.

So when client request server. The client will random get one server ip to request. And at same time, one of three server is shutdown and confuse connection. So the log will print the error, and client will get the next ip to try.
