### ISSUE TITLE
nacos 1.4.0 Version stopped exception

### ISSUE THREAD

**Issue by malversation** [alibaba/nacos#4457]
**Describe the bug**
An exception occurred when the service was stopped in version 1.4.0.
Stand-alone mode.

**Exception information**
2020-12-11 14:27:35.072 [ERROR] [Thread: com.alibaba.nacos.naming.push.receiver] [TraceId: ] [com.alibaba.nacos.client.naming] PushReceiver.java:110 [NA] error while receiving push data
java.net.SocketException: socket closed
	at java.net.DualStackPlainDatagramSocketImpl.socketReceiveOrPeekData(Native Method)
	at java.net.DualStackPlainDatagramSocketImpl.receive0(DualStackPlainDatagramSocketImpl.java:124)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at com.alibaba.nacos.client.naming.core.PushReceiver.run(PushReceiver.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by KomachiSion** [comment]
What's version of client? The problem seems be fixed in nacos-client 1.4.0.

**Comment by KomachiSion** [comment]
duplicate with #3850. And it should be fixed in 1.4.0 client. Please provide your client version.

**Comment by malversation** [comment]
@KomachiSion 
nacos client: Spring Cloud Alibaba 2.2.2.RELEASE
nacos server: 1.4.0

**Comment by KomachiSion** [comment]
Spring Cloud Alibaba 2.2.2.RELEASE depend nacos-client 1.3.2. Please upgrade 1.4.0client manually. Should have been fixed.

**Comment by KomachiSion** [comment]
@malversation  Any process?

**Comment by KomachiSion** [comment]
No more response from author, so we think new version has fixed this problem.

**Comment by kyle-gta** [comment]
i get the same problem.....
it can work when i run my application by using the windows platform, but using the docker version: nacos/nacos-server:1.3.2  in ubuntu...   
the version is 1.3.2, anybody can solve this problem except changing the nacos version?
