### ISSUE TITLE
nacos超时问题，老问题了

### ISSUE THREAD

**Issue by sky662626** [alibaba/nacos#4480]
一段时间不访问nacos就超时了，之前的issue说是更新到客户端版本1.2就可以，
现在都nacos客户端版本都1.3.0了还是这个问题？
java.net.ConnectException: no available server, currentServerAddr : http://172.16.10.45:8848
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:178) ~[nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:387) ~[nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:355) ~[nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:522) ~[nacos-client-1.3.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_221]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_221]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]

**Comment by KomachiSion** [comment]
有其他的报错信息吗？ 贴出来的这个报错信息不是真实的报错信息，日志里应该还有其他的错误日志

**Comment by sky662626** [comment]
你好，以下这个是全部的报错信息：


2020-12-14 19:12:10.823 ERROR 41952 --- [45_8848-scm-dev] c.a.n.c.config.http.ServerHttpAgent      : [NACOS SocketTimeoutException httpPost] currentServerAddr: http://172.16.10.45:8848， err : Read timed out
2020-12-14 19:12:10.824 ERROR 41952 --- [45_8848-scm-dev] c.a.n.c.config.http.ServerHttpAgent      : no available server, currentServerAddr : http://172.16.10.45:8848
2020-12-14 19:12:10.824 ERROR 41952 --- [45_8848-scm-dev] c.a.n.client.config.impl.ClientWorker    : [fixed-172.16.10.45_8848-scm-dev] [check-update] get changed dataId exception

java.net.ConnectException: no available server, currentServerAddr : http://172.16.10.45:8848
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:178) ~[nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:387) [nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:355) [nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:522) [nacos-client-1.3.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_221]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_221]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]

2020-12-14 19:12:10.825 ERROR 41952 --- [45_8848-scm-dev] c.a.n.client.config.impl.ClientWorker    : longPolling error : 

java.net.ConnectException: no available server, currentServerAddr : http://172.16.10.45:8848
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:178) ~[nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:387) ~[nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:355) ~[nacos-client-1.3.0.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:522) ~[nacos-client-1.3.0.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_221]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_221]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_221]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]

**Comment by KomachiSion** [comment]
是说运行一段时间后，这个错误就一直报吗？

有看过服务端的gc日志吗？是不是jvm设置的过小 导致一直fullgc？

**Comment by sky662626** [comment]
嗯嗯，是的，一段时间不访问nacos就会报这个错误，和网络波动有关系吗？
这个是启动信息
/usr/java/jdk1.8.0_251/bin/java -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Djava.ext.dirs=/jre/lib/ext:/jdk1.8.0_251/lib/ext -Xloggc:/opt/nacos/nacos-server-1.3.1/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M

**Comment by KomachiSion** [comment]
看一下/nacos/logs/nacos_gc.log,里面是不是有FullGC或者CMSGC？

如果有的话把内存改大一点。

**Comment by KomachiSion** [comment]
@sky662626 Any process?

**Comment by KomachiSion** [comment]
No more response from author. So we think the problem has solved.

**Comment by xiaozhahu** [comment]
> 嗯嗯，是的，一段时间不访问nacos就会报这个错误，和网络波动有关系吗？ 这个是启动信息 /usr/java/jdk1.8.0_251/bin/java -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Djava.ext.dirs=/jre/lib/ext:/jdk1.8.0_251/lib/ext -Xloggc:/opt/nacos/nacos-server-1.3.1/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M

解决了吗，兄弟

> 是说运行一段时间后，这个错误就一直报吗？
> 
> 有看过服务端的gc日志吗？是不是jvm设置的过小 导致一直fullgc？

解决了吗 兄弟

**Comment by xiaozhahu** [comment]
> 你好，以下这个是全部的报错信息：
> 
> 2020-12-14 19:12:10.823 ERROR 41952 --- [45_8848-scm-dev] c.a.n.c.config.http.ServerHttpAgent : [NACOS SocketTimeoutException httpPost] currentServerAddr: [http://172.16.10.45:8848，](http://172.16.10.45:8848%EF%BC%8C) err : Read timed out 2020-12-14 19:12:10.824 ERROR 41952 --- [45_8848-scm-dev] c.a.n.c.config.http.ServerHttpAgent : no available server, currentServerAddr : http://172.16.10.45:8848 2020-12-14 19:12:10.824 ERROR 41952 --- [45_8848-scm-dev] c.a.n.client.config.impl.ClientWorker : [fixed-172.16.10.45_8848-scm-dev] [check-update] get changed dataId exception
> 
> java.net.ConnectException: no available server, currentServerAddr : http://172.16.10.45:8848 at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:178) ~[nacos-client-1.3.0.jar:na] at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.3.0.jar:na] at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:387) [nacos-client-1.3.0.jar:na] at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:355) [nacos-client-1.3.0.jar:na] at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:522) [nacos-client-1.3.0.jar:na] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_221] at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_221] at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_221] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_221] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_221] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221] at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]
> 
> 2020-12-14 19:12:10.825 ERROR 41952 --- [45_8848-scm-dev] c.a.n.client.config.impl.ClientWorker : longPolling error :
> 
> java.net.ConnectException: no available server, currentServerAddr : http://172.16.10.45:8848 at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:178) ~[nacos-client-1.3.0.jar:na] at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.3.0.jar:na] at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:387) ~[nacos-client-1.3.0.jar:na] at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:355) ~[nacos-client-1.3.0.jar:na] at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:522) ~[nacos-client-1.3.0.jar:na] at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_221] at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_221] at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_221] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_221] at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_221] at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_221] at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_221] at java.lang.Thread.run(Thread.java:748) [na:1.8.0_221]

怎么解决的 老兄

**Comment by xinggongg** [comment]
但我超时了还是能使用
