### ISSUE TITLE
无法获取配置 NacosConfigService.getConfigInner

### ISSUE THREAD

**Issue by 501956430** [alibaba/nacos#4509]
`
[NACOS HTTP-GET] The maximum number of tolerable server reconnection errors has been reached
[2020-12-17 16:14:57.530] [ERROR] [e468451d30d04cb3b259] [] [http-nio-6077-exec-1] [com.alibaba.nacos.client.config.http.ServerHttpAgent 94] - [NACOS ConnectException] currentServerAddr: http://127.0.0.1:8848, httpCode: 500
[2020-12-17 16:14:57.535] [ERROR] [e468451d30d04cb3b259] [] [http-nio-6077-exec-1] [com.alibaba.nacos.client.config.impl.ClientWorker 235] - [fixed-127.0.0.1_8848-dev] [sub-server] get server config exception, dataId=unionapi, group=A_GROUP, tenant=dev

java.net.ConnectException: [NACOS HTTP-GET] The maximum number of tolerable server reconnection errors has been reached
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpGet(ServerHttpAgent.java:115)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpGet(MetricsHttpAgent.java:48)
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:230)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:143)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:92)
	at com.alibaba.nacos.spring.context.event.config.EventPublishingConfigService.getConfig(EventPublishingConfigService.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:879)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:793)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:634)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:741)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.druid.support.http.WebStatFilter.doFilter(WebStatFilter.java:124)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)

`

**Comment by wangweizZZ** [comment]
Please provide version and environment information according to the issue template.

Your question looks the same as  #3134、#3986 、#2941, you can first see if it helps you

**Comment by KomachiSion** [comment]
@501956430 Any process?

**Comment by 501956430** [comment]
> @501956430 Any process?

nacos server version : 1.4.0 
nacos client boot 0.2.7

上述问题似乎另有不同，并未能解决我的问题

**Comment by KomachiSion** [comment]
没有其他的错误信息吗？ 提供的错误信息就是客户端尝试连接服务端失败达到上限了。

看不出来问题。

**Comment by XINJIN422** [comment]
我也遇到了相同的问题。我是这样解决的：通过新增bootstrap.yml（之前搭建SpringCloud都是用的application.yml配置文件），在里面配置spring.cloud.nacos.config.enabled=false或者config的server-addr等信息，就不会再去连接 http://127.0.0.1:8848获取nacos配置了。具体哪边引起的bug我没有跟踪。

**Comment by KomachiSion** [comment]
@XINJIN422 你的问题看上去像是SCA读你的配置没有成功，传给nacos客户端是localhost，最好能够定位到问题然后给他们提issue。

**Comment by KomachiSion** [comment]
No response from author, and the provided information is not enough to be sure it's a problem of nacos. So close issue first.

If problem still exist, please open a new issue and provide more information.
