### ISSUE TITLE
Nacos 集群降级后，服务实例不能自动移除

### ISSUE THREAD

**Issue by coolbeevip** [alibaba/nacos#4510]
nacos 1.3.0 

3节点集群，当停止 leader 节点后，剩余的两个节点一个被选为 leader。

此时注册的服务停止后，在 nacos 的服务实例列表中这个服务实例没有被移除。

**Comment by wangweizZZ** [comment]
hi，你也是类似 #3337  一个nacos 节点和 服务实例同时挂么？

**Comment by coolbeevip** [comment]
> hi，你也是类似 #3337 一个nacos 节点和 服务实例同时挂么？

复现步骤如下：

1. 启动 nacos 三节点集群
2. 启动一个服务A注册到 nacos 集群
3. 停止 nacos 集群中的 leader 节点（注意，一定是停止 leader 节点）
4. 停止服务A
5. 此时在打开 nacos 集群中任意节点的页面，查看服务列表，此时服务A实例依然存在

**Comment by wangweizZZ** [comment]
是的。看上去1.3.0版本存在bug。在节点停止后，部分逻辑 未感知到节点停止事件,导致原本应该由其他节点接管健康检查的逻辑没有生效。 可以帮忙看下naming-server.log  是否有 healthy server list changed 日志打印
建议可以升级到1.4.0 试试，我这试了下1.4.0 不存在这个问题

**Comment by coolbeevip** [comment]
三个节点在一台服务器，靠端口区分：N1-8846，N2-8847，N3-8848

1. 启动三个节点，并启动一个 nc-examples-booking-biz 服务注册到集群后，看到日志如下

N1-8846(Leader) naming-raft.log

```
2020-12-18 14:03:48,044 INFO raft peers changed: [Member{address='127.0.0.1:8847'}, Member{address='127.0.0.1:8846'}, Member{address='127.0.0.1:8848'}]
2020-12-18 14:03:48,059 INFO initializing Raft sub-system
2020-12-18 14:03:48,059 INFO raft notifier started
2020-12-18 14:03:48,060 INFO finish loading all datums, size: 0 cost 1 ms.
2020-12-18 14:03:48,061 INFO cache loaded, datum count: 0, current term: 0
2020-12-18 14:03:48,061 INFO finish to load data from disk, cost: 2 ms.
2020-12-18 14:03:48,063 INFO timer started: leader timeout ms: 15000, heart-beat timeout ms: 5000
2020-12-18 14:03:48,511 INFO add listener: com.alibaba.nacos.naming.domains.meta.00-00---000-NACOS_SWITCH_DOMAIN-000---00-00
2020-12-18 14:03:48,525 INFO add listener: com.alibaba.nacos.naming.domains.meta.
2020-12-18 14:03:49,003 INFO raft peers changed: [Member{address='127.0.0.1:8847'}, Member{address='127.0.0.1:8846'}, Member{address='127.0.0.1:8848'}]
2020-12-18 14:04:00,008 WARN [IS LEADER] no leader is available now!
2020-12-18 14:04:01,067 INFO leader timeout, start voting,leader: null, term: 0
2020-12-18 14:04:01,145 INFO received approve from peer: {"ip":"127.0.0.1:8847","voteFor":"127.0.0.1:8846","term":1,"leaderDueMs":16569,"heartbeatDueMs":1500,"state":"FOLLOWER"}
2020-12-18 14:04:01,145 INFO received approve from peer: {"ip":"127.0.0.1:8848","voteFor":"127.0.0.1:8846","term":1,"leaderDueMs":19702,"heartbeatDueMs":5000,"state":"FOLLOWER"}
2020-12-18 14:04:01,149 INFO 127.0.0.1:8846 has become the LEADER
2020-12-18 14:04:01,149 INFO 127.0.0.1:8846 has become the LEADER
2020-12-18 14:11:05,432 INFO add listener: com.alibaba.nacos.naming.iplist.public##DEFAULT_GROUP@@nc-examples-booking-biz
```

N2-8847 naming-raft.log

```
2020-12-18 14:03:52,358 INFO raft peers changed: [Member{address='127.0.0.1:8847'}, Member{address='127.0.0.1:8846'}, Member{address='127.0.0.1:8848'}]
2020-12-18 14:03:52,368 INFO initializing Raft sub-system
2020-12-18 14:03:52,369 INFO raft notifier started
2020-12-18 14:03:52,370 INFO finish loading all datums, size: 0 cost 1 ms.
2020-12-18 14:03:52,371 INFO cache loaded, datum count: 0, current term: 0
2020-12-18 14:03:52,371 INFO finish to load data from disk, cost: 2 ms.
2020-12-18 14:03:52,372 INFO timer started: leader timeout ms: 15000, heart-beat timeout ms: 5000
2020-12-18 14:03:52,747 INFO add listener: com.alibaba.nacos.naming.domains.meta.00-00---000-NACOS_SWITCH_DOMAIN-000---00-00
2020-12-18 14:03:52,764 INFO add listener: com.alibaba.nacos.naming.domains.meta.
2020-12-18 14:03:53,326 INFO raft peers changed: [Member{address='127.0.0.1:8847'}, Member{address='127.0.0.1:8846'}, Member{address='127.0.0.1:8848'}]
2020-12-18 14:04:00,007 WARN [IS LEADER] no leader is available now!
2020-12-18 14:04:01,136 INFO vote 127.0.0.1:8846 as leader, term: 1
2020-12-18 14:04:05,651 INFO 127.0.0.1:8846 has become the LEADER, local: {"ip":"127.0.0.1:8847","voteFor":"127.0.0.1:8846","term":1,"leaderDueMs":15579,"heartbeatDueMs":5000,"state":"FOLLOWER"}, leader: {"ip":"127.0.0.1:8846","voteFor":"127.0.0.1:8846","term":1,"leaderDueMs":18655,"heartbeatDueMs":5000,"state":"LEADER"}
2020-12-18 14:11:05,498 INFO add listener: com.alibaba.nacos.naming.iplist.public##DEFAULT_GROUP@@nc-examples-booking-biz
```

N3-8848 naming-raft.log

```
2020-12-18 14:03:58,258 INFO raft peers changed: [Member{address='127.0.0.1:8847'}, Member{address='127.0.0.1:8846'}, Member{address='127.0.0.1:8848'}]
2020-12-18 14:03:58,267 INFO initializing Raft sub-system
2020-12-18 14:03:58,267 INFO raft notifier started
2020-12-18 14:03:58,268 INFO finish loading all datums, size: 0 cost 1 ms.
2020-12-18 14:03:58,269 INFO cache loaded, datum count: 0, current term: 0
2020-12-18 14:03:58,269 INFO finish to load data from disk, cost: 2 ms.
2020-12-18 14:03:58,270 INFO timer started: leader timeout ms: 15000, heart-beat timeout ms: 5000
2020-12-18 14:03:58,639 INFO add listener: com.alibaba.nacos.naming.domains.meta.00-00---000-NACOS_SWITCH_DOMAIN-000---00-00
2020-12-18 14:03:58,654 INFO add listener: com.alibaba.nacos.naming.domains.meta.
2020-12-18 14:03:59,226 INFO raft peers changed: [Member{address='127.0.0.1:8847'}, Member{address='127.0.0.1:8846'}, Member{address='127.0.0.1:8848'}]
2020-12-18 14:04:00,007 WARN [IS LEADER] no leader is available now!
2020-12-18 14:04:01,140 INFO vote 127.0.0.1:8846 as leader, term: 1
2020-12-18 14:04:05,651 INFO 127.0.0.1:8846 has become the LEADER, local: {"ip":"127.0.0.1:8848","voteFor":"127.0.0.1:8846","term":1,"leaderDueMs":18166,"heartbeatDueMs":5000,"state":"FOLLOWER"}, leader: {"ip":"127.0.0.1:8846","voteFor":"127.0.0.1:8846","term":1,"leaderDueMs":18655,"heartbeatDueMs":5000,"state":"LEADER"}
2020-12-18 14:11:05,494 INFO add listener: com.alibaba.nacos.naming.iplist.public##DEFAULT_GROUP@@nc-examples-booking-biz
```

2. 目前看起来一切正常，此时我停止 Nacos 的 Leader 节点 N1 后，N2，N3 的 naming-raft.log 日志看起来如下

N2-8847 被选举为新的 Leader，并且 N2-8847 不停的检测已停止的 N1-8846 节点

N2-8847(Leader) naming-raft.log

```
2020-12-18 14:14:44,894 INFO leader timeout, start voting,leader: {"ip":"127.0.0.1:8846","voteFor":"127.0.0.1:8846","term":1,"leaderDueMs":18655,"heartbeatDueMs":5000,"state":"LEADER"}, term: 1
2020-12-18 14:14:44,906 INFO received approve from peer: {"ip":"127.0.0.1:8848","voteFor":"127.0.0.1:8847","term":2,"leaderDueMs":16383,"heartbeatDueMs":4500,"state":"FOLLOWER"}
2020-12-18 14:14:44,909 INFO 127.0.0.1:8847 has become the LEADER
2020-12-18 14:14:49,881 ERROR NACOS-RAFT error while sending heart-beat to peer: 127.0.0.1:8846 {}
java.net.ConnectException: Connection refused: /127.0.0.1:8846 to http://127.0.0.1:8846/nacos/v1/ns/raft/beat
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:380)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: /127.0.0.1:8846
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 common frames omitted
```

N3-8848 naming-raft.log

```
2020-12-18 14:14:44,903 INFO vote 127.0.0.1:8847 as leader, term: 2
2020-12-18 14:14:49,881 INFO 127.0.0.1:8847 has become the LEADER, local: {"ip":"127.0.0.1:8848","voteFor":"127.0.0.1:8847","term":2,"leaderDueMs":18282,"heartbeatDueMs":5000,"state":"FOLLOWER"}, leader: {"ip":"127.0.0.1:8847","voteFor":"127.0.0.1:8847","term":2,"leaderDueMs":16854,"heartbeatDueMs":5000,"state":"LEADER"}
```

3. 我停止 nc-examples-booking-biz 服务后 naming-raft.log 没有特别的日志输出

**此时注册服务的实例列表中 nc-examples-booking-biz 依然存在**

4.  当我再次启动之前停止的 Leader 节点 N1 后，实例 nc-examples-booking-biz 从服务列表中被自动移除，N1 节点启动后 naming-server.log 日志变化如下

**此时在注册服务中查看 nc-examples-booking-biz 实例已经被清除，看到 N1-8846 的日志令人感觉有点奇怪，N1 已经不是Leader，但是好像这个节点才会运行 `open empty service auto clean job` 清理节点**

N1-8846(这是之前停止的节点) naming-server.log

```
2020-12-18 14:54:52,786 INFO open empty service auto clean job, initialDelay : 50000 ms, period : 30000 ms
2020-12-18 14:54:52,787 INFO listen for service meta change
2020-12-18 14:54:53,315 INFO [NACOS-DISTRO] healthy server list changed, old: [127.0.0.1:8846, 127.0.0.1:8847, 127.0.0.1:8848], new: [127.0.0.1:8846, 127.0.0.1:8847, 127.0.0.1:8848]
2020-12-18 14:55:22,563 INFO [NEW-SERVICE] {"name":"DEFAULT_GROUP@@nc-examples-booking-biz","protectThreshold":0.0,"groupName":"DEFAULT_GROUP","metadata":{},"finalizeCount":0,"owners":[],"resetWeight":false,"enabled":true,"selector":{"type":"none"},"namespaceId":"public","ipDeleteTimeout":30000,"lastModifiedMillis":1608274522552,"checksum":"d6680ed1607b922156a49be0005f2ce3","clusterMap":{},"empty":true}
2020-12-18 14:55:22,563 INFO [NACOS-RAFT] datum is changed, key: com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@nc-examples-booking-biz, value: {"instanceList":[{"instanceId":"10.1.71.155#40000#DEFAULT#DEFAULT_GROUP@@nc-examples-booking-biz","ip":"10.1.71.155","port":40000,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@nc-examples-booking-biz","metadata":{"management.home-page-url":"http://10.1.71.155:40000","gray":"NONE","management.health-check-url":"http://10.1.71.155:40000/actuator/health","server.servlet.schema":"http://","server.servlet.context-path":"","management.status-page-url":"http://10.1.71.155:40000/actuator/info","preserved.register.source":"SPRING_CLOUD","management.context-path":"/actuator","version":"4.1.0-SNAPSHOT","affinity":""},"lastBeat":1608271865425,"marked":false,"app":"unknown","instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]}
2020-12-18 14:55:22,569 WARN cluster: DEFAULT not found, ip: {"instanceId":"10.1.71.155#40000#DEFAULT#DEFAULT_GROUP@@nc-examples-booking-biz","ip":"10.1.71.155","port":40000,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@nc-examples-booking-biz","metadata":{"management.home-page-url":"http://10.1.71.155:40000","gray":"NONE","management.health-check-url":"http://10.1.71.155:40000/actuator/health","server.servlet.schema":"http://","server.servlet.context-path":"","management.status-page-url":"http://10.1.71.155:40000/actuator/info","preserved.register.source":"SPRING_CLOUD","management.context-path":"/actuator","version":"4.1.0-SNAPSHOT","affinity":""},"lastBeat":1608271865425,"marked":false,"app":"unknown","instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}, will create new cluster with default configuration.
2020-12-18 14:55:27,560 INFO [AUTO-DELETE-IP] service: DEFAULT_GROUP@@nc-examples-booking-biz, ip: {"instanceId":"10.1.71.155#40000#DEFAULT#DEFAULT_GROUP@@nc-examples-booking-biz","ip":"10.1.71.155","port":40000,"weight":1.0,"healthy":false,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@nc-examples-booking-biz","metadata":{"management.home-page-url":"http://10.1.71.155:40000","gray":"NONE","management.health-check-url":"http://10.1.71.155:40000/actuator/health","server.servlet.schema":"http://","server.servlet.context-path":"","management.status-page-url":"http://10.1.71.155:40000/actuator/info","preserved.register.source":"SPRING_CLOUD","management.context-path":"/actuator","version":"4.1.0-SNAPSHOT","affinity":""},"lastBeat":1608271865425,"marked":false,"app":"unknown","instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}
2020-12-18 14:55:27,569 INFO [NACOS-RAFT] datum is changed, key: com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@nc-examples-booking-biz, value: {"instanceList":[]}
2020-12-18 14:57:42,792 WARN namespace : public, [DEFAULT_GROUP@@nc-examples-booking-biz] services are automatically cleaned
2020-12-18 14:57:42,813 INFO [DEAD-SERVICE] {"name":"DEFAULT_GROUP@@nc-examples-booking-biz","protectThreshold":0.0,"groupName":"DEFAULT_GROUP","metadata":{},"finalizeCount":5,"owners":[],"resetWeight":false,"enabled":true,"selector":{"type":"none"},"namespaceId":"public","ipDeleteTimeout":30000,"lastModifiedMillis":1608274527570,"checksum":"bb5f2acb2e0c09f0816f2525cba65779","clusterMap":{"DEFAULT":{"serviceName":"DEFAULT_GROUP@@nc-examples-booking-biz","name":"DEFAULT","healthChecker":{"type":"TCP"},"defaultPort":80,"defaultCheckPort":80,"useIPPort4Check":true,"metadata":{},"sitegroup":"","defCkport":80,"defIPPort":80,"empty":true}},"empty":true}
```

N2-8847(Leader) naming-server.log

```
2020-12-18 14:55:27,593 INFO [NACOS-RAFT] datum is changed, key: com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@nc-examples-booking-biz, value: {"instanceList":[]}
2020-12-18 14:57:42,813 INFO [DEAD-SERVICE] {"name":"DEFAULT_GROUP@@nc-examples-booking-biz","protectThreshold":0.0,"groupName":"DEFAULT_GROUP","metadata":{},"finalizeCount":0,"owners":[],"resetWeight":false,"enabled":true,"selector":{"type":"none"},"namespaceId":"public","ipDeleteTimeout":30000,"lastModifiedMillis":1608274527593,"checksum":"bb5f2acb2e0c09f0816f2525cba65779","clusterMap":{"DEFAULT":{"serviceName":"DEFAULT_GROUP@@nc-examples-booking-biz","name":"DEFAULT","healthChecker":{"type":"TCP"},"defaultPort":80,"defaultCheckPort":80,"useIPPort4Check":true,"metadata":{},"sitegroup":"","defCkport":80,"defIPPort":80,"empty":true}},"empty":true}
```


N3-8848  naming-server.log

```
2020-12-18 14:55:27,593 INFO [NACOS-RAFT] datum is changed, key: com.alibaba.nacos.naming.iplist.ephemeral.public##DEFAULT_GROUP@@nc-examples-booking-biz, value: {"instanceList":[]}
2020-12-18 14:57:42,818 INFO [DEAD-SERVICE] {"name":"DEFAULT_GROUP@@nc-examples-booking-biz","protectThreshold":0.0,"groupName":"DEFAULT_GROUP","metadata":{},"finalizeCount":0,"owners":[],"resetWeight":false,"enabled":true,"selector":{"type":"none"},"namespaceId":"public","ipDeleteTimeout":30000,"lastModifiedMillis":1608274527593,"checksum":"bb5f2acb2e0c09f0816f2525cba65779","clusterMap":{"DEFAULT":{"serviceName":"DEFAULT_GROUP@@nc-examples-booking-biz","name":"DEFAULT","healthChecker":{"type":"TCP"},"defaultPort":80,"defaultCheckPort":80,"useIPPort4Check":true,"metadata":{},"sitegroup":"","defCkport":80,"defIPPort":80,"empty":true}},"empty":true}

```

**Comment by wangweizZZ** [comment]
:-)  这是个bug，建议升到1.4.0.
我想是如下原因。参考
https://github.com/alibaba/nacos/blob/1.3.0/naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java#L73
https://github.com/alibaba/nacos/blob/1.3.0/naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java#L118
每个节点会对服务hash取模后后进行自己范围内服务实例的健康检查。而由于8846挂了之后，这个healthyList 没有改变。导致你的服务实例始终只能被8846处理。

你看你 8847、8848的 naming-server.log 日志在8846挂掉之后是否出现 [NACOS-DISTRO] healthy server list changed 日志打印即可确认是否如此

另外你说的open empty service auto clean job 和是否leader节点无关。同样他们也受`distroMapper.responsible()`影响，只处理自己负责的部分

**Comment by coolbeevip** [comment]
> :-) 这是个bug，建议升到1.4.0.
> 我想是如下原因。参考
> https://github.com/alibaba/nacos/blob/1.3.0/naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java#L73
> https://github.com/alibaba/nacos/blob/1.3.0/naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java#L118
> 每个节点会对服务hash取模后后进行自己范围内服务实例的健康检查。而由于8846挂了之后，这个healthyList 没有改变。导致你的服务实例始终只能被8846处理。
> 
> 你看你 8847、8848的 naming-server.log 日志在8846挂掉之后是否出现 [NACOS-DISTRO] healthy server list changed 日志打印即可确认是否如此
> 
> 另外你说的open empty service auto clean job 和是否leader节点无关。同样他们也受`distroMapper.responsible()`影响，只处理自己负责的部分

8846 节点停止后，8847，8848 并没有出现 ` [NACOS-DISTRO] healthy server list changed` 日志

**Comment by wangweizZZ** [comment]
对啊。所以我想就是这个原因。你可以升到1.4.0 试试呢

**Comment by coolbeevip** [comment]
> 对啊。所以我想就是这个原因。你可以升到1.4.0 试试呢

我看 1.4.0 升级变化挺大的，我试试吧，谢谢

**Comment by coolbeevip** [comment]
> 对啊。所以我想就是这个原因。你可以升到1.4.0 试试呢

我看最新版本的 [spring-cloud-starter-alibaba-nacos-config](https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-config/2.2.3.RELEASE) 使用的是 nacos-client-1.3.3 版本，如果我的nacos集群升级到 1.4.0  那我可以使用这个 starter 连接吗？

**Comment by wangweizZZ** [comment]
> > 对啊。所以我想就是这个原因。你可以升到1.4.0 试试呢
> 
> 我看最新版本的 [spring-cloud-starter-alibaba-nacos-config](https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-config/2.2.3.RELEASE) 使用的是 nacos-client-1.3.3 版本，如果我的nacos集群升级到 1.4.0 那我可以使用这个 starter 连接吗？

可以的

**Comment by coolbeevip** [comment]
> :-)  这是个bug，建议升到1.4.0.
> 我想是如下原因。参考
> https://github.com/alibaba/nacos/blob/1.3.0/naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java#L73
> https://github.com/alibaba/nacos/blob/1.3.0/naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java#L118
> 每个节点会对服务hash取模后后进行自己范围内服务实例的健康检查。而由于8846挂了之后，这个healthyList 没有改变。导致你的服务实例始终只能被8846处理。
> 
> 你看你 8847、8848的 naming-server.log 日志在8846挂掉之后是否出现 [NACOS-DISTRO] healthy server list changed 日志打印即可确认是否如此
> 
> 另外你说的open empty service auto clean job 和是否leader节点无关。同样他们也受`distroMapper.responsible()`影响，只处理自己负责的部分 

再讨论一下哈，nacos 使用raft一致性协议，这个我想是不是每个节点要检查的服务实例列表都应该是一致的，这样就没问题了

**Comment by wangweizZZ** [comment]
> > :-)  这是个bug，建议升到1.4.0.
> > 我想是如下原因。参考
> > https://github.com/alibaba/nacos/blob/1.3.0/naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java#L73
> > https://github.com/alibaba/nacos/blob/1.3.0/naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java#L118
> > 每个节点会对服务hash取模后后进行自己范围内服务实例的健康检查。而由于8846挂了之后，这个healthyList 没有改变。导致你的服务实例始终只能被8846处理。
> > 你看你 8847、8848的 naming-server.log 日志在8846挂掉之后是否出现 [NACOS-DISTRO] healthy server list changed 日志打印即可确认是否如此
> > 另外你说的open empty service auto clean job 和是否leader节点无关。同样他们也受`distroMapper.responsible()`影响，只处理自己负责的部分
> 
> 再讨论一下哈，nacos 使用raft一致性协议，这个我想是不是每个节点要检查的服务实例列表都应该是一致的，这样就没问题了

如代码里所示。实例列表是一致的，只是每个节点分管一部分来检测。正常情况下，在某一节点挂了之后 该节点负责的服务实例会被其他节点检查，也不会有问题。而之所以没有每个节点都去检查所有实例列表，个人猜想一方面没必要，增加每个节点负担，另外一方面如果由于一些延迟等原因，导致不同节点检查有差异，反而有问题。这部分详细的设计想法 可以加钉钉群讨论哈~ 1.4.0 没这个问题话。这个issue 关了吧:-)

**Comment by coolbeevip** [comment]
OK，关闭此问题，我去尝试一下1.4.0

**Comment by Da-Hong** [comment]
> > > :-)  这是个bug，建议升到1.4.0.
> > > 我想是如下原因。参考
> > > https://github.com/alibaba/nacos/blob/1.3.0/naming/src/main/java/com/alibaba/nacos/naming/healthcheck/ClientBeatCheckTask.java#L73
> > > https://github.com/alibaba/nacos/blob/1.3.0/naming/src/main/java/com/alibaba/nacos/naming/core/DistroMapper.java#L118
> > > 每个节点会对服务hash取模后后进行自己范围内服务实例的健康检查。而由于8846挂了之后，这个healthyList 没有改变。导致你的服务实例始终只能被8846处理。
> > > 你看你 8847、8848的 naming-server.log 日志在8846挂掉之后是否出现 [NACOS-DISTRO] healthy server list changed 日志打印即可确认是否如此
> > > 另外你说的open empty service auto clean job 和是否leader节点无关。同样他们也受`distroMapper.responsible()`影响，只处理自己负责的部分
> > 
> > 
> > 再讨论一下哈，nacos 使用raft一致性协议，这个我想是不是每个节点要检查的服务实例列表都应该是一致的，这样就没问题了
> 
> 如代码里所示。实例列表是一致的，只是每个节点分管一部分来检测。正常情况下，在某一节点挂了之后 该节点负责的服务实例会被其他节点检查，也不会有问题。而之所以没有每个节点都去检查所有实例列表，个人猜想一方面没必要，增加每个节点负担，另外一方面如果由于一些延迟等原因，导致不同节点检查有差异，反而有问题。这部分详细的设计想法 可以加钉钉群讨论哈~ 1.4.0 没这个问题话。这个issue 关了吧:-)

我想问一下
1、集群中某个节点下线了为什么没有重新分配一下负责的服务实例呢
2、客户端发起的心跳，如果使用vip模式，心跳打到了不是负责该服务实例的节点上了，那么会不会被认为不健康呢
