### ISSUE TITLE
在linux容器中部署集群，注册服务时出错，请问是哪里差了配置吗

### ISSUE THREAD

**Issue by yangzhouNNN** [alibaba/nacos#4525]
[2020-12-19 16:08:45.708] [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [updateServiceNow,336] - [NA] failed to update serviceName: DEFAULT_GROUP@@bootServer
com.alibaba.nacos.api.exception.runtime.NacosDeserializationException: errCode: 101, errMsg: Nacos deserialize for class [com.alibaba.nacos.api.naming.pojo.ServiceInfo] failed.  
	at com.alibaba.nacos.common.utils.JacksonUtils.toObj(JacksonUtils.java:161)
	at com.alibaba.nacos.client.naming.core.HostReactor.processServiceJson(HostReactor.java:127)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:333)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:397)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.fasterxml.jackson.core.JsonParseException: Illegal character ((CTRL-CHAR, code 31)): only regular white space (\r, \n, \t) is allowed between tokens
 at [Source: (String)"�

**Comment by ThoreauBai** [comment]
能描述一下你的用法么？和具体执行过程

**Comment by yangzhouNNN** [comment]
1、linux服务器使用容器拉取官方docker镜像进行部署，部署成功后nacos能够正常访问。2、配置中心也能够正常访问。
3、问题是如果加上spring-cloud-starter-alibaba-nacos-discovery 2.2.2.RELEASE，并在启动类上配置@EnableDiscoveryClient注解后会一直报错。但是发现注册中心也注册成功，问题就是一直报错。











------------------&nbsp;原始邮件&nbsp;------------------
发件人: "ThoreauBai"<notifications@github.com&gt;; 
发送时间: 2020年12月19日(星期六) 晚上11:03
收件人: "alibaba/nacos"<nacos@noreply.github.com&gt;; 
抄送: "芒果"<1075136624@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [alibaba/nacos] 在linux容器中部署集群，注册服务时出错，请问是哪里差了配置吗 (#4525)





 
能描述一下你的用法么？和具体执行过程

**Comment by KomachiSion** [comment]
从报错看，好像是有非法字符，你是否有挂载nginx并开启了zip压缩功能？可以考虑升级一下客户端版本试试 ，比如spring-cloud-starter-alibaba-nacos-discovery 2.2.3.RELEASE 或手动变更nacos-client为1.4.0

**Comment by yangzhouNNN** [comment]
谢谢，解决了我的问题

**Comment by yangzhouNNN** [comment]
解决方法：排除config、discovery中的client，单独添加client版本1.4.0，目前未发现错误！
		
		
 		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
			<version>2.2.2.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
		</dependency> 

		
    		<dependency>
			<groupId>com.alibaba.cloud</groupId>
			<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
			<version>2.2.2.RELEASE</version>
            <exclusions>
                <exclusion>
                    <groupId>com.alibaba.nacos</groupId>
                    <artifactId>nacos-client</artifactId>
                </exclusion>
            </exclusions>
		</dependency>   
		
		
		<dependency>
		    <groupId>com.alibaba.nacos</groupId>
		    <artifactId>nacos-client</artifactId>
		    <version>1.4.0</version>
		</dependency>
