### ISSUE TITLE
jdk1.8  java.lang.UnsupportedClassVersionError: org/springframework/boot/loader

### ISSUE THREAD

**Issue by luotianwen** [alibaba/nacos#4532]
jdk1.8
nacos 1.4.0

startup.cmd -m standalone

Exception in thread "main" java.lang.UnsupportedClassVersionError: org/springframework/boot/loader
/PropertiesLauncher : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)

**Comment by luotianwen** [comment]
D:\soft\nacos-server-1.4.0\nacos\bin>java -version
java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

**Comment by horizonzy** [comment]
Can you echo `JAVE_HOME` in your pc, check the value is right.

**Comment by horizonzy** [comment]
Can you echo `JAVE_HOME` in your pc, check the value is right?

**Comment by KomachiSion** [comment]
You can try add a `print` in nacos startup.cmd to print out the `JAVE_HOME` the script get. And check whether it is right first.

**Comment by luotianwen** [comment]
ok ! JAVE_HOME  is error
