### ISSUE TITLE
java.lang.NoClassDefFoundError: com/alibaba/nacos/client/config/impl/CacheData$1

### ISSUE THREAD

**Issue by cch-wh** [alibaba/nacos#4540]
**Describe the bug**
生产上面每次在nacos上更新配置下发时候，都会触发这个ERROR java.lang.NoClassDefFoundError:
这个ERROR不停的写入我的项目日志，导致我的项目日志里全是它，业务日志就无法写入。。。
目前版本情况如下：

<spring-boot.version>2.2.6.RELEASE</spring-boot.version>
<dependency>
	<groupId>com.alibaba.boot</groupId>
	<artifactId>nacos-config-spring-boot-starter</artifactId>
	<version>0.2.3</version>
</dependency>

详细报错如下：
[goods-v-s][ERROR] [2020-12-22 02:05:45][com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:563)]longPolling error : 
java.lang.NoClassDefFoundError: com/alibaba/nacos/client/config/impl/CacheData$1
	at com.alibaba.nacos.client.config.impl.CacheData.safeNotifyListener(CacheData.java:183)
	at com.alibaba.nacos.client.config.impl.CacheData.checkListenerMd5(CacheData.java:174)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:552)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[goods-v-s][ERROR] [2020-12-22 02:06:16][com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:563)]longPolling error : 
java.lang.NoClassDefFoundError: com/alibaba/nacos/client/config/impl/CacheData$1
	at com.alibaba.nacos.client.config.impl.CacheData.safeNotifyListener(CacheData.java:183)
	at com.alibaba.nacos.client.config.impl.CacheData.checkListenerMd5(CacheData.java:174)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:552)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by KomachiSion** [comment]
自行检查是否有依赖冲突。

**Comment by cch-wh** [comment]
能说一下具体大概的方向嘛？但是目前项目里的冲突已将排除了

**Comment by cch-wh** [comment]
> 自行检查是否有依赖冲突。
能说一下具体大概的方向嘛？但是目前项目里的冲突已将排除了

**Comment by KomachiSion** [comment]
那就是排除了错误的版本。

**Comment by cch-wh** [comment]
> 那就是排除了错误的版本。

嗯？大佬，通过这个ERROR 能判断是哪个依赖有问题吗？

**Comment by KomachiSion** [comment]
nacos-client的版本有冲突

**Comment by cch-wh** [comment]
> nacos-client的版本有冲突

服务端是1.1.3版本 springboot引用的是
com.alibaba.boot
nacos-config-spring-boot-starter
0.2.3
我看里面的nacos-client也是1.1.3  冲突的可能性不大吧

**Comment by KomachiSion** [comment]
这需要你自己去确认排查，还有个简单的方法就是写一个demo程序， 只有nacos-config-spring-boot-starter 0.2.3 其他什么都不引入，启动之后试试会不会出现这个问题。

**Comment by KomachiSion** [comment]
Any process? If no more response, we will close issue.
