### ISSUE TITLE
【Pressure measurement】Why is TPS of cluster mode registration service so low

### ISSUE THREAD

**Issue by robotLJW** [alibaba/nacos#4542]
【nacos version】：1.3.0

【Machine configuration】：16U32G

【startup parameter】：startup.sh -p embedded
/opt/jdk1.8.0_271/bin/java  -DembeddedStorage=true -server -Xms20g -Xmx20g -Xmn10g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.member.list= -Djava.ext.dirs=/opt/jdk1.8.0_271/jre/lib/ext:/opt/jdk1.8.0_271/lib/ext -Xloggc:/opt/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000 -Dloader.path=/opt/nacos/plugins/health,/opt/nacos/plugins/cmdb,/opt/nacos/plugins/mysql -Dnacos.home=/opt/nacos -jar /opt/nacos/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/opt/nacos/conf/ --logging.config=/opt/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288

【pressure measuring tools】：jmter

【url—registration services】：like POST   '172.16.0.93:8848/nacos/v1/ns/service?serviceName=TestService${__UUID()}&protectThreshold=0'

【result】：**TPS is only about 230**

100 concurrent：

Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +      1 in 00:00:00 =    4.9/s Avg:    29 Min:    29 Max:    29 Err:     0 (0.00%) Active: 92 Started: 92 Finished: 0
summary +   5846 in 00:00:25 =  238.3/s Avg:   416 Min:    25 Max:   438 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =   5847 in 00:00:25 =  236.3/s Avg:   416 Min:    25 Max:   438 Err:     0 (0.00%)
summary +   7095 in 00:00:30 =  236.5/s Avg:   422 Min:   405 Max:   451 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  12942 in 00:00:55 =  236.4/s Avg:   419 Min:    25 Max:   451 Err:     0 (0.00%)
summary +   7050 in 00:00:30 =  235.0/s Avg:   425 Min:   409 Max:   484 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary =  19992 in 00:01:25 =  235.9/s Avg:   421 Min:    25 Max:   484 Err:     0 (0.00%)

500 concurrent：

Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +      1 in 00:00:00 =    4.9/s Avg:    18 Min:    18 Max:    18 Err:     0 (0.00%) Active: 112 Started: 112 Finished: 0
summary +   5980 in 00:00:26 =  232.1/s Avg:  2045 Min:    16 Max:  2243 Err:     0 (0.00%) Active: 500 Started: 500 Finished: 0
summary =   5981 in 00:00:26 =  230.3/s Avg:  2045 Min:    16 Max:  2243 Err:     0 (0.00%)
summary +   7004 in 00:00:30 =  233.5/s Avg:  2143 Min:  1258 Max:  2261 Err:     0 (0.00%) Active: 500 Started: 500 Finished: 0
summary =  12985 in 00:00:56 =  232.0/s Avg:  2098 Min:    16 Max:  2261 Err:     0 (0.00%)
summary +   7065 in 00:00:30 =  235.5/s Avg:  2122 Min:  1257 Max:  2251 Err:     0 (0.00%) Active: 500 Started: 500 Finished: 0
summary =  20050 in 00:01:26 =  233.2/s Avg:  2106 Min:    16 Max:  2261 Err:     0 (0.00%)

---
**But when use the registration instance interface，the TPS can reach 10000.**

Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary + 367188 in 00:00:17 = 22065.3/s Avg:     4 Min:     0 Max:   475 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary + 320148 in 00:00:30 = 10695.1/s Avg:     9 Min:     0 Max:  3047 Err:     4 (0.00%) Active: 100 Started: 100 Finished: 0
summary = 687336 in 00:00:47 = 14757.6/s Avg:     6 Min:     0 Max:  3047 Err:     4 (0.00%)
summary + 162019 in 00:00:30 = 5416.5/s Avg:    18 Min:     0 Max:  2901 Err:     2 (0.00%) Active: 100 Started: 100 Finished: 0
summary = 849355 in 00:01:16 = 11104.6/s Avg:     8 Min:     0 Max:  3047 Err:     6 (0.00%)

【My expectations】：Is there something wrong with my test method? thx.

**Comment by robotLJW** [comment]
@KomachiSion thx

**Comment by KomachiSion** [comment]
POST `nacos/v1/ns/service` will create persist service and it will use CP raft to synchronize data. Only more than half of response, you will get the respons.

registration instance interface will create service with ephemeral, It will use AP distro to synchronize data. and will merge data in a short time. So TPS is better.

you can do same test in 1.4.0. We use Jraft to replace old raft. The performance may improve for POST `nacos/v1/ns/service`

**Comment by robotLJW** [comment]
【nacos version】1.4.0

【startup parameter】：sh startup.sh -p embedded
/opt/jdk1.8.0_271/bin/java  -DembeddedStorage=true -server -Xms20g -Xmx20g -Xmn10g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/opt/nacos/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.member.list= -Djava.ext.dirs=/opt/jdk1.8.0_271/jre/lib/ext:/opt/jdk1.8.0_271/lib/ext -Xloggc:/opt/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=8000 -Dloader.path=/opt/nacos/plugins/health,/opt/nacos/plugins/cmdb -Dnacos.home=/opt/nacos -jar /opt/nacos/target/nacos-server.jar  --spring.config.location=file:/opt/nacos/conf/,classpath:/,classpath:/config/,file:./,file:./config/ --logging.config=/opt/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288

【result】：I'm not sure if the performance has improved, but I've found errors in concurrent access

【err】：
com.alibaba.nacos.api.exception.NacosException: null
        at com.alibaba.nacos.naming.core.ServiceManager.addOrReplaceService(ServiceManager.java:447)
        at com.alibaba.nacos.naming.controllers.ServiceController.create(ServiceController.java:128)
        at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
com.alibaba.nacos.api.exception.NacosException: null
        at com.alibaba.nacos.naming.core.ServiceManager.addOrReplaceService(ServiceManager.java:447)
        at com.alibaba.nacos.naming.controllers.ServiceController.create(ServiceController.java:128)
        at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:65)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)


---
100 concurrent：
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +  16620 in 00:00:10 = 1738.1/s Avg:    21 Min:     5 Max:  6021 Err:     0 (0.00%) Active: 100 Started: 100 Finished: 0
summary +    300 in 00:00:30 =   10.0/s Avg:  9982 Min:  6021 Max: 10026 Err:   297 (99.00%) Active: 100 Started: 100 Finished: 0
summary =  16920 in 00:00:40 =  427.6/s Avg:   198 Min:     5 Max: 10026 Err:   297 (1.76%)
summary +    300 in 00:00:30 =   10.0/s Avg: 10003 Min: 10001 Max: 10088 Err:   300 (100.00%) Active: 100 Started: 100 Finished: 0
summary =  17220 in 00:01:10 =  247.5/s Avg:   368 Min:     5 Max: 10088 Err:   597 (3.47%)
summary +    300 in 00:00:30 =   10.0/s Avg: 10002 Min: 10001 Max: 10007 Err:   300 (100.00%) Active: 100 Started: 100 Finished: 0
summary =  17520 in 00:01:40 =  175.9/s Avg:   533 Min:     5 Max: 10088 Err:   897 (5.12%)

---
500 concurrent：
Waiting for possible Shutdown/StopTestNow/HeapDump/ThreadDump message on port 4445
summary +   6867 in 00:00:02 = 3142.8/s Avg:   117 Min:    32 Max:   363 Err:     0 (0.00%) Active: 500 Started: 500 Finished: 0
summary +  10004 in 00:00:31 =  318.1/s Avg:   690 Min:    28 Max: 30009 Err:   401 (4.01%) Active: 500 Started: 500 Finished: 0
summary =  16871 in 00:00:34 =  501.7/s Avg:   457 Min:    28 Max: 30009 Err:   401 (2.38%)
summary +    600 in 00:00:30 =   20.0/s Avg: 25026 Min: 20016 Max: 30058 Err:   600 (100.00%) Active: 500 Started: 500 Finished: 0
summary =  17471 in 00:01:04 =  274.6/s Avg:  1301 Min:    28 Max: 30058 Err:  1001 (5.73%)
summary +    600 in 00:00:30 =   20.0/s Avg: 25019 Min: 20029 Max: 29993 Err:   600 (100.00%) Active: 500 Started: 500 Finished: 0
summary =  18071 in 00:01:34 =  193.0/s Avg:  2088 Min:    28 Max: 30058 Err:  1601 (8.86%)

**Comment by robotLJW** [comment]
@KomachiSion thx

**Comment by KomachiSion** [comment]
From my test, the error has no possible happen. what's your url used?

**Comment by robotLJW** [comment]
same

【url】：POST 'xxxx:8848/nacos/v1/ns/service?serviceName=TestService${__UUID()}&protectThreshold=0'
---
【jmx】：

<?xml version="1.0" encoding="UTF-8"?>
<jmeterTestPlan version="1.2" properties="5.0" jmeter="5.3">
  <hashTree>
    <TestPlan guiclass="TestPlanGui" testclass="TestPlan" testname="NacosCreateServicesTest" enabled="true">
      <stringProp name="TestPlan.comments"></stringProp>
      <boolProp name="TestPlan.functional_mode">false</boolProp>
      <boolProp name="TestPlan.tearDown_on_shutdown">true</boolProp>
      <boolProp name="TestPlan.serialize_threadgroups">false</boolProp>
      <elementProp name="TestPlan.user_defined_variables" elementType="Arguments" guiclass="ArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
        <collectionProp name="Arguments.arguments"/>
      </elementProp>
      <stringProp name="TestPlan.user_define_classpath"></stringProp>
    </TestPlan>
    <hashTree>
      <ThreadGroup guiclass="ThreadGroupGui" testclass="ThreadGroup" testname="Thread Group 01" enabled="true">
        <stringProp name="ThreadGroup.on_sample_error">continue</stringProp>
        <elementProp name="ThreadGroup.main_controller" elementType="LoopController" guiclass="LoopControlPanel" testclass="LoopController" testname="Loop Controller" enabled="true">
          <boolProp name="LoopController.continue_forever">false</boolProp>
          <intProp name="LoopController.loops">-1</intProp>
        </elementProp>
        <stringProp name="ThreadGroup.num_threads">500</stringProp>
        <stringProp name="ThreadGroup.ramp_time">0</stringProp>
        <boolProp name="ThreadGroup.scheduler">false</boolProp>
        <stringProp name="ThreadGroup.duration"></stringProp>
        <stringProp name="ThreadGroup.delay"></stringProp>
        <boolProp name="ThreadGroup.same_user_on_next_iteration">true</boolProp>
      </ThreadGroup>
      <hashTree>
        <HTTPSamplerProxy guiclass="HttpTestSampleGui" testclass="HTTPSamplerProxy" testname="CreateMicroService" enabled="true">
          <elementProp name="HTTPsampler.Arguments" elementType="Arguments" guiclass="HTTPArgumentsPanel" testclass="Arguments" testname="User Defined Variables" enabled="true">
            <collectionProp name="Arguments.arguments">
              <elementProp name="serviceName" elementType="HTTPArgument">
                <boolProp name="HTTPArgument.always_encode">false</boolProp>
                <stringProp name="Argument.value">TestService${__UUID()}</stringProp>
                <stringProp name="Argument.metadata">=</stringProp>
                <boolProp name="HTTPArgument.use_equals">true</boolProp>
                <stringProp name="Argument.name">serviceName</stringProp>
              </elementProp>
              <elementProp name="protectThreshold" elementType="HTTPArgument">
                <boolProp name="HTTPArgument.always_encode">false</boolProp>
                <stringProp name="Argument.value">0</stringProp>
                <stringProp name="Argument.metadata">=</stringProp>
                <boolProp name="HTTPArgument.use_equals">true</boolProp>
                <stringProp name="Argument.name">protectThreshold</stringProp>
              </elementProp>
            </collectionProp>
          </elementProp>
          <stringProp name="HTTPSampler.domain">172.16.0.5</stringProp>
          <stringProp name="HTTPSampler.port">8848</stringProp>
          <stringProp name="HTTPSampler.protocol">http</stringProp>
          <stringProp name="HTTPSampler.contentEncoding">utf-8</stringProp>
          <stringProp name="HTTPSampler.path">/nacos/v1/ns/service</stringProp>
          <stringProp name="HTTPSampler.method">POST</stringProp>
          <boolProp name="HTTPSampler.follow_redirects">true</boolProp>
          <boolProp name="HTTPSampler.auto_redirects">false</boolProp>
          <boolProp name="HTTPSampler.use_keepalive">true</boolProp>
          <boolProp name="HTTPSampler.DO_MULTIPART_POST">false</boolProp>
          <stringProp name="HTTPSampler.embedded_url_re"></stringProp>
          <stringProp name="HTTPSampler.connect_timeout"></stringProp>
          <stringProp name="HTTPSampler.response_timeout"></stringProp>
        </HTTPSamplerProxy>
        <hashTree/>
        <HeaderManager guiclass="HeaderPanel" testclass="HeaderManager" testname="HTTP Header Manager01" enabled="true">
          <collectionProp name="HeaderManager.headers">
            <elementProp name="" elementType="Header">
              <stringProp name="Header.name">x-domain-name</stringProp>
              <stringProp name="Header.value">default</stringProp>
            </elementProp>
          </collectionProp>
        </HeaderManager>
        <hashTree/>
        <ResultCollector guiclass="ViewResultsFullVisualizer" testclass="ResultCollector" testname="View Results Tree" enabled="true">
          <boolProp name="ResultCollector.error_logging">false</boolProp>
          <objProp>
            <name>saveConfig</name>
            <value class="SampleSaveConfiguration">
              <time>true</time>
              <latency>true</latency>
              <timestamp>true</timestamp>
              <success>true</success>
              <label>true</label>
              <code>true</code>
              <message>true</message>
              <threadName>true</threadName>
              <dataType>true</dataType>
              <encoding>false</encoding>
              <assertions>true</assertions>
              <subresults>true</subresults>
              <responseData>false</responseData>
              <samplerData>false</samplerData>
              <xml>false</xml>
              <fieldNames>true</fieldNames>
              <responseHeaders>false</responseHeaders>
              <requestHeaders>false</requestHeaders>
              <responseDataOnError>false</responseDataOnError>
              <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>
              <assertionsResultsToSave>0</assertionsResultsToSave>
              <bytes>true</bytes>
              <sentBytes>true</sentBytes>
              <url>true</url>
              <threadCounts>true</threadCounts>
              <idleTime>true</idleTime>
              <connectTime>true</connectTime>
            </value>
          </objProp>
          <stringProp name="filename"></stringProp>
        </ResultCollector>
        <hashTree/>
        <ResultCollector guiclass="StatVisualizer" testclass="ResultCollector" testname="聚合报告" enabled="true">
          <boolProp name="ResultCollector.error_logging">false</boolProp>
          <objProp>
            <name>saveConfig</name>
            <value class="SampleSaveConfiguration">
              <time>true</time>
              <latency>true</latency>
              <timestamp>true</timestamp>
              <success>true</success>
              <label>true</label>
              <code>true</code>
              <message>true</message>
              <threadName>true</threadName>
              <dataType>true</dataType>
              <encoding>false</encoding>
              <assertions>true</assertions>
              <subresults>true</subresults>
              <responseData>false</responseData>
              <samplerData>false</samplerData>
              <xml>false</xml>
              <fieldNames>true</fieldNames>
              <responseHeaders>false</responseHeaders>
              <requestHeaders>false</requestHeaders>
              <responseDataOnError>false</responseDataOnError>
              <saveAssertionResultsFailureMessage>true</saveAssertionResultsFailureMessage>
              <assertionsResultsToSave>0</assertionsResultsToSave>
              <bytes>true</bytes>
              <sentBytes>true</sentBytes>
              <url>true</url>
              <threadCounts>true</threadCounts>
              <idleTime>true</idleTime>
              <connectTime>true</connectTime>
            </value>
          </objProp>
          <stringProp name="filename"></stringProp>
        </ResultCollector>
        <hashTree/>
      </hashTree>
    </hashTree>
  </hashTree>
</jmeterTestPlan>

**Comment by KomachiSion** [comment]
I run with your jmx in local there are no error you print out. some error caused by GC, (local test with 512M JVM)


CreateMicroService | 29391 | 35 | 6 | 9 | 10 | 18 | 1 | 10009 | 0.002926065802456534 | 275.21724473743353 | 43.92992225833864 | 87.31950346526425
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
TOTAL | 29391 | 35 | 6 | 9 | 10 | 18 | 1 | 10009 | 0.002926065802456534 | 275.21724473743353 | 43.92992225833864 | 87.31950346526425

**Comment by KomachiSion** [comment]
Can you move to nacos-server and print some point error log for us?

**Comment by robotLJW** [comment]
I found that the log was too large, only part of it was taken, and the error was the same
---
[nacos.log](https://github.com/alibaba/nacos/files/5734285/nacos.log)

**Comment by robotLJW** [comment]
@KomachiSion thx

**Comment by chuntaojun** [comment]
I will try to reslve this problem and find out why tps was so low
