### ISSUE TITLE
make springboot web service offline throw exception

### ISSUE THREAD

**Issue by yuzhiyuxia** [alibaba/nacos#4557]
make springboot web service offline throw exception:
Exception in thread "com.alibaba.naocs.core.raft-cli-service.-7" java.lang.ClassCastException: com.alibaba.nacos.consistency.entity.WriteRequest cannot be cast to com.alibaba.nacos.consistency.entity.Response
        at com.alibaba.nacos.core.distributed.raft.JRaftServer$3.complete(JRaftServer.java:444)
        at com.alipay.sofa.jraft.rpc.impl.GrpcClient$1.lambda$onNext$0(GrpcClient.java:152)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

nacos server: https://github.com/alibaba/nacos/releases/download/2.0.0-ALPHA.1/nacos-server-2.0.0-ALPHA.1.tar.gz

**Comment by KomachiSion** [comment]
This problem will fix in next release, now please remove `data` dir under `nacos` dir and restart nacos-server.

**Comment by KomachiSion** [comment]
Fixed by https://github.com/alibaba/nacos/pull/4411.
