### ISSUE TITLE
registry infomation is imcomplete in single machine with local cache file mode

### ISSUE THREAD

**Issue by xinhaiCai** [alibaba/nacos#4569]
**Describe the bug**
````
2020-12-25 09:25:28,195 ERROR [main] cache.DiskCache (DiskCache.java:135) - [NA] error while parsing cache file: {"hosts":[{"ip":"169.254.200.224","port":20880,"valid":true,"healthy":true,"marked":false,"instanceId":"169.254.200.224#20880#DEFAULT#DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","metadata":{"side":"provider","methods":"saveAuditLogBatch,findEntityLogByEntityId,findExactOpLogDTOLogDataPackage,saveAuditOpLogBatch,findEntityLogByOpLogId,findOpLogDataPackage,findExactOpLogDataPackage,findOpLogDTODataPackage,saveAuditEntityLogBatch","release":"2.7.8","deprecated":"false","description":"服务提供者由AutoServiceBeanDefinitionRegistryPostProcessor自动注册","dubbo":"2.0.2","pid":"4336","interface":"com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService","generic":"false","revision":"3.1.0","path":"com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService","default":"true","protocol":"dubbo","application":"pmss-business","dynamic":"true","belong.to.value":"auditlog","service.filter":"tsieDubboExceptionFilter,-exception","category":"providers","anyhost":"true","timestamp":"1608811439995"},"enabled":true,"weight":1.0,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","ephemeral":true}],"dom":"DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","name":"DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","cacheMillis":10000,"lastRefTime":1608811444824,"checksum":"097b2c82249de6a51fa1facc00a1f0a0","useSpecifiedURL":false,"clusters":"","en
com.alibaba.nacos.api.exception.runtime.NacosDeserializationException: errCode: 101, errMsg: Nacos deserialize for class [com.alibaba.nacos.api.naming.pojo.ServiceInfo] failed.  
	at com.alibaba.nacos.common.utils.JacksonUtils.toObj(JacksonUtils.java:160) ~[nacos-common-1.3.1.jar:?]
	at com.alibaba.nacos.client.naming.cache.DiskCache.read(DiskCache.java:129) ~[nacos-client-1.3.1.jar:?]
	at com.alibaba.nacos.client.naming.core.HostReactor.<init>(HostReactor.java:102) ~[nacos-client-1.3.1.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:99) ~[nacos-client-1.3.1.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:83) ~[nacos-client-1.3.1.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_181]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_181]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_181]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_181]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:60) ~[nacos-api-1.3.1.jar:?]
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77) ~[nacos-api-1.3.1.jar:?]
	at org.apache.dubbo.registry.nacos.util.NacosNamingServiceUtils.createNamingService(NacosNamingServiceUtils.java:108) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.registry.nacos.NacosRegistryFactory.createRegistry(NacosRegistryFactory.java:40) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:122) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:34) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:354) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:208) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:62) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:153) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:492) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:325) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:300) ~[dubbo-2.7.8.jar:2.7.8]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:206) ~[dubbo-2.7.8.jar:2.7.8]
	at com.tsieframework.boot.autoconfigure.dubbo.AutoRegistryServiceBean.afterPropertiesSet(AutoRegistryServiceBean.java:43) ~[tsie-boot-autoconfigure-3.1.0.jar:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1855) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1792) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:595) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323) ~[spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) [spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321) [spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) [spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:879) [spring-beans-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) [spring-context-5.2.4.RELEASE.jar:5.2.4.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.2.5.RELEASE.jar:2.2.5.RELEASE]
	at com.tsie.pmss.web.WebRunSingleApplication.main(WebRunSingleApplication.java:18) [classes/:?]
Caused by: com.fasterxml.jackson.core.io.JsonEOFException: Unexpected end-of-input in field name
 at [Source: (String)"{"hosts":[{"ip":"169.254.200.224","port":20880,"valid":true,"healthy":true,"marked":false,"instanceId":"169.254.200.224#20880#DEFAULT#DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","metadata":{"side":"provider","methods":"saveAuditLogBatch,findEntityLogByEntityId,findExactOpLogDTOLogDataPackage,saveAuditOpLogBatch,findEntityLogByOpLogId,findOpLogDataPackage,findExactOpLogDataPackage,findOpLogDTODataPackage,saveAuditEntityLogBatch","release":"2.7.8""[truncated 1075 chars]; line: 1, column: 1576]
	at com.fasterxml.jackson.core.base.ParserMinimalBase._reportInvalidEOF(ParserMinimalBase.java:664) ~[jackson-core-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName2(ReaderBasedJsonParser.java:1727) ~[jackson-core-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser._parseName(ReaderBasedJsonParser.java:1711) ~[jackson-core-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.core.json.ReaderBasedJsonParser.nextFieldName(ReaderBasedJsonParser.java:933) ~[jackson-core-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:295) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:151) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4202) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3205) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3173) ~[jackson-databind-2.10.2.jar:2.10.2]
	at com.alibaba.nacos.common.utils.JacksonUtils.toObj(JacksonUtils.java:158) ~[nacos-common-1.3.1.jar:?]
	... 44 more
````

**Expected behavior**
registry cached file content is
`{"hosts":[{"ip":"169.254.200.224","port":20880,"valid":true,"healthy":true,"marked":false,"instanceId":"169.254.200.224#20880#DEFAULT#DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","metadata":{"side":"provider","methods":"saveAuditLogBatch,findEntityLogByEntityId,findExactOpLogDTOLogDataPackage,saveAuditOpLogBatch,findEntityLogByOpLogId,findOpLogDataPackage,findExactOpLogDataPackage,findOpLogDTODataPackage,saveAuditEntityLogBatch","release":"2.7.8","deprecated":"false","description":"服务提供者由AutoServiceBeanDefinitionRegistryPostProcessor自动注册","dubbo":"2.0.2","pid":"4336","interface":"com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService","generic":"false","revision":"3.1.0","path":"com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService","default":"true","protocol":"dubbo","application":"pmss-business","dynamic":"true","belong.to.value":"auditlog","service.filter":"tsieDubboExceptionFilter,-exception","category":"providers","anyhost":"true","timestamp":"1608811439995"},"enabled":true,"weight":1.0,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","ephemeral":true}],"dom":"DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","name":"DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","cacheMillis":10000,"lastRefTime":1608811444824,"checksum":"097b2c82249de6a51fa1facc00a1f0a0","useSpecifiedURL":false,"clusters":"","env":"","metadata":{}}`

**Acutally behavior**
the registry cached file content is
`{"hosts":[{"ip":"169.254.200.224","port":20880,"valid":true,"healthy":true,"marked":false,"instanceId":"169.254.200.224#20880#DEFAULT#DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","metadata":{"side":"provider","methods":"saveAuditLogBatch,findEntityLogByEntityId,findExactOpLogDTOLogDataPackage,saveAuditOpLogBatch,findEntityLogByOpLogId,findOpLogDataPackage,findExactOpLogDataPackage,findOpLogDTODataPackage,saveAuditEntityLogBatch","release":"2.7.8","deprecated":"false","description":"服务提供者由AutoServiceBeanDefinitionRegistryPostProcessor自动注册","dubbo":"2.0.2","pid":"4336","interface":"com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService","generic":"false","revision":"3.1.0","path":"com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService","default":"true","protocol":"dubbo","application":"pmss-business","dynamic":"true","belong.to.value":"auditlog","service.filter":"tsieDubboExceptionFilter,-exception","category":"providers","anyhost":"true","timestamp":"1608811439995"},"enabled":true,"weight":1.0,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","ephemeral":true}],"dom":"DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","name":"DEFAULT_GROUP@@providers:com.tsintergy.auditlog.serviceapi.facade.api.AuditLogFacadeService::","cacheMillis":10000,"lastRefTime":1608811444824,"checksum":"097b2c82249de6a51fa1facc00a1f0a0","useSpecifiedURL":false,"clusters":"","en`

**How to Reproduce**
1. download 1.3.1 version and unzip, use the default configuration
2. start nacos-server with startup.cmd, use nacos-client 1.3.1 version with spring-boot and dubbo

### easy reproduce:
refer to com.alibaba.nacos.client.naming.cacheDiskCache.write, run the follow code.

````
public class Test {
    public static void main(String[] args) throws IOException {
        File testFile = new File("testFileChannel.txt");
        testFile.createNewFile();
        String content = "{\"hosts\":[{\"ip\":\"169.254.200.224\",\"port\":20880,\"valid\":true,\"healthy\":true,\"marked\":false,\"instanceId\":\"169.254.200.224#20880#DEFAULT#DEFAULT_GROUP@@providers:com.tsieframework.cloud.security.serviceapi.system.api.SecurityService::\",\"metadata\":{\"side\":\"provider\",\"methods\":\"doBindExistAccount,doDealDeleteTsieRoleMenuBatch,queryTsieMenuByUserid,queryUserRole,queryAllMenuRole,queryUserRoleByUserid,doDealRoleMenuAuth,queryTsieUserVO,doChangeUserPassword,queryTsieGroupVO,queryTsieRoleMenu,queryTsieGroupUser,queryIfExistGroupRole,queryAllMenu,queryAllData,doTsieMenuVo,queryTsieRoleMenuTree,doDealTsieUserRoleVOBatch,doDealTsieRoleMenuBatch,queryAllRole,doDealTsieGroupUserBatch2,queryTsieMenuAllByUserId,doTsieRoleVo,doDealTsieUserRoleVO,doTsieGroupVo,doDealTsieGroupRole,queryGroupByGroupId,queryTsieGroupRole,doResetUserPassword,queryUserRoleAll,doTsieUserVo,queryTsieRoleVO,queryTsieUserVo,doChangeMyPassword,doDealTsieGroupRoleBatch,queryTsieMenuVO,doGenerateMenu,doDealTsieGroupUser,doBindNewAccount,queryTsieUserGroup,doDealTsieGroupUserBatch,doDealTsieRoleMenu,queryTsieUserMenuTree\",\"release\":\"2.7.8\",\"deprecated\":\"false\",\"description\":\"服务提供者由AutoServiceBeanDefinitionRegistryPostProcessor自动注册\",\"dubbo\":\"2.0.2\",\"pid\":\"4336\",\"interface\":\"com.tsieframework.cloud.security.serviceapi.system.api.SecurityService\",\"generic\":\"false\",\"revision\":\"3.1.0\",\"path\":\"com.tsieframework.cloud.security.serviceapi.system.api.SecurityService\",\"default\":\"true\",\"protocol\":\"dubbo\",\"application\":\"pmss-business\",\"dynamic\":\"true\",\"belong.to.value\":\"security\",\"service.filter\":\"tsieDubboExceptionFilter,-exception\",\"category\":\"providers\",\"anyhost\":\"true\",\"timestamp\":\"1608859748891\"},\"enabled\":true,\"weight\":1.0,\"clusterName\":\"DEFAULT\",\"serviceName\":\"DEFAULT_GROUP@@providers:com.tsieframework.cloud.security.serviceapi.system.api.SecurityService::\",\"ephemeral\":true}],\"dom\":\"DEFAULT_GROUP@@providers:com.tsieframework.cloud.security.serviceapi.system.api.SecurityService::\",\"name\":\"DEFAULT_GROUP@@providers:com.tsieframework.cloud.security.serviceapi.system.api.SecurityService::\",\"cacheMillis\":10000,\"lastRefTime\":1608859748927,\"checksum\":\"d5299e87b07caf4dc1622f0e190247a6\",\"useSpecifiedURL\":false,\"clusters\":\"\",\"env\":\"\",\"metadata\":{}}";
        ConcurrentDiskUtil.writeFileContent(testFile, content, Charset.defaultCharset().toString());

    }
}
````

**Desktop (please complete the following information):**
 - OS: win10 EE
 - Module [naming/config]
 - SDK [ spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
I remember this problem has been fixed. Can you upgrade the version of client and retry ?

**Comment by KomachiSion** [comment]
duplicate with https://github.com/alibaba/nacos/issues/3815

Please upgrade 1.4.0 and retry.

**Comment by xinhaiCai** [comment]
It works,thank you.
