### ISSUE TITLE
nacos 注册实例到server失败

### ISSUE THREAD

**Issue by adminSxs** [alibaba/nacos#4646]
nacos server version: 1.4.0
能读取到配置，但是注册实例到nacos server就报错

```
[REGISTER-SERVICE] 16b4869a-06ed-45c3-9837-622ced825224 registering service dev@@wiz-account-service with instance: Instance{instanceId='null', ip='10.244.5.214', port=8080, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={preserved.register.source=SPRING_CLOUD}}
2021-01-07 06:07:48.270 ERROR 1 --- [           main] com.alibaba.nacos.client.naming          : [NA] failed to request

com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Jan 07 14:07:48 CST 2021</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 10.244.20.1</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:611) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:239) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:200) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:70) [spring-cloud-starter-alibaba-nacos-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) [spring-cloud-starter-alibaba-nacos-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:166) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at com.wiz.accounts.Application.main(Application.java:22) [classes!/:2.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_275]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [accounts.jar:2.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [accounts.jar:2.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [accounts.jar:2.0.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [accounts.jar:2.0.0]

2021-01-07 06:07:48.295 ERROR 1 --- [           main] com.alibaba.nacos.client.naming          : [NA] failed to request

com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Jan 07 14:07:48 CST 2021</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 10.244.7.91</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:611) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:538) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:239) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:200) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:70) [spring-cloud-starter-alibaba-nacos-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) [spring-cloud-starter-alibaba-nacos-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:166) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at com.wiz.accounts.Application.main(Application.java:22) [classes!/:2.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_275]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [accounts.jar:2.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [accounts.jar:2.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [accounts.jar:2.0.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [accounts.jar:2.0.0]

2021-01-07 06:07:48.312 ERROR 1 --- [           main] com.alibaba.nacos.client.naming          : [NA] failed to request

com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Thu Jan 07 14:07:48 CST 2021</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 10.244.17.34</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:611) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:538) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:239) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:200) [nacos-client-1.3.3.jar!/:na]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:70) [spring-cloud-starter-alibaba-nacos-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) [spring-cloud-starter-alibaba-nacos-discovery-2.1.3.RELEASE.jar!/:2.1.3.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) [spring-cloud-commons-2.1.2.RELEASE.jar!/:2.1.2.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:166) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552) [spring-context-5.1.6.RELEASE.jar!/:5.1.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248) [spring-boot-2.1.4.RELEASE.jar!/:2.1.4.RELEASE]
	at com.wiz.accounts.Application.main(Application.java:22) [classes!/:2.0.0]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_275]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_275]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_275]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_275]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48) [accounts.jar:2.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87) [accounts.jar:2.0.0]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50) [accounts.jar:2.0.0]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51) [accounts.jar:2.0.0]

```

**Comment by horizonzy** [comment]
你好，请问你的nacos-server是集群部署的吗。
`10.244.17.34`,`10.244.7.91`, `10.244.20.1`这三个机器是否是你的nacos-server集群的节点。

**Comment by KomachiSion** [comment]
推测是3台节点的配置文件有问题，导致distro协议没有路由到正确的处理节点，
麻烦提供下3台机器的`conf/cluster.conf`文件，以及3台节点上`grep "healthy server list" naming-server.log`的结果。

**Comment by adminSxs** [comment]
> 你好，请问你的nacos-server是集群部署的吗。
> `10.244.17.34`,`10.244.7.91`, `10.244.20.1`这三个机器是否是你的nacos-server集群的节点。

ip不对，不是这个ip

**Comment by adminSxs** [comment]
> 你好，请问你的nacos-server是集群部署的吗。
> `10.244.17.34`,`10.244.7.91`, `10.244.20.1`这三个机器是否是你的nacos-server集群的节点。

是集群，部署到k8s的，但是我不是参考官方文档的

**Comment by adminSxs** [comment]
> 推测是3台节点的配置文件有问题，导致distro协议没有路由到正确的处理节点，
> 麻烦提供下3台机器的`conf/cluster.conf`文件，以及3台节点上`grep "healthy server list" naming-server.log`的结果。

我是部署到k8s的，用的的service注册的  nacos-serve1.nacos.svc:8488,nacos-serve2.nacos.svc:8488,nacos-serve3.nacos.svc:8488,这样的。能拉取到配置，就是无法注册

**Comment by horizonzy** [comment]
> > 你好，请问你的nacos-server是集群部署的吗。
> > `10.244.17.34`,`10.244.7.91`, `10.244.20.1`这三个机器是否是你的nacos-server集群的节点。
> :
> ip不对，不是这个ip

这几个ip是什么机器，是客户端的机器嘛？如果是的话，我推测是客户端的请求被加了请求头`User-Agent: Nacos-Server`

**Comment by adminSxs** [comment]
> > > 你好，请问你的nacos-server是集群部署的吗。
> > > `10.244.17.34`,`10.244.7.91`, `10.244.20.1`这三个机器是否是你的nacos-server集群的节点。
> > > :
> > > ip不对，不是这个ip
> 
> 这几个ip是什么机器，是客户端的机器嘛？如果是的话，我推测是客户端的请求被加了请求头`User-Agent: Nacos-Server`

![image](https://user-images.githubusercontent.com/15902505/103984502-3931c380-51c2-11eb-8c4e-75cceaf8a58d.png)

**Comment by adminSxs** [comment]
> > > 你好，请问你的nacos-server是集群部署的吗。
> > > `10.244.17.34`,`10.244.7.91`, `10.244.20.1`这三个机器是否是你的nacos-server集群的节点。
> > > :
> > > ip不对，不是这个ip
> 
> 这几个ip是什么机器，是客户端的机器嘛？如果是的话，我推测是客户端的请求被加了请求头`User-Agent: Nacos-Server`

实际上这几个ip我没有

**Comment by KomachiSion** [comment]
参考一下https://github.com/nacos-group/nacos-docker 的exmaple

docker或k8s启动时 如果使用host模式需要添加 `PREFER_HOST_MODE`

对应到nacos的实际启动参数是 `-Dnacos.preferHostnameOverIp=true`

**Comment by adminSxs** [comment]
> PREFER_HOST_MODE

就是没有加PREFER_HOST_MODE，已经配置好了。非常感谢

**Comment by adminSxs** [comment]
> 参考一下https://github.com/nacos-group/nacos-docker 的exmaple
> 
> docker或k8s启动时 如果使用host模式需要添加 `PREFER_HOST_MODE`
> 
> 对应到nacos的实际启动参数是 `-Dnacos.preferHostnameOverIp=true`

遇到一个问题，我有三个环境，相同的的代码，用namespace区分。注册到nacos server上去，只有一个环境有实例显示。另外两个没有实例，但是通过fegin调用又能调用到。这个是怎么回事

**Comment by horizonzy** [comment]
> 遇到一个问题，我有三个环境，相同的的代码，用namespace区分。注册到nacos server上去，只有一个环境有实例显示。另外两个没有实例，但是通过fegin调用又能调用到。这个是怎么回事

确认一下是否是你在应用配置中输入namespaceId和console控制台中的不一致。console控制台上用的是名称显示，在应用配置中需要用namespaceId

**Comment by KomachiSion** [comment]
> > 参考一下https://github.com/nacos-group/nacos-docker 的exmaple
> > docker或k8s启动时 如果使用host模式需要添加 `PREFER_HOST_MODE`
> > 对应到nacos的实际启动参数是 `-Dnacos.preferHostnameOverIp=true`
> 
> 遇到一个问题，我有三个环境，相同的的代码，用namespace区分。注册到nacos server上去，只有一个环境有实例显示。另外两个没有实例，但是通过fegin调用又能调用到。这个是怎么回事

这是个新的问题 请重新open issue进行提问。 好像原来那个问题已经解决了，我先关闭该issue了
