### ISSUE TITLE
用docker打包spring boot 注册nacos老是出错

### ISSUE THREAD

**Issue by whatkind** [alibaba/nacos#4667]
日志是现实注册成功的，但是后来又报错。我试了本地IP注册，阿里云的内网IP注册，外网IP注册，都不行
```log
04:52:12.121 [main] INFO  com.alibaba.cloud.nacos.registry.NacosServiceRegistry - nacos registry, DEFAULT_GROUP auth 172.17.0.3:9001 register finished
04:52:12.126 [main] INFO  com.qmhd.auth.AuthApplication - Started AuthApplication in 8.188 seconds (JVM running for 9.288)
04:52:12.139 [main] INFO  com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-localhost_8848] [subscribe] auth+DEFAULT_GROUP
04:52:12.141 [main] INFO  com.alibaba.nacos.client.config.impl.CacheData - [fixed-localhost_8848] [add-listener] ok, tenant=, dataId=auth, group=DEFAULT_GROUP, cnt=1
04:52:12.141 [main] INFO  com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-localhost_8848] [subscribe] auth.yaml+DEFAULT_GROUP
04:52:12.141 [main] INFO  com.alibaba.nacos.client.config.impl.CacheData - [fixed-localhost_8848] [add-listener] ok, tenant=, dataId=auth.yaml, group=DEFAULT_GROUP, cnt=1
04:52:12.151 [com.alibaba.nacos.client.Worker.longPolling.fixed-localhost_8848] ERROR com.alibaba.nacos.client.config.http.ServerHttpAgent - [NACOS ConnectException httpPost] currentServerAddr: http://localhost:8848, err : Connection refused (Connection refused)
04:52:12.351 [com.alibaba.nacos.client.Worker.longPolling.fixed-localhost_8848] ERROR com.alibaba.nacos.client.config.http.ServerHttpAgent - [NACOS ConnectException httpPost] currentServerAddr: http://localhost:8848, err : Connection refused (Connection refused)
04:52:12.552 [com.alibaba.nacos.client.Worker.longPolling.fixed-localhost_8848] ERROR com.alibaba.nacos.client.config.http.ServerHttpAgent - [NACOS ConnectException httpPost] currentServerAddr: http://localhost:8848, err : Connection refused (Connection refused)
04:52:12.751 [com.alibaba.nacos.client.Worker.longPolling.fixed-localhost_8848] ERROR com.alibaba.nacos.client.config.http.ServerHttpAgent - [NACOS ConnectException httpPost] currentServerAddr: http://localhost:8848, err : Connection refused (Connection refused)
04:52:12.752 [com.alibaba.nacos.client.Worker.longPolling.fixed-localhost_8848] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - [fixed-localhost_8848] [check-update] get changed dataId exception
java.net.ConnectException: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:170) ~[nacos-client-1.2.1.jar!/:?]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.2.1.jar!/:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:386) [nacos-client-1.2.1.jar!/:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:354) [nacos-client-1.2.1.jar!/:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:521) [nacos-client-1.2.1.jar!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]
04:52:12.752 [com.alibaba.nacos.client.Worker.longPolling.fixed-localhost_8848] ERROR com.alibaba.nacos.client.config.impl.ClientWorker - longPolling error : 
java.net.ConnectException: [NACOS HTTP-POST] The maximum number of tolerable server reconnection errors has been reached
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:170) ~[nacos-client-1.2.1.jar!/:?]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:64) ~[nacos-client-1.2.1.jar!/:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:386) ~[nacos-client-1.2.1.jar!/:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:354) ~[nacos-client-1.2.1.jar!/:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:521) [nacos-client-1.2.1.jar!/:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

```

**Comment by horizonzy** [comment]
The error info show that `connection refused`. Did you start nacos-server which listen 8848 port in your localhost.

**Comment by whatkind** [comment]
> The error info show that `connection refused`. Did you start nacos-server which listen 8848 port in your localhost.

this is my bootstrap.yml config
```
spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: 172.26.208.64:8848
```
Dockerfile
```
FROM java:8
MAINTAINER qmhd
RUN mkdir -p /data/docker/auth/config
COPY auth-1.0-SNAPSHOT.jar /app.jar
WORKDIR /data/docker/auth
EXPOSE 9001
ENTRYPOINT ["java", "-jar", "/app.jar","--spring.config.location=/data/docker/auth/config/bootstrap.yml,/data/docker/auth/config/application.yml"]
```
but docker logs is `localhost:8848`

**Comment by horizonzy** [comment]
> 
> this is my bootstrap.yml config
> 
> ```
> spring:
>   application:
>     name: auth
>   cloud:
>     nacos:
>       discovery:
>         server-addr: 172.26.208.64:8848
> ```

You just config the `discover.server-addr`, also need config `config.server-addr`.

**Comment by whatkind** [comment]
> > this is my bootstrap.yml config
> > ```
> > spring:
> >   application:
> >     name: auth
> >   cloud:
> >     nacos:
> >       discovery:
> >         server-addr: 172.26.208.64:8848
> > ```
> 
> You just config the `discover.server-addr`, also need config `config.server-addr`.

thank you for the perfect solution!
bootstrap.yml
```
spring:
  application:
    name: auth
  cloud:
    nacos:
      discovery:
        server-addr: 172.26.208.64:8848
      config:
        server-addr: 172.26.208.64:8848
        file-extension: yaml
        prefix: ${spring.application.name}
        group: DEFAULT_GROUP
```
