### ISSUE TITLE
nacos 升级1.4.1之后开启鉴权，注册到配置中心的时候报unkown user

### ISSUE THREAD

**Issue by sky-dail** [alibaba/nacos#4723]
**Describe the bug**

nacos 升级1.4.1使用 docker 部署，配置用户名密码之后，可以获取nacos配置，但是注册到注册中心时报了个unkown user，对应nacos-client依赖也升级到了1.4.1
java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:787)
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:768)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:322)
Caused by: com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Sun Jan 17 14:39:51 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:306)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:155)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:98)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigAndSignListener(NacosConfigService.java:104)
	at kl.pki.common.nacos.listener.NacosConfigListener.dynamicLocaleMessageByNacosListener(NacosConfigListener.java:68)
	at kl.pki.common.nacos.listener.NacosConfigListener.run(NacosConfigListener.java:87)
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:784)
	... 3 common frames omitted

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
看下注册中心相关配置是不是也配置了正确的用户名密码。

**Comment by sky-dail** [comment]
> 看下注册中心相关配置是不是也配置了正确的用户名密码。
> 
> 而且报错的信息并不是注册中心 而是配置中心。

都配置了用户名密码，但是我的配置中心的是写在bootstrap.yml里面的，注册中心是写在application.yml里面的

**Comment by KomachiSion** [comment]
都配在bootstrap.yml试试看

**Comment by foryq** [comment]
高版本有个bug，至少我觉得是个bug，就是用户名密码不能带特殊字符，如果带特殊字符就会报：There was an unexpected error (type=Forbidden, status=403).
unknown user!
管理台可以正常登录，但是服务去连就会报，不知道你是不是这个问题

**Comment by hegphegp** [comment]
> 1.4.1版本有个bug，至少我觉得是个bug，就是用户名密码不能带特殊字符，如果带特殊字符就会报：There was an unexpected error (type=Forbidden, status=403).
> unknown user!
> 管理台可以正常登录，但是服务去连就会报，不知道你是不是这个问题

我试了很多次，发现在spring-cloud-starter-alibaba-nacos-discovery:2021.1也存在这个bug，你是怎么解决的？

**Comment by foryq** [comment]
要么改源码，要么不用特殊字符，看你自己需求。

**Comment by foryq** [comment]
> > 1.4.1版本有个bug，至少我觉得是个bug，就是用户名密码不能带特殊字符，如果带特殊字符就会报：There was an unexpected error (type=Forbidden, status=403).
> > unknown user!
> > 管理台可以正常登录，但是服务去连就会报，不知道你是不是这个问题
> 
> 我试了很多次，发现在spring-cloud-starter-alibaba-nacos-discovery:2021.1也存在这个bug，你是怎么解决的？

要么改源码重新打包，要么不用特殊字符，看你自己需求

**Comment by wangdejian163** [comment]
> > > 1.4.1版本的bug，至少我觉得是个bug，就是用户名密码不能带特殊字符，如果带特殊字符会报告：There was an unexpected error (type=Forbid, status=403)。
> > > 未知用户！
> > > 管理台正常登录，但服务去连可以报，不知道你不是这个问题
> > 
> > 
> > 我试了很多次，发现在spring-cloud-starter-alibaba-nacos-discovery:2021.1也存在这个bug，你是怎么解决的？
> 
> 原来改原重打包，不用特殊的文字，看你自己的需求

确实是个bug，密码修改成特殊字符后。nacos管理正常登录。服务注册启动后会报403，unknown user。
