### ISSUE TITLE
nacos-config: After the configuration is released, the next release cannot take effect

### ISSUE THREAD

**Issue by admintertar** [alibaba/nacos#4731]
The first release configuration is valid, then an error is reported, and the next release is invalid
![image](https://user-images.githubusercontent.com/29689362/104894704-00f36780-59b0-11eb-9ef8-ffcb0a6ebe5e.png)
After modifying user.name, issue an error
修改user.name后，发布报错

**Desktop (please complete the following information):**
 - OS: [windows10]
 - Version [ nacos-server 1.4.1, nacos-client 1.4.1]
 - Module [config]
 - SDK [spring-cloud-alibaba-nacos]

2021-01-18 17:05:29.021  INFO 22084 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [polling-resp] config changed. dataId=fxk-system, group=DEFAULT_GROUP
2021-01-18 17:05:29.021  INFO 22084 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : get changedGroupKeys:[fxk-system+DEFAULT_GROUP]
2021-01-18 17:05:29.025  INFO 22084 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [data-received] dataId=fxk-system, group=DEFAULT_GROUP, tenant=null, md5=6c97dd04af2e612e296c009d4e19978a, content=user: 
 name: toms, type=yaml
2021-01-18 17:05:29.026  INFO 22084 --- [-127.0.0.1_8848] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [notify-context] dataId=fxk-system, group=DEFAULT_GROUP, md5=6c97dd04af2e612e296c009d4e19978a
2021-01-18 17:05:29.681  WARN 22084 --- [-127.0.0.1_8848] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[fxk-system.yaml] & group[DEFAULT_GROUP]
2021-01-18 17:05:29.681  INFO 22084 --- [-127.0.0.1_8848] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-fxk-system.yaml,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-fxk-system,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-all-service.yaml,DEFAULT_GROUP'}]
2021-01-18 17:05:29.682  INFO 22084 --- [-127.0.0.1_8848] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2021-01-18 17:05:29.692  INFO 22084 --- [-127.0.0.1_8848] o.s.boot.SpringApplication               : Started application in 0.663 seconds (JVM running for 16.606)
2021-01-18 17:05:29.694  INFO 22084 --- [-127.0.0.1_8848] c.a.n.c.config.http.ServerHttpAgent      : com.alibaba.nacos.client.config.http.ServerHttpAgent do shutdown begin
2021-01-18 17:05:29.694  WARN 22084 --- [-127.0.0.1_8848] com.alibaba.nacos.client.naming          : [ConfigHttpClientManager] Start destroying NacosRestTemplate
2021-01-18 17:05:29.694  WARN 22084 --- [-127.0.0.1_8848] com.alibaba.nacos.client.naming          : [ConfigHttpClientManager] Destruction of the end
2021-01-18 17:05:29.694  INFO 22084 --- [-127.0.0.1_8848] c.a.n.client.identify.CredentialWatcher  : [null] CredentialWatcher is stopped
2021-01-18 17:05:29.694  INFO 22084 --- [-127.0.0.1_8848] c.a.n.client.identify.CredentialService  : [null] CredentialService is freed
2021-01-18 17:05:29.694  INFO 22084 --- [-127.0.0.1_8848] c.a.n.c.config.http.ServerHttpAgent      : com.alibaba.nacos.client.config.http.ServerHttpAgent do shutdown stop
2021-01-18 17:05:29.694  INFO 22084 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : com.alibaba.nacos.client.config.impl.ClientWorker do shutdown begin
2021-01-18 17:05:32.720  INFO 22084 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : com.alibaba.nacos.client.config.impl.ClientWorker do shutdown stop
2021-01-18 17:05:32.823  INFO 22084 --- [-127.0.0.1_8848] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [user.name]
2021-01-18 17:05:32.823  INFO 22084 --- [-127.0.0.1_8848] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [notify-ok] dataId=fxk-system, group=DEFAULT_GROUP, md5=6c97dd04af2e612e296c009d4e19978a, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@69af2130 
2021-01-18 17:05:32.823  INFO 22084 --- [-127.0.0.1_8848] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [notify-listener] time cost=3797ms in ClientWorker, dataId=fxk-system, group=DEFAULT_GROUP, md5=6c97dd04af2e612e296c009d4e19978a, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@69af2130 
2021-01-18 17:05:32.828 ERROR 22084 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : longPolling error : 

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@304e7247 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@7465c4a2[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 1]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[na:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) [na:1.8.0_251]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) ~[na:1.8.0_251]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) ~[na:1.8.0_251]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622) ~[na:1.8.0_251]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635) ~[nacos-client-1.4.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_251]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_251]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_251]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_251]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_251]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_251]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_251]

2021-01-18 17:05:33.295  INFO 22084 --- [ing.beat.sender] c.a.n.client.identify.CredentialWatcher  : null No credential found

**Comment by admintertar** [comment]
![image](https://user-images.githubusercontent.com/29689362/104895143-795a2880-59b0-11eb-9cc4-4597eb976321.png)

**Comment by KomachiSion** [comment]
Nacos 已经正确推送了配置，日志已经显示了。

从日志上看，应用启动起来之后立刻就被关闭了。

```
2021-01-18 17:05:29.692 INFO 22084 --- [-127.0.0.1_8848] o.s.boot.SpringApplication : Started application in 0.663 seconds (JVM running for 16.606)
2021-01-18 17:05:29.694 INFO 22084 --- [-127.0.0.1_8848] c.a.n.c.config.http.ServerHttpAgent : com.alibaba.nacos.client.config.http.ServerHttpAgent do shutdown begin
```

建议排查一下自己应用的问题。

**Comment by admintertar** [comment]
> 纳科斯
> 
> 从日志上看，应用启动起来之后立刻就被关闭了。
> 
> ```
> 2021-01-18 17:05:29.692 INFO 22084 --- [-127.0.0.1_8848] o.s.boot.SpringApplication : Started application in 0.663 seconds (JVM running for 16.606)
> 2021-01-18 17:05:29.694 INFO 22084 --- [-127.0.0.1_8848] c.a.n.c.config.http.ServerHttpAgent : com.alibaba.nacos.client.config.http.ServerHttpAgent do shutdown begin
> ```
> 
> 建议排查一下自己应用的问题。

我使用了spring-cloud-alibaba-examples下面的nacos-config-example这个项目运行，也是出现这样的问题。

启动后到报错的完整日志：


  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v2.3.2.RELEASE)

2021-01-18 17:47:08.454  INFO 16564 --- [           main] c.a.n.c.c.impl.LocalConfigInfoProcessor  : LOCAL_SNAPSHOT_PATH:C:\Users\PING\nacos\config
2021-01-18 17:47:08.471  WARN 16564 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[test2.yaml] & group[DEFAULT_GROUP]
2021-01-18 17:47:08.476  WARN 16564 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[extension1.properties] & group[DEFAULT_GROUP]
2021-01-18 17:47:08.480  WARN 16564 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[test1.yml] & group[DEFAULT_GROUP]
2021-01-18 17:47:08.487  WARN 16564 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[test-aaa] & group[DEFAULT_GROUP]
2021-01-18 17:47:08.491  WARN 16564 --- [           main] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[test-aaa.yaml] & group[DEFAULT_GROUP]
2021-01-18 17:47:08.492  INFO 16564 --- [           main] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-test-aaa.yaml,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-test-aaa,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-test1.yml,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-extension1.properties,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-test2.yaml,DEFAULT_GROUP'}]
2021-01-18 17:47:08.501  INFO 16564 --- [           main] com.alibaba.cloud.examples.Application   : No active profile set, falling back to default profiles: default
2021-01-18 17:47:09.425  INFO 16564 --- [           main] o.s.cloud.context.scope.GenericScope     : BeanFactory id=7d04a59e-a9c9-30ac-b885-f11074779095
2021-01-18 17:47:09.629  INFO 16564 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 18084 (http)
2021-01-18 17:47:09.635  INFO 16564 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2021-01-18 17:47:09.636  INFO 16564 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet engine: [Apache Tomcat/9.0.37]
2021-01-18 17:47:09.699  INFO 16564 --- [           main] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2021-01-18 17:47:09.700  INFO 16564 --- [           main] w.s.c.ServletWebServerApplicationContext : Root WebApplicationContext: initialization completed in 1176 ms
2021-01-18 17:47:10.066  INFO 16564 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2021-01-18 17:47:10.650  INFO 16564 --- [           main] o.s.b.a.e.web.EndpointLinksResolver      : Exposing 16 endpoint(s) beneath base path '/actuator'
2021-01-18 17:47:10.740  INFO 16564 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 18084 (http) with context path ''
2021-01-18 17:47:10.991  INFO 16564 --- [           main] com.alibaba.cloud.examples.Application   : Started Application in 4.677 seconds (JVM running for 5.821)
Initial username=PING, userAge=25
2021-01-18 17:47:10.997  INFO 16564 --- [           main] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [subscribe] nacos-config-example.properties+DEFAULT_GROUP
2021-01-18 17:47:10.999  INFO 16564 --- [           main] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [add-listener] ok, tenant=, dataId=nacos-config-example.properties, group=DEFAULT_GROUP, cnt=1
2021-01-18 17:47:11.001  INFO 16564 --- [           main] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [subscribe] test-aaa+DEFAULT_GROUP
2021-01-18 17:47:11.001  INFO 16564 --- [           main] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [add-listener] ok, tenant=, dataId=test-aaa, group=DEFAULT_GROUP, cnt=1
2021-01-18 17:47:11.001  INFO 16564 --- [           main] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [subscribe] test1.yml+DEFAULT_GROUP
2021-01-18 17:47:11.001  INFO 16564 --- [           main] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [add-listener] ok, tenant=, dataId=test1.yml, group=DEFAULT_GROUP, cnt=1
2021-01-18 17:47:11.001  INFO 16564 --- [           main] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [subscribe] test-aaa.yaml+DEFAULT_GROUP
2021-01-18 17:47:11.001  INFO 16564 --- [           main] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [add-listener] ok, tenant=, dataId=test-aaa.yaml, group=DEFAULT_GROUP, cnt=1
2021-01-18 17:47:11.001  INFO 16564 --- [           main] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [subscribe] test2.yaml+DEFAULT_GROUP
2021-01-18 17:47:11.001  INFO 16564 --- [           main] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [add-listener] ok, tenant=, dataId=test2.yaml, group=DEFAULT_GROUP, cnt=1
2021-01-18 17:47:11.002  INFO 16564 --- [           main] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [subscribe] extension1.properties+DEFAULT_GROUP
2021-01-18 17:47:11.002  INFO 16564 --- [           main] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [add-listener] ok, tenant=, dataId=extension1.properties, group=DEFAULT_GROUP, cnt=1
2021-01-18 17:47:11.775  INFO 16564 --- [3)-172.31.160.1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring DispatcherServlet 'dispatcherServlet'
2021-01-18 17:47:11.775  INFO 16564 --- [3)-172.31.160.1] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
2021-01-18 17:47:11.782  INFO 16564 --- [3)-172.31.160.1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 7 ms
2021-01-18 17:49:48.754  INFO 16564 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [polling-resp] config changed. dataId=test-aaa.yaml, group=DEFAULT_GROUP
2021-01-18 17:49:48.754  INFO 16564 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : get changedGroupKeys:[test-aaa.yaml+DEFAULT_GROUP]
2021-01-18 17:49:48.763  INFO 16564 --- [-127.0.0.1_8848] c.a.nacos.client.config.utils.JvmUtil    : isMultiInstance:false
2021-01-18 17:49:48.765  INFO 16564 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : [fixed-127.0.0.1_8848] [data-received] dataId=test-aaa.yaml, group=DEFAULT_GROUP, tenant=null, md5=b3ff497f6ccec67c402b3c94f6b2a85e, content=user: 
 name: 张三
 age: 99, type=yaml
2021-01-18 17:49:48.765  INFO 16564 --- [-127.0.0.1_8848] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [notify-context] dataId=test-aaa.yaml, group=DEFAULT_GROUP, md5=b3ff497f6ccec67c402b3c94f6b2a85e
2021-01-18 17:49:49.334  WARN 16564 --- [-127.0.0.1_8848] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[test2.yaml] & group[DEFAULT_GROUP]
2021-01-18 17:49:49.338  WARN 16564 --- [-127.0.0.1_8848] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[extension1.properties] & group[DEFAULT_GROUP]
2021-01-18 17:49:49.341  WARN 16564 --- [-127.0.0.1_8848] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[test1.yml] & group[DEFAULT_GROUP]
2021-01-18 17:49:49.345  WARN 16564 --- [-127.0.0.1_8848] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[test-aaa] & group[DEFAULT_GROUP]
2021-01-18 17:49:49.384  INFO 16564 --- [-127.0.0.1_8848] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-test-aaa.yaml,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-test-aaa,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-test1.yml,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-extension1.properties,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-test2.yaml,DEFAULT_GROUP'}]
2021-01-18 17:49:49.386  INFO 16564 --- [-127.0.0.1_8848] o.s.boot.SpringApplication               : No active profile set, falling back to default profiles: default
2021-01-18 17:49:49.393  INFO 16564 --- [-127.0.0.1_8848] o.s.boot.SpringApplication               : Started application in 0.623 seconds (JVM running for 164.223)
2021-01-18 17:49:49.395  INFO 16564 --- [-127.0.0.1_8848] c.a.n.c.config.http.ServerHttpAgent      : com.alibaba.nacos.client.config.http.ServerHttpAgent do shutdown begin
2021-01-18 17:49:49.396  WARN 16564 --- [-127.0.0.1_8848] com.alibaba.nacos.client.naming          : [ConfigHttpClientManager] Start destroying NacosRestTemplate
2021-01-18 17:49:49.396  WARN 16564 --- [-127.0.0.1_8848] com.alibaba.nacos.client.naming          : [ConfigHttpClientManager] Destruction of the end
2021-01-18 17:49:49.396  INFO 16564 --- [-127.0.0.1_8848] c.a.n.client.identify.CredentialWatcher  : [null] CredentialWatcher is stopped
2021-01-18 17:49:49.396  INFO 16564 --- [-127.0.0.1_8848] c.a.n.client.identify.CredentialService  : [null] CredentialService is freed
2021-01-18 17:49:49.396  INFO 16564 --- [-127.0.0.1_8848] c.a.n.c.config.http.ServerHttpAgent      : com.alibaba.nacos.client.config.http.ServerHttpAgent do shutdown stop
2021-01-18 17:49:49.396  INFO 16564 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : com.alibaba.nacos.client.config.impl.ClientWorker do shutdown begin
2021-01-18 17:49:52.421  INFO 16564 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : com.alibaba.nacos.client.config.impl.ClientWorker do shutdown stop
2021-01-18 17:49:52.509  INFO 16564 --- [-127.0.0.1_8848] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [user.age, user.name]
2021-01-18 17:49:52.510  INFO 16564 --- [-127.0.0.1_8848] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [notify-ok] dataId=test-aaa.yaml, group=DEFAULT_GROUP, md5=b3ff497f6ccec67c402b3c94f6b2a85e, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@713f05a 
2021-01-18 17:49:52.510  INFO 16564 --- [-127.0.0.1_8848] c.a.nacos.client.config.impl.CacheData   : [fixed-127.0.0.1_8848] [notify-listener] time cost=3745ms in ClientWorker, dataId=test-aaa.yaml, group=DEFAULT_GROUP, md5=b3ff497f6ccec67c402b3c94f6b2a85e, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@713f05a 
2021-01-18 17:49:52.512 ERROR 16564 --- [-127.0.0.1_8848] c.a.n.client.config.impl.ClientWorker    : longPolling error : 

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@46892300[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@3b45cda1[Wrapped task = com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable@5e8089aa]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@43f0fb0a[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 6]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:705) ~[na:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635) ~[nacos-client-1.4.1.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

2021-01-18 17:49:57.263  INFO 16564 --- [io-18084-exec-7] c.a.n.client.identify.CredentialWatcher  : null No credential found

**Comment by baobeidaodao** [comment]
我也遇到了这个问题。求解？
I also had this problem. help?

**Comment by admintertar** [comment]
> 我也遇到了这个问题。求解？
> I also had this problem. help?

目前看来是线程池被停止之后又向它提交了一个新的任务executorService.execute(this);
--还没找是什么原因停止了executorService这个线程池

**Comment by KomachiSion** [comment]
从大家反馈的日志来看， nacos获取的配置都是正确的，中文都可以显示
```
content=user:
name: 张三
age: 99, type=yaml
```

有可能是SCA解析的时候字符集没有对应上，然后解析失败之后，SCA直接shutdown了app。 然后很多shutdownhook就开始工作了。线程池之类的就都停止了。

**Comment by KomachiSion** [comment]
可以试一下其他版本的nacos+现在的SCA会不会报错。

**Comment by admintertar** [comment]
> 可以试一下其他版本的nacos+现在的SCA会不会报错。

1.3.1;1.3.2;1.4.0;1.4.1;2.0.0-ALPHA.1+现在的SCA都会出现这个问题

**Comment by KomachiSion** [comment]
那应该是SCA的问题了， 提到SCA社区吧。

**Comment by admintertar** [comment]
> 我也遇到了这个问题。求解？
> I also had this problem. help?

找到问题了，临时解决方法-修改如下源码：
![image](https://user-images.githubusercontent.com/29689362/104983853-8d516900-5a48-11eb-970e-e56ba9f94cfa.png)
，原因大概是spring触发容器释放资源资源的时候，这里没有判断服务的状态就直接调用shutDown了，导致后面HttpAgent和ClientWorker直接调用shutdown，，等SCA社区看看吧

**Comment by hanchen1234599** [comment]
这个问题在spring cloud 的 2.2.4中会出现，降一下版本就好了
