### ISSUE TITLE
2.0.0-ALPHA.1 升级 Nacos 2.0.0-ALPHA.2 后，配置获取的鉴权有问题

### ISSUE THREAD

**Issue by CherishCai** [alibaba/nacos#4732]
**Describe the bug**
2.0.0-ALPHA.1 正常获取到配置
升级 Nacos 2.0.0-ALPHA.2 后，login接口正确获取到 accessToken，但是配置获取的鉴权有问题

```java
2021-01-18 17:38:11.046 ERROR 24893 --- [           main] c.a.n.client.config.impl.ClientWorker    : [config_rpc_client] [sub-server-error]  dataId=mysql.properties, group=DEFAULT_GROUP, tenant=, code=Response{resultCode=500, errorCode=403, message='null', requestId='null'}
2021-01-18 17:38:11.052 ERROR 24893 --- [           main] c.alibaba.nacos.spring.util.NacosUtils   : Can't get content from dataId : mysql.properties , groupId : DEFAULT_GROUP

com.alibaba.nacos.api.exception.NacosException: http error, code=403,dataId=mysql.properties,group=DEFAULT_GROUP,tenant=
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:944) ~[nacos-client-2.0.0-ALPHA.2.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:380) ~[nacos-client-2.0.0-ALPHA.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:131) ~[nacos-client-2.0.0-ALPHA.2.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:74) ~[nacos-client-2.0.0-ALPHA.2.jar:na]
	at com.alibaba.nacos.spring.context.event.config.EventPublishingConfigService.getConfig(EventPublishingConfigService.java:60) ~[nacos-spring-context-0.3.6.jar:na]
	at com.alibaba.nacos.spring.util.NacosUtils.getContent(NacosUtils.java:334) ~[nacos-spring-context-0.3.6.jar:na]
	at com.alibaba.nacos.spring.util.config.NacosConfigLoader.load(NacosConfigLoader.java:92) [nacos-spring-context-0.3.6.jar:na]
	at com.alibaba.nacos.spring.core.env.AbstractNacosPropertySourceBuilder.doBuild(AbstractNacosPropertySourceBuilder.java:181) [nacos-spring-context-0.3.6.jar:na]
	at com.alibaba.nacos.spring.core.env.AbstractNacosPropertySourceBuilder.build(AbstractNacosPropertySourceBuilder.java:118) [nacos-spring-context-0.3.6.jar:na]
	at com.alibaba.nacos.spring.core.env.NacosPropertySourcePostProcessor.buildNacosPropertySources(NacosPropertySourcePostProcessor.java:151) [nacos-spring-context-0.3.6.jar:na]
	at com.alibaba.nacos.spring.core.env.NacosPropertySourcePostProcessor.processPropertySource(NacosPropertySourcePostProcessor.java:133) [nacos-spring-context-0.3.6.jar:na]
	at com.alibaba.nacos.spring.core.env.NacosPropertySourcePostProcessor.postProcessBeanFactory(NacosPropertySourcePostProcessor.java:118) [nacos-spring-context-0.3.6.jar:na]
	at com.alibaba.nacos.spring.util.NacosBeanUtils.invokeNacosPropertySourcePostProcessor(NacosBeanUtils.java:416) [nacos-spring-context-0.3.6.jar:na]
	at com.alibaba.nacos.spring.context.annotation.config.NacosConfigBeanDefinitionRegistrar.registerBeanDefinitions(NacosConfigBeanDefinitionRegistrar.java:73) [nacos-spring-context-0.3.6.jar:na]
	at org.springframework.context.annotation.ImportBeanDefinitionRegistrar.registerBeanDefinitions(ImportBeanDefinitionRegistrar.java:86) [spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromRegistrars$1(ConfigurationClassBeanDefinitionReader.java:384) [spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684) ~[na:1.8.0_202]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromRegistrars(ConfigurationClassBeanDefinitionReader.java:383) [spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:148) [spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:120) [spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:331) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:236) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:280) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:96) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:707) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:533) ~[spring-context-5.2.7.RELEASE.jar:5.2.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) ~[spring-boot-2.3.1.RELEASE.jar:2.3.1.RELEASE]
	at com.antbank.metis.example.SpringBootMySQLApplication.main(SpringBootMySQLApplication.java:12) ~[classes/:na]

```

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**
![image](https://user-images.githubusercontent.com/16837364/104898061-1cf90800-59b4-11eb-8865-376739af372c.png)

**Comment by CherishCai** [comment]
确认为 2.0.0-ALPHA.1 的鉴权有问题；
部署 2.0.0-ALPHA.2，对账号增加对应的 namespace 权限正常获取配置。

**Comment by hegphegp** [comment]
> 确认为 2.0.0-ALPHA.1 的鉴权有问题；
> 部署 2.0.0-ALPHA.2，对账号增加对应的 namespace 权限正常获取配置。

这个怎么解决，spring-cloud-starter-alibaba-nacos-discovery:2021.1也存在这个bug，这个bug一直存在，你是怎么解决的？

**Comment by CherishCai** [comment]
> > 确认为 2.0.0-ALPHA.1 的鉴权有问题；
> > 部署 2.0.0-ALPHA.2，对账号增加对应的 namespace 权限正常获取配置。
> 
> 这个怎么解决，spring-cloud-starter-alibaba-nacos-discovery:2021.1也存在这个bug，这个bug一直存在，你是怎么解决的？

建议用最新版的 Nacos 2 吧，官方可能解决了不少问题
