### ISSUE TITLE
用nacos下使用dubbo会连接旧的服务ip情况

### ISSUE THREAD

**Issue by txlaijava** [alibaba/nacos#4737]
### 运行环境
nacos 1.4.1
dubbo 2.7.5
### 问题
NACOS是单机模式启动，用之前的IP（192.168.198.122）正常启动过，然后更换nacos服务的IP地址（192.168.198.250），但消费者启动依然还是会请求旧的服务的IP地址。
`org.apache.dubbo.remoting.RemotingException: client(url: dubbo://192.168.198.122:20883/com.shopping.base.facade.theme.IDecorateTmplGroupService?anyhost=true&application=server-platform&category=providers&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&heartbeat=60000&init=false&interface=com.shopping.base.facade.theme.IDecorateTmplGroupService&logger=log4j2&methods=getOneObjByProperty,getObjById,save,update,detachObj,queryBySQL,delete,queryBySQLPage,getByGroupList,queryByNativeSQL,deleteByIds,getObjByProperty&path=com.shopping.base.facade.theme.IDecorateTmplGroupService&pid=27694&protocol=dubbo&qos.enable=false&register.ip=192.168.198.130&release=2.7.5&remote.application=registry-nacos-provider-theme&retries=0&revision=1.1.1-SNAPSHOT&side=consumer&sticky=false&timeout=6000&timestamp=1610680649102&version=zz) failed to connect to server /192.168.198.122:20883 client-side timeout 3000ms (elapsed: 3005ms) from netty client 192.168.198.130 using dubbo version 2.7.5
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:173) ~[dubbo-2.7.5.jar:2.7.5]
`
在nacos控制面板上已经显示服务是注册到新的地址上了，如图所示：
![image](https://qiniu.rblcmall.com/uPic/2l1wsq.jpg)
请问应该是什么问题？消费者端服务的配置已经改成注册中心新的IP地址。

**Comment by KomachiSion** [comment]
到消费者端看一下${user.home}/logs/nacos/naming.log 是否收到了该provider新的ip列表？ 如果收到了那可能是dubbo缓存了旧ip没有更新。

如果没有收到，麻烦把日志（客户端服务端）与这个provider和consumer相关的日志发出来。

**Comment by txlaijava** [comment]
@KomachiSion 删除掉${user.home}/nacos/naming/ 下文件就没问题了。能正常连接到新的服务。
请教下这个缓存机制是什么？为什么没有刷新旧的缓存？

**Comment by KomachiSion** [comment]
nacos客户端是会刷新缓存的。客户端收到服务列表变更后都会刷新本地缓存。

我建议还是先确认下日志是否收到。确认问题出在哪里

**Comment by txlaijava** [comment]
看日志的确有异常，是否这个原因导致provider未返回新的ip列表？
```
serviceName='DEFAULT_GROUP@@providers:com.shopping.base.facade.address.IUserAddressService:txl:', cluster='null', metadata={side=provider, methods=getOneObjByProperty,getObjById,save,update,deteleUserAddress,detachObj,queryBySQL,delete,queryBySQLPage,setAddressDefalut,setUserAddress,getUserAddressList,queryByNativeSQL,defalutAddress,deleteByIds,getObjByProperty, release=2.7.5, deprecated=false, dubbo=2.0.2, pid=17503, interface=com.shopping.base.facade.address.IUserAddressService, version=txl, generic=false, revision=1.1.1-SNAPSHOT, path=com.shopping.base.facade.address.IUserAddressService, protocol=dubbo, application=registry-nacos-provider-base, dynamic=true, category=providers, anyhost=true, timestamp=1611128266411}, scheduled=false, period=5000, stopped=false} to beat map.
2021-01-20 15:37:46.424 INFO [main :c.a.n.c.naming] [REGISTER-SERVICE] public registering service DEFAULT_GROUP@@providers:com.shopping.base.facade.address.IUserAddressService:txl: with instance: Instance{instanceId='null', ip='192.168.198.130', port=20880, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='null', serviceName='null', metadata={side=provider, methods=getOneObjByProperty,getObjById,save,update,deteleUserAddress,detachObj,queryBySQL,delete,queryBySQLPage,setAddressDefalut,setUserAddress,getUserAddressList,queryByNativeSQL,defalutAddress,deleteByIds,getObjByProperty, release=2.7.5, deprecated=false, dubbo=2.0.2, pid=17503, interface=com.shopping.base.facade.address.IUserAddressService, version=txl, generic=false, revision=1.1.1-SNAPSHOT, path=com.shopping.base.facade.address.IUserAddressService, protocol=dubbo, application=registry-nacos-provider-base, dynamic=true, category=providers, anyhost=true, timestamp=1611128266411}}
2021-01-20 15:37:46.427 ERROR [main :c.a.n.c.naming] [NA] failed to request
com.alibaba.nacos.api.exception.NacosException: caused: Get data failed, key: com.alibaba.nacos.naming.iplist.public##DEFAULT_GROUP@@providers:com.shopping.base.facade.address.IUserAddressService:txl:;
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:611) [nacos-client-1.3.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524) [nacos-client-1.3.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) [nacos-client-1.3.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486) [nacos-client-1.3.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:239) [nacos-client-1.3.2.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:200) [nacos-client-1.3.2.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:190) [nacos-client-1.3.2.jar:na]
	at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doRegister$1(NacosRegistry.java:150) [dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:473) [dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:150) [dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:240) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.registry.ListenerRegistryWrapper.register(ListenerRegistryWrapper.java:57) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:175) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:209) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:60) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:64) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:143) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:470) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:315) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:287) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:205) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.lambda$exportServices$13(DubboBootstrap.java:873) ~[dubbo-2.7.5.jar:2.7.5]
	at java.util.HashMap$Values.forEach(HashMap.java:980) ~[na:1.8.0_111]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.exportServices(DubboBootstrap.java:861) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.bootstrap.DubboBootstrap.start(DubboBootstrap.java:703) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onContextRefreshedEvent(DubboBootstrapApplicationListener.java:52) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.spring.context.DubboBootstrapApplicationListener.onApplicationContextEvent(DubboBootstrapApplicationListener.java:45) ~[dubbo-2.7.5.jar:2.7.5]
	at org.apache.dubbo.config.spring.context.OneTimeExecutionApplicationContextEventListener.onApplicationEvent(OneTimeExecutionApplicationContextEventListener.java:40) ~[dubbo-2.7.5.jar:2.7.5]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:403) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:360) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:897) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:140) ~[spring-boot-2.3.0.RELEASE.jar:2.3.0.RELEASE]
	at com.shopping.dubbo.provider.base.bootstrap.ProviderBaseBootstrap.main(ProviderBaseBootstrap.java:20) ~[classes/:na]
```

**Comment by KomachiSion** [comment]
这个日志是注册失败的日志， 看样子是dubbo注册这个服务失败了，然后就没有去注册consumer，所以一直没有更新服务列表。

由于不清楚你的依赖关系和启动方式， 可能需要你自己梳理一下，看下是不是启动顺序和依赖顺序有问题导致的。

比如先启动了consumer，然后从本地缓存中拿的ip直接去连接，发现连不上就直接报错，没有给nacos-client刷新缓存的机会，然后删除本地缓存之后只能等服务端返回新ip，所以可以启动。

**Comment by cyf0477** [comment]
> 这个日志是注册失败的日志， 看样子是dubbo注册这个服务失败了，然后就没有去注册consumer，所以一直没有更新服务列表。
> 
> 由于不清楚你的依赖关系和启动方式， 可能需要你自己梳理一下，看下是不是启动顺序和依赖顺序有问题导致的。
> 
> 比如先启动了consumer，然后从本地缓存中拿的ip直接去连接，发现连不上就直接报错，没有给nacos-client刷新缓存的机会，然后删除本地缓存之后只能等服务端返回新ip，所以可以启动。

最后这个先启动了consumer  本地拿没问题  ,但Provider 启动之后  还是会更新consumer 的    没说到点上
