### ISSUE TITLE
nacos启动正常注册服务异常

### ISSUE THREAD

**Issue by chengkai666** [alibaba/nacos#4746]
at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
Caused by: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([192.168.209.1:12222]) tried: failed to req API:192.168.209.1:12222/nacos/v1/ns/instance. code:500 msg: caused: Get data failed, key: com.alibaba.nacos.naming.iplist.public##DEFAULT_GROUP@@providers:cn.hsa.cep.usc.api.service.InsuEmpInfoService:1.0.0:USC-LOCAL;
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:464)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
        at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:188)
        at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:205)
        at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:184)
        at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doRegister$1(NacosRegistry.java:153)
        at org.apache.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:466)
        at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:153)
        at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:236)
        ... 36 common frames omitted
2021-01-19 15:56:08.205 - [] - [main] WARN  o.a.dubbo.registry.integration.RegistryProtocol.warn(91) -  [DUBBO] unregister url == null, dubbo version: 2.7.3, current host: 192.168.223.1
java.lang.IllegalArgumentException: unregister url == null

**Comment by KomachiSion** [comment]
Which version you used？I suggest that you upgrade version and retry, I see your version is too old.

**Comment by KomachiSion** [comment]
And can you find `[NA] failed to request` error log in your client log? This is the real error.

**Comment by chengkai666** [comment]
> And can you find `[NA] failed to request` error log in your client log? This is the real error
no ,This is the client error log, no more

**Comment by chengkai666** [comment]
> Which version you used？I suggest that you upgrade version and retry, I see your version is too old.

1.4.1 , but I switch to 1.3.1 it is okay ,no problem

**Comment by KomachiSion** [comment]
The community need the `[NA] failed to request` information, because we can't reproduce problem. Can you provide it?

**Comment by KomachiSion** [comment]
duplicate with #4836
