### ISSUE TITLE
配置更新发布后客户端报错bug

### ISSUE THREAD

**Issue by oilqw** [alibaba/nacos#4748]
使用版本 NACOS1.4.1

配置管理-配置列表-编辑配置 
打开编辑配置后 修改配置内容后 点击发布后  客户端更新时候报错  报错信息如下
 2021-01-19 16:29:30.830  INFO 12416 --- [10.13.0.91_8848] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [useLocalCache]
2021-01-19 16:29:30.830  INFO 12416 --- [10.13.0.91_8848] c.a.nacos.client.config.impl.CacheData   : [fixed-10.13.0.91_8848] [notify-ok] dataId=example, group=DEFAULT_GROUP, md5=7c0adb9a731d801469803e60b2257359, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@ad6f918 
2021-01-19 16:29:30.830  INFO 12416 --- [10.13.0.91_8848] c.a.nacos.client.config.impl.CacheData   : [fixed-10.13.0.91_8848] [notify-listener] time cost=3342ms in ClientWorker, dataId=example, group=DEFAULT_GROUP, md5=7c0adb9a731d801469803e60b2257359, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@ad6f918 
2021-01-19 16:29:30.830 ERROR 12416 --- [10.13.0.91_8848] c.a.n.client.config.impl.ClientWorker    : longPolling error : 

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@e2f2a2c rejected from java.util.concurrent.ScheduledThreadPoolExecutor@30c76ce8[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063) ~[na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830) [na:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326) ~[na:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533) ~[na:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622) ~[na:1.8.0_211]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635) ~[nacos-client-1.4.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_211]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_211]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_211]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_211]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_211]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_211]

2021-01-19 16:29:31.320  INFO 12416 --- [ing.beat.sender] c.a.n.client.identify.CredentialWatcher  : null No credential found

**Comment by christophe-liwei** [comment]
同样遇到这个问题，使用spring cloud动态配置

**Comment by horizonzy** [comment]
> 同样遇到这个问题，使用spring cloud动态配置

能够稳定复现吗？

**Comment by KomachiSion** [comment]
@christophe-liwei @oilqw  能试一下降低nacos版本 看下能不能复现吗？

**Comment by christophe-liwei** [comment]
@KomachiSion @horizonzy 是spring cloudalibaba的问题，已经解决

**Comment by KomachiSion** [comment]
Does it refer to https://github.com/alibaba/spring-cloud-alibaba/issues/1926 ?

**Comment by christophe-liwei** [comment]
yes @KomachiSion

**Comment by lucian521** [comment]
> 同样遇到这个问题，使用spring cloud动态配置

问下 spring cloud 如何动态配置  nacos
