### ISSUE TITLE
Dubbo could not register with nacos after nacos was upgraded to 1.4.0/1.4.1 and Auth verification was enabled

### ISSUE THREAD

**Issue by reminisences** [alibaba/nacos#4760]
Dubbo could not register with nacos after nacos was upgraded to 1.4.0/1.4.1 and Auth verification was enabled

nacos升级到1.4.0/1.4.1，并且开启auth验证后,dubbo无法注册到nacos. Dubbo配置username/password没起作用,请问这种情况如何破解？

`com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([192.168.1.10:8848]) tried: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Jan 20 16:30:23 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>unknown user!</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:556) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.deregisterService(NamingProxy.java:271) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.deregisterInstance(NacosNamingService.java:252) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.deregisterInstance(NacosNamingService.java:238) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.deregisterInstance(NacosNamingService.java:222) ~[nacos-client-1.4.1.jar:na]
	at org.apache.dubbo.registry.nacos.NacosRegistry.lambda$doUnregister$2(NacosRegistry.java:169) [dubbo-2.7.7.jar:2.7.7]`

Dependencies and versions
-nacos-spring-context 1.0.0
-nacos-client 1.4.1/1.4.0
-nacos-config-spring-boot-starter 0.2.7
-apache dubbo 2.7.7/2.7.8
-apache dubbo-spring-boot-starter 2.7.7/2.7.8

application.yml
dubbo:
  registry:
    parameters:
      namespace: ${nacos.namespace}
      username: ${nacos.username} #这样配置无效
      password: ${nacos.password} #这样配置无效
    address: nacos://${nacos.service-address}:${nacos.port}
    group: ${nacos.group}
    username: ${nacos.username} #这样配置无效
    password: ${nacos.password}  #这样配置无效
    register: true
    subscribe: true
    check: false

**Comment by horizonzy** [comment]
In dubbo project, just config the username and password in the registryConfig's url.
And `dubbo-spring-boot-starter` is not maintenance by anyone, I'm not sure it can support username and password.

Ask this question in [dubbo](https://github.com/apache/dubbo) community will be better.
