### ISSUE TITLE
Nacos 1.4.1 开启 Auth 后，动态刷新就报错了 - Null No credential found

### ISSUE THREAD

**Issue by Lee27149** [alibaba/nacos#4772]
```
2021-01-21 18:17:23.179  INFO 42860 --- [on(3)-127.0.0.1] o.s.web.servlet.DispatcherServlet        : Completed initialization in 9 ms
2021-01-21 18:20:29.011  INFO 42860 --- [c8-35f99ec0ab25] c.a.n.client.config.impl.ClientWorker    : [fixed-116.62.5.***_8848-5bcb010f-1e57-4aac-97c8-35f99ec0ab25] [polling-resp] config changed. dataId=common-test.yaml, group=DEFAULT_GROUP, tenant=5bcb010f-1e57-4aac-97c8-35f99ec0ab25
2021-01-21 18:20:29.011  INFO 42860 --- [c8-35f99ec0ab25] c.a.n.client.config.impl.ClientWorker    : get changedGroupKeys:[common-test.yaml+DEFAULT_GROUP+5bcb010f-1e57-4aac-97c8-35f99ec0ab25]
2021-01-21 18:20:29.068  INFO 42860 --- [c8-35f99ec0ab25] c.a.n.client.config.impl.ClientWorker    : [fixed-116.62.5.***_8848-5bcb010f-1e57-4aac-97c8-35f99ec0ab25] [data-received] dataId=common-test.yaml, group=DEFAULT_GROUP, tenant=5bcb010f-1e57-4aac-97c8-35f99ec0ab25, md5=53c6527efdd50016dfebc327dde5b0da, content=common_message: hello world!wocao444400087754544, type=yaml
2021-01-21 18:20:29.070  INFO 42860 --- [c8-35f99ec0ab25] c.a.nacos.client.config.impl.CacheData   : [fixed-116.62.5.***_8848-5bcb010f-1e57-4aac-97c8-35f99ec0ab25] [notify-context] dataId=common-test.yaml, group=DEFAULT_GROUP, md5=53c6527efdd50016dfebc327dde5b0da
2021-01-21 18:20:29.458  WARN 42860 --- [c8-35f99ec0ab25] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[provider] & group[DEFAULT_GROUP]
2021-01-21 18:20:29.483  WARN 42860 --- [c8-35f99ec0ab25] c.a.c.n.c.NacosPropertySourceBuilder     : Ignore the empty nacos configuration and get it based on dataId[provider.yaml] & group[DEFAULT_GROUP]
2021-01-21 18:20:29.516  INFO 42860 --- [c8-35f99ec0ab25] b.c.PropertySourceBootstrapConfiguration : Located property source: [BootstrapPropertySource {name='bootstrapProperties-provider-test.yaml,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-provider.yaml,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-provider,DEFAULT_GROUP'}, BootstrapPropertySource {name='bootstrapProperties-common-test.yaml,DEFAULT_GROUP'}]
2021-01-21 18:20:29.522  INFO 42860 --- [c8-35f99ec0ab25] o.s.boot.SpringApplication               : The following profiles are active: test
2021-01-21 18:20:29.539  INFO 42860 --- [c8-35f99ec0ab25] o.s.boot.SpringApplication               : Started application in 0.458 seconds (JVM running for 198.241)
2021-01-21 18:20:29.542  INFO 42860 --- [c8-35f99ec0ab25] c.a.n.c.config.http.ServerHttpAgent      : com.alibaba.nacos.client.config.http.ServerHttpAgent do shutdown begin
2021-01-21 18:20:29.542  WARN 42860 --- [c8-35f99ec0ab25] com.alibaba.nacos.client.naming          : [ConfigHttpClientManager] Start destroying NacosRestTemplate
2021-01-21 18:20:29.542  WARN 42860 --- [c8-35f99ec0ab25] com.alibaba.nacos.client.naming          : [ConfigHttpClientManager] Destruction of the end
2021-01-21 18:20:29.543  INFO 42860 --- [c8-35f99ec0ab25] c.a.n.client.identify.CredentialWatcher  : [null] CredentialWatcher is stopped
2021-01-21 18:20:29.543  INFO 42860 --- [c8-35f99ec0ab25] c.a.n.client.identify.CredentialService  : [null] CredentialService is freed
2021-01-21 18:20:29.543  INFO 42860 --- [c8-35f99ec0ab25] c.a.n.c.config.http.ServerHttpAgent      : com.alibaba.nacos.client.config.http.ServerHttpAgent do shutdown stop
2021-01-21 18:20:29.543  INFO 42860 --- [c8-35f99ec0ab25] c.a.n.client.config.impl.ClientWorker    : com.alibaba.nacos.client.config.impl.ClientWorker do shutdown begin
2021-01-21 18:20:29.719  INFO 42860 --- [ing.beat.sender] c.a.n.client.identify.CredentialWatcher  : null No credential found
2021-01-21 18:20:32.550  INFO 42860 --- [c8-35f99ec0ab25] c.a.n.client.config.impl.ClientWorker    : com.alibaba.nacos.client.config.impl.ClientWorker do shutdown stop
2021-01-21 18:20:32.791  INFO 42860 --- [c8-35f99ec0ab25] o.s.c.e.event.RefreshEventListener       : Refresh keys changed: [common_message]
2021-01-21 18:20:32.791  INFO 42860 --- [c8-35f99ec0ab25] c.a.nacos.client.config.impl.CacheData   : [fixed-116.62.5.***_8848-5bcb010f-1e57-4aac-97c8-35f99ec0ab25] [notify-ok] dataId=common-test.yaml, group=DEFAULT_GROUP, md5=53c6527efdd50016dfebc327dde5b0da, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@2d2e26fd 
2021-01-21 18:20:32.791  INFO 42860 --- [c8-35f99ec0ab25] c.a.nacos.client.config.impl.CacheData   : [fixed-116.62.5.***_8848-5bcb010f-1e57-4aac-97c8-35f99ec0ab25] [notify-listener] time cost=3721ms in ClientWorker, dataId=common-test.yaml, group=DEFAULT_GROUP, md5=53c6527efdd50016dfebc327dde5b0da, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@2d2e26fd 
2021-01-21 18:20:32.795 ERROR 42860 --- [c8-35f99ec0ab25] c.a.n.client.config.impl.ClientWorker    : longPolling error : 

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@55441ce8[Not completed, task = java.util.concurrent.Executors$RunnableAdapter@2370a8a0[Wrapped task = com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable@981daeb]] rejected from java.util.concurrent.ScheduledThreadPoolExecutor@4c3ada7d[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 8]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:340) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:562) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:705) ~[na:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635) ~[nacos-client-1.4.1.jar:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:834) ~[na:na]

```
**开启 auth 后，动态刷新就报错了。**

```
Spring-boot-version: 2.3.2.RELEASE
Spring-cloud.version: Hoxton.SR9
Sspring-cloud-alibaba.version: 2.2.4.RELEASE
```

**Comment by horizonzy** [comment]
这个不是报错。只是Info提示而已，这个在程序shutdown的时候进行打印。
应该是你的配置问题，导致应用没有启动成功。
```
core.auth.enabled: true
      ### 关闭使用user-agent判断服务端请求并放行鉴权的功能
      core.auth.enable.userAgentAuthWhite: false
      core.auth.server.identity.key: 123
      core.auth.server.identity.value: 123
```
这些配置是给nacos服务端使用的，不是给客户端使用的。客户端只需要配置用户名和密码。

**Comment by Lee27149** [comment]
mi

> 这个不是报错。只是Info提示而已，这个在程序shutdown的时候进行打印。
> 应该是你的配置问题，导致应用没有启动成功。

明白了

> 这个不是报错。只是Info提示而已，这个在程序shutdown的时候进行打印。
> 应该是你的配置问题，导致应用没有启动成功。
> 
> ```
> core.auth.enabled: true
>       ### 关闭使用user-agent判断服务端请求并放行鉴权的功能
>       core.auth.enable.userAgentAuthWhite: false
>       core.auth.server.identity.key: 123
>       core.auth.server.identity.value: 123
> ```
> 
> 这些配置是给nacos服务端使用的，不是给客户端使用的。客户端只需要配置用户名和密码。

明白了，谢谢！

**Comment by laydazz** [comment]
我也是这样，什么原因呢？有没有小伙伴知道的，咋解决的？
报了这个 at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635) ~[nacos-client-1.4.1.jar:na]

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@7046ef6d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3331a9b5[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 28]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(Unknown Source) ~[na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.reject(Unknown Source) [na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(Unknown Source) ~[na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(Unknown Source) ~[na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(Unknown Source) ~[na:1.8.0_202]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635) ~[nacos-client-1.4.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [na:1.8.0_202]
	at java.util.concurrent.FutureTask.run(Unknown Source) [na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(Unknown Source) [na:1.8.0_202]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(Unknown Source) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) [na:1.8.0_202]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) [na:1.8.0_202]
	at java.lang.Thread.run(Unknown Source) [na:1.8.0_202]
