### ISSUE TITLE
Question about ClientManager in Nacos 2.0.0 alpha2 

### ISSUE THREAD

**Issue by catcherwong** [alibaba/nacos#4788]
**Describe the bug**

After upgrading from alpha1 to alpha2, the registration instance of the naming module is unsuccessful.

When debugging, it is found that when `ClientManagerDelegate` obtains `ClientManager`, it obtains `ephemeralIpPortClientManager`, but the number of clients in it is 0, and only the `connectionBasedClientManager` has a corresponding client.

As a result, the obtained client is null, which leads to a null pointer.

-----

从alpha1升级到alpha2之后，naming 模块注册实例不成功。

调试的时候发现`ClientManagerDelegate`在获取`ClientManager`时，获取到的是`ephemeralIpPortClientManager`，但是它里面的client数量为0，只有`connectionBasedClientManager`里面才有对应的client。

导致获取到的client为null，从而引发空指针。

https://github.com/alibaba/nacos/blob/11ab95812b580969e28e127906eb8a37181033f0/naming/src/main/java/com/alibaba/nacos/naming/core/v2/client/manager/ClientManagerDelegate.java#L96-L100

![image](https://user-images.githubusercontent.com/8394988/105573241-05949300-5d97-11eb-9b46-d7c7d9d42752.png)

remote-digest.log 部分日志如下

```
2021-01-23 11:59:22,465 INFO Connection transportReady,connectionId = 1611374362465_0:0:0:0:0:0:0:1_60957 

2021-01-23 11:59:22,500 DEBUG [grpc]  server check request receive ,clientIp : 0:0:0:0:0:0:0:1 

2021-01-23 11:59:29,749 ERROR [grpc] fail to handle request ,error message :null

java.lang.NullPointerException: null
	at com.alibaba.nacos.naming.core.v2.service.impl.EphemeralClientOperationServiceImpl.registerInstance(EphemeralClientOperationServiceImpl.java:53)
	at com.alibaba.nacos.naming.remote.rpc.handler.InstanceRequestHandler.registerInstance(InstanceRequestHandler.java:63)
	at com.alibaba.nacos.naming.remote.rpc.handler.InstanceRequestHandler.handle(InstanceRequestHandler.java:53)
	at com.alibaba.nacos.naming.remote.rpc.handler.InstanceRequestHandler.handle(InstanceRequestHandler.java:37)
	at com.alibaba.nacos.core.remote.RequestHandler.handleRequest(RequestHandler.java:52)
	at com.alibaba.nacos.core.remote.grpc.GrpcRequestAcceptor.request(GrpcRequestAcceptor.java:88)
	at com.alibaba.nacos.core.remote.grpc.BaseGrpcServer.lambda$addServices$0(BaseGrpcServer.java:166)
	at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
	at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
	at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
	at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
	at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:814)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Expected behavior**

**Acutally behavior**

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS:  Windows
 - Version nacos-server 2.0.0 alpha2
 - Module naming
 - SDK nacos-sdk-csharp

**Additional context**

**Comment by catcherwong** [comment]
This also has a great influence on the `conn_id` generated by the server

alpha2 use timestamp remote ip and remote port

https://github.com/alibaba/nacos/blob/11ab95812b580969e28e127906eb8a37181033f0/core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java#L118

alpha1 use Uuid

https://github.com/alibaba/nacos/blob/26c6720f4e770c64e8631ba0ea970fb52bae9aae/core/src/main/java/com/alibaba/nacos/core/remote/grpc/BaseGrpcServer.java#L130

**Comment by KomachiSion** [comment]
2.0.0还处于ALPHA阶段， 有些接口和内容可能会发生更改，请以最新版本为准。

**Comment by KomachiSion** [comment]
如果是ipv6的话，好像客户端id有问题。

**Comment by catcherwong** [comment]
是的，说的是IPV6这个问题。

应该是`getClientManagerById`这里的判断需要调整一下。

**Comment by catcherwong** [comment]
It works now.

可以了。
