### ISSUE TITLE
Nacos 1.4.1 java.net.ConnectException: no available server, currentServerAddr

### ISSUE THREAD

**Issue by Lee27149** [alibaba/nacos#4794]
```
2021-01-24 20:16:20 | INFO  | com.alibaba.nacos.naming.beat.sender | com.alibaba.nacos.client.naming | [REGISTER-SERVICE] public registering service DEFAULT_GROUP@@user-service with instance: Instance{instanceId='null', ip='192.168.31.193', port=3301, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='DEFAULT_GROUP@@user-service', metadata={preserved.register.source=SPRING_CLOUD}}
2021-01-24 20:16:33 | ERROR | com.alibaba.nacos.client.Worker.longPolling.fixed-******_8848-ec9d8c56-d1ea-4a0f-9494-89fc4bdd0fc0 | com.alibaba.nacos.client.config.http.ServerHttpAgent | [NACOS SocketTimeoutException httpPost] currentServerAddr: http://******:8848， err : Read timed out
2021-01-24 20:16:33 | ERROR | com.alibaba.nacos.client.Worker.longPolling.fixed-******_8848-ec9d8c56-d1ea-4a0f-9494-89fc4bdd0fc0 | com.alibaba.nacos.client.config.http.ServerHttpAgent | no available server, currentServerAddr : http://******:8848
2021-01-24 20:16:33 | ERROR | com.alibaba.nacos.client.Worker.longPolling.fixed-******_8848-ec9d8c56-d1ea-4a0f-9494-89fc4bdd0fc0 | com.alibaba.nacos.client.config.impl.ClientWorker | [fixed-******_8848-ec9d8c56-d1ea-4a0f-9494-89fc4bdd0fc0] [check-update] get changed dataId exception
java.net.ConnectException: no available server, currentServerAddr : http://******:8848
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:190)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:68)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:441)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:408)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:596)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2021-01-24 20:16:33 | ERROR | com.alibaba.nacos.client.Worker.longPolling.fixed-******_8848-ec9d8c56-d1ea-4a0f-9494-89fc4bdd0fc0 | com.alibaba.nacos.client.config.impl.ClientWorker | longPolling error : 
java.net.ConnectException: no available server, currentServerAddr : http://******:8848
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:190)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:68)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:441)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:408)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:596)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

```
spring-boot:  2.3.8.RELEASE
spring-cloud: Hoxton.SR9
spring-cloud-alibaba: 2.2.4.RELEASE
```

**nacos配置中心在远程服务器上，本地电脑连接，电脑锁屏后打开就这样了。好像也没有重连！**

**Comment by Lee27149** [comment]
升级到 **2.2.5.RC1** 就没有这个问题
