### ISSUE TITLE
Dubbo2.6.5版本集成Nacos作为注册中心服务启动时报错

### ISSUE THREAD

**Issue by TulleyT** [alibaba/nacos#483]
provider启动方式为 com.alibaba.dubbo.container.Main.main(new String[] { "spring" }) main函数
<dubbo:application name="fs-provider" logger="slf4j"/> spring配置文件指明了日志输出方式为slf4j
maven依赖中添加了如下依赖
<dependency>
			<groupId>log4j</groupId>
			<artifactId>log4j</artifactId>
			<version>1.2.16</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.25</version>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.25</version>
		</dependency>
provider启动时nacos报错：
Tue Dec 18 13:32:19 CST 2018 sun.misc.Launcher$AppClassLoader@2a139a55 JM.Log:ERROR Failed to get Slf4jLogger
java.lang.IllegalArgumentException: delegate must be logback impl or slf4j-log4j impl
	at com.alibaba.nacos.client.logger.slf4j.Slf4jLogger.<init>(Slf4jLogger.java:69)
	at com.alibaba.nacos.client.logger.slf4j.Slf4jLoggerFactory.getLogger(Slf4jLoggerFactory.java:36)
	at com.alibaba.nacos.client.logger.LoggerFactory.getLogger(LoggerFactory.java:77)
	at com.alibaba.nacos.client.naming.utils.LogUtils.<clinit>(LogUtils.java:44)
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:89)
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:109)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:43)
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:74)
	at com.alibaba.dubbo.registry.nacos.NacosRegistryFactory.buildNamingService(NacosRegistryFactory.java:58)
	at com.alibaba.dubbo.registry.nacos.NacosRegistryFactory.createRegistry(NacosRegistryFactory.java:51)
	at com.alibaba.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:96)
	at com.alibaba.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:203)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:137)
	at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:60)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:98)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:55)
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:513)
	at com.alibaba.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:358)
	at com.alibaba.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:317)
	at com.alibaba.dubbo.config.ServiceConfig.export(ServiceConfig.java:216)
	at com.alibaba.dubbo.config.spring.ServiceBean.export(ServiceBean.java:291)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:131)
	at com.alibaba.dubbo.config.spring.ServiceBean.onApplicationEvent(ServiceBean.java:53)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:138)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:383)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:337)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:882)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:545)
	at com.alibaba.dubbo.container.spring.SpringContainer.start(SpringContainer.java:50)
	at com.alibaba.dubbo.container.Main.main(Main.java:86)
	at com.sinosoft.ehosp.test.BootMain.main(BootMain.java:6)

**Comment by TulleyT** [comment]
研究了一下异常抛出的位置，抛出该异常是因为在SLF4JLOG4J_CLASSNAME.equals(delegate.getClass().getName())这个判断为false
其中SLF4JLOG4J_CLASSNAME这个常量的值为"org.apache.logging.slf4j.Log4jLogger"
但是实际上使用slf4j+log4j的组合最后delegate.getClass().getName()为“org.slf4j.impl.Log4jLoggerAdapter”
而"org.apache.logging.slf4j.Log4jLogger"是slf4j+log4j2的桥接包中的路径，所以当项目日志框架为slf4j+log4j的时候会抛出异常

**Comment by TulleyT** [comment]
而在com.alibaba.nacos.client.logger.LoggerFactory中的注释中说支持slf4j + slf4j-log4j12 + log4j，那很明显是不是在com.alibaba.nacos.client.logger.slf4j.Slf4jLogger的构造方法中的判断逻辑少了对于这个组合的判断？

**Comment by sqdf1990** [comment]
我也遇到了这个问题，log4j里面配置了好多东西，不想升级，还不知道怎么办

**Comment by wuhulala** [comment]
org.slf4j.impl.Log4jLoggerAdapter

**Comment by hzh7272** [comment]
> 我也遇到了这个问题，log4j里面配置了好多东西，不想升级，还不知道怎么办
排除冲突的jar包就可以了
<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.1.1</version>
            <exclusions>
                <exclusion>
                    <artifactId>logback-core</artifactId>
                    <groupId>ch.qos.logback</groupId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by trycome** [comment]
原zookeeper 改nacos 报这个异常，大家解决了吗？org.apache.catalina.loader.StandardClassLoader@11bbdc80
 JM.Log:ERROR Failed to get Slf4jLogger
java.lang.IllegalArgumentException: delegate must be logback impl or slf4j-log4j impl
	at com.alibaba.nacos.client.logger.slf4j.Slf4jLogger.<init>(Slf4jLogger.java:69)
	at com.alibaba.nacos.client.logger.slf4j.Slf4jLoggerFactory.getLogger(Slf4jLoggerFactory.java:36)
	at com.alibaba.nacos.client.logger.LoggerFactory.getLogger(LoggerFactory.java:77)
	at com.alibaba.nacos.client.naming.utils.LogUtils.<clinit>(LogUtils.java:44)
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:89)
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:109)

**Comment by arrowfeng** [comment]
同样的问题，大家解决了吗？

**Comment by Summerslyb** [comment]
Log4J1 兼容升级到 Log4J2可以用`log4j-1.2-api`的Bridge
他这边的Log4J日志实现是会往日志的配置里另外再塞Appender的, 所以只兼容Log4J2
如果不在意它的`NAMING_LOGGER`的话 直接无视就可以了

**Comment by nkorange** [comment]
升级到dubbo 2.7.1 可以解决

**Comment by sunyukun8888** [comment]
> 升级到dubbo 2.7.1 可以解决

升级也未解决  log4j2 也升级了 dubbo 用的 2.7.1 依然报错
og4j:WARN Continuable parsing error 2 and column 30
log4j:WARN ????? "configuration" ???? DOCTYPE ? "null"?
log4j:WARN Continuable parsing error 2 and column 30
log4j:WARN ????: ??????
log4j:WARN The <configuration> element has been deprecated.
log4j:WARN Use the <log4j:configuration> element instead.
log4j:WARN Unrecognized element Properties
log4j:WARN Unrecognized element appenders
log4j:WARN Unrecognized element loggers
log4j:WARN No appenders could be found for logger (org.springframework.web.context.ContextLoader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
Wed Jul 10 08:13:25 CST 2019 ParallelWebappClassLoader
Wed Jul 10 08:13:25 CST 2019 ParallelWebappClassLoader
  context: ROOT
  context: ROOT
  delegate: false
  delegate: false
----------> Parent Classloader:
----------> Parent Classloader:
java.net.URLClassLoader@76a4d6c
 JM.Log:INFO Init JM logger with Slf4jLoggerFactory success, ParallelWebappClassLoader
java.net.URLClassLoader@76a4d6c
  context: ROOT
  delegate: false
 JM.Log:ERROR Failed to get Slf4jLogger
----------> Parent Classloader:
java.net.URLClassLoader@76a4d6c
java.lang.IllegalArgumentException: delegate must be logback impl or slf4j-log4j impl

	at com.alibaba.nacos.client.logger.slf4j.Slf4jLogger.<init>(Slf4jLogger.java:69)
	at com.alibaba.nacos.client.logger.slf4j.Slf4jLoggerFactory.getLogger(Slf4jLoggerFactory.java:36)
	at com.alibaba.nacos.client.logger.LoggerFactory.getLogger(LoggerFactory.java:77)
	at com.alibaba.nacos.client.naming.utils.LogUtils.<clinit>(LogUtils.java:44)
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:90)
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:110)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:45)
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:74)
	at com.alibaba.dubbo.registry.nacos.NacosRegistryFactory.buildNamingService(NacosRegistryFactory.java:59)
	at com.alibaba.dubbo.registry.nacos.NacosRegistryFactory.createRegistry(NacosRegistryFactory.java:52)
	at com.alibaba.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:96)
	at com.alibaba.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
	at com.alibaba.dubbo.registry.integration.RegistryProtocol.refer(RegistryProtocol.java:276)
	at com.alibaba.dubbo.qos.protocol.QosProtocolWrapper.refer(QosProtocolWrapper.java:69)
	at com.alibaba.dubbo.rpc.protocol.ProtocolListenerWrapper.refer(ProtocolListenerWrapper.java:65)
	at com.alibaba.dubbo.rpc.protocol.ProtocolFilterWrapper.refer(ProtocolFilterWrapper.java:106)
	at com.alibaba.dubbo.rpc.Protocol$Adaptive.refer(Protocol$Adaptive.java)
	at com.alibaba.dubbo.config.ReferenceConfig.createProxy(ReferenceConfig.java:396)
	at com.alibaba.dubbo.config.ReferenceConfig.init(ReferenceConfig.java:335)
	at com.alibaba.dubbo.config.ReferenceConfig.get(ReferenceConfig.java:164)
	at com.alibaba.dubbo.config.spring.ReferenceBean.getObject(ReferenceBean.java:67)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.doGetObjectFromFactoryBean(FactoryBeanRegistrySupport.java:168)
	at org.springframework.beans.factory.support.FactoryBeanRegistrySupport.getObjectFromFactoryBean(FactoryBeanRegistrySupport.java:103)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getObjectForBeanInstance(AbstractBeanFactory.java:1514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:250)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.findAutowireCandidates(DefaultListableBeanFactory.java:1127)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1051)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:949)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:527)
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:87)
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:302)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:229)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:298)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:193)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:762)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:757)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:480)
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:403)
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
	at com.effect.saweb.listener.StartupListener.contextInitialized(StartupListener.java:15)
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4745)
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207)
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
	at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:752)
	at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:728)
	at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:734)
	at org.apache.catalina.startup.HostConfig.manageApp(HostConfig.java:1736)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:482)
	at org.apache.catalina.mbeans.MBeanFactory.createStandardContext(MBeanFactory.java:431)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.tomcat.util.modeler.BaseModelMBean.invoke(BaseModelMBean.java:300)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:361)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:568)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:826)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:683)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:682)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Wed Jul 10 08:13:25 CST 2019 ParallelWebappClassLoader

**Comment by sunyukun8888** [comment]
> 升级到dubbo 2.7.1 可以解决

经过测试是可以的具体POM详见

<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-alibaba</artifactId>
                <version>0.9.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>0.9.0.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>


        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <artifactId>spring-boot-starter-logging</artifactId>
                    <groupId>org.springframework.boot</groupId>
                </exclusion>
            </exclusions>
        </dependency>

        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-spring-boot-starter</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.apache.dubbo</groupId>
                    <artifactId>dubbo</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo</artifactId>
            <exclusions>
                <exclusion>
                    <groupId>org.springframework</groupId>
                    <artifactId>spring</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>javax.servlet</groupId>
                    <artifactId>servlet-api</artifactId>
                </exclusion>
                <exclusion>
                    <groupId>log4j</groupId>
                    <artifactId>log4j</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

        
        <dependency>
            <groupId>org.apache.dubbo</groupId>
            <artifactId>dubbo-registry-nacos</artifactId>
            <version>2.7.1</version>
        </dependency>

        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
        </dependency>
