### ISSUE TITLE
 集群节点状态suspicious，应用端、nacos-server节点一直提示： request: http://xxx.xxxxx:8848/nacos/v1/ns/instance/beat, caused: {} timeout

### ISSUE THREAD

**Issue by niejian** [alibaba/nacos#4830]
**Describe the bug**
注册实例数量在1000左右，nacos-server状态正常。
当注册实例增加到一定量的时候集群节点状态suspicious，应用端提示： request: `http://xxx.xxxxx:8848/nacos/v1/ns/instance/beat, caused: {} timeout`。
nacos-server各个节点也提示这个错误。
后面应用程序注册不进nacos，整个集群不可用。

**Expected behavior**
重启，无法解决
查看文件打开数、http连接数都正常
**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS:  [centos]
 - Version [ nacos-server 1.4.0, nacos-client 1.1.3],[ nacos-server 1.1.3, nacos-client 1.1.3]
 - Module [ naming]
 - SDK [ spring-cloud-alibaba-nacos, dubbo]

**Additional context**
后续`nacos-server.log`一直输出如下堆栈信息：

```java
2021-01-28 22:51:28,786 ERROR Servlet.service() for servlet [dispatcherServlet] in context with path [/nacos] threw exception

java.lang.IllegalStateException: Cannot call sendError() after the response has been committed
        at org.apache.catalina.connector.ResponseFacade.sendError(ResponseFacade.java:456)
        at javax.servlet.http.HttpServletResponseWrapper.sendError(HttpServletResponseWrapper.java:120)
        at com.alibaba.nacos.naming.web.DistroFilter.doFilter(DistroFilter.java:143)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.nacos.naming.web.AuthFilter.doFilter(AuthFilter.java:98)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.nacos.naming.web.TrafficReviseFilter.doFilter(TrafficReviseFilter.java:69)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:92)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:117)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:106)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:490)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:139)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:74)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:668)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:408)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:791)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1417)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
````

**Comment by KomachiSion** [comment]
1.  看下nacos-server是否有FullGC
2. 统计下每台nacos节点的TPS和QPS
3. 提供下nacos节点服务器的配置参数，和JVM参数
4. issue中说1000个实例正常， 那是多少的时候不正常？

**Comment by niejian** [comment]
> 1. 看下nacos-server是否有FullGC
> 2. 统计下每台nacos节点的TPS和QPS
> 3. 提供下nacos节点服务器的配置参数，和JVM参数
> 4. issue中说1000个实例正常， 那是多少的时候不正常？

* gc.log 中未发现有fullgc日志
* 未统计，如果要统计需要怎么做？
* 服务器配置：12C 16G，JVM参数： -Xms8g -Xmx12g -Xmn1g -XX:MetaspaceSize=512m -XX:MaxMetaspaceSize=640m，其他jvm参数默认
* 到了1700左右就开始瘫痪了
**application.properties中的tomcat相关参数需要调整吗，如果需要怎么调**

**Comment by KomachiSion** [comment]
1. gc.log中有CMSGC吗？ 用jstat -gcutil 看下GC情况，从JVM参数来看应该不会是内存问题
2. 服务器有几台？
3. QPS统计你们有服务器监控吗？ 没有的话抓包看下。
4. 可以适当调大tomcat的worker线程数和queueSize。主要是下面3个参数`acceptCount`,`maxConnections`,`maxThreads`
5. 同时看一下服务端的tcp连接，是不是有很多TIME_WAIT的。是的话调整一下服务端的tcp内核参数，让系统快速回收TIME_WAIT的连接并且设置成可复用。

**Comment by niejian** [comment]
> 1. gc.log中有CMSGC吗？ 用jstat -gcutil 看下GC情况，从JVM参数来看应该不会是内存问题
> 2. 服务器有几台？
> 3. QPS统计你们有服务器监控吗？ 没有的话抓包看下。
> 4. 可以适当调大tomcat的worker线程数和queueSize。主要是下面3个参数`acceptCount`,`maxConnections`,`maxThreads`
> 5. 同时看一下服务端的tcp连接，是不是有很多TIME_WAIT的。是的话调整一下服务端的tcp内核参数，让系统快速回收TIME_WAIT的连接并且设置成可复用。

* gc.log中没看到CMSGC
凌晨搞崩了就全部回退到zk注册中心了，这些情况暂时也复现不了了。只能先等压测环境那边搭好

**Comment by KomachiSion** [comment]
Any response and process?

**Comment by niejian** [comment]
> Any response and process?
还是一样

**Comment by niejian** [comment]
> Any response and process?


还是一样，各种调优都试了，没用

**Comment by KomachiSion** [comment]
根据我自己的测试 8C 16G 单台nacos 扛住6000实例应该是没有问题的。

jvm：
```
-server -Xms10g -Xmx10g -Xmn4g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m
```

不清楚你是dubbo的实例还是spring cloud的实例

**Comment by niejian** [comment]
> 根据我自己的测试 8C 16G 单台nacos 扛住6000实例应该是没有问题的。
> 
> jvm：
> 
> ```
> -server -Xms10g -Xmx10g -Xmn4g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m
> ```
> 
> 不清楚你是dubbo的实例还是spring cloud的实例

dubbo实例

**Comment by KomachiSion** [comment]
那你说的1700实例是nacos意义上的实例，还是有这么多台机器实例？

如果是机器实例， 那实际上的nacos实例数应该是 接口数*机器数。

**Comment by niejian** [comment]
> 那你说的1700实例是nacos意义上的实例，还是有这么多台机器实例？
> 
> 如果是机器实例， 那实际上的nacos实例数应该是 接口数*机器数。

可以理解 接口数*机器数 = 1700

**Comment by KomachiSion** [comment]
那不应该扛不住， 我们这里跑1w+接口实例的dubbo服务也没有出现这个问题。 我压测单机抗6000接口实例也没有压力。

得具体看环境信息来排查了。

**Comment by niejian** [comment]
我现在也在测试这一块的问题，单纯的部署服务提供者没问题。

通过dubbo-montor查看所有的消费者实例数有 9292个，我觉得是不是在项目部署的过程中，服务提供者ip频繁发生变化，nacos-server不断的推送消息给消费者而导致问题发生的

**Comment by KomachiSion** [comment]
我也测试过频繁变更场景， 3台机器注册2w实例 之后 随机选10%～20%注销再注册， 每个接口5个消费者。 也没有发生该问题。
当然可能和订阅量有关系，如果订阅量不是5而是几十上百，或许会有你说的这个问题。

所以还是回到最开始的问题，
```
2. 统计下每台nacos节点的TPS和QPS
```

**Comment by niejian** [comment]
> 我也测试过频繁变更场景， 3台机器注册2w实例 之后 随机选10%～20%注销再注册， 每个接口5个消费者。 也没有发生该问题。
> 当然可能和订阅量有关系，如果订阅量不是5而是几十上百，或许会有你说的这个问题。
> 
> 所以还是回到最开始的问题，
> 
> ```
> 2. 统计下每台nacos节点的TPS和QPS
> ```

通过grafana统计看到。
![](https://gitee.com/justCode4Fun/pic/raw/master/img/20210308143731.png)
管理界面看到，有两个节点在`UP`和`DOWN`两种状态来回变化。

**Comment by KomachiSion** [comment]
qps 2218 如果是持续的，那其实很高了。

粗略估计 订阅者非常多 有2w个实例以上（单台节点）

**Comment by niejian** [comment]
> qps 2218 如果是持续的，那其实很高了。
> 
> 粗略估计 订阅者非常多 有2w个实例以上（单台节点）
是的，单台服务上有订阅者在2w以上。
在真实的测试环境中，发现集成nacos注册中心的某些关键服务，在运行一段时间后，端口资源被消耗干净，通过命令`netstat -anp`统计全是连接nacos的tcp连接

**Comment by KomachiSion** [comment]
这种场景建议试用一下2.0版本，1.X通过HTTP+UDP的方式，在如此多订阅者的情况下可能会出现较大的压力，可能需要横行扩容。

**Comment by KomachiSion** [comment]
tcp连接的问题，可以看下是否都是TimeWait的状态，如果是的话可以通过修改tcp的os参数来快速释放和复用

**Comment by niejian** [comment]
> tcp连接的问题，可以看下是否都是TimeWait的状态，如果是的话可以通过修改tcp的os参数来快速释放和复用

已经跳了time_wait的相关参数了。就等2.0版本发布了

**Comment by KomachiSion** [comment]
可以先试用一下2.0-BETA版本，在测试或者预发环境。帮我们更早发的发现问题。

这个issue先关闭了
