### ISSUE TITLE
nacos1.4集群服务注册server is DOWN now, please try again later!

### ISSUE THREAD

**Issue by planwk** [alibaba/nacos#4888]
阿里云上部署，nacos1.4版本集群，cluster.conf使用内网地址
172.17.11.140:8848
172.17.11.141:8848
172.17.11.142:8848
startup.sh也增加了JAVA_OPT="${JAVA_OPT} -Dnacos.server.ip=172.17.1x.1xx，启动后3节点状态都是up，
节点元数据
节点1
`{
    "adWeight": "0",
    "lastRefreshTime": 1612510712393,
    "naming": {
        "voteFor": "172.17.11.140:8848",
        "ip": "172.17.11.140:8848",
        "heartbeatDueMs": 5000,
        "term": 151,
        "leaderDueMs": 16977,
        "state": "LEADER"
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}
`
`{
    "adWeight": "0",
    "lastRefreshTime": 1612511688674,
    "naming": {
        "voteFor": "172.17.11.141:8848",
        "ip": "172.17.11.141:8848",
        "heartbeatDueMs": 4000,
        "term": 64,
        "leaderDueMs": 13872,
        "state": "CANDIDATE"
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}
`
`{
    "adWeight": "0",
    "lastRefreshTime": 1612511687702,
    "naming": {
        "ip": "172.17.11.142:8848",
        "heartbeatDueMs": 2148,
        "term": -1,
        "leaderDueMs": 6105,
        "state": "FOLLOWER"
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}`
节点2
`{
    "adWeight": "0",
    "lastRefreshTime": 1612511712678,
    "naming": {
        "voteFor": "172.17.11.140:8848",
        "ip": "172.17.11.140:8848",
        "heartbeatDueMs": 5000,
        "term": 62,
        "leaderDueMs": 18073,
        "state": "LEADER"
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}`
`{
    "adWeight": "0",
    "lastRefreshTime": 1612511701705,
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}`
`{
    "adWeight": "0",
    "raftPort": "7848",
    "site": "unknow",
    "weight": "1"
}`
节点3
`{
    "adWeight": "0",
    "lastRefreshTime": 1612511712678,
    "naming": {
        "voteFor": "172.17.11.140:8848",
        "ip": "172.17.11.140:8848",
        "heartbeatDueMs": 5000,
        "term": 62,
        "leaderDueMs": 18073,
        "state": "LEADER"
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}`
`{
    "adWeight": "0",
    "lastRefreshTime": 1612509156712,
    "naming": {
        "voteFor": "172.17.11.141:8848",
        "ip": "172.17.11.141:8848",
        "heartbeatDueMs": 5000,
        "term": 65,
        "leaderDueMs": 18133,
        "state": "LEADER"
    },
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}`
`{
    "adWeight": "0",
    "lastRefreshTime": 1612511713706,
    "raftPort": "7848",
    "site": "unknow",
    "version": "1.4.0",
    "weight": "1"
}`
但是服务注册一直报如下报错，但是能注册到其中一个服务节点，其它两个服务都看不到
ERROR com.alibaba.nacos.client.naming - [NA] failed to request
com.alibaba.nacos.api.exception.NacosException: server is DOWN now, please try again later!
同时查看nacos.log日志，出现如下错误
`java.lang.IllegalStateException: old raft protocol already stop
	at com.alibaba.nacos.naming.controllers.RaftController.vote(RaftController.java:97)
	at sun.reflect.GeneratedMethodAccessor171.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
`

**Comment by planwk** [comment]
服务器通过hostname -i得到的都是正确的内网ip地址

**Comment by planwk** [comment]
其中一台服务查看naming-raft.log
2021-02-05 18:28:04,438 ERROR NACOS-RAFT vote failed: 500, url: http://172.16.11.142:8848/nacos/v1/ns/raft/vote

2021-02-05 18:28:04,438 ERROR NACOS-RAFT vote failed: 500, url: http://172.16.11.140:8848/nacos/v1/ns/raft/vote

2021-02-05 18:28:15,000 WARN [IS LEADER] no leader is available now!

^C
[root@iZbp146lua66tfu1qrvr6qZ logs]# curl http://172.16.11.142:8848/nacos/v1/ns/raft/vote
server is DOWN now, please try again later![root@iZbp146lua66tfu1qrvr6qZ logs]#

**Comment by KomachiSion** [comment]
麻烦提供下protocol-raft 和alipay-jraft的日志。

**Comment by xinkuang** [comment]
2021-02-08 08:37:52.534 ERROR 7 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : [NA] failed to request
com.alibaba.nacos.api.exception.NacosException: server is DOWN now, please try again later!
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615) [nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) [nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) [nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:433) [nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167) [nacos-client-1.4.1.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_275]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_275]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_275]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_275]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_275]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_275]

**Comment by planwk** [comment]
> 麻烦提供下protocol-raft和alipay-jraft的日志。
protocol-raft
`java.lang.IllegalArgumentException: Blank leader
	at com.alipay.sofa.jraft.util.Requires.requireTrue(Requires.java:85)
	at com.alipay.sofa.jraft.RouteTable.updateLeader(RouteTable.java:181)
	at com.alipay.sofa.jraft.RouteTable.refreshLeader(RouteTable.java:264)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.refreshRouteTable(JRaftServer.java:501)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.lambda$createMultiRaftGroup$1(JRaftServer.java:276)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-02-09 10:00:33,173 ERROR Fail to refresh raft metadata info for group : naming_persistent_service, error is : {}`

alipay-jraft
`2021-02-09 10:03:13,455 WARN Node <naming_persistent_service/172.17.11.140:7848> channel init failed, address=172.17.11.140:7848.

2021-02-09 10:03:14,216 ERROR Fail to connect 172.17.11.140:7848, remoting exception: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception.
`

**Comment by planwk** [comment]
为啥会出现7848端口啊？我没有找到哪里定义的呢

**Comment by Jean711** [comment]
刚刚遇到同样的问题
通过查看protocol-raft 日志发现异常“ERROR Fail to refresh leader for group : naming_persistent_service, status is : Status[UNKNOWN<-1>: Fail to init channel to 192.168.12.228:7848, Unknown leader”
这里7848的端口访问有点可疑，于是关闭防火墙测试，异常消失，不知道是否是这里的问题。

**Comment by kwz1993** [comment]
同样的问题，

**Comment by wolfewf** [comment]
坑

**Comment by KeithTt** [comment]
Same problem!
