### ISSUE TITLE
动态刷新数据库(Mysql)连接配置时(password),存在错误如下 ( 版本 : 2.0.0-BETA (Feb 5th, 2021) )

### ISSUE THREAD

**Issue by bravelionet** [alibaba/nacos#4897]
**测试动态刷新 DruidDataSource 资源时发生以下错误**

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@71c1b95d rejected from java.util.concurrent.ScheduledThreadPoolExecutor@3ddb8782[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**配置类如下 :** 
  @Configuration
  public class DataSourceProperties {
  
      @Bean
      @ConfigurationProperties(prefix="spring.datasource")
      @RefreshScope
      public DataSource dataSource(){
  
          return new DruidDataSource();
      }
  }

**Comment by KomachiSion** [comment]
looks like duplicate with #4748
