### ISSUE TITLE
config start NullPointerException 

### ISSUE THREAD

**Issue by HPxianliru** [alibaba/nacos#4905]
**Describe the bug**
startup project logger error，not set nacos.config.data-ids value
**Expected behavior**
not set data-ids successful startup without loading configuration
the Process Is Now Blocked
**Acutally behavior**
logger error NullPointerException

**How to Reproduce**
1. not set application.yml nacos.config.data-ids value
2. Startup Project
3. logger error java.lang.NullPointerException: null
4. java.lang.NullPointerException: null
	at org.springframework.core.env.MutablePropertySources.assertLegalRelativeAddition(MutablePropertySources.java:176)
	at org.springframework.core.env.MutablePropertySources.addAfter(MutablePropertySources.java:125)
	at com.alibaba.boot.nacos.config.util.NacosConfigLoader.loadConfig(NacosConfigLoader.java:76)
	at com.alibaba.boot.nacos.config.autoconfigure.NacosConfigEnvironmentProcessor.loadConfig(NacosConfigEnvironmentProcessor.java:94)

**Desktop (please complete the following information):**
 - OS: windows
 - Version nacos-server 1.3.0, nacos-client 1.2.0
 - Module naming/config
  - nacos:
      config:
        server-addr: ${nacos.address:10.247.121.124:8848}
        bootstrap:
          enable: true
          log-enable: true
        remote-first: true
        type: yaml
        auto-refresh: false
        data-ids:
 - SDK groupId: com.alibaba.boot artifactId: nacos-config-spring-boot-starter  version 0.2.7 

**Additional context**

**Comment by HPxianliru** [comment]
I'm  trying to solve this problem

**Comment by HPxianliru** [comment]
@i will solve it@

**Comment by HPxianliru** [comment]
Ask the administrator to close this question, this question is another project question

groupId: com.alibaba.boot artifactId: nacos-config-spring-boot-starter version 0.2.7
