### ISSUE TITLE
SpringBoot 以 @ImportResource(locations = { "classpath: nacos.xml"}) 方式，出现 【APPLICATION FAILED TO START】

### ISSUE THREAD

**Issue by Chunghwa-2018** [alibaba/nacos#4953]
**Describe the bug**
SpringBoot 以 @ImportResource(locations = { "classpath: nacos.xml"}) 方式，出现 【APPLICATION FAILED TO START】

**Expected behavior**
SpringBoot 使用 @ImportResource(locations = { "classpath: nacos.xml"}) 方式，正常启动，并从 nacos server 拉取配置

**Acutally behavior**
SpringBoot 中使用注解配置，启动正常，拉去配置正常
@EnableNacosConfig(globalProperties = @NacosProperties(serverAddr = "127.0.0.1:8848"))
@NacosPropertySources({
      @NacosPropertySource(dataId = "hx-order-mysql-server", groupId = "dev", autoRefreshed = true)
})
但仿照 nacos-spring-example/nacos-spring-config-datasource-example 采用 nacos.xml  方式
以 @ImportResource(locations = { "classpath: nacos.xml"})  导入，引发 APPLICATION FAILED TO START】 问题

**How to Reproduce**
1. 在pom.xml 引入 nacos-spring-context
<dependency>
      <groupId>com.alibaba.nacos</groupId>
      <artifactId>nacos-spring-context</artifactId>
      <version>0.2.2-RC1</version>
</dependency>
2. 在 src/man/resources/ 下 创建 nacos.xml
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:nacos="http://nacos.io/schema/nacos"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd
       http://nacos.io/schema/nacos
       http://nacos.io/schema/nacos.xsd">
    <nacos:global-properties server-addr="127.0.0.1:8848" />
    <nacos:property-source data-id="mysql-server" group-id="dev" auto-refreshed="true" />
</beans>

（关于mybatis 配置省略， 使用 nacos 可正常从 nacos 获取配置）

3. 在 DemoApplition 添加 @ImportResource(locations = { "classpath: nacos.xml"})  
4. 启动
5. 错误如下
***************************
APPLICATION FAILED TO START
***************************

Description:

An attempt was made to call a method that does not exist. The attempt was made from the following location:

    com.alibaba.nacos.spring.context.config.xml.GlobalNacosPropertiesBeanDefinitionParser.parse(GlobalNacosPropertiesBeanDefinitionParser.java:51)

The following method did not exist:

    org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.getEnvironment()Lorg/springframework/core/env/Environment;

The method's class, org.springframework.beans.factory.xml.BeanDefinitionParserDelegate, is available from the following locations:

    jar:file:/Users/zhaohongliang/.m2/repository/org/springframework/spring-beans/5.1.9.RELEASE/spring-beans-5.1.9.RELEASE.jar!/org/springframework/beans/factory/xml/BeanDefinitionParserDelegate.class

It was loaded from the following location:

    file:/Users/zhaohongliang/.m2/repository/org/springframework/spring-beans/5.1.9.RELEASE/spring-beans-5.1.9.RELEASE.jar

Action:

Correct the classpath of your application so that it contains a single, compatible version of org.springframework.beans.factory.xml.BeanDefinitionParserDelegate

**Desktop (please complete the following information):**
 - OS: [Mac OS]
 - Version [ nacos 1.4.1]
 - Module [ 订单模块 ]
 - SDK [ nacos-spring-context  ]

**Additional context**

**Comment by JackSun-Developer** [comment]
>APPLICATION FAILED TO START
具体的堆栈报错信息可以提供一下么？

**Comment by Chunghwa-2018** [comment]
@JackSun-Developer ， nacos.xml 配置是拷贝过来的，改动如下

<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:nacos="http://nacos.io/schema/nacos"
       xsi:schemaLocation="http://www.springframework.org/schema/beans
       http://www.springframework.org/schema/beans/spring-beans.xsd
       http://nacos.io/schema/nacos
       http://nacos.io/schema/nacos.xsd">

    <nacos:global-properties server-addr="127.0.0.1:8848" />

    <nacos:property-source data-id="hx-order-mysql-server" group-id="dev" auto-refreshed="true" />
    
</beans>

**Comment by JackSun-Developer** [comment]
> @JackSun-Developer ， nacos.xml 配置是拷贝过来的，改动如下
> 
> ```
> <nacos:global-properties server-addr="127.0.0.1:8848" />
> 
> <nacos:property-source data-id="hx-order-mysql-server" group-id="dev" auto-refreshed="true" />
> ```

报错的堆栈信息呢？可以提供下么

**Comment by Chunghwa-2018** [comment]
@JackSun-Developer 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2021-02-25 14:33:00.539 [main] ERROR c.h.o.u.ProjectBootUnifiedFailureAnalyzer-25 遇到运行时异常
org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [nacos/nacos.xml]; nested exception is java.lang.NoSuchMethodError: org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.getEnvironment()Lorg/springframework/core/env/Environment;
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:419)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:336)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:304)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:224)
	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:195)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.lambda$loadBeanDefinitionsFromImportedResources$0(ConfigurationClassBeanDefinitionReader.java:358)
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsFromImportedResources(ConfigurationClassBeanDefinitionReader.java:325)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitionsForConfigurationClass(ConfigurationClassBeanDefinitionReader.java:144)
	at org.springframework.context.annotation.ConfigurationClassBeanDefinitionReader.loadBeanDefinitions(ConfigurationClassBeanDefinitionReader.java:117)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.processConfigBeanDefinitions(ConfigurationClassPostProcessor.java:327)
	at org.springframework.context.annotation.ConfigurationClassPostProcessor.postProcessBeanDefinitionRegistry(ConfigurationClassPostProcessor.java:232)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanDefinitionRegistryPostProcessors(PostProcessorRegistrationDelegate.java:275)
	at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:95)
	at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:705)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:531)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at cn.hx.order.application.OrderServiceApplication.main(OrderServiceApplication.java:39)
Caused by: java.lang.NoSuchMethodError: org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.getEnvironment()Lorg/springframework/core/env/Environment;
	at com.alibaba.nacos.spring.context.config.xml.GlobalNacosPropertiesBeanDefinitionParser.parse(GlobalNacosPropertiesBeanDefinitionParser.java:51)
	at org.springframework.beans.factory.xml.NamespaceHandlerSupport.parse(NamespaceHandlerSupport.java:74)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1391)
	at org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.parseCustomElement(BeanDefinitionParserDelegate.java:1371)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.parseBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:179)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.doRegisterBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:149)
	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:96)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:513)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:393)
	... 23 common frames omitted
2021-02-25 14:33:00.541 [main] ERROR o.s.b.d.LoggingFailureAnalysisReporter-40

**Comment by KomachiSion** [comment]
```
path resource [nacos/nacos.xml]; nested exception is java.lang.NoSuchMethodError: org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.getEnvironment()Lorg/springframework/core/env/Environment;
```

spring版本依赖包冲突，自行排查解决下把。

**Comment by Chunghwa-2018** [comment]
> ```
> path resource [nacos/nacos.xml]; nested exception is java.lang.NoSuchMethodError: org.springframework.beans.factory.xml.BeanDefinitionParserDelegate.getEnvironment()Lorg/springframework/core/env/Environment;
> ```
> 
> spring版本依赖包冲突，自行排查解决下把。

@KomachiSion 这是启动时运行异常
spring-boot-starter-parent 版本是2.1.8.RELEASE， 包含 spring-beans:5.1.9.RELEASE ，在spring-beans:5.1.9.RELEASE，没有找到对应的方法导致的，nacos-spring-context 的版本使用1.0.0 也不支持 xml 方式，对于 nacos-spring-context 是不是做出一个 版本说明啊

**Comment by Chunghwa-2018** [comment]
@KomachiSion 如果工程采用spring boot 2.0以后的版本， spring 的基础版本是5.0以上， spring boot 支持 javaconfig 注解方式配置，也支持 xml 方式配置， 但是 nacos-spring-context 和 nacos-config-spring-boot-starter 对于 spring boot 2.0 不支持 xml方式配置。目前来看工程里其他 spring 的 xml 配置都是没问题的，而报错信息提示也是 nacos.xml 找不到 spring 的方法报出的运行异常。如果一定要使用 xml 方式配置， 总不至于把 spring boot 降低到2.0一下，甚至替换为 spring 4.0 mvc 模式吧。对于 nacos 是否支持 spring boot 以 @ImportResource 方式引入，还是重新确定一下吧

**Comment by KomachiSion** [comment]
nacos-spring-boot有适配spring-boot2.0的版本，可能是你依赖的nacos-spring-boot的版本不对，到nacos-spring-boot的wiki下面看一下对应的版本吧
