### ISSUE TITLE
build ClientInfo with empty user-agent throws java.lang.StringIndexOutOfBoundsException

### ISSUE THREAD

**Issue by pixystone** [alibaba/nacos#4987]
**Describe the bug**

Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1919)
	at com.alibaba.nacos.naming.push.v1.ClientInfo.<init>(ClientInfo.java:41)
	at com.alibaba.nacos.naming.core.InstanceOperatorServiceImpl.listInstance(InstanceOperatorServiceImpl.java:146)

**Expected behavior**

return a ClientInfo with an unknown version by default

**Acutally behavior**

throws an exception

**How to Reproduce**

```
new ClientInfo("")
```

**Desktop (please complete the following information):**
 - OS: [osx]
 - Version [nacos-server 2.0.0-BETA]
 - Module [naming]
 - SDK [original]

**Additional context**

**Comment by pixystone** [comment]
`ClientType.getType()` the same
