### ISSUE TITLE
应用注册报400，receive invalid redirect request from peer 

### ISSUE THREAD

**Issue by lualeslie** [alibaba/nacos#4992]
nacos：1.4.1
mode：3AZ集群模式
cluster.conf：3个实例外部路由+一个内部路由（启动自带，不知原因）
报错原因：配置不同的spring.application.name，有些名字可以正常注册，有些名字又会报这个400错，但是查看源码发现没有严格的命名校验规范
报错内容：
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/api//nacos/v1/ns/instance after all servers([http://za23-nacos-cluster-headless-single.xxxx.xxxx.cn:80]) tried: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Wed Mar 03 02:19:10 UTC 2021</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 172.30.18.1</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:496) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:401) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:397) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:212) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:207) ~[nacos-client-1.2.1.jar:na]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:64) ~[spring-cloud-starter-alibaba-nacos-discovery-2.1.2.RELEASE.jar:2.1.2.RELEASE]

**Comment by JackSun-Developer** [comment]
cluster.conf里面的所有服务器的IP地址，都用
'''
curl -X POST 'http://IP:8848/nacos/v1/ns/instance?port=8848&healthy=true&ip=11.11.11.11&weight=1.0&serviceName=nacos.test.3&encoding=GBK&namespaceId=n1'
'''
测试一下,确保cluster.conf里的各个服务器都能正常提供服务

**Comment by lualeslie** [comment]
cluster.conf里面使用的是.com域名形式的地址，并不是使用的IP地址，且配置了PREFER_HOST_MODE=hostname

**Comment by JackSun-Developer** [comment]
> cluster.conf里面使用的是.com域名形式的地址，并不是使用的IP地址，且配置了PREFER_HOST_MODE=hostname

域名和IP一样的道理，那就把IP换成域名访问一下。我的意思是让你先通过openAPI这种方式看看集群里的机器是否都正常工作且网络畅通

**Comment by lualeslie** [comment]
postman访问cluster.conf里面的地址，返回400报错，
{
    "timestamp": "2021-03-03T06:58:16.635+0000",
    "status": 400,
    "error": "Bad Request",
    "message": "receive invalid redirect request from peer 172.30.8.1",
    "path": "/nacos/v1/ns/instance"
}

**Comment by JackSun-Developer** [comment]
> postman访问cluster.conf里面的地址，返回400报错，
> {
> "timestamp": "2021-03-03T06:58:16.635+0000",
> "status": 400,
> "error": "Bad Request",
> "message": "receive invalid redirect request from peer 172.30.8.1",
> "path": "/nacos/v1/ns/instance"
> }

所以你的nacos server本身就没有启动成功

**Comment by lualeslie** [comment]
172.30.8.1这并不是使用的机器的真实IP地址，nacos server应该是启动成功了，可以打开console页面，另外换个spring.application.name名字可能可以成功注册上去。另外我们是部署的3AZ（3个不同的集群，实例相互之间用.com域名进行通信，每个集群一个实例）。

**Comment by lualeslie** [comment]
不知道你们是否有试过这种部署方式，另外发现使用http的端口号为80，然后计算出来的raft协议端口号为-920（80-1000），我们通过http://xxx.com:80域名方式部署nacos集群是否可行。

**Comment by lualeslie** [comment]
> > postman访问cluster.conf里面的地址，返回400报错，
> > {
> > "timestamp": "2021-03-03T06:58:16.635+0000",
> > "status": 400,
> > "error": "Bad Request",
> > "message": "receive invalid redirect request from peer 172.30.8.1",
> > "path": "/nacos/v1/ns/instance"
> > }
> 
> 所以你的nacos server本身就没有启动成功，你应该在172.30.8.1机器上看一下nacos启动日志，排查一下问题。启动失败问题可以去查一下其他的ISSUE

nacos是启动成功了，但是感觉cluster.conf配置域名方式和IP方式是否有不同之处，换一种配置方式可能可以成功。

**Comment by KomachiSion** [comment]
`cluster.conf：3个实例外部路由+一个内部路由（启动自带，不知原因）`没看懂

是说你写了3个ip/域名，然后启动之后多了一个？

如果是这个问题，说明你填写的ip/域名和nacos读取到的本机ip不同（常见于多网卡）

可以在启动的时候加-Dnacos.server.ip=(ip/domain)来指定本机IP/域名
或者使用application.properties中`nacos.inetutils.ip-address=` 指定

docker镜像可以通过环境变量`NACOS_SERVER_IP`指定。

**Comment by lualeslie** [comment]
> `cluster.conf：3个实例外部路由+一个内部路由（启动自带，不知原因）`没看懂
> 
> 是说你写了3个ip/域名，然后启动之后多了一个？
> 
> 如果是这个问题，说明你填写的ip/域名和nacos读取到的本机ip不同（常见于多网卡）
> 
> 可以在启动的时候加-Dnacos.server.ip=(ip/domain)来指定本机IP/域名
> 或者使用application.properties中`nacos.inetutils.ip-address=` 指定
> 
> docker镜像可以通过环境变量`NACOS_SERVER_IP`指定。

是的，自动多添加了一个。
另外我尝试在docker镜像里面添加`NACOS_SERVER_IP`，加入的是域名，如http://xxx.com:80，但是启动的时候报错，报如下错：
```
2021-03-04 15:44:38 Caused by: java.lang.RuntimeException: nacos address http://xxx.com:80 is not ip
2021-03-04 15:44:38 	at com.alibaba.nacos.sys.utils.InetUtils$1.run(InetUtils.java:87)
2021-03-04 15:44:38 	at com.alibaba.nacos.sys.utils.InetUtils.<clinit>(InetUtils.java:133)
```

**Comment by lualeslie** [comment]
另外想问一下如果cluster.conf使用域名，`nacos.inetutils.prefer-hostname-over-ip=true`这个需要配置吗？和docker的PREFER_HOST_MODE=hostname是否是一样的效果？

**Comment by lualeslie** [comment]
官方提供的制作nacos镜像，推荐使用的是nacos-k8s还是nacos-docker？

**Comment by KomachiSion** [comment]
> 另外想问一下如果cluster.conf使用域名，`nacos.inetutils.prefer-hostname-over-ip=true`这个需要配置吗？和docker的PREFER_HOST_MODE=hostname是否是一样的效果？

是的 如果用域名 需要设置true，应该是一样的效果。

**Comment by KomachiSion** [comment]
> 官方提供的制作nacos镜像，推荐使用的是nacos-k8s还是nacos-docker？

都一样。 k8s也是继续nacos-docker，只是加了一些k8s的设置。

**Comment by lualeslie** [comment]
> > 官方提供的制作nacos镜像，推荐使用的是nacos-k8s还是nacos-docker？
> 
> 都一样。 k8s也是继续nacos-docker，只是加了一些k8s的设置。

您好，可以加钉钉详聊吗？我的钉钉号tpv_h28fz6yyj

**Comment by KomachiSion** [comment]
如果issue所提问题已解决，请关闭issue。如果还有其他不同问题，请提新的issue询问。

**Comment by KomachiSion** [comment]
No more response from author, we will close issue first, if has more problem, please submit new issue.

**Comment by bigfacewo** [comment]
遇到同样的问题，我通过
```
curl -X POST 'http://IP:8848/nacos/v1/ns/instance?port=8848&healthy=true&ip=11.11.11.11&weight=1.0&serviceName=nacos.test.3&encoding=GBK&namespaceId=n1'
```
测试三个nacos节点都返回ok
但是我的服务报错：
```
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([nacos-headless.default.svc.cluster.local:8848]) tried: ErrCode:400, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Sep 07 14:36:42 CST 2021</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 10.233.105.77</div></body></html>
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:556)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493)
        at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:246)
        at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:212)
        at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74)
        ... 35 common frames omitted

```

**Comment by admlke** [comment]
> 遇到同样的问题，我通过
> 
> ```
> curl -X POST 'http://IP:8848/nacos/v1/ns/instance?port=8848&healthy=true&ip=11.11.11.11&weight=1.0&serviceName=nacos.test.3&encoding=GBK&namespaceId=n1'
> ```
> 
> 测试三个nacos节点都返回ok 但是我的服务报错：
> 
> ```
> Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([nacos-headless.default.svc.cluster.local:8848]) tried: ErrCode:400, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Sep 07 14:36:42 CST 2021</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 10.233.105.77</div></body></html>
>         at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:556)
>         at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
>         at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493)
>         at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:246)
>         at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:212)
>         at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74)
>         ... 35 common frames omitted
> ```

这个问题有解决吗？我也是集群成功，但项目里报错...

**Comment by jiangtianyou** [comment]
> 

你的解决了吗?

**Comment by zhaoweilong007** [comment]
@jiangtianyou 我指定了NACOS_SERVER_IP为本地ip后不会出现400了，正常了

**Comment by spairy** [comment]
management.endpoints.web.exposure.inculde=* 这一行会引起400 receive invalid redirect request from peer 的报错，在application.properties中把这一行注释掉就正常了。
