### ISSUE TITLE
service register  fail： receive invalid redirect request from peer xx.xx.xx.xx

### ISSUE THREAD

**Issue by jackwang-wangcb** [alibaba/nacos#5113]
**Describe the bug**
nacos遇到一个很神奇的事情
用docker 部署了三个nacos 组成集群，用nginx反向代理
写了一个服务，命名为cardGateway，注册失败提示 
**Expected behavior**
nacos registry, cardGateway register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='192.168.78.242:8048', endpoint='', namespace='cardplat-config', watchDelay=30000, logName='', service='cardGateway', weight=1.0, clusterName='DEFAULT', group='cardApp', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.78.124', networkInterface='', port=18085, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null}},

com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([192.168.78.242:8048]) tried: ErrCode:400, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Mar 16 14:33:21 CST 2021</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 192.168.78.242</div></body></html>
： receive invalid redirect request from peer 192.168.78.242

**How to Reproduce**
然后 服务换个名cardGateay111 就能注册成功
为了测试 是否是部署的问题，逐一停掉docker nacos，发现任意停集群中的掉两个，都能注册成功。

实在是不知道该如何修改了：（

**Comment by jackwang-wangcb** [comment]
在 naming-server.log 中监控到了这样的错误
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
        at com.alibaba.nacos.common.http.client.request.DefaultAsyncHttpClientRequest.execute(DefaultAsyncHttpClientRequest.java:52)
        at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.execute(NacosAsyncRestTemplate.java:364)
        at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.get(NacosAsyncRestTemplate.java:66)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpRequest(HttpClient.java:186)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpGet(HttpClient.java:133)
        at com.alibaba.nacos.naming.misc.ServerStatusSynchronizer.send(ServerStatusSynchronizer.java:55)
        at com.alibaba.nacos.naming.cluster.ServerListManager$ServerStatusReporter.run(ServerListManager.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
