### ISSUE TITLE
service register  fail： receive invalid redirect request from peer xx.xx.xx.xx

### ISSUE THREAD

**Issue by jackwang-wangcb** [alibaba/nacos#5138]
Describe the bug
nacos遇到一个很神奇的事情
用docker 部署了三个nacos 组成集群，用nginx反向代理
写了一个服务，命名为cardGateway，注册失败提示
Expected behavior
nacos registry, cardGateway register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='192.168.78.242:8048', endpoint='', namespace='cardplat-config', watchDelay=30000, logName='', service='cardGateway', weight=1.0, clusterName='DEFAULT', group='cardApp', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.78.124', networkInterface='', port=18085, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null}},

com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([192.168.78.242:8048]) tried: ErrCode:400, ErrMsg:

Whitelabel Error Page
This application has no explicit mapping for /error, so you are seeing this as a fallback.

Tue Mar 16 14:33:21 CST 2021
There was an unexpected error (type=Bad Request, status=400).
receive invalid redirect request from peer 192.168.78.242

： receive invalid redirect request from peer 192.168.78.242
How to Reproduce
然后 服务换个名cardGateay111 就能注册成功
为了测试 是否是部署的问题，逐一停掉docker nacos，发现任意停集群中的掉两个，都能注册成功。

实在是不知道该如何修改了：（

在 naming-server.log 中监控到了这样的错误
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
at org.apache.http.util.Asserts.check(Asserts.java:46)
at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
at com.alibaba.nacos.common.http.client.request.DefaultAsyncHttpClientRequest.execute(DefaultAsyncHttpClientRequest.java:52)
at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.execute(NacosAsyncRestTemplate.java:364)
at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.get(NacosAsyncRestTemplate.java:66)
at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpRequest(HttpClient.java:186)
at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpGet(HttpClient.java:133)
at com.alibaba.nacos.naming.misc.ServerStatusSynchronizer.send(ServerStatusSynchronizer.java:55)
at com.alibaba.nacos.naming.cluster.ServerListManager$ServerStatusReporter.run(ServerListManager.java:235)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by KomachiSion** [comment]
Which version？

This problem is that the healthy status of nacos-server are different and the distro can't calculate right responsible server node.

**Comment by jackwang-wangcb** [comment]
version:NACOS1.4.1 
docker deploy?
节点状态为：
192.168.78.241:8848 UP 节点元数据
192.168.78.241:8849 UP 节点元数据
192.168.78.242:8848 UP 节点元数据

How to solve it

**Comment by KomachiSion** [comment]
search log in naming-server.log.  key word is `healthy server list`.

Please search in all server node and provide newest logs.

**Comment by jackwang-wangcb** [comment]
找到您说的日志：
nacos1：
2021-03-19 00:00:03,759 INFO [NACOS-DISTRO] healthy server list changed, old: [192.168.78.241:8848, 192.168.78.242:8848], new: [192.168.78.241:8848]
2021-03-19 00:00:04,923 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: 192.168.78.241:8849
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
        at com.alibaba.nacos.common.http.client.request.DefaultAsyncHttpClientRequest.execute(DefaultAsyncHttpClientRequest.java:52)
        at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.execute(NacosAsyncRestTemplate.java:364)

2021-03-19 00:00:05,537 INFO [NACOS-DISTRO] healthy server list changed, old: [192.168.78.241:8848], new: [192.168.78.241:8848, 192.
168.78.242:8848]

2021-03-19 00:00:06,924 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: 192.168.78.241:8849

java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
        at com.alibaba.nacos.common.http.client.request.DefaultAsyncHttpClientRequest.execute(DefaultAsyncHttpClientRequest.java:52)
        at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.execute(NacosAsyncRestTemplate.java:364)
        at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.get(NacosAsyncRestTemplate.java:66)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpRequest(HttpClient.java:186)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpGet(HttpClient.java:133)
        at com.alibaba.nacos.naming.misc.ServerStatusSynchronizer.send(ServerStatusSynchronizer.java:55)
        at com.alibaba.nacos.naming.cluster.ServerListManager$ServerStatusReporter.run(ServerListManager.java:235)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)


nacos2的日志:

2021-03-19 00:00:06,947 INFO [NACOS-DISTRO] healthy server list changed, old: [192.168.78.241:8848, 192.168.78.241:8849, 192.168.78.242:8848], new: [192.168.78.241:8848, 192.168.78.241:8849, 192.168.78.242:8848]
2021-03-19 00:00:07,537 INFO [NACOS-DISTRO] healthy server list changed, old: [192.168.78.241:8848, 192.168.78.241:8849, 192.168.78.242:8848], new: [192.168.78.241:8848, 192.168.78.241:8849, 192.168.78.242:8848]
2021-03-19 00:00:07,653 INFO receive config info: unknown#192.168.78.241:8848#1616083207652#4^M
2021-03-19 00:00:08,727 INFO receive config info: unknown#192.168.78.242:8848#1616083522428#4^M


naocs3 的日志：
没有发现 key=healthy server list  相关记录

**Comment by KomachiSion** [comment]
nacos1 和nacos2 的节点信息不一致导致的，需要排查下192.168.78.241:8848和192.168.78.241:8849 之间的互通问题。

**Comment by jackwang-wangcb** [comment]
同一个主机，只是不同的端口，从网络层面讲，他们的互通会有啥问题呢？

**Comment by jackwang-wangcb** [comment]
多问一句nacos 2.0 稳定版 何时发布，当前的版本应该不太适合 生产环境，期待2.0 能解决这些问题

**Comment by KomachiSion** [comment]
```
2021-03-19 00:00:04,923 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: 192.168.78.241:8849
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
```

同一台主机 不同端口， 然后nio显示I/O reactor是Stop的状态，说明和系统环境有关。

**Comment by CherishCai** [comment]
![image](https://user-images.githubusercontent.com/16837364/142798172-5ebf7c51-496b-4944-adba-1b0cb8649c81.png)

https://stackoverflow.com/questions/35350376/java-lang-illegalstateexception-request-cannot-be-executed-i-o-reactor-status

https://issues.apache.org/jira/browse/HTTPASYNC-104

@KomachiSion 建议升级下 asyncclient 的版本

**Comment by CherishCai** [comment]
@KomachiSion Maybe DirectMemory OOM?

https://stackoverflow.com/questions/35350376/java-lang-illegalstateexception-request-cannot-be-executed-i-o-reactor-status

https://issues.apache.org/jira/browse/HTTPASYNC-104
