### ISSUE TITLE
rejectedExecution

### ISSUE THREAD

**Issue by VitZhou** [alibaba/nacos#5200]
2021-03-26 12:04:52.156 ERROR [authority,,,] 5698 --- [31.247_8848-dev] c.a.n.client.config.impl.ClientWorker    : longPolling error : 

java.util.concurrent.RejectedExecutionException: Task java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask@a46cd27 rejected from java.util.concurrent.ScheduledThreadPoolExecutor@66bfd8ea[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 5]
	at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2063)
	at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:830)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:326)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:533)
	at java.util.concurrent.ScheduledThreadPoolExecutor.execute(ScheduledThreadPoolExecutor.java:622)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:635)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

每次动态刷新之后就报错

**Desktop (please complete the following information):**
 - OS: centos
 - Version nacos-server 1.4.1
 - SDK spring-cloud-alibaba-nacos: 1.4.1

**Additional context**
目前来看executorService.execute(new LongPollingRunnable(i)); 跟LongPollingRunnable里面的executorService.execute(this);形成了一个死循环导致this对象不断的往线程池中添加任务最终导致队列塞满

**Comment by KomachiSion** [comment]
duplicate with #4748
