### ISSUE TITLE
V2.0 create service error. did not find the Leader node

### ISSUE THREAD

**Issue by areswxin** [alibaba/nacos#5239]
deploy k8s,standalone
configuration management is work,but create service appear error.

caused: errCode: 500, errMsg: do metadata operation failed ;caused: com.alibaba.nacos.consistency.exception.ConsistencyException: com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException: The Raft Group [naming_service_metadata] did not find the Leader node;caused: com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException: The Raft Group [naming_service_metadata] did not find the Leader node;

protocol-raft.log:
2021-03-30 17:52:11,070 ERROR Fail to refresh leader for group : naming_instance_metadata, status is : Status[UNKNOWN<-1>: Unknown leader]

2021-03-30 17:52:11,072 ERROR Fail to refresh route configuration for group : naming_instance_metadata, status is : Status[UNKNOWN<-1>: Fail to get leader of group naming_instance_metadata]

2021-03-30 17:52:12,998 ERROR Fail to refresh leader for group : naming_persistent_service_v2, status is : Status[UNKNOWN<-1>: Unknown leader]

2021-03-30 17:52:13,000 ERROR Fail to refresh route configuration for group : naming_persistent_service_v2, status is : Status[UNKNOWN<-1>: Fail to get leader of group naming_persistent_service_v2]

2021-03-30 17:52:17,092 ERROR Fail to refresh leader for group : naming_instance_metadata, status is : Status[UNKNOWN<-1>: Unknown leader]

2021-03-30 17:52:17,094 ERROR Fail to refresh route configuration for group : naming_instance_metadata, status is : Status[UNKNOWN<-1>: Fail to get leader of group naming_instance_metadata]

2021-03-30 17:52:18,000 ERROR Fail to refresh leader for group : naming_service_metadata, status is : Status[UNKNOWN<-1>: Unknown leader]

2021-03-30 17:52:18,001 ERROR Fail to refresh route configuration for group : naming_service_metadata, status is : Status[UNKNOWN<-1>: Fail to get leader of group naming_service_metadata]

 nacos.log:
Caused by: java.util.concurrent.ExecutionException: com.alibaba.nacos.consistency.exception.ConsistencyException: com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException: The Raft Group [naming_service_metadata] did not find the Leader node
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1928)
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.write(JRaftProtocol.java:181)
	at com.alibaba.nacos.naming.core.v2.metadata.NamingMetadataOperateService.submitMetadataOperation(NamingMetadataOperateService.java:139)
	... 88 common frames omitted
Caused by: com.alibaba.nacos.consistency.exception.ConsistencyException: com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException: The Raft Group [naming_service_metadata] did not find the Leader node
	at com.alibaba.nacos.core.distributed.raft.utils.FailoverClosureImpl.run(FailoverClosureImpl.java:60)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.invokeToLeader(JRaftServer.java:455)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.commit(JRaftServer.java:363)
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.writeAsync(JRaftProtocol.java:186)
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.write(JRaftProtocol.java:179)
	... 89 common frames omitted
2021-03-30 17:52:00,876 WARN clearConfigHistory start

**Comment by areswxin** [comment]
image： nacos/nacos-server:2.0.0

**Comment by KomachiSion** [comment]
`com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException` there is no leader for jraft. Please check `alipay-jraft.log` and `protocol-raft.log` to find out reason.

and also can try to fix it like doc FAQ `Error code:503,msg:server is DOWN now, please try again later! during using.` in https://nacos.io/en-us/docs/2.0.0-compatibility.html

**Comment by areswxin** [comment]
@KomachiSion  tks!
Because V1 and V2 versions exist at the same time,It's causing this problem.
Delete the v1 version and return to normal
