### ISSUE TITLE
k8s部署多个服务副本，过一段时间后出现服务无法同步

### ISSUE THREAD

**Issue by a386572631** [alibaba/nacos#5258]
每加载一次服务列表，服务不一致。
尝试部署单个服务副本，暂未发现问题。

**Comment by a386572631** [comment]
nacos2.0.0

**Comment by a386572631** [comment]
more /home/nacos/logs/alipay-jraft.log
-----------------------------------------------------------------------------------------------------------------------------------
2021-04-01 08:17:27,577 ERROR Fail to connect nacos-2.nacos.wfw-test.svc.cluster.local:7848, remoting exception: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io excep
tion.

2021-04-01 08:17:27,577 ERROR Fail to connect peer nacos-2.nacos.wfw-test.svc.cluster.local:7848 to get leader for group naming_persistent_service.

2021-04-01 08:17:27,579 WARN Channel in TRANSIENT_FAILURE state: nacos-1.nacos.wfw-test.svc.cluster.local:7848.

2021-04-01 08:17:27,579 WARN Channel in SHUTDOWN state: nacos-1.nacos.wfw-test.svc.cluster.local:7848.

2021-04-01 08:17:28,139 WARN Channel in TRANSIENT_FAILURE state: nacos-0.nacos.wfw-test.svc.cluster.local:7848.

2021-04-01 08:17:28,139 WARN Channel in SHUTDOWN state: nacos-0.nacos.wfw-test.svc.cluster.local:7848.
-----------------------------------------------------------------------------------------------------------------------------------

7848端口通的

**Comment by a386572631** [comment]
more /home/nacos/logs/alipay-jraft.log

2021-04-01 08:17:27,577 ERROR Fail to connect nacos-2.nacos.wfw-test.svc.cluster.local:7848, remoting exception: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io excep
tion.

2021-04-01 08:17:27,577 ERROR Fail to connect peer nacos-2.nacos.wfw-test.svc.cluster.local:7848 to get leader for group naming_persistent_service.
7848端口是开放的

**Comment by KomachiSion** [comment]
但是日志显示连接不上。 有没有可能是域名的问题？

**Comment by a386572631** [comment]
> 但是日志显示连接不上。 有没有可能是域名的问题？

可以解析

**Comment by batizhao** [comment]
部署在 k8s 上，三个节点，按官方 YAML。
从 1.4.0 升级到 2.0.0，也遇到这个问题。
服务列表不稳定，刷新会掉一些服务。

依赖版本都更新到最新
`
<spring-boot.version>2.4.4</spring-boot.version>
<spring-cloud-alibaba.version>2020.0.RC1</spring-cloud-alibaba.version>
<spring-cloud.version>2020.0.2</spring-cloud.version>
`

 Nacos 集群测试返回 true
`curl -X POST 'http://xxx/nacos/v1/cs/configs?dataId=example.properties&group=DEFAULT_GROUP&content=useLocalCache=false'`

经过反复清除集群测试，发现可能是 MySQL 这边的数据问题，清理了 /var/lib/mysql 目录，
但是 k8s 调度以后，可能还是会调度到之前的数据，索性把 volumes: mysql-data 干掉以后，现在稳定下来了。
另外，还手动增加了 9848，9849 两个端口，不过应该不加也可以。

**Comment by 1019822077** [comment]
集群脑裂了，我们也遇到这个问题了，可以看元数据，leader是否一样，任期是否一样。

**Comment by a386572631** [comment]
> 部署在 k8s 上，三个节点，按官方 YAML。
> 从 1.4.0 升级到 2.0.0，也遇到这个问题。
> 服务列表不稳定，刷新会掉一些服务。
> 
> 依赖版本都更新到最新
> `<spring-boot.version>2.4.4</spring-boot.version> <spring-cloud-alibaba.version>2020.0.RC1</spring-cloud-alibaba.version> <spring-cloud.version>2020.0.2</spring-cloud.version>`
> 
> Nacos 集群测试返回 true
> `curl -X POST 'http://xxx/nacos/v1/cs/configs?dataId=example.properties&group=DEFAULT_GROUP&content=useLocalCache=false'`
> 
> 经过反复清除集群测试，发现可能是 MySQL 这边的数据问题，清理了 /var/lib/mysql 目录，
> 但是 k8s 调度以后，可能还是会调度到之前的数据，索性把 volumes: mysql-data 干掉以后，现在稳定下来了。
> 另外，还手动增加了 9848，9849 两个端口，不过应该不加也可以。
但是我发现服务注册信息并不是存到数据库里的，数据库里只是配置

**Comment by a386572631** [comment]
> 集群脑裂了，我们也遇到这个问题了，可以看元数据，leader是否一样， "term": 1任期是否一样。如果不一样，说明脑裂了，多主了，所以服务就乱了。

选主正常，任期也一样

**Comment by a386572631** [comment]
> 部署在 k8s 上，三个节点，按官方 YAML。
> 从 1.4.0 升级到 2.0.0，也遇到这个问题。
> 服务列表不稳定，刷新会掉一些服务。
> 
> 依赖版本都更新到最新
> `<spring-boot.version>2.4.4</spring-boot.version> <spring-cloud-alibaba.version>2020.0.RC1</spring-cloud-alibaba.version> <spring-cloud.version>2020.0.2</spring-cloud.version>`
> 
> Nacos 集群测试返回 true
> `curl -X POST 'http://xxx/nacos/v1/cs/configs?dataId=example.properties&group=DEFAULT_GROUP&content=useLocalCache=false'`
> 
> 经过反复清除集群测试，发现可能是 MySQL 这边的数据问题，清理了 /var/lib/mysql 目录，
> 但是 k8s 调度以后，可能还是会调度到之前的数据，索性把 volumes: mysql-data 干掉以后，现在稳定下来了。
> 另外，还手动增加了 9848，9849 两个端口，不过应该不加也可以。

但是我发现服务注册信息并不是存到数据库里的，数据库里只是配置

**Comment by batizhao** [comment]
@a386572631 按道理是的，但我不知道问题出在哪里，目前是正常了。

**Comment by 1019822077** [comment]
> @a386572631 按道理是的，但我不知道问题出在哪里，目前是正常了。

你现在是正常的，因为集群正常了，当你不正常的时候，可以去看一下集群是否脑裂，其实可以复现的，直接看元数据哪个是leader，就docker stop掉它，剩下2个选主完毕后，再docker stop掉1个主，然后再star这2个，此时就脑裂了。

**Comment by batizhao** [comment]
@1019822077 那解决这个问题最好的方法是？

**Comment by KomachiSion** [comment]
如果是查询发现完全没有服务，看一下是不是返回了Server down的错误
如果查询发现有些有有些没有，就需要查看集群是不是都正确升级到2.0版本了（看官方升级文档说明，确认状态）。升级状态如果没有稳定，中间状态数据可能是有问题的。

**Comment by batizhao** [comment]
跑了几天，现在又不正常了。
服务列表里不稳定，时有时无。

**Comment by KomachiSion** [comment]
先确认下 
1. 是否有出现过重启nacos服务端的现象
2. protocol-distro和naming-distro日志是否有什么异常或者一直不停对某一个ip不停同步的情况
3. 确认naming-server日志是否都有Upgrade2.0 等字样
4. 查看集群管理页面各个节点的状态。

**Comment by a386572631** [comment]
@KomachiSion 后来我发现可能是nacos-quick-start.yaml文件部署的问题，我只是指定了数据库，没有nfs，所以不知道是把集群信息存在哪里了。然后部署了nfs，就没发现这种问题了。所以我想问下前者方式部署的话，集群信息存在哪里的？

**Comment by batizhao** [comment]
@KomachiSion

1、看 pod 没有重启过；
2、protocol-distro 确实有异常
### protocol-distro
```
2021-04-12 09:22:16,795 WARN [DISTRO] Sync data change failed.

com.alibaba.nacos.api.exception.NacosException: Connection is unregistered.
	at com.alibaba.nacos.common.remote.client.grpc.GrpcConnection$2.onSuccess(GrpcConnection.java:142)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcConnection$2.onSuccess(GrpcConnection.java:135)
	at com.google.common.util.concurrent.Futures$CallbackListener.run(Futures.java:1347)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-04-12 09:22:20,197 INFO [DISTRO-START] DistroSyncDeleteTask for DistroKey{resourceKey='resolve_failed:53337#true', resourceType='Nacos:Naming:v2:ClientData', targetServer='nacos-2.nacos-headless.default.svc.cluster.local.:8848'}
```

### naming-distro
```
2021-04-12 09:23:48,553 INFO client 172.20.4.10:57165#true is invalid, get new client from 172.20.2.167

2021-04-12 09:23:48,591 INFO [Client-Add] Received distro client sync data 172.20.4.10:57165#true

2021-04-12 09:23:51,244 INFO to remove keys: [], to update keys: [], source: nacos-2.nacos-headless.default.svc.cluster.local.:8848

2021-04-12 09:23:56,244 INFO to remove keys: [], to update keys: [], source: nacos-2.nacos-headless.default.svc.cluster.local.:8848

2021-04-12 09:24:01,245 INFO to remove keys: [], to update keys: [], source: nacos-2.nacos-headless.default.svc.cluster.local.:8848

2021-04-12 09:24:06,245 INFO to remove keys: [], to update keys: [], source: nacos-2.nacos-headless.default.svc.cluster.local.:8848
```
3、三个节点都是 UP
```
"raftPort": "7848",
"readyToUpgrade": true,
"version": "2.0.0"
```

**Comment by batizhao** [comment]
> @KomachiSion 后来我发现可能是nacos-quick-start.yaml文件部署的问题，我只是指定了数据库，没有nfs，所以不知道是把集群信息存在哪里了。然后部署了nfs，就没发现这种问题了。所以我想问下前者方式部署的话，集群信息存在哪里的？

2.0 之前我用的 1.4.0，一直没用过 nfs，也出现过这个问题，后来重新清理集群就好了。
现在 2.0 清理了，过几天就又出错了。

**Comment by a386572631** [comment]
@batizhao 实在不知道没有nfs的话服务信息是存哪的，可能这部分数据丢失了

**Comment by KomachiSion** [comment]
看样子是集群间的连接出问题导致数据无法同步 所以不一致了。 升级到2.0.0-bugfix再试试看。

另外看看其他日志是否有异常信息， 当前给出的日志只知道是连接不上。连接不上的原因未知。

**Comment by a386572631** [comment]
@KomachiSion 你好，我问个另外一个问题，nacos不支持hystrix么？只要开启hystrix，请求到的B服务的信息就是null，关掉hystrix又正常了。nacos2.0-bugfix版本。

**Comment by batizhao** [comment]
@KomachiSion 
升级到 2.0.0-bugfix 以后，跑了一个星期，应该是没问题了。
