### ISSUE TITLE
nacos无法创建bean——instanceOperatorClientImpl

### ISSUE THREAD

**Issue by TreasureJade** [alibaba/nacos#5289]
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'instanceOperatorClientImpl' defined in URL [jar:file:/Users/hobo/Documents/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.0.jar!/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientOperationServiceProxy' defined in URL [jar:file:/Users/hobo/Documents/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.0.jar!/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/Users/hobo/Documents/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.0.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/dv/m82y6_9d6r1b_qt2dr62yh8c0000gn/T/librocksdbjni27542608875363170.jnilib: dlopen(/private/var/folders/dv/m82y6_9d6r1b_qt2dr62yh8c0000gn/T/librocksdbjni27542608875363170.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/dv/m82y6_9d6r1b_qt2dr62yh8c0000gn/T/librocksdbjni27542608875363170.jnilib: mach-o, but wrong architecture
	/private/var/folders/dv/m82y6_9d6r1b_qt2dr62yh8c0000gn/T/librocksdbjni27542608875363170.jnilib: mach-o, but wrong architecture
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:107)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientOperationServiceProxy' defined in URL [jar:file:/Users/hobo/Documents/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.0.jar!/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/Users/hobo/Documents/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.0.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/dv/m82y6_9d6r1b_qt2dr62yh8c0000gn/T/librocksdbjni27542608875363170.jnilib: dlopen(/private/var/folders/dv/m82y6_9d6r1b_qt2dr62yh8c0000gn/T/librocksdbjni27542608875363170.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/dv/m82y6_9d6r1b_qt2dr62yh8c0000gn/T/librocksdbjni27542608875363170.jnilib: mach-o, but wrong architecture
	/private/var/folders/dv/m82y6_9d6r1b_qt2dr62yh8c0000gn/T/librocksdbjni27542608875363170.jnilib: mach-o, but wrong architecture
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 27 common frames omitted

**Comment by JackSun-Developer** [comment]
> /private/var/folders/dv/m82y6_9d6r1b_qt2dr62yh8c0000gn/T/librocksdbjni27542608875363170.jnilib: dlopen(/private/var/folders/dv/m82y6_9d6r1b_qt2dr62yh8c0000gn/T/librocksdbjni27542608875363170.jnilib, 1): no suitable image found. Did find:

这是由于你的RocksDB缺失，可以去网上搜索相关依赖包，或者去RocksDB社区咨询

**Comment by TreasureJade** [comment]
这个问题出现在2.0版本，重新安装1.4.1版本的时候就可以了，谢谢大佬

**Comment by realJackSun** [comment]
@TreasureJade 这个问题是在同一个平台上，重装了一下1.4.1就解决的吗？

**Comment by XTL-666** [comment]
启动没有报错，显示运行，查端口没有运行，拉日志看是这个错

**Comment by 54853315** [comment]
运行2.1.0版本，也是提示这个。
设备mac M1，openjdk18

**Comment by fudong121** [comment]
我的安装路径没有中文，单击模式一启动就报这个错，2.2.0版本的，有人知道怎么解决吗

**Comment by 54853315** [comment]
> 我的安装路径没有中文，单击模式一启动就报这个错，2.2.0版本的，有人知道怎么解决吗

去另外一个issue里，用别人准备好的docker镜像替换docker-compose里的nacos镜像来启动nacos2.1.0是可以的。

**Comment by fudong121** [comment]
> ocker-

感谢回答，我用的是win10装的2.2.0版本的nacos，一直报的是这个错，我又换了1.4.4的版本最后装好了，祝工作顺利！

**Comment by LuvYamashitaMizuki** [comment]
启动时也发现了这个问题：

- Windows 10
- Java 1.8.0_131
- Nacos 2.1.0 standalone模式启动

**Comment by fudong121** [comment]
> 

可以尝试nacos1.4.4版本

**Comment by rabbit-zhao** [comment]
java 版本问题，jdk 17 可以

**Comment by 3054308729** [comment]
使用JAVA11.0.13版本可以正常启动
