### ISSUE TITLE
nacos1.4.1 k8s集群化部署问题

### ISSUE THREAD

**Issue by lualeslie** [alibaba/nacos#5290]
利用k8s进行nacos1.4.1集群化部署，官方给的例子是一个statsfulset，3个副本，但是我尝试3个statefulset，各
1个副本组成集群，发现启动就有点问题，找不到peer，另外cluster.conf都是用的类似nacos-app-0-0.nacos-goku-0.microservice-nacos.svc.cluster.local:8848域名形式，想问下这两种方式区别在哪？
报错如下：
java.lang.IllegalStateException: unable to find local peer: nacos-app-0-0.nacos-goku-0.microservice-nacos.svc.cluster.local:8848, all peers: []
        at com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.local(RaftPeerSet.java:286)
        at com.alibaba.nacos.naming.core.ServiceManager.getMySelfClusterState(ServiceManager.java:307)
        at com.alibaba.nacos.naming.controllers.OperatorController.getClusterStates(OperatorController.java:283)
        at sun.reflect.GeneratedMethodAccessor145.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.nacos.naming.web.DistroFilter.doFilter(DistroFilter.java:157)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:69)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at com.alibaba.nacos.naming.web.TrafficReviseFilter.doFilter(TrafficReviseFilter.java:83)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:748)

**Comment by JackSun-Developer** [comment]
从日志来看，是各个节点互相无法访问，全都成为了孤岛。可能是k8s的yaml配置上的域名，与cluster.conf里填的不一致；或者由于k8s的部署方式不对，互相无法访问？可以沿着这个思路排查一下问题。

**Comment by KomachiSion** [comment]
3个statefulset的话，可能需要你自己修改一下k8s， 让nacos能够正确访问到其他2台服务端，同时cluster。conf也要正确配置。

1个statefulset的话，k8s会自动创建3个递增的域名，并且保证互通。配置文件只需要配置对应的递增域名。

**Comment by lualeslie** [comment]
> 3个statefulset的话，可能需要你自己修改一下k8s， 让nacos能够正确访问到其他2台服务端，同时cluster。conf也要正确配置。
> 
> 1个statefulset的话，k8s会自动创建3个递增的域名，并且保证互通。配置文件只需要配置对应的递增域名。

需要怎么针对性地改动？现在配置的NACOS_SEVERS=nacos-goku-0.microservice-nacos.svc.cluster.local:8848 nacos-goku-1.microservice-nacos.svc.cluster.local:8848 nacos-goku-2.microservice-nacos.svc.cluster.local:8848环境变量，用的yaml基本上是在quick-start.yaml上面改了一下数据库配置而已。

**Comment by lualeslie** [comment]
另外我看见1.4.1源码里面已经把com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet准备废弃掉了，但是一直在报错，curl了一下service地址，是能通的，这就很奇怪。

**Comment by lualeslie** [comment]
另外我看见1.4.1源码里面已经把com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet准备废弃掉了，但是一直在报错，curl了一下service地址，是能通的，这就很奇怪。

**Comment by KomachiSion** [comment]
curl能通是正常的，接口还在，但是应该是报错`old raft close`之类。 如果一直在报错，就需要排查下集群是否通信不正常，导致某一台一直没有关闭old raft，还一直在用旧raft来选主。

**Comment by lualeslie** [comment]
> curl能通是正常的，接口还在，但是应该是报错`old raft close`之类。 如果一直在报错，就需要排查下集群是否通信不正常，导致某一台一直没有关闭old raft，还一直在用旧raft来选主。

有什么办法确认集群是否通信正常，查看相应日志？还是？

**Comment by KomachiSion** [comment]
> > curl能通是正常的，接口还在，但是应该是报错`old raft close`之类。 如果一直在报错，就需要排查下集群是否通信不正常，导致某一台一直没有关闭old raft，还一直在用旧raft来选主。
> 
> 有什么办法确认集群是否通信正常，查看相应日志？还是？

有报错说明通信是正常的，主要看状态是不是正常的。

看日志是一种方法，naming-raft.log里能够看到close old raft之类的日志，且不会一直报你贴出的错误日志就说明是正常的。

还有一种确认方式就是看控制台上的集群管理的元数据， 如果还能看到naming字段，就是不正常的

**Comment by lualeslie** [comment]
> > > curl能通是正常的，接口还在，但是应该是报错`old raft close`之类。 如果一直在报错，就需要排查下集群是否通信不正常，导致某一台一直没有关闭old raft，还一直在用旧raft来选主。
> > 
> > 
> > 有什么办法确认集群是否通信正常，查看相应日志？还是？
> 
> 有报错说明通信是正常的，主要看状态是不是正常的。
> 
> 看日志是一种方法，naming-raft.log里能够看到close old raft之类的日志，且不会一直报你贴出的错误日志就说明是正常的。
> 
> 还有一种确认方式就是看控制台上的集群管理的元数据， 如果还能看到naming字段，就是不正常的

还有个问题想问下，我这边如果只想使用AP功能，能不能关闭CP功能，把raft协议相关内容屏蔽掉，且不影响正常使用。我这边感觉nacos没办法正常启动多受raft影响。

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/issues/5346

有计划在2.X版本优化这个部分。目前1.X没有这方面计划。
