### ISSUE TITLE
网络异常时，BeatReactor 心跳线程会中断，导致dubbo网络恢复后服务注册信息无法自动重新注册

### ISSUE THREAD

**Issue by bestpayAmes** [alibaba/nacos#5291]
The exception of BeatReactor ‘s BeatTask catched is wrong,when the dns can't work,the beat will suspend;
when unkownHost ,the nacos heat thread will interrupt;dubbo 's register info will be no recovery ;

dns不能工作时，com.alibaba.nacos.client.naming.beat.BeatReactor.BeatTask#run里会抛出非NacosException的异常，导致心跳任务停止，dns恢复后dubbo注册的服务不能恢复；

**Comment by JackSun-Developer** [comment]
您使用的nacos版本号，以及dubbo的版本号是？

**Comment by bestpayAmes** [comment]
nacos 1.4.1 ,dubbo 2.7.8
@JackSun-Developer

**Comment by KomachiSion** [comment]
能麻烦提供下，是哪一行，抛出了异常？

**Comment by bestpayAmes** [comment]
你跑个demo，然后吧而网线拔了，就能复现

**Comment by haoyann** [comment]
@bestpayAmes 
Hi，我用nacos 1.4.1没有复现呢，这是`com.alibaba.nacos.client.naming.net.NamingProxy#callServer`客户端发起请求的地方，我把网络断开，异常这里也捕获住了。
![image](https://user-images.githubusercontent.com/43994656/114418203-dbf44680-9be4-11eb-9565-9620547d194f.png)
`BeatTask` 也能捕获这个异常。
![image](https://user-images.githubusercontent.com/43994656/114419211-d2b7a980-9be5-11eb-8df5-0a5133312328.png)
重新连接网络之后，心跳也能恢复正常。你能提供一下是在哪里抛出的什么异常吗？

**Comment by bestpayAmes** [comment]
at com.alibaba.nacos.common.utils.IPUtil.splitIPPortStr(IPUtil.java:152) ~[nacos-common-1.4.1.jar:?]
	at com.alibaba.nacos.common.utils.IPUtil.containsPort(IPUtil.java:119) ~[nacos-common-1.4.1.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:595) ~[nacos-client-1.4.1.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) ~[nacos-client-1.4.1.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) ~[nacos-client-1.4.1.jar:?]
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:433) ~[nacos-client-1.4.1.jar:?]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:153) [classes/:?]

**Comment by bestpayAmes** [comment]
我用的是域名

**Comment by bestpayAmes** [comment]
问题描述里写了dns的

**Comment by haoyann** [comment]
@bestpayAmes 好的，谢谢！

**Comment by KomachiSion** [comment]
Fixed by #4802 .

but we also can enhance it by catch Exception in BeatTask like

```
            } catch (NacosException ex) {
                NAMING_LOGGER.error("[CLIENT-BEAT] failed to send beat: {}, code: {}, msg: {}",
                        JacksonUtils.toJson(beatInfo), ex.getErrCode(), ex.getErrMsg());
            } catch (Exception unknownEx) {
                XXX
            } finally {
            executorService.schedule(new BeatTask(beatInfo), nextTime, TimeUnit.MILLISECONDS);
}
```
