### ISSUE TITLE
nacos client的依赖包reflections升级到0.9.12版本后无法使用

### ISSUE THREAD

**Issue by ly532123842** [alibaba/nacos#5294]
目前项目上使用的是nacos client（2.0.0版本），其依赖的reflections版本为0.9.11。
因reflections  0.9.11版本的bug导致项目上必须将其升级为0.9.12，结果升级之后nacos异常无法使用了，请解决该问题

异常代码位置：
![image](https://user-images.githubusercontent.com/31655126/113833839-b3bbb080-97bc-11eb-96ef-87c63be58cbd.png)

异常信息：
com.alibaba.nacos.api.exception.NacosException: java.lang.reflect.InvocationTargetException
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:63) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77) ~[nacos-client-2.0.0.jar:?]
	at com.lc.ibps.common.nacos.NacosUtil.createService(NacosUtil.java:41) ~[ibps-common-biz-2.10.0-ZZHT.RELEASE.jar:?]
	at com.lc.ibps.common.nacos.service.impl.NacosInitListener.onApplicationEvent(NacosInitListener.java:69) ~[ibps-common-biz-2.10.0-ZZHT.RELEASE.jar:?]
	at com.lc.ibps.common.nacos.service.impl.NacosInitListener.onApplicationEvent(NacosInitListener.java:1) ~[ibps-common-biz-2.10.0-ZZHT.RELEASE.jar:?]
	at com.lc.ibps.common.nacos.service.impl.NacosInitListener$$FastClassBySpringCGLIB$$d9f7d7d8.invoke(<generated>) ~[ibps-common-biz-2.10.0-ZZHT.RELEASE.jar:?]
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204) ~[spring-core-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:746) ~[spring-aop-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:294) [spring-tx-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:98) [spring-tx-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) [spring-aop-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:185) [spring-aop-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:688) [spring-aop-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at com.lc.ibps.common.nacos.service.impl.NacosInitListener$$EnhancerBySpringCGLIB$$a8ef9e1e.onApplicationEvent(<generated>) [ibps-common-biz-2.10.0-ZZHT.RELEASE.jar:?]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) [spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) [spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) [spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) [spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) [spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:886) [spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) [spring-context-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:409) [spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:291) [spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at com.lc.ibps.base.web.listener.StartupListner.initWebApplicationContext(StartupListner.java:75) [ibps-base-web-2.10.0-ZZHT.RELEASE.jar:?]
	at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:103) [spring-web-5.0.10.RELEASE.jar:5.0.10.RELEASE]
	at com.lc.ibps.base.web.listener.StartupListner.contextInitialized(StartupListner.java:65) [ibps-base-web-2.10.0-ZZHT.RELEASE.jar:?]
	at com.lc.ibps.web.listener.WebApiStartupListener.contextInitialized(WebApiStartupListener.java:29) [classes/:?]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4727) [catalina.jar:8.5.9]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5189) [catalina.jar:8.5.9]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [catalina.jar:8.5.9]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [catalina.jar:8.5.9]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [catalina.jar:8.5.9]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_92]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_92]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_92]
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_92]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_92]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_92]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:60) ~[nacos-client-2.0.0.jar:?]
	... 37 more
Caused by: java.lang.ExceptionInInitializerError
	at com.alibaba.nacos.common.remote.client.RpcClientFactory.createClient(RpcClientFactory.java:78) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.<init>(NamingGrpcClientProxy.java:83) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:77) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:89) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:75) ~[nacos-client-2.0.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_92]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_92]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_92]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:60) ~[nacos-client-2.0.0.jar:?]
	... 37 more
Caused by: org.reflections.ReflectionsException: Scanner SubTypesScanner was not configured
	at org.reflections.Store.get(Store.java:39) ~[reflections-0.9.12.jar:?]
	at org.reflections.Store.get(Store.java:61) ~[reflections-0.9.12.jar:?]
	at org.reflections.Store.get(Store.java:46) ~[reflections-0.9.12.jar:?]
	at org.reflections.Store.getAll(Store.java:93) ~[reflections-0.9.12.jar:?]
	at org.reflections.Reflections.getSubTypesOf(Reflections.java:404) ~[reflections-0.9.12.jar:?]
	at com.alibaba.nacos.api.remote.PayloadRegistry.scan(PayloadRegistry.java:57) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.api.remote.PayloadRegistry.init(PayloadRegistry.java:44) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.common.remote.client.RpcClient.<clinit>(RpcClient.java:109) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.common.remote.client.RpcClientFactory.createClient(RpcClientFactory.java:78) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.<init>(NamingGrpcClientProxy.java:83) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:77) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:89) ~[nacos-client-2.0.0.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:75) ~[nacos-client-2.0.0.jar:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_92]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_92]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_92]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_92]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:60) ~[nacos-client-2.0.0.jar:?]
	... 37 more

**Comment by JackSun-Developer** [comment]
nacos暂不支持reflections包升级至0.9.12

**Comment by brothelul** [comment]
This issue is still not fixed in reflections 0.9.12, please see [reflections #273](https://github.com/ronmamo/reflections/issues/273)

**Comment by KomachiSion** [comment]
看起来这是0.9.12的一个bug。反而不应该升级。

我看issue中有提到使用reflections8， 是否应该调用一下我们是否可以用reflections8来替代？

**Comment by KomachiSion** [comment]
2.1.0 已经移除了对Reflections的依赖，该issue应该已经解决。
