### ISSUE TITLE
server-addr 会截断最后的字符

### ISSUE THREAD

**Issue by Mrchenkeyu** [alibaba/nacos#5297]
`cloud:
    nacos:
      discovery:
        server-addr: https://xxx.a.com`

报错如下：
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([**https://xxx.a.co**]) tried: failed to req API:https://xxx.a.co/nacos/v1/ns/instance. code:500 msg: java.net.UnknownHostException: xxx.a.co
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:464) ~[nacos-client-1.1.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386) ~[nacos-client-1.1.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:188) ~[nacos-client-1.1.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:205) ~[nacos-client-1.1.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:184) ~[nacos-client-1.1.1.jar:na]

查看源码`NacosDiscoveryProperties`类192-194行
`if (serverAddr.lastIndexOf("/") != -1) {
			serverAddr = serverAddr.substring(0, serverAddr.length() - 1);
		}`

**Comment by JackSun-Developer** [comment]
这貌似是Spring Cloud Alibaba里对于地址解析的写法问题吧，可以提ISSUE到Spring Cloud Alibaba社区。
