### ISSUE TITLE
nacos2.0 配合2.0的client无法注册服务

### ISSUE THREAD

**Issue by xulingfeng931027** [alibaba/nacos#5299]
**Describe the bug**
使用2.0的客户端连接2.0的nacos集群, 表现为能够正常拉取配置,但无法注册到注册中心,能够订阅服务(订阅者列表能搜到).

服务对应的日志如下:

2021-04-07 17:24:05.557 INFO [main][TomcatWebServer.java:start:203] - Tomcat started on port(s): 18017 (http) with context path ''
2021-04-07 17:24:05.675 INFO [main][NacosServiceRegistry.java:register:75] - nacos registry, DEFAULT_GROUP service-base 172.22.16.2:18017 register finished
2021-04-07 17:24:05.682 INFO [main][StartupInfoLogger.java:logStarted:61] - Started BaseApplication in 27.116 seconds (JVM running for 31.374)
2021-04-07 17:38:35.331 WARN [com.alibaba.nacos.client.naming.updater.-1][ServiceInfoUpdateService.java:run:195] - [NA] failed to update serviceName: DEFAULT_GROUP@@service-base
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:213)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.queryInstancesOfService(NamingGrpcClientProxy.java:128)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.queryInstancesOfService(NamingClientProxyDelegate.java:111)
	at com.alibaba.nacos.client.naming.core.ServiceInfoUpdateService$UpdateTask.run(ServiceInfoUpdateService.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.nacos.api.exception.NacosException: Request fail,Unknown Error
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:678)
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:608)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:203)
	... 10 common frames omitted

经debug 发现连接是建立了的 但就是无法注册  使用1.4 的client可以正常注册调用.  
8848 9848 9849 端口是通的 已经telnet过了
服务的bootstrap配置如下:
#服务名
spring.application.name=service-base
#环境
spring.profiles.active=dev
#bean-overriding
spring.main.allow-bean-definition-overriding=true
#nacos
spring.cloud.nacos.server-addr=172.22.10.65:8848,172.22.10.66:8848,172.22.10.67:8848
spring.cloud.nacos.discovery.namespace=mall-${spring.profiles.active}
spring.cloud.nacos.config.namespace=mall-${spring.profiles.active}
spring.cloud.nacos.config.shared-configs[0].dataId=service-common.properties
spring.cloud.nacos.config.shared-configs[0].group=GLOBAL
spring.cloud.nacos.config.shared-configs[1].dataId=redis.properties
spring.cloud.nacos.config.shared-configs[1].group=GLOBAL
spring.cloud.nacos.config.shared-configs[2].dataId=sentinel.properties
spring.cloud.nacos.config.shared-configs[2].group=GLOBAL
spring.cloud.nacos.config.shared-configs[3].dataId=prometheus.properties
spring.cloud.nacos.config.shared-configs[3].group=GLOBAL

**Comment by JackSun-Developer** [comment]
请升级到2.0.0-bugfix版本

**Comment by chengjiaxiongkf** [comment]
我有遇到此问题类似的情况，使用nacos1.4版本一切正常，但是换成nacos2.0版本后。
可以从注册中心拉取配置正常启动，日志输出也是 register finished，并且服务能调用通，nacos控制台上服务列表中不显示注册的服务实例 。
nacos客户端为java的nacos-client 2.0.0 jar包,其他依赖包版本为
<spring-boot.version>2.2.2.RELEASE</spring-boot.version>
<spring-cloud.version>Hoxton.RELEASE</spring-cloud.version>
<spring-cloud-alibaba.version>2.2.0.RELEASE</spring-cloud-alibaba.version>
使用了spring-cloud-starter-dubbo整合内置默认的dubbo2.7.4

nacos服务端为以下2.0.0-bugfix版本:
https://github.com/alibaba/nacos/releases/download/2.0.0-bugfix/nacos-server-2.0.0.tar.gz

**Comment by KomachiSion** [comment]
@xulingfeng931027 , 有其他的提示信息吗？ 看下服务端是否有报错？

**Comment by warthur1214** [comment]
无法注册问题看下这个issue: #5215
nacos2.0的账号必须分配public空间权限

**Comment by KomachiSion** [comment]
> 在服务器上直接执行./stratup.sh 方式部署时，如果部署过单机模式会生成protocol文件夹，之后如果再部署集群模式，会导致nacos控制台-服务列表没有服务实例信息并且查询请求报HTTP错误码503。解决方案：在部署集群模式前删除/nacos/data/protocol 这个文件夹。

https://nacos.io/en-us/docs/2.0.0-compatibility.html FAQ

> 集群模式部署多个服务端实例，不要使用内置嵌入数据源，会导致服务注册成功但是nacos中找不到服务实例，解决方案：使用mysql等外置数据源。

和内嵌数据源没有关系，注册成功但是找不到服务很可能是控制台请求返回了Server Down错误，原因和上一个问题一致。

**Comment by xulingfeng931027** [comment]
节点的元数据如下:
{
    "lastRefreshTime": 1617784317590,
    "raftMetaData": {
        "metaDataMap": {
            "naming_instance_metadata": {
                "leader": "172.22.10.66:7848",
                "raftGroupMember": [
                    "172.22.10.66:7848",
                    "172.22.10.65:7848",
                    "172.22.10.67:7848"
                ],
                "term": 2
            },
            "naming_persistent_service": {
                "leader": "172.22.10.66:7848",
                "raftGroupMember": [
                    "172.22.10.66:7848",
                    "172.22.10.65:7848",
                    "172.22.10.67:7848"
                ],
                "term": 9
            },
            "naming_persistent_service_v2": {
                "leader": "172.22.10.67:7848",
                "raftGroupMember": [
                    "172.22.10.66:7848",
                    "172.22.10.65:7848",
                    "172.22.10.67:7848"
                ],
                "term": 2
            },
            "naming_service_metadata": {
                "leader": "172.22.10.67:7848",
                "raftGroupMember": [
                    "172.22.10.66:7848",
                    "172.22.10.65:7848",
                    "172.22.10.67:7848"
                ],
                "term": 2
            }
        }
    },
    "raftPort": "7848",
    "readyToUpgrade": false,
    "version": "2.0.0"
}

nacos日志没有明显报错

**Comment by KomachiSion** [comment]
`"readyToUpgrade": false,` 虽然是2.0.0版本，但是集群状态并没有升级到2.0 使用的仍然是1.X体系。

```
curl -X PUT 'localhost:8848/nacos/v1/ns/operator/switches?entry=doubleWriteEnabled&value=false'
```

执行一下这个命令再试试
