### ISSUE TITLE
k8s nacos1.4.1集群突然故障

### ISSUE THREAD

**Issue by bestpayAmes** [alibaba/nacos#5311]
请问k8s 部署的nacos 1.4.1 忽然出现
protocol-raft.log:2021-04-07 22:42:59,276 ERROR Fail to refresh route configuration for group : naming_persistent_service, status is : Status[UNKNOWN<-1>: handleRequest internal error]
2021-04-07 22:42:59,212 WARN Node <naming_persistent_service/nacos-0.nacos-headless.nacos.svc.cluster.local:7848> steps down when alive nodes don't satisfy quorum, term=1, deadNodes=nacos-2.nacos-headless.nacos.svc.cluster.local:7848,nacos-1.nacos-headless.nacos.svc.clu
ster.local:7848, conf=nacos-2.nacos-headless.nacos.svc.cluster.local:7848,nacos-1.nacos-headless.nacos.svc.cluster.local:7848,nacos-0.nacos-headless.nacos.svc.cluster.local:7848.

2021-04-07 22:42:59,227 INFO onLeaderStop: status=Status[ERAFTTIMEDOUT<10001>: Majority of the group dies: 2/3].

2021-04-07 22:42:59,228 INFO Replicator Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=89, lastLogIncluded=0, lastLogIndex=89, lastTermIncluded=0>, peerId=nacos-2.nacos-headless.nacos.svc.cluster.local:7848, type=Follower] is going to quit

2021-04-07 22:42:59,252 INFO Replicator Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=89, lastLogIncluded=0, lastLogIndex=89, lastTermIncluded=0>, peerId=nacos-1.nacos-headless.nacos.svc.cluster.local:7848, type=Follower] is going to quit

2021-04-07 22:42:59,253 INFO Node <naming_persistent_service/nacos-0.nacos-headless.nacos.svc.cluster.local:7848> received PreVoteRequest from nacos-2.nacos-headless.nacos.svc.cluster.local:7848, term=2, currTerm=1, granted=true, requestLastLogId=LogId [index=89, term=1
], lastLogId=LogId [index=89, term=1].

2021-04-07 22:42:59,258 INFO Node <naming_persistent_service/nacos-0.nacos-headless.nacos.svc.cluster.local:7848> received RequestVoteRequest from nacos-2.nacos-headless.nacos.svc.cluster.local:7848, term=2, currTerm=1.

2021-04-07 22:42:59,253 ERROR handleRequest group_id: "naming_persistent_service"
leader_id: "nacos-0.nacos-headless.nacos.svc.cluster.local:7848"
failed

java.lang.IllegalStateException: Not leader
at com.alipay.sofa.jraft.core.NodeImpl.listPeers(NodeImpl.java:2908)
at com.alipay.sofa.jraft.rpc.impl.cli.GetPeersRequestProcessor.processRequest0(GetPeersRequestProcessor.java:58)
at com.alipay.sofa.jraft.rpc.impl.cli.GetPeersRequestProcessor.processRequest0(GetPeersRequestProcessor.java:33)
at com.alipay.sofa.jraft.rpc.impl.cli.BaseCliRequestProcessor.processRequest(BaseCliRequestProcessor.java:119)
at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:53)
at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:35)
at com.alipay.sofa.jraft.rpc.impl.GrpcServer.lambda$null$1(GrpcServer.java:194)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

的报错，所有服务全部下线，集群不可用；这个是什么问题？

**Comment by bestpayAmes** [comment]
2021-04-07 22:42:59,212 WARN Node <naming_persistent_service/nacos-0.nacos-headless.nacos.svc.cluster.local:7848> steps down when alive nodes don't satisfy quorum, term=1, deadNodes=nacos-2.nacos-headless.nacos.svc.cluster.local:7848,nacos-1.nacos-headless.nacos.svc.clu
ster.local:7848, conf=nacos-2.nacos-headless.nacos.svc.cluster.local:7848,nacos-1.nacos-headless.nacos.svc.cluster.local:7848,nacos-0.nacos-headless.nacos.svc.cluster.local:7848.

2021-04-07 22:42:59,227 INFO onLeaderStop: status=Status[ERAFTTIMEDOUT<10001>: Majority of the group dies: 2/3].

2021-04-07 22:42:59,228 INFO Replicator Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=89, lastLogIncluded=0, lastLogIndex=89, lastTermIncluded=0>, peerId=nacos-2.nacos-headless.nacos.svc.cluster.local:7848, type=Follower] is going to quit

2021-04-07 22:42:59,252 INFO Replicator Replicator [state=Replicate, statInfo=<running=IDLE, firstLogIndex=89, lastLogIncluded=0, lastLogIndex=89, lastTermIncluded=0>, peerId=nacos-1.nacos-headless.nacos.svc.cluster.local:7848, type=Follower] is going to quit

2021-04-07 22:42:59,253 INFO Node <naming_persistent_service/nacos-0.nacos-headless.nacos.svc.cluster.local:7848> received PreVoteRequest from nacos-2.nacos-headless.nacos.svc.cluster.local:7848, term=2, currTerm=1, granted=true, requestLastLogId=LogId [index=89, term=1
], lastLogId=LogId [index=89, term=1].

2021-04-07 22:42:59,258 INFO Node <naming_persistent_service/nacos-0.nacos-headless.nacos.svc.cluster.local:7848> received RequestVoteRequest from nacos-2.nacos-headless.nacos.svc.cluster.local:7848, term=2, currTerm=1.

2021-04-07 22:42:59,253 ERROR handleRequest group_id: "naming_persistent_service"
leader_id: "nacos-0.nacos-headless.nacos.svc.cluster.local:7848"
 failed

java.lang.IllegalStateException: Not leader
	at com.alipay.sofa.jraft.core.NodeImpl.listPeers(NodeImpl.java:2908)
	at com.alipay.sofa.jraft.rpc.impl.cli.GetPeersRequestProcessor.processRequest0(GetPeersRequestProcessor.java:58)
	at com.alipay.sofa.jraft.rpc.impl.cli.GetPeersRequestProcessor.processRequest0(GetPeersRequestProcessor.java:33)
	at com.alipay.sofa.jraft.rpc.impl.cli.BaseCliRequestProcessor.processRequest(BaseCliRequestProcessor.java:119)
	at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:53)
	at com.alipay.sofa.jraft.rpc.RpcRequestProcessor.handleRequest(RpcRequestProcessor.java:35)
	at com.alipay.sofa.jraft.rpc.impl.GrpcServer.lambda$null$1(GrpcServer.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by KomachiSion** [comment]
java.lang.IllegalStateException: Not leader

看一下控制台是否报错是`server Down`

**Comment by bestpayAmes** [comment]
无法复现了，已经重启恢复了，日志我都可以提供，不能通过日志定位吗？

**Comment by bestpayAmes** [comment]
> java.lang.IllegalStateException: Not leader
> 
> 看一下控制台是否报错是`server Down`

已经重启恢复了,没法看控制台了，但是日志我都可以提供，能通过日志定位吗？

**Comment by KomachiSion** [comment]
`deadNodes=nacos-2.nacos-headless.nacos.svc.cluster.local:7848,nacos-1.nacos-headless.nacos.svc.clu
ster.local:7848, conf=nacos-2.nacos-headless.nacos.svc.cluster.local:7848,nacos-1.nacos-headless.nacos.svc.cluster.local:7848,nacos-0.nacos-headless.nacos.svc.cluster.local:7848`

应该是当时集群网络出故障了，重启pod之后网络恢复了。就正常了。应该不是选主问题。
