### ISSUE TITLE
bug report - Nacos 2.0 running in cluster model, but cannot find each

### ISSUE THREAD

**Issue by greatwave** [alibaba/nacos#5317]
## Issue Description
I am running Nocas 2.0 in two machine, 192.168.1.111, 192.168.1.112, when I start the nacos, it always throw exception.

`2021-04-09 12:52:58,255 ERROR [Cluster-192.168.1.112:8848]Send request fail, request=DistroDataRequest{headers={}, requestId='null'}, retryTimes=0,errorMessage=Client not connected.

2021-04-09 12:52:58,355 ERROR [Cluster-192.168.1.112:8848]Send request fail, request=DistroDataRequest{headers={}, requestId='null'}, retryTimes=1,errorMessage=Client not connected.

2021-04-09 12:52:58,455 ERROR [Cluster-192.168.1.112:8848]Send request fail, request=DistroDataRequest{headers={}, requestId='null'}, retryTimes=2,errorMessage=Client not connected.

2021-04-09 12:52:58,724 INFO [Cluster-192.168.1.112:8848] fail to connect server,after trying 79 times, last try server is {serverIp='192.168.1.112', server main port=8848},error=unknown`

`2021-04-09 12:51:12,094 INFO [Cluster-192.168.1.111:8848] fail to connect server,after trying 1 times, last try server is {serverIp='192.168.1.111', server main port=8848},error=unknown

2021-04-09 12:51:13,306 INFO [Cluster-192.168.1.111:8848] fail to connect server,after trying 2 times, last try server is {serverIp='192.168.1.111', server main port=8848},error=unknown

2021-04-09 12:51:16,612 INFO [Cluster-192.168.1.111:8848] fail to connect server,after trying 3 times, last try server is {serverIp='192.168.1.111', server main port=8848},error=unknown

2021-04-09 12:51:17,018 INFO [Cluster-192.168.1.111:8848] fail to connect server,after trying 4 times, last try server is {serverIp='192.168.1.111', server main port=8848},error=unknown

2021-04-09 12:51:17,528 INFO [Cluster-192.168.1.111:8848] fail to connect server,after trying 5 times, last try server is {serverIp='192.168.1.111', server main port=8848},error=unknown`

But I visit the nacos web page, it shows correct.

### Describe what happened (or what feature you want)

I running my springboot application register on Nacos

`
Spring  
cloud:
    nacos:
      discovery:
        server-addr: 192.168.1.111:8848,192.168.1.112:8848
nacos:
  config:
    server-addr: 192.168.1.111:8848,192.168.1.112:8848
  discovery:
    server-addr: 192.168.1.111:8848,192.168.1.112:8848`

it also show register error.

`com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([192.168.1.111:8848, 192.168.1.112:8848]) tried: ErrCode:503, ErrMsg:server is DOWN now, please try again later!
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:556) ~[nacos-client-1.4.1.jar!/:na]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) ~[nacos-client-1.4.1.jar!/:na]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) ~[nacos-client-1.4.1.jar!/:na]
        at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:246) ~[nacos-client-1.4.1.jar!/:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:212) ~[nacos-client-1.4.1.jar!/:na]
`
### Describe what you expected to happen
I have running Nacos cluster successfully before, but it crashes suddenly. I try several way to restore including back to standalone mode, and re-install nacos. but all won't work.

please let me know what this happens? and any solution for that?

The Nacos running on two clear machines, without any other applications.

**Comment by JackSun-Developer** [comment]
把~/nacos/data目录删了，重启一下试试？

**Comment by KomachiSion** [comment]
Please make sure your cluster status is right. From the error information, your cluster is not ready and can't connect to each other.

web page can open is not means that your nacos is running well. It ONLY open the port.

**Comment by greatwave** [comment]
> 把~/nacos/data目录删了，重启一下试试？

两个服务器的Data目录都删了，还是原样

**Comment by greatwave** [comment]
问题解决了，这个是由于防火墙只开了8848端口，而屏蔽了关联端口导致。按照Nocas 2.0的文档，Nacos除了8848以后，会同步位移1000以及1001作为Naming service。
系统里面，我默认值开启了8848，所以导致naming service无法连接。
