### ISSUE TITLE
 升级到1.4.1一直打印error日志并删除了Provider服务

### ISSUE THREAD

**Issue by TyCode-Tommy** [alibaba/nacos#5319]
Nacos升级到1.4.1版本后 **naming.log** 日志内容：
**Issue Description**
2021-04-09 14:06:04.929 ERROR [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] [NA] failed to request
org.apache.http.impl.execchain.RequestAbortedException: Request execution failed
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:199) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.12.jar:4.5.12]
	at com.alibaba.nacos.common.http.client.DefaultHttpClientRequest.execute(DefaultHttpClientRequest.java:54) ~[nacos-common-1.3.1.jar:na]
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:330) ~[nacos-common-1.3.1.jar:na]
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:319) ~[nacos-common-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:599) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:330) [nacos-client-1.3.1.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:397) [nacos-client-1.3.1.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_201]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_201]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_201]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_201]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_201]
Caused by: java.util.concurrent.CancellationException: Operation aborted
	at org.apache.http.pool.AbstractConnPool.operationAborted(AbstractConnPool.java:182) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.pool.AbstractConnPool.access$200(AbstractConnPool.java:70) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:251) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:198) ~[httpcore-4.4.13.jar:4.4.13]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:306) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:282) ~[httpclient-4.5.12.jar:4.5.12]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:190) ~[httpclient-4.5.12.jar:4.5.12]
	... 23 common frames omitted

**持续输出很多遍，大概运行半天后，Nacos自动将Dubbo Provider服务全部删除，造成系统瘫痪，日志如下：**
2021-04-09 14:10:58.974 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.knowledge.service.KnowledgeService:: -> [{"instanceId":"172.29.226.7#20881#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.knowledge.service.KnowledgeService::","ip":"172.29.226.7","port":20881,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.knowledge.service.KnowledgeService::","metadata":{"serialization":"fst","path":"com.purvar.knowledge.service.KnowledgeService","protocol":"dubbo","application":"pgy-logic","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936426821"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:10:58.994 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.knowledge.service.KnowledgeService:: -> []
2021-04-09 14:11:02.751 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.school.service.SchoolService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.school.service.SchoolService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.school.service.SchoolService::","metadata":{"serialization":"fst","path":"com.purvar.school.service.SchoolService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936426376"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:02.765 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.school.service.SchoolService:: -> []
2021-04-09 14:11:04.079 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.que.service.QueService:: -> [{"instanceId":"172.29.226.7#20881#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.que.service.QueService::","ip":"172.29.226.7","port":20881,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.que.service.QueService::","metadata":{"serialization":"fst","path":"com.purvar.que.service.QueService","protocol":"dubbo","application":"pgy-logic","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936431836"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:04.089 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.que.service.QueService:: -> []
2021-04-09 14:11:09.446 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.classes.service.ClassesService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.classes.service.ClassesService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.classes.service.ClassesService::","metadata":{"serialization":"fst","path":"com.purvar.classes.service.ClassesService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936429066"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:09.454 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.classes.service.ClassesService:: -> []
2021-04-09 14:11:09.848 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.system.service.PstuAccountService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.system.service.PstuAccountService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.system.service.PstuAccountService::","metadata":{"serialization":"fst","path":"com.purvar.system.service.PstuAccountService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936429136"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:09.858 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.system.service.PstuAccountService:: -> []
2021-04-09 14:11:10.795 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.message.service.MessageService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.message.service.MessageService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.message.service.MessageService::","metadata":{"serialization":"fst","path":"com.purvar.message.service.MessageService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936429228"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:10.804 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.message.service.MessageService:: -> []
2021-04-09 14:11:12.756 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysPermisService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.system.service.SysPermisService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.system.service.SysPermisService::","metadata":{"serialization":"fst","path":"com.purvar.system.service.SysPermisService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936429308"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:12.765 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysPermisService:: -> []
2021-04-09 14:11:14.046 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysUserService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.system.service.SysUserService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.system.service.SysUserService::","metadata":{"serialization":"fst","path":"com.purvar.system.service.SysUserService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936429503"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:14.058 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysUserService:: -> []
2021-04-09 14:11:14.411 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.order.service.OrderService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.order.service.OrderService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.order.service.OrderService::","metadata":{"serialization":"fst","path":"com.purvar.order.service.OrderService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936429592"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:14.420 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.order.service.OrderService:: -> []
2021-04-09 14:11:15.366 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysRolePermisService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.system.service.SysRolePermisService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.system.service.SysRolePermisService::","metadata":{"serialization":"fst","path":"com.purvar.system.service.SysRolePermisService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936429699"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:15.385 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysRolePermisService:: -> []
2021-04-09 14:11:15.451 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysRoleService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.system.service.SysRoleService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.system.service.SysRoleService::","metadata":{"serialization":"fst","path":"com.purvar.system.service.SysRoleService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936429821"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:15.462 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysRoleService:: -> []
2021-04-09 14:11:15.811 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.school.service.SchYearTermService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.school.service.SchYearTermService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.school.service.SchYearTermService::","metadata":{"serialization":"fst","path":"com.purvar.school.service.SchYearTermService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936429914"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:15.823 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.school.service.SchYearTermService:: -> []
2021-04-09 14:11:16.793 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.message.service.MessageTemplateService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.message.service.MessageTemplateService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.message.service.MessageTemplateService::","metadata":{"serialization":"fst","path":"com.purvar.message.service.MessageTemplateService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936430036"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:16.804 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.message.service.MessageTemplateService:: -> []
2021-04-09 14:11:17.905 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysRoleAccountService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.system.service.SysRoleAccountService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.system.service.SysRoleAccountService::","metadata":{"serialization":"fst","path":"com.purvar.system.service.SysRoleAccountService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936430259"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:17.915 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysRoleAccountService:: -> []
2021-04-09 14:11:19.279 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.exercise.service.PstuExerciseErrorQueService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.exercise.service.PstuExerciseErrorQueService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.exercise.service.PstuExerciseErrorQueService::","metadata":{"serialization":"fst","path":"com.purvar.exercise.service.PstuExerciseErrorQueService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936430371"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:19.296 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.exercise.service.PstuExerciseErrorQueService:: -> []
2021-04-09 14:11:20.297 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] removed ips(1) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysPermisGroupService:: -> [{"instanceId":"172.29.226.7#20882#DEFAULT#DEFAULT_GROUP@@providers:com.purvar.system.service.SysPermisGroupService::","ip":"172.29.226.7","port":20882,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.purvar.system.service.SysPermisGroupService::","metadata":{"serialization":"fst","path":"com.purvar.system.service.SysPermisGroupService","protocol":"dubbo","application":"pgy-sso","release":"2.7.8","deprecated":"false","dubbo":"2.0.2","category":"providers","timeout":"3600000","timestamp":"1617936430614"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2021-04-09 14:11:20.310 INFO [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] current ips:(0) service: DEFAULT_GROUP@@providers:com.purvar.system.service.SysPermisGroupService:: -> []
2021-04-09 14:17:03.845 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.classes.service.ClassesService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.856 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.classes.service.ClassesService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.882 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.packages.service.TblUserPackageDetailService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.888 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.packages.service.TblUserPackageDetailService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.890 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.wximage.service.WxImageService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.891 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.wximage.service.WxImageService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.892 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.school.service.SchYearTermService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.898 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.school.service.SchYearTermService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.900 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.report.service.IndexGradeService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.901 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.report.service.IndexGradeService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.903 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.system.service.SysRolePermisService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.903 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.system.service.SysRolePermisService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.906 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.system.service.SysAccountService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.906 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.system.service.SysAccountService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.909 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.que.service.QueService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.914 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.que.service.QueService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.917 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.system.service.SysAttachService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.917 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.system.service.SysAttachService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.918 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.exercise.service.TrainingCaseService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.919 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.exercise.service.TrainingCaseService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.921 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.system.service.SysRoleAccountService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.921 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.system.service.SysRoleAccountService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.922 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.system.service.SysRoleService:::172.29.226.7:0 from beat map.
2021-04-09 14:17:03.923 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [DEREGISTER-SERVICE] public deregistering service DEFAULT_GROUP@@consumers:com.purvar.system.service.SysRoleService:: with instance: Instance{instanceId='null', ip='172.29.226.7', port=0, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={}}
2021-04-09 14:17:03.924 INFO [RMI TCP Connection(13)-127.0.0.1:c.a.n.c.naming] [BEAT] removing beat: DEFAULT_GROUP@@consumers:com.purvar.system.service.SysCodeService:::172.29.226.7:0 from beat map.

在Nacos Web管理界面查询如下：
![image](https://user-images.githubusercontent.com/82196192/114142884-0aa0c180-9946-11eb-8bf4-d140f11a2848.png)

所有服务已然变为空服务。

**Comment by TyCode-Tommy** [comment]
Important：Keep the project nacos client consistent with the nacos server
