### ISSUE TITLE
k8s cluster mode： NacosException: server is DOWN now, please try again later!

### ISSUE THREAD

**Issue by liurongwei** [alibaba/nacos#5334]
**Describe the bug**
spring boot discovery client throw exceptions,  but config client not get error , in the nacos console board to check the service registry info , refresh the service in the service list , the service is unstable in the list. although I have checked cluster status is in healty status , but the service discovery client still throw the exception below .

`021-04-11 11:48:59.686 ERROR 4188 --- [ing.beat.sender] com.alibaba.nacos.client.naming          : [NA] failed to request

com.alibaba.nacos.api.exception.NacosException: server is DOWN now, please try again later!
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:433)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

`{
    "lastRefreshTime": 1618113171231,
    "raftMetaData": {
        "metaDataMap": {
            "naming_instance_metadata": {
                "leader": "nacos-0.nacos-hs.prod.svc.cluster.local:7848",
                "raftGroupMember": [
                    "nacos-1.nacos-hs.prod.svc.cluster.local:7848",
                    "nacos-0.nacos-hs.prod.svc.cluster.local:7848"
                ],
                "term": 1
            },
            "naming_persistent_service": {
                "leader": "nacos-0.nacos-hs.prod.svc.cluster.local:7848",
                "raftGroupMember": [
                    "nacos-1.nacos-hs.prod.svc.cluster.local:7848",
                    "nacos-0.nacos-hs.prod.svc.cluster.local:7848"
                ],
                "term": 1
            },
            "naming_persistent_service_v2": {
                "leader": "nacos-0.nacos-hs.prod.svc.cluster.local:7848",
                "raftGroupMember": [
                    "nacos-1.nacos-hs.prod.svc.cluster.local:7848",
                    "nacos-0.nacos-hs.prod.svc.cluster.local:7848"
                ],
                "term": 1
            },
            "naming_service_metadata": {
                "leader": "nacos-0.nacos-hs.prod.svc.cluster.local:7848",
                "raftGroupMember": [
                    "nacos-1.nacos-hs.prod.svc.cluster.local:7848",
                    "nacos-0.nacos-hs.prod.svc.cluster.local:7848"
                ],
                "term": 1
            }
        }
    },
    "raftPort": "7848",
    "readyToUpgrade": true,
    "version": "2.0.0"
}`

**Expected behavior**
service registry should work properly as the service instance work well .

**Acutally behavior**
set up the nacos cluster , and login to the nacos console ,and check cluster status 

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by KomachiSion** [comment]
Fixed by merge #5350
