### ISSUE TITLE
java应用奔溃

### ISSUE THREAD

**Issue by whaon** [alibaba/nacos#5342]
nacos版本为1.3.2，部署3台集群
1. nacos服务本身长期占用cpu，差不多20%-50%左右
2. nacos客户端的java应用疯狂输出日志：
[2021-04-12 10:41:17:669] [TID: N/A] [] [WARN] com.alibaba.nacos.client.naming.updater - com.alibaba.nacos.client.naming.core.HostReactor.processServiceJson(HostRe
actor.java:140) - out of date data received, old-t: 1618195377023, new-t: 1618195277674
[2021-04-12 10:41:17:928] [TID: N/A] [] [WARN] com.alibaba.nacos.client.naming.updater - com.alibaba.nacos.client.naming.core.HostReactor.processServiceJson(HostRe
actor.java:140) - out of date data received, old-t: 1618195377278, new-t: 1618195277932
[2021-04-12 10:41:21:295] [TID: N/A] [] [WARN] com.alibaba.nacos.client.naming.updater - com.alibaba.nacos.client.naming.core.HostReactor.processServiceJson(HostRe
actor.java:140) - out of date data received, old-t: 1618195380633, new-t: 1618195281300

3. java应用崩溃过，OOM，发现是gc频繁，mat结果如下：

![Dingtalk_20210412151055](https://user-images.githubusercontent.com/2542483/114354954-7cc11280-9ba1-11eb-8159-5cfec86c141c.jpg)
![image](https://user-images.githubusercontent.com/2542483/114356109-d1b15880-9ba2-11eb-9cde-9e1c986e8ba1.png)

![image](https://user-images.githubusercontent.com/2542483/114356089-c9f1b400-9ba2-11eb-877a-89631b8d2368.png)

**Comment by KomachiSion** [comment]
看一下有多少个NacosNamingService对象，如果超过1个请先自行排查是否用法有错误。

如果是使用dubbo或SCA。请升级至最新版本解决该问题。

**Comment by whaon** [comment]
> 看一下有多少个NacosNamingService对象，如果超过1个请先自行排查是否用法有错误。
> 
> 如果是使用dubbo或SCA。请升级至最新版本解决该问题。

感谢回答
是使用sca，并且使用dubbo，最新版本是nacos和客户端同时升级么，是1.4.1么，无缝升级么
这个是bug么，产生的原因是什么，有没有详细点的信息

**Comment by KomachiSion** [comment]
这个bug是dubbo或spring cloud的bug。 并非nacos的。 原因是在使用时， 创建很多个NacosNamingService对象。每个NacosNamingService对象又持有一个HostReactor，HostReactor再创建很数个线程和上下文。导致线程和内存问题。

方法应该是升级SCA或者dubbo的版本。具体对应的issue可以到SCA和dubbo的issue中检索一下。 nacos的issue也有相关。

**Comment by luoxiner** [comment]
Service数据的更新依靠客户端主动pull和server在数据改变的时候向client push，out of date warning 是在processServiceJson函数中出现的，所以猜测出现这样的warning可能的原因：
客户端先进行pull，而后server在service变动之后进行push，但是push得到的json数据被先处理，更新了serviceInfoMap中的数据，在这之后客户端处理了pull获取的json数据，此时得到的LastRefTime是大于pull的LastRefTime的，产生warning。

**Comment by KomachiSion** [comment]
日志的warning问题主要可能有两种
1. 如图示，有很多NacosNamingService导致很多HostReactor，影响了服务端的推送。
2. 客户端的时钟和服务端的时钟差距过大。导致比较时间时总是过期。

优先解决一下NacosNamingService和HostReactor数量过多问题。然后再看下是否稳定。

**Comment by whaon** [comment]
> 日志的warning问题主要可能有两种
> 
> 1. 如图示，有很多NacosNamingService导致很多HostReactor，影响了服务端的推送。
> 2. 客户端的时钟和服务端的时钟差距过大。导致比较时间时总是过期。
> 
> 优先解决一下NacosNamingService和HostReactor数量过多问题。然后再看下是否稳定。

感谢哈，正在准备升级
目前sca版本为2.2.3.RELEASE，dubbo也是用的starter，版本也为2.2.3.RELEASE，dubbo实际版本为2.7.8
但dubbo的stater最新版本使用的dubbo依然为2.7.8，坐标如下：
```
  <groupId>com.alibaba.cloud</groupId>
  <artifactId>spring-cloud-starter-dubbo</artifactId>
  <version>2021.1</version>
```
如果强行使用dubbo最新版本2.7.10，会报以下错误，导致项目起不来：
```
java.lang.NoSuchMethodError: com.alibaba.nacos.client.config.http.HttpAgent.httpGet(Ljava/lang/String;Ljava/util/List;Ljava/util/List;Ljava/lang/String;J)Lcom/alibaba/nacos/client/config/impl/HttpSimpleClient$HttpResult;
	at org.apache.dubbo.configcenter.support.nacos.NacosDynamicConfiguration.getConfigKeys(NacosDynamicConfiguration.java:271) ~[dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.common.config.configcenter.wrapper.CompositeDynamicConfiguration.lambda$getConfigKeys$5(CompositeDynamicConfiguration.java:82) ~[dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.common.config.configcenter.wrapper.CompositeDynamicConfiguration.iterateConfigOperation(CompositeDynamicConfiguration.java:94) ~[dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.common.config.configcenter.wrapper.CompositeDynamicConfiguration.getConfigKeys(CompositeDynamicConfiguration.java:82) ~[dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.metadata.DynamicConfigurationServiceNameMapping.lambda$getAndListen$1(DynamicConfigurationServiceNameMapping.java:86) ~[dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.metadata.DynamicConfigurationServiceNameMapping.execute(DynamicConfigurationServiceNameMapping.java:96) ~[dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.metadata.DynamicConfigurationServiceNameMapping.getAndListen(DynamicConfigurationServiceNameMapping.java:84) ~[dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.findMappedServices(ServiceDiscoveryRegistry.java:414) ~[dubbo-2.7.10.jar:2.7.10]

```
请问升级的最佳实践是什么，或者版本匹配是什么

**Comment by KomachiSion** [comment]
错误应该是dubbo使用了反射获取nacos的内部对象来使用，但是内部对象有可能在版本更新时修改，导致dubbo无法匹配。

这方面正在和dubbo社区进行沟通解决。

如果需要升级。建议直接使用默认引入的版本。
