### ISSUE TITLE
版本1.3.2部署了三台的集群，选举出了Leader，Leader宕机后其他两台没有进行重新选举，为什么？

### ISSUE THREAD

**Issue by tyhqiushen** [alibaba/nacos#5385]
如题所述

![a646cde0ccad0586714cc03d25d01cb](https://user-images.githubusercontent.com/9135264/114977909-0ed75c80-9ebb-11eb-925f-7b7ceecaee9b.png)

**Comment by KomachiSion** [comment]
看一下naming-raft.log有没有什么异常。

**Comment by tyhqiushen** [comment]
> 看一下naming-raft.log有没有什么异常。

java.net.ConnectException: Connection refused: no further information: /192.168.25.97:8848 to http://192.168.25.97:8848/nacos/v1/ns/raft/beat
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:380)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: no further information: /192.168.25.97:8848
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 common frames omitted
2021-04-16 18:28:23,518 ERROR NACOS-RAFT error while sending heart-beat to peer: 192.168.25.97:8848 {}


一直连接宕机的那台，说连接被拒绝。但是那台已经宕机了，连接被拒绝应该是正常的。

**Comment by tyhqiushen** [comment]
> 看一下naming-raft.log有没有什么异常。

java.net.ConnectException: Connection refused: no further information: /192.168.25.97:8848 to http://192.168.25.97:8848/nacos/v1/ns/raft/beat
	at com.ning.http.client.providers.netty.NettyConnectListener.operationComplete(NettyConnectListener.java:103)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListener(DefaultChannelFuture.java:427)
	at org.jboss.netty.channel.DefaultChannelFuture.notifyListeners(DefaultChannelFuture.java:418)
	at org.jboss.netty.channel.DefaultChannelFuture.setFailure(DefaultChannelFuture.java:380)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:109)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.process(NioClientBoss.java:79)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:312)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.run(NioClientBoss.java:42)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.ConnectException: Connection refused: no further information: /192.168.25.97:8848
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.connect(NioClientBoss.java:150)
	at org.jboss.netty.channel.socket.nio.NioClientBoss.processSelectedKeys(NioClientBoss.java:105)
	... 8 common frames omitted
2021-04-16 18:28:23,518 ERROR NACOS-RAFT error while sending heart-beat to peer: 192.168.25.97:8848 {}


一直连接宕机的那台，说连接被拒绝。但是那台已经宕机了，连接被拒绝应该是正常的。

**Comment by KomachiSion** [comment]
看下有没有选主的日志，以及移除非健康节点的日志。

如果没有的话可能是旧版本的bug，需要升级到新版本再试下

**Comment by tyhqiushen** [comment]
> 看下有没有选主的日志，以及移除非健康节点的日志。
> 
> 如果没有的话可能是旧版本的bug，需要升级到1.3.2再试下

nacos-cluster.log日志中也全是错误：
2021-04-16 18:28:23,516 ERROR failed to report new info to target node : 192.168.25.97:8848, error : caused: Connection refused: no further information;

就一直提示无法提交信息给宕机那个节点。

我现在这个版本就是1.3.2版本了，我看好像官网说这个版本稳定，我就选的这个。

**Comment by KomachiSion** [comment]
您的关注点跑偏了啊，已经down的这台有这个错误是正常的，不应该关注这个点。

您应该关注的是raft的相关日志，并排除掉这台down掉的机器，查看下剩余的信息，为什么没有发生选主，还是说选主了但是控制台元数据没有更新。

**Comment by tyhqiushen** [comment]
> 您的关注点跑偏了啊，已经down的这台有这个错误是正常的，不应该关注这个点。
> 
> 您应该关注的是raft的相关日志，并排除掉这台down掉的机器，查看下剩余的信息，为什么没有发生选主，还是说选主了但是控制台元数据没有更新。

是这样的，我其实不是关注down掉的那台机器。我的意思是说，那台机器宕机了，那另外两台不应该再去关注那台宕机的机器是否还能连上，而应该发起选举过程。

目前我这个集群，从leader宕机之后，另外两台感觉一直在尝试去连宕机那台服务器，也不重新发起选举，并且在各自的raft日志文件中，一直输出ERROR failed to report new info to target node : 192.168.25.97:8848, error : caused: Connection refused: no further information;   然后其他的什么也不做。


昨天我试了一下1.4.1版本，也是三台集群，停掉leader之后。也出现了类似的情况。并且jraft日志一直输出：2021-04-23 10:32:56,524 INFO Node naming_persistent_service:10.168.101.226:12879 received InstallSnapshotResponse from 10.168.102.240:12879 lastIncludedIndex=2 lastIncludedTerm=8 success=true   3/4毫秒就刷一条，仍然启动的两台Nacos都是这个情况。

但是无法选出leader，几个小时的时间，jraft日志文件刷了2GB，CPU也拉上去了。
我的用法再普通不过了。三台机器一起启动的时候，一切正常，可以选举出leader。把leader强制关闭，其余两台马上就出问题了。比较头疼，我也没有什么比较奇怪的操作，感觉都是常规操作。

公司在做这方面的技术选型，我力挺Nacos，结果出现这样的情况，感觉实在有点尴尬。。

**Comment by tyhqiushen** [comment]
2021-04-22 20:51:55,200 INFO raft peers changed: [Member{ip='10.168.102.240', port=12880, state=UP, extendInfo={raftPort=12879}}, Member{ip='10.168.101.226', port=12880, state=UP, extendInfo={raftPort=12879}}, Member{ip='10.168.101.238', port=12880, state=UP, extendInfo={raftPort=12879}}]

2021-04-22 20:51:55,345 INFO raft peers changed: [Member{ip='10.168.102.240', port=12880, state=UP, extendInfo={raftPort=12879}}, Member{ip='10.168.101.226', port=12880, state=UP, extendInfo={raftPort=12879}}, Member{ip='10.168.101.238', port=12880, state=UP, extendInfo={raftPort=12879}}]

2021-04-22 20:51:55,714 INFO initializing Raft sub-system

2021-04-22 20:51:55,720 INFO finish loading all datums, size: 0 cost 1 ms.

2021-04-22 20:51:55,740 INFO cache loaded, datum count: 0, current term: 0

2021-04-22 20:51:55,745 INFO finish to load data from disk, cost: 25 ms.

2021-04-22 20:51:55,779 INFO timer started: leader timeout ms: 15000, heart-beat timeout ms: 5000

2021-04-22 20:52:04,763 INFO leader timeout, start voting,leader: null, term: 0

2021-04-22 20:52:09,060 ERROR error while sending vote to server: 10.168.101.238:12880

java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:748)
2021-04-22 20:52:11,613 INFO received approve from peer: {"ip":"10.168.102.240:12880","voteFor":"10.168.102.240:12880","term":11,"leaderDueMs":3003,"heartbeatDueMs":1500,"state":"CANDIDATE"}

2021-04-22 20:52:13,472 INFO snapshot load from : /home/nacos/nacos/data/protocol/raft/naming_persistent_service/snapshot/snapshot_1/naming_persistent

2021-04-22 20:52:15,796 INFO add listener: com.alibaba.nacos.naming.domains.meta.00-00---000-NACOS_SWITCH_DOMAIN-000---00-00

2021-04-22 20:52:15,938 INFO add listener: com.alibaba.nacos.naming.domains.meta.

2021-04-22 20:52:21,752 INFO leader timeout, start voting,leader: null, term: 1

2021-04-22 20:52:21,802 INFO received approve from peer: {"ip":"10.168.102.240:12880","voteFor":"10.168.102.240:12880","term":12,"leaderDueMs":6896,"heartbeatDueMs":500,"state":"CANDIDATE"}

2021-04-22 20:52:25,246 INFO received approve from peer: {"ip":"10.168.101.238:12880","voteFor":"10.168.101.238:12880","term":3,"leaderDueMs":18792,"heartbeatDueMs":4500,"state":"CANDIDATE"}

2021-04-22 20:52:34,097 INFO [RAFT] make remote as leader, remote peer: {"ip":"10.168.102.240:12880","voteFor":"10.168.102.240:12880","term":13,"leaderDueMs":19410,"heartbeatDueMs":5000,"state":"LEADER"}

2021-04-22 20:52:34,126 INFO 10.168.102.240:12880 has become the LEADER, local: {"ip":"10.168.101.226:12880","voteFor":"10.168.102.240:12880","term":2,"leaderDueMs":19892,"heartbeatDueMs":5000,"state":"FOLLOWER"}, leader: {"ip":"10.168.102.240:12880","voteFor":"10.168.102.240:12880","term":13,"leaderDueMs":19410,"heartbeatDueMs":5000,"state":"LEADER"}

2021-04-22 20:52:35,078 WARN start to close old raft protocol!!!

2021-04-22 20:52:35,078 WARN stop old raft protocol task for notifier

2021-04-22 20:52:35,080 WARN stop old raft protocol task for master task

2021-04-22 20:52:35,081 WARN stop old raft protocol task for heartbeat task

2021-04-22 20:52:35,081 WARN clean old cache datum for old raft

2021-04-22 20:52:35,084 WARN start to close old raft protocol!!!

2021-04-22 20:52:35,085 WARN stop old raft protocol task for notifier

2021-04-22 20:52:35,086 WARN stop old raft protocol task for master task

2021-04-22 20:52:35,086 WARN stop old raft protocol task for heartbeat task

2021-04-22 20:52:35,086 WARN clean old cache datum for old raft

2021-04-22 20:52:35,086 WARN start to move old raft protocol metadata

2021-04-22 20:52:35,091 WARN start to move old raft protocol metadata

2021-04-22 20:52:37,021 INFO raft peers changed: [Member{ip='10.168.102.240', port=12880, state=UP, extendInfo={lastRefreshTime=1619095956999, naming={voteFor=10.168.102.240:12880, ip=10.168.102.240:12880, heartbeatDueMs=4500, term=13, leaderDueMs=15793, state=LEADER}, raftMetaData={metaDataMap={naming_persistent_service={leader=10.168.101.238:12879, raftGroupMember=[10.168.101.226:12879, 10.168.102.240:12879, 10.168.101.238:12879], term=8}}}, raftPort=12879, version=1.4.1}}, Member{ip='10.168.101.226', port=12880, state=UP, extendInfo={lastRefreshTime=1619095955091, raftMetaData=com.alibaba.nacos.consistency.ProtocolMetaData@23913fe, raftPort=12879, version=1.4.1}}, Member{ip='10.168.101.238', port=12880, state=UP, extendInfo={lastRefreshTime=1619095956780, naming={voteFor=10.168.102.240:12880, ip=10.168.101.238:12880, heartbeatDueMs=5000, term=13, leaderDueMs=19329, state=FOLLOWER}, raftMetaData={metaDataMap={naming_persistent_service={leader=10.168.101.238:12879, raftGroupMember=[10.168.101.226:12879, 10.168.102.240:12879, 10.168.101.238:12879], term=8}}}, raftPort=12879, site=unknown, version=1.4.1, weight=1}}]


这是挡掉leader之后，出问题的naming-raft.log

**Comment by KomachiSion** [comment]
你用的不是1.3.2吗？ 怎么日志是1.4.1的？

1.4.1用的是jraft，旧的raft只是给升级的时候用的，全部升级到1.4.1之后就不需要了，数据不会更新，并且会删除掉。

```
raftMetaData={metaDataMap={naming_persistent_service={leader=10.168.101.238:12879, raftGroupMember=[10.168.101.226:12879, 10.168.102.240:12879, 10.168.101.238:12879], term=8}}}
```

真正的leader看这个信息。

**Comment by tyhqiushen** [comment]
> 你用的不是1.3.2吗？ 怎么日志是1.4.1的？
> 
> 1.4.1用的是jraft，旧的raft只是给升级的时候用的，全部升级到1.4.1之后就不需要了，数据不会更新，并且会删除掉。
> 
> ```
> raftMetaData={metaDataMap={naming_persistent_service={leader=10.168.101.238:12879, raftGroupMember=[10.168.101.226:12879, 10.168.102.240:12879, 10.168.101.238:12879], term=8}}}
> ```
> 
> 真正的leader看这个信息。

我是开始用的1.3.2，不是一直有问题吗，leader宕机，其余两台无法选出leader。我实在没办法了。就用1.4.1又试了一下，毕竟这是最新的稳定版本。

raftMetaData={metaDataMap={naming_persistent_service={leader=10.168.101.238:12879, raftGroupMember=[10.168.101.226:12879, 10.168.102.240:12879, 10.168.101.238:12879], term=8}}}
真正的leader看这个信息。


问题就在这了，这说的238是leader了，可我238已经宕机了。。。。[\哭][\哭]
我一共三台机器，226  238   240，   238宕机后，我这个是从226上拿下来的日志。。。

**Comment by SealinRepo** [comment]
我记得选举Leader要至少3个节点才能进行吧, 看起来你的节点只剩两个, 集群无法继续工作是正常情况, 你可以启动4个节点, 再关leader试试剩下的节点能不能正常选举.@tyhqiushen

**Comment by tyhqiushen** [comment]
> 我记得选举Leader要至少3个节点才能进行吧, 看起来你的节点只剩两个, 集群无法继续工作是正常情况, 你可以启动4个节点, 再关leader试试剩下的节点能不能正常选举.@tyhqiushen

不是的，集群选举raft算法只要集群数量过半就可以，集群是3台机器。宕机一台其实也是3台。剩下两台只要都投给一个节点。那个节点就可以当选新leader。其实推荐是奇数台机器，偶数台机器比较浪费。

**Comment by KomachiSion** [comment]
是不是你发出日志的时候238还没down，选主了。down了之后选主的日志你没有贴出来。

**Comment by tyhqiushen** [comment]
> 是不是你发出日志的时候238还没down，选主了。down了之后选主的日志你没有贴出来。
> 
> 而且你日志贴出的元数据感觉也有问题。 整个集群升级到1.4.1后，应该没有naming内容的元数据了。但是你提供的日志还是有的。感觉是中间状态的日志。

所以，我也觉得很奇怪。我升级到1.4.1的时候，是重新部署的。
238这台机器我停掉了大概有15分钟了，我才截取的这个日志。我感觉应该不存在238还存活的情况。直接kill -9杀的进程。

我感觉你们也没什么头绪，可能不是常见问题，也说不准和我本地环境有关，触发了某些问题。
要不我再自己排查一下吧。辛苦了。


另外，感觉选举过程中，cpu会高一下，选举成功后，cpu就降为正常了。
这个选举过程怎么这么消耗cpu资源。现在我们团队领导不太敢上，怕我把cpu给他们干上天。
我都没发说啥。。。很是尴尬。

**Comment by SealinRepo** [comment]
> > 我记得选举Leader要至少3个节点才能进行吧, 看起来你的节点只剩两个, 集群无法继续工作是正常情况, 你可以启动4个节点, 再关leader试试剩下的节点能不能正常选举.@tyhqiushen
> 
> 不是的，集群选举raft算法只要集群数量过半就可以，集群是3台机器。宕机一台其实也是3台。剩下两台只要都投给一个节点。那个节点就可以当选新leader。其实推荐是奇数台机器，偶数台机器比较浪费。

好吧, 可能是我理解有问题, 我理解的数量过半是健康节点的数量不能少于N / 2 + 1, 也就是说在3个节点的情况挂一个, 剩两个健康节点就不满足这个条件了

**Comment by KomachiSion** [comment]
2个节点能够成功选主，没有问题。 主要还是部署的环境可能存在问题。  另外日志一直没有找到核心信息，没法找到问题点。

1.3.2和1.4.1的选主是有区别的。如果是1.4.1的话，需要看protocol-raft和alipay-jraft两个日志。
