### ISSUE TITLE
windows 版，单机模式启动异常

### ISSUE THREAD

**Issue by dwj1979** [alibaba/nacos#5441]
**Describe the bug**
2.0.0_BugFix版windows发布包，使用单机模式及默认的内置文件数据库，所以没有配置数据库信息，使用压缩包内的配置文件，启动失败，提示数据库相关的错误：

**Expected behavior**
启动正常启动

**Acutally behavior**
发生异常：
2021-04-21 21:20:59,622 ERROR [db-load-error]load jdbc.properties error

java.lang.IllegalArgumentException: db.num is null
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceProperties.build(ExternalDataSourceProperties.java:75)
	at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl.reload(ExternalDataSourceServiceImpl.java:123)
	at com.alibaba.nacos.config.server.service.datasource.ExternalDataSourceServiceImpl.init(ExternalDataSourceServiceImpl.java:106)
	at com.alibaba.nacos.config.server.service.datasource.DynamicDataSource.getDataSource(DynamicDataSource.java:55)
	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.init(ExternalStoragePersistServiceImpl.java:134)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

**How to Reproduce**
1. 下载2.0.0-BugFix版，Windows版的zip压缩包
2. 解压缩，使用默认配置， 使用 -m standlone 参数启动
3.See error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Version： nacos-server 2.0.0 BugFix

**Comment by dwj1979** [comment]
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosAuthManager': Unsatisfied dependency expressed through field 'authenticationManager'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosAuthConfig': Unsatisfied dependency expressed through field 'userDetailsService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'nacosUserDetailsServiceImpl': Unsatisfied dependency expressed through field 'userPersistService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'externalUserPersistServiceImpl': Unsatisfied dependency expressed through field 'persistService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalStoragePersistServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:598)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:90)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:376)

**Comment by JackSun-Developer** [comment]
![image](https://user-images.githubusercontent.com/58767027/115640753-42e2cf80-a34a-11eb-9248-d8a3345f03d2.png)
怀疑是这里打错导致的？应该是 -m standalone

**Comment by KomachiSion** [comment]
try `startup.cmd -m standalone` again
