### ISSUE TITLE
[2.0.0] Server requesting non-exist api `cluster/state` on old version server (e.g. 1.1.3)

### ISSUE THREAD

**Issue by pixystone** [alibaba/nacos#5444]
**Describe the bug**

The api `cluster/state` is not exist on version 1.1.3 or below

```
2021-04-22 10:25:33,226 - WARN - [.naming.timer.2] - NamingProxy

java.io.IOException: failed to req API:http://11.*.*.96:7001/nacos/v1/ns/operator/cluster/state. code:501 msg: {"timestamp":"2021-04-22T02:25:33.226+0000","status":501,"error":"Not Implemented","message":"no such api: GET /nacos/v1/ns/operator/cluster/state","path":"/nacos/v1/ns/operator/cluster/state"}
        at com.alibaba.nacos.naming.misc.NamingProxy.reqCommon(NamingProxy.java:321)
        at com.alibaba.nacos.naming.cluster.ServerListManager$ServerInfoUpdater.run(ServerListManager.java:183)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:186)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:300)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
        at java.lang.Thread.run(Unknown Source)
```

**Expected behavior**

Close the request thread when meet `501` or `404`.

**Acutally behavior**

Requesting and logging errors.

**Additional context**

ServerInfoUpdater

**Comment by JackSun-Developer** [comment]
![image](https://user-images.githubusercontent.com/58767027/115668939-4beb9500-a37a-11eb-93f9-9911520b118f.png)

See this Note, this API is deprecated, If your client version is old, and the server version is 2.0.0, Then the  "failed to req API:" error will be triggered.

**Comment by pixystone** [comment]
This API is added for old raft protocol which is not used by 2.0.x servers.

Close it.
