### ISSUE TITLE
com.alibaba.nacos.api.exception.NacosException: dataId invalid

### ISSUE THREAD

**Issue by dwhgygzt** [alibaba/nacos#5466]
**Describe the bug**
use 2.0.0-bugfix  + org.apache.dubbo 2.7.10 + spring boot 2.3.8

in java code have dubbo consumer config info
```java
    /**
     * 所有分系统
     */
    @Lazy
    @DubboReference(version = "2.0", group = "*", merger = "true")
    protected DataPublishRpcService dataPublishRpcService;

```

when running springboot 
An exception message appears on the console

**Expected behavior**
 running springboot  ok.

**Acutally behavior**
 exception message   like this

```shell
com.alibaba.nacos.api.exception.NacosException: dataId invalid
	at com.alibaba.nacos.client.config.utils.ParamUtils.checkKeyParam(ParamUtils.java:90) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.utils.ParamUtils.checkParam(ParamUtils.java:147) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfigInner(NacosConfigService.java:222) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfig(NacosConfigService.java:121) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfig(NacosConfigService.java:116) ~[nacos-client-1.4.1.jar:na]
	at org.apache.dubbo.metadata.store.nacos.NacosConfigServiceWrapper.publishConfig(NacosConfigServiceWrapper.java:35) ~[dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.storeMetadata(NacosMetadataReport.java:199) [dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.doStoreConsumerMetadata(NacosMetadataReport.java:160) [dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.storeConsumerMetadataTask(AbstractMetadataReport.java:286) [dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.lambda$storeConsumerMetadata$1(AbstractMetadataReport.java:272) [dubbo-2.7.10.jar:2.7.10]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]

2021-04-23 17:49:21.751 ERROR 14656 --- [Report-thread-1] o.a.d.m.store.nacos.NacosMetadataReport  :  [DUBBO] Failed to put consumer metadata org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@e4f9d7a;  {init=false, side=consumer, release=2.7.10, methods=getLogSyncCntByTime,getRealSyncCntByTime, logger=slf4j, dubbo=2.0.2, check=false, interface=com.middol.huizhong.biqsdp.dubbo.DataPublishRpcService, version=2.0, timeout=30000, revision=2.0, retries=0, metadata-type=remote, application=biqs-data-aggregation, sticky=false, merger=true, group=*}, cause: Failed to put org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@e4f9d7a to nacos {"init":"false","side":"consumer","release":"2.7.10","methods":"getLogSyncCntByTime,getRealSyncCntByTime","logger":"slf4j","dubbo":"2.0.2","check":"false","interface":"com.middol.huizhong.biqsdp.dubbo.DataPublishRpcService","version":"2.0","timeout":"30000","revision":"2.0","retries":"0","metadata-type":"remote","application":"biqs-data-aggregation","sticky":"false","merger":"true","group":"*"}, cause: dataId invalid, dubbo version: 2.7.10, current host: 192.168.1.160

org.apache.dubbo.rpc.RpcException: Failed to put org.apache.dubbo.metadata.report.identifier.MetadataIdentifier@e4f9d7a to nacos {"init":"false","side":"consumer","release":"2.7.10","methods":"getLogSyncCntByTime,getRealSyncCntByTime","logger":"slf4j","dubbo":"2.0.2","check":"false","interface":"com.middol.huizhong.biqsdp.dubbo.DataPublishRpcService","version":"2.0","timeout":"30000","revision":"2.0","retries":"0","metadata-type":"remote","application":"biqs-data-aggregation","sticky":"false","merger":"true","group":"*"}, cause: dataId invalid
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.storeMetadata(NacosMetadataReport.java:205) ~[dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.doStoreConsumerMetadata(NacosMetadataReport.java:160) ~[dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.storeConsumerMetadataTask(AbstractMetadataReport.java:286) [dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.metadata.report.support.AbstractMetadataReport.lambda$storeConsumerMetadata$1(AbstractMetadataReport.java:272) [dubbo-2.7.10.jar:2.7.10]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_151]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_151]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_151]
Caused by: com.alibaba.nacos.api.exception.NacosException: dataId invalid
	at com.alibaba.nacos.client.config.utils.ParamUtils.checkKeyParam(ParamUtils.java:90) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.utils.ParamUtils.checkParam(ParamUtils.java:147) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfigInner(NacosConfigService.java:222) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfig(NacosConfigService.java:121) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfig(NacosConfigService.java:116) ~[nacos-client-1.4.1.jar:na]
	at org.apache.dubbo.metadata.store.nacos.NacosConfigServiceWrapper.publishConfig(NacosConfigServiceWrapper.java:35) ~[dubbo-2.7.10.jar:2.7.10]
	at org.apache.dubbo.metadata.store.nacos.NacosMetadataReport.storeMetadata(NacosMetadataReport.java:199) ~[dubbo-2.7.10.jar:2.7.10]
	... 6 common frames omitted
```

**How to Reproduce**
debug find this:

when start spring boot  create dataId  , the dataId  vaue is
"com.middol.huizhong.biqsdp.dubbo.DataPublishRpcService:2.0:*.condition-router"

nacos  ParamUtils  will check
```java
    /**
     * Check key param.
     *
     * @param dataId dataId
     * @param group  group
     * @throws NacosException nacos exception
     */
    public static void checkKeyParam(String dataId, String group) throws NacosException {
        if (StringUtils.isBlank(dataId) || !ParamUtils.isValid(dataId)) {
            throw new NacosException(NacosException.CLIENT_INVALID_PARAM, "dataId invalid");
        }
        if (StringUtils.isBlank(group) || !ParamUtils.isValid(group)) {
            throw new NacosException(NacosException.CLIENT_INVALID_PARAM, "group invalid");
        }
    }

    /**
     * 白名单的方式检查, 合法的参数只能包含字母、数字、以及validChars中的字符, 并且不能为空.
     *
     * @param param parameter
     * @return true if valid
     */
    public static boolean isValid(String param) {
        if (param == null) {
            return false;
        }
        int length = param.length();
        for (int i = 0; i < length; i++) {
            char ch = param.charAt(i);
            if (!Character.isLetterOrDigit(ch) && !isValidChar(ch)) {
                return false;
            }
        }
        return true;
    }

```

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version dubbo 2.7.10  dubbo-registry-nacos 2.7.10
 - Module config
 - SDK JDK1.8

**Comment by JackSun-Developer** [comment]
![image](https://user-images.githubusercontent.com/58767027/115859258-83357100-a462-11eb-9431-138a4097871f.png)
dataId 不能出现除了这几个之外的特殊字符，你的dataId不符合规范。
![image](https://user-images.githubusercontent.com/58767027/115859326-9fd1a900-a462-11eb-8ef4-92c7519ad9e5.png)

**Comment by KomachiSion** [comment]
Why set group `*`？

**Comment by dwhgygzt** [comment]
Dubbo aggregation service   will set  group *

Doesn't Nacos support * yet ？

**Comment by KomachiSion** [comment]
This is dubbo's problem. If dubbo aggression service for any group, dubbo should handle this wildcard.

Nacos use namespace + group + serviceName as the unified tag for service. And * is a invalid char for this unified.

**Comment by dwhgygzt** [comment]
ok thanks
