### ISSUE TITLE
How to skip nacos discovery when run test case locally

### ISSUE THREAD

**Issue by afeiluo** [alibaba/nacos#5490]
When I run testcase using the command blow
```shell
 mvn -Dtest=xxx test -DargLine="-Dspring.cloud.bootstrap.enabled=false"
```
The SpringApplicationContext start with exceptions as blow
```xml
java.io.IOException: Error while requesting: http:///nacos/serverlist'. Server returned: 500
        at com.alibaba.nacos.client.naming.net.NamingProxy.getServerListFromEndpoint(NamingProxy.java:144)
        at com.alibaba.nacos.client.naming.net.NamingProxy.refreshSrvIfNeed(NamingProxy.java:177)
        at com.alibaba.nacos.client.naming.net.NamingProxy.access$000(NamingProxy.java:62)
        at com.alibaba.nacos.client.naming.net.NamingProxy$2.run(NamingProxy.java:120)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
java.io.IOException: Error while requesting: http:/
```
actually I did not need discovery service when I run testcase(use mocking instead)

nacos I used
```xml
<dependency>
    <groupId>com.alibaba.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
    <version>${nacos.config.version}</version> //2.2.1.RELEASE
</dependency>
<dependency>
    <groupId>org.springframework.cloud</groupId>
    <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
    <version>${nacos.discovery.version}</version> //0.9.0.RELEASE
</dependency>
```

**Comment by KomachiSion** [comment]
Please move issue to spring cloud alibaba community
