### ISSUE TITLE
Mac m1 bad

### ISSUE THREAD

**Issue by liaotian1005** [alibaba/nacos#5502]
start nacos project  by  Mac mbpro m1 ,follower information:

rg.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'instanceOperatorClientImpl' defined in URL [jar:file:/Users/ltz/software/repository/com/pig4cloud/nacos/nacos-naming/2.0.0.RELEASE/nacos-naming-2.0.0.RELEASE.jar!/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientOperationServiceProxy' defined in URL [jar:file:/Users/ltz/software/repository/com/pig4cloud/nacos/nacos-naming/2.0.0.RELEASE/nacos-naming-2.0.0.RELEASE.jar!/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/Users/ltz/software/repository/com/pig4cloud/nacos/nacos-naming/2.0.0.RELEASE/nacos-naming-2.0.0.RELEASE.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/48/2lrwxp_92bsg1k13v2vrjpdh0000gn/T/librocksdbjni7157681814585662109.jnilib: dlopen(/private/var/folders/48/2lrwxp_92bsg1k13v2vrjpdh0000gn/T/librocksdbjni7157681814585662109.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/48/2lrwxp_92bsg1k13v2vrjpdh0000gn/T/librocksdbjni7157681814585662109.jnilib: mach-o, but wrong architecture
	/private/var/folders/48/2lrwxp_92bsg1k13v2vrjpdh0000gn/T/librocksdbjni7157681814585662109.jnilib: mach-o, but wrong architecture
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1354)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1204)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:564)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:524)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:782)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:774)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:439)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1340)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329)
	at com.alibaba.nacos.PigNacosApplication.main(PigNacosApplication.java:39)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/Users/ltz/software/repository/com/pig4cloud/nacos/nacos-naming/2.0.0.RELEASE/nacos-naming-2.0.0.RELEASE.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/48/2lrwxp_92bsg1k13v2vrjpdh0000gn/T/librocksdbjni7157681814585662109.jnilib: dlopen(/private/var/folders/48/2lrwxp_92bsg1k13v2vrjpdh0000gn/T/librocksdbjni7157681814585662109.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/48/2lrwxp_92bsg1k13v2vrjpdh0000gn/T/librocksdbjni7157681814585662109.jnilib: mach-o, but wrong architecture
	/private/var/folders/48/2lrwxp_92bsg1k13v2vrjpdh0000gn/T/librocksdbjni7157681814585662109.jnilib: mach-o, but wrong architecture

```
<properties>
		<nacos.version>2.0.0.RELEASE</nacos.version>
	</properties>

	<dependencies>
		<dependency>
			<groupId>com.pig4cloud.nacos</groupId>
			<artifactId>nacos-config</artifactId>
			<version>${nacos.version}</version>
		</dependency>
		<dependency>
			<groupId>org.apache.tomcat.embed</groupId>
			<artifactId>tomcat-embed-jasper</artifactId>
		</dependency>

		<dependency>
			<groupId>com.pig4cloud.nacos</groupId>
			<artifactId>nacos-naming</artifactId>
			<version>${nacos.version}</version>
		</dependency>

		<dependency>
			<groupId>com.pig4cloud.nacos</groupId>
			<artifactId>nacos-istio</artifactId>
			<version>${nacos.version}</version>
		</dependency>
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter-security</artifactId>
		</dependency>

		<dependency>
			<groupId>cn.hutool</groupId>
			<artifactId>hutool-system</artifactId>
			<version>${hutool.version}</version>
		</dependency>
	</dependencies>

```

**Comment by KomachiSion** [comment]
duplicate with #4336
