### ISSUE TITLE
DuplicateKeyException

### ISSUE THREAD

**Issue by yankunsam** [alibaba/nacos#5504]
**Describe the bug**
Here is the message from ARMS:

org.springframework.dao.DuplicateKeyException

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:247)

	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)

	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)

	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)

	at org.springframework.jdbc.core.JdbcTemplate.update(JdbcTemplate.java:893)

	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.addConfigInfoAtomic(ExternalStoragePersistServiceImpl.java:1963)

	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.lambda$addConfigInfo$0(ExternalStoragePersistServiceImpl.java:184)

	at org.springframework.transaction.support.TransactionTemplate.execute(TransactionTemplate.java:140)

	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.addConfigInfo(ExternalStoragePersistServiceImpl.java:182)

**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [ nacos-server 1.4.0, nacos-client 1.3.1]
 
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by JackSun-Developer** [comment]
> at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.addConfigInfo(ExternalStoragePersistServiceImpl.java:182)

 I think there may be something wrong with your Database.

You can use ** bash startup.sh -p embedded** to use embedded database, or configure your application about the **db.num** **db.url** , etc, fields.

**Comment by yankunsam** [comment]
The dabase is provided by nacos, the image is "nacos-mysql:5.7".

**Comment by JackSun-Developer** [comment]
@yankunsam  
First check the connection of each nacos pod to each other.

You can follow the document nacos.io, and the following two templates to deploy your nacos group, nacos will start successfully, unless your k8s or docker is not configured correctly.
> https://github.com/nacos-group/nacos-k8s
> https://github.com/nacos-group/nacos-docker

**Comment by yankunsam** [comment]
> @yankunsam
> First check the connection of each nacos pod to each other.
> 
> You can follow the document nacos.io, and the following two templates to deploy your nacos group, nacos will start successfully, unless your k8s or docker is not configured correctly.
> 
> > https://github.com/nacos-group/nacos-k8s
> > https://github.com/nacos-group/nacos-docker

Case By Case,站在上帝视角回答问题有意思吗？

**Comment by yankunsam** [comment]
> @yankunsam
> First check the connection of each nacos pod to each other.
> 
> You can follow the document nacos.io, and the following two templates to deploy your nacos group, nacos will start successfully, unless your k8s or docker is not configured correctly.
> 
> > https://github.com/nacos-group/nacos-k8s
> > https://github.com/nacos-group/nacos-docker

Case By Case,站在上帝视角回答问题有意思吗？

**Comment by JackSun-Developer** [comment]
> > @yankunsam
> > First check the connection of each nacos pod to each other.
> > You can follow the document nacos.io, and the following two templates to deploy your nacos group, nacos will start successfully, unless your k8s or docker is not configured correctly.
> > > https://github.com/nacos-group/nacos-k8s
> > > https://github.com/nacos-group/nacos-docker
> 
> Case By Case,站在上帝视角回答问题有意思吗？

Could you provide more logs, the logs is too short to locate where the problem is...
But most of the problem root in the wrong configuration, so I asked you to recheck them.

**Comment by KomachiSion** [comment]
DuplicateKeyException means your primary or unified key is duplicated.

I think you should check whether your public config duplicately.
