### ISSUE TITLE
ErrCode:-400,ErrMsg:null  when no logger dependency in classpath

### ISSUE THREAD

**Issue by CarpenterLee** [alibaba/nacos#551]
# Reporting bugs

Nacos will raise a NPE when no logger dependency in the class path or pom, which will cause nacos init fail. And the exception stack is as flowing:
```
ErrCode:-400,ErrMsg:null
	at com.alibaba.nacos.api.config.ConfigFactory.createConfigService(ConfigFactory.java:45)
	at com.alibaba.nacos.api.NacosFactory.createConfigService(NacosFactory.java:41)
        .......
```
The root cause if a NPE in the following code: 

```java
public static ConfigService createConfigService(Properties properties) throws NacosException {
    try {
        Class<?> driverImplClass = Class.forName("com.alibaba.nacos.client.config.NacosConfigService");
        Constructor constructor = driverImplClass.getConstructor(Properties.class);
        ConfigService vendorImpl = (ConfigService)constructor.newInstance(properties); // NPE 
        return vendorImpl;
    } catch (Throwable e) {
        throw new NacosException(-400, e.getMessage()); // exception e is dropped.
    }
}
```
When I debug into the code, I found the real `Throwable e` is 
```
Caused by: java.lang.ExceptionInInitializerError
	at com.alibaba.nacos.client.logger.util.MessageFormatter.arrayFormat(MessageFormatter.java:210)
	at com.alibaba.nacos.client.logger.util.MessageUtil.formatMessage(MessageUtil.java:26)
	at com.alibaba.nacos.client.logger.log4j2.Log4j2Logger.info(Log4j2Logger.java:72)
	at com.alibaba.nacos.client.utils.ParamUtil.<clinit>(ParamUtil.java:52)
	at com.alibaba.nacos.client.config.impl.ServerListManager.<init>(ServerListManager.java:360)
	at com.alibaba.nacos.client.config.impl.ServerHttpAgent.<init>(ServerHttpAgent.java:228)
	at com.alibaba.nacos.client.config.NacosConfigService.<init>(NacosConfigService.java:82)
	... 16 more
Caused by: java.lang.NullPointerException
	at com.alibaba.nacos.client.logger.util.FormattingTuple.<init>(FormattingTuple.java:39)
	at com.alibaba.nacos.client.logger.util.FormattingTuple.<init>(FormattingTuple.java:32)
	at com.alibaba.nacos.client.logger.util.FormattingTuple.<clinit>(FormattingTuple.java:25)
	... 23 more
```

After I add log4j2 dependency, the code works fine.

## Environment
```xml
<dependency>
    <groupId>com.alibaba.nacos</groupId>
    <artifactId>nacos-client</artifactId>
    <version>0.6.2</version>
</dependency>
```

**Comment by hyw520110** [comment]
It's also possible that guava's dependency conflicts lead to it. add guava  dependency:
<dependency>
	 		<groupId>com.google.guava</groupId>
	 		<artifactId>guava</artifactId>
	 		<version>19.0</version>
	 	</dependency>
