### ISSUE TITLE
Question consultation

### ISSUE THREAD

**Issue by duibu** [alibaba/nacos#5542]
Whether nacos supports compiling war packages and deploying them

**Comment by JackSun-Developer** [comment]
No, Nacos do not recommend mixed deployment through war package and other applications.

**Comment by KomachiSion** [comment]
You can compliling war packages by yourself. Community will not provider war version.

**Comment by SamaDream** [comment]
> > 不，Nacos 不建议通过war 包和其他应用程序混合部署。
> 
> 业务场景不允许jar部署，有没有建议，谢谢

你好，目前碰到了同样的问题，请问您解决了吗？如果解决的话，是否方便提供下源码呢。

**Comment by mvpbang** [comment]
war构建的步骤，不太清楚，只能干瞪眼

**Comment by dingmingyang** [comment]
我下载源码打成了war包。部署在类tomcat容器tongweb中，nacos的管理页面什么的都什么问题，但是server端一直有个错：
[2023-08-24 18:12:18 254] [WARNING] [nacos-grpc-executor-184] [systemout] [Exception in thread "nacos-grpc-executor-184" ]
[2023-08-24 18:12:18 256] [WARNING] [nacos-grpc-executor-184] [systemout] [java.lang.NoSuchMethodError: com.alibaba.nacos.api.grpc.auto.Payload$Builder.setBody(Lcom/alibaba/nacos/shaded/com/google/protobuf/Any$Builder;)Lcom/alibaba/nacos/api/grpc/auto/Payload$Builder;]
[2023-08-24 18:12:18 256] [WARNING] [nacos-grpc-executor-184] [systemout] [     at com.alibaba.nacos.common.remote.client.grpc.GrpcUtils.convert(GrpcUtils.java:103)]
[2023-08-24 18:12:18 257] [WARNING] [nacos-grpc-executor-184] [systemout] [     at com.alibaba.nacos.core.remote.grpc.GrpcRequestAcceptor.request(GrpcRequestAcceptor.java:91)]
[2023-08-24 18:12:18 257] [WARNING] [nacos-grpc-executor-184] [systemout] [     at com.alibaba.nacos.core.remote.grpc.BaseGrpcServer.lambda$addServices$0(BaseGrpcServer.java:176)]
[2023-08-24 18:12:18 257] [WARNING] [nacos-grpc-executor-184] [systemout] [     at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)]
[2023-08-24 18:12:18 257] [WARNING] [nacos-grpc-executor-184] [systemout] [     at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)]
[2023-08-24 18:12:18 257] [WARNING] [nacos-grpc-executor-184] [systemout] [     at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)]
[2023-08-24 18:12:18 257] [WARNING] [nacos-grpc-executor-184] [systemout] [     at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)]
[2023-08-24 18:12:18 257] [WARNING] [nacos-grpc-executor-184] [systemout] [     at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)]
[2023-08-24 18:12:18 257] [WARNING] [nacos-grpc-executor-184] [systemout] [     at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)]
[2023-08-24 18:12:18 257] [WARNING] [nacos-grpc-executor-184] [systemout] [     at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:820)]
[2023-08-24 18:12:18 258] [WARNING] [nacos-grpc-executor-184] [systemout] [     at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)]
[2023-08-24 18:12:18 258] [WARNING] [nacos-grpc-executor-184] [systemout] [     at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)]
[2023-08-24 18:12:18 258] [WARNING] [nacos-grpc-executor-184] [systemout] [     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)]
[2023-08-24 18:12:18 258] [WARNING] [nacos-grpc-executor-184] [systemout] [     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)]
[2023-08-24 18:12:18 258] [WARNING] [nacos-grpc-executor-184] [systemout] [     at java.lang.Thread.run(Thread.java:748)]



客户端注册时候一直报
ERROR 36476 --- [t.remote.worker] c.a.n.c.remote.client.grpc.GrpcClient    : Server check fail, please check server 192.168.200.142 ,port 9848 is available , error ={}

java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNKNOWN

应该是grpc通讯的问题。也找不到原因
