### ISSUE TITLE
用open API 查询实例详情时如果不存在，则会抛出status code: 500 异常

### ISSUE THREAD

**Issue by jiangguilong2000** [alibaba/nacos#5823]
如果不存在服务的相关信息，客户端会收到500的HTTP errrorcode :
```
2021-05-23 15:41:02.803 ERROR [main][PlatformClient.java:322] - status code: 500
org.apache.http.client.HttpResponseException: status code: 500
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70) ~[httpclient-4.5.13.jar:4.5.13]
	at org.apache.http.client.fluent.Response.handleResponse(Response.java:90) ~[fluent-hc-4.5.13.jar:4.5.13]
	at org.apache.http.client.fluent.Response.returnContent(Response.java:97) ~[fluent-hc-4.5.13.jar:4.5.13]
```

预期应该是返回空的信息，HTTP 状态应该还是200，不应该提示500 服务器内部错误，查看了nacos服务器端，
```
com.alibaba.nacos.api.exception.NacosException: no ips found for cluster DEFAULT in service game@@1-10018-1-6
        at com.alibaba.nacos.naming.core.InstanceOperatorClientImpl.getInstance0(InstanceOperatorClientImpl.java:196)
        at com.alibaba.nacos.naming.core.InstanceOperatorClientImpl.getInstance(InstanceOperatorClientImpl.java:189)
        at com.alibaba.nacos.naming.controllers.InstanceController.detail(InstanceController.java:336)
```

查看了代码：
原来是当服务为空时就会抛出该异常：
```
  private Instance getInstance0(Service service, String cluster, String ip, int port) throws NacosException {
    ServiceInfo serviceInfo = this.serviceStorage.getData(service);
    if (serviceInfo.getHosts().isEmpty())//进到了这个判断
      throw new NacosException(404, "no ips found for cluster " + cluster + " in service " + service
          .getGroupedServiceName()); 
    for (Instance each : serviceInfo.getHosts()) {
      if (cluster.equals(each.getClusterName()) && ip.equals(each.getIp()) && port == each.getPort())
        return each; 
    } 
    throw new NacosException(404, "no matched ip found!");
  }
```
求官方鉴定！

**Comment by jiangguilong2000** [comment]
![image](https://user-images.githubusercontent.com/5009933/119252454-e7bd2a80-bbde-11eb-985f-85eea6137187.png)

**Comment by JackSun-Developer** [comment]
用户在查询实例详情时，默认应该是希望service存在的；如果service都不存在的基础上就查询instance的信息，违反了查询的先验条件，个人认为不应该抛出200正常返回。

而在另一种场景下：用户希望查询某个service下有多少实例，这种情况下如果service不存在，查询的主体为空，但没有先验条件的缺失，这种可以返回200+空对象。

**Comment by KomachiSion** [comment]
查询实例详情，但是服务下面是空实例列表，也就意味着实例肯定是不存在的。客户端返回404没有问题。

只是这个404是封装在Nacos的异常里面，httpclient无法识别到，只识别到了异常，所以表面信息看到的是500。
