### ISSUE TITLE
客户端报错 code:500 msg: java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by woshishitou** [alibaba/nacos#5853]
## Issue Description

Type: *bug report* or *feature request*

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3. 

### Tell us your environment
客户端nacos-client1.0.0
服务端nacos-server2.0.1

### Anything else we need to know?
1、我们使用了 “域名+SLB” 模式搭建了三个节点的集群，集群状态正常，一主两从
2、我们的应用分布在n台服务器上，只有一台服务器上的应用（全部三个应用都报）报这个错，其他服务器上的应用都没有报这个错
3、包括报错的应用在内，所有的服务都在nacos的服务列表可以看到，而且状态都是正常的
4、我知道客户端和服务端版本存在一定的不匹配，但比较奇怪为什么只有一台服务器上的应用会报错

**Comment by woshishitou** [comment]
2021-05-26 09:55:06.453 ERROR [com.alibaba.nacos.naming.beat.sender][NamingProxy.java:370] - request nacos.work.com:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://nacos.work.com:8848/nacos/v1/ns/instance/beat. code:500 msg: java.net.SocketTimeoutException: connect timed out
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340) ~[nacos-client-1.0.0.jar!/:?]        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) [nacos-client-1.0.0.jar!/:?]        at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:227) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:109) [nacos-client-1.0.0.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
2021-05-26 09:55:06.453 ERROR [com.alibaba.nacos.naming.beat.sender][NamingProxy.java:234] - [CLIENT-BEAT] failed to send beat: {"cluster":"DEFAULT","ip":"172.21.16.7","metadata":{"preserved.register.source":"SPRING_CLOUD"},"port":8600,"scheduled":true,"serviceName":"DEFAULT_GROUP@@boss","weight":1.0}
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([nacos.work.com:8848]) tried: failed to req API:http://nacos.work.com:8848/nacos/v1/ns/instance/beat. code:500 msg: java.net.SocketTimeoutException: connect timed out
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:227) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:109) [nacos-client-1.0.0.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]



2021-05-26 09:48:25.442 ERROR [com.alibaba.nacos.client.naming.updater][NamingProxy.java:370] - request nacos.work.com:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://nacos.work.com:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318) [nacos-client-1.0.0.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
2021-05-26 09:48:25.442 ERROR [com.alibaba.nacos.client.naming.updater][HostReactor.java:278] - [NA] failed to update serviceName: DEFAULT_GROUP@@system
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([nacos.work.com:8848]) tried: failed to req API:http://nacos.work.com:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318) [nacos-client-1.0.0.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]

**Comment by woshishitou** [comment]
网络和端口都是通的

**Comment by woshishitou** [comment]
`2021-05-26 09:55:06.453 ERROR [com.alibaba.nacos.naming.beat.sender][NamingProxy.java:370] - request nacos.work.com:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://nacos.work.com:8848/nacos/v1/ns/instance/beat. code:500 msg: java.net.SocketTimeoutException: connect timed out
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340) ~[nacos-client-1.0.0.jar!/:?]        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) [nacos-client-1.0.0.jar!/:?]        at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:227) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:109) [nacos-client-1.0.0.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
2021-05-26 09:55:06.453 ERROR [com.alibaba.nacos.naming.beat.sender][NamingProxy.java:234] - [CLIENT-BEAT] failed to send beat: {"cluster":"DEFAULT","ip":"172.21.16.7","metadata":{"preserved.register.source":"SPRING_CLOUD"},"port":8600,"scheduled":true,"serviceName":"DEFAULT_GROUP@@boss","weight":1.0}
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([nacos.work.com:8848]) tried: failed to req API:http://nacos.work.com:8848/nacos/v1/ns/instance/beat. code:500 msg: java.net.SocketTimeoutException: connect timed out
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:227) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:109) [nacos-client-1.0.0.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]



2021-05-26 09:48:25.442 ERROR [com.alibaba.nacos.client.naming.updater][NamingProxy.java:370] - request nacos.work.com:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://nacos.work.com:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318) [nacos-client-1.0.0.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
2021-05-26 09:48:25.442 ERROR [com.alibaba.nacos.client.naming.updater][HostReactor.java:278] - [NA] failed to update serviceName: DEFAULT_GROUP@@system
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([nacos.work.com:8848]) tried: failed to req API:http://nacos.work.com:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:380) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217) ~[nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273) [nacos-client-1.0.0.jar!/:?]
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318) [nacos-client-1.0.0.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_211]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_211]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_211]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_211]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_211]
`

**Comment by woshishitou** [comment]
对了，这样的错误一直在报，不是偶现的

**Comment by KomachiSion** [comment]
升级SLB，SLB会拦截和丢弃掉所有QPS超过阈值的请求。现象就是客户端一直连接超时。

**Comment by anryHan** [comment]
> 对了，这样的错误一直在报，不是偶现的

客户端为什么不升级到2.0.1呢？

**Comment by woshishitou** [comment]
> 升级SLB，SLB会拦截和丢弃掉所有QPS超过阈值的请求。现象就是客户端一直连接超时。

我们用的是腾讯云的slb，没看出来什么拦截和丢弃，而且感觉slb拦截丢弃的话，应该也不会只对一台机器上的请求起作用。
目前我通过抓包排查到，是SYN超时导致的连接超时，但SYN已经从问题机器发出去了，腾讯云slb那里我们也抓不了包，无法知道后续情况。
谢谢您的回复，您关闭这个issue吧，我们升级下client到2.0.1，没有那么多连接了，问题应该不会出现了。

**Comment by woshishitou** [comment]
> > 对了，这样的错误一直在报，不是偶现的
> 
> 客户端为什么不升级到2.0.1呢？

好几个项目，升级比较麻烦，而且想研究下这个问题，所以暂时没升级。不过现在只有升级了。

**Comment by KomachiSion** [comment]
> > 升级SLB，SLB会拦截和丢弃掉所有QPS超过阈值的请求。现象就是客户端一直连接超时。
> 
> 我们用的是腾讯云的slb，没看出来什么拦截和丢弃，而且感觉slb拦截丢弃的话，应该也不会只对一台机器上的请求起作用。
> 目前我通过抓包排查到，是SYN超时导致的连接超时，但SYN已经从问题机器发出去了，腾讯云slb那里我们也抓不了包，无法知道后续情况。
> 谢谢您的回复，您关闭这个issue吧，我们升级下client到2.0.1，没有那么多连接了，问题应该不会出现了。

SLB 都一样的 会对连接数，每秒创建连接数及HTTP Request的TPS进行限流，只要有一个超过了，新的SYN包会直接丢掉，不会有任何响应。 因为包直接丢弃了，所以nacos服务端根本就没有收到这个连接建立请求，更不会回http response。

客户端一直没收到ACK包，所以就连接超时了。

解决办法就是升级到2.X版本，不再使用http。或者升级SLB，提高TPS限流，让他不丢包。

**Comment by zhaijingrong** [comment]
你好，我们也是遇到同样的问题，请问你们解决了。或者说你们升级Nacos client版本到2.0之后解决了吗？🙏

**Comment by yinhang-fs** [comment]
你好，我们也是遇到同样的问题，请问你们解决了。或者说你们升级Nacos client版本到2.0之后解决了吗？🙏

**Comment by woshishitou** [comment]
> 你好，我们也是遇到同样的问题，请问你们解决了。或者说你们升级Nacos client版本到2.0之后解决了吗？🙏

我们当时尝试升级客户端，但遇到了https://github.com/alibaba/nacos/issues/5935这个问题，然后我尝试用maven的shade解决，但打出的包里多了一些奇怪的东西，后来别的事忙，没时间仔细研究了，就暂时搁置了。
对了，这个issue里提到的超时问题，虽然我们现在还是在一直报错，但好像并不影响使用。
你们那边有什么进展吗？

**Comment by woshishitou** [comment]
> 你好，我们也是遇到同样的问题，请问你们解决了。或者说你们升级Nacos client版本到2.0之后解决了吗？🙏

你好，回复见上面

**Comment by yinhang-fs** [comment]
@woshishitou 我们也是一直没有解决掉，一直报错，但并不影响使用
