### ISSUE TITLE
Return error Optional[Distro protocol is not initialized] when server start

### ISSUE THREAD

**Issue by ToBeIronMan** [alibaba/nacos#5920]
![image](https://user-images.githubusercontent.com/53281822/120304268-39159a00-c302-11eb-95fb-356c49e3c315.png)
sometimes can register on  nacos ,but ofen canot
`2021-06-01 09:57:18.633 ERROR 1 --- [TaskScheduler-1] o.s.c.a.nacos.discovery.NacosWatch       : Error watching Nacos Service change
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([192.168.31.80:30048]) tried: failed to req API:192.168.31.80:30048/nacos/v1/ns/service/list. code:503 msg: server is DOWNnow, detailed error message: Optional[Distro protocol is not initialized]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:464) ~[nacos-client-1.1.0.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:430) ~[nacos-client-1.1.0.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:376) ~[nacos-client-1.1.0.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:358) ~[nacos-client-1.1.0.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:334) ~[nacos-client-1.1.0.jar!/:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:440) ~[nacos-client-1.1.0.jar!/:na]
	at org.springframework.cloud.alibaba.nacos.discovery.NacosWatch.nacosServicesWatch(NacosWatch.java:127) ~[spring-cloud-alibaba-nacos-discovery-0.2.2.RELEASE.jar!/:0.2.2.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.0.8.RELEASE.jar!/:5.0.8.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) ~[na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]`

**Comment by JackSun-Developer** [comment]
This problem may be caused by incorrect setting. In application.properties, set

> nacos.naming.data.warmup=false

Then this problem will not occur, and nacos work correctly.

**Comment by JackSun-Developer** [comment]
@ToBeIronMan Did you start nacos in standalone mode or cluster mode?

**Comment by KomachiSion** [comment]
No more response from author.

**Comment by xigpz** [comment]
> This problem may be caused by incorrect setting. In application.properties, set
> 
> > nacos.naming.data.warmup=false
> 
> Then retry.
为什么呢，这个参数在windows集群下是正常有效的，但是这个是长期报错的，这个设置只是避开了数据预热阶段报错，但这不是本质的解决吧
