### ISSUE TITLE
The log of the master node keeps reporting exceptions： I/O reactor status: STOPPED

### ISSUE THREAD

**Issue by syapollo** [alibaba/nacos#5931]
**Describe the bug**
2021-06-03 00:00:03,635 ERROR failed to req API:http://XXXX:XX/nacos/v1/ns/distro/checksum

java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
        at com.alibaba.nacos.common.http.client.request.DefaultAsyncHttpClientRequest.execute(DefaultAsyncHttpClientRequest.java:52)
        at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.execute(NacosAsyncRestTemplate.java:364)
        at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.put(NacosAsyncRestTemplate.java:147)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpPutLarge(HttpClient.java:296)
        at com.alibaba.nacos.naming.misc.NamingProxy.syncCheckSums(NamingProxy.java:75)
        at com.alibaba.nacos.naming.consistency.ephemeral.distro.component.DistroHttpAgent.syncVerifyData(DistroHttpAgent.java:64)
        at com.alibaba.nacos.core.distributed.distro.task.verify.DistroVerifyTask.verifyForDataStorage(DistroVerifyTask.java:67)
        at com.alibaba.nacos.core.distributed.distro.task.verify.DistroVerifyTask.run(DistroVerifyTask.java:52)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

**Desktop (please complete the following information):**

 - Version [e.g. nacos-server 1.4.1, nacos-client 1.4.1]

**Additional context**
The current function seems to be all normal, I don’t know if there will be any impact in a while

**Comment by KomachiSion** [comment]
The exception is http client throw out.
Please check network environment by yourself. And check the server run status by yourself.

**Comment by KomachiSion** [comment]
Maybe duplicate with #5905

**Comment by syapollo** [comment]
> The exception is http client throw out.
> Please check network environment by yourself. And check the server run status by yourself.

I can see that the service is normal through /operator/servers, and there is no problem with my registration service and get configuration, that is, the background keeps reporting errors，I'm not sure what the impact of this distro module's error report will be. Can I restart the process?

**Comment by KomachiSion** [comment]
I have no idea about your environments, so you need to check and research by yourself. 

The exception is throw by http client, which means that the connection has close and still want to do new request.

**Comment by KANLON** [comment]
应该是关联 这个 issue 的 ，https://github.com/alibaba/nacos/issues/6367  这里记录一下，因为Google 出来的结果是这个，以免后面找不到原因
