### ISSUE TITLE
nacos1.4.1 provider实例down掉但是nacos并没有下线该节点的某个service

### ISSUE THREAD

**Issue by hakiGithub** [alibaba/nacos#5955]
**Describe the bug**
这边发现 provider实例每次因为k8s下线后，nacos并没有下线对应provider实例，导致consumer一直会找不到对应的provider
除此之外 只有provider中的实例中某个service会有以上这种情况，该实例的其余service并没有这种情况
![provider实例异常](https://user-images.githubusercontent.com/37412226/120798248-aa0db980-c56f-11eb-90bb-232f4ec26b17.png)

**How to Reproduce**
每次上下线该provider实例节点都会复现。
但是暂无复现nacos 服务端的方法

**Desktop (please complete the following information):**
 - Version [nacos-server 1.4.1, nacos-client 1.2.1]
 - SDK: [nacos-config-spring-boot-starter 0.2.1]
 - Deployment-Type: [k8s]

**Additional context**
除此之外，发现nacos3个节点 有个节点的时间戳出现异常
![异常的时间戳](https://user-images.githubusercontent.com/37412226/120798764-6d8e8d80-c570-11eb-9169-99829585a5fa.png)

但是刷新之后，出现异常时间戳的节点变成另外一个
![另外一个节点出现异常的时间戳](https://user-images.githubusercontent.com/37412226/120798791-75e6c880-c570-11eb-96e6-59676a906aa2.png)

**Comment by KomachiSion** [comment]
推测是distro的责任节点计算有问题，看一下naming-server.log和naming-distro.log有没有一些报错

**Comment by hakiGithub** [comment]
由于升级1.4.2的版本就没再出现这个问题了..而且之前的日志也丢了。所以暂且关闭该issuse先把

**Comment by hakiGithub** [comment]
三个节点其中一个节点的
`naming-distro.log`文件
显示下列的错误,一直在抛出该异常

```
2021-07-04 00:00:01,336 ERROR failed to req API:http://nacos-0.nacos-headless.prod.svc.cluster.local:8848/nacos/v1/ns/distro/checksum

java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at org.apache.http.util.Asserts.check(Asserts.java:46)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
        ....
```

而`naming-server.log`文件在某个服务节点下线后旧出现下列的异常了

```
2021-07-04 01:38:03,193 INFO [AUTO-DELETE-IP] service: DEFAULT_GROUP@@providers:com.baturu.pq.service.sms.SmsMessageService:1.0.0:, ip: {"instanceId":"172.20.0.150#20830#DEFAULT#DEFAULT_GROUP@@providers:com.baturu.pq.service.sms.SmsMessageService:1.0.0:","ip":"172.20.0.150","port":20830,"weight":1.0,"healthy":false,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.baturu.pq.service.sms.SmsMessageService:1.0.0:","metadata":{"side":"provider","methods":"getVerifyCode,sendVerifyCode","release":"2.7.7","deprecated":"false","dubbo":"2.0.2","loadbalance":"roundrobin","pid":"20","interface":"com.baturu.pq.service.sms.SmsMessageService","version":"1.0.0","generic":"false","timeout":"6000","revision":"1.2.2_addPriceOf4sAndPartsCodeRemark-RELEASE","path":"com.baturu.pq.service.sms.SmsMessageService","protocol":"dubbo","application":"btr-pq-gateway","dynamic":"true","service.filter":"ProviderCatLogFilter,default,tlogDubboFilter","category":"providers","anyhost":"true","timestamp":"1625333466248"},"lastBeat":1625333851555,"marked":false,"app":"unknown","instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}

2021-07-04 01:38:03,195 ERROR [IP-DEAD] failed to delete ip automatically, ip: {"instanceId":"172.20.0.150#20830#DEFAULT#DEFAULT_GROUP@@providers:com.baturu.pq.service.sms.SmsMessageService:1.0.0:","ip":"172.20.0.150","port":20830,"weight":1.0,"healthy":false,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@providers:com.baturu.pq.service.sms.SmsMessageService:1.0.0:","metadata":{"side":"provider","methods":"getVerifyCode,sendVerifyCode","release":"2.7.7","deprecated":"false","dubbo":"2.0.2","loadbalance":"roundrobin","pid":"20","interface":"com.baturu.pq.service.sms.SmsMessageService","version":"1.0.0","generic":"false","timeout":"6000","revision":"1.2.2_addPriceOf4sAndPartsCodeRemark-RELEASE","path":"com.baturu.pq.service.sms.SmsMessageService","protocol":"dubbo","application":"btr-pq-gateway","dynamic":"true","service.filter":"ProviderCatLogFilter,default,tlogDubboFilter","category":"providers","anyhost":"true","timestamp":"1625333466248"},"lastBeat":1625333851555,"marked":false,"app":"unknown","instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}, error: {}
```

**Comment by wangzhenxyz1** [comment]
142集群，集群状态正常，但下线的服务一直在，不能正常下线，只能重启集群

**Comment by shaohaikkk** [comment]
> 142集群，集群状态正常，但下线的服务一直在，不能正常下线，只能重启集群
> java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
> at org.apache.http.util.Asserts.check(Asserts.java:46)
> at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)

我是2.0.1  版本，也出现了这个问题，好像如果是对等网络就没事，虚拟后的网络就存在问题

**Comment by wangzhenxyz1** [comment]
2.0.3应该修复了，1.4.x还没修复

**Comment by wushengju** [comment]
遇到了相同的问题，目前还没有啥解决办法，1.4.x版本

**Comment by shaohaikkk** [comment]
官方回复我说是使用的问题，但是按照我的经验来说肯定不是使用的问题，程序机制上应该存在某种bug，看好多同学都遇到了，我们现在是临时下线了那个实例



***@***.***
 
发件人： wushengju
发送时间： 2021-08-25 15:56
收件人： alibaba/nacos
抄送： zero; Comment
主题： Re: [alibaba/nacos] nacos1.4.1 provider实例down掉但是nacos并没有下线该节点的某个service (#5955)
遇到了相同的问题，目前还没有啥解决办法，1.4.x版本
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by naturezhm** [comment]
我这边也遇到完全相同问题，nacos版本也是1.4.1 
naming-server.log很多报错 ：
`2021-08-31 15:58:10,923 ERROR [IP-DEAD] failed to delete ip automatically, ip: {"instanceId":"172.19.5.26 .... }
java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
	at org.apache.http.util.Asserts.check(Asserts.java:46)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
	at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
	at com.alibaba.nacos.common.http.client.request.DefaultAsyncHttpClientRequest.execute(DefaultAsyncHttpClientRequest.java:52)
	at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.execute(NacosAsyncRestTemplate.java:364)
	at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.delete(NacosAsyncRestTemplate.java:105)
	at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpRequest(HttpClient.java:195)
	at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpDelete(HttpClient.java:159)
	at com.alibaba.nacos.naming.healthcheck.ClientBeatCheckTask.deleteIp(ClientBeatCheckTask.java:144)
	at com.alibaba.nacos.naming.healthcheck.ClientBeatCheckTask.run(ClientBeatCheckTask.java:122)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by lfift** [comment]
这个问题有办法解决吗，我这边不是容器网络，而且各个服务器之间的网络都是没问题的，时间也是一致的但是在leader节点就一直报这个错

**Comment by shaohaikkk** [comment]
nacos 操作界面手动下线点那个有问题的实例



***@***.***
 
发件人： lfift
发送时间： 2021-09-02 10:22
收件人： alibaba/nacos
抄送： zero; Comment
主题： Re: [alibaba/nacos] nacos1.4.1 provider实例down掉但是nacos并没有下线该节点的某个service (#5955)
这个问题有办法解决吗，我这边不是容器网络，而且各个服务器之间的网络都是没问题的，时间也是一致的但是在leader节点就一直报这个错
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
