### ISSUE TITLE
Dubbo服务注册不支持通配符*

### ISSUE THREAD

**Issue by yakecanlee** [alibaba/nacos#598]
## 描述
dubbo消费者定义服务版本为*,注册到Nacos时一直失败,Nacos输出错误日志.Dubbo在2.2.0版本就支持通配符了,请问Nacos目前是还不支持吗?
```java
@Reference(version = "*")
private UserService userService;
```
### 消费者错误信息:
```java
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:267) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:167) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:170) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry$2.callback(NacosRegistry.java:148) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:460) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:146) ~[dubbo-registry-nacos-0.0.2.jar:0.0.2]
	at com.alibaba.dubbo.registry.support.FailbackRegistry.retry(FailbackRegistry.java:315) ~[dubbo-2.6.2.jar:2.6.2]
	at com.alibaba.dubbo.registry.support.FailbackRegistry$1.run(FailbackRegistry.java:68) [dubbo-2.6.2.jar:2.6.2]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_162]
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_162]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_162]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_162]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_162]
```

### Nacos错误信息:
```java
2019-01-09 17:02:21,431 WARN Resolved [com.alibaba.nacos.naming.exception.NacosException: dom not found: providers:com.xxx.UserService:*]

2019-01-09 17:02:22,281 WARN Resolved [java.lang.IllegalArgumentException: dom name can only have these characters: 0-9a-zA-Z.:_-; current: consumers:com.xxx.UserService:*]
```

**Comment by hxy1991** [comment]
目前暂不支持，计划是 1.0 支持。

**Comment by nkorange** [comment]
Version * is not supported in Dubbo, neither does Nacos.
