### ISSUE TITLE
req api:/nacos/v1/ns/api/srvIPXT failed, server(127.0.0.1:8848

### ISSUE THREAD

**Issue by coolsnow77** [alibaba/nacos#605]
错误log如下， （使用nacos 版本0.7， jdk8, nacos 单机模式运行)
2019-01-10 14:15:13.517 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [] [] [NA] req api:/nacos/v1/ns/api/srvIPXT failed, server(127.0.0.1:8848
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:320)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:343)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:326)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-01-10 14:15:13.533 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [] [] [NA] failed to update serviceName: THRIFT_DEMO
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([127.0.0.1:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:351)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:326)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by nkorange** [comment]
Is your Nacos server up?

**Comment by coolsnow77** [comment]
nacos 肯定起来了， 这个是在对应用做并发测试的时候， nacos 有时候会报告这个错误。

**Comment by sunyibinbing** [comment]
2019-02-26 17:36:49.835 ERROR [ace-admin,,,] 11156 --- [.naming.updater] com.alibaba.nacos.client.naming          : [] [] [CALL-SERVER] failed to req API:http://127.0.0.1:8848/nacos/v1/ns/api/srvIPXT. code:404 msg: dom not found: localhost
2019-02-26 17:36:49.842 ERROR [ace-admin,,,] 11156 --- [.naming.updater] com.alibaba.nacos.client.naming          : [] [] [NA] req api:/nacos/v1/ns/api/srvIPXT failed, server(127.0.0.1:8848

**Comment by chensk1** [comment]
运行起来没问题 请求也能达到 但是后台不断报
2019-03-06 02:20:24.712 ERROR [pig-upms-biz,,,] 78587 --- [.naming.updater] com.alibaba.nacos.client.naming          : [] [] [NA] failed to update serviceName: localhost

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([192.168.3.5:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

版本0.9

**Comment by liaoxianrong** [comment]
我也遇到同样的问题，nacos0.8和0.9都是如此：
1、启动单个服务很久都不会出现，一旦同时启动多个服务的时候会出现且一直不停
2、用示例代码的时候不会出现这个问题，暂时还没有找到是什么原因

**Comment by xiaochanglaoshi** [comment]
我也遇到,单开一个正常,开两个就报404错误了 .

**Comment by Jacobs7** [comment]
我也是 +1  还有解决的 办法

**Comment by JornTang** [comment]
我也遇到这样的问题了，官方可有解决方案。麻烦指导下。下面是报错信息
ERROR [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] [] [] [NA] failed to update serviceName: localhost
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([nacos-server:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
01 2019-03-27 15:30:04.654 ERROR [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] [] [] [CALL-SERVER] failed to req API:http://nacos-server:8848/nacos/v1/ns/api/srvIPXT. code:404 msg: dom not found: localhost
01 2019-03-27 15:30:04.654 ERROR [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] [] [] [NA] req api:/nacos/v1/ns/api/srvIPXT failed, server(nacos-server:8848
com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:327)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
01 2019-03-27 15:30:04.654 ERROR [com.alibaba.nacos.client.naming.updater:c.a.n.c.naming] [] [] [NA] failed to update serviceName: localhost
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([nacos-server:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by vickze** [comment]
![image](https://user-images.githubusercontent.com/19652735/55158042-ef1c5100-5198-11e9-8903-1c2f9d5dbcd5.png)

使用nacos 版本1.0.0-RC2， jdk8, nacos 单机模式运行 spring-cloud-alibaba 0.2.1.RELEASE

我也遇到了，最终追踪到这里传进来的是localhost，因为nacos里并没有这个服务，所以报了这样的问题

具体情况是启动一个服务注册进去不会出现，第二个服务（不是同一个服务）注册后过一段时间（大概一两分钟）就出现了

参考 [https://github.com/alibaba/nacos/issues/842](https://github.com/alibaba/nacos/issues/842)  bilaisheng 的回复，创建个名为localhost的服务，可以暂时解决

**Comment by qq1311256696** [comment]
我这也是这个问题，服务一直报错导致日志文件太大，我们磁盘都满了。希望官方关注一下这个问题呀，谢谢

**Comment by fatiaojie** [comment]
+1

**Comment by nkorange** [comment]
Lock this issue now, please open another issue.
