### ISSUE TITLE
mach-o, but wrong architecture

### ISSUE THREAD

**Issue by lihanfei-dev** [alibaba/nacos#6058]
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/67/qy61bdpx4c3_s40j30t35xtw0000gn/T/librocksdbjni7987725137738801042.jnilib: dlopen(/private/var/folders/67/qy61bdpx4c3_s40j30t35xtw0000gn/T/librocksdbjni7987725137738801042.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/67/qy61bdpx4c3_s40j30t35xtw0000gn/T/librocksdbjni7987725137738801042.jnilib: mach-o, but wrong architecture
	/private/var/folders/67/qy61bdpx4c3_s40j30t35xtw0000gn/T/librocksdbjni7987725137738801042.jnilib: mach-o, but wrong architecture
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:187)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300)
	... 55 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/67/qy61bdpx4c3_s40j30t35xtw0000gn/T/librocksdbjni7987725137738801042.jnilib: dlopen(/private/var/folders/67/qy61bdpx4c3_s40j30t35xtw0000gn/T/librocksdbjni7987725137738801042.jnilib, 1): no suitable image found.  Did find:
	/private/var/folders/67/qy61bdpx4c3_s40j30t35xtw0000gn/T/librocksdbjni7987725137738801042.jnilib: mach-o, but wrong architecture
	/private/var/folders/67/qy61bdpx4c3_s40j30t35xtw0000gn/T/librocksdbjni7987725137738801042.jnilib: mach-o, but wrong architecture
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
	at java.lang.Runtime.load0(Runtime.java:811)
	at java.lang.System.load(System.java:1088)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.<clinit>(RocksDBLogStorage.java:75)
	at com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory.createLogStorage(DefaultJRaftServiceFactory.java:50)
	at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:571)
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:991)
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:138)
	at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGroup(JRaftServer.java:268)
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.addRequestProcessors(JRaftProtocol.java:163)
	at com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl.<init>(PersistentClientOperationServiceImpl.java:92)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:175)
	... 57 common frames omitted

**Comment by realJackSun** [comment]
rocksdb依赖错误或缺少库，请检查一下rocksdb依赖，或者到RocksDB社区提问。

**Comment by lihanfei-dev** [comment]
Mac M1版本会有此问题

**Comment by plusmancn** [comment]
see https://github.com/alibaba/nacos/issues/4336#issuecomment-821246302
