### ISSUE TITLE
nacos超时问题

### ISSUE THREAD

**Issue by ShameWoo** [alibaba/nacos#6069]
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_111]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_111]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_111]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_111]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_111]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432) ~[?:1.8.0_111]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527) ~[?:1.8.0_111]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:211) ~[?:1.8.0_111]
        at sun.net.www.http.HttpClient.New(HttpClient.java:308) ~[?:1.8.0_111]
        at sun.net.www.http.HttpClient.New(HttpClient.java:326) ~[?:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1202) ~[?:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138) ~[?:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032) ~[?:1.8.0_111]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:966) ~[?:1.8.0_111]
        at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:112) ~[nacos-common-1.4.2.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482) ~[nacos-common-1.4.2.jar!/:?]
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427) ~[nacos-common-1.4.2.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:603) [nacos-client-1.4.2.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) [nacos-client-1.4.2.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) [nacos-client-1.4.2.jar!/:?]
        at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:433) [nacos-client-1.4.2.jar!/:?]
        at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167) [nacos-client-1.4.2.jar!/:?]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_111]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_111]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [?:1.8.0_111]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [?:1.8.0_111]
        at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by xiaoheng1** [comment]
客户端和服务端当时网络是联通的吗？

**Comment by ShameWoo** [comment]
> 客户端和服务端当时网络是联通的吗？

**Comment by ShameWoo** [comment]
网络通的，所有服务都报这个错

**Comment by KomachiSion** [comment]
连接超时只有两类问题：
1. 服务端处于无法新建连接的状态（如长时间FullGC，连接端口占满，acceptQueue占满）
2. 网络问题，TCP的SYN包丢失或被丢弃。

建议先排查下服务端状态，比如curl localhost一下 或者telnet一下，如果是正常的。那么一定是网络问题。查看一下是不是有中间层比如slb，VIP，nginx之类的东西拦截掉了，或者网络本身就很差。

**Comment by ShameWoo** [comment]
![image](https://user-images.githubusercontent.com/33536883/122154216-0be6f100-ce97-11eb-978c-7558dedb35c4.png)
crul 没问题，nginx是放在docker里，应该也不影响

**Comment by ShameWoo** [comment]
> ![image](https://user-images.githubusercontent.com/33536883/122154216-0be6f100-ce97-11eb-978c-7558dedb35c4.png)
> crul 没问题，nginx是放在docker里也没有拦截8848，应该也不影响

**Comment by realJackSun** [comment]
会不会是你们的cluster.conf配置有问题？可以展示一下cluster.conf么？

有一种情况，就是cluster.conf中使用的是hostname或域名，然后dns系统无法发现这个域名，也有可能会导致SocketTimeoutException

**Comment by ShameWoo** [comment]
没有哦，是可以通过nacos调用其他服务的，只是一段时间不访问服务后再访问就会报超时，后面访问几次就又可用了，感觉一歇后访问就得报几下；另外日志里的这个timeout感觉和上面问题无关，无论服务可不可用，日志里都有这个exception

**Comment by KomachiSion** [comment]
把nginx去掉 直连试试

**Comment by KomachiSion** [comment]
No more response from author, so it is a env problem
