### ISSUE TITLE
Client request from server repsonse  token expired!

### ISSUE THREAD

**Issue by jiangshubian** [alibaba/nacos#6074]
Client version:  1.3.3
Server Cluster Version:  2.0.1 

server application.properties
server.servlet.contextPath=/nacos
server.port=8848
spring.datasource.platform=mysql
db.num=1
db.url.0=jdbc:mysql://192.168.3.3:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
db.user.0=nacos
db.password.0=****
db.pool.config.connectionTimeout=30000
db.pool.config.validationTimeout=10000
db.pool.config.maximumPoolSize=20
db.pool.config.minimumIdle=2
nacos.naming.empty-service.auto-clean=true
nacos.naming.empty-service.clean.initial-delay-ms=50000
nacos.naming.empty-service.clean.period-time-ms=30000
management.metrics.export.elastic.enabled=false
management.metrics.export.influx.enabled=false
server.tomcat.accesslog.enabled=false
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b %D %{User-Agent}i %{Request-Source}i
server.tomcat.basedir=
nacos.security.ignore.urls=/,/error,/**/*.css,/**/*.js,/**/*.html,/**/*.map,/**/*.svg,/**/*.png,/**/*.ico,/console-ui/public/**,/v1/auth/**,/v1/console/health/**,/actuator/**,/v1/console/server/**
nacos.core.auth.system.type=nacos
nacos.core.auth.enabled=true
nacos.core.auth.default.token.expire.seconds=18000
nacos.core.auth.default.token.secret.key=SecretKey012345678901234567890123456789012345678901234567890123456789
nacos.core.auth.caching.enabled=true
nacos.core.auth.enable.userAgentAuthWhite=false
nacos.core.auth.server.identity.key=nacosidentity
nacos.core.auth.server.identity.value=nacosidentity
nacos.istio.mcp.server.enabled=false

core-auth.log ：
2021-06-15 16:14:48,827 DEBUG auth start, request: PUT /nacos/v1/ns/instance/beat
2021-06-15 16:14:48,828 DEBUG auth permission: Permission{resource='9e8b1a13-22c1-482f-92ab-5396f2ef0985:DEFAULT_GROUP:naming/a.service', action='w'}, user: NacosUser{token='eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYyMzc1OTY2OH0.BOmcZ_mK0owzeKFUbSc_e_zQIl8F7a4t9cyxU_ZYxzc', globalAdmin=true}
2021-06-15 16:14:48,938 WARN Invalid server identity value for nacosidentity from 192.168.2.3

client log
2021-06-15 13:08:19.490 [com.alibaba.nacos.naming.beat.sender] ERROR a.service [TID:N/A] [-] com.alibaba.nacos.client.naming:613 [NA] 
failed to request
com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you a
re seeing this as a fallback.</p><div id='created'>Tue Jun 15 13:09:16 CST 2021</div><div>There was an unexpected error (type=Forbidden, status=403).</div
><div>token expired!</div></body></html>
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:611)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:538)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
        at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:426)
        at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

It is currently being resolved by restarting the service!!

**Comment by realJackSun** [comment]
This seems been fixed in 1.4.0
see #2866

**Comment by KomachiSion** [comment]
I think it may be not duplicated. Error information is `token expired!`. Have we added the token expired feature?

**Comment by AngryMills** [comment]
We had the same problem
Client version: 1.1.4
Server Cluster Version: 1.4.0
Our applications are deployed in container of docker
It's ok in first few days ，suddenly occur this error log for almost one whole day，then recover automatically

**Comment by KomachiSion** [comment]
I check the code of server, the jwt token with expired time auto. When the jwt token is expired, the validate will throw the ExpiredJwtException and nacos will return AccessException.

client received AccessException and retry to login again with username and password users set and get new token. So the exception is not problem or bugs. It is a expected behavior, if it can recover automatically.

**Comment by samuel072** [comment]
> 
这个问题到底是怎么解决呀！没有看懂呀！大佬给说哈子呗
