### ISSUE TITLE
单机模式运行Nacos无法打开控制台，日志显示在一个非套接字上尝试了一个操作。

### ISSUE THREAD

**Issue by zrsatgz** [alibaba/nacos#6099]
如题，运行如下
![QQ图片20210617181038](https://user-images.githubusercontent.com/35551883/122380662-b0059080-cf9a-11eb-8181-c80b1f30f5e4.png)
日志如下
2021-06-17 17:37:15,130 WARN Unexpected exception in the selector loop.

java.io.IOException: An exception occurred during the execution of select(): 
java.io.IOException: 在一个非套接字上尝试了一个操作。

	at java.base/sun.nio.ch.WindowsSelectorImpl$FinishLock.checkForException(WindowsSelectorImpl.java:328)
	at java.base/sun.nio.ch.WindowsSelectorImpl.doSelect(WindowsSelectorImpl.java:189)
	at java.base/sun.nio.ch.SelectorImpl.lockAndDoSelect(SelectorImpl.java:129)
	at java.base/sun.nio.ch.SelectorImpl.selectNow(SelectorImpl.java:151)
	at io.grpc.netty.shaded.io.netty.channel.nio.SelectedSelectionKeySetSelector.selectNow(SelectedSelectionKeySetSelector.java:56)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.selectNow(NioEventLoop.java:770)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop$1.get(NioEventLoop.java:72)
	at io.grpc.netty.shaded.io.netty.channel.DefaultSelectStrategy.calculateStrategy(DefaultSelectStrategy.java:30)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:446)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:831)
2021-06-17 17:37:16,145 INFO Migrated 1 channel(s) to the new Selector.

**Comment by KomachiSion** [comment]
这个可能是netty或者java的nio在windows上的bug。  我在mac和linux系统上没有遇到过。

**Comment by KomachiSion** [comment]
这个可能是netty或者java的nio在windows上的bug。  我在mac和linux系统上没有遇到过。

**Comment by KomachiSion** [comment]
There is no more response from author and this problem should no be nacos problem in windows. Maybe need change the jre or jdk version to fix it.
