### ISSUE TITLE
nacos日志文件中总是输出错误日志

### ISSUE THREAD

**Issue by wytjiayou** [alibaba/nacos#6140]
**Describe the bug**
客户端注册到nacos上，隔一段时间后，偶尔有刷新nacos服务列表，服务一下在列表中，一下不在列表中的现象。

**Expected behavior**
客户端错误日志：
2021-06-23 12:11:59.269|ERROR|[myyule-public-common:172.18.192.86:8666]|[,,]|longPolling error : 

java.net.ConnectException: no available server, currentServerAddr : http://172.18.192.86:8848
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:189)
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:68)
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:465)
        at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:432)
        at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:620)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

服务端错误日志：
2021-06-21 04:13:28,630 INFO [NACOS-DISTRO] healthy server list changed, old: [172.18.192.86:8848, 172.18.192.87:8848, 172.18.192.99:8848], new: [172.18.192.86:8848, 172.18.192.87:8848, 172.18.192.99:8848]

2021-06-21 04:13:31,381 WARN Exception while request: http://172.18.192.99:8848/nacos/v1/ns/instance/beat, caused: {}

java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:171)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getStatusCode(JdkHttpClientResponse.java:75)
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:43)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:483)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchange(NacosRestTemplate.java:447)
	at com.alibaba.nacos.naming.misc.HttpClient.request(HttpClient.java:114)
	at com.alibaba.nacos.naming.web.DistroFilter.doFilter(DistroFilter.java:144)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:65)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.naming.web.TrafficReviseFilter.doFilter(TrafficReviseFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2021-06-21 04:13:32,813 INFO [NACOS-RAFT] datum is changed, key: com.alibaba.nacos.naming.iplist.ephemeral.test-namespace##DEFAULT_GROUP@@myyule-pass-channel, value: {"instanceList":[{"instanceId":"172.18.192.88#8445#DEFAULT#DEFAULT_GROUP@@myyule-pass-channel","ip":"172.18.192.88","port":8445,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@myyule-pass-channel","metadata":{"preserved.register.source":"SPRING_CLOUD"},"lastBeat":1624220004378,"marked":false,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000},{"instanceId":"172.18.192.89#8445#DEFAULT#DEFAULT_GROUP@@myyule-pass-channel","ip":"172.18.192.89","port":8445,"weight":1.0,"healthy":false,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@myyule-pass-channel","metadata":{"preserved.register.source":"SPRING_CLOUD"},"lastBeat":1624219992601,"marked":false,"app":"unknown","instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]}

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - nacos-server 1.4.0, nacos-client 1.3.3
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by wytjiayou** [comment]
2021-06-21 22:22:52,817 INFO [AUTO-DELETE-IP] service: DEFAULT_GROUP@@myyule-pass-config, ip: {"instanceId":"172.18.192.89#8450#DEFAULT#DEFAULT_GROUP@@myyule-pass-config","ip":"172.18.192.89","port":8450,"weight":1.0,"healthy":false,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@myyule-pass-config","metadata":{"preserved.register.source":"SPRING_CLOUD"},"lastBeat":1624285338781,"marked":false,"app":"unknown","instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}

客户端与服务端不存在网络问题，为什么会有客户端实例被服务端删除的现象？

**Comment by MajorHe1** [comment]
从报错信息来看，客户端和服务端、服务端和服务端之间还是存在网络通信问题的
使用的版本是nacos-server 1.4.0, nacos-client 1.3.3 ？ 建议升级到最新版试试？

**Comment by wytjiayou** [comment]
> 从报错信息来看，客户端和服务端、服务端和服务端之间还是存在网络通信问题的
> 使用的版本是nacos-server 1.4.0, nacos-client 1.3.3 ？ 建议升级到最新版试试？

网络通信问题，可以通过升级版本解决？

**Comment by MajorHe1** [comment]
> > 从报错信息来看，客户端和服务端、服务端和服务端之间还是存在网络通信问题的
> > 使用的版本是nacos-server 1.4.0, nacos-client 1.3.3 ？ 建议升级到最新版试试？
> 
> 网络通信问题，可以通过升级版本解决？

我之前在社区看到很多其他用户也有这样类似的问题，版本都比较老了
你要是能确定并排查清楚是否真的网络通信存在问题，那就先排查网络问题
要是确信网络没问题，就先升级版本，排除变量法，试试嘛

**Comment by KomachiSion** [comment]
读超时和ConnectException: no available server的问题，都是http调用失败导致的问题，
可能的原因是
1. 网络问题
2. 中间转发层限流导致（比如nginx）
3. 服务端FullGC导致响应慢
4. 服务端连接满/accessQueue满

前2个问题自行排查。后两个问题通过jstat/jmap/ss等jdk或系统命令找到问题源头，然后提issue反馈。

**Comment by realJackSun** [comment]
any progress? @wytjiayou

**Comment by KomachiSion** [comment]
No more response from author, so we think it is a env problem.

**Comment by KeithTt** [comment]
裂开了 什么问题都能遇到... Nacos 2.0.4

```
2022-04-07 15:23:04,389 INFO [NACOS-DISTRO] healthy server list changed, old: [172.16.69.42:8848, 172.16.69.44:8848], new: [172.16.69.42:8848, 172.16.69.43:8848, 172.16.69.44:8848]

2022-04-07 15:23:04,481 INFO upgrade check result false
```

日志不停地刷，状态也不停地变化

![image](https://user-images.githubusercontent.com/15189954/162149505-c91422a9-649f-42fe-ae12-1bb4d2ed53c1.png)

**Comment by KeithTt** [comment]
> 裂开了 什么问题都能遇到... Nacos 2.0.4
> 
> ```
> 2022-04-07 15:23:04,389 INFO [NACOS-DISTRO] healthy server list changed, old: [172.16.69.42:8848, 172.16.69.44:8848], new: [172.16.69.42:8848, 172.16.69.43:8848, 172.16.69.44:8848]
> 
> 2022-04-07 15:23:04,481 INFO upgrade check result false
> ```
> 
> 日志不停地刷，状态也不停地变化
> 
> ![image](https://user-images.githubusercontent.com/15189954/162149505-c91422a9-649f-42fe-ae12-1bb4d2ed53c1.png)

三节点集群，同时停掉俩再起来就恢复了。
