### ISSUE TITLE
nacos v1.3.1升级到v2.0.2报错

### ISSUE THREAD

**Issue by kody1025** [alibaba/nacos#6186]
nacos v1.3.1升级到v2.0.2报错，start.out打印启动成功，naming-server一直打印以下错误：

2021-06-28 17:57:08,110 ERROR Nacos task execute error : org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.alibaba.nacos.naming.core.v2.upgrade.doublewrite.execute.InstanceUpgradeHelper' available

org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.alibaba.nacos.naming.core.v2.upgrade.doublewrite.execute.InstanceUpgradeHelper' available
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:350)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:341)
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1124)
	at com.alibaba.nacos.sys.utils.ApplicationUtils.getBean(ApplicationUtils.java:150)
	at com.alibaba.nacos.naming.core.v2.upgrade.doublewrite.delay.ServiceChangeV1Task$ServiceChangeV1TaskProcessor.dispatchInstanceTask(ServiceChangeV1Task.java:163)
	at com.alibaba.nacos.naming.core.v2.upgrade.doublewrite.delay.ServiceChangeV1Task$ServiceChangeV1TaskProcessor.process(ServiceChangeV1Task.java:136)
	at com.alibaba.nacos.common.task.engine.NacosDelayTaskExecuteEngine.processTasks(NacosDelayTaskExecuteEngine.java:154)
	at com.alibaba.nacos.common.task.engine.NacosDelayTaskExecuteEngine$ProcessRunnable.run(NacosDelayTaskExecuteEngine.java:174)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2021-06-28 17:57:09,034 INFO upgrade check result false

**Comment by realJackSun** [comment]
duplicate with #6109

**Comment by kody1025** [comment]
OK.
