### ISSUE TITLE
Registering nacos config with docker did not change the server address

### ISSUE THREAD

**Issue by andochiwa** [alibaba/nacos#6328]
I want to package my spring cloud demo with docker-compose, use nacos as the config center, and set the server address of the config center in bootstrap.yml, but when executed inside docker, the address becomes localhost:8848, which causes to be unable to connection nacos config center.
```bash
2021-07-11 18:15:38.176  INFO 1 --- [           main] c.a.n.c.c.impl.LocalConfigInfoProcessor  : LOCAL_SNAPSHOT_PATH:/root/nacos/config
2021-07-11 18:15:38.338  INFO 1 --- [           main] c.a.nacos.client.config.impl.Limiter     : limitTime:5.0
2021-07-11 18:15:38.414 ERROR 1 --- [           main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-07-11 18:15:38.576 ERROR 1 --- [           main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-07-11 18:15:38.775 ERROR 1 --- [           main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-07-11 18:15:38.977 ERROR 1 --- [           main] c.a.n.c.config.http.ServerHttpAgent      : [NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused (Connection refused)
2021-07-11 18:15:39.003 ERROR 1 --- [           main] c.a.n.client.config.impl.ClientWorker    : [fixed-localhost_8848-66d272a3-fd82-41d7-a86c-e95096d2a2c7] [sub-server] get server config exception, dataId=nacos.yml, group=DEFAULT_GROUP, tenant=66d272a3-fd82-41d7-a86c-e95096d2a2c7

java.net.ConnectException: [NACOS HTTP-GET] The maximum number of tolerable server reconnection errors has been reached
        at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpGet(ServerHttpAgent.java:125) ~[nacos-client-1.4.1.jar!/:na]
        at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpGet(MetricsHttpAgent.java:51) ~[nacos-client-1.4.1.jar!/:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:274) ~[nacos-client-1.4.1.jar!/:na]
        at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:155) ~[nacos-client-1.4.1.jar!/:na]
        at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:98) ~[nacos-client-1.4.1.jar!/:na]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:85) ~[spring-cloud-starter-alibaba-nacos-config-2020.0.RC1.jar!/:2020.0.RC1]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:73) ~[spring-cloud-starter-alibaba-nacos-config-2020.0.RC1.jar!/:2020.0.RC1]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199) ~[spring-cloud-starter-alibaba-nacos-config-2020.0.RC1.jar!/:2020.0.RC1]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186) ~[spring-cloud-starter-alibaba-nacos-config-2020.0.RC1.jar!/:2020.0.RC1]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosConfiguration(NacosPropertySourceLocator.java:158) ~[spring-cloud-starter-alibaba-nacos-config-2020.0.RC1.jar!/:2020.0.RC1]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadExtConfiguration(NacosPropertySourceLocator.java:128) ~[spring-cloud-starter-alibaba-nacos-config-2020.0.RC1.jar!/:2020.0.RC1]
        at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:102) ~[spring-cloud-starter-alibaba-nacos-config-2020.0.RC1.jar!/:2020.0.RC1]
        at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51) ~[spring-cloud-context-3.0.3.jar!/:3.0.3]
        at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47) ~[spring-cloud-context-3.0.3.jar!/:3.0.3]
        at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95) ~[spring-cloud-context-3.0.3.jar!/:3.0.3]
        at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:634) ~[spring-boot-2.5.2.jar!/:2.5.2]
        at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:403) ~[spring-boot-2.5.2.jar!/:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:337) ~[spring-boot-2.5.2.jar!/:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.2.jar!/:2.5.2]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.2.jar!/:2.5.2]
        at com.github.demo.GatewayApplication.main(GatewayApplication.java:10) ~[classes!/:0.0.1-SNAPSHOT]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[demo.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[demo.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[demo.jar:0.0.1-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[demo.jar:0.0.1-SNAPSHOT]
```
this is my bootstrap.yml file
```yaml
spring:
  profiles:
    active: dev
  cloud:
    nacos:
      config:
        namespace: 66d272a3-fd82-41d7-a86c-e95096d2a2c7
        file-extension: yaml
        extension-configs:
          - data-id: nacos.yml
            refresh: true
        server-addr: nacos:8848
```
docker-compose
```yaml
version: "3"

services:
  nacos:
    image: nacos/nacos-server:1.4.0
    container_name: nacos
    restart: always
    ports:
      - "8848:8848"
    environment:
      - PREFER_HOST_MODE=hostname
      - MODE=standalone
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=mysql
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=nacos_demo_config
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=root
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&serverTimezone=Japan
    networks:
      - web-demo
  gateway:
    build: ./spring-cloud-gateway-demo
    container_name: gateway-demo
    depends_on:
      - nacos
    networks:
      - web-demo

networks:
  web-demo:
```
Dockerfile
```bash
FROM openjdk:11.0.9.1-jdk
COPY target/demo-0.0.1-SNAPSHOT.jar /app/demo.jar
WORKDIR /app
CMD ["java", "-jar", "demo.jar"]
```
pom.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.5.2</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>
    <groupId>com.github</groupId>
    <artifactId>demo</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>demo</name>
    <description>Demo project for Spring Boot</description>
    <properties>
        <java.version>11</java.version>
        <spring-cloud.version>2020.0.3</spring-cloud.version>
    </properties>
    <dependencies>
        <!--Service registration and discovery-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
            <version>2020.0.RC1</version>
        </dependency>
        <!--service config-->
        <dependency>
            <groupId>com.alibaba.cloud</groupId>
            <artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
            <version>2020.0.RC1</version>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-loadbalancer</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-gateway</artifactId>
        </dependency>
        <dependency>
            <groupId>org.springframework.cloud</groupId>
            <artifactId>spring-cloud-starter-bootstrap</artifactId>
        </dependency>

        <dependency>
            <groupId>org.projectlombok</groupId>
            <artifactId>lombok</artifactId>
            <optional>true</optional>
        </dependency>
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
        </dependency>
    </dependencies>
    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <plugins>
            <plugin>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-maven-plugin</artifactId>
                <configuration>
                    <excludes>
                        <exclude>
                            <groupId>org.projectlombok</groupId>
                            <artifactId>lombok</artifactId>
                        </exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>

</project>
```
But the server addr can be read when the jar file is executed outside the docker container.
![QQ图片20210712041426](https://user-images.githubusercontent.com/67818237/125207514-af28fb80-e2c7-11eb-8ef2-7fdff3bc031b.png)
the java version:
```bash
openjdk 11.0.11 2021-04-20
OpenJDK Runtime Environment (build 11.0.11+9-Ubuntu-0ubuntu2.18.04)
OpenJDK 64-Bit Server VM (build 11.0.11+9-Ubuntu-0ubuntu2.18.04, mixed mode, sharing)
```

**Comment by realJackSun** [comment]
> The maximum number of tolerable server reconnection errors has been reached

 Is your server load too heavy?

**Comment by KomachiSion** [comment]
Please move issue to Spring cloud community
