### ISSUE TITLE
局域网单机nacos无法监听配置中心

### ISSUE THREAD

**Issue by zero47** [alibaba/nacos#6364]
**Describe the bug**
局域网搭建单机nacos可以注册成功，但无法读取配置中心配置。
但更换为本地nacos(127.0.0.1)后可以正确读取配置。

**Expected behavior**
`[2021-07-15 15:29:04,503] [ERROR] [com.alibaba.nacos.client.Worker.longPolling.fixed-172.16.100.200_8848] [c.alibaba.nacos.client.config.http.ServerHttpAgent ServerHttpAgent.java:173] [NACOS Exception httpPost] currentServerAddr: http://172.16.100.200:8848
java.io.IOException: Server returned HTTP response code: 502 for URL: http://172.16.100.200:8848/nacos/v1/cs/configs/listener
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getBody(JdkHttpClientResponse.java:55)
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handleError(AbstractResponseHandler.java:51)
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:44)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:458)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.postForm(NacosRestTemplate.java:401)
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:155)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:68)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:465)
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:432)
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:620)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**How to Reproduce**
1. 局域网搭建nacos
2. 使用内网地址访问nacos config

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version:
 1. nacos-server 2.0.1 
 2. spring-cloud-starter-alibaba-nacos-config:2.2.2.RELEASE
 3. spring-cloud:Hoxton.SR11
 4. spring-boot:2.2.2.RELEASE
 
 - SDK spring-cloud-alibaba-nacos

**Comment by zero47** [comment]
已查明是vpn问题

**Comment by csi0n** [comment]
> 已查明是vpn问题

hi, 我也遇到了同样的问题，可以肯定的是确实是VPN的问题，但是可以在开VPN的情况下解决这个问题吗？我用的AnyConnect。
