### ISSUE TITLE
Nacos client runs for a period of time and runs out of memory

### ISSUE THREAD

**Issue by JeremyHJ** [alibaba/nacos#6380]
**problem：**Nacos client runs for a period of time and runs out of memory

Nacos client is 1.3.2, Nacos service is 1.3.1
pom：

 ```
            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2.2.1.RELEASE</version>
                <type>pom</type>
                <scope>import</scope>
                <exclusions>
                    <exclusion>
                        <artifactId>com.alibaba.nacos</artifactId>
                        <groupId>nacos-client</groupId>
                    </exclusion>
                </exclusions>
            </dependency>
```
```
            <dependency>
                <groupId>com.alibaba.nacos</groupId>
                <artifactId>nacos-client</artifactId>
                <version>1.3.2</version>
            </dependency>
```
Linux kernel.pid_max = 32768，the current number of processes is far less than the maximum

**error log ：**
```
Exception in thread "taskExecutor-4153" java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:717)
        at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:957)
        at java.util.concurrent.ThreadPoolExecutor.processWorkerExit(ThreadPoolExecutor.java:1025)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
WARN - 2021-07-18 08:21:14,334 - com.alibaba.nacos.client.naming - [NA] failed to update serviceName: DEFAULT_GROUP@@providers:com.dmj.micro.cps.provider.IWphGoodsProvider::prd-group
java.lang.OutOfMemoryError: unable to create new native thread
        at java.lang.Thread.start0(Native Method)
        at java.lang.Thread.start(Thread.java:717)
        at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:112)
        at sun.net.www.http.KeepAliveCache$1.run(KeepAliveCache.java:96)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.net.www.http.KeepAliveCache.put(KeepAliveCache.java:95)
        at sun.net.www.http.HttpClient.putInKeepAliveCache(HttpClient.java:438)
        at sun.net.www.http.HttpClient.finished(HttpClient.java:395)
        at sun.net.www.http.ChunkedInputStream.closeUnderlying(ChunkedInputStream.java:219)
        at sun.net.www.http.ChunkedInputStream.processRaw(ChunkedInputStream.java:455)
        at sun.net.www.http.ChunkedInputStream.readAheadNonBlocking(ChunkedInputStream.java:520)
        at sun.net.www.http.ChunkedInputStream.readAhead(ChunkedInputStream.java:611)
        at sun.net.www.http.ChunkedInputStream.available(ChunkedInputStream.java:725)
        at java.io.FilterInputStream.available(FilterInputStream.java:168)
        at sun.nio.cs.StreamDecoder.inReady(StreamDecoder.java:363)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:324)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at java.io.Reader.read(Reader.java:140)
        at com.alibaba.nacos.common.utils.IoUtils.copy(IoUtils.java:195)
        at com.alibaba.nacos.common.utils.IoUtils.toString(IoUtils.java:180)
        at com.alibaba.nacos.common.utils.IoUtils.toString(IoUtils.java:168)
        at com.alibaba.nacos.common.http.client.handler.StringResponseHandler.convertResult(StringResponseHandler.java:36)
        at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:46)
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:458)
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:422)
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:599)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400)
        at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:330)
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:397)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by JeremyHJ** [comment]
The Internet is also accessible

**Comment by KomachiSion** [comment]
`java.lang.OutOfMemoryError: unable to create new native thread` Please check your application has enough memory to create Thread.

If enough. please check whether your application has thread leak.

Or can you provider your jmap dump and jstack context?
