### ISSUE TITLE
k8s部署nacos1.4.2升级成2.0.1 3节点 一直starting等很久才启动好

### ISSUE THREAD

**Issue by sundong1982** [alibaba/nacos#6381]
同样的k8s yaml脚本 1.4.2正常

**Comment by KomachiSion** [comment]
一直starting原因是什么？ 是配置中心无法选主导致dump不出数据？ 还是其他原因？ 我自己的环境staring打10个以内就能启动好（配置比较少）

**Comment by KomachiSion** [comment]
需要提供更多相关信息。

**Comment by MajorHe1** [comment]
这个大概率是双写的问题，如果不是生产环境，可以在测试环境随便搞的话，启动脚本里面强制关闭双写很快就启动完了。

在main函数里面 
`ApplicationUtils.getBean(SwitchDomain.class).setDoubleWriteEnabled(false);`

**Comment by KomachiSion** [comment]
双写不会导致一直starting，一只starting一定是spring容器还在初始化。nacos目前会阻塞spring容器初始化的只有config的配置dump流程。

**Comment by sundong1982** [comment]
![1](https://user-images.githubusercontent.com/10413078/126587168-ae4da0fa-c65b-4765-beab-2e1ddb97e69e.png)
![2](https://user-images.githubusercontent.com/10413078/126587177-a20deba0-112d-44b3-b574-d6d3c1b8a036.png)
![3](https://user-images.githubusercontent.com/10413078/126587183-254f8996-1820-424f-bf6d-b259c3eb1a7e.png)
[log.zip](https://github.com/alibaba/nacos/files/6859846/log.zip)

**Comment by MajorHe1** [comment]
> ![1](https://user-images.githubusercontent.com/10413078/126587168-ae4da0fa-c65b-4765-beab-2e1ddb97e69e.png)
> ![2](https://user-images.githubusercontent.com/10413078/126587177-a20deba0-112d-44b3-b574-d6d3c1b8a036.png)
> ![3](https://user-images.githubusercontent.com/10413078/126587183-254f8996-1820-424f-bf6d-b259c3eb1a7e.png)
> [log.zip](https://github.com/alibaba/nacos/files/6859846/log.zip)

refer to #6413

估计答案在 #6072里面，Nginx配置错误的问题

**Comment by sundong1982** [comment]
@MajorHe1 没有用nginx

**Comment by KomachiSion** [comment]
有几种可能性：
1. 网络不好，从数据库中dump初始化数据过慢
2. 配置数据过多，dump速度过慢
3. 磁盘IO有问题，从数据库中dump数据写入磁盘过慢
4. 系统配置过低，或者超配比严重，没有足够的cpu资源处理dump的出来的数据。
5. 内存配置过低，过多GC或FullGC导致处理慢

**Comment by sundong1982** [comment]
@KomachiSion 这些问题在用1.4.2的各种环境都没出现过，开发环境只是把镜像版本从1.4.2改成了2.0.1其他配置并没变，(其中2.0需要的那些端口在用1.4.2时也一直放开的)。

**Comment by sundong1982** [comment]
@KomachiSion 这些问题在用1.4.2的各种环境都没出现过，开发环境只是把镜像版本从1.4.2改成了2.0.1其他配置并没变，(其中2.0需要的那些端口在用1.4.2时也一直放开的)。

**Comment by sundong1982** [comment]
@KomachiSion 这些问题在用1.4.2的各种环境都没出现过，开发环境只是把镜像版本从1.4.2改成了2.0.1其他配置并没变，(其中2.0需要的那些端口在用1.4.2时也一直放开的)。

**Comment by KomachiSion** [comment]
那您可以试着dump一下线程，看一下starting的时候 main线程的堆栈在处理些什么？

**Comment by sundong1982** [comment]
naming-raft.log

2021-07-28 14:43:08,880 ERROR error while sending vote to server: nacos-server-1.nacos-server-headless.nacos-server.svc.cluster.local:8848

java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:748)
2021-07-28 14:43:08,880 ERROR error while sending vote to server: nacos-server-2.nacos-server-headless.nacos-server.svc.cluster.local:8848

java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:748)
2021-07-28 14:43:10,438 INFO Raft group naming_persistent_service has leader nacos-server-0.nacos-server-headless.nacos-server.svc.cluster.local:7848

2021-07-28 14:43:25,102 INFO leader timeout, start voting,leader: null, term: 1

2021-07-28 14:43:25,106 ERROR error while sending vote to server: nacos-server-1.nacos-server-headless.nacos-server.svc.cluster.local:8848

java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:748)
2021-07-28 14:43:25,224 INFO received approve from peer: {"ip":"nacos-server-2.nacos-server-headless.nacos-server.svc.cluster.local:8848","voteFor":"nacos-server-0.nacos-server-headless.nacos-server.svc.cluster.local:8848","term":2,"leaderDueMs":16870,"heartbeatDueMs":4000,"state":"FOLLOWER"}

2021-07-28 14:43:25,237 INFO nacos-server-0.nacos-server-headless.nacos-server.svc.cluster.local:8848 has become the LEADER

2021-07-28 14:43:27,547 INFO received illegitimate vote, voter-term:2, votee-term:2

2021-07-28 14:43:33,920 WARN start to close old raft protocol!!!

2021-07-28 14:43:33,920 WARN stop old raft protocol task for notifier

2021-07-28 14:43:33,920 WARN stop old raft protocol task for master task

2021-07-28 14:43:33,920 WARN stop old raft protocol task for heartbeat task

2021-07-28 14:43:33,920 WARN clean old cache datum for old raft

2021-07-28 14:43:33,920 WARN start to close old raft protocol!!!

2021-07-28 14:43:33,920 WARN stop old raft protocol task for notifier

2021-07-28 14:43:33,920 WARN stop old raft protocol task for master task

2021-07-28 14:43:33,920 WARN stop old raft protocol task for heartbeat task

2021-07-28 14:43:33,920 WARN clean old cache datum for old raft

2021-07-28 14:43:33,920 WARN start to move old raft protocol metadata

2021-07-28 14:43:33,920 WARN start to move old raft protocol metadata

**Comment by sundong1982** [comment]
访问http://xxxx:8848/nacos/v1/ns/operator/cluster/state

nacos.log报


java.lang.IllegalStateException: unable to find local peer: nacos-server-0.nacos-server-headless.nacos-server.svc.cluster.local:8848, all peers: []
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.local(RaftPeerSet.java:286)
	at com.alibaba.nacos.naming.core.ServiceManager.getMySelfClusterState(ServiceManager.java:298)
	at com.alibaba.nacos.naming.controllers.OperatorController.getClusterStates(OperatorController.java:258)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:626)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.naming.web.DistroFilter.doFilter(DistroFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.naming.web.ServiceNameFilter.doFilter(ServiceNameFilter.java:68)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.naming.web.TrafficReviseFilter.doFilter(TrafficReviseFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2021-07-28 14:51:53,462 ERROR CONSOLE

**Comment by sundong1982** [comment]
用 http://xxx:8848/nacos/v1/ns/operator/servers 访问  3个节点的state都是up

**Comment by sundong1982** [comment]
两个版本的naming_persistent_service lead分别是0和2这个正常吗
![image](https://user-images.githubusercontent.com/10413078/127279921-c956f39a-84c9-4f03-9d6f-b4d0d0c34784.png)

**Comment by KomachiSion** [comment]
启动没有问题，只是启动慢，你要做的看在打starting的时候，main线程在做什么，卡在哪里。如果你关注点错了那肯定是找不到正确答案的。

**Comment by sundong1982** [comment]
dump后没发现什么异常，猜测像是3个节点在相互等待，一直starting.10多秒，启动成功后节点状态都是up，一开始我以为节点都是up，不存在其他问题，结果后面使用其他依赖nacos的软件都报错。你们可以用k8s搭建一套最简单的nacos2.x 3节点就可以复现问题了，脚本在https://github.com/nacos-group/nacos-k8s  。如果你们的nacos-k8s集群能正常运行，麻烦贴一个k8s脚本，我去捣鼓一下。

**Comment by paderlol** [comment]
你们k8s环境有使用istio吗？脚本用的nfs？

**Comment by sundong1982** [comment]
@paderlol 没有使用istio 直接用了https://github.com/nacos-group/nacos-k8s提供的脚本。修改了nacos镜像版本号和数据库配置

**Comment by KomachiSion** [comment]
我们使用k8s运行了上千个nacos集群，启动速度和功能都没有问题。从上述截图也没有看出问题，raft是多group设计，每个group单独选主，不同group leader在不同节点上也是正常的，你说有报错，错误是什么也没说。

而且内容和issue title已经偏离了， 这个issue应该主要关注启动慢的问题，从最新的回答感觉starting 10多秒其实不算慢，毕竟需要dump配置数据、选主、加载快照等操作。
