### ISSUE TITLE
nocas集群，某个nocas节点宕机之后，有微服务注册不上出现的问题，问题描述如下

### ISSUE THREAD

**Issue by henpangpang** [alibaba/nacos#6393]
nocas集群，某个nocas节点宕机之后，有微服务注册不上出现的问题，这个情况无法满足高可用，当节点重启之后，微服务停止报错，但是出现假死，YGC  5000多   YGCT 55   具体应该如何排查

**Comment by KomachiSion** [comment]
看日志，是连接不上导致注册不上还是集群有报错导致连不上。

YGC 5000+是运行多久的结果？ 有没有FGC等等。

**Comment by henpangpang** [comment]
有FGC，在公司的电脑上，明天我上班就贴上来！是连接不上导致微服务假死，大概是报了一个多小时的connect refuse，nocas宕机的那个节点重启后，微服务注册上就不报错，观察了半个小时左右，YGC  5000+，后面nocas没有出现宕机的情况，微服务也一直正常运行，目前我就把问题锁定在nocas集群高可用失败这里

**Comment by henpangpang** [comment]
![image](https://user-images.githubusercontent.com/47917922/126417532-1b8db7bc-81da-4bde-95b8-311ef2117bf6.png)

**Comment by henpangpang** [comment]
> 看日志，是连接不上导致注册不上还是集群有报错导致连不上。
> 
> YGC 5000+是运行多久的结果？ 有没有FGC等等。

是连接不上导致微服务假死，大概是报了一个多小时的connect refuse，nocas宕机的那个节点重启后，微服务注册上就不报错，但是假死了，观察了半个小时左右，总共加起来2小时左右，YGC 5000+，后面nocas没有出现宕机的情况，微服务也一直正常运行，目前我就把问题锁定在nocas集群高可用失败这里

**Comment by LeeGaning** [comment]
```log
2021-07-21 07:47:31.572  WARN 1 --- [aming.updater.1] com.alibaba.nacos.client.naming          : [NA] failed to update serviceName: DEFAULT_GROUP@@xxxxx

com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:213)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.queryInstancesOfService(NamingGrpcClientProxy.java:128)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.queryInstancesOfService(NamingClientProxyDelegate.java:111)
	at com.alibaba.nacos.client.naming.core.ServiceInfoUpdateService$UpdateTask.run(ServiceInfoUpdateService.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html.
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:205)
	... 10 common frames omitted

2021-07-21 07:48:30.192  INFO 1 --- [aming.updater.0] com.alibaba.nacos.client.naming          : removed ips(1) service: DEFAULT_GROUP@@xxxxx@@DEFAULT -> [{"ip":"10.0.2.193","port":8080,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@xxxxxx","metadata":{"preserved.register.source":"SPRING_CLOUD","management.context-path":"/auth/actuator"},"ipDeleteTimeout":30000,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000}]
2021-07-21 07:48:30.192  INFO 1 --- [aming.updater.0] com.alibaba.nacos.client.naming          : current ips:(0) service: DEFAULT_GROUP@@xxxxxxxx@@DEFAULT -> []
2021-07-21 08:01:19.481  INFO 1 --- [   .....
```
no more before restart client

感觉是客户端的问题？重连成功之后把客户端配置信息删掉了

**Comment by henpangpang** [comment]
> ```
> 2021-07-21 07:47:31.572  WARN 1 --- [aming.updater.1] com.alibaba.nacos.client.naming          : [NA] failed to update serviceName: DEFAULT_GROUP@@xxxxx
> 
> com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
> 	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:213)
> 	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.queryInstancesOfService(NamingGrpcClientProxy.java:128)
> 	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.queryInstancesOfService(NamingClientProxyDelegate.java:111)
> 	at com.alibaba.nacos.client.naming.core.ServiceInfoUpdateService$UpdateTask.run(ServiceInfoUpdateService.java:182)
> 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
> 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
> 	at java.lang.Thread.run(Thread.java:748)
> Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html.
> 	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:205)
> 	... 10 common frames omitted
> 
> 2021-07-21 07:48:30.192  INFO 1 --- [aming.updater.0] com.alibaba.nacos.client.naming          : removed ips(1) service: DEFAULT_GROUP@@xxxxx@@DEFAULT -> [{"ip":"10.0.2.193","port":8080,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@xxxxxx","metadata":{"preserved.register.source":"SPRING_CLOUD","management.context-path":"/auth/actuator"},"ipDeleteTimeout":30000,"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000}]
> 2021-07-21 07:48:30.192  INFO 1 --- [aming.updater.0] com.alibaba.nacos.client.naming          : current ips:(0) service: DEFAULT_GROUP@@xxxxxxxx@@DEFAULT -> []
> 2021-07-21 08:01:19.481  INFO 1 --- [   .....
> ```
> 
> no more before restart client
> 客户端使用2.0.1，RPC连接。在重启客户端之前，没有更多日志
> 感觉是客户端的问题？重连成功之后把客户端配置信息删掉了
> 有的客户端使用1.3.2版本客户端，http方式，没有出现问题

谢谢指导，后面我再观察观察是否是这个问题导致的

**Comment by KomachiSion** [comment]
`Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html.`

提示这么明显。。

**Comment by LeeGaning** [comment]
> `Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html.`
> 
> 提示这么明显。。

我看到了，然后关闭了双写。接下来就没有报错了，客户端也没有注册上

**Comment by KomachiSion** [comment]
没有注册上是控制台看不到还是consumer看不到？

如果是控制台看不到那可能是服务端返回错误了，用浏览器审查元素看下服务端的response。如果有错误把信息贴一下

**Comment by yyang1207** [comment]
兄弟的问题解决了没，我也遇到无法注册的问题了。
3个节点的集群宕机了2个节点，启动节点后服务无法注册，nacos ui也刷不出来已注册的服务数据。
7848  8848 9848  9849  的端口都已开启

**Comment by xyohn** [comment]
想咨询一下 这个错误是因为Nacos都关闭了双写 后有节点重启进入后默认开启了双写导致的吗
我们这边容器化部署下 关闭双写 部分节点出现重启后也会有这个问题 这种情况下Nacos控制台里看不到相关客户端 服务一直在报这个错 手动把重启的Nacos关闭双写后恢复正常 （不报错 控制台看得到服务）
但这需要手工介入 Nacos啥时候会被重启我们不能确定（可能会因为pod占用磁盘过大被驱逐） 我们的服务都是用2.0客户端的 有没有办法永久性关闭双写呢？（即便服务重启也不会开启双写）

> `Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html.`
> 
> 
> 
> 提示这么明显。。

**Comment by KomachiSion** [comment]
No response from author, the other response is not relative with the title problem, so close issue first.
