### ISSUE TITLE
微服务启动 就会报502错误

### ISSUE THREAD

**Issue by TuYv** [alibaba/nacos#6455]
报错日志如下 微服务启动注册到nacos上之后就会刷这个日志

c.a.n.c.config.http.ServerHttpAgent      : [NACOS Exception httpPost] currentServerAddr: http://121.5.170.146:8848

java.io.IOException: Server returned HTTP response code: 502 for URL: http://121.5.170.146:8848/nacos/v1/cs/configs/listener
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:na]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:488) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1963) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1958) ~[na:na]
	at java.base/java.security.AccessController.doPrivileged(Native Method) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1957) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1525) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1509) ~[na:na]
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getBody(JdkHttpClientResponse.java:60) ~[nacos-common-1.4.1.jar:na]
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handleError(AbstractResponseHandler.java:51) ~[nacos-common-1.4.1.jar:na]
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:44) ~[nacos-common-1.4.1.jar:na]
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:483) ~[nacos-common-1.4.1.jar:na]
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.postForm(NacosRestTemplate.java:407) ~[nacos-common-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:155) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:68) [nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:441) [nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:408) [nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:596) [nacos-client-1.4.1.jar:na]

**Comment by brotherlu-xcq** [comment]
你的Nacos Server有正常启动吗？还有server的版本还有对应的错误日志可以提供一下吗？

**Comment by TuYv** [comment]
大佬好。nacos的日志文件太多了 我找了半天没有看到服务端的错误日志在哪里 所以才来这里求助的。
然后情况是这样的 我用另外一台电脑去运行同一份代码 启动微服务是正常的 但是用我的笔记本电脑的时候微服务就会有这样的日志输出
 nacos版本的话是2.0.1

**Comment by KomachiSion** [comment]
那么服务端应该没有什么问题，可能是笔记本那台的网络或者本地环境导致的。 是否有登陆VPN之类的？

**Comment by adougebabi** [comment]
我也是这样的情况，把clashX关了就好了，但是看日志，nacos的ip走的是DIRECT，而且之前一直都没有问题，最近这两个月才出现的502，用postman调用这个接口又不会，很奇怪。

**Comment by TuYv** [comment]
惊了 还真是clashX的原因 奇怪 不过解决了就好

**Comment by myoss** [comment]
用 1.50.1 ClashX就正常， 1.65.0就有这个问题

**Comment by chansanya** [comment]
好家伙 ，我也是关了clashX 就好了

**Comment by illeagalName** [comment]
好家伙，我也是关了clashX 就好了

**Comment by BrogenWang** [comment]
好家伙，我也是关了clashX 就好了

**Comment by McSources** [comment]
好家伙，我也是关了clashX 就好了 1.71 依然有问题。

**Comment by xiaofsu** [comment]
好家伙，我没关clashX，但是我看大佬们说好了，我就感觉我的也好了。

**Comment by xuhongyux** [comment]
关了，好了

**Comment by CharlotteZeng** [comment]
哈哈哈 我也是 关了代理好了

**Comment by CharlotteZeng** [comment]
哈哈哈 我也是 关了代理好了``

**Comment by 2bestnick** [comment]
由于邮箱总是会受到提醒，看来有不少小伙伴有这个问题，我还是说一下我的成功解决方案吧。
1. 用低版本calshx
2. 在clashx配置文件夹中增加proxyIgnoreList.plist，配置内容如下
`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<array>
	<string>192.168.0.0/16</string>
	<string>10.0.0.0/8</string>
	<string>172.16.0.0/12</string>
	<string>127.0.0.1</string>
	<string>localhost</string>
	<string>*.local</string>
	<string>*.crashlytics.com</string>
	<string>my-custom-site.com</string>
	<string>192.168.1.101</string>
	<string>192.168.1.42</string>
</array>
</plist>
`
最后两个地址是我常用环境的nacos地址，你可以替换成你的；至于最原始的proxyIgnoreList.plist文件内容是啥样我也忘了，当时也是google之后通过实践发现这种方法确实有效。

**Comment by SorryArtorius** [comment]
**确实是代理的问题，如果nacos本机访问出现502情况 建议是将代理关闭再访问 **

**Comment by zhaoljhub** [comment]
针对CFW（clash for windows）导致的该问题，我找到一个处理办法，在 settings -> system proxy -> Bypass domain/IPNet 。点击编辑，在末尾追加你的nacos的domain即可，这样就不需要关闭VPN了，在关闭和打开之间来回切换。
我一开始就是配置的这里，但是我我想偷懒采用了正则匹配：（\*.myconpany.\*） 以为这样可以解决所有的地址问题，结果就出现了上诉错误，但是某些nacos server的服务API又是可以的，这点我很疑惑。对了我的clashX版本是0.20.22。

**Comment by WhiteStart** [comment]
关闭了代理显示检查拼写错误

**Comment by Gretycos** [comment]
消费者的配置写 spring.cloud.nacos.discovery.ip-type=IPv4

**Comment by WhiteStart** [comment]
2023-07-07 15:45:48    ,--,:  : |                                           Nacos 2.0.3
2023-07-07 15:45:48 ,`--.'`|  ' :                       ,---.               Running in stand alone mode, All function modules
2023-07-07 15:45:48 |   :  :  | |                      '   ,'\   .--.--.    Port: 8848
2023-07-07 15:45:48 :   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: 1
2023-07-07 15:45:48 |   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://nacos:8848/nacos/index.html
2023-07-07 15:45:48 '   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_
2023-07-07 15:45:48 |   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io
2023-07-07 15:45:48 '   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \
2023-07-07 15:45:48 |   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  /
2023-07-07 15:45:48 '   : |     ;  :   .'   \   :    : `----'  '--'.     /
2023-07-07 15:45:48 ;   |.'     |  ,     .-./\   \  /            `--'---'
2023-07-07 15:45:48 '---'        `--`---'     `----'
2023-07-07 15:45:48 

根据这个网址访问不到，只有(http://localhost:8848/nacos/index.html)才能访问
