### ISSUE TITLE
failed to req API:doctor-register:8848/nacos/v1/ns/service/list. code: 500 msg: java.net.SocketException:Unexpected end of file from server

### ISSUE THREAD

**Issue by kevin-onepiece** [alibaba/nacos#6481]
**Describe the bug**
M1 使用转译的jdk，启动nacos单机模式，可以启动成功，注册会报500，如下，昨天前天用的还好好的，今天就不行，

**Expected behavior**
正常使用
**Acutally behavior**
### java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/service/list after all servers([doctor-register:8848]) tried: failed to req API:doctor-register:8848/nacos/v1/ns/service/list. code:500 msg: java.net.SocketException: Unexpected end of file from server
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:464)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:430)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:376)
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:358)
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:334)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:440)
	at com.alibaba.cloud.nacos.discovery.NacosDiscoveryClient.getServices(NacosDiscoveryClient.java:108)
	at org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient.getServices(CompositeDiscoveryClient.java:67)
	at org.springframework.cloud.client.discovery.health.DiscoveryClientHealthIndicator.health(DiscoveryClientHealthIndicator.java:69)
	at org.springframework.cloud.client.discovery.health.DiscoveryCompositeHealthContributor.lambda$asHealthIndicator$0(DiscoveryCompositeHealthContributor.java:77)
	at org.springframework.boot.actuate.health.HealthIndicator.getHealth(HealthIndicator.java:37)
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:81)
	at org.springframework.boot.actuate.health.HealthEndpoint.getHealth(HealthEndpoint.java:38)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:108)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:119)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:105)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getAggregateHealth(HealthEndpointSupport.java:119)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getContribution(HealthEndpointSupport.java:105)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:83)
	at org.springframework.boot.actuate.health.HealthEndpointSupport.getHealth(HealthEndpointSupport.java:70)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:75)
	at org.springframework.boot.actuate.health.HealthEndpoint.health(HealthEndpoint.java:65)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
	at org.springframework.boot.actuate.endpoint.invoke.reflect.ReflectiveOperationInvoker.invoke(ReflectiveOperationInvoker.java:77)
	at org.springframework.boot.actuate.endpoint.annotation.AbstractDiscoveredOperation.invoke(AbstractDiscoveredOperation.java:60)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:121)
	at org.springframework.boot.actuate.endpoint.jmx.EndpointMBean.invoke(EndpointMBean.java:96)
	at com.sun.jmx.interceptor.DefaultMBeanServerInterceptor.invoke(DefaultMBeanServerInterceptor.java:819)
	at com.sun.jmx.mbeanserver.JmxMBeanServer.invoke(JmxMBeanServer.java:801)
	at javax.management.remote.rmi.RMIConnectionImpl.doOperation(RMIConnectionImpl.java:1468)
	at javax.management.remote.rmi.RMIConnectionImpl.access$300(RMIConnectionImpl.java:76)
	at javax.management.remote.rmi.RMIConnectionImpl$PrivilegedOperation.run(RMIConnectionImpl.java:1309)
	at javax.management.remote.rmi.RMIConnectionImpl.doPrivilegedOperation(RMIConnectionImpl.java:1401)
	at javax.management.remote.rmi.RMIConnectionImpl.invoke(RMIConnectionImpl.java:829)
	at sun.reflect.GeneratedMethodAccessor91.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:357)
	at sun.rmi.transport.Transport$1.run(Transport.java:200)
	at sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:573)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:834)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:688)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:687)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

### access_log
0:0:0:0:0:0:0:1 - - [28/Jul/2021:14:51:58 +0800] "GET /nacos/ HTTP/1.1" 304 - 420 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 -
0:0:0:0:0:0:0:1 - - [28/Jul/2021:14:51:59 +0800] "GET /nacos/v1/console/server/state?accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYyNjg2NjUwMX0.sRkAHOfjMh_niOlf4BdTz1P1qpmRbnOSwIvQTV9surM HTTP/1.1" 200 82 390 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 -
0:0:0:0:0:0:0:1 - - [28/Jul/2021:14:51:59 +0800] "GET /nacos/console-ui/public/img/favicon.ico HTTP/1.1" 200 4286 186 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 -
0:0:0:0:0:0:0:1 - - [28/Jul/2021:14:51:59 +0800] "GET /nacos/jQuery HTTP/1.1" 404 145 545 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 -
0:0:0:0:0:0:0:1 - - [28/Jul/2021:14:51:59 +0800] "GET /nacos/iframe HTTP/1.1" 404 145 543 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 -
0:0:0:0:0:0:0:1 - - [28/Jul/2021:14:51:59 +0800] "GET /nacos/psl HTTP/1.1" 404 142 544 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 -
0:0:0:0:0:0:0:1 - - [28/Jul/2021:14:51:59 +0800] "GET /nacos/v1/console/namespaces?&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYyNjg2NjUwMX0.sRkAHOfjMh_niOlf4BdTz1P1qpmRbnOSwIvQTV9surM&namespaceId= HTTP/1.1" 200 131 824 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 -
0:0:0:0:0:0:0:1 - - [28/Jul/2021:14:52:00 +0800] "GET /nacos/page/2 HTTP/1.1" 404 145 86 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 -
0:0:0:0:0:0:0:1 - - [28/Jul/2021:14:52:00 +0800] "GET /nacos/v1/ns/catalog/services?hasIpCount=true&withInstances=false&pageNo=1&pageSize=10&serviceNameParam=&groupNameParam=&accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTYyNjg2NjUwMX0.sRkAHOfjMh_niOlf4BdTz1P1qpmRbnOSwIvQTV9surM&namespaceId= HTTP/1.1" 200 39 212 Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 -

### nacos_gc.log.0.current
Java HotSpot(TM) 64-Bit Server VM (25.301-b09) for bsd-amd64 JRE (1.8.0_301-b09), built on Jun  9 2021 14:35:36 by "java_re" with gcc 4.2.1 Compatible Apple LLVM 11.0.0 (clang-1100.0.33.17)
Memory: 4k page, physical 16777216k(103752k free)

/proc/meminfo:

CommandLine flags: -XX:GCLogFileSize=104857600 -XX:InitialHeapSize=536870912 -XX:MaxHeapSize=536870912 -XX:MaxNewSize=268435456 -XX:NewSize=268435456 -XX:NumberOfGCLogFiles=10 -XX:+PrintGC -XX:+PrintGCDateStamps -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseCompressedClassPointers -XX:+UseCompressedOops -XX:+UseGCLogFileRotation -XX:+UseParallelGC
2021-07-28T14:50:47.199-0800: 1.826: [GC (Allocation Failure) [PSYoungGen: 196608K->8865K(229376K)] 196608K->8873K(491520K), 0.0260353 secs] [Times: user=0.06 sys=0.02, real=0.03 secs]
2021-07-28T14:50:48.162-0800: 2.789: [GC (Allocation Failure) [PSYoungGen: 205473K->10213K(229376K)] 205481K->10229K(491520K), 0.0293803 secs] [Times: user=0.08 sys=0.02, real=0.03 secs]
2021-07-28T14:50:48.479-0800: 3.106: [GC (Metadata GC Threshold) [PSYoungGen: 79581K->6469K(229376K)] 79597K->6493K(491520K), 0.0180381 secs] [Times: user=0.06 sys=0.02, real=0.02 secs]
2021-07-28T14:50:48.497-0800: 3.125: [Full GC (Metadata GC Threshold) [PSYoungGen: 6469K->0K(229376K)] [ParOldGen: 24K->6227K(262144K)] 6493K->6227K(491520K), [Metaspace: 20655K->20654K(1069056K)], 0.0211127 secs] [Times: user=0.05 sys=0.01, real=0.02 secs]
2021-07-28T14:50:49.854-0800: 4.482: [GC (Allocation Failure) [PSYoungGen: 196608K->6096K(229376K)] 202835K->12331K(491520K), 0.0088369 secs] [Times: user=0.02 sys=0.01, real=0.01 secs]
2021-07-28T14:50:51.615-0800: 6.243: [GC (Allocation Failure) [PSYoungGen: 202704K->10740K(229376K)] 208939K->16975K(491520K), 0.0139215 secs] [Times: user=0.04 sys=0.01, real=0.01 secs]
2021-07-28T14:50:52.254-0800: 6.881: [GC (Allocation Failure) [PSYoungGen: 207348K->12772K(229888K)] 213583K->33567K(492032K), 0.0406378 secs] [Times: user=0.06 sys=0.01, real=0.04 secs]
2021-07-28T14:50:53.113-0800: 7.741: [GC (Allocation Failure) [PSYoungGen: 229860K->22516K(239616K)] 250655K->47007K(501760K), 0.0367487 secs] [Times: user=0.06 sys=0.02, real=0.04 secs]
2021-07-28T14:50:54.654-0800: 9.282: [GC (Allocation Failure) [PSYoungGen: 239604K->15572K(229376K)] 264095K->41983K(491520K), 0.0257377 secs] [Times: user=0.09 sys=0.02, real=0.03 secs]
2021-07-28T14:50:56.377-0800: 11.004: [GC (Allocation Failure) [PSYoungGen: 222420K->10240K(234496K)] 248831K->41055K(496640K), 0.0166703 secs] [Times: user=0.04 sys=0.01, real=0.02 secs]
2021-07-28T14:50:56.430-0800: 11.057: [GC (Metadata GC Threshold) [PSYoungGen: 17575K->3072K(234496K)] 48391K->37503K(496640K), 0.0038741 secs] [Times: user=0.01 sys=0.00, real=0.00 secs]
2021-07-28T14:50:56.434-0800: 11.061: [Full GC (Metadata GC Threshold) [PSYoungGen: 3072K->0K(234496K)] [ParOldGen: 34431K->18428K(262144K)] 37503K->18428K(496640K), [Metaspace: 34197K->34197K(1081344K)], 0.0590067 secs] [Times: user=0.12 sys=0.01, real=0.06 secs]
2021-07-28T14:50:58.449-0800: 13.077: [GC (Allocation Failure) [PSYoungGen: 207872K->5568K(235008K)] 226300K->24004K(497152K), 0.0069735 secs] [Times: user=0.02 sys=0.00, real=0.01 secs]
2021-07-28T14:51:00.356-0800: 14.984: [GC (Allocation Failure) [PSYoungGen: 213440K->9832K(236544K)] 231876K->31276K(498688K), 0.0141030 secs] [Times: user=0.03 sys=0.01, real=0.02 secs]
2021-07-28T14:51:02.820-0800: 17.447: [GC (Allocation Failure) [PSYoungGen: 219240K->10602K(235008K)] 240684K->34650K(497152K), 0.0150486 secs] [Times: user=0.06 sys=0.00, real=0.01 secs]
2021-07-28T14:51:04.668-0800: 19.295: [GC (Metadata GC Threshold) [PSYoungGen: 185560K->11418K(239104K)] 209608K->40545K(501248K), 0.0109760 secs] [Times: user=0.04 sys=0.00, real=0.01 secs]
2021-07-28T14:51:04.679-0800: 19.306: [Full GC (Metadata GC Threshold) [PSYoungGen: 11418K->0K(239104K)] [ParOldGen: 29126K->38526K(262144K)] 40545K->38526K(501248K), [Metaspace: 56731K->56731K(1101824K)], 0.1407525 secs] [Times: user=0.42 sys=0.05, real=0.15 secs]
2021-07-28T14:51:07.644-0800: 22.272: [GC (Allocation Failure) [PSYoungGen: 214528K->9312K(237568K)] 253054K->47838K(499712K), 0.0126740 secs] [Times: user=0.05 sys=0.00, real=0.01 secs]

**Desktop (please complete the following information):**
 - OS: macos big sur 11.2.2
 - Version [nacos-server:1.4.2和nacos-server:2.0.1]
 - JDK:1.8.0_301(x86 jdk转arm)

**Additional context**

**Comment by KomachiSion** [comment]
是否有经过网络转发？ 导致contentType变了？ 

而且之前用的好好的说明应该不是代码问题是环境问题。

或者是你的服务中有某种特殊的字符导致的问题，需要更多信息。

**Comment by kevin-onepiece** [comment]
@KomachiSion 换了梯子，然后就不行了。。。关掉梯子或者换回之前梯子就可以了
