### ISSUE TITLE
服务端集群同时重启，导致客户端无法自动注册

### ISSUE THREAD

**Issue by zyzyzy523** [alibaba/nacos#6486]
2.0.2的服务端，2.0.2的客户端，服务端部署使用k8s部署，三个节点构建集群。
当服务端三个节点同时重启后，客户端在服务端重启完成后无法自定注册到nacos，看日志显示订阅失败，和重新注册失败。日志文件如下：
07-28 16:54:54.613   --- [t.remote.worker]  : [e5f12498-4cec-4c15-9ad1-262b5c40779a] fail to connect server,after trying 34 times, last try server is {serverIp='nacos-headless', server main port=8848},error=unknown 
2021-07-28 16:54:58.231   --- [t.remote.worker]  : [e5f12498-4cec-4c15-9ad1-262b5c40779a] success to connect a server  [nacos-headless:8848],connectionId=1627462498118_10.42.3.246_47452 
2021-07-28 16:54:58.231   --- [t.remote.worker]  : [e5f12498-4cec-4c15-9ad1-262b5c40779a] Abandon prev connection ,server is  nacos-headless:8848, connectionId is 1627462395216_10.42.3.246_40074 
2021-07-28 16:54:58.232   --- [t.remote.worker]  : [e5f12498-4cec-4c15-9ad1-262b5c40779a]Notify disconnected event to listeners 
2021-07-28 16:54:58.232   --- [t.remote.worker]  : Grpc connection disconnect 
2021-07-28 16:54:58.232   --- [t.remote.worker]  : [33774bde-cbaf-4420-9f47-c1294116a0ce_config-0] success to connect a server  [nacos-headless:8848],connectionId=1627462498118_10.42.3.246_47456 
2021-07-28 16:54:58.232   --- [t.remote.worker]  : [e5f12498-4cec-4c15-9ad1-262b5c40779a]Notify connected event to listeners. 
2021-07-28 16:54:58.232   --- [t.remote.worker]  : [33774bde-cbaf-4420-9f47-c1294116a0ce_config-0] Abandon prev connection ,server is  nacos-headless:8848, connectionId is 1627462371994_10.42.3.246_38350 
2021-07-28 16:54:58.232   --- [t.remote.worker]  : Grpc re-connect, redo subscribe services 
2021-07-28 16:54:58.232   --- [t.remote.worker]  : [33774bde-cbaf-4420-9f47-c1294116a0ce_config-0]Notify disconnected event to listeners 
2021-07-28 16:54:58.233   --- [t.remote.worker]  : [33774bde-cbaf-4420-9f47-c1294116a0ce_config-0] DisConnected,clear listen context... 
2021-07-28 16:54:58.233   --- [t.remote.worker]  : [33774bde-cbaf-4420-9f47-c1294116a0ce_config-0]Notify connected event to listeners. 
2021-07-28 16:54:58.233   --- [t.remote.worker]  : [33774bde-cbaf-4420-9f47-c1294116a0ce_config-0] Connected,notify listen context... 
2021-07-28 16:54:58.760   --- [t.remote.worker]  : re subscribe service base failed 
 
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:216) ~[classes/:?] 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:172) ~[classes/:?] 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcConnectionEventListener.redoSubscribe(NamingGrpcConnectionEventListener.java:50) [classes/:?] 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcConnectionEventListener.onConnected(NamingGrpcConnectionEventListener.java:40) [classes/:?] 
	at com.alibaba.nacos.common.remote.client.RpcClient.notifyConnected(RpcClient.java:211) [nacos-client-2.0.2.jar:?] 
	at com.alibaba.nacos.common.remote.client.RpcClient$2.run(RpcClient.java:298) [nacos-client-2.0.2.jar:?] 
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?] 
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?] 
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?] 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?] 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?] 
	at java.lang.Thread.run(Thread.java:834) [?:?] 
Caused by: com.alibaba.nacos.api.exception.NacosException 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:208) ~[classes/:?] 
	... 11 more 
 
2021-07-28 16:54:58.761   --- [t.remote.worker]  : Grpc re-connect, redo register services 
2021-07-28 16:54:58.761   --- [t.remote.worker]  : [REGISTER-SERVICE] empty registering service base with instance Instance{instanceId='null', ip='10.42.3.246', port=9083, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={preserved.register.source=SPRING_CLOUD}} 
2021-07-28 16:54:59.255   --- [t.remote.worker]  : redo register for service DEFAULT_GROUP@@base, Instance{instanceId='null', ip='10.42.3.246', port=9083, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={preserved.register.source=SPRING_CLOUD}} failed 
 
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:216) ~[classes/:?] 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:102) ~[classes/:?] 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcConnectionEventListener.redoRegisterEachInstance(NamingGrpcConnectionEventListener.java:69) [classes/:?] 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcConnectionEventListener.redoRegisterEachService(NamingGrpcConnectionEventListener.java:63) [classes/:?] 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcConnectionEventListener.onConnected(NamingGrpcConnectionEventListener.java:41) [classes/:?] 
	at com.alibaba.nacos.common.remote.client.RpcClient.notifyConnected(RpcClient.java:211) [nacos-client-2.0.2.jar:?] 
	at com.alibaba.nacos.common.remote.client.RpcClient$2.run(RpcClient.java:298) [nacos-client-2.0.2.jar:?] 
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) [?:?] 
	at java.util.concurrent.FutureTask.run(FutureTask.java:264) [?:?] 
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) [?:?] 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?] 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?] 
	at java.lang.Thread.run(Thread.java:834) [?:?] 
Caused by: com.alibaba.nacos.api.exception.NacosException 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:208) ~[classes/:?] 
	... 12 more 
 
 
2021-07-28 16:55:24.389   --- [aming.updater.0]  : removed ips(1) service: DEFAULT_GROUP@@base@@DEFAULT -> [{"ip":"10.42.3.246","port":9083,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@base","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}] 
2021-07-28 16:55:24.389   --- [aming.updater.0]  : current ips:(0) service: DEFAULT_GROUP@@base@@DEFAULT -> []

**Comment by KomachiSion** [comment]
duplicate with #6142 and #6384.

BTW, restart all nodes is not right operation.
