### ISSUE TITLE
nacos1.4.2单机运行(并发数在5个)，偶发性报instance/list请求失败(500)。nacos.log日志在此时间点附近均无异常信息。

### ISSUE THREAD

**Issue by jasonhewg** [alibaba/nacos#6489]
2021-07-28 15:31:05.550 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming - [NA] failed to update serviceName: wms-hwg@@jztd-ent
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([122.9.127.251:8848]) tried: failed to req API:122.9.127.251:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:467)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:389)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:300)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:279)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:325)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)

项目中有三个同样配置的微服务，其中2个服务实例很长时间没报此异常，但第三个服务实例在间隔30min出现了上述异常信息。

**Comment by KomachiSion** [comment]
`java.net.SocketTimeoutException: connect timed out` 连接超时，说明网络可能有问题或者nacos服务端处于无法建立连接的状态。

如果其他客户端没有这个问题，那大概率就是有问题的那个节点的网络环境或者系统环境有问题。

**Comment by jasonhewg** [comment]
> `java.net.SocketTimeoutException: connect timed out` 连接超时，说明网络可能有问题或者nacos服务端处于无法建立连接的状态。
> 
> 如果其他客户端没有这个问题，那大概率就是有问题的那个节点的网络环境或者系统环境有问题。

---->关键是这三个微服务的客户端，都是在本地环境启动成功的(即同一个网络环境，只是端口不一样)，所连接的nacos服务端，是在另一台服务器上。

**Comment by realJackSun** [comment]
> > `java.net.SocketTimeoutException: connect timed out` 连接超时，说明网络可能有问题或者nacos服务端处于无法建立连接的状态。
> > 如果其他客户端没有这个问题，那大概率就是有问题的那个节点的网络环境或者系统环境有问题。
> 
> ---->关键是这三个微服务的客户端，都是在本地环境启动成功的(即同一个网络环境，只是端口不一样)，所连接的nacos服务端，是在另一台服务器上。

在客户端直接ping服务端，能ping通吗？

**Comment by jasonhewg** [comment]
客户端报连接超时的时候，也能正常ping通，telnet也可以。nacos服务端在控制台页面上，服务列表里也能看到。
另外，尝试调整了metadata相关参数值(preserved.heart.beat.interval/timeout、preserved.ip.delete.timeout)，也是会偶发性出现请求API超时(如：instance/beat、instance/list等)。

**Comment by jasonhewg** [comment]
![1627607936606_BEE3FAB9-84CE-4f7a-9CBA-6F9699C502A5](https://user-images.githubusercontent.com/88084634/127586184-d6c2fcff-9cb0-4c71-92a8-7d66edd6cb3c.png)

**Comment by realJackSun** [comment]
是的，遇到流量波峰，有可能会出现小概率的丢包。
