### ISSUE TITLE
新服务注册到nacos之后，在控制台看不到，并且nacos日志中持续抛出异常

### ISSUE THREAD

**Issue by yuzhaopeng** [alibaba/nacos#6558]
**Describe the bug**
新服务注册之后，在nacos控制台中看不到；
服务侧都是正常的，没有报错信息；
nacos日志文件中持续的有错误信息抛出，从报错信息上看是uri中包含了特殊字符导致的，但是不清楚为什么会这样；

**Expected behavior**
服务注册之后，可以在nacos控制台看到这个服务

**Acutally behavior**
新服务注册之后，在nacos控制台看不到这个服务

**How to Reproduce**
运行一段时间后出现的，暂时不清楚如何重现

**Desktop (please complete the following information):**
 - OS: [ k8s 1.17.3 ]
 - Docker Image : [ nacos/nacos-server:1.4.0 ]
 - Version [ nacos/nacos-server:1.4.0 ]
 - Module [ naming ]

**Additional context**
naming-server.log 日志文件中的异常信息如下：
``` bash
2021-08-04 11:03:02,581 ERROR [IP-DEAD] failed to delete ip automatically, ip: {"instanceId":"10.200.30.53#3014#DEFAULT#DEFAULT_GROUP@@cloudproduct-service-autoscaling","ip":"10.200.30.53","port":3014,"weight":1.0,"healthy":false,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@cloudproduct-service-autoscaling","metadata":{"preserved.register.source":"SPRING_CLOUD"},"lastBeat":1616393204476,"marked":false,"app":"unknown","instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}, error: {}

java.net.URISyntaxException: Illegal character in query at index 141: http://127.0.0.1:8848/nacos/v1/ns/instance?ephemeral=true&serviceName=DEFAULT_GROUP@@cloudproduct-service-autoscaling&port=3014&namespaceId=${REGISTER_NAMESPACE}&ip=10.200.30.53&clusterName=DEFAULT&?encoding=UTF-8&nofix=1
        at java.net.URI$Parser.fail(URI.java:2848)
        at java.net.URI$Parser.checkChars(URI.java:3021)
        at java.net.URI$Parser.parseHierarchical(URI.java:3111)
        at java.net.URI$Parser.parse(URI.java:3053)
        at java.net.URI.<init>(URI.java:588)
        at com.alibaba.nacos.common.http.HttpUtils.buildUri(HttpUtils.java:244)
        at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.execute(NacosAsyncRestTemplate.java:359)
        at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.delete(NacosAsyncRestTemplate.java:105)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpRequest(HttpClient.java:193)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpDelete(HttpClient.java:157)
        at com.alibaba.nacos.naming.healthcheck.ClientBeatCheckTask.deleteIp(ClientBeatCheckTask.java:142)
        at com.alibaba.nacos.naming.healthcheck.ClientBeatCheckTask.run(ClientBeatCheckTask.java:120)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by brotherlu-xcq** [comment]
你们的namespace有配置吗？这里取到还是填充符。
![image](https://user-images.githubusercontent.com/25661357/128163912-ebf7918b-509b-4a41-a297-86a8f4d0ae67.png)

**Comment by yuzhaopeng** [comment]
今天排查了一下是 k8s 环境导致的。

nacos 的 namespace 等信息是配置在 k8s 的 configMap 里，然后 pod 启动的时候，configMap 变量可能还没有设置到 pod 环境变量中，所以就没有拿到 namespace 变量，直接把填充符当作了 namespaceId 注册了，注册之后 nacos 控制台就看不到这个服务，然后自动删除的时候一直没法删除，就持续报异常。

还有个问题很奇怪，spring 如果找不到填充符对应的环境变量，那么这个值应该是空字符串，而不是把填充符字符串当作值，这里很奇怪，不过这应该不是 nacos 的问题了。

感谢，感谢！
