### ISSUE TITLE
部署nacos时报错

### ISSUE THREAD

**Issue by huie2018** [alibaba/nacos#6619]
操作环境：Windows Sever2012 64位；jdk 1.8 64位
分别部署了nacos1.4.0以及nacos2.0.1;启动时都提示如下错误
<img width="505" alt="1" src="https://user-images.githubusercontent.com/40845091/128966221-effdb655-0539-4812-8928-1d0571ff46ff.png">

**Comment by brotherlu-xcq** [comment]
你可以参照这个https://github.com/alibaba/nacos/issues/4336 尝试解决一下

**Comment by huie2018** [comment]
完整日志
```
Error starting ApplicationContext. To display the conditions report re-run your
application with 'debug' enabled.

2021-08-11 10:23:36,134 ERROR Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating
 bean with name 'instanceOperatorClientImpl' defined in URL [jar:file:/D:/qms-wx
/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.2.jar!/com/alibaba
/nacos/naming/core/InstanceOperatorClientImpl.class]: Unsatisfied dependency exp
ressed through constructor parameter 1; nested exception is org.springframework.
beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'cli
entOperationServiceProxy' defined in URL [jar:file:/D:/qms-wx/nacos/target/nacos
-server.jar!/BOOT-INF/lib/nacos-naming-2.0.2.jar!/com/alibaba/nacos/naming/core/
v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed
through constructor parameter 1; nested exception is org.springframework.beans.f
actory.BeanCreationException: Error creating bean with name 'persistentClientOpe
rationServiceImpl' defined in URL [jar:file:/D:/qms-wx/nacos/target/nacos-server
.jar!/BOOT-INF/lib/nacos-naming-2.0.2.jar!/com/alibaba/nacos/naming/core/v2/serv
ice/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via con
structor failed; nested exception is org.springframework.beans.BeanInstantiation
Exception: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.
PersistentClientOperationServiceImpl]: Constructor threw exception; nested excep
tion is java.lang.UnsatisfiedLinkError: C:\Users\qmsadmin\AppData\Local\Temp\lib
rocksdbjni7907214632176776528.dll: Can't find dependent libraries
        at org.springframework.beans.factory.support.ConstructorResolver.createA
rgumentArray(ConstructorResolver.java:769)
        at org.springframework.beans.factory.support.ConstructorResolver.autowir
eConstructor(ConstructorResolver.java:218)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:514)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$
doGetBean$0(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:319)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
preInstantiateSingletons(DefaultListableBeanFactory.java:866)
        at org.springframework.context.support.AbstractApplicationContext.finish
BeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refres
h(AbstractApplicationContext.java:550)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicat
ionContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.
java:744)
        at org.springframework.boot.SpringApplication.refreshContext(SpringAppli
cation.java:391)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:312)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1215)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java
:1204)
        at com.alibaba.nacos.Nacos.main(Nacos.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.
java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAcces
sorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner
.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLau
ncher.java:467)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Err
or creating bean with name 'clientOperationServiceProxy' defined in URL [jar:fil
e:/D:/qms-wx/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.2.jar!
/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.class]: Un
satisfied dependency expressed through constructor parameter 1; nested exception
 is org.springframework.beans.factory.BeanCreationException: Error creating bean
 with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/D:/q
ms-wx/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.2.jar!/com/al
ibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.cla
ss]: Bean instantiation via constructor failed; nested exception is org.springfr
amework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nac
os.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructo
r threw exception; nested exception is java.lang.UnsatisfiedLinkError: C:\Users\
qmsadmin\AppData\Local\Temp\librocksdbjni7907214632176776528.dll: Can't find dep
endent libraries
        at org.springframework.beans.factory.support.ConstructorResolver.createA
rgumentArray(ConstructorResolver.java:769)
        at org.springframework.beans.factory.support.ConstructorResolver.autowir
eConstructor(ConstructorResolver.java:218)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:514)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$
doGetBean$0(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:319)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolve
Candidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
doResolveDependency(DefaultListableBeanFactory.java:1276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
resolveDependency(DefaultListableBeanFactory.java:1196)
        at org.springframework.beans.factory.support.ConstructorResolver.resolve
AutowiredArgument(ConstructorResolver.java:857)
        at org.springframework.beans.factory.support.ConstructorResolver.createA
rgumentArray(ConstructorResolver.java:760)
        ... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creati
ng bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:fil
e:/D:/qms-wx/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.2.jar!
/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceI
mpl.class]: Bean instantiation via constructor failed; nested exception is org.s
pringframework.beans.BeanInstantiationException: Failed to instantiate [com.alib
aba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Con
structor threw exception; nested exception is java.lang.UnsatisfiedLinkError: C:
\Users\qmsadmin\AppData\Local\Temp\librocksdbjni7907214632176776528.dll: Can't f
ind dependent libraries
        at org.springframework.beans.factory.support.ConstructorResolver.instant
iate(ConstructorResolver.java:304)
        at org.springframework.beans.factory.support.ConstructorResolver.autowir
eConstructor(ConstructorResolver.java:285)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBean
Factory.createBean(AbstractAutowireCapableBeanFactory.java:514)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$
doGetBean$0(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistr
y.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBe
an(AbstractBeanFactory.java:319)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean
(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolve
Candidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
doResolveDependency(DefaultListableBeanFactory.java:1276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.
resolveDependency(DefaultListableBeanFactory.java:1196)
        at org.springframework.beans.factory.support.ConstructorResolver.resolve
AutowiredArgument(ConstructorResolver.java:857)
        at org.springframework.beans.factory.support.ConstructorResolver.createA
rgumentArray(ConstructorResolver.java:760)
        ... 41 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to insta
ntiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationS
erviceImpl]: Constructor threw exception; nested exception is java.lang.Unsatisf
iedLinkError: C:\Users\qmsadmin\AppData\Local\Temp\librocksdbjni7907214632176776
528.dll: Can't find dependent libraries
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:1
87)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy
.instantiate(SimpleInstantiationStrategy.java:117)
        at org.springframework.beans.factory.support.ConstructorResolver.instant
iate(ConstructorResolver.java:300)
        ... 55 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: C:\Users\qmsadmin\AppData\Local\Temp\
librocksdbjni7907214632176776528.dll: Can't find dependent libraries
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1941)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1824)
        at java.lang.Runtime.load0(Runtime.java:809)
        at java.lang.System.load(System.java:1086)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoade
r.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:
56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.<clinit>(RocksDB
LogStorage.java:75)
        at com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory.createLogStorag
e(DefaultJRaftServiceFactory.java:50)
        at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:571)

        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:991)
        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:138)
        at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftSe
rviceFactory.java:47)
        at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:12
9)
        at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGr
oup(JRaftServer.java:268)
        at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.addRequestProce
ssors(JRaftProtocol.java:163)
        at com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperati
onServiceImpl.<init>(PersistentClientOperationServiceImpl.java:94)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstruct
orAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingC
onstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:1
75)
        ... 57 common frames omitted
```

**Comment by huie2018** [comment]
#4336 没有实际解决问题，windows server2012,英特尔E5-2690这种平台怎么容许出现兼容性问题呢

**Comment by huie2018** [comment]
windows server2012 64位+英特尔E5-2690 v3+ oracle JDK1.8.161 64位都兼容不了，虽然是开源但还是忍不住想爆粗口

**Comment by KomachiSion** [comment]
那你应该去rocksdb社区爆粗口

**Comment by huie2018** [comment]
是不是得怪英特尔造芯片时沙子没选好

**Comment by zhouwenzhe9** [comment]
此BUG为平台架构层问题，经多次实验，在安装vc++2015失败的基础上，总结出一个解决方案；解决nacos2.0.0在window server 2012 R2环境中，因平台架构缺少dll依赖的问题；
详见如下：
![image](https://user-images.githubusercontent.com/32068814/140027064-b9f3abed-cc05-47bf-a6a5-c9ab9e951a1d.png)
将此1-9安装程序顺序安装（一定要遵循顺序）将可解决此问题；
此压缩包我已存在阿里云盘，如有需要请发送邮件至13693121220@163.com
