### ISSUE TITLE
Compatibility exists between nacos and springboot

### ISSUE THREAD

**Issue by pirateskipper** [alibaba/nacos#6620]
**Describe the bug**

- `Compatibility exists between nacos-config-spring-boot-starter:0.2.7 and springboot:2.4.x`

**pom dependencies**

- `<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-starter</artifactId>
            <version>0.2.7</version>
        </dependency>`

- `<dependency>
            <groupId>com.alibaba.boot</groupId>
            <artifactId>nacos-config-spring-boot-actuator</artifactId>
            <version>0.2.7</version>
        </dependency>`

- `<parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.4.9</version>
        <relativePath/> 
    </parent>`

**Acutally behavior**

- `Caused by: java.lang.NoClassDefFoundError: org/springframework/boot/context/properties/ConfigurationBeanFactoryMetadata
	at com.alibaba.boot.nacos.config.binder.NacosBootConfigurationPropertiesBinder.<init>(NacosBootConfigurationPropertiesBinder.java:51) ~[nacos-config-spring-boot-autoconfigure-0.2.7.jar:0.2.7]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_281]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_281]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_281]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_281]
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:208) ~[spring-beans-5.3.9.jar:5.3.9]`

**Expected behavior**

- `Start completed And Start Success...`

**Comment by pirateskipper** [comment]
- `Currently it is necessary to reduce the springboot version to below 2.4.x`
