### ISSUE TITLE
An error is reported in the startup log, but it does not affect the use:could not create Vfs.Dir from url. ignoring the exception and continuing

### ISSUE THREAD

**Issue by gang0713** [alibaba/nacos#6626]
**No error is reported under win10 and error is reported under CentOS 8.3**

2021-08-11 11:09:16.093  INFO 391743 --- [           main] o.r.Reflections                          : Reflections took 30 ms to scan 1 urls, producing 3 keys and 6 values 
2021-08-11 11:09:16.133  INFO 391743 --- [           main] o.r.Reflections                          : Reflections took 26 ms to scan 1 urls, producing 4 keys and 9 values 
2021-08-11 11:09:16.155  INFO 391743 --- [           main] o.r.Reflections                          : Reflections took 20 ms to scan 1 urls, producing 3 keys and 10 values 
2021-08-11 11:09:16.197  WARN 391743 --- [           main] o.r.Reflections                          : **could not create Vfs.Dir from url. ignoring the exception and continuing**

org.reflections.ReflectionsException: could not create Vfs.Dir from url, no matching UrlType was found [file:/opt/team-boot/lib/user-5.0.0.war]
**either use fromURL(final URL url, final List<UrlType> urlTypes) or use the static setDefaultURLTypes(final List<UrlType> urlTypes) or addDefaultURLTypes(UrlType urlType) with your specialized UrlType.**
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:109) ~[reflections-0.9.11.jar!/:?]
	at org.reflections.vfs.Vfs.fromURL(Vfs.java:91) ~[reflections-0.9.11.jar!/:?]
	at org.reflections.Reflections.scan(Reflections.java:240) ~[reflections-0.9.11.jar!/:?]
	at org.reflections.Reflections.scan(Reflections.java:202) ~[reflections-0.9.11.jar!/:?]
	at org.reflections.Reflections.<init>(Reflections.java:123) ~[reflections-0.9.11.jar!/:?]
	at org.reflections.Reflections.<init>(Reflections.java:168) ~[reflections-0.9.11.jar!/:?]
	at org.reflections.Reflections.<init>(Reflections.java:141) ~[reflections-0.9.11.jar!/:?]
	at com.alibaba.nacos.api.remote.PayloadRegistry.scan(PayloadRegistry.java:56) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.api.remote.PayloadRegistry.init(PayloadRegistry.java:44) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.common.remote.client.RpcClient.<clinit>(RpcClient.java:109) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.common.remote.client.RpcClientFactory.lambda$createClient$0(RpcClientFactory.java:79) ~[nacos-client-2.0.3.jar!/:?]
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853) ~[?:1.8.0_201]
	at com.alibaba.nacos.common.remote.client.RpcClientFactory.createClient(RpcClientFactory.java:75) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.<init>(NamingGrpcClientProxy.java:87) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:77) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:95) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:81) ~[nacos-client-2.0.3.jar!/:?]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_201]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.spring.factory.CacheableEventPublishingNacosServiceFactory$NamingCreateWorker.run(CacheableEventPublishingNacosServiceFactory.java:274) ~[nacos-spring-context-1.1.1.jar!/:?]
	at com.alibaba.nacos.spring.factory.CacheableEventPublishingNacosServiceFactory$NamingCreateWorker.run(CacheableEventPublishingNacosServiceFactory.java:261) ~[nacos-spring-context-1.1.1.jar!/:?]
	at com.alibaba.nacos.spring.factory.CacheableEventPublishingNacosServiceFactory.createNamingService(CacheableEventPublishingNacosServiceFactory.java:96) ~[nacos-spring-context-1.1.1.jar!/:?]
	at com.alibaba.nacos.spring.beans.factory.annotation.NamingServiceBeanBuilder.createService(NamingServiceBeanBuilder.java:47) ~[nacos-spring-context-1.1.1.jar!/:?]
	at com.alibaba.nacos.spring.beans.factory.annotation.NamingServiceBeanBuilder.createService(NamingServiceBeanBuilder.java:32) ~[nacos-spring-context-1.1.1.jar!/:?]
	at com.alibaba.nacos.spring.beans.factory.annotation.AbstractNacosServiceBeanBuilder.build(AbstractNacosServiceBeanBuilder.java:75) ~[nacos-spring-context-1.1.1.jar!/:?]
	at com.alibaba.nacos.spring.beans.factory.annotation.AnnotationNacosInjectedBeanPostProcessor.doGetInjectedBean(AnnotationNacosInjectedBeanPostProcessor.java:116) ~[nacos-spring-context-1.1.1.jar!/:?]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.getInjectedObject(AbstractAnnotationBeanPostProcessor.java:409) ~[spring-context-support-1.0.11.jar!/:?]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor$AnnotatedFieldElement.inject(AbstractAnnotationBeanPostProcessor.java:626) ~[spring-context-support-1.0.11.jar!/:?]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:119) ~[spring-beans-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at com.alibaba.spring.beans.factory.annotation.AbstractAnnotationBeanPostProcessor.postProcessPropertyValues(AbstractAnnotationBeanPostProcessor.java:179) ~[spring-context-support-1.0.11.jar!/:?]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1430) ~[spring-beans-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:593) ~[spring-beans-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:516) ~[spring-beans-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:324) ~[spring-beans-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) [spring-beans-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) [spring-beans-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) [spring-beans-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:897) [spring-beans-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:879) [spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:551) [spring-context-5.2.15.RELEASE.jar!/:5.2.15.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) [spring-boot-2.3.12.RELEASE.jar!/:2.3.12.RELEASE]
	at com.xykq.user.UserApplication.main(UserApplication.java:33) [classes!/:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_201]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_201]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) [user-5.0.0.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) [user-5.0.0.war:?]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) [user-5.0.0.war:?]
	at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) [user-5.0.0.war:?]

**Comment by KomachiSion** [comment]
Maybe Reflection can't support centos8.3， we are planning to remove the dependency.
