### ISSUE TITLE
nacos-client 2.0.2启动报错：Server check fail, please check server 我的服务器ip,port 9848 is available , error ={} 

### ISSUE THREAD

**Issue by xswby** [alibaba/nacos#6636]
日志：
```
Server check fail, please check server 47.111.189.105 ,port 9848 is available , error ={}

java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 4 milliseconds, 746150 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@26dcd8c0[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@55b8dbda, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@3b569985, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@3a022576}}}}}]]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:146)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:268)
```
下载 2.0.2安装的，单机模式，nacos-client也是 2.0.2，spring-cloud-alibaba-dependencies.version：2021.1

**Comment by brotherlu-xcq** [comment]
你可以下面检查一下你的IP和端口是不是通的？

**Comment by xswby** [comment]
telnet 8848\9848\9849 都是通的

**Comment by ngxjscj1993** [comment]
你可以试试加上 spring.cloud.nacos.discovery.server-addr 的配置

**Comment by KomachiSion** [comment]
No response from author, this problem may be solved.

**Comment by lpaz010** [comment]
@xswby 遇到同样问题，你是怎么解决的呢?

**Comment by onlyanewbie** [comment]
有找到原因吗 @xswby
