### ISSUE TITLE
standalone模式下，“下线服务“百分百发生错误

### ISSUE THREAD

**Issue by LonePheasantWarrior** [alibaba/nacos#6669]
Caused by: com.alibaba.nacos.consistency.exception.ConsistencyException: com.alibaba.nacos.core.distributed.raft.exception.NoLeaderException: The Raft Group [naming_instance_metadata] did not find the Leader node
        at com.alibaba.nacos.core.distributed.raft.utils.FailoverClosureImpl.run(FailoverClosureImpl.java:60)
        at com.alibaba.nacos.core.distributed.raft.JRaftServer.invokeToLeader(JRaftServer.java:455)
        at com.alibaba.nacos.core.distributed.raft.JRaftServer.commit(JRaftServer.java:363)
        at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.writeAsync(JRaftProtocol.java:186)
        at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.write(JRaftProtocol.java:179)

**Comment by LonePheasantWarrior** [comment]
问题已经被解决，方案来自
https://github.com/alibaba/nacos/issues/6408#issuecomment-886314022

解决方法
停止集群，然后清理nacos/data/protocol目录

具体错误原因见日志
alipay-jraft.log和protocol-raft.log
