### ISSUE TITLE
LocalConfigInfoProcessor write file error with windows char ':'

### ISSUE THREAD

**Issue by torna-group** [alibaba/nacos#6700]
**Describe the bug**
I use spring cloud alibaba, dubbo2.7.8+nacos1.4.1, dubbo metadata save in nacos, dataId like "com.xx.api.XXService::provider:xx"

But save file error, because the filename is dataId.

```java

    public static void saveSnapshot(String envName, String dataId, String group, String tenant, String config) {
        if (SnapShotSwitch.getIsSnapShot()) {
            File file = getSnapshotFile(envName, dataId, group, tenant);
            if (null == config) {
                try {
                    IoUtils.delete(file);
                } catch (IOException var9) {
                    LOGGER.error("[" + envName + "] delete snapshot error, " + file, var9);
                }
            } else {
                try {
                    File parentFile = file.getParentFile();
                    if (!parentFile.exists()) {
                        boolean isMdOk = parentFile.mkdirs();
                        if (!isMdOk) {
                            LOGGER.error("[{}] save snapshot error", envName);
                        }
                    }

                    if (JvmUtil.isMultiInstance()) {
                        ConcurrentDiskUtil.writeFileContent(file, config, "UTF-8");
                    } else {
                       // here caught the error, the filename is dataId which has ':' char
                        IoUtils.writeStringToFile(file, config, "UTF-8");
                    }
                } catch (IOException var8) {
                    LOGGER.error("[" + envName + "] save snapshot error, " + file, var8);
                }
            }

        }
    }
```

error detail:

```
java.io.FileNotFoundException: C:\Users\xx\nacos\config\fixed-11.22.115.111_8848_nacos\snapshot\dubbo\com.xx.xx.service.CommandService:1.0.1::provider:command (文件名、目录名或卷标语法不正确。)
	at java.io.FileOutputStream.open0(Native Method) ~[na:1.8.0_251]
	at java.io.FileOutputStream.open(FileOutputStream.java:270) ~[na:1.8.0_251]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213) ~[na:1.8.0_251]
	at java.io.FileOutputStream.<init>(FileOutputStream.java:162) ~[na:1.8.0_251]
	at com.alibaba.nacos.common.utils.IoUtils.writeStringToFile(IoUtils.java:113) ~[nacos-common-1.4.1.jar:na]

```

pom version 

```xml
<java.version>1.8</java.version>
        <!-- springboot 版本-->
        <spring-boot.version>2.3.2.RELEASE</spring-boot.version>
        <!-- spring cloud 版本 -->
        <spring-cloud.version>Hoxton.SR8</spring-cloud.version>
        <!-- spring cloud alibaba 版本 -->
        <spring-cloud-alibaba.version>2.2.5.RELEASE</spring-cloud-alibaba.version>
        <dubbo.version>2.7.8</dubbo.version>
```

**Comment by brotherlu-xcq** [comment]
this problem like https://github.com/alibaba/nacos/issues/6702

**Comment by brotherlu-xcq** [comment]
@KomachiSion I think if we want to support the symbol `:` in dataId, we must replace it when we use it to create the cache file. #6702 also have this problem.

**Comment by KomachiSion** [comment]
This is window problem? window file system not support `:` , if we want fix it, only fix windows os. other os can support `:` and will has cache file with `:`.

**Comment by nopol** [comment]
> This is window problem? window file system not support `:` , if we want fix it, only fix windows os. other os can support `:` and will has cache file with `:`.

yes, windows os will caught this error.
