### ISSUE TITLE
[NA] error while receiving push data java.net.SocketException: Socket closed

### ISSUE THREAD

**Issue by yongnights** [alibaba/nacos#6713]
nacos版本：2.0.1

SpringCloud项目，组件版本如下：
    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <maven.compiler.target>1.8</maven.compiler.target>
        <java.version>1.8</java.version>
        <argLine>-Dfile.encoding=utf-8</argLine>
        <spring-boot.version>2.3.2.RELEASE</spring-boot.version>
        <spring.cloud.version>Hoxton.SR8</spring.cloud.version>
        <spring-cloud-alibaba.version>2.2.3.RELEASE</spring-cloud-alibaba.version>
    </properties>

在windows系统下使用命令：mvn clean install -DskipTests=true编译后，使用命令：java -jar app.jar  --spring.profiles.active=test --spring.cloud.nacos.config.server-addr=192.168.1.218:8848 --spring.cloud.nacos.discovery.server-addr=192.168.1.218:8848 运行，没有报错信息，项目可以正常启动。

但是在linux系统下使用同样的命令：mvn clean install -DskipTests=true编译后，使用命令：java -jar app.jar  --spring.profiles.active=test --spring.cloud.nacos.config.server-addr=192.168.1.218:8848 --spring.cloud.nacos.discovery.server-addr=192.168.1.218:8848 运行，有报错信息，项目无法启动，报错信息如下：
[requestId:defaultrequestId]  2021-08-16 10:55:15.857 ERROR com.alibaba.nacos.client.naming Line:110 - [NA] error while receiving push data
java.net.SocketException: Socket closed
	at java.net.PlainDatagramSocketImpl.receive0(Native Method)
	at java.net.AbstractPlainDatagramSocketImpl.receive(AbstractPlainDatagramSocketImpl.java:143)
	at java.net.DatagramSocket.receive(DatagramSocket.java:812)
	at com.alibaba.nacos.client.naming.core.PushReceiver.run(PushReceiver.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

除了这个项目外，还有其他项目在使用这个nacos，在linux系统下编译运行，都没有出现这个报错信息。

请问这个问题有啥解决办法没？

**Comment by KomachiSion** [comment]
升级一下nacos-client的版本试试。这个报错应该不是原因，有其他原因导致了连接被关闭，所以才报了这个错。

**Comment by KomachiSion** [comment]
No more response
