### ISSUE TITLE
用nacos作为注册中心时，服务提供方ip有变化后，客户端仍旧调用之前的ip地址

### ISSUE THREAD

**Issue by tangtaotao2021** [alibaba/nacos#6729]
**运行环境**
nacos服务端：2.0.2
nacos客户端 ：1.3.3
dubbo：2.7.12

问题
应用是采用k8s部署，服务端之前IP地址是172.18.2.28，重启后注册地址更改为 172.18.0.174，查看客户端日志有收到 地址变为172.18.0.174记录，但是再次调用时依旧使用的172.18.2.28调用，导致报错。
<html>
<body>

2021-08-24 00:32:13.368 [com.alibaba.nacos.naming.push.receiver] INFO  com.alibaba.nacos.client.naming:228 - current ips:(1) service: product team@@srm-account -> [{"instanceId":"172.18.0.174#11000#DEFAULT#product team@@srm-account","ip":"172.18.0.174","port":11000,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"product team@@srm-account","metadata":{"dubbo.metadata-service.urls":"[ \"dubbo://172.18.0.174:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=srm-account&bind.ip=172.18.0.174&bind.port=20880&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=srm-account&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=7&qos.enable=false&release=2.7.12&revision=2.2.3.RELEASE&service.name=ServiceBean:srm-account/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0&side=provider&timestamp=1629736306804&version=1.0.0\" ]","preserved.register.source":"SPRING_CLOUD","dubbo.protocols.dubbo.port":"20880"},"ipDeleteTimeout":30000,"instanceHeartBeatTimeOut":15000,"instanceHeartBeatInterval":5000}]
--

</body>
</html>
2021-08-24 00:33:00.547 [dubbo-client-idleCheck-thread-1] ERROR o.a.d.r.exchange.support.header.ReconnectTimerTask:51 -  [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [/172.18.2.91:54346 -> /172.18.2.28:20880]], dubbo version: 2.7.12, current host: 172.18.2.91
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://172.18.2.28:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=srm-message&bind.ip=172.18.2.28&bind.port=20880&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&group=srm-account&heartbeat=60000&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=7&qos.enable=false&register.ip=172.18.2.91&release=2.7.12&remote.application=srm-account&revision=2.2.3.RELEASE&service.name=ServiceBean:srm-account/com.alibaba.cloud.dubbo.service.DubboMetadataService:1.0.0&side=consumer&sticky=false&timeout=5000&timestamp=1629732897642&version=1.0.0) failed to connect to server /172.18.2.28:20880 client-side timeout 3000ms (elapsed: 3001ms) from netty client 172.18.2.91 using dubbo version 2.7.12
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:174)
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:198)
	at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:254)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:166)
	at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49)
	at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727)
	at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449)
	at java.lang.Thread.run(Thread.java:748)

**Comment by KomachiSion** [comment]
`查看客户端日志有收到 地址变为172.18.0.174记录` 那就说明nacos没有问题，是dubbo没有使用新地址，请提交issue到dubbo社区询问。
