### ISSUE TITLE
spring boot优雅关闭等待nacos关闭超时

### ISSUE THREAD

**Issue by VitZhou** [alibaba/nacos#6779]
**Describe the bug**

2021-08-31 16:00:58.463  INFO [scrm,,,] 20243 --- [extShutdownHook] io.undertow                              : stopping server: Undertow - 2.1.7.Final
2021-08-31 16:00:58.516  INFO [scrm,,,] 20243 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'Nacos-Watch-Task-Scheduler'
2021-08-31 16:00:58.521  WARN [scrm,,,] 20243 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor  : Failed to stop bean 'nacosWatch'

java.lang.IllegalStateException: UT015023: This Context has been already destroyed
	at io.undertow.servlet.spec.ServletContextImpl.getDeploymentInfo(ServletContextImpl.java:211)
	at io.undertow.servlet.spec.ServletContextImpl.getInitParameterNames(ServletContextImpl.java:438)
	at org.springframework.web.context.support.ServletContextPropertySource.getPropertyNames(ServletContextPropertySource.java:41)
	at com.alibaba.spring.util.PropertySourcesUtils.getPropertyNames(PropertySourcesUtils.java:130)
	at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:103)
	at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:57)
	at com.alibaba.cloud.nacos.NacosDiscoveryProperties.enrichNacosDiscoveryProperties(NacosDiscoveryProperties.java:616)
	at com.alibaba.cloud.nacos.NacosDiscoveryProperties.getNacosProperties(NacosDiscoveryProperties.java:610)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:166)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:98)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:238)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:377)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:210)
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:128)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1022)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:170)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:949)

2021-08-31 16:01:12.501  INFO [scrm,,,] 20243 --- [g.push.receiver] com.alibaba.nacos.client.naming          : received push data: {"type":"dom","data":"{\"hosts\":[{\"ip\":\"192.168.31.77\",\"port\":8585,\"valid\":true,\"healthy\":true,\"marked\":false,\"instanceId\":\"192.168.31.77#8585#DEFAULT#DEFAULT_GROUP@@scrm\",\"metadata\":{\"preserved.register.source\":\"SPRING_CLOUD\",\"user.name\":\"admin\",\"user.password\":\"admin\"},\"enabled\":true,\"weight\":1.0,\"clusterName\":\"DEFAULT\",\"serviceName\":\"DEFAULT_GROUP@@scrm\",\"ephemeral\":true}],\"dom\":\"DEFAULT_GROUP@@scrm\",\"name\":\"DEFAULT_GROUP@@scrm\",\"cacheMillis\":10000,\"lastRefTime\":1630396872495,\"checksum\":\"4f604a4a4a905d83f4643dc9ad6e68c7\",\"useSpecifiedURL\":false,\"clusters\":\"DEFAULT\",\"env\":\"\",\"metadata\":{}}","lastRefTime":452600839725868} from /192.168.31.179
2021-08-31 16:01:28.522  INFO [scrm,,,] 20243 --- [extShutdownHook] o.s.c.support.DefaultLifecycleProcessor  : Failed to shut down 1 bean with phase value 0 within timeout of 30000ms: [nacosWatch]

**Desktop (please complete the following information):**
 - OS: macos
 - Version server:1.4.1 client: clients: 2.2.3-release
 - Module naming&config
 - SDK spring-cloud-alibaba-nacos

**Comment by KomachiSion** [comment]
you need move issue to spring cloud community
