### ISSUE TITLE
Request nacos server failed and Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily

### ISSUE THREAD

**Issue by beijing-penguin** [alibaba/nacos#6791]
**Describe the bug**
NACOS 2.0.3
spring pom.xml
```xml
<dependency>
	<groupId>com.alibaba.nacos</groupId>
	<artifactId>nacos-client</artifactId>
	<version>2.0.3</version>
</dependency>
<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
	<version>2.2.6.RELEASE</version>
</dependency>
<!-- https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-discovery -->
<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
	<version>2.2.6.RELEASE</version>
</dependency>
```

**Expected behavior**
i hope run success..

**Acutally behavior**
A clear and concise description of what you actually to happen.

```
2021-09-03 00:27:14.526 [main] INFO  o.s.s.c.ExecutorConfigurationSupport.initialize(ExecutorConfigurationSupport.java:181) - Initializing ExecutorService 'taskScheduler'
2021-09-03 00:27:14.673 [main] INFO  o.s.i.endpoint.EventDrivenConsumer.logComponentSubscriptionEvent(EventDrivenConsumer.java:107) - Adding {logging-channel-adapter:_org.springframework.integration.errorLogger} as a subscriber to the 'errorChannel' channel
2021-09-03 00:27:14.674 [main] INFO  o.s.i.c.AbstractSubscribableChannel.adjustCounterIfNecessary(AbstractSubscribableChannel.java:64) - Channel 'mall-manager-1.errorChannel' has 1 subscriber(s).
2021-09-03 00:27:14.674 [main] INFO  o.s.i.endpoint.AbstractEndpoint.start(AbstractEndpoint.java:159) - started bean '_org.springframework.integration.errorLogger'
2021-09-03 00:27:14.710 [main] ERROR c.a.cloud.nacos.discovery.NacosWatch.start(NacosWatch.java:135) - namingService subscribe failed, properties:NacosDiscoveryProperties{serverAddr='172.16.51.187:18848,172.16.51.187:28848,172.16.51.187:38848', endpoint='', namespace='local', watchDelay=30000, logName='', service='mall-manager', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.232.1', networkInterface='', port=-1, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, failFast=true}
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:279)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:227)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:212)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:147)
	at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:393)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.start(NacosWatch.java:131)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
	at com.emar.mall.manager.MallManagerApplication.main(MallManagerApplication.java:23)
Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html.
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:271)
	... 20 common frames omitted
```

**How to Reproduce**
use nacos2.0.3  zip version.
1. Modify cluster.config
172.16.51.187:18848
172.16.51.187:28848
172.16.51.187:38848

2.i have make application.config prefect(config mysql)......modify application.properties
```
*************** Config Module Related Configurations ***************#
### If use MySQL as datasource:
spring.datasource.platform=mysql

### Count of DB:
db.num=1

### Connect URL of DB:
db.url.0=jdbc:mysql://localhost:5701/dc_test?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
db.user.0=xxxxxxx
db.password.0=xxxxxxxx
```

3.cmd run three local node nacos（only Different ports）
>>>>>>startup.cmd

![image](https://user-images.githubusercontent.com/10703753/131883394-9cb59ada-030c-4a89-b966-968a09a2a349.png)

**Desktop (please complete the following information):**
 - OS: [win10]
 - Version [e.g. nacos-server 2.0.3, nacos-client 2.0.3]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]
```xml
<dependency>
	<groupId>com.alibaba.nacos</groupId>
	<artifactId>nacos-client</artifactId>
	<version>2.0.3</version>
</dependency>
<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-config</artifactId>
	<version>2.2.6.RELEASE</version>
</dependency>
<!-- https://mvnrepository.com/artifact/com.alibaba.cloud/spring-cloud-starter-alibaba-nacos-discovery -->
<dependency>
	<groupId>com.alibaba.cloud</groupId>
	<artifactId>spring-cloud-starter-alibaba-nacos-discovery</artifactId>
	<version>2.2.6.RELEASE</version>
</dependency>
```
**Additional context**

**Comment by KomachiSion** [comment]
As you see `Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily` . 
your cluster is not upgrade finished, can't accept gRPC request.

Please see upgrade document to upgrade your cluster.
