### ISSUE TITLE
nacos集群，重启网络后程序报错

### ISSUE THREAD

**Issue by ai641843909** [alibaba/nacos#6852]
之前是正常的，使用了service network restart 命令重启网络后，程序会报错，如下：

**Describe the bug**
[2021-09-09 17:14:16.734 PM] 172.22.1.135 cngc-cloud-application ERROR ,, com.alibaba.nacos.naming.beat.sender com.alibaba.nacos.client.naming [CLIENT-BEAT] failed to send beat: {"cluster":"DEFAULT","ip":"172.22.1.135","metadata":{"preserved.register.source":"SPRING_CLOUD"},"period":5000,"port":8098,"scheduled":false,"serviceName":"DEFAULT_GROUP@@cngc-cloud-application","stopped":false,"weight":1.0}
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/beat after all servers([nacos-headless:8848]) tried: failed to req API:nacos-headless:8848/nacos/v1/ns/instance/beat. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:464)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:309)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:92)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2021-09-09 17:14:24.799 PM] 172.22.1.135 cngc-cloud-application WARN  ,, com.alibaba.nacos.client.naming.updater com.alibaba.nacos.client.naming failed to request http://nacos-headless:8848/nacos/v1/ns/instance/list?healthyOnly=false&namespaceId=cngc-cloud-seata&clientIP=172.22.1.135&serviceName=SEATA_GROUP%40%40seata-server&udpPort=54328&encoding=UTF-8&clusters=default from 172.23.14.205
[2021-09-09 17:14:24.799 PM] 172.22.1.135 cngc-cloud-application ERROR ,, com.alibaba.nacos.client.naming.updater com.alibaba.nacos.client.naming [NA] failed to request 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:89)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:410)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:451)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:297)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:270)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2021-09-09 17:14:24.801 PM] 172.22.1.135 cngc-cloud-application ERROR ,, com.alibaba.nacos.client.naming.updater com.alibaba.nacos.client.naming request nacos-headless:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:nacos-headless:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:424)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:451)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:297)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:270)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2021-09-09 17:14:24.801 PM] 172.22.1.135 cngc-cloud-application ERROR ,, com.alibaba.nacos.client.naming.updater com.alibaba.nacos.client.naming [NA] failed to update serviceName: SEATA_GROUP@@seata-server
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([nacos-headless:8848]) tried: failed to req API:nacos-headless:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:464)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:297)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:270)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2021-09-09 17:14:37.804 PM] 172.22.1.135 cngc-cloud-application WARN  ,, com.alibaba.nacos.client.naming.updater com.alibaba.nacos.client.naming failed to request http://nacos-headless:8848/nacos/v1/ns/instance/list?healthyOnly=false&namespaceId=cngc-cloud-seata&clientIP=172.22.1.135&serviceName=SEATA_GROUP%40%40seata-server&udpPort=54328&encoding=UTF-8&clusters=default from 172.23.14.205
[2021-09-09 17:14:37.804 PM] 172.22.1.135 cngc-cloud-application ERROR ,, com.alibaba.nacos.client.naming.updater com.alibaba.nacos.client.naming [NA] failed to request 
java.net.SocketTimeoutException: connect timed out
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:607)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:89)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:410)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:451)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:297)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:270)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2021-09-09 17:14:37.804 PM] 172.22.1.135 cngc-cloud-application ERROR ,, com.alibaba.nacos.client.naming.updater com.alibaba.nacos.client.naming request nacos-headless:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:nacos-headless:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:424)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:451)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:297)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:270)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
[2021-09-09 17:14:37.804 PM] 172.22.1.135 cngc-cloud-application ERROR ,, com.alibaba.nacos.client.naming.updater com.alibaba.nacos.client.naming [NA] failed to update serviceName: SEATA_GROUP@@seata-server
java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance/list after all servers([nacos-headless:8848]) tried: failed to req API:nacos-headless:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException: connect timed out
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:464)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:386)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:297)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:270)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:315)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by li-xiao-shuang** [comment]
是否持续报错？有可能是重启网卡导致的网络中断，此时发送的请求就会超时

**Comment by ai641843909** [comment]
对，一直不断的报错。这个应该怎么处理呢？

**Comment by li-xiao-shuang** [comment]
> 对，一直不断的报错。这个应该怎么处理呢？

有尝试过重启下nacos集群嘛？

**Comment by ai641843909** [comment]
有，重装nacos，重启nacos和微服务，都不行，依然还是持续报这个错

**Comment by li-xiao-shuang** [comment]
麻烦提供一下Nacos客户端、服务端版本号，和接入的方式

**Comment by ai641843909** [comment]
客户端：springCloud 2.X
服务端：1.4.2
接入方式：k8s-nacos，参考的官网k8s的方式安装

**Comment by li-xiao-shuang** [comment]
> 客户端：springCloud 2.X
> 服务端：1.4.2
> 接入方式：k8s-nacos，参考的官网k8s的方式安装

1.手动访问一下报错api看看是否报错
2.k8s集群中的应用有没有暴露在外部网络
3.查看该pod所在主机这个端口是否可以访问 curl -v http://$POD_IP:端口/ping
 暴露服务的方式可参考 https://juejin.cn/post/6844903654391021581

**Comment by realJackSun** [comment]
Long time no response from author, close.
