### ISSUE TITLE
在做单元测试的时候可不可以设置禁用nacos？

### ISSUE THREAD

**Issue by liugh1974** [alibaba/nacos#6875]
做单元测试的时候，不需要依赖远程nacos上的配置，全部都是本地的测试配置，因此可不可以在单元测试的时候把nacos禁用掉？

我尝试配置 
spring.cloud.nacos.discovery.registerEnabled: false
spring.cloud.nacos.config.enabled: false 
但是都不生效。

在单元测试的时候一直在请求远程服务器，甚至把单元测试的线程都阻塞了。如下日志：
2021-09-14 14:47:57.799 +0800 [TID: N/A] [com.alibaba.nacos.client.Worker.longPolling.fixed-nacos_8848] ERROR c.a.n.c.config.impl.ClientWorker:550 - longPolling error : 
java.net.UnknownHostException: nacos
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:196)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:162)

**Comment by lpaz010** [comment]
用mock吧

**Comment by liugh1974** [comment]
> 用mock吧

请问怎样去mock它了，搜了一阵，没有搜到相关的东西。能给个例子不？谢谢！

**Comment by li-xiao-shuang** [comment]
单元测试中用到Nacos了嘛？  还是启动环境的时候报错的？

**Comment by lpaz010** [comment]
这是一段来自Nacos配置中心模块的单元测试，并加了点注释，供您参考：
```
/**
 * 感谢Nacos！
 * 这是官方单元测试（NacosConfigServiceTest）的片段，使用Mockito
 */
public class NacosConfigSrvTest {

    private NacosConfigService nacosConfigService;

    private ClientWorker mockWoker;

    private void setFinal(Field field, Object ins, Object newValue) throws Exception {
        field.setAccessible(true);
        field.set(ins, newValue);
        field.setAccessible(false);

    }

    @Before
    public void mock() throws Exception {
        // 提供构造方法必要的参数properties
        final Properties properties = new Properties();
        properties.put("serverAddr", "1.1.1.1");
        // 测试NacosConfigService
        nacosConfigService = new NacosConfigService(properties);
        // 模拟NacosConfigService类中的worker字段，即初始化它
        mockWoker = Mockito.mock(ClientWorker.class);
        setFinal(NacosConfigService.class.getDeclaredField("worker"), nacosConfigService, mockWoker);
    }

    /**
     * 获取配置
     */
    @Test
    public void testGetConfig() throws NacosException {
        final String dataId = "1";
        final String group = "2";
        final String tenant = "";
        final int timeout = 3000;
        ConfigResponse response = new ConfigResponse();
        response.setContent("aa");
        response.setConfigType("bb");
        // 模拟mockWorker的行为，即模拟NacosConfigService之外的服务，这样就不会有网络请求了
        Mockito.when(mockWoker.getServerConfig(dataId, group, "", timeout, false)).thenReturn(response);
        // 测试
        final String config = nacosConfigService.getConfig(dataId, group, timeout);
        // 断言
        Assert.assertEquals("aa", config);
        Mockito.verify(mockWoker, Mockito.times(1)).getServerConfig(dataId, group, tenant, timeout, false);

    }
}
```
