### ISSUE TITLE
no com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll_x86_64

### ISSUE THREAD

**Issue by pinxiong** [alibaba/nacos#6915]
**Describe the bug**

Using nacos as registry center, I found `java.lang.UnsatisfiedLinkError: no com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll_x86_64` error

**Expected behavior**

Everything is OK

**Acutally behavior**

`java.lang.UnsatisfiedLinkError: no com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll_x86_64` 

**How to Reproduce**
1. Deploy Dubbo3.x in Ubuntu
2. Startup nacos-server
3. Startup Dubbo
4. Run testcases

**Desktop (please complete the following information):**
 - OS: [Ubuntu]
 - Version [18.04.5]
 - SDK [nacos-client-2.0.3]

**Additional context**
```java
2021-09-18T07:29:50.9282348Z 07:29:50.723 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): unavailable
2021-09-18T07:29:50.9287439Z 07:29:50.724 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
2021-09-18T07:29:50.9292244Z 07:29:50.724 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - maxDirectMemory: 536870912 bytes (maybe)
2021-09-18T07:29:50.9297145Z 07:29:50.725 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
2021-09-18T07:29:50.9302116Z 07:29:50.725 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
2021-09-18T07:29:50.9310558Z 07:29:50.727 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.maxDirectMemory: -1 bytes
2021-09-18T07:29:50.9316503Z 07:29:50.731 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.uninitializedArrayAllocationThreshold: -1
2021-09-18T07:29:50.9344649Z 07:29:50.732 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.CleanerJava9 - java.nio.ByteBuffer.cleaner(): available
2021-09-18T07:29:50.9349770Z 07:29:50.736 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
2021-09-18T07:29:50.9354913Z 07:29:50.776 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
2021-09-18T07:29:50.9360364Z 07:29:50.778 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.deleteLibAfterLoading: true
2021-09-18T07:29:50.9366151Z 07:29:50.778 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - -Dio.netty.native.tryPatchShadedId: true
2021-09-18T07:29:50.9371871Z 07:29:50.788 [main] DEBUG com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader - Unable to load the library 'com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll_x86_64', trying other loading mechanism.
2021-09-18T07:29:50.9375720Z java.lang.UnsatisfiedLinkError: no com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll_x86_64 in java.library.path: [/usr/java/packages/lib, /usr/lib64, /lib64, /lib, /usr/lib]
2021-09-18T07:29:50.9377506Z 	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2670)
2021-09-18T07:29:50.9378825Z 	at java.base/java.lang.Runtime.loadLibrary0(Runtime.java:830)
2021-09-18T07:29:50.9379988Z 	at java.base/java.lang.System.loadLibrary(System.java:1873)
2021-09-18T07:29:50.9383370Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
2021-09-18T07:29:50.9387336Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-18T07:29:50.9389833Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-18T07:29:50.9392751Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-18T07:29:50.9395076Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-18T07:29:50.9398083Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
2021-09-18T07:29:50.9473980Z 	at java.base/java.security.AccessController.doPrivileged(Native Method)
2021-09-18T07:29:50.9478306Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
2021-09-18T07:29:50.9484876Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
2021-09-18T07:29:50.9490458Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
2021-09-18T07:29:50.9495544Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:186)
2021-09-18T07:29:50.9499805Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.epoll.Native.<clinit>(Native.java:57)
2021-09-18T07:29:50.9503354Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
2021-09-18T07:29:50.9505574Z 	at java.base/java.lang.Class.forName0(Native Method)
2021-09-18T07:29:50.9506527Z 	at java.base/java.lang.Class.forName(Class.java:315)
2021-09-18T07:29:50.9508960Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.Utils.isEpollAvailable(Utils.java:220)
2021-09-18T07:29:50.9512374Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:92)
2021-09-18T07:29:50.9516106Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:72)
2021-09-18T07:29:50.9565889Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
2021-09-18T07:29:50.9571707Z 	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
2021-09-18T07:29:50.9576211Z 	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
2021-09-18T07:29:50.9579629Z 	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewChannelStub(GrpcClient.java:97)
2021-09-18T07:29:50.9583094Z 	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:265)
2021-09-18T07:29:50.9585951Z 	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:394)
2021-09-18T07:29:50.9588916Z 	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.start(NamingGrpcClientProxy.java:96)
2021-09-18T07:29:50.9592441Z 	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.<init>(NamingGrpcClientProxy.java:89)
2021-09-18T07:29:50.9595850Z 	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:77)
2021-09-18T07:29:50.9598865Z 	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:95)
2021-09-18T07:29:50.9601430Z 	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:81)
2021-09-18T07:29:50.9604045Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
2021-09-18T07:29:50.9607227Z 	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
2021-09-18T07:29:50.9610967Z 	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
2021-09-18T07:29:50.9613822Z 	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
2021-09-18T07:29:50.9616073Z 	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59)
2021-09-18T07:29:50.9618637Z 	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77)
2021-09-18T07:29:50.9622214Z 	at org.apache.dubbo.registry.nacos.util.NacosNamingServiceUtils.createNamingService(NacosNamingServiceUtils.java:101)
2021-09-18T07:29:50.9626142Z 	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.doInitialize(NacosServiceDiscovery.java:61)
2021-09-18T07:29:50.9629560Z 	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.initialize(AbstractServiceDiscovery.java:38)
2021-09-18T07:29:50.9633211Z 	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.lambda$createServiceDiscovery$0(ServiceDiscoveryRegistry.java:115)
2021-09-18T07:29:50.9636331Z 	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46)
2021-09-18T07:29:50.9639857Z 	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.createServiceDiscovery(ServiceDiscoveryRegistry.java:115)
2021-09-18T07:29:50.9705830Z 	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.<init>(ServiceDiscoveryRegistry.java:91)
2021-09-18T07:29:50.9709695Z 	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistryFactory.createRegistry(ServiceDiscoveryRegistryFactory.java:35)
2021-09-18T07:29:50.9713938Z 	at org.apache.dubbo.registry.support.AbstractRegistryFactory.getRegistry(AbstractRegistryFactory.java:86)
2021-09-18T07:29:50.9717244Z 	at org.apache.dubbo.registry.RegistryFactoryWrapper.getRegistry(RegistryFactoryWrapper.java:33)
2021-09-18T07:29:50.9719797Z 	at org.apache.dubbo.registry.RegistryFactory$Adaptive.getRegistry(RegistryFactory$Adaptive.java)
2021-09-18T07:29:50.9722574Z 	at org.apache.dubbo.registry.integration.RegistryProtocol.getRegistry(RegistryProtocol.java:386)
2021-09-18T07:29:50.9725578Z 	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:237)
2021-09-18T07:29:50.9728715Z 	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64)
2021-09-18T07:29:50.9731833Z 	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58)
2021-09-18T07:29:50.9735190Z 	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47)
2021-09-18T07:29:50.9737668Z 	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java)
2021-09-18T07:29:50.9739394Z 	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:650)
2021-09-18T07:29:50.9741506Z 	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:624)
2021-09-18T07:29:50.9743560Z 	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:584)
2021-09-18T07:29:50.9745969Z 	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:415)
2021-09-18T07:29:50.9748465Z 	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:403)
2021-09-18T07:29:50.9750472Z 	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:378)
2021-09-18T07:29:50.9752449Z 	at org.apache.dubbo.config.ServiceConfig.exportOnly(ServiceConfig.java:254)
2021-09-18T07:29:50.9843675Z 	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:257)
2021-09-18T07:29:50.9847796Z 	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:229)
2021-09-18T07:29:50.9850940Z 	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:122)
2021-09-18T07:29:50.9855095Z 	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:103)
2021-09-18T07:29:50.9860355Z 	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:96)
2021-09-18T07:29:50.9867586Z 	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:42)
2021-09-18T07:29:50.9873026Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
2021-09-18T07:29:50.9878492Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
2021-09-18T07:29:50.9883782Z 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
2021-09-18T07:29:50.9888509Z 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404)
2021-09-18T07:29:50.9892780Z 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361)
2021-09-18T07:29:50.9923703Z 	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898)
2021-09-18T07:29:50.9927864Z 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554)
2021-09-18T07:29:50.9932085Z 	at org.springframework.context.annotation.AnnotationConfigApplicationContext.<init>(AnnotationConfigApplicationContext.java:89)
2021-09-18T07:29:50.9935704Z 	at org.apache.dubbo.config.spring.JavaConfigBeanTest.testBean(JavaConfigBeanTest.java:77)
2021-09-18T07:29:50.9938516Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2021-09-18T07:29:50.9940999Z 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2021-09-18T07:29:50.9943926Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-09-18T07:29:50.9946105Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-09-18T07:29:50.9948066Z 	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:686)
2021-09-18T07:29:50.9950966Z 	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
2021-09-18T07:29:50.9954472Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
2021-09-18T07:29:50.9957787Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
2021-09-18T07:29:50.9961265Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
2021-09-18T07:29:50.9964971Z 	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
2021-09-18T07:29:50.9968345Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
2021-09-18T07:29:50.9971379Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
2021-09-18T07:29:50.9974696Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
2021-09-18T07:29:50.9978453Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
2021-09-18T07:29:50.9982452Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
2021-09-18T07:29:50.9986439Z 	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
2021-09-18T07:29:50.9989652Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
2021-09-18T07:29:50.9992387Z 	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
2021-09-18T07:29:50.9995646Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6(TestMethodTestDescriptor.java:205)
2021-09-18T07:29:50.9999416Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-09-18T07:29:51.0084119Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:201)
2021-09-18T07:29:51.0088145Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:137)
2021-09-18T07:29:51.0092110Z 	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:71)
2021-09-18T07:29:51.0095596Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
2021-09-18T07:29:51.0099120Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-09-18T07:29:51.0161727Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2021-09-18T07:29:51.0164699Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2021-09-18T07:29:51.0167568Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2021-09-18T07:29:51.0171435Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-09-18T07:29:51.0175298Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2021-09-18T07:29:51.0181422Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2021-09-18T07:29:51.0183580Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-09-18T07:29:51.0187588Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-09-18T07:29:51.0192721Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2021-09-18T07:29:51.0196217Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-09-18T07:29:51.0199859Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2021-09-18T07:29:51.0202992Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2021-09-18T07:29:51.0205832Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2021-09-18T07:29:51.0209398Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-09-18T07:29:51.0213257Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2021-09-18T07:29:51.0216775Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2021-09-18T07:29:51.0218879Z 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
2021-09-18T07:29:51.0222898Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
2021-09-18T07:29:51.0228082Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
2021-09-18T07:29:51.0231576Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-09-18T07:29:51.0235208Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
2021-09-18T07:29:51.0238038Z 	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
2021-09-18T07:29:51.0303039Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
2021-09-18T07:29:51.0306799Z 	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
2021-09-18T07:29:51.0310620Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
2021-09-18T07:29:51.0314193Z 	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
2021-09-18T07:29:51.0319047Z 	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
2021-09-18T07:29:51.0324797Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
2021-09-18T07:29:51.0329094Z 	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
2021-09-18T07:29:51.0332438Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:220)
2021-09-18T07:29:51.0334936Z 	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:188)
2021-09-18T07:29:51.0337944Z 	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:202)
2021-09-18T07:29:51.0340938Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:181)
2021-09-18T07:29:51.0343436Z 	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
2021-09-18T07:29:51.0372360Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invokeAllTests(JUnitPlatformProvider.java:150)
2021-09-18T07:29:51.0376170Z 	at org.apache.maven.surefire.junitplatform.JUnitPlatformProvider.invoke(JUnitPlatformProvider.java:120)
2021-09-18T07:29:51.0380164Z 	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:384)
2021-09-18T07:29:51.0383622Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:345)
2021-09-18T07:29:51.0386217Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:126)
2021-09-18T07:29:51.0388395Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:418)
```

**Comment by complone** [comment]
I think this is the same as netty [issue-7319](https://github.com/netty/netty/issues/7319)

i will solve it

**Comment by KomachiSion** [comment]
@complone It seems only a debug log for netty. We has no neccessary to fix it. I think set the logger level to Info is ok.
