### ISSUE TITLE
nacos client 端 grpc调用异常 UNAVAILABLE: HTTP/2 error code: NO_ERROR Received Goaway

### ISSUE THREAD

**Issue by laohuihui178** [alibaba/nacos#6969]
nacos 客户端 grpc调用异常 ,异常信息如下:

Caused by: com.alibaba.nacos.api.exception.NacosException: java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
Received Goaway
app_requested
	at com.alibaba.nacos.common.remote.client.grpc.GrpcConnection.request(GrpcConnection.java:78) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:657) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:635) ~[nacos-client-2.0.3.jar!/:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:269) ~[nacos-client-2.0.3.jar!/:?]
	... 10 more
Caused by: java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: HTTP/2 error code: NO_ERROR
这可能是什么原因引起的

**Comment by laohuihui178** [comment]
nacos是以standalone模式运行,  出现一分钟异常, 过后又自动恢复了

**Comment by yourkiwifruit** [comment]
@laohuihui178 我觉得你可以借鉴这篇文章https://blog.csdn.net/qq_25112523/article/details/84887092，可能是文章说的第二种情况，你可能需要检查下你的client和server端的grpc版本，是不是使用了不同的版本

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
