### ISSUE TITLE
nacos2.0.3  use mysql error：UnsatisfiedDependencyException No DataSource set

### ISSUE THREAD

**Issue by blank-1** [alibaba/nacos#6975]
2021-09-24 16:31:50,867 ERROR Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.0.3.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
        at com.alibaba.nacos.Nacos.main(Nacos.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
No DataSource set

**Comment by blank-1** [comment]
![2021-09-24_16-37-31](https://user-images.githubusercontent.com/30788027/134644729-f373f0e9-0edf-4518-afc8-703537b748f5.png)

**Comment by zhourong119** [comment]
我mysql 5.7.33 碰到了，但是mysql 8.0.21 没问题

**Comment by Comven** [comment]
一种解释是将url中的连接时间和超时时间设置长一点 
![image](https://user-images.githubusercontent.com/8464801/135386899-a05bad65-8908-4a84-a1f5-a3eff8083d84.png)
比如1000->10000；3000->30000

**Comment by blank-1** [comment]
![2021-09-30_14-06-47](https://user-images.githubusercontent.com/30788027/135396621-81f01d48-fa4a-47aa-baff-4f09fe749bd5.png)
![2021-09-30_14-07-08](https://user-images.githubusercontent.com/30788027/135396633-370438a1-e39a-4982-9246-65fac03b120e.png)

**Comment by Hxhzfd** [comment]
解决了没？

**Comment by JamesLiAndroid** [comment]
同，mysql用的8.0.26，问题日志一模一样，我这边设置了三个节点做集群！

**Comment by hyt05** [comment]
同，mysql用的8.0.27，问题日志一模一样，

**Comment by xuhn** [comment]
同，mysql用的8.0.27，问题日志一模一样

**Comment by xuhn** [comment]
已解决，我的mysql密码里 有特殊字符=，加上单引号后解决

**Comment by jingzhao-self** [comment]
我是用的自建cluster，使用外部mysql的方式。经测试，导致此问题的可能性有：
1，mysql中的数据库：注意数据库的版本信息，用master分支可能会有问题，需要与nacos的版本对应，如2.0.4；https://github.com/alibaba/nacos/blob/2.0.4/distribution/conf/nacos-mysql.sql
2，mysql中的数据库名：数据库表说明中使用了nacos_config作为数据库名，但很多连接mysql的配置中都是写成了nacos，这也将导致如上错误；
3，我的密码也是包含复杂字符的，在使用application.properties中的db.password.0=不能加单引号或者双引号；

nacos太坑了，文档老，配置不统一。。。

**Comment by einsteinarbert** [comment]
hello, I has been successfully with this guide:
> https://nacos.io/en-us/docs/v2/quickstart/quick-start-docker.html
```bash
git clone https://github.com/nacos-group/nacos-docker.git
cd nacos-docker
docker-compose -f example/standalone-derby.yaml up
```
