### ISSUE TITLE
failed to request

### ISSUE THREAD

**Issue by Kesling515** [alibaba/nacos#6986]
使用Nacos，开启了认证模式，启动后服务能注册成功并且可读取到nacos的配置，但是过一会儿就会报数据库通话连接失败
 
`19:24:08.593 [com.alibaba.nacos.naming.beat.sender] ERROR c.a.n.client.naming - [callServer,617] - [NA] failed to request
com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Sun Sep 26 19:24:08 CST 2021</div><div>There was an unexpected error (type=Internal Server Error, status=500).</div><div>Server failed,PreparedStatementCallback; SQL [SELECT count(*) FROM roles WHERE  username= ? ]; Communications link failure

The last packet successfully received from the server was 3,123 milliseconds ago. The last packet sent successfully to the server was 3,130 milliseconds ago.; nested exception is com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure

The last packet successfully received from the server was 3,123 milliseconds ago. The last packet sent successfully to the server was 3,130 milliseconds ago.</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:433)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by lpaz010** [comment]
@Kesling515 会不会是数据库网络不通，看见`Communications link failure`

**Comment by Jennyfriel** [comment]
Good day,

 Am sorry hear that before all of you disappointed i have problem in my mobile and also internet connection. I try my best to communicate to help others to contact me, i want to help new entrepreneur to succeed day by day covid. Me and my children, family i fight alone i choise to face it and help it. I uploaded apps you can easy to contact me connect. Am sorry! 

  Much better to easy communication with transaction

**Comment by Kesling515** [comment]
> @Kesling515 会不会是数据库网络不通，看见`Communications link failure`

哈喽，应该不是数据库网络不通，我之前是通过docker部署的nacos报了这个错误，最后下载程序包运行nacos就没报过这个错误了

**Comment by Kesling515** [comment]
@lpaz010 哈喽，应该不是数据库网络不通，我之前是通过docker部署的nacos报了这个错误，最后下载程序包运行nacos就没报过这个错误了

**Comment by Jennyfriel** [comment]
Good day,

  Please can you translate this?? How i can help you?
