### ISSUE TITLE
something about token expired

### ISSUE THREAD

**Issue by zjg1993** [alibaba/nacos#6995]
my service is running! but once an error occurred! Then all down,i dont know why
![image](https://user-images.githubusercontent.com/20152153/134839663-8b60992b-539d-4672-9923-6010c4f89f36.png)

**Comment by realJackSun** [comment]
Which version of nacos?(Both client and server)

**Comment by zjg1993** [comment]
both 1.4.1

**Comment by zjg1993** [comment]
who know it ?

**Comment by samuel072** [comment]
Me too. Who solved it

**Comment by ConnorLH** [comment]
same problem,  server:1.4.0, client:1.3.3
```
com.alibaba.cloud.nacos.discovery.NacosDiscoveryClient:70 : get service name from nacos server fail,
ErrCode:500, ErrMsg:failed to req API:/nacos/v1/ns/service/list after all servers([172.16.1.15:8848, 172.16.1.16:8848, 172.16.1.7:8848]) tried: ErrCode:403, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Jan 21 09:31:50 CST 2022</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>token expired!</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:552)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:474)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:492)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:480)
	at com.alibaba.cloud.nacos.discovery.NacosServiceDiscovery.getServices(NacosServiceDiscovery.java:69)
	at com.alibaba.cloud.nacos.discovery.NacosDiscoveryClient.getServices(NacosDiscoveryClient.java:67)
	at org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient.getServices(CompositeDiscoveryClient.java:67)
	at org.springframework.cloud.client.discovery.health.DiscoveryClientHealthIndicator.health(DiscoveryClientHealthIndicator.java:69)
```

**Comment by qngl** [comment]
Nacos v2.0.4

`
2022-08-22 02:02:10.409 ERROR 21540 --- [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming          : [NA] failed to request

com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Mon Aug 22 07:02:12 CST 2022</div><div>There was an unexpected error (type=Forbidden, status=403).</div><div>token expired!</div></body></html>
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
        at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:433)
        at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:748)

`

**Comment by alexhaoxuan** [comment]
The 2. x Nacos source code is analyzed. The validity period of Nacos account password authentication is only 5 hours. 403 will appear after the service time expires. It is recommended to configure the secret key authentication method

> Nacos v2.0.4
> 
> ` 2022-08-22 02:02:10.409 错误 21540 --- [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming : [NA] 请求失败
> 
> com.alibaba.nacos.api.exception.NacosException:
> 
> # 白标错误页面
> 此应用程序没有针对 /error 的显式映射，因此您将其视为后备。
> 
> 2022 年 8 月 22 日星期一 07:02:12 CST
> 出现意外错误（类型=Forbidden，状态=403）。
> 令牌过期！
> 
> 在 com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615)
> 在 com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
> 在 com.alibaba .nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
> 在 com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:433)
> 在 com.alibaba.nacos.client .naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167)
> 在 java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
> 在 java.util.concurrent.FutureTask.run(FutureTask.java :266)
> 在 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
> 在 java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
> 在 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
> 在 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor .java:617)
> 在 java.lang.Thread.run(Thread.java:748)
> `

**Comment by KomachiSion** [comment]
newest version should have solved this problem.
