### ISSUE TITLE
The client discovers the service from the registry and fails to call /api/srvIPXT when the client returns updateServiceNow().

### ISSUE THREAD

**Issue by wy82623** [alibaba/nacos#703]
调用/api/srvIPXT时，发现其参数中dom总是为localhost，这个东西好像时RibbonClientConfiguration里面的name属性，取值来自${ribbon.client.name}，导致报如下错误：
	`2019-01-24 17:35:57.509 ERROR [service-hi,,,] 5576 --- [.naming.updater] com.alibaba.nacos.client.naming          : [] [] [NA] failed to update serviceName: localhost

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([218.61.208.170:8081]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429) [nacos-client-0.6.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_101]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_101]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_101]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_101]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_101]`

是我工程里缺少什么配置么？还是哪有问题呢？

**Comment by nkorange** [comment]
This is a SpringCloud bug, please go to https://github.com/spring-cloud-incubator/spring-cloud-alibaba/issues to submit your problem.
