### ISSUE TITLE
打开文件过多

### ISSUE THREAD

**Issue by aliujb** [alibaba/nacos#7102]
报错日志如下，不知道是什么原因导致的：
2021-10-15 16:55:22.045 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming:548 - request: /nacos/v1/ns/instance/list failed, servers: [192.168.1.199:8848], code: 500, msg: Too many open files
2021-10-15 16:55:30.039 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming:613 - [NA] failed to request
java.net.SocketException: Too many open files
        at java.net.Socket.createImpl(Socket.java:478)
        at java.net.Socket.connect(Socket.java:605)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
        at sun.net.www.http.HttpClient.New(HttpClient.java:339)
        at sun.net.www.http.HttpClient.New(HttpClient.java:357)
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1226)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1162)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1056)
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:990)
        at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:109)
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482)
        at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427)
        at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:599)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
        at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
        at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400)
        at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:339)
        at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:420)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-10-15 16:55:30.039 [com.alibaba.nacos.client.naming.updater] ERROR com.alibaba.nacos.client.naming:613 - [NA] failed to request

**Comment by onewe** [comment]
@aliujb Which version?

**Comment by onewe** [comment]
Can you describe this problem for more details?

**Comment by wangdongyun** [comment]
我今天也是出现了这个问题，看上去很奇怪，
复现的场景是3节点部署，我关闭了一个节点，执行 systemctl stop nacos
结果很奇怪 
java.io.IOException: Too many open files
java.io.IOException: Too many open files
java.io.IOException: Too many open files
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files

tomcat 和  grpc 都开始报这个错误

操作系统限制 
open files                      (-n) 65535

但是观察实际连接数是 5000 左右

远远不到数量

**Comment by wangdongyun** [comment]
> 我今天也是出现了这个问题，看上去很奇怪， 复现的场景是3节点部署，我关闭了一个节点，执行 systemctl stop nacos 结果很奇怪 java.io.IOException: Too many open files java.io.IOException: Too many open files java.io.IOException: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
> 
> tomcat 和 grpc 都开始报这个错误
> 
> 操作系统限制 open files (-n) 65535
> 
> 但是观察实际连接数是 5000 左右
> 
> 远远不到数量 执行命令 cat /proc/sys/fs/file-nr `5088 0 392936`

**问题找到了**
**不是nacos的问题，是 systemctl的问题，systemctl 设置的最大连接时 4k**

**Comment by whiletrue2009** [comment]
@wangdongyun   能详细点描述下吗？  systemctl  的什么设置

> > 我今天也是出现了这个问题，看上去很奇怪， 复现的场景是3节点部署，我关闭了一个节点，执行 systemctl stop nacos 结果很奇怪 java.io.IOException: Too many open files java.io.IOException: Too many open files java.io.IOException: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: accept(..) failed: Too many open files
> > tomcat 和 grpc 都开始报这个错误
> > 操作系统限制 open files (-n) 65535
> > 但是观察实际连接数是 5000 左右
> > 远远不到数量 执行命令 cat /proc/sys/fs/file-nr `5088 0 392936`
> 
> **问题找到了** **不是nacos的问题，是 systemctl的问题，systemctl 设置的最大连接时 4k**
