### ISSUE TITLE
nacos 不支持 spring native 吗？

### ISSUE THREAD

**Issue by Lee27149** [alibaba/nacos#7153]
```
2021-10-31 11:53:43.335 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed


org.springframework.context.ApplicationContextException: Failed to start bean 'nacosWatch'; nested exception is java.lang.RuntimeException: ErrCode:-400, ErrMsg:Type `com.alibaba.nacos.common.notify.DefaultPublisher` can not be instantiated reflectively as it does not have a no-parameter constructor or the no-parameter constructor has not been added explicitly to the native image.

	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[com.example.demo.DemoApplication:5.3.12]

	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[com.example.demo.DemoApplication:5.3.12]

	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[na:na]

	at java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]

	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[com.example.demo.DemoApplication:5.3.12]

	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[com.example.demo.DemoApplication:5.3.12]

	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[na:na]

	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[na:na]

	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[na:na]

	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[com.example.demo.DemoApplication:2.5.6]

	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[com.example.demo.DemoApplication:2.5.6]

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[com.example.demo.DemoApplication:2.5.6]

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[com.example.demo.DemoApplication:2.5.6]

	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[com.example.demo.DemoApplication:2.5.6]

	at com.example.demo.DemoApplication.main(DemoApplication.java:10) ~[com.example.demo.DemoApplication:na]
```

**Comment by realJackSun** [comment]
支持的，参考nacos-group下的demo

**Comment by Lee27149** [comment]
> 支持的，参考nacos-group下的demo

能发个链接吗？没找到

**Comment by 305983806** [comment]
> > 支持的，参考nacos-group下的demo
> 
> 类似这种，确定有吗？好像没找到。能发个具体链接吗？
> 
> ```
>     <dependency>
>       <groupId>org.springframework.experimental</groupId>
>       <artifactId>spring-native</artifactId>
>       <version>${spring-native.version}</version>
>     </dependency>
> ```

找到解决方案了吗？
