### ISSUE TITLE
out of date data received, old-t: 1635900357897, new-t: 0

### ISSUE THREAD

**Issue by panpengfei21** [alibaba/nacos#7168]
# mic-service logs
```
2021-11-02 20:21:03.397  WARN 1 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : [NA] failed to update serviceName: DEFAULT_GROUP@@service-base-data

java.lang.IllegalArgumentException: The IPv4 address("nacos-headless.default.svc.cluster.local") is incorrect.
	at com.alibaba.nacos.common.utils.IPUtil.splitIPPortStr(IPUtil.java:152) ~[nacos-common-1.4.1.jar!/:na]
	at com.alibaba.nacos.common.utils.IPUtil.containsPort(IPUtil.java:119) ~[nacos-common-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:595) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460) ~[nacos-client-1.4.1.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_302]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_302]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_302]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_302]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]

2021-11-02 20:21:03.400  WARN 1 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : [NA] failed to update serviceName: DEFAULT_GROUP@@service-alarm

java.lang.IllegalArgumentException: The IPv4 address("nacos-headless.default.svc.cluster.local") is incorrect.
	at com.alibaba.nacos.common.utils.IPUtil.splitIPPortStr(IPUtil.java:152) ~[nacos-common-1.4.1.jar!/:na]
	at com.alibaba.nacos.common.utils.IPUtil.containsPort(IPUtil.java:119) ~[nacos-common-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:595) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378) ~[nacos-client-1.4.1.jar!/:na]
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460) ~[nacos-client-1.4.1.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_302]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_302]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_302]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_302]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_302]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_302]

2021-11-02 20:40:57.438  WARN 1 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : out of date data received, old-t: 1635885597435, new-t: 0
2021-11-02 21:03:57.488  WARN 1 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : out of date data received, old-t: 1635886977485, new-t: 0
2021-11-02 21:34:57.553  WARN 1 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : out of date data received, old-t: 1635888837551, new-t: 0
2021-11-02 21:57:57.593  WARN 1 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : out of date data received, old-t: 1635890217591, new-t: 0
2021-11-02 22:20:57.670  WARN 1 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : out of date data received, old-t: 1635891597668, new-t: 0
2021-11-02 22:36:57.695  WARN 1 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : out of date data received, old-t: 1635892557693, new-t: 0
2021-11-02 23:29:57.778  WARN 1 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : out of date data received, old-t: 1635895737776, new-t: 0
```

# server date

## no.1
```
[root@k8smaster dnsTest]# date
2021年 11月 03日 星期三 08:58:45 CST
```
## no.2
```
[root@K8snode1 ~]# date
2021年 11月 03日 星期三 08:58:45 CST
```
## no.3
```
[root@k8snode2 ~]# date
2021年 11月 03日 星期三 08:58:46 CST
```

## no.4
```
[root@k8snode3 ~]# date
2021年 11月 03日 星期三 08:58:45 CST
```

# version

nacos-client
```
    <dependency>
      <groupId>com.alibaba.nacos</groupId>
      <artifactId>nacos-client</artifactId>
      <version>1.4.1</version>
      <scope>compile</scope>
    </dependency>
```

nacos-server
```
1.4.2
```

![截屏2021-11-03 上午9 22 22](https://user-images.githubusercontent.com/7960250/139989720-7c0f6138-4d5c-42ce-bb9a-1af0009b0ba2.png)

**Comment by CherishCai** [comment]
notify
