### ISSUE TITLE
nacos 2.0.3重启后，服务注册nacos报错，重启服务还是报相同的错

### ISSUE THREAD

**Issue by thirteen13Floor** [alibaba/nacos#7261]
**Describe the bug**
10:05:14.141 logback [main] INFO  com.alibaba.nacos.client.naming - [BEAT] adding beat: BeatInfo{port=8081, ip='10.42.14.211', weight=1.0, serviceName='DEFAULT_GROUP@@bmp-bpc.uac', cluster='DEFAULT', metadata={preserved.register.source=SPRING_CLOUD}, scheduled=false, period=5000, stopped=false} to beat map. 
10:05:14.143 logback [main] INFO  com.alibaba.nacos.client.naming - [REGISTER-SERVICE] 8d49cbbe-786f-4540-8b88-5cf4bf8ed8f9 registering service DEFAULT_GROUP@@bmp-bpc.uac with instance: Instance{instanceId='null', ip='10.42.14.211', port=8081, weight=1.0, healthy=true, enabled=true, ephemeral=true, clusterName='DEFAULT', serviceName='null', metadata={preserved.register.source=SPRING_CLOUD}} 
10:05:14.151 logback [main] ERROR com.alibaba.nacos.client.naming - [NA] failed to request 
com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Nov 19 10:05:14 CST 2021</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 172.18.0.3</div></body></html> 
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:246) 
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:212) 
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239) 
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) 
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) 
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) 
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) 
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) 
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) 
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:46) 
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) 
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) 
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) 
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) 
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) 
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) 
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) 
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) 
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) 
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) 
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) 
	at com.vgdt.bmp.bpc.uac.BootApplication.main(BootApplication.java:60) 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) 
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) 
10:05:14.158 logback [main] ERROR com.alibaba.nacos.client.naming - [NA] failed to request 
com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Nov 19 10:05:14 CST 2021</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 172.18.0.3</div></body></html> 
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:246) 
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:212) 
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239) 
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) 
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) 
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) 
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) 
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) 
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) 
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:46) 
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) 
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) 
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) 
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) 
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) 
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) 
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) 
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) 
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) 
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) 
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) 
	at com.vgdt.bmp.bpc.uac.BootApplication.main(BootApplication.java:60) 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) 
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) 
10:05:14.224 logback [main] ERROR com.alibaba.nacos.client.naming - [NA] failed to request 
com.alibaba.nacos.api.exception.NacosException: <html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Fri Nov 19 10:05:14 CST 2021</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 172.18.0.3</div></body></html> 
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) 
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:246) 
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:212) 
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239) 
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88) 
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) 
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) 
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) 
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) 
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) 
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) 
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:46) 
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) 
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) 
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) 
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) 
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) 
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) 
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) 
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) 
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) 
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) 
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) 
	at com.vgdt.bmp.bpc.uac.BootApplication.main(BootApplication.java:60) 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.base/java.lang.reflect.Method.invoke(Method.java:566) 
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) 
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) 
**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - 
 - nacos-server 2.0.3  nacos-client 1.4.1
 - 
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by MajorHe1** [comment]
错误信息是 “receive invalid redirect request from peer 172.18.0.3”
![image](https://user-images.githubusercontent.com/53824889/143370293-4140084f-422c-48c5-b78c-a54fa30ce08e.png)
要么请求包构造的有问题，header里面标识了这是nacos-server的请求，要么集群构造的有问题。
建议要么源码调试一下看问题出在哪，要么升级客户端到2.0.3再试

**Comment by evin0329** [comment]
> 错误信息是 “receive invalid redirect request from peer 172.18.0.3” ![image](https://user-images.githubusercontent.com/53824889/143370293-4140084f-422c-48c5-b78c-a54fa30ce08e.png) 要么请求包构造的有问题，header里面标识了这是nacos-server的请求，要么集群构造的有问题。 建议要么源码调试一下看问题出在哪，要么升级客户端到2.0.3再试

代码运行到这个位置是不正确的，这端代码是将当前请求交给其他服务实例处理。正常情况下应该进入下个过滤器处理。
![image](https://user-images.githubusercontent.com/35405705/180612168-92024121-0471-4828-9a67-6c30281ea458.png)

**Comment by KomachiSion** [comment]
https://github.com/alibaba/nacos/issues?q=is%3Aissue+receive+invalid+redirect+request+from+peer+is%3Aclosed

There are too many cluster deploy problem cause this exception. Please search them.
