### ISSUE TITLE
NacosConfigApplication启动时偶然出现空指针

### ISSUE THREAD

**Issue by 15057196735** [alibaba/nacos#7300]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

java.lang.NullPointerException: null
	at java.util.LinkedList$ListItr.next(LinkedList.java:893) ~[na:1.8.0_71]
	at com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher.replayDeferredEvents(DeferredApplicationEventPublisher.java:75) ~[nacos-spring-context-0.2.2-RC1.jar:na]
	at com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher.onApplicationEvent(DeferredApplicationEventPublisher.java:69) ~[nacos-spring-context-0.2.2-RC1.jar:na]
	at com.alibaba.nacos.spring.context.event.DeferredApplicationEventPublisher.onApplicationEvent(DeferredApplicationEventPublisher.java:37) ~[nacos-spring-context-0.2.2-RC1.jar:na]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:400) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:354) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:888) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:161) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:553) ~[spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243) [spring-boot-2.0.3.RELEASE.jar:2.0.3.RELEASE]
	at com.alibaba.nacos.example.spring.boot.NacosConfigApplication.main(NacosConfigApplication.java:25) [classes/:na]

### How to reproduce it (as minimally and precisely as possible)

1. 启动时报错。偶然性出现，但出现次数还是比较高，一个下午会出现五六次
2. 重新启动又好了

### Tell us your environment
Nacos 2.0.3
jdk1.8
nacos-spring-boot-config-example 0.2.0-SNAPSHOT

**Comment by SteafanMrZhou** [comment]
Anyone wants to sovle it?

**Comment by SteafanMrZhou** [comment]
Providing your service running environment,please.

**Comment by SteafanMrZhou** [comment]
首先，该错误不是发生在 Nacos-Server 中，而是发生在 nacos-spring-boot-config-example 0.2.0.RELEASE 包下
其次，根据你提供的环境，跟进源码发现，并没有发生你说的这个问题（反复启动数十次并没有发生该问题）
最后，DeferredApplicationEventPublisher 源码中并没有对 deferredEvents 这个 LinkedList 添加非空判断，针对于你这种情况可以对 deferredEvents 增加非空判断的 assert 断言，以避免该问题的发生：
![image](https://user-images.githubusercontent.com/23360739/144959831-677f12c6-a81e-4a20-945f-0748b2ac5100.png)

**Comment by SteafanMrZhou** [comment]
该 issue 应该在 nacos-group/nacos-example 下提出，稍后我在 nacos-example 下提个 PR 。

**Comment by SteafanMrZhou** [comment]
该错误不是发生在 Nacos-Server 中，而是发生在 nacos-spring-boot-config-example 0.2.0.RELEASE 包下
根据你提供的环境，跟进源码发现，并没有发生你说的这个问题（反复启动数十次并没有发生该问题）
请进一步提供问题详情信息
