### ISSUE TITLE
I encountered an error in the arm server clusterV

### ISSUE THREAD

**Issue by FrameWorkHome** [alibaba/nacos#7317]
我在arm机器上做nacos 伪集群的时候出现了问题 版本 v2.0.3 
奇怪的是我集群成功了2台第三台集群报错端口占用
![3120f69cd944f0571ade8e6e84715f7](https://user-images.githubusercontent.com/23151462/144002006-bf341439-ddc5-49c5-ade4-120b1f697d9b.png)

错误日志
`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grpcClusterServer': Invocation of init method failed; nested exception is java.io.IOException: Failed to bind
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:413)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1761)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.io.IOException: Failed to bind
	at io.grpc.netty.shaded.io.grpc.netty.NettyServer.start(NettyServer.java:246)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:184)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:90)
	at com.alibaba.nacos.core.remote.grpc.BaseGrpcServer.startServer(BaseGrpcServer.java:152)
	at com.alibaba.nacos.core.remote.BaseRpcServer.start(BaseRpcServer.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 26 common frames omitted
Caused by: java.net.BindException: 地址已在使用
	at sun.nio.ch.Net.bind0(Native Method)
	at sun.nio.ch.Net.bind(Net.java:433)
	at sun.nio.ch.Net.bind(Net.java:425)
	at sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:223)
	at io.grpc.netty.shaded.io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:132)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:551)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1345)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:503)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:488)
	at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:984)
	at io.grpc.netty.shaded.io.netty.channel.AbstractChannel.bind(AbstractChannel.java:247)
	at io.grpc.netty.shaded.io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:355)
	at io.grpc.netty.shaded.io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:416)
	at io.grpc.netty.shaded.io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:515)
	at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:918)
	at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)`

我退回到1.4.2版本在arm上伪集群成功，但是有个疑问为什么有一个节点的集群列表显示出来所有的集群信息
全部的
![image](https://user-images.githubusercontent.com/23151462/144001963-0902d989-7ba8-4d41-a717-6eb73d79d8d4.png)

部分的 
![image](https://user-images.githubusercontent.com/23151462/144001934-07d4aeb0-8c34-4e47-88e1-6c139be6fa62.png)

**Comment by kuaile-zc** [comment]
> 

Does this mean there is a problem with 2.x running on ARM machines?  
这个是不是意味着2.X版本在ARM机器上面运行存在一定的问题呢？

**Comment by FrameWorkHome** [comment]
就是 最后的异常是提示到了native方法里面，所以我没法找出原因了（其它有关的代码 我都看了下源码 看不出来写的有什么问题），不知道您 那边清楚不
但是单环境在arm上又是正常的，有什么建议的话可以告知我下 我可以去测试 排查下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年11月30日(星期二) 下午5:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/nacos] I encountered an error in the arm server clusterV (Issue #7317)





   
Does this mean there is a problem with 2.x running on ARM machines?
 这个是不是意味着2.X版本在ARM机器上面运行存在一定的问题呢？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hujun-w-2** [comment]
很显然，是因为端口的原因
nacos启动一共开启了三个端口
tomcat 8850 8852 8853
GrpcSdkServer 9850 9852 9853（这里显然已经被占用了，所以报你图上的原因）
GrpcClusterServer  9851 9853

**Comment by caomingjie-code** [comment]
关于gpcserver我看了一下，感觉设计的不太合理。端口是通过固定加法获得。应该优先配置(适合docker.网关环境），如果没有配置则选用未使用的端口。(适合无docker，网关环境)，避免固定逻辑计算端口。我想将其改造一下不知是否可以。

**Comment by FrameWorkHome** [comment]
嗯，应该优先配置，然后走相应的随机算法



---Original---
From: ***@***.***&gt;
Date: Mon, Dec 6, 2021 22:03 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [alibaba/nacos] I encountered an error in the arm server clusterV (Issue #7317)




 
关于gpcserver我看了一下，感觉设计的不太合理。端口是通过固定加法获得。应该优先配置(适合docker.网关环境），如果没有配置则选用未使用的端口。(适合无docker，网关环境)，避免固定逻辑计算端口。我想将其改造一下不知是否可以。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SteafanMrZhou** [comment]
看了下源码，获取端口并没有添加优先配置：
![image](https://user-images.githubusercontent.com/23360739/145748533-4c0865a5-73bf-48c8-b80c-bebafcf04dff.png)

**Comment by caomingjie-code** [comment]
#7361 碰到的问题一样.  看来此问题还很多。可以看一下我的修改意见 #7361
