### ISSUE TITLE
502  http://10.2.3.209:18117/nacos/v1/cs/configs/listener   

### ISSUE THREAD

**Issue by aiden-liu413** [alibaba/nacos#7331]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
java.io.IOException: Server returned HTTP response code: 502 for URL: http://10.2.3.209:18117/nacos/v1/cs/configs/listener
	at sun.reflect.GeneratedConstructorAccessor74.newInstance(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:1.8.0_282]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[?:1.8.0_282]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950) ~[?:1.8.0_282]
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945) ~[?:1.8.0_282]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_282]
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944) ~[?:1.8.0_282]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514) ~[?:1.8.0_282]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_282]
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getBody(JdkHttpClientResponse.java:64) ~[nacos-common-1.4.2.jar:?]
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handleError(AbstractResponseHandler.java:51) ~[nacos-common-1.4.2.jar:?]
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:44) ~[nacos-common-1.4.2.jar:?]
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:483) ~[nacos-common-1.4.2.jar:?]
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.postForm(NacosRestTemplate.java:407) ~[nacos-common-1.4.2.jar:?]
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpPost(ServerHttpAgent.java:155) ~[nacos-client-1.4.2.jar:?]
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpPost(MetricsHttpAgent.java:67) ~[nacos-client-1.4.2.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateConfigStr(ClientWorker.java:380) [nacos-client-1.4.2.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker.checkUpdateDataIds(ClientWorker.java:347) [nacos-client-1.4.2.jar:?]
	at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:535) [nacos-client-1.4.2.jar:?]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_282]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [?:1.8.0_282]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [?:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [?:1.8.0_282]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_282]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_282]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_282]
Caused by: java.io.IOException: Server returned HTTP response code: 502 for URL: http://10.2.3.209:18117/nacos/v1/cs/configs/listener
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1900) ~[?:1.8.0_282]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498) ~[?:1.8.0_282]
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480) ~[?:1.8.0_282]
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getStatusCode(JdkHttpClientResponse.java:79) ~[nacos-common-1.4.2.jar:?]
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:43) ~[nacos-common-1.4.2.jar:?]
	... 15 more

### Describe what you expected to happen
![图片](https://user-images.githubusercontent.com/44597411/144220988-b0bf3e56-522f-409c-9219-fb53f7c61ddd.png)

### How to reproduce it (as minimally and precisely as possible)

1. nacos server 打开权限认证开关
2. 服务添加config和discovery依赖，并启动
3. 爆出502错误。暂时看来为影响业务
4. 应该只是影响了配置的自动更新

### Tell us your environment
spring cloud alibaba 2.2.6
springboot boot 2.3.2

nacos server 2.0.3 and turn on the auth 打开权限认证

**Comment by jiakai908** [comment]
@aiden-liu413 是不是本地有vpn代理服务，关掉再测试一下

**Comment by aiden-liu413** [comment]
> @aiden-liu413 是不是本地有vpn代理服务，关掉再测试一下

还真是。🙏

**Comment by gangan0623** [comment]
> @aiden-liu413 是不是本地有vpn代理服务，关掉再测试一下

感谢!太感谢了.困扰了一整天
