### ISSUE TITLE
Run subscruber ITCase failed when use httpClientProxy only.

### ISSUE THREAD

**Issue by lpaz010** [alibaba/nacos#7344]
**Describe the bug**
Disable `grpcClientProxy`  and use `httpClientProxy` only in `NamingClientProxyDelegate`, then run `Subscribe_ITCase`，`SubscribeCluster_ITCase` failed.

**Expected behavior**
should run properly successfully.

**Acutally behavior**
1. run Subscribe_ITCase.java, result as below:
```
java.lang.IllegalArgumentException: Param 'groupName' is illegal, groupName is blank
	at com.alibaba.nacos.api.naming.utils.NamingUtils.getGroupedName(NamingUtils.java:50)
	at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:114)
	at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:40)
	at com.alibaba.nacos.common.notify.DefaultPublisher.lambda$notifySubscriber$0(DefaultPublisher.java:201)
	at com.alibaba.nacos.common.notify.DefaultPublisher.notifySubscriber(DefaultPublisher.java:208)
	at com.alibaba.nacos.common.notify.DefaultPublisher.receiveEvent(DefaultPublisher.java:192)
	at com.alibaba.nacos.common.notify.DefaultPublisher.openEventHandler(DefaultPublisher.java:118)
	at com.alibaba.nacos.common.notify.DefaultPublisher.run(DefaultPublisher.java:95)
```
2. SubscribeCluster_ITCase.java Tests failed: 2, passed: 2 of 4 tests - 38 s 406 ms
```
java.lang.IllegalArgumentException: Param 'groupName' is illegal, groupName is blank
	at com.alibaba.nacos.api.naming.utils.NamingUtils.getGroupedName(NamingUtils.java:50) ~[classes/:na]
	at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:114) ~[classes/:na]
	at com.alibaba.nacos.client.naming.event.InstancesChangeNotifier.onEvent(InstancesChangeNotifier.java:40) ~[classes/:na]
	at com.alibaba.nacos.common.notify.DefaultPublisher.lambda$notifySubscriber$0(DefaultPublisher.java:201) [classes/:na]
	at com.alibaba.nacos.common.notify.DefaultPublisher.notifySubscriber(DefaultPublisher.java:208) [classes/:na]
	at com.alibaba.nacos.common.notify.DefaultPublisher.receiveEvent(DefaultPublisher.java:192) [classes/:na]
	at com.alibaba.nacos.common.notify.DefaultPublisher.openEventHandler(DefaultPublisher.java:118) [classes/:na]
	at com.alibaba.nacos.common.notify.DefaultPublisher.run(DefaultPublisher.java:95) [classes/:na]
```

**How to Reproduce**
1. Go to 'NamingClientProxyDelegate.java'
2.  make method `NamingClientProxyDelegate#getExecuteClientProxy` always return `httpClientProxy`, like  
```
    private NamingClientProxy getExecuteClientProxy(Instance instance) {
        return httpClientProxy;
    }
```
3. remove all `grpcClientProxy` declaration and replace `grpcClientProxy` invocation, like
```
getExecuteClientProxy(null).subscribe(serviceName, groupName, clusters)
```
4. run subscriber ITCase and see error

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version: nacos-server 2.1.0-SNAPSHOT, nacos-client 2.1.0-SNAPSHOT
 - Module:  naming

**Comment by lpaz010** [comment]
### Addtional
when use `HttpClientProxy` only, i have a question how naming-server push service without using `PushReceiver`.

**How to Reproduce**
Steps to reproduce the behavior:
1. setup a naming-server running in standalone mode
2. [**IMPORTANT**] remove all `grpcClientProxy` declaration and replace `grpcClientProxy` invocation with `httpClientProxy`
3.  make break point in `PushReceiver#run()`
4. edit and debug run `App.java` under nacos-example module, like
```
public class App {
    public static void main(String[] args) throws NacosException, IOException {
        Properties properties = new Properties();
        properties.setProperty("serverAddr", "127.0.0.1:8848");
//        properties.setProperty("namespace", "quickStart");
        NamingService naming = NamingFactory.createNamingService(properties);
        naming.registerInstance("nacos.test.3", "11.11.11.11", 8888, "TEST1");
        naming.registerInstance("nacos.test.3", "2.2.2.2", 9999, "DEFAULT");
        System.out.println(naming.getAllInstances("nacos.test.3"));

        naming.subscribe("nacos.test.3", Constants.DEFAULT_GROUP, e -> {
            System.out.println("e =============== " + e);
        });

        System.in.read();
    }
}
```
5. register and deregister serviceName "nacos.test.3"
6. observe the console logs

**Comment by lpaz010** [comment]
各位大佬帮忙看下吧，@MajorHe1 何老师，新开一个ISSUE来讨论下订阅，望您指点一下。
综上：
**版本**：develop分支最新（2021/12/02）

**测试条件**：将NamingClientProxyDelegate中初始化grpcClientProxy和使用都注释/删除，所有网络请求走httpClientProxy和基于udp的PushReceiver来接收推送

**测试目的**：V2版客户端不使用长连接只使用短链接，观察短链接和长连接在订阅功能是否一致的表现，发现订阅服务那里情况并不一致。

**Comment by MajorHe1** [comment]
原因：

**Comment by lpaz010** [comment]
@MajorHe1 何老师，按照您的思路修改`NamingUtils#getGroupedName`，可以解决subscriber ITCase中的IllegalArgumentException异常，修改见下截图：
![image](https://user-images.githubusercontent.com/39051367/144568202-be56accc-26ae-4c5d-a7ec-646731951d2e.png)
其中`NamingUtils#checkServiceNameFormat`是已经存在的方法:
```
    public static void checkServiceNameFormat(String combineServiceName) {
        String[] split = combineServiceName.split(Constants.SERVICE_INFO_SPLITER);
        if (split.length <= 1) {
            throw new IllegalArgumentException(
                    "Param 'serviceName' is illegal, it should be format as 'groupName@@serviceName'");
        }
        if (split[0].isEmpty()) {
            throw new IllegalArgumentException("Param 'serviceName' is illegal, groupName can't be empty");
        }
    }
```
这种修改NamingUtils会不会影响较大 :sweat_smile:

**Comment by MajorHe1** [comment]
我觉得还好
NamingUtils#getGroupedName 方法的本意就是为了把group跟servicename拼接起来
如果发现group参数为空，但是serviceName已经包括group字段了，是想要的结果，为什么不能直接返回呢
如果这里不改，正常使用nacos client 2.x 版本应该没什么问题，但是考虑到如果有人想要直接使用这些 clientProxy（例如 spring cloud alibaba），还真有可能订阅出错。
