### ISSUE TITLE
Subscriber will be removed after more than 30 seconds when use httpClientProxy only.

### ISSUE THREAD

**Issue by lpaz010** [alibaba/nacos#7353]
**Describe the bug**
subscribers will be removed by naming-server after 30 seconds more (like 35s)  when use httpClientProxy only.

**Expected behavior**
should query subscribers properly using restful api.

**Acutally behavior**
can't find any subscribers after 35 seconds when use restful api,  some logs in naming-server as below:
```
2021-12-03 20:15:17,454 INFO Client connection 1.1.1.1:8080#true connect

2021-12-03 20:15:17,489 INFO Client change for service Service{namespace='public', group='DEFAULT_GROUP', name='jinhanC4TQt.49332.com', ephemeral=true, revision=0}, 1.1.1.1:8080#true

2021-12-03 20:15:18,266 INFO Client connection 13.2.5.53:63822#true connect

2021-12-03 20:15:18,801 INFO DEFAULT_GROUP@@jinhanC4TQt.49332.com is changed, add it to push queue.

2021-12-03 20:15:18,821 INFO serviceName: DEFAULT_GROUP@@jinhanC4TQt.49332.com changed, schedule push for: 13.2.5.53:63822, agent: Nacos-Java-Client:v2.1.0-SNAPSHOT, key: 13.2.5.53,63822,40409830316700

2021-12-03 20:15:18,822 INFO send udp packet: 13.2.5.53,63822,40409830316700

2021-12-03 20:15:18,829 INFO [PUSH-SUCC] 29ms, all delay time 561ms for subscriber 13.2.5.53, Service{namespace='public', group='DEFAULT_GROUP', name='jinhanC4TQt.49332.com', ephemeral=true, revision=1}, DataSize=1

2021-12-03 20:15:21,608 INFO Client connection 13.2.5.53:63993#true connect

2021-12-03 20:15:22,126 INFO DEFAULT_GROUP@@jinhanC4TQt.49332.com is changed, add it to push queue.

2021-12-03 20:15:22,129 INFO serviceName: DEFAULT_GROUP@@jinhanC4TQt.49332.com changed, schedule push for: 13.2.5.53:63993, agent: Nacos-Java-Client:v2.1.0-SNAPSHOT, key: 13.2.5.53,63993,40413145542200

2021-12-03 20:15:22,130 INFO send udp packet: 13.2.5.53,63993,40413145542200

2021-12-03 20:15:22,132 INFO [PUSH-SUCC] 6ms, all delay time 523ms for subscriber 13.2.5.53, Service{namespace='public', group='DEFAULT_GROUP', name='jinhanC4TQt.49332.com', ephemeral=true, revision=1}, DataSize=1

2021-12-03 20:15:52,129 INFO Client connection 13.2.5.53:63822#true disconnect, remove instances and subscribers

2021-12-03 20:15:52,131 INFO Client connection 13.2.5.53:63993#true disconnect, remove instances and subscribers

2021-12-03 20:15:56,662 INFO Client connection 20.1.1.1:8080#true connect

2021-12-03 20:15:56,663 INFO Client change for service Service{namespace='public', group='DEFAULT_GROUP', name='jinhanC4TQt.49332.com', ephemeral=true, revision=1}, 20.1.1.1:8080#true

2021-12-03 20:15:56,669 INFO Client connection 30.1.1.1:8080#true connect

2021-12-03 20:15:56,669 INFO Client change for service Service{namespace='public', group='DEFAULT_GROUP', name='jinhanC4TQt.49332.com', ephemeral=true, revision=2}, 30.1.1.1:8080#true

2021-12-03 20:15:56,670 INFO [PUSH] Task merge for Service{namespace='public', group='DEFAULT_GROUP', name='jinhanC4TQt.49332.com', ephemeral=true, revision=3}


java.lang.AssertionError: 
Expected :1
Actual   :0
<Click to see difference>


	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at com.alibaba.nacos.test.naming.Subscribe_ITCase.querySubscribers(Subscribe_ITCase.java:267)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.springframework.test.context.junit4.statements.RunBeforeTestExecutionCallbacks.evaluate(RunBeforeTestExecutionCallbacks.java:74)
	at org.springframework.test.context.junit4.statements.RunAfterTestExecutionCallbacks.evaluate(RunAfterTestExecutionCallbacks.java:84)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.springframework.test.context.junit4.statements.RunBeforeTestMethodCallbacks.evaluate(RunBeforeTestMethodCallbacks.java:75)
	at org.springframework.test.context.junit4.statements.RunAfterTestMethodCallbacks.evaluate(RunAfterTestMethodCallbacks.java:86)
	at org.springframework.test.context.junit4.statements.SpringRepeat.evaluate(SpringRepeat.java:84)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:251)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:97)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
	at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:190)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

**How to Reproduce**
1. Go to 'NamingClientProxyDelegate.java'
2.  make method `NamingClientProxyDelegate#getExecuteClientProxy` always return `httpClientProxy`, like  
```
    private NamingClientProxy getExecuteClientProxy(Instance instance) {
        return httpClientProxy;
    }
```
3. remove all `grpcClientProxy` declaration and replace `grpcClientProxy` invocation with `httpClientProxy`, like
```
getExecuteClientProxy(null).subscribe(serviceName, groupName, clusters)
```
4. edit subscriber ITCase `Subscribe_ITCase#querySubscribers()` in line 248, set client sleeping 35 seconds.
```
TimeUnit.SECONDS.sleep(35);
````
5. run test case and observe.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version: nacos-server 2.1.0-SNAPSHOT, nacos-client 2.1.0-SNAPSHOT
 - Module:  naming

**Comment by lpaz010** [comment]
望各位大佬帮忙看看:hugs:
@MajorHe1 贺老师，测到这个，是设计如此呢还是问题呀？

1. 如果需要解决，是否可以通过心跳（BeatInfo）携带UDP的ip和udpPort去刷新一下这个udp客户端（clientId）的时间戳，来保证客户端管理器不剔除这个订阅客户端；
2. 如果认为udp客户端是一个Client，那么它不应该有订阅者（订阅者发布的服务实例，订阅者的订阅者，与设计矛盾？），理解起来有点怪，这里您是怎么看的？

**Comment by MajorHe1** [comment]
你试试用 grpc  请求 订阅服务，然后sleep 35秒，看subscriber是否被移除了

**Comment by lpaz010** [comment]
@MajorHe1 贺老师，默认就是直接用grpcClientProxy实现的订阅和推送，使用grpc是没有问题的。

**Comment by MajorHe1** [comment]
我刚翻了一下源码
1、订阅者subscriber列表维护在 AbstractClient
2、AbstractClient的两个实现类 ConnnectionBasedClient 和 IpPortBasedClient 都有 expire 机制， ConnnectionBasedClient 默认过期时间3分钟，IpPortBasedClient 的过期机制相对复杂一点
![image](https://user-images.githubusercontent.com/53824889/144963366-6443934c-ded9-4b8f-a27c-ac1696996661.png)
但是可以看到都在30秒之内

所以根据你的过程，我猜想是因为 35秒的sleep， 导致client都被remove掉了，我觉得这就是设计如此。
没有理解你说的UDP客户端是什么，我理解基于http请求的就只是IpPortBasedClient

**Comment by lpaz010** [comment]
贺老师，我是这么理解的：
> UDP客户端是什么，我理解基于http请求的就只是IpPortBasedClient
1. 基于http请求的都是IpPortBasedClient，同意。
2. “UDP客户端”这里指：使用udp的ip和port初始化（组成clientId）的客户端。
 
> 因为 35秒的sleep， 导致client都被remove掉了，我觉得这就是设计如此。

根据下面源码，疑问点在：为什么创建了“UDP客户端”之后30秒又移除了。
1. 导致Restful API查询不到。
2. 30秒移除发出ClientDisconnect事件导致ClientServiceIndexesManager移除了这个udp组成的clientId, 那么最终如何组成UPD packet推送呢？
![image](https://user-images.githubusercontent.com/39051367/144966094-debd4482-ce9c-4a54-b77d-390efcd1ef38.png)

**Comment by MajorHe1** [comment]
> 为什么创建了“UDP客户端”之后30秒又移除了

IpPortBasedClient 都是有心跳检查机制的，这个跟1.x 的机制是类似的，你 sleep 了35秒，在30秒的时候跟这个client相关的instance 和 service  都被remove掉了，然后clientManager调用 isExpireClient的时候认为这个client已经过期，就调用了clientDisconnected方法，因此client也被remove掉了，所以 RestfulAPI 查不到是正常的。

>那么最终如何组成UDP packet推送呢

显然不会再推送了，这个subscriber的信息都没了。

**Comment by lpaz010** [comment]
贺老师，那就是说：
1. 那就只做一个兼容（30秒内有效）而已，后续所有的推送都走grpc了，因为grpc默认就初始化了:laughing:；
2. 使用nacos-client V2.X只使用httpClientProxy时，不支持原来的udp推送:joy:，udp推送被grpc取代了。

是这个样子吧？

**Comment by MajorHe1** [comment]
> 贺老师，那就是说：
> 
> 1. 那就只做一个兼容（30秒内有效）而已，后续所有的推送都走grpc了，因为grpc默认就初始化了😆；
> 2. 进而，使用nacos-client V2.X只使用httpClientProxy时，不支持原来的udp推送😂，udp推送被grpc取代了。
> 
> 是这个样子吧？

你的描述有点混乱，get不到你的重点

nacos-client 2.x 的版本，naming模块的subscriber 方法，默认使用的是grpcClientProxy就走的grpc协议，你强行改成  http 的才会经历 udp 推送的过程。使用http proxy 就用 udp推送，使用 grpc proxy 就用 grpc 推送，不存在谁被谁取代的问题。

**Comment by lpaz010** [comment]
> 强行改成 http 的才会经历 udp 推送的过程
对，这个issue重点就在，nacos-client 2.x强行使用http proxy时，订阅者查询（subscriber）和udp推送机制失效了:joy:

**Comment by MajorHe1** [comment]
> 对，这个issue重点就在，nacos-client 2.x强行使用http proxy时，订阅者查询（subscriber）和udp推送机制失效了😂

并没有失效，失效的原因是你sleep了35秒

**Comment by lpaz010** [comment]
好的，我再研究一下
