### ISSUE TITLE
Errors$NativeIoException:bind(..) failed: Address already in use

### ISSUE THREAD

**Issue by caomingjie-code** [alibaba/nacos#7361]
**Describe the bug**

2021-12-05 22:54:06.927  INFO 6104 --- [           main] c.a.n.c.l.StartingApplicationListener    : The server IP list of Nacos is [192.168.0.107:8847, 192.168.0.107:8848, 192.168.0.107:8849]
2021-12-05 22:54:07.928  INFO 6104 --- [acos-starting.0] c.a.n.c.l.StartingApplicationListener    : Nacos is starting...
2021-12-05 22:54:08.929  INFO 6104 --- [acos-starting.0] c.a.n.c.l.StartingApplicationListener    : Nacos is starting...
2021-12-05 22:54:09.929  INFO 6104 --- [acos-starting.0] c.a.n.c.l.StartingApplicationListener    : Nacos is starting...
start server : ServerImpl{logId=18, transportServers=[NettyServer{logId=17, address=0.0.0.0/0.0.0.0:9849}]}
start server : ServerImpl{logId=21, transportServers=[NettyServer{logId=20, address=0.0.0.0/0.0.0.0:9848}]}
2021-12-05 22:54:10.721  INFO 6104 --- [           main] c.a.n.c.l.StartingApplicationListener    : Nacos Log files: ./distribution/node2/logs
2021-12-05 22:54:10.722  INFO 6104 --- [           main] c.a.n.c.l.StartingApplicationListener    : Nacos Log files: ./distribution/node2/conf
2021-12-05 22:54:10.722  INFO 6104 --- [           main] c.a.n.c.l.StartingApplicationListener    : Nacos Log files: ./distribution/node2/data
2021-12-05 22:54:10.722 ERROR 6104 --- [           main] c.a.n.c.l.StartingApplicationListener    : Startup errors : 

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grpcSdkServer': Invocation of init method failed; nested exception is java.io.IOException: Failed to bind
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:413)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1761)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.alibaba.nacos.Nacos.main(Nacos.java:40)
Caused by: java.io.IOException: Failed to bind
	at io.grpc.netty.shaded.io.grpc.netty.NettyServer.start(NettyServer.java:246)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:184)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:90)
	at com.alibaba.nacos.core.remote.grpc.BaseGrpcServer.startServer(BaseGrpcServer.java:155)
	at com.alibaba.nacos.core.remote.BaseRpcServer.start(BaseRpcServer.java:48)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 18 common frames omitted
Caused by: io.grpc.netty.shaded.io.netty.channel.unix.Errors$NativeIoException: bind(..) failed: Address already in use

2021-12-05 22:54:12.527  WARN 6104 --- [           main] c.a.nacos.sys.file.WatchFileCenter       : [WatchFileCenter] start close
2021-12-05 22:54:12.527  WARN 6104 --- [           main] c.a.nacos.sys.file.WatchFileCenter       : [WatchFileCenter] start to shutdown this watcher which is watch : ./distribution/node2/data/loader
2021-12-05 22:54:12.527  WARN 6104 --- [           main] c.a.nacos.sys.file.WatchFileCenter       : [WatchFileCenter] start to shutdown this watcher which is watch : ./distribution/node2/conf
2021-12-05 22:54:12.527  WARN 6104 --- [           main] c.a.nacos.sys.file.WatchFileCenter       : [WatchFileCenter] start to shutdown this watcher which is watch : ./distribution/node2/data/tps
2021-12-05 22:54:12.527  WARN 6104 --- [           main] c.a.nacos.sys.file.WatchFileCenter       : [WatchFileCenter] already closed
2021-12-05 22:54:12.527  WARN 6104 --- [           main] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Start destroying Publisher
2021-12-05 22:54:12.528  WARN 6104 --- [           main] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Destruction of the end
2021-12-05 22:54:12.528 ERROR 6104 --- [           main] c.a.n.c.l.StartingApplicationListener    : Nacos failed to start, please see ./distribution/node2/logs/nacos.log for more details.

**Expected behavior**
经过阅读源码发现 RpcServer 在启动的时候是经过固定计算的获得，因此在一定的概率上会导致端口冲突。这种方式我感觉很不妥当。源码如下：
![图片](https://user-images.githubusercontent.com/63859342/144751863-acfc074a-8c27-4d5e-8af6-478086920920.png)

修改逻辑如下：
应该获取一个服务器未使用的端口进行使用，因为原接口具有密等性，因此在首次获取时进进行存储。本人使用一变量进行储存。
![图片](https://user-images.githubusercontent.com/63859342/144752736-ed403368-9871-47b6-8823-b531adb7da27.png)

修改后经过测试解决了上面的错误。如果可以我将提交一个pr请求。

**Comment by caomingjie-code** [comment]
If ok, I will submit a PR request.

**Comment by onewe** [comment]
How to set port for docker or firewall rules?

**Comment by caomingjie-code** [comment]
如果是你说的这种情况，应在在配置里明确指出这两个端口，类似与zk, 2888:3888 . 这样用户也知道这两个端口是做什么用的，否则当出现问题的时候没有明确的错误信息。只能通过源码阅读的方式来查找问题。这样会浪费很多的时间。并且在启动时应增加这两个端口的打印日志方便排查问题。 If this is what you said, you should clearly point out these two ports in the configuration, similar to ZK, 2888:3888. In this way, the user also knows what these two ports are used for. Otherwise, there is no clear error message when there is a problem. You can only find problems by reading the source code. This will waste a lot of time. In addition, the print logs of these two ports should be added during startup to facilitate troubleshooting.

**Comment by caomingjie-code** [comment]
If the port is specified, you do not need to query the free port. 如果明确指出端口则不需要查询空闲端口

**Comment by onewe** [comment]
这个就看官方咋个说了

**Comment by onewe** [comment]
这个就看官方咋个说了

**Comment by onewe** [comment]
这个就看官方咋个说了
