### ISSUE TITLE
 failed to req API:http://nacos1:8848/nacos/v1/ns/operator/cluster/state. code:500 msg: caused: unable to find local peer: nacos1:8848

### ISSUE THREAD

**Issue by wagnx** [alibaba/nacos#7384]
`java.io.IOException: failed to req API:http://nacos1:8848/nacos/v1/ns/operator/cluster/state. code:500 msg: caused: unable to find local peer: nacos1:8848, all peers: [];
        at com.alibaba.nacos.naming.misc.NamingProxy.reqCommon(NamingProxy.java:321)
        at com.alibaba.nacos.naming.cluster.ServerListManager$ServerInfoUpdater.run(ServerListManager.java:183)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2021-12-09 15:00:31,524 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: nacos1:8848

2021-12-09 15:00:32,962 INFO upgrade check result false`

**Comment by wagnx** [comment]
使用docker-compose安装的2.0.3版本，数据库mysql8

**Comment by wagnx** [comment]
启动时候日志没有报错，向nacos注册服务时候，发现只有注册到8848这个节点能够成功，但注册的服务在服务列表中看不到，节点列表中只有8848自己；另外两个nacos节点注册服务都是失败，但是在节点列表中可以看到除自己以外的其他节点，上面的日志片段来自nacos2和nacos3节点的naming-server.log文件

**Comment by onewe** [comment]
@wagnx See https://github.com/nacos-group/nacos-docker please.

**Comment by wagnx** [comment]
@onewe 就是在这里下载的，修改了docker-compose.yml和env/nacos-hostname.env文件，麻烦您帮忙看看哪里有问题
docker-compose.yml
`
version: "3"
services:
  nacos1:
     hostname: nacos1
     container_name: nacos1
     image: nacos/nacos-server:2.0.3
     volumes:
       - ./cluster-logs/nacos1:/home/nacos/logs
       - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
     ports:
       - "8848:8848"
       - "9848:9848"
       - "9849:9849"
       - "9555:9555"
     env_file:
       - ./env/nacos-hostname.env
     restart: always

  nacos2:
     hostname: nacos2
     image: nacos/nacos-server:2.0.3
     container_name: nacos2
     volumes: 
       - ./cluster-logs/nacos2:/home/nacos/logs
       - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
     ports:
       - "8850:8848"
       - "9850:9848"
       - "9851:9849"
     env_file:
       - ./env/nacos-hostname.env
     restart: always

  nacos3:
     hostname: nacos3
     image: nacos/nacos-server:2.0.3
     container_name: nacos3
     volumes: 
       - ./cluster-logs/nacos3:/home/nacos/logs
       - ./init.d/custom.properties:/home/nacos/init.d/custom.properties
     ports:
       - "8852:8848"
       - "9852:9848"
       - "9853:9849"
     env_file:
       - ./env/nacos-hostname.env
     restart: always
`
nacos-hostname.env 
`
PREFER_HOST_MODE=hostname
NACOS_SERVERS=nacos1:8848 nacos2:8848 nacos3:8848
MYSQL_SERVICE_HOST=192.168.10.46
MYSQL_SERVICE_DB_NAME=ry-config
MYSQL_SERVICE_PORT=3406
MYSQL_SERVICE_USER=root
MYSQL_SERVICE_PASSWORD=zjapl123
JVM_XMS=128m
JVM_XMX=128m
JVM_XMN=128m
JVM_MS=64m
JVM_MMS=128m
`
