### ISSUE TITLE
Request nacos server failed

### ISSUE THREAD

**Issue by zzx769394358** [alibaba/nacos#7385]
spring boot 版本：2.1.7.RELEASE
nacos-discovery-spring-boot-starter 、 nacos-config-spring-boot-starter：0.2.10 （排除nacos-client）
nacos-client: 2.0.3

启动报错：
ErrCode:500, ErrMsg:Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:279)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:146)

若将0.2.10改为0.2.8，  2.0.3改为1.4.2，并启动相应的nacos-server，项目可以正常启动

求解

**Comment by onewe** [comment]
@zzx769394358 客户端的问题,估计 https://github.com/nacos-group/nacos-spring-project 这个项目没人管了吧.

**Comment by zzx769394358** [comment]
> @zzx769394358 客户端的问题,估计 https://github.com/nacos-group/nacos-spring-project 这个项目没人管了吧.
我看了下 nacos.log，  服务端启动的时候也报了
2021-12-10 10:22:56,155 WARN Failed to scan [file:/D:/work/apache-maven-3.6.3/repository/io/grpc/grpc-netty-shaded/1.24.0/j2objc-annotations-1.1.jar] from classloader hierarchy

java.io.IOException: java.lang.reflect.InvocationTargetException

Caused by: java.nio.file.NoSuchFileException: D:\work\apache-maven-3.6.3\repository\io\grpc\grpc-netty-shaded\1.24.0\j2objc-annotations-1.1.jar
问题，但还是正常启动了



然后客户端启动时报了这个
java.net.SocketException: Connection reset
	at java.base/sun.nio.ch.SocketChannelImpl.throwConnectionReset(SocketChannelImpl.java:367)
	at java.base/sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:398)
	at io.grpc.netty.shaded.io.netty.buffer.PooledByteBuf.setBytes(PooledByteBuf.java:247)
并且启动失败

**Comment by onewe** [comment]
@zzx769394358 你 nacos 服务端是多少？？

**Comment by onewe** [comment]
只有 2.x 版本的 nacos server 端才支持 grpc 你确认一下. 并且确认一下 grpc 的端口是不是通的.

**Comment by zzx769394358** [comment]
> @zzx769394358 你 nacos 服务端是多少？？

2.0.3

**Comment by zzx769394358** [comment]
> 只有 2.x 版本的 nacos server 端才支持 grpc 你确认一下. 并且确认一下 grpc 的端口是不是通的.

server 用的是2.0.3，  然后我这个是在本地啊

**Comment by onewe** [comment]
@zzx769394358 那你再检查一下 服务端开了哪些端口. 可能是服务端的 grpc 监听端口启动失败了.

**Comment by zzx769394358** [comment]
> @zzx769394358 那你再检查一下 服务端开了哪些端口. 可能是服务端的 grpc 监听端口启动失败了.

**Comment by zzx769394358** [comment]
> @zzx769394358 那你再检查一下 服务端开了哪些端口. 可能是服务端的 grpc 监听端口启动失败了.

怎么查呀， 您方便的话加我下？ 账号数字就是q

**Comment by yangmingyuan380** [comment]
> spring boot 版本：2.1.7.RELEASE nacos-discovery-spring-boot-starter 、 nacos-config-spring-boot-starter：0.2.10 （排除nacos-client） nacos-client: 2.0.3
> 
> 启动报错： ErrCode:500, ErrMsg:Request nacos server failed: at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:279) at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129) at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115) at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95) at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:146)
> 
> 若将0.2.10改为0.2.8， 2.0.3改为1.4.2，并启动相应的nacos-server，项目可以正常启动
> 
> 求解

可以查看nacos的官方文档，https://nacos.io/zh-cn/docs/2.0.0-compatibility.html，nacos 2.0版本新增了gRPC的通信方式，因此需要增加2个端口9848和9849

**Comment by shijieyangsir** [comment]
very nice！that it helped me!
