### ISSUE TITLE
java sdk get config get error

### ISSUE THREAD

**Issue by jack-steven-root** [alibaba/nacos#7401]
**Describe the bug**
在用最新版本的nacos时，获取配置信息，结果报错
 错误信息如下：
Exception in thread "main" java.lang.ExceptionInInitializerError
	at com.alibaba.nacos.common.remote.client.RpcClientFactory.lambda$createClient$0(RpcClientFactory.java:79)
	at java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1853)
	at com.alibaba.nacos.common.remote.client.RpcClientFactory.createClient(RpcClientFactory.java:75)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:936)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1104)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.publishConfig(ClientWorker.java:1119)
	at com.alibaba.nacos.client.config.impl.ClientWorker.publishConfig(ClientWorker.java:302)
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfigInner(NacosConfigService.java:219)
	at com.alibaba.nacos.client.config.NacosConfigService.publishConfig(NacosConfigService.java:117)
	at update_task.flink_nacos.ConfigManagerTest.publishConfig(ConfigManagerTest.java:79)
	at update_task.flink_nacos.ConfigManagerTest.main(ConfigManagerTest.java:37)
Caused by: org.reflections.ReflectionsException: Scanner SubTypesScanner was not configured
	at org.reflections.Store.get(Store.java:39)
	at org.reflections.Store.get(Store.java:61)
	at org.reflections.Store.get(Store.java:46)
	at org.reflections.Store.getAll(Store.java:93)
	at org.reflections.Reflections.getSubTypesOf(Reflections.java:404)
	at com.alibaba.nacos.api.remote.PayloadRegistry.scan(PayloadRegistry.java:57)
	at com.alibaba.nacos.api.remote.PayloadRegistry.init(PayloadRegistry.java:44)
	at com.alibaba.nacos.common.remote.client.RpcClient.<clinit>(RpcClient.java:109)
	... 11 more

 请问，上面问题改如何解决
**Expected behavior**

**Acutally behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by onewe** [comment]
How to reproduce it?

**Comment by jack-steven-root** [comment]
在调用nacos cli 使用2.0.3版本，然后采用rpc 方式连接nacos，在本地运行的时候，就会出现上面的错误
















At 2021-12-16 14:15:09, "onewe" ***@***.***> wrote:

How to reproduce it?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by SUJAYJHORA** [comment]
Open

**Comment by onewe** [comment]
@jack-steven-root 试一试最新版本,`reflections `包已经被移除了.
