### ISSUE TITLE
NPE encountered during Dubbo shutdown

### ISSUE THREAD

**Issue by chickenlj** [alibaba/nacos#7411]
版本： Dubbo 3.0.4 + Nacos 2.0.3
情景：本地没启动 Nacos Server，所以 Dubbo 启动后报错进入销毁流程，销毁过程中 Nacos 报了以下NPE。

```java
[13/12/21 11:54:31:031 CST] DubboShutdownHook  WARN support.RegistryManager:  [DUBBO] java.lang.NullPointerException, dubbo version: 3.0.4, current host: 192.168.0.105
java.lang.RuntimeException: java.lang.NullPointerException
	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:48)
	at org.apache.dubbo.registry.client.ServiceDiscoveryRegistry.destroy(ServiceDiscoveryRegistry.java:277)
	at org.apache.dubbo.registry.support.RegistryManager.destroyAll(RegistryManager.java:105)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.destroyRegistries(DefaultApplicationDeployer.java:1034)
	at org.apache.dubbo.config.deploy.DefaultApplicationDeployer.postDestroy(DefaultApplicationDeployer.java:860)
	at org.apache.dubbo.rpc.model.ApplicationModel.onDestroy(ApplicationModel.java:262)
	at org.apache.dubbo.rpc.model.ScopeModel.destroy(ScopeModel.java:105)
	at org.apache.dubbo.config.DubboShutdownHook.doDestroy(DubboShutdownHook.java:67)
	at org.apache.dubbo.config.DubboShutdownHook.run(DubboShutdownHook.java:62)
Caused by: java.lang.NullPointerException
	at com.alibaba.nacos.common.remote.client.RpcClient.shutdown(RpcClient.java:465)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.shutdown(GrpcClient.java:81)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.shutdown(NamingGrpcClientProxy.java:286)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.shutdown(NamingClientProxyDelegate.java:180)
	at com.alibaba.nacos.client.naming.NacosNamingService.shutDown(NacosNamingService.java:456)
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.shutdown(NacosNamingServiceWrapper.java:84)
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.doDestroy(NacosServiceDiscovery.java:67)
	at org.apache.dubbo.registry.client.AbstractServiceDiscovery.destroy(AbstractServiceDiscovery.java:81)
	at org.apache.dubbo.common.function.ThrowableAction.execute(ThrowableAction.java:46)
	... 8 more
```

**Comment by KomachiSion** [comment]
```
    @Override
    public void shutdown() throws NacosException {
        LOGGER.info("Shutdown rpc client, set status to shutdown");
        rpcClientStatus.set(RpcClientStatus.SHUTDOWN);
        LOGGER.info("Shutdown client event executor " + clientEventExecutor);
        clientEventExecutor.shutdownNow();
        closeConnection(currentConnection);
    }
```

clientEventExecutor maybe null if the client has no `start`. can judgement whether is null.

**Comment by onewe** [comment]
@onewe  will solve it@

**Comment by brotherlu-xcq** [comment]
It has been fixed by https://github.com/alibaba/nacos/pull/6534, due to the connection is null when the connection doesn't establish.
![image](https://user-images.githubusercontent.com/25661357/145995810-b2edbea1-972f-4d7d-9b62-a469159e16e0.png)
