### ISSUE TITLE
集群方式部署3个节点，服务器扩容重启节点（86节点）后，一直报错

### ISSUE THREAD

**Issue by Brian415** [alibaba/nacos#7463]
3节点：172.17.191.84，172.17.233.59，172.17.191.86（重启）
其中86节点，naming-server.log 报错日志如下：

java.io.IOException: failed to req API:http://172.17.191.84:8848/nacos/v1/ns/operator/cluster/state. code:500 msg: caused: unable to find local peer: 172.17.191.84:8848, all peers: [];
        at com.alibaba.nacos.naming.misc.NamingProxy.reqCommon(NamingProxy.java:321)
        at com.alibaba.nacos.naming.cluster.ServerListManager$ServerInfoUpdater.run(ServerListManager.java:183)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2021-12-20 21:47:39,178 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: 172.17.191.84:8848

2021-12-20 21:47:39,181 WARN [STATUS-SYNCHRONIZE] failed to request serverStatus, remote server: 172.17.233.59:8848

2021-12-20 21:47:40,145 INFO upgrade check result false

2021-12-20 21:47:40,178 WARN [STATUS-SYNCHRONIZE] failed to request serviceStatus, remote server: 172.17.191.84:8848

2021-12-20 21:47:40,178 WARN [STATUS-SYNCHRONIZE] failed to request serviceStatus, remote server: 172.17.191.84:8848

2021-12-20 21:47:40,179 WARN [STATUS-SYNCHRONIZE] failed to request serviceStatus, remote server: 172.17.233.59:8848

2021-12-20 21:47:40,180 WARN [STATUS-SYNCHRONIZE] failed to request serviceStatus, remote server: 172.17.233.59:8848

在nacos管理控制台上86节点时有时无，不知道是什么原因

**Comment by wangwei-ying** [comment]
什么版本的server

**Comment by Brian415** [comment]
> 什么版本的server

2.0.3

**Comment by liuxuzxx** [comment]
作者如何处理的？
