### ISSUE TITLE
nacos集群+nginx

### ISSUE THREAD

**Issue by zzx769394358** [alibaba/nacos#7556]
nacos版本： 2.0.3 

在三台机器上部署了nacos-server
a:8848   b:8848   c:8848

然后在a上配置nginx，   其中nginx.conf 的 stream内容

```
stream {
        upstream nacosClu {
            server a:8848;
            server b:8848;
            server c:8848;
       }
       server {
             listen       9085;
             proxy_pass nacosClu;
       }    
 }
```

访问  a:9085/nacos     nacos控制台没问题；
但将 server-addr   设置为  a:8085， 报错
```
c.a.n.c.r.client.grpc.GrpcClient : Server check fail, please check server a ,port 9085 is available , error ={}
java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566) ~[guava-30.1-jre.jar:na]
	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:445) ~[guava-30.1-jre.jar:na]
```

**Comment by zzx769394358** [comment]
搞定：
根据https://nacos.io/zh-cn/docs/2.0.0-compatibility.html  图
正确的 nginx.conf


```
stream {
    upstream nacosGrpc {
        server a:9848;     //  X + 1000
        server b6:9848;
        server c:9848;
    }

    server {
        listen 9080;     //  Y + 1000
        proxy_pass nacosGrpc;
    }
}

http {
   #  ignore something here
    #gzip  on;

   upstream nacosClu {
        server a:8848;      //  X = nacos端口
        server b:8848;
        server c:8848;
    }

    server {
        listen       8080;     //  Y = nginx监听端口， 但是端口别跟其他的冲突了
        server_name  nginxIp;

        location / {
            proxy_pass http://nacosClu;
        }
       #  ignore something here
   }
}
```

控制台地址: nginxIp: Y/nacos 
server-addr地址:  nginxIp: Y
