### ISSUE TITLE
nacos address {domain} is not ip

### ISSUE THREAD

**Issue by adeng-wc** [alibaba/nacos#7566]
1.4.2 升级 2.0.3 出现异常。

异常信息：

15:18:17.304 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.ExceptionInInitializerError: null
	at com.alibaba.nacos.core.listener.StartingApplicationListener.initSystemProperty(StartingApplicationListener.java:201)
	at com.alibaba.nacos.core.listener.StartingApplicationListener.environmentPrepared(StartingApplicationListener.java:102)
	at com.alibaba.nacos.core.code.SpringApplicationRunListener.environmentPrepared(SpringApplicationRunListener.java:65)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.RuntimeException: nacos address nacos-cluster-1 is not ip
	at com.alibaba.nacos.sys.utils.InetUtils$1.run(InetUtils.java:86)
	at com.alibaba.nacos.sys.utils.InetUtils.<clinit>(InetUtils.java:131)
	... 17 common frames omitted

异常原因：
    com.alibaba.nacos.sys.utils.InetUtils$1.run(InetUtils.java:86)，增加了 nacosIP 的校验。

建议：
   部署的环境中，ip是动态变的，所以绑定了一个固定的 domain 。因此，nacos-docker 中 NACOS_SERVER_IP 配置的是 nacos-cluster-1。

suggestion:
    In the deployment environment, the IP is dynamically changed, so a fixed domain is bound. Therefore, NACOS_SERVER_IP in nacos-docker configures nacos-cluster-1.

**Comment by adeng-wc** [comment]
当把 NACOS_SERVER_IP 从 ”nacos-cluster-1“ 改成 "nacos-cluster-1.1362-dev-2484" 时，InternetAddressUtil.isDomain(nacosIP) 通过校验，但是  new URI(null, null, "nacos-cluster-2.1362-dev-2484", 9849, null, null, null) 缺报错。

异常信息：
2022-01-07 11:03:57,763 ERROR [Cluster-nacos-cluster-2.1362-dev-2484:8848]Fail to connect to server!,error={}

java.lang.IllegalArgumentException: Invalid host or port: nacos-cluster-2.1362-dev-2484 9849
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:481)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:123)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:109)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
	at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
	at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewChannelStub(GrpcClient.java:97)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:265)
	at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:528)
	at com.alibaba.nacos.common.remote.client.RpcClient$3.run(RpcClient.java:373)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in hostname at index 18: //nacos-cluster-2.1362-dev-2484:9849
	at java.net.URI$Parser.fail(URI.java:2847)
	at java.net.URI$Parser.parseHostname(URI.java:3394)
	at java.net.URI$Parser.parseServer(URI.java:3235)
	at java.net.URI$Parser.parseAuthority(URI.java:3154)
	at java.net.URI$Parser.parseHierarchical(URI.java:3096)
	at java.net.URI$Parser.parse(URI.java:3062)
	at java.net.URI.<init>(URI.java:673)
	at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:479)
	... 16 common frames omitted

**Comment by huhu-sky** [comment]
@adeng-wc   Invalid host or port: nacos-cluster-2.1362-dev-2484 9849 这个错误你们最后怎么处理呢

**Comment by adeng-wc** [comment]
> @adeng-wc Invalid host or port: nacos-cluster-2.1362-dev-2484 9849 这个错误你们最后怎么处理呢

暂时放弃升级了。

**Comment by huhu-sky** [comment]
nacos-cluster-2.1362-dev-2484    这个地址你们可以变通下；
比如 nacos-cluster-2.1362-dev-2484.svc  ; 或者   1362-dev-2484 这个 namespace 变更下，要求 namespace 不要以 数字开头；

**Comment by adeng-wc** [comment]
> nacos-cluster-2.1362-dev-2484 这个地址你们可以变通下； 比如 nacos-cluster-2.1362-dev-2484.svc ; 或者 1362-dev-2484 这个 namespace 变更下，要求 namespace 不要以 数字开头；

这个地址是平台提供方提供的，要改的话，需要第三方配合，太麻烦了。
