### ISSUE TITLE
2.0.3 NACOS_SERVER_IP 不支持自定义域名

### ISSUE THREAD

**Issue by adeng-wc** [alibaba/nacos#7575]
1.4.2 升级 2.0.3 出现异常。

异常信息：

15:18:17.304 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.ExceptionInInitializerError: null
at com.alibaba.nacos.core.listener.StartingApplicationListener.initSystemProperty(StartingApplicationListener.java:201)
at com.alibaba.nacos.core.listener.StartingApplicationListener.environmentPrepared(StartingApplicationListener.java:102)
at com.alibaba.nacos.core.code.SpringApplicationRunListener.environmentPrepared(SpringApplicationRunListener.java:65)
at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
at com.alibaba.nacos.Nacos.main(Nacos.java:35)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.RuntimeException: nacos address nacos-cluster-1 is not ip
at com.alibaba.nacos.sys.utils.InetUtils$1.run(InetUtils.java:86)
at com.alibaba.nacos.sys.utils.InetUtils.(InetUtils.java:131)
... 17 common frames omitted

异常原因：
com.alibaba.nacos.sys.utils.InetUtils$1.run(InetUtils.java:86)，增加了 nacosIP 的校验。

-----------------------------------------------

当把 NACOS_SERVER_IP 从 ”nacos-cluster-1“ 改成 "nacos-cluster-1.1362-dev-2484" 时，InternetAddressUtil.isDomain(nacosIP) 通过校验，但是 new URI(null, null, "nacos-cluster-2.1362-dev-2484", 9849, null, null, null) 缺报错。

异常信息：
2022-01-07 11:03:57,763 ERROR [Cluster-nacos-cluster-2.1362-dev-2484:8848]Fail to connect to server!,error={}

java.lang.IllegalArgumentException: Invalid host or port: nacos-cluster-2.1362-dev-2484 9849
at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:481)
at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.(NettyChannelBuilder.java:123)
at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:109)
at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewChannelStub(GrpcClient.java:97)
at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:265)
at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:528)
at com.alibaba.nacos.common.remote.client.RpcClient$3.run(RpcClient.java:373)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
at java.util.concurrent.FutureTask.run(FutureTask.java:266)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in hostname at index 18: //nacos-cluster-2.1362-dev-2484:9849
at java.net.URI$Parser.fail(URI.java:2847)
at java.net.URI$Parser.parseHostname(URI.java:3394)
at java.net.URI$Parser.parseServer(URI.java:3235)
at java.net.URI$Parser.parseAuthority(URI.java:3154)
at java.net.URI$Parser.parseHierarchical(URI.java:3096)
at java.net.URI$Parser.parse(URI.java:3062)
at java.net.URI.(URI.java:673)
at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:479)
... 16 common frames omitted

**Comment by onewe** [comment]
@onewe will solve it@

**Comment by onewe** [comment]
相当于你这个不支持 hostname 解析对吧

**Comment by adeng-wc** [comment]
nacos-docker 中有个配置"PREFER_HOST_MODE"，我配置了 ”hostname“，对应nacos中的  
com.alibaba.nacos.sys.env.Constants#PREFER_HOSTNAME_OVER_IP_PROPERTY_NAME，并没有使用。所以，我使用了 ”NACOS_SERVER_IP“ ，配置 ”nacos-cluster-1“，”nacos-cluster-2“，”nacos-cluster-3“。
我部署的环境是 前面一台ng，后台3个nacos-docker。没有使用docker的服务编排。

**Comment by adeng-wc** [comment]
> 相当于你这个不支持主机名解析对吧

nacos-docker 中有个配置"PREFER_HOST_MODE"，我配置了 ”hostname“，对应nacos中的
com.alibaba.nacos.sys.env.Constants#PREFER_HOSTNAME_OVER_IP_PROPERTY_NAME，并没有使用。所以，我使用了 ”NACOS_SERVER_IP“ ，配置 ”nacos-cluster-1“，”nacos-cluster-2“，”nacos-cluster-3“。
我部署的环境是 前面一台ng，后台3个nacos-docker。没有使用docker的服务编排。

**Comment by KomachiSion** [comment]
java.lang.IllegalArgumentException: Invalid host or port: nacos-cluster-2.1362-dev-2484 9849
at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:481)

grpc的问题，应该是域名非法， 域名是有格式要求的。

**Comment by KomachiSion** [comment]
```
Exception in thread "main" java.net.URISyntaxException: Illegal character in hostname at index 18: //nacos-cluster-2.1362-dev-2484:9848
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseHostname(URI.java:3395)
	at java.net.URI$Parser.parseServer(URI.java:3236)
	at java.net.URI$Parser.parseAuthority(URI.java:3155)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:673)
	at komachi.sion.url.DomainTest.main(DomainTest.java:12)
```

`.` 后应该不能为数字吧。 我改成nacos-cluster-2.x1362-dev-2484 就通过了。 看来nacos的domain校验还是比实际的规范要宽泛一点

**Comment by KomachiSion** [comment]
```
Exception in thread "main" java.net.URISyntaxException: Illegal character in hostname at index 18: //nacos-cluster-2.1362-dev-2484:9848
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseHostname(URI.java:3395)
	at java.net.URI$Parser.parseServer(URI.java:3236)
	at java.net.URI$Parser.parseAuthority(URI.java:3155)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3063)
	at java.net.URI.<init>(URI.java:673)
	at komachi.sion.url.DomainTest.main(DomainTest.java:12)
```

`.` 后应该不能为数字吧。 我改成nacos-cluster-2.x1362-dev-2484 就通过了。 看来nacos的domain校验还是比实际的规范要宽泛一点
