### ISSUE TITLE
Nacos Client TimeoutException

### ISSUE THREAD

**Issue by Belyenochi** [alibaba/nacos#7605]
Nacos Version: 2.0.3
Nacos Client connected Service Config:
![image](https://user-images.githubusercontent.com/26409132/148730491-14a191e0-3ac4-4295-8c4b-7f1a857d7ca2.png)
![image](https://user-images.githubusercontent.com/26409132/148730617-13e6b1a4-ff64-483f-ba04-d113f24dffb4.png)

Nacos Client Error log(Appears every half hour):
```
com.alibaba.nacos.api.exception.NacosException: java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 69404 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@6e3f5700[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@141c9cb3, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@75af2bb3, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@d3b75be}}}}}]]
        at com.alibaba.nacos.common.remote.client.grpc.GrpcConnection.request(GrpcConnection.java:78)
        at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:657)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1067)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1042)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.removeConfig(ClientWorker.java:1139)
        at com.alibaba.nacos.client.config.impl.ClientWorker.removeConfig(ClientWorker.java:281)
        at com.alibaba.nacos.client.config.NacosConfigService.removeConfigInner(NacosConfigService.java:234)
        at com.alibaba.nacos.client.config.NacosConfigService.removeConfig(NacosConfigService.java:169)
        at com.mcloud.test.task.NacosTask.NacosMetricsCollectTask.collectNacosRequest(NacosMetricsCollectTask.java:67)
        at sun.reflect.GeneratedMethodAccessor563.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:81)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 69404 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@6e3f5700[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@141c9cb3, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@75af2bb3, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@d3b75be}}}}}]]
        at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcConnection.request(GrpcConnection.java:76)
        ... 21 common frames omitted
```

**Comment by vividfish** [comment]
at com.mcloud.test.task.NacosTask.NacosMetricsCollectTask.collectNacosRequest(NacosMetricsCollectTask.java:67)

**Comment by Belyenochi** [comment]
> at com.mcloud.test.task.NacosTask.NacosMetricsCollectTask.collectNacosRequest(NacosMetricsCollectTask.java:67)
I found that I left port 9849 on the server side. When I opened it, the error disappeared. Why can port 9849 be perceived on the client side?

**Comment by Belyenochi** [comment]
> at com.mcloud.test.task.NacosTask.NacosMetricsCollectTask.collectNacosRequest(NacosMetricsCollectTask.java:67)

I found that I left port 9849 on the server side. When I opened it, the error disappeared. Why can port 9849 be perceived on the client side?

**Comment by Belyenochi** [comment]
> at com.mcloud.test.task.NacosTask.NacosMetricsCollectTask.collectNacosRequest(NacosMetricsCollectTask.java:67)

configServices.removeConfig(dataId, group);

**Comment by vividfish** [comment]
9848 is uesd by nacos 2.x  new feature:grpc

**Comment by Belyenochi** [comment]
> 9848 is uesd by nacos 2.x new feature:grpc

Thanks Reply
In what scenarios will grpc be used, the features of the client SDK or the features of the server SDK, why do you need 9849 when 9848 already exists?

**Comment by Belyenochi** [comment]
> 9848 is uesd by nacos 2.x new feature:grpc

I found that this grpc doesn't seem to be useful in the configuration center scenario

**Comment by vividfish** [comment]
> > 9848 is uesd by nacos 2.x new feature:grpc
> 
> I found that this grpc doesn't seem to be useful in the configuration center scenario

it's used, you can see com.alibaba.nacos.core.remote.grpc.GrpcRequestAcceptor

**Comment by lpaz010** [comment]
> why do you need 9849 when 9848 already exists?
port 9849 for nacos server cluster data synchronization

**Comment by vividfish** [comment]
> > why do you need 9849 when 9848 already exists?
> 
> port 9849 for nacos server cluster data synchronization

是的，我前面看错数字了，我以为你问9848 。 
9849端口可以看com.alibaba.nacos.core.remote.grpc.GrpcClusterServer

**Comment by Belyenochi** [comment]
> > why do you need 9849 when 9848 already exists?
> 
> port 9849 for nacos server cluster data synchronization

Does this port need to be opened to the client SDK?

**Comment by Belyenochi** [comment]
> > > why do you need 9849 when 9848 already exists?
> > 
> > 
> > port 9849 for nacos server cluster data synchronization
> 
> 是的，我前面看错数字了，我以为你问9848 。 9849端口可以看com.alibaba.nacos.core.remote.grpc.GrpcClusterServer

Does this port need to be opened to the client SDK?

**Comment by Belyenochi** [comment]
> com.alibaba.nacos.api.exception.NacosException: java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 69404 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@6e3f5700[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@141c9cb3, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@75af2bb3, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@d3b75be}}}}}]]

If the client does not need to access this port, then please see why the error reported in my initial question can be solved by opening the 9849 port, does this mean that the JAVA SDK has the possibility to access the Nacos 9849 Grpc port

**Comment by Belyenochi** [comment]
> > > why do you need 9849 when 9848 already exists?
> > 
> > 
> > port 9849 for nacos server cluster data synchronization
> 
> 是的，我前面看错数字了，我以为你问9848 。 9849端口可以看com.alibaba.nacos.core.remote.grpc.GrpcClusterServer

If the client does not need to access this port, then please see why the error reported in my initial question can be solved by opening the 9849 port, does this mean that the JAVA SDK has the possibility to access the Nacos 9849 Grpc port.

**Comment by lpaz010** [comment]
@Belyenochi 
1. 我这里没用容器部署过，不清楚:sweat_smile:
2. 端口9849只在服务端集群内使用

**Comment by vividfish** [comment]
是不是把默认端口8848改成了8849？

**Comment by Belyenochi** [comment]
> 是不是把默认端口8848改成了8849？

![image](https://user-images.githubusercontent.com/26409132/149089744-eeba0f2c-058d-4604-88e8-5936acdeace4.png)

![image](https://user-images.githubusercontent.com/26409132/149089809-a3e86de5-9d45-4449-800e-cbd6a8684e71.png)

![image](https://user-images.githubusercontent.com/26409132/149089909-24f83629-414a-4643-b885-af9526d209fe.png)

**Comment by Belyenochi** [comment]
> @Belyenochi
> 
> 1. 我这里没用容器部署过，不清楚😅
> 2. 端口9849只在服务端集群内使用

不开9849会有什么影响，我观测到不开9849服务端启动也可以通过JRaft同步metadata以及通过Distro协议同步数据

**Comment by Belyenochi** [comment]
> 是不是把默认端口8848改成了8849？

我现在很迷惑的是这个报错的触发条件是啥，就算我开了9849端口（默认SDK通过+1001）但是还是会偶发的报错，之前是每半小时报错一次

**Comment by Belyenochi** [comment]
> 是不是把默认端口8848改成了8849？

目前我在做压力测试，不清楚是不是和这个有关系，可以看到每隔几个小时会有这个报错
```
com.alibaba.nacos.api.exception.NacosException: java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 66743 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@22d5e964[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@f02a6f3, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@4c6873a7, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@60601fcb}}}}}]]
```
我不清楚这个SDK层面报错的status=PENDING意味着客户端PENDING还是SERVER端PENDING，也不清楚如果服务端PENDING需要查看哪个日志？

**Comment by Belyenochi** [comment]
> 是不是把默认端口8848改成了8849？

目前我在做压力测试，不清楚是不是和这个有关系，可以看到每隔几个小时会有这个报错
```
com.alibaba.nacos.api.exception.NacosException: java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 66743 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@22d5e964[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@f02a6f3, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@4c6873a7, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@60601fcb}}}}}]]
```
我不清楚这个SDK层面报错的status=PENDING意味着客户端PENDING还是SERVER端PENDING，也不清楚如果服务端PENDING需要查看哪个日志？

**Comment by lpaz010** [comment]
> 不开9849会有什么影响，我观测到不开9849服务端启动也可以通过JRaft同步metadata以及通过Distro协议同步数据

端口9849是给集群内基于GRPC同步的（Distro）,目前2.0.3集群内还有基于HTTP的Distro，所有应该走HTTP同步了吧。

**Comment by lpaz010** [comment]
@Belyenochi 您是使用容器部署的，目前我没有试过...

**Comment by Belyenochi** [comment]
> @Belyenochi 您是使用容器部署的，目前我没有试过...
这和容器应该没关系，我在客户端报的这个grpc Timeout很令人迷惑，我去看看SDK逻辑

**Comment by Belyenochi** [comment]
> @Belyenochi 您是使用容器部署的，目前我没有试过...

这和容器应该没啥关系，主要是这个SDK Timeout的case对应什么我不了解

**Comment by Belyenochi** [comment]
> @Belyenochi 您是使用容器部署的，目前我没有试过...

容器是我用k8s-nacos部署了，加了9848，9849的service

**Comment by Belyenochi** [comment]
> 

是否可以留一个联系方式请教一下问题

**Comment by john1337** [comment]
这个问题都没解决就被关闭了，有些不太好吧

**Comment by freshgeek** [comment]
所以这玩意是啥情况
