### ISSUE TITLE
开启日志等级bug

### ISSUE THREAD

**Issue by zzx769394358** [alibaba/nacos#7685]
nacos version：2.0.3， 集群模式

nacos-server部署在远程服务器
项目接入starter，  配置文件开启  logging.level.   xxxxx = xxx ， 启动

报

```
2022‐01‐ ERROR 37816 --- [com.alibaba.nacos.client.remote.worker] c.a.n.c.r.client.grpc.GrpcClient : Server check fail, please check server localhost ,port 9848 is available , error ={}
java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 360500 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@19bb3e2e[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@31c0c7e5, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@912747d, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@78ea700f}}}}}]]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:146) [nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:268) [nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:528) [nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient$3.run(RpcClient.java:373) [nacos-client-2.0.3.jar:na
```

若在本地也启动nacos-server，错误消失

**Comment by myifeng** [comment]
这个看起来是连接GRPC时候的错误，检查一下9848端口？

**Comment by zzx769394358** [comment]
> 这个看起来是连接GRPC时候的错误，检查一下9848端口？

才发现，另一个项目也开启了这样的日志打印级别配置， 它正常启动了啊  （这两个项目是在同一个大项目底下的）
所以正常来说 端口应该是没问题的吧

**Comment by myifeng** [comment]
ping 一下 gRPC的端口 看看通不通

**Comment by zzx769394358** [comment]
> ping 一下 gRPC的端口 看看通不通

telnet  naocs-server的所有机器  9848
均成功 （进入了一个未知的界面）

**Comment by myifeng** [comment]
那就是了 `please check server localhost ,port 9848 is available` 访问不到 `localhost:9848`

**Comment by zzx769394358** [comment]
> 那就是了 `please check server localhost ,port 9848 is available` 访问不到 `localhost:9848`

项目正常启动也是这样。
那这怎么解决？

**Comment by myifeng** [comment]
可能其他项目访问的不是 localhost:9848
