### ISSUE TITLE
nacos version 2.0.3 Failed to save registry cache file, will retry, cause: null

### ISSUE THREAD

**Issue by rmzf9192** [alibaba/nacos#7706]
2022-01-25 10:25:05.652  WARN 1 --- [yCache-thread-1] o.a.dubbo.registry.nacos.NacosRegistry   :  [DUBBO] Failed to save registry cache file, will retry, cause: null,
 dubbo version: 2.7.8, current host: 12.1.38.66

java.nio.channels.OverlappingFileLockException: null
        at java.base/sun.nio.ch.FileLockTable.checkList(FileLockTable.java:229) ~[na:na]
        at java.base/sun.nio.ch.FileLockTable.add(FileLockTable.java:123) ~[na:na]
        at java.base/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1154) ~[na:na]
        at java.base/java.nio.channels.FileChannel.tryLock(FileChannel.java:1165) ~[na:na]
        at org.apache.dubbo.registry.support.AbstractRegistry.doSaveProperties(AbstractRegistry.java:180) ~[dubbo-2.7.8.jar!/:2.7.8]
        at org.apache.dubbo.registry.support.AbstractRegistry$SaveProperties.run(AbstractRegistry.java:526) ~[dubbo-2.7.8.jar!/:2.7.8]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:829) ~[na:na]

**Comment by KomachiSion** [comment]
dubbo’s problem, please move to dubbo community.
