### ISSUE TITLE
server is DOWN now, please try again later!

### ISSUE THREAD

**Issue by lzh123** [alibaba/nacos#7735]
开工第一天有个服务突然一直报server is DOWN now, please try again later! ，其他服务没有报这个问题
alipay-jraft.log日志如下：
2022-02-06 06:50:04,355 ERROR Fail to init snapshot writer.

2022-02-06 06:50:04,363 ERROR Encountered an error=Status[EIO<1014>: Fail to create snapshot writer.] on StateMachine com.alibaba.nacos.core.distributed.raft.NacosStateMachine, it's highly recommended to implement this method as raft stops working since some error occurs, you should figure out the cause and repair or remove this node.

com.alipay.sofa.jraft.error.RaftException: ERROR_TYPE_SNAPSHOT
	at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.reportError(SnapshotExecutorImpl.java:691)
	at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.doSnapshot(SnapshotExecutorImpl.java:346)
	at com.alipay.sofa.jraft.core.NodeImpl.doSnapshot(NodeImpl.java:3098)
	at com.alipay.sofa.jraft.core.NodeImpl.lambda$handleSnapshotTimeout$0(NodeImpl.java:607)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-02-06 06:50:04,363 WARN Node <naming_persistent_service/xxx:7848> got error: {}.

com.alipay.sofa.jraft.error.RaftException: ERROR_TYPE_SNAPSHOT
	at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.reportError(SnapshotExecutorImpl.java:691)
	at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.doSnapshot(SnapshotExecutorImpl.java:346)
	at com.alipay.sofa.jraft.core.NodeImpl.doSnapshot(NodeImpl.java:3098)
	at com.alipay.sofa.jraft.core.NodeImpl.lambda$handleSnapshotTimeout$0(NodeImpl.java:607)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-02-06 06:50:04,363 WARN FSMCaller already in error status, ignore new error: {}

com.alipay.sofa.jraft.error.RaftException: ERROR_TYPE_SNAPSHOT
	at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.reportError(SnapshotExecutorImpl.java:691)
	at com.alipay.sofa.jraft.storage.snapshot.SnapshotExecutorImpl.doSnapshot(SnapshotExecutorImpl.java:346)
	at com.alipay.sofa.jraft.core.NodeImpl.doSnapshot(NodeImpl.java:3098)
	at com.alipay.sofa.jraft.core.NodeImpl.lambda$handleSnapshotTimeout$0(NodeImpl.java:607)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-02-06 06:50:04,364 INFO onStopFollowing: LeaderChangeContext [leaderId=xxx:7848, term=3, status=Status[EBADNODE<10009>: Raft node(leader or candidate) is in error.]].

2022-02-06 06:50:04,665 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 06:50:05,170 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 06:50:05,672 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 06:50:06,173 WARN Node <naming_persistent_servic2022-02-06 11:03:57,301 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:03:57,802 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:03:58,303 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 11:03:58,303 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:03:58,804 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 11:03:58,804 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:03:59,305 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 11:03:59,305 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:03:59,806 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 11:03:59,806 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:04:00,306 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 11:04:00,307 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:04:00,807 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 11:04:00,807 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:04:01,308 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 11:04:01,308 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:04:01,809 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:04:01,810 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 11:04:02,310 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:04:02,310 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 11:04:02,811 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:04:02,811 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 11:04:03,311 WARN Node <naming_persistent_service/xxx:7848> ignore InstallSnapshotRequest as it is not in active state STATE_ERROR.

2022-02-06 11:04:03,312 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

2022-02-06 11:04:03,812 WARN Node <naming_persistent_service/xxx:7848> is not in active state, currTerm=3.

nacos集群没有重启过，现在这个节点出现问题，没有排查到原因，请帮忙分析下什么情况会 导致这个问题的产生

**Comment by vividfish** [comment]
<img width="784" alt="image" src="https://user-images.githubusercontent.com/24951831/153562896-a2d95e06-94c8-49b8-af3a-af35db8fe5fa.png">
看源码像文件读写的io问题

**Comment by vividfish** [comment]
检查下文件的读写权限和磁盘是否有空间？

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
