### ISSUE TITLE
SpringBoot作为Nacos客户端，启动时候注册NacosServer集群失败，failed to req API:/nacos/v1/ns/instance 报400

### ISSUE THREAD

**Issue by Naylor55** [alibaba/nacos#7740]
## Issue Description

SpringBoot配置Nacos为注册中心，Nacos为集群（本地启动三个实例），SpringBoot程序启动报错，之后假死状态。详细报错信息如下：

~~~

2022-02-08 21:50:54.468 ERROR 5088 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.context.ApplicationContextException: Failed to start bean 'webServerStartStop'; nested exception is java.lang.reflect.UndeclaredThrowableException
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:181) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.9.jar:5.3.9]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.5.3.jar:2.5.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.3.jar:2.5.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.3.jar:2.5.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.3.jar:2.5.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.3.jar:2.5.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.3.jar:2.5.3]
	at com.ramble.nacosclientuser.NacosClientUserApplication.main(NacosClientUserApplication.java:12) ~[classes/:na]
Caused by: java.lang.reflect.UndeclaredThrowableException: null
	at org.springframework.util.ReflectionUtils.rethrowRuntimeException(ReflectionUtils.java:147) ~[spring-core-5.3.9.jar:5.3.9]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:83) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar:2021.1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:232) ~[spring-cloud-commons-3.0.3.jar:3.0.3]
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar:2021.1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:133) ~[spring-cloud-commons-3.0.3.jar:3.0.3]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:98) ~[spring-cloud-commons-3.0.3.jar:3.0.3]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:86) ~[spring-cloud-commons-3.0.3.jar:3.0.3]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) ~[spring-cloud-commons-3.0.3.jar:3.0.3]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.9.jar:5.3.9]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:46) ~[spring-boot-2.5.3.jar:2.5.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.9.jar:5.3.9]
	... 14 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: failed to req API:/nacos/v1/ns/instance after all servers([127.0.0.1:8848]) tried: ErrCode:400, ErrMsg:<html><body><h1>Whitelabel Error Page</h1><p>This application has no explicit mapping for /error, so you are seeing this as a fallback.</p><div id='created'>Tue Feb 08 21:50:44 CST 2022</div><div>There was an unexpected error (type=Bad Request, status=400).</div><div>receive invalid redirect request from peer 192.168.1.169</div></body></html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:556) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:246) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:212) ~[nacos-client-1.4.1.jar:na]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar:2021.1]
	... 27 common frames omitted


~~~
### 环境
* NacosServer 版本：2.0.3
* NacosServer集群部署方式：在windows11下启动三个实例，分别运行在8848，8858，8868端口上面，三个实例连接同一个MySQL数据库
* NacosClient为 SpringBoot 程序，使用 SpringInitializr 创建，未引入其他无关依赖
* SpringBoot版本：2.5.3
* SpringCloud版本：2020.0.3
* SpringCloudAlibaba版本：2021.1
* 笔记本：酷睿I5-11代，RAM-16G

### How to reproduce it (as minimally and precisely as possible)

1. 启动NacosServer 集群
2. SpringBoot配置：

~~~
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
      config:
        server-addr: 127.0.0.1:8848
        file-extension: yaml
~~~

3. 启动SpringBoot就可以看到报错

### Anything else we need to know?

1：网上有人说是 NacosServer 负载过高导致，尝试过 停掉Nacos集群然后删除 data 文件夹，再重新启动，但是没有解决此问题。

**Comment by Naylor55** [comment]
鼓捣了一会，搞好了。解决过程简单整理了一下：
https://www.cnblogs.com/Naylor/p/15873192.html

**Comment by qq1018656369** [comment]
同样的问题，我是在k8s环境重启nacos集群，微服务启动后就一直报注册失败
2022-02-15 20:36:18.856 ERROR 1 --- [           main] c.a.c.n.registry.NacosServiceRegistry    : nacos registry, api-gateway register failed...NacosRegistration{nacosDiscoveryProperties=NacosDiscoveryProperties{serverAddr='nacos.test.svc.cluster.local:8848', endpoint='', namespace='44405694-78a3-46ad-b068-6e180dd17b26', watchDelay=30000, logName='', service='api-gateway', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.heart.beat.timeout=3000, preserved.ip.delete.timeout=3000, preserved.register.source=SPRING_CLOUD, preserved.heart.beat.interval=1000}, registerEnabled=true, ip='10.100.8.31', networkInterface='', port=80, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, failFast=true}},
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:279) ~[nacos-client-2.0.3.jar:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129) ~[nacos-client-2.0.3.jar:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115) ~[nacos-client-2.0.3.jar:na]
        at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95) ~[nacos-client-2.0.3.jar:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.0.3.jar:na]
        at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:74) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.7.RELEASE.jar:2.2.7.RELEASE]
        at com.alibaba.cloud.nacos.registry.NacosServiceRegistry$$FastClassBySpringCGLIB$$ca3a8dbd.invoke(<generated>) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.7.RELEASE.jar:2.2.7.RELEASE]
        at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218) ~[spring-core-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:779) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:163) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:56) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:175) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:95) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:750) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:692) ~[spring-aop-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at com.alibaba.cloud.nacos.registry.NacosServiceRegistry$$EnhancerBySpringCGLIB$$4948d1cb.register(<generated>) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.7.RELEASE.jar:2.2.7.RELEASE]
        at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:239) ~[spring-cloud-commons-2.2.9.RELEASE.jar:2.2.9.RELEASE]
        at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.7.RELEASE.jar:2.2.7.RELEASE]
        at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:138) ~[spring-cloud-commons-2.2.9.RELEASE.jar:2.2.9.RELEASE]
        at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:101) ~[spring-cloud-commons-2.2.9.RELEASE.jar:2.2.9.RELEASE]
        at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:88) ~[spring-cloud-commons-2.2.9.RELEASE.jar:2.2.9.RELEASE]
        at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:47) ~[spring-cloud-commons-2.2.9.RELEASE.jar:2.2.9.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.boot.web.reactive.context.WebServerManager.start(WebServerManager.java:56) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.web.reactive.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:40) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:182) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:53) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:360) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:158) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:122) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:895) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.15.RELEASE.jar:5.2.15.RELEASE]
        at org.springframework.boot.web.reactive.context.ReactiveWebServerApplicationContext.refresh(ReactiveWebServerApplicationContext.java:62) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:755) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:402) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236) ~[spring-boot-2.3.12.RELEASE.jar:2.3.12.RELEASE]
        at com.nozo.api.gateway.ApiGatewayApplication.main(ApiGatewayApplication.java:14) ~[classes/:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:566) ~[na:na]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[application/:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[application/:na]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[application/:na]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[application/:na]
Caused by: com.alibaba.nacos.api.exception.NacosException: Nacos cluster is running with 1.X mode, can't accept gRPC request temporarily. Please check the server status or close Double write to force open 2.0 mode. Detail https://nacos.io/en-us/docs/2.0.0-upgrading.html.
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:271) ~[nacos-client-2.0.3.jar:na]
        ... 57 common frames omitted

**Comment by Naylor55** [comment]
你可以尝试停掉所有节点，然后删除data文件夹，最后挨个重启。 看是否可以解决你的问题，如果解决了，你再回来说一声哈。

**Comment by Naylor55** [comment]
真的吗？3171448083，明天有空了可以一起研究一下，我们现在在测试环境里面在试用，还没有上生产，慌的一批

**Comment by onewe** [comment]
@Naylor55 看了你写的博客,对于多了一条`192.168.1.169:8858`这个应该是nacos的机制导致的,因为nacos集群启动的时候会先去获取本机非回环ip地址作为本节点的地址,然后再去解析配置文件. 由于配置文件全是`127.0.0.1`所以就多了一条`192.168.1.169`记录

**Comment by evin0329** [comment]
本机地址192.168.1.169反而是对的，cluster.conf文件中不能写成127.0.0.1形式。会导致com.alibaba.nacos.core.cluster.ServerMemberManager#init初始化和cluster.conf解析完后出现类似重复的地址。从而影响过滤器DistroFilter无法进入下个过滤器进行处理，转而请求其他服务实例。
![image](https://user-images.githubusercontent.com/35405705/180611237-655811c6-ec3d-457c-8a90-db86bf19e2f4.png)
![image](https://user-images.githubusercontent.com/35405705/180611035-5dbae43b-893c-4234-8d9d-e3767145bb06.png)
![image](https://user-images.githubusercontent.com/35405705/180611330-f2b6d2d0-5bdb-4d04-9818-49f12b897037.png)


> @Naylor55看了你写的博客,对于多了一条`192.168.1.169:8858`这个应该是高洛的机制导致的,因为高洛集群启动的时候会先去获取本机非回环互联网协议（Internet Protocol的缩写）地址作为本节点的地址,然后再去解析配置文件。由于配置文件全是`127.0.0.1`所以就多了一条`192.168.1.169`记录

**Comment by evin0329** [comment]
> 本机地址192.168.1.169反而是对的，cluster.conf文件中不能写成127.0.0.1形式。会导致com.alibaba.nacos.core.cluster.ServerMemberManager#init初始化和cluster.conf解析完后出现类似重复的地址。从而影响过滤器DistroFilter无法进入下个过滤器进行处理，转而请求其他服务实例。 ![image](https://user-images.githubusercontent.com/35405705/180611237-655811c6-ec3d-457c-8a90-db86bf19e2f4.png) ![image](https://user-images.githubusercontent.com/35405705/180611035-5dbae43b-893c-4234-8d9d-e3767145bb06.png) ![image](https://user-images.githubusercontent.com/35405705/180611330-f2b6d2d0-5bdb-4d04-9818-49f12b897037.png)
> 
> > @Naylor55看了你写的博客,对于多了一条`192.168.1.169:8858`这个应该是高洛的机制导致的,因为高洛集群启动的时候会先去获取本机非回环互联网协议（Internet Protocol的缩写）地址作为本节点的地址,然后再去解析配置文件。由于配置文件全是`127.0.0.1`所以就多了一条`192.168.1.169`记录

更加离谱的是，当写成127.0.0.1的形式，在MemberUtil.syncToFile(finalMembers);中会把 InetUtils.getSelfIP()的地址写到cluster.con。

**Comment by evin0329** [comment]
> 本机地址192.168.1.169反而是对的，cluster.conf文件中不能写成127.0.0.1形式。会导致com.alibaba.nacos.core.cluster.ServerMemberManager#init初始化和cluster.conf解析完后出现类似重复的地址。从而影响过滤器DistroFilter无法进入下个过滤器进行处理，转而请求其他服务实例。 ![image](https://user-images.githubusercontent.com/35405705/180611237-655811c6-ec3d-457c-8a90-db86bf19e2f4.png) ![image](https://user-images.githubusercontent.com/35405705/180611035-5dbae43b-893c-4234-8d9d-e3767145bb06.png) ![image](https://user-images.githubusercontent.com/35405705/180611330-f2b6d2d0-5bdb-4d04-9818-49f12b897037.png)
> 
> > @Naylor55看了你写的博客,对于多了一条`192.168.1.169:8858`这个应该是高洛的机制导致的,因为高洛集群启动的时候会先去获取本机非回环互联网协议（Internet Protocol的缩写）地址作为本节点的地址,然后再去解析配置文件。由于配置文件全是`127.0.0.1`所以就多了一条`192.168.1.169`记录

com.alibaba.nacos.naming.core.DistroMapper 的 healthyList计算问题，补充正常和异常情况下的图片：
配置为127.0.0.1的情况（错误的方式）：
![image](https://user-images.githubusercontent.com/35405705/180611724-831982ca-25b2-4e2a-9888-f53863659fd5.png)
配置为本机网卡地址（正确的情况）：
![image](https://user-images.githubusercontent.com/35405705/180611807-184829be-0d94-43bf-80cb-22b12f6dbf76.png)

**Comment by evin0329** [comment]
> > 本机地址192.168.1.169反而是对的，cluster.conf文件中不能写成127.0.0.1形式。会导致com.alibaba.nacos.core.cluster.ServerMemberManager#init初始化和cluster.conf解析完后出现类似重复的地址。从而影响过滤器DistroFilter无法进入下个过滤器进行处理，转而请求其他服务实例。 ![image](https://user-images.githubusercontent.com/35405705/180611237-655811c6-ec3d-457c-8a90-db86bf19e2f4.png) ![image](https://user-images.githubusercontent.com/35405705/180611035-5dbae43b-893c-4234-8d9d-e3767145bb06.png) ![image](https://user-images.githubusercontent.com/35405705/180611330-f2b6d2d0-5bdb-4d04-9818-49f12b897037.png)
> > > @Naylor55看了你写的博客,对于多了一条`192.168.1.169:8858`这个应该是高洛的机制导致的,因为高洛集群启动的时候会先去获取本机非回环互联网协议（Internet Protocol的缩写）地址作为本节点的地址,然后再去解析配置文件。由于配置文件全是`127.0.0.1`所以就多了一条`192.168.1.169`记录
> 
> com.alibaba.nacos.naming.core.DistroMapper 的 healthyList计算问题，补充正常和异常情况下的图片： 配置为127.0.0.1的情况（错误的方式）： ![image](https://user-images.githubusercontent.com/35405705/180611724-831982ca-25b2-4e2a-9888-f53863659fd5.png) 配置为本机网卡地址（正确的情况）： ![image](https://user-images.githubusercontent.com/35405705/180611807-184829be-0d94-43bf-80cb-22b12f6dbf76.png)

本机网卡地址在com.alibaba.nacos.core.cluster.ServerMemberManager#init中初始化填充serverList.put

**Comment by onewe** [comment]
这个的确是有问题, 可以优化一下 https://github.com/alibaba/nacos/blob/4a3472b9b78f654fa6f780d9163629f986801d6f/core/src/main/java/com/alibaba/nacos/core/cluster/ServerMemberManager.java#L347 这里的逻辑, 我认为在对比的时候 如果发现是member里的ip是 本地回环ip地址, 只需比较端口即可, 若端口一致则表示已经包含 SelfIp

**Comment by onewe** [comment]
感觉这样简单处理 后续牵扯的东西有点多, 为了避免改动范围过大, 也可以把 127.0.0.1 这种配置的全部替换成 程序获取到的 localAddress

**Comment by onewe** [comment]
或者从 Distro hash 着手 修改

**Comment by evin0329** [comment]
> 感觉这样简单处理 后续牵扯的东西有点多, 为了避免改动范围过大, 也可以把 127.0.0.1 这种配置的全部替换成 程序获取到的 localAddress

也可以在读到127.0.0.1的时候能给个提示信息  或者  抛出异常   改动风险最小

**Comment by onewe** [comment]
这个可以, 目前临时解决办法可以使用  `nacos.server.ip` 指定 一个ip地址, 比如指定为: 127.0.0.1 这个问题就没了

**Comment by onewe** [comment]
这本质上是个多网卡的问题 并非只有 127.0.0.1 才会出现这个问题

**Comment by 1praiseThesun** [comment]
@Naylor55 我用的云服务器的ip，集运已经部署成功，但boot却一直连接不上，报400，不知道为什么，删了data再启动也不行

**Comment by fanchunmeng-98** [comment]
> @Naylor55 我用的云服务器的ip，集运已经部署成功，但boot却一直连接不上，报400，不知道为什么，删了data再启动也不行

我也有相同的问题,你解决了吗

**Comment by wallacefw1987** [comment]
> 感觉这样简单处理 后续牵扯的东西有点多, 为了避免改动范围过大, 也可以把 127.0.0.1 这种配置的全部替换成 程序获取到的 localAddress

没错，按照集群启动生成一个ip地址即可，不要写127.0.0.1！但是假如真实配置应该不用，直接服务器ip地址应该可以

**Comment by wallacefw1987** [comment]
> > @Naylor55 我用的云服务器的ip，集运已经部署成功，但boot却一直连接不上，报400，不知道为什么，删了data再启动也不行
> 
> 我也有相同的问题,你解决了吗

我已经解决了！用nacos生成的第4个地址【上面讲的那个】，cover到你配置的请外3个nacos-server服务地址即可！

**Comment by fanchunmeng-98** [comment]
刚才说的不太准确哈，在client端程序指定服务运行的ip和serverip到同一网段后，我的服务就可以选择正确的网卡并成功路由了，对了，云服务器的话还要设置出入站规则开放端口。发自我的荣耀手机-------- 原始邮件 --------发件人： wallacefw ***@***.***>日期： 2022年9月7日周三 傍晚6:10收件人： alibaba/nacos ***@***.***>抄送： 范春萌 ***@***.***>, Comment ***@***.***>主    题： Re: [alibaba/nacos] SpringBoot作为Nacos客户端，启动时候注册NacosServer集群失败，failed to req API:/nacos/v1/ns/instance 报400 (Issue #7740)





@Naylor55 我用的云服务器的ip，集运已经部署成功，但boot却一直连接不上，报400，不知道为什么，删了data再启动也不行



我也有相同的问题,你解决了吗



我已经解决了！用nacos生成的第4个地址【上面讲的那个】，cover到你配置的请外3个nacos-server服务地址即可！

**Comment by 1praiseThesun** [comment]
@fanchunmeng-98 ### 我解决了。我给各nacos的“配置中心”配置外网ip。我查了一下nacos的配置中心文档，就弄好了。
![image](https://user-images.githubusercontent.com/97266136/189309943-ec08e4a9-ab6a-4205-b81a-6c718caf9cfd.png)
