### ISSUE TITLE
nacos 0.8 login error

### ISSUE THREAD

**Issue by liaozan** [alibaba/nacos#779]
```java
Caused by: java.lang.RuntimeException: load schema.sql error.org.apache.commons.dbcp.SQLNestedException: Cannot create PoolableConnectionFactory (Failed to start database '/root/nacos/data/derby-data' with class loader org.springframework.boot.loader.LaunchedURLClassLoader@17f052a3, see the next exception for details.)
	at com.alibaba.nacos.config.server.service.LocalDataSourceServiceImpl.reload(LocalDataSourceServiceImpl.java:110)
	at com.alibaba.nacos.config.server.service.LocalDataSourceServiceImpl.init(LocalDataSourceServiceImpl.java:94)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 70 common frames omitted
```
`nacos 0.8 release`

**Comment by Jnoee** [comment]
0.8.0 单机模式用默认的用户名/密码 nacos 登录提示用户名或密码错误，不过后台没有以上错误日志。

**Comment by paderlol** [comment]
请问你使用的什么版本的jdk? 是openjdk吗?

**Comment by liaozan** [comment]
java version "1.8.0_172"
Java(TM) SE Runtime Environment (build 1.8.0_172-b11)
Java HotSpot(TM) 64-Bit Server VM (build 25.172-b11, mixed mode)

**Comment by calvin-ye** [comment]
io.jsonwebtoken.security.SignatureException: Unable to obtain JCA MAC algorithm 'HmacSHA256': Algorithm HmacSHA256 not available

java version "1.8.0_202"
Java(TM) SE Runtime Environment (build 1.8.0_202-b08)
Java HotSpot(TM) 64-Bit Server VM (build 25.202-b08, mixed mode)

**Comment by mr253727942** [comment]
这个看起来是权限的问题 你要不把nacos安装到非root目录下看看 ？

**Comment by paderlol** [comment]
是这个问题 那就是因为没有设置JAVA_HOME环境变量引起的,可以参考下 #712 的pr,下个版本这个问题就没有了,目前建议自己设置以下java环境变量 JAVA_HOME

**Comment by liaozan** [comment]
> 是这个问题 那就是因为没有设置JAVA_HOME环境变量引起的,可以参考下 #712 的pr,下个版本这个问题就没有了,目前建议自己设置以下java环境变量 JAVA_HOME

设置好JAVA_HOME问题解决了
