### ISSUE TITLE
2.04 fail to start on m1 

### ISSUE THREAD

**Issue by fyeeme** [alibaba/nacos#7793]
**Describe the bug**
1. download  .tar.gz 
2.  use in standalone mode
3. seam is not support arm64 ,but i can startup with 1.4.3

**Acutally behavior**

Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/Users/lorraine/Downloads/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.4.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/4g/_n9_019d02j3x9qgbqxb9mzh0000gn/T/librocksdbjni15403411332113230034.jnilib: dlopen(/private/var/folders/4g/_n9_019d02j3x9qgbqxb9mzh0000gn/T/librocksdbjni15403411332113230034.jnilib, 0x0001): tried: '/private/var/folders/4g/_n9_019d02j3x9qgbqxb9mzh0000gn/T/librocksdbjni15403411332113230034.jnilib' (mach-o file, but is an **incompatible architecture (have 'x86_64', need 'arm64e'))** , '/usr/lib/librocksdbjni15403411332113230034.jnilib' (no such file)

**Desktop (please complete the following information):**
 - OS: macos 
 - Version12.1

**Comment by Liubey** [comment]
incompatible architecture (have 'x86_64', need 'arm64e')) ,

**Comment by SayGoodbyeWithSmile** [comment]
so did i
* Version: Nacos-1.4.3(source code)
* OS: 12.2.1  M1

when I try running  NamingApp，I get the same mistake

`Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.consistency.persistent.PersistentConsistencyServiceDelegateImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/26/y6tzy50x4n5_1sl78lp52l7w0000gn/T/librocksdbjni17202709408027714177.jnilib: dlopen(/private/var/folders/26/y6tzy50x4n5_1sl78lp52l7w0000gn/T/librocksdbjni17202709408027714177.jnilib, 0x0001): tried: '/private/var/folders/26/y6tzy50x4n5_1sl78lp52l7w0000gn/T/librocksdbjni17202709408027714177.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni17202709408027714177.jnilib' (no such file)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:187)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300)
	... 120 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/26/y6tzy50x4n5_1sl78lp52l7w0000gn/T/librocksdbjni17202709408027714177.jnilib: dlopen(/private/var/folders/26/y6tzy50x4n5_1sl78lp52l7w0000gn/T/librocksdbjni17202709408027714177.jnilib, 0x0001): tried: '/private/var/folders/26/y6tzy50x4n5_1sl78lp52l7w0000gn/T/librocksdbjni17202709408027714177.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni17202709408027714177.jnilib' (no such file)
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:384)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:228)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:170)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2389)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1953)
	at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
	at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
	at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
	at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
	at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.<clinit>(RocksDBLogStorage.java:75)
	at com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory.createLogStorage(DefaultJRaftServiceFactory.java:50)
	at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:571)
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:991)
	at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:138)
	at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
	at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGroup(JRaftServer.java:268)
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.addRequestProcessors(JRaftProtocol.java:163)
	at com.alibaba.nacos.naming.consistency.persistent.impl.PersistentServiceProcessor.afterConstruct(PersistentServiceProcessor.java:79)
	at com.alibaba.nacos.naming.consistency.persistent.PersistentConsistencyServiceDelegateImpl.createNewPersistentServiceProcessor(PersistentConsistencyServiceDelegateImpl.java:108)
	at com.alibaba.nacos.naming.consistency.persistent.PersistentConsistencyServiceDelegateImpl.<init>(PersistentConsistencyServiceDelegateImpl.java:54)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:175)
	... 122 common frames omitted`

**Comment by lleiwang** [comment]
so am I

```
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'instanceOperatorClientImpl' defined in URL [jar:file:/Users/lleiwang/WorkSpace/console-utils-binary/ry-config-nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.4.jar!/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientOperationServiceProxy' defined in URL [jar:file:/Users/lleiwang/WorkSpace/console-utils-binary/ry-config-nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.4.jar!/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/Users/lleiwang/WorkSpace/console-utils-binary/ry-config-nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.4.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib: dlopen(/private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib, 0x0001): tried: '/private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni5368432748747639712.jnilib' (no such file)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
        at com.alibaba.nacos.Nacos.main(Nacos.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'clientOperationServiceProxy' defined in URL [jar:file:/Users/lleiwang/WorkSpace/console-utils-binary/ry-config-nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.4.jar!/com/alibaba/nacos/naming/core/v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/Users/lleiwang/WorkSpace/console-utils-binary/ry-config-nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.4.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib: dlopen(/private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib, 0x0001): tried: '/private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni5368432748747639712.jnilib' (no such file)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
        ... 27 common frames omitted
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/Users/lleiwang/WorkSpace/console-utils-binary/ry-config-nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.4.jar!/com/alibaba/nacos/naming/core/v2/service/impl/PersistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib: dlopen(/private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib, 0x0001): tried: '/private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni5368432748747639712.jnilib' (no such file)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:304)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196)
        at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
        ... 41 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib: dlopen(/private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib, 0x0001): tried: '/private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni5368432748747639712.jnilib' (no such file)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:187)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300)
        ... 55 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib: dlopen(/private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib, 0x0001): tried: '/private/var/folders/_4/1gvr7bvj6hz01ztf7qzqkv4r0000gn/T/librocksdbjni5368432748747639712.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/lib/librocksdbjni5368432748747639712.jnilib' (no such file)
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
        at java.lang.Runtime.load0(Runtime.java:811)
        at java.lang.System.load(System.java:1088)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.<clinit>(RocksDBLogStorage.java:75)
        at com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory.createLogStorage(DefaultJRaftServiceFactory.java:50)
        at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:579)
        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:999)
        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:139)
        at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
        at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
        at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGroup(JRaftServer.java:268)
        at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.addRequestProcessors(JRaftProtocol.java:163)
        at com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl.<init>(PersistentClientOperationServiceImpl.java:95)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:175)
        ... 57 common frames omitted
```

**Comment by YunWZ** [comment]
try use JDK1.8 .

**Comment by fyeeme** [comment]
@YunWZ  as [offical doc](https://nacos.io/en-us/docs/quick-start.html) says, nacos support jdk 1.8+
```text
64bit OS: Linux/Unix/Mac/Windows supported, Linux/Unix/Mac recommended.
64bit JDK 1.8+: [downloads](http://www.oracle.com/technetwork/java/javase/downloads/jdk8-downloads-2133151.html), [JAVA_HOME settings](https://docs.oracle.com/cd/E19182-01/820-7851/inst_cli_jdk_javahome_t/).
Maven 3.2.x+: [downloads](https://maven.apache.org/download.cgi), [settings](https://maven.apache.org/settings.html).
```

**Comment by fyeeme** [comment]
@YunWZ  jdk 1.8 is also not suppported 


<img width="1493" alt="image" src="https://user-images.githubusercontent.com/6078758/155161664-7d8ddfa1-04ed-4c61-8019-01d9246b7116.png">
<img width="1498" alt="image" src="https://user-images.githubusercontent.com/6078758/155161788-54a4572d-0bf9-4513-8f07-0ac1671fd76e.png">

**Comment by onewe** [comment]
@fyeeme Please use oracle jdk,Don't use zulu jdk.

**Comment by fyeeme** [comment]
@onewe  oracle jdk will use rosseta2, so nacos is not supported  macos arm?

**Comment by vividfish** [comment]
> 

nacos  dependence jraft ，jraft strong dependence rocksdbjni, rocksdbjni 6.29.x will support mac-silicon, but still not publish in maven yet. you can download  rocksdb release  6.29.x and  run `make jclean clean rocksdbjavastaticpublish` to build rocksdbjni  at local. see issue https://github.com/facebook/rocksdb/issues/7720.

**Comment by KomachiSion** [comment]
#4336

**Comment by ityuhan-x** [comment]
m1 pro 
WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'serviceOperatorV2Impl' defined in URL [jar:file:/Users/lhf/Downloads/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.1.0-BETA.jar!/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'namingMetadataOperateService' defined in URL [jar:file:/Users/lhf/Downloads/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.1.0-BETA.jar!/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.metadata.NamingMetadataOperateService]: Constructor threw exception; nested exception is com.alibaba.nacos.core.distributed.raft.exception.JRaftException: java.io.IOException: Failed to bind
