### ISSUE TITLE
gRPC not supports https?

### ISSUE THREAD

**Issue by myifeng** [alibaba/nacos#7842]
**Describe the bug**

We need to use https for grpc connection, but I set the link address of https, and grpc still uses http.  I got the following error:

```
2022-02-25 16:33:03.659  INFO 602256 --- [t.remote.worker] com.alibaba.nacos.common.remote.client   : [e068c063-3fe4-45d0-b400-76d7e642c08d_config-0] Try to reconnect to a new server, server is  not appointed, will choose a random server.
2022-02-25 16:33:03.660  INFO 602256 --- [           main] com.alibaba.nacos.common.remote.client   : [e068c063-3fe4-45d0-b400-76d7e642c08d_config-0] Register server push request handler:com.alibaba.nacos.common.remote.client.RpcClient$ConnectResetRequestHandler
2022-02-25 16:33:03.660  INFO 602256 --- [           main] com.alibaba.nacos.common.remote.client   : [e068c063-3fe4-45d0-b400-76d7e642c08d_config-0] Register server push request handler:com.alibaba.nacos.common.remote.client.RpcClient$$Lambda$346/2124360754
2022-02-25 16:33:03.661 DEBUG 602256 --- [ault-executor-0] c.a.n.s.i.grpc.internal.DnsNameResolver  : No TXT records found for tb-tst6.domain.com
2022-02-25 16:33:03.697 DEBUG 602256 --- [-worker-ELG-1-8] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x461b3c7e, L:/10.119.144.121:49468 - R:tb-tst6.domain.com/10.102.84.158:9848] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
2022-02-25 16:33:03.697 DEBUG 602256 --- [-worker-ELG-1-8] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x461b3c7e, L:/10.119.144.121:49468 - R:tb-tst6.domain.com/10.102.84.158:9848] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2022-02-25 16:33:03.700 DEBUG 602256 --- [-worker-ELG-1-8] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x461b3c7e, L:/10.119.144.121:49468 - R:tb-tst6.domain.com/10.102.84.158:9848] INBOUND SETTINGS: ack=false settings=[id: 0x461b3c7e, L:/10.119.144.121:49468 - R:tb-tst6.domain.com/10.102.84.158:9848]
2022-02-25 16:33:03.700 DEBUG 602256 --- [-worker-ELG-1-8] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x461b3c7e, L:/10.119.144.121:49468 - R:tb-tst6.domain.com/10.102.84.158:9848] OUTBOUND SETTINGS: ack=true
2022-02-25 16:33:03.702 DEBUG 602256 --- [-worker-ELG-1-8] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x461b3c7e, L:/10.119.144.121:49468 - R:tb-tst6.domain.com/10.102.84.158:9848] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: tb-tst6.domain.com:9848, :path: /Request/request, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.24.0, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2022-02-25 16:33:03.702 DEBUG 602256 --- [-worker-ELG-1-8] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0x461b3c7e, L:/10.119.144.121:49468 - R:tb-tst6.domain.com/10.102.84.158:9848] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=81 bytes=000000004c12241a12536572766572436865636b52657175657374420e31302e3131392e3134342e3132311a2412227b2268656164657273223a7b7d2c226d6f...
2022-02-25 16:33:03.726 DEBUG 602256 --- [-worker-ELG-1-8] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : Network channel is closed
2022-02-25 16:33:03.728 ERROR 602256 --- [t.remote.worker] c.a.n.c.remote.client.grpc.GrpcClient    : Server check fail, please check server tb-tst6.domain.com ,port 9848 is available , error ={}

java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:445) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:148) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:264) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:522) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.lambda$start$2(RpcClient.java:370) [nacos-client-2.0.4.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
Caused by: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at com.alibaba.nacos.shaded.io.grpc.Status.asRuntimeException(Status.java:533) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[nacos-client-2.0.4.jar:na]
	... 3 common frames omitted

2022-02-25 16:33:03.845 DEBUG 602256 --- [ault-executor-0] c.a.n.s.i.grpc.internal.DnsNameResolver  : No TXT records found for tb-tst6.domain.com
2022-02-25 16:33:03.875 DEBUG 602256 --- [worker-ELG-1-10] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0xaecb923f, L:/10.119.144.121:49469 - R:tb-tst6.domain.com/10.102.84.158:9848] OUTBOUND SETTINGS: ack=false settings={ENABLE_PUSH=0, MAX_CONCURRENT_STREAMS=0, INITIAL_WINDOW_SIZE=1048576, MAX_HEADER_LIST_SIZE=8192}
2022-02-25 16:33:03.876 DEBUG 602256 --- [worker-ELG-1-10] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0xaecb923f, L:/10.119.144.121:49469 - R:tb-tst6.domain.com/10.102.84.158:9848] OUTBOUND WINDOW_UPDATE: streamId=0 windowSizeIncrement=983041
2022-02-25 16:33:03.879 DEBUG 602256 --- [worker-ELG-1-10] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0xaecb923f, L:/10.119.144.121:49469 - R:tb-tst6.domain.com/10.102.84.158:9848] INBOUND SETTINGS: ack=false settings=[id: 0xaecb923f, L:/10.119.144.121:49469 - R:tb-tst6.domain.com/10.102.84.158:9848]
2022-02-25 16:33:03.880 DEBUG 602256 --- [worker-ELG-1-10] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0xaecb923f, L:/10.119.144.121:49469 - R:tb-tst6.domain.com/10.102.84.158:9848] OUTBOUND SETTINGS: ack=true
2022-02-25 16:33:03.882 DEBUG 602256 --- [worker-ELG-1-10] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0xaecb923f, L:/10.119.144.121:49469 - R:tb-tst6.domain.com/10.102.84.158:9848] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: tb-tst6.domain.com:9848, :path: /Request/request, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.24.0, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
2022-02-25 16:33:03.883 DEBUG 602256 --- [worker-ELG-1-10] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0xaecb923f, L:/10.119.144.121:49469 - R:tb-tst6.domain.com/10.102.84.158:9848] OUTBOUND DATA: streamId=3 padding=0 endStream=true length=81 bytes=000000004c12241a12536572766572436865636b52657175657374420e31302e3131392e3134342e3132311a2412227b2268656164657273223a7b7d2c226d6f...
2022-02-25 16:33:03.917 DEBUG 602256 --- [worker-ELG-1-10] c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : Network channel is closed
2022-02-25 16:33:03.920 ERROR 602256 --- [t.remote.worker] c.a.n.c.remote.client.grpc.GrpcClient    : Server check fail, please check server tb-tst6.domain.com ,port 9848 is available , error ={}

java.util.concurrent.ExecutionException: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:566) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:445) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:148) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:264) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:522) [nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.lambda$start$2(RpcClient.java:370) [nacos-client-2.0.4.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) ~[na:1.8.0_212]
	at java.util.concurrent.FutureTask.run(FutureTask.java) ~[na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_212]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_212]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_212]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_212]
Caused by: com.alibaba.nacos.shaded.io.grpc.StatusRuntimeException: UNAVAILABLE: Network closed for unknown reason
	at com.alibaba.nacos.shaded.io.grpc.Status.asRuntimeException(Status.java:533) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$UnaryStreamToFuture.onClose(ClientCalls.java:490) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.CensusStatsModule$StatsClientInterceptor$1$1.onClose(CensusStatsModule.java:700) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.PartialForwardingClientCallListener.onClose(PartialForwardingClientCallListener.java:39) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ForwardingClientCallListener.onClose(ForwardingClientCallListener.java:23) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.ForwardingClientCallListener$SimpleForwardingClientCallListener.onClose(ForwardingClientCallListener.java:40) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.CensusTracingModule$TracingClientInterceptor$1$1.onClose(CensusTracingModule.java:399) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.closeObserver(ClientCallImpl.java:510) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl.access$300(ClientCallImpl.java:66) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.close(ClientCallImpl.java:630) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl.access$700(ClientCallImpl.java:518) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInternal(ClientCallImpl.java:692) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ClientCallImpl$ClientStreamListenerImpl$1StreamClosed.runInContext(ClientCallImpl.java:681) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37) ~[nacos-client-2.0.4.jar:na]
	at com.alibaba.nacos.shaded.io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123) ~[nacos-client-2.0.4.jar:na]
	... 3 common frames omitted
```

I refer to #3315 and try to use `System.setProperty(TlsSystemConfig.TLS_ENABLE, "true");`, but it doesn't solve my problem.

```yaml
spring:
  cloud:
    nacos:
      config:
        server-addr: https://tb-tst6.domain.com:8848
        file-extension: yaml
        namespace: *****
      discovery:
        enabled: true
        server-addr: https://tb-tst6.domain.com:8848
        namespace: *****
```
log:
```
c.a.n.s.i.g.n.s.i.g.n.NettyClientHandler : [id: 0xb212bce9, L:/10.119.144.121:49470 - R:tb-tst6.domain.com/10.102.84.158:9848] OUTBOUND HEADERS: streamId=3 headers=GrpcHttp2OutboundHeaders[:authority: tb-tst6.domain.com:9848, :path: /Request/request, :method: POST, :scheme: http, content-type: application/grpc, te: trailers, user-agent: grpc-java-netty/1.24.0, grpc-accept-encoding: gzip] streamDependency=0 weight=16 exclusive=false padding=0 endStream=false
```

**Expected behavior**
grpc with https

**Acutally behavior**
Server check fail

**How to Reproduce**

**Desktop (please complete the following information):**
 - OS: [client: windows, server: Linux]
 - Version [e.g. nacos-server 2.0.3, nacos-client 2.0.3]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by myifeng** [comment]
@KomachiSion Indeed, Amazon ELB interrupted the connection with status code 400, because the connection requires HTTPS instead of HTTP. 

Therefore, my question is why I have configured HTTPS, but grpc still uses http. 

My expectation is that grpc uses HTTPS.

**Comment by myifeng** [comment]
@realJackSun @KomachiSion How to configure gprc to use https？

**Comment by KomachiSion** [comment]
Need to research grpc and use https, I think.

**Comment by wenerme** [comment]
@KomachiSion why closed ?

**Comment by wenerme** [comment]
GrpcClient 写死了 usePlainText，可以改成可配置么

**Comment by xujunhua555** [comment]
兄弟，你后面问题查出来了吗

**Comment by Jevgens** [comment]
****

**Comment by akwangl** [comment]
官方就不考虑两种协议都支持吗，默认grpc
