### ISSUE TITLE
queryConfigInfoByNamespace -BadSqlGrammarException

### ISSUE THREAD

**Issue by worldofchu** [alibaba/nacos#7923]
2022-03-10 09:05:49,658 ERROR CONSOLE /nacos/v1/cs/history/configs

org.springframework.jdbc.BadSqlGrammarException: PreparedStatementCallback; bad SQL grammar [SELECT data_id,group_id,tenant_id,app_name,type FROM config_info_beta WHERE tenant_id=?]; nested exception is java.sql.SQLSyntaxErrorException: ORA-00904: "TYPE": 标识符无效

	at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:239)
	at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
	at org.springframework.jdbc.core.JdbcTemplate.translateException(JdbcTemplate.java:1443)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:633)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:669)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:700)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:712)
	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:763)
	at com.alibaba.nacos.config.server.service.repository.extrnal.ExternalStoragePersistServiceImpl.queryConfigInfoByNamespace(ExternalStoragePersistServiceImpl.java:2835)
	at com.alibaba.nacos.config.server.controller.HistoryController.getDataIds(HistoryController.java:175)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	 
Caused by: java.sql.SQLSyntaxErrorException: ORA-00904: "TYPE": 标识符无效

**Comment by Chaos-coder** [comment]
> 

nacos版本是多少呢，我这边在nacos2.0.4下未能复现

**Comment by KomachiSion** [comment]
no more response from author, we think the problem has solved.
