### ISSUE TITLE
An LDAP authentication error occurs

### ISSUE THREAD

**Issue by zhangwenliang012** [alibaba/nacos#7954]
2022-03-18 14:03:26,941 ERROR login error:[LDAP: error code 49 - 80090308: LdapErr: DSID-0C090447, comment: AcceptSecurityContext error, data 52e, v3839]

2022-03-18 14:03:26,942 ERROR CONSOLE /nacos/v1/auth/users/login

java.lang.RuntimeException: login error!
	at com.alibaba.nacos.console.security.nacos.LdapAuthenticationProvider.ldapLogin(LdapAuthenticationProvider.java:145)
	at com.alibaba.nacos.console.security.nacos.LdapAuthenticationProvider.authenticate(LdapAuthenticationProvider.java:97)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:200)

config：
nacos.core.auth.system.type=ldap

### If turn on auth system:
nacos.core.auth.enabled=true

### worked when nacos.core.auth.system.type=ldap，{0} is Placeholder,replace login username
nacos.core.auth.ldap.url=ldap://*.*.*.*:389
nacos.core.auth.ldap.userdn=cn={0},dc=prenp,dc=cn

**Comment by zhangwenliang012** [comment]
Whether to configure the user name and password

**Comment by KomachiSion** [comment]
LDAP is contributed by community fully, need community help

**Comment by karsonto** [comment]
Please reference #7924 comment
