### ISSUE TITLE
JSON格式配置不正确

### ISSUE THREAD

**Issue by chandlerFan** [alibaba/nacos#799]
现象:
在控制台编辑配置，配置格式为JSON,配置内容为标准的json格式
[
    {
        "jdbc":"a",
        "url":"cc"
    }
],

项目启动报错:
Caused by: java.lang.IllegalArgumentException: Could not resolve placeholder 'jdbc' in string value "${jdbc}"
	at org.springframework.util.PropertyPlaceholderHelper.parseStringValue(PropertyPlaceholderHelper.java:173)
	at org.springframework.util.PropertyPlaceholderHelper.replacePlaceholders(PropertyPlaceholderHelper.java:125)
	at org.springframework.core.env.AbstractPropertyResolver.doResolvePlaceholders(AbstractPropertyResolver.java:190)
	at org.springframework.core.env.AbstractPropertyResolver.resolveRequiredPlaceholders(AbstractPropertyResolver.java:164)
	at org.springframework.context.support.PropertySourcesPlaceholderConfigurer$2.resolveStringValue(PropertySourcesPlaceholderConfigurer.java:167)
	at org.springframework.beans.factory.support.AbstractBeanFactory.resolveEmbeddedValue(AbstractBeanFactory.java:764)

如果改成非标准json格式，编辑器提醒格式异常，项目却可以正常启动并且读取数据
[
    {
        jdbc:a,
        url:cc
    }
]

原因:
项目读取配置是用NacosUtils#toProperties()方法，最终是使用java.util.Properties#load()方法，这个方法加载标准json格式后，key都是带双引号的，导致spring无法识别配置，去掉配置的双引号就可以了，但是编辑器却提醒格式异常。

**Comment by fallingyou** [comment]
读取的值后面还会多一个逗号

**Comment by KomachiSion** [comment]
Can you try to use latest version and retry? The issue is too old to search. If latest version still has problem, please open a new issue let us know.
