### ISSUE TITLE
failed to req API:/nacos/v1/ns/instance

### ISSUE THREAD

**Issue by zhengziw** [alibaba/nacos#8046]
nacos log:
failed to req API:http://nacosserver.cn/nacos/v1/ns/instance. code:500 msg: java.net.SocketTimeoutException: connect timed out

java console:
Caused by: java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/instance after all servers([nacosserver.cn]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:375)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:294)
	at com.alibaba.nacos.client.naming.net.NamingProxy.registerService(NamingProxy.java:176)
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:185)
	at com.alibaba.dubbo.registry.nacos.NacosRegistry$2.callback(NacosRegistry.java:134)
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.execute(NacosRegistry.java:457)
	at com.alibaba.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:132)
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:230)
	... 29 common frames omitted

**Comment by zhengziw** [comment]
windows上启动没问题，mac m1启动，注册dubbo服务时超时
