### ISSUE TITLE
 The problem of springmvc starting to connect to the configuration center of nacos

### ISSUE THREAD

**Issue by andyhewenhui** [alibaba/nacos#8070]
In nacos 2.0.4, our client is the 4.3.18.RELEASE of springmvc. Our service for connecting to nacos is Discovery to be very good, but once we connect to the configuration center, our own tomcat will start an error. In addition, an error will be reported once the nacos annotation is opened. ex： <nacos:annotation-driven></nacos:annotation-driven>

The error that occurs when our tomcat starts is as follows:
[ERROR][2022-04-01 14:55:25] org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:355) Context initialization failed 
java.lang.NoSuchMethodError: com.alibaba.spring.util.BeanUtils.getBeanNames(Lorg/springframework/beans/factory/config/ConfigurableListableBeanFactory;Ljava/lang/Class;)[Ljava/lang/String;
        at com.alibaba.nacos.spring.core.env.NacosPropertySourcePostProcessor.postProcessBeanFactory(NacosPropertySourcePostProcessor.java:152)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:283)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.invokeBeanFactoryPostProcessors(PostProcessorRegistrationDelegate.java:127)
        at org.springframework.context.support.AbstractApplicationContext.invokeBeanFactoryPostProcessors(AbstractApplicationContext.java:687)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:525)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:443)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:325)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:107)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4900)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5363)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:145)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1410)
        at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1400)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
01-Apr-2022 14:55:25.282 严重 [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file

**Comment by andyhewenhui** [comment]
<?xml version="1.0" encoding="UTF-8"?>
<beans xmlns="http://www.springframework.org/schema/beans"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xmlns:nacos="http://nacos.io/schema/nacos"
       xmlns:dubbo="http://dubbo.apache.org/schema/dubbo"
       xsi:schemaLocation="http://www.springframework.org/schema/beans http://www.springframework.org/schema/beans/spring-beans.xsd
       http://nacos.io/schema/nacos http://nacos.io/schema/nacos.xsd
       http://dubbo.apache.org/schema/dubbo http://dubbo.apache.org/schema/dubbo/dubbo.xsd" default-lazy-init="false">

    


    <nacos:global-properties server-addr="${nacos.server.addr}" namespace="${nacos.namespace}" />
    
    <nacos:property-source data-id="kada-server.properties" group-id="DEFAULT_GROUP" auto-refreshed="false" />


    
    
    <dubbo:application name="kada-server" >
        <dubbo:parameter key="qos.port" value="33333"/>
    </dubbo:application>
    
    <dubbo:registry address="${nacos.protocol.addr}" port="20881" />
    
    

    <dubbo:reference id="userService" interface="com.hhdd.dts.common.UserService" check="false" timeout="5000"/>



</beans>

**Comment by KomachiSion** [comment]
`java.lang.NoSuchMethodError: com.alibaba.spring.util.BeanUtils.getBeanNames(Lorg/springframework/beans/factory/config/ConfigurableListableBeanFactory;Ljava/lang/Class;)[Ljava/lang/String;`

I think it is the reason, the spring mvc version or spring version is not match.

**Comment by andyhewenhui** [comment]
[nacos-examples](https://github.com/nacos-group/nacos-examples)/[nacos-spring-example](https://github.com/nacos-group/nacos-examples/tree/master/nacos-spring-example)/pom.xml    include <spring.framework.version>3.2.18.RELEASE</spring.framework.version>  , but we use spring-framework 4.3.18 ,how to solve this problem?

**Comment by KomachiSion** [comment]
fix in nacos-spring to support spring-framework 4.3.18

**Comment by andyhewenhui** [comment]
> fix in nacos-spring to support spring-framework 4.3.18


When will it be settled? What version?

**Comment by andyhewenhui** [comment]
We use nacos-spring-context 1.1.1 version ，Isn't it 1.1.2?

**Comment by KomachiSion** [comment]
I have no idea, it depend whether has someone from community to support it. If there are still no one to do this. Maybe the issue is not `issue` itself.

**Comment by payephyoeaung87** [comment]
I live in Myanmar and I'm not sure what the subject is.  Please explain to me if possible.  I'm trying to be the best I can be

**Comment by payephyoeaung87** [comment]
And now there seems to be someone trying to harass me and steal my information.  Let me ask you to help me with this as well.

**Comment by andyhewenhui** [comment]
I have abandoned the spring xml way to use nacos's config, and I now use NacosFactory to implement classes written by myself
