### ISSUE TITLE
gateway+nacos：java.net.UnknownHostException

### ISSUE THREAD

**Issue by GoGOGORS** [alibaba/nacos#8089]
框架版本：springboot2.6.4+springcloud2021.0.1
问题描述：在测试新版本的整合问题时，我发现在gateway中的 uri配置为服务名称时，无法根据服务名称获取到服务对应的ip：port，而当我配置uri完整的（uri：127.0.0.1:8100）ip时，可以通过gateway调用到具体服务。
[学习代码仓库：](https://github.com/GoGOGORS/spring-cloud-cli.git)
请大佬指教，感激不尽

gateway下的application：
`server:
  port: 8600

spring:
  application:
    name: gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.199.5:8848
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: userServiceRouter
          uri: http://user-consumer
          predicates:
            - Path=/api/userService/user/**
          filters:
            - StripPrefix=2`

**Comment by huhu-sky** [comment]
你的问题应该是  lb:// 吧；   uri: lb://user-consumer

**Comment by GoGOGORS** [comment]
> 



> 你的问题应该是 lb:// 吧； uri: lb://user-consumer

这个还真的不是，如果你用lb虽然控制台不会出错，但是访问会没有结果

**Comment by KomachiSion** [comment]
看起来和nacos没什么关系，应该是网关问题吧。

**Comment by GoGOGORS** [comment]
> 就是不知道什么问题，查资料也没找到，就来这里求助了

**Comment by huhu-sky** [comment]
你把具体错误信息贴出来吧；  请求方、gateway、被请求方；
看是哪个的host 被 unknown；

如果用了 lb://user-consumer 没有报错，但是访问没有结果， 这个没有结果是怎么样的表现， 是 responsecode 200 ？还是不响应 还是其它？， 具体说明吧

**Comment by huhu-sky** [comment]
你把具体错误信息贴出来吧；  请求方、gateway、被请求方；
看是哪个的host 被 unknown；

如果用了 lb://user-consumer 没有报错，但是访问没有结果， 这个没有结果是怎么样的表现， 是 responsecode 200 ？还是不响应 还是其它？， 具体说明吧

**Comment by GoGOGORS** [comment]
> 你把具体错误信息贴出来吧； 请求方、gateway、被请求方； 看是哪个的host 被 unknown；
> 
> 如果用了 lb://user-consumer 没有报错，但是访问没有结果， 这个没有结果是怎么样的表现， 是 responsecode 200 ？还是不响应 还是其它？， 具体说明吧

如果使用http， gateway的控制台会出现：

java.net.UnknownHostException: Failed to resolve 'user-consumer' after 4 queries 
	at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047) ~[netty-resolver-dns-4.1.74.Final.jar:4.1.74.Final]
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP GET "/api/userService/user/addUser/jsf" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047) ~[netty-resolver-dns-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000) ~[netty-resolver-dns-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418) ~[netty-resolver-dns-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:971) ~[netty-resolver-dns-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.resolver.dns.DnsResolveContext.access$700(DnsResolveContext.java:66) ~[netty-resolver-dns-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:471) ~[netty-resolver-dns-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) [netty-common-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) [netty-common-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) [netty-common-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) [netty-common-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) [netty-common-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) [netty-common-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) [netty-common-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:216) ~[netty-resolver-dns-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:208) ~[netty-resolver-dns-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1314) ~[netty-resolver-dns-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[netty-codec-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[netty-transport-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986) ~[netty-common-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[netty-common-4.1.74.Final.jar:4.1.74.Final]
		at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[netty-common-4.1.74.Final.jar:4.1.74.Final]
		at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_171]

返回信息为：
{
    "timestamp": "2022-04-07T05:39:05.803+00:00",
    "path": "/api/userService/user/addUser/jsf",
    "status": 500,
    "error": "Internal Server Error",
    "requestId": "8314cdb4-1"
}

如果是使用lb，控制台无错误信息，但返回错误503：
{
    "timestamp": "2022-04-07T05:41:35.934+00:00",
    "path": "/api/userService/user/addUser/jsf",
    "status": 503,
    "error": "Service Unavailable",
    "requestId": "aa315a8b-1"
}

**Comment by GoGOGORS** [comment]
我把springboot版本回退到了2.3.12.RELEASE，spring cloud版本为Hoxton.SR12，alibaba的版本为2.2.7.RELEASE
<spring-boot.version>2.3.12.RELEASE</spring-boot.version>
<spring-cloud.version>Hoxton.SR12</spring-cloud.version>
<spring.alibaba.version>2.2.7.RELEASE</spring.alibaba.version>

并且不修改任何配置的情况下，uri使用lb，可以正常使用gateway。

然后切换回新版本，同样是错误，，，，这算是个bug把

**Comment by KomachiSion** [comment]
那应该是SCA的bug吧，建议把信息收集完全，然后提交到SCA社区看看。

**Comment by Wizarder54088** [comment]
我也遇到这个Bug了很难受啊。
