### ISSUE TITLE
nacos 心跳问题

### ISSUE THREAD

**Issue by zhangle910522** [alibaba/nacos#8090]
nacos 服务端：2.0.0
nacos client：1.3.3 
我们这边发现一个问题，使用nacos集群情况下，某个master 节点full gc 时间达到了两分钟，导致很多client 无法连接服务端，master 恢复后，发现客户端心跳时间 比当前时间 小太多，因此剔除了改客户端的健康实例，然后推送通知到应用 导致其上游服务无法获取到服务列表。麻烦确认下是否存在这个问题。

client naming.log  日志

2022-04-06 18:42:19.535 ERROR [com.alibaba.nacos.client.naming.updater:client.naming] [NA] failed to request
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method) ~[?:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350) ~[?:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206) ~[?:1.8.0_151]
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188) ~[?:1.8.0_151]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392) ~[?:1.8.0_151]
        at java.net.Socket.connect(Socket.java:589) ~[?:1.8.0_151]
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175) ~[?:1.8.0_151]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:463) ~[?:1.8.0_151]
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:558) ~[?:1.8.0_151]
        at sun.net.www.http.HttpClient.<init>(HttpClient.java:242) ~[?:1.8.0_151]
        at sun.net.www.http.HttpClient.New(HttpClient.java:339) ~[?:1.8.0_151]
        at sun.net.www.http.HttpClient.New(HttpClient.java:357) ~[?:1.8.0_151]
        at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220) ~[?:1.8.0_151]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156) ~[?:1.8.0_151]
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050) ~[?:1.8.0_151]
        at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984) ~[?:1.8.0_151]

server naming.log 日志
2022-04-06 18:42:19,704 INFO {POS} {IP-DISABLED} valid: 172.22.23.213:21817@DEFAULT@DEFAULT_GROUP@@message-center, region: unknown, msg: client timeout after 15000, last beat: 1649241621615

2022-04-06 18:42:19,704 INFO {POS} {IP-DISABLED} valid: 172.22.23.212:21817@DEFAULT@DEFAULT_GROUP@@message-center, region: unknown, msg: client timeout after 15000, last beat: 1649241619536

2022-04-06 18:42:19,704 INFO {POS} {IP-DISABLED} valid: 172.22.23.211:21807@DEFAULT@DEFAULT_GROUP@@user-center, region: unknown, msg: client timeout after 15000, last beat: 1649241620260

2022-04-06 18:42:19,704 INFO {POS} {IP-DISABLED} valid: 172.22.23.210:21807@DEFAULT@DEFAULT_GROUP@@user-center, region: unknown, msg: client timeout after 15000, last beat: 1649241620147

**Comment by KomachiSion** [comment]
非持久化实例，过期不发心跳会分为级别判断，默认15s变为不健康， 默认30s移除。您截图这部分是变为不健康的部分，不是移除的部分。

这个问题你可以尝试升级服务端到新版本，新版本中的verify逻辑是会更新非责任节点的心跳时间的。

另一点就是fullGC的问题，这个需要你再排查下或者多提供些信息，可能是内存设置不合理，也可能是其他原因。

最后可以尝试将客户端升级到2.0的最新版本，可以极大缓解问题。

**Comment by zhangle910522** [comment]
> 非持久化实例，过期不发心跳会分为级别判断，默认15s变为不健康， 默认30s移除。您截图这部分是变为不健康的部分，不是移除的部分。
> 
> 这个问题你可以尝试升级服务端到新版本，新版本中的verify逻辑是会更新非责任节点的心跳时间的。
> 
> 另一点就是fullGC的问题，这个需要你再排查下或者多提供些信息，可能是内存设置不合理，也可能是其他原因。
> 
> 最后可以尝试将客户端升级到2.0的最新版本，可以极大缓解问题。

fgc的问题 后面排查是因为 当前服务器内存使用紧张 同时开启了 swap，导致触发了 swap内存置换 最终导致 fgc 时间过长，感谢 回复
