### ISSUE TITLE
nacos-server 1.4.2 线程大量BLOCKED，cpu打满

### ISSUE THREAD

**Issue by wyt** [alibaba/nacos#8165]
三台集群节点，其中一个节点cpu打满，重启立刻打满，其他节点无问题，堆栈中大量线程被阻塞：

所有阻塞线程处理：com.alibaba.nacos.console.security.nacos.JwtTokenManager.validateToken(JwtTokenManager.java:100)

线程dump：

[https://github.com/wyt/nacos-problem/blob/main/tdump.out_bogon_220415110625](url)

@KomachiSion 帮忙分析下，谢谢

**Comment by liqipeng** [comment]
好像提供的背景信息比较少（比如是在使用什么功能naming or config引发的、多少数据量、机器是什么配置、jvm参数如何设置、出现问题时gc情况、服务日常请求量），建议补充更多信息，如果有自行排查的分析或者测最好也提供一下。

**Comment by wyt** [comment]
ui里改过nacos密码，其他没动过。qps100左右吧

**Comment by jefferson-chern** [comment]
你们开启了鉴权功能吗？

**Comment by jefferson-chern** [comment]
然后你们的实例数有多少？naming-performance.log日志看看

**Comment by liqipeng** [comment]
https://github.com/wyt/nacos-problem/blob/main/tid
根据你提供的信息 （ https://github.com/wyt/nacos-problem/blob/main/top https://github.com/wyt/nacos-problem/blob/main/tid ） ，可以看到：
```
[root@bogon logs]# top
top - 11:22:29 up 15 days, 21:06,  2 users,  load average: 74.49, 72.00, 63.93
Tasks: 139 total,   1 running, 137 sleeping,   1 stopped,   0 zombie
%Cpu(s): 97.2 us,  1.6 sy,  0.0 ni,  0.9 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
KiB Mem :  3872672 total,   200780 free,  3200704 used,   471188 buff/cache
KiB Swap:  1048572 total,   555532 free,   493040 used.   411640 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                 
56623 app       20   0 6432780   2.3g  18028 S 394.7 61.5 153:37.39 java                                                                                                                    
  947 root      20   0 1100208  24644   4812 S   0.7  0.6 340:52.88 sky-agent                                                                                                               
 3758 root      20   0 4378672 481312   6484 S   0.7 12.4 328:35.14 java                                                                                                                    
 3793 app       20   0  219272  24600   1092 S   0.7  0.6   2:35.55 redis-server 
[root@bogon ~]# top -Hp 56623
top - 11:06:27 up 15 days, 20:50,  2 users,  load average: 58.19, 52.27, 56.39
Threads: 458 total,   1 running, 457 sleeping,   0 stopped,   0 zombie
%Cpu(s): 26.8 us,  2.8 sy,  0.0 ni, 69.0 id,  0.0 wa,  0.0 hi,  1.4 si,  0.0 st
KiB Mem :  3872672 total,   249484 free,  3042620 used,   580568 buff/cache
KiB Swap:  1048572 total,   547764 free,   500808 used.   569896 avail Mem 

  PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                  
56629 app       20   0 6403996   2.1g  18000 R 94.1 57.5   0:18.73 java                                                                                                                     
56623 app       20   0 6403996   2.1g  18000 S  0.0 57.5   0:00.01 java                                                                                                                     
56624 app       20   0 6403996   2.1g  18000 S  0.0 57.5   0:22.26 java     
```
线程 56629 （十六进制）占用CPU较多

https://raw.githubusercontent.com/wyt/nacos-problem/main/tdump.out_bogon_220415110625 里：
```
"VM Thread" os_prio=0 tid=0x00007f86c4140000 nid=0xdd35 runnable 

"GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f86c4020000 nid=0xdd31 runnable 
```

即是 "VM Thread" 占用了大量CPU，说明是出现了GC问题。

**Comment by wyt** [comment]
> https://github.com/wyt/nacos-problem/blob/main/tid 根据你提供的信息 （ https://github.com/wyt/nacos-problem/blob/main/top https://github.com/wyt/nacos-problem/blob/main/tid ） ，可以看到：
> 
> ```
> [root@bogon logs]# top
> top - 11:22:29 up 15 days, 21:06,  2 users,  load average: 74.49, 72.00, 63.93
> Tasks: 139 total,   1 running, 137 sleeping,   1 stopped,   0 zombie
> %Cpu(s): 97.2 us,  1.6 sy,  0.0 ni,  0.9 id,  0.0 wa,  0.0 hi,  0.3 si,  0.0 st
> KiB Mem :  3872672 total,   200780 free,  3200704 used,   471188 buff/cache
> KiB Swap:  1048572 total,   555532 free,   493040 used.   411640 avail Mem 
> 
>   PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                 
> 56623 app       20   0 6432780   2.3g  18028 S 394.7 61.5 153:37.39 java                                                                                                                    
>   947 root      20   0 1100208  24644   4812 S   0.7  0.6 340:52.88 sky-agent                                                                                                               
>  3758 root      20   0 4378672 481312   6484 S   0.7 12.4 328:35.14 java                                                                                                                    
>  3793 app       20   0  219272  24600   1092 S   0.7  0.6   2:35.55 redis-server 
> [root@bogon ~]# top -Hp 56623
> top - 11:06:27 up 15 days, 20:50,  2 users,  load average: 58.19, 52.27, 56.39
> Threads: 458 total,   1 running, 457 sleeping,   0 stopped,   0 zombie
> %Cpu(s): 26.8 us,  2.8 sy,  0.0 ni, 69.0 id,  0.0 wa,  0.0 hi,  1.4 si,  0.0 st
> KiB Mem :  3872672 total,   249484 free,  3042620 used,   580568 buff/cache
> KiB Swap:  1048572 total,   547764 free,   500808 used.   569896 avail Mem 
> 
>   PID USER      PR  NI    VIRT    RES    SHR S %CPU %MEM     TIME+ COMMAND                                                                                                                  
> 56629 app       20   0 6403996   2.1g  18000 R 94.1 57.5   0:18.73 java                                                                                                                     
> 56623 app       20   0 6403996   2.1g  18000 S  0.0 57.5   0:00.01 java                                                                                                                     
> 56624 app       20   0 6403996   2.1g  18000 S  0.0 57.5   0:22.26 java     
> ```
> 
> 线程 56629 （十六进制）占用CPU较多
> 
> https://raw.githubusercontent.com/wyt/nacos-problem/main/tdump.out_bogon_220415110625 里：
> 
> ```
> "VM Thread" os_prio=0 tid=0x00007f86c4140000 nid=0xdd35 runnable 
> 
> "GC task thread#0 (ParallelGC)" os_prio=0 tid=0x00007f86c4020000 nid=0xdd31 runnable 
> ```
> 
> 即是 "VM Thread" 占用了大量CPU，说明是出现了GC问题。

后面再抓tid都是业务线程，vm线程没怎么出现，而且重启完了立马cpu就上来了，
看起来更像是com.alibaba.nacos.console.security.nacos.NacosAuthManager.resolveTokenFromUser(NacosAuthManager.java:132)
处理这块逻辑的线程在消耗cpu

"http-nio-8848-exec-198" #366 daemon prio=5 os_prio=0 tid=0x00007f86581b3800 nid=0xded6 runnable [0x00007f860c645000]
   java.lang.Thread.State: RUNNABLE
	at org.springframework.security.crypto.bcrypt.BCrypt.crypt_raw(BCrypt.java:510)
	at org.springframework.security.crypto.bcrypt.BCrypt.hashpw(BCrypt.java:590)
	at org.springframework.security.crypto.bcrypt.BCrypt.checkpw(BCrypt.java:659)
	at org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder.matches(BCryptPasswordEncoder.java:102)
	at org.springframework.security.authentication.dao.DaoAuthenticationProvider.additionalAuthenticationChecks(DaoAuthenticationProvider.java:90)
	at org.springframework.security.authentication.dao.AbstractUserDetailsAuthenticationProvider.authenticate(AbstractUserDetailsAuthenticationProvider.java:166)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:175)
	at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:200)
	at org.springframework.security.config.annotation.web.configuration.WebSecurityConfigurerAdapter$AuthenticationManagerDelegator.authenticate(WebSecurityConfigurerAdapter.java:514)
	at com.alibaba.nacos.console.security.nacos.NacosAuthManager.resolveTokenFromUser(NacosAuthManager.java:132)
	at com.alibaba.nacos.console.security.nacos.NacosAuthManager.resolveToken(NacosAuthManager.java:121)
	at com.alibaba.nacos.console.security.nacos.NacosAuthManager.login(NacosAuthManager.java:65)
	at com.alibaba.nacos.console.controller.UserController.login(UserController.java:208)
	at sun.reflect.GeneratedMethodAccessor186.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:190)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:138)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:105)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:892)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:797)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1040)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:943)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:909)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:652)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:733)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:97)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:130)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:209)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:358)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:271)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:94)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.filterAndRecordMetrics(WebMvcMetricsFilter.java:114)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:104)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:202)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:143)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:690)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:343)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:374)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:868)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1590)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	- locked <0x00000000abbf9028> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)

   Locked ownable synchronizers:
	- <0x000000008f8257f0> (a java.util.concurrent.ThreadPoolExecutor$Worker)

**Comment by liqipeng** [comment]
可以考虑用 (arthas)[https://github.com/alibaba/arthas] 分析一下吧

**Comment by wyt** [comment]
> 

https://github.com/wyt/nacos-problem/tree/main/arthas

arthas抓了cpu消耗top10

基本定位就是这段逻辑引发的

at com.alibaba.nacos.console.security.nacos.NacosAuthManager.resolveTokenFromUser(NacosAuthManager.java:132)


这套nacos是一套测试环境，nacos账号改了密码，应用还在用错误的密码会触发这个case？

**Comment by jefferson-chern** [comment]
> 

如果开启了鉴权，服务端改了密码，但是客户端还在用错误密码请求，那肯定会出问题，应该就是这个原因，客户端改成正确的就好了，我们遇到过一模一样的问题。因为客户端有3次重试，只要是错误的用户名密码，beat、list和login请求都会重试3遍，加上jwt的校验token比较消耗cpu。nacos.log应该还有大量broken pipe的错误。

**Comment by jefferson-chern** [comment]
你们的实例数有多少？naming-performance.log日志看看

**Comment by jefferson-chern** [comment]
对了，你们是几节点集群？每台机器配置是多少核，内存是多大？实例数有多少？naming-performance.log日志看看

**Comment by zrlw** [comment]
nacos创建的GlobalExecutor线程池除了两个newFixedExecutorService之外都是无界（上限是Integer.MAX_VALUE)线程池，等待执行的线程持续增长，内存耗尽，然后正在执行的线程因为内存不足也处于等待，FullGC又释放不了这些Blocked状态的线程已经占用的资源，现象就是除了少数几个IN_NATIVE线程外都是BLOCKED。
nacos线程池大小设置比较随意，自己要根据jvm配置的内存大小做一下限制，直接用原版会遇到很多问题。

**Comment by wyt** [comment]
> 

naming-performance.log

2022-04-18 16:17:57,465 INFO PERFORMANCE:|141|147|-1|-1

2022-04-18 16:22:57,477 INFO PERFORMANCE:|141|148|-1|-1

2022-04-18 16:27:57,489 INFO PERFORMANCE:|142|150|-1|-1

2022-04-18 16:32:57,509 INFO PERFORMANCE:|143|148|10|6

2022-04-18 16:37:57,523 INFO PERFORMANCE:|142|148|-1|-1

2022-04-18 16:42:57,538 INFO PERFORMANCE:|144|149|-1|-1

2022-04-18 16:47:57,557 INFO PERFORMANCE:|143|148|-1|-1

2022-04-18 16:52:57,577 INFO PERFORMANCE:|143|149|-1|-1

2022-04-18 16:57:57,597 INFO PERFORMANCE:|143|146|-1|-1

2022-04-18 17:02:57,626 INFO PERFORMANCE:|141|146|6|6

2022-04-18 17:07:57,637 INFO PERFORMANCE:|141|146|-1|-1

2022-04-18 17:12:57,648 INFO PERFORMANCE:|141|145|-1|-1

2022-04-18 17:17:57,661 INFO PERFORMANCE:|141|145|-1|-1

2022-04-18 17:22:57,667 INFO PERFORMANCE:|142|147|-1|-1

2022-04-18 17:27:57,672 INFO PERFORMANCE:|141|146|-1|-1

2022-04-18 17:32:57,693 INFO PERFORMANCE:|143|149|-1|-1

2022-04-18 17:37:57,709 INFO PERFORMANCE:|144|150|-1|-1

**Comment by KomachiSion** [comment]
可以开prometheus监控，看一下login接口是不是有大量调用。
或者抓包看一下也行。

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce this problem.
