### ISSUE TITLE
Nacos Springboot junit test configuration load failed

### ISSUE THREAD

**Issue by pengsuwei** [alibaba/nacos#8246]
**Describe the bug**
Hi guys,
After I integrate nacos in springboot 2.6.6, the configuration file cannot be loaded when running junit tests.

**Expected behavior**
Configuration loaded successfully.

**Acutally behavior**
The configuration file cannot be loaded when running junit tests.

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]
 - Version [e.g. nacos-server 1.4.1, nacos-client 1.4.1]
 - SDK [spring-cloud-alibaba-nacos]

**Additional context**
```
@RunWith(SpringRunner.class)
@SpringBootTest
@TestPropertySource(locations = {"classpath:application.yml", "classpath:bootstrap-dev.yml"})
public class AdCompanyGatewayTest {
    @Autowired
    private AdCompanyGateway adCompanyGateway;

    @Test
    public void testQuery() {
        String companyId = "test_company_001";
        AdCompany adCompany = adCompanyGateway.queryById(companyId);
        Assert.assertNotNull(adCompany);
        Assert.assertEquals(companyId, adCompany.getCompanyId());
    }
}
```

```
2022-04-24 16:43:12:854|DESKTOP-5V7AMPK|main|ERROR|c.a.n.c.c.h.ServerHttpAgent:109|[NACOS ConnectException httpGet] currentServerAddr:http://localhost:8848, err : Connection refused: no further information
2022-04-24 16:43:12:862|DESKTOP-5V7AMPK|main|ERROR|c.a.n.c.c.i.ClientWorker:279|[fixed-localhost_8848] [sub-server] get server config exception, dataId=null.properties, group=DEFAULT_GROUP, tenant= java.net.ConnectException: [NACOS HTTP-GET] The maximum number of tolerable server reconnection errors has been reached
	at com.alibaba.nacos.client.config.http.ServerHttpAgent.httpGet(ServerHttpAgent.java:125)
	at com.alibaba.nacos.client.config.http.MetricsHttpAgent.httpGet(MetricsHttpAgent.java:51)
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:274)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:155)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:98)
```

What should I do?

**Comment by onewe** [comment]
If you just want to write a unit test, use mock best,don't depend on another services.

**Comment by KomachiSion** [comment]
`ttp://localhost:8848, err : Connection refused: no further information` the hint is very obvious. your unit test need connect a real env Does not meet the reproducibility principle of unit test.

If you want do like this, make sure start an nacos with `localhost` in your test env.
