### ISSUE TITLE
com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll_x86_64

### ISSUE THREAD

**Issue by sinolan** [alibaba/nacos#8247]
版本：2.0.3
启动报错
2022-04-24 18:26:23.013 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0:395 -- -Dio.netty.noUnsafe: false
2022-04-24 18:26:23.013 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0:851 -- Java version: 8
2022-04-24 18:26:23.014 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0:120 -- sun.misc.Unsafe.theUnsafe: available
2022-04-24 18:26:23.015 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0:144 -- sun.misc.Unsafe.copyMemory: available
2022-04-24 18:26:23.015 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0:182 -- java.nio.Buffer.address: available
2022-04-24 18:26:23.016 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0:243 -- direct buffer constructor: available
2022-04-24 18:26:23.017 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0:313 -- java.nio.Bits.unaligned: available, true
2022-04-24 18:26:23.017 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0:378 -- jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable prior to Java9
2022-04-24 18:26:23.017 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0:385 -- java.nio.DirectByteBuffer.<init>(long, int): available
2022-04-24 18:26:23.017 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent:970 -- sun.misc.Unsafe: available
2022-04-24 18:26:23.024 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent:1089 -- -Dio.netty.tmpdir: /tmp (java.io.tmpdir)
2022-04-24 18:26:23.024 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent:1168 -- -Dio.netty.bitMode: 64 (sun.arch.data.model)
2022-04-24 18:26:23.024 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent:159 -- -Dio.netty.maxDirectMemory: 484966400 bytes
2022-04-24 18:26:23.024 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent:166 -- -Dio.netty.uninitializedArrayAllocationThreshold: -1
2022-04-24 18:26:23.025 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.CleanerJava6:92 -- java.nio.ByteBuffer.cleaner(): available
2022-04-24 18:26:23.025 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent:186 -- -Dio.netty.noPreferDirect: false
2022-04-24 18:26:23.054 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader:73 -- -Dio.netty.native.workdir: /tmp (io.netty.tmpdir)
2022-04-24 18:26:23.054 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader:78 -- -Dio.netty.native.deleteLibAfterLoading: true
2022-04-24 18:26:23.054 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader:82 -- -Dio.netty.native.tryPatchShadedId: true
2022-04-24 18:26:23.062 [35m[main][0;39m [39mDEBUG[0;39m com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader:344 -- Unable to load the library 'com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll_x86_64', trying other loading mechanism.
java.lang.UnsatisfiedLinkError: no com_alibaba_nacos_shaded_io_grpc_netty_shaded_netty_transport_native_epoll_x86_64 in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1860)
	at java.lang.Runtime.loadLibrary0(Runtime.java:871)
	at java.lang.System.loadLibrary(System.java:1122)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:369)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:361)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:339)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:136)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:186)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.epoll.Native.<clinit>(Native.java:57)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:39)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.Utils.isEpollAvailable(Utils.java:220)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:92)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:72)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewChannelStub(GrpcClient.java:97)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:265)
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:394)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:941)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1104)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:996)
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:407)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:166)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:94)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:85)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:73)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadApplicationConfiguration(NacosPropertySourceLocator.java:141)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:103)
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:52)
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:98)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:623)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:367)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1247)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1236)
	at com.zhixuan.fota.gateway.GatewayApplication.main(GatewayApplication.java:14)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

**Comment by onewe** [comment]
windows 平台？

**Comment by sinolan** [comment]
就是不知道原因，才来提问的，望各位大神解答，是pc机安装centos6.9，然后虚拟出来的系统

**Comment by onewe** [comment]
这应该是不影响的. 我看了一下 netty 的一个 jni 的加载流程, netty 先去尝试加载 `java.library.path` 路径下的 so 库, 加载失败时才会去加载 jar 中的 so 库.

**Comment by onewe** [comment]
如果你有强迫症 可以把 jar 中的 本地库文件复制到 `java.library.path` 下就不会出现此类错误了,再或者你把日志级别调高点也行.

**Comment by sinolan** [comment]
是开发环境，先调高日志基本吧，谢谢
