### ISSUE TITLE
start nacos 2.04 with standalone failed

### ISSUE THREAD

**Issue by hahazcl** [alibaba/nacos#8253]
2022-04-25 14:40:06,931 INFO Starting Nacos v2.0.4 on VM-116-8-centos with PID 10840 (/home/exhibition/packages/nacos/target/nacos-server.jar started by exhibition in /home/exhibition/packages/nacos/bin)

...

2022-04-25 14:40:11,897 ERROR Startup errors : 

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'grpcSdkServer': Invocation of init method failed; nested exception is java.lang.IncompatibleClassChangeError: Class com.alibaba.nacos.api.grpc.auto.Payload does not implement the requested interface com.google.protobuf.MessageLite
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:413)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1761)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:592)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.lang.IncompatibleClassChangeError: Class com.alibaba.nacos.api.grpc.auto.Payload does not implement the requested interface com.google.protobuf.MessageLite
	at io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller.<init>(ProtoLiteUtils.java:128)
	at io.grpc.protobuf.lite.ProtoLiteUtils.marshaller(ProtoLiteUtils.java:84)
	at io.grpc.protobuf.ProtoUtils.marshaller(ProtoUtils.java:57)
	at com.alibaba.nacos.core.remote.grpc.BaseGrpcServer.addServices(BaseGrpcServer.java:172)
	at com.alibaba.nacos.core.remote.grpc.BaseGrpcServer.startServer(BaseGrpcServer.java:110)
	at com.alibaba.nacos.core.remote.BaseRpcServer.start(BaseRpcServer.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 26 common frames omitted
2022-04-25 14:40:13,402 WARN [WatchFileCenter] start close

2022-04-25 14:40:13,403 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /home/exhibition/packages/nacos/conf

2022-04-25 14:40:13,403 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /home/exhibition/packages/nacos/data/loader

2022-04-25 14:40:13,403 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /home/exhibition/packages/nacos/data/tps

2022-04-25 14:40:13,403 WARN [WatchFileCenter] already closed

2022-04-25 14:40:13,403 WARN [NotifyCenter] Start destroying Publisher

2022-04-25 14:40:13,403 WARN [NotifyCenter] Destruction of the end

2022-04-25 14:40:13,403 ERROR Nacos failed to start, please see /home/exhibition/packages/nacos/logs/nacos.log for more details.

2022-04-25 14:40:13,413 INFO 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.

2022-04-25 14:40:13,413 ERROR Application run failed

**Comment by hahazcl** [comment]
nacos 2.04 
jdk 1.8.0_301
mysql配置完毕

**Comment by KomachiSion** [comment]
I can't reproduce your problem, maybe your lib or jar is conflict or not right.
