### ISSUE TITLE
I got nullpointexception on RaftCore.onDelete method when I restart cluster

### ISSUE THREAD

**Issue by alex8224** [alibaba/nacos#8314]
**Describe the bug**
I got nullpointexception on RaftCore.onDelete method when I restart cluster. below is log lines
```
java.lang.NullPointerException: null
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftCore.onDelete(RaftCore.java:418)
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftConsistencyServiceImpl.remove(RaftConsistencyServiceImpl.java:101)
	at com.alibaba.nacos.naming.consistency.persistent.PersistentConsistencyServiceDelegateImpl.remove(PersistentConsistencyServiceDelegateImpl.java:69)
	at com.alibaba.nacos.naming.consistency.DelegateConsistencyServiceImpl.remove(DelegateConsistencyServiceImpl.java:55)
	at com.alibaba.nacos.naming.core.ServiceManager.cleanupService(ServiceManager.java:1029)
	at com.alibaba.nacos.naming.core.ServiceManager.destroyAllService(ServiceManager.java:1018)
	at com.alibaba.nacos.naming.core.ServiceManager.shutdown(ServiceManager.java:1003)
	at com.alibaba.nacos.naming.core.v2.upgrade.UpgradeJudgement.stopAll(UpgradeJudgement.java:259)
	at com.alibaba.nacos.naming.core.v2.upgrade.doublewrite.delay.DoubleWriteEventListener$DoubleWriteEnabledChecker.run(DoubleWriteEventListener.java:150)
2022-04-13 16:45:41,667 WARN start to close old raft protocol!!!

```

**Expected behavior**
Service normal
**Acutally behavior**

Service instance can't register 

**How to Reproduce**
only error log , 

nacos version: 2.0.3
client version: 1.4.1
[naming-raft.log.2022-04-13.log](https://github.com/alibaba/nacos/files/8644644/naming-raft.log.2022-04-13.log)
[protocol-raft.log.2022-04-13.0.log](https://github.com/alibaba/nacos/files/8644649/protocol-raft.log.2022-04-13.0.log)
[naming-server.log.2022-04-13.0.log](https://github.com/alibaba/nacos/files/8644655/naming-server.log.2022-04-13.0.log)
[protocol-distro.log.2022-04-13.0.log](https://github.com/alibaba/nacos/files/8644656/protocol-distro.log.2022-04-13.0.log)
[naming-distro.log.2022-04-13.0.log](https://github.com/alibaba/nacos/files/8644657/naming-distro.log.2022-04-13.0.log)

**Comment by KomachiSion** [comment]
Ignore it , the old raft has closed and shutdown when cluster running in 2.X mode.

The old raft only used in upgrading from 1.2 version. And will be removed after version 2.2
