### ISSUE TITLE
ERROR c.a.n.client.naming - [callServer,617] - [NA] failed to request

### ISSUE THREAD

**Issue by Ryder-yao** [alibaba/nacos#8335]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
14:48:16.223 [com.alibaba.nacos.naming.beat.sender] ERROR c.a.n.client.naming - [callServer,617] - [NA] failed to request
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(SocketInputStream.java:210)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at java.io.BufferedInputStream.fill(BufferedInputStream.java:246)
	at java.io.BufferedInputStream.read1(BufferedInputStream.java:286)
	at java.io.BufferedInputStream.read(BufferedInputStream.java:345)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:735)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:706)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1593)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getStatusCode(JdkHttpClientResponse.java:75)
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:43)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:483)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:427)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:603)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:433)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
14:48:16.224 [com.alibaba.nacos.naming.beat.sender] ERROR c.a.n.client.naming - [reqApi,552] - request: /nacos/v1/ns/instance/beat failed, servers: [17:8800], code: 500, msg: Connection reset
14:48:16.224 [com.alibaba.nacos.naming.beat.sender] ERROR c.a.n.client.naming - [run,198] - [CLIENT-BEAT] failed to send beat: {"port":9201,"ip":"172.1","weight":1.0,"serviceName":"DEFAULT_GROUP@@isystem","cluster":"DEFAULT","metadata":{"preserved.register.source":"SPRING_CLOUD"},"scheduled":false,"period":5000,"stopped":false}, code: 500, msg: failed to req API:/nacos/v1/ns/instance/beat after all servers([170:8800]) tried: java.net.SocketException: Connection reset
14:48:21.857 [com.alibaba.nacos.naming.beat.sender] ERROR c.a.n.client.naming - [callServer,617] - [NA] failed to request
java.net.SocketException: Connection reset

### Describe what you expected to happen
i`can start this nacos application; because it`s request is failed with 500. how can i slove it???

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by KomachiSion** [comment]
java.net.SocketException: Connection reset

your network has problem, please check your network.

**Comment by Ryder-yao** [comment]
thinks. i get it. i had find . my company network has limitations.




努力努力再努力h
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/nacos"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月11日(星期三) 上午10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/nacos] ERROR c.a.n.client.naming - [callServer,617] - [NA] failed to request (Issue #8335)





 
java.net.SocketException: Connection reset
 
your network has problem, please check your network.
