### ISSUE TITLE
need support for undertow

### ISSUE THREAD

**Issue by jsczrangel** [alibaba/nacos#8441]
After the Springboot project replaced the Tomcat container with undertow, it failed to unregister with NACOS when stopping the service, and it shows the null point expection. As a result, when the container was destroyed during containerization deployment and rolling update, it needed to rely on nacos timeout self-check to remove expired instances

**Comment by KomachiSion** [comment]
I can't get the problem from your description. If you change to undertow and throw NPE, you should check your changes. Because the original NACOS is work well. 

Or you can provider more detail information. For current information we only think your changes cause this problem.

**Comment by jsczrangel** [comment]
```
Disconnected from the target VM, address: '127.0.0.1:50351', transport: 'socket'
2022-05-23 15:55:37.461  WARN 6904 --- [      Thread-10] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Start destroying common HttpClient
2022-05-23 15:55:37.461  INFO 6904 --- [      Thread-73] net.polyv.common.v1.base.HttpClientUtil  : -----destroy HTTP POOL httpClient------
2022-05-23 15:55:37.462  WARN 6904 --- [      Thread-52] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Start destroying Publisher
2022-05-23 15:55:37.463  WARN 6904 --- [      Thread-52] c.a.nacos.common.notify.NotifyCenter     : [NotifyCenter] Destruction of the end
2022-05-23 15:55:37.479  WARN 6904 --- [      Thread-10] c.a.n.common.http.HttpClientBeanHolder   : [HttpClientBeanHolder] Destruction of the end
2022-05-23 15:55:37.533  INFO 6904 --- [extShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Waiting for workers to finish.
2022-05-23 15:55:38.106  INFO 6904 --- [extShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Successfully waited for workers to finish.
2022-05-23 15:55:38.110  INFO 6904 --- [extShutdownHook] io.undertow                              : stopping server: Undertow - 2.2.3.Final
2022-05-23 15:55:38.118  INFO 6904 --- [extShutdownHook] io.undertow.servlet                      : Destroying Spring FrameworkServlet 'dispatcherServlet'
2022-05-23 15:55:38.128  INFO 6904 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2022-05-23 15:55:38.136 ERROR 6904 --- [extShutdownHook] c.a.cloud.nacos.discovery.NacosWatch     : namingService unsubscribe failed, properties:NacosDiscoveryProperties{serverAddr='10.24.1.30:8848', endpoint='', namespace='2d750ac7-c405-4963-9246-5e9608f5295c', watchDelay=10000, logName='', service='resource-service', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.1.21', networkInterface='', port=9093, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null}

java.lang.NullPointerException: null
	at io.undertow.servlet.spec.ServletContextImpl.getInitParameterNames(ServletContextImpl.java:430)
	at org.springframework.web.context.support.ServletContextPropertySource.getPropertyNames(ServletContextPropertySource.java:41)
	at com.alibaba.spring.util.PropertySourcesUtils.getPropertyNames(PropertySourcesUtils.java:130)
	at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:103)
	at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:57)
	at com.alibaba.cloud.nacos.NacosDiscoveryProperties.enrichNacosDiscoveryProperties(NacosDiscoveryProperties.java:616)
	at com.alibaba.cloud.nacos.NacosDiscoveryProperties.getNacosProperties(NacosDiscoveryProperties.java:610)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:165)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:97)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:234)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:54)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:373)
	at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:206)
	at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:129)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1072)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:171)
	at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:996)

2022-05-23 15:55:38.173  INFO 6904 --- [extShutdownHook] c.a.c.n.registry.NacosServiceRegistry    : De-registering from Nacos Server now...
2022-05-23 15:55:38.174  WARN 6904 --- [extShutdownHook] .s.c.a.CommonAnnotationBeanPostProcessor : Destroy method on bean with name 'nacosAutoServiceRegistration' threw an exception: java.lang.NullPointerException
2022-05-23 15:55:38.175  INFO 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : com.alibaba.nacos.client.naming.beat.BeatReactor do shutdown begin
2022-05-23 15:55:41.203  INFO 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : com.alibaba.nacos.client.naming.beat.BeatReactor do shutdown stop
2022-05-23 15:55:41.203  INFO 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : com.alibaba.nacos.client.naming.core.HostReactor do shutdown begin
2022-05-23 15:55:44.222  INFO 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : com.alibaba.nacos.client.naming.core.PushReceiver do shutdown begin
2022-05-23 15:55:45.838  INFO 6904 --- [g.push.receiver] com.alibaba.nacos.client.naming          : received push data: {"type":"dom","data":"{\"name\":\"DEFAULT_GROUP@@resource-service\",\"clusters\":\"\",\"cacheMillis\":10000,\"hosts\":[{\"instanceId\":\"192.168.1.23#9093#DEFAULT#DEFAULT_GROUP@@resource-service\",\"ip\":\"192.168.1.23\",\"port\":9093,\"weight\":0.0,\"healthy\":true,\"enabled\":true,\"ephemeral\":true,\"clusterName\":\"DEFAULT\",\"serviceName\":\"DEFAULT_GROUP@@resource-service\",\"metadata\":{\"preserved.register.source\":\"SPRING_CLOUD\"},\"instanceHeartBeatInterval\":5000,\"instanceHeartBeatTimeOut\":15000,\"ipDeleteTimeout\":30000}],\"lastRefTime\":1653292545666,\"checksum\":\"\",\"allIPs\":false,\"reachProtectionThreshold\":false,\"valid\":true}","lastRefTime":2533332771436717} from /10.24.1.30
2022-05-23 15:55:45.838  INFO 6904 --- [g.push.receiver] com.alibaba.nacos.client.naming          : received push data: {"type":"dom","data":"{\"name\":\"DEFAULT_GROUP@@resource-service\",\"clusters\":\"DEFAULT\",\"cacheMillis\":10000,\"hosts\":[{\"instanceId\":\"192.168.1.23#9093#DEFAULT#DEFAULT_GROUP@@resource-service\",\"ip\":\"192.168.1.23\",\"port\":9093,\"weight\":0.0,\"healthy\":true,\"enabled\":true,\"ephemeral\":true,\"clusterName\":\"DEFAULT\",\"serviceName\":\"DEFAULT_GROUP@@resource-service\",\"metadata\":{\"preserved.register.source\":\"SPRING_CLOUD\"},\"instanceHeartBeatInterval\":5000,\"instanceHeartBeatTimeOut\":15000,\"ipDeleteTimeout\":30000}],\"lastRefTime\":1653292545666,\"checksum\":\"\",\"allIPs\":false,\"reachProtectionThreshold\":false,\"valid\":true}","lastRefTime":2533332771772343} from /10.24.1.30
2022-05-23 15:55:45.839  INFO 6904 --- [g.push.receiver] com.alibaba.nacos.client.naming          : new ips(1) service: DEFAULT_GROUP@@resource-service@@DEFAULT -> [{"instanceId":"192.168.1.23#9093#DEFAULT#DEFAULT_GROUP@@resource-service","ip":"192.168.1.23","port":9093,"weight":0.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@resource-service","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2022-05-23 15:55:45.839  INFO 6904 --- [g.push.receiver] com.alibaba.nacos.client.naming          : new ips(1) service: DEFAULT_GROUP@@resource-service -> [{"instanceId":"192.168.1.23#9093#DEFAULT#DEFAULT_GROUP@@resource-service","ip":"192.168.1.23","port":9093,"weight":0.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@resource-service","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2022-05-23 15:55:45.840  INFO 6904 --- [g.push.receiver] com.alibaba.nacos.client.naming          : current ips:(1) service: DEFAULT_GROUP@@resource-service@@DEFAULT -> [{"instanceId":"192.168.1.23#9093#DEFAULT#DEFAULT_GROUP@@resource-service","ip":"192.168.1.23","port":9093,"weight":0.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@resource-service","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2022-05-23 15:55:45.840  INFO 6904 --- [g.push.receiver] com.alibaba.nacos.client.naming          : current ips:(1) service: DEFAULT_GROUP@@resource-service -> [{"instanceId":"192.168.1.23#9093#DEFAULT#DEFAULT_GROUP@@resource-service","ip":"192.168.1.23","port":9093,"weight":0.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"DEFAULT_GROUP@@resource-service","metadata":{"preserved.register.source":"SPRING_CLOUD"},"instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}]
2022-05-23 15:55:47.248  INFO 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : com.alibaba.nacos.client.naming.core.PushReceiver do shutdown stop
2022-05-23 15:55:47.248  INFO 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown begin
2022-05-23 15:55:47.248  INFO 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : com.alibaba.nacos.client.naming.backups.FailoverReactor do shutdown stop
2022-05-23 15:55:47.249  INFO 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : com.alibaba.nacos.client.naming.core.HostReactor do shutdown stop
2022-05-23 15:55:47.249  INFO 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : com.alibaba.nacos.client.naming.net.NamingProxy do shutdown begin
2022-05-23 15:55:47.249  WARN 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : [NamingHttpClientManager] Start destroying NacosRestTemplate
2022-05-23 15:55:47.250  WARN 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : [NamingHttpClientManager] Destruction of the end
2022-05-23 15:55:47.250  INFO 6904 --- [extShutdownHook] c.a.n.client.identify.CredentialWatcher  : [null] CredentialWatcher is stopped
2022-05-23 15:55:47.250  INFO 6904 --- [extShutdownHook] c.a.n.client.identify.CredentialService  : [null] CredentialService is freed
2022-05-23 15:55:47.250  INFO 6904 --- [extShutdownHook] com.alibaba.nacos.client.naming          : com.alibaba.nacos.client.naming.net.NamingProxy do shutdown stop
2022-05-23 15:55:47.253  INFO 6904 --- [extShutdownHook] o.s.s.c.ThreadPoolTaskScheduler          : Shutting down ExecutorService 'taskScheduler'
2022-05-23 15:55:47.253  INFO 6904 --- [extShutdownHook] c.y.common.feign.config.NacosConfig      : deregister from nacos, serviceName:resource-service, groupName:DEFAULT_GROUP, clusterName:DEFAULT, ip:192.168.1.21, port:9093
2022-05-23 15:55:47.257  INFO 6904 --- [extShutdownHook] o.s.s.concurrent.ThreadPoolTaskExecutor  : Shutting down ExecutorService 'businessPool'
2022-05-23 15:55:47.289  INFO 6904 --- [extShutdownHook] o.s.a.r.l.SimpleMessageListenerContainer : Shutdown ignored - container is not active already
2022-05-23 15:55:47.296  INFO 6904 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2022-05-23 15:55:47.298  INFO 6904 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2022-05-23 15:55:47.298  INFO 6904 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Shutdown initiated...
2022-05-23 15:55:47.300  INFO 6904 --- [extShutdownHook] com.zaxxer.hikari.HikariDataSource       : HikariPool-2 - Shutdown completed.
```
我只要把pom里面替换tomcat为undertow代码恢复，这个错误就没有了
i just replace back to tomcat in pom  ,this will be fix

**Comment by onewe** [comment]
@jsczrangel  undertow 版本是多少?

**Comment by onewe** [comment]
我猜 你的 undertow 版本升级一下就好了,大概率已经修复了

**Comment by jsczrangel** [comment]
> @jsczrangel undertow 版本是多少?
spring-boot-starter-undertow 2.4.2 跟整体框架版本一致
里面undertow-core 2.2.3.Final

**Comment by onewe** [comment]
@jsczrangel 可以看看 undertow 的相关 PR https://github.com/undertow-io/undertow/pull/1030 , 升级一下版本就好

**Comment by jsczrangel** [comment]
3Q，解决
