### ISSUE TITLE
hostname -i   会导致服务启动失败

### ISSUE THREAD

**Issue by sunzhonghui** [alibaba/nacos#8455]
# 启动 jar 连接不上Nacos服务

### 前置条件

> - Nacos 版本 2.0.4
> - Nacos 服务没问题，后台页面可以打开
> - Nacos所在服务器8848/9848/9849/端口都开放，或者防火墙已经关闭
> - 启动相同的jar有的服务器有问题，有的没问题

### 启动jar 报错

```
20:39:30.692 [main] INFO  c.a.n.c.r.client - [printIfInfoEnabled,60] - [2d2b5901-f6f8-414e-850c-1a92807e9f25_config-0] Try to connect to server on start up, server: {serverIp = '192.168.x.x', server main port = 8848}
20:39:33.695 [main] ERROR c.a.n.c.r.c.g.GrpcClient - [printIfErrorEnabled,99] - Server check fail, please check server 192.168.166.51 ,port 9848 is available , error ={}
java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 65041 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@77114efe[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@77681ce4, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@5d96bdf8, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@6f76c2cc}}}}}]]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:148)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:264)
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:390)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:885)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1044)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:940)
	at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:397)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:166)
	at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:94)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.loadNacosData(NacosPropertySourceBuilder.java:85)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceBuilder.build(NacosPropertySourceBuilder.java:73)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosPropertySource(NacosPropertySourceLocator.java:199)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosDataIfPresent(NacosPropertySourceLocator.java:186)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadNacosConfiguration(NacosPropertySourceLocator.java:158)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.loadSharedConfiguration(NacosPropertySourceLocator.java:116)
	at com.alibaba.cloud.nacos.client.NacosPropertySourceLocator.locate(NacosPropertySourceLocator.java:101)
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:51)
	at org.springframework.cloud.bootstrap.config.PropertySourceLocator.locateCollection(PropertySourceLocator.java:47)
	at org.springframework.cloud.bootstrap.config.PropertySourceBootstrapConfiguration.initialize(PropertySourceBootstrapConfiguration.java:95)
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:613)
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:381)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1312)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1301)
	at com.hz.flowable.FlowableApplication.main(FlowableApplication.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

### 解决办法

查看连接不了机器的hostname跟对应的ip地址

```
[root@host-192-168-166-51 ~]# hostname
host-192-168-166-51
[root@host-192-168-166-51 ~]# hostname -i # 会反应很慢
192.168.166.51
```

修改 /etc/hosts

新增  **127.0.0.1   localhost host-192-168-166-52**

```
127.0.0.1   localhost host-192-168-166-52
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4 
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
```

现在执行

```
[root@host-192-168-166-51 ~]# hostname -i # 立即返回
127.0.0.1
```

### 具体原因
未知

**Comment by onewe** [comment]
使用的集群模式? 还是单机模式?

**Comment by sunzhonghui** [comment]
> 使用的集群模式? 还是单机模式?

单机

**Comment by onewe** [comment]
很抱歉我这边没有复现你说的问题,但不妨大胆试一试,启动时加上`-Dnacos.server.ip=ip地址`参数,看是否解决问题 @sunzhonghui

**Comment by sunzhonghui** [comment]
> 
通过配置 host 是可以解决这个问题的，但是不知道这个是不是bug，所以提交下。

**Comment by sunzhonghui** [comment]
> 很抱歉我这边没有复现你说的问题,但不妨大胆试一试,启动时加上`-Dnacos.server.ip=ip地址`参数,看是否解决问题 @sunzhonghui


通过配置 host 是可以解决这个问题的，但是不知道这个是不是bug，所以提交下。

**Comment by onewe** [comment]
我猜测是解析hostname超时了, java 好像没有超时时间

**Comment by sunzhonghui** [comment]
> 我猜测是解析hostname超时了, java 好像没有超时时间

好的
