### ISSUE TITLE
nacos-client-1.4.1问题修复

### ISSUE THREAD

**Issue by chensir9811007** [alibaba/nacos#8487]
各位阿里的大佬们，我在使用1.4.1版本的时候
spring.cloud.nacos.config.enabled=false
spring.cloud.nacos.discovery.enabled=false
配置不使用配置中心，注册中心，只是一个普通服务(不想把依赖删除)，然后就不停的有报错。
查看NamingProxy源码看到问题所在，如果我没配置server-addr，那么就会出现定时任务一直在刷
java.lang.IllegalArgumentException: protocol = http host = null
	at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:177)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1150)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at com.alibaba.nacos.common.http.client.request.JdkHttpClientRequest.execute(JdkHttpClientRequest.java:112)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.get(NacosRestTemplate.java:72)
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServerListFromEndpoint(NamingProxy.java:168)
	at com.alibaba.nacos.client.naming.net.NamingProxy.refreshSrvIfNeed(NamingProxy.java:203)
	at com.alibaba.nacos.client.naming.net.NamingProxy.access$000(NamingProxy.java:82)
	at com.alibaba.nacos.client.naming.net.NamingProxy$2.run(NamingProxy.java:148)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

按理说应该maxTry 3次就可以了，但是会一直刷
能不能在初始化做个判断，
public NamingProxy(String namespaceId, String endpoint, String serverList, Properties properties) {
        
        this.securityProxy = new SecurityProxy(properties, nacosRestTemplate);
        this.properties = properties;
        this.setServerPort(DEFAULT_SERVER_PORT);
        this.namespaceId = namespaceId;
        this.endpoint = endpoint;
        this.maxRetry = ConvertUtils.toInt(properties.getProperty(PropertyKeyConst.NAMING_REQUEST_DOMAIN_RETRY_COUNT,
                String.valueOf(UtilAndComs.REQUEST_DOMAIN_RETRY_COUNT)));
        
        if (StringUtils.isNotEmpty(serverList)) {
            this.serverList = Arrays.asList(serverList.split(","));
            if (this.serverList.size() == 1) {
                this.nacosDomain = serverList;
            }
        }
**这里加个 if(StringUtils.isblank(endpoint)) return**
        this.initRefreshTask();
    }
这样这个刷新任务也不执行

**Comment by sanxun0325** [comment]
@chensir9811007 可以提交个pr

**Comment by chensir9811007** [comment]
> @chensir9811007 可以提交个pr

啥意思

**Comment by chensir9811007** [comment]
> > > @chensir9811007 可以提交个pr
> > 
> > 
> > 啥意思
> 
> 就是你可以考虑下来修复它

修复很好操作的，就是需要源码，在那个分支搞呢

**Comment by li-xiao-shuang** [comment]
> > > > @chensir9811007 可以提交个pr
> > > 
> > > 
> > > 啥意思
> > 
> > 
> > 就是你可以考虑下来修复它
> 
> 修复很好操作的，就是需要源码，在那个分支搞呢

v1.x-develop

**Comment by chensir9811007** [comment]
> > > > > @chensir9811007 可以提交个pr
> > > > 
> > > > 
> > > > 啥意思
> > > 
> > > 
> > > 就是你可以考虑下来修复它
> > 
> > 
> > 修复很好操作的，就是需要源码，在那个分支搞呢
> 
> v1.x-develop

好的，我试着改下代码提交，估计2.x也是这个问题

**Comment by KomachiSion** [comment]
我感觉思路不对吧， 不是应该不依赖discovery吗？为什么会跑来改nacos-client代码？

**Comment by chensir9811007** [comment]
> 我感觉思路不对吧， 不是应该不依赖discovery吗？为什么会跑来改nacos-client代码？

依赖不发生变化，只是关闭注册中心，配置中心，应用还是可以启动的，可以采用Http形式继续访问的，而不用重新构建pom

**Comment by KomachiSion** [comment]
> > 我感觉思路不对吧， 不是应该不依赖discovery吗？为什么会跑来改nacos-client代码？
> 
> 依赖不发生变化，只是关闭注册中心，配置中心，应用还是可以启动的，可以采用Http形式继续访问的，而不用重新构建pom

那应该到spring cloud alibaba 里找找问题， 为什么关闭了还会启动nacos-client？
