### ISSUE TITLE
config导致注册中心无法感知订阅服务上下线

### ISSUE THREAD

**Issue by Master-Jack** [alibaba/nacos#8495]
版本 nacos Server:2.0.4  client:2.0.4

复现步骤：搞好配置中心和注册中心启动客户端A，A第一次订阅B服务后，B服务上下线A服务无法感知，只能通过UpdateTask更新服务。

去掉config的依赖或者不创建NacosConfigService回复正常，client日志如下
```
2022-06-01 15:47:27.938  INFO 35108 --- [ent-executor-12] com.alibaba.nacos.common.remote.client   : [9e83958a-825a-497a-b433-6aeb296008b4] Receive server push request, request = NotifySubscriberRequest, requestId = 2

2022-06-01 15:47:27.940  INFO 35108 --- [ent-executor-12] com.alibaba.nacos.common.remote.client   : [9e83958a-825a-497a-b433-6aeb296008b4] Ack server push request, request = NotifySubscriberRequest, requestId = 2
```

开启两台Nacos分别用作注册中心和配置中心也没用。

**可以通过A服务注入 DiscoveryClient来观察客户端的服务感知情况，在不引入配置中心，其他客户端的上下线A服务都可以第一时间感知到，引入后则无法感知。**

并且naming-push日志一直报超时，去掉config则正常，网络没有问题
```
2022-06-01 20:44:08,021 ERROR Reason detail: 
java.util.concurrent.TimeoutException: Timeout After 5000 milliseconds,requestId =116
  at com.alibaba.nacos.api.remote.DefaultRequestFuture$TimeoutHandler.run(DefaultRequestFuture.java:194)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.run(FutureTask.java:266)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)
2022-06-01 20:44:08,670 ERROR [PUSH-FAIL] 5008ms, Service{namespace='public', group='DEFAULT_GROUP', name='discover', ephemeral=true, revision=7}, reason=Timeout After 5000 milliseconds,requestId =117, target=192.168..xxx
```

**Comment by KomachiSion** [comment]
客户端升级到2.1.0试试， 可能是类冲突了。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
