### ISSUE TITLE
nacos启动报错 java.lang.IllegalStateException: Failed to load property source from location 和 Caused by: java.net.UnknownHostException:

### ISSUE THREAD

**Issue by tianj456** [alibaba/nacos#8538]
/opt/jdk1.8.0_333/bin/java -Djava.ext.dirs=/opt/jdk1.8.0_333/jre/lib/ext:/opt/jdk1.8.0_333/lib/ext  -server -Xms2g -Xmx2g -Xmn1g -XX:MetaspaceSize=128m -XX:MaxMetaspaceSize=320m -XX:-OmitStackTraceInFastThrow -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=//home/nacos/nacos-2.0/logs/java_heapdump.hprof -XX:-UseLargePages -Dnacos.member.list= -Xloggc://home/nacos/nacos-2.0/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=//home/nacos/nacos-2.0/plugins/health,//home/nacos/nacos-2.0/plugins/cmdb -Dnacos.home=//home/nacos/nacos-2.0 -jar //home/nacos/nacos-2.0/target/nacos-server.jar  --spring.config.additional-location=file://home/nacos/nacos-2.0/conf/ --logging.config=//home/nacos/nacos-2.0/conf/nacos-logback.xml --server.max-http-header-size=524288
11:26:22.796 [main] DEBUG org.springframework.boot.context.logging.ClasspathLoggingApplicationListener - Application failed to start with classpath: [jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/classes!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-web-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-json-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jackson-datatype-jdk8-2.9.10.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jackson-datatype-jsr310-2.9.10.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jackson-module-parameter-names-2.9.10.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/hibernate-validator-6.0.20.Final.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/validation-api-2.0.1.Final.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jboss-logging-3.3.3.Final.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/classmate-1.4.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-web-5.1.18.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-webmvc-5.1.18.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/nacos-api-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/reflections-0.9.11.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/javassist-3.21.0-GA.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/javax.annotation-api-1.3.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/nacos-core-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/nacos-common-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/nacos-consistency-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/hessian-4.0.63.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/nacos-auth-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/nacos-sys-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jjwt-api-0.11.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jjwt-impl-0.11.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jjwt-jackson-0.11.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-test-5.1.18.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-test-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jraft-core-1.3.5.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/asm-6.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/rocksdbjni-5.18.4.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jna-4.5.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jctools-core-2.1.1.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/disruptor-3.3.7.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/commons-lang-2.6.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/hessian-3.3.6.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/metrics-core-4.0.7.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/rpc-grpc-impl-1.3.5.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/guava-30.1-jre.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/failureaccess-1.0.1.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jsr305-3.0.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/checker-qual-3.5.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/j2objc-annotations-1.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-jdbc-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/HikariCP-3.4.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-jdbc-5.1.18.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-tx-5.1.18.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/commons-io-2.7.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/mysql-connector-java-8.0.21.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/derby-10.14.2.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/logback-classic-1.2.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/aspectjrt-1.9.6.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/cglib-nodep-2.1.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/httpasyncclient-4.1.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/httpcore-nio-4.4.13.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/commons-logging-1.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-tomcat-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/tomcat-embed-websocket-9.0.38.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jackson-core-2.12.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jackson-databind-2.12.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jackson-annotations-2.12.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/micrometer-registry-prometheus-1.1.18.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/micrometer-core-1.1.18.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/HdrHistogram-2.1.9.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/LatencyUtils-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/simpleclient_common-0.5.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/micrometer-registry-influx-1.1.18.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/micrometer-registry-elastic-1.1.18.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-aop-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/aspectjweaver-1.9.6.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-actuator-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-actuator-autoconfigure-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-actuator-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/snakeyaml-1.23.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/tomcat-embed-jasper-9.0.40.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/tomcat-embed-core-9.0.38.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/tomcat-annotations-api-9.0.38.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/tomcat-embed-el-9.0.38.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/ecj-3.18.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/netty-all-4.1.59.Final.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-core-5.1.18.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-jcl-5.1.18.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-context-5.1.18.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/commons-collections-3.2.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jackson-core-asl-1.9.13.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/slf4j-api-1.7.7.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/logback-core-1.2.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/mina-core-2.0.0-RC1.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/javatuples-1.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/httpcore-4.4.13.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/httpclient-4.5.12.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/commons-codec-1.11.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/nacos-cmdb-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/nacos-istio-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/nacos-client-2.0.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/simpleclient-0.5.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/grpc-netty-shaded-1.24.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/grpc-core-1.24.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/gson-2.8.6.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/annotations-4.1.1.4.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/perfmark-api-0.17.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/opencensus-api-0.21.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/opencensus-contrib-grpc-metrics-0.21.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/grpc-protobuf-1.24.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/grpc-api-1.24.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/grpc-context-1.24.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/error_prone_annotations-2.3.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/animal-sniffer-annotations-1.17.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/grpc-protobuf-lite-1.24.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/grpc-stub-1.24.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/proto-google-common-protos-1.17.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/protobuf-java-3.8.0.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/api-0.1.27.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/log4j-over-slf4j-1.7.30.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jcl-over-slf4j-1.7.30.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/jul-to-slf4j-1.7.30.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-security-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-autoconfigure-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-starter-logging-2.1.17.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/log4j-to-slf4j-2.11.2.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/log4j-api-2.13.3.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-aop-5.1.18.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-beans-5.1.18.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-security-config-5.1.12.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-security-core-5.1.12.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-security-web-5.1.12.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-expression-5.1.18.RELEASE.jar!/, jar:file:/home/nacos/nacos-2.0/target/nacos-server.jar!/BOOT-INF/lib/spring-boot-jarmode-layertools-2.5.3.jar!/]
11:26:22.803 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalStateException: Failed to load property source from location 'file://home/nacos/nacos-2.0/conf/application.properties'
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:526)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadForFileExtension(ConfigFileApplicationListener.java:475)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:445)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$null$6(ConfigFileApplicationListener.java:427)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.lambda$load$7(ConfigFileApplicationListener.java:427)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:424)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:323)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:204)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:188)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEnvironmentPreparedEvent(ConfigFileApplicationListener.java:178)
	at org.springframework.boot.context.config.ConfigFileApplicationListener.onApplicationEvent(ConfigFileApplicationListener.java:166)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:127)
	at org.springframework.boot.context.event.EventPublishingRunListener.environmentPrepared(EventPublishingRunListener.java:76)
	at org.springframework.boot.SpringApplicationRunListeners.environmentPrepared(SpringApplicationRunListeners.java:53)
	at org.springframework.boot.SpringApplication.prepareEnvironment(SpringApplication.java:342)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:305)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
Caused by: java.net.UnknownHostException: home
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:196)
	at java.net.Socket.connect(Socket.java:606)
	at sun.net.ftp.impl.FtpClient.doConnect(FtpClient.java:1063)
	at sun.net.ftp.impl.FtpClient.tryConnect(FtpClient.java:1025)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1120)
	at sun.net.ftp.impl.FtpClient.connect(FtpClient.java:1106)
	at sun.net.www.protocol.ftp.FtpURLConnection.connect(FtpURLConnection.java:311)
	at sun.net.www.protocol.ftp.FtpURLConnection.getInputStream(FtpURLConnection.java:417)
	at org.springframework.core.io.UrlResource.getInputStream(UrlResource.java:186)
	at org.springframework.boot.env.OriginTrackedPropertiesLoader$CharacterReader.<init>(OriginTrackedPropertiesLoader.java:157)
	at org.springframework.boot.env.OriginTrackedPropertiesLoader.load(OriginTrackedPropertiesLoader.java:74)
	at org.springframework.boot.env.OriginTrackedPropertiesLoader.load(OriginTrackedPropertiesLoader.java:63)
	at org.springframework.boot.env.PropertiesPropertySourceLoader.loadProperties(PropertiesPropertySourceLoader.java:60)
	at org.springframework.boot.env.PropertiesPropertySourceLoader.load(PropertiesPropertySourceLoader.java:47)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadDocuments(ConfigFileApplicationListener.java:544)
	at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:499)
	... 31 common frames omitted

**Comment by tianj456** [comment]
在win10上启动时正常的，linux上 ./startup.sh -m standalone 单级启动报错

**Comment by vividfish** [comment]
![image](https://user-images.githubusercontent.com/24951831/172548467-1f62f420-16ac-4ba3-a015-dc7d44526612.png)
检查下启动参数

**Comment by onewe** [comment]
@tianj456 路径多了个斜杆导致的,之前也有人反馈过 估计是 shell 的问题
