### ISSUE TITLE
undertow 与 nacos 一起用 服务停止的时候 异常报错

### ISSUE THREAD

**Issue by JavaLionLi** [alibaba/nacos#8550]
undertow 与 nacos 一起用 服务停止的时候 就会报这个错误
nacos版本 2.0.2 2.0.4 2.1.0 都试过了

![image](https://user-images.githubusercontent.com/31852897/172823274-d6c12a37-b6f7-46a0-941d-6368f60c7a8e.png)

`2022-06-09 18:08:57 [Thread-4] WARN  c.a.n.c.http.HttpClientBeanHolder
 - [HttpClientBeanHolder] Start destroying common HttpClient
2022-06-09 18:08:57 [Thread-7] WARN  c.a.nacos.common.notify.NotifyCenter
 - [NotifyCenter] Start destroying Publisher
2022-06-09 18:08:57 [Thread-4] WARN  c.a.n.c.http.HttpClientBeanHolder
 - [HttpClientBeanHolder] Destruction of the end
2022-06-09 18:08:57 [Thread-7] WARN  c.a.nacos.common.notify.NotifyCenter
 - [NotifyCenter] Destruction of the end
2022-06-09 18:08:57 [SpringContextShutdownHook] INFO  io.undertow
 - stopping server: Undertow - 2.2.17.Final
2022-06-09 18:08:57 [SpringContextShutdownHook] INFO  io.undertow.servlet
 - Destroying Spring FrameworkServlet 'dispatcherServlet'
2022-06-09 18:08:57 [SpringContextShutdownHook] ERROR c.a.cloud.nacos.discovery.NacosWatch
 - namingService unsubscribe failed, properties:NacosDiscoveryProperties{serverAddr='81.70.150.73:8848', username='', password='', endpoint='', namespace='dev', watchDelay=30000, logName='', service='ruoyi-a
uth', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='192.168.31.100', networkInterface=
'', port=9200, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, instanceEnabled=true, ephemeral=true, failureToleranceEnabled=false}, ipDeleteTim
eout=null, failFast=true}
java.lang.IllegalStateException: UT015023: This Context has been already destroyed
        at io.undertow.servlet.spec.ServletContextImpl.getDeploymentInfo(ServletContextImpl.java:211)
        at io.undertow.servlet.spec.ServletContextImpl.getInitParameterNames(ServletContextImpl.java:449)
        at org.springframework.web.context.support.ServletContextPropertySource.getPropertyNames(ServletContextPropertySource.java:41)
        at com.alibaba.spring.util.PropertySourcesUtils.getPropertyNames(PropertySourcesUtils.java:130)
        at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:103)
        at com.alibaba.spring.util.PropertySourcesUtils.getSubProperties(PropertySourcesUtils.java:57)
        at com.alibaba.cloud.nacos.NacosDiscoveryProperties.enrichNacosDiscoveryProperties(NacosDiscoveryProperties.java:657)
        at com.alibaba.cloud.nacos.NacosDiscoveryProperties.getNacosProperties(NacosDiscoveryProperties.java:651)
        at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:175)
        at com.alibaba.cloud.nacos.discovery.NacosWatch.stop(NacosWatch.java:107)
        at org.springframework.context.support.DefaultLifecycleProcessor.doStop(DefaultLifecycleProcessor.java:234)
        at org.springframework.context.support.DefaultLifecycleProcessor.access$300(DefaultLifecycleProcessor.java:54)
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.stop(DefaultLifecycleProcessor.java:373)
        at org.springframework.context.support.DefaultLifecycleProcessor.stopBeans(DefaultLifecycleProcessor.java:206)
        at org.springframework.context.support.DefaultLifecycleProcessor.onClose(DefaultLifecycleProcessor.java:129)
        at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1067)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.doClose(ServletWebServerApplicationContext.java:172)
        at org.springframework.context.support.AbstractApplicationContext$1.run(AbstractApplicationContext.java:991)
2022-06-09 18:08:57 [SpringContextShutdownHook] INFO  c.a.c.n.r.NacosServiceRegistry
 - De-registering from Nacos Server now...
2022-06-09 18:08:57 [SpringContextShutdownHook] WARN  o.s.c.a.CommonAnnotationBeanPostProcessor
 - Destroy method on bean with name 'nacosAutoServiceRegistration' threw an exception: java.lang.IllegalStateException: UT015023: This Context has been already destroyed
`

**Describe the bug**

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by onewe** [comment]
spring boot 版本号是多少？

**Comment by KomachiSion** [comment]
看报错就是你应用自己停止了，触发了shutdown， 和nacos没什么关系

**Comment by token01** [comment]
restart the service

**Comment by JavaLionLi** [comment]
boot 版本号 2.6.8

**Comment by JavaLionLi** [comment]
> 



> 看报错就是你应用自己停止了，触发了shutdown， 和nacos没什么关系

使用tomcat就不会报错

**Comment by JavaLionLi** [comment]
和 undertow 一起使用就会报错 而且是100%的

**Comment by onewe** [comment]
@JavaLionLi 我看了一下,这个问题会导致应用退出时不能正常下线,根本原因是关闭顺序问题,可以把问题转到 [spring-cloud-alibaba ](https://github.com/alibaba/spring-cloud-alibaba) 社区让他们看看怎么处理.
