### ISSUE TITLE
Nacos2.10 Client ErrMsg:Client not connected, current status:STARTING

### ISSUE THREAD

**Issue by Arvinzhu** [alibaba/nacos#8552]
**Describe the bug** 
当我使用nacos 2.1.0 java 客户端订阅服务出现了异常。开始我以为是服务器上面没有将nacos两个grpc端口放行导致的。但是由于我没有放行服务器端口的权限。因此我在本地启动了一个nacos服务，在确认配置信息全部无误后，仍然报同样的错误。
When I use nacos 2.1.0 java client to subscribe to the service an exception occurs. 
At first I thought it was because the two grpc ports of nacos were not released on the server. But since I don't have permission to release the server port. So I started a nacos service locally, and after confirming that all the configuration information is correct, the same error is still reported. 
**Expected behavior**
  能够成功订阅服务

**Actually behavior**
 ```
Caused by: ErrCode:500, ErrMsg:Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:288)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:229)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:214)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:147)
	at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:393)
	at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:377)
	at com.ctg.mes.config.console.service.nacos.impl.NacosServiceManagerImplTest.subscribeService(NacosServiceManagerImplTest.java:97)
	... 1 more
Caused by: ErrCode:-401, ErrMsg:Client not connected, current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:651)
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:631)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:278)
```

**How to Reproduce**
 如下是我的测试代码：
```
Properties properties = new Properties();
String serverAddr = "localhost:32088";
properties.put("serverAddr", serverAddr);
properties.setProperty("password", "xxxxxxx");
properties.setProperty("username", "nacos"); 
NamingService namingService = NamingFactory.createNamingService(properties); 
namingService.subscribe("default_service2","GROUP1", event -> {
    if (event instanceof NamingEvent) {
        System.out.println(((NamingEvent) event).getServiceName());
        System.out.println(((NamingEvent) event).getInstances());
    }
});
```

**Desktop (please complete the following information):**
 - OS:  Contos7.6
 - Version : Nacos  2.1.0   源码 develop  分支，checkout  version  8a9f6f8b
 - Module : naming 
 - SDK : nacos client ,   void subscribe(String serviceName, String groupName, EventListener listener) 

**Additional context**
我想问这是不是bug，该怎样修复呢，
I want to ask if this is a bug and how to fix it

**Comment by onewe** [comment]
nacos-server 启动参数有做调整吗？ 改了端口？

**Comment by KomachiSion** [comment]
your client can't connect to your server, please check your network is working well.

**Comment by onewe** [comment]
使用的集群模式？

**Comment by Arvinzhu** [comment]
单节点

**Comment by onewe** [comment]
我本地使用你相同的代码没有复现这个问题, 修改端口为`32088 `,GRPC端口要做相应的便宜哟

**Comment by KomachiSion** [comment]
修改了端口，客户端也要使用对应端口，如果加了vip或者slb这种中间转发的代理， 也需要在代理上配置对应的偏移。

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.
