### ISSUE TITLE
java.lang.RuntimeException: publish nacos metadata failed

### ISSUE THREAD

**Issue by hyw520110** [alibaba/nacos#8606]
如题报错，版本、依赖信息：
nacos-server 2.1.0
nacos-client版本:2.1.0
<spring.boot.version>2.6.6</spring.boot.version>
<spring.cloud.version>2021.0.1</spring.cloud.version>
<spring.cloud.alibaba.version>2021.0.1.0</spring.cloud.alibaba.version>
<dubbo.version>3.0.8</dubbo.version>

dubbo-registry-nacos排除间接依赖：log4j、dubbo-common、dubbo-remoting-api
spring-cloud-starter-alibaba-nacos-discovery排除间接依赖：HdrHistogram、nacos-client

具体错误：

https://github.com/apache/dubbo/issues/10187#issue-1278039652

**Comment by hyw520110** [comment]
换nacos 2.0.4(server和client版本对应)依旧有这个错误

**Comment by KomachiSion** [comment]
麻烦提供一下nacos-client的日志

${user.home}/logs/nacos/

**Comment by hyw520110** [comment]
config.log
2022-06-23 14:11:19.896 ERROR [com.alibaba.nacos.client.Worker:c.a.n.c.c.i.ClientWorker] Async listen config change error
com.alibaba.nacos.api.exception.NacosException: java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 96523 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@621dbbb8[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@d8aab1d, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@7d76cb49, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@1ae7c1dc}}}}}]]
        at com.alibaba.nacos.common.remote.client.grpc.GrpcConnection.request(GrpcConnection.java:78) ~[nacos-client-2.0.4.jar:na]
        at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:652) ~[nacos-client-2.0.4.jar:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1007) [nacos-client-2.0.4.jar:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:986) [nacos-client-2.0.4.jar:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.executeConfigListen(ClientWorker.java:777) [nacos-client-2.0.4.jar:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.lambda$startInternal$2(ClientWorker.java:695) [nacos-client-2.0.4.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_201]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_201]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
        at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
Caused by: java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 96523 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@621dbbb8[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@d8aab1d, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@7d76cb49, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@1ae7c1dc}}}}}]]
        at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508) ~[nacos-client-2.0.4.jar:na]
        at com.alibaba.nacos.common.remote.client.grpc.GrpcConnection.request(GrpcConnection.java:76) ~[nacos-client-2.0.4.jar:na]
        ... 12 common frames omitted


2022-06-24 13:52:33.136 WARN [DubboSaveMetadataReport-thread-1:c.a.n.c.c.i.ClientWorker] [config_rpc_client] [publish-single] error, dataId=com.XXXX:::provider:XXX, group=dev, tenant=, code=unkonw, msg=java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 4 milliseconds, 474969 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@5387cf31[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@4226a30e, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@4ff3a0d, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@7cbf7e14}}}}}]]

remote.log

2022-06-21 20:00:01.826 ERROR [DubboSaveMetadataReport-thread-1:c.a.n.c.r.client] Send request fail, request = ConfigPublishRequest{headers={}, requestId='null'}, retryTimes = 0, errorMessage = java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 84846 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@4b91f60d[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@33e35679, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@1e1d72f8, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@37a23e66}}}}}]]
2022-06-21 20:00:01.831 INFO [com.alibaba.nacos.client.remote.worker:c.a.n.c.r.client] [c073746a-b818-46b1-bbcc-f90f25a3afd2_config-0] Server check success, currentServer is nacos-server:8848
2022-06-21 20:00:03.759 ERROR [main :c.a.n.c.r.client] Send request fail, request = ConfigPublishRequest{headers={}, requestId='null'}, retryTimes = 0, errorMessage = java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 98895 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@1c41931a[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@33e35679, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@1e1d72f8, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@37a23e66}}}}}]]

**Comment by hyw520110** [comment]
nacos单机，和应用服务在同一台服务器上

**Comment by KomachiSion** [comment]
看报错事客户端和服务端之间的请求超时了， 可以看下是不是服务端在fullgc，或者客户端是不是在fullgc，如果都没有，看下是不是有线程争抢cpu。

**Comment by KomachiSion** [comment]
也可能是数据库慢了， 写数据库超时了。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.

**Comment by HeyChiang** [comment]
确实是nacos的问题，将nacos版本更新到2.1.1版本就好了
