### ISSUE TITLE
There is a 5-minute delay in the delivery of ncaos configuration

### ISSUE THREAD

**Issue by five111** [alibaba/nacos#8633]
The nacos server client version is 2.1.0
Use the nacos client to monitor the configuration and modify the configuration through the rest interface. The client can respond in up to 5 minutes.
After reading the source code, I found that the client implementation senses changes through timing synchronization.
We hope that once a configuration change occurs, the client can quickly perceive the change, similar to the implementation of version 1.4. Is there any way (I don't want to listen through the rest interface, and the performance can't bear it)?

nacos服务端客户端版本皆为2.1.0
使用nacos客户端监听配置，通过rest接口去修改此配置，客户端最长5分钟才能响应。
阅读源码后 发现客户端实现是通过定时同步去感知变化的。
我们希望一旦发生配置变更，客户端能够快速感知到变化，类似于1.4版本的实现，有没有什么办法（不希望通过rest接口去监听，性能扛不住）？

**Comment by li-xiao-shuang** [comment]
> The nacos server client version is 2.1.0 Use the nacos client to monitor the configuration and modify the configuration through the rest interface. The client can respond in up to 5 minutes. After reading the source code, I found that the client implementation senses changes through timing synchronization. We hope that once a configuration change occurs, the client can quickly perceive the change, similar to the implementation of version 1.4. Is there any way (I don't want to listen through the rest interface, and the performance can't bear it)?
> 
> nacos服务端客户端版本皆为2.1.0 使用nacos客户端监听配置，通过rest接口去修改此配置，客户端最长5分钟才能响应。 阅读源码后 发现客户端实现是通过定时同步去感知变化的。 我们希望一旦发生配置变更，客户端能够快速感知到变化，类似于1.4版本的实现，有没有什么办法（不希望通过rest接口去监听，性能扛不住）？

我理解你是不是在客户端添加个监听就可以了呢？

**Comment by five111** [comment]
> > The nacos server client version is 2.1.0 Use the nacos client to monitor the configuration and modify the configuration through the rest interface. The client can respond in up to 5 minutes. After reading the source code, I found that the client implementation senses changes through timing synchronization. We hope that once a configuration change occurs, the client can quickly perceive the change, similar to the implementation of version 1.4. Is there any way (I don't want to listen through the rest interface, and the performance can't bear it)?
> > nacos服务端客户端版本皆为2.1.0 使用nacos客户端监听配置，通过rest接口去修改此配置，客户端最长5分钟才能响应。 阅读源码后 发现客户端实现是通过定时同步去感知变化的。 我们希望一旦发生配置变更，客户端能够快速感知到变化，类似于1.4版本的实现，有没有什么办法（不希望通过rest接口去监听，性能扛不住）？
> 
> 我理解你是不是在客户端添加个监听就可以了呢？

我已经添加了监听 
通过client的configService.addListener方法去监听了我的配置
现在的问题是 当这个配置发生了变更 客户端无法在第一时间感知变更，
存在延迟的情况，这和客户端、服务端的实现有关

**Comment by KomachiSion** [comment]
看一下是不是数据库的时区和服务端的时区不一致，时区不一致可能导致变更的配置认为是旧配置而没有推送，通过每5min的兜底查询逻辑才能正确获取到。

**Comment by five111** [comment]
> 看一下是不是数据库的时区和服务端的时区不一致，时区不一致可能导致变更的配置认为是旧配置而没有推送，通过每5min的兜底查询逻辑才能正确获取到。

检查数据库表的GMT_MODIFIED时间可以吗 这个时间是与客户端时间是一致的

**Comment by five111** [comment]
刚刚又做了一边测试 更新下测试结果
nacos单节点 测试了大约100次 没有遇到这个问题
nacos两节点集群  A B 两个节点  客户端监听在A节点 通过rest请求配置更新在B节点发布
现象如下 
B节点正常更新 并且通过AsyncNotifyService的AsyncRpcTask任务发送通知给A节点
A节点现象如下 RpcConfigChangeNotifier中event事件有时会丢失 进入不了onenvent方法 
能进入onenvent方法的场景下 RpcPushTask经常失败 报超时
![image](https://user-images.githubusercontent.com/19482564/175933175-eafe8f0d-52b9-4841-b5f4-209dc89c81de.png)

**Comment by five111** [comment]
客户端接收push的代码入口在什么地方？

**Comment by five111** [comment]
客户端有大量这种日志 能看出什么端倪吗
java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 4 milliseconds, 636600 nanoseconds delay) for io.grpc.stub.ClientCalls$GrpcFuture@39f074e9[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@e36151b, responseMarshaller=io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@57d5b983, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@3e971091}}}}}]]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:494) ~[guava-28.1-android.jar:na]
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:192) [nacos-common-2.1.0.jar:na]
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:302) [nacos-common-2.1.0.jar:na]
        at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:389) [nacos-common-2.1.0.jar:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:885) [nacos-client-2.1.0.jar:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1032) [nacos-client-2.1.0.jar:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:940) [nacos-client-2.1.0.jar:na]
        at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:396) [nacos-client-2.1.0.jar:na]
        at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:166) [nacos-client-2.1.0.jar:na]
        at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:94) [nacos-client-2.1.0.jar:na]
        at com.huawei.GrpcThead.initNaocsGrpcConnection(GrpcThead.java:30) [classes/:na]
        at com.huawei.GrpcThead.run(GrpcThead.java:19) [classes/:na]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_222]

**Comment by KomachiSion** [comment]
> 刚刚又做了一边测试 更新下测试结果 nacos单节点 测试了大约100次 没有遇到这个问题 nacos两节点集群 A B 两个节点 客户端监听在A节点 通过rest请求配置更新在B节点发布 现象如下 B节点正常更新 并且通过AsyncNotifyService的AsyncRpcTask任务发送通知给A节点 A节点现象如下 RpcConfigChangeNotifier中event事件有时会丢失（这个频率较低） 进入不了onenvent方法 能进入onenvent方法的场景下 RpcPushTask失败（频率很高） 报超时 ![image](https://user-images.githubusercontent.com/19482564/175933175-eafe8f0d-52b9-4841-b5f4-209dc89c81de.png)

那就是时间戳的问题了，水平通知的时候会判断时间戳是否比数据库的新， 如果比数据库旧会认为是旧通知，旧忽略了。

**Comment by five111** [comment]
不好意思各位 发现问题了
我怀疑是环境的问题 在另一套服务器上部署了集群 现象一致 但是发现了如下报错 才发现是丢失了依赖 
```
2022-06-28 14:12:48.008|INFO|controller-reflector-io.kubernetes.client.openapi.models.V1DaemonSet-1|||78|i.k.c.i.cache.ReflectorRunnable class io.kubernetes.client.openapi.models.V1DaemonSet#Start listing and watching...
2022-06-28 14:12:48.339|INFO|grpc-default-worker-ELG-3-1|||146|com.alibaba.nacos.core.remote.digest Connection transportTerminated,connectionId = 1656389599353_172.16.0.1_40604
2022-06-28 14:12:48.340|INFO|grpc-default-worker-ELG-3-1|||231|com.alibaba.nacos.core.remote.digest [1656389599353_172.16.0.1_40604]Connection unregister*****#*#*****
2022-06-28 14:12:48.340|INFO|grpc-default-worker-ELG-3-1|||47|com.alibaba.nacos.core.remote.digest [1656389599353_172.16.0.1_40604]client disconnected,clear config listen context
2022-06-28 14:12:48.342|INFO|grpc-default-worker-ELG-3-1|||67|com.alibaba.nacos.core.remote [NotifyClientDisConnected] failed for listener null
java.lang.NoClassDefFoundError: com/alipay/hessian/clhm/EvictionListener
        at com.alibaba.nacos.core.remote.core.RpcAckCallbackInitorOrCleaner.clientDisConnected(RpcAckCallbackInitorOrCleaner.java:40)
        at com.alibaba.nacos.core.remote.ClientConnectionEventListenerRegistry.notifyClientDisConnected(ClientConnectionEventListenerRegistry.java:65)
        at com.alibaba.nacos.core.remote.ConnectionManager.unregister(ConnectionManager.java:232)
        at com.alibaba.nacos.core.remote.grpc.BaseGrpcServer$2.transportTerminated(BaseGrpcServer.java:147)
        at io.grpc.internal.ServerImpl$ServerTransportListenerImpl.transportTerminated(ServerImpl.java:465)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport.notifyTerminated(NettyServerTransport.java:199)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport.access$100(NettyServerTransport.java:49)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport$1TerminationNotifier.operationComplete(NettyServerTransport.java:134)
        at io.grpc.netty.shaded.io.grpc.netty.NettyServerTransport$1TerminationNotifier.operationComplete(NettyServerTransport.java:127)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:577)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:570)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:549)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:490)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:615)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:604)
        at io.grpc.netty.shaded.io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104)
        at io.grpc.netty.shaded.io.netty.channel.DefaultChannelPromise.trySuccess(DefaultChannelPromise.java:84)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$CloseFuture.setClosed(AbstractChannel.java:1159)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.doClose0(AbstractChannel.java:761)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:737)
        at io.grpc.netty.shaded.io.netty.channel.AbstractChannel$AbstractUnsafe.close(AbstractChannel.java:608)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollChannel$AbstractEpollUnsafe.shutdownInput(AbstractEpollChannel.java:479)
        at io.grpc.netty.shaded.io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:815)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:483)
        at io.grpc.netty.shaded.io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:383)
        at io.grpc.netty.shaded.io.netty.util.concurrent.SingleThreadEventExecutor$6.run(SingleThreadEventExecutor.java:1044)
        at io.grpc.netty.shaded.io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
        at io.grpc.netty.shaded.io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:750)
Caused by: java.lang.ClassNotFoundException: com.alipay.hessian.clhm.EvictionListener
        at java.net.URLClassLoader.findClass(URLClassLoader.java:407)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
        ... 29 common frames omitted
```
我们是自己编译nacos部署的 我们的编译镜像过程中 下面这个依赖的jar包名和nacos依赖的类似 我们有一种正则匹配的机制导致把这个依赖替代nacos的依赖编进了镜像  重新打包后解决了问题
```
<dependency>
        <groupId>com.caucho</groupId>
        <artifactId>hessian</artifactId>
</dependency>
```
耽误了大家时间 不好意思  感谢回答 @li-xiao-shuang @KomachiSion
