### ISSUE TITLE
应用服务报 failed to request  java.net.SocketTimeoutException: null  注册中心服务下线

### ISSUE THREAD

**Issue by kinggm520** [alibaba/nacos#8648]
问题描述：
 
nacos服务端  1.3.2版本   客户端1.0.0版本
![image](https://user-images.githubusercontent.com/34341760/176130127-9c235b7f-61fa-4be2-b179-a7aabc45b97b.png)

![image](https://user-images.githubusercontent.com/34341760/176130081-8458d12b-50d8-4c9a-b3ab-6f27cd0f1123.png)

集群模式 3台nacos机器

有个应用服务 突然报错

`
2022-06-27 08:51:33.074 ERROR [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming - request 10.211.8.139:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://10.211.8.139:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-06-27 08:51:00.447 ERROR [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming - [NA] failed to request 
java.net.SocketTimeoutException: null
	at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:89)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:326)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-06-27 08:50:20.570 WARN  [ThreadPoolTaskScheduler-1] com.alibaba.nacos.client.naming - failed to request http://10.211.8.139:8848/nacos/v1/ns/service/list?pageSize=2147483647&groupName=DEFAULT_GROUP&encoding=UTF-8&namespaceId=phoenix-online&pageNo=1 from 10.211.8.139
2022-06-27 08:51:21.672 ERROR [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming - request 10.211.8.139:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://10.211.8.139:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-06-27 08:52:05.075 WARN  [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming -
 failed to request http://10.211.8.142:8848/nacos/v1/ns/instance/list?healthyOnly=false&namespaceId=phoenix-online&clientIP=10.211.8.140&serviceName
 =DEFAULT_GROUP%40%40qgyun-service-workflow
 &udpPort=36131&encoding=UTF-8 from 10.211.8.142

 
 2022-06-27 08:51:21.672 ERROR [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming - request 10.211.8.139:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://10.211.8.139:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-06-27 08:52:14.497 ERROR [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming - [NA] failed to request 
java.net.SocketTimeoutException: null
	at java.net.SocksSocketImpl.remainingMillis(SocksSocketImpl.java:111)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.http.HttpClient.<init>(HttpClient.java:242)
	at sun.net.www.http.HttpClient.New(HttpClient.java:339)
	at sun.net.www.http.HttpClient.New(HttpClient.java:357)
	at sun.net.www.protocol.http.HttpURLConnection.getNewHttpClient(HttpURLConnection.java:1220)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.http.HttpURLConnection.connect(HttpURLConnection.java:984)
	at com.alibaba.nacos.client.naming.net.HttpClient.request(HttpClient.java:89)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:326)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-06-27 08:54:25.533 WARN  [com.alibaba.nacos.naming.beat.sender] com.alibaba.nacos.client.naming - failed to request http://10.211.8.137:8848/nacos/v1/ns/instance/beat?beat=%7B%22cluster%22%3A%22DEFAULT%22%2C%22ip%22%3A%2210.211.8.140%22%2C%22metadata%22%3A%7B%22preserved.register.source%22%3A%22SPRING_CLOUD%22%7D%2C%22port%22%3A8202%2C%22scheduled%22%3Atrue%2C%22serviceName%22%3A%22DEFAULT_GROUP%40%40ph-saas-ibmp%22%2C%22weight%22%3A1%7D&serviceName=DEFAULT_GROUP%40%40ph-saas-ibmp&encoding=UTF-8&namespaceId=phoenix-online from 10.211.8.137
2022-06-27 08:54:14.173 ERROR [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming - request 10.211.8.137:8848 failed.
com.alibaba.nacos.api.exception.NacosException: failed to req API:http://10.211.8.137:8848/nacos/v1/ns/instance/list. code:500 msg: java.net.SocketTimeoutException
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:340)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:367)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:217)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:273)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:318)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-06-27 09:01:44.644 WARN  [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming - failed to request http://10.211.8.142:8848/nacos/v1/ns/instance/list?
healthyOnly=false&namespaceId=phoenix-online&clientIP=10.211.8.140&serviceName=DEFAULT_GROUP%40%40ph-saas-platform-gateway
&udpPort=36131&encoding=UTF-8 from 10.211.8.142`

客户反馈 server error    立马查看nacos  发现 该实例在nacos已经直接查不到了      

且该实例所在服务器   有nacos相关time_wait  连接  4000+ 

怀疑是 连接数被占用完导致   重启了nacos集群  和 应用  后  发现 cluster.properties 配置文件多了个集群参数   原来是3个  后来变成了4个    （怀疑是 集群启动的端口不一致  后来三台机器端口都改成8848  cluster.properties 也相应修改    linux机器的 net.ipv4.ip_forward=1
net.ipv4.tcp_tw_reuse = 1
net.ipv4.tcp_tw_recycle = 1
三个配置也打开了    目前又运行了 2天了  暂时没发现  再报上面的 failed to request  java.net.SocketTimeoutException: null异常了
）

想请问下，报这种异常  并且实例直接掉线    结合我使用的版本  除了 连接数占用完   还有没有其他可能情况 （排除网络问题  应用代码问题）  ？

**Comment by onewe** [comment]
我记得 1.4.2 之前, 这种问题会导致 心跳线程 死掉, 导致永远无法自动上线. 建议升级客户端版本.

**Comment by jefferson-chern** [comment]
你们服务数和实例数分别多少？是dubbo和nacos结合的吗？
服务数和实例数看日志 naming-perfermance.log

**Comment by kinggm520** [comment]
十分感谢&nbsp; 我升级下客户端试试



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月28日(周二) 晚上6:49
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] 应用服务报 failed to request  java.net.SocketTimeoutException: null  注册中心服务下线 (Issue #8648)




 
我记得 1.4.2 之前, 这种问题会导致 心跳线程 死掉, 导致永远无法自动上线. 建议升级客户端版本.

**Comment by kinggm520** [comment]
> 
注册中心只有nacos，nacos-server 集群3个           掉线的那个应用  启动的实例数是2个   

我目前在测试环境 把1.0.0版本nacos-client升级到了1.4.3   nacos-server升级到了2.0.3     启了3个应用实例 使用webbench 压了10w并发  测试了3分钟   出现了
socketTimeout Exception   nacos上有部分应用开始掉线   3分钟压测结束后  又陆续上线了 
之前掉线无法自动回复  现在貌似可以了  不过还需要进行更长时间的压测再试试
![image](https://user-images.githubusercontent.com/34341760/176590701-2bed9606-4e1b-48ad-b076-a5b7ee0c0abe.png)
![image](https://user-images.githubusercontent.com/34341760/176590748-2c48da4a-b04a-4a46-b5e7-437a82d0b10e.png)

**Comment by kinggm520** [comment]
> 你们服务数和实例数分别多少？是dubbo和nacos结合的吗？ 服务数和实例数看日志 naming-perfermance.log

注册中心只有nacos，nacos-server 集群3个 掉线的那个应用 启动的实例数是2个

我目前在测试环境 把1.0.0版本nacos-client升级到了1.4.3 nacos-server升级到了2.0.3 启了3个应用实例 使用webbench 压了10w并发 测试了3分钟 出现了
socketTimeout Exception nacos上有部分应用开始掉线 3分钟压测结束后 又陆续上线了
之前掉线无法自动回复 现在貌似可以了 不过还需要进行更长时间的压测再试试

**Comment by KomachiSion** [comment]
1.x版本是断链接，每次心跳和查询都会创建新连接，有些客户端版本在关闭连接操作上可能有bug，会导致连接数上升。

最好的版版还是升级到2.1.0版本。 通过长链接来解决这个问题最好，正常使用情况下一个客户端不会超过3个连接

**Comment by kinggm520** [comment]
主要是目前应用系统使用的客户端版本是1.0.0&nbsp; &nbsp;直接升到2.1.0版本&nbsp; 可能到会有很多意料不到的问题&nbsp; &nbsp; 生产环境 目前承受不了超过一天时间的停机&nbsp; &nbsp; &nbsp;也只能先升级到1.4.3版本&nbsp; 过渡一下&nbsp; &nbsp;测试了下1.4.3 客户端连接数还是很多&nbsp; &nbsp; 不过&nbsp; 出现连接异常之后&nbsp; 服务下线&nbsp; &nbsp;并发下来之后&nbsp; 服务又会重新恢复上线&nbsp; &nbsp;目前准备还是暂时升级到1.4.3 过渡一下



---原始邮件---
发件人: "杨翊 ***@***.***&gt;
发送时间: 2022年7月1日(周五) 上午10:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] 应用服务报 failed to request  java.net.SocketTimeoutException: null  注册中心服务下线 (Issue #8648)




 
1.x版本是断链接，每次心跳和查询都会创建新连接，有些客户端版本在关闭连接操作上可能有bug，会导致连接数上升。
 
最好的版版还是升级到2.1.0版本。 通过长链接来解决这个问题最好，正常使用情况下一个客户端不会超过3个连接

**Comment by kinggm520** [comment]
注册中心只有nacos，nacos-server 集群3个&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;掉线的那个应用&nbsp; 启动的实例数是2个&nbsp; &nbsp;


我目前在测试环境 把1.0.0版本nacos-client升级到了1.4.3&nbsp; &nbsp;nacos-server升级到了2.0.3&nbsp; &nbsp; &nbsp;启了3个应用实例 使用webbench 压了10w并发&nbsp; 测试了3分钟&nbsp; &nbsp;出现了
socketTimeout Exception&nbsp; &nbsp;nacos上有部分应用开始掉线&nbsp; &nbsp;3分钟压测结束后&nbsp; 又陆续上线了&nbsp;&nbsp;
之前掉线无法自动回复&nbsp; 现在貌似可以了&nbsp; 不过还需要进行更长时间的压测再试试&nbsp;

---原始邮件---
发件人: "Jefferson ***@***.***&gt;
发送时间: 2022年6月30日(周四) 中午11:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/nacos] 应用服务报 failed to request  java.net.SocketTimeoutException: null  注册中心服务下线 (Issue #8648)




 
你们服务数和实例数分别多少？是dubbo和nacos结合的吗？
 服务数和实例数看日志 naming-perfermance.log
