### ISSUE TITLE
com.alibaba.nacos.client.naming :[NA] failed to read cache file

### ISSUE THREAD

**Issue by ipanocloud** [alibaba/nacos#8666]
`2022-06-30 21:31:36.908 ERROR [#][#] <main> com.alibaba.nacos.client.naming :[NA] failed to read cache file
java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer;
	at com.alibaba.nacos.client.naming.cache.ConcurrentDiskUtil.getFileContent(ConcurrentDiskUtil.java:93)
	at com.alibaba.nacos.client.naming.cache.DiskCache.read(DiskCache.java:119)
	at com.alibaba.nacos.client.naming.cache.ServiceInfoHolder.<init>(ServiceInfoHolder.java:72)
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:94)
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:81)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59)
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77)
	at org.apache.dubbo.registry.nacos.util.NacosNamingServiceUtils.createNamingService(NacosNamingServiceUtils.java:112)
	at org.apache.dubbo.registry.nacos.NacosServiceDiscovery.initialize(NacosServiceDiscovery.java:64)`

SCA 2.2.7.RELEASE版本,nacos-client 2.0.3版本引用启动时报错

**Comment by KomachiSion** [comment]
应该是类冲突了吧，java.nio.ByteBuffer这个类定义错误了。环境问题得自查了。
