### ISSUE TITLE
Nacos for Problems encountered during registration

### ISSUE THREAD

**Issue by rothschil** [alibaba/nacos#867]
## Issue Description

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)
Nacos client startup process, occurs in the registration process，“http://null/nacos/serverlist'. Server returned: 500”

### Describe what you expected to happen
![Configuration information](https://github.com/rothschil/static/raw/master/images/is/20190305/1.png)
![Problem screenshot](https://github.com/rothschil/static/raw/master/images/is/20190305/2.png)

### How to reproduce it (as minimally and precisely as possible)

1.  
2.  
3. 

### Tell us your environment
1、client server version : nacos-server-0.8.0
2.   spring-cloud-starter-alibaba-nacos-discovery version :  0.2.1.RELEASE

**Comment by nkorange** [comment]
Please re-upload your error screenshot.

**Comment by giraffe8** [comment]
我也出现这个问题，
spring boot version: 2.1.4.RELEASE
spring cloud version: Greenwich.RELEASE
spring cloud alibaba version: 0.2.1.RELEASE


2019-04-23 22:25:23.856  INFO 4576 --- [  restartedMain] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat started on port(s): 8087 (http) with context path ''
java.io.IOException: Error while requesting: http://null/nacos/serverlist'. Server returned: 500
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServerListFromEndpoint(NamingProxy.java:102)
	at com.alibaba.nacos.client.naming.net.NamingProxy.refreshSrvIfNeed(NamingProxy.java:135)
	at com.alibaba.nacos.client.naming.net.NamingProxy.access$000(NamingProxy.java:39)
	at com.alibaba.nacos.client.naming.net.NamingProxy$2.run(NamingProxy.java:83)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset$$$capture(FutureTask.java:308)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
java.io.IOException: Error while requesting: http://null/nacos/serverlist'. Server returned: 500
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServerListFromEndpoint(NamingProxy.java:102)
	at com.alibaba.nacos.client.naming.net.NamingProxy.refreshSrvIfNeed(NamingProxy.java:135)
	at com.alibaba.nacos.client.naming.net.NamingProxy.<init>(NamingProxy.java:87)
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:135)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:43)
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:74)
	at org.springframework.cloud.alibaba.nacos.NacosDiscoveryProperties.namingServiceInstance(NacosDiscoveryProperties.java:379)
	at org.springframework.cloud.alibaba.nacos.registry.NacosRegistration.getNacosNamingService(NacosRegistration.java:122)
	at org.springframework.cloud.alibaba.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:45)
	at org.springframework.cloud.alibaba.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:29)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:219)
	at org.springframework.cloud.alibaba.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:75)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:118)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.bind(AbstractAutoServiceRegistration.java:82)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:69)
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:32)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.finishRefresh(ServletWebServerApplicationContext.java:166)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:552)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.qingzu.renter.RenterApplication.main(RenterApplication.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49)

**Comment by giraffe8** [comment]
Spring Boot | Spring Cloud | Spring Cloud Alibaba
-- | -- | --
2.1.x | Greenwich | 0.9.x
2.0.x | Finchley | 0.2.x
1.5.x | Edgware | 0.1.x
1.5.x | Dalston | 0.1.x

Spring Cloud Alibaba 是不是需要0.9.x？

**Comment by nkorange** [comment]
@giraffe8 What's your configuration of Nacos?
