### ISSUE TITLE
将nacos的账号密码抽离到配置中心后无法获取到配置了

### ISSUE THREAD

**Issue by somta** [alibaba/nacos#8704]
**Describe the bug**
SpringBoot 2.4.2
nacos 1.4.2
spring cloud alibaba 2021.1
spring cloud 2020.0.1

1.开启nacos的认证

2.在代码本地的bootstrap.properties添加如下配置
server.port=8080
spring.application.name=test-demo
spring.cloud.nacos.server-addr=127.0.0.1:8848
spring.cloud.nacos.username=nacos_dev
spring.cloud.nacos.password=nacos_dev

3.nacos配置中心添加服务远程配置test-demo..properties,内容如下
common.name=zhansan

4. 获取配置中心配置
@RestController
@RefreshScope
public class TestController {

    // 配置中心的值
    @Value("${common.name}")
    private String configName;

    @GetMapping("/info")
    public String info() {
        return "test is ok:"  + configName;
    }
}

上面情况能正常获取配置中心的配置信息
=============================
错误场景
将账号密码配置抽离到配置中心的test-demo.properties中
spring.cloud.nacos.username=nacos_dev
spring.cloud.nacos.password=nacos_dev

启动直接报错，没有找到配置中心的配置文件，错误如下
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'testController': Injection of autowired dependencies failed; nested exception is java.lang.IllegalArgumentException: Could not resolve placeholder 'common.name' in value "${common.name}"
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessProperties(AutowiredAnnotationBeanPostProcessor.java:405) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1415) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:608) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:531) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:944) ~[spring-beans-5.3.3.jar:5.3.3]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:923) ~[spring-context-5.3.3.jar:5.3.3]

**Expected behavior**

**Actually behavior**
A clear and concise description of what you actually to happen.

**How to Reproduce**
4. See errors

**Desktop (please complete the following information):**
 - OS: [e.g. Centos]
 - Version [e.g. nacos-server 1.3.1, nacos-client 1.3.1]
 - Module [e.g. naming/config]
 - SDK [e.g. original, spring-cloud-alibaba-nacos, dubbo]

**Additional context**

**Comment by somta** [comment]
那只能通过环境变量注入了啊

**Comment by KomachiSion** [comment]
可以到spring cloud alibaba 社区问一问还有什么办法？
