### ISSUE TITLE
服务降级后，重新启动NACOS后，微服务注册不上去

### ISSUE THREAD

**Issue by wangwenpeng1** [alibaba/nacos#8725]
HI，您好：

     生产环境中，遇到系统中服务降级后，重新启动NACOS后，微服务注册不上去，具体的报错信息如下：

   ERROR c.alibaba.nacos.client.config.http.ServerHttpAgent:100 - [NACOS ConnectException] currentServerAddr: http://IP:80, httpCode: 502 
ERROR com.alibaba.nacos.client.config.impl.ClientWorker:303 - [fixed-IP_80] [sub-server] get server config exception, dataId=jeecloud-prod-config.yaml, group=DEFAULT_GROUP, tenant=
java.net.ConnectException: [NACOS HTTP-GET] The maximum number of tolerable server reconnection errors has been reached
 ........

2022-06-28 09:12:49.531 [boundedElastic-1] ERROR com.alibaba.nacos.client.naming:613 - [NA] failed to request
com.alibaba.nacos.api.exception.NacosException: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:611)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
	at com.alibaba.nacos.client.naming.net.NamingProxy.getServiceList(NamingProxy.java:474)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:492)
	at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:480)
	at com.alibaba.cloud.nacos.discovery.NacosServiceDiscovery.getServices(NacosServiceDiscovery.java:69)
	at com.alibaba.cloud.nacos.discovery.reactive.NacosReactiveDiscoveryClient.lambda$getServices$1(NacosReactiveDiscoveryClient.java:75)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:46)
	at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:187)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
	at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

................................................

2022-06-28 10:06:11.850 [com.alibaba.nacos.naming.beat.sender] ERROR com.alibaba.nacos.client.naming:613 - [NA] failed to request
com.alibaba.nacos.api.exception.NacosException: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
</body>
</html>
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:611)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:538)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
	at com.alibaba.nacos.client.naming.net.NamingProxy.sendBeat(NamingProxy.java:426)
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:167)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-06-28 10:06:11.851 [com.alibaba.nacos.naming.beat.sender] ERROR com.alibaba.nacos.client.naming:548 - request: /nacos/v1/ns/instance/beat failed, servers: [IP:80], code: 500, msg: <html>
<head><title>502 Bad Gateway</title></head>
<body>
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx</center>
。。。。

谢谢！！

**Comment by KomachiSion** [comment]
错误像是nginx抛出的， 直接在nacos上注册看看。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
