### ISSUE TITLE
No DataSource set（nacos 1.2.1 is failed,  nacos 1.4.2 is success）

### ISSUE THREAD

**Issue by cdk8s-zelda** [alibaba/nacos#8753]
## nacos 1.2.1 log

```

2022-07-16 20:21:50,807 ERROR Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'opsController' defined in URL [jar:file:/Users/meek/my-software/nacos/nacos-1.2.1/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-1.2.1.jar!/com/alibaba/nacos/config/server/controller/OpsController.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1308)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1154)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:538)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:846)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:863)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:546)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:142)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:316)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:593)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'dumpService': Invocation of init method failed; nested exception is java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:139)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:419)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1737)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:576)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:498)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:320)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:318)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:273)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1237)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1164)
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857)
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760)
	... 27 common frames omitted
Caused by: java.lang.RuntimeException: Nacos Server did not start because dumpservice bean construction failure :
No DataSource set
	at com.alibaba.nacos.config.server.service.dump.DumpService.init(DumpService.java:142)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:363)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:307)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:136)
	... 40 common frames omitted
```

```
2022-07-16 20:24:14,199 ERROR [db-error] master db 127.0.0.1 down.
2022-07-16 20:24:24,194 ERROR [master-db] master db not found.
2022-07-16 20:24:28,207 ERROR [db-error] master db 127.0.0.1 down.
2022-07-16 20:24:38,206 ERROR [master-db] master db not found.
```

-------------------------------------------------------------------

## nacos 1.2.1 startup log

- `sh /Users/meek/my-software/nacos/nacos-1.2.1/bin/startup.sh -m standalone`

```
/Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home/bin/java  -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Djava.ext.dirs=/Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home/jre/lib/ext:/Library/Java/JavaVirtualMachines/jdk1.8.0_311.jdk/Contents/Home/lib/ext -Xloggc:/Users/meek/my-software/nacos/nacos-1.2.1/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/Users/meek/my-software/nacos/nacos-1.2.1/plugins/health,/Users/meek/my-software/nacos/nacos-1.2.1/plugins/cmdb,/Users/meek/my-software/nacos/nacos-1.2.1/plugins/mysql -Dnacos.home=/Users/meek/my-software/nacos/nacos-1.2.1 -jar /Users/meek/my-software/nacos/nacos-1.2.1/target/nacos-server.jar  --spring.config.location=classpath:/,classpath:/config/,file:./,file:./config/,file:/Users/meek/my-software/nacos/nacos-1.2.1/conf/ --logging.config=/Users/meek/my-software/nacos/nacos-1.2.1/conf/nacos-logback.xml --server.max-http-header-size=524288
nacos is starting with standalone
nacos is starting，you can check the /Users/meek/my-software/nacos/nacos-1.2.1/logs/start.out
```

-------------------------------------------------------------------

## nacos 1.2.1 config

- This is a newly downloaded zip package, only modify this part of the content。

```
spring.datasource.platform=mysql

### Count of DB:
db.num=1

### Connect URL of DB:
db.url.0=jdbc:mysql://127.0.0.1:3306/nacos_config?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.user=root
db.password=123456
```

## I also downloaded nacos 1.4.2 , the same method and configuration is ok.

-------------------------------------------------------------------

 - OS: mac 12
 - Version nacos 1.2.1
 
-------------------------------------------------------------------

#### Navicat is ok

![image](https://user-images.githubusercontent.com/51701412/179355058-b3e7667b-aea8-47c1-9b79-1b3cb7337da5.png)

![image](https://user-images.githubusercontent.com/51701412/179355075-d415b7a7-6fd6-437c-9fae-fe6788e02dca.png)

**Comment by onewe** [comment]
please see the config-fatal.log

**Comment by cdk8s-zelda** [comment]
> 

Yes, please read it carefully

**Comment by cdk8s-zelda** [comment]
> please see the config-fatal.log

![image](https://user-images.githubusercontent.com/51701412/179355307-8772d938-1ec9-44a0-9ae2-b9fb769e5278.png)

**Comment by cdk8s-zelda** [comment]
> please see the config-fatal.log

- I didn't make any changes, only the database config is modified。
- I also downloaded nacos 1.4.2 , the same method and configuration is ok.
- Also, I'm just opening comments to modify the content, not copy

**Comment by onewe** [comment]
I got it, there is some error detail informations about database in the config-fatal.log , so you should check it.

**Comment by cdk8s-zelda** [comment]
> I got it, there is some error detail informations about database in the config-fatal.log , so you should check it.

- This is the full text of the document，I didn't find any useful information.

```
2022-07-16 20:21:46,101 ERROR [master-db] master db not found.

2022-07-16 20:21:50,111 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:21:50,723 WARN useAddressServer:true

2022-07-16 20:21:50,761 WARN isQuickStart:false

2022-07-16 20:21:50,779 ERROR Nacos Server did not start because dumpservice bean construction failure :
No DataSource set

2022-07-16 20:22:04,116 ERROR [master-db] master db not found.

2022-07-16 20:22:08,120 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:22:18,125 ERROR [master-db] master db not found.

2022-07-16 20:22:22,133 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:22:32,136 ERROR [master-db] master db not found.

2022-07-16 20:22:36,143 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:22:46,146 ERROR [master-db] master db not found.

2022-07-16 20:22:50,148 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:23:00,157 ERROR [master-db] master db not found.

2022-07-16 20:23:04,163 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:23:14,164 ERROR [master-db] master db not found.

2022-07-16 20:23:18,168 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:23:28,169 ERROR [master-db] master db not found.

2022-07-16 20:23:32,179 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:23:42,177 ERROR [master-db] master db not found.

2022-07-16 20:23:46,191 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:23:56,181 ERROR [master-db] master db not found.

2022-07-16 20:24:00,195 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:24:10,186 ERROR [master-db] master db not found.

2022-07-16 20:24:14,199 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:24:24,194 ERROR [master-db] master db not found.

2022-07-16 20:24:28,207 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:24:38,206 ERROR [master-db] master db not found.

2022-07-16 20:24:42,212 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:24:52,216 ERROR [master-db] master db not found.

2022-07-16 20:24:56,221 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:25:06,221 ERROR [master-db] master db not found.

2022-07-16 20:25:10,224 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:25:20,229 ERROR [master-db] master db not found.

2022-07-16 20:25:24,231 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:25:34,242 ERROR [master-db] master db not found.

2022-07-16 20:25:38,245 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:25:48,253 ERROR [master-db] master db not found.

2022-07-16 20:25:52,257 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:26:02,265 ERROR [master-db] master db not found.

2022-07-16 20:26:06,270 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:26:16,280 ERROR [master-db] master db not found.

2022-07-16 20:26:20,286 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:26:30,285 ERROR [master-db] master db not found.

2022-07-16 20:26:34,292 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:26:44,293 ERROR [master-db] master db not found.

2022-07-16 20:26:48,296 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:48:27,462 ERROR [master-db] master db not found.

2022-07-16 20:48:31,470 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:48:32,101 WARN useAddressServer:true

2022-07-16 20:48:32,139 WARN isQuickStart:false

2022-07-16 20:48:32,156 ERROR Nacos Server did not start because dumpservice bean construction failure :
No DataSource set

2022-07-16 20:48:45,486 ERROR [master-db] master db not found.

2022-07-16 20:48:49,488 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:48:59,495 ERROR [master-db] master db not found.

2022-07-16 20:49:03,504 ERROR [db-error] master db 127.0.0.1 down.

2022-07-16 20:49:13,503 ERROR [master-db] master db not found.

2022-07-16 20:49:17,516 ERROR [db-error] master db 127.0.0.1 down.


```

**Comment by onewe** [comment]
Why don't you use the latest version, the old version may have some bugs.

**Comment by cdk8s-zelda** [comment]
> Why don't you use the latest version, the old version may have some bugs.

- Because the official website told me，I use this version：`Spring Boot 2.2.5.RELEASE`
- <https://github.com/alibaba/spring-cloud-alibaba/wiki/%E7%89%88%E6%9C%AC%E8%AF%B4%E6%98%8E>

**Comment by onewe** [comment]
Hey, buddy, the document may be outdated, I suggest that you  use 1.4.3 or higher(2.x).

**Comment by cdk8s-zelda** [comment]
> Hey, buddy, the document may be outdated, I suggest that you use 1.4.3 or higher(2.x).

- 😒
- Ok， Thank you for your help tonight.
- I use `Spring Boot 2.2.5`， Which `Spring Cloud Alibaba` version do you recommend？

**Comment by onewe** [comment]
emmmm, I beg your pardon, I have no idea. I don't know much about SCA.

**Comment by cdk8s-zelda** [comment]
> emmmm, I beg your pardon, I have no idea. I don't know much about SCA.

- Thank you for tonight.

**Comment by judasn** [comment]
如果你使用的是比较旧的 nacos 比如 1.1.4，并且用的是 MySQL 8，则你需要在 nacos 目录下创建：plugins/mysql 目录，然后放上：mysql-connector-java-8.0.17.jar

如果你使用的是：1.4.4 或者 2.x 等新版本，那一般是不需要，因为 nacos-server.jar 的 lib 目录中已经自带了 mysql-connector-java-8.x.jar。
