### ISSUE TITLE
Dubbo client connect to the old service ip, How long is it updated? 

### ISSUE THREAD

**Issue by marvinpan8** [alibaba/nacos#8770]
**Describe the bug**
Dubbo client connect to the old service ip, How long is it updated? 

**Expected behavior**

Dubbo client connect to the new service ip
**Actually behavior**
 
 The bug as below:

```
2022-07-11 13:40:37.249 [nacos-grpc-client-executor-25] INFO  com.alibaba.nacos.common.remote.client: - [a3dd3b97-3826-4b7e-8f2b-1dbe8dc6f022]ack server push request,request=NotifySubscriberRequest,requestId=114270
2022-07-11 13:40:39.707 [dubbo-client-idleCheck-thread-1] ERROR o.a.d.r.exchange.support.header.ReconnectTimerTask: -  [DUBBO] Fail to connect to HeaderExchangeClient [channel=org.apache.dubbo.remoting.transport.netty4.NettyClient [/10.244.116.189:41532 -> /10.244.94.92:20880]], dubbo version: 2.7.8, current host: 10.244.116.189
org.apache.dubbo.remoting.RemotingException: client(url: dubbo://10.244.94.92:20880/com.alibaba.cloud.dubbo.service.DubboMetadataService?anyhost=true&application=vehicle&bind.ip=10.244.94.92&bind.port=20880&check=false&codec=dubbo&deprecated=false&dubbo=2.0.2&dynamic=true&generic=true&group=common&heartbeat=60000&interface=com.alibaba.cloud.dubbo.service.DubboMetadataService&metadata-type=remote&methods=getAllServiceKeys,getServiceRestMetadata,getExportedURLs,getAllExportedURLs&pid=1&qos.enable=false&register.ip=10.244.116.189&release=2.7.8&remote.application=common&revision=2.2.3.RELEASE&scope=remote&side=consumer&sticky=false&timestamp=1656064623727&version=1.0.0) failed to connect to server /10.244.94.92:20880 client-side timeout 3000ms (elapsed: 3000ms) from netty client 10.244.116.189 using dubbo version 2.7.8
	at org.apache.dubbo.remoting.transport.netty4.NettyClient.doConnect(NettyClient.java:174)
	at org.apache.dubbo.remoting.transport.AbstractClient.connect(AbstractClient.java:191)
	at org.apache.dubbo.remoting.transport.AbstractClient.reconnect(AbstractClient.java:247)
	at org.apache.dubbo.remoting.exchange.support.header.HeaderExchangeClient.reconnect(HeaderExchangeClient.java:166)
	at org.apache.dubbo.remoting.exchange.support.header.ReconnectTimerTask.doTask(ReconnectTimerTask.java:49)
	at org.apache.dubbo.remoting.exchange.support.header.AbstractTimerTask.run(AbstractTimerTask.java:87)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelTimeout.expire(HashedWheelTimer.java:648)
	at org.apache.dubbo.common.timer.HashedWheelTimer$HashedWheelBucket.expireTimeouts(HashedWheelTimer.java:727)
	at org.apache.dubbo.common.timer.HashedWheelTimer$Worker.run(HashedWheelTimer.java:449)
	at java.lang.Thread.run(Thread.java:748)
```

**How to Reproduce**
Update the registration services more frequently

**Desktop (please complete the following information):**
 - OS: [Centos]
 - Version [nacos-server 2.0.1, nacos-client 2.0.1]
 - Module [naming/config]
 - SDK [spring-cloud-alibaba-nacos, dubbo]

**Comment by KomachiSion** [comment]
See `${user.home}/logs/nacos/naming.log` to find which time the new ip push to client.

If common situation, the time should be under 3s.

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
