### ISSUE TITLE
进程退出时偶发死锁

### ISSUE THREAD

**Issue by jsagittary** [alibaba/nacos#8817]
Found one Java-level deadlock:
=============================
"Thread-9":
  waiting to lock monitor 0x0000000002463288 (object 0x00000007bb3066c8, a org.apache.http.pool.AbstractConnPool$2),
  which is held by "com.alibaba.nacos.client.naming.updater"
"com.alibaba.nacos.client.naming.updater":
  waiting for ownable synchronizer 0x00000005c091e2e0, (a java.util.concurrent.locks.ReentrantLock$NonfairSync),
  which is held by "Thread-9"

Java stack information for the threads listed above:
===================================================
"Thread-9":
	at org.apache.http.pool.AbstractConnPool$2.cancel(AbstractConnPool.java:207)
	- waiting to lock <0x00000007bb3066c8> (a org.apache.http.pool.AbstractConnPool$2)
	at org.apache.http.pool.RouteSpecificPool.shutdown(RouteSpecificPool.java:155)
	at org.apache.http.pool.AbstractConnPool.shutdown(AbstractConnPool.java:152)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.shutdown(PoolingHttpClientConnectionManager.java:396)
	at org.apache.http.impl.client.HttpClientBuilder$2.close(HttpClientBuilder.java:1225)
	at org.apache.http.impl.client.InternalHttpClient.close(InternalHttpClient.java:201)
	at com.alibaba.nacos.common.http.client.DefaultHttpClientRequest.close(DefaultHttpClientRequest.java:77)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.close(NacosRestTemplate.java:343)
	at com.alibaba.nacos.common.http.HttpClientBeanHolder.nacostRestTemplateShutdown(HttpClientBeanHolder.java:123)
	at com.alibaba.nacos.common.http.HttpClientBeanHolder.shutdown(HttpClientBeanHolder.java:110)
	at com.alibaba.nacos.common.http.HttpClientBeanHolder$1.run(HttpClientBeanHolder.java:50)
	at java.lang.Thread.run(Thread.java:745)
"com.alibaba.nacos.client.naming.updater":
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000005c091e2e0> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireQueued(AbstractQueuedSynchronizer.java:870)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2043)
	at org.apache.http.pool.AbstractConnPool.getPoolEntryBlocking(AbstractConnPool.java:377)
	at org.apache.http.pool.AbstractConnPool.access$200(AbstractConnPool.java:67)
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:243)
	- locked <0x00000007bb3066c8> (a org.apache.http.pool.AbstractConnPool$2)
	at org.apache.http.pool.AbstractConnPool$2.get(AbstractConnPool.java:191)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:282)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:269)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:191)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.alibaba.nacos.common.http.client.DefaultHttpClientRequest.execute(DefaultHttpClientRequest.java:54)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:330)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchangeForm(NacosRestTemplate.java:319)
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:599)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:524)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:491)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:486)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:400)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:330)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:397)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Found 1 deadlock.

**Comment by stone-98** [comment]
需要提供更多信息

**Comment by KomachiSion** [comment]
看上去像是apache-http的bug， 在shutdown的时候如果有请求会死锁，可以尝试升级一下nacos的版本试试， nacos新版本可能升级过apache-http版本。

**Comment by zhangyunan1994** [comment]
@jsagittary  这个可以提供一下使用的 Nacos 的版本吗

**Comment by jsagittary** [comment]
目前使用的nacos-client:1.3.1

**Comment by jsagittary** [comment]
> 看上去像是apache-http的bug， 在shutdown的时候如果有请求会死锁，可以尝试升级一下nacos的版本试试， nacos新版本可能升级过apache-http版本。

嗯，我正在尝试更新apache的版本，只是未能复现死锁的情况，还在观察中

**Comment by KomachiSion** [comment]
那就先关闭issue了，如果后续又出现了的话，收集一下更多信息再提交一个pr吧。
