### ISSUE TITLE
error of istio-proxy when config a nacos mcp service

### ISSUE THREAD

**Issue by jjluUp** [alibaba/nacos#8837]
**Describe the bug**
nacos integrated istio, nacos-server configuration
```
nacos.istio.mcp.server.enabled=true
nacos.istio.mcp.server.port=18848
nacos.istio.mcp.push.interval=3000
nacos.istio.domain.suffix=nacos
```
istio configuration
```
configSources:
  - address: xds://192.168.240.132:18848
```
LDS synchronization failure
```
$ istioctl ps
NAME                                                                CLUSTER      CDS        LDS                            EDS        RDS          ISTIOD                      VERSION
istio-demo-consumer-v1-7656c59f5-wh4ct.istio-demo                   cluster2     SYNCED     STALE (Never Acknowledged)     SYNCED     SYNCED       istiod-695d4fcd56-c4lqc     1.13.5
istio-demo-dubbo-producer-v1-54b85cb9fd-svg77.istio-demo            cluster2     SYNCED     STALE (Never Acknowledged)     SYNCED     SYNCED       istiod-695d4fcd56-c4lqc     1.13.5
istio-demo-gateway-v1-64884c95bc-zfx8x.istio-demo                   cluster2     SYNCED     STALE (Never Acknowledged)     SYNCED     SYNCED       istiod-695d4fcd56-c4lqc     1.13.5
istio-demo-gateway-v1-f8cfbcdf6-jfx8p.istio-demo                    cluster2     SYNCED     STALE (Never Acknowledged)     SYNCED     SYNCED       istiod-695d4fcd56-c4lqc     1.13.5
istio-demo-spring-cloud-producer-v1-659b87c656-kz2jw.istio-demo     cluster2     SYNCED     STALE (Never Acknowledged)     SYNCED     SYNCED       istiod-695d4fcd56-c4lqc     1.13.5
istio-ingressgateway-59b975fd78-zs5pc.istio-system                  cluster2     SYNCED     SYNCED                         SYNCED     SYNCED       istiod-695d4fcd56-c4lqc     1.13.5
```
Application istio-proxy failed to start
```
2022-07-30T16:54:46.914406Z error envoy config listener '240.240.0.2_0' failed to bind or apply socket options: cannot bind '240.240.0.2': Read-only file system

2022-07-30T16:54:46.988045Z error envoy config listener '240.240.0.1_0' failed to bind or apply socket options: cannot bind '240.240.0.1': Read-only file system

2022-07-30T16:54:47.714537Z warning envoy config gRPC config for type.googleapis.com/envoy.config.listener.v3.Listener rejected: Error adding/updating listener(s) 240.240.0.2_0: cannot bind '240.240.0.2': Read-only file system

240.240.0.1_0: cannot bind '240.240.0.1': Read-only file system

2022-07-30T16:54:49.662962Z warn Envoy proxy is NOT ready: config received from XDS server, but was rejected: cds updates: 1 successful, 0 rejected; lds updates: 0 successful, 1 rejected
```
Version
```
nacos version 2.1.0

istioctl version
client version: 1.13.5
control plane version: 1.13.5
data plane version: 1.13.5 (4 proxies)
```

**Comment by YunWZ** [comment]
has any nacos server log?
the log path default is `${nacos.home}/logs`, and log file name `istio-main.log`

**Comment by jjluUp** [comment]
@YunWZ I found that there will be problems when registering the dubbo service
dubbo versioon: 2.6.6
dubbo-registry-nacos version: 2.6.12

istio-main.log
```
2022-07-31 13:31:05,781 INFO xds: ack, type security.istio.io/v1beta1/AuthorizationPolicy, connection-id sidecar~10.241.72.160~istiod-85f65ddb8-jvxvl.istio-system~istio-system.svc.cluster.local-38, version 2022-07-31T00:55:09+08:00/24, nonce ee3a6b9aa1ce4b01b67f392424ee0117

2022-07-31 13:31:05,781 INFO xds: ack, type networking.istio.io/v1beta1/ProxyConfig, connection-id sidecar~10.241.72.143~istiod-85f65ddb8-r6wdg.istio-system~istio-system.svc.cluster.local-39, version 2022-07-31T00:55:09+08:00/24, nonce 07293d4209e64540a0f594684fa1c3f8

2022-07-31 13:31:05,781 INFO xds: ack, type security.istio.io/v1beta1/PeerAuthentication, connection-id sidecar~10.241.72.160~istiod-85f65ddb8-jvxvl.istio-system~istio-system.svc.cluster.local-38, version 2022-07-31T00:55:09+08:00/24, nonce a575df44e1e24d8eba48598fd779a19d

2022-07-31 13:31:05,781 INFO xds: ack, type security.istio.io/v1beta1/AuthorizationPolicy, connection-id sidecar~10.241.72.143~istiod-85f65ddb8-r6wdg.istio-system~istio-system.svc.cluster.local-39, version 2022-07-31T00:55:09+08:00/24, nonce 46b48135312f4535b2cb7434b7d9c762

2022-07-31 13:31:05,781 INFO xds: ack, type security.istio.io/v1beta1/RequestAuthentication, connection-id sidecar~10.241.72.160~istiod-85f65ddb8-jvxvl.istio-system~istio-system.svc.cluster.local-38, version 2022-07-31T00:55:09+08:00/24, nonce ad1fb897cf5f489e9c7611528bf7cba2

2022-07-31 13:31:05,781 INFO xds: ack, type telemetry.istio.io/v1alpha1/Telemetry, connection-id sidecar~10.241.72.160~istiod-85f65ddb8-jvxvl.istio-system~istio-system.svc.cluster.local-38, version 2022-07-31T00:55:09+08:00/24, nonce 85ecf9fcb4154b77a166ba67350b77a6

2022-07-31 13:31:05,781 INFO xds: ack, type security.istio.io/v1beta1/PeerAuthentication, connection-id sidecar~10.241.72.143~istiod-85f65ddb8-r6wdg.istio-system~istio-system.svc.cluster.local-39, version 2022-07-31T00:55:09+08:00/24, nonce fc6b8aaa873e4d028e55ef33d7ea386e

2022-07-31 13:31:05,781 INFO xds: ack, type security.istio.io/v1beta1/RequestAuthentication, connection-id sidecar~10.241.72.143~istiod-85f65ddb8-r6wdg.istio-system~istio-system.svc.cluster.local-39, version 2022-07-31T00:55:09+08:00/24, nonce 57cf2f0daac143488f688abee40c64d4

2022-07-31 13:31:05,781 INFO xds: ack, type telemetry.istio.io/v1alpha1/Telemetry, connection-id sidecar~10.241.72.143~istiod-85f65ddb8-r6wdg.istio-system~istio-system.svc.cluster.local-39, version 2022-07-31T00:55:09+08:00/24, nonce 1ed6bb7430af46819a36047adcdf6c20

2022-07-31 13:36:55,705 ERROR xds: sidecar~10.241.72.143~istiod-85f65ddb8-r6wdg.istio-system~istio-system.svc.cluster.local-39 stream error.

io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
	at io.grpc.Status.asRuntimeException(Status.java:524)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:275)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:867)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2022-07-31 13:36:55,707 ERROR xds: sidecar~10.241.72.160~istiod-85f65ddb8-jvxvl.istio-system~istio-system.svc.cluster.local-38 stream error.

io.grpc.StatusRuntimeException: CANCELLED: cancelled before receiving half close
	at io.grpc.Status.asRuntimeException(Status.java:524)
	at io.grpc.stub.ServerCalls$StreamingServerCallHandler$StreamingServerCallListener.onCancel(ServerCalls.java:275)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closedInternal(ServerCallImpl.java:353)
	at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.closed(ServerCallImpl.java:341)
	at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1Closed.runInContext(ServerImpl.java:867)
	at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
2022-07-31 14:08:24,123 INFO xds: event Service trigger push.

2022-07-31 14:08:24,123 DEBUG discoveryResponse: version_info: "2022-07-31T14:08:24+08:00/25"
resources {
  type_url: "type.googleapis.com/istio.mcp.v1alpha1.Resource"
  value: "\nb\n/public/istio-demo-consumer.DEFAULT-GROUP.public\022\006\b\230\213\223\227\006\032\00213\"\025\n\fregistryType\022\005nacos*\f\n\avirtual\022\0011\022\341\001\n:type.googleapis.com/istio.networking.v1alpha3.ServiceEntry\022\242\001\n.istio-demo-consumer.DEFAULT-GROUP.public.nacos\032\017\b\240E\022\004HTTP\032\004http \001(\0012[\n\r10.233.78.137\022\t\n\004http\020\240E\032\022\n\acluster\022\aDEFAULT\032)\n\031preserved.register.source\022\fSPRING_CLOUD0\001"
}
resources {
  type_url: "type.googleapis.com/istio.mcp.v1alpha1.Resource"
  value: "\na\n.public/istio-demo-gateway.DEFAULT-GROUP.public\022\006\b\230\213\223\227\006\032\00212\"\025\n\fregistryType\022\005nacos*\f\n\avirtual\022\0011\022\274\002\n:type.googleapis.com/istio.networking.v1alpha3.ServiceEntry\022\375\001\n-istio-demo-gateway.DEFAULT-GROUP.public.nacos\032\017\b\3543\022\004HTTP\032\004http \001(\0012Z\n\f10.233.77.25\022\t\n\004http\020\3543\032\022\n\acluster\022\aDEFAULT\032)\n\031preserved.register.source\022\fSPRING_CLOUD0\0012[\n\r10.233.113.32\022\t\n\004http\020\3543\032\022\n\acluster\022\aDEFAULT\032)\n\031preserved.register.source\022\fSPRING_CLOUD0\001"
}
resources {
  type_url: "type.googleapis.com/istio.mcp.v1alpha1.Resource"
  value: "\nh\n5public/istio-demo-cloud-producer.DEFAULT-GROUP.public\022\006\b\230\213\223\227\006\032\00211\"\025\n\fregistryType\022\005nacos*\f\n\avirtual\022\0011\022\346\001\n:type.googleapis.com/istio.networking.v1alpha3.ServiceEntry\022\247\001\n4istio-demo-cloud-producer.DEFAULT-GROUP.public.nacos\032\017\b\375M\022\004HTTP\032\004http \001(\0012Z\n\f10.233.78.70\022\t\n\004http\020\375M\032\022\n\acluster\022\aDEFAULT\032)\n\031preserved.register.source\022\fSPRING_CLOUD0\001"
}
resources {
  type_url: "type.googleapis.com/istio.mcp.v1alpha1.Resource"
  value: "\n\220\001\n]public/consumers:cn.com.bluemoon.istio.demo.dubbo.service.CustEmpService.DEFAULT-GROUP.public\022\006\b\230\213\223\227\006\032\00228\"\025\n\fregistryType\022\005nacos*\f\n\avirtual\022\0011\022\266\001\n:type.googleapis.com/istio.networking.v1alpha3.ServiceEntry\022x\n\\consumers:cn.com.bluemoon.istio.demo.dubbo.service.CustEmpService.DEFAULT-GROUP.public.nacos\032\024\022\bCONSUMER\032\bconsumer \001(\001"
}
resources {
  type_url: "type.googleapis.com/istio.mcp.v1alpha1.Resource"
  value: "\n\212\001\nWpublic/consumers:cn.com.bluemoon.service.common.service.EmpService.DEFAULT-GROUP.public\022\006\b\230\213\223\227\006\032\00225\"\025\n\fregistryType\022\005nacos*\f\n\avirtual\022\0011\022\223\004\n:type.googleapis.com/istio.networking.v1alpha3.ServiceEntry\022\324\003\nVconsumers:cn.com.bluemoon.service.common.service.EmpService.DEFAULT-GROUP.public.nacos\032\024\022\bCONSUMER\032\bconsumer \001(\0012\337\002\n\f10.233.78.70\022\f\n\bconsumer\020\000\032\022\n\acluster\022\aDEFAULT\032\020\n\004side\022\bconsumer\032\026\n\rdefault.check\022\005false\032\016\n\005dubbo\022\0052.0.2\032\t\n\003pid\022\00210\032\016\n\005check\022\005false\032>\n\tinterface\0221cn.com.bluemoon.service.common.service.EmpService\032\020\n\atimeout\022\00510000\032\021\n\brevision\022\0051.1.7\032\024\n\bprotocol\022\bconsumer\032(\n\vapplication\022\031istio-demo-cloud-producer\032\025\n\bcategory\022\tconsumers\032\032\n\ttimestamp\022\r16591604938590d"
}
type_url: "networking.istio.io/v1alpha3/ServiceEntry"
nonce: "d6a5a7eae43a4ce7b21f6b9c19d9edfa"

```

**Comment by YunWZ** [comment]
```
2022-07-31 13:36:55,705 ERROR xds: sidecar~10.241.72.143~istiod-85f65ddb8-r6wdg.istio-system~istio-system.svc.cluster.local-39 stream error.

2022-07-31 13:36:55,707 ERROR xds: sidecar~10.241.72.160~istiod-85f65ddb8-jvxvl.istio-system~istio-system.svc.cluster.local-38 stream error.
```

Call cancellation can be due to RPC deadline, manual client cancellation, or I/O failures.

Is the status of these two pods normal?

**Comment by jjluUp** [comment]
@YunWZ Probably due to scale down.

does it support dubbo service sync to istio?

**Comment by KomachiSion** [comment]
@SpecialYang

**Comment by yichouchou** [comment]
> @YunWZ Probably due to scale down.
> 
> does it support dubbo service sync to istio?

support，It has been verified by me
