### ISSUE TITLE
Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 

### ISSUE THREAD

**Issue by pengpengno** [alibaba/nacos#8867]
hi community, when is try to   use nacos as  registy Center , nacos return the error as follows 
```

java.lang.IllegalStateException: Failed to register dubbo://192.168.2.235:20891/com.ifx.account.service.AccountService?anyhost=true&application=accountService&background=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.ifx.account.service.AccountService&metadata-type=remote&methods=login,register&pid=17124&release=3.0.5&service-name-mapping=true&side=provider&timestamp=1659516722420 to registry 124.221.168.200:8848, cause: Failed to register dubbo://192.168.2.235:20891/com.ifx.account.service.AccountService?anyhost=true&application=accountService&background=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.ifx.account.service.AccountService&metadata-type=remote&methods=login,register&pid=17124&release=3.0.5&service-name-mapping=true&side=provider&timestamp=1659516722420 to nacos nacos://124.221.168.200:8848/org.apache.dubbo.registry.RegistryService?application=accountService&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&namespace=ifx&pid=17124&qos.enable=false&release=3.0.5, cause: Request nacos server failed: 
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:218) ~[dubbo-registry-api-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.ListenerRegistryWrapper.register(ListenerRegistryWrapper.java:59) ~[dubbo-registry-api-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.integration.RegistryProtocol.register(RegistryProtocol.java:209) ~[dubbo-registry-api-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.integration.RegistryProtocol.export(RegistryProtocol.java:246) ~[dubbo-registry-api-3.0.5.jar:3.0.5]
	at org.apache.dubbo.rpc.protocol.ProtocolListenerWrapper.export(ProtocolListenerWrapper.java:64) ~[dubbo-rpc-api-3.0.5.jar:3.0.5]
	at org.apache.dubbo.qos.protocol.QosProtocolWrapper.export(QosProtocolWrapper.java:74) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.rpc.cluster.filter.ProtocolFilterWrapper.export(ProtocolFilterWrapper.java:58) ~[dubbo-cluster-3.0.5.jar:3.0.5]
	at org.apache.dubbo.rpc.protocol.ProtocolSerializationWrapper.export(ProtocolSerializationWrapper.java:47) ~[dubbo-rpc-api-3.0.5.jar:3.0.5]
	at org.apache.dubbo.rpc.Protocol$Adaptive.export(Protocol$Adaptive.java) ~[dubbo-common-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrl(ServiceConfig.java:638) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.exportRemote(ServiceConfig.java:612) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.exportUrl(ServiceConfig.java:572) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrlsFor1Protocol(ServiceConfig.java:402) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.doExportUrls(ServiceConfig.java:388) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.doExport(ServiceConfig.java:363) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.ServiceConfig.export(ServiceConfig.java:237) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServiceInternal(DefaultModuleDeployer.java:338) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.exportServices(DefaultModuleDeployer.java:310) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.deploy.DefaultModuleDeployer.start(DefaultModuleDeployer.java:142) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onContextRefreshedEvent(DubboDeployApplicationListener.java:108) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:98) ~[dubbo-3.0.5.jar:3.0.5]
	at org.apache.dubbo.config.spring.context.DubboDeployApplicationListener.onApplicationEvent(DubboDeployApplicationListener.java:44) ~[dubbo-3.0.5.jar:3.0.5]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:404) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:361) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:898) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:554) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:758) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:750) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:315) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1237) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226) [spring-boot-2.3.3.RELEASE.jar:2.3.3.RELEASE]
	at com.ifx.account.AccountApplication.main(AccountApplication.java:16) [classes/:na]
Caused by: org.apache.dubbo.rpc.RpcException: Failed to register dubbo://192.168.2.235:20891/com.ifx.account.service.AccountService?anyhost=true&application=accountService&background=false&deprecated=false&dubbo=2.0.2&dynamic=true&generic=false&interface=com.ifx.account.service.AccountService&metadata-type=remote&methods=login,register&pid=17124&release=3.0.5&service-name-mapping=true&side=provider&timestamp=1659516722420 to nacos nacos://124.221.168.200:8848/org.apache.dubbo.registry.RegistryService?application=accountService&dubbo=2.0.2&interface=org.apache.dubbo.registry.RegistryService&namespace=ifx&pid=17124&qos.enable=false&release=3.0.5, cause: Request nacos server failed: 
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:180) ~[dubbo-registry-nacos-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.support.FailbackRegistry.register(FailbackRegistry.java:205) ~[dubbo-registry-api-3.0.5.jar:3.0.5]
	... 36 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:279) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:129) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.registerService(NamingGrpcClientProxy.java:115) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.registerService(NamingClientProxyDelegate.java:95) ~[nacos-client-2.0.3.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.registerInstance(NacosNamingService.java:145) ~[nacos-client-2.0.3.jar:na]
	at org.apache.dubbo.registry.nacos.NacosNamingServiceWrapper.registerInstance(NacosNamingServiceWrapper.java:59) ~[dubbo-registry-nacos-3.0.5.jar:3.0.5]
	at org.apache.dubbo.registry.nacos.NacosRegistry.doRegister(NacosRegistry.java:177) ~[dubbo-registry-nacos-3.0.5.jar:3.0.5]
	... 37 common frames omitted
Caused by: com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:271) ~[nacos-client-2.0.3.jar:na]
	... 43 common frames omitted

```

 is there somethings wrong in nacos 2.0.2 ? or dubbo 3.0.5 
my profile as follows
nacos ；2.0.2
dubbo:3.0.5
springstarter :2.3.3 release

> pom
```
    <properties>
        <dubbo.version>3.0.5</dubbo.version>
        <dubbo.registry.version>3.0.5</dubbo.registry.version>
    </properties>

            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-registry-nacos</artifactId>
                <version>${dubbo.registry.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo-spring-boot-autoconfigure</artifactId>
                <version>${dubbo.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.dubbo</groupId>
                <artifactId>dubbo</artifactId>
                <version>${dubbo.version}</version>
            </dependency>
```
> docker-compose
```
version: '3.7'
services:
  nacos:
    image: nacos/nacos-server:2.0.2
    container_name: ifx-nacos
    env_file:
      - ./config/nacos-config.env
    volumes:
      - ./log/nacos/:/home/nacos/logs
      - ./nacos/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
      - "9849:9849"
      - "9848:9848"
    restart: always

```

->  nacos-config.env 
```
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=
MYSQL_SERVICE_DB_NAME=nacos_config
MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=10000&socketTimeout=30000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
MYSQL_SERVICE_PORT=
MYSQL_SERVICE_USER=
MYSQL_SERVICE_PASSWORD=
JVM_XMS=256m
JVM_XMX=256m
JVM_XMN=256m
NACOS_AUTH_ENABLE=true
NACOS_AUTH_USER_AGENT_AUTH_WHITE_ENABLE=false
NACOS_AUTH_IDENTITY_KEY=
NACOS_AUTH_IDENTITY_VALUE=

```

> application.yaml

```
dubbo:
  application:
    name: accountService
  registry:
    address: nacos://124.221.168.200:8848
    password: nacos
    username: nacos
    parameters:
      namespace: ifx
  protocol:
    port: 20891
    name: dubbo

```

and my nacos is depled by docker  so  i according to nacos offical doc  export grpc port 9848 9849 
but  it seem like useless   ,hope community help ! thanks!
![image](https://user-images.githubusercontent.com/48426117/182569970-f7ba1696-6667-45bc-9ed3-a49f6004c9f9.png)

**Comment by KomachiSion** [comment]
Please see ${user.home}/logs/nacos/naming.log and remote.log found out why request failed.
