### ISSUE TITLE
nacos 三台机子集群正常启动运行一段时间后，出现错误

### ISSUE THREAD

**Issue by shanlongmei** [alibaba/nacos#8931]
OS：linux 
nacos ：2.1.1 

2022-08-10 15:04:27,053 ERROR Fail to compress snapshot, path=/app/soft/nacos/data/protocol/raft/naming_persistent_service_v2/snapshot/temp, file list={}.

java.lang.RuntimeException: Serialized class com.alibaba.nacos.naming.core.v2.pojo.BatchInstanceData must implement java.io.Serializable
 field: com.alibaba.nacos.naming.core.v2.client.ClientSyncData.batchInstanceData
 class: com.alibaba.nacos.naming.core.v2.client.ClientSyncData (object=com.alibaba.nacos.naming.core.v2.client.ClientSyncData@65222f42)
        at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:222)
        at com.caucho.hessian.io.UnsafeSerializer.writeObject(UnsafeSerializer.java:177)
        at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:465)
        at com.caucho.hessian.io.MapSerializer.writeObject(MapSerializer.java:116)
        at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:465)
        at com.alibaba.nacos.consistency.serialize.HessianSerializer.serialize(HessianSerializer.java:83)
        at com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl$PersistentInstanceSnapshotOperation.dumpSnapshot(PersistentClientOperationServiceImpl.java:335)
        at com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl$PersistentInstanceSnapshotOperation.writeSnapshot(PersistentClientOperationServiceImpl.java:305)
        at com.alibaba.nacos.naming.consistency.persistent.impl.AbstractSnapshotOperation.lambda$onSnapshotSave$0(AbstractSnapshotOperation.java:52)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.RuntimeException: Serialized class com.alibaba.nacos.naming.core.v2.pojo.BatchInstanceData must implement java.io.Serializable
 field: com.alibaba.nacos.naming.core.v2.client.ClientSyncData.batchInstanceData
        at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:303)
        at com.caucho.hessian.io.UnsafeSerializer.writeInstance(UnsafeSerializer.java:218)
        ... 11 common frames omitted
Caused by: java.lang.IllegalStateException: Serialized class com.alibaba.nacos.naming.core.v2.pojo.BatchInstanceData must implement java.io.Serializable
        at com.caucho.hessian.io.SerializerFactory.getDefaultSerializer(SerializerFactory.java:387)
        at com.caucho.hessian.io.SerializerFactory.loadSerializer(SerializerFactory.java:368)
        at com.caucho.hessian.io.SerializerFactory.getSerializer(SerializerFactory.java:267)
        at com.caucho.hessian.io.SerializerFactory.getObjectSerializer(SerializerFactory.java:217)
        at com.caucho.hessian.io.Hessian2Output.writeObject(Hessian2Output.java:463)
        at com.caucho.hessian.io.UnsafeSerializer$ObjectFieldSerializer.serialize(UnsafeSerializer.java:299)
        ... 12 common frames omitted

节点元数据：
{
    "lastRefreshTime": 1660125730834,
    "raftMetaData": {
        "metaDataMap": {
            "naming_instance_metadata": {
                "leader": "192.168.10.195:7848",
                "raftGroupMember": [
                    "192.168.10.154:7848",
                    "192.168.10.195:7848",
                    "192.168.10.194:7848"
                ],
                "term": 9
            },
            "naming_persistent_service": {
                "leader": "192.168.10.195:7848",
                "raftGroupMember": [
                    "192.168.10.154:7848",
                    "192.168.10.195:7848",
                    "192.168.10.194:7848"
                ],
                "term": 14
            },
            "naming_persistent_service_v2": {
                "errMsg": "Error [type=ERROR_TYPE_SNAPSHOT, status=Status[EIO<1014>: Fail to save snapshot.]]",
                "leader": "192.168.10.194:7848",
                "raftGroupMember": [
                    "192.168.10.154:7848",
                    "192.168.10.195:7848",
                    "192.168.10.194:7848"
                ],
                "term": 7
            },
            "naming_service_metadata": {
                "leader": "192.168.10.195:7848",
                "raftGroupMember": [
                    "192.168.10.154:7848",
                    "192.168.10.195:7848",
                    "192.168.10.194:7848"
                ],
                "term": 10
            }
        }
    },
    "raftPort": "7848",
    "readyToUpgrade": true,
    "version": "2.1.1"
}

**Comment by wuchubuzai2018** [comment]
@i will solve it@
看错误提示是对象序列化问题，应该上次别人提交的批量实例处理的代码，我提交了一个PR，希望可以被社区合并

**Comment by shanlongmei** [comment]
您好， 看到您的PR已经被采用了。 您看看能否在方便的时候， 发我一个更新好的jar文件 我这边一直没有找到合适的编译环境。 谢谢！

 


shanlongmei
 
发件人： 无处不在
发送时间： 2022-08-11 10:44
收件人： alibaba/nacos
抄送： shanlongmei; Author
主题： Re: [alibaba/nacos] nacos 三台机子集群正常启动运行一段时间后，出现错误 (Issue #8931)
@i will solve it@
看错误提示是对象序列化问题，应该上次别人提交的批量实例处理的代码，我提交了一个PR，希望可以被社区合并

**Comment by wuchubuzai2018** [comment]
> 您好， 看到您的PR已经被采用了。>

你下载源码后，执行打包的命令即可。
mvn -Prelease-nacos -Dmaven.test.skip=true -Dpmd.skip=true -Dcheckstyle.skip=true -Drat.skip=true clean install -U
