### ISSUE TITLE
how can trigger RunningConfig 

### ISSUE THREAD

**Issue by TenYearsIn** [alibaba/nacos#896]
I Run Nacos  in Wildfly 8.1.0.Final as *.war ，It can Compile successfully . but when it rruns，I find RunningConfig 's onApplicationEvent can not be invoked，And  I get below stack information:
Unexpected error occurred in scheduled task.: java.lang.IllegalStateException: unable to find local peer: 10.49.24.10:0, all peers: []
	at com.alibaba.nacos.naming.raft.PeerSet.local(PeerSet.java:191) [nacos-naming-0.8.0.jar:]
	at com.alibaba.nacos.naming.monitor.PerformanceLoggerThread.collectmetrics(PerformanceLoggerThread.java:114) [nacos-naming-0.8.0.jar:]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) [rt.jar:1.8.0_40]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) [rt.jar:1.8.0_40]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) [rt.jar:1.8.0_40]
	at java.lang.reflect.Method.invoke(Method.java:497) [rt.jar:1.8.0_40]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65) [spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) [spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at org.springframework.scheduling.concurrent.ReschedulingRunnable.run(ReschedulingRunnable.java:93) [spring-context-5.0.7.RELEASE.jar:5.0.7.RELEASE]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [rt.jar:1.8.0_40]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [rt.jar:1.8.0_40]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [rt.jar:1.8.0_40]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [rt.jar:1.8.0_40]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [rt.jar:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [rt.jar:1.8.0_40]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [rt.jar:1.8.0_40]
	at java.lang.Thread.run(Thread.java:745) [rt.jar:1.8.0_40]

BackGround：
1、Nacos's version is 0.8.0
2、SpringBoot version is 2.0.3.RELEASE

**Comment by nkorange** [comment]
It's fixed in Nacos 1.0.0
