### ISSUE TITLE
docker 按住nacos启动Failed to bind properties under 'server.tomcat.basedir' to java.io.File:

### ISSUE THREAD

**Issue by jansse-zhao** [alibaba/nacos#8960]
Caused by: org.springframework.core.convert.ConversionFailedException: Failed to convert from type [java.lang.String] to type [java.io.File] for value ''; nested exception is java.lang.IllegalStateException: Could not retrieve file for class path resource []: class path resource [] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/classes!/
        at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:47)
        at org.springframework.core.convert.support.GenericConversionService.convert(GenericConversionService.java:192)
        at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:109)
        at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:100)
        at org.springframework.boot.context.properties.bind.BindConverter.convert(BindConverter.java:92)
        at org.springframework.boot.context.properties.bind.Binder.bindProperty(Binder.java:456)
        at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:400)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:340)
        ... 82 common frames omitted
 Caused by: java.lang.IllegalStateException: Could not retrieve file for class path resource []: class path resource [] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/classes!/
        at org.springframework.boot.convert.StringToFileConverter.getFile(StringToFileConverter.java:59)
        at org.springframework.boot.convert.StringToFileConverter.convert(StringToFileConverter.java:49)
        at org.springframework.boot.convert.StringToFileConverter.convert(StringToFileConverter.java:34)
        at org.springframework.core.convert.support.GenericConversionService$ConverterAdapter.convert(GenericConversionService.java:386)
        at org.springframework.core.convert.support.ConversionUtils.invokeConverter(ConversionUtils.java:41)
        ... 89 common frames omitted
 2022-08-12 16:43:18,350 WARN [WatchFileCenter] start close
 
 2022-08-12 16:43:18,350 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /home/nacos/conf
 
 2022-08-12 16:43:18,350 WARN [WatchFileCenter] already closed
 
 2022-08-12 16:43:18,350 WARN [NotifyCenter] Start destroying Publisher
 
 2022-08-12 16:43:18,350 WARN [NotifyCenter] Destruction of the end
 
 2022-08-12 16:43:18,350 ERROR Nacos failed to start, please see /home/nacos/logs/nacos.log for more details.
 
 2022-08-12 16:43:18,369 INFO 
 
 Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
 
 2022-08-12 16:43:18,418 ERROR 
 
 ***************************
 APPLICATION FAILED TO START
 ***************************
 
 Description:
 
 Failed to bind properties under 'server.tomcat.basedir' to java.io.File:
 
     Property: server.tomcat.basedir
     Value: 
     Origin: InputStream resource [resource loaded through InputStream] - 34:0
     Reason: failed to convert java.lang.String to java.io.File (caused by java.lang.IllegalStateException: Could not retrieve file for class path resource []: class path resource [] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/classes!/)
 
 Action:
 
 Update your application's configuration
配置文件server.tomcat.basedir已经注释了，并且同样的配置在Windows可以启动，在Linux上不成

**Comment by KomachiSion** [comment]
(caused by java.lang.IllegalStateException: Could not retrieve file for class path resource []: class path resource [] cannot be resolved to absolute file path because it does not reside in the file system: jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/classes!/)
 
 这一段可能有些作用， 应该是配置内容上有问题， 我没有复现这个问题。

**Comment by KomachiSion** [comment]
@paderlol 是不是新的docker镜像有问题， 我不使用docker， 直接用release包启动没有这个问题。

**Comment by jansse-zhao** [comment]
这是我的docker nacos启动命令：docker run -p 8848:8848 --restart=always --name nacos88 --privileged=true -e JVM_XMS=256m -e JVM_XMX=256m -e MODE=standalone -e PREFER_HOST_MODE=hostname -v /home/docker_data/nacos/logs:/home/nacos/logs -v /home/docker_data/nacos/application.properties:/home/nacos/init.d/custom.properties -d nacos/nacos-server
这是我的配置截图
![image](https://user-images.githubusercontent.com/22760972/184322673-92e1d43d-6efb-43fb-97b9-6e821bdf77aa.png)

进入docker容器查看配置已经映射进去了

**Comment by onewe** [comment]
server.tomcat.basedir 这个属性不能注释掉, 否则 用 jar 启动方式会报错

**Comment by KomachiSion** [comment]
docker镜像已更新，可以到nacos-docker项目去查看。

**Comment by aaaaai** [comment]
给server.tomcat.basedir赋值一个存在的目录，没再报错
