### ISSUE TITLE
k8s中nacos重启，重启前服务的ip 仍然注册在nacos中，被上游服务获取到后访问失败

### ISSUE THREAD

**Issue by codelearner1024** [alibaba/nacos#8972]
**Describe the bug**
k8s中nacos重启，重启前服务的ip 仍然注册在nacos中，被上游服务获取到后访问失败

**Expected behavior**
k8s服务重启，会生成新的pod ip。nacos注册中心只保留新的ip，旧的ip跟随下线

**Actually behavior**
pod重启前的ip仍在注册中心保存着

<img width="917" alt="image" src="https://user-images.githubusercontent.com/31379137/184841540-7e06648b-2413-439c-95e3-6820177508f5.png">

**Desktop (please complete the following information):**
 - OS: [NAME="CentOS Linux"VERSION="7 (Core)"]
 - Version [nacos-server 1.4.2, nacos-client 1.1.4]
 - SDK [spring-cloud-starter-alibaba-nacos-discovery 2.1.1]

**Comment by onewe** [comment]
30s后自动下线没?

**Comment by codelearner1024** [comment]
> 30s后自动下线没?

没有。不手动删除。就一直不下线

**Comment by zzl14273119** [comment]
我也遇到了这种情况

**Comment by KomachiSion** [comment]
1. 如果注册的是持久化服务，需要手动删除。
2. 如果注册时非持久化服务，且不会自动删除，需要看一下是不是那个pod虽然下了，但是进程还在（大量出现过这个问题，pod没了，但是进程还在node里运行，不停发心跳/保持9848连接）
3. 如果注册时非持久化服务，且不会自动删除，且确认了没有心跳发送/保持连接，那就看一下nacos-server的日志。有没有报错信息。

目前我遇到过的情况均是前面2种。第3种情况几乎没有出现过。

**Comment by codelearner1024** [comment]
> 1. 如果注册的是持久化服务，需要手动删除。
> 2. 如果注册时非持久化服务，且不会自动删除，需要看一下是不是那个pod虽然下了，但是进程还在（大量出现过这个问题，pod没了，但是进程还在node里运行，不停发心跳/保持9848连接）
> 3. 如果注册时非持久化服务，且不会自动删除，且确认了没有心跳发送/保持连接，那就看一下nacos-server的日志。有没有报错信息。
> 
> 目前我遇到过的情况均是前面2种。第3种情况几乎没有出现过。

@KomachiSion @zzl14273119  

我在 容器里面执行源码（1.4.2）逻辑是成功的（旧ip被成功删除，一切恢复正常）： 
curl -X DELETE http://127.0.0.1:8848/nacos/v1/ns/instance?ephemeral=true&serviceName=INTEXPRESS_GROUP@@yl-xxx-customer-api&port=8080&namespaceId=c3245375-0451-46d2-9f13-b0d502f6ec06&ip=10.254.93.168&clusterName=DEFAULT&

但是naming-server.log 的日志中出现了这个：
``` 
2022-08-18 18:13:18,885 ERROR [IP-DEAD] failed to delete ip automatically, ip: {"instanceId":"10.254.102.144#8080#DEFAULT#INTEXPRESS_GROUP@@yl-xxx-customer-api","ip":"10.254.102.144","port":8080,"weight":1.0,"healthy":false,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"INTEXPRESS_GROUP@@yl-xxx-customer-api","metadata":{"management.port":"8070","preserved.register.source":"SPRING_CLOUD"},"lastBeat":1660816252230,"marked":false,"app":"unknown","instanceHeartBeatInterval":5000,"instanceHeartBeatTimeOut":15000,"ipDeleteTimeout":30000}, error: {}

java.lang.IllegalStateException: Request cannot be executed; I/O reactor status: STOPPED
        at org.apache.http.util.Asserts.check(Asserts.java:46)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase.ensureRunning(CloseableHttpAsyncClientBase.java:90)
        at org.apache.http.impl.nio.client.InternalHttpAsyncClient.execute(InternalHttpAsyncClient.java:123)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:75)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:108)
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClient.execute(CloseableHttpAsyncClient.java:92)
        at com.alibaba.nacos.common.http.client.request.DefaultAsyncHttpClientRequest.execute(DefaultAsyncHttpClientRequest.java:52)
        at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.execute(NacosAsyncRestTemplate.java:364)
        at com.alibaba.nacos.common.http.client.NacosAsyncRestTemplate.delete(NacosAsyncRestTemplate.java:105)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpRequest(HttpClient.java:195)
        at com.alibaba.nacos.naming.misc.HttpClient.asyncHttpDelete(HttpClient.java:159)
        at com.alibaba.nacos.naming.healthcheck.ClientBeatCheckTask.deleteIp(ClientBeatCheckTask.java:144)
        at com.alibaba.nacos.naming.healthcheck.ClientBeatCheckTask.run(ClientBeatCheckTask.java:122)

```

所以，目前看来这里的逻辑是不是有问题，需要理一下。
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/31379137/185384427-047e93c7-cba1-483d-acfc-ad146eeb7c33.png">

**Comment by YunWZ** [comment]
在其他nacos节点的**nacos-cluster.log**搜索一下,看看有没有关于“failed to report new info to target node”的信息

**Comment by codelearner1024** [comment]
> 在其他nacos节点的**nacos-cluster.log**搜索一下,看看有没有关于“failed to report new info to target node”的信息

1. 状态我记得是有时构建是不健康。有时候构建完又是健康的。
2. 确实有这个报错。
```
2022-08-18 23:57:34,263 ERROR failed to report new info to target node : nacos-2.nacos-headless.test-xxx.svc.cluster.local.:8848, error : caused: 2,500 milliseconds timeout on connection http-outgoing-233 [ACTIVE];

```

应该是这里挂掉了：
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/31379137/185530158-245cf66b-87dc-4d19-8d67-2d2e8dbd1738.png">

但是什么原因导致了这个线程挂掉就不知道如何确认了，目前的话重启后恢复了。

@YunWZ

**Comment by YunWZ** [comment]
你上面发的**naming-server.log**日志是挂掉的那个nacos节点的么?

**Comment by codelearner1024** [comment]
> 你上面发的**naming-server.log**日志是挂掉的那个nacos节点的么?

nacos节点没有挂，是旧的实例ip还注册在nacos-naming上，控制台能看到，实际gateway网关也拿到了旧的ip，导致请求的时候出错

**Comment by YunWZ** [comment]
找到一个类似的案例:https://issues.apache.org/jira/browse/HTTPASYNC-104

**Comment by KomachiSion** [comment]
可以升级到1.4.4试试看， 我记得有个社区同学修复过类似问题。

**Comment by yugj** [comment]
> 1. 如果注册的是持久化服务，需要手动删除。
> 2. 如果注册时非持久化服务，且不会自动删除，需要看一下是不是那个pod虽然下了，但是进程还在（大量出现过这个问题，pod没了，但是进程还在node里运行，不停发心跳/保持9848连接）
> 3. 如果注册时非持久化服务，且不会自动删除，且确认了没有心跳发送/保持连接，那就看一下nacos-server的日志。有没有报错信息。
> 
> 目前我遇到过的情况均是前面2种。第3种情况几乎没有出现过。

2.0.3 下出现类似问题，过去一天了，节点还在，naming-server 日志只有connect/change 没有remove，是临时节点，并且是开发人员主机（ps 是代码从Eureka那边通过过来的节点 调用namingService.registerInstance 注册的节点）
```
2022-08-23 11:28:10,404 INFO Client connection 192.168.8.109:8080#true connect
2022-08-23 11:28:10,404 INFO Client change for service Service{namespace='xxx', group='DEFAULT_GROUP', name='xxx-service', ephemeral=true, revision=103}, 192.168.8.109:8080#true
```
@KomachiSion 同求思路

**Comment by codelearner1024** [comment]
> 

这个有局限性,配套的spring版本是在整个架构中的,不允许随意改动,如果我的springboot springcloud版本不能动,那我的nacos版本升级也有局限性

**Comment by yugj** [comment]
> > 
> 
> 这个有局限性,配套的spring版本是在整个架构中的,不允许随意改动,如果我的springboot springcloud版本不能动,那我的nacos版本升级也有局限性

据悉client 是兼容的，文档不记得是哪个了

**Comment by codelearner1024** [comment]
> > > 
> > 
> > 
> > 这个有局限性,配套的spring版本是在整个架构中的,不允许随意改动,如果我的springboot springcloud版本不能动,那我的nacos版本升级也有局限性
> 
> 据悉client 是兼容的，文档不记得是哪个了

这么一说貌似，我本地测试都是用的2.0.3 服务端 ，好像也杠杠滴， @yugj   不过太老的client。在有限范围内还是得升一下 不然 那个老版本的 http 通信 就够恶心了

**Comment by KomachiSion** [comment]
> > 1. 如果注册的是持久化服务，需要手动删除。
> > 2. 如果注册时非持久化服务，且不会自动删除，需要看一下是不是那个pod虽然下了，但是进程还在（大量出现过这个问题，pod没了，但是进程还在node里运行，不停发心跳/保持9848连接）
> > 3. 如果注册时非持久化服务，且不会自动删除，且确认了没有心跳发送/保持连接，那就看一下nacos-server的日志。有没有报错信息。
> > 
> > 目前我遇到过的情况均是前面2种。第3种情况几乎没有出现过。
> 
> 2.0.3 下出现类似问题，过去一天了，节点还在，naming-server 日志只有connect/change 没有remove，是临时节点，并且是开发人员主机（ps 是代码从Eureka那边通过过来的节点 调用namingService.registerInstance 注册的节点）
> 
> ```
> 2022-08-23 11:28:10,404 INFO Client connection 192.168.8.109:8080#true connect
> 2022-08-23 11:28:10,404 INFO Client change for service Service{namespace='xxx', group='DEFAULT_GROUP', name='xxx-service', ephemeral=true, revision=103}, 192.168.8.109:8080#true
> ```
> 
> edit：ps，几个月里面大概出现2次，概率比较小 @KomachiSion 同求思路

打开naming-event的debug日志，看下是不是心跳还在发，或者抓包看也可以.

**Comment by KomachiSion** [comment]
No more response from author, I think the version has solve the problem.

**Comment by wangdh1** [comment]
所以，解决的方案是 升级 nacos-server到2.0.3？

**Comment by wsw136** [comment]
> > 你上面发的**naming-server.log**日志是挂掉的那个nacos节点的么?
> 
> nacos节点没有挂，是旧的实例ip还注册在nacos-naming上，控制台能看到，实际gateway网关也拿到了旧的ip，导致请求的时候出错

和我的状况一样，直接影响业务了

**Comment by wsw136** [comment]
> 可以升级到1.4.4试试看， 我记得有个社区同学修复过类似问题。

有url提供一下吗
