### ISSUE TITLE
服务注册异常导致启动阻塞

### ISSUE THREAD

**Issue by ettwz** [alibaba/nacos#8998]
**Describe the bug**
服务滚动更新时注册不上,client端没有心跳日志,server端没有{IP-NEW}日志

**Expected behavior**
服务滚动更新,会自动注册上新实例再将老实例下线.

**Actually behavior**
新pod没有注册心跳日志,main线程启动阻塞,服务启动失败.
在控制台手动将老实例下线再更新可以解决.

**How to Reproduce**
单一环境特定服务会出现此问题,其余环境及服务都没重现.

**Desktop (please complete the following information):**
 - OS: [Centos7.9,Kubernetes v1.21.11]
 - Version [nacos-server 1.4.3, nacos-client 1.4.1]
 - Module [naming]
 - SDK [spring-cloud-alibaba-nacos]

**Additional context**
客户端日志: 左为正常情况, 右为异常情况
<img width="1302" alt="截屏2022-08-19 09 57 16" src="https://user-images.githubusercontent.com/20449556/185528339-62288f1f-6e62-4475-aa87-42bd7aecc215.png">
naming日志: 左为正常情况, 右为异常情况
<img width="1221" alt="截屏2022-08-19 10 27 07" src="https://user-images.githubusercontent.com/20449556/185529563-5f10e802-20b3-4b5a-bc9f-c7813aefc4b4.png">

**Comment by KomachiSion** [comment]
没有注册服务的日志说明你的程序卡在了注册服务之前的动作，建议dump调用栈看下程序的main线程卡在了哪里

**Comment by ettwz** [comment]
没有阻塞和死锁, 完整版在这里

[threadDump.log](https://github.com/alibaba/nacos/files/9392630/threadDump.log)

```
JRE 11 Linux amd64-64-Bit Compressed References 20211022_282 (JIT enabled, AOT enabled)
OpenJ9   - e1e72c497
OMR      - 299b6a2d2
JCL      - 2d83aa3b76 based on jdk-11.0.13+8

"main" prio=5 Id=1 RUNNABLE
	at java.base@11.0.13/sun.nio.ch.FileDispatcherImpl.lock0(Native Method)
	at java.base@11.0.13/sun.nio.ch.FileDispatcherImpl.lock(FileDispatcherImpl.java:96)
	at java.base@11.0.13/sun.nio.ch.FileChannelImpl.tryLock(FileChannelImpl.java:1161)
	at java.base@11.0.13/java.nio.channels.FileChannel.tryLock(FileChannel.java:1165)
	at com.alibaba.nacos.client.naming.cache.ConcurrentDiskUtil.writeFileContent(ConcurrentDiskUtil.java:136)
	at com.alibaba.nacos.client.naming.cache.DiskCache.write(DiskCache.java:75)
	at com.alibaba.nacos.client.naming.core.HostReactor.processServiceJson(HostReactor.java:250)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:381)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:341)
	at com.alibaba.nacos.client.naming.core.HostReactor.getServiceInfo(HostReactor.java:316)
	at com.alibaba.nacos.client.naming.core.HostReactor.subscribe(HostReactor.java:139)
	at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:457)
	at com.alibaba.cloud.nacos.discovery.NacosWatch.start(NacosWatch.java:123)
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178)
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54)
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356)
	at <unknown class>.accept(Unknown Source)
	at java.base@11.0.13/java.lang.Iterable.forEach(Iterable.java:75)
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155)
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123)
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586)
	- locked java.lang.Object@53cd5292
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:775)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:448)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:339)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354)
	at com.lenovo.cloud.backup.BackupApplication.main(BackupApplication.java:13)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base@11.0.13/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base@11.0.13/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base@11.0.13/java.lang.reflect.Method.invoke(Method.java:566)
	at app//org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at app//org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at app//org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at app//org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)

	Locked ownable synchronizers: 0
```

**Comment by KomachiSion** [comment]
这不是卡在获取文件锁了吗？ 说明文件系统有问题，写不进去数据。

**Comment by ettwz** [comment]
锁的是naming的缓存文件

```
[root@localhost pi-dev]# ls -li dev%40%40pi-backup@@DEFAULT
1610613301 -rw-r--r-- 1 33 tape 590 Aug 16 10:24 dev%40%40pi-backup@@DEFAULT
[root@localhost pi-dev]# cat /proc/locks | grep 1610613301
14: POSIX  ADVISORY  WRITE 2563 fd:02:1610613301 0 EOF
[root@localhost pi-dev]# ps -p 2563
  PID TTY          TIME CMD
 2563 ?        3-22:24:30 lockd
```

不带`@@DEFAULT`后缀的缓存文件状态是正常的

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
