### ISSUE TITLE
nacos 2.0.3 server-addr  support ipv6?

### ISSUE THREAD

**Issue by wxjin** [alibaba/nacos#9031]
version: spring-cloud-starter-alibaba-nacos-discovery 2.2.8.RELEASE
spring.cloud.nacos.discovery.server-addr=[fe80::35ba:6822:c5fe:d161%11]:8848

connect fail:
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:288) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:229) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:214) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:147) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:393) ~[nacos-client-2.1.0.jar:na]

**Comment by KomachiSion** [comment]
supported I think, what's the full error information?

**Comment by wxjin** [comment]
> supported I think, what's the full error information?

full error information 

2022-08-25 17:27:44.269 ERROR 24636 --- [           main] c.a.cloud.nacos.discovery.NacosWatch     : namingService subscribe failed, properties:NacosDiscoveryProperties{serverAddr='[fe80::35ba:6822:c5ff:d161%11]:8848', endpoint='', namespace='6a3cda73-1e13-4ef9-b018-3be63327a39d', watchDelay=30000, logName='', service='emdp-ftp', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={preserved.register.source=SPRING_CLOUD}, registerEnabled=true, ip='172.19.66.99', networkInterface='', port=-1, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null, failFast=true}

com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:288) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:229) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:214) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:147) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:393) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.cloud.nacos.discovery.NacosWatch.start(NacosWatch.java:134) ~[spring-cloud-starter-alibaba-nacos-discovery-2.2.8.RELEASE.jar:2.2.8.RELEASE]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) [spring-context-5.3.15.jar:5.3.15]
	at java.lang.Iterable.forEach(Unknown Source) ~[na:1.8.0_171]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) [spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.15.jar:5.3.15]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:414) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:302) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1303) ~[spring-boot-2.6.3.jar:2.6.3]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1292) ~[spring-boot-2.6.3.jar:2.6.3]
	at com.cmcc.emdp.EmdpFtpApplication.main(EmdpFtpApplication.java:24) ~[classes/:na]
Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:651) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:631) ~[nacos-client-2.1.0.jar:na]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:278) ~[nacos-client-2.1.0.jar:na]
	... 20 common frames omitted

**Comment by KomachiSion** [comment]
maybe your 9848 port not open. Please see document to find which ports need to open

**Comment by wxjin** [comment]
> 

why need 9848? I make sure port 8848 is open and use ipv4 is normal.
And is there the document with nacos using ipv6 ?

**Comment by KomachiSion** [comment]
nacos need 9848 port, If you use ipv4 can work. means 9848 port has open.

nacos use grpc as connections,  and grpc support ipv6.

Your error is that client can't connect to server with grpc. You should check ${user.home}/logs/nacos/remote.log to see why can't connect.

**Comment by KomachiSion** [comment]
No more response from author, I think this maybe a env problem.
If some one cause this problem also, please submit new issue and provide ${user.home}/logs/nacos/remote.log

**Comment by wxjin** [comment]
> 
the romote log such as:


2022-09-22 17:08:38.345 ERROR [main :c.a.n.c.r.client] Send request fail, request = SubscribeServiceRequest{headers={accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJuYWNvcyIsImV4cCI6MTY2Mzg1NTcxOH0.hUA0fr3TeBvgTp2vylSqz3eyOUX8HT1ybFYRbCPk_NE, app=unknown}, requestId='null'}, retryTimes = 0, errorMessage = Client not connected, current status:STARTING
2022-09-22 17:08:38.347 ERROR [com.alibaba.nacos.client.remote.worker:c.a.n.c.r.c.g.GrpcClient] [f6eff33b-2938-485a-81ab-43a01d95c913]Fail to connect to server!,error={}
java.lang.IllegalArgumentException: Invalid host or port: [2409 9848
	at com.alibaba.nacos.shaded.io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:488) ~[nacos-client-2.1.0.jar!/:na]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:133) ~[nacos-client-2.1.0.jar!/:na]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:119) ~[nacos-client-2.1.0.jar!/:na]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37) ~[nacos-client-2.1.0.jar!/:na]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23) ~[nacos-client-2.1.0.jar!/:na]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39) ~[nacos-client-2.1.0.jar!/:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewChannelStub(GrpcClient.java:143) ~[nacos-client-2.1.0.jar!/:na]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:299) ~[nacos-client-2.1.0.jar!/:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:521) [nacos-client-2.1.0.jar!/:na]
	at com.alibaba.nacos.common.remote.client.RpcClient.lambda$start$2(RpcClient.java:369) [nacos-client-2.1.0.jar!/:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_261]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_261]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) ~[na:1.8.0_261]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) ~[na:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_261]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_261]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_261]
Caused by: java.net.URISyntaxException: Expected closing bracket for IPv6 address at index 12: //[2409:9848
	at java.net.URI$Parser.fail(URI.java:2847) ~[na:1.8.0_261]
	at java.net.URI$Parser.failExpecting(URI.java:2853) ~[na:1.8.0_261]
	at java.net.URI$Parser.parseServer(URI.java:3230) ~[na:1.8.0_261]
	at java.net.URI$Parser.parseAuthority(URI.java:3154) ~[na:1.8.0_261]
	at java.net.URI$Parser.parseHierarchical(URI.java:3096) ~[na:1.8.0_261]
	at java.net.URI$Parser.parse(URI.java:3062) ~[na:1.8.0_261]
	at java.net.URI.<init>(URI.java:673) ~[na:1.8.0_261]
	at com.alibaba.nacos.shaded.io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:486) ~[nacos-client-2.1.0.jar!/:na]
	... 16 common frames omitted
