### ISSUE TITLE
nacos.xsd获取不到，导致低版本的spring环境中，无法用xml配置的方式引入nacos

### ISSUE THREAD

**Issue by wangk-c** [alibaba/nacos#9092]
**Describe the bug**
http://nacos.io/schema/nacos.xsd无法访问，导致低版本的spring环境中，无法用xml配置的方式引入nacos

**Expected behavior**
因为项目spring版本太老，没办法用注解方式，所以请给出xml配置的解决方案。

**Actually behavior**
启动报错，详细堆栈信息为：
Caused by: org.xml.sax.SAXParseException; systemId: http://nacos.io/schema/nacos.xsd; lineNumber: 2; columnNumber: 35; s4s-elt-character: 方案元素中不允许出现除 'xs:appinfo' 和 'xs:documentation' 之外的非空格字符。发现了 '301 Moved Permanently'。
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.error(ErrorHandlerWrapper.java:134)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:396)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.characters(SchemaDOMParser.java:198)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:455)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:629)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaParsingConfig.parse(SchemaParsingConfig.java:685)
	at com.sun.org.apache.xerces.internal.impl.xs.opti.SchemaDOMParser.parse(SchemaDOMParser.java:530)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.getSchemaDocument(XSDHandler.java:2179)
	at com.sun.org.apache.xerces.internal.impl.xs.traversers.XSDHandler.parseSchema(XSDHandler.java:576)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaLoader.loadSchema(XMLSchemaLoader.java:613)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.findSchemaGrammar(XMLSchemaValidator.java:2446)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.handleStartElement(XMLSchemaValidator.java:1767)
	at com.sun.org.apache.xerces.internal.impl.xs.XMLSchemaValidator.startElement(XMLSchemaValidator.java:740)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.scanStartElement(XMLNSDocumentScannerImpl.java:374)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2784)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:602)
	at com.sun.org.apache.xerces.internal.impl.XMLNSDocumentScannerImpl.next(XMLNSDocumentScannerImpl.java:112)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:505)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:841)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:770)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.DOMParser.parse(DOMParser.java:243)
	at com.sun.org.apache.xerces.internal.jaxp.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:339)
	at org.springframework.beans.factory.xml.DefaultDocumentLoader.loadDocument(DefaultDocumentLoader.java:75)
	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:389)
	... 29 more

**How to Reproduce**
参照https://blog.csdn.net/u013696581/article/details/107367926/ 中 3、springMVC项目中章节nacos.xml的做法

**Desktop (please complete the following information):**
 - OS: windows
 - Version [nacos-client 1.4.1 nacos-spring-context 1.1.1]

**Comment by wuchubuzai2018** [comment]
1、正常情况下导入了nacos-spring-context的依赖包后，声明XML的方式，jar包里面的spring.schemas会IDEA和环境去加载到，从而解析内容，下面的地址是nacos去xsd映射了真实的地址。
https://github.com/nacos-group/nacos-spring-project/blob/develop/nacos-spring-context/src/main/resources/META-INF/spring.schemas
2、但是，如果你的开发环境是eclipse好像就有问题，eclipse通常看到xml中的地址后，先去访问远程的xsd地址，然后下载下来。
为了能让eclipse环境好使，可以手动下载下那个xsd文件，然后添加到eclipse的配置中:
https://blog.csdn.net/zhangzhanbin/article/details/116565324
3、如果自己想扩展xml标签元素，在xsd增加内容即可

**Comment by KomachiSion** [comment]
是旧版本spring的问题吗？ 如果是的社区应该不会继续适配，旧版本spring由于spring本身已经结束其生命周期不在维护，nacos社区应该不会去适配已经不维护的版本了。

**Comment by wangk-c** [comment]
> 

非常感谢您的及时回复，原因找到了，因为我的是osgi环境，存在多个类加载器，由于nacos-spring-context没有被我预先加载所以无法进行本地的xsd校验，于是去远程校验了，而远程url又访问不到，所以报错。我把nacos-spring-context设置成预先加载后就解决了。

**Comment by wangk-c** [comment]
> 1、正常情况下导入了nacos-spring-context的依赖包后，声明XML的方式，jar包里面的spring.schemas会IDEA和环境去加载到，从而解析内容，下面的地址是nacos去xsd映射了真实的地址。 https://github.com/nacos-group/nacos-spring-project/blob/develop/nacos-spring-context/src/main/resources/META-INF/spring.schemas 2、但是，如果你的开发环境是eclipse好像就有问题，eclipse通常看到xml中的地址后，先去访问远程的xsd地址，然后下载下来。 为了能让eclipse环境好使，可以手动下载下那个xsd文件，然后添加到eclipse的配置中: https://blog.csdn.net/zhangzhanbin/article/details/116565324 3、如果自己想扩展xml标签元素，在xsd增加内容即可

非常感谢您的及时回复，原因找到了，因为我的是osgi环境，存在多个类加载器，由于nacos-spring-context没有被我预先加载所以无法进行本地的xsd校验，于是去远程校验了，而远程url又访问不到，所以报错。我把nacos-spring-context设置成预先加载后就解决了。

**Comment by wangk-c** [comment]
> 是旧版本spring的问题吗？ 如果是的社区应该不会继续适配，旧版本spring由于spring本身已经结束其生命周期不在维护，nacos社区应该不会去适配已经不维护的版本了。

非常感谢您的及时回复，原因找到了，因为我的是osgi环境，存在多个类加载器，由于nacos-spring-context没有被我预先加载所以无法进行本地的xsd校验，于是去远程校验了，而远程url又访问不到，所以报错。我把nacos-spring-context设置成预先加载后就解决了。
