### ISSUE TITLE
nacos 2.1.1 run error: Unexpected end of file from server

### ISSUE THREAD

**Issue by YangKGcsdms** [alibaba/nacos#9164]
<img width="1245" alt="image" src="https://user-images.githubusercontent.com/67580387/190839996-5342937d-23ca-4494-a366-f3e9bc97d455.png">

As show this picture.
When I download nacos code and run it, it always prompts this error. Does anyone tell me what this url is for? Or how to avoid this error and successfully start nacos.

**Comment by YangKGcsdms** [comment]
Error message
Caused by: java.net.SocketException: Unexpected end of file from server
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:855)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:852)
	at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:678)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1596)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1501)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at com.alibaba.nacos.common.http.client.response.JdkHttpClientResponse.getStatusCode(JdkHttpClientResponse.java:79)
	at com.alibaba.nacos.common.http.client.handler.AbstractResponseHandler.handle(AbstractResponseHandler.java:43)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:483)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.get(NacosRestTemplate.java:72)
	at com.alibaba.nacos.core.cluster.lookup.AddressServerMemberLookup.syncFromAddressUrl(AddressServerMemberLookup.java:175)
	at com.alibaba.nacos.core.cluster.lookup.AddressServerMemberLookup.run(AddressServerMemberLookup.java:143)
	... 117 common frames omitted

**Comment by KomachiSion** [comment]
Please set your `cluster.conf` in nacos/conf.  or deploy address server.
