### ISSUE TITLE
nacos 增加用户认证功能对命名空间的要求

### ISSUE THREAD

**Issue by hillbun** [alibaba/nacos#9201]
nacos 增加用户认证功能后，是不是只有nacos用户可以访问public这个命名空间。其他用户哪怕授权对public命名空间有读写权限
应用也会认证报错？

**Comment by KomachiSion** [comment]
只要授权，其他用户也可以访问public。看一下具体的操作文档进行一下授权试试。

**Comment by hillbun** [comment]
用户授权以后，通过NACOS管理界面可以访问public这个命名空间
但是JAVA应用启动的时候，非nacos用户会提示认证失败，配置namespace到其他命名空间就能够正常启动

配置nacos用户就没有这个问题

**Comment by hillbun** [comment]
```
2022-09-26 10:10:16.566 ERROR 7 --- [ing.grpc.redo.0] com.alibaba.nacos.client.naming          : Redo instance operation REGISTER for DEFAULT_GROUP@@xxxxxxx failed. 

com.alibaba.nacos.api.exception.NacosException: authorization failed!
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:306) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doRegisterService(NamingGrpcClientProxy.java:154) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.processRegisterRedoType(RedoScheduledTask.java:102) [nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForInstance(RedoScheduledTask.java:79) [nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.redoForInstances(RedoScheduledTask.java:61) [nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.redo.RedoScheduledTask.run(RedoScheduledTask.java:51) [nacos-client-2.1.1.jar!/:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_272]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_272]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_272]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_272]
```

**Comment by hillbun** [comment]
而public这个命名空间，是没有namespace id的，所以不知道 springboot 的配置文件中，namespace应该填写什么？

而配置为nacos用户的话，springboot 的配置文件中不需要指定namespace，主动识别为public ，而且能够正常读取。

**Comment by hillbun** [comment]
而public这个命名空间，是没有namespace id的，所以不知道 springboot 的配置文件中，namespace应该填写什么？

而配置为nacos用户的话，springboot 的配置文件中不需要指定namespace，主动识别为public ，而且能够正常读取。

**Comment by hillbun** [comment]
而public这个命名空间，是没有namespace id的，所以不知道 springboot 的配置文件中，namespace应该填写什么？

而配置为nacos用户的话，springboot 的配置文件中不需要指定namespace，主动识别为public ，而且能够正常读取。

**Comment by hillbun** [comment]
通过 curl 命令访问接口的话，无论 tenant= 还是 tenant=public 传参，都能够成功返回配置文件结果
而springboot的配置文件中，无论 namespace 配置为空置还是public  都返回错误

2022-09-26 10:10:16.566 ERROR 7 --- [ing.grpc.redo.0] com.alibaba.nacos.client.naming          : Redo instance operation REGISTER for DEFAULT_GROUP@@xxxxxxx failed. 

com.alibaba.nacos.api.exception.NacosException: authorization failed!

**Comment by hillbun** [comment]
```xml
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.1.1</version>
        </dependency>
```

这个是客户端版本

**Comment by hillbun** [comment]
```xml
        <dependency>
            <groupId>com.alibaba.nacos</groupId>
            <artifactId>nacos-client</artifactId>
            <version>2.1.1</version>
        </dependency>
```

这个是客户端版本

**Comment by Daydreamer-ia** [comment]
我本地测试一切正常，版本都是2.1.1

**Comment by hillbun** [comment]
下面的配置文件用nacos账号可以成功注册到public命名空间

```
    nacos:
      config:
        enabled: true
        server-addr: nacos-cs:8848
        username: nacos
        password: nacos
        file-extension: yaml
        shared-configs[0]:
          dataId: xxx.yaml
          refresh: true
      discovery:
        enabled: true
        register-enabled: true
        server-addr: nacos-cs:8848
        username: nacos
        password: nacos
```

但是用 abc 这个账号的话，就注册失败。  这个账号通过控制台界面，是可以成功访问public这个命名空间的

```
    nacos:
      config:
        enabled: true
        server-addr: nacos-cs:8848
        username: abc
        password: abc-passwd
        file-extension: yaml
        shared-configs[0]:
          dataId: xxx.yaml
          refresh: true
      discovery:
        enabled: true
        register-enabled: true
        server-addr: nacos-cs:8848
        username: abc
        password: abc-passwd
```

错误日志：

```
2022-09-28 09:58:05.239 ERROR 7 --- [event-scheduler] c.a.c.n.discovery.NacosDiscoveryClient   : get service name from nacos server fail,

com.alibaba.nacos.api.exception.NacosException: authorization failed!
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:306) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.getServiceList(NamingGrpcClientProxy.java:227) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.getServiceList(NamingClientProxyDelegate.java:149) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:451) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:439) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.cloud.nacos.discovery.NacosServiceDiscovery.getServices(NacosServiceDiscovery.java:69) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar!/:2021.1]
        at com.alibaba.cloud.nacos.discovery.NacosDiscoveryClient.getServices(NacosDiscoveryClient.java:67) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar!/:2021.1]
        at org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient.getServices(CompositeDiscoveryClient.java:67) [spring-cloud-commons-3.0.3.jar!/:3.0.3]
        at com.tcl.register.event.listener.AbstractEventListener$PollTask.run(AbstractEventListener.java:87) [tcl-starter-register-event-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_272]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_272]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_272]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_272]
```

```
2022-09-28 09:58:13.909  INFO 7 --- [           main] com.alibaba.nacos.client.naming          : [SUBSCRIBE-SERVICE] service:tct-techcore-thirdparty-idc, group:DEFAULT_GROUP, clusters:DEFAULT 
2022-09-28 09:58:13.970 ERROR 7 --- [           main] c.a.cloud.nacos.discovery.NacosWatch     : namingService subscribe failed, properties:NacosDiscoveryProperties{serverAddr='nacos-cs.nacos-v211:8848', endpoint='', namespace='', watchDelay=30000, logName='', service='tct-techcore-thirdparty-idc', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={async.export.endpoint=/async-export-endpoint, VERSION=1.0.0, management.port=8080, preserved.register.source=SPRING_CLOUD, CONTEXT=/tct-techcore-thirdparty-idc}, registerEnabled=true, ip='10.201.164.181', networkInterface='', port=-1, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null}

com.alibaba.nacos.api.exception.NacosException: authorization failed!
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:306) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:255) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:240) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:160) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:404) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.cloud.nacos.discovery.NacosWatch.start(NacosWatch.java:123) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar!/:2021.1]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) [spring-context-5.3.7.jar!/:5.3.7]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_272]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:763) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at tct.tbox.ddd.techcore.thirdparty.idc.Application.main(Application.java:37) ~[classes!/:2.0.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_272]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_272]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_272]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_272]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:2.0.0-SNAPSHOT]
```


配置到其他非public的命名空间，就正常

**Comment by hillbun** [comment]
下面的配置文件用nacos账号可以成功注册到public命名空间

```
    nacos:
      config:
        enabled: true
        server-addr: nacos-cs:8848
        username: nacos
        password: nacos
        file-extension: yaml
        shared-configs[0]:
          dataId: xxx.yaml
          refresh: true
      discovery:
        enabled: true
        register-enabled: true
        server-addr: nacos-cs:8848
        username: nacos
        password: nacos
```

但是用 abc 这个账号的话，就注册失败。  这个账号通过控制台界面，是可以成功访问public这个命名空间的

```
    nacos:
      config:
        enabled: true
        server-addr: nacos-cs:8848
        username: abc
        password: abc-passwd
        file-extension: yaml
        shared-configs[0]:
          dataId: xxx.yaml
          refresh: true
      discovery:
        enabled: true
        register-enabled: true
        server-addr: nacos-cs:8848
        username: abc
        password: abc-passwd
```

错误日志：

```
2022-09-28 09:58:05.239 ERROR 7 --- [event-scheduler] c.a.c.n.discovery.NacosDiscoveryClient   : get service name from nacos server fail,

com.alibaba.nacos.api.exception.NacosException: authorization failed!
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:306) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.getServiceList(NamingGrpcClientProxy.java:227) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.getServiceList(NamingClientProxyDelegate.java:149) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:451) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:439) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.cloud.nacos.discovery.NacosServiceDiscovery.getServices(NacosServiceDiscovery.java:69) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar!/:2021.1]
        at com.alibaba.cloud.nacos.discovery.NacosDiscoveryClient.getServices(NacosDiscoveryClient.java:67) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar!/:2021.1]
        at org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient.getServices(CompositeDiscoveryClient.java:67) [spring-cloud-commons-3.0.3.jar!/:3.0.3]
        at com.tcl.register.event.listener.AbstractEventListener$PollTask.run(AbstractEventListener.java:87) [tcl-starter-register-event-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_272]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_272]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_272]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_272]
```

```
2022-09-28 09:58:13.909  INFO 7 --- [           main] com.alibaba.nacos.client.naming          : [SUBSCRIBE-SERVICE] service:tct-techcore-thirdparty-idc, group:DEFAULT_GROUP, clusters:DEFAULT 
2022-09-28 09:58:13.970 ERROR 7 --- [           main] c.a.cloud.nacos.discovery.NacosWatch     : namingService subscribe failed, properties:NacosDiscoveryProperties{serverAddr='nacos-cs.nacos-v211:8848', endpoint='', namespace='', watchDelay=30000, logName='', service='tct-techcore-thirdparty-idc', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={async.export.endpoint=/async-export-endpoint, VERSION=1.0.0, management.port=8080, preserved.register.source=SPRING_CLOUD, CONTEXT=/tct-techcore-thirdparty-idc}, registerEnabled=true, ip='10.201.164.181', networkInterface='', port=-1, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null}

com.alibaba.nacos.api.exception.NacosException: authorization failed!
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:306) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:255) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:240) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:160) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:404) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.cloud.nacos.discovery.NacosWatch.start(NacosWatch.java:123) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar!/:2021.1]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) [spring-context-5.3.7.jar!/:5.3.7]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_272]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:763) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at tct.tbox.ddd.techcore.thirdparty.idc.Application.main(Application.java:37) ~[classes!/:2.0.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_272]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_272]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_272]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_272]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:2.0.0-SNAPSHOT]
```


配置到其他非public的命名空间，就正常

**Comment by hillbun** [comment]
下面的配置文件用nacos账号可以成功注册到public命名空间

```
    nacos:
      config:
        enabled: true
        server-addr: nacos-cs:8848
        username: nacos
        password: nacos
        file-extension: yaml
        shared-configs[0]:
          dataId: xxx.yaml
          refresh: true
      discovery:
        enabled: true
        register-enabled: true
        server-addr: nacos-cs:8848
        username: nacos
        password: nacos
```

但是用 abc 这个账号的话，就注册失败。  这个账号通过控制台界面，是可以成功访问public这个命名空间的

```
    nacos:
      config:
        enabled: true
        server-addr: nacos-cs:8848
        username: abc
        password: abc-passwd
        file-extension: yaml
        shared-configs[0]:
          dataId: xxx.yaml
          refresh: true
      discovery:
        enabled: true
        register-enabled: true
        server-addr: nacos-cs:8848
        username: abc
        password: abc-passwd
```

错误日志：

```
2022-09-28 09:58:05.239 ERROR 7 --- [event-scheduler] c.a.c.n.discovery.NacosDiscoveryClient   : get service name from nacos server fail,

com.alibaba.nacos.api.exception.NacosException: authorization failed!
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:306) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.getServiceList(NamingGrpcClientProxy.java:227) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.getServiceList(NamingClientProxyDelegate.java:149) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:451) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.getServicesOfServer(NacosNamingService.java:439) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.cloud.nacos.discovery.NacosServiceDiscovery.getServices(NacosServiceDiscovery.java:69) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar!/:2021.1]
        at com.alibaba.cloud.nacos.discovery.NacosDiscoveryClient.getServices(NacosDiscoveryClient.java:67) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar!/:2021.1]
        at org.springframework.cloud.client.discovery.composite.CompositeDiscoveryClient.getServices(CompositeDiscoveryClient.java:67) [spring-cloud-commons-3.0.3.jar!/:3.0.3]
        at com.tcl.register.event.listener.AbstractEventListener$PollTask.run(AbstractEventListener.java:87) [tcl-starter-register-event-1.0.0-SNAPSHOT.jar!/:1.0.0-SNAPSHOT]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_272]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_272]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_272]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_272]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_272]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_272]
```

```
2022-09-28 09:58:13.909  INFO 7 --- [           main] com.alibaba.nacos.client.naming          : [SUBSCRIBE-SERVICE] service:tct-techcore-thirdparty-idc, group:DEFAULT_GROUP, clusters:DEFAULT 
2022-09-28 09:58:13.970 ERROR 7 --- [           main] c.a.cloud.nacos.discovery.NacosWatch     : namingService subscribe failed, properties:NacosDiscoveryProperties{serverAddr='nacos-cs.nacos-v211:8848', endpoint='', namespace='', watchDelay=30000, logName='', service='tct-techcore-thirdparty-idc', weight=1.0, clusterName='DEFAULT', group='DEFAULT_GROUP', namingLoadCacheAtStart='false', metadata={async.export.endpoint=/async-export-endpoint, VERSION=1.0.0, management.port=8080, preserved.register.source=SPRING_CLOUD, CONTEXT=/tct-techcore-thirdparty-idc}, registerEnabled=true, ip='10.201.164.181', networkInterface='', port=-1, secure=false, accessKey='', secretKey='', heartBeatInterval=null, heartBeatTimeout=null, ipDeleteTimeout=null}

com.alibaba.nacos.api.exception.NacosException: authorization failed!
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:306) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:255) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:240) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:160) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.nacos.client.naming.NacosNamingService.subscribe(NacosNamingService.java:404) ~[nacos-client-2.1.1.jar!/:na]
        at com.alibaba.cloud.nacos.discovery.NacosWatch.start(NacosWatch.java:123) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar!/:2021.1]
        at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) [spring-context-5.3.7.jar!/:5.3.7]
        at java.lang.Iterable.forEach(Iterable.java:75) ~[na:1.8.0_272]
        at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) [spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.7.jar!/:5.3.7]
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:144) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:771) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:763) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:438) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:339) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1329) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1318) ~[spring-boot-2.4.6.jar!/:2.4.6]
        at tct.tbox.ddd.techcore.thirdparty.idc.Application.main(Application.java:37) ~[classes!/:2.0.0-SNAPSHOT]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_272]
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_272]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_272]
        at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_272]
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:2.0.0-SNAPSHOT]
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:2.0.0-SNAPSHOT]
```


配置到其他非public的命名空间，就正常

**Comment by KomachiSion** [comment]
maybe duplicate with https://github.com/alibaba/nacos/issues/3525

**Comment by hillbun** [comment]
我在配置文件没有配置namespace， 而且在控制台可以正常访问public ns

```
nacos:
      config:
        enabled: true
        server-addr: nacos-cs:8848
        username: abc
        password: abc-passwd
        file-extension: yaml
        shared-configs[0]:
          dataId: xxx.yaml
          refresh: true
      discovery:
        enabled: true
        register-enabled: true
        server-addr: nacos-cs:8848
        username: abc
        password: abc-passwd
```

**Comment by hillbun** [comment]
需要进行什么额外配置吗

**Comment by KomachiSion** [comment]
先看是否是上述issue中的问题， 是的话可以先不使用默认命名空间， 或者到数据库中添加一个权限临时修复。

**Comment by hillbun** [comment]
通过修改数据库权限表解决了

需要如何根本解决？    等NACOS升级吗？

**Comment by KomachiSion** [comment]
> maybe duplicate with #3525

depend this issue, or not use public namespace.

**Comment by huangqy17** [comment]
这个问题解决了吗
