### ISSUE TITLE
Nacos support IPv6

### ISSUE THREAD

**Issue by HHoflittlefish777** [alibaba/nacos#9209]
Hi,I come from Spring Cloud alibaba,we have support register  IPv6 in nacos in new version, but nacos Server can't support IPv6 , I would like to support this function.

**Comment by KomachiSion** [comment]
I think nacos can support IPV6, Nacos has no perceive for the IP station, only use HTTP or Grpc to transport and connect.

**Comment by HHoflittlefish777** [comment]
you can refer this:https://github.com/alibaba/spring-cloud-alibaba/issues/2740
spring.cloud.nacos.discovery.server-addr=[fe80::35ba:6827:c5ff:d161%11]:8848 it will be error

**Comment by KomachiSion** [comment]
Is the error information same as #9269

**Comment by KomachiSion** [comment]
Move to https://github.com/alibaba/nacos/issues/9269

**Comment by pingdone** [comment]
i use nacos-server-2.1.2.tar.gz package start with standalone  show same error，but use ipv4 is ok.

` cloud:
    nacos:
      discovery:
        ip-type: IPv6
        server-addr: "[fe80::692c:85d7:d1aa:3208]:8848"
      config:
        ip-type: IPv6
        server-addr: "[fe80::692c:85d7:d1aa:3208]:8848"
        file-extension: yml
        shared-configs:
          - application-${spring.profiles.active}.${spring.cloud.nacos.config.file-extension}`
 
Down is error info:
`
java.lang.IllegalArgumentException: Invalid host or port: [fe80 9848
	at com.alibaba.nacos.shaded.io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:481)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:123)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:109)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)

Caused by: java.net.URISyntaxException: Expected closing bracket for IPv6 address at index 12: //[fe80:9848
	at java.base/java.net.URI$Parser.fail(URI.java:2913)
17:38:06.901 [main] ERROR c.a.n.c.r.c.g.GrpcClient - [connectToServer,295] - [67d5411c-0069-4b09-8afc-feab334d22b6_config-0]Fail to connect to server!,error={}

java.lang.IllegalArgumentException: Invalid host or port: [fe80 9848
	at com.alibaba.nacos.shaded.io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:481)

java.lang.IllegalArgumentException: Invalid host or port: [fe80 9848
	at com.alibaba.nacos.shaded.io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:481)
`
