### ISSUE TITLE
nacos v2.1.1集群模式IPV6环境部署，服务节点无法同步到其他nacos实例

### ISSUE THREAD

**Issue by wangzz-a** [alibaba/nacos#9234]
环境：
nacos v2.1.1版本
jdk11
nacos3台机器集群
异常描述：
nacos集群模式启动成功，控制台页面也可以正常访问，配置也能正常修改。但是服务注册到一个nacos实例，且长时间没有同步到其他两个实例，ipv4模式下可以正常同步，请问应该如何解决此问题，谢谢
-----------------------------------------
Environmental Science:
Nacos v2.1.1
jdk11
Three machine clusters of nacos
Exception description:
The nacos cluster mode starts successfully. The console page can also be accessed normally, and the configuration can also be modified normally. However, the service is registered to a nacos instance and has not synchronized to the other two instances for a long time. The service can be synchronized normally in the ipv4 mode. How can I solve this problem? Thank you
![微信截图_20220928170045](https://user-images.githubusercontent.com/13058646/192737721-6869f36a-76c9-4553-9b1d-92076f6439d9.png)

**Comment by wangzz-a** [comment]
这里是节点列表
![screencapture-10-19-181-125-8848-nacos-2022-09-28-17_06_49](https://user-images.githubusercontent.com/13058646/192739806-940be29f-37f3-4e07-bda4-3567269f641a.png)

**Comment by wangzz-a** [comment]
这里是节点列表
![screencapture-10-19-181-125-8848-nacos-2022-09-28-17_06_49](https://user-images.githubusercontent.com/13058646/192740330-a6ead32c-a6ef-41c8-bf64-1806ffe6b8d0.png)

**Comment by KomachiSion** [comment]
看一下其他日志文件有没有错误信息。

**Comment by wangzz-a** [comment]
你好！你发的邮件我已经收到！                       ——正

**Comment by wangzz-a** [comment]
你好老师，我在nacos.log日志中发现以下错误信息
Caused by: java.net.URISyntaxException: Expected closing bracket for IPv6 address at index 12: //[2409:9849
        at java.base/java.net.URI$Parser.fail(URI.java:2913)
        at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
        at java.base/java.net.URI$Parser.parseServer(URI.java:3292)
        at java.base/java.net.URI$Parser.parseAuthority(URI.java:3216)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3158)
        at java.base/java.net.URI$Parser.parse(URI.java:3125)
        at java.base/java.net.URI.<init>(URI.java:685)
        at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:512)
        ... 15 common frames omitted
2022-09-29 15:34:36,188 INFO [Cluster-[2409:xxxxxxxx::7E]:8848] Fail to connect server, after trying 62 times, last try server is {serverIp = '[2409', server main port = 8848}, error = unknown

2022-09-29 15:34:36,410 ERROR [Cluster-[2409:xxxxxxxx::7C]:8848]Fail to connect to server!,error={}

java.lang.IllegalArgumentException: Invalid host or port: [2409 9849
        at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:514)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<init>(NettyChannelBuilder.java:132)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:118)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
        at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
        at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:152)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:302)
        at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:521)
        at com.alibaba.nacos.common.remote.client.RpcClient.lambda$start$2(RpcClient.java:369)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.URISyntaxException: Expected closing bracket for IPv6 address at index 12: //[2409:9849
        at java.base/java.net.URI$Parser.fail(URI.java:2913)
        at java.base/java.net.URI$Parser.failExpecting(URI.java:2919)
        at java.base/java.net.URI$Parser.parseServer(URI.java:3292)
        at java.base/java.net.URI$Parser.parseAuthority(URI.java:3216)
        at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3158)
        at java.base/java.net.URI$Parser.parse(URI.java:3125)
        at java.base/java.net.URI.<init>(URI.java:685)
        at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:512)
        ... 15 common frames omitted
2022-09-29 15:34:36,411 INFO [Cluster-[2409:xxxxxxxx::7C]:8848] Fail to connect server, after trying 66 times, last try server is {serverIp = '[2409', server main port = 8848}, error = unknown

![image](https://user-images.githubusercontent.com/13058646/192969249-92e57802-b74e-4f8c-aa09-17368810a786.png)

**Comment by wangzz-a** [comment]
@KomachiSion 
> 你好老师，我在nacos.log日志中发现以下错误信息，但是我用telnet了一下这几个地址的端口，确认都是通的 Caused by: java.net.URISyntaxException: Expected closing bracket for IPv6 address at index 12: //[2409:9849 at java.base/java.net.URI$Parser.fail(URI.java:2913) at java.base/java.net.URI$Parser.failExpecting(URI.java:2919) at java.base/java.net.URI$Parser.parseServer(URI.java:3292) at java.base/java.net.URI$Parser.parseAuthority(URI.java:3216) at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3158) at java.base/java.net.URI$Parser.parse(URI.java:3125) at java.base/java.net.URI.(URI.java:685) at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:512) ... 15 common frames omitted 2022-09-29 15:34:36,188 INFO [Cluster-[2409:xxxxxxxx::7E]:8848] Fail to connect server, after trying 62 times, last try server is {serverIp = '[2409', server main port = 8848}, error = unknown
> 
> 2022-09-29 15:34:36,410 ERROR [Cluster-[2409:xxxxxxxx::7C]:8848]Fail to connect to server!,error={}
> 
> java.lang.IllegalArgumentException: Invalid host or port: [2409 9849 at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:514) at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.(NettyChannelBuilder.java:132) at io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.forAddress(NettyChannelBuilder.java:118) at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37) at io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23) at io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39) at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:152) at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:302) at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:521) at com.alibaba.nacos.common.remote.client.RpcClient.lambda$start$2(RpcClient.java:369) at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515) at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) at java.base/java.lang.Thread.run(Thread.java:834) Caused by: java.net.URISyntaxException: Expected closing bracket for IPv6 address at index 12: //[2409:9849 at java.base/java.net.URI$Parser.fail(URI.java:2913) at java.base/java.net.URI$Parser.failExpecting(URI.java:2919) at java.base/java.net.URI$Parser.parseServer(URI.java:3292) at java.base/java.net.URI$Parser.parseAuthority(URI.java:3216) at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3158) at java.base/java.net.URI$Parser.parse(URI.java:3125) at java.base/java.net.URI.(URI.java:685) at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:512) ... 15 common frames omitted 2022-09-29 15:34:36,411 INFO [Cluster-[2409:xxxxxxxx::7C]:8848] Fail to connect server, after trying 66 times, last try server is {serverIp = '[2409', server main port = 8848}, error = unknown
> 
> ![image](https://user-images.githubusercontent.com/13058646/192969249-92e57802-b74e-4f8c-aa09-17368810a786.png)



> 看一下其他日志文件有没有错误信息。

**Comment by wangzz-a** [comment]
protocol-distro.log，错误日志如下
2022-09-29 15:42:01,043 WARN data storage DistroClientDataProcessor has not finished initial step, do not send verify data

2022-09-29 15:42:04,613 INFO [DISTRO-INIT] load snapshot Nacos:Naming:v2:ClientData from [2409:xxxx:xxxx::7C]:8848

2022-09-29 15:42:04,613 ERROR [DISTRO-INIT] load snapshot Nacos:Naming:v2:ClientData from [2409:xxxx:xxxx::7C]:8848 failed.

com.alibaba.nacos.core.distributed.distro.exception.DistroException: [DISTRO-EXCEPTION][DISTRO] Cancel get snapshot caused by target server [2409:xxxx:xxxx::7C]:8848 unhealthy
        at com.alibaba.nacos.naming.consistency.ephemeral.distro.v2.DistroClientTransportAgent.getDatumSnapshot(DistroClientTransportAgent.java:190)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.loadAllDataSnapshotFromRemote(DistroLoadDataTask.java:104)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.load(DistroLoadDataTask.java:87)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.run(DistroLoadDataTask.java:63)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2022-09-29 15:42:04,613 INFO [DISTRO-INIT] load snapshot Nacos:Naming:v2:ClientData from [2409:xxxx:xxxx::7E]:8848

2022-09-29 15:42:04,613 ERROR [DISTRO-INIT] load snapshot Nacos:Naming:v2:ClientData from [2409:xxxx:xxxx::7E]:8848 failed.

com.alibaba.nacos.core.distributed.distro.exception.DistroException: [DISTRO-EXCEPTION][DISTRO] Cancel get snapshot caused by target server [2409:xxxx:xxxx::7E]:8848 unhealthy
        at com.alibaba.nacos.naming.consistency.ephemeral.distro.v2.DistroClientTransportAgent.getDatumSnapshot(DistroClientTransportAgent.java:190)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.loadAllDataSnapshotFromRemote(DistroLoadDataTask.java:104)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.load(DistroLoadDataTask.java:87)
        at com.alibaba.nacos.core.distributed.distro.task.load.DistroLoadDataTask.run(DistroLoadDataTask.java:63)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
2022-09-29 15:42:06,043 WARN data storage DistroClientDataProcessor has not finished initial step, do not send verify data

**Comment by KomachiSion** [comment]
java.lang.IllegalArgumentException: Invalid host or port: [2409 9849 at io.grpc.internal.GrpcUtil.authorityFromHostAndPort(GrpcUtil.java:514) at

说明grpc识别不了你输入的ipv6地址。

**Comment by KomachiSion** [comment]
move to #9269
