### ISSUE TITLE
2.1.1集群报连接不上异常，仍可以正常使用

### ISSUE THREAD

**Issue by dym1005** [alibaba/nacos#9243]
有个问题想请教一下各位大神，我在服务器上配置了nacos集群后以集群的方式启动本地的项目，idea控制台一直报如下连接不上的错误，服务中心也可以找到我开启的服务，三个端口也都开启了，postman返送请求测试也可以正常返回数据。之后我尝试在本地同时以单机的方式启动nacos，控制台就不再报错了，有没有大神解答一下这是因为什么？是我哪里的配置有问题吗？

控制台报错：
2022-09-29 14:23:06.840 [com.alibaba.nacos.client.remote.worker] [INFO ] com.alibaba.nacos.common.remote.client - [1b00580b-faea-4c0b-8c0c-9f9b2b8ad494_config-0] fail to connect server,after trying 4 times, last try server is {serverIp='localhost', server main port=8848},error=unknown
2022-09-29 14:23:08.310 [com.alibaba.nacos.client.Worker] [ERROR] com.alibaba.nacos.common.remote.client - Send request fail, request=ConfigBatchListenRequest{headers={charset=UTF-8, Client-AppName=unknown, Client-RequestToken=346633fc14d169c0da7ae41b9262d7d8, Client-RequestTS=1664432588203, exConfigInfo=true, Timestamp=1664432588203}, requestId='null'}, retryTimes=0,errorMessage=Client not connected,current status:STARTING
2022-09-29 14:23:08.417 [com.alibaba.nacos.client.Worker] [ERROR] com.alibaba.nacos.common.remote.client - Send request fail, request=ConfigBatchListenRequest{headers={charset=UTF-8, Client-AppName=unknown, Client-RequestToken=346633fc14d169c0da7ae41b9262d7d8, Client-RequestTS=1664432588203, exConfigInfo=true, Timestamp=1664432588203}, requestId='null'}, retryTimes=1,errorMessage=Client not connected,current status:STARTING
2022-09-29 14:23:08.525 [com.alibaba.nacos.client.Worker] [ERROR] com.alibaba.nacos.common.remote.client - Send request fail, request=ConfigBatchListenRequest{headers={charset=UTF-8, Client-AppName=unknown, Client-RequestToken=346633fc14d169c0da7ae41b9262d7d8, Client-RequestTS=1664432588203, exConfigInfo=true, Timestamp=1664432588203}, requestId='null'}, retryTimes=2,errorMessage=Client not connected,current status:STARTING
2022-09-29 14:23:08.526 [com.alibaba.nacos.client.Worker] [ERROR] com.alibaba.nacos.client.config.impl.ClientWorker - Async listen config change error 
com.alibaba.nacos.api.exception.NacosException: Client not connected,current status:STARTING
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:655)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1067)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.requestProxy(ClientWorker.java:1042)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.executeConfigListen(ClientWorker.java:831)
	at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient$4.run(ClientWorker.java:748)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2022-09-29 14:23:10.364 [com.alibaba.nacos.client.remote.worker] [ERROR] c.a.nacos.common.remote.client.grpc.GrpcClient - Server check fail, please check server localhost ,port 9848 is available , error ={}
java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 13 milliseconds, 328700 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@53efa93[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@2c30b71f, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@1d81e101, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@ec50f54}}}}}]]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:146)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:268)
	at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:528)
	at com.alibaba.nacos.common.remote.client.RpcClient$3.run(RpcClient.java:373)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by DickensTone** [comment]
我看你的报错里面有{serverIp=**'localhost',** server main port=8848},error=unknown。是不是你的idea本地服务的地址没配对啊，应该配你的服务服务器的地址

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
