### ISSUE TITLE
Docker容器环境下持久化数据库使用域名异常

### ISSUE THREAD

**Issue by kkkevin07** [alibaba/nacos#9247]
镜像版本nacos：nacos/nacos-server:v2.1.0

异常内容：
```
nacos  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.1.0.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
nacos  | No DataSource set
nacos  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769)
nacos  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218)
nacos  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338)
nacos  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185)
nacos  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554)
nacos  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514)
nacos  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321)
nacos  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
nacos  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319)
nacos  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
nacos  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866)
nacos  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
nacos  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
nacos  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
nacos  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744)
nacos  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391)
nacos  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312)
nacos  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
nacos  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204)
nacos  | 	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
nacos  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos  | 	at java.lang.reflect.Method.invoke(Method.java:498)
nacos  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
nacos  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
nacos  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
nacos  | 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
```

docker compose配置：
```version: '3.8'
services: 
  nacos:
    image: nacos/nacos-server:v2.1.0
    container_name: nacos
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    volumes:
      - /opt/nacos/logs/:/home/nacos/logs
    environment:
      - PREFER_HOST_MODE=ip
      - MODE=standalone
      - NACOS_AUTH_ENABLE=true
      - SPRING_DATASOURCE_PLATFORM=mysql
      - MYSQL_SERVICE_HOST=rwlb.rds.aliyuncs.com
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_DB_NAME=pengpeng_pre
      - MYSQL_SERVICE_USER=user
      - MYSQL_SERVICE_PASSWORD=pwd
      - MYSQL_SERVICE_DB_PARAM=characterEncoding=haracterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false
    restart: always
    deploy:
      resources:
        limits:
          memory: 1280m
```

**Comment by KomachiSion** [comment]
数据库访问失败， 看下日志里其他提示信息，找下具体原因。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
