### ISSUE TITLE
nacos获取实例超时

### ISSUE THREAD

**Issue by wangbo2013** [alibaba/nacos#9270]
问题如下：
        使用spring cloud gateway网关，使用GlobalFilter过滤器，nacos中服务配置了lb://这种格式，例如配置了服务A和服务B，当前端请求服务A的接口，我在gateway过滤器的网关中使用feign调用B服务接口，nacos获取不到B服务的实例，而A和B服务的实例是注册到nacos中的。开启nacos的debug模式后，日志如下：o.s.c.l.c.DiscoveryClientServiceInstanceListSupplier:106|Timeout occurred while retrieving instances for service FORUM-TOPIC.The instances could not be retrieved during PT30S，麻烦问题这个问题怎么解决。

**Comment by KomachiSion** [comment]
看不懂问题

lb://和nacos应该没什么关系， 这应该是scg的内容。

超时的报错也并非nacos报出的。 建议还是精炼一下问题。

**Comment by wangbo2013** [comment]
麻烦再看下，详细错误如下：
2022-09-26 16:19:37,988|DEBUG|forum-gateway,,|com.alibaba.nacos.client.Worker.longPolling.fixed-localhost_8848-naodao-prod|c.a.n.c.c.i.ConfigHttpClientManager:494|Execute via interceptors :[com.alibaba.nacos.client.config.impl.ConfigHttpClientManager$LimiterHttpClientRequestInterceptor@7f416310]
2022-09-26 16:19:39,661|DEBUG|forum-gateway,,|parallel-5|o.s.c.l.c.DiscoveryClientServiceInstanceListSupplier:106|Timeout occurred while retrieving instances for service FORUM-TOPIC.The instances could not be retrieved during PT30S
2022-09-26 16:19:39,661|WARN|forum-gateway,,|parallel-5|o.s.c.l.core.RoundRobinLoadBalancer:98|No servers available for service: FORUM-TOPIC
2022-09-26 16:19:39,661|WARN|forum-gateway,,|boundedElastic-88|o.s.c.o.l.FeignBlockingLoadBalancerClient:103|Load balancer does not contain an instance for the service FORUM-TOPIC
2022-09-26 16:19:39,662|DEBUG|forum-gateway,,|boundedElastic-88|o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler:147|[42636926] Resolved [ServiceUnavailable: [503] during [GET] to [http://FORUM-TOPIC/user/getUserStatusByUserId] [ITopicFeign#getUserStatusByUserId(String)]: [Load balancer does not contain an instance for the service FORUM-TOPIC]] for HTTP POST /file/file/partUpload
2022-09-26 16:19:39,662|ERROR|forum-gateway,,|boundedElastic-88|o.s.b.a.w.r.e.AbstractErrorWebExceptionHandler:122|[42636926]  500 Server Error for HTTP POST "/file/file/partUpload"
feign.FeignException$ServiceUnavailable: [503] during [GET] to [http://FORUM-TOPIC/user/getUserStatusByUserId] [ITopicFeign#getUserStatusByUserId(String)]: [Load balancer does not contain an instance for the service FORUM-TOPIC]
	at feign.FeignException.serverErrorStatus(FeignException.java:256)
	Suppressed: reactor.core.publisher.FluxOnAssembly$OnAssemblyException: 
Error has been observed at the following site(s):
	*__checkpoint ⇢ org.springframework.web.cors.reactive.CorsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.cloud.gateway.filter.WeightCalculatorWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ org.springframework.boot.actuate.metrics.web.reactive.server.MetricsWebFilter [DefaultWebFilterChain]
	*__checkpoint ⇢ HTTP POST "/file/file/partUpload" [ExceptionHandlingWebHandler]
Original Stack Trace:
		at feign.FeignException.serverErrorStatus(FeignException.java:256)
		at feign.FeignException.errorStatus(FeignException.java:197)
		at feign.FeignException.errorStatus(FeignException.java:185)
		at feign.codec.ErrorDecoder$Default.decode(ErrorDecoder.java:92)
		at feign.AsyncResponseHandler.handleResponse(AsyncResponseHandler.java:96)
		at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:138)
		at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:89)
		at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:100)
		at com.sun.proxy.$Proxy151.getUserStatusByUserId(Unknown Source)
		at com.naodao.gateway.intercept.MyGatewayFilter.filter(MyGatewayFilter.java:169)
		at sun.reflect.GeneratedMethodAccessor160.invoke(Unknown Source)
		at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
		at java.lang.reflect.Method.invoke(Method.java:498)
		at org.springframework.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:282)
		at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:485)
		at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
		at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:763)
		at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:708)
		at com.naodao.gateway.intercept.MyGatewayFilter$$EnhancerBySpringCGLIB$$a558f22d.filter(<generated>)
		at org.springframework.cloud.gateway.handler.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:137)
		at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:117)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:44)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:52)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:240)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
		at reactor.core.publisher.FluxMap$MapSubscriber.onComplete(FluxMap.java:144)
		at reactor.core.publisher.MonoNext$NextSubscriber.onComplete(MonoNext.java:102)
		at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:83)
		at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:98)
		at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:44)
		at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drainAsync(FluxFlattenIterable.java:421)
		at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.drain(FluxFlattenIterable.java:686)
		at reactor.core.publisher.FluxFlattenIterable$FlattenIterableSubscriber.onNext(FluxFlattenIterable.java:250)
		at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:74)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
		at reactor.core.publisher.MonoFlatMap$FlatMapInner.onNext(MonoFlatMap.java:249)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.complete(MonoIgnoreThen.java:292)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onNext(MonoIgnoreThen.java:187)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:236)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.onComplete(MonoIgnoreThen.java:203)
		at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onComplete(MonoIgnoreElements.java:89)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onComplete(FluxPeek.java:260)
		at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onComplete(FluxDematerialize.java:121)
		at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:91)
		at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:44)
		at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:340)
		at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:227)
		at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.request(FluxDematerialize.java:127)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.request(FluxPeek.java:138)
		at reactor.core.publisher.MonoIgnoreElements$IgnoreElementsSubscriber.onSubscribe(MonoIgnoreElements.java:72)
		at reactor.core.publisher.FluxPeek$PeekSubscriber.onSubscribe(FluxPeek.java:171)
		at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onSubscribe(FluxDematerialize.java:77)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
		at reactor.core.publisher.Mono.subscribe(Mono.java:4400)
		at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.subscribeNext(MonoIgnoreThen.java:263)
		at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:51)
		at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:157)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
		at reactor.core.publisher.DrainUtils.postCompleteDrain(DrainUtils.java:132)
		at reactor.core.publisher.DrainUtils.postComplete(DrainUtils.java:187)
		at reactor.core.publisher.FluxMaterialize$MaterializeSubscriber.onComplete(FluxMaterialize.java:141)
		at reactor.core.publisher.FluxTake$TakeSubscriber.onComplete(FluxTake.java:153)
		at reactor.core.publisher.FluxTake$TakeSubscriber.onNext(FluxTake.java:133)
		at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:79)
		at reactor.core.publisher.SerializedSubscriber.onNext(SerializedSubscriber.java:99)
		at reactor.core.publisher.FluxTimeout$TimeoutMainSubscriber.onNext(FluxTimeout.java:180)
		at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1816)
		at reactor.core.publisher.MonoCollectList$MonoCollectListSubscriber.onComplete(MonoCollectList.java:128)
		at org.springframework.cloud.commons.publisher.FluxFirstNonEmptyEmitting$FirstNonEmptyEmittingSubscriber.onComplete(FluxFirstNonEmptyEmitting.java:325)
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onComplete(FluxSubscribeOn.java:166)
		at reactor.core.publisher.FluxIterable$IterableSubscription.fastPath(FluxIterable.java:362)
		at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:227)
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.requestUpstream(FluxSubscribeOn.java:131)
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.onSubscribe(FluxSubscribeOn.java:124)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:165)
		at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:87)
		at reactor.core.publisher.Flux.subscribe(Flux.java:8469)
		at reactor.core.publisher.FluxFlatMap.trySubscribeScalarMap(FluxFlatMap.java:200)
		at reactor.core.publisher.MonoFlatMapMany.subscribeOrReturn(MonoFlatMapMany.java:49)
		at reactor.core.publisher.FluxFromMonoOperator.subscribe(FluxFromMonoOperator.java:76)
		at reactor.core.publisher.FluxSubscribeOn$SubscribeOnSubscriber.run(FluxSubscribeOn.java:194)
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:84)
		at reactor.core.scheduler.WorkerTask.call(WorkerTask.java:37)
		at java.util.concurrent.FutureTask.run(FutureTask.java:266)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
		at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
		at java.lang.Thread.run(Thread.java:748)

**Comment by KomachiSion** [comment]
完整日志看下来唯一和nacos有关的是配置中心长轮询，报错是loadbalance找不到服务，和nacos没什么关系， 根据描述里面nacos里面是有服务的。

可以看下应用的${user.home}/logs/nacos/naming.log ，看下有没有收到订阅服务的服务。

**Comment by KomachiSion** [comment]
No more response from author, and current information is not enough to find problem.
