### ISSUE TITLE
nacos集群三个节点只有一个节点能正常访问，start.out日志查看正常

### ISSUE THREAD

**Issue by liwei-2000** [alibaba/nacos#9314]
**前提：**一台Linux，通过不同端口实现nacos集群搭建；cluster.conf已配置ip:3333,ip:8848,ip:4444；已修改startup.sh启动脚本，添加-Dserver.port=${PORT}命令

**问题：**nacos集群启动后，三个节点只有一个节点可以访问（该节点的端口号配置在application.properties文件中）；通过nacos可视化界面查看节点列表，一个节点up，两个节点down

**日志查看：**
**start.out：**
INFO The server IP list of Nacos is [192.168.12.128:3333, 192.168.12.128:4444, 192.168.12.128:8848]

2022-10-12 07:41:16,405 INFO Nacos is starting...

2022-10-12 07:41:16,589 INFO Nacos is starting...

**nacos-cluster.log：**
2022-10-12 07:42:40,720 ERROR failed to report new info to target node : 192.168.12.128:4444, error : caused: Connection refused;

2022-10-12 07:42:42,724 ERROR failed to report new info to target node : 192.168.12.128:8848, error : caused: Connection refused;

**naming-server.log：**
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:716)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:174)
	at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:148)
	at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:351)
	at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:194)
	at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64)
	at java.lang.Thread.run(Thread.java:750)
2022-10-12 08:29:19,234 WARN Exception while request: http://192.168.12.128:8848/nacos/v1/ns/operator/cluster/state, caused: {}

org.apache.http.conn.HttpHostConnectException: Connect to 192.168.12.128:8848 [/192.168.12.128] failed: Connection refused (Connection refused)
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:156)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
	at com.alibaba.nacos.common.http.client.request.DefaultHttpClientRequest.execute(DefaultHttpClientRequest.java:58)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.execute(NacosRestTemplate.java:482)
	at com.alibaba.nacos.common.http.client.NacosRestTemplate.exchange(NacosRestTemplate.java:447)
	at com.alibaba.nacos.naming.misc.HttpClient.request(HttpClient.java:119)
	at com.alibaba.nacos.naming.misc.HttpClient.httpGet(HttpClient.java:82)
	at com.alibaba.nacos.naming.misc.NamingProxy.reqCommon(NamingProxy.java:308)
	at com.alibaba.nacos.naming.cluster.ServerListManager$ServerInfoUpdater.run(ServerListManager.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

**Comment by KomachiSion** [comment]
说明3333和4444没启动，和nacos无关。

**Comment by liwei-2000** [comment]
> 说明3333和4444没启动，和nacos无关。

start.out日志显示三个端口都启动成功了；使用 ps -ef|grep nacos|grep -v grep|wc -l 命令查询到nacos服务也是 3 个

**Comment by KomachiSion** [comment]
Connection refused 
这个报错没什么好说的， 基本都是端口没监听，建链接都建不了。

**Comment by liwei-2000** [comment]
> Connection refused 这个报错没什么好说的， 基本都是端口没监听，建链接都建不了。

Linux中开放了对应的端口权限，后续也通过关闭防火墙的方法测试过，是同样的问题

**Comment by KomachiSion** [comment]
telnet 127.0.0.1 4444 

lsof -i:4444

试一下

Connection refused是网络层的拒绝，请求都没走到代码里，在建立链接的时候就已经被拒绝了。
