### ISSUE TITLE
[Nacos-Docker Compose]load jdbc.properties error

### ISSUE THREAD

**Issue by 1798972** [alibaba/nacos#9337]
#### 1.git clone

```bash
git clone --depth 1 https://github.com/nacos-group/nacos-docker.git
```

#### 2.编辑配置文件

```bash
# 进入nacos-docker文件夹
[root@VM-12-8-centos software]# cd nacos-docker/

[root@VM-12-8-centos nacos-docker]# ll
total 36K
drwxr-xr-x 4 root root 4.0K 2022/10/17 23:37:26 build
-rw-r--r-- 1 root root 1.9K 2022/10/17 23:37:26 changlog
drwxr-xr-x 2 root root 4.0K 2022/10/17 23:37:26 env
drwxr-xr-x 4 root root 4.0K 2022/10/17 23:37:26 example
-rw-r--r-- 1 root root 7.5K 2022/10/17 23:37:26 README.md
-rw-r--r-- 1 root root 9.6K 2022/10/17 23:37:26 README_ZH.md

# 编辑example下的standalone-mysql-8.yaml文件
[root@VM-12-8-centos nacos-docker]# vim example/standalone-mysql-8.yaml
```

> 这是修改后的standalone-mysql-8.yaml

```yml
version: "3.8"
services:
  nacos:
    image: nacos/nacos-server:${NACOS_VERSION}
    container_name: nacos-standalone-mysql
    env_file:
      - ../env/nacos-standlone-mysql.env
    volumes:
      - /yang/logs/nacos:/home/nacos/logs
      - /yang/config/nacos/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9555:9555"
    restart: always
```

![image-20221017235157809](https://markdown-1258124344.cos.ap-guangzhou.myqcloud.com/image/20221017235157.png)

发现依赖了`../env/nacos-standlone-mysql.env`，编辑这个文件。

```bash
vim env/nacos-standlone-mysql.env
```

> 这是修改后的nacos-standlone-mysql.env

```yaml
#PREFER_HOST_MODE=ip
MODE=standalone
SPRING_DATASOURCE_PLATFORM=mysql
MYSQL_SERVICE_HOST=公网ip地址
MYSQL_SERVICE_DB_NAME=nacos
MYSQL_SERVICE_PORT=3306
MYSQL_SERVICE_USER=xxx
MYSQL_SERVICE_PASSWORD=xxx
#MYSQL_SERVICE_DB_PARAM=characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
```

#### 3.执行启动

```bash
docker-compose -f example/standalone-mysql-8.yaml up
```

#### 4.运行日志

```bash
nacos-standalone-mysql  | + exec /usr/lib/jvm/java-1.8.0-openjdk/bin/java -Xms1g -Xmx1g -Xmn512m -Dnacos.standalone=true -Dnacos.member.list= -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/health:/home/nacos/plugins/cmdb:/home/nacos/plugins/mysql -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar --spring.config.additional-location=file:/home/nacos/conf/ --spring.config.name=application --logging.config=/home/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
nacos-standalone-mysql  | 
nacos-standalone-mysql  |          ,--.
nacos-standalone-mysql  |        ,--.'|
nacos-standalone-mysql  |    ,--,:  : |                                           Nacos 2.1.1
nacos-standalone-mysql  | ,`--.'`|  ' :                       ,---.               Running in stand alone mode, All function modules
nacos-standalone-mysql  | |   :  :  | |                      '   ,'\   .--.--.    Port: 8848
nacos-standalone-mysql  | :   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: 1
nacos-standalone-mysql  | |   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://172.20.0.2:8848/nacos/index.html
nacos-standalone-mysql  | '   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_
nacos-standalone-mysql  | |   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io
nacos-standalone-mysql  | '   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \
nacos-standalone-mysql  | |   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  /
nacos-standalone-mysql  | '   : |     ;  :   .'   \   :    : `----'  '--'.     /
nacos-standalone-mysql  | ;   |.'     |  ,     .-./\   \  /            `--'---'
nacos-standalone-mysql  | '---'        `--`---'     `----'
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:44:52,627 INFO Tomcat initialized with port(s): 8848 (http)
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:44:52,719 INFO Root WebApplicationContext: initialization completed in 3947 ms
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:44:53,733 WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'consoleHealth' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/classes!/com/alibaba/nacos/console/controller/HealthController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalStoragePersistServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:44:53,777 INFO Nacos Log files: /home/nacos/logs
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:44:53,777 INFO Nacos Log files: /home/nacos/conf
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:44:53,777 INFO Nacos Log files: /home/nacos/data
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:44:53,778 ERROR Startup errors : 
nacos-standalone-mysql  | 
nacos-standalone-mysql  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'consoleHealth' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/classes!/com/alibaba/nacos/console/controller/HealthController.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalStoragePersistServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
nacos-standalone-mysql  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
nacos-standalone-mysql  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
nacos-standalone-mysql  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
nacos-standalone-mysql  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
nacos-standalone-mysql  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
nacos-standalone-mysql  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
nacos-standalone-mysql  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
nacos-standalone-mysql  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
nacos-standalone-mysql  | 	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
nacos-standalone-mysql  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos-standalone-mysql  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos-standalone-mysql  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos-standalone-mysql  | 	at java.lang.reflect.Method.invoke(Method.java:498)
nacos-standalone-mysql  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
nacos-standalone-mysql  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
nacos-standalone-mysql  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
nacos-standalone-mysql  | 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
nacos-standalone-mysql  | Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalStoragePersistServiceImpl': Invocation of init method failed; nested exception is java.lang.RuntimeException: java.lang.RuntimeException: [db-load-error]load jdbc.properties error
```

![image-20221017234552498](https://markdown-1258124344.cos.ap-guangzhou.myqcloud.com/image/20221017234552.png)

#### 5.docker exec后进入容器

> echo了几个环境变量，比如

![image-20221017234822138](https://markdown-1258124344.cos.ap-guangzhou.myqcloud.com/image/20221017234822.png)

在/home/nacos/bin下找到了启动脚本，搜索没有发现到MYSQL相关的那几个环境变量。

所以编辑了`conf/application.properties`下的配置文件，加上了这些信息。

```yml
spring.datasource.platform=mysql
db.num=1
db.url.0=jdbc:mysql://公网ip:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.user=xxx
db.password=xxx
```

然后再次启动，这个时候报错变成了。

```bash
nacos-standalone-mysql  | + exec /usr/lib/jvm/java-1.8.0-openjdk/bin/java -Xms1g -Xmx1g -Xmn512m -Dnacos.standalone=true -Dnacos.member.list= -Djava.ext.dirs=/usr/lib/jvm/java-1.8.0-openjdk/jre/lib/ext:/usr/lib/jvm/java-1.8.0-openjdk/lib/ext:/home/nacos/plugins/health:/home/nacos/plugins/cmdb:/home/nacos/plugins/mysql -Xloggc:/home/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dnacos.home=/home/nacos -jar /home/nacos/target/nacos-server.jar --spring.config.additional-location=file:/home/nacos/conf/ --spring.config.name=application --logging.config=/home/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288
nacos-standalone-mysql  | 
nacos-standalone-mysql  |          ,--.
nacos-standalone-mysql  |        ,--.'|
nacos-standalone-mysql  |    ,--,:  : |                                           Nacos 2.1.1
nacos-standalone-mysql  | ,`--.'`|  ' :                       ,---.               Running in stand alone mode, All function modules
nacos-standalone-mysql  | |   :  :  | |                      '   ,'\   .--.--.    Port: 8848
nacos-standalone-mysql  | :   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: 1
nacos-standalone-mysql  | |   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://172.20.0.2:8848/nacos/index.html
nacos-standalone-mysql  | '   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_
nacos-standalone-mysql  | |   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io
nacos-standalone-mysql  | '   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \
nacos-standalone-mysql  | |   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  /
nacos-standalone-mysql  | '   : |     ;  :   .'   \   :    : `----'  '--'.     /
nacos-standalone-mysql  | ;   |.'     |  ,     .-./\   \  /            `--'---'
nacos-standalone-mysql  | '---'        `--`---'     `----'
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:53:16,480 INFO Tomcat initialized with port(s): 8848 (http)
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:53:16,565 INFO Root WebApplicationContext: initialization completed in 4008 ms
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:53:34,081 WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.1.1.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
nacos-standalone-mysql  | No DataSource set
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:53:34,117 INFO Nacos Log files: /home/nacos/logs
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:53:34,117 INFO Nacos Log files: /home/nacos/conf
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:53:34,118 INFO Nacos Log files: /home/nacos/data
nacos-standalone-mysql  | 
nacos-standalone-mysql  | 2022-10-17 23:53:34,118 ERROR Startup errors : 
nacos-standalone-mysql  | 
nacos-standalone-mysql  | org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.1.1.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
nacos-standalone-mysql  | No DataSource set
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
nacos-standalone-mysql  | 	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
nacos-standalone-mysql  | 	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
nacos-standalone-mysql  | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
nacos-standalone-mysql  | 	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
nacos-standalone-mysql  | 	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
nacos-standalone-mysql  | 	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
nacos-standalone-mysql  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
nacos-standalone-mysql  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
nacos-standalone-mysql  | 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
nacos-standalone-mysql  | 	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
nacos-standalone-mysql  | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
nacos-standalone-mysql  | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
nacos-standalone-mysql  | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
nacos-standalone-mysql  | 	at java.lang.reflect.Method.invoke(Method.java:498)
nacos-standalone-mysql  | 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
nacos-standalone-mysql  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
nacos-standalone-mysql  | 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
nacos-standalone-mysql  | 	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
nacos-standalone-mysql  | Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
nacos-standalone-mysql  | No DataSource set
```

![image-20221017235431162](https://markdown-1258124344.cos.ap-guangzhou.myqcloud.com/image/20221017235431.png)

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.

**Comment by 1798972** [comment]
**最近比较忙，刚刚看了回复，问题解决了，谢谢指导~**

#### 1.nacos-standlone-mysql.env这个文件好像跟mysql连接不相关

> 配置的属性应该不是连接mysql的，推测是启动mysql容器的，我是用的自己的数据库，可以看上文中注释了standalone-mysql-8.yaml中的mysql部分。

```bash
 env/nacos-standlone-mysql.env
```

#### 2.编辑application.properties

> 启动容器时映射了目录

```bash
 volumes:
      - /yang/logs/nacos:/home/nacos/logs
      - /yang/config/nacos/application.properties:/home/nacos/conf/application.properties
```

在`application.properties`中添加了如下内容后，启动成功。

```yaml
spring.datasource.platform=mysql
db.num=1
db.url.0=jdbc:mysql://xxxx:3306/nacos?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true
db.user=root
db.password=xxx
```

---

#### 我是怎么解决这个问题的?

搜索问题: **[db-load-error]load jdbc.properties error**
找到了这个页面[[nacos 2.1.0 代码无法启动](https://github.com/alibaba/nacos/issues/7078)](https://github.com/alibaba/nacos/issues/7078)
发现[[brotherlu-xcq](https://github.com/brotherlu-xcq)](https://github.com/brotherlu-xcq)这位兄弟说:

```bash
config-fatal.log日志中有具体的启动错误，可以检查一下里面的日志看看是什么原因引起的
```

所以我去查看了我的`config-fatal.log`日志，发现了这样一行：

```bash
2022-10-31 21:35:31,143 ERROR [db-load-error]load jdbc.properties error

java.lang.IllegalArgumentException: db.num is null
```

`db.num`这个属性没有吗？所以我查找了[[nacos-docker](https://github.com/nacos-group/nacos-docker/blob/master/README_ZH.md)](https://github.com/nacos-group/nacos-docker/blob/master/README_ZH.md)，在下面的**属性配置列表**中没有发现这个环境变量，然后就有了**上面1的推测**。
接着我又把`application.properties`中的数据复原，观察**config-fatal.log**日志，发现是数据库密码写错了：

```bash
Caused by: com.mysql.cj.exceptions.CJException: Access denied for user 'xxx'@'xxx' (using password: YES)
```

嗯，修改这里后启动成功。
总结：**config-fatal.log**日志帮助了我。
@KomachiSion @DarkLight-Long
