### ISSUE TITLE
Nacos 2.1.2 集群启动 日志有报错

### ISSUE THREAD

**Issue by Vain-vayne** [alibaba/nacos#9345]
# 报错信息如下:

```
2022-10-19 09:31:02,355 INFO The server IP list of Nacos is [1.1.1.201:8848, 1.1.1.202:8848, 1.1.1.203:8848]

2022-10-19 09:31:02,370 INFO Starting Nacos v2.1.2 using Java 1.8.0_202 on vain02 with PID 2817 (/app/midware/nacos/target/nacos-server.jar started by appuser in /app/software)

2022-10-19 09:31:02,370 INFO No active profile set, falling back to 1 default profile: "default"

2022-10-19 09:31:03,367 INFO Nacos is starting...

2022-10-19 09:31:04,379 INFO Nacos is starting...

2022-10-19 09:31:05,397 INFO Nacos is starting...

2022-10-19 09:31:06,398 INFO Nacos is starting...

2022-10-19 09:31:07,142 INFO Tomcat initialized with port(s): 8848 (http)

2022-10-19 09:31:07,150 INFO Initializing ProtocolHandler ["http-nio-8848"]

2022-10-19 09:31:07,164 INFO Starting service [Tomcat]

2022-10-19 09:31:07,164 INFO Starting Servlet engine: [Apache Tomcat/9.0.63]

2022-10-19 09:31:07,339 INFO Initializing Spring embedded WebApplicationContext

2022-10-19 09:31:07,339 INFO Root WebApplicationContext: initialization completed in 4868 ms

2022-10-19 09:31:07,402 INFO Nacos is starting...

2022-10-19 09:31:07,765 INFO Nacos-related cluster resource initialization

2022-10-19 09:31:07,772 INFO Load com.alibaba.nacos.core.ability.RemoteAbilityInitializer for ServerAbilityInitializer

2022-10-19 09:31:07,772 INFO Load com.alibaba.nacos.naming.ability.NamingAbilityInitializer for ServerAbilityInitializer

2022-10-19 09:31:07,782 INFO The cluster resource is initialized

2022-10-19 09:31:08,007 INFO Get Distro config from env, DistroConfig{syncDelayMillis=1000, syncTimeoutMillis=3000, syncRetryDelayMillis=3000, verifyIntervalMillis=5000, verifyTimeoutMillis=3000, loadDataRetryDelayMillis=30000}

2022-10-19 09:31:08,415 INFO Nacos is starting...

2022-10-19 09:31:09,429 INFO Nacos is starting...

2022-10-19 09:31:10,454 INFO Nacos is starting...

2022-10-19 09:31:11,415 INFO HikariPool-1 - Starting...

2022-10-19 09:31:11,418 WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.

2022-10-19 09:31:11,460 INFO Nacos is starting...

2022-10-19 09:31:12,111 INFO HikariPool-1 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)

2022-10-19 09:31:12,126 INFO HikariPool-1 - Start completed.

2022-10-19 09:31:12,462 INFO Nacos is starting...

2022-10-19 09:31:13,054 INFO HikariPool-2 - Starting...

2022-10-19 09:31:13,055 WARN Registered driver with driverClassName=org.apache.derby.jdbc.EmbeddedDriver was not found, trying direct instantiation.

2022-10-19 09:31:13,377 INFO HikariPool-2 - Driver does not support get/set network timeout for connections. (Feature not implemented: No details.)

2022-10-19 09:31:13,379 INFO HikariPool-2 - Start completed.

2022-10-19 09:31:13,463 INFO Nacos is starting...

2022-10-19 09:31:14,464 INFO Nacos is starting...

2022-10-19 09:31:15,464 INFO Nacos is starting...

2022-10-19 09:31:16,466 INFO Nacos is starting...

2022-10-19 09:31:17,466 INFO Nacos is starting...

2022-10-19 09:31:18,467 INFO Nacos is starting...

2022-10-19 09:31:19,468 INFO Nacos is starting...

2022-10-19 09:31:20,468 INFO Nacos is starting...

2022-10-19 09:31:21,470 INFO Nacos is starting...

2022-10-19 09:31:22,471 INFO Nacos is starting...

2022-10-19 09:31:23,474 INFO Nacos is starting...

2022-10-19 09:31:24,483 INFO Nacos is starting...

2022-10-19 09:31:24,570 INFO Adding welcome page: class path resource [static/index.html]

2022-10-19 09:31:25,484 INFO Nacos is starting...

2022-10-19 09:31:26,108 WARN You are asking Spring Security to ignore Ant [pattern='/**']. This is not recommended -- please use permitAll via HttpSecurity#authorizeHttpRequests instead.

2022-10-19 09:31:26,110 INFO Will not secure Ant [pattern='/**']

2022-10-19 09:31:26,389 INFO Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@1cf2fed4, org.springframework.security.web.context.SecurityContextPersistenceFilter@56102e1c, org.springframework.security.web.header.HeaderWriterFilter@58c540cf, org.springframework.security.web.csrf.CsrfFilter@16fb356, org.springframework.security.web.authentication.logout.LogoutFilter@617fe9e1, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@7927bd9f, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@410954b, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@3af4e0bf, org.springframework.security.web.session.SessionManagementFilter@1b822fcc, org.springframework.security.web.access.ExceptionTranslationFilter@64f857e7]

2022-10-19 09:31:26,484 INFO Nacos is starting...

2022-10-19 09:31:26,561 INFO Exposing 14 endpoint(s) beneath base path '/actuator'

2022-10-19 09:31:27,419 INFO Starting ProtocolHandler ["http-nio-8848"]

2022-10-19 09:31:27,485 INFO Nacos is starting...

2022-10-19 09:31:27,531 INFO Tomcat started on port(s): 8848 (http) with context path '/nacos'

2022-10-19 09:31:27,595 INFO Started Nacos in 26.47 seconds (JVM running for 27.597)

2022-10-19 09:31:27,597 INFO Nacos started successfully in cluster mode. use embedded storage

2022-10-19 09:31:28,277 INFO Initializing Spring DispatcherServlet 'dispatcherServlet'

2022-10-19 09:31:28,277 INFO Initializing Servlet 'dispatcherServlet'

2022-10-19 09:31:28,279 INFO Completed initialization in 2 ms

2022-10-19 09:31:29,152 INFO [Cluster-1.1.1.203:8848] RpcClient init, ServerListFactory = com.alibaba.nacos.core.cluster.remote.ClusterRpcClientProxy$1

2022-10-19 09:31:29,156 INFO [Cluster-1.1.1.203:8848] Try to connect to server on start up, server: {serverIp = '1.1.1.203', server main port = 8848}

2022-10-19 09:31:29,491 INFO [Cluster-1.1.1.203:8848] Success to connect to server [1.1.1.203:8848] on start up, connectionId = 1666143089340_1.1.1.202_48070

2022-10-19 09:31:29,493 INFO [Cluster-1.1.1.203:8848] Register server push request handler:com.alibaba.nacos.common.remote.client.RpcClient$ConnectResetRequestHandler

2022-10-19 09:31:29,493 INFO [Cluster-1.1.1.203:8848] Register server push request handler:com.alibaba.nacos.common.remote.client.RpcClient$$Lambda$1049/3064635

2022-10-19 09:31:33,134 ERROR CONSOLE /nacos/v1/ns/operator/cluster/state

java.lang.IllegalStateException: unable to find local peer: 1.1.1.202:8848, all peers: []
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.local(RaftPeerSet.java:292)
	at com.alibaba.nacos.naming.core.ServiceManager.getMySelfClusterState(ServiceManager.java:287)
	at com.alibaba.nacos.naming.controllers.OperatorController.getClusterStates(OperatorController.java:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.nacos.console.filter.XssFilter.doFilterInternal(XssFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.nacos.naming.web.DistroFilter.doFilter(DistroFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.nacos.naming.web.ServiceNameFilter.doFilter(ServiceNameFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.nacos.naming.web.TrafficReviseFilter.doFilter(TrafficReviseFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:204)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2022-10-19 09:31:34,549 INFO [Cluster-1.1.1.201:8848] RpcClient init, ServerListFactory = com.alibaba.nacos.core.cluster.remote.ClusterRpcClientProxy$1

2022-10-19 09:31:34,551 INFO [Cluster-1.1.1.201:8848] Try to connect to server on start up, server: {serverIp = '1.1.1.201', server main port = 8848}

2022-10-19 09:31:34,687 INFO [Cluster-1.1.1.201:8848] Success to connect to server [1.1.1.201:8848] on start up, connectionId = 1666143094551_1.1.1.202_41684

2022-10-19 09:31:34,687 INFO [Cluster-1.1.1.201:8848] Register server push request handler:com.alibaba.nacos.common.remote.client.RpcClient$ConnectResetRequestHandler

2022-10-19 09:31:34,687 INFO [Cluster-1.1.1.201:8848] Register server push request handler:com.alibaba.nacos.common.remote.client.RpcClient$$Lambda$1049/3064635

2022-10-19 09:41:20,583 WARN clearConfigHistory start

2022-10-19 09:41:20,803 INFO [capacityManagement] start correct usage

2022-10-19 09:41:20,814 INFO [capacityManagement] end correct usage, cost: 0.009573076s

2022-10-19 09:46:40,152 ERROR CONSOLE /nacos/v1/ns/operator/cluster/state

java.lang.IllegalStateException: unable to find local peer: 1.1.1.202:8848, all peers: []
	at com.alibaba.nacos.naming.consistency.persistent.raft.RaftPeerSet.local(RaftPeerSet.java:292)
	at com.alibaba.nacos.naming.core.ServiceManager.getMySelfClusterState(ServiceManager.java:287)
	at com.alibaba.nacos.naming.controllers.OperatorController.getClusterStates(OperatorController.java:296)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:898)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:655)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.nacos.console.filter.XssFilter.doFilterInternal(XssFilter.java:42)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.nacos.naming.web.DistroFilter.doFilter(DistroFilter.java:98)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:69)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.nacos.naming.web.ServiceNameFilter.doFilter(ServiceNameFilter.java:77)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at com.alibaba.nacos.naming.web.TrafficReviseFilter.doFilter(TrafficReviseFilter.java:75)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:204)
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
	at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:748)
2022-10-19 09:51:20,584 WARN clearConfigHistory start

2022-10-19 09:51:20,814 INFO [capacityManagement] start correct usage

2022-10-19 09:51:20,815 INFO [capacityManagement] end correct usage, cost: 5.62718E-4s
```

**Comment by KomachiSion** [comment]
Ignore it,  old raft has been replaced with jraft after 1.4.0. Currently for upgrading from old version, run it templately, and will be closed after the cluster upgrade to new version.

The old raft will be removed completely in 2.2.0

**Comment by Vain-vayne** [comment]
现在生产环境推荐使用什么版本的 Nacos ?

**Comment by KomachiSion** [comment]
最新版本
