### ISSUE TITLE
nacos 2.1.2 ip 数量一夜间变为了 -786W

### ISSUE THREAD

**Issue by ijustyce** [alibaba/nacos#9351]
<img width="643" alt="image" src="https://user-images.githubusercontent.com/6041166/196840077-042ff126-e668-4950-9664-3745f81ad3a0.png">
如上图，且在继续减少中，昨晚8 点 多升级的 2.1.2，暂时未发现其他问题，只是这个统计 bug 了。

**Comment by KomachiSion** [comment]
应该是统计的地方有问题，某个情况下一直在扣除，之后尝试复现下。

**Comment by ijustyce** [comment]
> 应该是统计的地方有问题，某个情况下一直在扣除，之后尝试复现下。

如需协助，请回复，一直在线。不过这个只影响统计，没别的问题，即使减到了最小，会从最大开始重新减，不会抛出异常。

**Comment by KomachiSion** [comment]
能提供下客户端使用的是哪个版本吗？ 我用2.1.2版本客户端没有复现

**Comment by ijustyce** [comment]
> 能提供下客户端使用的是哪个版本吗？ 我用2.1.2版本客户端没有复现

目前客户端最多的是 1.3.2，也有 1.3.4 和 1.4.1 不过极少，基本都是 1.3.2

**Comment by KomachiSion** [comment]
我用1.3.2也没有复现，能否用arthas抓一下，看看是哪里一只在扣除统计：

stack com.alibaba.nacos.naming.monitor.MetricsMonitor decrementInstanceCount  -n 50

**Comment by ijustyce** [comment]
> 我用1.3.2也没有复现，能否用arthas抓一下，看看是哪里一只在扣除统计：
> 
> stack com.alibaba.nacos.naming.monitor.MetricsMonitor decrementInstanceCount -n 50

```
ts=2022-10-20 12:36:12;thread_name=http-nio-6801-exec-69;id=1f6;is_daemon=true;priority=5;TCCL=org.springframework.boot.web.embedded.tomcat.TomcatEmbeddedWebappClassLoader@79e18e38
    @com.alibaba.nacos.naming.monitor.MetricsMonitor.decrementInstanceCount()
        at com.alibaba.nacos.naming.core.v2.client.AbstractClient.removeServiceInstance(AbstractClient.java:90)
        at com.alibaba.nacos.naming.core.v2.service.impl.EphemeralClientOperationServiceImpl.deregisterInstance(EphemeralClientOperationServiceImpl.java:115)
        at com.alibaba.nacos.naming.core.v2.service.ClientOperationServiceProxy.deregisterInstance(ClientOperationServiceProxy.java:73)
        at com.alibaba.nacos.naming.core.InstanceOperatorClientImpl.removeInstance(InstanceOperatorClientImpl.java:118)
        at com.alibaba.nacos.naming.controllers.InstanceController.deregister(InstanceController.java:148)
        at jdk.internal.reflect.GeneratedMethodAccessor277.invoke(null:-1)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
        at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:150)
        at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:117)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:895)
        at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:808)
        at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:1067)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:963)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:1006)
        at org.springframework.web.servlet.FrameworkServlet.doDelete(FrameworkServlet.java:931)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:687)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:883)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:764)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:227)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:53)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.alibaba.nacos.console.filter.XssFilter.doFilterInternal(XssFilter.java:42)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CorsFilter.doFilterInternal(CorsFilter.java:91)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.alibaba.nacos.naming.web.DistroFilter.doFilter(DistroFilter.java:104)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.alibaba.nacos.core.auth.AuthFilter.doFilter(AuthFilter.java:69)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.alibaba.nacos.naming.web.ServiceNameFilter.doFilter(ServiceNameFilter.java:77)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at com.alibaba.nacos.naming.web.TrafficReviseFilter.doFilter(TrafficReviseFilter.java:75)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:204)
        at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:183)
        at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:354)
        at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:267)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:100)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.FormContentFilter.doFilterInternal(FormContentFilter.java:93)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.boot.actuate.metrics.web.servlet.WebMvcMetricsFilter.doFilterInternal(WebMvcMetricsFilter.java:96)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:201)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:117)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:189)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:162)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:197)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:97)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:541)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:135)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:92)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:78)
        at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:687)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:360)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:399)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:65)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:890)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1743)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1191)
        at org.apache.tomcat.util.threads.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:659)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:833)
```

**Comment by KomachiSion** [comment]
好像一直有注销实例接口的调用啊， 抓包看下来源，看下哪个服务一直在调用注销实例的接口？

**Comment by KomachiSion** [comment]
或者看下 naming-server.log ,  关键字`Client remove for service`

**Comment by ijustyce** [comment]
> 好像一直有注销实例接口的调用啊， 抓包看下来源，看下哪个服务一直在调用注销实例的接口？

注销实例调用属于正常，我们自己做了这个，避免更新时不平滑。更新时，会注销实例，但是不关闭 dubbo，并等待一定时间（业务自己指定）然后开始停止服务。

**Comment by ijustyce** [comment]
> 或者看下 naming-server.log , 关键字`Client remove for service`

这个 log 有 20657 条，但现在 ip count 为：-10207606

**Comment by KomachiSion** [comment]
会一直调用吗？  前面的stack命令就是查哪些地方来减这个ipCount， 如果一直都是有调用，但是又没有实际移除掉可能是有问题的

**Comment by ijustyce** [comment]
> stack com.alibaba.nacos.naming.monitor.MetricsMonitor decrementInstanceCount -n 50

> 会一直调用吗？ 前面的stack命令就是查哪些地方来减这个ipCount， 如果一直都是有调用，但是又没有实际移除掉可能是有问题的

间隔性刷屏，除了注销实例外，另一个 log 如下，基本就是他俩间隔性刷屏。

```
 @com.alibaba.nacos.naming.monitor.MetricsMonitor.decrementInstanceCount()
        at com.alibaba.nacos.naming.core.v2.client.AbstractClient.removeServiceInstance(AbstractClient.java:90)
        at com.alibaba.nacos.naming.consistency.ephemeral.distro.v2.DistroClientDataProcessor.upgradeClient(DistroClientDataProcessor.java:192)
        at com.alibaba.nacos.naming.consistency.ephemeral.distro.v2.DistroClientDataProcessor.handlerClientSyncData(DistroClientDataProcessor.java:167)
        at com.alibaba.nacos.naming.consistency.ephemeral.distro.v2.DistroClientDataProcessor.processData(DistroClientDataProcessor.java:149)
        at com.alibaba.nacos.core.distributed.distro.DistroProtocol.onReceive(DistroProtocol.java:173)
        at com.alibaba.nacos.naming.remote.rpc.handler.DistroDataRequestHandler.handleSyncData(DistroDataRequestHandler.java:89)
        at com.alibaba.nacos.naming.remote.rpc.handler.DistroDataRequestHandler.handle(DistroDataRequestHandler.java:57)
        at com.alibaba.nacos.naming.remote.rpc.handler.DistroDataRequestHandler.handle(DistroDataRequestHandler.java:37)
        at com.alibaba.nacos.core.remote.RequestHandler.handleRequest(RequestHandler.java:58)
        at com.alibaba.nacos.core.remote.grpc.GrpcRequestAcceptor.request(GrpcRequestAcceptor.java:168)
        at com.alibaba.nacos.core.remote.grpc.BaseGrpcServer.lambda$addServices$0(BaseGrpcServer.java:176)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
```

**Comment by KomachiSion** [comment]
这个是同步的，其他节点上的服务被删除同步过来了，应该也是正常。

还是要看naming-server.log `Client remove for service` 和 `Client change for service` ， 比如关注同一个服务的同一个实例的上述两个日志，有没有什么特别的

**Comment by ijustyce** [comment]
> stack com.alibaba.nacos.naming.monitor.MetricsMonitor decrementIpCountWithBatchRegister -n 50
> 
> 看下这个有没有被调用

没有调用。

**Comment by KomachiSion** [comment]
> 这个是同步的，其他节点上的服务被删除同步过来了，应该也是正常。
> 
> 还是要看naming-server.log `Client remove for service` 和 `Client change for service` ， 比如关注同一个服务的同一个实例的上述两个日志，有没有什么特别的

那就还是分析这个日志，或者提供一下这个日志。我没有复现出来这个问题。

**Comment by ijustyce** [comment]
> > 这个是同步的，其他节点上的服务被删除同步过来了，应该也是正常。
> > 还是要看naming-server.log `Client remove for service` 和 `Client change for service` ， 比如关注同一个服务的同一个实例的上述两个日志，有没有什么特别的
> 
> 那就还是分析这个日志，或者提供一下这个日志。我没有复现出来这个问题。

这个 log 打印并不频繁，我已上传：[https://cloud.kpromise.top/s/WdRK3EKio78Jw5Y](https://cloud.kpromise.top/s/WdRK3EKio78Jw5Y)

**Comment by KomachiSion** [comment]
1. 这里是bug，老版本移除连接的时候是吧subscribers和publisher都从统计去除，但是bug导致都去去除subscribers的统计。
2. provider 注册时不会把自己加入到subscribers中，只会加入到publisher中，你看的的consumer是dubbo把消费者也当服务注册上来了， 是dubbo的逻辑行为。对nacos来说只要是当服务注册的都是一样的。不管业务上它是什么意思。

**Comment by ijustyce** [comment]
> 1. 这里是bug，老版本移除连接的时候是吧subscribers和publisher都从统计去除，但是bug导致都去去除publisher的统计。
> 2. provider 注册时不会把自己加入到subscribers中，只会加入到publisher中，你看的的consumer是dubbo把消费者也当服务注册上来了， 是dubbo的逻辑行为。对nacos来说只要是当服务注册的都是一样的。不管业务上它是什么意思。

针对这个问题：
`
provider 注册时，将自己加到自己的 subscribers 列表中是出于什么原因考虑呢，感觉这个是浪费了？
`
我 debug 了下，我只注册了 provider，没 consumer，但是 provider 会请求 /instance/list 接口，从而把自己加入到了订阅者列表，这个逻辑感觉可以优化，不过再推进 2.x 升级了，似乎没必要，优化的原因是，如果自己是自己的订阅者，那么服务停止时，大概率 push 失败

**Comment by KomachiSion** [comment]
如果有调用/instance/list，就说明有订阅服务。用纯nacos-client注册服务不会调用
