### ISSUE TITLE
JDK17.0.4 , nacos-client:2.1.2  ，Springboot:2.7.4 

### ISSUE THREAD

**Issue by rola0411** [alibaba/nacos#9404]
```
java.lang.UnsupportedOperationException: Reflective setAccessible(true) disabled
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.ReflectionUtil.trySetAccessible(ReflectionUtil.java:31) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$4.run(PlatformDependent0.java:225) ~[nacos-client-2.1.2.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:219) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:223) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:210) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.AsciiString.cached(AsciiString.java:1401) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.AsciiString.<clinit>(AsciiString.java:48) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:72) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:74) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:163) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:303) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:359) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.start(NamingGrpcClientProxy.java:98) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.<init>(NamingGrpcClientProxy.java:91) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:78) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:99) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:84) ~[nacos-client-2.1.2.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.cloud.nacos.NacosServiceManager.createNewNamingService(NacosServiceManager.java:98) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar:2021.1]
	at com.alibaba.cloud.nacos.NacosServiceManager.buildNamingService(NacosServiceManager.java:89) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar:2021.1]
	at com.alibaba.cloud.nacos.NacosServiceManager.getNamingService(NacosServiceManager.java:52) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar:2021.1]
	at com.alibaba.cloud.nacos.endpoint.NacosDiscoveryEndpointAutoConfiguration.nacosDiscoveryHealthIndicator(NacosDiscoveryEndpointAutoConfiguration.java:62) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar:2021.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at com.zhongbao.pay.central.PayCentralApplication.main(PayCentralApplication.java:24) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.7.4.jar:2.7.4]

2022-10-26 16:50:55.300 DEBUG 7556 a.n.s.i.g.n.s.i.n.u.i.PlatformDependent0 : java.nio.Bits.unaligned: available, true
2022-10-26 16:50:55.301 DEBUG 7556 a.n.s.i.g.n.s.i.n.u.i.PlatformDependent0 : jdk.internal.misc.Unsafe.allocateUninitializedArray(int): unavailable

java.lang.IllegalAccessException: class com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$6 cannot access class jdk.internal.misc.Unsafe (in module java.base) because module java.base does not export jdk.internal.misc to unnamed module @316bcf94
	at jdk.internal.reflect.Reflection.newIllegalAccessException(Reflection.java:392) ~[?:?]
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:674) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:560) ~[?:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0$6.run(PlatformDependent0.java:335) ~[nacos-client-2.1.2.jar:?]
	at java.security.AccessController.doPrivileged(AccessController.java:318) ~[?:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent0.<clinit>(PlatformDependent0.java:326) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.isAndroid(PlatformDependent.java:289) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.internal.PlatformDependent.<clinit>(PlatformDependent.java:92) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:223) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.AsciiString.<init>(AsciiString.java:210) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.AsciiString.cached(AsciiString.java:1401) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.util.AsciiString.<clinit>(AsciiString.java:48) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.Utils.<clinit>(Utils.java:72) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:74) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:163) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:303) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:359) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.start(NamingGrpcClientProxy.java:98) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.<init>(NamingGrpcClientProxy.java:91) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:78) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:99) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:84) ~[nacos-client-2.1.2.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77) ~[nacos-client-2.1.2.jar:?]
	at com.alibaba.cloud.nacos.NacosServiceManager.createNewNamingService(NacosServiceManager.java:98) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar:2021.1]
	at com.alibaba.cloud.nacos.NacosServiceManager.buildNamingService(NacosServiceManager.java:89) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar:2021.1]
	at com.alibaba.cloud.nacos.NacosServiceManager.getNamingService(NacosServiceManager.java:52) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar:2021.1]
	at com.alibaba.cloud.nacos.endpoint.NacosDiscoveryEndpointAutoConfiguration.nacosDiscoveryHealthIndicator(NacosDiscoveryEndpointAutoConfiguration.java:62) ~[spring-cloud-starter-alibaba-nacos-discovery-2021.1.jar:2021.1]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:653) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:638) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1352) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1195) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955) ~[spring-beans-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583) ~[spring-context-5.3.23.jar:5.3.23]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:734) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:408) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.7.4.jar:2.7.4]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1295) ~[spring-boot-2.7.4.jar:2.7.4]
	at com.zhongbao.pay.central.PayCentralApplication.main(PayCentralApplication.java:24) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-2.7.4.jar:2.7.4]
```

**Comment by leopardrota** [comment]
Could you describe how to reproduce this issue?

**Comment by rola0411** [comment]
> Could you describe how to reproduce this issue?
说来话长。。我简单的跟了一下代码，或许这个异常你们是可以找到其它方法，大概是jdk17关闭了很多模块，需要额外在启动命令中设置开启。
下面图片这个类中。
![1667556963141](https://user-images.githubusercontent.com/46880610/199949067-07124665-4dc3-49a3-842c-87989cc7f8b1.jpg)
这个截图中的方法，想反射“java.nio.DirectByteBuffer”这个私有构造方法，
ReflectionUtil.trySetAccessible(constructor, true); 
这个静态方法里面就是判断是否允许操作SetAccessible，但是这个方法里面的判断
if (checkAccessible && !PlatformDependent0.isExplicitTryReflectionSetAccessible()) {
            return new UnsupportedOperationException("Reflective setAccessible(true) disabled");
        }
中的!PlatformDependent0.isExplicitTryReflectionSetAccessible() 是在项目启动时从系统变量获取的。
如下面这个方法。
```
private static boolean explicitTryReflectionSetAccessible0() {
    return SystemPropertyUtil.getBoolean("com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.tryReflectionSetAccessible", javaVersion() < 9);
}
```
当我设置了这个参数com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.tryReflectionSetAccessible=true时，
就绕过了你们的异常，这样最后抛出来了它本来的异常
Unable to make private java.nio.DirectByteBuffer(long,int) accessible: module java.base does not "opens java.nio" to unnamed module @550ee7e5
所以我只要在启动命令上打开一下就可以了。最后在启动命令上配置参数即可安全启动，如下：
--add-opens java.base/jdk.internal.misc=ALL-UNNAMED
--add-opens java.base/java.nio=ALL-UNNAMED
-Dcom.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.tryReflectionSetAccessible=true


idea ： 增加 vm option
java 启动命令： java ---add-opens java.base/jdk.internal.misc=ALL-UNNAMED --add-opens java.base/java.nio=ALL-UNNAMED 
-Dcom.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.tryReflectionSetAccessible=true   -jar  ....


我觉得如果你使用 jdk17 + nacos-client2.1.2 和 springboot2.7.4肯定能复现出来，启动的时候就报错，当然这个问题和springBoot没关系。

**Comment by KomachiSion** [comment]
其实是grpc和netty的问题， client只是把它们shaded进来了， 需要解决这个问题首先需要grpc和netty解决，之后nacos再升级到对应版本。

**Comment by rola0411** [comment]
> 其实是grpc和netty的问题， client只是把它们shaded进来了， 需要解决这个问题首先需要grpc和netty解决，之后nacos再升级到对应版本。

是的，但是你们的代码提前抛出个异常，如果不设置
-Dcom.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.tryReflectionSetAccessible=true
那么，下面的不生效
--add-opens java.base/java.nio=ALL-UNNAMED
系统会抛出我发的异常。我认为你们应该把它原本的异常释放出来，否则我启动会看到这个异常，有点难受，虽然不影响程序要运行。

**Comment by KomachiSion** [comment]
异常的捕获也不是nacos-client做的， 也是shaded的grpc和netty执行的， shaded不会改动原来的代码，只会改动一个package名称，所以还是需要确认依赖的内容确认修复后，nacos再升级到对应版本。
