### ISSUE TITLE
Client not connected,current status:UNHEALTHY  生产服务运行期间有段时间服务中断

### ISSUE THREAD

**Issue by zfpromise** [alibaba/nacos#9409]
11:14:03.196 [com.alibaba.nacos.client.remote.worker] WARN  c.a.n.client.naming - [onDisConnect,82] - Grpc connection disconnect, mark to redo
11:14:03.196 [com.alibaba.nacos.client.remote.worker] WARN  c.a.n.client.naming - [onDisConnect,89] - mark to redo completed
11:14:03.196 [com.alibaba.nacos.client.remote.worker] INFO  c.a.n.c.r.client - [printIfInfoEnabled,60] - [8cfa28eb-f5d3-40b5-96b8-7c9c6cbf9543]Notify connected event to listeners.
11:14:03.196 [com.alibaba.nacos.client.remote.worker] INFO  c.a.n.client.naming - [onConnected,76] - Grpc connection connect
11:14:03.273 [com.alibaba.nacos.client.naming.updater.0] ERROR c.a.n.c.r.client - [printIfErrorEnabled,99] - Send request fail, request=ServiceQueryRequest{headers={}, requestId='null'}, retryTimes=2,errorMessage=Client not connected,current status:UNHEALTHY
11:14:03.273 [com.alibaba.nacos.client.naming.updater.0] WARN  c.a.n.client.naming - [run,195] - [NA] failed to update serviceName: GLAWAY@@xxxxx
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:279)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.queryInstancesOfService(NamingGrpcClientProxy.java:169)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.queryInstancesOfService(NamingClientProxyDelegate.java:111)
	at com.alibaba.nacos.client.naming.core.ServiceInfoUpdateService$UpdateTask.run(ServiceInfoUpdateService.java:182)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected,current status:UNHEALTHY
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:655)
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:635)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:269)
	... 10 common frames omitted
11:14:03.320 [com.alibaba.nacos.client.remote.worker] INFO  c.a.n.c.r.client - [printIfInfoEnabled,60] - [8cfa28eb-f5d3-40b5-96b8-7c9c6cbf9543] success to connect a server  [nacos-server:8848],connectionId=1666840443206_10.1.1.187_44830
11:14:03.320 [com.alibaba.nacos.client.remote.worker] INFO  c.a.n.c.r.client - [printIfInfoEnabled,60] - [8cfa28eb-f5d3-40b5-96b8-7c9c6cbf9543] Abandon prev connection ,server is  nacos-server:8848, connectionId is 1666840443092_10.1.1.187_44752
11:14:03.320 [com.alibaba.nacos.client.remote.worker] INFO  c.a.n.c.r.client - [printIfInfoEnabled,60] - [8cfa28eb-f5d3-40b5-96b8-7c9c6cbf9543]Notify disconnected event to listeners
11:14:03.320 [com.alibaba.nacos.client.remote.worker] WARN  c.a.n.client.naming - [onDisConnect,82] - Grpc connection disconnect, mark to redo
11:14:03.320 [com.alibaba.nacos.client.remote.worker] WARN  c.a.n.client.naming - [onDisConnect,89] - mark to redo completed
11:14:03.320 [com.alibaba.nacos.client.remote.worker] INFO  c.a.n.c.r.client - [printIfInfoEnabled,60] - [8cfa28eb-f5d3-40b5-96b8-7c9c6cbf9543]Notify connected event to listeners.
11:14:03.320 [com.alibaba.nacos.client.remote.worker] INFO  c.a.n.client.naming - [onConnected,76] - Grpc connection connect
11:14:03.321 [com.alibaba.nacos.client.remote.worker] INFO  c.a.n.c.r.client - [printIfInfoEnabled,60] - [8cfa28eb-f5d3-40b5-96b8-7c9c6cbf9543] Server check success,currentServer isnacos-server:8848 
11:14:04.084 [nacos-grpc-client-executor-52040] WARN  c.a.n.c.r.c.g.GrpcClient - [printIfWarnEnabled,86] - [1666840443092_10.1.1.187_44752]Ignore error event,isRunning:true,isAbandon=true
11:14:05.276 [com.alibaba.nacos.client.naming.updater.0] INFO  c.a.n.client.naming - [isChangedServiceInfo,241] - removed ips(1) service: GLAWAY@@land-tenant@@DEFAULT -> [{"ip":"10.1.1.111","port":0000,"weight":1.0,"healthy":true,"enabled":true,"ephemeral":true,"clusterName":"DEFAULT","serviceName":"GLAWAY@@xxxxx","metadata":{"preserved.register.source":"SPRING_CLOUD"},"ipDeleteTimeout":30000,"instanceHeartBeatTimeOut":15000,"instanceHeartBeatInterval":5000}]
11:14:06.072 [com.alibaba.nacos.client.naming.updater.0] INFO  c.a.n.client.naming - [processServiceInfo,166] - current ips:(0) service:

**Comment by KomachiSion** [comment]
It's seems your network, server or client has something problem in runtime. You should check and find out the reason and ask for those. No one can help you find what's happen in your env.

**Comment by lxqgithub** [comment]
大佬，解决了吗？
