### ISSUE TITLE
k8s Nacos集群重启后，日志大量报错  后续发送心跳的客户端无法注册上服务

### ISSUE THREAD

**Issue by guozongkang** [alibaba/nacos#9425]
日志文件中大量存在以下异常,

2022-10-25 14:37:52,417 ERROR Nacos task execute error : org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.alibaba.nacos.naming.core.v2.upgrade.doublewrite.execute.InstanceUpgradeHelper' available

org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type 'com.alibaba.nacos.naming.core.v2.upgrade.doublewrite.execute.InstanceUpgradeHelper' available
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:350)
  at org.springframework.beans.factory.support.DefaultListableBeanFactory.getBean(DefaultListableBeanFactory.java:341)
  at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1124)
  at com.alibaba.nacos.sys.utils.ApplicationUtils.getBean(ApplicationUtils.java:150)
  at com.alibaba.nacos.naming.core.v2.upgrade.doublewrite.delay.ServiceChangeV1Task$ServiceChangeV1TaskProcessor.dispatchInstanceTask(ServiceChangeV1Task.java:163)
  at com.alibaba.nacos.naming.core.v2.upgrade.doublewrite.delay.ServiceChangeV1Task$ServiceChangeV1TaskProcessor.process(ServiceChangeV1Task.java:136)
  at com.alibaba.nacos.common.task.engine.NacosDelayTaskExecuteEngine.processTasks(NacosDelayTaskExecuteEngine.java:154)
  at com.alibaba.nacos.common.task.engine.NacosDelayTaskExecuteEngine$ProcessRunnable.run(NacosDelayTaskExecuteEngine.java:174)
  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
  at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
  at java.lang.Thread.run(Thread.java:748)

**Comment by guozongkang** [comment]
该时间发生在Nacos集群重启后几分钟都会报这个错

**Comment by KomachiSion** [comment]
upgrade to 2.1.2, and close upgrade from 1.X.

https://nacos.io/zh-cn/docs/v2/upgrading/2.0.0-upgrading.html

`nacos.core.support.upgrade.from.1x=false`
