### ISSUE TITLE
A large number of waiting threads are generated after modifying the configuration

### ISSUE THREAD

**Issue by YXxy1002** [alibaba/nacos#9464]
**Describe the bug**
I use the alicloud mse(2.0.0.0) as the register center, i got a problem today. when i modify the configuration, my app generated a large number of waiting threads and cannot access. I dump the thread info. this is the most waiting thread :
`"http-nio-9501-exec-60" #297 daemon prio=5 os_prio=0 tid=0x00007f286c1d5000 nid=0x12d waiting on condition [0x00007f28165a7000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x00000006b582cc28> (a java.util.concurrent.locks.ReentrantReadWriteLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireShared(AbstractQueuedSynchronizer.java:967)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireShared(AbstractQueuedSynchronizer.java:1283)
	at java.util.concurrent.locks.ReentrantReadWriteLock$ReadLock.lock(ReentrantReadWriteLock.java:727)
	at org.springframework.cloud.context.scope.GenericScope$LockedScopedProxyFactoryBean.invoke(GenericScope.java:494)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.proceed(CglibAopProxy.java:749)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:691)
	at com.jstd.dogerapi.manager.helper.DynamicHelper$$EnhancerBySpringCGLIB$$7a630145.getCoverVideoDynamicId(<generated>)
	at com.jstd.dogerapi.service.impl.StarDynamicV2ServiceImpl.getCoverVideo(StarDynamicV2ServiceImpl.java:2033)
	at com.jstd.dogerapi.service.impl.StarDynamicV2ServiceImpl$$FastClassBySpringCGLIB$$8d9f100c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:218)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:687)
	at com.jstd.dogerapi.service.impl.StarDynamicV2ServiceImpl$$EnhancerBySpringCGLIB$$749d808a.getCoverVideo(<generated>)
	at sun.reflect.GeneratedMethodAccessor1789.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)`

**Comment by KomachiSion** [comment]
The thread is your application thread, you should check and find out problem by yourself. not nacos problem.
