### ISSUE TITLE
configlisten disappear when redeploy nacos server

### ISSUE THREAD

**Issue by dennissky** [alibaba/nacos#9493]
1.nacos-server 2.1.1
2.nacos-client 2.0.3

when redeploy the nacos-server the listen search null,must redeploy the nacos-client i can see in this page

![image](https://user-images.githubusercontent.com/12591356/200210766-4e0aa1c7-f5cd-4383-bc94-e748a7351ca2.png)

**Comment by dennissky** [comment]
when reploy the nacos-client ican see
![image](https://user-images.githubusercontent.com/12591356/200211360-1f80f7e3-2b2c-4531-9be4-7de0ec92c916.png)

**Comment by KomachiSion** [comment]
standalone mode?

**Comment by dennissky** [comment]
> standalone mode?

cluster, with mysql

**Comment by KomachiSion** [comment]
see log `remote-digest.log` to find when these two ip re-connect to server.

I think you restart your cluster, and the connection connect to other cluster node, so can't show, and after other nodes restart, the connection re-connect back to the node which cause them show.

**Comment by dennissky** [comment]
protocol-raft.log i could see unknown leader
2022-11-04 15:03:50,224 INFO This Raft event changes : RaftEvent{groupId='naming_persistent_service', leader='null', term=null, raftClusterInfo=[xxx]}

2022-11-04 15:03:50,847 ERROR Failed to join the cluster, retry...

java.lang.IllegalStateException: Fail to get leader of group naming_persistent_service, Unknown leader, Unknown leader
	at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:631)
	at com.alipay.sofa.jraft.core.CliServiceImpl.getPeers(CliServiceImpl.java:524)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.registerSelfToCluster(JRaftServer.java:353)
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.lambda$createMultiRaftGroup$0(JRaftServer.java:264)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)

it will cause these scene？when delete cluster /data/protocol/raft ,and restart nacos cluster ,it will recover and i can see result in listener page

**Comment by dennissky** [comment]
when set nacos.core.auth.enabled=true. i restart nacos cluster. i cant see anything in listen page.but when nacos.core.auth.enabled=false, when i restart nacos cluster . i can see listen result @KomachiSion

**Comment by dennissky** [comment]
and when i when set nacos.core.auth.enabled=true,the nacos-client log will
2022-11-11 01:01:21.878 ERROR [com.alibaba.nacos.client.Worker:remote.client] Send request fail, request=ConfigBatchListenRequest{headers={}, requestId='null'}, retryTimes=0,errorMessage=java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 68925 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@7750da16[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@610fb8d5, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@26092cab, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@60c10fbc}}}}}]]
2022-11-11 01:01:21.880 INFO [com.alibaba.nacos.client.remote.worker:remote.client] [624174e7-0ca7-4b46-a75e-89161422d536_config-0] Server check success,currentServer isnacos-headless.sit-fc2mw-zctools:8848

**Comment by KomachiSion** [comment]
so the problem is request timeout, it should check network, client thread/GC and server GC problem

**Comment by dennissky** [comment]
> so the problem is request timeout, it should check network, client thread/GC and server GC problem

but when when set nacos.core.auth.enabled=false, it never appear Send request fail

**Comment by KomachiSion** [comment]
Then you should find out why enable auth request timeout. In my env, the auth open or close has not effect for RT.

**Comment by dennissky** [comment]
> Then you should find out why enable auth request timeout. In my env, the auth open or close has not effect for RT.

which log can help me location the bug

**Comment by KomachiSion** [comment]
I have no idea because I has no this problem, you can see remote.log in your app ${user.home}/logs/nacos, and with the remote-xxx.log in server to check whether request has been response in time and client whether received them.

Or trace the cost time with the arthas or other tools to check whether auth cost much time.

**Comment by dennissky** [comment]
> quest has been response in time

when Running application in more than 6h , will appear this log, and i found lots of 
DEBUG access denied, request: ConfigBatchListenRequest, reason: token expired! in  core-auth.log  more than 2w+ times

**Comment by KomachiSion** [comment]
reason: token expired!

I think your local login thread has been stopped so that you can't get generate new token after token expired.

you can get the executor `com.alibaba.nacos.client.Worker` to check login task.

or debug `alibaba.nacos.client.security.SecurityProxy login ` to check what's problem in your client.
