### ISSUE TITLE
nacos example can not running

### ISSUE THREAD

**Issue by umi-soft** [alibaba/nacos#957]
## Issue Description

Type: bug report

### Describe what happened (or what feature you want)

I download the lastest nacos on master branch，but and run nacos success.
but when i use nacos-spring-cloud-provider-example from nacos-examples, there has following error:

`java.lang.IllegalStateException: failed to req API:/api//nacos/v1/ns/api/clientBeat after all sites([127.0.0.1:8848]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.callAllServers(NamingProxy.java:247) ~[nacos-client-0.6.2.jar:na]
	at com.alibaba.nacos.client.naming.beat.BeatReactor$BeatTask.run(BeatReactor.java:99) ~[nacos-client-0.6.2.jar:na]
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_144]
	at java.util.concurrent.FutureTask.run$$$capture(FutureTask.java:266) [na:1.8.0_144]
	at java.util.concurrent.FutureTask.run(FutureTask.java) [na:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_144]
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_144]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_144]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_144]`

and i check the nacos log, has following
`2019-03-24 13:25:30,196 ERROR Responding with unauthorized error. Message - Full authentication is required to access this resource

2019-03-24 13:25:32,087 ERROR Responding with unauthorized error. Message - Full authentication is required to access this resource

2019-03-24 13:25:35,190 ERROR Responding with unauthorized error. Message - Full authentication is required to access this resource

2019-03-24 13:25:37,082 ERROR Responding with unauthorized error. Message - Full authentication is required to access this resource

2019-03-24 13:25:40,191 ERROR Responding with unauthorized error. Message - Full authentication is required to access this resource

2019-03-24 13:25:42,084 ERROR Responding with unauthorized error. Message - Full authentication is required to access this resource`

### Describe what you expected to happen

nacos example can not running ？？

### How to reproduce it (as minimally and precisely as possible)

just download lastest nacos，and examples， running, it will  reproduce

### Tell us your environment

MAC OS 10.14.2

**Comment by nkorange** [comment]
Download the 1.0.0-RC2 release again please. It's fixed.

**Comment by IAMTJW** [comment]
> Download the 1.0.0-RC2 release again please. It's fixed.

I have the same problem in 1.0.0-RC2，standalone , mac os 10.13.2，

2019-07-03 16:28:22,545 ERROR Responding with unauthorized error. Message - Full authentication is required to access this resource
