### ISSUE TITLE
nacos server http 500 status code error

### ISSUE THREAD

**Issue by liuxiong21** [alibaba/nacos#9592]
**Describe the bug**
I have three nacos-server behind nginx. I found spring cloud gateway server print nacos error log as below: 

```html
failed to request
com.alibaba.nacos.api.exception.NacosException: <html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:615)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:526)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:498)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqApi(NamingProxy.java:493)
	at com.alibaba.nacos.client.naming.net.NamingProxy.queryList(NamingProxy.java:407)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateService(HostReactor.java:378)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:460)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at 



c.a.n.c.naming[552] request: /nacos/v1/ns/instance/list failed, servers: [http://xxxx:8848], code: 500, msg: <html>
<head><title>500 Internal Server Error</title></head>
<body bgcolor="white">
<center><h1>500 Internal Server Error</h1></center>
<hr><center>nginx/1.10.3 (Ubuntu)</center>
</body>
</html>

```

nacos server cpu and memory is normal

**Desktop (please complete the following information):**
 - OS: ubuntu 16.0.1
 - Version: nacos-server 2.1.1, nacos-client 1.4.1
 - Module: naming/config
 - SDK spring-cloud-alibaba-dependencies:2021.1

**Comment by drgnchan** [comment]
showing nacos server's log message is better.

**Comment by liuxiong21** [comment]
> 

which log file，I run shell command in nacos logs dir: 

cat *.log |grep "ERROR" 

not found any helpful imformation，just found ERROR log as below


2022-11-17 07:00:14,795 ERROR [PUSH-FAIL] 20001ms, Service{namespace='public', group='DEFAULT_GROUP', name='accounts', ephemeral=true, revision=0}, reason=null, target=10.0.2.140
2022-11-17 07:00:14,795 ERROR [PUSH-FAIL] 20000ms, Service{namespace='public', group='DEFAULT_GROUP', name='accounts', ephemeral=true, revision=0}, reason=null, target=10.0.5.27


but at start.out file print warn log keep two seconds print one warn log

2022-11-17 12:04:02,170 WARN There are no [com.alibaba.nacos.common.trace.event.naming.PushServiceTraceEvent] publishers for this event, please register

**Comment by liuxiong21** [comment]
> showing nacos server's log message is better.

which log file，I run shell command in nacos logs dir: 

cat *.log |grep "ERROR" 

not found any helpful imformation，just found ERROR log as below


2022-11-17 07:00:14,795 ERROR [PUSH-FAIL] 20001ms, Service{namespace='public', group='DEFAULT_GROUP', name='accounts', ephemeral=true, revision=0}, reason=null, target=10.0.2.140
2022-11-17 07:00:14,795 ERROR [PUSH-FAIL] 20000ms, Service{namespace='public', group='DEFAULT_GROUP', name='accounts', ephemeral=true, revision=0}, reason=null, target=10.0.5.27


but at start.out file print warn log keep two seconds print one warn log

2022-11-17 12:04:02,170 WARN There are no [com.alibaba.nacos.common.trace.event.naming.PushServiceTraceEvent] publishers for this event, please register

**Comment by KomachiSion** [comment]
your udp network has problem， can connect from server to client，env problem you should check by yourself.

**Comment by liuxiong21** [comment]
> your udp network has problem， can connect from server to client，env problem you should check by yourself.

PUSH-FAIL ?

this ERROR is uncorrelated  with nacos http 500 status code ，PUSH-FAIL ERROR occur  I think is  because my microservices is deployed in k8s, pod is peroid destory.

**Comment by KomachiSion** [comment]
The 500 code is not throw by nacos but nginx, you should check your nginx not submit issue to nacos.

Or you can get the original information.
