### ISSUE TITLE
Failed to bind properties under 'spring.datasource' to javax.sql.DataSource

### ISSUE THREAD

**Issue by szqjige-nb** [alibaba/nacos#9625]
localhost.localdomain 09:02:32.473 [com.alibaba.nacos.client.Worker.longPolling.fixed-xxx.xxx.xxx.xxx_port8] INFO  c.a.n.c.config.impl.ClientWorker - get changedGroupKeys:[]
localhost.localdomain 09:02:32.474 [com.alibaba.nacos.client.Worker.longPolling.fixed-xxx.xxx.xxx.xxx_port8] INFO  c.a.n.client.config.impl.CacheData - [fixed-xxx.xxx.xxx.xxx_port8] [notify-context] dataId=xxx-xxx-xxx-xxx-xxx-test.yaml, group=DEFAULT_GROUP, md5=5a238ee41771d1e7f80ade7d137f8603
localhost.localdomain 09:02:32.632 [com.alibaba.nacos.client.Worker.longPolling.fixed-xxx.xxx.xxx.xxx_port8] INFO  o.s.c.s.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration' of type [org.springframework.cloud.autoconfigure.ConfigurationPropertiesRebinderAutoConfiguration$$EnhancerBySpringCGLIB$$b7193fc4] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
localhost.localdomain 09:02:32.734 [com.alibaba.nacos.client.Worker.longPolling.fixed-xxx.xxx.xxx.xxx_port8] WARN  c.a.c.n.c.NacosPropertySourceBuilder - Ignore the empty nacos configuration and get it based on dataId[xxx-xxx-xxx-xxx-xxx] & group[DEFAULT_GROUP]
localhost.localdomain 09:02:32.737 [com.alibaba.nacos.client.Worker.longPolling.fixed-xxx.xxx.xxx.xxx_port8] WARN  c.a.c.n.c.NacosPropertySourceBuilder - Ignore the empty nacos configuration and get it based on dataId[xxx-xxx-xxx-xxx-xxx.yaml] & group[DEFAULT_GROUP]
localhost.localdomain 09:02:32.748 [com.alibaba.nacos.client.Worker.longPolling.fixed-xxx.xxx.xxx.xxx_port8] INFO  o.s.c.b.c.PropertySourceBootstrapConfiguration - Located property source: CompositePropertySource {name='NACOS', propertySources=[NacosPropertySource {name='xxx-xxx-xxx-xxx-xxx-test.yaml,DEFAULT_GROUP'}, NacosPropertySource {name='xxx-xxx-xxx-xxx-xxx.yaml,DEFAULT_GROUP'}, NacosPropertySource {name='xxx-xxx-xxx-xxx-xxx,DEFAULT_GROUP'}, NacosPropertySource {name='xxx-common.yaml,DEFAULT_GROUP'}]}
localhost.localdomain 09:02:32.755 [com.alibaba.nacos.client.Worker.longPolling.fixed-xxx.xxx.xxx.xxx_port8] INFO  o.s.boot.SpringApplication - The following profiles are active: test
localhost.localdomain 09:02:32.789 [com.alibaba.nacos.client.Worker.longPolling.fixed-xxx.xxx.xxx.xxx_port8] INFO  o.s.boot.SpringApplication - Started application in 0.308 seconds (JVM running for 786.789)
localhost.localdomain 09:02:32.930 [com.alibaba.nacos.client.Worker.longPolling.fixed-xxx.xxx.xxx.xxx_port8] ERROR c.a.n.client.config.impl.CacheData - [fixed-xxx.xxx.xxx.xxx_port8] [notify-error] dataId=xxx-xxx-xxx-xxx-xxx-test.yaml, group=DEFAULT_GROUP, md5=5a238ee41771d1e7f80ade7d137f8603, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@605915ff tx={}
org.springframework.boot.context.properties.bind.BindException: Failed to bind properties under 'spring.datasource' to javax.sql.DataSource
        at org.springframework.boot.context.properties.bind.Binder.handleBindError(Binder.java:249)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:225)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:208)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:190)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBinder.bind(ConfigurationPropertiesBinder.java:83)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.bind(ConfigurationPropertiesBindingPostProcessor.java:107)
        at org.springframework.boot.context.properties.ConfigurationPropertiesBindingPostProcessor.postProcessBeforeInitialization(ConfigurationPropertiesBindingPostProcessor.java:93)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:414)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1754)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:405)
        at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:102)
        at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.rebind(ConfigurationPropertiesRebinder.java:84)
        at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:128)
        at org.springframework.cloud.context.properties.ConfigurationPropertiesRebinder.onApplicationEvent(ConfigurationPropertiesRebinder.java:50)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
        at org.springframework.cloud.context.refresh.ContextRefresher.refreshEnvironment(ContextRefresher.java:79)
        at org.springframework.cloud.context.refresh.ContextRefresher.refresh(ContextRefresher.java:68)
        at org.springframework.cloud.endpoint.event.RefreshEventListener.handle(RefreshEventListener.java:50)
        at org.springframework.cloud.endpoint.event.RefreshEventListener.onApplicationEvent(RefreshEventListener.java:39)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:172)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:165)
        at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:139)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:402)
        at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:359)
        at com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1.innerReceive(NacosContextRefresher.java:133)
        at com.alibaba.nacos.api.config.listener.AbstractSharedListener.receiveConfigInfo(AbstractSharedListener.java:38)
        at com.alibaba.nacos.client.config.impl.CacheData$1.run(CacheData.java:203)
        at com.alibaba.nacos.client.config.impl.CacheData.safeNotifyListener(CacheData.java:233)
        at com.alibaba.nacos.client.config.impl.CacheData.checkListenerMd5(CacheData.java:174)
        at com.alibaba.nacos.client.config.impl.ClientWorker$LongPollingRunnable.run(ClientWorker.java:552)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.IllegalStateException: Unable to set value for property driver-class-name
        at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.setValue(JavaBeanBinder.java:333)
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:89)
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:72)
        at org.springframework.boot.context.properties.bind.JavaBeanBinder.bind(JavaBeanBinder.java:54)
        at org.springframework.boot.context.properties.bind.Binder.lambda$null$4(Binder.java:344)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
        at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
        at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
        at java.util.stream.FindOps$FindOp.evaluateSequential(FindOps.java:152)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.findFirst(ReferencePipeline.java:464)
        at org.springframework.boot.context.properties.bind.Binder.lambda$bindBean$5(Binder.java:345)
        at org.springframework.boot.context.properties.bind.Binder$Context.withIncreasedDepth(Binder.java:448)
        at org.springframework.boot.context.properties.bind.Binder$Context.withBean(Binder.java:434)
        at org.springframework.boot.context.properties.bind.Binder$Context.access$400(Binder.java:388)
        at org.springframework.boot.context.properties.bind.Binder.bindBean(Binder.java:342)
        at org.springframework.boot.context.properties.bind.Binder.bindObject(Binder.java:277)
        at org.springframework.boot.context.properties.bind.Binder.bind(Binder.java:220)
        ... 39 common frames omitted
Caused by: java.lang.reflect.InvocationTargetException: null
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.context.properties.bind.JavaBeanBinder$BeanProperty.setValue(JavaBeanBinder.java:330)
        ... 59 common frames omitted
Caused by: java.lang.IllegalStateException: The configuration of the pool is sealed once started. Use HikariConfigMXBean for runtime changes.
        at com.zaxxer.hikari.HikariConfig.checkIfSealed(HikariConfig.java:1014)
        at com.zaxxer.hikari.HikariConfig.setDriverClassName(HikariConfig.java:472)
        ... 64 common frames omitted
localhost.localdomain 09:02:32.943 [com.alibaba.nacos.client.Worker.longPolling.fixed-xxx.xxx.xxx.xxx_port8] INFO  c.a.n.client.config.impl.CacheData - [fixed-XXX.XXX.XX.242_8848] [notify-listener] time cost=469ms in ClientWorker, dataId=xxx-xxx-xxx-xxx-xxx-test.yaml, group=DEFAULT_GROUP, md5=5a238ee41771d1e7f80ade7d137f8603, listener=com.alibaba.cloud.nacos.refresh.NacosContextRefresher$1@605915f

下面是整个平台版本:
spirngboot: 2.1.3.RELEASE
<spring-cloud.version> ：Greenwich.RELEASE
    <spring-cloud-alibaba.version>:2.1.2.RELEASE
    <spring-platform.version>:Cairo-SR7

问题描述：更新更新nacos配置文件中的值 30秒左右一直报错
Failed to bind properties under 'spring.datasource' to javax.sql.DataSource
Caused by: java.lang.IllegalStateException: Unable to set value for property driver-class-name

**Comment by KomachiSion** [comment]
it is not nacos‘ problem, the config has push to app, but app spring can't bind the properties to `javax.sql.DataSource`
