### ISSUE TITLE
nacos and zipkin exception

### ISSUE THREAD

**Issue by Fyuxuan** [alibaba/nacos#968]
## Issue Description

request data to zipkin success，but nacos exception

Type: *bug report* or *feature request*

### Describe what happened (or what feature you want)

2019-03-28 14:11:48.637 ERROR [ins-user,,,] 43273 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : [] [] [CALL-SERVER] failed to req API:http://192.168.0.253:8848/nacos/v1/ns/api/srvIPXT. code:404 msg: dom not found: 192.168.0.251
2019-03-28 14:11:48.638 ERROR [ins-user,,,] 43273 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : [] [] [NA] req api:/nacos/v1/ns/api/srvIPXT failed, server(192.168.0.253:8848

com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:327)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2019-03-28 14:11:48.715 ERROR [ins-user,,,] 43273 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : [] [] [CALL-SERVER] failed to req API:http://192.168.0.253:8849/nacos/v1/ns/api/srvIPXT. code:404 msg: dom not found: 192.168.0.251
2019-03-28 14:11:48.715 ERROR [ins-user,,,] 43273 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : [] [] [NA] req api:/nacos/v1/ns/api/srvIPXT failed, server(192.168.0.253:8849

com.alibaba.nacos.api.exception.NacosException: null
	at com.alibaba.nacos.client.naming.net.NamingProxy.callServer(NamingProxy.java:304)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:327)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

2019-03-28 14:11:48.716 ERROR [ins-user,,,] 43273 --- [com.alibaba.nacos.client.naming.updater] com.alibaba.nacos.client.naming          : [] [] [NA] failed to update serviceName: 192.168.0.251

java.lang.IllegalStateException: failed to req API:/nacos/v1/ns/api/srvIPXT after all servers([192.168.0.253:8848, 192.168.0.253:8849, 192.168.0.253:8850]) tried
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:335)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:310)
	at com.alibaba.nacos.client.naming.net.NamingProxy.reqAPI(NamingProxy.java:257)
	at com.alibaba.nacos.client.naming.core.HostReactor.updateServiceNow(HostReactor.java:340)
	at com.alibaba.nacos.client.naming.core.HostReactor$UpdateTask.run(HostReactor.java:429)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

### How to reproduce it (as minimally and precisely as possible)

1. register center and config center by nacos，and have conf data gain 
   
```
cloud:
    nacos:
      discovery:
        server-addr: 192.168.0.253:8848,192.168.0.253:8849,192.168.0.253:8850
      config:
        server-addr: 192.168.0.253:8848,192.168.0.253:8849,192.168.0.253:8850
        file-extension: yaml
        shared-dataids: all-service-common.yaml 
        refreshable-dataids: all-service-common.yaml 
 ```
2. add zipkin 
```
   <dependency>
		    <groupId>org.springframework.cloud</groupId>
		    <artifactId>spring-cloud-starter-zipkin</artifactId>
  </dependency>
zipkin:
    discovery-client-enabled: false
    base-url: http://192.168.0.251:9411/
  sleuth:
    sampler:
      probability: 1
```
3. arbitrarily springmvc  request，appear Exception

### Tell us your environment
SpringBoot 2.1.3.RELEASE
SpringCloud Greenwich.RELEASE
spring-cloud-alibaba 0.2.1.RELEASE
nacos-server 0.8

**Comment by nkorange** [comment]
This is a [spring-cloud-alibaba](https://github.com/spring-cloud-incubator/spring-cloud-alibaba) issue
