### ISSUE TITLE
java.lang.IllegalArgumentException: port out of range:-920 在线等，非常急

### ISSUE THREAD

**Issue by q6527127** [alibaba/nacos#9680]
我只指定了server.port=80
并没有指定任何关于-920的端口，启动时候端口超出范围
下面是启动日志
这是什么原因，在线等，非常急

/usr/local/java/jdk1.8.0_201/bin/java -Djava.ext.dirs=/usr/local/java/jdk1.8.0_201/jre/lib/ext:/usr/local/java/jdk1.8.0_201/lib/ext  -Xms512m -Xmx512m -Xmn256m -Dnacos.standalone=true -Dnacos.member.list= -Xloggc:/usr/local/nacos/logs/nacos_gc.log -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCDateStamps -XX:+PrintGCTimeStamps -XX:+UseGCLogFileRotation -XX:NumberOfGCLogFiles=10 -XX:GCLogFileSize=100M -Dloader.path=/usr/local/nacos/plugins/health,/usr/local/nacos/plugins/cmdb,/usr/local/nacos/plugins/selector -Dnacos.home=/usr/local/nacos -jar /usr/local/nacos/target/nacos-server.jar  --spring.config.additional-location=file:/usr/local/nacos/conf/ --logging.config=/usr/local/nacos/conf/nacos-logback.xml --server.max-http-header-size=524288 
nacos is starting with standalone 
 
         ,--. 
       ,--.'| 
   ,--,:  : |                                           Nacos 2.1.0 
,`--.'`|  ' :                       ,---.               Running in stand alone mode, All function modules 
|   :  :  | |                      '   ,'\   .--.--.    Port: 80 
:   |   \ | :  ,--.--.     ,---.  /   /   | /  /    '   Pid: 24 
|   : '  '; | /       \   /     \.   ; ,. :|  :  /`./   Console: http://10.42.153.168:80/nacos/index.html 
'   ' ;.    ;.--.  .-. | /    / ''   | |: :|  :  ;_ 
|   | | \   | \__\/: . ..    ' / '   | .; : \  \    `.      https://nacos.io 
'   : |  ; .' ," .--.; |'   ; :__|   :    |  `----.   \ 
|   | '`--'  /  /  ,.  |'   | '.'|\   \  /  /  /`--'  / 
'   : |     ;  :   .'   \   :    : `----'  '--'.     / 
;   |.'     |  ,     .-./\   \  /            `--'---' 
'---'        `--`---'     `----' 
 
2022-12-08 07:38:38,612 INFO Bean 'org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler@5c77053b' of type [org.springframework.security.access.expression.method.DefaultMethodSecurityExpressionHandler] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
 
2022-12-08 07:38:38,622 INFO Bean 'methodSecurityMetadataSource' of type [org.springframework.security.access.method.DelegatingMethodSecurityMetadataSource] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying) 
 
2022-12-08 07:38:39,515 INFO Tomcat initialized with port(s): 80 (http) 
 
2022-12-08 07:38:40,519 INFO Root WebApplicationContext: initialization completed in 10729 ms 
 
2022-12-08 07:38:45,707 WARN There are no [com.alibaba.nacos.config.server.model.event.LocalDataChangeEvent] publishers for this event, please register 
 
2022-12-08 07:38:45,709 WARN There are no [com.alibaba.nacos.config.server.model.event.LocalDataChangeEvent] publishers for this event, please register 
 
2022-12-08 07:38:45,710 WARN There are no [com.alibaba.nacos.config.server.model.event.LocalDataChangeEvent] publishers for this event, please register 
 
2022-12-08 07:38:48,299 WARN Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'serviceOperatorV2Impl' defined in URL [jar:file:/usr/local/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.1.0.jar!/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'namingMetadataOperateService' defined in URL [jar:file:/usr/local/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.1.0.jar!/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.metadata.NamingMetadataOperateService]: Constructor threw exception; nested exception is com.alibaba.nacos.core.distributed.raft.exception.JRaftException: java.lang.IllegalArgumentException: port out of range:-920 
 
2022-12-08 07:38:48,332 INFO Nacos Log files: /usr/local/nacos/logs 
 
2022-12-08 07:38:48,333 INFO Nacos Log files: /usr/local/nacos/conf 
 
2022-12-08 07:38:48,333 INFO Nacos Log files: /usr/local/nacos/data 
 
2022-12-08 07:38:48,333 ERROR Startup errors : 
 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'serviceOperatorV2Impl' defined in URL [jar:file:/usr/local/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.1.0.jar!/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'namingMetadataOperateService' defined in URL [jar:file:/usr/local/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.1.0.jar!/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.metadata.NamingMetadataOperateService]: Constructor threw exception; nested exception is com.alibaba.nacos.core.distributed.raft.exception.JRaftException: java.lang.IllegalArgumentException: port out of range:-920 
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769) 
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321) 
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) 
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866) 
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) 
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) 
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) 
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) 
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) 
	at com.alibaba.nacos.Nacos.main(Nacos.java:35) 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.lang.reflect.Method.invoke(Method.java:498) 
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) 
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) 
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'namingMetadataOperateService' defined in URL [jar:file:/usr/local/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.1.0.jar!/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.metadata.NamingMetadataOperateService]: Constructor threw exception; nested exception is com.alibaba.nacos.core.distributed.raft.exception.JRaftException: java.lang.IllegalArgumentException: port out of range:-920 
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:304) 
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321) 
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) 
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) 
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276) 
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196) 
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857) 
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760) 
	... 27 common frames omitted 
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.metadata.NamingMetadataOperateService]: Constructor threw exception; nested exception is com.alibaba.nacos.core.distributed.raft.exception.JRaftException: java.lang.IllegalArgumentException: port out of range:-920 
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:187) 
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) 
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300) 
	... 41 common frames omitted 
Caused by: com.alibaba.nacos.core.distributed.raft.exception.JRaftException: java.lang.IllegalArgumentException: port out of range:-920 
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.start(JRaftServer.java:225) 
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.init(JRaftProtocol.java:122) 
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.init(JRaftProtocol.java:92) 
	at com.alibaba.nacos.core.distributed.ProtocolManager.lambda$initCPProtocol$3(ProtocolManager.java:128) 
	at com.alibaba.nacos.sys.utils.ApplicationUtils.getBeanIfExist(ApplicationUtils.java:156) 
	at com.alibaba.nacos.core.distributed.ProtocolManager.initCPProtocol(ProtocolManager.java:124) 
	at com.alibaba.nacos.core.distributed.ProtocolManager.getCpProtocol(ProtocolManager.java:85) 
	at com.alibaba.nacos.naming.core.v2.metadata.NamingMetadataOperateService.<init>(NamingMetadataOperateService.java:46) 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:175) 
	... 43 common frames omitted 
Caused by: java.lang.IllegalArgumentException: port out of range:-920 
	at com.alipay.sofa.jraft.util.Requires.requireTrue(Requires.java:85) 
	at com.alipay.sofa.jraft.rpc.impl.GrpcRaftRpcFactory.createRpcServer(GrpcRaftRpcFactory.java:89) 
	at com.alipay.sofa.jraft.rpc.RaftRpcFactory.createRpcServer(RaftRpcFactory.java:64) 
	at com.alibaba.nacos.core.distributed.raft.utils.JRaftUtils.initRpcServer(JRaftUtils.java:79) 
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.start(JRaftServer.java:212) 
	... 55 common frames omitted 
2022-12-08 07:38:49,838 WARN [WatchFileCenter] start close 
 
2022-12-08 07:38:49,838 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /usr/local/nacos/data/loader 
 
2022-12-08 07:38:49,839 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /usr/local/nacos/conf 
 
2022-12-08 07:38:49,839 WARN [WatchFileCenter] start to shutdown this watcher which is watch : /usr/local/nacos/data/tps 
 
2022-12-08 07:38:49,839 WARN [WatchFileCenter] already closed 
 
2022-12-08 07:38:49,839 WARN [NotifyCenter] Start destroying Publisher 
 
2022-12-08 07:38:49,839 WARN [NotifyCenter] Destruction of the end 
 
2022-12-08 07:38:49,839 ERROR Nacos failed to start, please see /usr/local/nacos/logs/nacos.log for more details. 
 
2022-12-08 07:38:49,884 INFO 
 
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled. 
 
2022-12-08 07:38:49,886 ERROR Application run failed 
 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'serviceOperatorV2Impl' defined in URL [jar:file:/usr/local/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.1.0.jar!/com/alibaba/nacos/naming/core/ServiceOperatorV2Impl.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'namingMetadataOperateService' defined in URL [jar:file:/usr/local/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.1.0.jar!/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.metadata.NamingMetadataOperateService]: Constructor threw exception; nested exception is com.alibaba.nacos.core.distributed.raft.exception.JRaftException: java.lang.IllegalArgumentException: port out of range:-920 
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:769) 
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:218) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321) 
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) 
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:866) 
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878) 
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) 
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141) 
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:744) 
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:391) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:312) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) 
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) 
	at com.alibaba.nacos.Nacos.main(Nacos.java:35) 
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) 
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) 
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) 
	at java.lang.reflect.Method.invoke(Method.java:498) 
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) 
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) 
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467) 
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'namingMetadataOperateService' defined in URL [jar:file:/usr/local/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.1.0.jar!/com/alibaba/nacos/naming/core/v2/metadata/NamingMetadataOperateService.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.metadata.NamingMetadataOperateService]: Constructor threw exception; nested exception is com.alibaba.nacos.core.distributed.raft.exception.JRaftException: java.lang.IllegalArgumentException: port out of range:-920 
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:304) 
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:285) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1338) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1185) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:554) 
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:514) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:321) 
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:319) 
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) 
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:277) 
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1276) 
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1196) 
	at org.springframework.beans.factory.support.ConstructorResolver.resolveAutowiredArgument(ConstructorResolver.java:857) 
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:760) 
	... 27 common frames omitted 
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.metadata.NamingMetadataOperateService]: Constructor threw exception; nested exception is com.alibaba.nacos.core.distributed.raft.exception.JRaftException: java.lang.IllegalArgumentException: port out of range:-920 
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:187) 
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117) 
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:300) 
	... 41 common frames omitted 
Caused by: com.alibaba.nacos.core.distributed.raft.exception.JRaftException: java.lang.IllegalArgumentException: port out of range:-920 
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.start(JRaftServer.java:225) 
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.init(JRaftProtocol.java:122) 
	at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.init(JRaftProtocol.java:92) 
	at com.alibaba.nacos.core.distributed.ProtocolManager.lambda$initCPProtocol$3(ProtocolManager.java:128) 
	at com.alibaba.nacos.sys.utils.ApplicationUtils.getBeanIfExist(ApplicationUtils.java:156) 
	at com.alibaba.nacos.core.distributed.ProtocolManager.initCPProtocol(ProtocolManager.java:124) 
	at com.alibaba.nacos.core.distributed.ProtocolManager.getCpProtocol(ProtocolManager.java:85) 
	at com.alibaba.nacos.naming.core.v2.metadata.NamingMetadataOperateService.<init>(NamingMetadataOperateService.java:46) 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) 
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) 
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) 
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) 
	at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:175) 
	... 43 common frames omitted 
Caused by: java.lang.IllegalArgumentException: port out of range:-920 
	at com.alipay.sofa.jraft.util.Requires.requireTrue(Requires.java:85) 
	at com.alipay.sofa.jraft.rpc.impl.GrpcRaftRpcFactory.createRpcServer(GrpcRaftRpcFactory.java:89) 
	at com.alipay.sofa.jraft.rpc.RaftRpcFactory.createRpcServer(RaftRpcFactory.java:64) 
	at com.alibaba.nacos.core.distributed.raft.utils.JRaftUtils.initRpcServer(JRaftUtils.java:79) 
	at com.alibaba.nacos.core.distributed.raft.JRaftServer.start(JRaftServer.java:212) 
	... 55 common frames omitted

**Comment by mayl0415** [comment]
好像会启动一个-1000的端口吧

**Comment by q6527127** [comment]
> 好像会启动一个-1000的端口吧

在哪里改这个端口？

**Comment by mayl0415** [comment]
server.port加偏移量自动生成的，不用80端口呗

**Comment by q6527127** [comment]
> server.port加偏移量自动生成的，不用80端口呗

谢谢，确实是这个问题，我试了下不用80端口好了

**Comment by q6527127** [comment]
已解决
