### ISSUE TITLE
nacos1.4.1升级到2.1或2.0,以前的配置文件数据没有了

### ISSUE THREAD

**Issue by yfgcq** [alibaba/nacos#9681]
单机版本nacos1.4.1升级到2.1.2,以前的配置文件数据没有了

配置文件添加了
nacos.core.support.upgrade.from.1x=true

执行了以前操作:
1、nacos/bin/shutdown.sh
2、将其下的bin，conf，target目录覆盖原Nacos1.X的安装目录下
3、修改了配置文件application.prpperties的mysql配置，
添加了nacos.core.support.upgrade.from.1x=true
4、sh startup.sh -m standalone

tail -f logs/start.out
2022-12-09 10:33:53,040 INFO Will not secure Ant [pattern='/**']
2022-12-09 10:33:53,072 INFO Will secure any request with [org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@63cd604c, org.springframework.security.web.context.SecurityContextPersistenceFilter@10c8f62, org.springframework.security.web.header.HeaderWriterFilter@4ef27d66, org.springframework.security.web.csrf.CsrfFilter@1568159, org.springframework.security.web.authentication.logout.LogoutFilter@25bcd0c7, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@25f7391e, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@5ab14cb9, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@40dd3977, org.springframework.security.web.session.SessionManagementFilter@1d9bec4d, org.springframework.security.web.access.ExceptionTranslationFilter@5d5d9e5]
2022-12-09 10:33:53,097 INFO Exposing 1 endpoint(s) beneath base path '/actuator'
2022-12-09 10:33:53,173 INFO Tomcat started on port(s): 8858 (http) with context path '/nacos'
2022-12-09 10:33:53,199 INFO Nacos started successfully in stand alone mode. use embedded storage
2022-12-09 10:34:24,666 INFO Initializing Servlet 'dispatcherServlet'
2022-12-09 10:34:24,671 INFO Completed initialization in 5 ms

tail -f logs/nacos.log
2022-12-09 10:33:53,198 INFO Started Nacos in 10.692 seconds (JVM running for 11.325)
2022-12-09 10:33:53,199 INFO Nacos started successfully in stand alone mode. use embedded storage
2022-12-09 10:34:24,666 INFO Initializing Spring DispatcherServlet 'dispatcherServlet'
2022-12-09 10:34:24,666 INFO Initializing Servlet 'dispatcherServlet'
2022-12-09 10:34:24,671 INFO Completed initialization in 5 ms

tail -f logs/naming-server.log
2022-12-09 10:33:50,881 INFO [SelectorManager] Load SelectorContextBuilder(class com.alibaba.nacos.naming.selector.context.CmdbSelectorContextBuilder) contextType(CMDB) successfully.
2022-12-09 10:33:50,881 INFO [SelectorManager] Load SelectorContextBuilder(class com.alibaba.nacos.naming.selector.context.NoneSelectorContextBuilder) contextType(NONE) successfully.
2022-12-09 10:33:50,881 INFO [SelectorManager] Load Selector(class com.alibaba.nacos.naming.selector.LabelSelector) type(label) contextType(CMDB) successfully.
2022-12-09 10:33:50,881 INFO [SelectorManager] Load Selector(class com.alibaba.nacos.naming.selector.NoneSelector) type(none) contextType(NONE) successfully.
2022-12-09 10:33:52,048 INFO Load instance extension handler []

//nacos/v1/ns/upgrade/ops/metrics
upgraded                       = true
isAll20XVersion                = true
isDoubleWriteEnabled           = true
doubleWriteDelayTaskCount      =     0
serviceCountV1                 =     0
instanceCountV1                =     0
serviceCountV2                 =     0
instanceCountV2                =     0
subscribeCountV2               =     0
responsibleServiceCountV1      =     0
responsibleInstanceCountV1     =     0
ephemeralServiceCountV2        =     0
persistentServiceCountV2       =     0
ephemeralInstanceCountV2       =     0
persistentInstanceCountV2      =     0
service.V1.not.in.V2           = 
service.V2.not.in.V1           =

**Comment by KomachiSion** [comment]
standalone模式默认使用过的是derby数据库， derby数据库数据存放在nacos/data目录下， 如果这个目录删除了或者变动了，数据没了是正常的。建议用mysql数据库在存储。

**Comment by yfgcq** [comment]
1、之前升级后的配置文件这里没开启 spring.datasource.platform=mysql
2、现在升级后，提示这个错误。1.4.2升级到2.1.2数据库结构不自动升级吗？
tail -f logs/start.out
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'encrypted_data_key' in 'field list'
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:120)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:122)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeQuery(ClientPreparedStatement.java:1009)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeQuery(ProxyPreparedStatement.java:52)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeQuery(HikariProxyPreparedStatement.java)
	at org.springframework.jdbc.core.JdbcTemplate$1.doInPreparedStatement(JdbcTemplate.java:722)
	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:651)
	... 71 common frames omitted

**Comment by KomachiSion** [comment]
不会自动升级。

**Comment by yfgcq** [comment]
> 不会自动升级。
那1.4.2升级到2.1.2数据库如何升级勒

**Comment by KomachiSion** [comment]
变更一下表结构，新增一个字段。

字段内容在新版本的sql文件中有。

**Comment by kylincodelab** [comment]
> 变更一下表结构，新增一个字段。
> 
> 字段内容在新版本的sql文件中有。

请教下，是什么字段？
