### ISSUE TITLE
Failed to obtain the service instance by using the user with rw permission and reported "authentication failed!"

### ISSUE THREAD

**Issue by TC-wang** [alibaba/nacos#9696]
**Describe the bug**
Failed to obtain the service instance by using the user with rw permission and reported "authentication failed!"

**Expected behavior**
Getting service instance succeeded

**Actually behavior**
Client reported "authentication failed!"

```
Exception in thread "main" ErrCode:500, ErrMsg:Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:288)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.doSubscribe(NamingGrpcClientProxy.java:229)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.subscribe(NamingGrpcClientProxy.java:214)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.subscribe(NamingClientProxyDelegate.java:147)
	at com.alibaba.nacos.client.naming.NacosNamingService.selectInstances(NacosNamingService.java:290)
	at com.alibaba.nacos.client.naming.NacosNamingService.selectInstances(NacosNamingService.java:278)
	at com.alibaba.nacos.client.naming.NacosNamingService.selectInstances(NacosNamingService.java:266)
	at com.alibaba.nacos.client.naming.NacosNamingService.selectInstances(NacosNamingService.java:243)
	at com.bytedance.mse.ProviderApplication.main(ProviderApplication.java:26)
Caused by: ErrCode:403, ErrMsg:authorization failed!
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:280)
	... 8 more
```

**How to Reproduce**
1.  The ”test“ user has rw permission under public namespace;

2. The error code is as follows：

```
public class Test {
        public static void main(String[] args) throws Exception {
            Properties properties = new Properties();
            properties.put("serverAddr", "127.0.0.1:8848");
            properties.put("namespace", "");
            properties.put("username", "test");
            properties.put("password", "123456");
            NamingService namingService = NamingFactory.createNamingService(properties);
            List<Instance> list = namingService.selectInstances("provider", true);
            System.out.println(list);
    }
}
```

**Desktop (please complete the following information):**
 - Version [nacos-server 2.1.0, nacos-client 2.1.0]
 - Module [naming]
 - SDK [nacos-client 2.1.0]

**Additional context**

**Comment by KomachiSion** [comment]
duplicate with #3525

you can use other namespace use first.
