### ISSUE TITLE
spring-framework start failed, when PropertySourcesPlaceHolderConfigure bean init ,there has a conflict cause by globalNacosProperties$config ,systemProperties

### ISSUE THREAD

**Issue by qiguisen** [alibaba/nacos#9714]
spring-framework app start failed, when PropertySourcesPlaceHolderConfigure bean init ,there has a conflict cause by globalNacosProperties$config ,systemProperties

**Comment by KomachiSion** [comment]
Please provide your  all version information.

**Comment by KomachiSion** [comment]
and provide logs

**Comment by qiguisen** [comment]
Caused by: org.springframework.beans.factory.NoUniqueBeanDefinitionException: No qualifying bean of type 'java.util.Properties' available: expected single matching bean but found 2: globalNacosProperties,systemProperties
 at org.springframework.beans.factory.config.DependencyDescriptor.resolveNotUnique(DependencyDescriptor.java:220) ~[spring-beans-5.3.16.jar:5.3.16]
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1367) ~[spring-beans-5.3.16.jar:5.3.16]
 at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1309) ~[spring-beans-5.3.16.jar:5.3.16]
 at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireByType(AbstractAutowireCapableBeanFactory.java:1519) ~[spring-beans-5.3.16.jar:5.3.16]
 ... 27 more

<bean id="propertyPlaceHolderConfigurer" class ="org.springframework.context.support.PropertySourcesPlaceholderConfigurer">
  <property name="order" value="1"/>
  <property name="ignoreUnresolvablePlaceholders" value="true"/>
  <property name="ignoreResourceNotFound" value="true"/>
  <property name="locations">
         <list>
            <value>/WEB-INF/properties/redis.properties</value>
            <value>/WEB-INF/properties/rabbitmq.properties</value>
            <value>/WEB-INF/properties/nacos.properties</value>
         </list>
     </property>
 </bean>

spring 5.3.16 nacos 2.2.0

**Comment by qiguisen** [comment]
bean config
<bean id="propertyPlaceHolderConfigurer" class ="org.springframework.context.support.PropertySourcesPlaceholderConfigurer">
  <property name="order" value="1"/>
  <property name="ignoreUnresolvablePlaceholders" value="true"/>
  <property name="ignoreResourceNotFound" value="true"/>
  <property name="locations">
         <list>
            <value>/WEB-INF/properties/redis.properties</value>
            <value>/WEB-INF/properties/rabbitmq.properties</value>
            <value>/WEB-INF/properties/nacos.properties</value>
         </list>
     </property>
 </bean>

**Comment by KomachiSion** [comment]
It's your application problem, your application can build bean because there are two properties.

**Comment by qiguisen** [comment]
there is another sdk needs PropertySourcesPlaceHolderConfigure.any suggestion for this problems?
