### ISSUE TITLE
docker nacos-server 启动失败

### ISSUE THREAD

**Issue by pigping88** [alibaba/nacos#9718]
mac m1，镜像：nacos/nacos-server:v2.2.0-slim
`podman run -d --name nacos -p 8848:8848 --restart always -e MODE=standalone nacos/nacos-server:v2.2.0-slim`

```
2022-12-16 21:14:05,268 ERROR Application run failed
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.2.0.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
errCode: 102, errMsg: [MapperManager] Failed to find the datasource,dataSource:"" 
	at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
	at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
	at com.alibaba.nacos.Nacos.main(Nacos.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
	at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
```

**Comment by wuchubuzai2018** [comment]
感觉应该是未配置和启动数据源，比如未配置：
# spring.datasource.platform=mysql（新属性）
或
#spring.sql.init.platform=mysql（新属性）

**Comment by huangwenkan9** [comment]
同样的问题，standalone也需要配置数据源吗？配置了好像也不行~

**Comment by The-Gamer-01** [comment]
> 同样的问题，standalone也需要配置数据源吗？配置了好像也不行~

请问能描述一下版本、环境、修改过的配置等信息吗，我2.2.0在本地跑单机好像是可以启动成功的

**Comment by pigping88** [comment]
> mac m1，镜像：nacos/nacos-server:v2.2.0-slim
> `podman run -d --name nacos -p 8848:8848 --restart always -e MODE=standalone nacos/nacos-server:v2.2.0-slim`

**Comment by pigping88** [comment]
没改过任何配置

**Comment by paderlol** [comment]
> 没改过任何配置
我们验证过了,确实是docker镜像里面有个参数`spring.sql.init.platform`没有进行兼容导致的,目前已经解决并重新发布镜像, 麻烦重新拉取一下镜像.

**Comment by InGramViking** [comment]
> > 没改过任何配置
> > 我们验证过了,确实是docker镜像里面有个参数`spring.sql.init.platform`没有进行兼容导致的,目前已经解决并重新发布镜像, 麻烦重新拉取一下镜像.

使用最新版的镜像，k8s集群启动，报dataSource or tableName is null 

```log
2022-12-22 11:27:40,802 INFO Nacos is starting...
2022-12-22 11:27:41,514 INFO Nacos Log files: /home/nacos/logs
2022-12-22 11:27:41,515 INFO Nacos Log files: /home/nacos/conf
2022-12-22 11:27:41,515 INFO Nacos Log files: /home/nacos/data
2022-12-22 11:27:41,516 ERROR Startup errors : 
org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'memoryMonitor' defined in URL [jar:file:/home/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-config-2.2.0.jar!/com/alibaba/nacos/config/server/monitor/MemoryMonitor.class]: Unsatisfied dependency expressed through constructor parameter 0; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'asyncNotifyService': Unsatisfied dependency expressed through field 'dumpService'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'externalDumpService': Invocation of init method failed; nested exception is ErrCode:500, ErrMsg:Nacos Server did not start because dumpservice bean construction failure :
errCode: 102, errMsg: dataSource or tableName is null 
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at com.alibaba.nacos.Nacos.main(Nacos.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
```

**Comment by InGramViking** [comment]
我pull了最新的sha256:be794368c96f90e42a6dd9f288d3fb12d69608cebd782eb091a489ccb48cfd28 镜像，启动后看了conf/application.properties文件，里面依然没有默认选项mysql: spring.sql.init.platform=${SPRING_DATASOURCE_PLATFORM:} 
手动指定了后能连上库，但是第三个节点启动失败，可能是选举的问题

**Comment by InGramViking** [comment]
@paderlol

**Comment by alansun2** [comment]
未解决 @paderlol

**Comment by paderlol** [comment]
> 我pull了最新的sha256:be794368c96f90e42a6dd9f288d3fb12d69608cebd782eb091a489ccb48cfd28 镜像，启动后看了conf/application.properties文件，里面依然没有默认选项mysql: spring.sql.init.platform=${SPRING_DATASOURCE_PLATFORM:} 手动指定了后能连上库，但是第三个节点启动失败，可能是选举的问题

不指定默认就是嵌入式数据库啊

**Comment by paderlol** [comment]
> 未解决 @paderlol

你的启动方式也是上面这种用MODE=standalone的方式在启动吗？

**Comment by InGramViking** [comment]
> > 我pull了最新的sha256:be794368c96f90e42a6dd9f288d3fb12d69608cebd782eb091a489ccb48cfd28 镜像，启动后看了conf/application.properties文件，里面依然没有默认选项mysql: spring.sql.init.platform=${SPRING_DATASOURCE_PLATFORM:} 手动指定了后能连上库，但是第三个节点启动失败，可能是选举的问题
> 
> 不指定默认就是嵌入式数据库啊

[官网文档](https://nacos.io/zh-cn/docs/use-nacos-with-kubernetes.html)引导使用的Kubernetes Nacos是nacos-k8s仓库中的deploy目录获取的yaml，但是从[nacos-quick-start.yaml](https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-quick-start.yaml)或者[nacos-pvc-nfs.yaml](https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-pvc-nfs.yaml) 都没有标明需要这个参数，很多人都会出现这个问题。这个参数是最近几个版本加的吗？我1.4.0版本是没有用到这个参数的

**Comment by paderlol** [comment]
> > > 我pull了最新的sha256:be794368c96f90e42a6dd9f288d3fb12d69608cebd782eb091a489ccb48cfd28 镜像，启动后看了conf/application.properties文件，里面依然没有默认选项mysql: spring.sql.init.platform=${SPRING_DATASOURCE_PLATFORM:} 手动指定了后能连上库，但是第三个节点启动失败，可能是选举的问题
> > 
> > 
> > 不指定默认就是嵌入式数据库啊
> 
> [官网文档](https://nacos.io/zh-cn/docs/use-nacos-with-kubernetes.html)引导使用的Kubernetes Nacos是nacos-k8s仓库中的deploy目录获取的yaml，但是从[nacos-quick-start.yaml](https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-quick-start.yaml)或者[nacos-pvc-nfs.yaml](https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-pvc-nfs.yaml) 都没有标明需要这个参数，很多人都会出现这个问题。这个参数是最近几个版本加的吗？我1.4.0版本是没有用到这个参数的

我看了下 2.2.0的Nacos在多数据库设计上用到了这个值, 如果为空确实会出现你这个问题, 所以目前可能需要自己添加指定下,后续我们看怎么处理下

**Comment by InGramViking** [comment]
> > > > 我pull了最新的sha256:be794368c96f90e42a6dd9f288d3fb12d69608cebd782eb091a489ccb48cfd28 镜像，启动后看了conf/application.properties文件，里面依然没有默认选项mysql: spring.sql.init.platform=${SPRING_DATASOURCE_PLATFORM:} 手动指定了后能连上库，但是第三个节点启动失败，可能是选举的问题
> > > 
> > > 
> > > 不指定默认就是嵌入式数据库啊
> > 
> > 
> > [官网文档](https://nacos.io/zh-cn/docs/use-nacos-with-kubernetes.html)引导使用的Kubernetes Nacos是nacos-k8s仓库中的deploy目录获取的yaml，但是从[nacos-quick-start.yaml](https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-quick-start.yaml)或者[nacos-pvc-nfs.yaml](https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-pvc-nfs.yaml) 都没有标明需要这个参数，很多人都会出现这个问题。这个参数是最近几个版本加的吗？我1.4.0版本是没有用到这个参数的
> 
> 我看了下 2.2.0的Nacos在多数据库设计上用到了这个值, 如果为空确实会出现你这个问题, 所以目前可能需要自己添加指定下,后续我们看怎么处理下

实在是看不下去官网的文档了，经过上次1.4版本的部署，还有这次[想在2.2.0 添加pvc](https://github.com/nacos-group/nacos-k8s/issues/372)的事情。我正在整合修改nacos-k8s仓库中deploy目录的一些配置，那些yaml实在太老了。还有[nacos.io官网关于k8s创建集群](https://nacos.io/zh-cn/docs/use-nacos-with-kubernetes.html)的相关文档依然还处于数据库有主从的状态，稍后提交nacos-k8s仓库的PR

**Comment by paderlol** [comment]
好的 我们后续更新下官方文档的内容

**Comment by InGramViking** [comment]
> 好的 我们后续更新下官方文档的内容

官网文档和nacos-k8s仓库的yaml我提交了个PR，帮忙审核看一下

**Comment by KomachiSion** [comment]
欢迎提交PR到文档仓库帮忙更新文档。

**Comment by xshans** [comment]
集群的情况下也存在这个问题呀 官方文档已经更新了吗 要如何部署 nacos docker集群呢？

**Comment by InGramViking** [comment]
> 集群的情况下也存在这个问题呀 官方文档已经更新了吗 要如何部署 nacos docker集群呢？

我修改提交了 [V2的Kubernetes Nacos](https://nacos.io/zh-cn/docs/v2/quickstart/quick-start-kubernetes.html) 页面的md文件，但是官网页面好像没更新。

docker-compose按照官网文档，在引用的环境变量里面，已经添加SPRING_DATASOURCE_PLATFORM=mysql的配置了

**Comment by Queetinliu** [comment]
> 

按照这样操作好了，但是注意加了环境变量后得重启服务，不然识别不到还是报错。

**Comment by ldbxs** [comment]
添加了SPRING_DATASOURCE_PLATFORM=mysql，成功了
