### ISSUE TITLE
nacos2.2 standalone run failed

### ISSUE THREAD

**Issue by c3b2a7** [alibaba/nacos#9747]
**Describe the bug**

nacos2.2 standalone启动失败

**Expected behavior**

启动成功

**Actually behavior**

`instanceOperatorClientImpl`bean创建失败，导致启动失败，看错误日志是librocksdbjni不兼容m1

**Desktop (please complete the following information):**

 - OS: MacOS (M1 Pro)
 - Version nacos-server2.2.0

**Additional context**

```txt
2022-12-24 23:03:36,488 ERROR Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'instanceOperatorClientImpl' defined in URL [jar:file:/Users/lifei/opt/nacos/target/nacos-server.jar!/BOOT-INF/lib/nac
os-naming-2.2.0.jar!/com/alibaba/nacos/naming/core/InstanceOperatorClientImpl.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.Unsatisf
iedDependencyException: Error creating bean with name 'clientOperationServiceProxy' defined in URL [jar:file:/Users/lifei/opt/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.2.0.jar!/com/alibaba/nacos/na
ming/core/v2/service/ClientOperationServiceProxy.class]: Unsatisfied dependency expressed through constructor parameter 1; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating
 bean with name 'persistentClientOperationServiceImpl' defined in URL [jar:file:/Users/lifei/opt/nacos/target/nacos-server.jar!/BOOT-INF/lib/nacos-naming-2.2.0.jar!/com/alibaba/nacos/naming/core/v2/service/impl/Per
sistentClientOperationServiceImpl.class]: Bean instantiation via constructor failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2
.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213
594998947.jnilib: dlopen(/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib, 0x0001): tried: '/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813
208213594998947.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7
813208213594998947.jnilib' (no such file), '/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need '
arm64'))
        at org.springframework.beans.factory.support.ConstructorResolver.createArgumentArray(ConstructorResolver.java:800)
        at org.springframework.beans.factory.support.ConstructorResolver.autowireConstructor(ConstructorResolver.java:229)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.autowireConstructor(AbstractAutowireCapableBeanFactory.java:1372)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1222)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:953)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:145)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:745)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:420)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:307)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306)
        at com.alibaba.nacos.Nacos.main(Nacos.java:35)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.PropertiesLauncher.main(PropertiesLauncher.java:467)
...
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl]: Constructor threw exception; nested exception is java.lang.UnsatisfiedLinkError: /private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib: dlopen(/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib, 0x0001): tried: '/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib' (no such file), '/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:224)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:117)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:311)
        ... 55 common frames omitted
Caused by: java.lang.UnsatisfiedLinkError: /private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib: dlopen(/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib, 0x0001): tried: '/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib' (no such file), '/private/var/folders/6x/8nz4zv9n3j7c_zjbqz9tw0xc0000gn/T/librocksdbjni7813208213594998947.jnilib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
        at java.lang.ClassLoader$NativeLibrary.load(Native Method)
        at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1950)
        at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1832)
        at java.lang.Runtime.load0(Runtime.java:783)
        at java.lang.System.load(System.java:1100)
        at org.rocksdb.NativeLibraryLoader.loadLibraryFromJar(NativeLibraryLoader.java:78)
        at org.rocksdb.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:56)
        at org.rocksdb.RocksDB.loadLibrary(RocksDB.java:64)
        at org.rocksdb.RocksDB.<clinit>(RocksDB.java:35)
        at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.<clinit>(RocksDBLogStorage.java:75)
        at com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory.createLogStorage(DefaultJRaftServiceFactory.java:50)
        at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:579)
        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:999)
        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:139)
        at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
        at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
        at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGroup(JRaftServer.java:260)
        at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.addRequestProcessors(JRaftProtocol.java:163)
        at com.alibaba.nacos.naming.core.v2.service.impl.PersistentClientOperationServiceImpl.<init>(PersistentClientOperationServiceImpl.java:96)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
        ... 57 common frames omitted
```

**Comment by jjeejj** [comment]
@c3b2a7 这个问题有解决吗？ 现在还能遇到这样的问题

**Comment by Sunny-117** [comment]
+1
