### ISSUE TITLE
nacos k8s集群使用pvc, 集群报Fail to get leader of group naming_persistent_service_v2, Unknown leader, 节点启动失败

### ISSUE THREAD

**Issue by InGramViking** [alibaba/nacos#9766]
**Describe the bug**

当我部署nacos三节点集群,  使用阿里RDS和阿里NAS做pvc并去掉peer-finder(阿里云SLB做svc不能设置clusterIP: None)时, 其中一两个节点启动失败, 是我将old-raft-rpc的svc端口关闭的原因吗？或者是什么原因呢？
当我不用pvc时, 集群是正常的，所有节点的状态都为UP, 但是扩容时可能存在数据丢失风险。
如果我使用pvc, 如何修改我的Yaml配置呢？
所有log、data在 [nacos2.2.0-alinaspvc-alislb.tar.gz](https://github.com/alibaba/nacos/files/10317895/nacos2.2.0-alinaspvc-alislb.tar.gz)

When I deploy a three node cluster of nacos, use Alibaba RDS and Alibaba NAS to make pvc and remove the peer finder (Alibaba Cloud SLB cannot set the clusterIP: None for svc), one or two of the nodes fail to start. Is that why I shut down the svc port of old post rpc? Or why?
When I do not use PVC, the cluster is normal, and all nodes are in UP status. However, there may be a risk of data loss during node expansion.
If I want to use pvc, how can I modify my Yaml configuration?
All logs and data are in the [nacos2.2.0-alinaspvc-alislb.tar.gz](https://github.com/alibaba/nacos/files/10317895/nacos2.2.0-alinaspvc-alislb.tar.gz)

nacos.log:
```log
Fail to init node, please see the logs to find the reason.
```
nacos-cluster.log:
```log
2022-12-22 14:18:42,306 ERROR failed to report new info to target node : nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:8848, error : caused: Connection refused;

2022-12-22 14:18:44,937 INFO start a new rpc client to member - > : Member{ip='nacos220-1.nacos220-headless.pluginalpha.svc.cluster.local', port=8848, state=UP, extendInfo={lastRefreshTime=1671689920472, raftMetaData={metaDataMap={naming_instance_metadata={leader=nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848, raftGroupMember=[nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848, nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:7848, nacos220-1.nacos220-headless.pluginalpha.svc.cluster.local:7848], term=1}, naming_persistent_service={leader=nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848, raftGroupMember=[nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848, nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:7848, nacos220-1.nacos220-headless.pluginalpha.svc.cluster.local:7848], term=1}, naming_persistent_service_v2={errMsg=Error [type=ERROR_TYPE_META, status=Status[EIO<1014>: Fail to save raft meta, path=/home/nacos/data/protocol/raft/naming_persistent_service_v2/meta-data]], leader=unknown, raftGroupMember=[nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848, nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:7848, nacos220-1.nacos220-headless.pluginalpha.svc.cluster.local:7848], term=-1}}}, raftPort=7848, readyToUpgrade=true, version=2.2.0}}
```
alipay-jraft.log:
```log
2022-12-22 14:18:35,241 INFO SPI service [com.alipay.sofa.jraft.JRaftServiceFactory - com.alipay.sofa.jraft.core.DefaultJRaftServiceFactory] loading.

2022-12-22 14:18:35,407 INFO SPI service [com.alipay.sofa.jraft.rpc.RaftRpcFactory - com.alipay.sofa.jraft.rpc.impl.GrpcRaftRpcFactory] loading.

2022-12-22 14:18:31,674 INFO SPI service [com.alipay.sofa.jraft.util.JRaftSignalHandler - com.alipay.sofa.jraft.NodeDescribeSignalHandler] loading.

2022-12-22 14:18:31,675 INFO SPI service [com.alipay.sofa.jraft.util.JRaftSignalHandler - com.alipay.sofa.jraft.NodeMetricsSignalHandler] loading.

2022-12-22 14:18:31,678 INFO SPI service [com.alipay.sofa.jraft.util.JRaftSignalHandler - com.alipay.sofa.jraft.ThreadPoolMetricsSignalHandler] loading.

2022-12-22 14:18:31,681 INFO SPI service [com.alipay.sofa.jraft.util.timer.RaftTimerFactory - com.alipay.sofa.jraft.util.timer.DefaultRaftTimerFactory] loading.

2022-12-22 14:18:31,687 INFO The number of active nodes increment to 1.

2022-12-22 14:18:32,016 INFO Starts FSMCaller successfully.

2022-12-22 14:18:32,035 WARN No data for snapshot reader /home/nacos/data/protocol/raft/naming_persistent_service/snapshot.

2022-12-22 14:18:32,066 INFO Node <naming_persistent_service/nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848> init, term=0, lastLogId=LogId [index=0, term=0], conf=nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848,nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:7848,nacos220-1.nacos220-headless.pluginalpha.svc.cluster.local:7848, oldConf=.

2022-12-22 14:18:32,068 WARN RPC server is not started in RaftGroupService.

2022-12-22 14:18:32,068 INFO Start the RaftGroupService successfully.

2022-12-22 14:18:32,194 WARN Channel in TRANSIENT_FAILURE state: nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848.

2022-12-22 14:18:32,194 WARN Channel in SHUTDOWN state: nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848.

2022-12-22 14:18:32,958 WARN Channel in TRANSIENT_FAILURE state: nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:7848.

2022-12-22 14:18:32,962 WARN Channel in SHUTDOWN state: nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:7848.

2022-12-22 14:18:32,983 ERROR Fail to connect nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:7848, remoting exception: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception.

2022-12-22 14:18:32,983 ERROR Fail to connect peer nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:7848 to get leader for group naming_persistent_service.
```

**Expected behavior**
希望使用阿里SLB 访问到nacos集群，集群拥有自动扩容缩容能力和数据持久特性。
I want to use Alibaba SLB to access the nacos cluster. The cluster has the capability of automatic node expansion and reduction and data persistence.

**Actually behavior**
集群节点启动异常
Cluster node startup exception

**How to Reproduce**
Yaml:
```yaml
---
apiVersion: v1
kind: Service
metadata:
  name: nacos220-headless
  namespace: pluginalpha
  labels:
    app: nacos220-headless
  annotations:
    service.beta.kubernetes.io/alibaba-cloud-loadbalancer-id: lb-abcdefghijklmcdcdcdcd
    service.beta.kubernetes.io/alicloud-loadbalancer-force-override-listeners: 'true'
spec:
  publishNotReadyAddresses: true
  ports:
    - port: 28848
      name: server
      targetPort: 8848
    - port: 9848
      name: client-rpc
      targetPort: 9848
    - port: 9849
      name: raft-rpc
      targetPort: 9849
    # 与1.4版本的nacos共用了一个SLB，所以注释掉了这个端口
    # ## 兼容1.4.x版本的选举端口
    # - port: 7848
    #   name: old-raft-rpc
    #   targetPort: 7848
  selector:
    app: nacos220
  sessionAffinity: None
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nacos220-cm
  namespace: pluginalpha
data:
  mysql.host: "rm-2zabcdefghijklmncd.mysql.rds.aliyuncs.com"
  mysql.db.name: "nacos220_test"
  mysql.port: "3306"
  mysql.user: "nacos220_test"
  mysql.password: "rlllllllllllllll+Sa"
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  # namespace里面有老版本的nacos了，所以改了名
  name: nacos220
  namespace: pluginalpha
spec:
  serviceName: nacos220-headless
  # podManagementPolicy: Parallel
  replicas: 3
  template:
    metadata:
      labels:
        app: nacos220
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchExpressions:
                  - key: "app"
                    operator: In
                    values:
                      - nacos220-headless
              topologyKey: "kubernetes.io/hostname"
      # 因为要用SLB不能设置  clusterIP: None, 所以注释掉了peer
      # initContainers:
      #   - name: peer-finder-plugin-install
      #     image: registry-vpc.cn-beijing.aliyuncs.com/acegear/nacos-peer-finder-plugin:1.1
      #     imagePullPolicy: Always
      #     volumeMounts:
      #       - mountPath: /home/nacos/plugins/peer-finder
      #         name: data
      #         subPath: peer-finder
      containers:
        - name: nacos
          imagePullPolicy: Always
          image: nacos/nacos-server:v2.2.0
          resources:
            requests:
              memory: "2Gi"
          #     cpu: "500m"
          ports:
            - containerPort: 8848
              name: client-port
            - containerPort: 9848
              name: client-rpc
            - containerPort: 9849
              name: raft-rpc
            - containerPort: 7848
              name: old-raft-rpc
          env:
            - name: NACOS_REPLICAS
              value: "3"
            # 没用peer就注释掉这个了
            # - name: SERVICE_NAME
            #   value: "nacos220-headless"
            # - name: DOMAIN_NAME
            #   value: "cluster.local"
            # - name: POD_NAMESPACE
            #   valueFrom:
            #     fieldRef:
            #       apiVersion: v1
            #       fieldPath: metadata.namespace
            - name: MYSQL_SERVICE_HOST
              valueFrom:
                configMapKeyRef:
                  name: nacos220-cm
                  key: mysql.host
            - name: MYSQL_SERVICE_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: nacos220-cm
                  key: mysql.db.name
            - name: MYSQL_SERVICE_PORT
              valueFrom:
                configMapKeyRef:
                  name: nacos220-cm
                  key: mysql.port
            - name: MYSQL_SERVICE_USER
              valueFrom:
                configMapKeyRef:
                  name: nacos220-cm
                  key: mysql.user
            - name: MYSQL_SERVICE_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: nacos220-cm
                  key: mysql.password
            - name: SPRING_DATASOURCE_PLATFORM
              value: "mysql"
            - name: MODE
              value: "cluster"
            - name: NACOS_SERVER_PORT
              value: "8848"
            - name: PREFER_HOST_MODE
              value: "hostname"
            - name: NACOS_SERVERS
              value: "nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:8848 nacos220-1.nacos220-headless.pluginalpha.svc.cluster.local:8848 nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:8848"
          volumeMounts:
            # - name: data
            #   mountPath: /home/nacos/plugins/peer-finder
            #   subPath: peer-finder
            - name: data
              mountPath: /home/nacos/data
              subPath: data
            - name: data
              mountPath: /home/nacos/logs
              subPath: logs
      volumes:
      # 通过阿里云NAS做的nfs的pvc
        - name: data
          persistentVolumeClaim:
            claimName: nacos220-alpha
  selector:
    matchLabels:
      app: nacos220
```
PVC挂载选项:
PVC mount options:
```yaml
  mountOptions:
  - tcp,noresvport,minorversion=0,rsize=1048576,wsize=1048576,hard,timeo=600,retrans=2
  - vers=4
 ```

**Desktop (please complete the following information):**

k8s版本: 1.20.11-aliyun.1
nacos版本: nacos/nacos-server:v2.2.0

K8s version: 1.20.11-aliyun.1
nacos version: nacos/nacos-server:v2.2.0

**Comment by InGramViking** [comment]
protocol-distro.log 中的数据库地址与ConfigMap中的mysql.host不一样是因为我修改隐藏了真实地址，实际真实地址内容是一致的

**Comment by KomachiSion** [comment]
那就是你集群搭建有问题， jraft无法创建对应的连接，肯定无法选主。

**Comment by InGramViking** [comment]
为什么同样配置，只把pvc去掉就能正常呢？能否指出集群搭建的问题在哪里？

**Comment by KomachiSion** [comment]
`ERROR Fail to connect nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:7848, remoting exception: java.util.concurrent.ExecutionException: io.grpc.StatusRuntimeException: UNAVAILABLE: io exception.`

这就是原因

**Comment by KomachiSion** [comment]
pvc去掉后， 因为jraft的元数据没有保留，每次都是空磁盘空元数据，读取的是新的cluster.conf，所以能连接上。

pvc在的话，快照，日志，元数据都会保留，启动的时候会读取使用之前的元数据以及快照数据。此时发现旧的node连接不上，选不出主。

**Comment by InGramViking** [comment]
> pvc去掉后， 因为jraft的元数据没有保留，每次都是空磁盘空元数据，读取的是新的cluster.conf，所以能连接上。
> 
> pvc在的话，快照，日志，元数据都会保留，启动的时候会读取使用之前的元数据以及快照数据。此时发现旧的node连接不上，选不出主。


看过你的回复，将podManagementPolicy设置为了Parallel，所有pod节点同时启动，避免了启动时连接不到其他node的问题，并将NACOS_SERVERS环境变量注释了。

我清空了所有配置和目录，pvc目录在首次部署，pod启动之前是空目录
<img width="617" alt="image" src="https://user-images.githubusercontent.com/20497789/210473194-14fa2f61-a97d-4eac-9268-df354333dfce.png">
第一次集群启动时为什么是不正常的呢？
即使不是第一次启动的，旧node的节点信息是svc地址，后续的重启(同时启动)应该也不会发现不了旧node吧？毕竟节点每次启动的节点地址都是这个。

我重新提供一份集群第一次启动时的日志
[nacos2.2.0-alinaspvc-alislb-0104.tar.gz](https://github.com/alibaba/nacos/files/10341129/nacos2.2.0-alinaspvc-alislb-0104.tar.gz)

这次(修改podManagementPolicy和注释环境变量后)我在alipay-jraft.log 中找到这些日志，不知是否和使用阿里NAS做pvc有关，我的mountOptions使用的nfs版本为v4
```log
2023-01-04 10:24:08,569 INFO Starts FSMCaller successfully.

2023-01-04 10:24:08,589 WARN No data for snapshot reader /home/nacos/data/protocol/raft/naming_persistent_service/snapshot.

2023-01-04 10:24:08,615 INFO Node <naming_persistent_service/nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848> init, term=0, lastLogId=LogId [index=0, term=0], conf=nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848, oldConf=.

2023-01-04 10:24:08,617 INFO Node <naming_persistent_service/nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848> start vote and grant vote self, term=0.

2023-01-04 10:24:08,665 INFO Save raft meta, path=/home/nacos/data/protocol/raft/naming_persistent_service/meta-data, term=1, votedFor=nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848, cost time=37 ms

2023-01-04 10:24:08,669 INFO Node <naming_persistent_service/nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848> become leader of group, term=1, conf=nacos220-0.nacos220-headless.pluginalpha.svc.cluster.local:7848, oldConf=.

AndLoad(RocksDBLogStorage.java:226)
        at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.init(RocksDBLogStorage.java:205)
        at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.init(RocksDBLogStorage.java:70)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.init(LogManagerImpl.java:184)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.init(LogManagerImpl.java:77)
        at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:589)
        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:999)
        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:139)
        at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
        at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
        at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGroup(JRaftServer.java:260)
        at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.addRequestProcessors(JRaftProtocol.java:163)
        at com.alibaba.nacos.naming.consistency.persistent.impl.PersistentServiceProcessor.afterConstruct(PersistentServiceProcessor.java:76)
        at com.alibaba.nacos.naming.consistency.persistent.PersistentConsistencyServiceDelegateImpl.createPersistentServiceProcessor(PersistentConsistencyServiceDelegateImpl.java:88)
        at com.alibaba.nacos.naming.consistency.persistent.PersistentConsistencyServiceDelegateImpl.<init>(PersistentConsistencyServiceDelegateImpl.java:45)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

2023-01-04 10:24:10,963 ERROR Fail to init logStorage

2023-01-04 10:24:10,963 ERROR Node <naming_persistent_service/nacos220-2.nacos220-headless.pluginalpha.svc.cluster.local:7848> initLogStorage failed.

2023-01-04 10:24:11,057 INFO ThreadPool is terminated: JRaft-RPC-Processor, com.alipay.sofa.jraft.util.MetricThreadPoolExecutor@68c9d179[Shutting down, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 0].

2023-01-04 10:24:11,172 ERROR Fail to init RocksDBLogStorage, path=/home/nacos/data/protocol/raft/naming_persistent_service/log.

org.rocksdb.RocksDBException: While lock file: /home/nacos/data/protocol/raft/naming_persistent_service/log/LOCK: Resource temporarily unavailable
        at org.rocksdb.RocksDB.open(Native Method)
        at org.rocksdb.RocksDB.open(RocksDB.java:286)
        at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.openDB(RocksDBLogStorage.java:308)
        at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.initAndLoad(RocksDBLogStorage.java:226)
        at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.init(RocksDBLogStorage.java:205)
        at com.alipay.sofa.jraft.storage.impl.RocksDBLogStorage.init(RocksDBLogStorage.java:70)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.init(LogManagerImpl.java:184)
        at com.alipay.sofa.jraft.storage.impl.LogManagerImpl.init(LogManagerImpl.java:77)
        at com.alipay.sofa.jraft.core.NodeImpl.initLogStorage(NodeImpl.java:589)
        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:999)
        at com.alipay.sofa.jraft.core.NodeImpl.init(NodeImpl.java:139)
        at com.alipay.sofa.jraft.RaftServiceFactory.createAndInitRaftNode(RaftServiceFactory.java:47)
        at com.alipay.sofa.jraft.RaftGroupService.start(RaftGroupService.java:129)
        at com.alibaba.nacos.core.distributed.raft.JRaftServer.createMultiRaftGroup(JRaftServer.java:260)
        at com.alibaba.nacos.core.distributed.raft.JRaftProtocol.addRequestProcessors(JRaftProtocol.java:163)
```

**Comment by KomachiSion** [comment]
`org.rocksdb.RocksDBException: While lock file: /home/nacos/data/protocol/raft/naming_persistent_service/log/LOCK: Resource temporarily unavailable`

**Comment by KomachiSion** [comment]
rocksdb 启动的时候发现LOCK文件已经被占用。

**Comment by KomachiSion** [comment]
https://github.com/facebook/rocksdb/issues?q=is%3Aissue+is%3AopenResource+temporarily+unavailable

**Comment by InGramViking** [comment]
> rocksdb 启动的时候发现LOCK文件已经被占用。

是的，但到这我已经搞不懂应该怎么配置我的yaml使nacos集群启动起来了。

我理解在pvc挂载共享了data目录的情况下，3个节点启动时都想open文件，导致的lock的报错，但这和pvc共享是相悖的。

我看过了rocksdb的issues，各issues的原因大致都是上面讲的多进程访问单数据库导致的Resource temporarily unavailable

[官方仓库中的Yaml的配置](https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-pvc-nfs.yaml) 也有人https://github.com/nacos-group/nacos-k8s/issues/381 遇到了同样的问题。

仔细与官方yaml对照过以后，我除了没有使用peer-finder插件，注释掉了peer-finder插件的内容，其他配置基本一致，发版有对pvc模式的集群做过测试吗？测试Yaml能否分享一下？

**Comment by paderlol** [comment]
@InGramViking 你卷申明错误了, 每个节点应该都是单独的卷才对, STS应用需要使用volumeClaimTemplates 而不是Volume这种声明方式
https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-pvc-nfs.yaml
``` yaml
          volumeMounts:
            - name: data
              mountPath: /home/nacos/plugins/peer-finder
              subPath: peer-finder
            - name: data
              mountPath: /home/nacos/data
              subPath: data
            - name: data
              mountPath: /home/nacos/logs
              subPath: logs
  volumeClaimTemplates:
    - metadata:
        name: data
        annotations:
          volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
      spec:
        accessModes: [ "ReadWriteMany" ]
        resources:
          requests:
            storage: 20Gi
  selector:
    matchLabels:
      app: nacos
```

**Comment by InGramViking** [comment]
> @InGramViking 你卷申明错误了, 每个节点应该都是单独的卷才对, STS应用需要使用volumeClaimTemplates 而不是Volume这种声明方式 https://github.com/nacos-group/nacos-k8s/blob/master/deploy/nacos/nacos-pvc-nfs.yaml
> 
> ```yaml
>           volumeMounts:
>             - name: data
>               mountPath: /home/nacos/plugins/peer-finder
>               subPath: peer-finder
>             - name: data
>               mountPath: /home/nacos/data
>               subPath: data
>             - name: data
>               mountPath: /home/nacos/logs
>               subPath: logs
>   volumeClaimTemplates:
>     - metadata:
>         name: data
>         annotations:
>           volume.beta.kubernetes.io/storage-class: "managed-nfs-storage"
>       spec:
>         accessModes: [ "ReadWriteMany" ]
>         resources:
>           requests:
>             storage: 20Gi
>   selector:
>     matchLabels:
>       app: nacos
> ```

明白了，感谢解答
