### ISSUE TITLE
nacos-server中的spring-security的jar版本存在漏洞

### ISSUE THREAD

**Issue by XW512** [alibaba/nacos#9767]
目前发现，nacos-server中使用的spring-security5.6.5的版本存在漏洞，受影响版本为：Spring Security 5.6.0 - 5.6.8、5.7.0 - 5.7.4，需要将 Spring Security 升级到 5.6.9、5.7.5 及以上版本，我尝试用新版本替换nacos-server中lib下的spring-security的版本，发现替换后，服务注册不上去，能否官方升级一个版本
我替换的步骤是：
先解压taget下的nacos-server的jar
命令： jar -xvf nacos-server.jar
替换后：重新打包nacos-server的jar
命令： jar -cfM0 nacos-server.jar ./ 
发现启动没问题，但是，服务注册不了，报错信息如下：
Exception in thread "nacos-grpc-executor-268" java.lang.NoSuchMethodError: com.alibaba.nacos.api.grpc.auto.Payload$Builder.setBody(Lcom/alibaba/nacos/shaded/com/google/protobuf/Any$Builder;)Lcom/alibaba/nacos/api/grpc/auto/Payload$Builder;
        at com.alibaba.nacos.common.remote.client.grpc.GrpcUtils.convert(GrpcUtils.java:103)
        at com.alibaba.nacos.core.remote.grpc.GrpcRequestAcceptor.request(GrpcRequestAcceptor.java:91)
        at com.alibaba.nacos.core.remote.grpc.BaseGrpcServer.lambda$addServices$0(BaseGrpcServer.java:176)
        at io.grpc.stub.ServerCalls$UnaryServerCallHandler$UnaryServerCallListener.onHalfClose(ServerCalls.java:172)
        at io.grpc.PartialForwardingServerCallListener.onHalfClose(PartialForwardingServerCallListener.java:35)
        at io.grpc.ForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:23)
        at io.grpc.ForwardingServerCallListener$SimpleForwardingServerCallListener.onHalfClose(ForwardingServerCallListener.java:40)
        at io.grpc.Contexts$ContextualizedServerCallListener.onHalfClose(Contexts.java:86)
        at io.grpc.internal.ServerCallImpl$ServerStreamListenerImpl.halfClosed(ServerCallImpl.java:331)
        at io.grpc.internal.ServerImpl$JumpToApplicationThreadServerStreamListener$1HalfClosed.runInContext(ServerImpl.java:820)
        at io.grpc.internal.ContextRunnable.run(ContextRunnable.java:37)
        at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by KomachiSion** [comment]
duplicate with #9504
