### ISSUE TITLE
springboot打包成native image会报错

### ISSUE THREAD

**Issue by zgqq** [alibaba/nacos#9802]
spring boot 版本3.0.1
nacos client 版本 2.2.1-RC

` ./gradlew bootRun`启动正常
打包成native image
```
apply plugin: "org.graalvm.buildtools.native"
./gradlew bootBuildImage
```
docker run 打包的镜像 会报错，看起来有点像反射的问题

```
23-01-05 09:58:11.030 [scheduling-1] INFO  c.a.n.client.config.impl.LocalConfigInfoProcessor - LOCAL_SNAPSHOT_PATH:/root/nacos/config
23-01-05 09:58:11.031 [scheduling-1] INFO  com.alibaba.nacos.common.remote.client - [RpcClientFactory] create a new rpc client of fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0
23-01-05 09:58:11.034 [scheduling-1] INFO  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Register server push request handler:com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient$$Lambda$c6e0e9f3b789a04372e21fa9a81afe3ade7835ad
23-01-05 09:58:11.034 [scheduling-1] INFO  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Register server push request handler:com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient$$Lambda$07d9076b7484fab5b3789e47b0fdf5db00c33801
23-01-05 09:58:11.034 [scheduling-1] INFO  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Registry connection listener to current client:com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient$1
23-01-05 09:58:11.034 [scheduling-1] INFO  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] RpcClient init, ServerListFactory = com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient$2
23-01-05 09:58:11.035 [scheduling-1] INFO  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Try to connect to server on start up, server: {serverIp = 'config-nacos', server main port = 8848}
23-01-05 09:58:11.043 [scheduling-1] WARN  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Fail to connect to server on start up, error message = null, start up retry times left: 2
java.lang.ExceptionInInitializerError: null
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
        at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:163)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:303)
        at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:359)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:891)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1038)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:946)
        at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:402)
        at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:184)
        at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:96)
        at com.github.flycat.spi.impl.config.NacosConfigService.getConfig(NacosConfigService.java:70)
        at com.github.flycat.spi.impl.config.NacosConfigService.getConfig(NacosConfigService.java:59)
        at com.github.flycat.spi.impl.config.NacosConfigService.getJsonConfig(NacosConfigService.java:79)
        at com.github.zgqq.flycatprice.service.PriceService.checkWordAndNotifys(PriceService.java:340)
        at com.github.zgqq.flycatprice.job.QueryPriceJob.schedule(QueryPriceJob.java:58)
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base@17.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base@17.0.5/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base@17.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: java.lang.IllegalArgumentException: Class NioSocketChannel does not have a public non-arg constructor
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.ReflectiveChannelFactory.<init>(ReflectiveChannelFactory.java:36)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder.<clinit>(NettyChannelBuilder.java:74)
        ... 28 common frames omitted
Caused by: java.lang.NoSuchMethodException: com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.socket.nio.NioSocketChannel.<init>()
        at java.base@17.0.5/java.lang.Class.getConstructor0(DynamicHub.java:3585)
        at java.base@17.0.5/java.lang.Class.getConstructor(DynamicHub.java:2271)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.netty.channel.ReflectiveChannelFactory.<init>(ReflectiveChannelFactory.java:34)
        ... 29 common frames omitted
23-01-05 09:58:11.043 [scheduling-1] INFO  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Try to connect to server on start up, server: {serverIp = 'config-nacos', server main port = 8848}
23-01-05 09:58:11.043 [scheduling-1] WARN  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Fail to connect to server on start up, error message = Could not initialize class com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder, start up retry times left: 1
java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
        at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:163)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:303)
        at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:359)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:891)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1038)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:946)
        at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:402)
        at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:184)
        at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:96)
        at com.github.flycat.spi.impl.config.NacosConfigService.getConfig(NacosConfigService.java:70)
        at com.github.flycat.spi.impl.config.NacosConfigService.getConfig(NacosConfigService.java:59)
        at com.github.flycat.spi.impl.config.NacosConfigService.getJsonConfig(NacosConfigService.java:79)
        at com.github.zgqq.flycatprice.service.PriceService.checkWordAndNotifys(PriceService.java:340)
        at com.github.zgqq.flycatprice.job.QueryPriceJob.schedule(QueryPriceJob.java:58)
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base@17.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base@17.0.5/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base@17.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
23-01-05 09:58:11.043 [scheduling-1] INFO  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Try to connect to server on start up, server: {serverIp = 'config-nacos', server main port = 8848}
23-01-05 09:58:11.043 [scheduling-1] WARN  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Fail to connect to server on start up, error message = Could not initialize class com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder, start up retry times left: 0
java.lang.NoClassDefFoundError: Could not initialize class com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelBuilder
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:37)
        at com.alibaba.nacos.shaded.io.grpc.netty.shaded.io.grpc.netty.NettyChannelProvider.builderForAddress(NettyChannelProvider.java:23)
        at com.alibaba.nacos.shaded.io.grpc.ManagedChannelBuilder.forAddress(ManagedChannelBuilder.java:39)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:163)
        at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:303)
        at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:359)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.ensureRpcClient(ClientWorker.java:891)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.getOneRunningClient(ClientWorker.java:1038)
        at com.alibaba.nacos.client.config.impl.ClientWorker$ConfigRpcTransportClient.queryConfig(ClientWorker.java:946)
        at com.alibaba.nacos.client.config.impl.ClientWorker.getServerConfig(ClientWorker.java:402)
        at com.alibaba.nacos.client.config.NacosConfigService.getConfigInner(NacosConfigService.java:184)
        at com.alibaba.nacos.client.config.NacosConfigService.getConfig(NacosConfigService.java:96)
        at com.github.flycat.spi.impl.config.NacosConfigService.getConfig(NacosConfigService.java:70)
        at com.github.flycat.spi.impl.config.NacosConfigService.getConfig(NacosConfigService.java:59)
        at com.github.flycat.spi.impl.config.NacosConfigService.getJsonConfig(NacosConfigService.java:79)
        at com.github.zgqq.flycatprice.service.PriceService.checkWordAndNotifys(PriceService.java:340)
        at com.github.zgqq.flycatprice.job.QueryPriceJob.schedule(QueryPriceJob.java:58)
        at java.base@17.0.5/java.lang.reflect.Method.invoke(Method.java:568)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.base@17.0.5/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base@17.0.5/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305)
        at java.base@17.0.5/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base@17.0.5/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
23-01-05 09:58:11.044 [com.alibaba.nacos.client.remote.worker] INFO  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Try to reconnect to a new server, server is  not appointed, will choose a random server.
23-01-05 09:58:11.044 [scheduling-1] INFO  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Register server push request handler:com.alibaba.nacos.common.remote.client.RpcClient$ConnectResetRequestHandler
23-01-05 09:58:11.045 [scheduling-1] INFO  com.alibaba.nacos.common.remote.client - [fc026d2b-a539-4b7e-82c6-7ab789fff127_config-0] Register server push request handler:com.alibaba.nacos.common.remote.client.RpcClient$$Lambda$484601afdf3ae2dbcd86a48d6771535ef9fb5510
23-01-05 09:58:11.149 [scheduling-1] ERROR com.alibaba.nacos.common.remote.client - Send request fail, request = ConfigQueryRequest{headers={accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6Z3FxIiwiZXhwIjoxNjcyOTMwNjg1fQ.TMTSGEWNg58sJjK7KfdV3TWiiagu2YTE4wRNxlM6zY0, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=c0c0c7ce2188e772c873a0d80f5006f6, Client-RequestTS=1672912691045, exConfigInfo=true, notify=false}, requestId='null'}, retryTimes = 0, errorMessage = Client not connected, current status:STARTING
23-01-05 09:58:11.253 [scheduling-1] ERROR com.alibaba.nacos.common.remote.client - Send request fail, request = ConfigQueryRequest{headers={accessToken=eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ6Z3FxIiwiZXhwIjoxNjcyOTMwNjg1fQ.TMTSGEWNg58sJjK7KfdV3TWiiagu2YTE4wRNxlM6zY0, charset=UTF-8, Client-AppName=unknown, Client-RequestToken=c0c0c7ce2188e772c873a0d80f5006f6, Client-RequestTS=1672912691045, exConfigInfo=true, notify=false}, requestId='null'}, retryTimes = 1, errorMessage = Client not connected, current status:STARTING
```

**Comment by KomachiSion** [comment]
看样子像是地址解析的时候的时候，创建Address失败了，换成标准域名或者ip试试看？

**Comment by zgqq** [comment]
> 

应该不是这个问题，打成正常的 docker 镜像是没问题的

**Comment by KomachiSion** [comment]
那应该不是代码问题， 是不是打包成native的时候，没有扫描到这个类的使用，所以生成native 反射文件的时候没有生成对应的无参构造器

**Comment by zgqq** [comment]
看起来有点像是用到netty的代码，没有对native 做反射处理，后面netty的版本有对native进行反射的处理，参考一下？

**Comment by KomachiSion** [comment]
那需要你们自己参考后做这个反射处理扫描， 因为这个是打native包的时候做的事，并不是代码层面的事。

**Comment by KomachiSion** [comment]
No more response from author, I think this is a usage problem.
