### ISSUE TITLE
client2.2.1-RC 没有com.alibaba.nacos.shaded.io.grpc.census.包

### ISSUE THREAD

**Issue by rola0411** [alibaba/nacos#9872]
censusTracingAccessor = Class.forName("com.alibaba.nacos.shaded.io.grpc.census.InternalCensusStatsAccessor");
 
 在2.2.1-RC 这个版本中，没有这个类了，是提出去了吗？我需要引什么包

**Comment by KomachiSion** [comment]
我测试2.2.1-RC没有遇到问题， 这个包是您自己需要引入的吗？

**Comment by rola0411** [comment]
我用的是springboot3.0.2， jdk17.0.4  alibaba-cloud最新版的。启动报这个错误，这个错误都捕获异常了。
```
java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.census.InternalCensusStatsAccessor
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:375) ~[?:?]
	at com.alibaba.nacos.shaded.io.grpc.internal.AbstractManagedChannelImplBuilder.getEffectiveInterceptors(AbstractManagedChannelImplBuilder.java:534) ~[nacos-client-2.2.1-RC.jar:?]
	at com.alibaba.nacos.shaded.io.grpc.internal.AbstractManagedChannelImplBuilder.build(AbstractManagedChannelImplBuilder.java:517) ~[nacos-client-2.2.1-RC.jar:?]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:168) ~[nacos-client-2.2.1-RC.jar:?]
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:303) ~[nacos-client-2.2.1-RC.jar:?]
	at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:359) ~[nacos-client-2.2.1-RC.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.start(NamingGrpcClientProxy.java:104) ~[nacos-client-2.2.1-RC.jar:?]
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.<init>(NamingGrpcClientProxy.java:97) ~[nacos-client-2.2.1-RC.jar:?]
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.<init>(NamingClientProxyDelegate.java:78) ~[nacos-client-2.2.1-RC.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:102) ~[nacos-client-2.2.1-RC.jar:?]
	at com.alibaba.nacos.client.naming.NacosNamingService.<init>(NacosNamingService.java:85) ~[nacos-client-2.2.1-RC.jar:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
	at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
	at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59) ~[nacos-client-2.2.1-RC.jar:?]
	at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:77) ~[nacos-client-2.2.1-RC.jar:?]
	at com.alibaba.cloud.nacos.NacosServiceManager.createNewNamingService(NacosServiceManager.java:99) ~[spring-cloud-starter-alibaba-nacos-discovery-2022.0.0.0-RC1.jar:2022.0.0.0-RC1]
	at com.alibaba.cloud.nacos.NacosServiceManager.buildNamingService(NacosServiceManager.java:90) ~[spring-cloud-starter-alibaba-nacos-discovery-2022.0.0.0-RC1.jar:2022.0.0.0-RC1]
	at com.alibaba.cloud.nacos.NacosServiceManager.getNamingService(NacosServiceManager.java:46) ~[spring-cloud-starter-alibaba-nacos-discovery-2022.0.0.0-RC1.jar:2022.0.0.0-RC1]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.namingService(NacosServiceRegistry.java:193) ~[spring-cloud-starter-alibaba-nacos-discovery-2022.0.0.0-RC1.jar:2022.0.0.0-RC1]
	at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:68) ~[spring-cloud-starter-alibaba-nacos-discovery-2022.0.0.0-RC1.jar:2022.0.0.0-RC1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:264) ~[spring-cloud-commons-4.0.1.jar:4.0.1]
	at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:78) ~[spring-cloud-starter-alibaba-nacos-discovery-2022.0.0.0-RC1.jar:2022.0.0.0-RC1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:156) ~[spring-cloud-commons-4.0.1.jar:4.0.1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:119) ~[spring-cloud-commons-4.0.1.jar:4.0.1]
	at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:49) ~[spring-cloud-commons-4.0.1.jar:4.0.1]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:413) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:370) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.boot.web.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:47) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-6.0.4.jar:6.0.4]
	at java.lang.Iterable.forEach(Iterable.java:75) ~[?:?]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:932) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:587) ~[spring-context-6.0.4.jar:6.0.4]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:146) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:730) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:432) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1302) ~[spring-boot-3.0.2.jar:3.0.2]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1291) ~[spring-boot-3.0.2.jar:3.0.2]
	at com.zhongbao.openapi.oas.web.OpenapiOasWebApplication.main(OpenapiOasWebApplication.java:26) ~[classes/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.springframework.boot.devtools.restart.RestartLauncher.run(RestartLauncher.java:49) ~[spring-boot-devtools-3.0.2.jar:3.0.2]
```

对应的类，然后我看了你们的pom文件，并没有shaded对应的包，所以就找不到这个类，但你们代码里却加载这个类了。
异常虽然catch了，就是不知道如何规避这个异常
```
 @VisibleForTesting
    final List<ClientInterceptor> getEffectiveInterceptors() {
        List<ClientInterceptor> effectiveInterceptors = new ArrayList(this.interceptors);
        this.temporarilyDisableRetry = false;
        ClientInterceptor tracingInterceptor;
        Class censusTracingAccessor;
        Method getClientInterceptroMethod;
        if (this.statsEnabled) {
            this.temporarilyDisableRetry = true;
            tracingInterceptor = null;

            try {
                censusTracingAccessor = Class.forName("com.alibaba.nacos.shaded.io.grpc.census.InternalCensusStatsAccessor");
                getClientInterceptroMethod = censusTracingAccessor.getDeclaredMethod("getClientInterceptor", Boolean.TYPE, Boolean.TYPE, Boolean.TYPE);
                tracingInterceptor = (ClientInterceptor)getClientInterceptroMethod.invoke((Object)null, this.recordStartedRpcs, this.recordFinishedRpcs, this.recordRealTimeMetrics);
            } catch (ClassNotFoundException var9) {
                log.log(Level.FINE, "Unable to apply census stats", var9);
            } catch (NoSuchMethodException var10) {
                log.log(Level.FINE, "Unable to apply census stats", var10);
            } catch (IllegalAccessException var11) {
                log.log(Level.FINE, "Unable to apply census stats", var11);
            } catch (InvocationTargetException var12) {
                log.log(Level.FINE, "Unable to apply census stats", var12);
            }

            if (tracingInterceptor != null) {
                effectiveInterceptors.add(0, tracingInterceptor);
            }
        }

        if (this.tracingEnabled) {
            this.temporarilyDisableRetry = true;
            tracingInterceptor = null;

            try {
                censusTracingAccessor = Class.forName("com.alibaba.nacos.shaded.io.grpc.census.InternalCensusTracingAccessor");
                getClientInterceptroMethod = censusTracingAccessor.getDeclaredMethod("getClientInterceptor");
                tracingInterceptor = (ClientInterceptor)getClientInterceptroMethod.invoke((Object)null);
            } catch (ClassNotFoundException var5) {
                log.log(Level.FINE, "Unable to apply census stats", var5);
            } catch (NoSuchMethodException var6) {
                log.log(Level.FINE, "Unable to apply census stats", var6);
            } catch (IllegalAccessException var7) {
                log.log(Level.FINE, "Unable to apply census stats", var7);
            } catch (InvocationTargetException var8) {
                log.log(Level.FINE, "Unable to apply census stats", var8);
            }

            if (tracingInterceptor != null) {
                effectiveInterceptors.add(0, tracingInterceptor);
            }
        }

        return effectiveInterceptors;
    }
```

**Comment by KomachiSion** [comment]
我是用纯原生2.2.1-RC测试，是没有问题的。可以简单写个demo使用原生2.2.1-RC测试一下， 我怀疑是有依赖冲突导致的。

**Comment by KomachiSion** [comment]
我用原生2.2.1-RC测试的时候， AbstractManagedChannelImplBuilder 这个类总共只有300+行， 你的堆栈出了500+行。 说明肯定是加载了错误的依赖包或者自己有做修改导致的。

**Comment by rola0411** [comment]
我看了下没有任何得依赖冲突。请问您用的是springboot3.0.2和JDK17吗？，我没做任何修改
只是引入了spring-cloud-alibaba-dependencies
```
<dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>2022.0.1</version>
                <type>pom</type>
                <scope>import</scope>
                <exclusions>
                    <exclusion>
                        <groupId>io.seata</groupId>
                        <artifactId>seata-spring-boot-starter</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>com.fasterxml.jackson.core</groupId>
                        <artifactId>jackson-databind</artifactId>
                    </exclusion>
                    <exclusion>
                        <groupId>org.yaml</groupId>
                        <artifactId>snakeyaml</artifactId>
                    </exclusion>
                </exclusions>
            </dependency>
```

**Comment by KomachiSion** [comment]
原生2.2.1-RC，不使用spring启动， 新起一个demo project，直接初始化nacos-client来测试。

**Comment by KomachiSion** [comment]
No more response from author, and community can't reproduce problem.

**Comment by buruoyanyang** [comment]
目前我也遇到了一样的错误，对比了一下项目中的nacos-client:2.2.1-RC和这个库的2.2.1-RC-develop分支中的client目录的包结构，发现包的目录结构差距很大，项目中的nacos-client是SCA引入的，版本为2022.0.0.0-RC1。然后我去中央仓库（https://mvnrepository.com/artifact/com.alibaba.nacos/nacos-client）上下载了一下2.2.1-RC版本看了一下，包目录结构是与项目中的一致，也就是和本仓库的2.2.1-RC-develop分支存在很大的差距。所以https://mvnrepository.com/artifact/com.alibaba.nacos/nacos-client上面的包，不是本仓库维护的吗？

**Comment by chqbao** [comment]
spring boot 3 + nacos 2.2.1 正式版也是一样的抛 java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.census.InternalCensusStatsAccessor
问题解决了吗？

**Comment by pengliangs** [comment]
spring-cloud-alibaba 2022.0.0.0
nacos-client 2.2.1 中的 com.alibaba.nacos.api  不见了, 报红

**Comment by daydayfantasy** [comment]
> spring boot 3 + nacos 2.2.1 正式版也是一样的抛 java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.census.InternalCensusStatsAccessor 问题解决了吗？

我也遇到了同样的问题，求解

**Comment by RightFS** [comment]
2025.0.0 引入的nacos-client 3.0.1或者手动引入3.1.1都一样有这个问题

**Comment by DuForGit** [comment]
使用spring-cloud-alibaba-dependencies2025.1.0.0搭建微服务项目，也出现这个问题，运行栈如下：
另外：com.alibaba.nacos.common.remote.client.grpc.GrpcClient的check方法中使用到一个GrpcConstants的类，也是没有的，我看没有import信息，应该也是与GrpcClient同个包下的吧

java.lang.ClassNotFoundException: com.alibaba.nacos.shaded.io.grpc.census.InternalCensusTracingAccessor
at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[na:na]
at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[na:na]
at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[na:na]
at java.base/java.lang.Class.forName0(Native Method) ~[na:na]
at java.base/java.lang.Class.forName(Class.java:423) ~[na:na]
at java.base/java.lang.Class.forName(Class.java:414) ~[na:na]
at com.alibaba.nacos.shaded.io.grpc.internal.ManagedChannelImplBuilder.getEffectiveInterceptors(ManagedChannelImplBuilder.java:786) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.nacos.shaded.io.grpc.internal.ManagedChannelImplBuilder.build(ManagedChannelImplBuilder.java:731) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.nacos.shaded.io.grpc.ForwardingChannelBuilder2.build(ForwardingChannelBuilder2.java:278) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.createNewManagedChannel(GrpcClient.java:209) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:343) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.nacos.common.remote.client.RpcClient.start(RpcClient.java:350) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.start(NamingGrpcClientProxy.java:133) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.(NamingGrpcClientProxy.java:123) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.(NamingClientProxyDelegate.java:83) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.nacos.client.naming.NacosNamingService.init(NacosNamingService.java:130) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.nacos.client.naming.NacosNamingService.(NacosNamingService.java:108) ~[nacos-client-3.1.1.jar:na]
at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[na:na]
at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[na:na]
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[na:na]
at com.alibaba.nacos.api.naming.NamingFactory.createNamingService(NamingFactory.java:59) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.nacos.api.NacosFactory.createNamingService(NacosFactory.java:79) ~[nacos-client-3.1.1.jar:na]
at com.alibaba.cloud.nacos.NacosServiceManager.createNewNamingService(NacosServiceManager.java:99) ~[spring-cloud-starter-alibaba-nacos-discovery-2025.1.0.0.jar:2025.1.0.0]
at com.alibaba.cloud.nacos.NacosServiceManager.buildNamingService(NacosServiceManager.java:90) ~[spring-cloud-starter-alibaba-nacos-discovery-2025.1.0.0.jar:2025.1.0.0]
at com.alibaba.cloud.nacos.NacosServiceManager.getNamingService(NacosServiceManager.java:46) ~[spring-cloud-starter-alibaba-nacos-discovery-2025.1.0.0.jar:2025.1.0.0]
at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.namingService(NacosServiceRegistry.java:183) ~[spring-cloud-starter-alibaba-nacos-discovery-2025.1.0.0.jar:2025.1.0.0]
at com.alibaba.cloud.nacos.registry.NacosServiceRegistry.register(NacosServiceRegistry.java:67) ~[spring-cloud-starter-alibaba-nacos-discovery-2025.1.0.0.jar:2025.1.0.0]
at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.register(AbstractAutoServiceRegistration.java:263) ~[spring-cloud-commons-5.0.1.jar:5.0.1]
at com.alibaba.cloud.nacos.registry.NacosAutoServiceRegistration.register(NacosAutoServiceRegistration.java:80) ~[spring-cloud-starter-alibaba-nacos-discovery-2025.1.0.0.jar:2025.1.0.0]
at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.start(AbstractAutoServiceRegistration.java:155) ~[spring-cloud-commons-5.0.1.jar:5.0.1]
at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:124) ~[spring-cloud-commons-5.0.1.jar:5.0.1]
at org.springframework.cloud.client.serviceregistry.AbstractAutoServiceRegistration.onApplicationEvent(AbstractAutoServiceRegistration.java:48) ~[spring-cloud-commons-5.0.1.jar:5.0.1]
at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:180) ~[spring-context-7.0.3.jar:7.0.3]
at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:173) ~[spring-context-7.0.3.jar:7.0.3]
at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:151) ~[spring-context-7.0.3.jar:7.0.3]
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:447) ~[spring-context-7.0.3.jar:7.0.3]
at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:380) ~[spring-context-7.0.3.jar:7.0.3]
at org.springframework.boot.web.server.servlet.context.WebServerStartStopLifecycle.start(WebServerStartStopLifecycle.java:47) ~[spring-boot-web-server-4.0.2.jar:4.0.2]
at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:420) ~[spring-context-7.0.3.jar:7.0.3]
at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:409) ~[spring-context-7.0.3.jar:7.0.3]
at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:613) ~[spring-context-7.0.3.jar:7.0.3]
at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:379) ~[spring-context-7.0.3.jar:7.0.3]
at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:306) ~[spring-context-7.0.3.jar:7.0.3]
at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:1012) ~[spring-context-7.0.3.jar:7.0.3]
at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:623) ~[spring-context-7.0.3.jar:7.0.3]
at org.springframework.boot.web.server.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:143) ~[spring-boot-web-server-4.0.2.jar:4.0.2]
at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:756) ~[spring-boot-4.0.2.jar:4.0.2]
at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:445) ~[spring-boot-4.0.2.jar:4.0.2]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:321) ~[spring-boot-4.0.2.jar:4.0.2]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1365) ~[spring-boot-4.0.2.jar:4.0.2]
at org.springframework.boot.SpringApplication.run(SpringApplication.java:1354) ~[spring-boot-4.0.2.jar:4.0.2]
