### ISSUE TITLE
Problem "Unable to find instance for XXX" occurs when using spring-cloud-gateway & nacos

### ISSUE THREAD

**Issue by bearwind** [alibaba/nacos#988]
## Issue Description

Type: *bug report*

### Describe what happened
When integrating spring-cloud-gateway with nacos, we use nacos as service discovery & config center, define the gateway routes  for load-balance. 
 **Everthing goes well after starting apps and requesting api, but the exception "Unable to find instance for daoji-tourism-prod" occurs unschedully and unexpectedly, we cannot request api and the gateway server returns the message:** 
```
{
  "timestamp": "2019-04-01T02:38:56.034+0000",
  "path": "/tourism/login",
  "status": 500,
  "error": "Internal Server Error",
  "message": "Unable to find instance for daoji-tourism-prod"
}
```
**But after a few seconds, everything comes to be normal and the problem will occur repeatedly. 
The exception details are shown as below:**
```
2019-04-01 09:15:47.342 [reactor-http-server-epoll-7] ERROR org.springframework.boot.autoconfigure.web.reactive.error.DefaultErrorWebExceptionHandler[218]: Failed to handle request [POST http://localhost:8888/tourism/login]
org.springframework.cloud.gateway.support.NotFoundException: Unable to find instance for daoji-tourism-prod
	at org.springframework.cloud.gateway.filter.LoadBalancerClientFilter.filter(LoadBalancerClientFilter.java:72)
	at org.springframework.cloud.gateway.handler.FilteringWebHandler$GatewayFilterAdapter.filter(FilteringWebHandler.java:135)
	at org.springframework.cloud.gateway.filter.OrderedGatewayFilter.filter(OrderedGatewayFilter.java:44)
	at org.springframework.cloud.gateway.handler.FilteringWebHandler$DefaultGatewayFilterChain.lambda$filter$0(FilteringWebHandler.java:117)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:45)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3088)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3088)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3088)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3088)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:271)
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:803)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.core.publisher.FluxSwitchIfEmpty$SwitchIfEmptySubscriber.onNext(FluxSwitchIfEmpty.java:67)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1083)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:144)
	at reactor.core.publisher.FluxMap$MapSubscriber.onNext(FluxMap.java:108)
	at reactor.core.publisher.MonoNext$NextSubscriber.onNext(MonoNext.java:76)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.innerNext(FluxConcatMap.java:271)
	at reactor.core.publisher.FluxConcatMap$ConcatMapInner.onNext(FluxConcatMap.java:803)
	at reactor.core.publisher.FluxOnErrorResume$ResumeSubscriber.onNext(FluxOnErrorResume.java:73)
	at reactor.core.publisher.FluxPeek$PeekSubscriber.onNext(FluxPeek.java:185)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1083)
	at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.onNext(MonoFilterWhen.java:138)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1640)
	at reactor.core.publisher.MonoFilterWhen$MonoFilterWhenMain.onSubscribe(MonoFilterWhen.java:103)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.MonoFilterWhen.subscribe(MonoFilterWhen.java:56)
	at reactor.core.publisher.MonoPeek.subscribe(MonoPeek.java:71)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3088)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:418)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onNext(FluxConcatMap.java:241)
	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:114)
	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onNext(FluxDematerialize.java:42)
	at reactor.core.publisher.FluxIterable$IterableSubscription.slowPath(FluxIterable.java:244)
	at reactor.core.publisher.FluxIterable$IterableSubscription.request(FluxIterable.java:202)
	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.request(FluxDematerialize.java:157)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:227)
	at reactor.core.publisher.FluxDematerialize$DematerializeSubscriber.onSubscribe(FluxDematerialize.java:88)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:140)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:64)
	at reactor.core.publisher.FluxDematerialize.subscribe(FluxDematerialize.java:39)
	at reactor.core.publisher.FluxDefer.subscribe(FluxDefer.java:55)
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:121)
	at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40)
	at reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	at reactor.core.publisher.MonoMap.subscribe(MonoMap.java:55)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3088)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.drain(FluxConcatMap.java:418)
	at reactor.core.publisher.FluxConcatMap$ConcatMapImmediate.onSubscribe(FluxConcatMap.java:210)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:140)
	at reactor.core.publisher.FluxIterable.subscribe(FluxIterable.java:64)
	at reactor.core.publisher.FluxConcatMap.subscribe(FluxConcatMap.java:121)
	at reactor.core.publisher.MonoNext.subscribe(MonoNext.java:40)
	at reactor.core.publisher.MonoSwitchIfEmpty.subscribe(MonoSwitchIfEmpty.java:44)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoFlatMap$FlatMapMain.onNext(MonoFlatMap.java:150)
	at reactor.core.publisher.Operators$MonoSubscriber.complete(Operators.java:1083)
	at reactor.core.publisher.MonoZip$ZipCoordinator.signal(MonoZip.java:247)
	at reactor.core.publisher.MonoZip$ZipInner.onNext(MonoZip.java:329)
	at reactor.core.publisher.Operators$ScalarSubscription.request(Operators.java:1640)
	at reactor.core.publisher.MonoZip$ZipInner.onSubscribe(MonoZip.java:318)
	at reactor.core.publisher.MonoJust.subscribe(MonoJust.java:54)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3088)
	at reactor.core.publisher.MonoZip.subscribe(MonoZip.java:128)
	at reactor.core.publisher.MonoFlatMap.subscribe(MonoFlatMap.java:60)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:74)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoDefer.subscribe(MonoDefer.java:53)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.MonoOnErrorResume.subscribe(MonoOnErrorResume.java:44)
	at reactor.core.publisher.Mono.subscribe(Mono.java:3088)
	at reactor.core.publisher.MonoIgnoreThen$ThenIgnoreMain.drain(MonoIgnoreThen.java:172)
	at reactor.core.publisher.MonoIgnoreThen.subscribe(MonoIgnoreThen.java:56)
	at reactor.core.publisher.MonoPeekFuseable.subscribe(MonoPeekFuseable.java:70)
	at reactor.core.publisher.MonoPeekTerminal.subscribe(MonoPeekTerminal.java:61)
	at reactor.ipc.netty.channel.ChannelOperations.applyHandler(ChannelOperations.java:381)
	at reactor.ipc.netty.http.server.HttpServerOperations.onHandlerStart(HttpServerOperations.java:399)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:163)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:404)
	at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:315)
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:884)
	at java.lang.Thread.run(Thread.java:745)

```

### Describe what you expected to happen
We expecte that every time we can request the api through the gateway successfully.

### How to reproduce it (as minimally and precisely as possible)

1. 3 servers for nacos cluster
2. gateway app config as below:
```
spring:
  application:
    name: daoji-gateway-prod
  cloud:
    nacos:
      discovery:
        server-addr: warwick01:8848,warwick02:8848,warwick03:8848
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: daoji-tourism-auth-route
          uri: lb://daoji-tourism-prod
          predicates:
            - Path=/tourism/*/*/**
          filters: 
            - Authorization=true
        - id: daoji-tourism-login-route
          uri: lb://daoji-tourism-prod
          predicates:
            - Path=/tourism/login
          filters: 
            - LoginIssueToken=true
        - id: daoji-tourism-privilege-route
          uri: lb://daoji-tourism
          predicates: 
            - Path=/tourism/*
server:
  port: 8888
```
3. provider app config as below:
```
spring:
  application:
    name: daoji-tourism-prod
  cloud:
    nacos:
      discovery:
        server-addr: warwick01:8848,warwick02:8848,warwick03:8848
server:
  port: 9504
  servlet: 
    context-path: /tourism
```

### Tell us your environment
+ Ubuntu 16.04 LTS
+ JRE1.8
+ Nacos version: 0.8.0, cluster mode, 3 servers.
+ Spring-cloud-gateway version: 2.0.2.RELEASE

> Thx for helping us.

**Comment by bearwind** [comment]
Anybody here?

**Comment by nkorange** [comment]
@bearwind Not sure if this is a Nacos error, I don't see any message of Nacos in the exception stack.

Look for error in {user.home}/log/nacos/naming.log please.

**Comment by bearwind** [comment]
> @bearwind Not sure if this is a Nacos error, I don't see any message of Nacos in the exception stack.
> 
> Look for error in {user.home}/log/nacos/naming.log please.

Thx for your reply.
I have checked naming-server.log, the log outputs the exeption as below all the time whether requesting provider's api  succesfully or not:
```
2019-04-02 17:45:04,889 INFO [HEALTH-CHECK] health check is true

2019-04-02 17:45:33,575 INFO [STATUS-SYNCHRONIZE] sync dom status from: 192.168.88.86:8848, dom: public##daoji-tourism-prod

2019-04-02 17:45:33,577 WARN NamingProxy

java.io.IOException: failed to req API:http://192.168.88.86:8848/nacos/v1/ns/api/ip4Dom2. code:404 msg: dom: public##daoji-tourism-prod not found.
	at com.alibaba.nacos.naming.misc.NamingProxy.reqAPI(NamingProxy.java:214)
	at com.alibaba.nacos.naming.misc.DomainStatusSynchronizer.get(DomainStatusSynchronizer.java:82)
	at com.alibaba.nacos.naming.core.DomainsManager.updatedDom2(DomainsManager.java:184)
	at com.alibaba.nacos.naming.core.DomainsManager$DomUpdater.run(DomainsManager.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-02 17:45:33,577 WARN [DOMAIN-UPDATER] Exception while update dom: daoji-tourism-prod from 192.168.88.86:8848, error: {}

java.lang.NullPointerException: null
	at com.alibaba.nacos.naming.core.DomainsManager.updatedDom2(DomainsManager.java:185)
	at com.alibaba.nacos.naming.core.DomainsManager$DomUpdater.run(DomainsManager.java:175)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
2019-04-02 17:45:38,575 INFO [STATUS-SYNCHRONIZE] sync dom status from: 192.168.88.86:8848, dom: public##daoji-tourism-prod
```

I don't know if it's the reason for the problem.
Anything else I need to provide for helping us?

**Comment by nkorange** [comment]
Update nacos server to 1.0.0-RC2 and try again.

**Comment by sc750531323** [comment]
i meet the same problem. it seems that  the ribbonLoadbalancer in springcloud gateway can not find the service instance from servicename

**Comment by suxiaohei** [comment]
maybe you should restart or upgrade your eruake server。
