### ISSUE TITLE
2.1.2个别服务运行一段时间够就挂掉，端口是通的

### ISSUE THREAD

**Issue by dzh6699** [alibaba/nacos#9913]
nacos版本  2.1.2   
spring  cloud  alibaba 版本 2.2.9.RELEASE
spring boot 版本  2.3.12.RELEASE
spring cloud版本 Hoxton.SR12

同一台服务器，其他服务都正常，只有这个服务运行30分钟到一个小时，就会挂掉，最后内存溢出。
我们配置的nacos端口是 18808   grpc端口是 19808

```
2023-02-07 20:44:19.289 ERROR [TID: N/A] [com.alibaba.nacos.client.remote.worker] c.a.n.c.r.client.grpc.GrpcClient  Server check fail, please check server test.XXX.XXX.com ,port 19808 is available , error ={}
java.util.concurrent.TimeoutException: Waited 3000 milliseconds (plus 904 milliseconds, 557493 nanoseconds delay) for com.alibaba.nacos.shaded.io.grpc.stub.ClientCalls$GrpcFuture@381e0985[status=PENDING, info=[GrpcFuture{clientCall={delegate={delegate=ClientCallImpl{method=MethodDescriptor{fullMethodName=Request/request, type=UNARY, idempotent=false, safe=false, sampledToLocalTracing=true, requestMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@36ff2cc0, responseMarshaller=com.alibaba.nacos.shaded.io.grpc.protobuf.lite.ProtoLiteUtils$MessageMarshaller@4662d697, schemaDescriptor=com.alibaba.nacos.api.grpc.auto.RequestGrpc$RequestMethodDescriptorSupplier@2d43fb41}}}}}]]
	at com.alibaba.nacos.shaded.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:508)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.serverCheck(GrpcClient.java:192)
	at com.alibaba.nacos.common.remote.client.grpc.GrpcClient.connectToServer(GrpcClient.java:302)
	at com.alibaba.nacos.common.remote.client.RpcClient.reconnect(RpcClient.java:521)
	at com.alibaba.nacos.common.remote.client.RpcClient.lambda$start$2(RpcClient.java:369)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


2023-02-07 20:44:27.804 WARN  [TID: N/A] [com.alibaba.nacos.client.naming.updater.0] com.alibaba.nacos.client.naming  [NA] failed to update serviceName: sit@@service-XX-XX（这里的XX不是当前服务）
com.alibaba.nacos.api.exception.NacosException: Request nacos server failed: 
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:288)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.queryInstancesOfService(NamingGrpcClientProxy.java:168)
	at com.alibaba.nacos.client.naming.remote.NamingClientProxyDelegate.queryInstancesOfService(NamingClientProxyDelegate.java:110)
	at com.alibaba.nacos.client.naming.core.ServiceInfoUpdateService$UpdateTask.run(ServiceInfoUpdateService.java:185)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.alibaba.nacos.api.exception.NacosException: Client not connected, current status:UNHEALTHY
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:651)
	at com.alibaba.nacos.common.remote.client.RpcClient.request(RpcClient.java:631)
	at com.alibaba.nacos.client.naming.remote.gprc.NamingGrpcClientProxy.requestToServer(NamingGrpcClientProxy.java:278)
	... 10 common frames omitted

```

```
Exception in thread "http-nio-8470-Acceptor" Exception in thread "ForkJoinPool.commonPool-worker-0" java.lang.OutOfMemoryError: Java heap space
	at java.util.concurrent.ForkJoinPool$WorkQueue.growArray(ForkJoinPool.java:886)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1687)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
java.lang.OutOfMemoryError: Java heap space
	at java.nio.HeapByteBuffer.<init>(HeapByteBuffer.java:57)
	at java.nio.ByteBuffer.allocate(ByteBuffer.java:335)
	at org.apache.tomcat.util.net.SocketBufferHandler.<init>(SocketBufferHandler.java:58)
	at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:513)
	at org.apache.tomcat.util.net.NioEndpoint.setSocketOptions(NioEndpoint.java:80)
	at org.apache.tomcat.util.net.Acceptor.run(Acceptor.java:126)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "RibbonApacheHttpClientConfiguration.connectionManagerTimer" java.lang.OutOfMemoryError: Java heap space
Exception in thread "nacos-grpc-client-executor-test.ncs.scm.linshimuye.com-1487" java.lang.OutOfMemoryError: Java heap space

```

**Comment by dzh6699** [comment]
增加内存问题解决
