### ISSUE TITLE
nacos1.4.1 start error：NullPointerException, at com.alibaba.nacos.sys.env.EnvUtil.getProperty(EnvUtil.java:103) ~[classes/:na]

### ISSUE THREAD

**Issue by feixiangdeyuer** [alibaba/nacos#9977]
when I start nacos 1.4.1 as source code in local,it throws these errors:
java.lang.NullPointerException: null
	at com.alibaba.nacos.sys.env.EnvUtil.getProperty(EnvUtil.java:103) ~[classes/:na]
	at com.alibaba.nacos.config.server.utils.PropertyUtil.loadSetting(PropertyUtil.java:254) ~[classes/:na]
	at com.alibaba.nacos.config.server.utils.PropertyUtil.initialize(PropertyUtil.java:329) ~[classes/:na]
	at org.springframework.boot.SpringApplication.applyInitializers(SpringApplication.java:623) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
	at org.springframework.boot.SpringApplication.prepareContext(SpringApplication.java:367) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:311) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1204) [spring-boot-2.1.17.RELEASE.jar:2.1.17.RELEASE]
	at com.alibaba.nacos.Nacos.main(Nacos.java:35) [classes/:na]

**Comment by KomachiSion** [comment]
It should be your local env problem. Maybe no configuration properties file.

**Comment by KomachiSion** [comment]
No more response from author, I think this is a env problem.
